### ISSUE TITLE
Dune on Windows: naming and selection of executable files (clarification)

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10039]
Dear Coq Team,

I am experimenting with the dune build on Windows. I find the naming and selection of installed files a bit unexpected:

```
./_build/install/default/bin/coq-tex.exe
./_build/install/default/bin/coqc.byte.exe
./_build/install/default/bin/coqc.exe
./_build/install/default/bin/coqchk.exe
./_build/install/default/bin/coqdep.exe
./_build/install/default/bin/coqdoc.exe
./_build/install/default/bin/coqide.exe
./_build/install/default/bin/coqidetop.opt.exe
./_build/install/default/bin/coqpp.exe
./_build/install/default/bin/coqproofworker.opt.exe
./_build/install/default/bin/coqqueryworker.opt.exe
./_build/install/default/bin/coqtacticworker.opt.exe
./_build/install/default/bin/coqtop.byte.exe
./_build/install/default/bin/coqtop.exe
./_build/install/default/bin/coqtop.opt.exe
./_build/install/default/bin/coqwc.exe
./_build/install/default/bin/coqworkmgr.exe
./_build/install/default/bin/coq_dune.exe
./_build/install/default/bin/coq_makefile.exe
./_build/install/default/bin/csdpcert.exe
./_build/install/default/bin/fake_ide.exe
./_build/install/default/bin/votour.exe
```

Some executables (coqtop) have a byte, an opt and a normal version. The opt and normal version are identical. Others have just an opt version, yet others just a normal version and yet others a normal and a byte version. Can someone please explain the rationale behind this?

Even more unexpected is the naming of .bc files in the build folder:
```
./_build/default/checker/coqchk.bc
./_build/default/ide/coqide_main.bc
./_build/default/ide/idetop.bc
./_build/default/topbin/coqc_bin.bc
./_build/default/topbin/coqtop_byte_bin.bc
```
Why is there a separate byte_bin .ml file for coqtop `./_build/default/topbin/coqtop_byte_bin.ml`? Does this mean that when I byte code debug coqtop I debug different source code than when I execute native code coqtop? What is the rationale behind that? How is this .ml file generated (it does not appear in git)?

**Comment by Zimmi48** [comment]
I don't think this is really Windows specific, in the sense that Dune will build the same thing everywhere.

> Why is there a separate byte_bin .ml file for coqtop `./_build/default/topbin/coqtop_byte_bin.ml`? Does this mean that when I byte code debug coqtop I debug different source code than when I execute native code coqtop? What is the rationale behind that? How is this .ml file generated (it does not appear in git)?

It is not generated: see `topbin/coqtop_bin.ml` and `topbin/coqtop_byte_bin.ml`. The difference is the following:

```diff
11c11,29
< let drop_setup () = Mltop.remove ()
---
> let drop_setup () =
>   begin try
>     (* Enable rectypes in the toplevel if it has the directive #rectypes *)
>     begin match Hashtbl.find Toploop.directive_table "rectypes" with
>       | Toploop.Directive_none f -> f ()
>       | _ -> ()
>     end
>     with
>     | Not_found -> ()
>   end;
>   let ppf = Format.std_formatter in
>   Mltop.(set_top
>            { load_obj = (fun f -> if not (Topdirs.load_file ppf f)
>                           then CErrors.user_err Pp.(str ("Could not load plugin "^f))
>                         );
>              use_file = Topdirs.dir_use ppf;
>              add_dir  = Topdirs.dir_directory;
>              ml_loop  = (fun () -> Toploop.loop ppf);
>            })
```

This is basically enabling the byte version with the `Drop.` functionality.

**Comment by Zimmi48** [comment]
The only executable for which we provide a byte and a native version are `coqtop` and `coqc`. It was only `coqtop` before #9981. I agree that it is confusing and useless to have two copies of the native `coqtop` version. The only other executable files with an `.opt` extension are some internal ones defined in `topbin/`. It was @ejgallego's choice to give them this extension (see `topbin/dune`), which marks them more as internal (I guess) but maybe they should not have it.

Finally, I'm really surprised to see that `fake_ide` is installed. Should it really be the case?

**Comment by MSoegtropIMC** [comment]
Thanks for the explanations!

IMHO indicating that something is internal by giving it an .opt.exe extension is mildly confusing. People might speculate why other executables are not "optimized". I would vote for having .exe and .byte.exe as extensions.

That the executables have different basenames before and after installation is a bit of an extra burden for people starting to use the debugger, but I guess the group of people suffering from this is fairly restricted, so it is ok.

If a byte coqe version of coqtop is installed, I think we should also have a byte code version of coqidetop. The reason is that plugins are different and people developing plugins might prefer having a byte code version around. But then it should also be also available for people using CoqIDE. Or is there a different reason for having these than plugin compatibility?

**Comment by Zimmi48** [comment]
>Or is there a different reason for having these than plugin compatibility?

The main reason of having `coqtop.byte` is the `Drop.` feature IINM.
