### ISSUE TITLE
Error: Anomaly "Evar ?X184 was not declared." Please report at http://coq.inria.fr/bugs/.  on non-evar-normalized proof term with abstract

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10044]
#### Description of the problem
```coq
Goal Type.
  let v := open_constr:(_) in
  let __ := constr:(eq_refl : Set = v) in
  abstract exact v.
  (* Error: Anomaly "Evar ?X3 was not declared." Please report at http://coq.inria.fr/bugs/. *)
```

Note that adding `let v := (eval cbv delta [id] in v) in` before the last line fixes the anomaly, by evar-normalizing the term.

See also #9037.  Note that unlike #9037, there are no remaining evars here.

#### Coq Version

8.9.0

**Comment by SkySkimmer** [comment]
Fixed
