### ISSUE TITLE
[enhancement] Numeral Notations without the ltac plugin

### ISSUE THREAD

**Issue by jashug** [coq/coq#10054]
#### Description of the problem

In `coqtop -noinit`:

```coq
Fail Declare ML Module "numeral_notation_plugin".
(*
[Loading ML file numeral_notation_plugin.cmxs ... failed]
The command has indeed failed with message:
while loading
/home/jasperh/coq-master/plugins/syntax/numeral_notation_plugin.cmxs:
error loading shared library: /home/jasperh/coq-master/plugins/syntax/numeral_notation_plugin.cmxs: undefined symbol: camlLtac_plugin__Tacentries__argument_extend_12220
*)
Declare ML Module "ltac_plugin".
Declare ML Module "numeral_notation_plugin".
(* success *)
```

I would find it useful if it were possible to use numeral notations without loading the ltac plugin.

#### Coq Version

Coq master 75c5264aa687480c66a6765d64246b5ebd2c0d54

**Comment by ppedrot** [comment]
It's actually pretty easy: for some reason, the mlg file defines a generic argument, when a vernac generic argument would have sufficed. The latter doesn't call the Ltac plugin. I'll write a patch.
