### ISSUE TITLE
CoqIde no longer recognizes the -debug command line option

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10066]
#### Coq Version 8.9

CoqIde no longer recognizes the `-debug` option, which creates a debug file with various messages as well as printing the file's pathname at startup.  8.9 doesn't do either of these.  It works in 8.8.2. 
 Perhaps this was lost when the argument-handling code was refactored?

**Comment by ppedrot** [comment]
I cannot reproduce on my 8.9 installation (nor on master). What is your exact setting? I launched CoqIDE via the CLI with
```
coqide -debug
```

**Comment by jfehrle** [comment]
My confusion.  I was launching from the windows toolbar.  There are two spots in the setup dialog that look like plausible places to add a command line option.  My 8.8.2 has `-debug` in both place but I was looking at the wrong box.
