### ISSUE TITLE
Sphinx does not like Coq comments

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#10070]
Putting comments in the `.. coqtop::` directive seems to produce a timeout error, e.g.

```
.. coqtop::
   Check True.
   (* foo *)
```

**Comment by Zimmi48** [comment]
More generally, I think this timeout error arises if you are missing a dot at the end.

**Comment by jfehrle** [comment]
I fixed comments in Sphinx/coqtop about 2 years ago IIRC.
