### ISSUE TITLE
wish: local notations declared on inductives with where

### ISSUE THREAD

**Issue by jashug** [coq/coq#10074]
#### Description of the problem

In a certain style, it is best practice to put all notations in a module, so that they can be imported or not separately from the definitions and inductives (since names can be shadowed, but notations and parsing levels cannot). Since notations defined with `where` in a Record are local to that record, used with `Local Reserved Notation` they can be redeclared or not in a following module and leave no trace. With `Inductive ... where ...` however, the notation is always non-local, and so sticks around in the same scope as the inductive and its constructors. (Thus even if you put the inductive with notation in the notation module, then define aliases outside, when you import the notation module you also get the unqualified constructor names.)

It would be nice to have a way to make the notations declared with `Inductive ... where ...` local.

(Better control over importing notations or not would make this wish irrelevant)

#### Coq Version

Coq 8.9

**Comment by SkySkimmer** [comment]
You can workaround by declaring the inductive in a section.
~~~coq

Section foo.
Inductive foo (A B:Set) := tt where "A + B" := (foo A B).
End foo.
Fail Check nat + nat.
~~~

**Comment by jashug** [comment]
Oh, I hadn't thought of that. Thank you!

**Comment by SkySkimmer** [comment]
It would still make sense to unify the behaviour of `Record where` and `Inductive where` imo.
