### ISSUE TITLE
Hint Mode + does not work at all

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10072]
#### Description of the problem

This code should not loop, but it does:
```coq
Class Foo (T : Type) := foo : False.
Hint Mode Foo +.
Axiom F : Type -> Type.
Instance bad {T} {FT : Foo T} : Foo (F T) := foo.
Goal True.
  timeout 1 try let v := constr:(_ : Foo _) in idtac. (* should succeed, but does not *)
```

cc @mattam82 

#### Coq Version

8.9.0

**Comment by Zimmi48** [comment]
Try `Hint Mode Foo + : typeclass_instances.`

I'll requalify this as a request for enhancement of the documentation.
