### ISSUE TITLE
Incompatibility with ssreflect's ampersand syntactic sugar for inductives

### ISSUE THREAD

**Issue by erikmd** [coq/coq#10088]
- **Kind:** bug
- **Coq version:** 8.7.2
- **Minimal working example:**
    ```coq
    Require Import ssreflect.
    
    Inductive nat_list :=
      Nil
    | Cons of nat & nat_list.
    
    Print nat_list.
    (* Inductive nat_list : Set :=
           Nil : nat_list | Cons : nat -> nat_list -> nat_list *)

    From Ltac2 Require Import Ltac2.
    (*ok*)

    Inductive nat_list' :=
      Nil'
    | Cons' of nat & nat_list'.
    (*↓*)
    (* Toplevel input, characters 56-71:
       > Inductive nat_list' :=   Nil' | Cons' of nat & nat_list'.
       >                                          ^^^^^^^^^^^^^^^
       Error: Illegal application (Non-functional construction): 
       The expression "nat" of type "Set"
       cannot be applied to the term
        "nat_list'" : "Type" *)
    ```
- **Additional info:** if I process the file up to the `(*ok*)` comment (using ProofGeneral), backtrack to the top of the file, and process again the first inductive, then I get:
    ```coq
    (* Error: Anomaly "Missing hardwired primitive Ltac2.Control.refine"
       Please report at http://coq.inria.fr/bugs/. *)
    ```

**Comment by vbgl** [comment]
Pierre-Marie, by any chance, do you have a constructive proof of you “hopefully”?

In Ltac2, the ampersand symbol `&` is used in introduction patterns and for references. I think this last kind of use is the issue here. Should a different symbol be used to (un)quote references? \^/~%#`…

**Comment by ppedrot** [comment]
My hope is that this can be solved with a complex enough lookahead, but unluckily this is not constructive in any way. I'll have a look though.

**Comment by Zimmi48** [comment]
The anomaly when backtracking is probably a different issue though.

**Comment by ggonthier** [comment]
This shouldn't be only an SSreflect parsing problem - the SSreflect syntax is consistent with the `sigT` / `sig2` / `sigT2` / `exist2` syntax, using `&` as a terminator (that is, _constr1_ `&` _constr2_ cannot be parsed as an _operconstr_). If it doesn't want to break all of these (plus countless others in user developments) Ltac2 should either use a different character, or at least parse `&` _ref_ at level 10 or higher.
