### ISSUE TITLE
Missing parentheses when printing some types with Ltac2

### ISSUE THREAD

**Issue by erikmd** [coq/coq#10089]
Hi @ppedrot, I'm currently porting some tactics from Ltac1 to Ltac2 and it is a very pleasant experience!

During this work, I've noticed some parentheses are missing when printing types combining products and parameterized types, so the output is ambiguous… This seems to be related to ppedrot/ltac2#4, and below is a minimal working example:

```coq
From Ltac2 Require Import Ltac2.

Ltac2 foo1 a b := (a, [b]).

Ltac2 foo2_bug a b := [(a, b)].

Print Ltac2 foo1.
(* foo1 : 'a -> 'b -> 'a * 'b list *)
(* foo1 := fun a b => a, [b] *)

Print Ltac2 foo2_bug.
(* foo2_bug : 'a -> 'b -> 'a * 'b list *) (* should be 'a -> 'b -> ('a * 'b) list *)
(* foo2_bug := fun a b => [a, b] *)
```

**Comment by ppedrot** [comment]
This particular bug was fixed at some point, let's close it.
