### ISSUE TITLE
Message.printf

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10108]
The verbosity of `Message.of_*` and ` Message.concat ` is the third most annoying source of verbosity.  I'd like to see `Message.printf` with the various format specifiers.  (I guess there's, what?, `%a` for custom, `%s ` for string, `%d` for int, `%x`(?) for int as hex, and maybe also `%c` for constr, `%i ` for indent, `%m` for message, `%b` for Boolean (or is this used for int as binary?)?)  It might be nice to be able to declare / add format specifiers in user-space, but even one that just handled string, constr, and custom would be very welcome.

**Comment by jfehrle** [comment]
IIUC some useful simpler steps would be:
- ability to print any type of variable (e.g. "intropattern")
- ability to print with simpler syntax (e.g. `print x` vs `Message.print (Message.of_ident x)`
- ability to print multiple values on a single line.

**Comment by ppedrot** [comment]
The solution is fairly easy: export a scope that macro-expands to a type-safe format construction as in OCaml. We don't need to deconstruct these format instructions in Ltac2 so no need for GADTs, they can be given as abstract definitions with phantom types.

**Comment by jfehrle** [comment]
Ah, that would address the printf with a format string case?  What format string do you use for something of type `intropattern`?

Supporting a print without a format string would often be simpler and good enough for users provided that Ltac2 knows the type of each item.  Jason's suggestion of supporting `%a` seems like it would require having the appropriate formatter exported from OCaml code.
