### ISSUE TITLE
Please add deep pattern matching support

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10109]
I'd like to be able to match multiple things at once (it's fine if I have to wrap the discriminee in a tuple) and match deeply into the structure of, e.g., tuple components and record fields.  This is one of the two most annoying sources of verbosity

**Comment by JasonGross** [comment]
@ppedrot Is the primary issue here getting the syntax to work, or getting the semantics to work, or getting efficient semantics (a la [Compiling Pattern Matching to Good Decision Trees](http://moscova.inria.fr/~maranget/papers/ml05e-maranget.pdf)), or something else?

**Comment by ppedrot** [comment]
None of that (although you might call that semantics), the hard thing is to properly type-check them. The interpreter uses a case representation similar to the Coq kernel, so we also need to perform the case expansion.

There is nothing involved conceptually, it is a classical problem of ML, but it's a tedious one. I don't think there is a readily available implementation I can just copy and paste.

**Comment by JasonGross** [comment]
Interesting.  Do you need to type-check before doing case-explosion?  It seems like as long as you have access to unusable/fresh names, you could perform a case-explosion without knowing any types, only knowing which things in the patterns are constructors and which are names.

**Comment by rlepigre** [comment]
Can this be closed?
