### ISSUE TITLE
Notation for matching Booleans

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10110]
It should be possible to use Ltac2 notation to add `if ... then ` and `if ... then ... else ` for bool matching, and such notations should be bound in the Ltac2 std lib.  This is one of the two most annoying sources of verbosity.

**Comment by JasonGross** [comment]
Is it possible to do this in user-space with `Ltac2 Notation`, or does it have to be hard-coded?  Note that the branches should be automatically thunked if it's done in user space.

cc @ppedrot ?

**Comment by ppedrot** [comment]
Probably doable user-land, but you'd have to be careful for associativity. It'd be more robust to have such a basic syntactic sugar directly in the AST. Doing so would also allow to implement the if-then no-else case as done in OCaml with an implicit unit value in the else branch.
