### ISSUE TITLE
It should be possible to print a backtrace from Control.case / Control.plus

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10112]
I'd like some sort of object to show up in the error case that I can pass to a backtrace printer to get a message representing the backtrace associated with the error, and I'd like a version of `Control.throw` / `Control.zero` that accepts a backtrace argument as well as an exception, and considers the current location as re-raising the error / as an additional frame in the backtrace.

**Comment by SkySkimmer** [comment]
Can you be more specific? eg some pseudocode of what you want to do.

For instance are you talking about the ocaml backtrace or the ltac2 backtrace?

**Comment by rlepigre** [comment]
We've been meaning to upstream a fix for that for a while, so @janno or I will submit a PR when I have a moment in the next few days.

**Comment by SkySkimmer** [comment]
ping @rlepigre @Janno
