### ISSUE TITLE
Syntax for Ltac2 record update

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10117]
I'd like to be able to write `{ foo with field := val }` like in OCaml, for "updating" Ltac2 records (getting a new copy with a field value replaced).  This allows me to have option records and not need to update places where they are modified when I add an option.

**Comment by Blaisorblade** [comment]
(Record update syntax would maybe also be beneficial in Coq, tho that should be a separate issue.)

**Comment by jfehrle** [comment]
I marked this as an enhancement since IIUC you can work around this.
