### ISSUE TITLE
Fix the list of chapters in "How to read this book" after Ltac2 addition.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#10127]
I will wait closer to the 8.11 release date to fix this because it might not be the only chapter that has been added, removed, or moved around.

**Comment by ppedrot** [comment]
@Zimmi48 ping

**Comment by Zimmi48** [comment]
Despite behind trivial, I'll postpone to 8.11.0. I guess this is acceptable.

**Comment by ppedrot** [comment]
@Zimmi48 from the discussion at the WG, should I understand that this bug is to be postponed?

**Comment by Zimmi48** [comment]
Oh no, this is so trivial to fix, I'll do it now.
