### ISSUE TITLE
SProp record in Type

### ISSUE THREAD

**Issue by andreaslyn** [coq/coq#10122]
#### Description of the problem
When defining a record in `Type` with just irrelevant fields, then the record ends up in `Prop`. For example:
```
Set Allow StrictProp.
Record B (A:SProp) : Type := b { unb : A }.
Check B. (* B : SProp -> Prop *)
```
It works as expected for records in `Prop` and `Set`. I am not sure why one would want a record, with just irrelevant fields, in `Type` rather than `Set` or `Prop`. However, it seems wrong to put the record in `Prop` implicitly.

#### Coq Version
8.10+alpha

**Comment by SkySkimmer** [comment]
This is not specific to SProp, `Type` has a special meaning when used as the sort of an inductive.

We should probably document this somewhere.
Changing it is a bigger question due to backward compat issues.
