### ISSUE TITLE
Ltac2 coqdoc-generated documentation is not built / installed.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#10139]
@ppedrot wants users to refer to this documentation frequently instead of crowding the manual because many things are defined there instead of being primitive. But at the current time, it is not installed: https://coq.github.io/doc/master/stdlib/. This is consistent with the name and URL of this documentation BTW (if we consider that stdlib is the name of everything under the `Coq` prefix). This needs some thinking IMO, and is not so urgent, as long as it is done in time for 8.11.

**Comment by Zimmi48** [comment]
Bump. 8.11 is getting much closer. I have no idea what is the right strategy for this. Should the Ltac2 documentation be installed under https://coq.github.io/doc/master/stdlib/ (in which case, there should be a clear separation between what is in the "Coq" namespace and what is out of it)? Should it be installed somewhere like https://coq.github.io/doc/master/ltac2 (at the price of more infrastructure changes, and harder discoverability)?

Note that this should be decided taking into account that in the future, we will probably have more stuff out of the Coq namespace, and thus the solution should be applicable several times. Also, it should be compatible with the objective of #10142.

cc @ppedrot @maximedenes @silene @cpitclaudel

**Comment by ppedrot** [comment]
What do we do with this bug for 8.11?

**Comment by ppedrot** [comment]
This doesn't seem to move the masses, and even though I am the Ltac2 dev, I have zero idea about both coqdoc *and* installation scripts. Out of emergency, I am postponing this.

**Comment by Zimmi48** [comment]
I feel this is too bad, but I have no time to look myself at this issue, so I guess postponing is the only solution unless someone else steps in quickly. However, let's postpone only to the next patch-level version if we can.

**Comment by ejgallego** [comment]
Note that a fix is already available in #11413 so I suggest you de-postpone this issue.

**Comment by ppedrot** [comment]
We don't build the official doc by default with dune, do we?

**Comment by ejgallego** [comment]
> We don't build the official doc by default with dune, do we?

Yes we do, but note that PR fixes both build systems.

**Comment by Zimmi48** [comment]
The title of the PR is misleading. It fixes both the Dune and the legacy build AFAICT.
