### ISSUE TITLE
Static grammars not being synchronous with backtracking, and its consequences in coqc bugs

### ISSUE THREAD

**Issue by herbelin** [coq/coq#10146]
### A coqc problem...

`coqc a.v b.v` fails when compiling `b.v` due to some `ltac_plugin` data being missing. Just take `a.v` empty and `b.v` to be `Ltac f := match goal with |- _ => idtac end.`. What seems missing is the declaration of `|-` as a keyword: if I add a dummy `Notation "@@ a |- b" := (a + b) (at level 0).` in `b.v` just for the purpose of forcing `|-` to be a keyword, it works again!

### ...which hides a `Declare ML Module` problem

I could get a similar problem in `coqtop -nois -R theories Coq` as follows:
```
Module Import A. Declare ML Module "ltac_plugin". End A.
Ltac f := match goal with |- _ => idtac end. (* parsing error on |- *)
```
In both cases, the problem is related to trying to replay the action of `Declare ML Module ltac_plugin` where the latter had a non-synchronized action (such as statically declaring the `GRAMMAR EXTEND` part of the Ltac grammar) and a synchronized action (such as declaring tokens or `TACTIC EXTEND` rules).

### What to do?

I'm not fully sure of the conclusion to draw of this analysis, but I would say that a solution could be to make the `GRAMMAR EXTEND` synchronous with the backtracking.

I suspect that by encapsulating the whole result of `coqpp_main.ml` into a function and using `add_known_plugin` with this function rather than `add_known_module` would gives one part of the solution. As for the second part of the problem, we may have to place the `GRAMMAR EXTEND` grammars under the control of a freeze/unfreeze mechanism.

@ppedrot: does it make sense or is the issue more complicated?

### A possible direct fix for `coqc`?

As for the __`coqc` problem__, I suspect that it could otherwise be fixed in a lighter way by doing the `Vernacentries.vernac_require` once and forall rather than once for each file to compile (where, the second time, it dummily "reloads" Ltac in an environment where the keywords have been removed).

It would mean making `Stm.new_doc` and `Vernacentries.vernac_require` commute but I don't know how feasible it is? @gares, do you have an idea?

### A related problem: what to expect of `Import` for `Declare ML Module`?

There seems to be a slightly related problem with the `declare_cache_obj` method used in plugins to register objects such as the `TACTIC EXTEND` rules.
```
Module Import A. Require Import Prelude. End A.
Ltac f := match goal with |- _ => idtac end. (* parsing error on |- due to previous issue *)
Ltac g := intro. (* "intro" unknown *)
```
The reason for the unknown `intro` is that its visibility is controlled by `declare_cache_obj` which is called only at `caching` time (= at the moment of the exact declaration of the command) but not at import time. So, shouldn't we activate `declare_cache_obj` also at `Import` time?

I guess that the current specialist here is again @ppedrot.

**Comment by gares** [comment]
Do we have a real use case for coqc on multiple files? IIRC one has to pass them in the right order, defeating the only use case I could imagine (compile a many file project files without using coq_makefile or eventually dune).

I understand the problem, and I'm not sure it is easy to fix (especially the Declare ML one), but if we remove the possibility from compiling multiple files at least it would become harder to trigger, I guess.

**Comment by maximedenes** [comment]
I would rather fix the problem than hide it TBH.

**Comment by ppedrot** [comment]
> So, shouldn't we activate declare_cache_obj also at Import time?

No, it should rather be the role of the cache function to declare a libobject that will do the job. Otherwise the dynamic model is going to be a mess.

**Comment by ejgallego** [comment]
I think this is fixed by https://github.com/coq/coq/pull/17069 right?
