### ISSUE TITLE
lia performs unnecessary computation in 8.10alpha

### ISSUE THREAD

**Issue by Carotti** [coq/coq#10158]
#### Description of the problem

In coq 8.9, the following code compiles almost instantly as lia uses the `fib_47_computed` hypothesis to bound the value of `fib 47`.

Currently on master, lia appears to attempt to compute `fib 47` instead, resulting in a huge amount of memory being used and the compilation goes on seemingly indefinitely.

```coq
Require Import ZArith_base.
Require Import Coq.micromega.Lia.

Open Scope Z_scope.

Fixpoint fib (n: nat) : Z :=
  match n with
  | O => 1
  | S O => 1
  | S (S n as p) => fib p + fib n
  end.

Axiom fib_47_computed: fib 47 = 2971215073.

Lemma fib_bound:
  fib 47 < 2 ^ 32.
Proof.
  pose proof fib_47_computed.
  lia.
Qed.
```

Originally discovered in mit-plv/bedrock2#74

#### Coq Version

Problem recreated against commit `9f11eee`, doesn't appear in coq 8.9

**Comment by andres-erbsen** [comment]
@fajb has been responsive to lia issues.

**Comment by ppedrot** [comment]
FTR, it seems to be looping while looking for an instance of the ground term `GT` typeclass.

**Comment by fajb** [comment]
That was a bad idea to use typeclasses...
I'll propose a fix.
