### ISSUE TITLE
Notation token starting with a numeral is unusable

### ISSUE THREAD

**Issue by Bubbler-4** [coq/coq#10193]
#### Description of the problem

The OP of [this SO question](https://stackoverflow.com/questions/56205910/how-to-have-multiple-notations-of-0-in-coq) wants to use `0V` as a shorthand notation for the variable `zerov`, but the notation is not recognized. (The reason to use such a notation is provided in the SO question.) The tokenizer seems to split `0` and `V` and interpret `0V` as a function application. Short illustration:

```coq
Section test.
  Variable V : Type.
  Variable zeroV : V.
  Notation "0V" := zeroV.
  Locate "0V". (* Notation "0V" := zeroV (default interpretation) *)
  Check 0V. (* Error:
Illegal application (Non-functional construction): 
The expression "0" of type "nat" cannot be applied to the term
 "V" : "Type"
*)
```

Wrapping `0V` in single quotes doesn't help either, and gives the same error message.

This is not quite intuitive, given that starting with a symbol/letter and mixing symbols/numerals/letters is perfectly fine (up to my experience).

#### Coq Version

8.9.0

**Comment by ejgallego** [comment]
This is fixed, @herbelin , any idea on the PR that solved this issue?

**Comment by herbelin** [comment]
Probably #13664 (similar to the last case of what it solves). Should it appear in the change log?

**Comment by ejgallego** [comment]
Seems to me maybe worth a changelog entry? Certainly some users may observe it. I mostly worry about the situation where users define this kind of notations in master, but the code fail for users of older versions [and they cannot find what had changed].

Anyways, a nice fix, thanks for looking up the PR Hugo!
