### ISSUE TITLE
Describe getting coq via opam in README

### ISSUE THREAD

**Issue by simpadjo** [coq/coq#10194]
Hello! 
Currently README describes two ways of installing coq for Linux users:
1) getting it directly from linux repos
2) building it from sources

In my case version of coq in my Ubuntu LTS repo is too old and I thought that I have to build it myself. I'm new to ocaml/opam ecosystem so I haven't managed to do it.

But luckily I was given an advice to install coq via opam directly (https://stackoverflow.com/questions/56199634/coq-error-unable-to-locate-library-coq-extraction-extraction) and it worked perfectly. 
I think this option of getting coq should be mentioned in docs and considered preferable to building coq oneself.

**Comment by Lysxia** [comment]
Note that the README mentions the opam way.

> Download the pre-built packages of the latest release for Windows and macOS; read the help page on how to install Coq with OPAM; or refer to the INSTALL file for the procedure to install from source.

The download link on the official Coq site as well: https://coq.inria.fr/download

**Comment by simpadjo** [comment]
Sorry, read it not carefully enough.
