### ISSUE TITLE
Ltac2 Type foo := [ bar ] should fail.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#10196]
#### Description of the problem

`bar` does not start with an uppercase letter so shouldn't be supported.
Indeed, when trying to evaluate `bar`, later on it says that it is unbound, whereas if it was capitalized, it would say it has type `foo` when evaluated.

#### Coq Version

8.11+beta1

**Comment by Zimmi48** [comment]
There is the same issue with `Ltac2 Type foo ::= [ bar ]`.

**Comment by kyoDralliam** [comment]
Surprisingly there is one datatype in Ltac2 that has constructors starting with a lowercase, it's [bool](https://github.com/coq/coq/blob/55446694781674f4d4e74546fde54f3dbdea27bc/user-contrib/Ltac2/Init.v#L44). I don't understand why it's currently working but trying to fix this issue breaks that special case.

**Comment by ppedrot** [comment]
@Zimmi48 Yes. We do worse in Coq, so at least Ltac2 is a net enhancement in that respect.

**Comment by kyoDralliam** [comment]
@ppedrot  So what is the design choice wrt to constructors ? Enforce that constructor name start with an uppercase letter and change `true` and `false` to `True` and `False` (I have a branch doing that that I can pr) ? Or are `true` and `false` considered as reserved keywords (and the definition of `bool` should then be special-cased ?

**Comment by ppedrot** [comment]
Second option. Just define the bool type in ML, and check at the level of syntax that constructors should be uppercase.

**Comment by Zimmi48** [comment]
> We do worse in Coq

I disagree. We allow any casing. At least that's consistent.
