### ISSUE TITLE
unification finds Type instead of Prop and fails to downgrade

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#10191]
The following code works:

```coq
Axiom State: Type.
Inductive Command := CFoo | CSkip.

Inductive exec: Command -> State -> (State -> Prop) -> Prop :=
| exec_skip: forall s (post: State -> Prop),
    post s ->
    exec CFoo s post.
```

However, if I don't explicitly annotate `post`, I get

```coq
In environment
exec : Command -> State -> (State -> Prop) -> Prop
s : State
post : State -> Type
The term "post" has type "State -> Type" while it is expected to have type
"State -> Prop" (universe inconsistency).
```

Desired behavior: The above code should still work if I remove the type annotation of `post`.

Coq version: 8.9

Not sure if this has already been reported but I can't find it and I keep running into this issue.

/cc @andres-erbsen

**Comment by SkySkimmer** [comment]
Works now (probably since sort poly in elaboration)
