### ISSUE TITLE
Dune shims fail on Windows

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10216]
`dune exec dev/shim/coqtop-prelude` fails with an Exec error.  Perhaps as a consequence, COQLIB is not set and must be explicitly provided to `dune exec`.

```
$ pushd /cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq
/cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq ~

$ make -f Makefile.dune voboot
dune build -j 3 @vodeps
dune exec ./tools/coq_dune.exe _build/default/.vfiles.d

$ dune exec dev/shim/coqtop-prelude
Error: create_process: C:\Users\Jim.DESKTOP-MMPNVGH\Documents\coqSource\coq\_build/default/dev/shim/coqtop-prelude: Exec format error

$ dune exec coqtop
Error: cannot guess a path for Coq libraries; please use -coqlib option

$ dune exec coqtop -- -coqlib _build/install/default/lib/coq
Welcome to Coq DESKTOP-MMPNVGH:/cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq/_build/default,print_gram2 (e2ec51281596e1230c7bfde3c32f292238480940)

Coq < Quit.
```

**Comment by ejgallego** [comment]
This is due to Windows not recognizing a bash script as executable, the same problem happens with `(run ...)` actions. Not sure what to do, other than removing all shell scripts.

**Comment by jfehrle** [comment]
How about explicitly running `bash` for each bash script?

**Comment by Zimmi48** [comment]
In this case, it would be up to the user of the script, i.e. you, to run `bash _build/default/dev/shim/coqtop-prelude`.

**Comment by ejgallego** [comment]
@jfehrle is this still the case?

**Comment by jfehrle** [comment]
I've since switched to using WSL on Windows, which now runs Ubuntu in a virtual machine, so this no longer affects me personally.  I would have to set up a Cygwin development environment again to try this, which I'd rather not do.  Things work so much better in WSL

**Comment by ejgallego** [comment]
Ok, closing then.
