### ISSUE TITLE
GitHub security advisories

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#10232]
GitHub has just created a new "Security" tab, including a way to create private security reports (what they call advisories), and then to publicly disclose them. Currently, we are pretty transparent about our critical bugs, so we don't need the private advisories (at least not for this, it could still be useful to discuss security issues related to CI or the opam server, etc.) but the publicly disclosed advisories could be a way of informing users about currently known critical bugs, as an alternative or as a complement to `dev/doc/critical-bugs` (which is not currently held up-to-date with *open* critical bugs).

**Comment by JasonGross** [comment]
I would be interested in having a place where I can go to see the currently open critical bugs, and to see when critical bugs were closed.  Though I guess [issue search on the `priority: critical` label](https://github.com/coq/coq/issues?q=is%3Aopen+is%3Aissue+label%3A%22priority%3A+critical%22) can serve that purpose (we seem to have three critical issues open currently, and 17 closed ones).  (It might be nice to dig through the old closed bugs and apply the critical label to the relevant ones, sometime.)

**Comment by Zimmi48** [comment]
Indeed, this issue search already serves that purpose, so putting them in "security advisories" would more be about publicizing them.

>It might be nice to dig through the old closed bugs and apply the critical label to the relevant ones, sometime

Feel free to do that, though it might be hard to find them all.

**Comment by Zimmi48** [comment]
This is a link to a video demonstrating briefly the security advisories feature: https://youtu.be/KzdEm0vupR4?t=2101
The form includes fields for affected versions, patched versions, severity, and CVE identifier and some summary description.

This page on publishing security advisories further informs that GitHub reviews security advisories and can use this to send alerts to affected repositories (but I think they do this only for projects in the few languages in which they are tracking the projects' dependencies), and thus that it can up to 72 hour to get an advisory actually published.

I'm thinking now that this is not the right tool for now, at least as long as Coq can have several critical bugs at once stay open for several months!

**Comment by ejgallego** [comment]
Not sure how to proceed with this; the thing is that we should make clear that Coq is not intended (at all) to be used by adversaries. Right now, from the security point of view, if you load in Coq a malicious script it could likely create a lot of mess, as basically Coq has the capability to overwrite almost any file in the system [that the user has access]

I would be fine with closing that gap, or just documenting the (non) security model of Coq.

**Comment by Zimmi48** [comment]
I think the short-term thing to do is document the (non) security model of Coq. But if there is an issue to track this, it should probably be a different one, shouldn't it?

**Comment by ejgallego** [comment]
> But if there is an issue to track this, it should probably be a different one, shouldn't it?

I guess so, tho adding the documentation could just close this issue as "we don't issue security advisories"
