### ISSUE TITLE
[codeowners] Some data on maintainer activity.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#10234]
Hi all!

[this comment](https://github.com/coq/coq/pull/10050#issuecomment-495303736) made me think that maybe it is a good time to review the current maintainer list and maybe relate it with actual activity on the particular component. We don't have a good way to do that, so I grabbed commit numbers using:

```
git shortlog -s --no-merges V8.5..HEAD -- lib | sort -n
```

Of course, all the disclaimers about the non-scientific data apply, in particular commit count has to be taken with a (large) grain of salt, but nevertheless I find the data interesting.

<table>
  <tr>
    <th>component</th>
    <th>maintainers</th>
    <th>commiters since 8.5</th>
  </tr>
  <tr>
    <td>kernel</td>
    <td>
      <ol>
        <li>
          Maxime Dénès
        </li>
        <li>
          Pierre-Marie Pédrot / Bruno Barras [sub Gaëtan Gilbert]
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 173	Pierre-Marie Pédrot </li>
        <li> 107	Gaëtan Gilbert </li>
        <li> 69	Maxime Dénès </li>
        <li> 57	Emilio Jesús Gallego Arias </li>
        <li> 44	Matej Košík </li>
        <li> 44	Hugo Herbelin </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>library</td>
    <td>
      <ol>
        <li>
          Guillaume Melquiond
        </li>
        <li>
          Enrico Tassi
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 64	Emilio Jesús Gallego Arias </li>
        <li> 53	Pierre-Marie Pédrot </li>
        <li> 36	Maxime Dénès </li>
        <li> 25	Gaëtan Gilbert </li>
        <li> 17	Hugo Herbelin </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>engine</td>
    <td>
      <ol>
        <li>
          Pierre-Marie Pédrot
        </li>
        <li>
          Arnaud Spiwack [sub Gaëtan Gilbert]
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 123	Pierre-Marie Pédrot </li>
        <li> 105	Gaëtan Gilbert </li>
        <li> 58	Emilio Jesús Gallego Arias </li>
        <li> 57	Hugo Herbelin </li>
        <li> 33	Matthieu Sozeau </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>pretyping</td>
    <td>
      <ol>
        <li>
          Matthieu Sozeau
        </li>
        <li>
          Enrico Tassi
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 175	Pierre-Marie Pédrot </li>
        <li> 156	Hugo Herbelin </li>
        <li> 100	Gaëtan Gilbert </li>
        <li> 80	Matthieu Sozeau </li>
        <li> 72	Maxime Dénès </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>interp</td>
    <td>
      <ol>
        <li>
          Hugo Herbelin
        </li>
        <li>
          Emilio Jesús Gallego Arias
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 176	Hugo Herbelin </li>
        <li> 73	Pierre-Marie Pédrot </li>
        <li> 73	Emilio Jesús Gallego Arias </li>
        <li> 44	Gaëtan Gilbert </li>
        <li> 33	Maxime Dénès </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>parsing</td>
    <td>
      <ol>
        <li>
          Team
        </li>
        <li>
          Hugo, Pierre-Marie, Emilio
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 132	Pierre-Marie Pédrot </li>
        <li> 69	Hugo Herbelin </li>
        <li> 68	Emilio Jesús Gallego Arias </li>
        <li> 18	Maxime Dénès </li>
        <li> 18	Gaëtan Gilbert </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>proofs</td>
    <td>
      <ol>
        <li>
          Pierre-Marie Pédrot
        </li>
        <li>
          Théo Zimmermann
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 110	Pierre-Marie Pédrot </li>
        <li> 70	Emilio Jesús Gallego Arias </li>
        <li> 37	Gaëtan Gilbert </li>
        <li> 32	Hugo Herbelin </li>
        <li> 23	Matthieu Sozeau </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>printing</td>
    <td>
      <ol>
        <li>
          Hugo Herbelin
        </li>
        <li>
          Matthieu Sozeau
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 145	Hugo Herbelin </li>
        <li> 114	Pierre-Marie Pédrot </li>
        <li> 85	Emilio Jesús Gallego Arias </li>
        <li> 33	Gaëtan Gilbert </li>
        <li> 21	Maxime Dénès </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>tactics</td>
    <td>
      <ol>
        <li>
          Pierre-Marie Pédrot
        </li>
        <li>
          Matthieu Sozeau
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 292	Pierre-Marie Pédrot </li>
        <li> 106	Hugo Herbelin </li>
        <li> 78	Matthieu Sozeau </li>
        <li> 71	Emilio Jesús Gallego Arias </li>
        <li> 52	Gaëtan Gilbert </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>vernac</td>
    <td>
      <ol>
        <li>
          Matthieu Sozeau
        </li>
        <li>
          Maxime Dénès
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 177	Emilio Jesús Gallego Arias </li>
        <li> 134	Gaëtan Gilbert </li>
        <li> 99	Hugo Herbelin </li>
        <li> 63	Pierre-Marie Pédrot </li>
        <li> 45	Maxime Dénès </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>stm</td>
    <td>
      <ol>
        <li>
          Enrico Tassi
        </li>
        <li>
          Emilio Jesús Gallego Arias
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 108	Emilio Jesús Gallego Arias </li>
        <li> 52	Enrico Tassi </li>
        <li> 39	Maxime Dénès </li>
        <li> 32	Pierre-Marie Pédrot </li>
        <li> 32	Gaëtan Gilbert </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>toplevel</td>
    <td>
      <ol>
        <li>
          Emilio Jesús Gallego Arias
        </li>
        <li>
          Enrico Tassi
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 124	Emilio Jesús Gallego Arias </li>
        <li> 94	Pierre-Marie Pédrot </li>
        <li> 62	Hugo Herbelin </li>
        <li> 31	Matthieu Sozeau </li>
        <li> 30	Maxime Dénès </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>stdlib</td>
    <td>
      <ol>
        <li>
          Hugo Herbelin
        </li>
        <li>
          Matthieu Sozeau / Jason Gross
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 69	Hugo Herbelin </li>
        <li> 67	Jason Gross </li>
        <li> 22	Pierre Letouzey </li>
        <li> 16	Matthieu Sozeau </li>
        <li> 14	Théo Zimmermann </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>ide</td>
    <td>
      <ol>
        <li>
          Pierre-Marie Pédrot
        </li>
        <li>
          Tassi / Herbelin
        </li>
      </ol>
    </td>
    <td>
      <ul>
        <li> 95	Emilio Jesús Gallego Arias </li>
        <li> 51	Hugo Herbelin </li>
        <li> 47	Pierre-Marie Pédrot </li>
        <li> 27	Enrico Tassi </li>
        <li> 20	Guillaume Melquiond </li>
      </ul>
    </td>
  </tr>
</table>

In particular there seem to be some maintainers that are indeed not active anymore, and we have some interesting data gaps, for example on `vernac`.

**Comment by ejgallego** [comment]
For example, some "random" adjustements the data would support are:
- kernel: emeritus Barras, promote Gilbert to 2nd with Pédrot.
- library: add Dénès, emeritus one of Tassi / Melquiond?
- engine: emeritus Spiwak, promote Gilbert / Herbelin ?
- pretyping: hard to say, maybe remain?
- interp, parsing, printing, proofs: no change
- tactics: maybe add Hugo?
- vernac: emeritus Dénès and Sozeau? promote Gallego Gilbert, Herbelin?
- stm: no change
- toplevel: maybe promote Herbelin?
- stdlib: no change

**Comment by gares** [comment]
Why didn't you count merge commits?

**Comment by ejgallego** [comment]
> Why didn't you count merge commits?

No particular reason; as I said the data is quasi-random; better data would require reviews, etc... but that's beyond what I can do, feel free to make a new table.

**Comment by maximedenes** [comment]
I hope this is a joke.

**Comment by Zimmi48** [comment]
On the contrary, I think this is very interesting stuff, and thank you @ejgallego for starting this discussion. ATM we don't really have a process for changing maintainers but sometimes it is useful.

I wouldn't worry too much about a maintainer not being very active in terms of number of commits if they actually keep up with the state of the component by being active doing reviews. What data would be very helpful to get is something about who actually does review the PR that affect a component.

There have been many cases of PRs being overtaken by an alternative shepherd because the main owner was not responsive. This is usually a source of delay (we don't take over as soon as the PR is submitted), it means that the maintainer knows less and less well the code, and would be a good reason to switch maintainers. I would add that I think the ideal model is the one I started to put in place with teams of maintainers instead of a principal and a secondary one. Then all the experts of the component are in the team and whoever is more reactive can take it.

**Comment by Zimmi48** [comment]
>whoever is more reactive can take it

With the caveat that if the PR contains controversial material, being more reactive doesn't mean that you are allowed to take any decision without waiting for others to give their opinion.

**Comment by maximedenes** [comment]
> I hope this is a joke.

Let me be more specific.
1. I spent a lot of energy envisioning reorganizations of `vernac`, better handling of locality, propagation of flags (`is_program_mode` and the likes), moving vernac-related objects back to vernac, etc etc. I also reviewed changes, carried out refactorings, etc. Motivating this "study" by a comment saying I needed 24 more hours to review a vernac-related PR as at best a lack of tact.
1. As you write, you arbitrarily take the number of commits as a measure of activity. That's fine. But then you suggest some "adjustments" (a.k.a. decisions) that should be made based on it. I want to emit a big warning that basing decisions on some indicators will have a great deal of effect on the nature of the activity we have. In particular, I can surely optimize the number of commits I do, but I'm not sure that's in the best interest of Coq.
2. Adding reviews to the data will still introduce a huge bias: time spent on *design* won't be taken into account, for example. When you see how much some components of the system would need in this area, I really think that's not something we want.

Now some questions:
1. What's the exact link between this post and the comment you cited?
1. Couldn't we simply change/add/remove maintainers when me people agree? Why does it need to be "supported" by an aggregation of data, as you write?

**Comment by ejgallego** [comment]
I am not sure what to say, in particular I'm unsure how to reply to calling this work a "joke". Just a couple of clarifications:

> 2\. But then you suggest some "adjustments" (a.k.a. decisions) that should be made based on it.

In no moment I did such a thing. I wrote "the data would support" ; maintership and development model is a very complex issue and obviously cannot be determined by a `git log`.

> 2\. I can surely optimize the number of commits I do, but I'm not sure that's in the best interest of Coq.

Indeed commit data has many more problems than that, including granularity and global vs sub-system specific commits [which could be inferred tho using regression] . But an assumption that is needed of course is that a) developers are not adversaries , of if they are b) there are not adaptative.

Adversarial adaptative analysis of activity is likely going to fall into some impossibility result indeed.

> * What's the exact link between this post and the comment you cited?

The link is that I was not aware you were 2nd on vernac, so I though "oh, let me review all the maintainers again"

> 2\. Couldn't we simply change/add/remove maintainers when people agree? Why does it need to be "supported" by an aggregation of data, as you write?

Data is data, it is good to give ideas and to contribute to more comprenhensive analysis / understanding of the model, as @Zimmi48 pointed out.

**Comment by gares** [comment]
I think an interesting metric to analyze would be how many PR were reverted for each component, since these events typically happen when the component lacks proper tests and/or when the reviewers are not catching severe problems.

**Comment by ejgallego** [comment]
> I think an interesting metric to analyze would be how many PR were reverted for each component, since these events typically happen when the component lacks proper tests and/or when the reviewers are not catching severe problems.

That's a good idea, although I think we all have a good idea on which components are the trickiest, indeed we could have a tag for "problems after beta". The question is, what to do with that information?

Anyways, I think this issue is seeing its lifetime; I've been usually posting the data to Gitter but it seemed to me that posting here could made for a better storage.

Thus, I guess I'll close this unless anyone sees a case for keeping it open.
