### ISSUE TITLE
Omega plugin triggers (disabled-by-default) warning on import

### ISSUE THREAD

**Issue by tchajed** [coq/coq#10250]
#### Description of the problem

PR #10167 introduces a disabled-by-default warning for disjunctive patterns (`disj-pattern-notation,notation`) that is triggered by Omega, and possibly other parts of the standard library. Worse still, this warning is triggered on import, so that `coqc -W +all test.v` fails where `test.v` is just:

```
Require Import Omega.v
```

The standard library probably shouldn't be triggering this warning, and it also shouldn't affect importers. From what I can tell skimming the discussion of PR #10167 the support for adding warnings to a notation might be preliminary so maybe that isn't a known bug.

Note that because the warning is only on import the offending disjunctive pattern could really be anywhere in Omega or its recursive dependencies - I haven't tried to narrow that down.

#### Coq Version

8.10+alpha

**Comment by tchajed** [comment]
If anybody is running into this, just switch to `-W +all,-disj-pattern-notation` for now.

**Comment by ejgallego** [comment]
This seems not to be an issue in the Coq's stdlib anymore.
