### ISSUE TITLE
vio2vo produces incorrect term when discharging

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#10268]
~~~coq
Section Foo.
  Variable A : Type.

  Definition bla := A.

  Variable B : bla.

  Lemma blu : {X:Type & X}.
  Proof using A B.
    exists bla;exact B.
  Qed.
End Foo.
~~~
after coqc -quick and coqc -vio2vo, coqchk says
~~~
  checking cst:Test.foo.blu
Fatal Error: Type error: CantApplyNonFunctional
~~~

**Comment by ppedrot** [comment]
The problem comes from the abstract info provided to the discharge function. It is already half-discharge when passed as an argument to the STM. Will provide a fix soon.

**Comment by SkySkimmer** [comment]
Print says the term produced is
~~~coq
blu = 
fun (A : Type) (B : bla A A) => existT (fun X : Type => X) (bla A) B
     : forall A : Type, bla A -> {X : Type & X}
~~~

**Comment by ppedrot** [comment]
I am marking this bug as critical, even though producing a proof of False out of it is surely a bit involved. Yet, this is clearly an ill-typed term passing the kernel barrier without a fuss, so it deserves the flag.

**Comment by SkySkimmer** [comment]
There shouldn't be a proof of false from this, as the bug appears in the saving path for the proof witness which has already been checked, and it's opaque so nobody should be able to rely on its incorrectness.

**Comment by gares** [comment]
It can break extraction still. Looking forward to the fix!
