### ISSUE TITLE
YouShouldNotTypeThis tokens in the ssr grammar? coqpp change to fix?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10275]
#### Description of the problem

The ssr grammar has a number of productions that start with `YouShouldNotTypeThis`.  If `ARGUMENT EXTEND` in coqpp allowed an empty `tactic_rules`, could these rules be deleted?  Or is there some other simple change to make them unnecessary?

I will submit a PR for this if it makes sense.

**Comment by jfehrle** [comment]
@gares, @ppedrot ?

**Comment by gares** [comment]
Yes, empty extend statements would work, and I believe @maximedenes had a patch in a drawer...

**Comment by maximedenes** [comment]
> I believe @maximedenes had a patch in a drawer

Yes, but it was before coqpp. I don't remember if it was merged or not.

**Comment by ppedrot** [comment]
It's even easier now, because there is an ML API that you can use to define the arguments instead of having to rely partly on the macro.

**Comment by gares** [comment]
I guess we can fix that next week all together

**Comment by jfehrle** [comment]
Is the ML API preferred even for `ARGUMENT EXTEND`s that have useful productions?  If so, do we want to convert those to use the API, too?  Using both mechanisms makes the code a bit harder to understand.  On the other hand, having coqpp allow an empty `tactic_rules` would keep them all consistent.  And it appears to be a very simple change.

**Comment by DabrowskiFr** [comment]
The change was indeed very simple. Just submitted a PR (#10307)
