### ISSUE TITLE
Incomplete documentation for CoqIDE installation.

### ISSUE THREAD

**Issue by charguer** [coq/coq#10283]
#### Description of the problem

I've add trouble compiling CoqIDE 8.10, due to incomplete information on the dependencies. Because the trouble is related to the switch to lablgtk3, I suggest the changelog be more explicit about the new dependencies, or includes a pointer towards another page from the manual that provides an up-to-date list of dependencies.

After some investigation, I managed to decrypt the various error messages.
- ocamlfind is required by configure, but not installed by default on opam switch
- num is required for ocaml 4.06
- not only lablgtk3 but also the sourceview3 extension is required for compiling coqide, and the several corresponding system packages.

Here is the path that worked for me (Ubuntu 16.04):
```
   opam update
   opam switch create 4.07.1
   sudo apt-get install libexpat1-dev libgtk-3-dev libgtksourceview-3.0-dev
   opam install num ocamlfind lablgtk3 lablgtk3-sourceview3
   ./configure -local
   make -j 4
```

I know that details may vary from one OS/distribution to the next. Still, providing an example of how to get compilation to work on one (or two) systems could greatly help every user.

#### Coq Version

8.10beta1

**Comment by charguer** [comment]
Just to show one kind of confusing error message that I faced:

  ```
   $ ./configure  -coqide opt -local
   LablGtk3 not found:
   => cannot build requested CoqIde

   $ opam list
   # Packages matching: installed
   # Name              # Installed # Synopsis
    ...
   lablgtk3            3.0.beta6   OCaml interface to GTK+3
```

**Comment by Zimmi48** [comment]
@charguer We have an INSTALL file at the root of the repository. Could you read it and check that the information provided there is correct and sufficient? If it is, maybe we could just amend the changelog entry to remind about the existence of this file, but it is already advertised in the README and in the introduction of the refman.

**Comment by charguer** [comment]
The install file I just checked, could provide the exact names of the Debian packages for lablgtk dev. 

Besides, the changelog could point out that the install file has been updated to reflect changes in lablgtk. 

(not critizing anyone here, I'm just trying to save time to others before they get confused like I was) 

Thanks
