### ISSUE TITLE
Unused nonterminal symbols in ssr grammar

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10294]
I found 4 nonterminals that appear to be unused by the SSR grammar productions.  I was able to remove 2 of them and still compile.  I can put in a PR for this if you like.

ssrhyps
ssrsimpl
ssrindex - still used in 2 places, e.g. “TYPED AS (((ssrindex * ssrmmod)”
ssrpatternarg - used in ssrpatternarg.v.

**Comment by jfehrle** [comment]
@gares?

**Comment by gares** [comment]
The latter is there for condition in ltac tactic notation, for the others I don't know. Please submit a pr
