### ISSUE TITLE
Unexpected typeclass resolution (the return of)

### ISSUE THREAD

**Issue by charguer** [coq/coq#10298]
#### Description of the problem

A trivial "apply" of the identity function triggers typeclass resolution on evars, very unexpectedly. This is a serious backward incompatibility with Coq-8.9, for which I cannot figure any sensible work around. This seems to be similar to a prior issue #6583, but perhaps in a yet tricker form. As it stands, this undesirable behavior compromises all the infrastructure of my CFML program verification tool. 

After 2 hours of efforts, I finally managed to obtain a small, independent example. Here it is:

```coq
Set Implicit Arguments.

Generalizable Variables A.

Parameter val : Type.

Class Enc (A:Type) :=
  make_Enc { enc : A -> val }.

Global Instance Enc_dummy : Enc unit.
Admitted.

Definition FORM := forall A (EA:Enc A) (Q:A->Prop), Prop.

Definition IDF (F:FORM) : FORM := F.

Parameter ID : forall (G:Prop), G -> G.

Parameter EID : forall A (EA:Enc A) (F:FORM) (Q:A->Prop),
  F _ _ Q ->
  F _ _ Q.

Lemma bla : forall F,
  (forall A (EA:Enc A), IDF F EA (fun (X:A) => True) -> True) ->
  True.
Proof.
  intros F M.
  notypeclasses refine (M _ _ _).
  notypeclasses refine (EID _ _ _ _).
  eapply ID. (* undesirable instantiation of ?Goal0 *)
Abort.
```

#### Coq Version

coq 8.10beta1

**Comment by charguer** [comment]
Ping: what's the status for this bug? It's a major blocker for me. 

If can't be fixed, one possible workaround would be to provide a mean to prevent any typeclass resolution over a given tactic call. Essentially, generalize `notypeclasses refine E` to `notypeclasses tac`, for an arbitrary tactic, to switch a global flag turning off any typeclass resolution during the whole execution of tac (and the tactics called by tac). This would do the job, and shouldn't be too hard to implement.

**Comment by ppedrot** [comment]
@charguer did you try to bisect to find the culprit commit? It would probably help to narrow down the issue and its fix.

**Comment by ppedrot** [comment]
Issue seemingly introduced by fb1c2a017ef8112e061771db14ccc6cc1f09d41c.

**Comment by charguer** [comment]
Thanks @ppedrot for looking into this.

Sorry I don't have the expertise to bisect by myself on coq commits.
After my summer vacations, I'll put TLC and CFML2 into the CI to help catch these bugs sooner,
that's indeed the least I could do to help same time to Coq devs.

**Comment by ppedrot** [comment]
Pinging @mattam82 as he is the one to have introduced the change.

**Comment by Zimmi48** [comment]
?@mattam82 Had you had any chance to look into this?

**Comment by mattam82** [comment]
So, you expect `notypeclasses refine` to generate (even dependent) subgoals which are no longer candidates for resolution? The patch I did should allow to do that easily

**Comment by charguer** [comment]
Either I didn't explain the problem well, or I don't understand your last sentence. 
In my example, `refine` produces subgoals candidates for resolution.
But because I use `notypeclasses refine` instead of `refine` these subgoals are not resolved.
Subsequently, I call `eapply` on something completely unrelated.
I do not expect that call to interfere with the previously-generated subgoals.

In other words, there is in my mind some notion that `notypeclasses` modifiers means "don't try to resolve now nor later". But perhaps it is currently interpreted as "don't resolve just now, but try to resolve at any subsequent tactic invokation". What was the original intention?

**Comment by silene** [comment]
Perhaps you have minimized your example too much, but `?Goal0` occurs in the current subgoal, so it is not "completely unrelated".

**Comment by charguer** [comment]
> ?Goal0 occurs in the current subgoal, so it is not "completely unrelated".

Technically true, the original example was similar, as far as i recall.
But to make the counter-example look slightly worse, you can modify the end of the script as:

``` 
  match goal with |- IDF F ?X _ => set (EA := X) end.
  match goal with |- IDF F _ ?Y => set (FA := Y) end.
  clearbody EA.
  eapply ID.
```
Then the goal becomes
```
EA : Enc ?Goal
FA := fun _ : ?Goal => True : ?Goal -> Prop
______________________________________(1/1)
IDF F EA FA
```
and `eapply ID` still instantiates `?Goal` as `unit`, although I would like to think of the identity function as treating its argument somewhat "abstractly".

**Comment by silene** [comment]
You are applying `@ID (@IDF F ?Goal EA FA)` to the current subgoal. How is Coq supposed to guess that `?Goal` should not be resolved using typeclasses? That is why @mattam82 suggests to mark `?Goal` as definitely unresolvable.

**Comment by mattam82** [comment]
Yes. The “not later” confirms my understanding of the semantics you want, which makes sense.

**Comment by charguer** [comment]
I understand we both need a short-term solution to work-around the backward
compatibility issue, and a long-term solution with a good design, and it might
be hard to satisfy both right now.

Also, sorry I have only a partial understanding of the implementation and implication
of what's inside the typeclass beast; I'll nevertheless try to contribute.

I tried to understand the implication of "don't try to resolve now 
nor later" meaning of `notypeclasses refine`. It would be manageable but
probably far from perfect. I suspect that it would leave unshelved typeclasses
instances at the end of every one of my goal, to be then resolved by
`eauto with typeclasses`.

I have investigated further examples, and played with the option
`Set Typeclasses Strict Resolution`. For those who are not familiar, this
option prevents the typeclass arguments to be instantiated, by setting them
as rigid variable. ("When looking for unifications of a goal with an instance of
 this class, we “freeze” all the existentials appearing in the goals, meaning 
that they are considered rigid during unification and cannot be instantiated.")

This option does solve some problem, for my case, but causes other trouble.
In the specific case of my `Enc` typeclass or of the standard
`Inhabited` type class, with a single input (type) argument, it does mostly
the "desired" thing. One caveat I found with this option is that running
tactics `foo. bar.` works in cases where `foo; bar` fails 
(and `foo; instantiate; bar` also fails), even when `foo` produces a single
subgoal. I haven't found a workaround for at the moment (probably would 
deserve a separate issue), and this makes it impossible to implement some
of my tactics as a result.

Also, one big issue with `Set Typeclasses Strict Resolution` is that it does not
work well for typeclasses with several arguments, some of which are "input"
and other "output". I suspect that this option somehow implements support
for the special case where all arguments are input arguments.

I recall Matthieu and I once discussed setting "input" and "output" mode for 
typeclass arguments, it is probably related. One would declare `A` to be
an input argument to `Enc A` and ensure that resolution of `Enc X` gets
triggered at the moment when `X` becomes resolved. Yet this raised further
questions, what if `X` is only partially resolved, e.g. as `?X1 * ?X2`?
What does it mean for an argument `X` to be `fully` resolved before 
resolution should be attempted for `Enc X`?

Probably raising more questions than answers, sorry...

**Comment by Zimmi48** [comment]
Would reverting the faulty commit in `v8.10` be a way of solving the issue for 8.10 while a better fixed is being worked on? Or is it too complicated to do?

**Comment by mattam82** [comment]
@charguer indeed the fact that `foo. bar.` differs from `foo ; bar` looks suspicious. It might be that there is some part of the code that does not respect the evar instantiations properly and that's probably a bug. My proposed fix implements what you originally asked for, it would be good if you can experiment with it a bit to see if it helps.

**Comment by charguer** [comment]
I should be able to test your patch tomorrow, and also report on the other suspicious behavior. Thanks

**Comment by charguer** [comment]
The fix resolves some issue, but others remain. I posted the comment in the pull request thread.

**Comment by vbgl** [comment]
I’ve just removed the milestone, as it seems that the fix won’t be ready for the release of 8.10.0.

**Comment by charguer** [comment]
The fix works for me. I don't know the implication of pushing it to 8.10.0 without thorough beta testing. Good idea as it will avoid other people the bug? Bad idea because it hasn't sufficiently be tested? I fear both choices are terrible... :)

**Comment by Zimmi48** [comment]
It seems that it is already too late for 8.10.0, but your doubts should also apply to 8.10.1 because we do not release beta versions for patch-level versions. Thus, only bug fixes that are "safe" should be backported, and if you think that this bug fix is not safe, then maybe it should be delayed to 8.11.

**Comment by mattam82** [comment]
The idea is to fix a regression, so it should be safe in the end

**Comment by maximedenes** [comment]
@mattam82 I'm a bit lost here. The test case that was added in #10762 is different from the original example posted here, whose behavior seems to be the same in master as at the time of the report. Was the example invalid?
