### ISSUE TITLE
Anomaly "Uncaught exception Not_found." on basic apply

### ISSUE THREAD

**Issue by charguer** [coq/coq#10300]
#### Description of the problem

Raises "Anomaly Not_found".

```
Set Implicit Arguments.

Definition hprop := nat -> Prop.

Definition himpl := fun H1 H2 : hprop => forall (h : nat), H1 h -> H2 h.

Parameter himpl_refl : forall H : hprop, himpl H H.

Parameter hstar : hprop -> hprop -> hprop.

Parameter hpure : hprop.

Lemma test : (forall (H:hprop), himpl (hstar H H) hpure -> True) -> True.
Proof. intros M. eapply M. try apply himpl_refl. (* also anomaly without [try] *)
```

#### Coq Version

coq8.10beta1

**Comment by maximedenes** [comment]
Bisect says the first bad commit could be any of:
1c60cbedfd8a5e64bfa95dfb9a9497e278458c30
66892881c69cfb91fe1cd772cd88ac2c73c99bbe
78b51f541d0107f06c21fc1260aae2ab9f7229c5
8a5cd826ee8d7d51c85c834c28f090466dda33a5
a4157eb4cb5ede453e02b415aa0c2b10ce9f961d
acc4f5922dcc1f92f3dc3db653b7608949b60c2b
93ef4e058cb9f7bfc6f3abc8bdc5752a2d8df5ca
c002eae68ac12dc8ed92e906b346f73606e7fd69
2cf15ef8e3ddebe285ec0e9f5f8715b025ba4eec
e3178fb2de9a84bbcdc90a60cd8f27cd1323eb36
af9b88c253b578ad53ee884ff3102d0a74056a1e
e07fcc19cf8459ce2ae87d9ccbbc7806a0be576f
2265d20c48dff6e1ea9a5cb9be9640603f3be3cf
5f05bb81c2de54d31887b276d0f127455dd83815
781f050bcfabe02e225f3c1d29ee649610d6d680
ad0cf24789b0f7d5b12cef4d09f93c9d9aeb6150
62cf1ad380772628ed6e547de3fb875275610b4d
dc8f191f2d81fd5f851b84e7aeda487df584197e
1c9e1a39652b401805029519055aa62adacde339
ce36c131804cd7fb0a460277d88743c7131c5ed3
746e74ed6e70cf01f0a0e73f772c3565e28fe3f8
b74aaa4ce0191b92837a15773ae23e53abd22bd9
ab6397730354d6048062568c87a7d971f20934c0

@coq/ci-maintainers @Zimmi48 any thoughts on having so many intermediate commits that don't build? Shouldn't we test that at least the OCaml part of Coq builds for all commits?

**Comment by Zimmi48** [comment]
Until now, it was up to the PR author to test this kind of stuff, but if even core developers don't do it, then it might be worth checking it automatically now.

**Comment by ejgallego** [comment]
This is a consequence of rebased, Yeah we should add a job that does that.

**Comment by Zimmi48** [comment]
Unless someone plans to do it know, a new issue about this should probably be opened.

**Comment by vbgl** [comment]
Running `git bisect` points at ab6397730354d6048062568c87a7d971f20934c0 (aka #7819). Ping @mattam82.

**Comment by mattam82** [comment]
Really? That commit just does a renaming, probably an earlier one...

**Comment by vbgl** [comment]
Earlier commits in the PR do not build.

**Comment by ejgallego** [comment]
Fixing the build bisect points at:
```
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Jul 26 17:07:08 2018 +0200

    [evarconv] New flag handling for unifier
```
