### ISSUE TITLE
CoqIDE:  a zero size completion appears on the screen

### ISSUE THREAD

**Issue by thery** [coq/coq#10312]
#### Description of the problem

A zero size completion window randomly appears on the screen
![complet](https://user-images.githubusercontent.com/6795190/58946178-9e6f3880-8785-11e9-8750-8240b6e1466f.png)

#### Coq Version
8.10+alpha

**Comment by eponier** [comment]
Cf. https://github.com/coq/coq/issues/9945

@ppedrot reimplemented completion in GTK, but is not fully satisfied yet. Personally, I only find very minor problems with his implementation.

**Comment by thery** [comment]
@eponier I don't get any error message and my window is permanent (till I activate another completion)

**Comment by eponier** [comment]
I was more thinking of the [remark](https://github.com/coq/coq/issues/9945#issuecomment-488073299) of @herbelin in the same thread.

**Comment by ppedrot** [comment]
Probably fixed by #11400, so closing this. Reopen if not the case.
