### ISSUE TITLE
[Ltac2] Not possible to specify result type of functions

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10346]
Ltac2 does not allow to specify the result type of functions. The following is a syntax error:
```
Ltac2 bool_and (a : bool) (b : bool) : bool := …
```
I would prefer to have this because I think for use of Coq in engineering it is generally preferable to document result types in this way and not to use type inference. I know this is not terribly idiomatic but I think at least library code should be optimized for readability rather than writeability and one can argue that giving the types makes it easier/faster to understand what a function is supposed to do.

**Comment by tchajed** [comment]
Agreed that this is important. In fact in some cases the return annotation is necessary to reduce polymorphism, which can be good documentation as well as improve error messages for callers.

From gitter it sounds like @ppedrot is on board with this, if he can figure out how to parse the syntax unambiguously. Given that OCaml has the same syntax it should be possible, at least in theory.

**Comment by RalfJung** [comment]
I also just ran into this and was quite surprised to learn that return types cannot be specified in `Ltac2`.

**Comment by ppedrot** [comment]
This was actually fixed by #13914. I forgot to link this issue in the PR.

**Comment by RalfJung** [comment]
Oh, nice. :)
