### ISSUE TITLE
[Ltac2] no way to create an empty array without supplying an instance

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10348]
Ltac2 has no way to create empty arrays without supplying an instance. This leads to a lot of additional checks in the array library I proposed in PR #10343, since for functions which should return an empty array one frequently has no instance available one could supply to make.

**Comment by MSoegtropIMC** [comment]
@ppedrot : I made myself a bit familiar with the Ltac2 implementation and I could add this function. Shall I create a PR, or do you want to do this?

**Comment by ppedrot** [comment]
Feel free to write it if you have time, right now I don't have much myself.
