### ISSUE TITLE
big-memory CI worker for fiat-crypto

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10353]
I'd like to enable the more memory-intensive targets of fiat-crypto on Coq's CI, as they have recently been broken by an update to Coq (see #10352).  Peak memory usage per file seems to be 2 385 020 ko on master, a bit more on 8.9 (2 526 224 ko) and 8.8 (2 799 940 ko).

The relevant change to https://github.com/coq/coq/blob/45306c6c9c433b86406d041f58aafb7cf3a3ff82/dev/ci/ci-fiat-crypto.sh#L13-L18
is to change `print-nobigmem nobigmem` to `coq`

cc @ejgallego 

What needs to be done on my side?

**Comment by ejgallego** [comment]
Peak memory is just below current workers limits so you could try to enable them in a PR and see what happens.

If that's not enough, we would need to setup a worker with enough memory and use gitlab CI tags so the memory-hungry jobs are only ran in that special runner.
