### ISSUE TITLE
Coq master can no longer build fiat-crypto

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10352]
#### Description of the problem

https://travis-ci.org/mit-plv/fiat-crypto/jobs/543294608

Coq seems to run forever and eat up all the available memory on src/Curves/Weierstrass/Projective.v.  Possibly something to do with par:, and seems like a fairly recent regression (past week or two).

#### Coq Version

master

**Comment by ejgallego** [comment]
A bisect would be very useful.

**Comment by ppedrot** [comment]
I'd bet this has to do with the change in hashconsing introduced by #10198.

**Comment by JasonGross** [comment]
@ppedrot Didn't the bench show an improvement in all areas on fiat-crypto, though?  (The relevant target *is* tested by the bench, even if it's not tested by the CI.)

**Comment by JasonGross** [comment]
Hmmmmm, I am suspicious.  The PR I was merging into fiat-crypto failed twice in this way on master, I believe, but now that I've merged it, it seems to work fine on master.  So my current guess is that there's a heisenbug in `par:`, but I will close this as I can no longer reproduce it at the moment.
