### ISSUE TITLE
Extraction of primitive integers

### ISSUE THREAD

**Issue by vbgl** [coq/coq#10361]
Extraction of primitive integers does not behave as documented. In the following example, the primitives `int` and `add` are not mapped to the corresponding type and operator from the `Uint63` OCaml module.

~~~
From Coq Require Import Int63 Extraction.

Definition one := (0 + 1)%int63.

Extraction one.
(*
The following axioms must be realized in the extracted
code: int add.
 [extraction-axiom-to-realize,extraction]
(** val one : int **)

let one =
  add (Uint63.of_int (0)) (Uint63.of_int (1))
*)
~~~

Moreover, it should be possible for third-party projects to reuse the implementation of the `Uint63` module from the kernel. Currently, this is possible by linking to the `coq.kernel` library. I believe that this module should be taken out of the `kernel` library.

**Comment by thery** [comment]
I find the extraction of primitive int a bit strange

The function ``positive_to_int_rec` has the following code

``i >> 1``

 that is extracted as 

``(lsl0 i (Uint63.of_int (1))``

where this ``lsl0`` comes from????

When googling at how to translate I found this pull request  in nativecoq (@maximedenes )

https://github.com/maximedenes/native-coq/pull/15/

where @vblot adds a file  plugins/extraction/ExtractNative.v

is it not what we are missing in 8.10?

**Comment by vbgl** [comment]
About `lsl0`: when you extract “i >> 1”, you get a warning:

> Warning: The following axioms must be realized in the extracted
code: lsr int.
 [extraction-axiom-to-realize,extraction]

This highlights that extraction does not know what to do with the type “int” and the operator “>>”.

Moreover, as “lsl” is an OCaml keyword, extraction will use “lsl0” as identifier.

As you point out, a good fix for this issue seems to add a few “Extract Constant” directives. Should these directives belong to the “Int63” module or a dedicated one? I tend to prefer the second option and to amend the documentation: “in order to extract native integers to OCaml, the `Int63OCamlExtraction` module must be required”.

**Comment by thery** [comment]
@vbgl thanks for the explanation. A dedicated module for the directives are fine with me.

**Comment by maximedenes** [comment]
We should indeed review https://github.com/maximedenes/native-coq/pull/15 and merge it into master.
