### ISSUE TITLE
[Ltac2] Semicolon chaining operator sometimes requires extra Control.enter

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10387]
In some cases the semicolon tactic chaining operator does not focus the subgoals. That is:

`<some tactic>; <some tactic>.`

does not work while

`<some tactic>; Control.enter <some tactic>.`

does work. The second `<some tactic>` is in the first case fully applied, in the second case a thunk. An example (again from the VFA part of software foundations) is attached.

I understand the logic of `;` such that it should inherently do a Control.enter. Also it usually does work - the example also contains an example of destruct which does work, but not always.

Example:
[Redblack_Ltac2c.zip](https://github.com/coq/coq/files/3295867/Redblack_Ltac2c.zip)

**Comment by JasonGross** [comment]
`;` definitely should not focus the subgoals, otherwise `; [ > foo | bar ]` would never work

**Comment by MSoegtropIMC** [comment]
Well you are right that it would be wrong if `;` per se would focus the goal, but somewhere in the process of executing `a ; b` when b is applied to an individual sub goal produced by `a`, shouldn't this sub goal be focused then (one by one)? Otherwise one always has to know if a tactic accesses the goal e.g. via a match. Calling Control.enter on the entry of such tactics is also not much of an option, with the same argument that `; [ > foo | bar ]` wouldn't work then because a Control.enter in foo would focus sub goals foo is not supposed to handle.

**Comment by ppedrot** [comment]
@JasonGross is right, semi-colon should never focus. This was actually the semantic reason that required rewriting the tactic engine in 8.5 from scratch. Note that Ltac1 semi-colon doesn't focus either since then. The intended mental model is that tactics are acting on several goals at once, but most primitive tactics perform an implicit enter.

**Comment by MSoegtropIMC** [comment]
I see. So if tactics generally work on lists of goals, it does make sense to do a Control.enter at the beginning inside every tactic function which does goal matching or other stuff which panics if not exactly one goal is focused. Interesting. I will try this and see if the behavior then matches my expectations.

**Comment by MSoegtropIMC** [comment]
Closed - it works as expected taking the explanation of @ppedrot into account.

**Comment by JasonGross** [comment]
Note that in Ltac1 (any maybe Ltac2?), things like `constr` and `match goal` do in fact do Control.enter under the hood.

**Comment by MSoegtropIMC** [comment]
As far as I can tell one has to do the Control.enter explicitly in Ltac2 before a match goal.
