### ISSUE TITLE
dependent evars line empty

### ISSUE THREAD

**Issue by hendriktews** [coq/coq#10399]
In Coq 8.9.1, when I feed

    Set Printing Dependent Evars Line.
    Lemma x : exists(i : nat), i = 0.
    Proof using.
      eexists.

into `coqtop -emacs`, the dependent evars line shows one open existential:

    (dependent evars: ?X6 open,)

When I do the same on the current git master (8acc04d4c33ed41ac8dfa668a026010d4592388d), I only see

    (dependent evars:)

Was that change intentional?

(Some background: The dependent evar line was introduced by Arnaud Spiwack in 2011 for Coq 8.4 on my request for prooftree, the proof tree visualization program for Proof General and Coq. For 8.4 and 8.5 the line enables prooftree to highlight commands that introduce or instantiate a particular existential variable. Since 8.6 the feature is broken, because there is no way to link the evars appearing in the goals with those in the dependent evar line.)

**Comment by hendriktews** [comment]
I bisected the problem to commit 6608f64f001f8f1a50b2dc41fefdf63c0b84b270.

**Comment by JasonGross** [comment]
I was under the impression that this was deliberate; I seem to recall reporting an issue where displaying this line was a performance bottleneck (I believe it took multiple seconds to display each goal, because there were hundreds of thousands of evars)

**Comment by jfehrle** [comment]
> there were hundreds of thousands of evars

Really?  How long are your proofs?  (e.g. # of tactics including those generated by Ltac or size from "Show Proof").  I didn't think people were doing proofs of this size--if that's a common use case then you might want some different design choices.  And these are efficient proofs--without unneeded steps generated by automation?

**Comment by hendriktews** [comment]
> I didn't think people were doing proofs of this size--if that's

I don't know, but there was a performance problem reported with the dependent evars line. However, I would suggest to not address this problem because:
- the dependent evars line is off by default - only those people that deliberately switch it on will be affected
- Proof General switches the line on, but only when one deliberately requests a proof tree display. When people want to use proof tree with such huge proofs, I will make the evars feature of prooftree optional, such that they can choose to not enable the dependent evar line.

**Comment by JasonGross** [comment]
I may have overestimated a bit; #3691 reports "only" about 13 000 evars.  See also #4819, which invokes only three tactics, none of which leave evidence in the proof term.  (Apparently printing the dependent evars line can be slow even when there are not that many evars?)

It was for these issues that the option to turn off the dependent evars line was added in #207

**Comment by hendriktews** [comment]
Jason Gross <notifications@github.com> writes:

> printing the dependent evars line can be slow even when there
> are not that many evars?)

Maybe, I have never observed this and I used to use prooftree for
almost every proof with dependent evars line on.

> It was for these issues that the option to turn off the
> dependent evars line was added in #207

Just to clearly state it again: My feature request #10420 should
only affect the behavior when the option is on - and it should
stay off by default.

Hendrik
