### ISSUE TITLE
Definition without a body fails with `<var> is already used`, but adding a body makes it succeed

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#10409]
#### Description of the problem

In the following example, the first definition succeeds, but the second one fails with `Error: T is already used.`:

```coq
Section test.
  Variable T: Type.

  Definition P (T: Type) : Type := prod T T.
  Definition P' (T: Type) : Type.
```

#### Coq Version

8.4 through 8.9 and master

**Comment by SkySkimmer** [comment]
Is this not the desired behaviour?

**Comment by cpitclaudel** [comment]
I don't know which one is right, but the inconsistency looks wrong.

**Comment by JasonGross** [comment]
> I don't know which one is right, but the inconsistency looks wrong.

To elaborate, the inconsistency is because shadowing is allowed (`fun x x => x`), but we don't want to rename the section variable in interactive proof mode.  (Though if you really want to push the inconsistent behavior, consider `Definition P (T: Type) : Type := ltac:(exact (prod T T)).`)
