### ISSUE TITLE
build failure due to missing dependency on cmi

### ISSUE THREAD

**Issue by madroach** [coq/coq#10403]
#### Description of the problem
build failure due to missing dependency on cmi

#### Coq Version
Coq 8.9.1
camlp5 https://github.com/camlp5/camlp5/pull/37
OCaml 4.08.0
OpenBSD 6.5-current

#### Fix
``` diff
Index: Makefile.build
--- Makefile.build.orig
+++ Makefile.build
@@ -748,7 +748,7 @@ plugins/%.cmx: plugins/%.ml
 	$(SHOW)'OCAMLOPT  $<'
 	$(HIDE)$(OCAMLOPT) $(COND_OPTFLAGS) $(HACKMLI) $($(@:.cmx=_FORPACK)) -c $<
 
-%.cmx: %.ml
+%.cmx: %.ml %.cmi
 	$(SHOW)'OCAMLOPT  $<'
 	$(HIDE)$(OCAMLOPT) $(COND_OPTFLAGS) $(HACKMLI) -c $<
 
```

Edit: added camlp4, OCaml, OS versions.

**Comment by SkySkimmer** [comment]
This dependency should already be there either from ocamldep or https://github.com/coq/coq/blob/d501690a7d767d4a542867c5b6a65a722fa8c4c1/Makefile.build#L710-L729
What's the bug exactly?

**Comment by gares** [comment]
We also have ml only files, iirc, hence the rule cannot work

**Comment by madroach** [comment]
I changed the rule because of this error:
```
OCAMLOPT  clib/cObj.ml
File "clib/cObj.ml", line 1:
Error: Could not find the .cmi file for interface clib/cObj.mli.
gmake[1]: *** [Makefile.build:753: clib/cObj.cmx] Error 2
gmake[1]: Leaving directory '/usr/obj/pobj/coq-8.9.1/coq-8.9.1'
gmake: *** [Makefile:166: submake] Error 2
```
With the fix I proposed above the build continued until #10404.

> We also have ml only files, iirc, hence the rule cannot work

ocamlc can generate ``.cmi`` files from ``.ml``, too, can't it?

Oh, I forgot to mention my environment:
Coq 8.9.1
camlp5 https://github.com/camlp5/camlp5/pull/37
OCaml 4.08.0
OpenBSD 6.5-current

**Comment by ejgallego** [comment]
I guess the important difference here is bad make. If you need to compile on bad you can also try 8.10 beta and dune (see readme.dune.md)

**Comment by gares** [comment]
> I guess the important difference here is bad make

Hum, not sure, he seems to be using GNU Make.
Could you print the version of `gmake` ?

> ocamlc can generate `.cmi` files from `.ml`, too, can't it?

Yes but in a single step, that is you turn an .ml into a .cmx and .cmi, so making the .cmx depend on the .cmi only works if you compile both bytecode and opt, that may not be what you want.

> you can also try 8.10 beta and dune

Please, give this option a try, since we hope to drop the Makefile based build system and switch to dune.

**Comment by gares** [comment]
Also, the full log of a fresh build attempt would be better

**Comment by ejgallego** [comment]
Sorry I meant bsd make not bad make

**Comment by gares** [comment]
And, for the records, 8.10 does not need campl5, so it should be easier to compile in the first place.

**Comment by ejgallego** [comment]
Indeed make version is very important and missing from the report

**Comment by SkySkimmer** [comment]
>We also have ml only files, iirc, hence the rule cannot work
>ocamlc can generate .cmi files from .ml, too, can't it?

that's the hackmli stuff I linked...

**Comment by glondu** [comment]
I see the same error in Debian unstable, with ocaml 4.08.0 (from experimental), camlp5 7.08, coq 8.9.0, make 4.2.1.

[Full build log](https://github.com/coq/coq/files/3488318/coq.log)

There is no error in pure Debian unstable which has ocaml 4.05.0.

**Comment by SkySkimmer** [comment]
camlp5 is failing with `Error while loading "/usr/lib/ocaml/camlp5/pr_dump.cmo": The module `Pr_dump' is already loaded (either by the main program or a previously-dynlinked library).`
This prevents some ml files from being made, so make doesn't run ocamldep and fails later.

**Comment by garrigue** [comment]
I have open PR #10650 as a potential fix.
I'm testing in opam, where the fix would not need to wait for a release: https://github.com/ocaml/opam-repository/pull/14668
