### ISSUE TITLE
[question] Why is `variable_opacity` used in compute_head

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#10417]
Hi, does anyone know what the call to `variable_opacity` does in this code:

https://github.com/coq/coq/blob/623a431c293dcff42b4bc4dc3dc50c047a9ecbcc/pretyping/heads.ml#L36-L46

Shouldn't the opacity be stored elsewhere, not in the ad-hoc table in `Decls` which is only used for dumpglob otherwise?

**Comment by ppedrot** [comment]
Variable opacity doesn't mean much in general, I am afraid. Given that sections rely on the named context, section-local definitions are always implemented by means of let-bindings in the context, hence they're always transparent. The variable opacity status seems to be an ad-hoc way to remember that you finished a let with a Qed, but I wouldn't be too concerned about its semantics, it is barely used.

If anything, I would remove the three uses of `Decls.variable_opacity` from the code base and see what happens.

**Comment by ejgallego** [comment]
Indeed, I'm afraid this is useless code; I'm running a CI in my private gitlab to see what we get.

Note indeed that there is only this single use in the codebase, where do you see the others @ppedrot ?

Once I remove this I can remove `Decls` and `Decl_kind` in full so that was the motivation for this question.

I guess I'll submit the `Decls` PR later today as a draft so people can see what I mean.

**Comment by ppedrot** [comment]
This is also used in `Lemmas`. There is code trying to mimick the lack of body from a local definition by dropping it at proof start time, relying on this boolean.

**Comment by ejgallego** [comment]
Oh yes, sorry I missed it because my PR was moving this info to a place where Lemmas can still use it.

**Comment by ejgallego** [comment]
Removed from that part of the code.
