### ISSUE TITLE
Incomplete evars info when 'Printing Dependent Evars Line' enabled

### ISSUE THREAD

**Issue by hendriktews** [coq/coq#10420]
# Feature request

Please re-enable and extend the dependent evars line, such that it shows 

1. all not instantiated evars
2. all instantiated evars and for each of them the evars appearing in the instantiating term
3. the mapping between internal evar names and their printed representation
4. all the (open) evars apearing in the current goal

For the example proof script appended below, after `apply modpon.`, the dependent evar line should look similar to

    (dependent evars: ?X4 open, ?X5 using ?X11 ?X10, ?X10 using ?X11, ?X11 open
     this goal: ?X4, ?X11
     mapping: ?P : ?X4, ?Goal2 : ?X11)

Here line 1 (realizing point 1 and 2) is identical to the dependent evars line that is printed in Coq 8.4 till 8.9 and in versions before commit 6608f64f001f8f1a50b2dc41fefdf63c0b84b270. Since that commit the dependent evars line is always empty on the master branch, see also #10399.

Point 3 (realized by line 3) is a necessary enhancement because since 8.5 there is no way to connect the evars in the proofs with the identifiers appearing in the dependent evar line.

Instead of point 4 (realized by line 2) one could extract all matches for `\?[a-z0-9]+` from the goal text. But if it is not too much effort, an explicit list inside the dependent evars line seems more robust.

The example output above means that
- evars `?X4` and `?X11` are not instantiated
-`?X5` is instantiated with a term containing `?X11` and `?X10`
-`?X10` is instantiated with a term containing `?X11`
- the current goal contains `?X4` and `?X11`
- `?X4` is printed as `?P` and `?X11` as `?Goal2`

The dependent evars line should only be printed when the flag Printing Dependent Evars Line is on. It should be printed for the current goal and for the command `Show Goal 9 at <state>` from PR #10356.

**Note**  The dependent evars output appears only in coqtop (not CoqIDE).

# Background

If this feature request is granted, prooftree (the proof visualization program for Coq/Proof General) can support the following features.
- closed branches of the proof are shown in a different color, if they still depend on not yet instantiated evars
- the evar dialog shows the dependencies among evars and can highlight proof commands that introduced or instantiated a specific evar

These features were fully working for Coq 8.4 with a dependent evar line realizing points 1 and 2 that was implemented by Arnaud Spiwack in 2011. Since Coq 8.5, however, they are more or less broken, because or the missing link between different representations of the same evar.

# Example proof script

    Set Printing Dependent Evars Line.
    Lemma strange_imp_trans : 
      forall P Q R : Prop, (Q -> R) -> (P -> Q) -> (P -> Q) -> P -> R.
    Proof.
      auto.
    Qed.

    Lemma modpon : forall P Q : Prop, (P -> Q) /\ P -> Q.
    Proof.
      tauto.
    Qed.

    Section eex.
      Variables P1 P2 P3 P4 : Prop.
      Hypothesis p12 : P1 -> P2.
      Hypothesis p123 : (P1 -> P2) -> P3.
      Hypothesis p34 : P3 -> P4.

      Lemma p14 : P4.
      Proof.
        eapply strange_imp_trans. 
              apply modpon.
            intros H.
            split.
              eexact p34.
            apply p123.
            eexact H.
          intros H.
          split.
            trivial.
          apply p123.
          trivial.
        trivial.
      Qed.
    End eex.

**Comment by jfehrle** [comment]
Perhaps you would revise your bug description so the reader can get the idea **_in the first few lines_**?

-  Is this an enhancement or a regression or perhaps a combination?  (click on "Labels" to the right of the text and select one or more labels in the form "kind: XXX".)  If a regression, mention the last known good version (you say was implemented in 8.5, did it work in 8.6?  8.7?)  If a combination, be very clear about identifying the new parts.  Often it's better to file separate issues--bugs are more likely to get attention and sometimes (often?) the bug gets fixed while the enhancement isn't done at the same time, leaving the issue half-completed.

- Show the actual output and the expected output very close to the top, succinctly.  Include version numbers as appropriate.  Looks like master is incorrect.  Was 8.9 correct?

- The issue title could be better, e.g. "Incomplete evars info when 'Printing Dependent Evars Line' enabled."

> the dependent evars line, which is only shown with option -emacs and must be enabled with the flag Printing Dependent Evars Line.

I get the same behavior without `-emacs`.

> Proftree needs the following pieces of information for each proof goal:

Describe only the items that are missing.

Some of the other text would be better if written more succinctly--give enough for the reader to understand what change is requested and why it's needed without unneeded detail.  (Or at least move extra detail to the end and mark it as such).

**Comment by hendriktews** [comment]
> Perhaps you would revise your bug description

Updated. I hope I addressed all your points.

> click on "Labels" to the right of the text

"Labels" is not clickable - probably I don't have the necessary permissions.

> I get the same behavior without `-emacs`.

OK, didn't know that.

> Describe only the items that are missing.

With respect to master all items are missing. With respect to 8.9, only item 3 and 4 are missing.

**Comment by jfehrle** [comment]
That's a better description, thanks.

I take it that the minimum useful change is all of items 1-3 and that doing only, say, 1-2 is not helpful.

Restoring the output to what it was in 8.9 looks straightforward.

For your example

```
(dependent evars: ?X4 open, ?X5 using ?X11 ?X10, ?X10 using ?X11, ?X11 open
 this goal: ?X4, ?X11
 mapping: ?P : ?X4, ?Goal2 : ?X11)
```

Just to understand--you'll use the information for ?X5 and ?X10?  Will you display those names?  Would it work for you if Coq substituted ?P and ?Goal2 into the first line and omitted the third line?  With such a substitution, would you still need the second line?

I tried this with 8.4.  It says "Warning: There is no option Printing Dependent Evars Line.".  How did you get the info in 8.4?   (8.4 is available here: https://coq.inria.fr/distrib/, which has binaries for Windows, which I happen to use)

**Comment by jfehrle** [comment]
It's interesting to compare the dependent variables to "Show Existentials." in 8.9.  I see that 1 (P) and 5 (Goal2) are identical, also 2 (Goal) and 3 (Goal1) are identical.  I don't know if it's correct to suppose that ?X4 is 4 and ?X5 is 5--they don't match your example.

Would you post the output from 8.4 with "Show Existentials." and the equivalent of "Printing Dependent Evars Line"?

```
(dependent evars: ?X4 open, ?X5 using ?X11 ?X10 , ?X10 using ?X11 , ?X11 open,)

p14 < Show Existentials.
Existential 1 =
?P : [P1 : Prop
      P2 : Prop
      P3 : Prop
      P4 : Prop
      p12 : P1 -> P2
      p123 : (P1 -> P2) -> P3
      p34 : P3 -> P4 |- Prop] (shelved)
Existential 2 =
?Goal : [P1 : Prop
         P2 : Prop
         P3 : Prop
         P4 : Prop
         p12 : P1 -> P2
         p123 : (P1 -> P2) -> P3
         p34 : P3 -> P4 |- ?P -> (?Goal2 -> P4) /\ ?Goal2]
Existential 3 =
?Goal0 : [P1 : Prop
          P2 : Prop
          P3 : Prop
          P4 : Prop
          p12 : P1 -> P2
          p123 : (P1 -> P2) -> P3
          p34 : P3 -> P4 |- ?P -> (?Goal2 -> P4) /\ ?Goal2]
Existential 4 =
?Goal1 : [P1 : Prop
          P2 : Prop
          P3 : Prop
          P4 : Prop
          p12 : P1 -> P2
          p123 : (P1 -> P2) -> P3
          p34 : P3 -> P4 |- ?P]
Existential 5 =
?Goal2 : [P1 : Prop
          P2 : Prop
          P3 : Prop
          P4 : Prop
          p12 : P1 -> P2
          p123 : (P1 -> P2) -> P3
          p34 : P3 -> P4 |- Prop] (shelved)
```

**Comment by hendriktews** [comment]
> I take it that the minimum useful change is all of items 1-3 and that doing only, say, 1-2 is not helpful.

Yes.

> Restoring the output to what it was in 8.9 looks straightforward.

And this should give you 1.

> Just to understand--you'll use the information for ?X5 and ?X10? Will you display those names? Would it work for you if

Under the current circumstances yes, but not necessarily in principle - I am open for a discussion. The problem is that I need a unique identifier for an evar that does not change during the live time of a proof. In the current implementation, identifiers such as ?P or ?Goal2 may denote different evars in different states in one proof. I have an example somewhere on my disk.

>  With such a substitution, would you still need the second line?

Yes, because the second line tells me in which state I should request an updated printout of the goal when some of its evars have been instantiated.

> I tried this with 8.4. It says "Warning: There is no option

Please try coqtop -emacs.

**Comment by jfehrle** [comment]
> I need a unique identifier for an evar that does not change during the live time of a proof.

A common way to handle that is to qualify non-unique identifiers in your GUI display with the stateid. 

```
 this goal: ?X4, ?X11
 mapping: ?P : ?X4, ?Goal2 : ?X11)
```

When would these lines have different sets of `?X*`?  Could they be a single line?

Also, I think you'd be better off with a more obvious delimiter between the 3 lines, such as `;`.  Long lines may be split into multiple output lines.

**Comment by hendriktews** [comment]
> Would you post the output from 8.4 with "Show Existentials." and the equivalent of "Printing Dependent Evars Line"?

IIRC, before the Printing Dependent Evars Line flag, the evars
line was printed when the -emacs option was present. Here is the
output of Coq 8.4pl6 after `apply modpon`

    <prompt>p14 < 17 |p14| 2 < </prompt>          apply modpon.
    3 subgoals, subgoal 1 (ID 26)

      P1 : Prop
      P2 : Prop
      P3 : Prop
      P4 : Prop
      p12 : P1 -> P2
      p123 : (P1 -> P2) -> P3
      p34 : P3 -> P4
      ============================
       ?23 -> (?30 -> P4) /\ ?30

    subgoal 2 (ID 27) is:
     ?23 -> (?30 -> P4) /\ ?30
    subgoal 3 (ID 28) is:
     ?23

    (dependent evars: ?23 open, ?24 using ?30 ?29 , ?29 using ?30 , ?30 open,)

    <prompt>p14 < 18 |p14| 3 < </prompt>

**Comment by hendriktews** [comment]
In my answer from this morning, with "Under the current
circumstances..." I only answered the your question

> Would it work for you if Coq substituted ?P and ?Goal2...

For your question

> Just to understand--you'll use the information for ?X5 and ?X10? Will you display those names?

I answer now: Yes and yes. If you could simply try prooftree with Coq 8.4, you would see. After `apply modpon` it looks like

![p14](https://user-images.githubusercontent.com/16718397/60687390-a4545880-9eae-11e9-996e-e2e6c796e60d.png)

The color in the first branch shows that some goals in this branch depend on open existentials that have been introduced on that branch. You can also open the evar dialog, looking like

![p14-evar](https://user-images.githubusercontent.com/16718397/60687569-9c48e880-9eaf-11e9-8ddc-c641ec72e77d.png)

When you have a big proof, where you somewhere forgot to instantiate an evar, this dialog can directly show the proof command that introduced that evar (using the mark button).

**Comment by hendriktews** [comment]
... and you can also display the last sequent in the closed branch:

![p14-sequent-2](https://user-images.githubusercontent.com/16718397/60687776-f302f200-9eb0-11e9-9f33-607087a5faaa.png)

If you press the back button there, you see

![p14-sequent-2-back](https://user-images.githubusercontent.com/16718397/60687809-3a897e00-9eb1-11e9-9974-733fb96dda30.png)

This is the state before `apply modpon`. In order to gather all these different appearances of the proof goal, I need to issues Show Goal commands for older proof goals (this is now nicely solved with #10356). In order to issue appropriate Show Goal commands, I need to know which open evars appear in a proof goal and I need an indication when some of them get instantiated. For this I need evar identifiers from Coq that are unique during a proof.

**Comment by hendriktews** [comment]
> I see that 1 (P) and 5 (Goal2) are identical

Yes, because my example is a bit silly.

> I don't know if it's correct to suppose that ?X4 is 4 and ?X5 is 5--they don't match your example.

I don't know either - without the mapping from internal to external names of evars, it is difficult to say. ;-) But seriously, I might have mixed something up.

**Comment by hendriktews** [comment]
> A common way to handle that is to qualify non-unique identifiers in your GUI display with the stateid.

I believe there is a misunderstanding: I need unique evar identifiers from Coq in the dependent evar line. Otherwise its impossible to process the information in that line in a reliably way.

>  this goal: ?X4, ?X11
>  mapping: ?P : ?X4, ?Goal2 : ?X11)
> ```
> 
> When would these lines have different sets of `?X*`? 

The mapping line should print the external (sometimes changing identifiers) for *all* open existential variables in the state for which this is printed. Therefore, the X'es after `this goal` are always a subset of the X'es in mapping.

If, after `apply modpon`, you switch to goal 3, you see that this goal only contains one existential variable. Therefore, for this goal the sets are different.

> Could they be a single line?

I don't understand this question. As long as it is easy to parse, the format of the information can be arbitrary. 

> Also, I think you'd be better off with a more obvious delimiter between the 3 lines, such as `;`.

Sure. It would be nice if the output can be parsed with a few invocations of scanf.

> Long lines may be split into multiple output lines.

This was not the case so far for dependent evar lines. The syntax example that I gave assume that there are no automatic line splitting for dependent evar lines.

**Comment by jfehrle** [comment]
Alas, I'm not able to run prooftree on my system.  I run emacs/PG using Windows Substytem for Linux, which only supports character based output.  No graphics.

Is this right: the goal line should show all (and only) the existential variables visible in the current goal?  In the example, that would be ?P and ?Goal2.

> The mapping line should print the external (sometimes changing identifiers) for all open existential variables in the state for which this is printed.

For the example, "Show Existentials" shows 5 evars named ?P, ?Goal, ?Goal0, ?Goal1 and ?Goal2.  You want all of these to be printed, right?

**Comment by jfehrle** [comment]
Hendrik, try https://github.com/coq/coq/pull/10483.

**Comment by hendriktews** [comment]
> Is this right: the goal line should show all (and only) the existential variables visible in the current goal? In the example, that would be ?P and ?Goal2.

Do you mean the line with `this goal`, realizing the feature point 4? In case yes, I answer yes. Actually, I would say it should show precisely the existential variables visible in the goal that just has been printed. The difference comes with commands `Show 2` or `Show Goal X at Y`: For such a command, the dependent evar line printed below the goal should show precisely the evars visible in the just printed goal. For the goal printout after a proof command, the dependent evar info should contain in the `this goal` line` precisely the evars contained in the current goal.

> For the example, "Show Existentials" shows 5 evars named ?P, ?Goal, ?Goal0, ?Goal1 and ?Goal2. You want all of these to be printed, right?

The open (i.e., not yet instantiated) evars would be sufficient. If it is easier to print all, you can also print all and I filter out the instantiated ones. I will try tomorrow what that means for the example.

**Comment by jfehrle** [comment]
> Do you mean the line with `this goal`, realizing the feature point 4?

Yes.

> `Show 2` or `Show Goal X at Y`.

At the moment neither one of them shows the dependent variable info.

> The open (i.e., not yet instantiated) evars would be sufficient.

Like this since ?X7, ?X8 and ?X9 don't appear on the first line?:

```
(dependent evars: ?X4 open, ?X5 using ?X10 ?X11, ?X10 using ?X11, ?X11 open;
mapping: ?X4 : ?P, ?X11 : ?Goal2)
```

and not like this:

```
(dependent evars: ?X4 open, ?X5 using ?X10 ?X11, ?X10 using ?X11, ?X11 open;
mapping: ?X4 : ?P, ?X7 : ?Goal, ?X8 : ?Goal0, ?X9 : ?Goal1, ?X11 : ?Goal2)
```

But let's try to keep this as a fairly general feature that another tool could use--not make it totally specific to prooftree.

**Comment by hendriktews** [comment]
> For the example, "Show Existentials" shows 5 evars named ?P, ?Goal, ?Goal0, ?Goal1 and ?Goal2.

For our discussion, I would suggest to distinguish proper existential variables from open proof goals (I know they have the same representation internally, but for an average Coq user, there is quite a difference). Here only ?P and ?Goals2 are proper existential variables, ?Goal, ?Goal0 and ?Goal1 are the 3 open subgoals after `apply modpon`.

> You want all of these to be printed, right?

I would need only the proper existential variables, that is, ?P and ?Goals2. I don't mind to have the open goals among them, as long as I can easily filter them out (which seems to be the case now, because the open goals do not appear in the first line (which is prefixed with `dependent evars:`).

> > `Show 2` or `Show Goal X at Y`.
> 
> At the moment neither one of them shows the dependent variable info.

Having the dependent variable information for `Show Goal X at Y` is actually needed. For `Show X` I don't care and Proof General users won't care either, because Proof General cuts off the dependent variable information in its displays.

> > The open (i.e., not yet instantiated) evars would be sufficient.

I wrote this yesterday to make clear, that I don't need an entry in the mapping line for proper existential variables that have been instantiated. I only realize now that ?Goal, ?Goal0 and ?Goal1 are open goals.

> Like this since ?X7, ?X8 and ?X9 don't appear on the first line?:
> 
> ```
> (dependent evars: ?X4 open, ?X5 using ?X10 ?X11, ?X10 using ?X11, ?X11 open;
> mapping: ?X4 : ?P, ?X11 : ?Goal2)
> ```

Yes, this is my preferred solution.

> and not like this:
> 
> ```
> (dependent evars: ?X4 open, ?X5 using ?X10 ?X11, ?X10 using ?X11, ?X11 open;
> mapping: ?X4 : ?P, ?X7 : ?Goal, ?X8 : ?Goal0, ?X9 : ?Goal1, ?X11 : ?Goal2)
> ```

Right, not like this. But as I wrote before, this variant is also fine, because here I can easily filter the open goals out.

> But let's try to keep this as a fairly general feature that another tool could use--not make it totally specific to prooftree.

Sure. I am only stating the requirements for prooftree here. As long as I can infer the required information from the output, everything is fine.

Looking again at 

> ```
> (dependent evars: ?X4 open, ?X5 using ?X10 ?X11, ?X10 using ?X11, ?X11 open;
> mapping: ?X4 : ?P, ?X11 : ?Goal2)
> ```

it appear that one could coalesce the two lines, for instance

> ```
> (dependent evars: ?X4 open : ?P, ?X5 using ?X10 ?X11, ?X10 using ?X11, ?X11 open : ?Goal2)
> ```

But two lines are also fine - just choose what is simpler to implement.

**Comment by hendriktews** [comment]
I quickly looked at PR #10489. This looks quite good already, it addresses item 1-3. Only the point

> The dependent evars line [...] should be printed [...] for the command `Show Goal 9 at <state>` from PR #10356.

from the original feature request is missing.

**Comment by jfehrle** [comment]
I updated #10489.

**Comment by jfehrle** [comment]
Do you need the `?X5 using ?X10 ?X11, ?X10 using ?X11` part info?

**Comment by hendriktews** [comment]
> Do you need the `?X5 using ?X10 ?X11, ?X10 using ?X11` part info?

Yes, this is item 2.
