### ISSUE TITLE
CoqIDE links to old documentation

### ISSUE THREAD

**Issue by HJvT** [coq/coq#10432]
#### Description of the problem
Selecting _Help > Browse Coq Manual_ brings me at:
https://coq.inria.fr/distrib/8.5beta2/refman/
Selecting _Help > Browse Coq Library_ leads to:
https://coq.inria.fr/distrib/8.5beta2/stdlib/

#### Coq Version
8.9.1

**Comment by vbgl** [comment]
Thanks for your report. This is a duplicate of #8749.
