### ISSUE TITLE
[CI] Unimath fails with out of memory

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10437]
In this CI job: <https://gitlab.com/coq/coq/-/jobs/240732105> unimath failed with an out of memory:
```
UniMath/CategoryTheory/Bicategories/Transformations/PseudoTransformation (real: 19.08, user: 6.02, sys: 0.41, mem: 537976 ko)
COQC UniMath/CategoryTheory/Bicategories/DisplayedBicats/Examples/Algebras.v
File "./UniMath/CategoryTheory/Bicategories/DisplayedBicats/Examples/Algebras.v", line 1145, characters 0-12:
Error: Out of memory.

Command exited with non-zero status 1
```
For the time being the main purpose of this issue is to *track statistics on this failure*.

Btw.: do we have something like a "spurious failure" statistics tracker?

**Comment by ejgallego** [comment]
@MSoegtropIMC this is due to gitlab having provisioning some workers with a bit less memory than what we assume. We cannot do a lot, as we get a huge number of workers from them very generously, but at some point we could tag some jobs "highmem" and have our own high-mem workers.

By the way, I thin gitlab used to have a `4Gb` worker tag.

**Comment by ejgallego** [comment]
Not seeing this very often.

**Comment by Zimmi48** [comment]
According to @vbgl it continues to happen frequently in v8.10.

**Comment by vbgl** [comment]
Here is a example failing job: <https://gitlab.com/coq/coq/-/jobs/258893965>.

> COQC UniMath/CategoryTheory/Bicategories/DisplayedBicats/Examples/Algebras.v
Fatal error: out of memory.
Command exited with non-zero status 2
UniMath/CategoryTheory/Bicategories/DisplayedBicats/Examples/Algebras (real: 745.43, user: 32.84, sys: 1.47, mem: 594876 ko)
build/CoqMakefile.make:658: recipe for target 'UniMath/CategoryTheory/Bicategories/DisplayedBicats/Examples/Algebras.vo' failed
make[3]: *** [UniMath/CategoryTheory/Bicategories/DisplayedBicats/Examples/Algebras.vo] Error 2

**Comment by ppedrot** [comment]
This was probably mitigated quite a lot by #10818 in Coq 8.11. Is this still happening?

**Comment by ejgallego** [comment]
I think we can indeed close this, didn't see it in a while; failure was likely due to Gitlab assigning low-memory workers.

**Comment by MSoegtropIMC** [comment]
@ejgallego : since I recently made a python script to gather component failure statistics from Gitlab: do you think it would make sense to create a failure statistics over time plot? If so what would be a good time interval? Weekly?

**Comment by Zimmi48** [comment]
That would be awesome. Where would you post it?

**Comment by MSoegtropIMC** [comment]
I would first put it into #10846 but I guess it would make sense to run this script in CI once a day, create a PNG and link this from the Readme.md file. If the script runs on the INRIA runners, I could keep a cache of the old data (it takes hours to pull this from gitlab cause of API bandwidth limitations to 10 calls per second).
