### ISSUE TITLE
.mlg grammars: Why aren't these equivalent?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10449]
I expected that replacing this code in `g_ltac.mlg`:

```
      [ b = match_key; IDENT "goal"; "with"; mrl = match_context_list; "end" ->
          { TacMatchGoal (b,false,mrl) }
      | b = match_key; IDENT "reverse"; IDENT "goal"; "with";
        mrl = match_context_list; "end" ->
          { TacMatchGoal (b,true,mrl) }
```

with the following would give identical behavior:

```
      [ b = match_key; rev = OPT "reverse"; IDENT "goal"; "with";
        mrl = match_context_list; "end" ->
          { TacMatchGoal (b,rev <> None,mrl) }
```

However, when I try it, I get parse errors later on, such as:

```
File ".\theories/Init/Tauto.v", line 9, characters 4-6:
Error: Syntax error: [match_rule] expected after '|' (in [match_list]).
```

The error is on the third line:

```
Local Ltac not_dep_intros :=
  repeat match goal with
  | |- (forall (_: ?X1), ?X2) => intro
  | |- (Coq.Init.Logic.not _) => unfold Coq.Init.Logic.not at 1; intro
  end.
```

Why is that?  Is it a bug or a feature?

**Comment by gares** [comment]
You turned "reverse" into a keyword, you forgot IDENT.

**Comment by SkySkimmer** [comment]
>You turned "reverse" into a keyword, you forgot IDENT.

I don't think that's why there's an error, considering reverse doesn't appear in the example.

**Comment by jfehrle** [comment]
I get the same error substituting `OPT [IDENT "reverse" -> { 1 } ]`.  And for `OPT (IDENT "reverse")`, too.  So it must be something else.

**Comment by ppedrot** [comment]
Probably a problem with rule factorization with the next rule that also starts with `match_key`.

**Comment by jfehrle** [comment]
OK, then I guess it's a bug.

**Comment by SkySkimmer** [comment]
We're asking too much from the parser. It has to decide what comes after `match` is a match goal or a regular match, and this is ambiguous.
~~~coq
Goal True.
Proof.
  match goal with _ => idtac end. (* is it a match goal, or match on an unbound variable "goal"? *)
~~~

**Comment by jfehrle** [comment]
Right, thanks.  Too accustomed to working with parsers in which "goal" would be defined as a token.

**Comment by gares** [comment]
I'm all for making it a proper keyword :-)

**Comment by ppedrot** [comment]
Please don't. That would prevent writing the unqualified name for `Ltac2.Control.goal` in Ltac2.

**Comment by gares** [comment]
I guess we may discuss the choice of making Ltac2's grammar a sub grammar of the Coq one another time ;-)
Anyway, thanks for the heads up.

**Comment by ppedrot** [comment]
This can probably be closed.
