### ISSUE TITLE
coqc -time no longer reports Qed timings

### ISSUE THREAD

**Issue by tchajed** [coq/coq#10452]
#### Description of the problem

`coqc -time` no longer reports anything for the Qed vernacular:

test.v:
```
Theorem x : True.
Proof.
  exact I.
Qed.
```

current behavior:
```
$ coqc -time test.v
Chars 0 - 17 [Theorem~x~:~True.] 0. secs (0.u,0.s)
Chars 18 - 24 [Proof.] 0. secs (0.u,0.s)
Chars 27 - 35 [exact~I.] 0. secs (0.u,0.s)
```

I'm using `coqc -time` to keep track of how much time we're spending processing Qeds.

#### Coq Version

This bug was introduced in d4aeb1ef92a9fc35b242a0d91488de60c24d7bbb.

**Comment by tchajed** [comment]
@ejgallego looks like this was your commit, could you take a look?

**Comment by ejgallego** [comment]
I will prepare a fix soon, unfortunately to properly handle the control attributes for this case requires some tedious refactoring.
