### ISSUE TITLE
[ci] Windows workers are broken with "error setting certificate verify locations:"

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#10463]
Windows workers have been broken for a while, with message:
```
HEAD is now at a4f6189978 Merge PR #10443: Fix dev/doc/README.md by removing redundant, outdated info.
fatal: unable to access 'https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/coq/coq.git/': error setting certificate verify locations:
  CAfile: C:\Gitlab-Runner\builds\cd8bf1fc\0\coq\coq.tmp\CI_SERVER_TLS_CA_FILE
  CApath: none
Checking out 8ad71627 as pr-10446...
fatal: reference is not a tree: 8ad71627e8c4d8bfab4c6c62e3e4a6e8a9dcaa16
```
There are quite a few reports on Gitlab's CI regarding this failure, it seems the main workaround is to disable CA validation on the config file, by adding
```
environment = ["GIT_SSL_NO_VERIFY=true"]
```
to runner's `config.toml` file.

**Comment by SkySkimmer** [comment]
Do we know what issues to watch on gitlab to know when this will be resolved? Should we do the config manip (and if yes who can do it)?

**Comment by ejgallego** [comment]
Actually the workers seem to be working now, I wonder if that's due to action of someone in the team or due to fixes on Gitlab.
