### ISSUE TITLE
Grammar productions in Ltac2 would change Ltac1, etc.

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10460]
#### Description of the problem

I notice that the Ltac2 plugin adds productions for many existing nonterminals, some of which add to the syntax for Ltac1.  For example these 2 nonterminals are used in Ltac1.  The productions with "tac2expr6" are from Ltac2.  Other added productions are functionally identical to the main grammar.  (Note that `tactic_expr5` = `tactic_expr LEVEL 5`, etc.)

Seems like some of these should get new names in Ltac2 and others could be removed.

```
tactic_then_last: [
| "|" LIST0 ( OPT tactic_expr5 ) SEP "|" 
| 
| "|" LIST0 ( OPT tac2expr6 ) SEP "|" 
]

tactic_then_gen: [
| tactic_expr5 "|" tactic_then_gen 
| tactic_expr5 ".." tactic_then_last 
| ".." tactic_then_last 
| tactic_expr5 
| "|" tactic_then_gen 
| 
| tac2expr6 "|" tactic_then_gen 
| tac2expr6 ".." tactic_then_last 
| tac2expr6 
]
```

```
Symbols with multiple definition points in *.mlg:
  as_ipat:  g_ltac2.mlg g_tactic.mlg
  as_name:  g_ltac2.mlg g_tactic.mlg
  as_or_and_ipat:  g_ltac2.mlg g_tactic.mlg
  binder:  g_ltac2.mlg g_constr.mlg
  bindings:  g_ltac2.mlg g_tactic.mlg
  branches:  g_ltac2.mlg g_constr.mlg
  by_tactic:  g_ltac2.mlg g_tactic.mlg
  concl_occ:  g_ltac2.mlg g_tactic.mlg
  constr_with_bindings:  g_ltac2.mlg g_tactic.mlg
  conversion:  g_ltac2.mlg g_tactic.mlg
  delta_flag:  g_ltac2.mlg g_tactic.mlg
  destruction_arg:  g_ltac2.mlg g_tactic.mlg
  eqn_ipat:  g_ltac2.mlg g_tactic.mlg
  equality_intropattern:  g_ltac2.mlg g_tactic.mlg
  hypident:  g_ltac2.mlg ssrvernac.mlg g_tactic.mlg
  hypident_occ:  g_ltac2.mlg g_tactic.mlg
  in_clause:  g_ltac2.mlg g_tactic.mlg extraargs.mlg
  induction_clause:  g_ltac2.mlg g_tactic.mlg
  input_fun:  g_ltac2.mlg g_ltac.mlg
  intropatterns:  g_ltac2.mlg g_tactic.mlg
  let_clause:  g_ltac2.mlg g_ltac.mlg
  lident:  g_ltac2.mlg g_ltac2.mlg
  match_list:  g_ltac2.mlg g_ltac.mlg
  match_pattern:  g_ltac2.mlg g_ltac.mlg
  match_rule:  g_ltac2.mlg g_ltac.mlg
  naming_intropattern:  g_ltac2.mlg g_tactic.mlg
  occs:  g_ltac2.mlg g_tactic.mlg
  occs_nums:  g_ltac2.mlg g_tactic.mlg
  or_and_intropattern:  g_ltac2.mlg g_tactic.mlg
  orient:  g_ltac2.mlg g_tactic.mlg extraargs.mlg
  oriented_rewriter:  g_ltac2.mlg g_tactic.mlg
  rewriter:  g_ltac2.mlg g_tactic.mlg
  simple_binding:  g_ltac2.mlg g_tactic.mlg
  simple_intropattern:  g_ltac2.mlg g_tactic.mlg
  simple_intropattern_closed:  g_ltac2.mlg g_tactic.mlg
  strategy_flag:  g_ltac2.mlg g_tactic.mlg
  tactic_atom:  g_ltac2.mlg g_ltac.mlg
  tactic_then_gen:  g_ltac2.mlg g_ltac.mlg
  tactic_then_last:  g_ltac2.mlg g_ltac.mlg
  with_bindings:  g_ltac2.mlg g_tactic.mlg
```

**Comment by ppedrot** [comment]
I already mentioned that somewhere else, but these entries are *not* the same. They share part of the structure with Ltac1 by design, but some of the leaves (and thus what they parse in the end) are different. Thus, it is very unlikely that there are entries to be removed, at best they should all be renamed. I might have introduced some by mistake, but I highly doubt that there is more than a couple (if any). 

The few actual Ltac1 entries that are actually modified are done so willingly, they're extensions point for Ltac2 in Ltac1.

**Comment by ppedrot** [comment]
Thinking of which, you tool should take into account the GLOBAL modifier for grammars, it would prevent this kind of false positive.

**Comment by jfehrle** [comment]
I'm sure you'll handle all this sensibly at the right time.

We plan to include most or all of the grammar in the documentation.  For that, we really want a unique name for each nonterminal, whether by renaming local nonterminals or (ugh) inventing some kind of qualified nonterminal name.  Readers will be confused if there are multiple definitions for a nonterminal in different places in the document.  Non-unique names won't work for grammar hyperlinking, either, which operates across the entire document.  Also developers might get confused by the reused names from time to time.  So I think renaming is the best approach.  If you like, I could create a PR at some point to do the renaming.

Do you think you can wrap up your review of `doc_grammar` sometime soon?  IIRC you said it was almost ready several weeks ago.  (Subject, of course, to further tweaking of the tool as we start to apply it.)

**Comment by gares** [comment]
I'd opt for "qualified" non terminals. I had a similar issue with the grammar of ssr, especially the tactic index, and I think that "rewrite (ssreflect)" was a decent choice to disambiguate. In particular if the conflict disappears, eg ltac1 gets pulled out, then the "qualification" can be dropped as well.

Maybe guessing a good "qualification" in general is hard, but hardwiring in the tools that nonterminals found plugins/ltac2 should have a "(ltac2)" qualification is not too hard.

**Comment by jfehrle** [comment]
"rewrite (ssreflect)" is the name shown in the tactics index.  We can do something like that for ltac2-specific tactics (if there are any).  I agree on that.

But I was referring to duplicated local nonterminal names which we would show in `productionlist::` in the doc.  I think it's simpler and better to rename, for example, the local `ipat` nonterminal in the Ltac2 grammar to `ltac2_ipat` in the source code rather than adding code to doc_grammar to do a similar translation.

**Comment by ppedrot** [comment]
I think that the original bug report was invalid. If you have specific concerns about the autogenerated grammar doc, please open a new issue.
