### ISSUE TITLE
Building math compnents with HoTT

### ISSUE THREAD

**Issue by andreaslyn** [coq/coq#10475]
I am attempting to build math components with HoTT, see https://github.com/HoTT/HoTT/issues/1048. Currently I am replacing all occurrences of `Prop` with `Type` in math components.

To build math components without changing its code, would it make sens to add a `-prop-is-type` flag to Coq, which just syntactically replaces occurrences of `Prop` with `Type`? or is there a better solution?

**Comment by SkySkimmer** [comment]
If you want to hack something then just run sed on your files.

**Comment by andreaslyn** [comment]
> If you want to hack something then just run sed on your files.

That is basically what I am doing at the moment. I am wondering whether there is a better solution, which avoids having a different version of math components for HoTT.

**Comment by gares** [comment]
I would try `Notation Prop := Type`, but beware there are a few places, IIRC, where impredicativity is actually sued.

**Comment by andreaslyn** [comment]
`Notation Prop := Type` was my first attempt, but that gives a syntax error.

**Comment by SkySkimmer** [comment]
Try `Notation "'Prop'" := Type.` instead

**Comment by andreaslyn** [comment]
> Notation "'Prop'" := Type.

It works, nice trick!
