### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by fblanqui** [coq/coq#10477]
#### Description of the problem

In https://coq.inria.fr/distrib/current/refman/language/cic.html#reduction-rule, the example is not printed correctly:

{\def\plus{\mathsf{plus}} \def\tri{\triangleright_\iota}
\plus (S (S O)) (S O)\tri\tri\triS (\plus (S O) (S O))S (S (\plus O (S O)))S (S (S O))
}

**Comment by Zimmi48** [comment]
This has been fixed in 8.9.1 (see https://coq.github.io/doc/V8.9.1/refman/language/cic.html#reduction-rule). Unfortunately, the default version of the refman has not been updated since the 8.9.1 release (see coq/www#118). Ping @maximedenes.
