### ISSUE TITLE
`Export` in a module `foo` has effect in modules that do not import `foo`

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#10474]
The following example succeeds:

A.v
```coq
Require B.
Import B.
Check b.
```
B.v
```coq
Require C.
Import C.
```
C.v
```coq
Require D.
Export D.
```
D.v
```coq
Definition b := true.
```

Is this expected?

About `Export`, the manual says:

> When the module containing the command Export qualid is imported, qualid is imported as well.

but here, `A` does not import `C`.

**Comment by ppedrot** [comment]
FTR, it looks like a bug to me, but `Export` is full of quirks, and its semantics is ill-defined if you think a bit about it.

**Comment by maximedenes** [comment]
> FTR, it looks like a bug to me, but `Export` is full of quirks, and its semantics is ill-defined if you think a bit about it.

Btw, it seems to behave differently when these modules are not libraries.

**Comment by ppedrot** [comment]
> Btw, it seems to behave differently when these modules are not libraries.

There is the infamous library optimization that makes `Require Import` not behaving as `Require` + `Import`, it might be the same one kicking it here.

**Comment by maximedenes** [comment]
> There is the infamous library optimization that makes `Require Import` not behaving as `Require` + `Import`, it might be the same one kicking it here.

I think you are mixing two topics. What makes `Require Import` not behave the same as `Require` + `Import` is just the libobject definition(s).

The library "optimization" (aka ad-hoc change of semantics) is what makes `Import`/`Export` behave differently for modules and libraries. And you are right that it seems to be the one responsible for this.

**Comment by ppedrot** [comment]
@maximedenes I think I remember that the optimization was also causing mayhem in the `Require` part, atop of the already broken libobject implementation, but I might be wrong. In any case, this optimization is hard to remove, I remember trying it and abandoning the idea after an unsuccessful attempt at porting the stdlib.

**Comment by SkySkimmer** [comment]
I also tried, it led to 93ecb0426dafc2654853eba2643ab0c66c3a09f4 as it was causing some problem but I didn't try again after that.
