### ISSUE TITLE
`Export` sometimes has no effect

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#10480]
Consider the following example:

A.v
```coq
Require Import B.
Require Import C.
Eval compute in b.
```
B.v
```coq
Require Export D.
Definition b := true.
```
C.v
```coq
Require Export D.
```
D.v
```coq
Definition b := false.
```

In `A.v`, Coq incorrectly reports that `b` evaluates to `true`. That is, the `Require Import C` command did not have any effect.

Interestingly, merging the two `Require`s into `Require Import B C` fixes the problem.

This bug is fixed by #10476, but some libraries seem to rely on it.

**Comment by silene** [comment]
Somehow, this sounds like 9347618755eed17d683f590f8bd9c47aacfcfa17, so @herbelin might have a clue on what is happening.

**Comment by maximedenes** [comment]
The commit you mention extends an optimization that already existed. That optimization is indeed very related to this bug, since removing it fixes the problem.

However, I don't understand how this "optimization" could ever be sound. It would at least require classifying the commutativity of `Import` effects.

**Comment by silene** [comment]
Why commutativity? Only idempotence matters. From an external point of view, whether a module performs `Export A. Definition a. Export A` or `Definition a. Export A` should only have an impact on performances.

**Comment by SkySkimmer** [comment]
~~~coq
Module A.
Definition x := 1.
End A.
Module B.
Definition x := 1. 
End B.
Import A B. (* not the same as Import B A *)
~~~

**Comment by silene** [comment]
Yes, that is why I said that commutativity was not the correct property to look at; we all know that almost no vernacular command in Coq satisfies commutativity. My point was that `Import A B C D A B C` is indistinguishable from `Import D A B C`. (If there is a difference, I would like to know about it.)

**Comment by maximedenes** [comment]
> (If there is a difference, I would like to know about it.)

In `Import D A B C`, `A` can be a submodule of `D`. So the two `A`s are not necessarily the same, and cannot (always) be merged.

**Comment by SkySkimmer** [comment]
I guess that also means `Import A A.` is not the same as `Import A.`
But it might be if it's a Require Import (?)

**Comment by silene** [comment]
> In `Import D A B C`, A can be a submodule of D.

Really? That is new to me. I always believed that symbols were resolved before doing the actual import.

That said, that does not matter much here, since the module symbols are fully qualified inside `.vo` files, right?

**Comment by herbelin** [comment]
> Somehow, this sounds like 9347618, so @herbelin might have a clue on what is happening.

No particular clue.

As a general statement, that "Libraries be handled like other modules" looks good.
