### ISSUE TITLE
CoqIDE fails to parse a sentence

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#10481]
CoqIDE does not recognize the following sentence:

```coq
Ltac foo := let t := constr:((True) -> True) in exact t.
```

To reproduce the problem, paste this line in CoqIDE and try to play the script. Nothing is sent to Coq.

**Comment by ppedrot** [comment]
Probably an avatar of #10394.

**Comment by gares** [comment]
@vbgl this is a critical bug, I believe the safest is to revert in v8.10 #10374.

**Comment by vbgl** [comment]
This has been addressed in branch v8.10 by reverting #10394. I’ve thus postponed the milestone.

**Comment by ppedrot** [comment]
@gares should we also revert #10394 in 8.11 then?

**Comment by gares** [comment]
Yes, revert it in master as well

**Comment by maximedenes** [comment]
@gares was the revert in master done? Should we close this issue?

**Comment by gares** [comment]
I believe so

**Comment by Zimmi48** [comment]
Apparently, the revert was never done in master, leading to a regression in 8.12 ☹️
