### ISSUE TITLE
Feature request: mode to not remove parentheses

### ISSUE THREAD

**Issue by CarlsenSmart** [coq/coq#10492]
#### Description of the problem

It would be nice if I could see every parentheses in Coq to have a clear overview of the syntax.

So instead of 
`S n * (m * p) = S n * m * p`

It would show 
`S n * (m * p) = (S n * m) * p`

- Would help a lot, thanks.

#### Coq Version

The Coq Proof Assistant, version 8.6 (October 2017)
compiled on Oct 28 2017 14:23:55 with OCaml 4.05.0

- From Ubuntu repository.

**Comment by Zimmi48** [comment]
This is a frequent request from beginners. Solving this would amount to having a command to temporarily transform a "left associativity" or "right associativity" notation into a "no associativity" notation.

FTR @CarlsenSmart a non-fully-satisfying solution would be to display your terms without notations (CoqIDE option in the View menu or `Unset Printing Notations` in other editors).

**Comment by CarlsenSmart** [comment]
I don't know how to temporarily make it "no associativity", since I get an error that it is already defined.
Can you maybe help me how to do this ? :)

**Comment by Zimmi48** [comment]
The first part of my comment was not a suggestion to you, but instead a hint on how to solve this request by whoever wants to do it.

Only the second part of my comment was a suggestion on how to workaround this problem in the meantime.

**Comment by CarlsenSmart** [comment]
Ahh.. okay :) 

I think things becomes too messy with `Unset Printing Notations` for me,
but thanks for the suggestion ! :)

**Comment by Zimmi48** [comment]
#5591 is related: disabling a single notation would be less messy.

**Comment by rhz** [comment]
I would also like to see this feature implemented. Perhaps something like `Set Printing Parentheses`. Would something like that be too difficult to implement?

Another option would be to have a way to redefine notations. That way I could redefine a particular notation with `no associativity`. Is there any reason why notations are not redefinable?

**Comment by eponier** [comment]
`Set Printing Parentheses` is now available in coq 8.12.
