### ISSUE TITLE
Feature request: apply rewrite tactic to either left side or right side of equation

### ISSUE THREAD

**Issue by CarlsenSmart** [coq/coq#10493]
#### Description of the problem

Would really help if I had the possibility to use `rewrite` only to one side of the equation.

If for example, I have the associative rule for plus i.e. 
`a + (b + c) = (a + b) + c`

And I only want to apply this rule on the right side of some equation that I am trying to prove.

#### Coq Version

The Coq Proof Assistant, version 8.6 (October 2017)
compiled on Oct 28 2017 14:23:55 with OCaml 4.05.0

- From the Ubuntu repository

**Comment by SkySkimmer** [comment]
Does "rewrite at" not work?

Gaëtan Gilbert

**Comment by CarlsenSmart** [comment]
Can't really make it work :(

I have this goal:
```
1 subgoal
n, m, p, q : nat
______________________________________(1/1)
m + n + (p + q) = n + m + (p + q)
```
and when I use `rewrite plus_comm ` (commutative)  it only applies to the left side. 
I also tried to use the `rewrite plus_comm at` as you mentioned, but could not figure out how to only 
apply it to the right side or to a single term. 

Do you have any suggestions to only use `rewrite plus_comm` to a specific term or only the right side ?

The whole theorem is the following:
```
Theorem plus_rearrange : forall n m p q : nat,
  (n + m) + (p + q) = (m + n) + (p + q).
```

**Comment by SkySkimmer** [comment]
For that you could just do `rewrite (plus_comm n m)`

**Comment by CarlsenSmart** [comment]
Okay, that was actually a nice command : ) 
I guess that I can just use `symmetry` if I want to apply this to the right side at some point,
but would rather not flip things every time that I want to apply it to the right side.

All in all, this was a fine solution. Thanks :)

**Comment by SkySkimmer** [comment]
For this example you could use `rewrite (plus_comm m n)` to apply to the other side. The idea is to instantiate the lemma sufficiently to make where it applies unambiguous.
