### ISSUE TITLE
Coq's native_compute should clean up after itself

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10495]
#### Description of the problem

Before I run `make`, on my project, `du -sh /tmp` tells me that there are 57 MB of things in `/tmp`. Partway through `make`ing, `du -sh /tmp` tells me that `/tmp` is 15 GB, filled with things like `Coq_native0389c2.{cmi,cmx,cmxs,o,native}`.  This is quite annoying; I've twice run out of space on my HD while building this single project.  I should not have to set up a loop that clears out `/tmp` in the background just to be able to compile my project without running out of space.

#### Coq Version

8.10 / master

**Comment by gares** [comment]
Looks like this one is in @maximedenes ballpark, maybe an `at_exit Sys.remove` can just do it.

**Comment by SkySkimmer** [comment]
@JasonGross can you try https://github.com/coq/coq/pull/11081 ?
