### ISSUE TITLE
[build] Removal of python2

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#10491]
Following discussion on #10466 , we have moved all our python scripts to explicitly use a `/usr/bin/python3` shebang, except for `update-compat.sh`.

`update-compat.sh` does fail in Ubuntu when used with python3 [decode error]

To fix this issue we should thus:
- fix `update-compat.sh` so the enconding error is no more
- remove `python2` from azure
- remove `python2` from Nix
- `python2` is still pulled indirectly in Docker, that will be fixed when we update the Docker image to Ubuntu 20.04

**Comment by JasonGross** [comment]
What's the justification for not continuing to support python2 in the timing scripts?  It doesn't seem like it costs us much; we could, say, have one instance of the CI run the test-suite with python2 available, and have the other CI machines not have python2, and ensure that the test-suite passes even if you don't have python2.

**Comment by ejgallego** [comment]
We just scheduled phasing out python 2 support as to cut deps, I guess if there is a good reason to keep it we can hold for a while.

**Comment by JasonGross** [comment]
I agree with cutting any dependencies of building Coq or associated tools on python2.  However, I'd like the CI to check that any changes I make to the timing scripts remain compatible with python2, until python2 is no longer available as a package on whatever system we're using, or until the burden becomes too great.

**Comment by Zimmi48** [comment]
But Python2 is dead (or soon to be: https://pythonclock.org/) and Python3 is already available everywhere, so what's the point?
