### ISSUE TITLE
[CI] macOS and Windows builds are not reproducible.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#10505]
Azure builds on both windows and OSX are not reproducible, due to lack of pinning of the dependencies.

There could be several ways to solve this, either using Docker or more manual methods.

**Comment by vbgl** [comment]
Do docker work on the Windows/OSX VMs provided by Azure?

Regarding OSX, we may pin the homebrew-core repository to some known version rather than blindly running `brew update`.

**Comment by ejgallego** [comment]
> Do docker work on the Windows/OSX VMs provided by Azure?

At least for Windows, both Gitlab and Azure should support it:
- https://docs.gitlab.com/runner/executors/docker.html#configuring-a-windows-docker-executor
- https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml

For OSX the situation seems more dire.

**Comment by Alizter** [comment]
@Zimmi48 What do you think about this today? I think the situation has improved, shall we close?

**Comment by Zimmi48** [comment]
Yes, on macOS we manually pin whatever we install with opam and on Windows we pin the Coq Platform, which pins most of its own dependencies.
