### ISSUE TITLE
[github] Coq topic description

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#10507]
Quoting @Zimmi48 from Gitter:

> Someone should add a description for the Coq topic here: https://github.com/github/explore
> Here is what was done for OCaml: https://github.com/github/explore/blob/master/topics/ocaml/index.md
> And what this results in: https://github.com/topics/ocaml

**Comment by anton-trunov** [comment]
Please check this tentative topic description: https://github.com/anton-trunov/explore/commit/19257e30eaae2ec1796eb89248d48031f9a5a5f6

If it's fine, I'll open a PR

**Comment by Zimmi48** [comment]
LGTM, thanks @anton-trunov!

**Comment by anton-trunov** [comment]
You might want to track it here: https://github.com/github/explore/pull/864

**Comment by anton-trunov** [comment]
The PR has been merged, so I think it makes sense to close this issue. Feel free to reopen if there is something to improve.

**Comment by Zimmi48** [comment]
Awesome, thanks again @anton-trunov!
