### ISSUE TITLE
MoreStlc won't compile

### ISSUE THREAD

**Issue by mrakgr** [coq/coq#10519]
#### Description of the problem

I am trying to compile [MoreStlc.v](https://softwarefoundations.cis.upenn.edu/plf-current/MoreStlc.html) and the compilation won't go through. The IDE does not give any error messages (or any messages ever apart from the `Running: coqc -Q E:\TheoremProving\plf PLF "E:\TheoremProving\plf\MoreStlc.v" 2>&1` variants) and I am not sure how to try it from the command line due to having to supply paths manually.

At first I suspected that compilation takes too much memory, but that was probably due to me repeatedly trying to compile and the IDE not cleaning up. The particular chapter of the book has the most automation of anything up to date, so that may have something to do with this though.

Compilation does work for all the chapters leading up to this. Moreover `MoreStlc.v` works fine in the IDE.

What should I do here?

**Edit**: Note that I am talking about the version of MoreStlc with the exercises filled in. I do want to paste it here due to it being coursework.

#### Coq Version

8.8.2 and just now 8.9.1. Windows 10.

**Comment by mrakgr** [comment]
I also have the same problem with `Perm.v` in volume 3 of SF now. I wish I knew what the error was, but the IDE has a bug that prevents it from printing any compilation output. There is an [outstanding issue](https://github.com/coq/coq/issues/3991) of over 4 years old that refers to this.

**Comment by gares** [comment]
What I would try to do is to compile all files from a cygwin or WSL terminal in batch mode, with something like that (assuming the coq binaries are in your PATH).
```
coq_makefile -o Makefile.coq -f _CoqProject
make -f Makefile.coq
```

**Comment by mrakgr** [comment]
I got both `Perm.v` and `MoreStlc.v` to compile using [Proof General](https://proofgeneral.github.io/) + Emacs. I had no trouble installing Proof General, but I had some issues with installing [`make`](https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows) as there are many places one can get it. I managed to install it through Chocolatey in the end. I got the two files to compile without a hitch after that.

I started working on this before and was just done by the time I saw your post. I tried Coq back in 2016 and remembered that PG was a thing from back then. I guess I'll use PG until the compilation issue gets fixed on Windows.

Since things work for me now, I am not sure what the issue was. I can verify now that I have `make` that the issue still persists for the IDE. I erased the `Perm.vo` file by hand and tried compiling from the IDE without success.

**Comment by mrakgr** [comment]
I am not sure if `triage` means that the devs need to verify it personally, but I found an SO user for whom the [issue occurred](https://stackoverflow.com/questions/47242800/coqide-make-on-windows). So it not just me and that guy 4 years ago for whom the issue is occuring.

**Comment by ejgallego** [comment]
@mrakgr indeed triage means we need to investigate more as `MoreSTLC` is compiled by our CI correctly, so the problem could range from a UI issue, to a make issue, to a documentation one.

**Comment by lilred** [comment]
I'm available to help repro!

**Comment by ejgallego** [comment]
This went stale, and the large majority of users have this working, please re-open with repro instructions if still a problem.
