### ISSUE TITLE
Equations package causes unrelated rewrite to be too aggressive

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#10523]
I have an ordinary transparent Definition `field_at` whose name appears in my proof goal.
I do `rewrite sepcon_andp_prop'`, whose left hand side matches the unfolding of `field_at`, 
and as expected (and desired), the rewrite fails.

If import the Equations package, now the rewrite looks inside the definition and succeeds.  This is a bug.

How to reproduce:

```
Require Import VST.floyd.proofauto.
Lemma test (cs: compspecs) (p: val):
   field_at Ews tint nil nullval p * emp |-- FF.
Proof.
intros.
Fail rewrite sepcon_andp_prop'.
Require Import Equations.Equations.
rewrite sepcon_andp_prop'.
Abort.
```

To reproduce this, you'll need a current version of VST.  I used https://github.com/PrincetonUniversity/VST/commit/81bace55cb5b02c53bf16bb263e4f0986ca45753.  After building VST, install the code above as "test.v" in the VST main directory.  You will be using the _CoqProject that the VST makefile produces in that directory.

Coq version 8.9.0.

Thanks to @pablolh for helping diagnose this.

**Comment by SkySkimmer** [comment]
Equations issues should be reported on the equations repo https://github.com/mattam82/Coq-Equations/
