### ISSUE TITLE
Cannot use pattern in Fixpoint binder.

### ISSUE THREAD

**Issue by LailaElbeheiry** [coq/coq#10534]
#### Description of the problem

I'm trying to pattern match on the input to a fixpoint, which I've previously read that it's not possible, but then in the Gallina specification language, it says " A binder can also be any pattern prefixed by a quote, e.g. '(x,y). "  , which works for a Definition, but not a Fixpoint, is there any reason that is the case?

Example:

This works fine

`Definition dummy '(a,b) :=  a + b.`

but this doesn't:

`Fixpoint dummy '(a,b) := match a with 0 => b | S a' => dummy (a',b) end.`

#### Coq Version

Coq v8.9.0
OCaml v4.07.0

**Comment by vbgl** [comment]
This is not an answer to your question, but note that even if the failing example was syntactically correct, you would have a hard time convincing Coq and its guard condition that it always terminate. Indeed, if you write:

> Fail
Fixpoint dummy n : nat :=
 let '(a, b) := n in
 match a with 0 => b | S a' => dummy (a', b) end.

you get:

> Recursive definition of dummy is ill-formed. […] Recursive call to dummy has principal argument equal to “(a', b)” instead of a subterm of “n”.

Therefore, it might be much more convenient to rely on an auxiliary function that does not need the irrefutable pattern matching on its arguments:

> Fixpoint dummy2 a b : nat :=
  match a with
  | 0 => b
  | S a' => dummy2 a' b
  end.

> Definition dummy1 '(a, b) := dummy2 a b.

Also, you might be interested in the “Equations” plug-in (http://mattam82.github.io/Coq-Equations/) with which you can write your example as follows:

> From Equations Require Equations.
Equations dummy (n: nat * nat) : nat by wf (fst n) lt :=
dummy (0, b) := b ;
dummy (S a', b) := dummy (a', b).
