### ISSUE TITLE
setoid_rewrite anomaly Array.fold_left2 invalid argument

### ISSUE THREAD

**Issue by andres-erbsen-sifive** [coq/coq#10533]
See also #4617.

```coq
Require Import Eqdep Setoid.
Goal forall (t : unit) (pf : tt = t),
  if (match pf with eq_refl => false end) then True else False.
Proof.
  intros.
  try setoid_rewrite <-Eqdep.Eq_rect_eq.eq_rect_eq.
Abort.
```

```
Ltac call to "setoid_rewrite (orient) (glob_constr_with_bindings)" failed.
Anomaly "Uncaught exception Invalid_argument("Array.fold_left2")."
Please report at http://coq.inria.fr/bugs/.
```
8.9.1.

**Comment by mattam82** [comment]
That one is surprising, I don't see how the single call to `Array.fold_left2` in `rewrite.ml` could fail as the arrays should have the same length by construction... will need to trace this.

**Comment by ppedrot** [comment]
Trigger by legacy unification while trying to unify the following two pattern-matchings:
```
cM: EConstr.constr =
  match ?X14@{__:=t; __:=pf} in (@eq y) return (?X12@{__:=t; __:=pf} y) with
  | CSTR.eq._0._1 => ?X13@{__:=t; __:=pf}
  end
cN: EConstr.constr =
  (if match pf with
      | CSTR.eq._0._1 => CSTR.bool._0._2
      end
   then True
   else False)
```

**Comment by mattam82** [comment]
Oh boy

**Comment by SkySkimmer** [comment]
>They don't even match on the same type anyways.

I think this is expected to fail as we first unify the predicates (which contain the inductive), but in this case eta expansion makes the unification pass (as the predicates don't have the same type).
