### ISSUE TITLE
Bad error message for malformed mutual inductive definition

### ISSUE THREAD

**Issue by jaykru** [coq/coq#10547]
Attempting to define two inductive types mutually with the incorrect syntax below:
```
Inductive B: Type :=
| F: A -> B with
Inductive A: Type := mkA.
```
fails with the message "Error: Parameters should be syntactically the same for each inductive type." This seems wrong and misleading to me.

Using the correct syntax works fine:
```
Inductive B: Type :=
| F: A -> B with
A: Type := mkA.
```

**Comment by ppedrot** [comment]
IIUC, `Inductive` is not a keyword, thus Coq believes you want to define two mutually inductive types `B` and `Inductive`, respectively with no parameters and one parameter `A`. The message is indeed misleading, but the fix is probably going to be a bit ad-hoc.

**Comment by JasonGross** [comment]
> The message is indeed misleading, but the fix is probably going to be a bit ad-hoc.

I think the correct fix here is to name the inductives and the parameters:
```
Error: Parameters should be syntactically the same for each inductive type.
B has no parameters while
Inductive has one parameter: A
```
