### ISSUE TITLE
CoqIDE crashes (coqtop died badly) if file with a hyphen in the name is opened

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10540]
CoqIDE crahses with a coqtop dies badly whenever a file with a hyphen in the name is opened.

I tested this on Windows. It would be great if someone could asap test if this is also the case on Linux, so that we know if this is a Windows specific problem.

Since one doesn't have the filename under control in many cases, I would say that this is a pretty severe issue.

**Comment by Zimmi48** [comment]
It looks very similar to #10286.

**Comment by Zimmi48** [comment]
I confirm that this is the exact same behavior as in #10286 and that it happens on Linux as well.
