### ISSUE TITLE
Roquableu paused because anormal number of runner failures.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#10542]
While browsing the bot's log I noticed an almost infinite loop of coqbot retrying a job and the job failing with a runner failure. See here a failed job: https://gitlab.com/coq/coq/-/jobs/255969665/. In the list of job on the right, at the bottom, one can see all the failed attempts. A cursory look seem to indicate that this was roquableu consistently failing and these jobs only eventually passed when they were executed on another runner, like pyrolyse. I have therefore paused the runner roquableu from the GitLab CI/CD settings pending further investigation by someone who has access to this runner (e.g. @maximedenes).

**Comment by ejgallego** [comment]
This is usually happens either because the machine is low on memory [too many jobs] or because docker needs some maintenance w.r.t. cleanup.

**Comment by gares** [comment]
FTR the machine was moved to fedora 30 during the weekend

**Comment by maximedenes** [comment]
@thery any idea why the Docker daemon could have stopped on Roquableu?

**Comment by thery** [comment]
Roquableu has been updated and saturday

**Comment by thery** [comment]
docker is back and running

**Comment by Zimmi48** [comment]
I've resumed the runner. Please everyone have a careful look at the GitLab pipelines to see if everything seems right.

**Comment by ejgallego** [comment]
This should have been closed in due time; however I'm reusing this issue to note that roquableu has been broken since a few weeks:

https://gitlab.com/coq/coq/-/jobs/448330994

I notified devs on Gitter, but it seems we didn't fix the problem. I guess a restart / docker clean should bring things back to normal, if the problem persists we should however remove the runner.

**Comment by ejgallego** [comment]
I've paused roquableu for now.

**Comment by maximedenes** [comment]
I reinstalled docker on roquableu. Somehow, the right version had been replaced by an outdated one. Maybe @thery knows more, I'm not familiar at all with fedora.

@ejgallego can you try again a build on roquableu?

**Comment by ejgallego** [comment]
Restarted, let's see how they fare now.

**Comment by ejgallego** [comment]
Still broken, example: https://gitlab.com/coq/coq/-/jobs/451471171
```
Running with gitlab-runner 11.9.2 (fa86510e)
   on roquableu curNbQZR
 Using Docker executor with image registry.gitlab.com/coq/coq:bionic_coq-V2019-12-08-V82 ...
 Pulling docker image registry.gitlab.com/coq/coq:bionic_coq-V2019-12-08-V82 ...
 Using docker image sha256:420a7bb721bd1c2c95083866f6e469d4d5299e7287443610c8b71a8d0c5ba2c3 for registry.gitlab.com/coq/coq:bionic_coq-V2019-12-08-V82 ...
 ERROR: Job failed (system failure): Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"open /sys/fs/cgroup/docker/cpuset.cpus.effective: no such file or directory\"": unknown (executor_docker.go:1026:2s)
```

**Comment by thery** [comment]
@maximedenes only thing I can think of is that I' ve upgraded Roquableu to fedora 31 on January 25th

**Comment by thery** [comment]
@maximedenes  it seems related:  https://github.com/docker/for-linux/issues/689

**Comment by maximedenes** [comment]
I think you're right. We'll need to tweak the kernel used by roquableu. Why are we not using Debian, again? ...

**Comment by maximedenes** [comment]
Fedora basically activated a feature they knew would break all major container apps (like docker).

**Comment by ejgallego** [comment]
Fedora does indeed tend to activate experimental or new stuff pretty early, after all it is a test-bed :/

**Comment by maximedenes** [comment]
Roquableu is back in business (e.g. https://gitlab.com/coq/coq/-/jobs/453536375, the job is expected to fail but docker runs fine).

I'm closing this, please reopen if the problem shows up again.

**Comment by ejgallego** [comment]
Thanks Maxime!
