### ISSUE TITLE
vm_compute in 8.10

### ISSUE THREAD

**Issue by silene** [coq/coq#10551]
There is something terribly wrong with `vm_compute` in Coq 8.10. This was first noticed by @MSoegtropIMC, who is experiencing strange failures with CoqInterval (https://github.com/coq/coq/pull/10522#issuecomment-513721248). I am still in the process of reducing the testcase, so it still depends on CoqInterval, sorry. By the way, one can trivially build a proof of `False` from the testcase, since `vm_compute` disagrees with `cbv`.

```coq
From Coq Require Import Reals List.
From Bignums Require Import BigZ.
From Interval Require Import Interval_tactic Interval_xreal Interval_bisect Interval_specific_ops.
Import ListNotations Private.

Lemma foo (x : R)
(H : (0 <= x <= 1 / 512)%R)
(formula := [Unary (PowerInt (Z.of_nat (1 + (1 + 0)))) 0; Unary (PowerInt (Z.of_nat 32)) 3;
           Binary Div 5 0; Binary Mul 0 2; Binary Add 0 5;
           Unary (PowerInt (Z.of_nat (1 + 0))) 5; Binary Div 10 4; 
           Binary Mul 0 1; Binary Add 0 3; Unary (PowerInt (Z.of_nat 0)) 9;
           Binary Div 15 8; Binary Mul 0 1; Binary Add 0 3;
           Unary (PowerInt (Z.of_nat 2)) 13; Binary Add 20 0; 
           Unary Sqrt 0; Binary Add 16 0; Binary Div 23 0; Unary Atan 0; 
           Unary Sin 0; Binary Sub 0 7; Unary Abs 0; Unary (PowerInt (Z.of_nat 34)) 24;
           Binary Div 29 0; Binary Sub 0 2] : list term)
(bounds := [A.Bproof x (I.bnd SFBI2.zero (Float 1%bigZ (-9)%bigZ)) H;
          let f := SFBI2.zero in
          A.Bproof (I.T.toR SFBI2.zero) (I.bnd f f)
            (conj (Rle_refl (I.T.toR SFBI2.zero)) (Rle_refl (I.T.toR SFBI2.zero)));
          let f := Float 1%bigZ 1%bigZ in
          A.Bproof (I.T.toR (Float 1%bigZ 1%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float 1%bigZ 1%bigZ))) (Rle_refl (I.T.toR (Float 1%bigZ 1%bigZ))));
          let f := Float (-23622187)%bigZ 4%bigZ in
          A.Bproof (I.T.toR (Float (-23622187)%bigZ 4%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float (-23622187)%bigZ 4%bigZ)))
               (Rle_refl (I.T.toR (Float (-23622187)%bigZ 4%bigZ))));
          let f := Float (-759250737)%bigZ 1%bigZ in
          A.Bproof (I.T.toR (Float (-759250737)%bigZ 1%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float (-759250737)%bigZ 1%bigZ)))
               (Rle_refl (I.T.toR (Float (-759250737)%bigZ 1%bigZ))));
          let f := Float 759250125%bigZ 2%bigZ in
          A.Bproof (I.T.toR (Float 759250125%bigZ 2%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float 759250125%bigZ 2%bigZ))) (Rle_refl (I.T.toR (Float 759250125%bigZ 2%bigZ))));
          let f := Float 1%bigZ 0%bigZ in
          A.Bproof (I.T.toR (Float 1%bigZ 0%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float 1%bigZ 0%bigZ))) (Rle_refl (I.T.toR (Float 1%bigZ 0%bigZ))))] : list A.bound_proof) :
match bounds with
| A.Bproof _ (Interval_interval_float.Ibnd l u) _ :: tail =>
    let fi :=
      fun b : I.type =>
      A.TaylorValuator.TM.eval (prec_of_nat 60, 2%nat)
        (nth 0
           (A.TaylorValuator.eval (prec_of_nat 60) 2 b formula
              (A.TaylorValuator.TM.var
               :: map
                    (fun b0 : A.bound_proof =>
                     A.TaylorValuator.TM.const (A.interval_from_bp b0)) tail))
           A.TaylorValuator.TM.dummy) b b in
    A.bisect_1d l u (fun b : I.type => A.check_f A.positive_check (fi b)) 5 = true
| _ => False
end.
Proof.
vm_compute. (* false = true *)
apply eq_refl.
Qed.
```

**Comment by MSoegtropIMC** [comment]
Just a note: this test case uses CoqInterval 3.4.0 - most files have been renamed in CoqInterval master.
<https://gitlab.inria.fr/coqinterval/interval/tree/interval-3.4.0/src>

**Comment by silene** [comment]
Actually, the testcase uses CoqInterval 3.4.1, since 3.4.0 is not compatible with Coq 8.10.

**Comment by MSoegtropIMC** [comment]
Ah yes, sorry, I just wanted to mention that it is not Interval master (which has entirely different filenames).

**Comment by silene** [comment]
Here is a reduced testcase, which does not involve CoqInterval:
```coq
From Bignums Require Import BigN.

Lemma foo (v := BigN.sqrt (BigN.pow 2 151)) : False.
Proof.
generalize (eq_refl v) (BigN.eqb_refl v).
unfold v at 1 3.
clearbody v.
intros H1.
cbv in H1.
elim H1.
vm_compute.
discriminate.
Qed.
```

Yet, strangely enough, Coq notices there is an issue at `Qed` time. But, the issue is not even related to `vm_compute`. Indeed, for some reason, Coq's conversion algorithm does not even agree with the result of `cbv`, as can be seen from the following testcase. If you thought `eq_refl` was of type `v = v`, then Coq wants you to reconsider:
```coq
Lemma foo (v := BigN.sqrt (BigN.pow 2 151)) : v = v.
Proof.
cbv in v. unfold v at 1.
apply eq_refl.
Qed. (* The term "eq_refl" has type ... while it is expected to have type "v = v" *)
```

At this point, you are probably thinking "yet another bug in the square root, that would not be the first time". So, here is another proof of `False`, but without any square root. And this time, it does not even trigger a bug in Coq's conversion algorithm, so `Qed` goes through!
```coq
Lemma foo (v := BigN.div (BigN.pow 3 101) (BigN.pow 5 50)) : False.
Proof.
generalize (eq_refl v) (BigN.eqb_refl v).
unfold v at 1 3.
clearbody v.
intros H1.
cbv in H1.
elim H1.
vm_compute.
discriminate.
Qed. (* success! *)
```

**Comment by MSoegtropIMC** [comment]
The values for the terms given by @silene computed by cbv and vm_compute are:
```
v_cbv := 17407905077428%bigN : BigN.t'
v_vmc := 17407905077441%bigN : BigN.t'
```
This is computed with:
```
From Bignums Require Import BigN.

Goal True.
pose (BigN.div (BigN.pow 3 101) (BigN.pow 5 50)) as v_cbv.
pose (BigN.div (BigN.pow 3 101) (BigN.pow 5 50)) as v_vmc.
cbv in v_cbv.
vm_compute in v_vmc.
```

**Comment by silene** [comment]
And here comes the version without any external dependency:
```coq
Require Import Int63.

Lemma foo : False.
Proof.
set (v := fst (diveucl_21 9305446873517 1793572051078448654 4930380657631323783)).
generalize (eq_refl v) (eqb_refl v).
unfold v at 1 3.
clearbody v.
intros H1.
cbv in H1.
elim H1.
vm_compute.
discriminate.
Qed.
```

**Comment by MSoegtropIMC** [comment]
Looks like this is not the first issue with diveucl_21. See <https://github.com/coq/coq/issues/10031>

**Comment by silene** [comment]
Adding `& maxuint63` at `kernel/byterun/coq_uint63_native.h:146` fixes the issue. But I will be honest, I have absolutely no clue what this algorithm computes.

**Comment by MSoegtropIMC** [comment]
> But I will be honest, I have absolutely no clue what this algorithm computes.

If a grand masters in numerical computations like you is saying that ...

**Comment by MSoegtropIMC** [comment]
Btw.: since this is C code and since this function apparently already enabled two proofs of False (this one and #10031), it would be a nice exercise to verify the function with VST.

**Comment by vbgl** [comment]
Ping @proux01 @maximedenes

**Comment by vbgl** [comment]
Does anyone remembers why this diveucl-21 function is part of the TCB? i.e., provided as a primitive operator rather than implemented in Coq?

**Comment by MSoegtropIMC** [comment]
> Does anyone remembers why this diveucl-21 function is part of the TCB? i.e., provided as a primitive operator rather than implemented in Coq?

And if it is a primitive operation, why doesn't it use the corresponding CPU instructions? An Intel Architecture CPU, and I think also ARM 64 bit CPUs, can do 128 bit / 64 bit divide in 64 bit mode, and I would think most current implementations of C provide a 128 bit type and have efficient and correct implementations for 128/64 bit divide, even in 32 bit mode.

Such instructions are typically limited to 64 bit quotients. As far as I can tell diveucl-21 also returns a 64 bit quotient and remainder. I wonder what it does if the quotient overflows.

**Comment by proux01** [comment]
@MSoegtropIMC congrats for finding that
@silene thanks for the great job in reducing the testcase
@vbgl thanks for pinging

> Adding & maxuint63 at kernel/byterun/coq_uint63_native.h:146 fixes the issue.

That sounds like the good fix. I'm looking at it and preparing a PR. Looks like I'm the one who introduced this bug in https://github.com/coq/coq/pull/10046, sorry about that.

> I have absolutely no clue what this algorithm computes.

As mentionned in https://github.com/coq/coq/pull/10046#issue-275251724 the spec is the axiom diveucl_21_spec in theories/Numbers/Cyclic/Int63/Int63.v. It basically does a 126/63 bits division and returns both the remainder and the lowest 63 bits of the quotient.

> it would be a nice exercise to verify the function with VST.

In fact, there are three version of this algorithm (see https://github.com/coq/coq/pull/10046#issue-275251724 ) so it would be even nicer to prove all three of them, maybe resorting to Why3.

> Does anyone remembers why this diveucl-21 function is part of the TCB? i.e., provided as a primitive operator rather than implemented in Coq?

Performance ? No idea. I guess it is mostly, if not only, used in Bignum, maybe @thery would have a clue ?

> Such instructions are typically limited to 64 bit quotients. As far as I can tell diveucl-21 also returns a 64 bit quotient and remainder. I wonder what it does if the quotient overflows.

It keeps the lowest 63 bits, as explained in the comment preceding the function
```C
/* precondition: y <> 0 */
/* outputs r and sets ql to q % 2^63 s.t. x = q * y + r, r < y */
```
but looking at the use in Bignum, maybe could we require as precondition that the quotient won't overflow.

**Comment by MSoegtropIMC** [comment]
@proux01 : again the question: wouldn't it make sense to replace this code with C code which in the end uses the DIV instruction? It does support Double-Quadword / Quadword division in 64 bit mode. If one thing is formally verified in Intel CPUs, then it is division instructions (remember the FDIV bug). I don't see how this would be less safe than the existing code (unless one does verify it) and in applications like CoqInterval it could lead to noticeable performance improvements. But this would require that it doesn't overflow as pre condition or one has to check it upfront. Afaik the DIV instruction interrupts with "div by 0" in case of an overflow.

**Comment by silene** [comment]
@proux01 In case you didn't see, take a look at #10553.

**Comment by thery** [comment]
>> maybe @thery would have a clue ?
This operation was one of the building block of the Bignum library so at that time it made sense to have it native.

**Comment by thery** [comment]
>  it would be a nice exercise to verify the function with VST.

Back in 2010, it was our ideas to verify this code but we thought the technology was not ready.
In 2020, thanks to what @silene and his student are doing, I think the way to go is to forget about
BigNum and directly link Coq with a verified arbitrary-precision integer library.

**Comment by silene** [comment]
Note that it would not solve the current issue, since our library assumes that `div21` is a correctly-implemented primitive (as does any other arbitrary-precision integer library out there). Also, there are still some algorithms of BigNum that have a better asymptotic complexity than those of our library (as it happens, the division), though our library should be much faster for all practical uses. Finally, there are some portability concerns, as Coq supports more architectures than our library. So, while I agree with the sentiment, it is still too early to talk about it.

**Comment by silene** [comment]
> Afaik the DIV instruction interrupts with "div by 0" in case of an overflow.

As far as I know, this is precisely the reason why compilers such as gcc and llvm refuse to emit such an instruction. Instead, they insert a call to `udivmodti4`, which performs an expensive 128-by-128 division. (Expensive is relative, as it is presumably faster than the algorithm currently used by Coq.) I don't know of any way to get the optimal assembly code with these compilers without actually resorting to inline assembly code.

**Comment by thery** [comment]
> without actually resorting to inline assembly code.

please don't do this in Coq!

**Comment by MSoegtropIMC** [comment]
> As far as I know, this is precisely the reason why compilers such as gcc and llvm refuse to emit such an instruction.

Interesting! I will ask some colleagues if they know how to get around this.

Still I guess it would be faster to do a block division using 64 bit / 64 bit division instructions, which cannot overflow. Shall I provide an implementation proposal on that basis?

**Comment by proux01** [comment]
> wouldn't it make sense to replace this code with C code which in the end uses the DIV instruction?

I have no opinion on this point (except that I'm not skilled enough to write the appropriate assembly code and configure/build scripts myself).

> But this would require that it doesn't overflow as pre condition or one has to check it upfront.

AFAICT the only use (by Bignum) of this division indeed assumes no overflow, so that wouldn't be an issue. More precisely, Bignum uses the spec (in `theories/Numbers/Cyclic/Int63/Int63.v`)
```Coq
Lemma diveucl_21_spec_aux : ∀ a1 a2 b,
      wB/2 ≤ [|b|] →
      [|a1|] < [|b|] →
      let (q,r) := diveucl_21 a1 a2 b in
      [|a1|] *wB+ [|a2|] = [|q|] * [|b|] + [|r|] ∧
      0 ≤ [|r|] < [|b|].
```
rather than the original specification
```Coq
Axiom diveucl_21_spec :  ∀ a1 a2 b,
   let (q,r) := diveucl_21 a1 a2 b in
   let (q',r') := Z.div_eucl ([|a1|] * wB + [|a2|]) [|b|] in
   [|q|] = Z.modulo q' wB ∧ [|r|] = r'.
```
so the latter could just replace the former as specification.

**Comment by MSoegtropIMC** [comment]
> I have no opinion on this point (except that I'm not skilled enough to write the appropriate assembly code and configure/build scripts myself).

I meant to write C code which compiles to DIV, but @silene wrote that this is not trivial. I will think about a block division algorithm. Need to look into the good old books from Knuth,
