### ISSUE TITLE
"Duplicate clear" warnings all over the place

### ISSUE THREAD

**Issue by silene** [coq/coq#10550]
Starting with Coq 8.10, warnings are displayed whenever one uses `=> {H} H`. I don't know whether this pattern is idiomatic, but it is certainly used in various developments, sometimes intensively. Testcase:

```coq
Require Import ssreflect.
Lemma foo (H:True) : True -> True.
Proof.
  move => {H} H. (* Duplicate clear of H [duplicate-clear,ssr] *)
  exact I.
Qed.
```

This was introduced in commit f059d18c411b4c9e2abba6d158b3a125916f38dc, entitled `[ssr] clean up implementation of {}/v -> /v{v}`.

**Comment by vbgl** [comment]
I think this is expected and is somehow mentioned in the change-log: https://coq.github.io/doc/v8.10/refman/changes.html#summary-of-changes

You may now write `move => {} H.`

**Comment by silene** [comment]
Indeed, I had missed it. That said, it lacks a bit of uniformity:
```coq
move => {H1 H2} H1 H2. (* warning: Duplicate clear of H1 *)
move => {H2} H1 H2.    (* no warning *)
move => {} H1 H2.      (* error: H2 already used *)
move => {} H1 {} H2.   (* the proper way? *)
```

**Comment by vbgl** [comment]
> move => {H2} H1 H2.    (* no warning *)

This one may also be a “proper way”, right?

**Comment by Blaisorblade** [comment]
FWIW, I see now no way to write these patterns that still works for 8.9, other than `move => {H} H'.` (which doesn't work for branch-specific renames). Can't be changed now, but not ideal.

**Comment by gares** [comment]
The rule is `=> ... {}H ...` is elaborated to `=> ... {H}H ...`. It means "replace" and before it had no meaning, since `{}` was not allowed in `=>` (but was in `rewrite` with the same meaning).

I think you can also `=> {H1 H2} - H1 H2` (or repeat `=>`) if you want to disable the elaboration.
I believe the idiomatic way would be `=> {}H1 {}H2`, even if you don't gain characters.

**Comment by Blaisorblade** [comment]
Oh, what I needed is `move => {H} -H.` Thanks! I understand the other options, but I can't drop 8.9 support (yet).
