### ISSUE TITLE
wrong lemma in int63

### ISSUE THREAD

**Issue by tabareau** [coq/coq#10567]
#### Description of the problem

The lemma lsr_add_distr is actually the same as lsl_add_distr.

It should be 

Lemma lsr_add_distr x y n: (x + y) >> n = ((x >> n) + (y >> n))%int63.

#### Coq Version

Master and 8.10

**Comment by maximedenes** [comment]
@vbgl can you take this one?

**Comment by vbgl** [comment]
Sure.

**Comment by vbgl** [comment]
The thing is that the suggested statement is dubious.

Take x = y = 2⁶² and n = 1. LHS is null, RHS is not…

**Comment by tabareau** [comment]
Indeed, it seems to be true only when x + y < 2^63 or something like that

**Comment by vbgl** [comment]
Here is an other counter-example without overflow: x = y = n = 1.

**Comment by vbgl** [comment]
A sufficient precondition is that x and y have no common bit. In this case addition is bitwise OR (see lemma “bit_add_or”) and right logical shift distributes over it (see lemma “lor_lsr”).
