### ISSUE TITLE
Conversion failure in presence of let-in in 8.10.

### ISSUE THREAD

**Issue by silene** [coq/coq#10560]
With Coq 8.10, the following testcase fails at Qed time with a typing error.

```coq
From Coq Require Import Int63.
Open Scope int63_scope.

Lemma foo :
  let n := match subc 64 63 with C0 l => l | C1 l => l end in
  (WW (addmuldiv n 0 4611686018427387904) (addmuldiv n 0 0)) = WW 1 0.
Proof.
(*cbv zeta.*)
cbv. (* WW 1 0 = WW 1 0 *)
apply eq_refl.
Qed.
```

But, if you uncomment `cbv zeta` (which just replaces `n` by its body), then it goes through without error.

Note that the testcase is computationally minimal. In other words, any reduction by hand makes it succeed, e.g., replacing the body of `n` with `1`, replacing an occurrence of `n` with `1`, replacing any call to `sub` or `addmuldiv` by its result, etc.

**Comment by maximedenes** [comment]
This could be due to a bug in the reduction rule of `addmuldiv`. There's some logic to reduce only if concrete values are known for the arguments. Maybe this interacts badly with the laziness of `let` in the kernel reduction machine. I'll investigate.

**Comment by silene** [comment]
Indeed, the testcase can be reduced further by using some other functions:
```coq
Lemma foo :
  let n := opp 0 in
  WW (add n 0) n = WW 0 0.
```

**Comment by silene** [comment]
As far as I can tell, on the last example, at some point, `whd_stack (FInt 0) [...; add _ 0; ...]` is called (which corresponds to `add n 0`). The function believes that `(FInt 0)` is fully normalized, so it does not apply the stack to it. Thus, Coq ends up with two supposedly normalized terms with different stacks, so it complains that they cannot be convertible. I have not found yet why the term was marked as fully normalized.

**Comment by silene** [comment]
So, in the end, the bug had nothing to do with sharing and let-ins.
