### ISSUE TITLE
[ci] fiat-crypto is using too much memory for our workers

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#10566]
Unfortunately we seem to get workers that lack just a bit of memory to handle fiat-crypto successfully quite often.

I dunno how to proceed here, @JasonGross ?

cc: #8993 #9338 #10353

**Comment by JasonGross** [comment]
Which file?  I recently added a file (PerfTesting/Core) that uses quite a lot of memory (because it vm_computes an enormous term), but I can remove / disable that part of things if needed.  If it's some other file, I'll have to think more.

**Comment by JasonGross** [comment]
(Recently = a couple of weeks ago)

**Comment by ejgallego** [comment]
Timing seems about right indeed, and that's the file creating problems so it seems:
https://gitlab.com/coq/coq/-/jobs/258615768
```
Finished failing transaction in 195.771 secs (31.645u,3.139s) (failure)
File "./src/Rewriter/PerfTesting/Core.v", line 286, characters 2-72:
Error: Out of memory.

```

**Comment by ejgallego** [comment]
It'd be great to add a workaround then, do we need some change on Coq's part?

**Comment by JasonGross** [comment]
Should be fixed now

**Comment by ejgallego** [comment]
Thanks a lot Jason
