### ISSUE TITLE
coq_makefile should let .coqdeps file be configurable

### ISSUE THREAD

**Issue by mattam82** [coq/coq#10565]
#### Description of the problem

The `coq_makefile` tool does not allow setting a specific dependency file. This prevents the use of multiple _*Project files in the same directory. My setup is that I need first to extract code from a first bunch of .v files, the compile some ML code and finally compile another bunch of .v files depending on those. Everything works fine except the hardcoded VDFILE variable in the generated Makefiles makes that the two makefiles have a data race at it, whereas I would like to let the second bunch of files use another dependency file. I guess a `VDFILES =? .coqdeps.d` change would be enough to make this configurable.
#### Coq Version

8.8.2

**Comment by SkySkimmer** [comment]
You can just call `make VDFILE=bla`
