### ISSUE TITLE
Bogus syntax for AddPath and AddRecPath commands

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10576]
Notice that these commands require 2 `as` strings in a row if `as_dirpath` is not empty.  Probably an editing error.  On the other hand, if no one has noticed this since 10/24/2017, are these commands really needed?

```
  command:
         :
       (* For compatibility *)
      | IDENT "AddPath"; dir = ne_string; "as"; alias = as_dirpath ->
	  { VernacAddLoadPath (false, dir, alias) }
      | IDENT "AddRecPath"; dir = ne_string; "as"; alias = as_dirpath ->
	  { VernacAddLoadPath (true, dir, alias) }

  as_dirpath:
    [ [ d = OPT [ "as"; d = dirpath -> { d } ] -> { d } ] ]
```

**Comment by silene** [comment]
These commands have been deprecated for 18 years. And they were broken in 32170384190168856efeac5bcf90edf1170b54d6, so 17 years ago. For once, I would approve an immediate removal, even if those commands currently display no deprecation warning.

**Comment by maximedenes** [comment]
I can do it as part of #10575.

**Comment by maximedenes** [comment]
Done.
