### ISSUE TITLE
Is `double induction` deprecated?

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#10571]
The manual says that `double induction` is deprecated, but I couldn't find the corresponding deprecation warning in the codebase.

We should either remove the deprecation from the manual, or add it in the code.

Cc @herbelin

**Comment by herbelin** [comment]
In my opinion, double induction is an interesting concept and I would remove the deprecation in the manual, even if the current implementation certainly deserve some improvements.

For instance, the current `double induction` produces the following on two Peano numbers `n` and `p`:
```
  n, p, n0 : nat
  H : forall n1 : nat, (forall p : nat, P n1 p) -> P (S n1) n0
  n1 : nat
  H0 : forall p : nat, P n1 p
  ============================
  P (S n1) (S n0)
```
An alternative semantics would be to specialize `H` and `H0` as follows:
```
  n, p, n0 : nat
  H : P (S n1) n0
  n1 : nat
  H0 : P n1 (S n0)
  H1 : P n1 n0
  ============================
  P (S n1) (S n0)
```
which would really be a "symmetric" induction justifying the word "double".

And we could have another asymmetrical specialization which we could call "lexicographic induction":
```
  n, p, n0 : nat
  H : P (S n1) n0
  n1 : nat
  H0 : forall p, P n1 p
  ============================
  P (S n1) (S n0)
```

Also, `induction n p` should not to the same as `induction p n`. It should accept `p` and `n` in the context. It should reuse the names provided and clear the unused names.

**Comment by maximedenes** [comment]
> In my opinion, double induction is an interesting concept and I would remove the deprecation in the manual, even if the current implementation certainly deserve some improvements.

Thanks! I'm preparing a patch on the manual, I'll add it there.

**Comment by maximedenes** [comment]
> Thanks! I'm preparing a patch on the manual, I'll add it there.

In fact, I realize now that `double induction` is not documented, apart from its deprecation. I'm afraid I'm not competent to do it. So, @herbelin, would you mind replacing the deprecation in the manual with a proper documentation?

**Comment by jfehrle** [comment]
It was removed in 8.14, so closing.
