### ISSUE TITLE
ltac2 in notations: notation_subst function not found: ltac2:value

### ISSUE THREAD

**Issue by vbgl** [coq/coq#10615]
Using ltac2 tactic-in-terms under a notation raises an anomaly. Here is a small example.

~~~
From Ltac2
Require Import Ltac2.

Notation "n .+2" := ltac2:(Control.refine (fun () => constr:(S (S n))))
  (at level 20, only parsing).

Definition four := Eval cbv in 2.+2.
~~~

> Error: Anomaly "notation_subst function not found: ltac2:value." Please report at http://coq.inria.fr/bugs/.

Am I doing something wrong? Is this expected? Is there a workaround.

cc/ @ppedrot

**Comment by ppedrot** [comment]
This is most likely an oversight in the implementation.

**Comment by vbgl** [comment]
Thanks Pierre-Marie for the diagnostic. It thus seems that if I want to use ltac2-in-terms in notations I need to implement and register an appropriate substitution function. Or may I just use the same trick as Ltac1 and use a “let” rather than to substitute?

In any case, I need to turn a glob_constr (or maybe a constr_expr) into a glb_tacexpr. Is there an easy way to do so?

**Comment by ppedrot** [comment]
I think I have to ponder a bit the proper solution. We can probably go for the let bindings, but we need to be careful about the substitution by effectful terms hence it'd be better if they were thunks. In any case, this should be similar to what we do for Ltac2 notations.
