### ISSUE TITLE
Change picking of CompCert for 8.10.0

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10611]
@xavierleroy does not agree with the current picking of CompCert in 8.10 and made a different suggestion. See (https://github.com/AbsInt/CompCert/pull/305).

**Comment by MSoegtropIMC** [comment]
I just prepared the patch as described in the above link. It contains just 2 cherry-picked commits, but it is huge (30.000 lines). I am almost inclined to implement a cherry picking mechanism in the build system, so that one can give a tag + a few commits to cherry pick. But I wonder how generally useful this would be - these cherry picks went through without manual conflict resolution, but I guess especially for cherry picks that large, where such a feature makes most sense, this is not so common. Maybe some of the release managers who have a lot of experience with cherry picking can comment. Another issue is the timeline.

@vbgl : I guess you need this asap?

**Comment by vbgl** [comment]
Rather than implementing a complex and ad-hoc mechanism for computing the right version of the source code, what about pushing the resulting commit onto a public git repository?

Here is an example: https://github.com/vbgl/CompCert/tree/v3.5%2Bcoq-8.10

IMHO it would be even better if said commit belonged to the official upstream repository and got a tag.

**Comment by MSoegtropIMC** [comment]
That's also a viable option, indeed. The base of the code is CompCert tag v3.5 on which I cherry pick two commits which are in CompCert git. So all commits in there are in official CompCert, just not in that order.

I don't see that CompCert would make a branch with that specific version, but I will ask. In case they do it, it is a trivial change, in case not we keep a fork.

So unless others object, I will follow the approach suggested by @vbgl, this is commit the cherry picked version in a branch on my CompCert fork and link this fork in the overlays file.

**Comment by vbgl** [comment]
Closed by #10621.
