### ISSUE TITLE
Unable to import Basics

### ISSUE THREAD

**Issue by JJGO** [coq/coq#10627]
#### Description of the problem

I am following the book Logical Foundations and I am unable to proceed to the second chapter. To recreate the issue I do the following steps
    
    $ wget https://www.cis.upenn.edu/~bcpierce/sf/lf-current/lf.tgz
    $ aunpack lf.tgz
    $ cd lf/
    $ make Basics.v
    $ coqtop
   
Then within `coqtop` I am unable to import Basics

    Welcome to Coq 8.8.1 (August 2019)

    Coq < From LF Require Export Basics.
    Toplevel input, characters 23-29:
    > From LF Require Export Basics.
    >                        ^^^^^^
    Error:
    Cannot find a physical path bound to logical path matching suffix
    <> and prefix LF.

#### Coq Version

OS: macOS Mojave 10.14.6 18G84 x86_64 

    $ coqtop -v 
    The Coq Proof Assistant, version 8.8.1 (August 2019)
    compiled on Aug 5 2019 10:47:51 with OCaml 4.05.0
    $ coqc -v
    The Coq Proof Assistant, version 8.8.1 (August 2019)
    compiled on Aug 5 2019 10:47:51 with OCaml 4.05.0
    $ cat _CoqProject
    -Q . LF

**Comment by JasonGross** [comment]
You need to run `coqtop -Q . LF` or possibly `coqtop -f _CoqProject` (not sure if this one works).  Only CoqIDE and ProofGeneral automatically pick up `_CoqProject`; `coqtop` does not.  Does this issue indicate that there is missing documentation?

**Comment by JasonGross** [comment]
(Note also that `make Basics.v` is wrong, but `make Basics.vo` might work.)

**Comment by JJGO** [comment]
Thank you.  I switched to proof general and everything seems to work Yes, I was doing `make Basics.vo`. 

Regarding the missing documentation, I run into this issue using [coquille](https://github.com/the-lambda-church/coquille) (which now seems to be outdated in favour of coqtail) and coqtop. Maybe mention in the Induction intro section that for the import to work the IDE needs to understand about `_CoqProject` or be given the `-Q` option explicitly, as in `coqtop`?

**Comment by Zimmi48** [comment]
> Maybe mention in the Induction intro section that for the import to work the IDE needs to understand about `_CoqProject` or be given the `-Q` option explicitly, as in `coqtop`?

This is probably a good suggestion. cc @bcpierce00
Closing this as it is not an issue in Coq.

**Comment by bcpierce00** [comment]
Thanks — we’ve already added some text about this in the upcoming release of SF.

   - B
