### ISSUE TITLE
Diff Failure during installation

### ISSUE THREAD

**Issue by amalapani** [coq/coq#10628]
During installation, the following was shown: 

HOQC theories/Idempotents
File "./theories/Idempotents.v", line 886, characters 2-82:
Warning:
Diff failure: Input string is not lexable
Showing message without diff highlighting
Please report at http://coq.inria.fr/bugs/.

**Comment by vbgl** [comment]
Thanks for your report.

Could you please give a few more details about what you did? What do you try to install, on which operating system, which version of Coq, etc. Also, is it you first attempt or is it something that no longer works after you changed something (then what did you change)?

**Comment by amalapani** [comment]
Hello,

Sorry for the lack of details in the original report, I am brand new to Coq. I was following installation instructions found at https://github.com/HoTT/HoTT/blob/master/INSTALL.md <https://github.com/HoTT/HoTT/blob/master/INSTALL.md> for OSX. The error occurred after the end of step 3 under “QUICK INSTALLATION INSTRUCTIONS” (after running ‘make’). This was my first attempt installing Coq. 

The error did not stop the installation procedure. I was able to test Coq without issues.

I hope this helps. 
Best Regards

**Comment by Zimmi48** [comment]
@amalapani Thanks for reporting ;-)

@jfehrle You might be interested in this. It seems like you could extract a new test case from `theories/Idempotents.v` in the HoTT project.

**Comment by Zimmi48** [comment]
FYI @vbgl, this is just a warning, so nothing that really cause any trouble, but one that suggests opening a bug report because it reflects a limitation of Jim's diff feature. BTW @jfehrle, shouldn't this warning only be seen when diffs are turned on? I would be surprised that Diffs were turned on by default in HoTT...

**Comment by jfehrle** [comment]
In 8.9, certain error messages show diffs even if the Diffs flag is "off" (your suggestion, if you remember).  This was turned off in 8.10 because it was causing some transient confusion in PG.  It may eventualy be re-enabled.  The message is harmless.

I tried following the instructions to install HoTT to reproduce the issue, but the `make` fails.  I don't plan to pursue this issue any further.

```
*** Warning: in file coq/theories/Init/Prelude.v, declared ML module numeral_notation_plugin has not been found!
*** Warning: in file coq/theories/Init/Prelude.v, declared ML module numeral_notation_plugin has not been found!
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /mnt/c/proj/HoTT/etc/missing aclocal-1.14 -I etc
/mnt/c/proj/HoTT/etc/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:463: recipe for target 'aclocal.m4' failed
```

**Comment by Zimmi48** [comment]
Would be good if someone else is motivated to produce a minimal reproducible example from this issue.

**Comment by ejgallego** [comment]
Dunno if it still could be valid, but I have the impression the diff code is still fragile at some points.

**Comment by jfehrle** [comment]
Doubtful.  The "Please report" was removed ages ago.  This is only a warning, and the user still sees the underlying message.  It used to be we'd apply diffs to some error messages even if diffs was turned off.

**Comment by ejgallego** [comment]
Seems reasonable, let's close then.
