### ISSUE TITLE
Regression of "Set Diffs" with "coqtop -emacs" since Coq 8.10-beta2

### ISSUE THREAD

**Issue by erikmd** [coq/coq#10637]
#### Description of the problem

I've recently noticed that the **Coq Diffs** setting is now broken when using:
- **Coq master** and **`coqtop -emacs`** (for PG master on MELPA) → triggers an error
- while Coq master + `coqtop` alone is OK,
- and Coq 8.10-beta2 + `coqtop -emacs` is OK
- (and likewise Coq 8.10-beta2 + `coqtop` alone is OK)

(Hopefully this difference is not on-purpose, and `coqtop -emacs` for Coq master could behave like Coq 8.10-beta2, so there is no need to pass additional CLI options to `coqtop -emacs` w.r.t. before…)

Cc @jfehrle 
Cc @Matafou @cpitclaudel FYI

#### Actual result and Coq version

```
$ docker run --rm -it coqorg/coq:dev bash -c \
    'coqtop --version && echo "Set Diffs \"on\"." | coqtop -emacs'

The Coq Proof Assistant, version 8.10+alpha (August 2019)
compiled on Aug 4 2019 23:24:29 with OCaml 4.05.0
Welcome to Coq 23afeb783bb3:/home/coq/.opam/4.05.0/.opam-switch/build/coq.dev/_build/default,master (5f7c88d0835631ed4fdaf6dc056c958bf8865b56)

<prompt>Coq < 1 || 0 < </prompt>Toplevel input, characters 0-15:
> Set Diffs "on".
> ^^^^^^^^^^^^^^^
Error:
Enabling Diffs requires setting the "-color" command line argument to "on" or "auto".

<prompt>Coq < 1 || 0 < </prompt>
```

### Expected result

Similarly to how Coq behaves in these 3 other situations:
 
```
$ docker run --rm -it coqorg/coq:dev bash -c \
    'coqtop --version && echo "Set Diffs \"on\"." | coqtop'

The Coq Proof Assistant, version 8.10+alpha (August 2019)
compiled on Aug 4 2019 23:24:29 with OCaml 4.05.0
Welcome to Coq 23afeb783bb3:/home/coq/.opam/4.05.0/.opam-switch/build/coq.dev/_build/default,master (5f7c88d0835631ed4fdaf6dc056c958bf8865b56)

Coq < 
Coq < 

$ docker run --rm -it coqorg/coq:8.10-beta2 bash -c \
    'coqtop --version && echo "Set Diffs \"on\"." | coqtop -emacs'

The Coq Proof Assistant, version 8.10+beta2 (July 2019)
compiled on Jul 27 2019 13:03:33 with OCaml 4.05.0
Welcome to Coq 8.10+beta2 (July 2019)

<prompt>Coq < 1 || 0 < </prompt>
<prompt>Coq < 2 || 0 < </prompt>

$ docker run --rm -it coqorg/coq:8.10-beta2 bash -c \
    'coqtop --version && echo "Set Diffs \"on\"." | coqtop'

The Coq Proof Assistant, version 8.10+beta2 (July 2019)
compiled on Jul 27 2019 13:03:33 with OCaml 4.05.0
Welcome to Coq 8.10+beta2 (July 2019)

Coq < 
Coq < 
```

**Comment by jfehrle** [comment]
It appears the regression is in fe5389542af2d9b6e8d964bbc2c10e997af409fe by @herbelin.

For this code in coqargs.ml:

```
(** Options for proof general *)
let set_emacs opts =
  Printer.enable_goal_tags_printing := true;
  { opts with config = { opts.config with color = `OFF; print_emacs = true }}
```

The last line should be:

```
  { opts with config = { opts.config with color = `EMACS; print_emacs = true }}
```

`color` has 4 possible values ```[`ON | `AUTO | `EMACS | `OFF]```.  Specifying `-emacs` is supposed to set the color option to ``` `EMACS``` (i.e., provide color info with XML-style tags).  I didn't think it was worth mentioning this detail in the error message.

Hugo, are you OK with changing this as shown?

> . Coq master + coqtop alone is OK

The default color setting is ``` `AUTO```

Nice that the 8.10 beta is not affected.

**Comment by Zimmi48** [comment]
This is not likely, but it would be good to check that the regression is not present in `v8.10` as well, i.e. that the faulty PR has not been backported.

**Comment by ejgallego** [comment]
> that the faulty PR has not been backported.

almost 99% I didn't tag that for backporting.

**Comment by vbgl** [comment]
I’ve not backported PR #10246 to branch `v8.10`.

**Comment by Zimmi48** [comment]
Sorry, for some reason Octobox did not show me the comment above mine. That explains why I posted this comment.

**Comment by herbelin** [comment]
> Hugo, are you OK with changing this as shown?

I'm ok. It seems I missed 6ef5a36a69e when rebasing at some time. Sorry.
