### ISSUE TITLE
Quotient of classical real numbers without axioms ?

### ISSUE THREAD

**Issue by VincentSe** [coq/coq#10631]
After the recent merge of
https://github.com/coq/coq/pull/10445
the classical real numbers are defined as a quotient of the constructive real numbers. In file `Rdefinition.v`, the quotient is done by axioms `Rabst, Rrepr, Rquot1, Rquot2`. Is there a way to do this quotient without axioms ?

If we assume functional extensionality, then the classical reals can be embedded in the computable subsets of rationals `Q -> bool`, with HProps restricting to Dedekind cuts. funext gives a true equality on those functions `Q -> bool`. However funext is not currently assumed by the stdlib, and depending on the intended semantics of Coq, it might not be a good idea to add it.

Another possibility would be higher inductive types, like HoTT, where constructors of equalities (ie quotients) are allowed. However I am not sure whether we can do higher inductive types without univalence, and hence funext.

**Comment by JasonGross** [comment]
> Another possibility would be higher inductive types, like HoTT, where constructors of equalities (ie quotients) are allowed. However I am not sure whether we can do higher inductive types without univalence, and hence funext.

HITs do not require univalence, but the interval HIT (the quotient of bool under true = false) gives you funext.

**Comment by JasonGross** [comment]
Also, I think sprop might make funext provable these days?  I'm not entirely sure about this one.

**Comment by ppedrot** [comment]
@JasonGross Nope. SProp only lets you implement the Setoid model which enjoys funext as a program translation into CIC + SProp.

**Comment by spitters** [comment]
The only model I know for Coq with classical logic is the classical set theoretical model.
This certainly supports funext. Moreover, funext is available in other models too:
HoTT and the (conjectured?) model in constructive set theory.

**Comment by andres-erbsen** [comment]
I believe this was c690a68ba0b
