### ISSUE TITLE
CoqIDE: New files do not automatically get a .v extension -> coqtop error on load

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10653]
When a new file is created in CoqIDE and saved without explicitly giving a `.v` extension, the file does not get any extension. If the file is later loaded, the user get's a `coqtop died badly` error.

This happened to a few people during the HoTT summer school. The error was reported by @kristinas.

**Comment by Zimmi48** [comment]
This issue was duplicated as #10935.
