### ISSUE TITLE
Strange parser behavior

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10656]
I've been experimenting with instrumenting the parsing code to count how many times the action for each production is invoked while compiling all the *.v files.  Some actions are being invoked many, many times even when the .v file appears not to match the production at all.

Here's a specific example.  `extratactics.ml` has this code which provides the `contradiction` tactic:

```
TACTIC EXTEND contradiction
| [ "contradiction" constr_with_bindings_opt(c) ] ->
    { onSomeWithHoles contradiction c }
END
```

which coqpp compiles into:

```
let () = Tacentries.tactic_extend __coq_plugin_name "contradiction" ~level:0 
         [(Tacentries.TyML (Tacentries.TyIdent ("contradiction", Tacentries.TyArg (
                                                                 Extend.TUopt (
                                                                 Extend.TUentry (Genarg.get_arg_tag wit_constr_with_bindings)), 
                                                                 Tacentries.TyNil)), 
           (fun c ist -> 
# 250 "plugins/ltac/extratactics.mlg"
 onSomeWithHoles contradiction c 
           )))]
```

If I add a `Printf.printf` after the `# 250` line, it gets printed 474 times while coqc compiles `DecimalFacts.v` even though that file doesn't contain the string `contradiction`.  On the other hand, `Runcountable.v` prints this 15 times, which is exactly the number of `contradiction` tactics in that file (the string also appears twice in comments).  Across all non-test .v files in Coq, it gets printed 2645 times while the string `contradiction` appears in .v files only 140 times.

This seems very strange, like a bug.  Why do I see this behavior?

**Comment by gares** [comment]
Hum, the semantic action here is not just building an ast but is really the code of the tactics.

 I guess an Ltac foo := contradiction makes foo use the same code where you put the print.

**Comment by SkySkimmer** [comment]
contradiction is invoked through "now"/"easy" (defined in Tactics.v)

Gaëtan Gilbert

**Comment by ejgallego** [comment]
This question seems solved to me then.
