### ISSUE TITLE
Context allows declaring (letin) variables outside sections

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#10668]
~~~coq
Context (bla:=false).
About bla. (* expands to: Variable bla *)
~~~
You can even compile such a file (but not coqchk it).

This is risking proofs of false, but it seems we use check_hyps_inclusion and the like enough to prevent it.

I think this is since 398fe8ee23759a1c28d91204aa013beae1dc602b

**Comment by herbelin** [comment]
For the record, the bug in 398fe8e is a `Discharge` which should have been a `persistence` in line 299.
