### ISSUE TITLE
Print Grammar tactic, et al behavior and usefulness

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10662]
I see that the output of the `Print Grammar tactic` includes long lists that appear in random order (with 100+ lines).  Is this still a useful command?  Same question about `Print Grammar constr`.  I see there's also an undocumented `Print Grammar vernac`, which lists all the commands.

For `Print Ltac Signatures`, I don't see why the built-in tactic `intros` is listed.  I see that the built-in tactic `apply` is not listed.  `Print Ltac intros` gives uninteresting output:

```
Coq < Print Ltac intros.
Ltac intros := intros
```

Should some of these go away or behave differently?

**Comment by ejgallego** [comment]
These are mainly debug commands for developers / advanced users. I don't see what the problem with them is. The order is not random but deterministic by the way.

Tactics in the `simple_tactic` production are not registered using `TACTIC EXTEND` so this is the reason they don't appear in `Print Ltac Signature` output I think.

**Comment by andres-erbsen-sifive** [comment]
I rely heavily on `Print Grammar constr` when developing notations. Yes, the output is unwieldy, but it is just a reflection of the mess that is having notations in the same entry by default.

**Comment by maximedenes** [comment]
> Should some of these go away or behave differently?

Closing as the question is too vague IMHO. The sort answer is: these commands should stay.
