### ISSUE TITLE
coqtop -schedule-vio2vo discontinued

### ISSUE THREAD

**Issue by hendriktews** [coq/coq#10679]
Since 103f59ed6b8174ed9359cb11c909f1b2219390c9 coqtop -schedule-vio2vo does not work any longer. If this was intended, I suggest to change the documentation appropriately.

**Comment by gares** [comment]
It is now an option of `coqc`, since `coqtop` is not to be used to compile files in batch mode anymore.
The `--help` is updated, but there is a mention to coqtop in the refman part about async proofs.

**Comment by ejgallego** [comment]
We can tweak the message in 8.10.
