### ISSUE TITLE
How to get a callback when the parser recognizes a TACTIC EXTEND tactic?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10675]
(Follow up to #10656)

I'm trying to count how many times each production is invoked while compiling a .v file.  I need to get a callback when the parser matches a production.  The callback must pass info sufficient to tell which production was matched.  I can see a way to do this for GRAMMAR EXTEND, but TACTIC EXTEND is more complex.

While I see where `grammar.ml` calls action functions for productions, I don't see how grammar.ml alone can distinguish which tactic extend production was matched.  It appears that tactic extensions become notations internally, and some part of that conversion creates an action function, but I haven't found where that's done so I'm not able to modify that.

I've been trying to make sense of this code for the last several days, tried many experiments and learned some things.  Quite complex with many moving parts.  I'd appreciate some direction.

I'll also want to handle the other extension types, in particular VERNAC COMMAND EXTEND, which is probably similar to TACTIC EXTEND.

**Comment by ppedrot** [comment]
@jfehrle You can plug in there: https://github.com/coq/coq/blob/92f38826f767db01dbc51f2372b23e7b4e3b1aaa/plugins/ltac/tacentries.ml#L170-L181.

**Comment by gares** [comment]
what does `mkact` stand for?

**Comment by jfehrle** [comment]
I would think "make action".

**Comment by gares** [comment]
But it builds an AST :-) whatever...

**Comment by ppedrot** [comment]
It's a parsing action, and indeed, a parsing action builds an AST...

**Comment by ppedrot** [comment]
@jfehrle btw are you satisfied with my answer and can we close this PR, or do you need more advice?

**Comment by jfehrle** [comment]
@ppedrot OK, I have something that should work for that case, thanks.

There are 2 other cases that I don't yet understand well enough:

First, in the first match pattern of `Tacentries.tactic_extend`, there's a call to `Tacenv.register_ltac` below the comment "The extension is only made of a name followed by constr entries: we do not add any grammar nor printing rule and add it as a true Ltac definition."  So I expect there's a generic Ltac grammar rule that accepts a tactic name followed by one or more constr arguments.  I want to find that action and add a callback there.

`register_ltac` appears to save info on the tactic using `Lib.add_leaf id (inMD (local, None, for_ml, tac, deprecation))`, but I don't see how to lookup the info afterwards or whether/how Ltac fetches that info.

Second, I started looking at how to get a callback from COMMAND EXTEND. 
`Vernacextend.vernac_extend` calls `Egramml.extend_vernac_command_grammar` which calls `make_rule` which calls `ty_eval`.  My guess is that the callback point belongs where the Printf is in this modified line:

```
| TyStop -> fun f loc -> Printf.printf "call\n"; f loc [] 
```

If so, I need to pass additional parameters to `ty_eval` to identify which production was matched and pass that to the callback.  I've not figured out how to fit that in to the declaration line for `ty_eval`.  I've not found documentation for the OCaml `: type` construction used here and the following typical attempt (adding `-> int` in the declaration and `0` in the calls to `ty_eval`) fails:

```
let rec ty_eval : type s tr a. (s, tr, a, Loc.t -> s) ty_rule -> int -> s gen_eval -> a = function
| TyStop -> fun f loc -> Printf.printf "call\n"; f loc []
| TyNext (rem, tok, None) -> fun f _ -> ty_eval rem 0 f
| TyNext (rem, tok, Some inj) -> fun f x ->
  let f loc args = f loc (inj x :: args) in
  ty_eval rem 0 f
```

gives me this error (referring to the second "f" on the TyStop line):

```
File "vernac/egramml.ml", line 60, characters 49-50:
Error: This expression has type int
       This is not a function; it cannot be applied.
```

Your suggestions most welcome, thanks.

**Comment by ppedrot** [comment]
> So I expect there's a generic Ltac grammar rule that accepts a tactic name followed by one or more constr arguments. I want to find that action and add a callback there.

This is https://github.com/coq/coq/blob/6bb04f3240e14cc0bbb117879afd0305db31b64c/plugins/ltac/g_ltac.mlg#L159-L160
and
https://github.com/coq/coq/blob/6bb04f3240e14cc0bbb117879afd0305db31b64c/plugins/ltac/g_ltac.mlg#L219

> I don't see how to lookup the info afterwards or whether/how Ltac fetches that info.

See `Tacenv.locate_tactic` and related.

> If so, I need to pass additional parameters to ty_eval to identify which production was matched and pass that to the callback.

No, don't do that, this is tricky generic GADT business. Rather, plug your code there: 

https://github.com/coq/coq/blob/6bb04f3240e14cc0bbb117879afd0305db31b64c/vernac/egramml.ml#L91

**Comment by jfehrle** [comment]
Side comment: it seems inconsistent for `Tacentries.tactic_extend` to treat these `reflexivity` and `intros` productions differently.  Not sure if this affects behavior/users.

```
TACTIC EXTEND reflexivity
| [ "reflexivity" ] -> { Tactics.intros_reflexivity }
END
```

and `| [ "intro" ] ->` here:

```
TACTIC EXTEND intro
| [ "intro" ] -> { Tactics.intro_move None MoveLast }
| [ "intro" ident(id) ] -> { Tactics.intro_move (Some id) MoveLast }
| [ "intro" ident(id) "at" "top" ] -> { Tactics.intro_move (Some id) MoveFirst }
| [ "intro" ident(id) "at" "bottom" ] -> { Tactics.intro_move (Some id) MoveLast }
| [ "intro" ident(id) "after" hyp(h) ] -> { Tactics.intro_move (Some id) (MoveAfter h) }
| [ "intro" ident(id) "before" hyp(h) ] -> { Tactics.intro_move (Some id) (MoveBefore h) }
| [ "intro" "at" "top" ] -> { Tactics.intro_move None MoveFirst }
| [ "intro" "at" "bottom" ] -> { Tactics.intro_move None MoveLast }
| [ "intro" "after" hyp(h) ] -> { Tactics.intro_move None (MoveAfter h) }
| [ "intro" "before" hyp(h) ] -> { Tactics.intro_move None (MoveBefore h) }
END
```

**Comment by ppedrot** [comment]
@jfehrle nope, this is a conscious design choice. Not introducing parsing rules is better for modularity, as in the `reflexivity` case, but this is not always possible. In the `intro` case you *need* to add a parsing rule, otherwise the argument-less version of the tactic will trigger a parsing error.

**Comment by jfehrle** [comment]
I have 2 of the the three cases working.  I have an issue with the `  | _ ->` case in `Tacentries.tactic_extend`, which I thought I had covered until I tried it.  I planned to create a map from `kn_id` to `entry` in `add_ml_tactic_notation` and do a lookup in `add_tactic_entry.mkact`.  But  `add_ml_tactic_notation` is only called in the first `coqc` process and apparently cached in a file, so my map is empty for subsequent `coqc` processes.

Alternatively, I can pass the `entry` info to `add_glob_tactic_notation` and make it part of `tacobj`, which seems to be where items are added to the cache, but I couldn't figure out how retrieve that info in `add_tactic_entry.mkact`.  How can I do that?

By the way, `mkact` is a misleading name for these functions; `action` would be much clearer in that the functions don't "make" an action, they _are_ the actions.  I could update these in the PR.  Or not.

**Comment by ppedrot** [comment]
@jfehrle This is strange, but I'm not sure I understand this particular problem. In theory, the following closure should be called each time a tactic is parsed:
https://github.com/coq/coq/blob/92f38826f767db01dbc51f2372b23e7b4e3b1aaa/plugins/ltac/tacentries.ml#L170-L181
Inside it you can call the resolving functions to get the user-facing name and the like.

**Comment by jfehrle** [comment]
Yes, this is being called each time a tactic is parsed.  I have kn there, but I want to report the statistics using `entry` info (plugin name, tactic name, index) as the key, so I need to map the value.  But `obj` in `add_ml_tactic_notation` is not called in every coqc process, so the map is empty except for the first coqc process.  Any idea how to fetch the object with the kn so I can get the entry (from a field I will add)?

https://github.com/coq/coq/blob/92f38826f767db01dbc51f2372b23e7b4e3b1aaa/plugins/ltac/tacentries.ml#L675-L678

```
COQC -noinit theories/Init/Notations.v
tactic_extend3 ltac_plugin typeclasses_eauto
add_ml_tactic_notation: ltac_plugin typeclasses_eauto 2
for key Coq.Init.Notations.typeclasses_eauto_#_4C69D5F9, tactic = ltac_plugin typeclasses_eauto 2
add_ml_tactic_notation: ltac_plugin typeclasses_eauto 1
for key Coq.Init.Notations.typeclasses_eauto_#_with_#_4C69D5F8, tactic = ltac_plugin typeclasses_eauto 1
add_ml_tactic_notation: ltac_plugin typeclasses_eauto 0
for key Coq.Init.Notations.typeclasses_eauto_bfs_#_with_#_4C69D5FB, tactic = ltac_plugin typeclasses_eauto 0
COQC -noinit theories/Init/Logic.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Datatypes.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Logic_Type.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Specif.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Decimal.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Nat.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Byte.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Peano.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Wf.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Tactics.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Tauto.v
tactic_extend3 ltac_plugin typeclasses_eauto
COQC -noinit theories/Init/Prelude.v
tactic_extend3 ltac_plugin typeclasses_eauto
```

**Comment by ppedrot** [comment]
You can hack this way more easily: inside the closure, get the body of the alias using `Tacenv.interp_alias`,  then match on it and extract the entry data when it is a `TacML` node. That should do the trick, the only way to create such node is to go trough tactic extensions IIRC.

**Comment by ppedrot** [comment]
Closing this as the question has been answered.
