### ISSUE TITLE
lia choke points

### ISSUE THREAD

**Issue by rnrand** [coq/coq#10687]
#### Description of the problem

The `lia` tactics chokes on some surprisingly simple goals, which omega can solve almost instantly:

```
Lemma repad_lemma1_l : forall (a b d : nat),
  a < b -> d = (b - a - 1) -> b = a + 1 + d.
Proof. intros. subst. lia. Qed.

Lemma repad_lemma1_r : forall (a b d : nat),
  a < b -> d = (b - a - 1) -> b = d + 1 + a.
Proof. intros. subst. lia. Qed.

Lemma repad_lemma2 : forall (a b d : nat),
  a <= b -> d = (b - a) -> b = a + d.
Proof. intros. subst. lia. Qed.

Lemma le_ex_diff_l : forall a b, a <= b -> exists d, b = d + a. 
Proof. intros. exists (b - a). lia. Qed.

Lemma le_ex_diff_r : forall a b, a <= b -> exists d, b = a + d. 
Proof. intros. exists (b - a). lia. Qed.  

Lemma lt_ex_diff_l : forall a b, a < b -> exists d, b = d + 1 + a. 
Proof. intros. exists (b - a - 1). lia. Qed.

Lemma lt_ex_diff_r : forall a b, a < b -> exists d, b = a + 1 + d. 
Proof. intros. exists (b - a - 1). lia. Qed.
```

#### Coq Version

8.8.2

**Comment by ejgallego** [comment]
@rnrand I'm afraid the report seems invalid; these goals get resolved instantly in my `master` branch.

As we discussed by mail, if you want to report bugs for `Lia` you should use the development version of Coq.

**Comment by ejgallego** [comment]
@Zimmi48 should we add a label for `resolved: fixed in newer version`

**Comment by rnrand** [comment]
Oh good. 

I was hopeful that these were resolved in the current branch, I was just following @thery 's  suggestion to post them to make sure. I'll follow up with more examples (if they exist) when I've updated.

**Comment by ejgallego** [comment]
Yup, it is OK to post all the examples you see `lia` having trouble with.

However you may save time testing them in `master` of 8.10, 8.8.2 is really too old in terms of `lia`.

**Comment by ejgallego** [comment]
A quick way of testing 8.10 is using https://jscoq.github.io/ , you'll have to use `From Coq Require Import Lia.` tho as in jscoq all packages are qualified by default.

**Comment by thery** [comment]
Good news. I've tested them with `8.9.0 (March 2019)` and they all go through.

**Comment by Zimmi48** [comment]
> @Zimmi48 should we add a label for `resolved: fixed in newer version` ?

Yep, this is something I had been thinking about too. To be completed with the milestone in which the bug was resolved if we know it.

**Comment by ejgallego** [comment]
> Yep, this is something I had been thinking about too. To be completed with the milestone in which the bug was resolved if we know it.

Cool, I'd say let's submit a PR adding the tag to the contributing guide.

**Comment by Zimmi48** [comment]
I have #10646 that has been waiting for a review and an assignee for two weeks. I am always willing to enhance the contributing guide but it's always very hard to get feedback.
