### ISSUE TITLE
master uses 1.8x+ the memory as 8.9.1

### ISSUE THREAD

**Issue by andres-erbsen-sifive** [coq/coq#10684]
#### Description of the problem

Coq master seems to use almost twice as much memory as 8.9.1 when processing `Kami/CompileVerifiable.v`. This means we cannot run coq master in our CI, and thus cannot add kami to coq CI (#10306, and afaik this is the only remaining blocker for that).

build [log](https://builds.sr.ht/~andres_tries_srht_github/job/83001) and  [script](https://builds.sr.ht/api/jobs/83001/manifest) (failing after 2GB RAM runs out)

I confirmed this locally, seeing 281178 minor page faults from 8.9.1 and 530762 from master, putting it just slightly over 2GB.

```
git clone --recursive git@github.com:sifive/RiscvSpecFormal.git
cd  RiscvSpecFormal
make
/usr/bin/time -v coqc -q -Q coq-record-update/src RecordUpdate -Q bbv/theories bbv -Q Kami Kami -Q FpuKami FpuKami -Q ProcKami ProcKami -Q StdLibKami StdLibKami  Kami/CompileVerifiable.v
```

@tjmach @vmurali

#### Coq Version

e9c42c26d1fc653d1411fa2fe41b12bffa8ae992 vs 8.9.1

**Comment by ejgallego** [comment]
#10198 is the first PR to look at. Beware that sometimes more memory use can mean dramatic speedups, so indeed a quicker type-checking is often the preferred trade-off.

**Comment by andres-erbsen-sifive** [comment]
the commit before that PR, e9c42c26d1fc653d1411fa2fe41b12bffa8ae992, gives 315509 minor page faults

**Comment by ejgallego** [comment]
So indeed that seems to account for most of them [note that some OCaml GC tuning may be needed to get more accurate numbers]

The big question is, what is the difference in timing?

**Comment by ejgallego** [comment]
[Note, that PR was also backported to 8.10, differential testing may be easier in that branch]

**Comment by ejgallego** [comment]
> I am confused why coqtop gives me a different commit hash

This is typically makefile woes, the commit hash is stored in some auto-generated file which is not always properly updated. This should be solved once we work in the dune-based system a bit more.

**Comment by andres-erbsen-sifive** [comment]
> This should be solved once we work in the dune-based system a bit more.

Ok. FYI I was using `make -f Makefile.dune world`.

before: 1df3b08cb40bab6db1177b0289995d40287437f5: 315509 minor page faults, 185s
after: 13034bc2a322d250a971c9cc73881a34f9d64025: 545153 minor page faults, 174s

**Comment by ejgallego** [comment]
> FYI I was using `make -f Makefile.dune world`.

Yup, this is then a bug in the dune generation of that file, it is scheduled to be solved.

> before: [1df3b08](https://github.com/coq/coq/commit/1df3b08cb40bab6db1177b0289995d40287437f5): 315509 minor page faults, 185s
> after: [13034bc](https://github.com/coq/coq/commit/13034bc2a322d250a971c9cc73881a34f9d64025): 545153 minor page faults, 174s

So that's a 6% speedup in exchange of more memory [you could use gnu `time` maybe to see max RSS?]

I wonder what can we do, in some cases the speedup of that patch were in excess of 10% so that's not a small number for a lot of people. In general it is easy for proof engineers to throw a bit more memory [in the PR we measured 70% in some cases] , however it is quite hard for them to go faster.

Speaking for myself I think the current tradeoff is still good, tho of course we could try to have the best of both worlds, but that kind of fine tuning related to hash-consing is known to be very hard and time consuming :/

**Comment by ejgallego** [comment]
In the case of that particular file, a workaround would be using less Sections, but indeed, that also hurts big time in terms of readability / maintenance of the code :/

**Comment by andres-erbsen-sifive** [comment]
Thanks for the analysis, and for eyeballing the right PR! Wasn't there a pretty clear case for removing hash-consing altogether that was rejected due to memory usage increase of similar magnitude, or am I misremembering?

before: Maximum resident set size (kbytes): 1254756
after: Maximum resident set size (kbytes): 2166104

**Comment by ejgallego** [comment]
You are welcome!

As I wrote above time vs memory seems like a complicated tradeoff, given the large speedup the PR brought we sided with a faster Coq, as IMVHO it what makes sense for most users, even if in this case heavy users of sections are penalized with more memory [but let's not forget they are also getting faster checking times]

So I dunno what to do here, for example IRIS people would not like for their compilation to get again 15% slower, that's a lot over a work day, and memory is pretty cheap these days.

So I'd dare to say that the best option is to get more memory on the CI.

**Comment by ejgallego** [comment]
Maybe @ppedrot tho has some idea on how to improve memory consumption here, if we could pinpoint some pathological case it is likely memory use could be improved.

**Comment by ejgallego** [comment]
It would be very interesting to get total time numbers in the project, before and after the patch, to get an idea what kind of speedup we are talking about in Kami.

**Comment by ppedrot** [comment]
FTR, my personal plan is to fix #8241, which is probably an avatar of the issue at hand here, by offloading the opaque proof terms to disk (or even drop them altogether with a special flag). Hashconsing reduces the size of proof terms at the cost of a high CPU usage, but keeping opaque proof terms are actually useless 99% of the time.

**Comment by andres-erbsen-sifive** [comment]
and I was just about to write here that I am working on splitting the file.

**Comment by ejgallego** [comment]
@ppedrot tho it is not very likely that two opaque bodies share the same hash cons, isn't it?

[FTR something that my new proof checking scheduler supports is memory stats, I indeed access the kernel env in read-only mode to grab them]

**Comment by ppedrot** [comment]
@ejgallego It happens for section definitions though. And furthermore that's not the point, fact is that we shouldn't hashcons opaque bodies in so far as we're never going to observe them except if the user explicitly asks for them e.g. via printing or (dubiously allowed) extraction.

**Comment by ejgallego** [comment]
Indeed, what I mean is that it actually shouldn't already make a difference, in terms of explaining the higher memory use.
