### ISSUE TITLE
Fail to compile plugin_tutorial

### ISSUE THREAD

**Issue by lideji** [coq/coq#10690]
#### Description of the problem
I am compiling the project in directory tut0. Use the "make" command in the terminal. 
The error is 
#### 
/Users/zhangliao/opam-coq.8.8.1/default/bin//coq_makefile -f _CoqProject -o Makefile.coq Unknown option src/g_tuto0.mlg
make: *** No rule to make target `Makefile.coq'.  Stop.
####.
How could I solve this problem? Does it due to the coq version of me?

**Comment by SkySkimmer** [comment]
The plugin tutorial is for a specific version of Coq (which one depends on which version of the tutorial you pick), check that you have the right one.

**Comment by Zimmi48** [comment]
The versions compatible with Coq 8.9 or Coq 8.8 (as you seem to be using) can be found in the corresponding branches of https://github.com/ybertot/plugin_tutorials. But generally speaking, we encourage plugin writers to work with the latest version of the API, i.e. the one of the development version, in which case the plugin tutorial are in the Coq sources, but you should also compile with the dev version of Coq (coq.dev of the coq-core-dev opam repository, see https://github.com/coq/opam-coq-archive#repositories).

**Comment by zunction** [comment]
@Zhang-Liao Hi I'm also experiencing the same problem you encountered. Tried using the [https://github.com/ybertot/plugin_tutorials](https://github.com/ybertot/plugin_tutorials) suggested by @Zimmi48 but still didn't work for me. Would you be able to share how you over come this problem if you have managed to resolved it?

Below is the error msg i got:
```
/Users/zhangsheng/.opam/4.08.1/bin//coq_makefile -f _CoqProject -o Makefile.coq
Unknown option src/g_tuto0.mlg
Usage summary:

coq_makefile .... [file.v] ... [file.ml[i4]?] ... [file.ml{lib,pack}]
  ... [any] ... [-extra[-phony] result dependencies command]
  ... [-I dir] ... [-R physicalpath logicalpath]
  ... [-Q physicalpath logicalpath] ... [VARIABLE = value]
  ...  [-arg opt] ... [-opt|-byte] [-no-install] [-f file] [-o file]
  [-h] [--help]

Full list of options:

[file.v]: Coq file to be compiled
[file.ml[i4]?]: Objective Caml file to be compiled
[file.ml{lib,pack}]: ocamlbuild file that describes a Objective Caml
  library/module
[any] : subdirectory that should be "made" and has a Makefile itself
  to do so. Very fragile and discouraged.
[-extra result dependencies command]: add target "result" with command
  "command" and dependencies "dependencies". If "result" is not
  generic (do not contains a %), "result" is built by _make all_ and
  deleted by _make clean_.
[-extra-phony result dependencies command]: add a PHONY target "result"
 with command "command" and dependencies "dependencies". Note that
 _-extra-phony foo bar ""_ is a regular way to add the target "bar" as
 as a dependencies of an already defined target "foo".
[-I dir]: look for Objective Caml dependencies in "dir"
[-R physicalpath logicalpath]: look for Coq dependencies recursively
  starting from "physicalpath". The logical path associated to the
  physical path is "logicalpath".
[-Q physicalpath logicalpath]: look for Coq dependencies starting from
  "physicalpath". The logical path associated to the physical path
  is "logicalpath".
[VARIABLE = value]: Add the variable definition "VARIABLE=value"
[-byte]: compile with byte-code version of coq
[-opt]: compile with native-code version of coq
[-arg opt]: send option "opt" to coqc
[-install opt]: where opt is "user" to force install into user directory,
  "none" to build a makefile with no install target or
  "global" to force install in $COQLIB directory
[-f file]: take the contents of file as arguments
[-o file]: output should go in file file (recommended)
	Output file outside the current directory is forbidden.
[-h]: print this usage summary
[--help]: equivalent to [-h]
make: *** No rule to make target `.merlin'.  Stop.
```

**Comment by Zimmi48** [comment]
@zunction The error you reported is clearly not the one you get when trying to build the version in https://github.com/ybertot/plugin_tutorials given that these versions do not contain any `mlg` files. Please do make sure that you use the branch that matches your version of Coq. And if you want help, please provide details on which version of Coq you are using (and which branch you are trying to build).

**Comment by zunction** [comment]
@Zimmi48 Thanks a lot for your swift reply. Sorry for not providing the information, I'm using emacs 26.3, coq version 8.9.1. I went to check if I used another version instead of what I mentioned, but I have indeed used  [https://github.com/ybertot/plugin_tutorials ](https://github.com/ybertot/plugin_tutorials) which has  [`mlg`](https://github.com/ybertot/plugin_tutorials/blob/master/tuto0/src/g_tuto0.mlg) files in the`tuto0` folder.

**Comment by Zimmi48** [comment]
@zunction Right, but for Coq 8.9, you should use the `coq-8.9` branch of this repository. Sorry if I was unclear earlier.

**Comment by zunction** [comment]
@Zimmi48 Thanks for the clarification. In this case, since there is not `plugin_tutorial` in the `doc` folder, so I have to get my Coq version up to date (8.10 in this case) for me to be able to work the `plugin_tutorial`.

**Comment by ejgallego** [comment]
For plugin development I'd recommend to jump straight to 8.11 [and ultimately master], the plugin API has few stability guarantees so it makes little sense to use old versions.

**Comment by Zimmi48** [comment]
As @ejgallego said, we do recommend using the latest Coq version when developing plugins. However, if you or someone else absolutely needed to write a plugin for Coq 8.9, the corresponding version of the plugin tutorial is: https://github.com/ybertot/plugin_tutorials/tree/coq-8.9. Starting with Coq 8.10, the plugin tutorial should indeed be found within the Coq repository itself: https://github.com/coq/coq/tree/v8.10/doc/plugin_tutorial / https://github.com/coq/coq/tree/v8.11/doc/plugin_tutorial / https://github.com/coq/coq/tree/master/doc/plugin_tutorial.

**Comment by zunction** [comment]
@ejgallego @Zimmi48 Thanks for the pointer. I have been successful getting it to run on coq v8.10.2. Have been trying to understand `plugin_tutorial` but having problems understanding the code. Could you suggest any resource that would help ease me into it? 

Merry Xmas!

**Comment by Zimmi48** [comment]
I am not aware of any existing written resources beyond this plugin tutorial. You may be interested in reading this [blog post](https://taliasplse.wordpress.com/2018/06/10/coq-implementors-workshop/) from a plugin author (even though this is a documentation on writing plugin). As mentioned in the blog post, our [Gitter chat](https://gitter.im/coq/coq) is a good place to ask questions on plugin development.

Merry Christmas to you too!

**Comment by ejgallego** [comment]
@zunction I'd recommend to open specific documentation issues in this repos so we can improve the tutorial.

Are you familiar with OCaml? If you are not indeed it may take a while to understand code.
