### ISSUE TITLE
inversion_clear not in the tactic index

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#10701]
#### Description of the problem

The index at https://coq.inria.fr/refman/coq-tacindex.html should mention the `inversion_clear` tactic. The tactic already is documented at https://coq.inria.fr/refman/proof-engine/tactics.html#coq:tacn.inversion.

But also see https://github.com/coq/coq/issues/2465, that tactic has some serious bugs since basically forever.

**Comment by Zimmi48** [comment]
Already fixed in 8.9.1 (whose manual is still not the one available by default): https://coq.github.io/doc/V8.9.1/refman/proof-engine/tactics.html#coq:tacv.inversion-clear

**Comment by RalfJung** [comment]
> whose manual is still not the one available by default

Is that bug tracked somewhere?

**Comment by Zimmi48** [comment]
Oh yeah, it is coq/www#118. And it is not the first (nor the last I'm afraid) issue that references it.
:cry:
