### ISSUE TITLE
A goal that lia couldn't solve but omega can

### ISSUE THREAD

**Issue by xuanruiqi** [coq/coq#10707]
#### Description of the problem

I encountered a goal that could be solved by `omega`, but not `lia`:

```
 T : Type
 k : nat
 default : T
 arr : t 0 -> T
 H : (k < 0)%nat
 ============================
 match k with
 | 0 | _ => default
 end = arr (of_nat_lt H)
```

This goal is almost trivial, because H generates a contradiction, and then ex falso quodlibet. However, `lia` could not solve the goal, complaining that no witness could be found. `omega`, on the other hand, was able to solve it easily.

#### Coq Version
8.9.1

**Comment by vbgl** [comment]
Trying to reproduce the issue, it seems that the fact that the goal depends on the absurd hypothesis is important.

Could you please check whether your issue is impacted by PR #9856? Thanks.

**Comment by fajb** [comment]
Could you  provide a standalone example?
That would help a lot, thanks.

**Comment by fajb** [comment]
PR #9856 solves the following goal.
```
 forall
    (T : Type)
    (t : nat -> Type)
    (k : nat)
    (default : T)
    (arr : t 0 -> T)
    (H : (k < 0)%nat) of_nat_lt,
 match k with
 | 0 | _ => default
 end = arr (of_nat_lt H).
```
Hopefully, this solves the issue.
