### ISSUE TITLE
Are Proofview.Progress.goal_equal environments passed in the wrong order?

### ISSUE THREAD

**Issue by andreaslyn** [coq/coq#10711]
On the following line https://github.com/coq/coq/blob/0c6726655ee0ec06a40240cca44202d584506c9c/proofs/goal.ml#L94

it seems that the environments are passed in the wrong order. My reason to believe this is because later the environments are passed on to [Evarutil.eq_constr_univs_test](https://github.com/coq/coq/blob/0c6726655ee0ec06a40240cca44202d584506c9c/engine/evarutil.mli#L212) in the same order, and the documentation says
```
[eq_constr_univs_test sigma1 sigma2 t u] tests equality of [t] and
    [u] up to existential variable instantiation and equalisable
    universes. The term [t] is interpreted in [sigma1] while [u] is
    interpreted in [sigma2]. The universe constraints in [sigma2] are
    assumed to be an extension of those in [sigma1].
```
I would not expect the universes in `gls.Evd.sigma` to be an extension of those in `glss.Evd.sigma`, I would expect the opposite.

I discovered this while working on compiling math-comp with HoTT, by getting universe errors from `rewrite !term`. I have tried changing the line to
```
  | [ g ] -> not (Proofview.Progress.goal_equal gls.Evd.sigma gls.Evd.it glss.Evd.sigma g)
```
This seems to work. I am however unsure about this. After all, I think it is unlikely that there is an error here.

What do you think? Have I corrected the error in the wrong place?

**Comment by ppedrot** [comment]
The current order looks correct to me. Each evar is passed with the map in which it exists. Maybe `eq_constr_univs_test` is doing funny business with evarmaps though...

**Comment by SkySkimmer** [comment]
>After all, I think it is unlikely that there is an error here.

Based on what?
I think your change is correct, make a PR.

**Comment by andreaslyn** [comment]
> Based on what?
> I think your change is correct, make a PR.

I was unsure about it because this part of the sources seems rather central. Therefore, if there is a problem here, I think it is likely that someone else would have found it.

I have made a PR.

**Comment by ppedrot** [comment]
@SkySkimmer my comment was saying the opposite to you, I think this PR is incorrect.. How could the evar appear in an unrelated evarmap? There is no assumption of one evarmap extending the other!

**Comment by SkySkimmer** [comment]
>Each evar is passed with the map in which it exists

This issue is about changing the order of both the maps and the evars, so I don't understand what the above quote has to do with it.

**Comment by andreaslyn** [comment]
@ppedrot Notice that `gls.Evd.it` and `g` are also swapped.

**Comment by ejgallego** [comment]
If the function is order-sensitive maybe it would make sense to use named arguments?

**Comment by andreaslyn** [comment]
> If the function is order-sensitive maybe it would make sense to use named arguments?

That would make it clearer. The function [Evarutil.eq_constr_univs_test](https://github.com/coq/coq/blob/0c6726655ee0ec06a40240cca44202d584506c9c/engine/evarutil.ml#L869) is also order sensitive. I think it makes sense to use named the arguments for this function as well.

**Comment by ejgallego** [comment]
Indeed, as an API user I'd expect `eq_` functions to be symmetrical, so indeed named arguments + a comment may help, or even removing the `eq_` in this case could be worth it [what should it be, `leq_` ?]

**Comment by andreaslyn** [comment]
I think the name `eq_` is alright, since the function checks that `t` (interpreted in `sigma1`) and `u` (interpreted in `sigma2`) are equal, modulo existential variables and universes. I think the asymmetry is caused by this line
https://github.com/coq/coq/blob/0c6726655ee0ec06a40240cca44202d584506c9c/engine/evarutil.ml#L882

where it is assumed that the universes in `sigma2` is an extension of those in `sigma1`.

**Comment by ppedrot** [comment]
@andreaslyn Yeah sorry, I misread your patch. This is indeed correct.
