### ISSUE TITLE
CoqIDE: command "Variant" has no syntax highlighting

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10720]
In CoqIDE, the command "Variant" has no syntax highlighting.

This has been tested with a master version from end of July.

P.S.: I just found that the command "Declare Custom Entry" also has no syntax highlighting on CoqIDE.

**Comment by Zimmi48** [comment]
I am afraid that this is a widely occurring problem as there is no documented process for adding the highlighting when some command is added. This is also a problem that is more general than just in CoqIDE. Syntax highlighting for editors, or for web-rendering (as can be seen on GitHub) is also frequently missing commands.
