### ISSUE TITLE
library page about Ltac is empty

### ISSUE THREAD

**Issue by gares** [coq/coq#10746]
Look here: https://coq.inria.fr/distrib/current/stdlib/Coq.ltac.Ltac.html

I guess the Ltac.v file only loads the ML plugins but contains no Coq code, so its automatically generated coqdoc page is empty... This is quite misleading. We could at least put a comment pointing to the refman chapter about Ltac.

Context: here at ITP some newcomers found that confusing, and they are right ;-)

**Comment by herbelin** [comment]
Falling on this issue, I suspect that the canonical fix intended by @ppedrot is to turn this currently empty file into a file at least loading the ltac plugin??
