### ISSUE TITLE
lia only works after a manual `PreOmega.zify; rewrite ?Z2Nat.id in *`

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#10755]
```
Require Import Coq.ZArith.ZArith.
Require Import Coq.micromega.Lia.

Lemma HbtbAddr: forall x,
    (3 <= x)%Z ->
    Z.to_nat x = (3 + (Z.to_nat x - 3))%nat.
Proof.
  intros.
  Fail lia.
  PreOmega.zify. Fail lia.
  rewrite ?Z2Nat.id in *; lia.
Qed.
```

I would like `lia` to solve the above goal automatically, without having to manually invoke `PreOmega.zify; rewrite ?Z2Nat.id in *` before.

Both Coq 8.9.0 and Coq [master](https://github.com/coq/coq/commit/110e87a2bee21c112f7fc4291e5a7b7e5180217b) are affected.

/cc @andres-erbsen @fajb

**Comment by fajb** [comment]
fixed by PR #9856
