### ISSUE TITLE
[API] TacEnv.locate_tactic finds compute but not vm_compute

### ISSUE THREAD

**Issue by gares** [coq/coq#10769]
I'm not 100% sure, but it may be because
https://github.com/coq/coq/blob/c5ecc185ccb804e02ef78012fc6ae38c092cc80a/plugins/ltac/coretactics.mlg#L339-L345
does not register it

**Comment by gares** [comment]
CC @ppedrot

**Comment by ppedrot** [comment]
Why does it matter?

Ltac notations that look like a name won't be reachable either, and the lines you mention are but a hack to make the special case of notations for reduction tactics work. I wouldn't complain about adding it to the list, but it's no less ad-hoc than the current solution. Do you have a reason you want this to work?

**Comment by gares** [comment]
Ok, maybe I'm using the Wong API. I'd like to call an ltac1 tactic from Elpi, and this API seemed appropriate to find it based on the name. What should I use instead?

**Comment by ppedrot** [comment]
Parse the tactic and evaluate it with Tacinterp?

**Comment by gares** [comment]
Concretely, the API lookx like `coq.ltac1.call "foobar" [trm A, trm B]` where `A` and `B` are coq terms built via elpi, so I don't have the "text" for the entire tactic invocation. The call should be morally equivalent to `let A := constr:(....) in let B := ... in foobar A B`. It seems to work fine if "foobar" is `Ltac foobar A B := ....` but if "foobar" is `vm_compute` it does not work (to locate via `TacEnv`).

I'm fine to ask the user to "proxy" his ltac1 tactics, if this is needed. But I'd like to understand if I'm doing something wrong, or not, by using `TacEnv` and what else to use in case it is wrong (even with proxies).

**Comment by gares** [comment]
Oh, and at some point I'm going to add `coq.ltac2.call` so hints for that are also welcome.

**Comment by ppedrot** [comment]
I think that the underlying question was answered, let's close.
