### ISSUE TITLE
Option to disable lia caching

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#10772]
No matter how [fast](https://github.com/coq/coq/pull/10765) or [slow](https://github.com/coq/coq/issues/10743#issuecomment-531215534) lia caching is, it would be good to have an option to turn off the lia cache. This would make it easier to understand benchmark results, enable us to test whether it actually improves performance at all, and simplify lia benchmarking.

/cc @fajb @thery @andres-erbsen

**Comment by llelf** [comment]
Does not https://github.com/coq/coq/pull/10765 (the “fast” part) address it?
