### ISSUE TITLE
The extensible `zify` tactic reports anomaly when a class instance isn't a head normal form

### ISSUE THREAD

**Issue by pi8027** [coq/coq#10779]
#### Description of the problem

```coq
Require Import ZArith_base ZifyClasses ZifyInst ZifyBool.

Structure eqType := EqPack { sort :> Type; _ : sort -> sort -> bool }.

Definition eq_op (T : eqType) : T -> T -> bool :=
  match T return T -> T -> bool with @EqPack _ op => op end.

Canonical bool_eqType := @EqPack bool Bool.eqb.
Canonical nat_eqType := @EqPack nat Nat.eqb.

Instance Op_bool_eqb : BinOp Bool.eqb :=
  { TBOp := fun x y => isZero (Z.sub x y);
    TBOpInj := ltac:(now intros x y; destruct x, y) }.
Add BinOp Op_bool_eqb.

Instance Op_eqop_bool : BinOp (@eq_op bool_eqType) :=
  Op_bool_eqb. (* I think this must be a head normal form. *)
Add BinOp Op_eqop_bool.

Goal forall b : bool, eq_op _ b b = true.
Proof.
Fail Zify.zify.
(*
Anomaly "Uncaught exception Failure("Cannot register term Op_eqop_bool")."
Please report at http://coq.inria.fr/bugs/.
 *)
Abort.
```

cc: @fajb

#### Coq Version

master

**Comment by pi8027** [comment]
The `Instance` command doesn't support `:= Eval ... in ...` syntax so we need to repeat the body of `Op_bool_eqb` twice as follows. In this example, `zify` does nothing.
```coq
Require Import ZArith_base ZifyClasses ZifyInst ZifyBool.

Structure eqType := EqPack { sort :> Type; _ : sort -> sort -> bool }.

Definition eq_op (T : eqType) : T -> T -> bool :=
  match T return T -> T -> bool with @EqPack _ op => op end.

Canonical bool_eqType := @EqPack bool Bool.eqb.
Canonical nat_eqType := @EqPack nat Nat.eqb.

Instance Op_bool_eqb : BinOp Bool.eqb :=
  { TBOp := fun x y => isZero (Z.sub x y);
    TBOpInj := ltac:(now intros x y; destruct x, y) }.
Add BinOp Op_bool_eqb.

Instance Op_eqop_bool : BinOp (@eq_op bool_eqType) :=
  { TBOp := fun x y => isZero (Z.sub x y);
    TBOpInj := ltac:(now intros x y; destruct x, y) }.
Add BinOp Op_eqop_bool.

Goal forall b : bool, eq_op _ b b = true.
Proof.
Fail progress Zify.zify. (* Failed to progress. *)
Abort.
```

**Comment by fajb** [comment]
Yes. You are right.  

This should not be an anomaly but a genuine error.

**Comment by fajb** [comment]
- You need to perform `intros` before calling `zify`.
- This does not completely solve the issue.
`zify` does not seem to understand that `@eq_op  bool_eqType` has type `bool -> bool -> bool`.
Adding an explicit type annotation solves the issue.
I'll investigate this.

```
Goal forall b : bool, (eq_op _: bool -> bool -> bool) b b = true.
Proof.
  intros; Zify.zify;lia. 
Qed.
```

**Comment by pi8027** [comment]
@fajb Thank you so much for your help. Moreover, concrete instances of `eqType` have many syntactically different but convertible representations in MathComp, e.g., `bool_eqType` is convertible with `Choice.eqType bool_choiceType`, `Countable.eqType bool_countType`, `Choice.eqType (Countable.choiceType bool_countType)`, `Finite.eqType bool_finType`... So I guess this issue could be more difficult in general.

**Comment by fajb** [comment]
Have a look at https://github.com/fajb/coq/tree/zify-fix
where the reification code is a bit improved.
Now, the following code works.

```
Goal forall b : bool, eq_op _ b b = true.
Proof.
  intros; Zify.zify;lia. 
Qed.
```

`zify` does not try to perform reductions. The reification code is very syntactic and I wish to keep it so. 
For the time being, you may need to normalise operators before calling zify, or declare all of them.

If there is an existing Coq mechanism to perform the normalisation, at low cost, I'm all ears.

**Comment by fajb** [comment]
Sine commit  https://github.com/fajb/coq/commit/765e298cf3d330dc22a43f94b3c04c1a10f7dbe3, instances are reduced to hnf. Therefore the following declaration is now accepted.
```
Instance Op_eqop_bool : BinOp (@eq_op bool_eqType) :=
  Op_bool_eqb. 
Add BinOp Op_eqop_bool.
```

**Comment by pi8027** [comment]
@fajb Thank you so much. It does work (except for overloaded operators requiring unification for term comparisons). Please mark this issue to close when you submit a PR to merge it.

> zify does not try to perform reductions. The reification code is very syntactic and I wish to keep it so.
> For the time being, you may need to normalise operators before calling zify, or declare all of them.
> 
> If there is an existing Coq mechanism to perform the normalisation, at low cost, I'm all ears.

In my opinion, what I need here is not the normalisation, but the term comparison using unification like ssrmatching. I can demonstrate it later by writing some Ltac code.
