### ISSUE TITLE
Separate Extraction inside a module fails with an Anomaly

### ISSUE THREAD

**Issue by ana-borges** [coq/coq#10796]
#### Description of the problem

When attempting to do a Separate Extraction inside of a module, I obtain the following error message:

> Anomaly
> "File "plugins/extraction/extract_env.ml", line 639, characters 11-17: Assertion failed."
> Please report at http://coq.inria.fr/bugs/.

Here is a minimal working example:

```Coq
Require Extraction.

Module Example.

  Definition a : nat := 0.

  Separate Extraction a.

End Example.
```

This is easy to avoid by extracting only outside modules.

#### Coq Version

Version 8.9.1.

**Comment by herbelin** [comment]
Should it be a regular error instead?

**Comment by ana-borges** [comment]
> Should it be a regular error instead?

Sounds good.

**Comment by herbelin** [comment]
Note: PR #17344 is alternatively proposing to let `Separate Extraction` work in a module.
