### ISSUE TITLE
Reference manual has a number of extraneous invalid spaces in the middle of build targets

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10790]
For example, in https://coq.inria.fr/refman/practical-tools/utilities.html
> The sorting used here is the same as in the `print-pretty-timed -diff` target.

There is no `print-pretty-timed -diff` target, though there is a `print-pretty-timed-diff` target.  I will try to fix this when I get a chance.  (git blame suggests that the spaces were introduced in the initial porting from LaTeX to sphinx)

**Comment by Columbus240** [comment]
It seems, that someone already resolved this. At least, I can’t find (using grep) any typos of this kind in https://github.com/coq/coq/blob/master/doc/sphinx/practical-tools/utilities.rst. Maybe it was 395519de374e2c51cde2b2777af90f8af1200ea2 that fixed them.
I searched a little in other files whether the same kind of typo turned up, but couldn’t find any.
I propose closing this issue.
