### ISSUE TITLE
apply edge case has unexpected behavior

### ISSUE THREAD

**Issue by bergwerf** [coq/coq#10800]
I have been working with Coq for a while but I haven't seen this behavior before, and I don't know how to find out why it makes sense (or if it is actually a bug). The second application below (in `Example bug`) does not change the goal into the implication premise as I would expect.

#### Description of the problem

The Coq code below demonstrates the unexpected behavior.
```coq
From Coq Require Export Init.Datatypes.
From Coq Require Export Bool.Bool.

Lemma Is_true_implb_impl x y :
  (Is_true x -> Is_true y) <-> Is_true (implb x y).
Proof.
  destruct x; simpl; split; intros H.
  - apply H. apply I.
  - intros H'. assumption.
  - apply I.
  - intros H'. exfalso. assumption.
Qed.

Example expected :
  Is_true (implb false false).
Proof.
  Check (Is_true_implb_impl false false).
  (* (Is_true false -> Is_true false) <-> Is_true (implb false false) *)
  apply (Is_true_implb_impl false false).
  (* As expected, I now have to prove Is_true false -> Is_true false  *)
Abort.

Example bug :
  Is_true (implb true true).
Proof.
  Check (Is_true_implb_impl true true).
  (* (Is_true true -> Is_true true) <-> Is_true (implb true true) *)
  apply (Is_true_implb_impl true true).
  (* The goal didn't change! (but a subgoal was added) *)
Abort.
```

#### Coq Version

`8.8.1`

**Comment by SkySkimmer** [comment]
It looks like it tries the `<-` direction first, and since `implb true true = true` it actually gets chosen.

**Comment by bergwerf** [comment]
Ah, that makes sense. Of course this case is not really an issue for me but I was wondering if there was a slight issue here in the way apply works. I'm fine if this issue is closed.

**Comment by Alizter** [comment]
Feel free to reopen if this is really an issue.
