### ISSUE TITLE
subst fails if Section Variable is used in Section Definition

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#10812]
```
Section Foo.
  Context (a: nat).

  Definition foo(x: nat) := a * a = x.

  Goal forall n, foo n -> a = 5 -> False.
  Proof.
    intros.
    subst.
```

fails with

```
Error: Ltac call to "subst" failed.
       Found no subterm matching "a" in the current goal.
```

This is unfortunate, because the contract of `subst` is, as far as I understand, to never fail, and to substitute as much as it can. Proof scripts often depend on this contract, i.e. they don't put `subst` behind a `try`.

The desired behavior would be that `subst` does not fail. Whether or not it removes the `a = 5` hypothesis is less important to me.

Coq version: Both 8.9.0 and [master](https://github.com/coq/coq/commit/110e87a2bee21c112f7fc4291e5a7b7e5180217b) are affected.

**Comment by herbelin** [comment]
This is clearly a bug: `subst` should not fail.

An auxiliary question is whether `subst a` should fail or not in the same conditions. See this [comment](https://github.com/coq/coq/issues/12139#issuecomment-622743684) at #12139  for a discussion.
