### ISSUE TITLE
Ltac2 anomaly on simple function

### ISSUE THREAD

**Issue by eponier** [coq/coq#10810]
#### Description of the problem

I was playing with Ltac2 and the following simple function:

```
Require Import Ltac2.Ltac2.
Import Constr.Unsafe.

Ltac2 test c :=
  match kind c with
  | Lambda i c1 c2 =>
    match i with
    | None => ()
    | Some i => ()
    end
  | _ => ()
  end.

Eval compute in ltac2:(test constr:(fun n => n + 1)).
```
triggers:
```
Anomaly "Uncaught exception Invalid_argument("Array.fold_left2")."
Please report at http://coq.inria.fr/bugs/.
```
The error seems to be due to the inner match on `i`.

#### Coq Version
master

**Comment by SkySkimmer** [comment]
Can't reproduce since https://github.com/coq/coq/pull/10784, is your Coq really master?

**Comment by eponier** [comment]
No indeed, I was 10 days behind, and it does not seem to be reproducible on the real master.

Sorry for the noise.
