### ISSUE TITLE
Way to keep proof history in coqc the same as it is in coqtop for testing

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#10814]
I'm working on adding diffs to the `Show Proof` command.  For local testing, I tried modifying `Vernac.load_vernac_core.loop` so `coqc` would do a `Show Proof` after every tactic, but I find that the essential call `Stm.get_prev_proof` always returns `None`.  IIRC we don't save the proof history in `coqc` for performance reasons.  Is there a simple way to change this behavior?

My test code for `get_prev_proof`.  The first printf is often executed but the second one is never executed:

```
      if Vernacstate.Proof_global.there_are_pending_proofs () then begin
        Printf.printf "In a proof\n";
        let doc = state.doc in
        let oproof = Stm.get_prev_proof ~doc (Stm.get_current_state ~doc) in
        if oproof <> None then
          Printf.printf "get prev_proof\n"
      end;
      loop state (state.sid :: ids)
```

**Comment by jfehrle** [comment]
@gares, can you help me with this one?  Thanks.

**Comment by gares** [comment]
I think that there is a command line option to cache all states, we use it in test mode in order to make Undo work as expected. It used to be calle -async-proof-cache.

**Comment by jfehrle** [comment]
Great, thanks!  Its `-async-proofs-cache force`.  That's returning non-None results.
