### ISSUE TITLE
`Notation` does not always give priority to most recent, in the same scope

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#10824]
The following example shows up in lambdarust (of course it is minimized here):
```coq
Notation F := False.
Notation "!!" := False (at level 100).
Check False. (* !! : Prop *)
```
but:
```coq
Notation "!!" := False (at level 100).
Notation F := False.
Notation "!!" := False (at level 100).
Check False. (* F : Prop *)
```

since the same actions are performed at `Import` time, it means that (using `Export`), one can build an example where `Import A. Import A.`, with `A` fully qualified, is not the same as `Import A`.

I believe this regression was introduced by 849bf3600fe, where in order to not print a warning, the entire notation declaration is discarded.

This is extracted from https://github.com/coq/coq/issues/10773

**Comment by Zimmi48** [comment]
Your bet on the commit that introduced this does not seem right, because the reported behavior has not changed since at least 8.4pl6.

So the only regression here is that this behavior has consequences since the recent `Import` changes.

**Comment by maximedenes** [comment]
I thought I had tested with `master` and the commit I mentioned reverted, and it seemed to fix the issue.

> So the only regression here is that this behavior has consequences since the recent `Import` changes.

Note that the system was relying on this invariant before the recent `Import` fixes. It is only related because we noticed it while trying to debug the consequences of fixing `Import` on lambdarust.

**Comment by gares** [comment]
CC @chdoc is this the bug you experience when using HB ?

**Comment by chdoc** [comment]
Maybe, it certainly looks related. Note that changing notation scopes (including lonely notations) _does_ allow overriding the abbreviation:
```coq
Declare Scope foo_scope.
Open Scope foo_scope.
Notation "!!" := False (at level 100).
Check False. (* !! : Prop *)
Notation F := False.
Check False. (* F : Prop *)
Notation "!!" := False (at level 100) : foo_scope.
Check False. (* !! : Prop *)
```

**Comment by gares** [comment]
@maximedenes would you mind explaining how this is possible, maybe during the next Coq call, so that we can get at least a "spec" that makes sense w.r.t. Import/Export and then propose a fix?
