### ISSUE TITLE
FR: build coq using dune without coqide dependencies

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#10821]
#### Description of the problem

When trying to build coq I get the following error:

```
[build@archlinux coq]$ make -f Makefile.dune world
dune build  @vodeps
dune exec ./tools/coq_dune.exe _build/default/.vfiles.d
dune build  @install
File "ide/dune", line 49, characters 12-22:
49 |  (libraries coqide_gui))
                 ^^^^^^^^^^
Error: Library "coqide_gui" in _build/default/ide is hidden (optional with
unavailable dependencies).
Hint: try: dune external-lib-deps --missing @install
make: *** [Makefile.dune:55: world] Error 1
```

in the following environment:

```yaml
image: archlinux
packages:
- ocaml
- ocaml-num
- camlp5
- dune
- time
```

This is probably because I do not have gtk installed, and `make -f Makefile.dune world` expects it is. @JasonGross  says it would be great to have a CI target that tests building coq when gtk and such are not installed.

I am currently just ignoring that error in my build script.

cc @ejgallego 

#### Coq Version

efed96f90c73d8e33a6a1eb0f4161dbdd7f7f533

**Comment by Zimmi48** [comment]
@andres-erbsen AFAIR there is already an appropriate target for what you want. See `makefile -f Makefile.dune` (no arguments) to get the help documentation.

**Comment by andres-erbsen** [comment]
Indeed, seems so -- `- coq: build package Coq [toplevel compilers, tools, stdlib, no GTK]`, confirming [here](https://builds.sr.ht/~andres/job/93786) just in case.

**Comment by ejgallego** [comment]
@andres-erbsen what's the problem here? We build Coq without GTK in our CI, and it works fine.

**Comment by andres-erbsen** [comment]
The `coq` target mentioned in my latest comment no longer exists. If there's an alternative already, that's great, let's document it.

**Comment by ejgallego** [comment]
Oh, I was not aware that target was removed.

The only change that needs to be done in the Makefile is to remove `coqide.install` from the `NONDOC_INSTALL_TARGETS` variables, the PR should be trivial (we could for example have a few more orthogonal package variables).

**Comment by ejgallego** [comment]
Maybe; tho note that `world` target is pretty old in the Coq world, so any change of semantics will likely create some problems to users. Maybe `world-noide`?

Also our default `world` target should run with the `release` profile, as it is a net time saver due to the gains in `coqc` efficiency.

**Comment by SkySkimmer** [comment]
The old `world` would autodetect if gtk is present (in configure), I guess we could do some autodetection too if we wanted

**Comment by ejgallego** [comment]
Yup, but that was a kind of misfeature for regular developers, in the sense that it is hard to guess the intention of the developer, and incomplete builds due to forgetting to run configure did happen IIRC.

Intentions are hard to guess, so I think different targets that fully capture the intention are best.
