### ISSUE TITLE
[coq_makefile] `VDFILE := .coqdeps` probably should not be fixed to a constant by default

### ISSUE THREAD

**Issue by pi8027** [coq/coq#10839]
#### Description of the problem

Currently, the filename of the dependency file is fixed to `.coqdep.d` in the `coq_makefile` utility. One can change it from outside as https://github.com/coq/coq/issues/10565#issuecomment-514817313 indicated, but this seems to be a potential pitfall when we place multiple `Makefile`s generated by the `coq_makefile` utility in the same directory. I think it is better to make `VDFILE` depend on the name of `Makefile` like `Makefile.coq.conf` by default if there are no compatibility issues.

#### Coq Version

master

**Comment by gares** [comment]
Sure, good advice. I suggest to name if `.<name>.d` as in `.Makefile.coq.d` when `coq_makefile` is called with `-o Makefile.coq`. It should be enough to use here
  https://github.com/coq/coq/blob/e01c9132fc505a3c443bee27d88dcd16a566616f/tools/CoqMakefile.in#L229
something like `@CONF_FILE@`, see also
  https://github.com/coq/coq/blob/e01c9132fc505a3c443bee27d88dcd16a566616f/tools/coq_makefile.ml#L125-L140
