### ISSUE TITLE
minor bug on documentation of advanced recursive functions limitations

### ISSUE THREAD

**Issue by MuseBoy** [coq/coq#10831]
https://coq.github.io/doc/v8.10/refman/language/gallina-extensions.html#advanced-recursive-functions

in the section Limitations

1.  what does `term_0` refer to?
2.  the first demo (Function wrong) has wrong output message. It should be

```
The command has indeed failed with message:
Recursive definition of wrong is ill-formed.
In environment
wrong : nat -> nat
C : nat
Recursive call to wrong has principal argument equal
to "C" instead of
a subterm of "C".
Recursive definition is:
"fun C : nat => hd 0 (map wrong (C :: nil))".
```

**Comment by Zimmi48** [comment]
Thanks for the report. These are still (sigh!) artifacts from the migration to Sphinx (more than a year ago). `term_0` should just be `term` as it refers to the body of the function definition. I have also fixed the imports so that the correct error message is shown. Cf. #10834.
