### ISSUE TITLE
Typeclass resolution triggers unexpected universe mismatch

### ISSUE THREAD

**Issue by charguer** [coq/coq#10847]
In Coq 8.10beta1, I have a weird behavior, that unexpectedly depends on the context of universes. I discovered this as trying to implement new features, now that @mattam82 has solved my previously-blocking issues.

I also have the same bug in the `notypeclasses-refine` branch for Matthieu's patch. I don't know about 8.9 because I'm using features in the rest of my files that are not 8.9-compatible.

```coq

Set Implicit Arguments.
Require Import List String.

Generalizable Variables A B.

Parameter val : Type.
Parameter val_unit : val.
Parameter val_constr : string -> list val -> val.


Class Enc (A:Type) : Type :=
  make_Enc { enc : A -> val }.

Hint Mode Enc + : typeclass_instances.

Instance Enc_unit : Enc unit.
Proof using. constructor. eapply (fun (x:unit) => val_unit). Defined.

Instance Enc_list : forall A `{Enc A}, Enc (list A).
Proof using. constructor. eapply (fix f (l:list A) :=
  match l with
  | nil => val_constr "nil" nil
  | x::l' => val_constr "constr" ((enc x)::(f l')::nil)
  end). Defined.


Class Decode (v:val) A `{EA:Enc A} (V:A) : Type :=
  make_Decode { decode : v = enc V }.

Arguments decode v {A} {EA} {V} {Decode}.

Instance Decode_enc : forall A `{EA:Enc A} (V:A),
  Decode (enc V) V.
Proof using. intros. econstructor. eauto. Defined.

Instance Decode_nil : forall A (EA:Enc A),
  Decode (val_constr "nil" nil) (@nil A).
Proof using. intros. constructor. eauto. Defined.

Lemma test_nil :
  (forall A1 (EA1:Enc A1) (V1:A1), @Decode (val_constr "nil" nil) A1 EA1 V1 -> True) ->
  True.
Proof.
  intros M. eapply M. 

  (* Here the goal is [@Decode (val_constr "nil" (@nil val)) ?A1 ?EA1 ?V1] *)

  eapply Decode_nil.
  (*--> normally, the above would produce:
       All the remaining goals are on the shelf: [Type] and [Enc ?Goal] *)

  (* --> However, in a context with more universe constraints, I obtain:
     Unable to unify "Type@{max(Set,list.u0)}" with "Type@{Sep.WPLifted.53}"
   *)

  (* --> note that, regardless of the context, it is always possible to kill the
         goal directly with: *)
  eapply (@Decode_nil unit).

Abort.
```

Unfortunately, it's hard to reduce the set of universe constraints without seing the bug go away.
I have never faced any error message of this form, so I am not sure where to start debugging.
@mattam82 we might need to have a live debugging session again.

**Comment by SkySkimmer** [comment]
>~~~
>  (* --> However, in a context with more universe constraints, I obtain:
>     Unable to unify "Type@{max(Set,list.u0)}" with "Type@{Sep.WPLifted.53}"
>  *)
> ~~~

Not much we can do without a test case that actually produces the error.

**Comment by charguer** [comment]
I don't know if this has been fixed somehow.
In any case, I am no longer using the "Decoder" class that triggered the problem, so this is not blocking for me.
