### ISSUE TITLE
Require Export Same Module Twice break unification?

### ISSUE THREAD

**Issue by Huxpro** [coq/coq#10869]
#### Description of the problem

The dependency graph is some thing like

```
        Int
       /    \
  Types      Values
       \    /
        Eval
```

If I used 

```coq
Require Export Int.
```

in both `Type.v` and `Value.v`
then I will hit errors like

```
(cannot unify "I32.t" and "Values.I32.t").
```
(Int contains a module `I32.t` made from a functor)

#### Coq Version

```
λ coqtop -v
The Coq Proof Assistant, version 8.8.2 (April 2019)
compiled on Apr 9 2019 4:40:30 with OCaml 4.05.0
```

**Comment by Huxpro** [comment]
The workaround I found is to use `Require Import` in one module then the unification pass through.

**Comment by JasonGross** [comment]
Do you have a small reproducible test case?  I don't see why `Values.I32.t` should exist at all unless you're using `Include` or similar; `Export` doesn't create new constants.

**Comment by SkySkimmer** [comment]
Please reopen if you have a reproduction case.
