### ISSUE TITLE
Numeral Notation is sensitive to the implicit status of `option`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10878]
#### Description of the problem

```coq
Require Import Coq.ZArith.ZArith.

Definition Zto_pos_opt (v : Z) : option positive
  := match v with
     | Zpos v => Some v
     | _ => None
     end.
Declare Scope mypos_scope.
Declare Scope mypos_scope2.
Numeral Notation positive Zto_pos_opt Zpos : mypos_scope. (* success *)
Arguments option {_}.
Fail Numeral Notation positive Zto_pos_opt Zpos : mypos_scope2.
(* Error:
Zto_pos_opt should go from Decimal.int to positive or (option positive).
Instead of Decimal.int, the types Decimal.uint or Z or Int63.int or Decimal.decimal could be used (you may need to require BinNums or Decimal or Int63 first).
 *)
```
This is due to the use of `mkRefC`:
https://github.com/coq/coq/blob/ac862fb5ae8eb15c15f81817d78ba8db4430ea8b/plugins/syntax/numeral.ml#L117

#### Coq Version

master

**Comment by JasonGross** [comment]
There is a similar issue with `String Notation`:
https://github.com/coq/coq/blob/ac862fb5ae8eb15c15f81817d78ba8db4430ea8b/plugins/syntax/string_notation.ml#L53-L57

**Comment by herbelin** [comment]
I would have said that this due to the `let cty = mkRefC ty` line. At least, the following fixes the issue:
```
diff --git a/plugins/syntax/number.ml b/plugins/syntax/number.ml
index 04cd4dde6c..c7c9d98b04 100644
--- a/plugins/syntax/number.ml
+++ b/plugins/syntax/number.ml
@@ -462,7 +462,7 @@ let vernac_number_notation local ty f g opts scope =
   let tyc_params = locate_global_inductive_or_int63_or_float env (via = None) ty in
   let to_ty = Smartlocate.global_with_alias f in
   let of_ty = Smartlocate.global_with_alias g in
-  let cty = mkRefC ty in
+  let cty = CAst.make (CAppExpl ((ty,None),[])) in
   let app x y = mkAppC (x,[y]) in
   let arrow x y =
     mkProdC ([CAst.make Anonymous],Default Glob_term.Explicit, x, y)
```
where the `CAppExpl` ensures that `ty` is interpreted as `@ty` (working at the level of `constr_expr` is a bit fragile though in general).

If this corresponds to your expected semantics, I can make a PR.

We can ask the same question for 2nd and 3rd arguments. Should we ensure that no implicit arguments are added? If yes, their `CRef` could similarly be replaced by `CAppExpl ((ty,None),[])`.

**Comment by proux01** [comment]
This code should probably be rewritten to work on econstr rather than costr_expr but since it fixes the bug, let's for now merge the PR if the CI is happy.
