### ISSUE TITLE
[dune] Digest-based builds need transitive dependency computation of ML plugin deps

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#10874]
**edit**: it seems `.vo` files do store the checksum of linked `.vo` files, so the above problem doesn't hold for the pure-`.vo` fragment, however that's still a problem for ML plugins.

As noted by @mattam82 on Gitter, the current dune-based build system doesn't always correctly rebuild target `.vo` files. This is mainly due to `Exports` and transitive side effects, in a sense, Coq's require is similar to linking, so when requiring library `A` we must also take into account the libraries and plugins library `A` is exporting.

**edit**: it seems `.vo` files do store checksums of imported `.vo` files so we should be safe in the `.vo` fragment, however that's still a problem w.r.t. plugins.

For example, if we have libraries `A` `B`, and `C`, with `B` exporting `A` and `C` requiring `B`, `coqdep` will only reflect the dependency of `C` on `B`, however, it does implicitly depend on `A` too. It could be the case that `A` does change, however `B`'s digest is the same, but changes in `A` should force a rebuild on `C`; right now we will incorrectly skip rebuilding `C`, as the implicit dependency on `A` is not taken into account.

A similar situation arises for plugins.

This seems like a hard problem to solve, we need to think about what the right approach here is.

Should we take into account in the transitive dep closure only modules that are under `Export`? Or can purely `Require`d modules also produce transitive implicit consistency invalidation.

What do you think @maximedenes ?

**Comment by ejgallego** [comment]
Yeah `Require` is akin to linking, also, OCaml-like more precise analysis together with `Export` like accounting won't be enough due to the implicit scope of side-effects of linking a library.

So I guess no other solution than handling `Require` a linking and thus computing the dep closure for now :( :(

**Comment by gares** [comment]
This is weird, since B.vo should include an md5sum of A.vo, so its checksum should change too when A is changed.

**Comment by ejgallego** [comment]
> This is weird, since B.vo should include an md5sum of A.vo, so its checksum should change too when A is changed.

Oh good point, so indeed that only happens then for ML plugins?

**Comment by SkySkimmer** [comment]
The original example was that adding some random newline in extratactics.mlg doesn't cause a full recompile, but adding a new tactic does. So it's not that it does something wrong, we just don't understand why it does what it does.

**Comment by ejgallego** [comment]
> Oh good point, so indeed that only happens then for ML plugins?

The original report by Matthieu was indeed about `ltac_plugin.cmxa` changing however the file declaring the ML plugin did have the same digest.

**Comment by ejgallego** [comment]
> So it's not that it does something wrong, we just don't understand why it does what it does.

I think we understand what is going on in the example, adding a new tactic does change the digest of the importing file as the libobject is different, however the file importing the ml plugin doesn't store the digest of the plugin [likely due to `byte` vs `native` problems] so here we have the problem.

Indeed the easiest part would be to store the digest of the plugins as it is done for `.vo` files, but I dunno what would be the best way to do it.

**Comment by ejgallego** [comment]
> it does something wrong

It definitively does something wrong, as you can change a tactic fully, and the `.vo` files using the tactic won't be rebuild .

**Comment by gares** [comment]
> Indeed the easiest part would be to store the digest of the plugins as it is done for `.vo` files

There is a libobject for the loading of the cmxs. I guess you can put, next to the file name its hash.

**Comment by ejgallego** [comment]
@gares what to do with byte vs native compile tho?

**Comment by gares** [comment]
I guess you hash the one you loaded.
I don't know what you do with dune, but I guess you compile .v file with one variant of coq (opt or byte) and that variant is not picked at random.

I can see how to trick it, but I don't see a real scenario in which hashing the plugin being actually loaded could trick an unconscious user.

**Comment by ejgallego** [comment]
> I don't know what you do with dune, but I guess you compile .v file with one variant of coq (opt or byte) and that variant is not picked at random.
> 
> I can see how to trick it, but I don't see a real scenario in which hashing the plugin being actually loaded could trick an unconscious user.

Indeed I guess a sensible policy is doable, tho I wonder if the default build should maybe include both hashes. I'll think about it and do a patch.

**Comment by SkySkimmer** [comment]
Reopened by #15220

**Comment by SkySkimmer** [comment]
Actually let's make a new issue
