### ISSUE TITLE
CoqIDE Windows: auto-hide task bar is not accessible when CoqIDE is full screen

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#10873]
With the Coq 8.10.0 Windows release version, if the task bar is set to auto-hide, the task bar does not come up as it should, if the mouse is moved to the bottom of the screen and CoqIDE is in full screen mode. Changing tasks with Alt tab does work, though.

This bug has been reported by Roger Witte on the coq-club mailin glist.

**Comment by roger-witte** [comment]
This is fixed in 8.12 beta 1

I haven't checked 8.11.2 but my guess it's the change from GTK window surround to windows window surround that did the trick

**Comment by ejgallego** [comment]
Thanks for the feedback @roger-witte
