### ISSUE TITLE
[LoadPath]One is unabled to import another unless two files are in the same directory

### ISSUE THREAD

**Issue by IronPanda0** [coq/coq#10893]
Here is the directory structure:
```
Volumes - UncleqSSD - Coq -lf - Lists.v/Lists.vo.....
                                                 |
                                                 -Exercise.v
```
I created my own file named "Exercise.v" located in " /Volumes/UncleqSSD/Coq" ,as follows:
Exercise.v
~~~
Add LoadPath "/Volumes/UncleqSSD/Coq/lf" as MyLF.
**From MyLF Require Import Lists.**
.....
~~~

Of course I've already compiled "Lists.v" into "Lists.vo"
I' d like to introduce something defined or proved in the file "Lists.v"
However，when it ran to the bold code CoqIDE showed me an error message :

"The file /Volumes/UncleqSSD/Coq/lf/Lists.vo contains library
LF.Lists and not library MyLF.Lists"

So I tried：

 “Require Import LF.Lists."
"Require Import MyLF.Lists."
"From LF Require Import Lists."
....
With different Error message, all failed.

Is it a bug or I made some mistake?

#### Coq Version

CoqIDE 8.10 For MacOS
The Coq Proof Assistant, version 8.8.2

**Comment by vbgl** [comment]
As a general remark, I think that you should not use “Add Loatpath” at all.

A quick way to overcome your issue might be to replace “… as MyLF” by “… as LF” since you’ve compiled a “LF” library and not at “MyLF” library.

**Comment by IronPanda0** [comment]
> As a general remark, I think that you should not use “Add Loatpath” at all.
> 
> A quick way to overcome your issue might be to replace “… as MyLF” by “… as LF” since you’ve compiled a “LF” library and not at “MyLF” library.

Thanks a lot.  If I don't use "Add LoadPath"  at all.

**Comment by IronPanda0** [comment]
> As a general remark, I think that you should not use “Add Loatpath” at all.
> 
> A quick way to overcome your issue might be to replace “… as MyLF” by “… as LF” since you’ve compiled a “LF” library and not at “MyLF” library.

Thanks a lot. I completely solved it via using "...as LF".

 If I don't use "Add LoadPath" I still cannot Import "/Volumes/UncleqSSD/Coq/lf/Lists.vo" into "/Volumes/UncleqSSD/Coq/Exercise.v".
 Maybe this website display the wrong structure. Actually, "Lists.vo" is in the subdirectory of the directory where "Exercise.v" is located.

**Comment by Zimmi48** [comment]
Software Foundations should generally work fine if you use the provided makefile to compile and an editor supporting `_CoqProject` (like CoqIDE or Emacs + Proof General).

>Of course I've already compiled "Lists.v" into "Lists.vo"

If you did so manually using `coqc` then it won't work because you won't have provided the same arguments.

**Comment by maximedenes** [comment]
> like CoqIDE or Emacs + Proof General

Or VsCoq ;)

**Comment by Zimmi48** [comment]
Thanks for confirming this. I wasn't quite sure ;-)

**Comment by IronPanda0** [comment]
> Software Foundations should generally work fine if you use the provided makefile to compile and an editor supporting `_CoqProject` (like CoqIDE or Emacs + Proof General).
> 
> > Of course I've already compiled "Lists.v" into "Lists.vo"
> 
> If you did so manually using `coqc` then it won't work because you won't have provided the same arguments.

 SF:Vol.1 Logical Foundation works well in CoqIDE.
In fact, All my operation was done in CoqIDE. My problem could be avoided via other ways.
But, at least for convenience, I don't have to use "ctrl+c" and "ctrl+v" so frequently.LOL

**Comment by Zimmi48** [comment]
If you use CoqIDE, then you should use the "Compile" > "Make" menu rather than "Compile" > "Compile buffer". That's all what I'm saying.

**Comment by IronPanda0** [comment]
Solved!

**Comment by Zimmi48** [comment]
@IronPanda0 You should really be more specific in your comments if you want this issue to be of any help to anyone beyond yourself. For instance, "Solved!" does not say whether you solved it by yourself or if the recommendation I made was useful.
