### ISSUE TITLE
Coercion not working with datatype

### ISSUE THREAD

**Issue by Huxpro** [coq/coq#10898]
```coq
Inductive X := .
Inductive Y := XY (x : X).
Coercion XY : X >-> Y.
Parameter x : X.
Example Ys1 : list Y := [XY x].
Print Ys1.
(* -->
   Ys1 = [x]
     : list Y
 *)

Fail Example Ys2 : list Y := [x].
Fail Example Ys3 : list Y := cons x nil.
(* -->
   Error: The term "[x]" has type "list X" while it is expected to have type "list Y".
*)
```

The interesting fact is that `Coercion` IS working in printing. 
While none of the notational list or explicit `cons` working.

I am not sure which behavior is not expected but definitely they are inconsistent with each other.

**Comment by Huxpro** [comment]
I found a similar issue https://github.com/coq/coq/issues/5462 but not sure what's the status.

**Comment by vbgl** [comment]
The elaboration mechanism that introduce coercions does not take into account the top-level type annotation: the term on the right of the “:=” is only checked to have the type written in the annotation.

You can write for instance:

~~~
Example Ys2 := [ x : Y ]%list.

Example Ys3 := @cons Y x nil.
~~~

The “program mode” however uses so-called bidirectional type inference, so your examples work in that mode:

~~~
Program Example Ys4 : list Y := [ x ].
Program Example Ys5 : list Y := cons x nil.
~~~

Finally, Coq 8.11 will have “[bidirectionality hints](https://coq.github.io/doc/master/refman/language/gallina-extensions.html#bidirectionality-hints)”. You will then be able to write the following:

~~~
Arguments cons & _ _ _.

Example Ys6 : list Y := [ x ].
~~~

**Comment by SkySkimmer** [comment]
Yes, it fails the "uniform inheritance condition", cf https://coq.github.io/doc/master/refman/addendum/implicit-coercions.html#coercions
