### ISSUE TITLE
anomaly kernel doesn't support existentials with Declare + side effects

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#10890]
~~~coq
Require Import Derive.

Derive foo SuchThat (foo = foo :> nat) As bar.
Proof.
  Unshelve.
  2:abstract exact 0.
   exact eq_refl.
Defined. (* or Qed: anomaly kernel doesn't support existential variables *)
~~~
This is linked to https://github.com/coq/coq/blob/7f039cac07526881da1a149b8c0e49be32c2e89e/tactics/proof_global.ml#L177-L181
Since there are side effects the type doesn't get evar-normalized, and the type for the second entry is an evar.
See also 11cdf7c2ca0017f6bae906f9c9d9eef41972affe which introduced the `seff != empty` test.

**Comment by ejgallego** [comment]
Seem fixed in `master`
