### ISSUE TITLE
Set Default Proof Mode is not documented, and is important to mix Ltac2 and Ltac1.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#10909]
It is just hinted in the doc in a single example, that starts with:

```
From Ltac2 Require Import Ltac2.
Set Default Proof Mode "Classic".
```

And it should be made more explicit.

The option `Set Default Proof Mode` is not documented at all, and neither are its possible values, which include at least "Noedit", "Classic" and "Ltac2".

**Comment by ppedrot** [comment]
Postponing, but should definitely be solved by the time of the 8.11 release.
