### ISSUE TITLE
Ltac2 and Ltac1 together: fragile parsing.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#10908]
#### Description of the problem

Reusing an example of the reference manual, this works fine:

```
From Ltac2 Require Import Ltac2.
Set Default Proof Mode "Classic".
Goal True.
Proof.
ltac2:(fail).
```

This as well:
```
From Ltac2 Require Import Ltac2.
Set Default Proof Mode "Classic".
Goal True.
Proof.
idtac; ltac2:(fail).
```

But this doesn't work (doesn't parse):
```
From Ltac2 Require Import Ltac2.
Set Default Proof Mode "Classic".
Ltac mytac tac := idtac "I am being evaluated"; tac.
Goal True.
Proof.
mytac (idtac; ltac2:(fail)).
```

To make it parse, you have to replace `;` within the parentheses with `>`, which doesn't make any sense.

#### Coq Version

8.11

**Comment by ppedrot** [comment]
This has nothing to do with Ltac2, it's due to the parsing semantics of Ltac1. You have to wrap complex Ltac expressions in applications inside a `ltac:(...)` quotation, like this:
```
From Ltac2 Require Import Ltac2.
Set Default Proof Mode "Classic".
Ltac mytac tac := idtac "I am being evaluated"; tac.
Goal True.
Proof.
mytac ltac:(idtac; ltac2:(fail)).
```

**Comment by ppedrot** [comment]
(I think you can close that as a WONTFIX or INVALID, because fixing it essentially amounts to rewriting any single Ltac script in the wild.)

**Comment by Zimmi48** [comment]
OK
