### ISSUE TITLE
Anomaly "Uncaught exception Sys_blocked_io."

### ISSUE THREAD

**Issue by llelf** [coq/coq#10918]
#### Description of the problem

At least in `bash`, if the `stdin` is in the non-blocking mode (e. g. from the previous running process in the shell), `coqtop` will die upon its start, flooding with messages
```
Error: Anomaly "Uncaught exception Sys_blocked_io."
Please report at http://coq.inria.fr/bugs/.
```

The easy real-world way to reproduce is to start `coqtop` after forcibly `SIGKILL`ing Erlang REPL (start `erl` and press `^c a`).

More info (bash): https://lists.gnu.org/archive/html/bug-bash/2017-01/msg00039.html

#### Coq Version

8.9.1, 8.10.0, master (and likely many many more)

#### Note

This can be WONTFIX.  I’m posting the issue for the record and to save time for the next person who may encounter this (not very obvious) behaviour.

**Comment by gares** [comment]
Are you saying that `erl` REPL leaves stdin garbled?

**Comment by llelf** [comment]
@gares if you forcibly kill it.

**Comment by gares** [comment]
Hum, I'd call that a kill -9, here you write `^c a` that seems a "please exit" to me. Sorry I don't know erl very well.

**Comment by llelf** [comment]
It’s more like a “please immediately abort”, akin to kill -9.
