### ISSUE TITLE
coqpp fails on Windows with "is not a bytecode executable file"

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#10921]
#### Description of the problem

```
$ cat make.sh
#!/usr/bin/env bash

set -ex

cat > _CoqProject <<EOF
-R . Top
-I .
foo.mlg
foo.mllib
EOF

cat > foo.mlg <<EOF
DECLARE PLUGIN "foo"
EOF

cat > foo.mllib <<EOF
Foo
EOF

coq_makefile -f _CoqProject -o Makefile

make clean && make VERBOSE=1

$ ./make.sh
+ cat
+ cat
+ cat
+ coq_makefile -f _CoqProject -o Makefile
+ make clean
CLEAN
+ make VERBOSE=1
"coqdep" -dyndep var -f _CoqProject   > ".coqdeps.d" || ( RV=$?; rm -f ".coqdeps.d"; exit $RV )
*** Warning: foo.mllib already found in . (discarding ./foo.mllib)

*** Warning: foo.mlg already found in . (discarding ./foo.mlg)

"coqpp" foo.mlg
Fatal error: the file 'foo.mlg' is not a bytecode executable file
"coqpp" foo.mlg
Fatal error: the file 'foo.mlg' is not a bytecode executable file
make --no-print-directory -f "Makefile" pre-all
"coqpp" foo.mlg
Fatal error: the file 'foo.mlg' is not a bytecode executable file
if [ "8.10.0" != "8.10.0" ]; then\
  echo "W: This Makefile was generated by Coq 8.10.0";\
  echo "W: while the current Coq version is 8.10.0";\
fi
make --no-print-directory -f "Makefile" real-all
"coqpp" foo.mlg
Fatal error: the file 'foo.mlg' is not a bytecode executable file
"C:\ci\cygwin64_27101_29830\usr\x86_64-w64-mingw32\sys-root\mingw\bin/ocamlfind.exe" opt      -linkpkg -dontlink unix,str  -thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence -I .  -I "D:\Coq-8.10/lib/coq//config"  -I "D:\Coq-8.10/lib/coq//lib"  -I "D:\Coq-8.10/lib/coq//clib"  -I "D:\Coq-8.10/lib/coq//kernel"  -I "D:\Coq-8.10/lib/coq//library"  -I "D:\Coq-8.10/lib/coq//engine"  -I "D:\Coq-8.10/lib/coq//pretyping"  -I "D:\Coq-8.10/lib/coq//interp"  -I "D:\Coq-8.10/lib/coq//gramlib"  -I "D:\Coq-8.10/lib/coq//gramlib/.pack"  -I "D:\Coq-8.10/lib/coq//parsing"  -I "D:\Coq-8.10/lib/coq//proofs"  -I "D:\Coq-8.10/lib/coq//tactics"  -I "D:\Coq-8.10/lib/coq//toplevel"  -I "D:\Coq-8.10/lib/coq//printing"  -I "D:\Coq-8.10/lib/coq//ide"  -I "D:\Coq-8.10/lib/coq//stm"  -I "D:\Coq-8.10/lib/coq//vernac"  -I "D:\Coq-8.10/lib/coq//plugins/btauto"  -I "D:\Coq-8.10/lib/coq//plugins/cc"  -I "D:\Coq-8.10/lib/coq//plugins/derive"  -I "D:\Coq-8.10/lib/coq//plugins/extraction"  -I "D:\Coq-8.10/lib/coq//plugins/firstorder"  -I "D:\Coq-8.10/lib/coq//plugins/fourier"  -I "D:\Coq-8.10/lib/coq//plugins/funind"  -I "D:\Coq-8.10/lib/coq//plugins/ltac"  -I "D:\Coq-8.10/lib/coq//plugins/micromega"  -I "D:\Coq-8.10/lib/coq//plugins/nsatz"  -I "D:\Coq-8.10/lib/coq//plugins/omega"  -I "D:\Coq-8.10/lib/coq//plugins/rtauto"  -I "D:\Coq-8.10/lib/coq//plugins/setoid_ring"  -I "D:\Coq-8.10/lib/coq//plugins/ssr"  -I "D:\Coq-8.10/lib/coq//plugins/ssrmatching"  -I "D:\Coq-8.10/lib/coq//plugins/syntax" -warn-error +a-3  -a -o foo.cmxa
/bin/sh: C:\ci\cygwin64_27101_29830\usr\x86_64-w64-mingw32\sys-root\mingw\bin/ocamlfind.exe: No such file or directory
make[1]: *** [Makefile:621: foo.cmxa] Error 127
make: *** [Makefile:321: all] Error 2

```

#### Coq Version

8.10.0 (installed from https://github.com/coq/coq/releases/download/V8.10.0/coq-8.10.0-installer-windows-x86_64.exe)

**Comment by JasonGross** [comment]
cc @ppedrot @MSoegtropIMC

**Comment by ppedrot** [comment]
Hmm, this is strange, it looks like you're missing a value for the ocamlrun command or something. In any case, there is no way on earth the mlg is going to be OCaml bytecode, so something is messed up in the shell calls.

**Comment by JasonGross** [comment]
@ppedrot Does `coqpp` call out to the shell?  Even if I invoke it myself, I get the same error:
```
$ coqpp foo.mlg
Fatal error: the file 'foo.mlg' is not a bytecode executable file
```
(On linux, the invocation works fine.)  There is another issue going on here, which is that the Coq installer does not seem to have installed any of the ocaml executables and also emits the wrong location for ocamlfind, which I have reported separately as https://github.com/coq/coq/issues/10922

**Comment by ppedrot** [comment]
That's very strange to say the least. `coqpp` is literally just a script parsing a file and outputing some data, no shell involved at all. What does `ocamlrun coqpp foo.mlg` does?

**Comment by JasonGross** [comment]
Similar error
```
$ ocamlc -v
The OCaml compiler, version 4.04.2
Standard library directory: /usr/lib/ocaml

$ which ocamlrun
/usr/bin/ocamlrun

$ ocamlrun coqpp foo.mlg
Fatal error: the file '/cygdrive/d/Coq-8.10/bin/coqpp' is not a bytecode executable file
```

**Comment by MSoegtropIMC** [comment]
I will have a look at it on Wednesday.

**Comment by JasonGross** [comment]
Bump @ppedrot @MSoegtropIMC any progress on this?

**Comment by andrew-appel** [comment]
Now coqpp fails on Windows with a different error message:
```
the file 'src/abstraction.mlg' has not the right magic number: expected Caml1999X027, got c t
  }
END
```
This is on my Coq 8.11.2 installation:
```
$ coqpp -version
The OCaml runtime, version 4.10.0
```

**Comment by JasonGross** [comment]
@andrew-appel Did you compile Coq on Windows yourself?  This looks like it might be an issue having your system OCaml be different from the one that compiled Coq.

**Comment by andrew-appel** [comment]
No, I did not compile it myself, I used the standard package:  
[coq-8.11.2-installer-windows-i686.exe](https://github.com/coq/coq/releases/download/V8.11.2/coq-8.11.2-installer-windows-i686.exe)

**Comment by JasonGross** [comment]
It's not possible to compile OCaml plugins on Windows unless you have exactly the same OCaml setup as was used to compile Coq.  The easiest thing to do here is to compile Coq from source yourself.  See also #10922

**Comment by MSoegtropIMC** [comment]
@Andrew: I am not sure I understand what you want to achieve. If you want to compile e.g. a plugin so that it is compatible with Coq 8.11.2, the best way is to use the build script we use to compile the installer. This script sets up a fresh cygwin in a path you can configure, compiles Coq and everything and leaves you in this cygwin a build system which is at least good enough to compile Coq and all delivered plugins. The only manual work with this is that you have to give the options to this script.

So the procedure is (in a command shell with git ready or do the git otherwise and just CD to the coq folder)
```
git clone https://github.com/coq/coq.git
cd coq
git checkout V8.11.2    <<<< This is important to get exactly the same ocaml and everything as in 8.11.2
cd dev/build/windows

download cygwin 64 bit setup and put it into this folder e.g.
powershell -Command "(New-Object Net.WebClient).DownloadFile('http://www.cygwin.com/setup-x86_64.exe', 'setup-x86_64.exe')"

  SET EXTRA_ADDONS=^
    -addon=bignums ^
    -addon=equations ^
    -addon=mtac2 ^
    -addon=mathcomp ^
    -addon=menhir ^
    -addon=compcert ^
    -addon=extlib ^
    -addon=quickchick ^
    -addon=coquelicot ^
    -addon=vst ^
    -addon=aactactics ^
    -addon=flocq ^
    -addon=interval ^
    -addon=gappa_tool ^
    -addon=gappa

MakeCoq_MinGW.bat -threads=16 ^
  -arch=64 -installer=N -coqver="/cygdrive/c/<your coq root folder with / slashes> ^
  -destcyg=<your cygwin destination folder (Windows)> ^
  -destcoq=<your coq destination folder in windows format (Windows)> 
  -cygcache=<your local cygwin cache folder> ^
  %EXTRA_ADDONS% ^
  -setup setup-x86_64.exe
```
(I hope I cut and pasted this correctly)

The cygwin repo we use recently has hickups. In case you have issues with this, give a different one with the -cygrepo=url option from here: (https://cygwin.com/mirrors.html)

There are also command line options to install Coq inside of the cygwin rather than in a separate folder. See the Readme.txt in the same folder as the batch file. If you install to a separate folder it is easier to zip and give to someone else.

Sorry for the messy command line - historic reasons - I am working on a new one right now (opam based, will come soon).

**Comment by andrew-appel** [comment]
I was just trying to compile metacoq, which is indeed a plugin.  Now that I understand better, I see in hindsight that much confusion (and time spent by several people) could have been avoided if only the following were true:

coqpp should give an error message "Your ocaml configuration does not match the ocaml configuration under which coq was compiled.  Plug-ins can only be compiled using the same ocaml configuration as coq.  The only reliable way to achieve that is to compile coq yourself."

This would have been much more explanatory.

**Comment by JasonGross** [comment]
I think this would be better as a feature request for coq_makefile.  I'll go make a separate issue for it

**Comment by MSoegtropIMC** [comment]
@andrew-appel : it is partly also my fault - I never came up with an easy enough setup for Coq development on Windows. The CI build scripts are rather awkward to use for this purpose. Hopefully this changes with the new opam based Coq platform build scripts.

**Comment by ejgallego** [comment]
I am closing this in favor of #12656
