### ISSUE TITLE
Arrow containing Shortcuts on Linux do not work for Navigation

### ISSUE THREAD

**Issue by LukasKiederle** [coq/coq#10946]
#### Description of the problem

Arrow related Shotcuts do not work. This was already described in ticket #1742 for windows some years ago.

Shortcuts that do not work:

**Navigation** 
  - Forward
  - Backward
  - Go To

All the other ones work as expected.

### Environment:
I use the CoqIde on Linux Ubuntu 16.04 LTS.

#### Coq Version
**coqtop -v output:**
`The Coq Proof Assistant, version 8.4pl4 (November 2015)
compiled on Nov 04 2015 12:56:53 with OCaml 4.02.3
`

#### What I tried so far:

I changed my key bindings multiple times in  ~/.config/coq/coqide.keys and restarted my CoqIde.
The result was the same as stated above.

**Comment by vbgl** [comment]
Thanks for your report. The version of Coq that you use is _very_ old and no longer maintained. Would it be possible for you to use a more recent version of Coq, e.g. 8.9.1?

**Comment by Zimmi48** [comment]
Coq 8.4pl4 is probably the version that was available to you through `apt-get` on Ubuntu 16.04 LTS. If you update to Ubuntu 18.04 (the latest LTS), you will get Coq 8.6 (which is still quite old). If you update to Ubuntu 19.10 (the latest Ubuntu), you will get Coq 8.9.1. But, it may be a bit much to update Ubuntu just to get a newer version of Coq. You can also install any Coq version by using opam (https://coq.inria.fr/opam-using.html).

**Comment by LukasKiederle** [comment]
I will try to update to a newer version asap. I am currently a little bit busy, so it might take some days.

**Comment by LukasKiederle** [comment]
I just checked the the shortcuts in coq 8.10.0. The shortcuts are working fine.
