### ISSUE TITLE
coq doesn't open saved file

### ISSUE THREAD

**Issue by nishadawani** [coq/coq#10954]
i just downloaded coqide 8.10 and when i try to open a previously saved file, the software just closes. 
i'm able to open file in 8.9 but not 8.10
the name ends with ".v" so it's not because of that

**Comment by cpitclaudel** [comment]
Does that happen with any file, or just one specific one? If the latter, can you show the file?

**Comment by nishadawani** [comment]
any file

**Comment by Zimmi48** [comment]
FTR I cannot reproduce the problem on my Linux machine (using the Nix package), as one would have expected, however, I see a warning when opening a `.v` file: "Loading file /home/.../.foo.aux: /home/.../.foo.aux: No such file or directory". I have no idea if this could be related and could crash CoqIDE on other platforms.

**Comment by ejgallego** [comment]
Closing due to lack of feedback.
