### ISSUE TITLE
Feature request: print definitions with implicit annotations

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#10961]
### Description of the problem

It's currently hard to know which arguments of a constructor or function are implicit. 

* Check doesn't say say anything about them:

    ```coq
    Check Coq.Classes.RelationClasses.symmetry.
    (* RelationClasses.symmetry : forall x y : Prop, x <-> y -> y <-> x *)
    ```

* `About` uses an explicit list that's hard to read, and mentions argument names that do not appear int the actual signature (like `Symmetric` below)

    ```
    RelationClasses.symmetry :
    forall (A : Type) (R : Relation_Definitions.relation A),
    RelationClasses.Symmetric R -> forall x y : A, R x y -> R y x

    Arguments x, y are implicit
    Arguments A, R, Symmetric are implicit and maximally inserted
    Argument scopes are [type_scope _ _ _ _ _]
    ```

### Proposal

1. Change the output of `Check` to use curly braces for maximally inserted implicits.  In the future if syntax is added for non-maximally inserted, use that syntax in the output of Check too:

    ```coq
    Check @Coq.Classes.RelationClasses.symmetry.
    @RelationClasses.symmetry
     : forall {A : Type} {R : Relation_Definitions.relation A}
       {RelationClasses.Symmetric R}, forall x y : A, R x y -> R y x
    ```

2. Change the output of `About` to use a single `Arguments` command:

    ```coq
    Arguments symmetry {A} {R} {Symmetric} [x] [y] _.
    ```

Are either of these achievable?
Thanks!

#### Coq Version

8.9.1

**Comment by cpitclaudel** [comment]
Also, a real-life example:

```
interp_prog :
forall (rl_t rg_t x_fn_t : Type) (R : rg_t -> nat)
  (Sigma : x_fn_t -> Signature) (REnv : Env rg_t),
env_t REnv (fun idx : rg_t => val (R idx)) ->
(forall f : x_fn_t, Sigma f) ->
forall (rw : nat -> Type) (n : nat), prog R Sigma n -> val n

Arguments rl_t, rg_t, x_fn_t, R, Sigma, REnv, rw, n are implicit and maximally inserted
Argument scopes are [type_scope type_scope type_scope function_scope function_scope _ _ function_scope
  function_scope nat_scope _]
interp_prog is transparent
```

**Comment by SkySkimmer** [comment]
`@foo` is foo without the implicits so we shouldn't print `@foo : forall {bla}, ...`

The About proposal I agree with.

**Comment by SkySkimmer** [comment]
BTW it would be `Arguments symmetry {A%type} {R} {Symmetric} [x] [y] _.` (or `{A}%type`, both seem to be accepted) since `Arguments` handles argument scopes too.

**Comment by cpitclaudel** [comment]
> BTW it would be Arguments symmetry {A%type} {R} {Symmetric} [x] [y] _.

Yup, that would be great.

> @foo is foo without the implicits so we shouldn't print @foo : forall {bla}, ...

Good point; but then should `Check foo` include the implicits?

**Comment by SkySkimmer** [comment]
We should leave Check alone

**Comment by SkySkimmer** [comment]
See #10985

**Comment by cpitclaudel** [comment]
Btw, there was also this request: https://github.com/coq/coq/issues/5070
