### ISSUE TITLE
Unable to scroll through tabs in IDE

### ISSUE THREAD

**Issue by Alizter** [coq/coq#10986]
#### Description of the problem

Since compiling coqide with gtk3 I am unable to use the mouse scroll in order to quickly scroll through tabs.

The old version of coqide that used gtk2 had this feature.

#### Coq Version

```
The Coq Proof Assistant, version 8.11+alpha (October 2019)
compiled on Oct 27 2019 18:28:14 with OCaml 4.05.0
```

**Comment by XVilka** [comment]
If it is an issue with lablgtk3, then it is better to report it now, because the first stable release is going to be done soon - https://github.com/garrigue/lablgtk/issues/90

**Comment by Alizter** [comment]
I'm closing this issue since it looks like it will never be fixed. The problem stems from design decisions from gtk: https://bugzilla.gnome.org/show_bug.cgi?id=793824
