### ISSUE TITLE
Instance vs Program Instance since Coq 8.10

### ISSUE THREAD

**Issue by Zeimer** [coq/coq#10993]
I noticed that since Coq 8.10 the behaviour of the `Instance` command changed substantially. Now `Instance` is happy only if all fields are provided and results in an error otherwise. To be able to define some fields in proof mode, we have to use `Program Instance`, but then all the fields turn into proof obligations, which means we have to use `Next Obligation ... Qed/Defined` for every single one of them. This is very annoying and broke pretty much every single typeclass instance I have ever written in Coq. Not to mention that `Program Instance` sometimes generates additional obligations which are quite useless (for example I encountered one when using a pattern match like `| _, _ => ...`).

Is there any chance of getting back the old behaviour of `Instance`?

**Comment by SkySkimmer** [comment]
>Is there any chance of getting back the old behaviour of Instance?

Not really.

Instead of Program you can just move the term to the proof, ie replace 
~~~coq
Instance foo : bla := bli.
Proof. some tactics. Defined.
~~~
by
~~~coq
Instance foo : bla.
Proof. refine bli. some tactics. Defined.
~~~

**Comment by Zeimer** [comment]
I know, but this still requires either lots of manual labor or at least some find-and-replace regex hacking. Is there somebody who knows what was the point of this change?

**Comment by Zimmi48** [comment]
Indeed, there were several changes related to `Instance` which are documented in the [changelog](https://coq.inria.fr/refman/changes.html#other-changes-in-8-10-beta1) with links to the corresponding PRs:

>- Declare Instance now requires an instance name.
>  The flag Refine Instance Mode has been turned off by default, meaning that Instance no longer opens a proof when a body is provided. The flag has been deprecated and will be removed in the next version.
>  (#9270, and #9825, by Maxime Dénès)
>
>- Command Instance, when no body is provided, now always opens a proof. This is a breaking change, as instance of `Instance ident1 : ident2.` where `ident2` is a trivial class will have to be changed into `Instance ident1 : ident2 := {}.` or `Instance ident1 : ident2. Proof. Qed.`
>  (#9274, by Maxime Dénès).

In particular, the one you mentioned is the first of the two. In 8.10, you can turn back on the [Refine Instance Mode](https://coq.inria.fr/refman/addendum/type-classes.html#coq:flag.refine-instance-mode) flag but this flag has been removed in the upcoming 8.11 version, so this would only be a short postponement of the problem, leaving you time to fix it little by little.

The goal of this change was to help determine statically which commands open the proof mode and which do not (given that opening the proof mode changes the parser, this was an important step in making it possible to parse a Coq document without executing it cf. the referenced PRs).

**Comment by Zimmi48** [comment]
> To be able to define some fields in proof mode, we have to use `Program Instance`, but then all the fields turn into proof obligations, which means we have to use `Next Obligation ... Qed/Defined` for every single one of them.

I don't understand this BTW. You can still provide some fields when you define the instance, and only defer the others as obligations with `Program Instance`.
