### ISSUE TITLE
Reference ! default goal selector from bullet documentation.

### ISSUE THREAD

**Issue by TheoWinterhalter** [coq/coq#11036]
#### Description of the problem

As far as I know, there is currently no way to force usage of bullets, or I would expect it to appear [in the documentation of `Set Bullet Behavior`](https://coq.inria.fr/refman/proof-engine/proof-handling.html#set-bullet-behavior).
Bullets are great as they allow you to write *robust* proofs, however this robustness is greatly hindered by the fact they are not mandatory, *i.e.*, you are not *required* to use bullets whenever several goals are generated, applying any tactic will focus the first subgoal. 
Then, proofs might break because what was generating one subgoal does now generate several, and the tactics are then applied to the first one.

I would like to see some `Set Bullet Behavior Mandatory` to limit auto-focusing of subgoals to the case where there is only one. Otherwise the user would have to use goal selectors and/or bullets.

I strongly believe this should be the default behaviour,  but just having the option would be great.

**Comment by SkySkimmer** [comment]
You can actually do `Set Default Goal Selector "!".` https://coq.github.io/doc/master/refman/proof-engine/tactics.html#coq:opt.default-goal-selector
We could put a reference to that next to the bullet stuff.

**Comment by TheoWinterhalter** [comment]
Oh thanks! That's pretty neat. I don't know if I should leave my issue open or it should be about adding a reference to the doc.
