### ISSUE TITLE
Notations for coercions make coercions always visible

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#11033]
#### Description of the problem

Please consider the following test case:

```coq
Section Test.

Variables (A B : Type) (a : A) (b : B).
Variable c : A -> B.
Coercion c : A >-> B.

Notation COERCION := (c).

Goal b = a.
(**
The goal is displayed as
  b = COERCION a

but
  b = a
is expected
*)
Abort.

End Test.
```

The real issue arises when using e.g. `predI` from `ssrbool`.
`(predI a a) x = a x && a x` is displayed as `pred_of_simpl (predI a1 a2) x = a1 x && a2 x`

#### Coq Version

8.10.0 and 8.11+alpha (ab8ed0a39e7e39573716a473618ed4f7c219d072)

(The issue does not appear on Coq 8.9.1)

**Comment by gares** [comment]
We should really put some ci tests on the printer...

**Comment by gares** [comment]
bisecting now
