### ISSUE TITLE
binaries contain build time

### ISSUE THREAD

**Issue by olafhering** [coq/coq#11037]
#### Description of the problem

I packaged coq in [ocaml-coq](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml-coq) and noticed that each rebuild would publish a new binary, even with unchanged sources.

Storing random dates in binaries was never a useful way to track versions or variants. There is something what Debian sells as [reproducible builds](https://reproducible-builds.org/), but openSUSE just wants to reduce the load on its mirrors.

My workaround for the time being looks like this:

````diff
devel:languages:ocaml/ocaml-coq $ osc diff
Index: ocaml-coq.spec
===================================================================
--- ocaml-coq.spec      (revision 1)
+++ ocaml-coq.spec      (working copy)
@@ -54,6 +54,10 @@
 %build
 rm -rf doc
 rm -rf user-contrib/Ltac2/
+sed -i~ "
+s@Unix.time[[:blank:]]*([[:blank:]]*)@123467890.@
+" configure.ml
+diff -u "$_"~ "$_" && exit 0
 dune_release_pkgs='coq,coqide,coqide-server'
 %ocaml_dune_setup
 %ocaml_dune_build
````

For sort: do not store the result of `date` in binaries.

#### Coq Version
commit 66c7622ba8, v8.11 branch

**Comment by olafhering** [comment]
Using `date` was probably the SCM prior commit b4a932fad87 ...

**Comment by ejgallego** [comment]
Hi @olafhering , indeed we are aware of this problem; see for example #483 

The current plan is to use https://dune.readthedocs.io/en/stable/dune-libs.html#build-info , will that be enough to obtain reproducible builds?

**Comment by olafhering** [comment]
I think so, the `version` will be static for source-releases.
