### ISSUE TITLE
Remnants of "Template polymorphism breaks Prop/Set separation"

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#11044]
ie https://github.com/coq/coq/issues/9294

IIUC there are probably proofs of False based on that issue remaining when using a plugin as the kernel doesn't verify that the universes of the inductive are fresh, and the checker can't verify it as it doesn't have enough information.

**Comment by ppedrot** [comment]
I think that this has been solved by #11528.

**Comment by ppedrot** [comment]
Let's close since we don't have a reproducible test and the underlying issue has probably been fixed.
