### ISSUE TITLE
Ltac2 should prevent redefinition of open type's constructors

### ISSUE THREAD

**Issue by kyoDralliam** [coq/coq#11046]
#### Description of the problem

Ltac2 currently allows for constructors of open types to be redefined while assuming the opposite.

```coq
From Ltac2 Require Import Ltac2.
Ltac2 Type t := [..].
Ltac2 Type t ::= [A(int)].
Ltac2 z := A 3.
Ltac2 Type t ::= [A(bool)].
Ltac2 Eval z.
```
produces `Anomaly "File "user-contrib/Ltac2/tac2print.ml", line 120, characters 10-16: Assertion failed."`

#### Coq Version
Coq master b0fe318ea3b54f6f5f4c911bfb0e8523405e8c5c

**Comment by JasonGross** [comment]
I suppose if you try to `Require` two different files which define constructors of open types with non-unifying types, that should be an error, too.

cc @ppedrot

**Comment by ppedrot** [comment]
@JasonGross no, this is fine because names are qualified. What should be prevented is defining twice the same name in the same module.
