### ISSUE TITLE
[ci] disk space on workers

### ISSUE THREAD

**Issue by gares** [coq/coq#11055]
Dear @coq/ci-maintainers I did investigate failures of the `build:quick` job, and it is due to full hard drive. On my PC The sources of Coq (including .git) use 220M, building Coq requires extra 728M, and QUICK=1 adds 3.4G of .vio files.

Is there a known disk limitation on our workers?
Can we build this job on a machine with 5G free disk?

Note to self: gzipping .vio files brings them to 1.5G

**Comment by ejgallego** [comment]
Standard `.vo` files for the Coq build take 49M, in "quick" mode are turned into 3.5 GiB of `vio` files, it seems a tad too much for me, I guess this is not going to scale for some other developments.

Do you have a link to a concrete build failure?

**Comment by gares** [comment]
https://gitlab.com/coq/coq/-/jobs/342068626

**Comment by gares** [comment]
The full odd order is 3G, so it clearly depends on what you do. IIRC functors inflate a lot.

**Comment by ejgallego** [comment]
It seems workers do have enough space for now.
