### ISSUE TITLE
`clear` doesn't clear arguments of functions 

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#11056]
#### Description of the problem

The following example succeeds:

```coq
  Definition test (n: nat) :=
    ltac:(clear; match goal with
                 | [ H: ?t |- _ ] => exact H
                 end).
```

Shouldn't `clear` get rid of the `n: nat` hypothesis, causing the script to fail?

#### Coq Version

8.9.1

**Comment by SkySkimmer** [comment]
The goal is an existential variable which may use `n`, so it doesn't get cleared. 
This is expected behaviour AFAICT.

**Comment by SkySkimmer** [comment]
Note that for instance 
~~~coq
  Definition test (n: nat) : nat  :=
    ltac:(clear; match goal with
                 | [ H: ?t |- _ ] => exact H
                 end).
~~~
fails as you expect.
