### ISSUE TITLE
Enhance prodn in .rst doc files to cleanly support multiple productions in a prodn

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#11072]
@Zimmi48 and I have discussed documenting grammar productions using the `prodn` construct instead of `productionlist` to be more user-friendly.  Prodn lets you put optional items, alternatives and lists in-line while using a productionlist requires defining additional nonterminals.  (For user clarity, we don't want to overload characters such as `[` and `]` to mean literal characters in one production but metacharacters in others.)

For example, this prodn includes a list of idents in-line:

![image](https://user-images.githubusercontent.com/1253341/68431927-370c4900-0168-11ea-9233-5d12e3154077.png)

for which the productionlist needs multiple lines.  This is more verbose and thus harder to read:

![image](https://user-images.githubusercontent.com/1253341/68432686-ca924980-0169-11ea-996a-cc5d27790db9.png)

Here's an example of how the current prodn code handles multiple productions:

```
.. prodn::
   term += let: @pattern := @term in @term
   a_longer_nonterminal += let: @pattern := @term in @term
   another_term += let: @pattern := @term in @term let: @pattern := @term in @term let: @pattern := @term in @term
```

![image](https://user-images.githubusercontent.com/1253341/68433783-3d9cbf80-016c-11ea-856d-330957660bbf.png)

This would be look better (less cluttered) with
- a single blue box for the background, with only a single dark blue highlight across the top  (Alternatively, do we really need the box or the highlight?  productionlist doesn't have either.  The document would be even less cluttered without them.)
- aligning the `+=` for better readability (more like productionlist)
- giving extra indentation for productions that wrap to subsequent lines, probably lining up just to the right of the `+=`

**Comment by jfehrle** [comment]
I started looking at how to do this but didn't get too far.  For example, I can see where the colors #e7f2fa (the blue background) and #6ab0de (the darker blue highlight) are defined in CSS files but when I tried changing these to red as an initial experiment, I didn't get any change in appearance.  I don't do CSS or HTML every day.

@cpitclaudel I think you know this code best.  Perhaps you could get me pointed in the right direction?  Or if you have the time and inclination to take this issue on, that would be even better and much appreciated.

**Comment by cpitclaudel** [comment]
I'd be wary of deviating too much from the sphinx theme that we had, for consistency, but maybe we should indeed use the productionlist templates for these.  Your css changes were in the right direction, I think; can you show what you did exactly?

**Comment by Zimmi48** [comment]
> maybe we should indeed use the productionlist templates for these

What do you mean by this?

**Comment by cpitclaudel** [comment]
> What do you mean by this?

Maybe the lighter style that is currently used for production lists should be used for prodn objects.  I was agreeing with *(Alternatively, do we really need the box or the highlight? productionlist doesn't have either. The document would be even less cluttered without them.)* from @jfehrle's answer

**Comment by jfehrle** [comment]
> Your css changes were in the right direction, I think; can you show what you did exactly?

I was viewing the wrong file :-(.  I updated `coqdoc.css` to get rid of the highlighting.

I added some print statements to `handle_signature` for `prodn`.  For

```
.. prodn::
   binder += {| & @term | of @term }
```

![image](https://user-images.githubusercontent.com/1253341/68537715-85167d80-031d-11ea-8ca7-741d6e5bbb39.png)
rhs_node is

```
<inline classes="notation">
    <inline classes="alternative">
        <inline classes="alternative-block">
            <inline>&</inline>
            <pending_xref refdomain="std" reftarget="term" reftype="token">
                <inline classes="hole">term</inline>
            </pending_xref>
        </inline>
        <inline classes="alternative-separator">​</inline>
        <inline classes="alternative-block">
            <inline>of</inline>
            <pending_xref refdomain="std" reftarget="term" reftype="token">
                <inline classes="hole">term</inline>
            </pending_xref>
        </inline>
    </inline>
</inline>
```

which gets transformed to this HTML:

```
<dt>
    <code class="sig-name descname">
        <code class="docutils literal notranslate"><span class="pre">binder</span> <span class="pre">+=</span> </code>
        <span class="notation"><span class="alternative">
            <span class="alternative-block"><span>&amp;</span> <a class="reference internal"
                                                            href="../language/gallina-specification-language.html#grammar-token-term">
            <span class="hole">term</span></a></span>
            <span class="alternative-separator">​</span>
            <span class="alternative-block"><span>of</span> <a class="reference internal"
                                                         href="../language/gallina-specification-language.html#grammar-token-term">
            <span class="hole">term</span></a></span>
        </span></span>
    </code></dt>
```

To make prodn look more like a productionlist, I will need to create a table containing notations.

1. Can I just wrap `rhs_node`s in the appropriate HTML tags using dominate?  But adding this code to `coqdomain.py` gives a compile error:

```
from dominate import tags
from dominate.utils import text
```

```
COQBIN="/mnt/c/proj/coq2/bin/" COQLIB="/mnt/c/proj/coq2" sphinx-build -b html \
        -d doc/sphinx/_build/doctrees -j4 doc/sphinx doc/sphinx/_build/html
Running Sphinx v2.1.2

Extension error:
Could not import extension coqrst.coqdomain (exception: No module named 'dominate')
Makefile.doc:71: recipe for target 'refman-html' failed
```

2. I suspect I may need to gather all the productions in a `prodn` and then create the table all at once.  Any pointers on where/how to do that?  (I haven't looked at this at all).

> the productionlist templates

By this you mean generating html similar to that generated for productionlists--or are you referring to some "template" code feature?

**Comment by jfehrle** [comment]
I realize I've completely forgotten about the pdf output.  I imagine wrapping rhs_node in HTML doesn't make sense for the pdf and maybe not for the html either.

(Also, on my system `make refman-pdf` fails with

```
! fontspec error: "font-not-found"
!
! The font "FreeSerif" cannot be found.
```

If you happen to know which Ubuntu package is needed...)

**Comment by herbelin** [comment]
> If you happen to know which Ubuntu package is needed to get this font...)

Do you have `texlive-full`? Otherwise in [`texlive-fonts-extra`](https://packages.ubuntu.com/bionic/all/texlive-fonts-extra/filelist).

**Comment by advorkin** [comment]
Hello,

I'm getting the same error message on RHEL and can't find a package that would provide it.  Any suggestions?  Thank you!

> 
> ```
> ! fontspec error: "font-not-found"
> !
> ! The font "FreeSerif" cannot be found.
> ```
>

**Comment by cpitclaudel** [comment]
It's part of GNU FreeFont, so I expect https://rpms.remirepo.net/rpmphp/zoom.php?rpm=gnu-free-fonts might work?

**Comment by advorkin** [comment]
Thank you.   Trying it with gnu-free-serif-fonts..  I'm trying to build an RPM package with the latest code.

Got error message:
`(/usr/share/texlive/texmf-dist/tex/xelatex/polyglossia/gloss-english.ldf)

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.22 \setmainfont{FreeSerif}[
                             
? 
! Emergency stop.
 ...                                              
                                                  
l.22 \setmainfont{FreeSerif}[
                             
No pages of output.
`

**Comment by advorkin** [comment]
Sorry to bother it, but is it possible to find a full list of required texlive packages on RHEL?  Please let me know if I should open a separate ticket.  Seems like README file is for Ubuntu packages.

Thank you!

**Comment by jfehrle** [comment]
> Please let me know if I should open a separate ticket.

Yes.  Texlive is a separate concern, tangential to this issue, "Enhance prodn in .rst doc files to cleanly support multiple productions in a prodn".  It will likely be closed without considering texlive.
