### ISSUE TITLE
indeed failed with message: User interrupt.

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#11077]
#### Description of the problem

```
Fixpoint slow (n:nat) := 
  match n with
  | O => O
  | S n => slow n - slow n
  end.

Goal slow 120 = O.
  Fail cbv. (* cancel this command *)
  (* The command has indeed failed with message: *)
  (* User interrupt. *)%
```
This is particularly annoying because the rest of the file is still processed after `Fail` succeeds, leading to scenarios where a file looks okay in the editor (due to some cancellations getting processing past the `Fail)` but hangs in `coqc`.

#### Coq Version

8.10.1, on Linux, in coqide and coqtail.

**Comment by SkySkimmer** [comment]
Cannot reproduce in master, presumably because of be9a1834a48393185ec9cfd9c18d157fd2a7ff02 (#10173, 8.11)
