### ISSUE TITLE
Double clicking behaviour has changed in coqide

### ISSUE THREAD

**Issue by Alizter** [coq/coq#11078]
#### Description of the problem

Observe the following scenarios in coqide:

 1. Double clicking on `Foobar.` should highlight `Foobar`. Currently it highlights `Foobar.`. I am fairly certain that 8.9 did not have this behavior.
 2. Double clicking on `Foo.bar.foobar` highlights all of the text. Double clicking twice on the Foo part can sometimes cause only `Foo` to be highlighted. I don't know what the expected behavior was supposed to be here?

#### Coq Version

```
The Coq Proof Assistant, version 8.11+alpha (October 2019)
compiled on Oct 27 2019 18:28:14 with OCaml 4.05.0
```

**Comment by silene** [comment]
Issue 1 is a duplicate of #11058. For 2, the intended behavior is that the whole identifier is selected (see #10063). The code that handles double-click, however, is flaky. So, while I have never encountered this behavior, I am not surprised that it can happen.

**Comment by Alizter** [comment]
I'm closing this since the first seems to be fixed, and I believe the second is intended behaviour.
