### ISSUE TITLE
CoqIDE on Gtk3: Poor Windows UI compatibility

### ISSUE THREAD

**Issue by bcip** [coq/coq#11080]
I find CoqIDE is based on a new UI framework since 8.10.1 or 8.10.0. But this framework is not as good as the old one in compatibility with Windows UI. So I petition for moving back to the old one.

Here are some specific issues:
1. On Windows, shortcut Ctrl+Win+Left/Right is to move between desktops. When using this shortcut with a CoqIDE window is focused, that window will be moved to left/right half of the screen as the effect of Win+Left/Right.

![image](https://user-images.githubusercontent.com/7038073/68508571-b5d2b600-023c-11ea-8e65-68becf687f6e.png)

2. On Windows, clicking the tab of an already focused window on the taskbar is to minimize the window. It doesn't work for CoqIDE.

3. This is a bit personal, but maybe some people will agree with me. The position of the "close window" button is different from other windows and not at the top right corner but has a distance from it. This is inconvenient, especially when closing a series of windows in a row, that user needs to move the mouse accurately and click on a small button.

#### Coq Version
The Coq Proof Assistant, version 8.10.1 (October 2019)
compiled on Oct 25 2019 13:26:04 with OCaml 4.07.1

**Comment by ppedrot** [comment]
"Petitioning" won't be enough, unfortunately, as CoqIDE moved from the deprecated Gtk2 library to the current Gtk3 one. There is indeed quite a lot of breakage, but it's not clear what can be traced back to a change of semantics in Gtk, a breakage in the OCaml binding library lablgtkX, or in CoqIDE itself.

To add insult to injury, CoqIDE has never really been Windows-friendly. It is was already bug-ridden for a lack of dev implication on that platform, and the switch to Gtk3 definitely didn't help.

In the meantime, I recommend using the VSCoq plugin for VScode. It's not completely production-ready yet, but if you really can't stand ProofGeneral and CoqIDE is close to unusable, then it might be worth a try.

**Comment by Zimmi48** [comment]
Regarding the specific issues you reported, it would be good to know if other programs using Gtk3 have the same issues, or not. If yes, then it would mean that this is a bug with Gtk3 that should be reported to them. If only OCaml programs using Gtk3 (for instance Frama-C or Why3-IDE) have this bug, then it could be a bug with lablgtk3 to be reported to the maintainers. If no other program has these bugs, then it could be CoqIDE-specific.

**Comment by XVilka** [comment]
GTK 3 is more Windows-friendly in fact. But highly likely this is caused by the lablgtk3 itself. There are still some critical [issues](https://github.com/garrigue/lablgtk/issues) in lablgtk3 to be fixed, and even Windows building is [still quite tricky](https://github.com/garrigue/lablgtk/issues/52).

**Comment by ejgallego** [comment]
Windows build is pretty OK these days I think [the issue you link @XVilka is related to using Travis to do the CI, which I didn't manage to setup properly; Coq's appveyor setup is relatively simple and allows for lablgtk building]

I am not very familiar wrt the status of lablgtk3 bugs, a possibility to help users is to maintain the gtk2 version of coqide as a separate package; maybe I'll push it to my repos later on.

**Comment by XVilka** [comment]
If there are any issues with lablgtk3 still (please test the master branch of it), then it is better to report it now, because the first stable release is going to be done soon - https://github.com/garrigue/lablgtk/issues/90
