### ISSUE TITLE
Ltac2 array notation is not reparsable

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#11085]
#### Description of the problem

The last line of the code bellow errors out:

```coq
Require Import Ltac2.Ltac2.

Ltac2 Eval (Ltac2.Array.make 1 0).
(* - : int array = [| 0 |] *)

Fail Ltac2 Eval ([| 0 |]).
(* Syntax error: [tactic:tac2expr level 5] expected after '[' (in [tactic:tac2expr]). *)
```

This makes it impossible to have array constants, which would be convenient.

#### Coq Version

8.9.1

**Comment by ppedrot** [comment]
Yep, definitely a TODO.

**Comment by ppedrot** [comment]
Duplicate of #13976
