### ISSUE TITLE
lia fails with aliased type but omega succeeds

### ISSUE THREAD

**Issue by whonore** [coq/coq#11089]
#### Description of the problem
```
Require Import Omega Lia.
Definition t := nat.
Goal forall (n : t), n = n.
Proof.
  intros.
  Fail lia.
  omega.
Qed.
Goal let t' := nat in forall (n : t'), n = n.
Proof.
  intros.
  Fail lia.
  omega.
Qed.
```
`lia` suceeds in both cases if `t` or `t'` is unfolded, but `omega` seems to be able to figure out the types without that step.

#### Coq Version
8.8 - master. `lia` and `omega` both fail on versions before that.

**Comment by anton-trunov** [comment]
Thanks for the report. The first case was fixed in 8.11:

```Require Import Omega Lia.
Definition t := nat.
Goal forall (n : t), n = n.
Proof. intros; lia. Qed.
```

The second one still fails.
