### ISSUE TITLE
Visibility of class instances in modules

### ISSUE THREAD

**Issue by vzaliva** [coq/coq#11138]
Consider the following example:

```coq
(* Custom equality relation *)
Class Equiv (T: Type) := equiv: T -> T -> Prop.

(* module to wrap a type which has `Equiv` instance *)
Module Type Foo.
  Parameter Inline t : Type.
  Context `{Et: Equiv t}.
  (* 'foo_ok' definition works here, as it finds "Et" as an instance of
  "Equiv t" *)
  Lemma foo_ok: forall (x y: t), equiv x y. Admitted.
End Foo.

Module FooProperties (F: Foo).
  Import F.

  (* The following prints:
     Et : Equiv t
   *)
  Check Et.

  (*
    The following fails with the error:

     Error: Unable to satisfy the following constraints:
     In environment: x, y : t
     ?Equiv : "Equiv t"
  *)
  Lemma foo_error: forall (x y: t), equiv x y.
```
While `Et` is defined inside `FooProperties` as shown by `Check` it is not visible to typelcass resolution. I beleive it should be.

Tested with Coq version 8.9.1 only.

**Comment by Blaisorblade** [comment]
Instead of Context, using Declare Instance Et : Equiv t should work. I agree that Context's behavior is nonsense in this case, but I wonder if it shouldn't just be an error.

**Comment by vzaliva** [comment]
`Declare Instance` worked for me! Thanks. I wonder if there is an opporunity here to unify `Declare Instance` and `Context` into one instruction? They seems to do similar things except for Sections and Modules...

**Comment by Blaisorblade** [comment]
They seem pretty different, and their docs might be even more so.
Declare Instance works for Module Types and Context works well for Section. Outside of Section, Context declares axioms, which I've seldom found a use for. In addition, Context can also generalize on the typeclass arguments and superclasses: with the right settings (Generalizable All Variables), you can write
```coq
Context `{Et: Equiv t}.
```
without declaring t first.

**Comment by SkySkimmer** [comment]
Context without Section will be deprecated after https://github.com/coq/coq/pull/18880 so this issue probably doesn't really matter anymore.
