### ISSUE TITLE
configure can't find LablGtk3 unless opam environment is updated

### ISSUE THREAD

**Issue by Alizter** [coq/coq#11130]
#### Description of the problem

I often find myself doing the following when configuring coq:
```
$ ./configure

You have OCaml 4.05.0. Good!
You have OCamlfind 1.7.3. Good!
You have native-code compilation. Good!
LablGtk3 not found:
=> no CoqIde will be built.
Where should I install the Coq binaries [/usr/local/bin]? ^C

$ eval $(opam env)
$ ./configure

You have OCaml 4.05.0. Good!
You have OCamlfind 1.8.1. Good!
You have native-code compilation. Good!
LablGtk3 found (3.0.beta6), with native threads:
=> native CoqIde will be built.
```

This is pretty annoying. The simple solution would be to get the configure script to run `eval $(opam env)` for me, but this seems to be missing a more fundamental issue.

I haven't installed lablgtk3 recently or anything, but I need to do this every time I need to configure the library.

#### Coq Version

The configure script works in 8.9 with some complaints. For 8.10 and later the behavior above happens.

**Comment by SkySkimmer** [comment]
You're supposed to eval opam env in your shell startup if you want stuff to use opam, it's not configure's responsibility IMO.

>The configure script works in 8.9 with some complaints. For 8.10 and later the behavior above happens.

8.9 uses gtk2, which is why it's different.

**Comment by Alizter** [comment]
>You're supposed to eval opam env in your shell startup if you want stuff to use opam

Ah OK, that make sense.

It would be nice however, if when Lablgtk3 couldn't be found, it was suggested that you make sure you have eval opam env.

**Comment by ejgallego** [comment]
This is not a Coq problem but a problem of your OPAM setup; Coq configure should not alter user environment in any way.

OPAM 2 provides several ways to avoid this problem:
- you can let it modify your shell init files so the right environment is setup at shell start.
- you can let opam install a hook into the line prompt that will keep the environment up to date.

**Comment by ejgallego** [comment]
Note that dune-based build system does indeed integrate with opam, and will suggest opam commands in case of missing dependencies.
