### ISSUE TITLE
Bidirectionality hints perform (surprising?) simplification

### ISSUE THREAD

**Issue by Janno** [coq/coq#11140]
Enabling bidirectionality hints forces arguments to the right of the `&` marker to be simplified during typechecking. **The original argument is replaced by the simplified one**.  

I am not sure if this is intended behavior. It seems dangerous for code that relies on let bindings to avoid recomputation, though. For Mtac2, it makes bidirectionality hints inapplicable since we cannot tolerate spurious reduction or simplification.

I don't have a small example yet but I can provide a slightly tweaked version of Mtac2 that exhibits the problem. It's a bit unwieldy so I am hoping that somebody can spot the cause of the issue without a minimal example. 

In my Mtac2 use case, I can observe that the following scenarios. I have a definition `D` that could benefit from bidirectionality hints and a term applying `D` to an argument that contains a let binding of an applied identity function `I`. (Not `id`, a custom one.)

- bidir. hint disabled for `D`: no simplification during typechecking, resulting term is as written by the user
- bidir. hint enabled for `D`:
  - `I` marked `simpl never`: as above, no simplification, ..
  - `I` *not* marked `simpl never`: let binding reduced, id function reduced away, term differs from user-specified term.

#### Coq Version
branch v8.11 at a613ea5c48bb486e71382afa8e4a1b772beda58a

**Comment by gares** [comment]
With "an argument that contains a let binding" you mean `D (let x := big in x + x)` or `D x` where `x := big` is in the context?

I'll try to look into this tomorrow.

**Comment by Janno** [comment]
> With "an argument that contains a let binding" you mean `D (let x := big in x + x)` or `D x` where `x := big` is in the context?

The former: https://github.com/Mtac2/Mtac2/blob/master-8.11/tests/ttactics.v#L56

To reproduce the problem, add
```
Arguments mmatch' {A P} E y & ps.
```
after https://github.com/Mtac2/Mtac2/blob/master-8.11/theories/intf/M.v#L511

ttactics.v should now fail. (`make tests/ttactics.vo` should help with compiling everything needed for that.)

Marking `reduce` as `simpl never` by adding
```
Arguments reduce : simpl never.
```
after https://github.com/Mtac2/Mtac2/blob/master-8.11/theories/intf/M.v#L511 makes ttactics.v compile again.

**Comment by Janno** [comment]
Urghs, a correction: the whole `simpl never` thing is a red herring. I hadn't recompiled properly. It doesn't seem to change anything. The let binding is away reduced either way when bidir. hints are enabled for `mmatch'`.

**Comment by gares** [comment]
CC @maximedenes To me the problem is here: https://github.com/coq/coq/blob/5d10145531b2920f5e7b9d47bc15b5de06783d97/pretyping/pretyping.ml#L751
The elaborated term `t` contains `newarg` that was possibly instantiated by the bidir step. We then ensure that the actual argument `j` unifies with that, but we should replace in `t` newarg with  `j`.

I think we discussed that during the design of the feature, but then got convinced it was the same.
Indeed the the values are convertible, but the one inferred from the context is preferred over the one explicitly written by the user, which is surprising at best.

I don't understand what is the role played by `bs` in the example. I guess it is the list of branches, and that the type of mmatch is so that its last argument occurs in its return type. But then I don't get how to see the type expected by the context, in particular how it is rigid enough to need the let-in being reduced in order to unify.

**Comment by SkySkimmer** [comment]
>I think we discussed that during the design of the feature, but then got convinced it was the same.

I think I mostly was convinced that the term surgery would be tricky in edge cases (eg if the application got coerced halfway you can't just replace the nth argument of the result) to a point that wasn't worth doing before having use cases.

**Comment by gares** [comment]
Did you hijack Gaetan's account?

**Comment by gares** [comment]
Or Gaetan and Maxime are the same person... :-)

**Comment by Janno** [comment]
I would really love to use this feature for all the various dependently-typed, hacky notations in Mtac2 so I am putting the consortium label on it.

**Comment by SkySkimmer** [comment]
>Or Gaetan and Maxime are the same person... :-)

???
I was there too https://github.com/coq/coq/pull/10049/#pullrequestreview-242749247

**Comment by gares** [comment]
I started working on it already, doing it with a zipper but forgot how to compute derivatives... A prototype will come soonish.

**Comment by maximedenes** [comment]
@Janno I'll talk tomorrow with @gares and @SkySkimmer to see what remains to be done to fix this issue.

**Comment by maximedenes** [comment]
> tomorrow

I meant today.

**Comment by maximedenes** [comment]
@Janno https://github.com/coq/coq/pull/11317 should fix this.

**Comment by Janno** [comment]
> @Janno #11317 should fix this.

It does indeed seem to fix the issue. Thanks!
