### ISSUE TITLE
Typeclass search over Lets

### ISSUE THREAD

**Issue by jihgfee** [coq/coq#11149]
#### Description of the problem

Typeclass search does not unfold Lets, which seems like unintended behaviour, as the intention of Let seems to be aliasing code snippets.

If not, then a clarification on the intended use of Lets would be appreciated.
What I expect from Let is exactly what I would get from:
`Notation x := (e).`

A clarification on the differences of their intended use is therefore also greatly appreciated.

Code that isolates the error: (Thanks to @robbertkrebbers )
```coq
Class Foo (A : Type) := {}.
Instance foo_nat : Foo nat := {}.

Section test
Let T := nat.
Definition T' := nat.
Notation T'' := nat.
Definition test1 : Foo nat := _.
Fail Definition test2 : Foo T := _. (* fails *)
Definition test3 : Foo T' := _.
Definition test4 : Foo T'' := _.
End test.
```

#### Coq Version

The Coq Proof Assistant, version 8.9.1 (August 2019)
compiled on Aug 20 2019 11:00:41 with OCaml 4.07.1

**Comment by ejgallego** [comment]
> What I expect from Let is exactly what I would get from:
> `Notation x := (e).`

This is very far from true; as of today `Let` introduces something akin to a definition [but local], however `Notation` is purely syntactic and is resolved just after parsing.

**Comment by robbertkrebbers** [comment]
> This is very far from true; as of today Let introduces something akin to a definition [but local], however Notation is purely syntactic and is resolved just after parsing.

Note that the testcase works for a `Local Definition`.

Also, it fails for an inline let:

```
Class Foo (A : Type) := {}.
Instance foo_nat : Foo nat := {}.
Definition test5 (T := nat) : Foo T := _. (* fails *)
```
