### ISSUE TITLE
coqtop cannot find .vos file

### ISSUE THREAD

**Issue by Alizter** [coq/coq#11153]
#### Description of the problem

The travis builds in the HoTT library have been failing since this business with .vos files:

[https://travis-ci.org/HoTT/HoTT/builds/614732266](https://travis-ci.org/HoTT/HoTT/builds/614732266)

The reason some of these builds are failing is because they are pulling from the latest version of coq master. The makefile is old and doesn't consider .vos/.vok files.

It used to be 3/8 builds were succeeding but since #11075 4/8 are now passing. The failures seem to be the following:
 
```
$ hoqtop
Welcome to Coq 8.11+alpha (November 2019)
Error: Unable to locate library
Prelude with prefix Coq. (While searching for a .vos file.)
```

So clearly it seems coqtop isn't happy with no .vos file.

A fix that may be done by us is to install the .vos/.vok files but this might not be possible. The reason these travis builds exist is to ensure newer versions of coq work on our current version of the library, which is set at coq 8.10 currently. I would expect that backwards compatibility is important.

As an additional query, what is the point of .vos/.vok files? How come they are suddenly so critical to the success of coqtop?

**Comment by ejgallego** [comment]
This was bug #11057 , it should be solved since this morning when we merged #11075 ; can you re-check with an up-to-date master ?

p.s: Still it is annoying that we produce new files [empty .vos] even if people is not using this functionality, but I'm afraid we'll have to live with that for now.

**Comment by Alizter** [comment]
@ejgallego This travis build ran after #11075 was merged.

**Comment by Alizter** [comment]
Here is a build before #11075 for comparison: [https://travis-ci.org/HoTT/HoTT/builds/614310590](https://travis-ci.org/HoTT/HoTT/builds/614310590).

**Comment by SkySkimmer** [comment]
Are the remaining failing jobs getting master or 8.11?

**Comment by Alizter** [comment]
@JasonGross will know.

**Comment by ejgallego** [comment]
I think the failing jobs are using Jason's coq-daily packages, thus we may have to wait for them to be rebuilt before checking if the problem is solved.

**Comment by ejgallego** [comment]
Indeed the packages are at hash e687dd9 which doesn't have fix.

**Comment by Alizter** [comment]
@ejgallego Ah ok. The final job in the list was being built with master if I am not mistaken. Before #11075, it would fail but now it succeeds. So it does seem to be a problem with our side.

**Comment by ejgallego** [comment]
Not really a problem in your side, the bug in Coq was real; I guess we just need to wait for the `.deb` packages to get rebuilt.

**Comment by Alizter** [comment]
@ejgallego I suppose we will see tomorrow?

**Comment by ejgallego** [comment]
> @ejgallego I suppose we will see tomorrow?

Indeed I think so.

**Comment by Alizter** [comment]
It is all working now!
