### ISSUE TITLE
Canonical Instances cannot be Local nor on a Let

### ISSUE THREAD

**Issue by gares** [coq/coq#11155]
While working at hierarchy-builder I've just discovered that `Local` cannot be used to limit the scope of `Canonical Structure` and also that one cannot declare a section variable introduced with `Let` as canonical. CC @ggonthier @maximedenes @CohenCyril @pi8027 

I think I can remedy both limitations, but there are a few details I'd like to have discussed.
Specifically:
- Canonical x : current behavior not to break things, if x is a Let from the current section we have two options:
  - accepted, x is dropped when it goes out of scope
  - an error is raised, you should have used Local Canonical
- Local Canonical x : dropped at the end of the section
- Global Canonical x : As of today, error is x is a Let

Preferences?

**Comment by pi8027** [comment]
> * Canonical x : current behavior not to break things, if x is a Let from the current section we have two options:
>   * accepted, x is dropped when it goes out of scope
>   * an error is raised, you should have used Local Canonical

Declaring local `Let` as `Canonical` would be useful at least to implement factories by hand, but actually, there is a workaround that is reasonable to me: https://github.com/math-comp/math-comp/blob/5c9502d11acd59f3c549e823ebad0921c78e4102/mathcomp/ssreflect/order.v#L3671-L3677

**Comment by pi8027** [comment]
@gares Also, could we have `Canonical Let` command to abbreviate `Let x := ... . Canonical x.` with `Canonical Let x := ... .` if we decide to accept declaring local `Let` as `Canonical`?

**Comment by SkySkimmer** [comment]
>@gares Also, could we have Canonical Let command to abbreviate Let x := ... . Canonical x. with Canonical Let x := ... . if we decide to accept declaring local Let as Canonical?

Note that for fixpoint the order is `Let Fixpoint`, it may be worth following that for consistency

**Comment by gares** [comment]
I'd rather have a `#[canonical]` attribute to put before the `Let`, exactly to avoid the point raised by @SkySkimmer

**Comment by gares** [comment]
I've just pushed a commit in #11164 that lets you write `#[canonical] Let` (and also `#[canonical] Definition`).
