### ISSUE TITLE
lablgtk3 not found

### ISSUE THREAD

**Issue by Alizter** [coq/coq#11160]
#### Description of the problem

I have been trying to build coq from master. Currently I am on the master branch commit 83ab871c90c862ebb08bcc549701beec0afc6cce.

I run `./configure`:

```
$ sudo ./configure
You have OCaml 4.05.0. Good!
You have OCamlfind 1.7.3. Good!
You have native-code compilation. Good!
LablGtk3 not found:
=> no CoqIde will be built.
Where should I install the Coq binaries [/usr/local/bin]? 
```
Which is strange, so I do the following to make sure:
```
$ eval $(opam env)
$ sudo ./configure
You have OCaml 4.05.0. Good!
You have OCamlfind 1.7.3. Good!
You have native-code compilation. Good!
LablGtk3 not found:
=> no CoqIde will be built.
Where should I install the Coq binaries [/usr/local/bin]? 
```

Same message. I definitely have lablgtk3 since:

```
$ sudo opam install lablgtk3-sourceview3
[WARNING] Running as root is not recommended
[NOTE] Package lablgtk3-sourceview3 is already installed (current version is
       3.0.beta6).
```
and
```
$ sudo apt-get install libgtksourceview-3.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgtksourceview-3.0-dev is already the newest version (3.24.7-1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```
For some reason ocaml cannot find lablgtk3 and I don't know how to fix this.

**Comment by ejgallego** [comment]
You are using `sudo` thus likely all your opam / coq setup is already broken. Opam, as the warning correctly says, should be run as a regular user.

**Comment by ejgallego** [comment]
Wipe your `~/.opam` folder and don't use sudo in any of the above commands.

**Comment by ejgallego** [comment]
Reopen if the problem without sudo appears.

**Comment by Alizter** [comment]
@ejgallego  Thank you for your help. Being trigger happy with sudo eventually caught up to me it seems. I have reinstalled everything without sudo and it seems to working.

**Comment by ejgallego** [comment]
Glad to hear things are working now, you are welcome!
