### ISSUE TITLE
Canonical projection for `_ -> _` cannot be used with `fun .. => ..` terms, only with (local) definitions

### ISSUE THREAD

**Issue by Janno** [coq/coq#11189]
#### Description of the problem
The following code shows a structure with one type field `key` and canonical structures for a base case (`unit`) and a case for implications `_ -> _`. I had expected the line prefixed with `Fail` below to succeed but it does not. Instead, it reports the following error message:
```
The type of this term is a product while it is expected to be
 (key ?n).
```
I find this very surprising since the code registers a canonical projection for (non-dependent) function types, as Coq gladly reports in `Print Canonical Projections`:
```
_ -> _ <- key ( @step )
```
The reason is not, I think, a failure in CS search but rather a limitation in the pretyper: `evardefine.split_tycon` is what my backtrace points to.

The last four lines show that the problem can be circumvented in multiple ways, including wrapping the `fun` term in `id`.

Is there a reason why it cannot work with `fun`?

```coq
Structure trivial_cs := { key : Type }.

Canonical Structure base : trivial_cs := {|key := unit|}.
Canonical Structure step {A : Type} (t : trivial_cs) : trivial_cs := {| key := A -> key t |}.

Definition test := fun (t : trivial_cs) (k : key t) => tt.

Fail Check test (_) (fun x : unit => tt).

Check let this := (fun x : unit => tt) in test (_) this.
Definition this := fun x : unit => tt.
Check test (_) this.
Check test _ (id (fun x : unit => tt)).
```

#### Coq Version
8.11 branch as of a few days ago.

**Comment by SkySkimmer** [comment]
`Check test (_) ((fun x : unit => tt) : _).` also succeeds. It's an issue with the way bidirectionality works for lambdas.

**Comment by Janno** [comment]
Hm, this looks to me like it needs just one layer of evar indirection to work. `id` would certainly introduce an evar for its type argument and `: _` probably introduces an evar for the type as well. Is this the crux of the issue?

It's interesting that you mention bidirectionality. I couldn't make any headway with bidirectionality hints in this case but I don't understand them well enough yet to claim with certainty that they couldn't possible help with this.

**Comment by SkySkimmer** [comment]
This is bidirectionality for lambda not application.

**Comment by Janno** [comment]
So is it the case that the `fun` term is checked (rather than synthesized) because of the existing constraint that it has to be of type `key ?t`? And then Coq probably tries to reduce that type—unsuccessfully, of course—and complaints that a `fun` term can only have type `forall ..`?

I suppose with the `: _` annotation the `fun` term's type would be synthesized and in a later step `key ?t` would be unified with `forall ..` (or rather `.. -> ..`) and that then succeeds.

Is this (roughly) correct?

**Comment by ggonthier** [comment]
I've also run into this recently alongside #9663. AFAICT the problem is that CS inference checks that a product is _non-dependent_ before using a `->` hint, and that depending on how quickly evars constraints are propagated a `fun` may still appear to have a dependent `forall` type when unification starts looking for CS hints. That non-dependency check is inherently problematic because it is contra variant wrt unification constraints, failing if constraints are not propagated fast enough, whereas CS hints are mostly neutral in this respect (unification happily propagates structure projection unification constraints for flexible terms). Since there's no strong motivation for this check in the first place, the obvious solution would be to remove it altogether.

**Comment by SkySkimmer** [comment]
>AFAICT the problem is that CS inference checks that a product is non-dependent before using a -> hint

No, there is no attempt to do CS inference at all in `Check test (_) (fun x : unit => tt).`

**Comment by Janno** [comment]
Would it be a valid fix to perform CS inference (specifically: searching for a `_ -> _` projection) when checking a `fun` terms against `key _`? Likewise, wouldn't it be sensible to apply the same approach to the dual problem such that checking the application of `x y` would trigger a search for a `_ -> _` projection if `x` has type `key _`?

My intuition says that this will have very limited impact on code that compiles today. In fact, I would almost be willing to bet that sensible code shouldn't be affected. (I know, no true Scotsman and all that.) It would of course have a performance impact.

**Comment by Janno** [comment]
This was addressed by https://github.com/coq/coq/pull/14715.
