### ISSUE TITLE
Missing definition for canonical structures in glob files

### ISSUE THREAD

**Issue by ybertot** [coq/coq#11194]
#### Description of the problem
Compilation using coqc of files containing canonical structures fails to add a definition for objects that are defined using the `Canonical Structure` command. 
Here is a short example (in file `file.v`)

    Record a_struct := { anum : nat }.
    Canonical Structure a_struct_0 := {| anum := 0|}.
    Definition rename_a_s_0 := a_struct_0.

Run the command `coqc file.v`.
The file `file.glob` contains a reference line where `a_struct_0` is being used, but no def line where `a_struct_0` is being defined.  This leads to unsatisfactory behavior of coqdoc generated files.

#### Coq Version

this problem happens with coq 8.9, coq 8.10.0 and coq 8.11+alpha (compiled on Nov. 21 from master, with Ocaml 4.09)

**Comment by herbelin** [comment]
Fixed in #12025!
