### ISSUE TITLE
Regression of lia ?

### ISSUE THREAD

**Issue by erikmd** [coq/coq#11191]
#### Description of the problem

When recompiling (some dev branch of) coq-interval with coq master with @proux01, we noticed what appears to be a regression of lia.

Minimal working example:

``` 
Require Import ZArith Psatz.

Goal forall p, (0 < Z.pos (p ^ 2))%Z.
intros.
Fail lia. (* worked with 8.10 *)
Abort.

Goal forall p n, (0 < Z.pos (p ^ n))%Z.
intros.
Fail lia. (* worked with 8.10 *)
Abort.
```

Cc @fajb 

As an aside, do you think coq-interval could be added to Coq's CI? Cc @silene  

#### Coq Version

coq master, compiled a few days ago;
still reproducible with 0e9cd0fe99216bc09a09a0da6906f9501b682223

**Comment by fajb** [comment]
Thanks for the report.
zify is doing a better job and this has a bad side-effect:

```
  p, n : positive
  cstr : (0 < Z.pos n)%Z
  cstr0 : (0 < Z.pos p)%Z
  ============================
  (0 < Z.pos p ^ Z.pos n)%Z
```
The workaround is to add saturation rules for Zpower. I'll propose a PR for that.
