### ISSUE TITLE
Function example from documentation has syntax error

### ISSUE THREAD

**Issue by bergwerf** [coq/coq#11216]
#### Description of the problem

I am trying to use Function to proof termination with a measure and use induction later. However the example from the documentation already produces a syntax error.

```
Function plus (m n : nat) {struct n} : nat :=
match n with
| 0 => m
| S p => S (plus m p)
end.
```

Gives `Syntax error: [tactic:ltac_use_default] expected after [tactic:tactic] (in [vernac:tactic_command]).`

#### Coq Version

8.8.1

I checked and the same Function syntax is already defined in the documentation for that version (https://coq.inria.fr/distrib/V8.8.1/refman/language/gallina-extensions.html?highlight=function#coq:cmd.function)

**Comment by ppedrot** [comment]
You need to `Require Recdef.`. This is documented in the link you provided.
