### ISSUE TITLE
CoqIDE 8.10.* crashes when built with lablgtk3/lablgtk3-sourceview3 3.0.beta7 on MacOS

### ISSUE THREAD

**Issue by Blaisorblade** [coq/coq#11217]
#### Description of the problem

After building CoqIDE 8.10.2 on Mac myself (through opam, from the formula in https://github.com/ocaml/opam-repository/pull/15417), the resulting coqide always crashes immediately at startup. Sample trace:
https://gist.github.com/Blaisorblade/35b55a5ec5ffd43c87c2cc34ab28bec8

That bug was fixed by downgrading lablgtk3 and lablgtk3-sourceview3 from 3.0.beta7 to 3.0.beta6. The older version that was also the library version I used when I last built CoqIDE, so the problem might also affect older CoqIDE.

#### Os/libs Version

MacOS 10.14.6

Relevant libraries (installed with homebrew):
atk: stable 2.34.1
gdk-pixbuf: stable 2.40.0
glib: stable 2.62.3
gtk+3: stable 3.24.12
gtksourceview3: stable 3.24.11
pango: stable 1.44.7
libepoxy: stable 1.5.4

**Comment by ppedrot** [comment]
There are 19 non-merge commits between those two versions, maybe you could bisect?

**Comment by ejgallego** [comment]
If you use dune it is super easy to bisect Coq + lablgtk3, just drop the lablgtk3 sources in the Coq tree and call the right `Makefile.dune` target; builds will compose and you will get proper incremental rebuilding across both projects.

**Comment by Blaisorblade** [comment]
With lablgtk3/lablgtk3-sourceview3 3.0.beta7, the problem doesn't appear when building with dune. So @ejgallego asked for the respective link commands. Here they are — tho I assume they're reproducible (hopefully) elsewhere.

```
$ (cd _build/default && /usr/local/bin/ocamlopt.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -keep-locs -warn-error -A -rectypes -w -9-27+40+60 -g -o ide/coqide_main.exe -I /Users/pgiarrusso/.opam/tmp/lib/cairo2 -I /Users/pgiarrusso/.opam/tmp/lib/lablgtk3 -I /Users/pgiarrusso/.opam/tmp/lib/lablgtk3-sourceview3 -I /usr/local/lib/ocaml/threads -I clib -I config -I ide -I ide/protocol -I lib /usr/local/lib/ocaml/str.cmxa /usr/local/lib/ocaml/unix.cmxa /usr/local/lib/ocaml/threads/threads.cmxa clib/clib.cmxa config/config.cmxa lib/lib.cmxa ide/protocol/protocol.cmxa ide/core.cmxa /usr/local/lib/ocaml/bigarray.cmxa /Users/pgiarrusso/.opam/tmp/lib/cairo2/cairo.cmxa /Users/pgiarrusso/.opam/tmp/lib/lablgtk3/lablgtk3.cmxa /Users/pgiarrusso/.opam/tmp/lib/lablgtk3-sourceview3/lablgtk3_sourceview3.cmxa ide/coqide_gui.cmxa ide/.coqide_main.eobjs/native/coqide_main.cmx)
```

```
$ make -j4 bin/coqide VERBOSE=1

/Library/Developer/CommandLineTools/usr/bin/make --warn-undefined-variable --no-builtin-rules -f Makefile.build bin/coqide

"/Users/pgiarrusso/.opam/tmp/bin/ocamlfind" opt -thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence  -I coqpp -I config -I clib -I lib -I kernel -I kernel/byterun -I library -I engine -I pretyping -I interp -I proofs -I gramlib/.pack -I parsing -I printing -I tactics -I vernac -I stm -I toplevel -I ide -I ide/protocol -package lablgtk3-sourceview3 -g    -o bin/coqide \
	       -linkpkg -package str,unix,dynlink,threads,lablgtk3-sourceview3 -linkall  config/config.cmxa clib/clib.cmxa lib/lib.cmxa ide/protocol/ideprotocol.cmxa ide/ide.cmxa ide/coqide_os_specific.cmx ide/coqide_main.mli ide/coqide_main.ml
true bin/coqide
```

**Comment by Blaisorblade** [comment]
I'm out of time now, but I wonder if the problem comes from https://github.com/garrigue/lablgtk/commit/576b1932db594c3f7baf1ab15c3dd13783af8ca3.
The only other substantial change seems https://github.com/garrigue/lablgtk/commit/933fe0dd8785b3b8bd3a3c50c6a3ba9072413493...

**Comment by Blaisorblade** [comment]
Bisection completed. The issue starts with https://github.com/garrigue/lablgtk/commit/09e6645a349ab0bdf3ce54a01a4207b31b3faf57, and is still specific to using Coq makefiles.

Command to build lablgtk:
```
PATH/TO/lablgtk$ dune build -j4 -p lablgtk3,lablgtk3-sourceview3 && dune install  -j4 lablgtk3 lablgtk3-sourceview3
```

Command to build coqide:
```
PATH/to/coq$ git clean -fdx ide/ && make bin/coqide -j4 && ./bin/coqide
```

**Comment by ejgallego** [comment]
That's a very weird commit to be blamed, unless there is a cut and paste error, the changes should not be observable. Does that happen on a clean switch too?

**Comment by Blaisorblade** [comment]
Dunno, the two releases seem virtually identical anyway, and even ignoring paste errors, couldn't that commit affect how the library is linked? 
Also, as a clueless outsider: that change mixes moving lots of stuff around with independent changes — I'm sure each of those had a reason (e.g. `gtkgl_tags.h` seems to disappear, tho I guess it was unused?), but it's hard to inspect (at least for ignorant me).

Regardless, while I no expert dune user, I can repeatably go from working to segfaulting and back when switching between that commit and the parent. Ditto if I clean lablgtk and Coq completely with `git clean -fdx`.

Last, that stays true in a clean switch where I install the following packages, dune-install lablgtk, then build coqide (well, technically, I have installed some dependencies when dune/make failed, but I hope that doesn't matter):
```
base-bigarray       base
base-threads        base
base-unix           base
cairo2              0.6.1       Binding to Cairo, a 2D Vector Graphics Library
conf-cairo          1           Virtual package relying on a Cairo system installation
conf-findutils      1           Virtual package relying on findutils
conf-gtk3           18          Virtual package relying on GTK+ 3
conf-gtksourceview3 0+1         Virtual package relying on a GtkSourceView-3 system installation
conf-m4             1           Virtual package relying on m4
conf-pkg-config     1.1         Virtual package relying on pkg-config installation
dune                2.0.0       Fast, portable, and opinionated build system
dune-configurator   2.0.0       Helper library for gathering system configuration
dune-private-libs   2.0.0       Private libraries of Dune
num                 1.3         The legacy Num library for arbitrary-precision integer and rational arithmetic
ocaml               4.08.1      The OCaml compiler (virtual package)
ocaml-config        1           OCaml Switch Configuration
ocaml-system        4.08.1      The OCaml compiler (system version, from outside of opam)
ocamlfind           1.8.1       A library manager for OCaml
```

**Comment by ejgallego** [comment]
Indeed the problem seems to be the linkall that Coq's makefile is passing to the coqide linker.

In the commit you point out indeed we include `GtkInit` and `GtkThread` in the generated `.cma`, thus using `-linkall` does create problems.

I'm not sure what is the right thing to do here, @garrigue ?

**Comment by ejgallego** [comment]
The change does not show in the diff as we replace an explicit list of modules `src/dune` by the default of all files in the directory.

**Comment by ejgallego** [comment]
Indeed adding these files was wrong, I'm convinced now, see https://github.com/garrigue/lablgtk/pull/100

**Comment by Blaisorblade** [comment]
Thanks for finding out what's going on!

**Comment by ejgallego** [comment]
> Thanks for finding out what's going on!

Let me know if the branch in the PR does fix your problem.

**Comment by Blaisorblade** [comment]
It does.

**Comment by Blaisorblade** [comment]
Just confirmed that 8.10.1 and 8.10.0 also suffer from this bug.
https://github.com/ocaml/opam-repository/pull/15431 blacklists the offending lablgtk3 version.

**Comment by ejgallego** [comment]
Thanks @Blaisorblade ; the right fix IMO is not to blacklist the version in OPAM but to fix Coq's makefile which is indeed using `-linkall` in a bogus way; the conflict should be present for unfixed versions tho.

**Comment by Blaisorblade** [comment]
@ejgallego Not disagreeing.
All I'm saying is: I think installing coqide 8.10.{0,1,2} should keep working. Maybe that's more support than usual, but I volunteered minimal fixes to ensure that :-). coqide 8.10.dev can wait for the backport (if any).

**Comment by ejgallego** [comment]
Indeed, that's why I meant "the conflict should be present for unfixed versions"
