### ISSUE TITLE
CoqIDE tactics and templates menus are out of sync.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#11219]
#### Description of the problem

As remarked by @silene in #10575, the tactics and templates menus in CoqIDE are completely out of sync: many new tactics and commands are not listed (despite what seems like an attempt to provide an exhaustive list), while on the other hand some deprecated or even removed commands and options are listed.

I have personally always thought that these menus are useless. In particular, they didn't help me when I was a beginner, while it could have been the case if they had provided only a sub-selection of the most useful commands and tactics.

Anyway, the fact that this is completely out of sync seems to show that it is hard for IDE maintenance to keep up with the rapid evolution of the Coq language. I hope that this is not the same list that is used for automatic completion, otherwise that's even more worrying.

I suggest one of the following options:
- get rid completely of these menus (most radical, and most easily implemented);
- abandon the attempt at exhaustiveness and provide a small sub-selection instead;
- figure out a way of keeping these lists automatically in sync.

#### Coq Version

8.5-8.12

**Comment by ppedrot** [comment]
I'd personally favour removal. Never understood the point of those menus either, even back then when I was a Coq noob. It takes more time to browse to gargantuan menus than type the tactic, and from the point of discoverability this is close to useless because there are too many tactics and no doc. Thus, the embodiment of a crappy UI / UX.

**Comment by Blaisorblade** [comment]
Agreed on CoqIDE — and more expensive fixes make little sense if CoqIDE itself is deprecated.

However, the same problem applies to autocompletion in other IDEs? I've seen specific issues in vscoq — and I suspect the autocompletion was never in sync. Ideally, Coq should offer some API for IDEs to learn available commands, so that IDEs might support new Coq versions without a new release.

**Comment by Zimmi48** [comment]
> CoqIDE itself is deprecated

FTR CoqIDE is not deprecated. There are still several people in the development team who care about it (even if I'm not one of them). And given that there was recently an important effort to port it to Gtk3, it's not to remove it right after. That being said, there might be a move in the future to treat CoqIDE more like just an option among others, and stop giving it a privileged status.

> Coq should offer some API for IDEs to learn available commands, so that IDEs might support new Coq versions without a new release.

Good point, and in fact the work that has been done by @jfehrle on automatically ensuring that the grammar in the documentation is in sync with the code could also serve as a good basis to provide such support.

**Comment by Blaisorblade** [comment]
> FTR CoqIDE is not deprecated.

Then I misunderstood some comment — what matters is "does anybody plan to implement significant new CoqIDE features" — up to any such volunteer.

> Good point, and in fact the work that has been done by @jfehrle on automatically ensuring that the grammar in the documentation is in sync with the code could also serve as a good basis to provide such support.

👍

**Comment by jfehrle** [comment]
> Thus, the embodiment of a crappy UI / UX.

I would go for removal, too, but not this overly colorful language.  It might tend to discourage the creator(s) of this feature--and perhaps some readers--from working more with the Coq team.  The comment is also exaggerated--it's an apparently useless feature on the menu that users can ignore.

**Comment by herbelin** [comment]
This tactic menu and the wizard tactic menu were popular at some time, and a few months ago, a Coq math user from Nice asked me, ah, are there still these tactic menus in Coqide?

The guilty person is rather me who never used this menu and did not pay attention to it not being synchronized anymore.

As for taking a decision, what about polling users on coq-club, telling that we'd like to simplify the code of coqide so as to make the maintenance easier, asking to comment on whether this feature is really worth the maintenance cost?

**Comment by Zimmi48** [comment]
A poll cannot hurt, especially if you are personally ready to spend some effort on this feature if people answer they would like to keep it.

OTOH, I personally am of the impression that spending time preparing "cheat sheets" summarizing the most important tactics and commands, and improving the reference manual more generally, are a better use of time to make sure these users are supported.

**Comment by Zimmi48** [comment]
Note that the Discourse forum includes a feature to generate a poll (see cog icon in menu bar when creating a post). If you choose to run the poll on Discourse, you can have more answers (that do not require sending a message) and you can advertise it on Coq-Club.

**Comment by Blaisorblade** [comment]
Semi-related point (sorry if I repeat myself): my favorite tactic index were the PDF bookmarks of the Coq manual till Coq 8.7.2 (on the left side of the screenshot below). It's a list of tactics, sorted by topic exactly like in the manual.

![image](https://user-images.githubusercontent.com/289960/72637190-05321280-3961-11ea-9792-9eb86b48a873.png)

**Comment by herbelin** [comment]
Answering to @Zimmi48 (and letting @Zimmi48 answer the tactic index question): ok, not spending time on this tactic menu and using time instead on documentation.

**Comment by Zimmi48** [comment]
@Blaisorblade Feel free to open a specific issue if there is something that you miss in the new format.

**Comment by jfehrle** [comment]
>  FTR CoqIDE is not deprecated. There are still several people in the
development team who care about it (even if I'm not one of them).

What interface do you prefer?  Proof General?

Jim

**Comment by Zimmi48** [comment]
> What interface do you prefer? Proof General?

I personally use PG because I've got used to Emacs for all these years. But for students who still haven't yet a preferred editor, I'd recommend VsCoq. Actually, right now I'm experimenting teaching a class with Jupyter (thanks to the Coq support at https://github.com/EugeneLoy/coq_jupyter/) but this is not really comparable nor suitable for multi-file projects.
