### ISSUE TITLE
How to reduce terms of definition

### ISSUE THREAD

**Issue by Alizter** [coq/coq#11222]
#### Description of the problem

I am trying to work out how to reduce the proof term of a definition. Observe the following:
```coq
Inductive N :=
  | zero : N
  | succ : N -> N.

Notation "0" := zero.
Notation "1" := (succ 0).
Notation "2" := (succ 1).
Notation "3" := (succ 2).
Notation "4" := (succ 3).
Notation "5" := (succ 4).
Notation "6" := (succ 5).
Notation "7" := (succ 6).

Fixpoint plus (n m : N) {struct n} : N
  := match n with
      | 0 => m
      | succ k => succ (plus k m)
     end.

Infix "+" := plus.

Definition badeight : N
  := 2 + 5.

Print badeight.
(*
badeight@{} = 2 + 5
     : N
*)
```

Is there some way of defining `badeight` but having applied some reduction on it first? For example I can write `Eval cbv in badeight` and get what I want but how do I stick this in a definition?

**Comment by Zimmi48** [comment]
```coq
Definition badeight := Eval cbv in 2 + 5.
```

Note this kind of question is better asked on Discourse or StackOverflow. Cf. https://github.com/coq/coq/blob/master/.github/SUPPORT.md

**Comment by Alizter** [comment]
@Zimmi48 Thank you for your help.
