### ISSUE TITLE
[dune/make] Ltac2 install dir

### ISSUE THREAD

**Issue by proux01** [coq/coq#11225]
When compiling with make, OCaml files for Ltac2 are installed along the .vo:
```
% ls lib/coq/user-contrib/Ltac2
Array.glob  Char.vo       Env.glob     Ident.v    Int.vos     ltac2_plugin.cmi    Message.vos     Pattern.v    String.vos       tac2extffi.cmi  tac2print.cmi
Array.v     Char.vos      Env.v        Ident.vo   List.glob   ltac2_plugin.cmx    Notations.glob  Pattern.vo   tac2core.cmi     tac2extffi.cmx  tac2print.cmx
Array.vo    Constr.glob   Env.vo       Ident.vos  List.v      ltac2_plugin.cmxs*  Notations.v     Pattern.vos  tac2core.cmx     tac2ffi.cmi     tac2qexpr.cmi
Array.vos   Constr.v      Env.vos      Init.glob  List.vo     ltac2_plugin.o      Notations.vo    Std.glob     tac2dyn.cmi      tac2ffi.cmx     tac2quote.cmi
Bool.glob   Constr.vo     Fresh.glob   Init.v     List.vos    Ltac2.v             Notations.vos   Std.v        tac2dyn.cmx      tac2intern.cmi  tac2quote.cmx
Bool.v      Constr.vos    Fresh.v      Init.vo    Ltac1.glob  Ltac2.vo            Option.glob     Std.vo       tac2entries.cmi  tac2intern.cmx  tac2stdlib.cmi
Bool.vo     Control.glob  Fresh.vo     Init.vos   Ltac1.v     Ltac2.vos           Option.v        Std.vos      tac2entries.cmx  tac2interp.cmi  tac2stdlib.cmx
Bool.vos    Control.v     Fresh.vos    Int.glob   Ltac1.vo    Message.glob        Option.vo       String.glob  tac2env.cmi      tac2interp.cmx  tac2tactics.cmi
Char.glob   Control.vo    g_ltac2.cmx  Int.v      Ltac1.vos   Message.v           Option.vos      String.v     tac2env.cmx      tac2match.cmi   tac2tactics.cmx
Char.v      Control.vos   Ident.glob   Int.vo     Ltac2.glob  Message.vo          Pattern.glob    String.vo    tac2expr.cmi     tac2match.cmx   tac2types.cmi
```

whereas when compiling with dune, they are put in a different directory with different names:
```
ls lib/coq/plugins/ltac2/
g_ltac2.ml                   ltac2_plugin__Tac2dyn.cmt       ltac2_plugin__Tac2ffi.cmi      ltac2_plugin__Tac2print.cmt     ltac2_plugin__Tac2types.cmi   tac2interp.ml
ltac2_plugin.a               ltac2_plugin__Tac2dyn.cmti      ltac2_plugin__Tac2ffi.cmt      ltac2_plugin__Tac2print.cmti    ltac2_plugin__Tac2types.cmti  tac2interp.mli
ltac2_plugin.cma             ltac2_plugin__Tac2dyn.cmx       ltac2_plugin__Tac2ffi.cmti     ltac2_plugin__Tac2print.cmx     tac2core.ml                   tac2match.ml
ltac2_plugin.cmi             ltac2_plugin__Tac2entries.cmi   ltac2_plugin__Tac2ffi.cmx      ltac2_plugin__Tac2qexpr.cmi     tac2core.mli                  tac2match.mli
ltac2_plugin.cmt             ltac2_plugin__Tac2entries.cmt   ltac2_plugin__Tac2intern.cmi   ltac2_plugin__Tac2qexpr.cmti    tac2dyn.ml                    tac2print.ml
ltac2_plugin.cmx             ltac2_plugin__Tac2entries.cmti  ltac2_plugin__Tac2intern.cmt   ltac2_plugin__Tac2quote.cmi     tac2dyn.mli                   tac2print.mli
ltac2_plugin.cmxa            ltac2_plugin__Tac2entries.cmx   ltac2_plugin__Tac2intern.cmti  ltac2_plugin__Tac2quote.cmt     tac2entries.ml                tac2qexpr.mli
ltac2_plugin.cmxs            ltac2_plugin__Tac2env.cmi       ltac2_plugin__Tac2intern.cmx   ltac2_plugin__Tac2quote.cmti    tac2entries.mli               tac2quote.ml
ltac2_plugin.ml              ltac2_plugin__Tac2env.cmt       ltac2_plugin__Tac2interp.cmi   ltac2_plugin__Tac2quote.cmx     tac2env.ml                    tac2quote.mli
ltac2_plugin__G_ltac2.cmi    ltac2_plugin__Tac2env.cmti      ltac2_plugin__Tac2interp.cmt   ltac2_plugin__Tac2stdlib.cmi    tac2env.mli                   tac2stdlib.ml
ltac2_plugin__G_ltac2.cmt    ltac2_plugin__Tac2env.cmx       ltac2_plugin__Tac2interp.cmti  ltac2_plugin__Tac2stdlib.cmt    tac2expr.mli                  tac2stdlib.mli
ltac2_plugin__G_ltac2.cmx    ltac2_plugin__Tac2expr.cmi      ltac2_plugin__Tac2interp.cmx   ltac2_plugin__Tac2stdlib.cmti   tac2extffi.ml                 tac2tactics.ml
ltac2_plugin__Tac2core.cmi   ltac2_plugin__Tac2expr.cmti     ltac2_plugin__Tac2match.cmi    ltac2_plugin__Tac2stdlib.cmx    tac2extffi.mli                tac2tactics.mli
ltac2_plugin__Tac2core.cmt   ltac2_plugin__Tac2extffi.cmi    ltac2_plugin__Tac2match.cmt    ltac2_plugin__Tac2tactics.cmi   tac2ffi.ml                    tac2types.mli
ltac2_plugin__Tac2core.cmti  ltac2_plugin__Tac2extffi.cmt    ltac2_plugin__Tac2match.cmti   ltac2_plugin__Tac2tactics.cmt   tac2ffi.mli
ltac2_plugin__Tac2core.cmx   ltac2_plugin__Tac2extffi.cmti   ltac2_plugin__Tac2match.cmx    ltac2_plugin__Tac2tactics.cmti  tac2intern.ml
ltac2_plugin__Tac2dyn.cmi    ltac2_plugin__Tac2extffi.cmx    ltac2_plugin__Tac2print.cmi    ltac2_plugin__Tac2tactics.cmx   tac2intern.mli
```

This is particularly annoying when developing Ltac2 plugins.

@ejgallego do you think it would be possible to uniformize this (possibly by modifying make according to #11221)?

**Comment by ejgallego** [comment]
> This is particularly annoying when developing Ltac2 plugins.

Umm, what's the exact problem here? I don't see a relation with #11226 

Usually dependencies on ML stuff are better handled using `ocamlfind`, which indeed is missing for the Ltac2 case, are you using coq_makefile to build your plugin?

**Comment by proux01** [comment]
Indeed, using ocamlfind could fix the issue.

Currently, we have to call coq_makefile with both `-I "$(shell coqtop -where)/user-contrib/Ltac2"` and `-I "$(shell coqtop -where)/plugins/ltac2"` due to the different paths.

Also, with the difference in file names/packing, `open Ltac2_plugin` did no longer work correctly. I had to make strange things to make our plugin compile with dune compiled Coq 8.11 : https://github.com/validsdp/validsdp/commit/11fcea18c882fd16ad05fbedac2b943ff4a499dc Although I must admit I did not investigate much further and don't really understand what's precisely happening here.

**Comment by ejgallego** [comment]
> Indeed, using ocamlfind could fix the issue.

I suggest then we fix this by updating the `META` file for `coq.plugins.ltac2` so you can do a single call and the build file is more robust towards future reorgs.

> make strange things to make our plugin compile with dune compiled Coq 8.11 : [validsdp/validsdp@11fcea1](https://github.com/validsdp/validsdp/commit/11fcea18c882fd16ad05fbedac2b943ff4a499dc)

Umm, that's quite bizarre, if you already opened the plugin things should be fine for Dune, the problem in makefile is that interfaces are also exported in a non-packed way.

**Comment by proux01** [comment]
> I suggest then we fix this by updating the `META` file for `coq.plugins.ltac2` so you can do a single call and the build file is more robust towards future reorgs.

That would be great!

> > make strange things to make our plugin compile with dune compiled Coq 8.11 : [validsdp/validsdp@11fcea1](https://github.com/validsdp/validsdp/commit/11fcea18c882fd16ad05fbedac2b943ff4a499dc)
> 
> Umm, that's quite bizarre, if you already opened the plugin things should be fine for Dune, the problem in makefile is that interfaces are also exported in a non-packed way.

I see, but I still don't understand why
```
mofule Tac2ffi = Ltac2_plugin.Tac2ffi
Tac2ffi.function
```
works whereas
```
open Ltac2_plugin
Tac2ffi.function
```
doesn't?

**Comment by ejgallego** [comment]
> I see, but I still don't understand why [...] works whereas [...] doesnt?

That's bizarre, it should definitively work, but I am not sure what `coq_makefile` does.

**Comment by proux01** [comment]
So, looking a bit deeper, coq_makefile produces the exact same Makefile.coq in both cases.
The differences seem to be in the output of ocamldep. In the first case (working), `plugin.mlg.d` looks like
```
plugins/soswitness/src/soswitness.cmo : \
    /home/coq/.opam/4.05.0/lib/zarith/z.cmi \
    /home/coq/.opam/4.05.0/lib/zarith/q.cmi \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/ltac2_plugin.cmo
plugins/soswitness/src/soswitness.cmx : \
    /home/coq/.opam/4.05.0/lib/zarith/z.cmi \
    /home/coq/.opam/4.05.0/lib/zarith/q.cmi \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/ltac2_plugin.cmx
```
whereas in the second one (not working), we get
```
plugins/soswitness/src/soswitness.cmo : \
    /home/coq/.opam/4.05.0/lib/zarith/z.cmi \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/tac2ffi.cmi \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/tac2expr.cmi \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/tac2env.cmi \
    /home/coq/.opam/4.05.0/lib/zarith/q.cmi \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/ltac2_plugin.cmo
plugins/soswitness/src/soswitness.cmx : \
    /home/coq/.opam/4.05.0/lib/zarith/z.cmi \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/tac2ffi.cmx \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/tac2expr.cmi \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/tac2env.cmx \
    /home/coq/.opam/4.05.0/lib/zarith/q.cmi \
    /home/coq/.opam/4.05.0/lib/coq/plugins/ltac2/ltac2_plugin.cmx
```
and we get the error
```
No rule to make target '/home/coq/.opam/4.07.1+flambda/lib/coq/plugins/ltac2/tac2ffi.cmx'
```
This file indeed doesn't exist in the dune build (it does in the Makefile build, hence the issue not appearing with the Makefile built Coq).

**Comment by ejgallego** [comment]
I see, I'll have a look thanks! [I wonder if it is `ocamldep` or `coqdep` who produces the deps in this case]

**Comment by proux01** [comment]
ocamldep

**Comment by proux01** [comment]
It may be interesting to notice that if the files `tac2{env,expr,ffi,...}.{ml,mli}` are removed from `lib/coq/plugin/ltac2`, then ocamldep does generate the "correct" dependencies and everything is fine.

**Comment by ejgallego** [comment]
Umm, so the problem here is not the different path, but the interaction of coq_makefile and the dune build.

In #8729 plugins built using Coq makefile for a dune-based Coq used to work OK, so this could be a regression?

**Comment by proux01** [comment]
> Umm, so the problem here is not the different path, but the interaction of coq_makefile and the dune build.

Well if dune is also using ocamldep, I would probably get the same result building my plugin with dune (haven't tried though).

> In #8729 plugins built using Coq makefile for a dune-based Coq used to work OK, so this could be a regression?

Maybe is it specific to Ltac2 plugins.

**Comment by ejgallego** [comment]
> Well if dune is also using ocamldep, I would probably get the same result building my plugin with dune (haven't tried though).

dune manages module dependencies a bit differently, in particular it uses `ocamldep -modules` so ocamldep's output doesn't depend on the filesystem.

> Maybe is it specific to Ltac2 plugins.

I'd be surprised, I don't think there is something too special. Do you have the code of the plugin around, I may try to have a look.

**Comment by proux01** [comment]
Sure it is here : https://github.com/validsdp/validsdp/tree/futur-master

It builds with `./autogen.sh && ./configure && make plugin`. There are lot of dependencies required in the configure.ac but you can comment out most of them if you are only interested in the plugin.

**Comment by proux01** [comment]
And the three first `module` lines of  https://github.com/validsdp/validsdp/blob/futur-master/plugins/soswitness/src/soswitness_v811.mlg have to be replaced by `open Ltac2_plugin` to reproduce the issue.

**Comment by ejgallego** [comment]
Thanks @proux01 , I'll have a look.

**Comment by ejgallego** [comment]
I had a look @proux01 , I'm a bit at a loss here, in the sense that I'm unsure who's to blame here. Indeed, `ocamldep` produces incorrect dependencies in cases like this, so build systems tend to workaround it by using `-modules`.

So is this really a `coq_makefile` issue? I dunno, using alias-packed modules is a perfectly legal thing to do, but `coq_makefile` doesn't support it so well. So yeah, I guess there is no other choice than to refer to modules in a fully qualified way or to switch to dune for building your plugin.
