### ISSUE TITLE
Name collisions between cmx and cmxs in the way packed plugins are currently compiled

### ISSUE THREAD

**Issue by herbelin** [coq/coq#11221]
#### Description of the problem

Dependencies on plugins compiled in pack mode are confusing when compiling with `make`/`coq_makefile`. I noticed this when compiling a plugin depending on a standard Coq plugin (`extraction`) but this virtually applies also when depending on a third-party plugin.

For instance, If I'm a compiling a plugin `foo_plugin` depending on the module associated to the file `plugins/extraction/table.ml` of the Coq installation, the compilation goes well by doing `open Table`, but, at the time of doing:
```
Require Import Extraction.
Declare ML Module "foo_plugin".
```
There is an inconsistency between what the packed `extraction_plugin.cmxs` provides and what the plugin expects. Namely, `extraction_plugin.cmxs` provides modules named of the form `Extraction_plugin.Table` while the plugin expects `Table`.

The solution is of course to replace `open Table` by `open Extraction_plugin.Table` but this is a bit tricky to know.

I mentioned this to @ejgallego who is aware of the issue and says that `dune` does not have the problem.

I don't know if there is already a consensus but it seems that:
- this is a new incitation to go to dune
- if we have a transition period - maybe wise in any case? -, we may try to prevent this issue by changing the structure of Coq plugins, and changing similarly how `coq_makefile` manage packed plugins.

I'm not fully sure of what should exactly be done. I suspect that one possibility could be that `foo.cm?` files do not go in the same directory as `foo.ml` but instead in a subdirectory, say `_forpack`, with no `-I` by default on this directory except when in the process of precisely compiling the other files of the corresponding plugin directory.

Or the converse, that the `foo_plugin.cm{i,xs}` file are put in a specific directory which is the only one visible from outside.

**Comment by ejgallego** [comment]
Yeah, this is a know issue with our packing setup and linking; we cannot do much more other than moving to Dune or tweaking the makefile setup in the lines you did suggest [having a _intf object dir could do the job]
