### ISSUE TITLE
Ltac(1) in coqrc breaks CoqIDE 

### ISSUE THREAD

**Issue by Blaisorblade** [coq/coq#11239]
#### Description of the problem

On branches `v8.11` and `master`, CoqIDE fails to start with my .coqrc, even tho that's accepted by Coq — that's because that content doesn't work with `coqtop -nois -batch` (or `coqtop -nois`). Apparently, that's because ltac1 now doesn't work any more in with `-nois`.

```
$ /Applications/CoqIDE_8.11+beta1.app/Contents/Resources/bin/coqtop -nois -batch
File "/Users/pgiarrusso/.coqrc", line 2, characters 0-19:
Warning: There is no option Ltac Backtrace. [unknown-option,option]
Load of rcfile failed.
File "/Users/pgiarrusso/.coqrc", line 4, characters 0-4:
Error: Syntax error: illegal begin of vernac.
```

However, that content does work on normal coqtop:
```
$ /Applications/CoqIDE_8.11+beta1.app/Contents/Resources/bin/coqtop
Welcome to Coq Mac-772.local:/Users/runner/runners/2.160.1/work/1/s,(HEAD detached at 30a4027c) (30a4027cf09c51dd7c488dce22437d35a8acc005)

Coq < Test Ltac Backtrace. (* This is disabled by default and enabled by my coqrc *)
The Ltac Backtrace mode is on
```

#### .coqrc content

```
Set Nested Proofs Allowed.
Set Ltac Backtrace.
Axiom skip: forall {T: Prop}, T.
Ltac skip := apply skip.
Ltac skipType := destruct (@skip False).
```

This content is inspired by a Jason Gross email and already featured in #11096.

#### Coq Version

Coq on the v8.11 branch (https://github.com/coq/coq/runs/333965411) and on master (https://github.com/coq/coq/runs/331135895).

**Comment by SkySkimmer** [comment]
Ltac Backtrace isn't the problem (unknown option is only a warning), the issue is 
>File "/Users/pgiarrusso/.coqrc", line 4, characters 0-4:
>Error: Syntax error: illegal begin of vernac.

ie the `Ltac skip := apply skip`.

**Comment by Blaisorblade** [comment]
Right, I was just showing that `coqtop` without options starts, and the .coqrc has taken effect.
