### ISSUE TITLE
clear - H fails to clear

### ISSUE THREAD

**Issue by Barry-Jay** [coq/coq#11238]
[bug_no_clear.log](https://github.com/coq/coq/files/3925340/bug_no_clear.log)

#### Description of the problem

I have uploaded the file bug_no_clear.log, which is a renaming of bug_no_clear.v, as the latter file type was not supported :( I hope this displays correctly :)

In the proof of clear_fails, the tactic "clear - H." had no effect though "clear IHp1." succeeds. 
The problem goes away in the slightly smaller example, clear_succeeds. 

#### Coq Version

Book-proofs coqtop -v
The Coq Proof Assistant, version 8.9.0 (April 2019)
compiled on Apr 24 2019 13:38:18 with OCaml 4.07.0

**Comment by Barry-Jay** [comment]
Here is the code inserted directly into the window. 

Inductive Tree:  Set :=
  | App : Tree -> Tree -> Tree   
  | Node : Tree   
.


Definition all_node p := 
  match p with
  | Node => Node
  | _ => Node 
  end.


Lemma clear_succeeds:
  forall p, all_node p = Node -> False.
Proof.
  induction p; intros. 
  eapply IHp2. 
  clear - H.
  (* clear succeeds *)
Abort.


Definition node_test p s:= 
  match p with
  | Node => s
  | _ => Node 
  end.


Lemma clear_fails:
  forall p s, node_test p s = Node -> False.
Proof.
  induction p; intros. 
  eapply IHp2. 
  clear - H.
  (* clear using "-" fails *)
  clear IHp1.
  (* positive clear succeeds *) 
Abort.

**Comment by Zimmi48** [comment]
For short examples, it is indeed better to put the code directly in the description.

**Comment by ppedrot** [comment]
The problem stems from the fact that there is an evar in the goal, which literally mentions all variables from the context. It seems `clear` does a more involved analysis, but I don't know what the best behaviour is.

**Comment by Barry-Jay** [comment]
If the evar mentioned IHp1 then "clear IHp1" should fail, right? Either this example shows a bug, or "clear - H" is intended to be conservative, i.e. may not clear all that it is safe to clear. Anyway, thought I'd bring it to your attention, in case you find it interesting.

**Comment by SkySkimmer** [comment]
Not a bug
