### ISSUE TITLE
Report on the 8.8 to 8.10 compatibility of packages in coq-contribs

### ISSUE THREAD

**Issue by herbelin** [coq/coq#11244]
Hi, here are a few (partial) comments about porting developments from Coq 8.8 to 8.10 (continuing #8793).

Globally, it takes time but it works relatively well, with helpful messages or tools. It was painful in some specific cases though.

#### Deprecation of alias

The script `replace-notations.py` was very good. A posteriori, the warning could have been improved to report about the full name (including its dirpath) and not only the basename.

#### Removal of `Implicit Arguments` and `Arguments Scope`

This is rather straightforward. A posteriori, that would somehow have been good to have a script in the style of `replace-notations.py`.

#### Move from .ml4 to .mlg

The renaming and insertion of curly brackets is easy, but `coqpp` seems to suffer from being a bit "young" and not helpful in case of problems. To fix syntax errors, I have to look at the code of `coqpp` to know what to do. Also, entries such as `INT` and `LIDENT` are not supported anymore and cause the brutal death of `coqpp`. (I still have to find what are the replacements...) Location reporting does not seem always accurate.

#### Removal of `Quote`

I'll probably add it as a package (which requires less thinking than adapting).

#### Removal of template polymorphism in sections

Moving the type outside the section is canonical.

#### Unidentified problems with import of coercions

Problems with imports are the most difficult to solve: need to compare the old and new scripts, and sometimes not at the place where it starts to fail.

#### Miscellaneous regressions

- `cofix with` tactic is broken (I made a fix at #11241). That would be good to do have a 8.10 with a working  `cofix with`??
- `coq_makefile` does not support anymore the camlp5 extensions automatically (in case of a ml4 file which is not about extending the grammar but of, e.g. using an `IFDEF`). I guess this can be resolved by calling `ocamlfind` explicitly but I don't know yet how to do it.
- maybe in relation with the removal of `Standard Proposition Elimination Names`, `Program Fixpoint` was still using `H`-names for `eq_dec` and cie but stops doing so in 8.10. Compatibility is obtained by using some `try rename`.
- some mini-changes such as putting hints in a database (6f1634d2f82) have an impact.

#### Warnings

- `Focus`: easy to fix using `n:{ ... }` as explained in the warning message.
- changes in ml files: generally the suggestions are very useful! Sometimes, knowing how the code is organized is needed (e.g. when to use `econstr`, how universes and globals work together, proof engine, ...). I hope it is not too painful for external contributors.
- hints in core: easy (a script should be made!)
- "The extraction is currently set to bypass opacity": don't know what to do. 

#### `fourier`

The upgrade works rather well by using `lra`. The difficulties are that `Require Import Fourier` includes some constants and scopes which have to be expressed differently (e.g. using lemmas from `Reals`).

#### `omega`/`romega`

The move to `lia` works pretty well. A painful consequence has been to control the section variables used by `omega`/`lia` since this affects the form of a theorem at the end of the section.

#### Primitive string parsers

Adding `Import Coq.Strings.String.string` works well.

**Comment by ejgallego** [comment]
Nice overview thanks @herbelin 

> * `coq_makefile` does not support anymore the camlp5 extensions automatically (in case of a ml4 file which is not about extending the grammar but of, e.g. using an `IFDEF`). I guess this can be resolved by calling `ocamlfind` explicitly but I don't know yet how to do it.

That should be pretty easy to add as a rule, are there are lot of developments ? If not you could just add the rules in the local makefile.

**Comment by herbelin** [comment]
Basically, there are two contribs (PTS from Bruno and graphs from J. Goubault) which use `let rec expr = parser [< ... >] -> ...` and I don't know what the good way to write a rule to support that (formerly, the `PP` variable of coq_makefile, referring to $(CAMLP5O), $(CAMLLIB) and$(CAMLP5EXTEND), was apparently doing the job).

**Comment by ejgallego** [comment]
@herbelin something such as:
```
%.ml: %.ml4
       camlp5o pr_o.cmo -impl $@ -o $<"
```
should do the job [modulo the modules that you want to load]

**Comment by herbelin** [comment]
But shouldn't I ask `ocamlfind` to tell where is `camlp5o` the same way as one asks it to find `ocamlc`? (I'm rather ignorant of `ocamlfind`.)

**Comment by ejgallego** [comment]
> But shouldn't I ask `ocamlfind` to tell where is `camlp5o` the same way as one asks it to find `ocamlc`?

No, you should use the one that is in the path.

What `ocamlfind ocamlc` does is to compute the flags for packages, that is to say, expands `ocamlfind opt -package foo` to `ocamlopt -I ... foo.cmxa` etc...

**Comment by herbelin** [comment]
Is it correct that `Instance ... := ...` should now be prefixed with `Program` when obligations remain? I don't see a reference to that in the release notes.

**Comment by SkySkimmer** [comment]
In 8.10 you can set Refine Instance Mode, iin 8.11 you can use `#[refine]` locally.
The deprecation and later removal of Refine Instance Mode should be in the changelog AFAIK.

**Comment by Zimmi48** [comment]
>  The deprecation and later removal of Refine Instance Mode should be in the changelog AFAIK.

Indeed, it is.

**Comment by herbelin** [comment]
Thanks. I did not know this flag and I had only grepped `Program` and `Obligation`. So, my understanding is that the intended fix is to add `Program`.

**Comment by herbelin** [comment]
Do I now produce opam packages for coq-contribs 8.9 and 8.10 like I did for Coq 8.7 and 8.8 or is there something smarter to do?

**Comment by Zimmi48** [comment]
Yes, this would be great!

**Comment by ejgallego** [comment]
This was nice feedback, I guess we can archive it.
