### ISSUE TITLE
typo in the reference manual

### ISSUE THREAD

**Issue by matejkosik** [coq/coq#11275]
#### Description of the problem

Section [Calculus of Inductive Constructions](https://coq.inria.fr/distrib/current/refman/language/cic.html#typing-rules) of the "Coq Reference Manual" contains a typo.

The second hypothesis of the "Prod-Type" rule should be

  Type(i)

Currently, it reads

  Typei

(parentheses around "i" are missing).

#### Coq Version

8.10.2

**Comment by Columbus240** [comment]
Was fixed by commit 9995c44df32858624a84a5f87f14a4a24124f84e.
