### ISSUE TITLE
Bad printing with letin in inductive arity

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#11282]
~~~coq
Inductive foo : forall (A:Type) (B:=Set), Type := .

Set Printing All.
Print foo_rect.
(* foo_rect = 
fun (P : forall A : Type, let B : Type := Set in forall _ : foo A, Type) (A : Type) =>
let B : Type := Set in fun f : foo A => match f as f0 in (@foo A0 B0) return (P A0 f0) with
                                        end
     : forall (P : forall A : Type, let B : Type := Set in forall _ : foo A, Type) 
         (A : Type) (f : foo A), P A f

Arguments foo_rect _%function_scope _%type_scope
*)
~~~
`in (@foo A0 B0)` isn't right: B isn't a real argument.

**Comment by ppedrot** [comment]
IIRC I fixed this in my branch that changes the representation of pattern-matching.

**Comment by SkySkimmer** [comment]
@ppedrot still present

**Comment by herbelin** [comment]
It is not really a bug. For instance, you can reparse the result. The point is that in patterns, and the `in` clause actually takes a pattern as argument, it is allowed to give names to local definitions.

The name given to the local definitions can even be used, as e.g. in:
```
Check fun (P : forall A : Type, let B : Type := Set in forall _ : foo A, Type) (A : Type) =>
let B : Type := Set in fun f : foo A => match f as f0 in (@foo A0 B0) return B0 -> (P A0 f0) with end.
```
Of course, we could still optimize and drop the display of `B0` when `B0` is not used in the return clause...
