### ISSUE TITLE
Access to the rest rest of the eauto search in Hint Extern?

### ISSUE THREAD

**Issue by gmalecha** [coq/coq#11290]
#### Description of the problem

This is a *feature request*. I'm wondering if it would be possible to get access to the rest of the search as a tactic in a `Hint Extern`. For example, I would like to be able to do something like:

```coq
Hint Extern 3 (f ...) => eapply X; continue : lemmas.
```

Where the `continue` tactic resumes the search on the generated goal. My motivation for wanting something like this is I would like to check some side-conditions, e.g. lack of unification variables in certain positions, before applying a lemma. For example,

```coq
Hint Extern 3 (f ?A ?B) =>
  assert_fails (has_evar A) ; apply lemma ; continue : lemmas.
```

The alternative would be to replace `continue` with `eauto` but I lose access to the other hint databases that might be included in the current search and I lose access to the current depth.

When would ensure that `lemma` is only applied if the first argument of `f` does not contain a unification variable.

*I'd be happy to hack on this if people are interested.*

#### Coq Version

```
The Coq Proof Assistant, version 8.9.1 (June 2019)
compiled on Jun 4 2019 22:11:06 with OCaml 4.07.1
```

**Comment by JasonGross** [comment]
I'm a bit confused.  Isn't this the default behavior already (unless you've run out of search depth), to continue on generated subgoals?

**Comment by gmalecha** [comment]
I wasn't aware of this. From reading the docs this doesn't seem clear to me, but you're right, it seems to behave this way. Thanks for the clarification.
