### ISSUE TITLE
`make TIMED=1` should also display time of ocaml commands

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11309]

**Comment by Zimmi48** [comment]
@JasonGross Was this addressed by #12211? If not, do you still intend to address it for 8.12?

**Comment by JasonGross** [comment]
Yes, this was closed by #12211 .  I guess I forgot I had reported this.  Perhaps the changelog entry should be updated?

**Comment by Zimmi48** [comment]
>Perhaps the changelog entry should be updated?

Not a big deal.
