### ISSUE TITLE
`constr_eq` identifies identifiers that are printed differently

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#11300]
#### Description of the problem

~~~coq
Require Import ZArith.

Goal BinIntDef.Z.of_N = BinInt.Z.of_N.
  (* Goal : BinIntDef.Z.of_N = Z.of_N *)
  assert_fails (constr_eq BinIntDef.Z.of_N BinInt.Z.of_N).
  (* Tactic failure: <tactic closure> succeeds. *)
Abort.
~~~

So of course we write `change BinIntDef.Z.of_N with Z.of_N in *` to read out goals. It's tolerable, but why...

#### Coq Version

The Coq Proof Assistant, version 8.10.1 (November 2019)
compiled on Nov 1 2019 17:12:46 with OCaml 4.09.0

**Comment by JasonGross** [comment]
This is one of the rough spots of Coq.  When you `Include` a module, there is special support for identifying the inductive types.  They have different kernel names, but are considered to be the same.  But it is much easier to get two terms which print differently but are the same under `constr_eq`: `fun x : unit => x` and `fun y : unit => y`.  I don't think we want `constr_eq` to be sensitive to alpha, but it would be nice to be able to fine-tune the various options of constr equality, I think.

**Comment by maximedenes** [comment]
I think this is invalid, these two terms are indeed equal.
