### ISSUE TITLE
Omega deprecation in 8.11

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#11304]
Hi folks,

I'm opening this issue to discuss deprecation of the omega tactic in 8.11, I intended to discuss this on the WG but we didn't have time.

- @maximedenes wrote on some discussion on Gitter: "bottom line: we'll deprecated once stdlib is ported without regressions"

I disagree with this strategy, and I think we should start warning about `omega` planned obsolescence now. As far as I could witness in https://github.com/coq/coq/pull/11286 core users are still developing new code using `omega`.

IMHO the current situation is a strong disservice to them, as they will have to work twice, once now as they are writing proofs with omega, and later on when indeed `omega` becomes stronger via the rebinding to `lia`.

Maxime points out that there is indeed a problem due to the `auto` hints using omega; that's easy to solve technically for 8.11 as we can ignore the warning only for these hints [by rebinding them to a warning-free omega version]

@ppedrot to what my regards feel free to close this issue if you think it is too late [but I'd suggest we add a notice to the changelog at the very least]

**Comment by ppedrot** [comment]
It's probably too late, but I am open to an official statement of "pre-deprecation" somewhere visible though.

**Comment by maximedenes** [comment]
The "ciao" was not part of the comment, I was going for lunch :)

**Comment by maximedenes** [comment]
> an official statement of "pre-deprecation" somewhere visible though

Yeah, I think that's the way to go, encouraging users to experiment with `lia`.

An actual deprecation warning should wait for us to make sure we can port the current developments without regressions (like the ones we had so far, a few incompleteness bugs and performance regressions that have been fixed).



> as they will have to work twice, once now as they are writing proofs with omega, and later on when indeed `omega` becomes stronger via the rebinding to `lia`.

As I said in the discussion, I think this argument is bogus, since the transition will be transparent for any development which does not rely on `omega` bugs (i.e. relying on some linear arithmetic goals not being solved by `omega`). I expect this to happen much less often than standard uses of `omega`, which won't induce any duplicate work (beyond a search-and-replace).

**Comment by ejgallego** [comment]
> The "ciao" was not part of the comment, I was going for lunch :)

Ups, I selected too much sorry.

**Comment by ejgallego** [comment]
> I think this argument is bogus, since the transition will be transparent for any development which does not rely on `omega` bugs

I fail to see how the argument is bogus; in the worst case it could not be apply indeed if no development would rely on `omega` bugs; however this is not the case; preliminary testing seems to suggest that breakage due to `lia` being stronger is quite pervasive and may require large development effort to fix.

How have you come up with the number of places "omega" is used "incorrectly".

**Comment by Zimmi48** [comment]
I agree with @ppedrot and @maximedenes: this is too late to add the deprecation in 8.11, but could get a special mention in the changelog.

**Comment by maximedenes** [comment]
Looks good to me, for 8.11 it would be good to encourage users to switch to `lia` if they don't fear potential regressions (as we will probably fix a few more when completing the port), and if they make sure their code won't rely on `lia` bugs.

**Comment by ejgallego** [comment]
@Blaisorblade notes the GHC style for deprecation notices https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid#Writingcompatiblecode

Indeed the omega -> lia should include best practices for user migration.

**Comment by Zimmi48** [comment]
The conclusion was:

- to deprecate `omega with` in 8.11
- to document in the changelog and documentation that users should probably start using `lia` instead of `omega` at least for new code, and report any regression they find.

**Comment by ppedrot** [comment]
Who is writing the documentation patch for the recommendation to switch to lia in 8.11?

**Comment by Zimmi48** [comment]
See #11349 for a proposal.
