### ISSUE TITLE
Spurious failures in complexity tests

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#11303]
I have seen recently a number of spurious failures in our CI due to complexity tests. I believe we should run them on the bench infrastructure (which we have precisely to get consistent performance) instead of the CI, where VMs can make performance vary greatly from one build to another.

Cc @coq/ci-maintainers

**Comment by maximedenes** [comment]
Example failure that looks spurious (although I don't know how to read the numbers and compare them to the expected bounds): https://dev.azure.com/coq/coq/_build/results?buildId=6451&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=77aad734-2057-5694-9ae2-ee1f5f26eae8

**Comment by maximedenes** [comment]
Another one here: https://dev.azure.com/coq/coq/_build/results?buildId=6439&view=logs&j=800c766b-cf7f-545c-6b0a-ae5b31f2fdcf&t=55ae28f1-7f2e-576e-a111-f47fcce6aea9

**Comment by maximedenes** [comment]
Another one: https://dev.azure.com/coq/coq/_build/results?buildId=6453&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=77aad734-2057-5694-9ae2-ee1f5f26eae8

**Comment by maximedenes** [comment]
Cc @herbelin

**Comment by maximedenes** [comment]
I'm going to ignore these failures in order to unblock the merge of important PRs, hoping not to do anything wrong.

**Comment by SkySkimmer** [comment]
Windows should be ignoring the complexity tests since there aren't bogomips, what is going on?

**Comment by SkySkimmer** [comment]
Could be from the recent release of cygwin 3.1.0 https://cygwin.com/ml/cygwin-announce/2019-12/msg00015.html
>- Improve /proc/cpuinfo output and align more closely with Linux.

**Comment by SkySkimmer** [comment]
See https://github.com/coq/coq/pull/11312

**Comment by maximedenes** [comment]
Thanks, @SkySkimmer !

**Comment by JasonGross** [comment]
If you scroll up in the build log, you'll notice `expr: syntax error`.  The issue is that there's an extra trailing newline (probably `\r`?) that ends up in the first contents of `res`, which makes the recalculation of `res` be empty, which makes `expr` fail because it's trying to do `expr \(  \* 6120 \)` or similar.  See #11308
