### ISSUE TITLE
Strange Behaviour with Custom Entries and Import/Export

### ISSUE THREAD

**Issue by Janno** [coq/coq#11313]
#### Description of the problem

There seems to be bad interaction with custom entries and importing/exporting modules that define such entries.

In the following code, the custom entry `test` ends up being empty.
```coq
Module G.
  Declare Custom Entry test.
  Notation "'some_keyword'" := (1) (in custom test at level 0).
End G.
Import G.
Print Custom Grammar test. (* one rules *)
Import G.
Print Custom Grammar test. (* zero rules *)
```

Additionally, undoing the second `Import G` deletes the custom entry entirely. (I.e., `Print Custom Entry test` fails.)

The second `Import G` can be replaced by `Export G`, yielding the same behaviour.

#### Coq Version

master with a bunch of PRs already merged in because I like to live dangerously. With a bit of extra notation one can reproduce this in the 8.11 branch. Define
```coq
Notation "'[test' t ]" := (t) (at level 0, t custom test at level 0).
```
and substitute `Print Custom Grammar test` by `Check [test some_keyword ]`.

**Comment by maximedenes** [comment]
At least some of these problems show up without `Import`:

```coq
Declare Custom Entry foo.
Print Custom Grammar foo.
Declare Custom Entry foo.
```

playing these three commands, navigating back to after the first command and printing again triggers `Unknown or unprintable grammar entry.`

Cc @ppedrot who nicely offered to help on this issue, as he knows more about the way the camlp5 state is synchronized with the rest of the system state.

**Comment by ppedrot** [comment]
This bug actually raises the question of the semantics of custom entries inside functors. I guess that if we go for a kernel-name based solution they need to be generative...

**Comment by JasonGross** [comment]
The semantics should be the same as the current semantics of `Declare Scope` and `Declare Reduction` (even though I think the semantics of `Declare Reduction` should change to match that of `Ltac`, `Definition`, and `Notation` without quotes...)
