### ISSUE TITLE
Set Default Proof Using doesn't allow -vos to skip proofs within sections

### ISSUE THREAD

**Issue by tchajed** [coq/coq#11342]
I wanted to take advantage of the new vos support and found it gave essentially no speedup. This seems to be because all the proofs are still being compiled due to everything being in a section and missing Proof using annotations, even though there's a `Set Default Proof Using "Type"` in basically every file.

#### Description of the problem

`proof_using.v`:
```
Section foo.
  Context {H:True}.
  Theorem test1 : True.
  Proof.
    (* this gets printed with -vos because there's no annotation *)
    idtac "without using".
    exact I.
  Qed.
End foo.

Section foo.
  Context {H:True}.
  Set Default Proof Using "Type".
  Theorem test2 : True.
  Proof.
    (* BUG: this gets printed when compiling with -vos *)
    idtac "proof with default using".
    exact I.
  Qed.

  Theorem test3 : True.
  Proof using Type.
    (* this isn't printed with -vos *)
    idtac "using".
    exact I.
  Qed.
End foo.

```

```
❯ coqc -vos proof_using.v
without using
proof with default using
```

The first line "without using" is fine (there isn't the right annotation), but "proof with default using" should not be printed.

#### Coq Version

8.12+alpha

**Comment by gares** [comment]
I'll Try to have a look for the final release

**Comment by tchajed** [comment]
@gares I looked into this a little bit and I think https://github.com/coq/coq/blob/master/stm/stm.ml#L2157-L2180 is to blame. This is the code that decides if there's a proof using annotation. It only looks at the VernacProof object, whereas [vernac/vernacentries.ml](https://github.com/coq/coq/blob/master/vernac/vernacentries.ml#L2290) checks `Proof_using.get_default_proof_using`.

This looks a little complicated to me but I could figure it out. Is that enough information to make this easy for you?

**Comment by gares** [comment]
Yes, I think it is ok.

**Comment by Blaisorblade** [comment]
Both I and @tchajed observed Coq *deadlock* with this PR, upon certain proofs that omit `Proof.`.
We should file a proper bug, but that's bad enough that for now I'm taking the liberty to reopen this.

**Comment by tchajed** [comment]
Opened #11608 for the new issue.

**Comment by gares** [comment]
There are a few horrible hacks to make vio not hang. Maybe we should double che the if guards also trigger on vos mode.

**Comment by gares** [comment]
I'm talking about skipping Print or Extraction of period not being computed.
