### ISSUE TITLE
Extraction with `Unset Extraction SafeImplicits` may produce ill-typed code

### ISSUE THREAD

**Issue by pi8027** [coq/coq#11344]
#### Description of the problem

```coq
Require Extraction.

Definition id (x : nat) := x.

Extraction Implicit id [x].
Unset Extraction SafeImplicits.
Recursive Extraction id.
```

```ocaml
type __ = Obj.t
let __ = let rec f _ = Obj.repr f in Obj.repr f

type nat =
| O
| S of nat

(** val id : __ -> nat **)

let id _ =
  __ (* 1st argument (x) of id *)
```

`__` is expected to have type `nat` but have type `Obj.t`.

#### Coq Version

master

**Comment by ppedrot** [comment]
Isn't it by definition? The documentation states that a warning is emitted if some implicit argument remains accessible in the extracted code, which is the case in your example. This behaviour doesn't constitute a bug, AFAIU.

**Comment by pi8027** [comment]
> The documentation states that a warning is emitted if some implicit argument remains accessible in the extracted code, which is the case in your example.

@ppedrot Yes. The warning says "this code is potentially *unsafe*" and requires to review it manually, but does not say this is potentially non-compilable code.

**Comment by pi8027** [comment]
> Note that this extracted code might not compile or run properly, depending of the use of these remaining implicit arguments.

Oh, I didn't check this documentation. Let's close then. (But I think the warning message probably should be improved.)
