### ISSUE TITLE
Using ExtrOcamlNatInt and ExtrOcamlZInt generates code that is deprecated in OCaml > 4.07

### ISSUE THREAD

**Issue by palmskog** [coq/coq#11359]
#### Description of the problem

The OCaml developers deprecated the `Pervasives` module in OCaml > 4.07.0. However, using the files `plugins/extraction/ExtrOcamlNatInt.v` and `plugins/extraction/ExtrOcamlZInt.v` lead to extracted OCaml code that contains calls to functions in `Pervasives`.

Here is a simple example:
```coq
Fixpoint max n m :=
  match n, m with
    | 0, _ => m
    | S n', 0 => n
    | S n', S m' => S (max n' m')
  end.
Require Extraction.
Require Import ExtrOcamlNatInt.
Extraction "max.ml" max.
```
We can then run the file and compile the OCaml code on 4.09.0:
```bash
$ coqc max.v
$ ocamlc max.ml
File "max.ml", line 10, characters 17-32:
10 |       (fun m' -> Pervasives.succ (max n' m'))
                      ^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the 
stdlib-shims library: https://github.com/ocaml/stdlib-shims
```
The straightforward fix is to change `Pervasives` to `Stdlib`, but this will likely break a lot of extraction-based projects, so some deprecation warning in 8.11.0 might be useful.

#### Coq Version

All Coq versions up to and including `master` as of January 2020.

**Comment by JasonGross** [comment]
I think a better solution would be to implement #11987, and then have these files blacklist `succ` so that we can extract the constant to (unqualified) `succ`, to be compatible with both versions.

**Comment by palmskog** [comment]
@ppedrot could we add this issue to OCaml 5.0 project? Since `Pervasives` breaks in OCaml 5.0. For example: https://github.com/ocaml/opam-repository/commit/73245fbffa505bc6968944ca023efa75d690d8aa

**Comment by ppedrot** [comment]
Yes, do not hesitate to put stuff there on your own volition.
