### ISSUE TITLE
Version picking for 8.11

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#11351]
This is not really an issue, more a reminder and maybe a point for discssion. There appear to be a few deviations from the discussed policy in the version picking in file `dev\ci\ci-basic-overlay.sh` for 8.11:

- bignums_CI_REF:=v8.11 is a branach
- mtac2_CI_REF:=master-8.11 is a branch
- paramcoq_CI_REF:=v8.11 is a branch

I guess you plan to replace these with hashes and/or tags shortly before the release?

Everything else is set to commit hashes. Is it really so that for none of the addons we can pick proper tagged releases? Afaik the discussed policy is to use the latest tagged release unless this doesn't work.

If any of the picks are controversial and need testing or if I can help otherwise with this please let me know.

**Comment by ppedrot** [comment]
I am not quite sure what the policy is, I have heard contradicting pieces of advice. Summoning @Zimmi48.

**Comment by MSoegtropIMC** [comment]
Yes it is not really written down, but it has been discussed quite a bit in the previous picking issues and PRs. The point is that some owners of libraries or components complain if we pick more or less arbitrary intermediate points of their developments. And of cause it makes sense. The problem is that it is not really possible to do it right - something I want to solve with the platform approach. First release just Coq, give the libray developers a few months to make proper releases and then release the platform (Coq + libraries + plugins). But at least we can try until the platform approach is ready.

**Comment by Zimmi48** [comment]
@ppedrot did the picked arbitrary commit hashes to make sure CI will keep passing on v8.11 (and that explains the use of a branch when it exists). For the final release, it would be good to change this to use the latest tag when such tag happens to be compatible with Coq 8.11. This is clunky indeed, and this is why we need to move forward on the platform to have a more robust approach and relieve the RM from this topic. @MSoegtropIMC I am currently working on internship proposals related to this. I'll send them to you for review before publicizing them.

**Comment by MSoegtropIMC** [comment]
@ppedrot : just wanted to ask if you think you need help with this this week.

@Zimmi48 : sure, I am looking foward to it. Please note that a preliminary "platform charter" already exists at (https://github.com/MSoegtropIMC/coq-platform/blob/master/charter.md). I didn't get that much further as yet, but I think the key is the experience we gathered in the past with what works and what not. Having some interns working on this would definitely be ideas. I would be happy to help with guidance and reviews, but I should also shortly be able to work on it my self (the job change was time consuming).

**Comment by ppedrot** [comment]
@MSoegtropIMC I won't mind a bit of help on that front, thanks.

**Comment by MSoegtropIMC** [comment]
@ppedrot : how shall we split the work? Do you want to look at it first and tell me which packages are controversial and need follow up or shall I do the first analysis? Btw.: this is not only important for the packages we deliver with Windows, it is also important for other packages since this serves e.g. as reference for opam version dependency entries. But in the past I focused on what was delivered with the Windows installer and pretty mugh ignored the other packages in CI and the release managers typically didn't have time to look into the other packages either. We can also do it such that I concentrate on the packages which come with Windows and you on the other packages. But I am also fine if you say you want the compelete set at least looked at (in the sense that the basic overlays file has some comments why specific versionshave been picked in case they are not the latest tag).

**Comment by Zimmi48** [comment]
I think for this release it is fine to focus only on the packages that are shipped in the Windows installer and leave the other at what they are today (a commit hash or a dedicated v8.11 branch).

**Comment by MSoegtropIMC** [comment]
OK, I will look into this over the week and prepare a PR. What is the current schedule?

**Comment by Zimmi48** [comment]
@MSoegtropIMC Is your new e-mail address the same one as before but with `apple` instead of `intel`?

**Comment by ppedrot** [comment]
@MSoegtropIMC the schedule is defined as the shortest one that is reasonably achievable, AFAICT. A few days of delay are fine, but this should expand much more past that.

**Comment by MSoegtropIMC** [comment]
I am traveling on the weekend and can't tell if I can finish it before. I am quite sure I can finish it before Tuesday next week.

**Comment by ppedrot** [comment]
That should be fine.

**Comment by MSoegtropIMC** [comment]
Just wanted to lat you know that I am working on this today and if I can't finish it today also tomorrow.

**Comment by MSoegtropIMC** [comment]
A question on the CompCert picking: for those modules which have a proper release management (to which CompCert belongs) I prefer to use the latest release with only minor patches on top to fix 8.11 compatibility (that is a cherry pick of  a commit in master over v3.6). The earliest commit in master which compiles does have functional changes over 3.6 which is not nice (it would behave differently from 3.6 on 8.10.2).

The Windows build system does support this - it has a patching system. The usual CI system does not support this (at least not that I knowof). The options are:

- Disable compcert in CI (it is still tested in Windows and it would not build without the patch when v3.6 is picked)
- Override the compcert_CI_REF variable in the Windows build and use a commit from master in CI
- Support the patching system used in the Windows build in CI - originally it was intended to fix Windows specific stuff but it is mostly used for release patching since a few years
- Implement cherry picking in CI and Windows (that is have a compcert_CI_CHERRYPICK variable).
- Do a quick solution now (either disable it in CI or use different versions) and create an issue to do it properly later.

**Comment by ppedrot** [comment]
As the RM, I'd personally favour the "quick" solution, even if it's hackish and duplicating code paths.

**Comment by MSoegtropIMC** [comment]
OK, I will pick something from master for CI then and override it in the Windows build with v3.6 + the cherry pick.
