### ISSUE TITLE
Inconsistent variable substitution when matching on "let fix" using Ltac

### ISSUE THREAD

**Issue by lastland** [coq/coq#11389]
#### Description of the problem

Here is a minimal example that can reproduce the bug:
```coq
Definition foo :=
  let fix go n a b :=
      match n with
      | S n' => (n, n + snd (go n' a b))
      | O => (a, b)
      end in
  go.

Goal forall n, n > 0 -> snd (foo n 0 0) > 0.
Proof.
  intros. cbv beta delta[foo]. 
  match goal with
  | |- snd ((let x := ?rhs in ?body) _ _ _) > 0 => idtac rhs; idtac body
  end.
```

The output:
```coq
(fix go (n a b : nat) {struct n} : nat * nat := match n with
                                                | 0 => (a, b)
                                                | S n' => (n, n + snd (go n' a b))
                                                end)
x
```

In the first part (in `rhs`), the fixpoint's name remains as `go` while in the second part (in `body`) the name has been changed to `x`, which is the variable name we used in the matching clause in Ltac. If we change the variable name to `y` in the matching clause, the variable name in `body` will change as well, but not the variable name in `rhs`, which should refer to the same variable.

The problem did not appear when we were using Coq 8.8. Unfortunately, I have not got the time to test since which Coq version the problem has appeared.

This has affected us in the `hs-to-coq` project. In particular, we rely on a custom tactic to "float" `let`-clauses outside, which works well with Coq 8.8 but no longer works with Coq 8.10.2. We have to resolve to a temporary workaround here:https://github.com/antalsz/hs-to-coq/commit/74e83ea7ffc558ff778678597139dcd87f58b94f#diff-4c03f5269c19d75442f5862b0de92ef1

#### Coq Version

8.10.2

**Comment by ppedrot** [comment]
Contrarily to what you experienced, Coq 8.8 seems to behave the same as Coq 8.11 on my machine, i.e. `body` is printed as `x`. What exactly do you want the body to be? `go`?
