### ISSUE TITLE
build failure of 8.10.2 on debian/arm64: Unbound module Gramlib

### ISSUE THREAD

**Issue by treinen** [coq/coq#11391]
#### Description of the problem

Version 8.10.2 (the debianized version) fails to build on arm64, with error message

````
"/usr/bin/ocamlfind" ocamlc -thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence    -I coqpp -I config -I clib -I lib -I kernel -I kernel/byterun -I library -I engine -I pretyping -I interp -I proofs -I gramlib/.pack -I parsing -I printing -I tactics -I vernac -I stm -I toplevel -I tools -I tools/coqdoc -I plugins/omega -I plugins/micromega -I plugins/setoid_ring -I plugins/extraction -I plugins/cc -I plugins/funind -I plugins/firstorder -I plugins/derive -I plugins/rtauto -I plugins/nsatz -I plugins/syntax -I plugins/btauto -I plugins/ssrmatching -I plugins/ltac -I plugins/ssr -g  -open Gramlib -no-alias-deps -w -49 -no-alias-deps -w -49 -c clib/cSig.mli
File "command line", line 1:
Error: Unbound module Gramlib
````

The full build log can be found [here](https://buildd.debian.org/status/fetch.php?pkg=coq&arch=arm64&ver=8.10.2-1&stamp=1578910488&raw=0). 

#### Coq Version

8.10.2 (debian/experimental)

**Comment by ppedrot** [comment]
Ping @ejgallego, AFAIR he's the one to have implemented the packing script for gramlib.

**Comment by SkySkimmer** [comment]
log says
~~~
"/usr/bin/ocamlfind" opt -thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence  -I coqpp -I config -I clib -I lib -I kernel -I kernel/byterun -I library -I engine -I pretyping -I interp -I proofs -I gramlib/.pack -I parsing -I printing -I tactics -I vernac -I stm -I toplevel -I tools -I tools/coqdoc -I plugins/omega -I plugins/micromega -I plugins/setoid_ring -I plugins/extraction -I plugins/cc -I plugins/funind -I plugins/firstorder -I plugins/derive -I plugins/rtauto -I plugins/nsatz -I plugins/syntax -I plugins/btauto -I plugins/ssrmatching -I plugins/ltac -I plugins/ssr -g     -o bin/coqdep_boot -linkpkg  -I tools -package unix clib/segmenttree.cmx clib/unicodetable.cmx clib/unicode.cmx clib/minisys.cmx tools/coqdep_lexer.cmx tools/coqdep_common.cmx tools/coqdep_boot.cmx && true bin/coqdep_boot && true bin/coqdep_boot
collect2: fatal error: ld terminated with signal 4 [Illegal instruction]
compilation terminated.
File "caml_startup", line 1:
Error: Error during linking
~~~
which I guess is the real error.

**Comment by treinen** [comment]
@SkySkimmer yes, this is most probably the source of the error. In fact, there is a second
occurrence of a fatal error of ld (just search for "fatal" in the log). Is this a bug of the ocaml compiler on arm64? We are using 4.08.1.

**Comment by ejgallego** [comment]
After a closer look at this bug with @treinen it seems that the buildd is not able to build any binary with success; this is very likely an OCaml problem.

@treinen as discussed offline here is the repos to try to reproduce the bug on a developer machine

https://github.com/ejgallego/ocaml-arm64-bug

`dune build` should try to build the same binary that failed, check `_build/log` or use `--display=verbose` to get more details; let me know how that turns out, thanks.

**Comment by treinen** [comment]
I just stumbled by chance over [this bug report about ld failing on arm64](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948803). So I guess we don't have to look any further.

**Comment by treinen** [comment]
This seems to be fixed by the new version of the binutils package in debian.
