### ISSUE TITLE
Rlist hides standard list constructors cons and nil in 8.11

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#11396]
In 8.11 we have this:
```
Require Import Reals.
Print cons.

Inductive Rlist : Set := nil : Rlist | cons : R -> Rlist -> Rlist
Arguments cons _%R_scope
```
This results in very substantial trouble in many modules which include Reals. A major issue is that many tactics use the standard list constructors. Unlike for Gallina code Coq cannot check at compile time if using such tactics would actually work - usually it doesn't. Many modules using Reals compile fine (possibly after some patching) but tactics don't work. The required patching can be substantial and tactics must be tested.

Since this is such a mess and likely also breaks a lot of user code (likely pretty much everything whic uses Reals) I would consider replacing Rlist with list R. I had a discussion with @ybertot on gitter on the topic and he mentioned that the raison d'être of Rlist is long gone (list was once restricted to Set).

I think we need to decide if we replace Rlist with list R and fix up the standard library in 8.11. I would strongly vote for it. It is likely faster than fixing up all the remaining failing modules in the 8.11 Windows installer (gappa is failing and proper picking for interval is extremely time consuming, some things are still untested).

**Comment by MSoegtropIMC** [comment]
P.S.: the reason we didn't have this issue in 8.10 is likely because the bug in module load we had before 8.11 had the effect that Rlist did not hide list. After fixing this bug it does hide list.

**Comment by ppedrot** [comment]
We're quite late in the release process for this kind of bug, but if it is so troublesome, I guess we can make an exception. I don't think many people use the `Rlist` anymore, but removing it brutally may be a bit too much. In any case, we need a full CI run to evaluate the breakage.

The following alternative strategies I am thinking about are:
- Simply deprecate it. This should be enough to trigger warnings, even in Ltac code.
- Rename the constructors into `Rnil` and `Rcons`.
- Remove the Rlist module export from Reals.

**Comment by MSoegtropIMC** [comment]
I would say removing the export might be least invasive. If this is OK with you, I will do this as separate commit in the picking PR (since I need this there).

**Comment by MSoegtropIMC** [comment]
OK. Should I cherry pick the commit then in the picking PR then? Or do you get this in quickly and then I rebase?

**Comment by Zimmi48** [comment]
> I'd prefer a separate PR to easily spot it for bisects.

It is also better to make this a separate PR because it should target master whereas the picking PR is targeting v8.11 only. It makes sense for you to cherry-pick your fix in your picking PR, at least for testing.

**Comment by MSoegtropIMC** [comment]
OK, I will prepare a PR for master then.

**Comment by amahboubi** [comment]
Hi @MSoegtropIMC @Zimmi48 . I am glad to see that this is going to happen. I raised a similar issue a while ago: https://github.com/coq/coq/issues/6607. I am linking it so that it is closed as soon as the PR is merged.

**Comment by MSoegtropIMC** [comment]
@amahboubi : it is not exactly the same - this PR just avoids that RList is exported everywhere by importing Reals. I would also strongly vote for replacing RList with list R as you did, but I would do this as a second step (we are a bit under pressure with the 8.11 release).

**Comment by amahboubi** [comment]
@MSoegtropIMC, agreed.

**Comment by ybertot** [comment]
#11404 is just an experiment to see how heavy is the work to get rid of type RList.  @amahboubi, does duplicate some of your work?
