### ISSUE TITLE
Reserved Infix fails to reserve

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11402]
#### Description of the problem

```coq
Reserved Infix "||->{ f }" (at level 50, left associativity).
Infix "||->{ f }" := f.
(* Error: A left-recursive notation must have an explicit level. *)
Reserved Infix "||->[ f ]" (at level 50, left associativity).
Infix "||->[ f ]" := f.
(* Error: A left-recursive notation must have an explicit level. *)
```

cc @herbelin 

Maybe related to #4970 / #2867 ?

#### Coq Version

8.10.0

**Comment by JasonGross** [comment]
But apparently this works fine:
```coq
Reserved Notation "A ||->{ f } B" (at level 50, left associativity). 
Infix "||->{ f }" := f.
```
Apparently `Reserved Infix` is just broken?

**Comment by herbelin** [comment]
`Infix` was not intended to have extra parameters inside the infix list of symbols but this is actually a good idea. The generalization actually comes for free. It is in PR #14379.
