### ISSUE TITLE
[configure] float precision flags are C compiler-dependent.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#11426]
As pointed out in the discussion at https://github.com/coq/coq/pull/9867#issuecomment-575791940 , different C compilers do need different flags regarding floating point support.

Configure should thus detect the C compiler OCaml is using `config.c_compiler` [note that this doesn't have to be a single command]

There is also the question if another flag could be used, for example `-std=c99`.

**Comment by proux01** [comment]
Indeed, using `-std=c99` would be a good solution but the VM uses `asm` which is a GNU extension (also implemented by clang). A solution would be to use `-std=c99` in conjonction with `-fasm`. Would you agree with a PR implementing this?

**Comment by ejgallego** [comment]
I'm not expert enough on C compilers, so I'd prefer others to comment, but if that works indeed seems simpler than adding C compiler detection to `configure`.

By the way, that's likely a different bug but we should document in INSTALL the set of C compilers we support.

**Comment by proux01** [comment]
Well, let's go for the PR (#11432).

> By the way, that's likely a different bug but we should document in INSTALL the set of C compilers we support.

Unfortunately, we don't really choose the C sompiler. We use the one set at OCaml configure time. And the only information I could find in OCaml documentation is basically : « The GNU C Compiler (gcc) is recommended » (https://github.com/ocaml/ocaml/blob/trunk/INSTALL.adoc). Maybe we could say the same, or state the required features:
* implement C99 (`-std=c99`)
* implement asm GNU extension (`-fasm`)
* ...
