### ISSUE TITLE
Broken example in documentation of V8.9.0

### ISSUE THREAD

**Issue by fpottier** [coq/coq#11434]
#### Description of the problem

The paragraph entitled [Caveat](https://coq.inria.fr/distrib/V8.9.0/refman/language/gallina-specification-language.html#caveat) in the reference manual, version V8.9.0, contains broken examples: the examples include error messages from Coq, like `Error: Stream already exists.`

The problem disappears in V8.10.0.

#### Coq Version

8.9.0

**Comment by Zimmi48** [comment]
Hi, thanks for the report, but we do not actively maintain the 8.9 version anymore. You could still open a PR on the v8.9 branch though. That wouldn't result in fixing the 8.9.0 version of the manual at https://coq.inria.fr/distrib/V8.9.0/refman/, but it would still be automatically deployed at https://coq.github.io/doc/v8.9/refman/.
