### ISSUE TITLE
[install] CoqIDE install fails on byte architectures

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#11453]
Reported by @treinen :

```
install bin/coqide "/<<PKGBUILDDIR>>/debian/tmp/usr/bin"
install: cannot stat 'bin/coqide': No such file or directory
```
I guess we either could:
- build `coqide.opt` and use a special rule as for coqidetop:
```
$(COQIDEEXE): $(COQIDE:.opt=.$(BEST))
	rm -f $@ && cp $< $@
```
- guard the install step with `ifeq ($(HASCOQIDE),opt)`

**Comment by treinen** [comment]
Thanks for the indications. [This patch](https://salsa.debian.org/ocaml-team/coq/blob/master/debian/patches/install-coqide-bytecode) fixes the issue (with coq 8.9.1).
