### ISSUE TITLE
Missing "e" when printing decimal notations in R_scope using Coq 8.10

### ISSUE THREAD

**Issue by erikmd** [coq/coq#11467]
**Kind:** bug

### Description of the problem

I'm sorry to notice this only now that the 8.11 has been tagged :-/ but it seems a bug crept in PR https://github.com/coq/coq/pull/8764, which added parsing and pretty-printing support of decimal numeral litterals in Coq 8.10+.

Cc @proux01 

Namely, there is the following issue when pretty-printing litterals in scope `R_scope`: **the `e` is missing in scope `R_scope`**, while it is OK in `Q_scope` (see below); terms are parsed as expected so they can be proved equal with the intended terms, but this pretty-printing issue can obviously be confusing if we re-parse the pretty-printed terms…

### Coq Version

Using Coq 8.10 and Coq 8.11+beta1, miminal working example:

```bash
$ docker run --rm -i coqorg/coq:8.10 rlwrap coqtop <<EOF
Require Import QArith Reals Psatz.
Check (1.23e1, 32e+1, 0.1)%Q.
Check (1.23e1, 32e+1, 0.1)%R.
Goal (1.23e1, 32e+1, 0.1)%R = (123/10, 320, 1/10)%R. now repeat f_equal; lra. Qed.
EOF

Welcome to Coq 8.10.2 (January 2020)
[…]

Coq < (123e-1, 320, 1e-1)
     : Q * Q * Q

Coq < (123-1%R, 321%R, 1-1%R)
     : R * R * R

Coq < 
1 subgoal
  
  ============================
  (123-1%R, 321%R, 1-1%R) = ((123 / 10)%R, 320%R, (1 / 10)%R)

No more subgoals.
Unnamed_thm is defined
```

**Comment by proux01** [comment]
@erikmd : nice catch, I'm preparing a patch (will probably a +--1 line patch)

**Comment by erikmd** [comment]
@proux01 thanks! and you could probably also add some ".out" tests (one for each scope involved…)
