### ISSUE TITLE
coqtop 8.11+beta1 ignores vio files

### ISSUE THREAD

**Issue by hendriktews** [coq/coq#11470]
#### Description of the problem

`echo "Require Export a." | coqtop` fails with `Unable to locate library a. (While searching for a .vos file.)`, while `a.vio` is present in the current directory.

`a.vio` has been created by `touch a.v; coqc -quick a.v`.

#### Coq Version

The Coq Proof Assistant, version 8.11+beta1 (January 2020)
compiled on Jan 28 2020 9:03:23 with OCaml 4.09.0

**Comment by ppedrot** [comment]
Isn't that a duplicate of #11195, and thus fixed by #11280?

**Comment by hendriktews** [comment]
OK, sorry.

**Comment by ejgallego** [comment]
duplicate of #11195
