### ISSUE TITLE
lia regression in 8.11 with eta-expanded terms

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#11482]
#### Description of the problem

In Coq 8.10 `lia` worked on eta-expanded terms. In 8.11 it does not. For example,
```
Require Import Psatz.

Goal (S 1) + 1 = 1 + ((fun x => S x) 1).
Proof.
lia.
Qed.
```
works in 8.10, and fails in 8.11 with the message `Tactic failure:  Cannot find witness.`.
#### Coq Version

The Coq Proof Assistant, version 8.11.0 (January 2020)
compiled on Jan 24 2020 22:35:23 with OCaml 4.07.1

**Comment by herbelin** [comment]
Actually, this can also be seen as about `beta`-expanded terms!

Cc @fajb

**Comment by fajb** [comment]
Hi @mrhaandi , 
I did not see the bug report earlier.
I suspect that 8.10 was using an aggressive type-classes based identification of constants. This feature was quickly removed as it was sometimes very, very costly. 
So, I am sorry but the regression won't be fixed. That was a misfeature of 8.10...

**Comment by JasonGross** [comment]
World it be sufficient to add `cbv beta in *` to the preprocessor?  Would this have harmful effects in non-pathological cases?
