### ISSUE TITLE
Coqide: background color

### ISSUE THREAD

**Issue by davidnowak** [coq/coq#11506]
#### Description of the problem

When changing the background color, only the left frame is changed:
<img width="868" alt="coqide" src="https://user-images.githubusercontent.com/22745394/73606514-4b1ae780-45ab-11ea-8fc1-af9a6c7e5431.png">

#### Coq Version

On macOS Catalina 10.15.3, I have updated Opam to 2.0.6 with an up-to-date Homebrew, and then I have installed Coqide 8.11.0 with Opam.

**Comment by ppedrot** [comment]
Are you really using 8.11? The ability to change the background color was removed from that version, delegating it to the GTK style CSS.

**Comment by davidnowak** [comment]
> Are you really using 8.11?

Yes, definitely:

```
$ opam show coqide
<><> coqide: information on all versions ><><><><><><><><><><><><><><><><><>  🐫 
name                   coqide
all-installed-versions 8.11.0 [default]
```

For the screenshot, In _Edit -> Préférences -> Colors -> Highlighting style_ I chose "solarized-light".

**Comment by Alizter** [comment]
I've also noticed this on master fairly recently.

**Comment by herbelin** [comment]
PR #12106 fixes the application of the style to all three text buffers.

See also #11158 for changing the theme of the rest of CoqIDE (toolbar, frame, menus, ...).

**Comment by Zimmi48** [comment]
Your second link seems incorrect @herbelin.

**Comment by herbelin** [comment]
Fixed. I meant #11558.
