### ISSUE TITLE
Ltac2 rewrite on wildcard

### ISSUE THREAD

**Issue by tjmach** [coq/coq#11515]
**Error**
Don't know if this is already known,

```
From Ltac2 Require Import Ltac2.
Lemma foo :
  True.
Proof.
  rewrite _.
```
Produces the error message 

` Error: Anomaly "Evar ?X11 was not declared."
`
**Coq Version:**
8.11.0

**Comment by ppedrot** [comment]
Interesting, Ltac1 is not affected...
