### ISSUE TITLE
`Scheme Equality` should reuse existing boolean equalities

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#11541]
```coq
Require Import Coq.Strings.String.
Inductive bar := B1(x: string) | B2.

Scheme Equality for bar.
```

```
bool_beq is defined
ascii_beq is defined
string_beq is defined
bar_beq is defined
bar_eq_dec is defined
```

```coq
Print bar_beq.
```

```
bar_beq =
fix bar_eqrec (X Y : bar) {struct X} : bool :=
  match X with
  | B1 x => match Y with
            | B1 x0 => string_beq x x0
            | B2 => false
            end
  | B2 => match Y with
          | B1 _ => false
          | B2 => true
          end
  end
     : bar -> bar -> bool
```

As we can see, `bar_beq` does not use the existing `String.eqb`, which is unfortunate, because then I can't reuse existing proofs about `String.eqb`.

So I would like to have a way to tell `Scheme Equality` that it should use `String.eqb`. I tried

```coq
Definition string_beq := String.eqb.
```

before the `Scheme` command, but then `Scheme` says

```
Error: string_beq already exists.
```

Coq version: master

Not sure if that feature already exists and I just don't know how to use it -- if that's the case, then please treat this issue as a request to improve the documentation at https://coq.inria.fr/refman/user-extensions/proof-schemes.html.

**Comment by olaure01** [comment]
duplicate of #6794 ?

**Comment by samuelgruetter** [comment]
Yes, duplicate!
