### ISSUE TITLE
Ltac2 is incompatible with $ as alias for function application

### ISSUE THREAD

**Issue by tchajed** [coq/coq#11549]
#### Description of the problem

stdpp defines a notation `f $ x` for function application (at a higher precedence so that `f $ x + 1 = f (x + 1)` and `f $ g $ y = f (g y)` work, as in Haskell). Requiring Ltac2 breaks this notation:

```
From Ltac2 Require Ltac2.

Notation "t $ r" := (t r)
  (at level 65, right associativity, only parsing).
Check S $ O.
(* Error: Unbound value O *)
```

Specifically this triggers whenever you use `... $ ident`.

#### Coq Version

The Coq Proof Assistant, version 8.12+alpha (February 2020)
compiled on Feb 7 2020 14:12:30 with OCaml 4.08.1

**Comment by tchajed** [comment]
@ppedrot Is there any way in the Ltac2 parser to check that there's no space between $ and the next identifier, and let notations take over if there is whitespace? Iris never uses `f$x` with no space and I don't think support for `$ x` in Ltac2 is intentional.

**Comment by ppedrot** [comment]
I thought that this parsing issue was fixed at some point, but it seems not... There are several ways to fix this but it's going to be a pain.

**Comment by lilred** [comment]
I hit the same issue today. Tangentially, this seems to mess up CoqIDE state somehow. If you enter the file @tchajed provided and remove the Ltac2 import, it's still broken; but if you copy the resulting content and paste it into a separate buffer, it works.

**Comment by tchajed** [comment]
I think this is just a consequence of loading the Ltac2 plugin; requiring a plugin has some effects which Coq cannot undo when you backtrack over the import command. I can reproduce it in Proof General as well.

You can fix your IDE state by restarting the coqtop process (the up arrow button in CoqIDE) - note this is different from backtracking to the beginning of the file.

**Comment by ppedrot** [comment]
> I think this is just a consequence of loading the Ltac2 plugin; requiring a plugin has some effects which Coq cannot undo when you backtrack over the import command.

It shouldn't be the case though, save for really built-in behaviours, so this should be considered a bug. Do you have a reproducible snippet?

**Comment by tchajed** [comment]
Sure, here's an example. It's pretty simple - you can't undo vernacular extensions, right?

```
(* Run this, backtrack over it, then run the below command; it runs
   Tac2entries.print_ltac (but it can't find Std.intros so that fails).

  Before Ltac2 is loaded, this vernacular would be a syntax error.
 *)
From Ltac2 Require Ltac2.

Print Ltac2 Ltac2.Std.intros.
```
Instead of `Print Ltac2`, you can use `Check S $O` (with no space it's unaffected by your bug fix). It errors either way, but Ltac2 changes the error from "Lexer: Undefined token" to "Unbound value O".

**Comment by ppedrot** [comment]
Indeed, but this is not directly caused by Ltac2. Rather, vernacular extensions should be backtracked upon by plugins. I wonder why nobody ever complained about that so far.
