### ISSUE TITLE
Loading Ltac2 breaks Set Ltac Backtrace

### ISSUE THREAD

**Issue by tchajed** [coq/coq#11547]
#### Description of the problem

Requiring the Ltac2 plugin appears to break the `Set Ltac Backtrace` option. Note that backtracking over the `Require` interactively in Proof General doesn't even fix it (you have to restart Coq and not load Ltac2).

```
Require Import ssreflect.
Set Ltac Backtrace.

Goal False.
  Fail done.
  (* output includes
  Ltac call to "done" failed.
   *)
Abort.

From Ltac2 Require Ltac2.
Set Ltac Backtrace.

Goal False.
  Fail done.
  (* output no longer has message about done *)
Abort.
```

This breaks the Iris Proof Mode output tests.

#### Coq Version

The Coq Proof Assistant, version 8.12+alpha (February 2020)
compiled on Feb 7 2020 14:12:30 with OCaml 4.08.1

**Comment by ppedrot** [comment]
Most likely due to the call to `register_additional_error_info` in `Tac2entries`.

**Comment by ppedrot** [comment]
OK, this is actually a bug in `CErrors`, not in Ltac2. The way the handlers are sequentially tried is nonsense, it will always return the first one.

**Comment by ppedrot** [comment]
Also, this is in @ejgallego's ballpark, he is the one who last changed this code and introduced this new function.

**Comment by ejgallego** [comment]
The function was already there; I think I just moved it around in some cleanup. I recall indeed I saw something fishy and even tried to get rid of it, I'll have a look to see what's going on.

**Comment by ejgallego** [comment]
@tchajed please test and report how the things are working out; the PR Pierre-Marie just merged should improve things but actually the whole infrastructure is not very well tested.
