### ISSUE TITLE
Ltac2 breaks Search and Check vernaculars during proofs

### ISSUE THREAD

**Issue by tchajed** [coq/coq#11552]
#### Description of the problem

Using Search or Check during a proof with `Set Default Proof Mode "Ltac2"` fails with an Unbound constructor error. These are both useful while developing a proof so it would be nice if they were still recognized as queries.

```coq
From Ltac2 Require Import Ltac2.

Search unit.

Goal True.
  Fail Search unit.
  (* Unbound constructor Search *)
  Fail Check tt.
  (* Unbound constructor Check *)
Abort.
```

#### Coq Version

8.12+alpha

**Comment by tchajed** [comment]
@ppedrot can you comment on what might be going on here? For me this is a rather serious blocker to switching to Ltac2 by default. I'm confused why Ltac2 overriding the vernacular grammar in this situation and getting triggered at all.

**Comment by MSoegtropIMC** [comment]
For me this is also a serious issue.

**Comment by ppedrot** [comment]
It seems that the grammar rules are not processed in the right order. I'll have a look at the code.
