### ISSUE TITLE
Side effect safety may be broken by universe effects

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#11592]
This requires a plugin and is caught by the checker. In the plugin:
~~~ocaml
TACTIC EXTEND magic
| [ "magic" ident(i) ident(j) ] -> {
  DeclareUniv.do_constraint ~poly:false [ GType (Libnames.qualid_of_ident i), Univ.Lt, GType (Libnames.qualid_of_ident j)]; Proofview.tclUNIT()
}
END
~~~
In the .v:
~~~coq
Universes i j.

Lemma foo@{} : Type@{j}.
Proof.
  magic i j; transparent_abstract exact_no_check Type@{i}.
Defined.

Definition bar : Type@{i} := Type@{j}.
~~~
Note that using `Constraint i < j.` instead of `magic`  doesn't cause the issue because it gets replayed.

**Comment by ppedrot** [comment]
Wasn't there already a bug opened about this kind of problem?

**Comment by SkySkimmer** [comment]
One way to fix may be to put a marker that universes were changed in the revstruct, eg e9adac17c00fb69a8c9aca2f2e041955221cb206
It feels somewhat wrong somehow though, needs more though.

**Comment by ppedrot** [comment]
The important bit is to be fast when no retypechecking is needed. I conducted experiments some time ago, and the number of monomorphic universes stored in the safe environment is actually quite small. We could simply store the diff in the side effect certificate and check for structural equality with the safe environment, in addition to physical equality with the revstruct.
