### ISSUE TITLE
Universe inconsistency when defined inside a section

### ISSUE THREAD

**Issue by davidnowak** [coq/coq#11594]
The following definition of `b` is accepted by Coq 8.9.1, but rejected by Coq 8.11:

```
Section S.

Variable X : Type.

Inductive A : Type :=
| a : X -> A.

End S.

Definition b (Y : Set) : Set := A Y.
```

The error message is:
```
In environment
Y : Set
The term "A Y" has type "Type" while it is expected to have type "Set" (universe inconsistency).
```
On the other hand, the following definition (without a Section) is accepted by both versions of Coq:

```
Inductive A (X : Type) : Type :=
| a : X -> A X.

Definition b (Y : Set) : Set := A Y.
```

**Comment by ppedrot** [comment]
Indeed, this is a deliberate limitation to template polymorphic inductive types inside a section to work around a deeply rooted soundness bug. I am afraid this is here to stay. You should use cumulative inductive types instead if you really want this to work in a section, or drop the section altogether.

**Comment by davidnowak** [comment]
@ppedrot Is it documented somewhere? Does it only affect Inductive?
I am asking because I have other cases of universe inconsistencies that might also be due to definitions inside a section.

**Comment by ppedrot** [comment]
Have a look at the [8.10 changes](https://coq.inria.fr/distrib/current/refman/changes.html#changes-in-8-10-beta3). For cumulativity to work, you also need your variable to be polymorphic, so you'd better set the universe polymorphism flag before entering the section.

**Comment by ppedrot** [comment]
Anyways, closing this as INVALID.
