### ISSUE TITLE
Parsing and displaying floating-point numbers up to approximation

### ISSUE THREAD

**Issue by herbelin** [coq/coq#11611]
I wonder whether this is moral or not that the following proof fails:
```
Require Import Floats.
Open Scope float_scope.
Goal 0.1 + 0.2 = 0.3.
Fail reflexivity.
```
and, conversely, that the following succeeds:
```
Require Import Floats.
Open Scope float_scope.
Goal 0.3 = 0.29999999999999997.
reflexivity.
Qed.
```

The documentation for [floats](https://coq.inria.fr/refman/language/coq-library.html?highlight=float#floats-library) says that `parse` of `print` is the identity thanks to the printer ensuring at least 17 digits and thus determining a unique float from its decimal approximation. Nothing is said about `print` of `parse` though.

The initial proposal about floats at #8276 was otherwise raising the question:

> Pretty-printing and parsing of floating-point values raises interesting questions. An easy solution would be to parse/print floats in hexadecimal format (e.g., `0xcp-3`) but this is ugly and perfectly unreadable for humans. A decimal format (e.g., `1.5`) would be more readable.
> It is known that using 17 digits while printing binary64 guarantees `parse \circ print : float -> float` to be the identity although `parse` is of course not injective.

Indeed, when reasoning with floating-point numbers, I guess that we quickly get familiar with having all numbers in the range [0.2999999999999997;0.30000000000000001] being bound to the same canonical representation 0.299999999999999988897769753748434595763683319091796875, so, the current approach is probably a good compromise for experts wanting to reason about floating-point numbers.

On the other side, I wonder if something more could be done for the non-specialist users who may be surprised by the discrepancy between what they type and what they see, and what is actually hidden behind the scene?

For instance, would it make sense that by default the parser warns about what exactly happens every time a float is parsed, indicating the full 54-digit denotation it shall be using internally and telling that for conciseness the printer will non-ambiguously write only the canonical first 17 digits of this denotation? Then an option would allow to deactivate this warning.

As a side remark, would it be better or on the contrary more confusing that `0.3` is displayed `0.3` rather than `0.2999999999999997`, since, after all, any member of the range is in principle good enough as a representative of the range and, if the purpose is conciseness, the printer could choose the shorter decimal representation?

Cc @erikmd, @proux01

**Comment by proux01** [comment]
Thanks for raising this point!

> I wonder whether this is moral or not [...]

I would say yes, considering that the real numbers `0.1`, `0.2` and `0.3` are not (binary64) floating-point numbers. I agree the behavior can be somewhat disturbing though. This is however a widespread phenomena among all programming languages offering floating-point computations.

> For instance, would it make sense that by default the parser warns about what exactly happens every time a float is parsed, indicating the full 54-digit denotation it shall be using internally and telling that for conciseness the printer will non-ambiguously write only the canonical first 17 digits of this denotation? Then an option would allow to deactivate this warning.

Sounds a good idea. We should definitely do that. To avoid too many warnings, we could also triger it only when the parsing is not "exact", for instance parsing `42` or `0.25` does not require a warning.

> As a side remark, would it be better or on the contrary more confusing that `0.3` is displayed `0.3` rather than `0.2999999999999997`, since, after all, any member of the range is in principle good enough as a representative of the range and, if the purpose is conciseness, the printer could choose the shorter decimal representation?

`0.3` looks definitely nicer but I feel `0.29999999...` better conveys the idea of approximative value. Maybe @silene would have a stronger opinion?
