### ISSUE TITLE
primitive/uint63/* tests fail on 32bit architectures

### ISSUE THREAD

**Issue by treinen** [coq/coq#11624]
The test suite fails on primitive/uint63/* on 32-bit architectures , see https://gitlab.com/coq/coq/-/jobs/436836250.
I have observed the same on an i386 porterbox, using ocaml 4.08.1. @ejgallego says it
looks like a bug, so here we go ..

#### Coq Version

8.11.0

**Comment by treinen** [comment]
For the record: I got the same test failures, plus a few additional  ones, on the debian armel architecture. This is a 32bit ARM architecture, bytecode-only.

**Comment by ejgallego** [comment]
Note this also fails generally on our CI if we use OCaml >= 4.08
