### ISSUE TITLE
coqchk regression: "Fatal Error: User error: Inconsistent assumptions over module Coq.Init.Byte ."

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#11628]
#### Description of the problem

Yesterday, coqchk started failing on our CI. The [commit where it started](https://gitlab.mpi-sws.org/iris/iris/commit/1a5d7d58f8f592ab565aac91ad6bd1f5a4eeacf0) touches only docs, so this is most likely caused by a coqchk regression. You can see a [failing log here](https://gitlab.mpi-sws.org/iris/iris/-/jobs/56681).

#### Coq Version

Last version that worked:
```
name        coq
version     dev
source-hash fdcfe8b7
The Coq Proof Assistant, version 8.12+alpha (February 2020)
compiled on Feb 18 2020 8:27:53 with OCaml 4.07.1
```
First version that broke:
```
name        coq
version     dev
source-hash 43c3c7d6
The Coq Proof Assistant, version 8.12+alpha (February 2020)
compiled on Feb 18 2020 21:14:55 with OCaml 4.07.1
```

That corresponds to [this commit range](https://github.com/coq/coq/compare/fdcfe8b7...43c3c7d6).

**Comment by SkySkimmer** [comment]
We `make validate` in our CI job for Iris so this is quite strange.

**Comment by SkySkimmer** [comment]
>That corresponds to this commit range.

So #10204 #11529 #11530 
I don't see how the other 2 could get this result so cc @ejgallego for #11529

**Comment by RalfJung** [comment]
Indeed something is strange, this does not reproduce locally.

Maybe there is a problem with upgrading an existing Coq install in-place?

**Comment by RalfJung** [comment]
Or maybe it is related to https://github.com/ocaml/opam/issues/4091

**Comment by ejgallego** [comment]
> Maybe there is a problem with upgrading an existing Coq install in-place?

If you are not doing `make clean` then indeed bad things can happen. Proper incremental builds using make are not supported if the set of target files changes [they will be once we have Dune, but only between commits after the bootstrap]

**Comment by RalfJung** [comment]
We are using `opam`, so we shouldn't have to manually clean anything.

**Comment by rjbou** [comment]
Some explanation in this https://github.com/ocaml/opam/issues/4091#issuecomment-588425357

**Comment by RalfJung** [comment]
@rjbou thanks!
So, could this lead to opam not removing old files when uninstalling/upgraing coq?

**Comment by RalfJung** [comment]
Yeah looks like clearing the opam state made this issue go away. Sorry for the noise!
