### ISSUE TITLE
Logic in def_body in g_vernac.mlg is out of place.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#11659]
The `vernac_expr` AST should reflect exactly what is parsed and `mlg` files should be limited to parsing. Here, we have a case of out of place early translation:

https://github.com/coq/coq/blob/7ef010c50c9d8efcd20d44807126efcd418c4e0d/vernac/g_vernac.mlg#L351-L372

~~This is detrimental to properly implementing some syntax restrictions following @ejgallego's [suggestion](https://github.com/coq/coq/pull/11646#issuecomment-589740074).~~ EDIT1: In this case, the transformation is actually fine for this particular check because the `CLocalPattern` binders will anyway be disallowed and thus what this transformation does is to render indistinguishable `Definition foo : nat := 0.` and `Definition foo := 0 : nat.` (not a big deal). EDIT2: But this transformation may actually lead to incorrect error messages (say "type must be provided" when the issue is actually "pattern binder is not supported").

**Comment by herbelin** [comment]
There are two post-parsing treatments here: one to bypass the not yet supported `CLocalPattern`, and one to reinterpret `c : t` in the syntax of terms as if it were `... : t := c`. Are you questioning both?

> EDIT1: In this case, the transformation is actually fine for this particular check because the `CLocalPattern` binders will anyway be disallowed and thus what this transformation does is to render indistinguishable `Definition foo : nat := 0.` and `Definition foo := 0 : nat.` (not a big deal). 

This is the `CLocalPattern` issue (see #11658, which indeed is not supported at the moment), and, for that purpose uses a (sometimes incorrect) hack of manually building a `fun bl => c : t` (incorrect when `Eval` is provided).

> EDIT2: But this transformation may actually lead to incorrect error messages (say "type must be provided" when the issue is actually "pattern binder is not supported").

This transformation is debatable. Eventually, it leads to the question of, for `Definition d := c : t.`, whether `Print d` should show:
```
d = c : t
      : t
```
or simply:
```
d = c
      : t
```
i.e. whether the cast is kept in the body stored in the kernel or if the cast is seen as a type.

In case you think it helps and clarifies, you can make a PR out of this [branch](https://github.com/herbelin/github-coq/pull/new/master+helping11659-moving-pattern-in-binder-hack-out-of-g_vernac). It moves the `CLocalPattern` hack to `comDefinition.ml` and leaves  in `g_vernac.mlg` only the `CastConv` hack.

**Comment by Zimmi48** [comment]
Thanks!
