### ISSUE TITLE
significant slowdown with ocaml 4.08.1

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#11652]
#### Description of the problem

I just noticed a [significant build time regression](https://coq-speed.mpi-sws.org/d/1QE_dqjiz/coq-compare?orgId=1&var-project=iris&var-branch1=master&var-commit1=7ddea37a842878fa5a9eb53130e0f867aced2655&var-config1=build-coq.8.11.0&var-branch2=master&var-commit2=4815e68e8bad53eb3fb832d39c282ea8ac36a676&var-config2=build-coq.8.11.0&var-group=(.*)%2F%5B%5E%2F%5D*&var-metric=instructions) in Iris even though these commits did not actually change the Coq code at all. But what did change around that time is the OCaml version that we are using on CI: we used to use 4.07.1, but I recently bumped that to 4.08.1 (to match Debian testing).

That resulted in an almost 14% slowdown for the full Iris build time. As you can see, every single file got slower, some by almost 30%.

Cc @robbertkrebbers 

#### Coq Version

8.11.0

**Comment by ejgallego** [comment]
Data is extremely worry, see https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/861/console

There are a few candidates in the changelog that could be causing this; I'll report upstream.

**Comment by ppedrot** [comment]
I have found a line that is reliably slow in the various benches, that's the call to `Export FinCDistrLattice.Exports.` from `ssreflect/order.v` in mathcomp. I'll investigate a bit more with perf.

**Comment by ppedrot** [comment]
IIUC the upstream bug has been fixed so this can be closed.

**Comment by ejgallego** [comment]
> IIUC the upstream bug has been fixed so this can be closed.

Not sure the 4.08 branch released the fix, so maybe some documentation is needed.

**Comment by Blaisorblade** [comment]
Yes, at least to understand which versions are affected today. It seems 4.11.2 was the first version releasing the fix upstream, but haven’t checked Opam backports yet. The fix was backported to all maintenance branches (as visible in https://github.com/ocaml/ocaml/pull/10125 at the end), but for 4.08-4.10 it shows up among “unreleased” commits:
https://github.com/ocaml/ocaml/compare/4.08.1...4.08
https://github.com/ocaml/ocaml/compare/4.09.1...4.09
https://github.com/ocaml/ocaml/compare/4.10.2...4.10

For later releases, it’s not visible:
https://github.com/ocaml/ocaml/compare/4.11.2...4.11
https://github.com/ocaml/ocaml/compare/4.12.1...4.12

**Comment by ejgallego** [comment]
Thanks for getting this information @Blaisorblade , so indeed people on a particular version can pin to the branch a get the fix.

Would be great if we could document this, I'd volunteer but got no free cycles now :(

**Comment by Blaisorblade** [comment]
This is worth delegating... haven't had time, but I realized that on ARM the Coq platform defaults to the "vanilla" 4.10.2: https://github.com/ocaml/opam-repository/blob/master/packages/ocaml-variants/ocaml-variants.4.10.2+flambda/opam. Now I know why 4.12.1 seemed so much faster!

**Comment by Zimmi48** [comment]
cc @MSoegtropIMC: updating to 4.11.2 or 4.12.1 (or to the tip of the 4.10 branch) might be worth for speeding up the Coq Platform.

**Comment by MSoegtropIMC** [comment]
Indeed I think restrictions which forced me to 4.10.2 might be gone meanwhile. I set a note.
