### ISSUE TITLE
Why is Inductive foo := Bar |. accepted?

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#11654]
#### Description of the problem

The following syntax is accepted.

```coq
Inductive foo := Bar |.
```

But as soon as there are two constructors or more, the trailing pipe is no longer supported. The trailing pipe is also not supported when there is a leading pipe.

Is this a mistake? Can we remove the syntax? Can we switch a deprecation phase considering that this is a bug?

Discovered by @jfehrle thanks to his grammar documentation effort.

#### Coq Version

8.5-8.11

**Comment by herbelin** [comment]
Apparently introduced in 9fe895d340a. I suspect that this is a mistake.

> Can we switch a deprecation phase considering that this is a bug?

Do you mean "skip"? Unless this is used inadvertently a lot, I believe this can be fixed without notice.

**Comment by Zimmi48** [comment]
Yes, I meant skip :)
