### ISSUE TITLE
Any attribute is accepted on query commands.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#11661]
#### Description of the problem

These commands are accepted:

```coq
Polymorphic About nat.
#[ universes(polymorphic) ] Check nat.
#[ deprecated(note="") ] Print nat.
#[ canonical ] Compute nat.
```

They probably should raise the `unsupported-attributes` fatal warning instead.

#### Coq Version

Since 8.10.

In 8.9, `#[ polymorphic ] Check nat.` raised `This command does not support Polymorphism`.

**Comment by maximedenes** [comment]
So is this a regression? If so, what introduced it?

**Comment by ejgallego** [comment]
> If so, what introduced it?

Given the timeframe likely the new attribute system, see #13027 for the fix.
