### ISSUE TITLE
Section names and file names conflicting

### ISSUE THREAD

**Issue by vmurali** [coq/coq#11678]
#### Description of the problem

I have two files and one directory in the top level directory TOP:
Foo/T.v: empty file T.v in directory TOP/Foo.
Foo.v: It has the following contents in directory TOP
```
Require Import Foo.T.

Section T.
End T.
```

I compile it using the following commands:
coqc -Q . Sth Foo/T.v
coqc -Q . Sth Foo.v

I get an error:
File "./Foo.v", line 3, characters 0-10:
Error: T already exists.

#### Coq Version
8.11

**Comment by herbelin** [comment]
This is expected. Coq names combine (so-called) logical names bound with `-Q` to directories, with subdirectories segments as well as with file names, as well as module/section names to form fully-qualified names which have to be distinct.

The directory `.` is bound to `Sth`. So file `T` in subdirectory `Foo` has logical name `Sth.Foo.T`. The second file `Foo.v` is in current directory, so its logical name is `Foo` and a module or section named `T` in it has fully-qualified name `Foo.T` too. This is not possible.

Sorry for the late answer. I'm closing, but don't hesitate to ask further questions if needed.
