### ISSUE TITLE
ssreflect "rewrite .. in .." in "match goal" grabs section variable instead of the bound hypothesis

### ISSUE THREAD

**Issue by Armael** [coq/coq#11670]
Coq version: tested with 8.9.1 and 8.11

```coq
Section S.
  Context `{H: True}.
  Goal forall n, n + 0 = 0 + n -> n + 0 = n -> True.
    intros n H1 H2.
    match goal with H : context [ ?n + 0 = ?n ] |- _ => rewrite H1 in H end.
```
fails with: `Error: Can't clear section hypothesis H`

It seems ssreflect's `rewrite` resolves `in H` by using the section hypothesis named `H`, instead of the name bound by the pattern (which would resolve to `H2`) in that case.

**Comment by Blaisorblade** [comment]
Like #10928 and #6687, this affects name resolution in ssreflect tactics. Potential duplicate?

**Comment by Armael** [comment]
Ahh, I just checked with coq/master, and the issue has been fixed there. So it was probably a duplicate of #10928 indeed. Thanks for the information!

**Comment by Blaisorblade** [comment]
Uh, #10928 isn't fixed (just a duplicate), but cool anyway! :-)
