### ISSUE TITLE
"The following expression should have type unit." has no following expression

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11683]
#### Description of the problem

This error message is a bit confusing
```coq
Require Import Ltac2.Init.
Require Ltac2.Ltac1.

Ltac foo tac := ltac2:(tac1 |- fun () => Ltac1.run tac1).
(* Warning: The following expression should have type unit. [not-unit,ltac] *)
```

#### Coq Version

master 92a294ca53752b61b0270a719826ffc759a25e8d

**Comment by ppedrot** [comment]
The expression is highlighted in CoqIDE though.

**Comment by maximedenes** [comment]
Maybe "following" is confusing? Why not "This expression"?

**Comment by JasonGross** [comment]
In CoqIDE, yes.  On the command line, no.  In coqtop, the expression fines before.  And in PG, the cursor is moved to the beginning of the expression, but it is not highlighted.

**Comment by ppedrot** [comment]
FTR after #14027 we also get the type of the expression. I am a bit reluctant to print the whole expression since it won't be very informative in general. I'd recommend closing this bug since #14027 makes it easier to understand what is going on. The fact we have deficient UIs should not be circumvented by making the base program overly verbose.

**Comment by SkySkimmer** [comment]
>In CoqIDE, yes. On the command line, no. In coqtop, the expression fines before. And in PG, the cursor is moved to the beginning of the expression, but it is not highlighted.

Sounds like the real issue is https://github.com/ProofGeneral/PG/issues/548 then.

**Comment by Zimmi48** [comment]
I second Maxime's recommendation of changing "the following" by "this" before closing this issue.

**Comment by ppedrot** [comment]
@Zimmi48 your desires are orders: #14133.
