### ISSUE TITLE
Documentation of Hint Immediate is misleading

### ISSUE THREAD

**Issue by mikeshulman** [coq/coq#11697]
#### Description of the problem

The Coq reference manual entry for [Hint Immediate](https://coq.inria.fr/refman/proof-engine/tactics.html#coq:cmdv.hint-immediate) says

> This command adds `simple apply term; trivial` to the hint list associated with the head symbol of the type of `ident` in the given database. This tactic will fail if all the subgoals generated by `simple apply term` are not solved immediately by the `trivial` tactic...  The cost of this tactic (which never generates subgoals) is always 1...

This is misleading, because `simple apply term; trivial` _can_ generate subgoals; according to its documentation, the tactic `trivial` "either solves completely the goal or else succeeds without changing the goal".  In particular, `Hint Immediate term` is _not_ equivalent to

```coq
Hint Extern 1 <pat> => simple apply term; trivial
```

since the latter can leave subgoals, and hence typeclass inference can continue.  It seems that a closer equivalent would be

```coq
Hint Extern 1 <pat> => simple apply term; solve [ trivial ]
```

but I can't be sure since I don't know exactly how `Hint Immediate` is implemented; nothing like `solve` shows up in `Print HintDb` for a `Hint Immediate`, but nevertheless typeclass inference doesn't proceed across one if `trivial` doesn't solve all the goals.

(Also, more trivially, I think "the type of `ident`" in the documentation should be "the type of `term`"; `ident` is the hint database.)

#### Coq Version

8.10/master

**Comment by mikeshulman** [comment]
Apparently `Hint Immediate` is not equivalent to `Hint Extern 1 <pat> => simple apply term; solve [ trivial ]` either; see HoTT/HoTT#1279 (I don't have a MWE unfortunately).  So maybe the basic question is: is there any `Hint Extern` that's equivalent to `Hint Immediate`, and if so what is it?

**Comment by Zimmi48** [comment]
All the documentation that tells you what `Hint Resolve` or variants are equivalent to is lying because in practice, the unification flags used by `auto` / `eauto` / `typeclasses eauto` are slightly different from those of `simple apply` / `simple eapply` (and possibly different between themselves). We hope to solve this by making these tactics user-configurable. In the meantime, feel free to improve the documentation in any way that you feel would make it better. In particular, you are right that the closest equivalent of `Hint Immediate` is `simple apply term; solve [ trivial ]`.

**Comment by mikeshulman** [comment]
Can you say anything about how `Hint Immediate` differs from `simple apply term; solve [ trivial ]`?  In particular, in what cases can it leave over subgoals to be solved by further hints?

**Comment by Zimmi48** [comment]
> Can you say anything about how `Hint Immediate` differs from `simple apply term; solve [ trivial ]`? In particular, in what cases can it leave over subgoals to be solved by further hints?

I am not aware that it can leave subgoals to be solved by further hints. My comment was only related to the fact that the `simple apply` part of the description is an approximation because it may not be using exactly the same unification flags.
