### ISSUE TITLE
Link from the manual to the standard library documentation is dead 

### ISSUE THREAD

**Issue by let-def** [coq/coq#11696]
This is a very minor problem, but the link to the standard library in https://coq.inria.fr/refman/language/coq-library.html#survey targets https://coq.inria.fr/stdlib which fails.
The correct link seems to be https://coq.inria.fr/stdlib/.

The final slash matters. Either the manual or the web server configuration should be updated :).

**Comment by Zimmi48** [comment]
>Either the manual or the web server configuration should be updated :)

Both in fact, but the first one is something that I know how to do, while the second one is something I would need help with (cf. https://github.com/coq/www/issues/111#issuecomment-547004652).
