### ISSUE TITLE
feature request: Set Automatic Bidi Constructors

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11702]
#### Description of the problem
It seems useful to have a flag `Set Automatic Bidi Constructors` or similar that would make it so that all inductives declared while this flag is set have automatic bidi declarations for all of their constructors, which place the `&` (bidi location) between the last (uniform?) inductive parameter and the first constructor argument.

#### Coq Version

8.12

**Comment by aspiwack** [comment]
May I enquire if there is any particular reason for using `Bidi` rather than a full word?

**Comment by ppedrot** [comment]
@aspiwack Because it reminds the user of the vast alpine wilderness?
<img src="https://www.filmspourenfants.net/wp-content/uploads/2018/04/heidi-a-353x500.jpg" width="200">

(I am out.)

**Comment by JasonGross** [comment]
Bidi is fewer characters, but I wouldn't object at all to using bidirectional instead.

**Comment by aspiwack** [comment]
> Because it reminds the user of the vast alpine wilderness?

Well played, sir.

> Bidi is fewer characters, but I wouldn't object at all to using bidirectional instead.

I'd rather. Shorthands are pretty obscure, in my opinion.

**Comment by JasonGross** [comment]
Duplicate of #11066
