### ISSUE TITLE
ocamlfind: Package `coq.top_printers` not found

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#11716]
Dune newbie here, sorry if I'm doing something obviously wrong.

On a clean Coq master checkout, with OCaml 4.09.0, I do:
```coq
make -f Makefile.dune voboot
dune exec -- dev/dune-dbg coqtop
```

Ocamldebug loads, but I get `ocamlfind: Package coq.top_printers not found`.

What is more surprising to me is that running `make -f Makefile.dune quickbyte` does not fix the issue.

Is this expected?

**Comment by maximedenes** [comment]
Cc @coq/build-maintainers

**Comment by SkySkimmer** [comment]
This is a known issue (not sure if there is a formal issue), you need to make world for a few seconds so that it installs something (not sure what exactly). You don't need to do it again after changing code IIRC.

**Comment by maximedenes** [comment]
Indeed, it works. Let's keep this open to track the problem. Thanks!

**Comment by ejgallego** [comment]
Indeed, see the comment in the file; there are a few possible workarounds:
- strengthen the deps so the META file is available [slow and cumbresome]
- improve the generation so we print the actual path needed for ocamldebug, that seems like the best fix, now that Dune has variable artifacts that's easy to do IMO.
- add ocamldebug support to Dune [fairly easy, hopefully somebody has some spare cycles]

**Comment by maximedenes** [comment]
> see the comment in the file

What comment in which file?

**Comment by maximedenes** [comment]
I guess you mean this:
```
Unfortunately, dependency handling here is not fully refined, so you
need to build enough of Coq once to use this target [it will then
correctly compute the deps and rebuild if you call the script again]
```

TBH, I had read it but it was not informative enough for me to make sense of it (in particular, it does not mention what dependency is missing, what should be build manually instead).

**Comment by ejgallego** [comment]
In `dev/dune`, adding a dep on `../META.coq` does seem to solve the issues these days.

**Comment by ejgallego** [comment]
Ahh it is more subtle than that, I remember now...

Also, something is going on, as this used to work fine after make world.
