### ISSUE TITLE
Strange grammar for @argument_spec_block in Arguments command

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#11712]
{* @argument_spec_block } accepts strings such as "& & &".  This doesn't seem right.  Perhaps worth cleaning up.

![image](https://user-images.githubusercontent.com/1253341/75577713-6eed1400-5a17-11ea-96fe-d9ae0cdfb0cf.png)

**Comment by jfehrle** [comment]
@Zimmi48's comment (via email):

Indeed, it seems that it should rather have been {* argument_spec_block } {? & {* argument_spec_block } }.
When testing "Arguments id & &." gives "The "&" modifier may only occur once."
I have no idea why this was not enforced in the syntax directly but it is probably worth trying.

**Comment by Zimmi48** [comment]
The issue though is the same with `/` which can also occur just once. I don't think we can have the parser ensure that both can occur only once but in any order without it becoming much more complex (anticipating all the possible orderings) so I think it will stay like this and we will just have to document these restrictions (and the corresponding error messages "The "/" modifier may only occur once." and "The "&" modifier may only occur once.")

**Comment by jfehrle** [comment]
OK, probably best left as-is.  I'll add the messages to the doc.
