### ISSUE TITLE
`dune exec coqtop` triggers `Error: Dynlink error: interface mismatch`

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#11726]
Again, I hope I'm not doing something too obviously wrong, here are the repro steps on a fresh checkout of master, with OCaml 4.07.1 and Dune 2.1.2 (I observed similar behavior with OCaml 4.09.0 and Dune 2.3.1):

1. run `make -f Makefile.dune world` which succeeds
1. `dune exec coqtop` to check it runs fine too
1. I edit an interface. For example I replaced `type structured_values` with `type structured_values = values` in `vmvalues.mli`
1. `dune exec coqtop` builds some files, then launches Coq which fails with `Error: Dynlink error: interface mismatch on Vmvalues`

**Comment by maximedenes** [comment]
Cc @coq/build-maintainers

**Comment by ejgallego** [comment]
I think this is expected and [almost documented], does `dune exec -- coqtop -noinit` work in your case?

`coqtop` doesn't depend by itself on the plugins loaded by the stdlib, so the shim must be used if you are intending the libraries to be rebuilt correctly [the joy of plugins :)]

**Comment by maximedenes** [comment]
> I think this is expected and [almost documented], does `dune exec -- coqtop -noinit` work in your case?

Ah yes, it does.

I think the clarification of the documentation you submitted would indeed have helped me figuring out what to do.

**Comment by ejgallego** [comment]
> I think the clarification of the documentation you submitted would indeed have helped me figuring out what to do.

Indeed, this stuff is not well documented, the same happens in the Makefile system, you need to build states before running coqtop [in dune you can do that too]

The medium-term solution is to actually have a `dune coqtop` / `coqc` command à la `dune utop`, so  the command will actually put in scope / build whatever libraries are in scope for the current library context.
