### ISSUE TITLE
micromega should be ported to `Coqlib.lib_ref`

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#11739]
Like a few other plugins, micromega is using a deprecated `Coqlib` API. See for example: 

https://github.com/coq/coq/blob/18aa9ca60ec9b3d1712276ec0c615dfe54c1a251/plugins/micromega/coq_micromega.ml#L218-L223

Current work on stdlib2 requires it to be ported to `Coqlib.lib_ref`.

Could we get some help from @coq/micromega-maintainers on this issue?

**Comment by maximedenes** [comment]
@vbgl do you have any unpublished branch that addresses this, by any chance?

**Comment by vbgl** [comment]
No, sorry. I haven’t addressed this long-standing issue yet.

**Comment by maximedenes** [comment]
@coq/micromega-maintainers any chance I can get some help on this? This is going to be a blocker for stdlib2 fairly soon, I'm afraid.

**Comment by fajb** [comment]
I can look at it -- end of this week maybe.
Does it mean declaring the refs in Coq ?
Register bla as X
and using Coqlib.lib_ref "X" in the ml code ?

**Comment by maximedenes** [comment]
Yes, exactly. Note that some of these `Register` commands are already in place.

**Comment by fajb** [comment]
If the CI agrees to start, PR #11990 shoudl do the trick.

**Comment by olaure01** [comment]
I am not familiar with API. I have the following problem with `Nat.le` and `lia`:
```coq
Require Import PeanoNat Lia.

Goal forall x y z, le x y -> le y z -> le x z.
Proof.
intros; lia.
Qed.

Goal forall x y z, Nat.le x y -> Nat.le y z -> Nat.le x z.
Proof.
intros x y z.
Fail lia.
unfold Nat.le; lia.
Qed.
```
Is it related or should I open a new issue?

**Comment by fajb** [comment]
Hi @olaure01 , you can report a new issue.
 
PS: ping @fajb in the issue.
