### ISSUE TITLE
funind should be ported to `Coqlib.lib_ref`

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#11738]
Like a few other plugins, funind is using a deprecated `Coqlib` API. See for example: 

- https://github.com/coq/coq/blob/18aa9ca60ec9b3d1712276ec0c615dfe54c1a251/plugins/funind/indfun_common.ml#L96
- https://github.com/coq/coq/blob/18aa9ca60ec9b3d1712276ec0c615dfe54c1a251/plugins/funind/indfun_common.ml#L455

Current work on stdlib2 requires it to be ported to `Coqlib.lib_ref`.

Could we get some help from @coq/funind-maintainers on this issue?

**Comment by Matafou** [comment]
I should be able to help, what is the recommended API to refer to stdlib
constants?


Le mar. 3 mars 2020 à 11:07, Maxime Dénès <notifications@github.com> a
écrit :

**Comment by maximedenes** [comment]
The recommended approach is in two steps:
- In `.v` files, you use a `Register c as "foo.bar.c"` command.
- In `.ml` files you refer to that constant by `Coqlib.lib_ref "foo.bar.c"`

The codebase has already been partially ported, so you can grep `lib_ref` to find some examples.

**Comment by Matafou** [comment]
I see. Is there an easy mean to know the internal name of a constant? For instance

```Coqlib.lib_ref "Coq.Arith.Wf_nat.well_founded_ltof"```

does not seem to be found.

**Comment by maximedenes** [comment]
@Matafou the name that you need to pass to `lib_ref` is the one you used for `Register`.
