### ISSUE TITLE
Build of `doc-stdlib` produces dozens of warnings

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#11749]
These warnings say `Warning: foo will be hidden from the index`

My guess is that this should not be a warning, but I'm not sure. If that's the case, we should stop emitting them. Otherwise, they should be addressed.

@coq/doc-maintainers

**Comment by Zimmi48** [comment]
I agree. The infrastructure requires an explicit list of hidden files, so there is no reason to warn when building.
