### ISSUE TITLE
[CI] Failure in building stdlib doc should not prevent base build

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#11748]
The build of the `doc-stdlib` target is known to be fragile. For example, adding or removing a file without reflecting it in the explicit listing of files (in `index-list.html.template` or `doc/stdlib/hidden-files`) will make the build fail.

It would be much better if this scenario was not triggering a failure of the base build, which currently prevents all tests from running, whereas the real error is relevant only for the documentation.

Cc @coq/ci-maintainers @coq/doc-maintainers

**Comment by Zimmi48** [comment]
I'm surprised to read this. I don't know why the base build breaks. I assume this will be fixed by Dune though.

cc @coq/legacy-build-maintainers

**Comment by maximedenes** [comment]
> I'm surprised to read this. I don't know why the base build breaks

This is a CI issue. The `build:base` job builds the `doc-stdlib` target, which fails in the scenario above.

@coq/ci-maintainers could we move the build of this target to another job?

**Comment by SkySkimmer** [comment]
IIRC I had trouble building the stdlib doc using the installed artifact.
We could just rely on `doc:stdlib:dune` (which doesn't build the pdf) at risk of silently breaking the make target I guess.

**Comment by Zimmi48** [comment]
Can we delay this until we ditch the legacy build system?

**Comment by gares** [comment]
Was the roadmap for dune finally discussed?
