### ISSUE TITLE
Undocumented tactics

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#11743]
None of these tactics are documented.  Are any of them candidates for removal (less to write up)?
(Not planning to add doc for these right now.)

```
autounfold_one {? @hintbases } {? in @ident }
casetype @term1_extended
constr_eq_nounivs @term1_extended @term1_extended
debug eauto {? @int_or_var } {? @int_or_var } {? @auto_using } {? @hintbases }
dependent generalize_eqs @ident
dependent generalize_eqs_vars @ident
dependent {| simple inversion | inversion | inversion_clear } {| @ident | @num } {? @as_or_and_ipat } {? with @term1_extended }
destauto {? in @ident }
dfs eauto {? @int_or_var } {? @auto_using } {? @hintbases }
field_lookup @ltac_expr [ {* @term1_extended } ] {+ @term1_extended }
generalize_eqs @ident
generalize_eqs_vars @ident
gintuition {? @ltac_expr }
head_of_constr @ident @term1_extended
hget_evar @int_or_var
hresolve_core ( @ident := @term1_extended ) {? at @int_or_var } in @term1_extended
info_eauto {? @int_or_var } {? @int_or_var } {? @auto_using } {? @hintbases }
info_trivial {? @auto_using } {? @hintbases }
is_cofix @term1_extended
is_const @term1_extended
is_constructor @term1_extended
is_fix @term1_extended
is_ground @term1_extended
is_ind @term1_extended
is_proj @term1_extended
lra_Q @ltac_expr
lra_R @ltac_expr
new auto {? @int_or_var } {? @auto_using } {? @hintbases }
not_evar @term1_extended
nsatz_compute @term1_extended
progress_evars @ltac_expr
prolog [ {* @term1_extended } ] @int_or_var
protect_fv @string {? in @ident }
psatz_Q {? @int_or_var } @ltac_expr
psatz_R {? @int_or_var } @ltac_expr
psatz_Z {? @int_or_var } @ltac_expr
rewrite_db @ident {? in @ident }
ring_lookup @ltac_expr0 [ {* @term1_extended } ] {+ @term1_extended }
setoid_etransitivity
simple eapply {+, @constr_with_bindings_arg } {? @in_hyp_as }
simple injection {? @destruction_arg }
simple notypeclasses refine @term1_extended
simple subst
soft functional induction {+ @term1_extended } {? @fun_ind_using } {? @with_names }
sos_Q @ltac_expr
sos_R @ltac_expr
sos_Z @ltac_expr
specialize_eqs @ident
substitute {? {| -> | <- } } @constr_with_bindings
xlia @ltac_expr
xnlia @ltac_expr
xnqa @ltac_expr
xnra @ltac_expr
zify_iter_let @ltac_expr
zify_iter_specs @ltac_expr
zify_op
zify_saturate
```

**Comment by Zimmi48** [comment]
There was already an issue about undocumented tactics (#3225).

To still answer (partially) your question:

- `debug eauto`, `info_eauto`, `info_trivial` are already documented but simply missing from the index (cf. https://coq.github.io/doc/master/refman/proof-engine/tactics.html#automation);

- `dfs eauto` is eventually going away but maybe not that soon;

- `new auto` should probably have been deprecated for a long time;

- `prolog` is deprecated as of today;

- `is_cofix`, `is_const`, `is_constructor`, `is_fix`, `is_ground`, `is_ind`, `is_proj` should probably be documented in the Ltac1 chapter (as they can be replaced by more native stuff in Ltac2);

- the `simple` tactics should be documented;

- the `zify_` tactics should be documented as internal.

**Comment by samuelgruetter** [comment]
`rewrite_db` is [listed](https://coq.inria.fr/refman/proofs/writing-proofs/equality.html#coq:tacn.rewrite_db) in the manual, but there's no text explaining what it does. Is it just an alias for `autorewrite`?

**Comment by jfehrle** [comment]
It appears more related to `rewrite_strat`.  `db` looks like the name of a hint database:

```
let db_strat db = StratUnary (Topdown, StratHints (false, db))
let cl_rewrite_clause_db ist db = cl_rewrite_clause_strat (strategy_of_ast ist (db_strat db))

TACTIC EXTEND rewrite_strat
| [ "rewrite_strat" rewstrategy(s) "in" hyp(id) ] -> { cl_rewrite_clause_strat s (Some id) }
| [ "rewrite_strat" rewstrategy(s) ] -> { cl_rewrite_clause_strat s None }
| [ "rewrite_db" preident(db) "in" hyp(id) ] -> { cl_rewrite_clause_db ist db (Some id) }
| [ "rewrite_db" preident(db) ] -> { cl_rewrite_clause_db ist db None }
END
```

**Comment by samuelgruetter** [comment]
Aah thanks for the code quote, so I guess 
```
rewrite_db db_name in H
``` 
is just a shorthand for
```
rewrite_strat (topdown (hints db_name)) in H
```

**Comment by Zimmi48** [comment]
All the tactics are now listed in the refman (IIRC) but some are still marked as undocumented. Feel free to contribute some documentation text (and possibly examples) if you have figured out what they do.

**Comment by jfehrle** [comment]
I added `rewrite_db` in #15546.  But as @Zimmi48 suggests, contributions are very welcome.  Many hands makes for light(er) work.

**Comment by Zimmi48** [comment]
Closing in favor of #16652 and individual issues on specific undocumented tactics.
