### ISSUE TITLE
Ltac2: Ltac2 rec ... with ... is supported but not documented

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#11757]
Ltac does support the syntax
```
Ltac2 rec funcA (argA : typeA) :=
  ...
with funcB (argB : typeB) :=
  ...
.
```
but this is not documented in (https://coq.inria.fr/refman/proof-engine/ltac2.html#ltac-definitions).

Since Ltac2 is still missing some syntatic sugar, it is not obvious that this works (one could use local let rec unless one needs to call both functions from the outside.

**Comment by SkySkimmer** [comment]
4a7e39323bd57ac41ec90d4ea18f10423029e8b5 changed https://coq.inria.fr/refman/proof-engine/ltac2.html#ltac2-definitions to add the optional `with` to the grammar
