### ISSUE TITLE
Doc: The link to "flag" in the syntax description for cbv is wrong

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#11759]
In the reference manual (https://coq.inria.fr/refman/proof-engine/tactics.html#performing-computations) in the syntax description of `cbv` the link for `flag` points to the wrong entity (the kind of flag which can be set with Set and Unset). I would like a link to see the syntax of cbv flags, especially how to specify symbols for delta reduction as supported by Ltac2 cbv.

**Comment by Zimmi48** [comment]
Well spotted! This should be `strategy_flag` instead of just `flag`. The grammar description for these flags has recently been introduced in `master`: https://coq.github.io/doc/master/refman/language/gallina-specification-language.html#computations.

@jfehrle Should I open a PR fixing this or will this soon be included in a PR of yours on the Tactics chapter?

**Comment by jfehrle** [comment]
Up to you.  The correct syntax is

```
cbv {? @strategy_flag } {? @clause_dft_concl }
lazy {? @strategy_flag } {? @clause_dft_concl }
cbn {? @strategy_flag } {? @clause_dft_concl }
```

However `clause_dft_concl` is not defined in master.

This is already fixed in my local copy, but it may be a month or two before that gets merged.
If you want to do something right now, just leave off the `clause_dft_concl`.

**Comment by jfehrle** [comment]
> especially how to specify symbols for delta reduction as supported by Ltac2 cbv

Note that cbv is independent of Ltac2.  Also that Ltac syntax documentation has not been updated (it's way out of date), but that may be completed within a month.  Review/update of Ltac2 syntax in the doc might happen in a couple months.

**Comment by MSoegtropIMC** [comment]
It is in no way urgent.

**Comment by Zimmi48** [comment]
I think that will wait.

**Comment by jfehrle** [comment]
`cbv` was rewritten some time ago.  The issue description above doesn't fit the doc.  If you think there's still an issue, please reopen and explain the issue.
