### ISSUE TITLE
Add warning about writing parsers and other tools based on grammars in the manual, and warning rationale

### ISSUE THREAD

**Issue by palmskog** [coq/coq#11768]
#### Description of the problem

The current Coq manual lists quite a few grammars, e.g, for [basic Gallina](https://coq.github.io/doc/master/refman/language/gallina-specification-language.html). It's becoming apparent that some readers of the manual are under the impression that these grammars are (close to) canonical definitions of the grammars in Coq's implementation, and therefore can be used to implement tools such as stand-alone parsers. See, for example, [this discussion](https://coq.discourse.group/t/is-there-a-full-documentation-of-coqs-grammar/647/7) on the Discourse forum.

To discourage practitioners from implementing ad-hoc parsers for the various levels of syntax of Coq, I believe some kind of warning needs to be added, most directly at the [first overview](https://coq.inria.fr/refman/language/gallina-specification-language.html#about-the-grammars-in-the-manual) of the grammars. For example, the warning could go something like this:

> The grammars in the manual are provided for informational and educational purposes only. They should **not** be used as a basis for writing parsers or other tools for Coq. Tool developers that need to process Coq's syntax are recommended to instead write Coq plugins or rely on external libraries linked to Coq's implementation, such as SerAPI.

Ideally, the warning should come with a convincing rationale, e.g., that the grammars are not directly tied to the implementation, the implementation may change at any time independently, and many details in the real grammars have been abstracted away.

#### Coq Version

All released and in-development versions of Coq.

**Comment by Zimmi48** [comment]
Please check https://coq.gitlab.io/-/coq/-/jobs/533749342/artifacts/_install_ci/share/doc/coq/sphinx/html/language/core/basic.html#syntax-conventions, especially the note and the warning. The corresponding code is here: https://github.com/coq/coq/pull/12172/files#diff-a7469508612acbf195931678e09a488aR18-R76

**Comment by jfehrle** [comment]
For tool creation, maybe it would be feasible to extract the Coq parser as a standalone module by adding a coqpp option to replace the grammar actions with a generic callback while keeping syntax-modifying commands such as Notation.  I guess you'd have to handle some of the effects of loading modules and notation scopes as well, so there would have to be some refactoring to conditionally omit code not relevant to modifying syntax.  Perhaps also for loading plugins.

Some have suggested SerApi as an alternative.  IIUC SerApi has to execute the Coq code to produce the parse tree (slow) and from what I've seen, the AST it produces has transformed the input a good bit beyond a simple parse tree.  (IIUC we have a pretty-printing tool; I wonder how that works.)  For tools, it would also be nice if the parser could resync after errors as well as report comments (which the lexer discards).

Who knows, perhaps an IDE could run such a parser in the background to control syntax highlighting.

This might be an interesting project for a student.  It would require (at least) advice and buy-in from the relevant maintainers.

**Comment by Zimmi48** [comment]
I'll let @coq/parsing-maintainers comment, but I am not convinced that this is realistic nor that it is worthwhile.

**Comment by jfehrle** [comment]
Your comment isn't too helpful without any specifics to respond to.  I thought it would be clear this is just a trial balloon.  Ideas that are half-right or half-wrong may lead to better ideas.  I'm certainly not planning to start writing code for this now.

**Comment by ppedrot** [comment]
Currently this is not realistic, since there is no phase separation between parsing and evaluation. You essentially need the whole Coq system to be able to do that, not to mention the fact you will probably have to evaluate all sentences for it to work anyways. Part of the work of @maximedenes is to precisely to make this easier, by splitting this into two statically separate phases.

**Comment by jfehrle** [comment]
"evaluate all sentences" primarily because they need to interpret notation scopes?  That's the main work of the split?  Would there be a new layer/data structure between the parser actions and their interpretation?

**Comment by Zimmi48** [comment]
Not long ago, it was possible for `Instance` to open the proof mode or not depending on whether the obligations have been solved automatically or not. This (the `Refine Instance Mode`) has been deprecated then removed by @maximedenes. I don't know if there are other remaining examples of such things preventing to parse a document without executing it.

**Comment by ppedrot** [comment]
> I don't know if there are other remaining examples of such things preventing to parse a document without executing it.

I don't know either for Coq proper, but since plugins can perform arbitrary effects, we can't be ever sure that somebody out there is not introducing this kind of interactions. Untangling the phases statically is the only way to ensure correctness with 100% confidence.

**Comment by maximedenes** [comment]
> interpret notation scopes

AFAIK, notation scopes have nothing to do with parsing.

`Instance` was a very specific example, but think about `Import`. It essentially makes parsing state depend on name resolution, functor instantiation, etc.

**Comment by jfehrle** [comment]
> AFAIK, notation scopes have nothing to do with parsing.

The following is not related to parsing?  Remove "%ex" and Coq reports a parse error.

```
Declare Scope ex_scope.
Delimit Scope ex_scope with ex.
Notation "A '//' B" := (plus A B) (at level 35, right associativity) : ex_scope.
Check (1 // 2)%ex.
```

> think about `Import`. It essentially makes parsing state depend on name resolution, functor instantiation, etc.

Sure.  Supporting a standalone parser would require applying those aspects of commands that affect parsing.  That would probably require some refactoring and/or conditionally skipping parts of the current code that don't affect parsing.

**Comment by Zimmi48** [comment]
> > AFAIK, notation scopes have nothing to do with parsing.
> 
> The following is not related to parsing? Remove "%ex" and Coq reports a parse error.
> 
> ```
> Declare Scope ex_scope.
> Delimit Scope ex_scope with ex.
> Notation "A '//' B" := (plus A B) (at level 35, right associativity) : ex_scope.
> Check (1 // 2)%ex.
> ```

The error message is: Unknown interpretation for notation "_ // _".
That's not a parser error.

Notations are parsed the same way whatever the notation scope. This is why you sometimes have to "reserve notation". Notation scopes only determine how notations are *interpreted*. Maybe we should have kept the name "interpretation scope" in the refman after all...

**Comment by jfehrle** [comment]
Good point, too hasty on that example.  How about this one?

```
(*Notation "'IFX' c1 'then' c2 'else' c3" := (IF_then_else c1 c2 c3)
  (at level 200, right associativity) : ex.*)
Check (IFX True then True else True).
```

works if the notation is defined, but gives this error otherwise:

`Syntax error: ',' or ')' expected after [constr:operconstr level 200] (in [constr:operconstr]).`

**Comment by Zimmi48** [comment]
Sure, notations do change the parser. Notation scopes do not.

**Comment by jfehrle** [comment]
Sorry for my imprecise language.
