### ISSUE TITLE
Mention of figures in the documentation are meaningless in the HTML?

### ISSUE THREAD

**Issue by Ptival** [coq/coq#11770]
If you browse to this page:

https://coq.inria.fr/refman/addendum/extended-pattern-matching.html

You can read:

> The full syntax of match is presented in Figures 1.1 and 1.2.

These figures are either missing from said page, or in a different section and unlinked.

**Comment by Zimmi48** [comment]
Seems like a remnant of the

**Comment by Zimmi48** [comment]
Sorry, on my phone. I meant this is probably a leftover of the Sphinx migration.

**Comment by larsr** [comment]
What the figures referred to is now found here: https://coq.inria.fr/refman/language/gallina-specification-language.html#syntax-of-terms
