### ISSUE TITLE
Universe undefined with Require in Section

### ISSUE THREAD

**Issue by attila9778** [coq/coq#11783]
#### Description of the problem
For some reason the IDE states:
'Anomaly "Universe Coq.Lists.ListSet.1 undefined."
Please report at http://coq.inria.fr/bugs/.'

My code is reachable here: https://github.com/piszkor/AML-Formalization/blob/aea27dd944ae45a1754fab5b3a872ffc51e60e76/AML_definition.v
Or if having issues by accessing, than you can also reach here until 1st June: https://www.dropbox.com/s/ulqtaczra976xld/AML_definition.v?dl=0
#### Coq Version
CoqIDE 8.11.0

Operating system: Windows 10 Education, Version 1903, Build 18362.657

**Comment by ppedrot** [comment]
Here is a local copy of the bug, just in case: [bug.zip](https://github.com/coq/coq/files/4305206/bug.zip).

**Comment by ppedrot** [comment]
And here is a much shorter reproducible example:
```
Section AML.

Inductive T : Set := evar_c.

Require Import Coq.Lists.ListSet.

Inductive got : Prop := G (x : set T) : got

.

End AML.
```

**Comment by treeck** [comment]
I have a similar error message, with "13" instead of a "1" using version 8.11.0:
Anomaly "Universe Coq.Lists.List.13 undefined."
Please report at http://coq.inria.fr/bugs/.

The coq file is located at https://github.com/treeck/RASRGeometry/blob/master/euclidrelations.v

The file is large and I have no idea what lines are causing the error message.

**Comment by SkySkimmer** [comment]
Even shorter example:
~~~coq
Section S.
  Require Import Coq.Lists.ListSet.

  Definition x := set Type.
End S.
~~~
BTW if you do `Definition x := set nat.` instead you get `Anomaly "File "clib/int.ml", line 46, characters 14-20: Assertion failed."`

**Comment by SkySkimmer** [comment]
Maybe it's time to forbid require in section.

**Comment by ppedrot** [comment]
It was brought several times to the discussion, but every time somebody complained against its removal, so...

**Comment by SkySkimmer** [comment]
Currently it's de facto removed though.
I guess we could warn on Require and error on section End as a compromise :?

**Comment by treeck** [comment]
I'm not an expert on coq. If a Require in a section should not be used anymore, then what keyword should be used instead? An error message that says how to rectify legacy coq files containing a Require would be useful. Even better would be an update script that would scan and update files to the latest styles.

**Comment by ppedrot** [comment]
Requiring module should be done at toplevel, i.e. outside of sections and modules. We also recommend factorizing the require at the beginning of the v file as best practice.

**Comment by JasonGross** [comment]
Can we make it a warning that's an error by default, much like nested proofs?  It's very useful to be able to `Require` without having to go back to the top of the file, even if it should not be used in non-interactive development.

**Comment by JasonGross** [comment]
(Er, I guess nested proofs is a setting, but I'd be fine with either a setting or a warning that is fatal by default)
