### ISSUE TITLE
Give error message for invalid "fixannot" options, not an anomaly

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#11816]
`Definition foo := fix foo (n : nat) { wf n n } := 0.` generates the anomaly ""Non-structural recursive argument in non-program fixpoint".  This should be an error message, not an anomaly since it's just an unsupported combination.

Same thing for `Definition foo := fix foo (n : nat) { measure n } := 0.`

@Zimmi48 also tells me that "`wf` and `measure` fixannots are only supported in commands like Function and Program Fixpoint".  Would someone check that the commands that are not like these two give a reasonable error message (and not an anomaly)?

These clauses are defined in the `fixannot` nonterminal in the grammar.

Questions to @Zimmi48, I am just the scribe on this.

**Comment by Zimmi48** [comment]
At least, command `Fixpoint` itself gives a proper error message: "Well-founded induction requires Program Fixpoint or Function."
