### ISSUE TITLE
Ltac2 should expose the contents of the cast type

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11837]
#### Description of the problem

I want to be able to build terms with, e.g., `vm_cast`, but `cast` is opaque:
https://github.com/coq/coq/blob/901cbfab468efa868e3838c2009ac09978ee661a/user-contrib/Ltac2/Init.v#L26

cc @ppedrot 

#### Coq Version

master

**Comment by ppedrot** [comment]
Not hard to do, but I'd rather prioritize the more common use cases for the short-term future.
