### ISSUE TITLE
Sphinx 3.0 deprecation warnings.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#11856]
With Sphinx 2.3.1, I get new deprecation warnings related to the upcoming 3.0 Sphinx version:

```
.../sphinx/transforms/post_transforms/compat.py:69: RemovedInSphinx30Warning: math node for Sphinx was replaced by docutils'. Please use ``docutils.nodes.math_block`` instead.
.../sphinx_rtd_theme/search.html:21: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
```

It seems that the first one is something that can be fixed in `coqrst`. More precisely it looks like what needs to be changed is:

https://github.com/coq/coq/blob/4c2a4890b75d516acfeccdb4105e46760239a7f1/doc/tools/coqrst/coqdomain.py#L37

and

https://github.com/coq/coq/blob/4c2a4890b75d516acfeccdb4105e46760239a7f1/doc/tools/coqrst/coqdomain.py#L76-L83

@cpitclaudel Can you look into this? My own attempt was too naive to manage to fix this properly.

**Comment by cpitclaudel** [comment]
Done in #11862
