### ISSUE TITLE
Ltac2 Notations do not respect precedence

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#11866]
It is not entirely clear from the documentation, but it appears that `Ltac2 Notation ... : n := ...` is a way to set the parsing precedence of the notation. This does not seem to work, however:
```coq
From Ltac2 Require Import Ltac2 Message.

Ltac2 Notation "foo" : 2 := print (of_string "a").
Ltac2 Notation "foo" : 1 := print (of_string "b").

Goal True.
foo.
```
This prints `b`, while I would expect it to print `a`. Is this a bug or am I using it wrong?

#### Coq Version

The Coq Proof Assistant, version 8.12+alpha (March 2020)
compiled on Mar 20 2020 10:37:25 with OCaml 4.09.0

**Comment by ppedrot** [comment]
I think it is the other way around: lower numbers have higher precedence. This is the same semantics as in Ltac1, theoretically, because they both use camlp5 as backend.

**Comment by LasseBlaauwbroek** [comment]
Tested that too, does not work.

**Comment by LasseBlaauwbroek** [comment]
Here is another test case. It appears that all notations are getting registered at level 6:
```coq
From Ltac2 Require Import Ltac2 Message.

Ltac2 Notation "foo" := print (of_string "b").

Ltac2 Notation "bar1" t(self) := t.
Ltac2 Notation "bar2" t(next) := t.
Ltac2 Notation "bar3" t(tactic(6)) := t.
Ltac2 Notation "bar4" t(next) : 5 := t.
Ltac2 Notation "bar5" t(next) : -1 := t.
Ltac2 Notation "bar6" t(next) : 6 := t.

Goal True.
bar1 foo.
Fail bar2 foo.
bar3 foo.
Fail bar4 foo.
Fail bar5 foo.
Fail bar6 foo.
```

**Comment by JasonGross** [comment]
Here's another test-case:
```
Require Import Ltac2.Ltac2.

Ltac2 Notation "ex0" x(tactic(0)) := ().
Ltac2 Notation "ex1" x(tactic(1)) := ().
Ltac2 Notation "ex2" x(tactic(2)) := ().
Ltac2 Notation "ex3" x(tactic(3)) := ().
Ltac2 Notation "ex4" x(tactic(4)) := ().
Ltac2 Notation "ex5" x(tactic(5)) := ().
Ltac2 Notation "ex6" x(tactic(6)) := ().

Ltac2 Notation ":::0" x(tactic) "+0" y(tactic) : 0 := ().
Ltac2 Notation ":::1" x(tactic) "+1" y(tactic) : 1 := ().
Ltac2 Notation ":::2" x(tactic) "+2" y(tactic) : 2 := ().
Ltac2 Notation ":::3" x(tactic) "+3" y(tactic) : 3 := ().
Ltac2 Notation ":::4" x(tactic) "+4" y(tactic) : 4 := ().
Ltac2 Notation ":::5" x(tactic) "+5" y(tactic) : 5 := ().
Ltac2 Notation ":::6" x(tactic) "+6" y(tactic) : 6 := ().
Ltac2 Notation ":::7" x(tactic) "+7" y(tactic) : 7 := ().
Goal True.
  ex0 :::0 0 +0 0.
  ex1 :::0 0 +0 0.
  (*ex2 :::0 0 +0 0.*) (* fails with an anomaly, cf COQBUG(https://github.com/coq/coq/issues/12807) *)
  (*ex3 :::0 0 +0 0.*)
  ex4 :::0 0 +0 0.
  ex5 :::0 0 +0 0.
  ex6 :::0 0 +0 0.

  ex0 :::1 0 +1 0.
  ex1 :::1 0 +1 0.
  (*ex2 :::1 0 +1 0.*)
  (*ex3 :::1 0 +1 0.*)
  ex4 :::1 0 +1 0.
  ex5 :::1 0 +1 0.
  ex6 :::1 0 +1 0.

  ex0 :::6 0 +6 0.
  ex1 :::6 0 +6 0.
  (*ex2 :::6 0 +6 0.*)
  (*ex3 :::6 0 +6 0.*)
  ex4 :::6 0 +6 0.
  ex5 :::6 0 +6 0.
  ex6 :::6 0 +6 0.

  ex0 :::7 0 +7 0.
  ex1 :::7 0 +7 0.
  (*ex2 :::7 0 +7 0.*)
  (*ex3 :::7 0 +7 0.*)
  ex4 :::7 0 +7 0.
  ex5 :::7 0 +7 0.
  ex6 :::7 0 +7 0.
```

**Comment by jfehrle** [comment]
> I think it is the other way around: lower numbers have higher precedence. This is the same semantics as in Ltac1, theoretically, because they both use camlp5 as backend.

camlp5 doesn't enforce this.  Levels don't have to be assigned a label; the label string doesn't have to be a number.  I believe camlp5 only looks at the order in which the levels appear in the grammar file, so the numbers can be descending, ascending or a hodge-podge.  The Coq grammar follows the conventions that labels that are always numbers and that they are always descending.  For sanity's sake.

If you reverse the order of the notations, it prints "a".

Even so, having 2 identical productions doesn't make a lot of sense; there's nothing to distinguish.  After fixing the Ltac2 Notation code, I'm pretty sure camlp5 will match at the "2" level.  An exercise for the reader: try it by modifiying an mlg file.  A realistic example would something like defining `A my+ B `at level 2 and `A my* B` at level 1 so that `x my+ y my* z` is `x my+ (y my* z)`.

**Comment by ppedrot** [comment]
After looking at this issue, I am quite confused. It does look like the level argument reaches the gramlib library, but for some reason it has no effect in the actual grammar extension. This is very weird, could it be a bug in gramlib?

**Comment by ppedrot** [comment]
Ah, got it: it's a confusion between the *level* and the *position*. Don't quite remember the difference but let's cargo cult and it should work properly.
