### ISSUE TITLE
Coq master regression: firstorder solves fewer goals

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#11865]
#### Description of the problem

Since last night, our regular build of GPFSL against Coq master started failing.
In [this line](https://gitlab.mpi-sws.org/iris/gpfsl/-/blob/254dbbe49b04fd501362708fd78050e86c71935e/theories/lang/lang.v#L1018), all goals are solved on Coq 8.11, but with the exact same version of all dependencies, some goals remain open on Coq master.

Concretely, the following goal used to be solved by `firstorder`, but is no longer:
```
  z1, z2 : Z
  NEQ : LitV z2 ≠ LitV z1
  ============================
  z1 ≠ z2
```

#### Coq Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.12+alpha (March 2020)
compiled on Mar 20 2020 7:21:23 with OCaml 4.08.1
$ opam show coq -f version,source-hash
version     dev
source-hash 47d92a69
```
(Would be really useful if Coq could show the source hash in its version number, for dev builds...)

**Comment by RalfJung** [comment]
Looking at https://github.com/coq/coq/pull/11760, seems like this was deliberate? I now replaced a few uses of `firstorder` by `naive_solver` from std++, and things work again for us.

**Comment by vbgl** [comment]
This goal is not about first order logic but about injectivity of constructors. It can be solved by `congruence` for instance.

**Comment by Zimmi48** [comment]
You can also use the unreleased changelog to know if a change was deliberate: https://coq.github.io/doc/master/refman/changes.html#unreleased-changes

**Comment by Zimmi48** [comment]
Looks like we can close this.
