### ISSUE TITLE
Feature Request: Destructor function for plugins

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#11864]
I would like there to be a hook into the end of the compilation process of a file for plugins. This would need to happen when the source file is completely processed but the document is still open. Then the plugin can have the option to put some final information in the `.vo` file, such as summaries. Of course this would only make sense in compilation mode.

As far as I can see there is currently no way to achieve this. This feature could be very simple. Just a way to register a function with `Ccompile` that is called as a heads up if the document is processed.

**Comment by ejgallego** [comment]
Actually that exists in the form of `Declaremods.append_end_library_hook`, but using that API is fairly dangerous.

For example if you want to save stuff in `.vo` files you should use the regular `Libobject` mechanism.

**Comment by LasseBlaauwbroek** [comment]
A interesting, I was not aware of `Declaremods.append_end_library_hook`. Would it be safe to save things through `Libobj` at the moment that `Declaremods.append_end_library_hook` is called?

**Comment by ejgallego** [comment]
Libobj should save the stuff automatically for you, no need to use the hook which is indeed dangerous.

**Comment by LasseBlaauwbroek** [comment]
Sure, but I would like to generate some new stuff at the end of file compilation.

**Comment by LasseBlaauwbroek** [comment]
But yeah, looking at the code this should be suitable enough for me. I guess I shouldn't have opened an issue. Thanks for the help. Closing.

**Comment by ejgallego** [comment]
> Sure, but I would like to generate some new stuff at the end of file compilation.

I'm unsure if libobjects allow this, but they should.

Feel of course free to open issues; that's what the issue system is here for.
