### ISSUE TITLE
The external function `coq_uint63_to_float_byte' is not available

### ISSUE THREAD

**Issue by advorkin** [coq/coq#11893]
Hello.  I'm getting the following error message when compiling/building coq 8.11.0 on RHEL 7 based OS.  Does this error message look familiar at all?  Thank you!

#### Description of the problem

"/usr/bin/ocamlfind" ocamlc -thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence  -I config -I clib -I lib -I checker -I kernel -I kernel/byterun -g  -c checker/votour.ml
"/usr/bin/ocamlfind" ocamlc -thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence  -I coqpp -I config -I clib -I lib -I kernel -I kernel/byterun -I library -I engine -I pretyping -I interp -I proofs -I gramlib/.pack -I parsing -I printing -I tactics -I vernac -I stm -I toplevel -I tools -I tools/coqdoc -I plugins/omega -I plugins/micromega -I plugins/setoid_ring -I plugins/extraction -I plugins/cc -I plugins/funind -I plugins/firstorder -I plugins/derive -I plugins/rtauto -I plugins/nsatz -I plugins/syntax -I plugins/btauto -I plugins/ssrmatching -I plugins/ltac -I plugins/ssr -I user-contrib/Ltac2 -g   -o bin/votour -linkpkg  -I checker clib/cObj.cmo kernel/uint63.cmo kernel/float64.cmo checker/analyze.cmo checker/values.cmo checker/votour.cmo kernel/byterun/libcoqrun.a
File "_none_", line 1:
Error: Error while linking kernel/uint63.cmo:
The external function `coq_uint63_to_float_byte' is not available
make[1]: *** [bin/votour] Error 2

#### Coq Version

8.11.0

**Comment by herbelin** [comment]
This seems to be what #11634 is fixing (to be available in 8.11.1).

Which architecture are you on?

**Comment by advorkin** [comment]
Thank you for a quick response.

It's Springdale 7 (RedHat based).

$ uname -a
Linux sevenbuild 3.10.0-693.11.6.el7.x86_64 #1 SMP Wed Jan 3 19:03:22 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

Do you have an estimate of when 8.11.1 will be available?

Thank you again for your prompt response.

**Comment by advorkin** [comment]
I was able to follow the #11634 fix and that was it.  I manually changed the code.

Thank you so much!

**Comment by ejgallego** [comment]
Glad you solved the problem, thanks for reporting @advorkin !
