### ISSUE TITLE
Standard library : non-recursive functions defined using Fixpoint

### ISSUE THREAD

**Issue by ddemange** [coq/coq#11903]
#### Description of the problem
Several non-recursive functions in the standard library are defined using the `Fixpoint` keyword. This raises some warnings when compiling their extracted Ocaml code with option -w A.
Examples found: [N.eqb](https://github.com/coq/coq/blob/7ba059507b67b1f6ea3566a5d1dee40f6af78316/theories/NArith/BinNatDef.v#L129), [N.ldiff](https://github.com/coq/coq/blob/7ba059507b67b1f6ea3566a5d1dee40f6af78316/theories/NArith/BinNatDef.v#L316), [Z.eqb](https://github.com/coq/coq/blob/7ba059507b67b1f6ea3566a5d1dee40f6af78316/theories/ZArith/BinIntDef.v#L211).
There may be other examples.

#### Coq Version
Observed with version 8.8.2, but seems present on more recent (and current) versions.

**Comment by maximedenes** [comment]
Shouldn't we introduce a Coq warning for non-recursive fixpoints?

**Comment by Zimmi48** [comment]
>Shouldn't we introduce a Coq warning for non-recursive fixpoints?

Yes, absolutely! It is a typical example of beginner's mistake that I've observed over several years in my Coq classes. It can also lead to proofs that are hard to debug and that are in fact due to the definition using `Fixpoint` instead of `Definition`.

**Comment by herbelin** [comment]
@maxidenes, @zimmi48: do you plan to add a warning? Or do we ask @ddemange if interested in contributing a PR fixing the above three examples?

**Comment by herbelin** [comment]
Or, maybe, do we simply ignore the `Fixpoint` declaration and do as if a `Definition`?

**Comment by Zimmi48** [comment]
>a PR fixing the above three examples

The warning is the only way to know if there are more.
I have saved this issue in my list and will come back to it if nobody takes care of it first (which I would appreciate of course given that I've many other things to do).
