### ISSUE TITLE
Errors and warning index in doc is unreadable

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#11900]
Some of the messages in this index are very long, which doesn't play well with the HTML.  The HTML panel is truncating the left hand side of the panel, so the beginnings of each message are not visible.  It's not possible to scroll the panel, either.

A reasonable fix would be to truncate the messages at a certain length--or better, at the last space before that length.

![image](https://user-images.githubusercontent.com/1253341/77477999-8337ed00-6dda-11ea-806e-8c62347b3614.png)

**Comment by jfehrle** [comment]
The doc on the Coq website doesn't have this problem.

**Comment by Zimmi48** [comment]
> The doc on the Coq website doesn't have this problem.

It does if you quick jump to a letter. Example: https://coq.inria.fr/refman/coq-exnindex.html#cap-t

**Comment by jfehrle** [comment]
Oddly enough, I don't see this problem after quick jump on my phone, though the page is formatted differently.

**Comment by jfehrle** [comment]
This is no longer broken; the index entries are appropriately wrapped now.  Perhaps fixed by a Sphinx upgrade.
