### ISSUE TITLE
Critical sections in tactics

### ISSUE THREAD

**Issue by ckeller** [coq/coq#11923]
#### Description of the problem
I wonder if it is possible to have critical sections in tactics (to prevent parts of the code to be run in parallel in asynchronous mode).

See http://chadok.info/~ckeller/Divers/d1da9cf45ee36be30e07cae255e9a35d83b1dea5/mutex.tar.gz for a toy example:
```bash
make foo
make vio
make checkproofs J=10
```
The interesting file is `src/shared.ml`.

Since I had to use a file (`foo`) to have a shared value for the tactic (instead of a shared variable, see the code that is commented out), my understanding is that the mutex as well is not shared between the asynchronous calls of the tactic. Is that correct? Thus, is there a way to implement critical sections?

(I would like to have it because I am implementing a tactic that calls another program (as a black-box) that does share a file.)

#### Coq Version
8.11.0

**Comment by ckeller** [comment]
Hi, do you have any idea? Thanks!

**Comment by ppedrot** [comment]
Since there is no guarantee that two tasks will run in the same process, I think you should rely on the capabilities of the OS, in particular POSIX locks. You should generate a file, store the name of that file in the summary, and use it as a lock.

**Comment by ckeller** [comment]
Thank you for your answer. Could you detail a bit more in the example I have posted?

**Comment by ppedrot** [comment]
@ckeller something along those lines:
```
let mutex = Summary.ref ~name:"COQ-LOCK" (Filename.temp_file "coq" "lock")

let lock_mutex () =
  let fd = Unix.openfile !mutex [Unix.O_WRONLY] 0o600 in
  let () = Unix.lockf fd Unix.F_LOCK 0 in
  fd

let unlock_mutex fd =
  let () = Unix.lockf fd Unix.F_ULOCK 0 in
  Unix.close fd

(* Testing *)

let test use_mutex =
  Random.self_init();
  let s1 = Random.int 15 in
  let s2 = Random.int 15 in
  let s3 = Random.int 15 in
  Unix.sleep s1;

  let fd = lock_mutex () in

  increment ();
  Unix.sleep s2;
  Feedback.msg_notice (Pp.strbrk ("value = "^(string_of_int (value ()))));
  assert (value () = 1);
  Feedback.msg_notice (Pp.strbrk "Everything is awesome!");
  Unix.sleep s3;
  reset ();

  unlock_mutex fd
```

You could reuse the same `foo` file for locking but you have to be careful to use the same file descriptor, since closing any file descriptor referring to a file removes all locks on that file.
