### ISSUE TITLE
Coq refman search does not work

### ISSUE THREAD

**Issue by tchajed** [coq/coq#11936]
#### Description of the problem

If you go to https://coq.github.io/doc/master/refman/, search doesn't work. The javascript console says `Stemmer` is not defined, which lead me to https://github.com/sphinx-doc/sphinx/issues/5460. It's possible the refman needs to be regenerated with a fixed version of Sphinx.

#### Coq Version

8.12+alpha

**Comment by Zimmi48** [comment]
Thanks @tchajed for the report and the investigation! Do you want to prepare the PR to update the minimal required version to 1.8.3? Cf. the advice I gave to Clément in #11862. If not, that's fine and I'll take care of this before 8.12.

**Comment by tchajed** [comment]
I’d prefer if you take care of it @Zimmi48. I don’t even have a working Sphinx set up at the moment.

**Comment by Zimmi48** [comment]
Right, though in this case it doesn't require doing anything locally. I personally have Sphinx 2.3.1 on my machine, so I cannot even see the issue locally.

**Comment by tchajed** [comment]
Thanks for fixing this @cpitclaudel!
