### ISSUE TITLE
match rules in ltac_expr1 are missing optional [|] in the documented syntax

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11932]
### Description of the problem

I see at https://coq.inria.fr/refman/proof-engine/ltac.html#grammar-token-ltac_expr1
![image](https://user-images.githubusercontent.com/396076/77697574-7a374f00-6f85-11ea-9b49-af5211afcf00.png)

This grammar suggests that `match goal with | _ => idtac end` is not valid, but it is.  Just as in Gallina `match`, there is an optional `|` at the beginning of the `|`-separated list of branches.

Note that the Gallina `match` is correctly documented at https://coq.inria.fr/refman/language/gallina-specification-language.html#grammar-token-term:
![image](https://user-images.githubusercontent.com/396076/77697722-c2ef0800-6f85-11ea-9e95-693d1be30d4d.png)

#### Coq Version

8.11.0

**Comment by Zimmi48** [comment]
@JasonGross A rework of the documentation of the grammar is currently ongoing. The Gallina chapter has already been updated. The Ltac chapter will be done before 8.12. See https://coq.github.io/doc/master/refman/ for the documentation of the master branch.
