### ISSUE TITLE
Setoid rewrite in Type much slower than setoid rewrite in Prop

### ISSUE THREAD

**Issue by VincentSe** [coq/coq#11973]
#### Description of the problem

Constructive reals intensely use setoid rewriting in sort Type, because the strict order `x < y` is in sort Type. For example in file coq/theories/Reals/Abstract/ConstructiveLimits.v, this chain of 3 rewrites is slow at line 294
`rewrite CRmult_1_r, <- CRmult_assoc, <- CR_of_Q_mult in abs. `

Those same rewrites are a lot faster when applied to a large order `x <= y`, which is in sort Prop.

Are there really more checks to do in sort Type, or is it just a bug of class `CRelationClasses.Equivalence` compared to class `RelationClasses.Equivalence` ?

#### Coq Version

8.11, linux debian.

**Comment by ppedrot** [comment]
My initial guess would be universe polymorphism. Judging from the profiling, most of the time is passed adding universe constraints, which is consistent with polymorphism being slow.

**Comment by VincentSe** [comment]
In that particular case, there is a proof `ConstructiveReals.CRltEpsilon` that the type `x < y` is actually equivalent to a Prop. Can this proof be registered somewhere, so that Coq doesn't check any universe constraints ?

**Comment by ppedrot** [comment]
Nope, you have to use the monomorphic term. Being logically equivalent has nothing to do with kernel type-checking, unfortunately :/
