### ISSUE TITLE
Shared proof mode grammar

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#12004]
As of today, bullets and focusing brackets (and commands) and some proof-mode only commands (like `Grab Existential Variables`) are defined in the main grammar and thus can be run outside proof-mode (which makes no sense). OTOH, goal selectors, including goal selectors in front of focusing brackets, are only defined in the Ltac1 grammar, and thus cannot be used from Ltac2 (until they are re-implemented in Ltac2).

It seems to me that all of these should be defined in a special grammar that is loaded by default by all proof modes (unless they specifically reject it). So that, for instance, `{` is rejected outside of proof editing mode, and that `2: {` is accepted by default by Ltac2.

EDIT: the discussion below from Oct. 2020 is on a slightly different topic which is whether parsing proof commands / tactics in all context (and failing at interpretation time) could lead to error messages that are easier to understand.

**Comment by jfehrle** [comment]
Currently if you enter a tactic outside a proof, you get a syntax error.  For a while now, I've thought that's user unfriendly--we should parse the tactic and have a semantic check report that "Tactics may only be used in the body of a proof."  Perhaps that approach would work for this issue, too.  Of course, the user would still have to choose whether to use `Classic` or `Ltac2` for parsing the tactics.

**Comment by jfehrle** [comment]
> ... are defined in the main grammar

In `subprf`.  `subprf ::= "{"` overlaps with `tactic_mode ::= {? toplevel_selector } "{"`.

**Comment by Zimmi48** [comment]
> Currently if you enter a tactic outside a proof, you get a syntax error.  For a while now, I've thought that's user unfriendly--we should parse the tactic and have a semantic check report that "Tactics may only be used in the body of a proof."  Perhaps that approach would work for this issue, too.  Of course, the user would still have to choose whether to use `Classic` or `Ltac2` for parsing the tactics.

I find this idea very nice. I wonder if there could be drawbacks to this approach (cc @coq/parsing-maintainers). If not, I think it would make sense to follow it instead of the additional complexity that my original proposal would introduce.

**Comment by ejgallego** [comment]
> I find this idea very nice. I wonder if there could be drawbacks to this approach (cc @coq/parsing-maintainers). If not, I think it would make sense to follow it instead of the additional complexity that my original proposal would introduce.

Tactics are defined for plugins so indeed it may be complex to implement this properly, in particular due to plugin-local state. IMHO not worth it, as opposed to adding more structure to documents.

**Comment by jfehrle** [comment]
Perhaps.  I thought it might be done pretty simply by eliminating `NoEdit` mode as a distinct set of grammar productions and adding a semantic check in the parser action routine for the production that executes tactics.  I expect tactics from plugins would generally rely on the same action routine; not doing so seems like a violation of Coq's current design (e.g. Stm handles all tactic execution).  And if not, it may not matter, a minor plugin-specific glitch--or the plugin could make the same check where appropriate.

**Comment by Zimmi48** [comment]
>Tactics are defined for plugins so indeed it may be complex to implement this properly, in particular due to plugin-local state. IMHO not worth it, as opposed to working in adding more structure to documents.

I don't understand / don't follow. The goal is not to have the tactics be loaded by default, nor to get rid of proof modes, but to make no parsing distinction between the interactive proof mode and the rest of the document (to fail at interpretation time). Could you make it clearer on how this would be complex to do and how it is related to plugin-local state? My naïve intuition was rather that it is the current situation distinguishing the parsing state inside and outside interactive proof mode which introduces a more complex design...

**Comment by ejgallego** [comment]
@Zimmi48 what I mean is that the parsing rules are loaded by the plugin itself, so if you don't load the plugin you cannot parse ltac, also parsing in principle can depend for example on having a proof state or some other state that is local to the plugin, so IMHO it seems hard to depend on that, unless you merge the plugin grammar into the main grammar.

The current design is complex for other reasons, I'd say that in general is due to the _full_ parsing state, of which the mode is only one part, you also have notations, etc... The current implementation is at odds with the proof parsing state because it needs to perform static analysis, but that's a particularity of the implementation, other document managers won't have a problem with this I think.

**Comment by Zimmi48** [comment]
> what I mean is that the parsing rules are loaded by the plugin itself, so if you don't load the plugin you cannot parse ltac

Again, I think there is a misunderstanding. The goal is certainly not to parse Ltac in all circumstances. The goal is only to not switch the parser when entering the interactive proof mode (i.e. after a `Lemma` command for instance) and when leaving it (after `Qed`). Of course, tactics will only be parsed if and only if the Ltac plugin is loaded.

**Comment by Zimmi48** [comment]
In particular (and to further clarify), I disagree with Jim that we could / should get rid of the `Noedit` mode, because you need a default (no extension of the vernacular) when the prelude (and thus Ltac) is not loaded.

**Comment by ejgallego** [comment]
> The goal is certainly not to parse Ltac in all circumstances. The goal is only to not switch the parser when entering the interactive proof mode (i.e. after a `Lemma` command for instance) and when leaving it (after `Qed`). Of course, tactics will only be parsed if and only if the Ltac plugin is loaded.

I see, I understand now. That could be interesting but I'd expect some issues.

> In particular (and to further clarify), I disagree with Jim that we could / should get rid of the `Noedit` mode, because you need a default (no extension of the vernacular) when the prelude (and thus Ltac) is not loaded.

Well, what you are proposing is to get rid of modes at all right? Or they would be just global?

In theory all this is easy, if you look into `pcoq` you will see that mode switching is just a callback; but yeah, in particular with the higher layers there are still some bugs / issues that could impact this.

**Comment by Zimmi48** [comment]
> Well, what you are proposing is to get rid of modes at all right? Or they would be just global?

We would still need modes to be able to switch, e.g., between Ltac and Ltac2. We cannot avoid this without sacrificing too much. However, the modes would become "global" in some sense yes, since the parsing rules would be activated everywhere in the document.

**Comment by ejgallego** [comment]
Some weird things that are allowed today are for example:
```coq
- Definition a := 3.
```

I noticed this in a proof development where random `-` where inserted due to a botched merged, however the file compiled fine O_O
