### ISSUE TITLE
Name mangling mangles explicitly given argument names

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#12001]
#### Description of the problem

Name mangling via `-mangle-names` seems to mangle each and every argument name, even those that are explicitly given:
```coq
Lemma leibniz_equiv_iff {A : Type} (x y : A) : True.
Proof. tauto. Qed.
About leibniz_equiv_iff.
```
prints
```
leibniz_equiv_iff : forall {mangled_0 : Type}, mangled_0 -> mangled_0 -> True
```

That currently makes it rather useless as it breaks uses like `leibniz_equiv_iff (A:=...)`.

#### Coq Version

```
$ coqc --version
The Coq Proof Assistant, version 8.12+alpha (April 2020)
compiled on Apr 2 2020 8:51:47 with OCaml 4.08.1
```
But that's not very useful for dev builds, so let's ask opam:
```
<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version      dev
repository   coq-core-dev-test
source-hash  971c8e12
```

**Comment by maximedenes** [comment]
Related issues: https://github.com/coq/coq/issues/6785, https://github.com/coq/coq/issues/6786.

The problem is that Coq tries to rename user-given arguments on the fly, because it accepts non-fresh names, as in:
```coq
Section foo.
Variable A : Type.
Lemma leibniz_equiv_iff : forall {A : Type} (x y : A), True.
Proof. intros; tauto. Qed.
About leibniz_equiv_iff.
End foo.
```

https://github.com/coq/coq/pull/11510 introduces a warning in such cases, but it does not seem to remove this on-the-fly renaming.

It is not 100% clear to me why we need names to be fresh.

**Comment by RalfJung** [comment]
https://github.com/coq/coq/issues/4536 could also be related? It is closed though.

**Comment by maximedenes** [comment]
Sorry to report on this a bit late. I spent some time thinking about the issue, and I believe a clean way to do it would be to redesign the named arguments machinery. We could introduce a system similar to the OCaml labels : 
- arguments could be applied by name only for explicitely labeled binders
- labeled binders would have to be fresh, so they won't be renamed on the fly by Coq

**Comment by maximedenes** [comment]
@RalfJung would you mind testing again the use of `-mangle-names`, now that this issue has been fixed?

**Comment by RalfJung** [comment]
I will definitely do that. :) However I am defending my PhD thesis tomorrow, and finishing up the dissertation next week, so this might have to wait a bit.

**Comment by RalfJung** [comment]
@maximedenes  The good news is that for the first time, std++ `base.v` compiles with name mangling.

The bad news is that a later file triggers an anomaly: https://github.com/coq/coq/issues/12880.
