### ISSUE TITLE
String_as_OT.compare blows up when evaluated

### ISSUE THREAD

**Issue by formalize** [coq/coq#12015]
#### Description of the problem
Here's a straightforward use of FSets:

    From Coq Require Import FSets.FSetAVL Structures.OrderedTypeEx String.

    Module StringAVLSet := FSetAVL.Make String_as_OT.
    Import StringAVLSet.
    Open Scope string_scope.

    Eval vm_compute in mem "aa" (add "aa" (add "ab" empty)).

However, Coq evaluates this term to a 200K monstrosity and takes some time too:

    $ time coqc Bug.v | wc
       3512    9636  206693

    real	0m8,475s
    user	0m8,138s
    sys	0m0,310s

Is a set of two elements really supposed to work like this?

#### Coq Version
Tried under:
8.10.0
8.10.1
8.10.2
8.11.0

**Comment by ppedrot** [comment]
The set implementation probably relies on opaque proofs, which are blocking the reduction, leading to the kind of issues you observed. AFAIU, FSets are not supposed to be used from inside Coq to perform computation, they are typically used to prove programs and get extracted. If you want e.g. to write reflexive tactics and the like, you should use other data structures.

**Comment by formalize** [comment]
Thank you, I'll do that.

**Comment by proux01** [comment]
Well, FSet (assuming it behaves like its sibling FMaps) can perfectly be used inside Coq. One just have to be careful to surround the call in {,vm_,native_}compute by a functions such as M.elements to avoid computing the huge balancing proof terms. See an example (wit FMaps) here : https://github.com/CoqEAL/CoqEAL/blob/master/refinements/multipoly.v#L21

**Comment by ppedrot** [comment]
@proux01 here the function is supposed to return a boolean in log(n), so how do you do that efficiently? Using lists kind of defeats the purpose, doesn't it?

**Comment by SkySkimmer** [comment]
I think it's the compare on strings which blows up, not the fset machinery. eg
~~~coq
From Coq Require Import OrderedTypeEx String.

Open Scope string_scope.

Eval vm_compute in String_as_OT.compare "aa" "ab".
(* 2k lines blocked on Ascii.ascii_nat_embedding and PeanoNat.Nat.compare_eq *)
~~~

**Comment by ppedrot** [comment]
Let's reopen then, that's a proper issue indeed.

**Comment by ppedrot** [comment]
The `MSet` API is a bit unfortunate, it should separate the computational `compare` function from its specification...

**Comment by formalize** [comment]
I've written a replacement for String_as_OT that doesn't have this issue:
https://github.com/formalize/coq-yul/blob/master/StringCmp.v

**Comment by proux01** [comment]
Note that the original code was submitted by @lastland in #7221 He may have an opinion on this.

**Comment by lastland** [comment]
@proux01 Thanks for bringing this up to my attention.

It seems that this is my fault: as @SkySkimmer pointed out, it is the `compare` function that blows up. And it blows up because I embedded a proof of a lemma in a recursive computation procedure:
https://github.com/coq/coq/blob/V8.11.0/theories/Structures/OrderedTypeEx.v#L389-L396

I tried extracting the proof as a local lemma ended with `Qed` (this part carries no actual computation, so it should be OK, right?) and the comparison has got much faster:
```coq
Module String_as_OT.
  ...
  Local Lemma nat_of_ascii_eq_implies_eq :
    forall a b, (nat_of_ascii a ?= nat_of_ascii b)%nat = Eq -> a = b.
  Proof.
    intros. apply Nat.compare_eq in H.
    assert (ascii_of_nat (nat_of_ascii a)
            = ascii_of_nat (nat_of_ascii b)) by auto.
    repeat rewrite ascii_nat_embedding in H0.
    assumption.
  Qed.

  Definition compare x y : Compare lt eq x y.
  Proof.
    generalize dependent y.
    induction x as [ | a s1]; destruct y as [ | b s2].
    - apply EQ; constructor.
    - apply LT; constructor.
    - apply GT; constructor.
    - destruct ((nat_of_ascii a) ?= (nat_of_ascii b))%nat eqn:ltb.
      + apply nat_of_ascii_eq_implies_eq in ltb. subst.
        destruct (IHs1 s2).
        * apply LT; constructor; auto.
        * apply EQ. unfold eq in e. subst. constructor; auto.
        * apply GT; constructor; auto.
      + apply nat_compare_lt in ltb.
        apply LT; constructor; auto.
      + apply nat_compare_gt in ltb.
        apply GT; constructor; auto.
  Defined.

  Definition eq_dec (x y : string): {x = y} + { ~ (x = y)} := string_dec x y.
End String_as_OT.
```
The same command given by @SkySkimmer will now give a result in 13 lines (as opposed to 2k+ lines)...

**Comment by proux01** [comment]
Great! Could you open a PR with this fix please?

**Comment by ppedrot** [comment]
I prefer @formalize 's solution, which clearly separates the computational content from the proofs.

**Comment by proux01** [comment]
I agree. The only thing that bothers me is that if it changes the definition of lt, it may break code that would depend on it (but if this reduces to @lastland 's code and he agrees, that's certainly fine).

**Comment by lastland** [comment]
I am certainly fine if people hope to use @formalize 's solution.

I have only briefly looked at @formalize 's solution, it seems to implement the same comparison algorithm, but---as @ppedrot pointed out---it has a clear separation between computational content and proofs: when having a long string, @formalize 's solution only needs to produce one proof, whereas mine produces one every time a recursive call happens (although the proof involved is only a simple application, it's a bit wasteful).

**Comment by formalize** [comment]
Alright, I've opened a PR with a version that doesn't change the definition of lt.

**Comment by formalize** [comment]
The PR was approved, closing.

**Comment by ppedrot** [comment]
@formalize technically, merging the PR would have automatically close this issue, but well...

**Comment by formalize** [comment]
Sorry, didn't do it before.
