### ISSUE TITLE
ssreflect "rewrite ... in" does not work with setoids

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#12011]
#### Description of the problem

Consider this code:
```
From Coq Require Import Setoid ssreflect.

Lemma test A (R : relation A) `{Equivalence _ R} (x y z : A) :
  R x y -> R y z -> R x z.
Proof.
  intros Hxy Hyz.
  Fail rewrite -Hxy in Hyz.
  (* The command has indeed failed with message:
  tampering with discharged assumptions of "in" tactical *)
  rewrite <-Hxy in Hyz.
```

This demonstrates that ssreflect `rewrite .. in` is broken when setoid relations are involved, even though Coq's `rewrite <-` works fine.

(This bug is outstanding for years and I thought it has long been reported, but I cannot find a report here. Maybe it was in the ssreflect repo and was forgotten to be moved over or so.)

#### Coq Version

Coq 8.11.0

**Comment by Blaisorblade** [comment]
I think this was https://github.com/math-comp/math-comp/issues/16; which should maybe be closed for this.

**Comment by RalfJung** [comment]
I'm not sure who to ping here, but it'd be good to figure out if anyone has a good idea for what it would take to fix this. This bug is a constantly reoccurring source of trouble for anyone using both ssreflect and setoids.

**Comment by gares** [comment]
CC @coq/ssreflect-maintainers

**Comment by SkySkimmer** [comment]
See https://github.com/coq/coq/pull/13882
