### ISSUE TITLE
Numeral Notation reversed for uint?

### ISSUE THREAD

**Issue by sleepyprof** [coq/coq#12016]
#### Description of the problem

Not sure if this is a bug or a feature, but the Numeral Notation seems to be reversed when using `uint`:
```coq
Require Import DecimalNat.
Declare Scope test_scope.
Open Scope test_scope.
Numeral Notation Decimal.uint Decimal.uint_of_uint Decimal.uint_of_uint : test_scope.
Compute Unsigned.to_lu (10%nat).
```
yields
```coq
= 01
     : Decimal.uint
```
#### Coq Version
Tested with CoqIDE_8.11.0 (Mac OS).

**Comment by herbelin** [comment]
> Not sure if this is a bug or a feature.

One would need a specialist of the `Decimal` module (@JasonGross, @proux01, @letouzey), but I suspect that this is not a bug: `to_lu` stands for conversion to "little endian" representation, while the decimal printer is supposed to work on big endian. Printing the big endian conversion, `Compute Nat.to_uint (10%nat).`, is giving the expected result. I don't know however what is the purpose of this `to_lu` conversion from `nat`.

**Comment by proux01** [comment]
I agree.

> I don't know however what is the purpose of this to_lu conversion from nat.

It seems to be used for specification/proof that parser and printing functions are (somewhat) in bijection (c.f. https://github.com/coq/coq/blob/master/theories/Numbers/DecimalNat.v).

**Comment by sleepyprof** [comment]
ah, my fault then. I did not realize that I should use `to_uint` instead of `to_lu`. Thanks for your help.
