### ISSUE TITLE
coq_makefile command line options are not documented, etc.

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12029]
At the least the doc should mention that `coq_makefile --help` shows all the options.

This line in the help output seems outdated (what about mlgs?  are ml4s still accepted?): `[file.ml[i4]?]: Objective Caml file to be compiled`

The fact that coqc will use `-R . Top` as the default should be documented.  (Perhaps that's worth a warning or even making -R required.)

**Comment by herbelin** [comment]
> At the least the doc should mention that coq_makefile --help shows all the options.

That'll be nice indeed.

> This line in the help output seems outdated (what about mlgs? are ml4s still accepted?): [file.ml[i4]?]: Objective Caml file to be compiled

This was fixed in e29a479c.

> The fact that coqc will use -R . Top as the default should be documented. (Perhaps that's worth a warning or even making -R required.)

I would slightly lean for the first option. I'd be curious about user opinions (I'm afraid beginners would find strange that it does not work as simply as just passing the file to compile, at least in a first step).

**Comment by Zimmi48** [comment]
> > 
> 
> I would slightly lean for the first option. I'd be curious about user opinions (I'm afraid beginners would find strange that it does not work as simply as just passing the file to compile, at least in a first step).

A warning would be already an improvement on today's situation which is that a lot of beginners think that using a coq_makefile-generate makefile is just like calling `coqc` manually but do not realize that they need to pass a `-R` option to `coqc`, which leads them to "Inconsistent" errors. But warnings can be ignored, whereas an error would force users to realize the need for this option and its consequences.
