### ISSUE TITLE
Anomaly "Uncaught exception Constr.DestKO." in "induction ... using ..."

### ISSUE THREAD

**Issue by wilcoxjay** [coq/coq#12045]
#### Description of the problem

I get `Error: Anomaly "Uncaught exception Constr.DestKO."` on the following code.

```
Lemma foo :
  forall (P : nat -> Prop),
    (forall n, P (S n)) ->
    forall n,
      (fun e => 
         IsSucc e ->
         P e) n.
Proof.
Admitted.

Theorem bar : forall n,
    IsSucc n ->
    True.
Proof.
  intros.
  induction n using foo.
```

I assume this is because the strange/malformed shape of `foo` not what the induction tactic expects. So the expected behavior would be a non-Anomaly error message about "not recognizing an induction scheme", or whatever.

#### Coq Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.11.0 (April 2020)
compiled on Apr 7 2020 3:48:34 with OCaml 4.09.1
```

I am running macOS 10.15.

**Comment by herbelin** [comment]
Should be fixed by #12116. Thanks for reporting!
