### ISSUE TITLE
Improve "Print LoadPath" output 

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12061]
I expected that `Print LoadPath` would help users, particularly newcomers, to understand how the loadpath is set up.  In particular, I'd like to see each of the logical name roots identified, and preferably shown in the form of the `-Q ...` and `-R ...` options that are used on the command line and in _CoqProject.

In addition, the doc for the `Require` command says "If several files match, one of them is picked in an unspecified fashion."  I expected `Print LoadPath` would give help the user understand what file is chosen.  And I think it's unreasonable to say it's unspecified when it is AFAIK neither indeterminant or operating-system dependent; it seems an important detail users will want to understand

https://github.com/coq/coq/pull/11961#discussion_r405202034 points out 1) that the reverse-alphabetic ordering of items is strange and 2) that the listing includes things that are not modules (e.g. firstorder) as well as some `Locate` anomalies.

What should we do?

**Comment by ejgallego** [comment]
On the contrary I think users should never ever have to look at low-level, implementation-dependent stuff such as `LoadPaths`. Things should just work for them once they have listed their deps on the package definition file.

**Comment by jfehrle** [comment]
I agree.  In practice beginners often have trouble with loadpaths, which are not covered so clearly in the doc.  Would you remove the command entirely?

If we have `Add LoadPath` it makes sense to have a `Print LoadPath` even if it's not frequently used (and if we discourage `Add LoadPath`.  IMHO the command as it is somewhat broken.  I'm suggesting small incremental improvements.

Not to mention the statement for `Require`.

**Comment by ejgallego** [comment]
Indeed I think `Add LoadPath` should be removed, it is mostly deprecated. We didn't push for removing it yet as we had no need in terms of support, but I'm pretty sure at some point in the evolution of the library handling code we will indeed remove it.

> Not to mention the statement for `Require`.

What problems do you see with `Require`? Plans in this sense mostly are to deprecate the form that doesn't use `From pkg Require mod.` I know of no other medium-term plans at that level [partial imports maybe, but that is happening at a different level of the system]

**Comment by ejgallego** [comment]
> In practice beginners often have trouble with loadpaths, which are not covered so clearly in the doc.

In my view that's an user interface / build system issue. We have some improvements in the immediate roadmap [such as `dune coqtop`] that should help; the medium plan is more unclear as it depends on a large refactoring to properly support a document server.

**Comment by jfehrle** [comment]
> What problems do you see with Require?

What I said at the top:

In addition, the doc for the Require command says "If several files match, one of them is picked in an unspecified fashion." ... I think it's unreasonable to say it's unspecified when it is AFAIK neither indeterminant or operating-system dependent; it seems an important detail users will want to understand".  I'm expecting it can be described rather than a code change.

"unspecified" doesn't apply to `From ... Require` because it's always fully qualified??

Seems like eventually removing `Require` will force almost everyone to change their code.  Seems that won't be possible for quite a while.  Also, I see 1600+ uses of `Require` in the .v file but only 7 `From ... Require`--not showing best practices.  (An automatic conversion would be nice for this.)

**Comment by ejgallego** [comment]
> In addition, the doc for the Require command says "If several files match, one of them is picked in an unspecified fashion." ... I think it's unreasonable to say it's unspecified when it is AFAIK neither indeterminant or operating-system dependent; it seems an important detail users will want to understand". I'm expecting it can be described rather than a code change.
> 
> "unspecified" doesn't apply to `From ... Require` because it's always fully qualified??

I see, sorry; I got confused as this is not a problem of `Require` per-se , but of the loadpath infrastructure [of which require is a client]

The plan w.r.t. ambiguity is to make it into a hard error; a few details are still missing, but it is likely that it will first require we install libs outside a common root.

**Comment by ejgallego** [comment]
> Also, I see 1600+ uses of `Require` in the .v files but only 7

Note that we will make `Require Foo` mean `From current_pkg Require ...` [so if you rename your pkg you don't have to rename everything]

So indeed the change won't be so big, but external projects will indeed have to start using `From Coq ...` or `From Stdlib1 ...` etc....

**Comment by Zimmi48** [comment]
> Plans in this sense mostly are to deprecate the form that doesn't use `From pkg Require mod.`

> Note that we will make `Require Foo` mean `From current_pkg Require ...` [so if you rename your pkg you don't have to rename everything]

Indeed, this seems more like the latter: force people to use `From ... Require` except when loading from one's own namespace.

> "unspecified" doesn't apply to `From ... Require` because it's always fully qualified??

It does apply, but only if the library author created several files of the same name in their library (e.g. `A/Foo.v` and `B/Foo.v`). At some point, build systems should raise an error if that's the case. Actually, @ejgallego, what about having Dune enforce this now?

**Comment by ejgallego** [comment]
> At some point, build systems should raise an error if that's the case. Actually, @ejgallego, what about having Dune enforce this now?

That's on the roadmap , but still would be incompatible with some developments; IMHO we want even to add this check to Coq first, once we refactor the loadpath code.

**Comment by Zimmi48** [comment]
> still would be incompatible with some developments

Does not seem like a blocker to me.

**Comment by ejgallego** [comment]
> Does not seem like a blocker to me.

Indeed; Dune is not the right place to address this maybe, in the sense that having a module `A/B.v` and `B/B.v` is not an error per-se, but using the wrong `From` form is. So this needs to be handled first at the loadpath code level which is not cost-effective to do until the library is made common, which is not effective to do until we phase the make system out and remove the complex bootstrap procedure.

**Comment by Zimmi48** [comment]
> having a module `A/B.v` and `B/B.v` is not an error per-se

But we could decide that it becomes one. It would make the logic much simpler.

**Comment by ejgallego** [comment]
> But we could decide that it becomes one. It would make the logic much simpler.

It seems like quite a strong usability restriction to me, and unlikely to work at all in large libraries. Even worse, with the current global namespace that would mean module names have to be unique across all Coq developments.

**Comment by jfehrle** [comment]
I think checking at compile time is not going to be that useful.  We should move toward reporting a run time error when a `Require` is ambiguous.  It might also be helpful to have command that identifies ambiguous names given the current load path.

If you have 2 library source trees compiled separately, they may reuse a name but separate compiles could not detect that if there's no mutual dependency.  (Reusing names within a source tree may even be reasonable at times, e.g. using names `V1.Nat` and `V2.Nat` while you're developing V2).

The other consideration is whether the loadpath is interpreted statically (Coq looks for .vo files only when the loadpath is altered) or dynamically (e.g. another process adds a .v and compiles it and Coq discovers this automatically or some command rescans the loadpath directories).  This is like my IDE (and maybe emacs?) - whenever my IDE regains focus in the GUI, it scans for updated files.

**Comment by jfehrle** [comment]
PS Also, a standard loadpath mechanism to make the loadpath ordered and load the first matching name (and only report an error if it's ambiguous within a single loadpath directory).

**Comment by SkySkimmer** [comment]
ambiguous Require is an error since https://github.com/coq/coq/pull/14718
