### ISSUE TITLE
Bad naming convention for Obligation

### ISSUE THREAD

**Issue by bgregoir** [coq/coq#12080]
#### Description of the problem
The name of an obligation for function `foo` defined by `Program Fixpoint` is `foo_func`
This is crazy, since if you change the extension it will break theories.

Furthermore, if I define a function named `foo`, using program, I prefer to write
```coq
Next Obligation foo
```
and not
```coq
Next Obligation foo_func
```

**Comment by ejgallego** [comment]
Hi @bgregoir , not sure what you mean here; `foo_func` is the helper function when using `measure` and indeed doesn't have the same type than `foo`. Could you provide an actual example of how you would like things to work?

**Comment by ejgallego** [comment]
Closing due to lack of feedback, please reopen with more info.
