### ISSUE TITLE
named lemmas + Save

### ISSUE THREAD

**Issue by llelf** [coq/coq#12098]
#### Description of the problem

Docs:
>This  command can only be used if the original goal  was opened using the `Goal` command. 

8.11.0:
```coq
Example foo:True. trivial. Fail Save bar.
(* The command has indeed failed with message: *)
(* This command can only be used for unnamed theorem. *)
```

master:
```coq
Example foo:True. trivial. Save bar.
Fail Check foo. Check bar.
```

#### Coq Version

master(459faeddd095789affa30e7cf3b59fdaf95c1a0f)

**Comment by ejgallego** [comment]
Thanks for the report @llelf , we have allowed this as it costs little, but indeed we could also easily make this an error, or correct the doc. I dunno what others think.

**Comment by Zimmi48** [comment]
I think that the restriction was not very interesting in the first place. You could use `Save` with other things than `Goal`, but provided you named your theorem `Unnamed_thm`.

```coq
Lemma Unnamed_thm : True. easy. Save bar.
```

OTOH, with this change, the following becomes possible whereas it was not the case before.

```coq
Class foo := { n : nat }.
Instance : foo. split. exact 0. Save bar.
```

So this seems like an improvement to me and this becomes a documentation issue.

The future (in line with [CEP#42](https://github.com/coq/ceps/pull/42)) will probably be to allow unnamed theorems with `Theorem :` (like `Instance :`), deprecate `Goal` in favor of such forms, and have `Save` enforce that the name is the one provided in the beginning unless it was not.
