### ISSUE TITLE
Add a helper to Ltac2 to export an identifier inside a binder

### ISSUE THREAD

**Issue by tchajed** [coq/coq#12095]
#### Description of the problem
Due to #11607, it's impossible to create a binder with code that is compatible with both Coq v8.11 and Coq v8.12+alpha. My only use case for this API was to create a lambda with a specific identifier as the binder for passing an identifier from Ltac2 to Ltac1,

I propose adding this helper function to the Ltac2 standard library so it can be released in Coq 8.11.2 and solve this problem. Without this, I can't actually use the Ltac2-based Iris [string-ident](https://gitlab.mpi-sws.org/iris/string-ident) plugin for my main research.

Here's the code involved. The name is open to discussion.

Coq 8.11:
```
  Ltac2 ident_to_lambda id :=
    U.make (U.Lambda ({ Constr.binder_name := Some id;
                        Constr.binder_relevance := Constr.Relevant; })
                     'unit (U.make (U.Rel 1))).
```

Coq 8.12+alpha:
```
  Ltac2 ident_to_lambda id := U.make (U.Lambda (Constr.Binder.make (Some id) 'unit) (U.make (U.Rel 1))).
```

I think this should go in `user-contrib/Ltac2/Ltac1.v`, since its main use case is to pass an identifier to Ltac1 as a constr. To pass the identifier the user calls `let x := ident_to_lambda id in exact $x`.  To retrieve the identifier from an Ltac1 tactic `t` that uses `ident_to_lambda`, the user just has to do

```
let x := constr:(ltac:(t)) in
match x with
| (fun (name:_) => _) => (* use name *)
end
```

#### Coq Version

8.11 and 8.12+alpha

**Comment by JasonGross** [comment]
Is there a reason not to have two different files, and select which one to use based on the version of Coq?

(Is there even going to be an 8.11.2?)

An alternative to this could be making the Compat811 file define a version of Lambda and the relevance stuff that ignores the relevance and shadows the 8.12 version.  Then you could just `Require Import Coq.Compat.Coq811` in both versions

**Comment by tchajed** [comment]
Ok, I just implemented this in our Makefile and it does work, so that definitely solves my problem in the short term.

**Comment by tchajed** [comment]
Closing since this doesn't really need attention. Thanks for pushing me to just implement that solution @JasonGross!
