### ISSUE TITLE
"About" command reports 2 arguments when there are really 4

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12105]
`About ex_intro` reports that `ex_intro` has 2 arguments (one merely `_`) on the "Arguments" line of the output even though the definition has 4 (A, P, x and y).  But `Arguments ... assert` requires all 4 arguments, after which `About` also shows 4 arguments.

```
> About ex_intro.
ex_intro : forall (A : Type) (P : A -> Prop) (x : A), P x -> exists y, P y

ex_intro is not universe polymorphic
Arguments ex_intro [A]%type_scope _%function_scope
Expands to: Constructor Coq.Init.Logic.ex_intro

> Arguments ex_intro A P x y:assert.
> About ex_intro.
ex_intro : forall (A : Type) (P : A -> Prop) (x : A), P x -> exists y, P y

ex_intro is not universe polymorphic
Arguments ex_intro [A]%type_scope P%function_scope x y : rename
Expands to: Constructor Coq.Init.Logic.ex_intro
```

**Comment by Zimmi48** [comment]
It seems that `Arguments ... : assert` has the same effect as `Arguments ... : rename` excepts that it checks that the names of arguments have not changed.

`Arguments` can be used with a prefix of the argument lists, so the syntax shown in the first `About` is correct, but probably a little confusing.

**Comment by jfehrle** [comment]
Sounds like a rationalization.  One would expect the output to show full information on the arguments rather than an `Arguments` command with incomplete information.  And the `_` seems pretty bogus as well.  In my opinion.

**Comment by SkySkimmer** [comment]
Fixed I forgot when
