### ISSUE TITLE
HoTT's CI doesn't build enough to use install-devfiles

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12115]
#### Description of the problem

```
install: cannot stat 'plugins/syntax/float_syntax_plugin.cmi': No such file or directory
install: cannot stat 'plugins/derive/derive_plugin.cmi': No such file or directory
install: cannot stat 'plugins/ssrmatching/ssrmatching_plugin.cmi': No such file or directory
install: cannot stat 'plugins/ssr/ssreflect_plugin.cmi': No such file or directory
install: cannot stat 'user-contrib/Ltac2/ltac2_plugin.cmi': No such file or directory
install: cannot stat 'plugins/micromega/zify_plugin.cmi': No such file or directory
Makefile.install:104: recipe for target 'install-devfiles' failed
```
See https://github.com/HoTT/HoTT/pull/1312/checks?check_run_id=596263545

This is a recent regression in Coq master, which breaks the ability of HoTT's CI to build against master.  Please fix, or advise us on how to fix HoTT's build (ideally without needing to build and install all of the Coq stdlib).

#### Coq Version

master (probably f3af9a4c6e6813f32dfe632209e145ffbf5fed98 )

**Comment by JasonGross** [comment]
Note that we are running
```
make states tools coqlight plugins || exit $?
touch bin/coqtop.byte bin/coqchk stm/{proof,tac,query}workertop.cma
sudo make install-binaries install-devfiles
```

**Comment by SkySkimmer** [comment]
`plugins` is not a real target (it doesn't complain because the directory exists)
I guess you want `pluginsopt` instead

Or maybe just use `coqocaml`, I don't know why you build  `coqlight`

**Comment by JasonGross** [comment]
It is a regression, because `install-devfiles` works fine on 8.11.  But perhaps something changed when the contents of the `plugins` folder changed to no longer contain .v files?  In any case I am trying out `coqocaml` at HoTT/HoTT#1320

**Comment by SkySkimmer** [comment]
There is nothing saying that `install-devfiles` should work after some arbitrary selection of targets

**Comment by JasonGross** [comment]
Indeed, but I did not find a `devfiles` target, and was unsure what the relevant target was.
