### ISSUE TITLE
Extraction produces syntax-incorrect code

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#12127]
#### Description of the problem

The following code is extracted to syntax-invalid OCaml code:

```coq
Universe U0.

Module x.
  Inductive t' : Type@{U0} := .
End x.

Module z.
  Include x.
End z.

Require Import Extraction.
Extraction z.
```

Coq replaces inductive types without constructors in Type with `unit`, but also re-exports that type using an equation:

```ocaml
module Coq_x =
 struct
  type t' = unit (* empty inductive *)
 end

module Coq_z =
 struct
  type t' = Coq_x.t' = unit (* empty inductive *)

  (** val t'_rect : t' -> 'a1 **)

  let t'_rect _ =
    assert false (* absurd case *)

  (** val t'_rec : t' -> 'a1 **)

  let t'_rec _ =
    assert false (* absurd case *)
 end
```

`type t' = Coq_x.t' = unit` isn't valid syntax.

#### Coq Version

8.10.2

**Comment by herbelin** [comment]
Fixed in #15967 by requiring a version of OCaml that supports the syntax `type t' = |` for declaring an empty type.
