### ISSUE TITLE
Coq accepts } in nonsense places

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12138]
#### Description of the problem

The following files pass `coqc` fine:
```coq
}
```
```coq
} Check Set.
```
```coq
Existing Class True.
(* x *) } Existing Instance I.
```
```coq
(* x *) } Definition J := I.
```
I thought I had a file where it was not accepted, but cannot find an instance of it.

h/t @jadephilipoom for finding this

#### Coq Version

8.11.1

**Comment by Zimmi48** [comment]
Related to #12004.

**Comment by herbelin** [comment]
The regression appeared between 8.9 and 8.10.

**Comment by herbelin** [comment]
Seems to come from a8b3c907c which dropped the test checking that a proof state is defined.

**Comment by ejgallego** [comment]
> Seems to come from [a8b3c90](https://github.com/coq/coq/commit/a8b3c907cb2d6da16bdeea10b943552dc9efc0ed) which dropped the test checking that a proof state is defined.

This seems not intended indeed, @herbelin would you mind pointing out the place the check was done so I can try to provide a fix?

**Comment by herbelin** [comment]
> would you mind pointing out the place the check was done so I can try to provide a fix?

In `vernac_require_open_lemma` which was called by `modify_pstate`, both in `Vernacentries`.

**Comment by herbelin** [comment]
Maybe replacing the `Option.map` with `with_pstate` in `VtModify` could be enough (up to the changes that occurred afterwards).
