### ISSUE TITLE
Calling Ltac1 from Ltac2 with argument

### ISSUE THREAD

**Issue by bcip** [coq/coq#12153]
#### Description of the problem
I wrote the following code according to documentation, but it doesn't work.

```
Require Import Ltac2.Ltac2.

Ltac foo l :=
  ltac2:(l |- ()) l.
```

`Syntax error: '.' expected after [vernac:command] (in [vernac_aux]).`

#### Coq Version

The Coq Proof Assistant, version 8.11.0 (March 2020)
compiled on Mar 24 2020 12:42:57 with OCaml 4.06.0

**Comment by ppedrot** [comment]
This is due to limitations in the syntax of Ltac1. You can't write complex terms as the left-hand side of function applications, the only thing allowed is a reference. So you have to write `let f := ltac2:(l |- ()) in f l` instead.

**Comment by ppedrot** [comment]
This syntax is already documented in the refman, I think we can close this bug.
