### ISSUE TITLE
CoqIDE performs nonsensical syntax highlighting on messages

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#12169]
The following snippet shows the issue:
```
Goal forall (Notation : nat), tt = Notation.
```
This renders as:
![Screenshot_20200424_144034](https://user-images.githubusercontent.com/1202327/80213642-c7b4e380-8639-11ea-9948-eeddf73e322e.png)

Observe how `Notation` is now written in bold. This is because the syntax highlighter believes it is a vernacular keyword. This bug was not present in 8.11 and I believe that it was introduced by #12106.

cc @herbelin

**Comment by herbelin** [comment]
Caused by #12106 indeed. I think I've just been overzealous and applied not only the style scheme but the "language "and its highlighting rules to the message window. The fix shall be easy. Sorry.
