### ISSUE TITLE
Coq mixes up reporting "recursively defined" and "corecursively defined"

### ISSUE THREAD

**Issue by tchajed** [coq/coq#12177]
#### Description of the problem

These are backward:

```coq
CoInductive T: Type := mkT.
CoFixpoint corecursive (x:T) : T := x.
(* corecursive is defined
   corecursive is recursively defined *)
Fixpoint recursive (x:unit) : unit := x.
(* recursive is defined
   recursive is corecursively defined *)
```

Seems likely #11785 broke this in a refactor.

#### Coq Version

8.12+alpha

**Comment by ejgallego** [comment]
This happened in one of my cleanups, where the parameter was renamed from `cofix` to `isfix` at the request of a reviewer but I forgot to invert the logic here.
