### ISSUE TITLE
New Library.Faulty anomalies.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#12192]
#### Description of the problem

The Sphinx build is consistently failing *locally* for both @jfehrle and myself with the following error (I call Sphinx through `dune` and Jim does it through `make`):

```
reading sources... [ 49%] language/coq-library
Extension error:
/mnt/c/proj/coq2/doc/sphinx/language/coq-library.rst:899: Error while sending the following to coqtop:
    Require Import Reals.
  coqtop output:
    Toplevel input, characters 0-21:
    > Require Import Reals.
    > ^^^^^^^^^^^^^^^^^^^^^
    Error:
    Anomaly
    "Uncaught exception Library.Faulty("/mnt/c/proj/coq2/theories/ZArith/Zminmax.vo")."
    Please report at http://coq.inria.fr/bugs/.
```

Strangely enough, it succeeds in the CI.

Recently, @llelf reported on Gitter a similar problem when trying to build the dev version of the opam package on macOS:

https://gist.github.com/llelf/aece08801e5a13d8558053f3561d8838

The error is in another file:

```
# File "./theories/Reals/Rtrigo1.v", line 25, characters 0-27:
# Error:
# Anomaly
# "Uncaught exception Library.Faulty("/Users/lelf/.opam/cnr/.opam-switch/build/coq.dev/_build/default/theories/Logic/Classical_Pred_Type.vo")."
# Please report at http://coq.inria.fr/bugs/.
```

#### Coq Version

This is on an up-to-date master and is apparently a consequence of #12092 (that was merged two days ago).

**Comment by SkySkimmer** [comment]
I removed the catch at https://github.com/coq/coq/blob/25c7e0cb30a7e196a293df9620bc4b801eaafa27/vernac/library.ml#L67 and got `too many open files`
Indeed we `open_in_bin` but never close AFAICT...

Probably https://github.com/coq/coq/pull/12188 fixes the refman although we would still leak open files when accessing opaque tables. Will make a PR.

**Comment by jfehrle** [comment]
> Probably #12188 fixes the refman

Yes, it works now, thanks!

> Strangely enough, it succeeds in the CI.

The number of file handles per process will vary across environments (Windows, Ubuntu, and CI). 
I expect it's configurable in some flavors of Linux.
