### ISSUE TITLE
[micromega] lia does not understand Nat.le

### ISSUE THREAD

**Issue by olaure01** [coq/coq#12210]
#### Description of the problem

`lia` fails to solve goal with `Nat.le` while the corresponding one with `le` (i.e. `Peano.le`) is solved:
```coq
Require Import PeanoNat Lia.

Goal forall x, le x x.
Proof.
intros; lia.
Qed.

Goal forall x, Nat.le x x.
Proof.
intros.
Fail lia.
unfold Nat.le; lia.
Qed.

Goal forall x, Nat.le x x.
Proof. reflexivity. Qed.
```

#### Coq Version

at least from Coq 8.9.1 to master

**Comment by olaure01** [comment]
@fajb

**Comment by fajb** [comment]
Thanks for the report.
The problem is that Nat.le, Nat.lt and Nat.eq are aliased to le, lt and (eq nat).
That should be easy to fix.
