### ISSUE TITLE
[ci] [overlays] name inconsistencies for ci in scripts

### ISSUE THREAD

**Issue by olaure01** [coq/coq#12215]
Names of ci used in [ci-basic-overlay.sh](https://github.com/coq/coq/blob/master/dev/ci/ci-basic-overlay.sh) and in [Makefile.ci](https://github.com/coq/coq/blob/master/Makefile.ci) are not consistent with respect to "-" or "_" and with respect to capitalization.
This generates problems in particular when using [create_overlays.sh](https://github.com/coq/coq/blob/master/dev/tools/create_overlays.sh):

- `./dev/tools/create_overlays.sh author 99999 Corn` fails because rule `ci-Corn` is not found
- `./dev/tools/create_overlays.sh author 99999 corn` fails because directory `corn` is not found

(same with `ext_lib` and `ext-lib`).

**Comment by ejgallego** [comment]
Yes, this is a problem,sorry about that; feel absolutely free to provide a patch.

**Comment by olaure01** [comment]
I am working on it and will submit a PR proposal as soon as possible.
Not easy to find all needed modifications but I'll do my best.

**Comment by ejgallego** [comment]
> I am working on it and will submit a PR proposal as soon as possible.
> Not easy to find all needed modifications but I'll do my best.

Indeed, what I've been doing is to fix the problematic ones as I find them.
