### ISSUE TITLE
"implementation mismatch on" should be documented in the reference manual

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12232]
#### Description of the problem

Consider the error message
```
COQC src/Rewriter/Util/plugins/StrategyTactic.v
File "./src/Rewriter/Util/plugins/StrategyTactic.v", line 1, characters 0-43:
Error: while loading
/home/fiat/plv/fiat-crypto/rewriter/src/Rewriter/Util/plugins/strategy_tactic_plugin.cmxs:
implementation mismatch on Stdlib__list
```
This is sort-of insructable.  It generally means that either (a) you forgot to recompile part of your OCaml dependency chain for your plugin (so that Coq is loading two different compiled files that are inconsistent), or, much more commonly, (b) that your version of OCaml is not the OCaml that compiled your version of Coq.

I think the ideal situation here would be that we can detect the latter kind of error and instead error with something like "OCaml version mismatch detected: Coq was compiled with OCaml version ...., but /home/fiat/plv/fiat-crypto/rewriter/src/Rewriter/Util/plugins/strategy_tactic_plugin.cmxs was compiled with OCaml version ..."

Either way, I think these error messages should be documented in the reference manual, which currently [gives only one result](https://coq.inria.fr/distrib/current/refman/search.html?q=implementation+mismatch+on&check_keywords=yes&area=default#) for "implementation mismatch on", and highlighting "If a mismatch occurs between the expected type of a pattern and its actual type, a coercion made from constructors is sought"

#### Coq Version

8.11.1

**Comment by ejgallego** [comment]
I think this rather means c) your packaging / build system is broken.

**Comment by JasonGross** [comment]
No, this can easily happen if you upgrade ocaml without upgrading manually installed versions of Coq, or if you are running from absolute paths without doing `opam switch`, or you forgot to run `eval $(opam env)`

**Comment by ejgallego** [comment]
> No, this can easily happen if you upgrade ocaml without upgrading manually installed versions of Coq, or if you are running from absolute paths without doing `opam switch`, or you forgot to run `eval $(opam env)`

Which means "c) your packaging system is broken"

**Comment by JasonGross** [comment]
Okay, sure, but I think error messages should be resilient to common failure modes in packaging systems.

**Comment by andres-erbsen** [comment]
To put it the other way, perhaps package systems would do a better job here if the need for rebuilding coq every time ocaml is rebuilt was documented :). Not everyone has given up on being able to upgrade a highly-depended-on package without replacing everything downstream. I don't think that decision by itself qualifies as broken, it's just a different trade-off between cost of updates on the user and default levels of engineering sanity (and often effort) expected from the software being packaged. And it seems entirely plausible to me that Coq package maintainers, while overall qualified for the task, have just never happened to run into this issue. Yes, one could guess that plugins are ocaml under the hood and thus likely need coq to match to compiler version, but the point of documentation is to let people get things right without guessing.

**Comment by Zimmi48** [comment]
The specific error message should not be documented since it is not a Coq error message but rather an OCaml one. However, it makes sense to answer the request of @andres-erbsen, and for this reason I opened #12243. Let me know what you think.

**Comment by ejgallego** [comment]
I dunno, the message is a bit incomplete in the sense that not only the OCaml version has to be the same, but depending libraries, etc...

**Comment by JasonGross** [comment]
> I think this rather means c) your packaging / build system is broken.

@ejgallego I hit a variant of this in Coq's CI (https://github.com/coq/coq/issues/12400); is the CI build system broken?

**Comment by ejgallego** [comment]
> @ejgallego I hit a variant of this in Coq's CI (#12400); is the CI build system broken?

No idea, here we have 3 build systems involved, the one in Coq's kernel, fiat-crypto's, and CI. One of them is doing something wrong indeed.

**Comment by JasonGross** [comment]
It's not fiat-crypto's, I'm pretty sure; we're just compiling a Coq file that issues a call to `Eval native_compute`.  I suspect there's a fourth "build system" that you're missing here, which is the CI setup
