### ISSUE TITLE
dune stdlib-html doesn't classify identifiers (missing globs?)

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#12230]
Compare https://coq.inria.fr/library/Coq.Lists.List.html https://coq.gitlab.io/-/coq/-/jobs/534823036/artifacts/_build/default/doc/stdlib/html/Coq.Lists.List.html
![screen](https://user-images.githubusercontent.com/2461932/80861867-92c81280-8c71-11ea-98b3-f17ccf8748f3.png)
For instance the color of `hd` in `Definition hd` or `list` in `l:list A`.

**Comment by ejgallego** [comment]
I think this should be solved, need someone to check.

**Comment by Alizter** [comment]
Seems to be OK:
- https://coq.inria.fr/library/Coq.Lists.List.html
- https://coq.gitlab.io/-/coq/-/jobs/2517075772/artifacts/_install_ci/share/doc/coq/html/stdlib/Coq.Lists.List.html
