### ISSUE TITLE
including autosave functionality in coqide

### ISSUE THREAD

**Issue by GrandGarcon** [coq/coq#12242]
#### Description of the problem

just simple request , as i had been working on seriving a large inductive  theorem and was working blood and sweat  for 6 hours and  forgot to  save the  project and unfortunately the  computer crashed . so just in case there wil be autosaving after , lets say 30 mins , that will be great .
thank you.
#### Coq Version
CoqIDE

**Comment by Zimmi48** [comment]
I doubt that any of the CoqIDE maintainers will ever implement such a feature, but of course, pull requests are welcome!

**Comment by herbelin** [comment]
Hi @GrandGarcon, there is actually an autosave feature. See the `Files` tab in the preferences. It is turned on by default with a 10s delay, so you may actually have a file called `#foo.v#` in your directory (assuming your file was called `foo.v`).

**Comment by Zimmi48** [comment]
OK, I didn't know this :stuck_out_tongue_closed_eyes:
