### ISSUE TITLE
[dune] plugins & merlin

### ISSUE THREAD

**Issue by gares** [coq/coq#12248]
I"m having troubles developing ssr with dune:

![Screenshot from 2020-05-04 14-07-46](https://user-images.githubusercontent.com/1013846/80964212-bd9c9d00-8e10-11ea-87cb-26f0aa4c2fdf.png)

Help!

**Comment by ejgallego** [comment]
Can't reproduce in emacs, seems VSCode specific? Did you run `make -f Makefile.dune check` ?

**Comment by SkySkimmer** [comment]
Did you declare `tacMK_SSR_CONST` twice? ie in a mli (or module type)
~~~ocaml
val foo : unit
val foo : unit
~~~
The first `foo` triggers the unused value warning.
In master I see `tacMK_SSR_CONST` at line 470 but in your screenshot it's at line 239 so maybe you have it twice.

**Comment by gares** [comment]
I've exported it twice, damn. Thanks.
