### ISSUE TITLE
Should extracted Haskell code always be unambiguous?

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12258]
#### Description of the problem
I just got
```
    • Ambiguous type variable ‘a0’ arising from a use of ‘GHC.Base.==’
      prevents the constraint ‘(GHC.Base.Eq a0)’ from being solved.
      Probable fix: use a type annotation to specify what ‘a0’ should be.
      These potential instances exist:
        instance (GHC.Base.Eq b, GHC.Base.Eq a) =>
                 GHC.Base.Eq (Prelude.Either a b)
          -- Defined in ‘Data.Either’
        instance GHC.Base.Eq GHC.Base.Ordering -- Defined in ‘GHC.Classes’
        instance GHC.Base.Eq GHC.Base.TyCon -- Defined in ‘GHC.Classes’
        ...plus 24 others
        ...plus three instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the first argument of ‘unsafeCoerce’, namely ‘(GHC.Base.==)’
      In the expression: unsafeCoerce (GHC.Base.==)
      In a case alternative: String -> unsafeCoerce (GHC.Base.==)
```
In my code.  This is because of
https://github.com/coq/coq/blob/bc79d319d38f766a6b7bbeb1f1071b046642089b/theories/extraction/ExtrHaskellString.v#L42-L43

When `String.eqb` is used in a sufficiently polymorphic context that extraction wraps it in `unsafeCoerce`, then Haskell cannot resolve type classes.  The easy fix to this is to replace `"(Prelude.==)"` with `"((Prelude.==) :: Prelude.String -> Prelude.String -> Prelude.Bool)"` and insert similar type annotations for the other uses of `Prelude.==`.
This makes the extracted code a bit more ugly, but also makes it always typecheck.  This seems probably worth it to me.

cc @tchajed @zeldovich , the two Coq users I'm aware of who use Haskell extraction.  Thoughts on this?
cc also @letouzey 

#### Coq Version
8.11.1

**Comment by zeldovich** [comment]
Explicitly specifying the types for `(Prelude.==)` seems reasonable.

In this particular case, `ExtrHaskellString.v` does not force the use of `ExtrHaskellBasic.v`, so the result of `String.eqb` might not be `Prelude.Bool`.  So perhaps we should annotate as `((Prelude.==) :: Prelude.String -> Prelude.String -> _)`, or just import `ExtrHaskellBasic` in `ExtrHaskellString`.

**Comment by JasonGross** [comment]
`((Prelude.==) :: Prelude.String -> Prelude.String -> _)` gives
```
    • Found type wildcard ‘_’ standing for ‘GHC.Base.Bool’
      To use the inferred type, enable PartialTypeSignatures
    • In an expression type signature:
        GHC.Base.String -> GHC.Base.String -> _
      In the first argument of ‘unsafeCoerce’, namely
        ‘((GHC.Base.==) :: GHC.Base.String -> GHC.Base.String -> _)’
      In the expression:
        unsafeCoerce
          ((GHC.Base.==) :: GHC.Base.String -> GHC.Base.String -> _)
    • Relevant bindings include
        t :: Base1
          (bound at src/ExtractionHaskell/bedrock2_word_by_word_montgomery.hs:7270:17)
        base_interp_beq :: Base1
                           -> Base_interp -> Base_interp -> GHC.Base.Bool
          (bound at src/ExtractionHaskell/bedrock2_word_by_word_montgomery.hs:7270:1)
```
In any case, http://hackage.haskell.org/package/base-4.14.0.0/docs/Data-Eq.html seems to mandate that `(Prelude.==)` lands in `Prelude.Bool`, regardless of what `bool` is extracted to, and hence the extraction is ill-typed if it's expected to land in anything other than`Prelude.Bool`.  I reported this as https://github.com/coq/coq/issues/12257, and will prepare a pull request to fix both.
