### ISSUE TITLE
Errors when running test suite with recent Dune.

### ISSUE THREAD

**Issue by kindaro** [coq/coq#12264]
## Description of the problem

When `dune runtest`, [build errors appear][log]. Some of them can be solved by [a few `chmod` invocations][patch]. [Other errors are then reached][log2] for which I have not found a solution. Test suite therefore fails.

[log]: https://gist.github.com/kindaro/d284b4e8bcc76aaefaba192ad2f3f371#file-dune-log
[patch]: https://gist.github.com/kindaro/d284b4e8bcc76aaefaba192ad2f3f371#file-fix-diff
[log2]: https://gist.github.com/kindaro/d284b4e8bcc76aaefaba192ad2f3f371#file-dune-2-log

My suspicion is that [the upgrade of _dune_][dune] has something to do with this.

[dune]: https://github.com/coq/coq/commit/bc411fa4d8c04424c579d506dd0507cb83db7bc7

#### Coq Version

    The Coq Proof Assistant, version 8.12+alpha (May 2020)
    compiled on May 6 2020 4:32:32 with OCaml 4.09.0

#### Dune Version

    2.5.0
    2.5.1

#### Make Version

    GNU Make 4.3
    Built for x86_64-pc-linux-gnu

#### CSDP Version

    Name            : coin-or-csdp
    Version         : 6.2.0-3
    Description     : A C library for Semidefinite Programming
    Architecture    : x86_64

_(On Arch Linux.)_

**Comment by ejgallego** [comment]
> My suspicion is that [the upgrade of _dune_](https://github.com/coq/coq/commit/bc411fa4d8c04424c579d506dd0507cb83db7bc7) has something to do with this.

You are correct, after https://github.com/ocaml/dune/pull/3092 and our bumping of `(lang dune)` to 2.5, source files will be copied to the build directory in read-only mode. Thus, the workflow of:
```
  cp orig_file.ml new_file.ml
  echo "foo" >> new_file.ml
```
is going to fail now with a permission error [if that was implemented as a dune rule it would work tho]

There are two things to do here:
- determine why this doesn't fail in the the test-suite in CI; this seems very bizarre; 
- determine what is the best fix for the 3 use cases that copy a file then append (chmod may be fine, other options work.

WDYT @SkySkimmer ?

**Comment by SkySkimmer** [comment]
Maybe we could `cat orig > new` instead of cp

**Comment by SkySkimmer** [comment]
Or `cp --no-preserve=mode` but not sure if that's available on nongnu

**Comment by ejgallego** [comment]
I think that `cp` + `chmod` is the safest choice for now; cp should ensure that we don't have a hardlink anymore, indeed I'm concerned about nongnu.

**Comment by ejgallego** [comment]
Let's get this fixed for the beta.
