### ISSUE TITLE
"deprecated" attribute for Lemmas.

### ISSUE THREAD

**Issue by vzaliva** [coq/coq#12266]
Feature Request: It would be nice to be able to mark some lemmas as "deprecated" so compilation warning will be issued when they are used. There’s the deprecated attribute 3, but it doesn’t work for Lemmas.

There are workarounds (via Notation) but they look rather clumsy to me.
Related discussion: https://coq.discourse.group/t/deprecated/814

**Comment by olaure01** [comment]
Being able to mark full files as deprecated in such a way that requiring them would generate a warning would be nice as well.

**Comment by Zimmi48** [comment]
> Being able to mark full files as deprecated in such a way that requiring them would generate a warning would be nice as well.

Agreed. However, while adding support for the `deprecated` attribute to the - `Definition` command is rather straightforward, deprecating a entire file requires some more design.

Indeed, at the current time, attributes can be attached to a command (from the outside). In the case of the `polymorphic` attribute on the `Section` command, the change is for the whole section. We could add support for the `deprecated` attribute on the `Module` command, but this would only allow deprecating an internal module. However given that library files implicitly declare modules, there is no way to attach an attribute to it.

We could consider two options (that I can see):
- a new optional command to start a library file, to which we could attach attributes (this would be reminiscent of languages like Haskell, where such command is compulsory)
- a new syntax to attach an attribute from the inside (but I'm not convinced by this option if this is the only use case).

Alternatively, a third option should be to not use an attribute in this case but rather a dedicated `Deprecated.` command whose goal is to trigger a warning when the library file is `Require`-d (non-transitively).

**Comment by maximedenes** [comment]
> Being able to mark full files as deprecated in such a way that requiring them would generate a warning would be nice as well.

See #8032.

**Comment by maximedenes** [comment]
I'll have a look at it.
