### ISSUE TITLE
coqdoc script injection vulnerability

### ISSUE THREAD

**Issue by randomdross** [coq/coq#12265]
#### Description of the problem

I renamed the [links.v test](https://github.com/coq/coq/blob/master/test-suite/coqdoc/links.v) to:
`links<iframe src='javascript:alert(1);'>Evil.v`

Running coqdoc on this file results in injection into the generated index.html:
`<a href="links<iframe src='javascript:alert(1);'>Evil.html">links<iframe src='javascript:alert(1);'>Evil</a> [library]<br/>`

There's some escaping happening [here](https://github.com/coq/coq/blob/master/tools/coqdoc/output.ml) where the markup appears to be generated, however it doesn't seem to apply everywhere it should.

I'm testing on coqdoc version 8.9.0 so it's possible something has changed since the latest version, but I'm still seeing [mostly the same code in `format_global_index`](https://github.com/coq/coq/blob/master/tools/coqdoc/output.ml#L850) so I think likely this works in the latest release as well.

#### Coq Version

8.9.0

index.html contains:
![iframe](https://user-images.githubusercontent.com/1694025/81140745-5c172400-8f1f-11ea-9dab-ade711c77bd8.JPG)

**Comment by herbelin** [comment]
@randomdross: Thanks for signalling this kind of issue.

PR #12277 is now forbidding filenames which are not legal Coq identifiers. This of course include a name such as `links<iframe src='javascript:alert(1);'>Evil.v`.

Do you see other kinds of vulnerability which we should prevent?

**Comment by randomdross** [comment]
I'd just poke around to try to determine:
1)  Where else is generating markup based on untrusted input, which may not go through encoding / sanitization.
2)  If the encoding sanitization in each instance is appropriate for the context into which injection is happening in markup.  (E.g.: In the context of an anchor href, javascript:alert(1) would execute script. 
 In the context of HTML markup, a javascript URL wouldn't work but a script tag would.)
3)  If the encoding / sanitization is sufficient for the context in which it's intended to operate.  (This is slightly different from 2 above.)

Looking at the source, I just picked the first example to demonstrate script execution.  I do suspect there are more issues in output.ml and I want to spend more time pinning some of them down if I can.

I've found it a pain to get up and running building coq from source.  It's understandably out of scope for this bug, but please let me know if you have a particular favorite & simple config, something like:
1)  Get set up with [a particular linux distro].
2)  Build this version of ocaml from [this place].
3)  git clone coq source and it should build fine after running ./configure.
...then I'll try to play around with this more and maybe find more bugs!

**Comment by JasonGross** [comment]
> It's understandably out of scope for this bug, but please let me know if you have a particular favorite & simple config, something like:

I generally use the latest LTS version of Ubuntu with opam installed via the instructions on https://opam.ocaml.org/doc/Install.html#Binary-distribution, and then install something like OCaml 4.07, and then `opam install num ocamlfind dune`, and then your clone/configure/build instructions should work fine.
