### ISSUE TITLE
GH actions to flag/close stale issues/PRs

### ISSUE THREAD

**Issue by gares** [coq/coq#12260]
I've just discovered this
  https://github.com/marketplace/actions/close-stale-issues

Just wondering what other devs think. I think we should at least flag stale PRs automatically.

**Comment by Zimmi48** [comment]
Before this action existed, there was also the very popular https://probot.github.io/apps/stale/ (same idea) but I'm pretty much against closing issues automatically (this is just moving dust under the carpet). Automatic labeling is certainly not as radical. It *might* be useful, but it is not clear to me in exactly what way.

My personal preference (which I haven't yet taken the time to implement) would be to have a clear definition of what it means for an issue to be triaged. Ideally, we could check the criteria automatically and use the `needs: triage` label for those who do not meet them.

Regarding stale PRs, my main concern is that we should more clearly distinguish between those that are waiting for an action of the author from those that are waiting for an action from someone else, and that the first category should not pollute people's review request lists.

**Comment by ppedrot** [comment]
From his original post, @gares original interest seems to have been PRs, not issues. Since coqbot now closes stale PRs after a while, I think we can close this issue.

**Comment by Zimmi48** [comment]
There was a related issue opened on the bot repo: https://github.com/coq/bot/issues/115
Should that issue be closed as well?
