### ISSUE TITLE
[contributing] Integrate Théo's remarks in the contributing guide.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#12274]
I think it would be a good idea to integrate Théo's remarks and advice on the contributing guide:

https://sympa.inria.fr/sympa/arc/coqdev/2020-03/msg00003.html

**Comment by Zimmi48** [comment]
Which ones?

**Comment by Alizter** [comment]
Is this now covered by the `coq/CODE_OF_CONDUCT.md `?

**Comment by Zimmi48** [comment]
Most of it was indeed already a reminder of things that were (already at that time) covered by the Code of Conduct. Maybe we can add a few words in addition to the reviewer section of the contributing guide about being extra careful when talking to new contributors. I'll open a PR.
