### ISSUE TITLE
[win] CoqIDE crash

### ISSUE THREAD

**Issue by gares** [coq/coq#12282]
While testing the installer produced by https://github.com/coq/coq/pull/12032 I found out that executing a sentence from the script window crashed coqidetop. Running the same sentence via the query windows works fine, so I suspect is some code specific to the script window, possibly gtksourceview.

![Screenshot from 2020-05-08 14-29-49](https://user-images.githubusercontent.com/1013846/81405959-f900d980-9138-11ea-81bc-b1ae2e0d4793.png)

**Comment by gares** [comment]
Note: I was running CoqIDE via wine.

**Comment by Zimmi48** [comment]
I couldn't reproduce on Windows 32 bits with Coq 8.11.1 nor Coq master.

**Comment by ejgallego** [comment]
I couldn't reproduce it either, let's postpone to 8.12

**Comment by Zimmi48** [comment]
@MSoegtropIMC Do you still plan to have a look at this for 8.12.0? Note that according to our testing, this issue seems hard to reproduce, and might be wine-specific. Therefore, it doesn't look very high priority to me.

**Comment by gares** [comment]
Btw, didn't the version of lablgtk change too? I seem to recall something like that.

**Comment by Zimmi48** [comment]
Yes, that's possible.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : it is on my "final test list" (probably done this week end). If it is not reproducible I will close this.

**Comment by SkySkimmer** [comment]
@MSoegtropIMC ping

**Comment by ejgallego** [comment]
Looks like not an issue otherwise we would have heard.

**Comment by MSoegtropIMC** [comment]
Yes, I think it is a Wine issue. I would say we close this.
