### ISSUE TITLE
Frequent failures of PDF manual build on Pyrolyse.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#12280]
I frequently see the following failure in the build of the PDF manual:

```
1210 Latexmk: Run number 1 of rule 'pdflatex'
1211 This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian) (preloaded format=xelatex)
1212  restricted \write18 enabled.
1213 entering extended mode
1214 Latexmk: Summary of warnings:
1215   Latex failed to resolve 930 reference(s)
1216   Latex failed to resolve 59 citation(s)
1217 Latexmk: Run number 1 of rule 'makeindex CoqRefMan.idx'
1218 Latexmk: calling xindy( -L english -C utf8 -M sphinx.xdy -I xelatex -q -o CoqRefMan.ind CoqRefMan.idx )
1219 Cannot map memory to address 0x8023d0894000 .
1220 [/build/clisp-u7VYrq/clisp-2.49.20170913/src/spvw_mmap.d:498] errno = 12 (Collected error summary (may duplicate other messages):
1221   makeindex CoqRefMan.idx: Command for 'makeindex CoqRefMan.idx' gave return code 1024
1222 Latexmk: Use the -f option to force complete processing,
1223  unless error was exceeding maximum runs of latex/pdflatex.
1224 Makefile:35: recipe for target 'CoqRefMan.pdf' failed
1225 make[1]: *** [CoqRefMan.pdf] Error 12
1226 make[1]: Leaving directory '/builds/coq/coq/_build/default/doc/refman-pdf'
1227 make: *** [refman-pdf] Error 1
1228 Makefile.dune:103: recipe for target 'refman-pdf' failed
```

(from https://gitlab.com/coq/coq/-/jobs/543104449)

I have always observed that the runner was pyrolyse when such error happened.

Note that the converse is not true, here is a job on pyrolyse that was successful: https://gitlab.com/coq/coq/-/jobs/541601113.

On the last 3000 jobs that ran, only 4 of them were PDF manual builds on pyrolyse. 3 out of 4 failed with this error.

**Comment by Zimmi48** [comment]
I wanted to work around this issue by excluding pyrolyse from running these jobs, but I cannot see a way to do this. In particular, tag exclusion does not seem to exist.

**Comment by ejgallego** [comment]
Certainly runners tags seem to be designed to expose features, so this use case (workaround for a buggy runner) seems not to fit.

I guess in the first place these failures do look worrying, and could signal some deeper problem with pyrolyse. Meanwhile, we can just modify the script and exit with true if `hostname` matches the buggy machine.

**Comment by Zimmi48** [comment]
Unfortunately, it can also happen on the make-based full refman build (HTML + PDF): https://gitlab.com/coq/coq/-/jobs/543727483
In this case we could limit the build to HTML only?

**Comment by ejgallego** [comment]
Or add the same hack there? The hack is far from nice tho...

**Comment by Zimmi48** [comment]
Yeah, I meant, use a similar hack but instead of succeeding immediately still run the HTML build.

**Comment by ejgallego** [comment]
Sounds OK to me; let's see if I can put some cycles to investigate pyrolise tho.

**Comment by SkySkimmer** [comment]
See also https://github.com/sphinx-doc/sphinx/issues/7015 ?

**Comment by Zimmi48** [comment]
@cpitclaudel Do you know why we need xindy?

@ejgallego A softer version of your hack would be to only disable xindy when the runner is pyrolyse.

**Comment by ejgallego** [comment]
> @ejgallego A softer version of your hack would be to only disable xindy when the runner is pyrolyse.

That would be great.

**Comment by cpitclaudel** [comment]
> @cpitclaudel Do you know why we need xindy?

Not really; we use it because Sphinx uses it by default.  Do you want me to investigate?

**Comment by Zimmi48** [comment]
If you have some time to spare, that would be great. Removing a dependency and fixing a spurious failure at the same time would be a bliss.

**Comment by jfehrle** [comment]
Just a shot in the dark: Pyrolyse is an 8 core machine and I see NJOBS=2 (and AFAICT native Linux, not on Windows at all), whereas IIUC most of the build machines are single-core.  Perhaps there's some synchronization problem that only shows up for this parallel case?

**Comment by jfehrle** [comment]
> See also sphinx-doc/sphinx#7015 ?

Yeah, dropping xindy lets build the pdf on Windows/WSL.
