### ISSUE TITLE
Ltac2 eintros is dead code, because views aren't supported yet

### ISSUE THREAD

**Issue by Blaisorblade** [coq/coq#12292]
@kyoDralliam writes in #12235:
> It would be great to add a test case [for `eintros`], however I don't see how to that without a view (as you wrote in gitter), and looking at the ltac2 implementation, those are not supported yet as intropatterns...

I figured this might warrant an issue.
EDIT: concretely, whoever implements views should make sure to add a test for where `eintros Hfoo%lemma` succeeds and creates evars and `intros Hfoo%lemma` fails (see explanation below).

**Comment by jfehrle** [comment]
Are you referring to SSR views?  And why are views needed?  Perhaps you could elaborate--the double indirection (to #12235 and then to gitter) doesn't help.  I didn't understand what you're referring to.

**Comment by Blaisorblade** [comment]
Something like SSR views is indeed involved, tho I don’t know the correct name. Below’s my understanding, tho I’m sure there’s mistakes.

With goal `A → B`, and a lemma `mylemma args: A → C`, ssreflect call `move ⇒ /mylemma Hfoo` can also be written `intros Hfoo%mylemma` (with similar but not identical semantics) — that applies lemma `mylemma` to an hypothesis of type `A`, and introduces the result of type `C` In the context with name `Hfoo`.

However, maybe applying `mylemma` creates evars, because some of the arguments `args` can’t be inferred from `A`. In that case, `intros Hfoo%mylemma`, but replacing `intros` by `eintros` should succeed — but I’ve never actually tried!

To conclude, views seem needed to test `eintros`, unless there is _another_ introduction pattern that can create evars.
