### ISSUE TITLE
CI for SF broken

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#12290]
Looks like the api call returns `[]` since about 15h ago (https://gitlab.com/coq/coq/-/jobs/545458364 is the oldest failing job)
Maybe because we fetch some old job which I guess got cleaned up.
cc @maximedenes @ejgallego

**Comment by Zimmi48** [comment]
It's the biannual SF failing when the next release is approaching joke :laughing:

**Comment by ejgallego** [comment]
We need to write to Benjamin so somebody sends us a link to a valid artifact, not a big job I think.

**Comment by Zimmi48** [comment]
>We need to write to Benjamin so somebody sends us a link to a valid artifact, not a big job I think.

Maybe a simple GitHub ping will be enough... @bcpierce00

**Comment by ejgallego** [comment]
> Maybe a simple GitHub ping will be enough

I think mail is better in this case as a link has to be sent, maybe not by Benjamin itself but by whoever is in charge of SF CI [and there could be some issue with tokens etc]

**Comment by bcpierce00** [comment]
Yishuai and I will take a look.

**Comment by liyishuai** [comment]
We've created a public repo for the latest source files: https://github.com/DeepSpec/sf
You can also donwload the tarballs via:
- https://deepspec.github.io/sf/lf-current/lf.tgz
- https://deepspec.github.io/sf/plf-current/plf.tgz
- https://deepspec.github.io/sf/vfa-current/vfa.tgz
- https://deepspec.github.io/sf/qc-current/qc.tgz
