### ISSUE TITLE
.. coqtop:: output regression

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#12305]
A recent PR (#12272) was intended to improve the `.. coqtop::` output. Unfortunately, between the first version of this PR (whose output I checked) and the one that was merged, a regression was introduced in the sentence splitting.
Compare the printing of the output in the example in the two links below:
- https://coq.gitlab.io/-/coq/-/jobs/542422443/artifacts/_install_ci/share/doc/coq/sphinx/html/proof-engine/vernacular-commands.html#coq:exn.module-section-qualid-not-found
- https://coq.gitlab.io/-/coq/-/jobs/544681807/artifacts/_install_ci/share/doc/coq/sphinx/html/proof-engine/vernacular-commands.html#coq:exn.module-section-qualid-not-found

In the second one nothing is split. All the outputs are at the end. Apparently, a double newline is necessary to have the sentences be split in the new version.

_Originally posted by @Zimmi48 in https://github.com/coq/coq/pull/12272#issuecomment-626387244_

Another example of bad output formatting was shown by @kyoDralliam: https://coq.gitlab.io/-/coq/-/jobs/548310062/artifacts/_install_ci/share/doc/coq/sphinx/html/proof-engine/ltac2.html#coq:cmd.ltac2-set

cc @mpu and @cpitclaudel

**Comment by mpu** [comment]
Hmm, the regex is wrong. I'd be of the opinion to do the simple more explicit thing and replace the call to `re.split` with my original loopy code.

**Comment by cpitclaudel** [comment]
Or just change `\s+` to `\s*`, no?

**Comment by mpu** [comment]
> Or just change `\s+` to `\s*`, no?

I tried that, but it drops sequences of newlines on the floor.

**Comment by cpitclaudel** [comment]
I'm happy with any strategy, but I think we should try to have a precise spec:

```python
import re

def split_lines(source):
    """Split Coq input in chunks
    A chunk is a minimal sequence of consecutive lines of the input that
    ends with a '.'

    >>> split_lines('A.\\nB.''')
    ['A.', 'B.']

    >>> split_lines('A.\\n\\nB.''')
    ['A.', '\\nB.']

    >>> split_lines('A.\\n\\nB.\\n''')
    ['A.', '\\nB.']
    """
    return re.split(r"(?<=(?<!\.)\.)\n", source.strip())
```

You can test that with `python -m doctest test.py`

**Comment by Zimmi48** [comment]
So, is the latest code shown by @cpitclaudel the one which should be integrated to fix the issue?

**Comment by Zimmi48** [comment]
ping @cpitclaudel: Do you want to open a PR with the code above?

**Comment by Zimmi48** [comment]
I tested the regexp proposed by @cpitclaudel but it doesn't seem to fix the issue of consecutive lines not being split. @mpu Would you be available to open a PR with a fix (any fix as long as it works)? Otherwise, we should revert #12272 in v8.12.
