### ISSUE TITLE
`positive` delimiter doesn't seem to work

### ISSUE THREAD

**Issue by vsiles** [coq/coq#12306]
#### Description of the problem

Consider the following script:
```
From Coq Require Import Numbers.BinNums.

Check (1%positive). (* displays 1 : nat *)
```
I would have expected a `1 : positive` or something similar. Am I doing something wrong ?

#### Coq Version
Coq installed via opam, on MacOs Catalina 10.15.4
```
$ coqc --version
The Coq Proof Assistant, version 8.11.0 (March 2020)
compiled on Mar 5 2020 8:39:08 with OCaml 4.08.1
```

**Comment by JasonGross** [comment]
Does it work if you `Require Import PArith`?  I'm inclined to think you're just not getting the right file where the notation is defined

**Comment by proux01** [comment]
Indeed, you're right. Even requiring `BinPos` (where the numeral notation is defined) is enough.

So what's happening is that here no notation for `1` exists in scope `positive` so the one in `nat` gets used. This would then not be a bug. Should we close this?

**Comment by JasonGross** [comment]
Feel free to open a new issue (e.g. that the documentation should be improved) if you think there's still an issue here.
