### ISSUE TITLE
merge-pr doesn't understand pagination

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#12300]
For instance with #12129 it sees no APPROVED review because it's on page 2 (https://api.github.com/repos/coq/coq/pulls/12129/reviews?page=2)

Not sure if ignoring pagination can cause issues with the main api call.

**Comment by Zimmi48** [comment]
> Not sure if ignoring pagination can cause issues with the main api call.

In theory, it could miss a label, but I don't think the number of labels on a PR will ever come close to the pagination limit :laughing:

**Comment by JasonGross** [comment]
A kludgy partial fix for this would be to add `?per_page=100` to the API calls

**Comment by Zimmi48** [comment]
The fix would be partial indeed, however, it seems to me that it would still be a good idea to do this since we are interested in all the reviews anyway (and it would certainly limit the occurrences of this bug a lot).
