### ISSUE TITLE
dev/tools/merge-pr.sh dies silently when the current branch has no remote

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12314]
The call 
https://github.com/coq/coq/blob/d80458841316ca7edf7317ef412142e27133c931/dev/tools/merge-pr.sh#L84
will cause the script to exit (due to `set -e`) silently if there is no remote.  Perhaps there should be an `|| true` at the end?

**Comment by Zimmi48** [comment]
@JasonGross The issue is that the script should exit with an explicit error, right? Then if you put some `|| true`, you also need to put some new check below, right?

**Comment by JasonGross** [comment]
There is already a check below, so the effect of `|| true` is to make the script exit with an explicit error:
https://github.com/coq/coq/blob/d80458841316ca7edf7317ef412142e27133c931/dev/tools/merge-pr.sh#L84-L90

**Comment by Zimmi48** [comment]
Oh right! Sounds good.
