### ISSUE TITLE
Set Printing Depth 0, 1, 2, 3, 4 are no-ops

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12331]
#### Description of the problem

```coq
Polymorphic Definition id {A} (x : A) := x.
Goal id id id id id id 0 = 0.
  (* 1 subgoal (ID 10)

  ============================
  id id id id id id 0 = 0 *)
  Set Printing Depth 0. Show. (* no change *)
  Set Printing Depth 1. Show. (* no change *)
  Set Printing Depth 2. Show. (* no change *)
  Set Printing Depth 3. Show. (* no change *)
  Set Printing Depth 4. Show.
  (* 1 subgoal (ID 10)
  ...
   *)
  Set Printing Depth 5. Show.
  (* 1 subgoal (ID 10)
  ...
  ============================
  ...
   *)
  Set Printing Depth 6. Show.
  (* 1 subgoal (ID 10)
  ...
  ============================
  ... = 0
   *)
  Set Printing Depth 7. Show.
  (* 1 subgoal (ID 10)

  ============================
  id id id id id id 0 = 0
*)
```
Also, some tests of `Set Printing Depth` should be in the output test-suite if they are not already

#### Coq Version

8.11.1

**Comment by SkySkimmer** [comment]
Isn"t it just that there are a bunch of boxes before you get any strings?

**Comment by ejgallego** [comment]
This is not a bug, printing depth is not a precise parameter and indeed depending on the concrete way to print a term may get wrapped in less or more boxes. Your example is not fixable for example without breaking quite a bit of other stuff.

I know that is weird but it is the way the formatter works, from a UI point of view what makes sense is to have an increase / decrease current printing depth.

**Comment by JasonGross** [comment]
What I'm confused about is the fact that printing depths 0, 1, 2, and 3 all print
```
1 subgoal (ID 10)

  ============================
  id id id id id id 0 = 0
```
which is more than is printed by higher printing depths.  Neither explanation really makes sense to me to explain this behavior.

**Comment by JasonGross** [comment]
Oh, I see what's going on here.  `Show` for printing depths 0 and 1 prints nothing (so PG does not update the goal), and it is not until depth 4 that "1 subgoal" is printed, and so PG doesn't recognize a goal update until then.  Agreed, this is not a bug.

**Comment by SkySkimmer** [comment]
0 and 1 should have no effect as ocaml does `let pp_set_max_boxes state n = if n > 1 then state.pp_max_boxes <- n` (the option just forwards to the ocaml stdlib setting)
