### ISSUE TITLE
limit_in in Coq.Reals.Rlimit dosen't require that x can't be the same as x0.

### ISSUE THREAD

**Issue by YunosukeY** [coq/coq#12340]
#### Description of the problem

limit_in in Coq.Reals.Rlimit dosen't require that x can't be the same as x0.
In the usual epsilon–delta definition, I think x can't be the same as x0, but Coq library isn't so.  

If x can be the same as x0, it leads a problem.  
Let f : R -> R be a function such as f(0) = 1 and f(t) = 0 (where t != 0).  
I think the limit at 0 of f should be 0.  
Let x0 = 0, l = 0, and eps = 0.1.  
Then no matter how we take the value of alp,  
if let x = 0,  "Rabs x x0 < alp" holds and "Rabs (f x) l < eps" dosen't hold.  
So the limit at 0 of f is not 0.  

Is this a bug?

#### Coq Version
```
$ coqtop -v
The Coq Proof Assistant, version 8.11.1 (April 2020)
compiled on Apr 6 2020 4:38:42 with OCaml 4.09.0
```

**Comment by YunosukeY** [comment]
Now I noticed D_x which requires different point is used in the definition of continue_in and D_in.  
But I think the above problem haven't been resolved.

**Comment by herbelin** [comment]
@YunosukeY: The library was mostly based on French curriculum (e.g. https://books.google.de/books?id=caH1CQAAQBAJ&pg=PA486&redir_esc=y) for which having a limit on a defined point [seems](https://fr.wikipedia.org/wiki/Limite_(math%C3%A9matiques)#Limite_et_continuit%C3%A9_en_un_point) to imply continuity in this point. I'm not a specialist of the subtle differences in real analysis conventions depending on countries but it seems indeed, based e.g. on the corresponding popular  [Wikipedia](https://en.wikipedia.org/wiki/Limit_(mathematics)#Limit_of_a_function) page, that the convention x≠x0 can be adopted too.

In any case, you can indeed call `limit_on` on `D_x x0` to recover the other definition.

Does this answer your concern?

**Comment by YunosukeY** [comment]
I didn't know that.
Thank you for your comment!
