### ISSUE TITLE
Anomaly "Uncaught exception Not_found." with pattern matching

### ISSUE THREAD

**Issue by gasparattila** [coq/coq#12348]
The following code raises an anomaly:
```coq
Check let 'tt := tt in
      let X := nat in
      let b : bool := _ in
      (fun n : nat => 0 : X) : _.
(* Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/. *)
```
This variant results in "Ill-typed evar instance":
```coq
Check let 'tt := tt in
      let X := nat in
      let b : bool := true in
      (fun n : nat => 0 : X) : _.
(* Ill-typed evar instance *)
```
When `let b` is removed, the return clause cannot be inferred:
```coq
Check let 'tt := tt return ?[R] in
      let X := nat in
      (fun n : nat => 0 : X) : _.
(*
In environment
X := nat : Set
Unable to unify "nat -> X" with "?R@{u:=tt}" (cannot instantiate 
"?R" because "X" is not in its scope: available arguments are "tt").
*)
```
Note that all the errors disappear when either the pattern matching or the `: _` at the end is removed.

#### Coq Version
8.11.0

**Comment by herbelin** [comment]
Fixed in #12348 which makes both examples working (this was due to an unfortunate de Bruijn indices problem showing in the presence of let-ins). Thanks a lot for reporting!
