### ISSUE TITLE
Carefully select the version to include in the Windows installer.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#12360]
Before tagging and releasing 8.12+beta1 we need to select more carefully (than #12355) the version of the add-ons that will be in the installer. As often as possible, we should aim for tagged versions (releases), possibly slightly patched for compatibility.

**Comment by Zimmi48** [comment]
#12415 does a first selection, but we will have to come back to this selection and update it for the final release, so I'm changing the milestone.

**Comment by Zimmi48** [comment]
@MSoegtropIMC not much remains to do for this issue except maybe getting your CompCert / VST patches upstreamed and possibly a tagged version for these two projects?

**Comment by ejgallego** [comment]
Finished in #12745
