### ISSUE TITLE
"exists a, b" can fail even if "exists a; exists b" succeeds

### ISSUE THREAD

**Issue by gasparattila** [coq/coq#12365]
#### Description of the problem

```coq
Parameter a b : nat.
Parameter p : a = b.

Goal exists (_ : True) (_ : exists x, x = b), True.
Proof.
  Fail exists I, (ex_intro _ a p).
  exists I; exists (ex_intro _ a p).
```
The failure is caused by the evar constraints from `ex_intro _ a p` being present when `I` is used. These constraints cannot be solved by unification without additional information from the goal.

#### Coq Version
8.11.0

**Comment by SkySkimmer** [comment]
You mean it should interleave using terms and interpreting them instead of first interpreting all of them then using all of them?

**Comment by gasparattila** [comment]
Yes, that way more information is available for unification.
