### ISSUE TITLE
Multiple index keys for the same command does not work in the PDF output.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#12361]
#### Description of the problem

In the 8.12 version of the reference manual, it is possible to have a single command that is referred to by multiple index keys (this is the case of `Definition` / `Example`, `Theorem` and variants, `Parameter` and variants, `Require` / `Require Import` / `Require Export`, `Implicit Type` and plural form, `Record` / `Structure`). This works fine in the HTML output, but it doesn't in the PDF output: only the last key works, and the others are displayed with some `??` showing a reference not found.

See example here: https://coq.gitlab.io/-/coq/-/jobs/543104421/artifacts/_install_ci/share/doc/coq/sphinx/latex/CoqRefMan.pdf

#### Coq Version

v8.12 and master

cc @jfehrle who implemented this feature

**Comment by jfehrle** [comment]
Also, the general index only includes the last provided name, e.g. `Variables`.

**Comment by cpitclaudel** [comment]
I blame this from `sphinx/writers/latex.py`:

```python
    def visit_desc_signature(self, node: Element) -> None:
        if node.parent['objtype'] != 'describe' and node['ids']:
            hyper = self.hypertarget(node['ids'][0]) # ← here
        else:
            hyper = ''
        self.body.append(hyper)
        if not node.get('is_multiline'):
            self._visit_signature_line(node)
        else:
            self.body.append('%\n\\pysigstartmultiline\n')
```

**Comment by cpitclaudel** [comment]
Maybe adding this to coqdomain.py (or even conf.py) is enough:

```python
# FIXME: Patch this in Sphinx
# https://github.com/coq/coq/issues/12361
def visit_desc_signature(self, node):
    hyper = ''
    if node.parent['objtype'] != 'describe' and node['ids']:
        for id in node['ids']:
            hyper += self.hypertarget(id)
    self.body.append(hyper)
    if not node.get('is_multiline'):
        self._visit_signature_line(node)
    else:
        self.body.append('%\n\\pysigstartmultiline\n')
LaTeXTranslator.visit_desc_signature = visit_desc_signature
```
