### ISSUE TITLE
[dune] which version?

### ISSUE THREAD

**Issue by gares** [coq/coq#12376]
```
gares@ollypat:~/COQ/master$ git grep '\(lang\|dune\).*2\.[0-9]'
coq.opam:  "dune"      { >= "2.5.0"  }
coqide-server.opam:  "dune"      { >= "2.0.0" }
coqide.opam:  "dune"                 { >= "2.0.0" }
dev/build/windows/makecoq_mingw.sh:  if build_prep https://github.com/ocaml/dune/archive/ 2.0.0 tar.gz 1 dune-2.0.0 ; then
dev/ci/docker/bionic_coq/Dockerfile:    BASE_OPAM_EDGE="dune.2.5.0 dune-release.1.3.3 ocamlformat.0.14.0"
dev/dune-workspace.all:(lang dune 2.0)
dune-project:(lang dune 2.5)
```

I guess we should centralize this piece of info, one way or another, in order to avoid duplication.

**Comment by Zimmi48** [comment]
Right. FTR, the correct version is the one that you can see in `coq.opam` and `dune-project` and `Dockerfile`, i.e. Dune >= 2.5 is needed. The best way to remove some duplication and potential for inconsistency is to start generating the opam files through Dune (which we should be able to do nowadays). I think it's fine if the `dune-worskpace` file as an older version of the language listed. As for `makecoq_mingw.sh`, it is not yet used to build Coq itself.

**Comment by ejgallego** [comment]
Actually `coqide` and `coqide-server` should work fine with dune 2.0 [as they don't build .v files] so I'm not sure if we wanna bump them.

**Comment by rgrinberg** [comment]
Given that you only have a single `dune-project` file that require 2.5, you need to bump to 2.5. Otherwise, you'll ned to move `coqide` and `coqide-server` to their own dune projects (not worth it IMO)

**Comment by ejgallego** [comment]
Moving `coqide` to its own repos is an option I think.
