### ISSUE TITLE
[zulip] Please move notifications to their own stream.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#12382]
The notifications topics currently live in the "Coq dev" stream; IMHO they would be better in their own stream "Github notifications", the current setup:
- pollutes the list of topics in the stream [the topics are consistently at the top]
- makes it harder so follow the dev stream. I know I could mute them but sometimes I'd like to have a look at them too.

**Comment by Zimmi48** [comment]
cc @CohenCyril (I will take care of this)

**Comment by Zimmi48** [comment]
Done
