### ISSUE TITLE
Coq allows one to try to prove `forall (P : SProp) (x y : P), x = y`, despite being ill-typed.

### ISSUE THREAD

**Issue by Mbodin** [coq/coq#12381]
#### Description of the problem

I found this line in a Coq project: https://gitlab.inria.fr/kmaillar/dijkstra-monads-for-all/-/blob/master/theories/sprop/SPropBase.v#L262
I don’t know much of `SProp`, but as I didn’t see this issue reported here, I wanted to make sure that this issue is referenced here too.

Here is a minimal example:
```coq
(* -*- coq-prog-args: ("-allow-sprop"); -*- *)

Goal forall (P : SProp) (x y : P), x = y.
Proof.
admit.
Admitted. (* fails *)
```

#### Coq Version
Coq 8.10.1.

**Comment by SkySkimmer** [comment]
It's explained in the manual https://coq.github.io/doc/master/refman/addendum/sprop.html#issues-with-non-cumulativity
