### ISSUE TITLE
[refman] Version switcher is broken

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#12395]
The version switcher doesn't appear anymore on https://coq.github.io/doc/master/refman/ and https://coq.github.io/doc/v8.12/refman/. I assume this is a consequence of the update of the version of the theme (part of #12224 that we failed to notice when reviewing the output of this PR).

cc @cpitclaudel (is this something that you think would be easy to fix)

**Comment by cpitclaudel** [comment]
Thanks for the heads up; I'll look at it today.  It shouldn't be hard to fix.

**Comment by Zimmi48** [comment]
ping @cpitclaudel: If it's easy to fix, it'd be good to do it now, otherwise we should remove the changelog entry I added about it from the 8.12+beta1 release notes.

**Comment by Zimmi48** [comment]
The cause of the issue is likely something else than the bump in the update of the theme, because the version switcher still works in PR builds (e.g. https://coq.gitlab.io/-/coq/-/jobs/581141713/artifacts/_install_ci/share/doc/coq/sphinx/html/index.html), but it doesn't on deployed builds.

**Comment by Zimmi48** [comment]
OK, I think I've got it. It's a dependency registration issue with Dune!

**Comment by cpitclaudel** [comment]
:+1: I need to be more careful about promising to do things "today"

**Comment by Zimmi48** [comment]
In the end, it gave me time to figure things out :wink: 

If you do find out some available time, the most pressing issue to look into now is #12305 (because it is a regression). And if you have even more time, #12435 could be worth a look as well.
