### ISSUE TITLE
Anomaly with ill-typed arity in inductive types

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#12390]
In Coq master (ea9463bc10e83759586a41d562e996e1d34e627f):

```
Inductive T : nat :=.
(* Anomaly "Uncaught exception Reduction.NotArity." *)
```

This bug was not present in 8.11.

**Comment by ejgallego** [comment]
The `NotArity` exception is not caught and doesn't have a printer when it reaches the toplevel.

It is an exception that should be printed by the toplevel ? It doesn't seem so, so maybe the caller of reductionops should handle it?

**Comment by ejgallego** [comment]
Concretely this code in comInductive is not working anymore:
``` 
  | exception Invalid_argument _ ->
    user_err ?loc (str "Not an arity")
```
seems due the lower-level layer using a different exn?

**Comment by ejgallego** [comment]
Adding this:
```
  | exception Reduction.NotArity ->
    user_err ?loc (str "Not an arity")
```
fixes the issue, exceptions...
