### ISSUE TITLE
[engine-bench] "Fatal error: ref_table overflow" is uninformative and missing location info

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12401]
#### Description of the problem

What does this error even mean?
https://gitlab.com/coq/coq/-/jobs/565431385

#### Coq Version

16e0877c6e3ec6228875e10afb1ec17d640eb1e9

**Comment by JasonGross** [comment]
Seems to probably come from the OCaml GC? https://github.com/ocaml/ocaml/blob/10561873487c185c0727f08b26706226dbb1a7b6/runtime/minor_gc.c#L614-L622

**Comment by SkySkimmer** [comment]
Not much we can do with this, especially without a reproduction case.
