### ISSUE TITLE
"idtac ; idtac" in coqtop:: directive in doc behaves differently from coqtop binary and coqIDE

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12435]
Running `idtac "x"; idtac "y".` in the coqtop binary or coqIDE gives the correct output:

```
x
y
```

whereas the same tactic in a `coqtop::` directive in the doc only shows

![image](https://user-images.githubusercontent.com/1253341/83554797-29caf900-a4c2-11ea-90fe-945df34c9fb9.png)

I see this even if it's not the last tactic in the `coqtop::`.

This is with coqtop from master and coqIDE 8.11 and this input:

```
      .. coqtop:: reset none
      
         Goal True.
         
      .. coqtop:: all

         idtac "x"; idtac "y".         
```

I see the same problem with this variation; "y" is not printed:

```
      .. coqtop:: all
      
         idtac "x".   
         idtac "y".
```

But this works as expected:

```
      .. coqtop:: all

         match True with
         | True => idtac "branch 1"; fail
         | _ => idtac "branch 2"
         end.
```

![image](https://user-images.githubusercontent.com/1253341/83555677-811d9900-a4c3-11ea-81bb-b88d061ed1a0.png)

**Comment by jfehrle** [comment]
@Zimmi48 I hope we can fix this sooner rather than later.  I created 3 useful examples for the Ltac chapter that don't make sense without the correct output.

**Comment by Zimmi48** [comment]
Any chance for this to be related to #12305?

**Comment by jfehrle** [comment]
Seems like a good guess though I haven't looked at any code.

**Comment by jfehrle** [comment]
That patch appears to affect input, not output.  So not relevant.

I added a print statement to show the output gathered by Coqtop.sendone().  It is not seeing the output from `idtac "y"` in `idtac "x"; idtac "y".`, so it appears the problem is related to `expect`.  I see the same problem in 8.11.2 and 8.9 alpha, so it's not new.  (I forgot the incantation to download a release & didn't feel like looking it up.)

OTOH, in the older versions `idtac "x". idtac "y".` works correctly.

```
```
