### ISSUE TITLE
`Proof <term>.` fails if it follows a non-Lemma-like command

### ISSUE THREAD

**Issue by erikmd** [coq/coq#12444]
#### Description of the problem

If there is a (setting, query, ...) vernacular between `Goal/Lemma` and `Proof <term>.`, then the proof term is rejected.

MWE using coqtop:

<pre>
Lemma test : True.
Check 0. (* or  Set Printing All.  or … *)
Proof I.
<b>(* Toplevel input, characters 0-8:
   > Proof I.
   > ^^^^^^^^
   Error:  (in proof test): Attempt to save an incomplete proof *)</b>
</pre>

This is reproducible with Coq 8.11, 8.10, 8.9... as long as the `Proof I.` command does not immediately follows `Lemma …`

Initially reported in the PG bug tracker by @mwuttke97 − https://github.com/ProofGeneral/PG/issues/498

Cc @Matafou @cpitclaudel @monnier FYI

#### Coq Version
```
$ coqtop -v
The Coq Proof Assistant, version 8.11.1 (April 2020)
compiled on Apr 9 2020 18:18:55 with OCaml 4.05.0
```
on Debian GNU/Linux

**Comment by Zimmi48** [comment]
I think this issue is more or less known and there is no intent to fix it. But rather to deprecate and remove the `Proof <term>` command as soon as `Lemma :=` (cf. coq/ceps#42) is available.

**Comment by Zimmi48** [comment]
This is possibly a duplicate but `Proof <term>` is too hard to search for me to dig up the relevant issue.

**Comment by erikmd** [comment]
@Zimmi48 indeed, I found there are at least 2 duplicates :)
* https://github.com/coq/coq/issues/5592
* https://github.com/coq/coq/issues/8229
but as these two issues are a bit more specific (they only speak of `Unset Silent`), would it make sense to close them as duplicate, then close #12444 as wontfix (now or later)?

**Comment by Zimmi48** [comment]
Sure!

**Comment by erikmd** [comment]
done, I didn't close #12444 as wont-fix for the time being, but feel free to do so when you see fit
