### ISSUE TITLE
Proof using suggestion appear even outside sections 

### ISSUE THREAD

**Issue by Matafou** [coq/coq#12447]
#### Description of the problem
Proof Using suggestion appear even for proofs outside sections.
Is it intended? It forces IDEs to be smart about inserting the proposed annotations.
Proof using annotations are allowed outside section but mainly useless, aren't they?

```
Lemma foo: forall x :nat, x = x.
Proof.
(* Print titi. *)
  intro.
  auto.
Qed.
```
==>
```
The proof of foo should start with one of the following commands:
Proof using . 
Proof using All. 
Proof using Type*. 
Proof using Type.
```
#### Coq Version
master

**Comment by gares** [comment]
The code I wrote a long ago was under such a test (actually it tested if the section variables list was empty). Then the code was moved outside the kernel by #1103 by @SkySkimmer which kept the test as far as I can tell. Then the code was moved around by @ejgallego , I don't have time to exactly find the commit that lost that condition, see:
https://github.com/coq/coq/blob/0ae20176df146b90f11e131aff3673584e6ffb3a/vernac/declare.ml#L925

It should be fixable by calling calling `Lib.sections_are_opened` in https://github.com/coq/coq/blob/0ae20176df146b90f11e131aff3673584e6ffb3a/vernac/declare.ml#L914 or some equivalent test.
I'm sorry but I don't have time for this.

**Comment by SkySkimmer** [comment]
>It should be fixable by calling calling Lib.sections_are_opened 

Ideally it should be the same test as the one used by the stm to decide if delegating is ok
I believe that's https://github.com/coq/coq/blob/0ae20176df146b90f11e131aff3673584e6ffb3a/stm/stm.ml#L2550

**Comment by gares** [comment]
Yes, that one also covers "open sections with no variables" with is a bit better
