### ISSUE TITLE
Ltac command should take an "ident" instead of a "qualid" before ":="

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12469]
Since this is semantically prohibited, we should change the grammar so it only takes an "ident".

```
Ltac a.b := idtac 1.
(* error: This expression should be a simple identifier. *)
```

**Comment by Zimmi48** [comment]
`Ltac a.b ::=` is authorized though and that's probably not possible to parse it without also parsing `Ltac a.b :=`. So that is, I think, the reason why it is rejected at evaluation time and not parsing time.

**Comment by jfehrle** [comment]
I had forgotten about modules.

Nor did I expect you could redefine symbols defined in modules.  Are you generally allowed to redefine module symbols--is Ltac consistent on this?

```
Module S.
Ltac y := idtac.
End S.

Ltac S.y ::= idtac  "X".
Goal True.
S.y.

(* X *)
```

**Comment by JasonGross** [comment]
I believe Ltac and Ltac2 can redefine symbols in modules.  I don't believe any other part of the system allows redefinition of symbols.

**Comment by Zimmi48** [comment]
In Ltac2, this feature is more principled since you have to define the symbol as mutable in the first place, and when you use a different command to redefine it, so there is no syntax clash. See https://coq.github.io/doc/master/refman/proof-engine/ltac2.html#ltac-definitions.
