### ISSUE TITLE
SProp does not match SProp, but does match Prop

### ISSUE THREAD

**Issue by jlottes** [coq/coq#12529]
#### Description of the problem

    Goal SProp.
    Fail match goal with |- SProp => idtac end.
    (* The command has indeed failed with message:
    No matching clauses for match. *)
    Abort.

    Goal Prop.
    match goal with |- SProp => idtac end.
    Abort.

I would guess this is related to the failure of an attempt to declare some typeclass instances on SProp (using explicit patterns):

    Class F A := f : A.
    
    Inductive pFalse : Prop  := .
    Inductive sFalse : SProp := .

    Hint Extern 0 (F Prop) => exact pFalse : typeclass_instances.
    Definition pf := f : Prop.

    Hint Extern 0 (F SProp) => exact sFalse : typeclass_instances.
    Fail Definition sf := (f : SProp).
    Fail Definition pf' := (f : Prop).

The definition of `sf` fails because the SProp hint is not applied for it, while the definition of `pf'` fails because the SProp hint is erroneously applied for it.

#### Coq Version
8.11.2

**Comment by SkySkimmer** [comment]
Fix at https://github.com/coq/coq/pull/12530
