### ISSUE TITLE
Setting Implicit arguments for constructor of a record breaks record-style pattern matching syntax

### ISSUE THREAD

**Issue by Janno** [coq/coq#12534]
#### Description of the problem

The following code fails and I can't find a way to make it succeed with the `{| ..|}` syntax:

```coq
Class C {PROP: Prop} (P : PROP) : Type := { c : unit}.
Check fun '{|c:=x|} => tt.      (* Fine *)
Arguments Build_C {_ _} _.
Check fun '(Build_C _) => tt. (* Works. Note: just 1 argument! *)
Check fun '{|c:=x|} => tt.
(* Error: The constructor @Build_C (in type @C) expects 1 argument. *)
```

This very likely related to #11112 but apart from being a confusing error message, in the example above it also means that the record syntax cannot be used at all (as far as I can tell). Thus, I am reporting it as a separate bug, assuming that it can probably be fixed without fixing the confusing error message.

#### Coq Version
8.11

**Comment by SkySkimmer** [comment]
Same error with Record instead of Class.
