### ISSUE TITLE
CoqIDE on macos frequently doesn't work

### ISSUE THREAD

**Issue by chrisfcarroll** [coq/coq#12543]
## Steps to reproduce

1. Download and install from https://github.com/coq/coq/releases/tag/V8.11.2
2. Run coqIDE and type some examples from, for instance, Coq in a Hurry:
```
Check 3.
```
Then Menu->Queries->Check

Expected: 
```
3
   : nat
```

Actual: NO Output at all

### Other info:
`Check True.` and `Check False.` work as expected
coqtop on the commandline works as expected

### Coq Version

coqtop -v
The Coq Proof Assistant, version 8.11.2 (June 2020)
compiled on Jun 16 2020 15:34:08 with OCaml 4.09.0

**Comment by Zimmi48** [comment]
@chrisfcarroll Sorry for the delayed answer. I don't think this is specific to macOS. I think the difference is related to the fact that `3` is only one character-long, so you cannot put your cursor in the middle of it. However, if you select it before using the query menu, it should work. Note that in CoqIDE, you can also step through the document, in which case the `Check` command should always work (and when you use the query menu, you do not have to write `Check` in the document).
