### ISSUE TITLE
New square bracket implicit in Context misinterpreted

### ISSUE THREAD

**Issue by roger-witte** [coq/coq#12551]
#### Description of the problem
```coq
Section Sect.
Context {A : Type} [a : A] {b : A}.
Definition F : A * A := (a, b).
End Sect.
About F.
(* 
F : forall {A : Type}, A -> A -> A * A

F is not universe polymorphic
Arguments F {A}%type_scope {a b}
F is transparent
Expands to: Constant Top.F
*)
(** I expected Arguments F {A}%type_scope [a] {b} *)
```
#### Coq Version

8.12 beta 1

**Comment by Zimmi48** [comment]
Thanks for the report!

@SimonBoulier do you think that this is something that could be fixed easily? If not, I think we should still address this by 8.12.0, e.g. by adding a check that prevents the use of this new syntax in the `Context` command.

**Comment by SimonBoulier** [comment]
I will try to have a look next week.

**Comment by SkySkimmer** [comment]
There's already https://github.com/coq/coq/pull/12626

**Comment by SimonBoulier** [comment]
Okay thanks.
