### ISSUE TITLE
Documentation of native flags

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#12564]
It seems to me that there is no specification of how native flags should work; this makes it hard to support native properly as we have to guess what the intended behavior is, and this may not match implemented one.

For now we have two flags:

- `configure`'s `-native-compile={yes,no}`
- `coqc`'s `-native-compiler={yes,no,ondemand}`

that gives us 6 possible combinations to document. In particular, important points for each combination (set) are:
- files that are produced
- files that are required

**Comment by SkySkimmer** [comment]
>that gives us 6 possible combinations to document

If configure is no then coqc is also no (warns but ignores others)

**Comment by maximedenes** [comment]
| `configure`  | `coqc` | produced |
| ------------- | ------------- | ------------- |
| yes | yes | `.coq-native`/* + temporary (when calling `native_compute`) |
| yes | ondemand | temporary |
| yes | no | none |
| no | yes | none |
| no | ondemand | none |
| no | no | none |

Coq's standard library should be compiled with `-native-compiler yes`.

If `B` depends on `A`, the files that are required by `B` are the ones that are produced when building `A`, except temporary ones (which are put in the temp directory).

**Comment by ejgallego** [comment]
One particular tricky point to support is fast builds , where native is on, but we want to skip native compilation as we are developing.

> If configure is no then coqc is also no (warns but ignores others)

Umm, that happens as is today, however generation of the `.cmx` files is independent of whether the tactics are enabled, right?

That's a bit tricky for the build system as in this case the target set will depend on a configure option passed to Coq, for example what should the behavior be when a user says `(mode Native)` in their theory, but native was not enabled? Should the build system fail, or just warn.

**Comment by maximedenes** [comment]
> the target set

For context, why does the build system need to know the exact target set? Can't it check the existence of a byproduct (here `.coq-native/*`) and install it if it exists once the build is completed?

**Comment by ejgallego** [comment]
> | `configure` |	`coqc`|	produced |
> |---|---|---|
> | yes|	yes|	`.coq-native/*` + temporary (when calling `native_compute`)|
> | yes|	ondemand|	temporary|
> | yes|	no|	none|

So is that equivalent to the previous setup where we had `produce_native_files` and `enable_native_reduction` , but discarding one casE?

> Coq's standard library should be compiled with `-native-compiler yes`.

Should or must? [Trying to figure out what should happen if it is not, in the case configure=no]

Currently, Dune's opam file compiles Coq with `configure=yes,native=ondemand]`, so it should work if I understood correctly from the discussion a few months ago. [native=ondemand] is the default.

> If `B` depends on `A`, the files that are required by `B` are the ones that are produced when building `A`, except temporary ones (which are put in the temp directory).

Not sure I fully follow, what happens when the flags of `A` are different? Maybe you could add a 4th column to describe the dependencies?

**Comment by ejgallego** [comment]
> For context, why does the build system need to know the exact target set? Can't it check the existence of a byproduct (here `.coq-native/*`) and install it if it exists once the build is completed?

Incremental builds require that for soundness, otherwise you may end with stale `coq-native` files. [Or you would be forced to clean all .coq-native then getting very bad object reuse]

**Comment by maximedenes** [comment]
> Not sure I fully follow, what happens when the flags of `A` are different?

They should be irrelevant.

**Comment by ejgallego** [comment]
> They should be irrelevant.

Ok, then the current documentation / behavior in `master` may be wrong, as it seems to require flags of dependencies to be transitive.

**Comment by maximedenes** [comment]
> Ok, then the current documentation / behavior in `master` may be wrong, as it seems to require flags of dependencies to be transitive.

Maybe the documentation was made stricter. Do you have a pointer?

**Comment by ejgallego** [comment]
https://github.com/coq/coq/blob/master/doc/sphinx/practical-tools/utilities.rst#precompiling-for-native_compute

**Comment by SkySkimmer** [comment]
>If B depends on A, the files that are required by B are the ones that are produced when building A, 

Doesn't that mean coqc yes needs coqc yes on the dependencies transitively?

**Comment by maximedenes** [comment]
> https://github.com/coq/coq/blob/master/doc/sphinx/practical-tools/utilities.rst#precompiling-for-native_compute

This may be a `coq_makefile` requirement, but I don't think that's a `native_compute` requirement.

**Comment by maximedenes** [comment]
In fact, it is indeed a `native_compute` requirement, I just tested in master. So maybe this has changed, but the documentation seems right.

> Doesn't that mean coqc yes needs coqc yes on the dependencies transitively?

Yes, that's what it means.

**Comment by maximedenes** [comment]
> Not sure I fully follow, what happens when the flags of `A` are different? Maybe you could add a 4th column to describe the dependencies?

Right, flags of dependencies are relevant in fact, so let's add the column:

| `configure`  | `coqc` | produced | requirements on dependencies |
| ------------- | ------------- | ------------- | ------------- |
| yes | yes | `.coq-native/*` + temporary (when calling `native_compute`) | dependencies should be compiled with the same native flags |
| yes | ondemand | temporary | none |
| yes | no | none | none |
| no | yes | none | none |
| no | ondemand | none | none|
| no | no | none | none |

@ejgallego Does it answer your questions?

**Comment by ejgallego** [comment]
> @ejgallego Does it answer your questions?

I think so, thanks. We should add this table to the manual under the relevant command line flags. I need to think a bit on all possible cases to see if we forgot some case, but I think that this should be good.

Main issue is that at the installed library level, we should use something such as `META` file as to know when a library is not available so the build system can actually not rely on failing call to `coqc`

**Comment by silene** [comment]
As a side note, I should mention that the current behavior is painful for library authors. For example, CoqInterval has five dependencies (Stdlib, Mathcomp, Coquelicot, Flocq, Bignum). So, to compile it with `-native-compiler yes`, I need to first check that all five dependencies were compiled using `-native=compiler yes`. Guess what, I don't bother, so `-native-compiler yes` is never passed to `coqc`, despite CoqInterval providing support for `native_compute` (and installing the native files if they are produced). In turn, users never pass the `i_native_compute` flag to tactic `interval`, due to the huge overhead it incurs because CoqInterval was not compiled with `-native-compiler yes`.

**Comment by ejgallego** [comment]
> As a side note, I should mention that the current behavior is painful for library authors.

@silene note that behavior changed recently as bignums was the first library that actually tested native=yes in our CI setup.

How would you like things to work? Currently indeed library authors have to enable native mode manually.

**Comment by silene** [comment]
The old behavior was that native files were compiled by `coqc` if possible. So, library authors did not have to worry about anything.

**Comment by ejgallego** [comment]
> The old behavior was that native files were compiled by `coqc` if possible. So, library authors did not have to worry about anything.

But that was the source of the overhead you were referring to, right?

**Comment by silene** [comment]
No, we are not talking about the same overhead. I guess you are talking about the overhead at compilation time. (And I understand why this may infuriate a user who does not care about `native_compute`.) I am talking about the one at runtime:

```coq
From Coq Require Import Reals.
From Coquelicot Require Import Coquelicot.
From Interval Require Import Tactic.

Goal (0 <= RInt exp 0 1)%R.
Time integral.
(* Finished transaction in 0.02 secs (0.02u,0.s) *)
Undo.
Time integral with (i_native_compute).
(* Finished transaction in 2.127 secs (0.217u,0.035s) *)
Qed.
```

So, unless the goal takes several seconds to solve, users will not bother with `native_compute`.

**Comment by ejgallego** [comment]
> I guess you are talking about the overhead at compilation time.

Umm, we have:

- old setup: library authors don't have to worry, you pay a huge runtime penalty due to on-demand, not cached compilation.
- new setup: library authors should enable native, you pay no overhead.

So actually you are advocating for the new setup?

Actually I have a question @maximedenes , `ondemand` still will compile the full dependency chain, right? So the 4th column should be a conditional [will compile if not available?]

Is that what we want, or should `ondemand` become more restrictive?

**Comment by maximedenes** [comment]
I imagine it would be better to turn native precompilation on by default on release builds of libraries. The only case where it may need to be disabled is for libraries relying on very large transparent terms (typically obtained through Ltac with `Defined`).

**Comment by silene** [comment]
No, you are mistaken about the old setup. When `native_compute` was added to Coq, native files were always produced (and installed), if possible. Later on, the behavior was changed to never produce native files unless `-native-compiler yes` was explicitly passed. But `-native-compiler yes` causes a hard error if Coq cannot produce native files.

So, no, I am not advocating for the new behavior, because library authors have no way to safely enable native compilation.

**Comment by Zimmi48** [comment]
@silene I think you are mistaking what @ejgallego designated as old / new behaviors. There was a very recent change from the "new" behavior that he describes, that allows library authors to safely enable native compilation.

**Comment by Zimmi48** [comment]
cf. #12070

**Comment by ejgallego** [comment]
Ok, that's the "old'" setup, IIANM we did have indeed 3 different setups in terms of semantics of the flags.

> So, no, I am not advocating for the new behavior, because library authors have no way to safely enable native compilation.

I'm a bit lost sorry @silene, can you elaborate on what behavior you would like? Do you propose indeed that release libraries should always compile native?

This is in a sense what the new behavior would be, requiring dependencies to add a flag [could be made the default tho so the flag would disable]

**Comment by ejgallego** [comment]
> I imagine it would be better to turn native precompilation on by default on release builds of libraries. The only case where it may need to be disabled is for libraries relying on very large transparent terms (typically obtained through Ltac with `Defined`).

This seems reasonable, if I understand the feedback of `native` users.

**Comment by silene** [comment]
> can you elaborate on what behavior you would like?

I would like a behavior that makes it possible for me to install native files for CoqInterval, so that users can use the `i_native_compute` flag of `interval` without suffering from a huge overhead. In fact, I should never have had to add this flag; the tactic should have been using `native_compute` by default.

**Comment by silene** [comment]
> There was a very recent change departing from what you called "new" behavior and what he called "old" behavior, that allows library authors to safely enable native compilation.

Could you point me to this change?

**Comment by silene** [comment]
Oops, sorry, missed the reference.

But that does not solve the issue, because it does not take into account dependencies, does it?

**Comment by silene** [comment]
What I mean is that, if I add `-native-compiler yes` to CoqInterval, then compilation fails with
```
Error: Unbound module NFlocq_Core_Raux
Error: Native compiler exited with status 2
```
And #12070 has no impact on that failure.

**Comment by SkySkimmer** [comment]
>
>~~~coq
>From Coq Require Import Reals.
>From Coquelicot Require Import Coquelicot.
>From Interval Require Import Tactic.
>
>Goal (0 <= RInt exp 0 1)%R.
>Time integral.
>(* Finished transaction in 0.02 secs (0.02u,0.s) *)
>Undo.
>Time integral with (i_native_compute).
>(* Finished transaction in 2.127 secs (0.217u,0.035s) *)
>Qed.
>~~~

What's the timing like when everything is precompiled btw?

**Comment by silene** [comment]
> What's the timing like when everything is precompiled btw?

```
Finished transaction in 0.125 secs (0.028u,0.014s)
```

So, not that great, but at least it is a fraction of a second.

**Comment by Blaisorblade** [comment]
- Any progress here? We discussed some plans on Zulip with @ejgallego.
- Is it worth enabling native-compute by default in opam for now? How many people rely on it, and can they use it out-of-the-box? If you need to customize library installation, asking users to customize one more step _might_ be okay?

**Comment by erikmd** [comment]
@Zimmi48 @ejgallego do you think that the CEP coq/ceps#48 (once it is finalized) could be seen as addressing this issue #12564?
or should we e.g. add some remarks in coq's reference manual…

**Comment by ejgallego** [comment]
IMHO this needs to be closed by indeed documenting the setup in Coq itself, so #13352 for example could help.

**Comment by erikmd** [comment]
OK… so maybe @proux01 or I could add a bit of some sphinx doc in #13352, inspired by this nice tabular https://github.com/coq/coq/issues/12564#issuecomment-647464937 by @maximedenes :)

**Comment by Zimmi48** [comment]
@erikmd It would be good indeed to advertise the CEP as a changelog entry (even though only part of it required actual changes in Coq). This could be done by modifying @proux01's changelog from #13352 or by adding a new entry. Furthermore, it would be good to also document the `-native-compiler` option in https://coq.github.io/doc/master/refman/practical-tools/coq-commands.html#by-command-line-options, to remove or change the recommendation when installing via `opam` in https://coq.github.io/doc/master/refman/practical-tools/utilities.html#precompiling-for-native-compute and to advertise the `coq-native` virtual package in https://coq.inria.fr/opam-using.html (source for this last page is https://github.com/coq/www/blob/master/pages/opam-using.html).

**Comment by proux01** [comment]
@Zimmi48 the changelog for #13352 already links to the CEP (or at least its PR). So isn't it already visible in the changelog?

**Comment by Zimmi48** [comment]
Here I was more specifically talking about the `coq-native` part of the CEP. I believe this is worth advertising in the changelog despite being implemented outside the code base. People should be made aware of this without having to follow the link to the CEP IMHO. This can be a separate changelog entry if you think it's better to separate concerns.

**Comment by proux01** [comment]
I agree, I'll open a PR modifying the changelog once the OPAm PR are merged.

**Comment by erikmd** [comment]
FYI @Zimmi48 @proux01 I just posted a message on Discourse/coq-club to announce that `coq-native` package in advance:
https://coq.discourse.group/t/about-the-native-compiler-flag-and-the-coq-native-opam-package-to-be-released-before-coq-8-13-beta1/1147

Also, the OPAM PR Pierre was mentioning is going to be merged on this Monday: https://github.com/ocaml/opam-repository/pull/17690

**Comment by proux01** [comment]
I wanted to update the changelog of #13586 as offered above but due to the release, the changelog has been created and the specific changelog file is gone. Not sure this is worth a direct modification of changes.rst.

**Comment by Zimmi48** [comment]
You probably meant #13352. The changelog is now integrated in `doc/sphinx/changes.rst` but indeed, given that the released is planned for today, I think it's too late for this now.

**Comment by gares** [comment]
What is the status of this? What needs to be done?

**Comment by proux01** [comment]
A bit of documentation. Is that ok if I open this documentation PR by the end of the week?

**Comment by gares** [comment]
The release if for January 7th, it if is merged before I'm ok.
