### ISSUE TITLE
Typeclass search opacity for axioms wrong by default

### ISSUE THREAD

**Issue by Janno** [coq/coq#12563]
#### Description of the problem

In the following example, TC search attempts to apply the instance `Inh_P` of type `Inh P` to a goal of the form `Inh True`, despite P being an axiom and thus (I think) not unifiable with anything but itself. Turning on `Hint Constants Opaque : typeclass_instances` solves the problem and seems to be the *only* solution since `Hint Opaque` don't take axioms as arguments.

I included a `control` definition that's declared `Hint Opaque` to exclude the possibility of `True` being considered transparent (as that would lead to a unification attempt of `True` and `control`).

```coq
Class Inh (A : Prop) := inh : A.

Axiom P : Prop.
Axiom p : P.

Definition control : Prop := True.

Instance Inh_P : Inh P | 0 := p.
Instance Inh_control : Inh control | 1 := I.
Instance Inh_True : Inh True | 100 := I.

Hint Opaque control : typeclass_instances.

Set Typeclasses Debug.
Set Typeclasses Debug Verbosity 2.

Goal True.
  apply inh.                    (* tries to unify [P] and [True] but not [control] and [True] *)
Qed.

(* The above shows that [True] and [control] are already considered opaque but [P] is not. *)

(* Sadly, we cannot set the opacity of [P] explicitly. *)
Fail Hint Opaque P : typeclass_instances.

(* BUT apparently it is still covered by [Hint Constants Opaque]?? *)
Hint Constants Opaque : typeclass_instances.
Goal True.
  apply inh.                    (* doesn't try to unify [P] and [True] *)
Qed.
```

I am reasonably sure that fixing this is an extremely easy (potential) performance win: teaching the discmrination tree (dnet, I guess?) to properly discriminate axioms shouldn't break any existing developments. Of course, it is possible that almost nobody uses TC instances with axioms but even then fixing this at least shouldn't break or slow down anything!

#### Coq Version
8.11, master

**Comment by ppedrot** [comment]
That one should be trivial to fix, working on it.

**Comment by Janno** [comment]
Is the same code path used for constants from sealed modules? TC search also considers those transparent by default:

```coq
Class Inh (A : Prop) := inh : A.

Module Type MT.
  Parameter True' : Prop.
  Parameter I' : True'.
End MT.

Module M : MT.
Definition True' : Prop := True.
Definition I' : True' := I.
End M.

Import M.

Instance Inh_True' : Inh True' | 1 := I'.
Instance Inh_True : Inh True | 100 := I.

Set Typeclasses Debug.
Set Typeclasses Debug Verbosity 2.

Goal True.
  apply inh.                (* attempts to pick [Inh_True'] but can't unify its type with [Inh True] *)
Qed.
```

**Comment by ppedrot** [comment]
@Janno yep, axioms and opaque constants are considered alike.
