### ISSUE TITLE
pre-commit not run in rebase

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12578]
I'm still not able to use Dune conveniently because doc_grammar is only usable in make.  In `CONTRIBUTING.md`, please add make instructions and at the very least, say it depends on Dune.  Periodically I waste 30 minutes or more laboriously cleaning up white space.  And yes, I have the white space cleanup tool enabled, but it only works on the top commit.

**Comment by Zimmi48** [comment]
The `pre-commit` hook doesn't depend on Dune and if it is installed it should apply to every commit you make. As for just cleaning whitespace, the simple `git rebase --whitespace=fix` (which is documented in https://github.com/coq/coq/blob/master/CONTRIBUTING.md#understanding-automatic-feedback) should usually be enough. I'm sorry but I'm not willing to spend time porting the linter to `make`.

**Comment by jfehrle** [comment]
It is not applied during rebases.  The doc should at least mention it's a Dune-only feature.

**Comment by Zimmi48** [comment]
Right. But how come whitespaces get introduced during rebases? If you edit a commit during a rebase, then the pre-commit hook should get triggered.

**Comment by jfehrle** [comment]
Ah, no, doesn't work.  May be because the spaces are in HEAD~2.

**Comment by Zimmi48** [comment]
I'd appreciate getting an example (e.g. a branch) so that I can reproduce your issue because I'm puzzled by it.

**Comment by SkySkimmer** [comment]
It seems rebase doesn't call any hooks (except with fixup/squash where it calls post-rewrite) so we can't really fix this.

(I already said this in the PR but since it's closed that's not very visible)
