### ISSUE TITLE
Document flags affecting native-compiler and native-compute

### ISSUE THREAD

**Issue by Blaisorblade** [coq/coq#12574]
#### Description of the problem

When investigating #11178 and related issues, I recall I struggled to find the meaning and interactions of the various `-native-compiler` options. Those behaviors have changed but are still not clearly documented, even in the 8.12 manual. There is a `-native-compiler` flag to `configure`, a `-native-compiler` argument to Coq (with different behavior), and the `native_compute` tactic, but the manual only documents the tactic and the [`-native-compiler yes` case](https://coq.github.io/doc/v8.12/refman/practical-tools/utilities.html?highlight=native%20compiler#precompiling-for-native-compute), but not the `-native-compiler ondemand` or `-native-compiler no` cases for `coqc` and `configure`.

**Comment by Blaisorblade** [comment]
BTW, #12550 confirms that I'm not the only one confused by the behavior of those flags.

**Comment by SkySkimmer** [comment]
Duplicate https://github.com/coq/coq/issues/12564

**Comment by Blaisorblade** [comment]
Thanks and sorry!
