### ISSUE TITLE
Cumulative definitional class should fail

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#12625]
ie
~~~coq
Polymorphic Cumulative Class x := y : nat.
~~~

**Comment by ppedrot** [comment]
Isn't definitional equality the ultimate form of cumulativity though?

**Comment by Janno** [comment]
I actually stumbled over this and wasted a good 10 minutes trying to figure out why `About` wasn't showing the usual sigils for cumulative universes. A warning would be nice at least.
