### ISSUE TITLE
Typeclass Search has issues with Set universes

### ISSUE THREAD

**Issue by Janno** [coq/coq#12623]
#### Description of the problem

In the code below, in the line marked with `Fail`, typeclass search is unable to find the instance `seq_one` despite types matching just fine (at least to the naked eye). Giving the instance explicitly works just fine.

```coq
Set Universe Polymorphism.

Axiom M : Type -> Prop.
Axiom raise : forall {T}, M T.

Inductive goal : Type :=
| AHyp : forall {A : Type}, goal.

Definition gtactic := goal -> M (False).

Class Seq (C : Type) :=
  seq : C -> gtactic.
Arguments seq {C _} _.

Instance seq_one : Seq@{Set _ _} (gtactic) := fun t2 => fun g => raise.

Fail Definition x1 : gtactic := @seq@{_ _ _} _ _ (fun g : goal => raise).
Definition x2 : gtactic := @seq@{_ _ _} _ seq_one (fun g : goal => raise).
```
I could not reduce this any further without making it fail for other reasons.

With the right incantation of options we can see the following unification failure (my file is called bug.v hence the universe names):
```
Debug: Starting resolution with 1 goal(s) under focus and 0 shelved goal(s) in only_classes mode, unbounded
Debug: 1: looking for (Seq@{bug.33 bug.31 bug.32} (forall x : goal@{bug.38}, M@{bug.39} ?T@{g:=x})) with backtracking
Debug: Starting unification
Debug: Seq@{Set bug.40 bug.41} gtactic@{bug.42 bug.43} ~= Seq@{bug.33 bug.31 bug.32} (forall x : goal@{bug.38}, M@{bug.39} ?T@{g:=x})
Debug: Seq@{Set bug.40 bug.41} ~= Seq@{bug.33 bug.31 bug.32}
Debug: Leaving unification with failure
Debug: 1.1: exact seq_one@{bug.23 bug.24 bug.25 bug.26} on [...]
```

I'll let the universe experts figure out what's going on.

I should mention that (if I haven't messed up again) this is responsible for one of the 3 failures that currently block #12449. With that PR, the instance `seq_one` will get its first universe minimized to `Set` automatically which then triggers this bug.

#### Coq Version
8.11, master

**Comment by mattam82** [comment]
This looks like a tricky interaction with impredicativity. Unification/inference seems to rule out too early that the sort of `fun g : goal => raise` can be `Prop`. I.e. the following works:

```coq
Definition x1 : gtactic := @seq@{_ _ _} _ _ ((fun g : goal => raise) : _ : Prop).
```

**Comment by SkySkimmer** [comment]
It looks like an impredicativity issue. If you do
~~~coq
Set Printing All. Set Printing Universes.
Check @seq (goal -> M False).
~~~
you get 
~~~coq
@seq@{u u0 u1} (forall _ : goal@{u2}, M@{u3} False)
(* u u0 u1 u2 u3 |=  *)
~~~
but with `@seq (goal -> _)` we get 
~~~coq
@seq@{u u0 u1} (forall _ : goal@{u2}, _)
(* u u0 u1 u2 |= u2 < u *)
~~~
and universes are implicitly `>= Set` so `Set < u`.

If you give the instance explicitly impredicativity is available in time to save us from imprecision. 
Without it we get `(fun g : goal => raise) : ?X6 : Type@{foo.33}` so we generate `?X9 : Type@{foo.36}` and `?X10 : Type@{foo.37}` such that `?X6 := forall x : ?X6, ?X9`, and `foo.33 >= foo.36, foo.37`.
Then we do `goal@{foo.38} == ?X6` so `foo.38 < foo.36 <= foo.33`. 
Then we continue and eventually get an unsolvable typeclass problem.

**Comment by mattam82** [comment]
The source of the problem is `define_evar_as_product` which forces the sort of `fun g : goal => raise` to be greater than the type of `goal` and `raise`, treating it predicatively. We would need to delay `max (i, j) <= k` constraints to handle this properly.

**Comment by mattam82** [comment]
That's another instance where sorts variables ranging over Prop would help then.

**Comment by SkySkimmer** [comment]
A workaround may be to have `Seq` be a cumulative record instead of a definitional class, however unification.ml does not use inductive cumulativity (and is the unification involved here).

**Comment by Janno** [comment]
> A workaround may be to have Seq be a cumulative record instead of a definitional class, however unification.ml does not use inductive cumulativity (and is the unification involved here).

I tried that and it leads to other random failures. :(

**Comment by SkySkimmer** [comment]
We can also explain by saying that `fun` does some bidirectionality, but isn't compatible with impredicativity (see @mattam82's comment on define_evar_as_product).
Adding a `: _` breaks the bidirectionality which is why it makes the definition pass.
