### ISSUE TITLE
Erroneous implicits-in-term warning

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#12651]
~~~coq
Set Warnings "+implicits-in-term".
Definition thing : forall {A}, A -> A := fun A a => a.
~~~
should not fail.

I'll make a patch.

**Comment by SkySkimmer** [comment]
Also `Definition thing : forall {A}, A -> A := fun [A] a => a.` should warn but currently doesn't.

**Comment by herbelin** [comment]
> ```coq
> Set Warnings "+implicits-in-term".
> Definition thing : forall {A}, A -> A := fun A a => a.
> ```

It was my original intention that it failed but the expression "incompatible declaration" in the message was obviously not clear enough.

This being said, it also makes sense to not warn/error in the case where what is "dropped" is not an explicit mark of implicitness, as you do in #12652.

> Also `Definition thing : forall {A}, A -> A := fun [A] a => a.` should warn but currently doesn't.

This should warn for sure.
