### ISSUE TITLE
retracting Require doesn't undo its effect

### ISSUE THREAD

**Issue by jonleivent** [coq/coq#12658]
Using Coq 8.12beta1,
Consider:
```Coq
Require FunInd.
Function foo(a b:nat) := a+b.
```
Within ProofGeneral, if this code is processed, then retracted and the `Require FunInd` is removed, then reprocessed, it accepts the definition of `foo` without emitting an error on its use of `Function` without `FunInd`.  In other words, retracting `Require FunInd` does not undo its effect.

**Comment by Zimmi48** [comment]
This is similar to #12575, except that in this case it seems to go beyond just parsing.

**Comment by Zimmi48** [comment]
FTR this issue is present since 8.7 (which introduced the separate `FunInd` module).

**Comment by SkySkimmer** [comment]
Fixed in 8.17
