### ISSUE TITLE
Elaboration/type inference should allow delaying constraints (or have a mode/option that does so)

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12659]
#### Description of the problem

Consider this code:
```coq
Check option_map (fun b => if b then 1 else 0) (Some true).
(* Error: Cannot infer a type for this expression. *)
```
It is complaining about the `b` in the `if` statement.    I tried all of 
```coq
Arguments option_map {_ _} & _ _.
```
```coq
Arguments option_map {_ _} _ & _.
```
```coq
Arguments option_map {_ _} _ _ & .
```
None of these allowed Coq to do type inference here.

cc ... @gares?

#### Coq Version

8.11.1

**Comment by SkySkimmer** [comment]
You would need to process arguments in a different order to make it work, that's not bidirectionality.

**Comment by gares** [comment]
IIRC, for this specific example, ssreflect provides a better "notation" for `if then else` that hints the type checker that the guard is a boolean (I don't recall which file/plugin):

```coq
Coq < Require Import ssreflect ssrfun ssrbool.
[Loading ML file ssrmatching_plugin.cmxs ... done]
[Loading ML file ssreflect_plugin.cmxs ... done]
Overwriting previous delimiting key bool in scope bool_scope

Coq < Check option_map (fun b => if b then 1 else 0) (Some true).
option_map (fun b : bool => if b then 1 else 0) (Some true)
     : option nat

```

**Comment by gares** [comment]
I guess something tricked you Jason. Maybe the doc about bidirectional hints is misleading? I see that in English it could mean "from both left to right and right to left" but in type inference "bidirectional" is pretty standard.

**Comment by gares** [comment]
Otherwise we can close the issue I guess.

**Comment by JasonGross** [comment]
Ah, okay, I guess I don't have a good understanding of BIDI, I should read up on it more.  In any case, I think this should then be turned into a more general feature request, to allow delayed constraints.  (I seem to recall this being an issue in `rewrite` matching too.)

**Comment by SkySkimmer** [comment]
This isn't a failing constraint, typechecking simply cannot proceed without knowing what inductive you are matching at.

**Comment by gares** [comment]
You could suspend the elaboration of the subterm `if .... ` until the type of `b` is know. This is what Jason is asking for, but this example is trivially solved by loading ssr, so I'm closing this issue
