### ISSUE TITLE
"Print Universes Subgraph" is slow with large dependencies loaded

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#12688]
#### Description of the problem

`Print Universes Subgraph` can take unreasonably long time, even though the same command may work fine with fewer imports. Of course one doesn't always have the luxury of a small dependency footprint, so it would be nice to be able to use this command with universes for things that do actually have large dependencies.

Minimal example:

```coq
Record my_mod: Type := mk { datatype: Type; }.
Print Universes Subgraph (my_mod.u0). (* OK *)
From ITree Require Export ITree.      (* using coq-itree for the sake of example *)
Print Universes Subgraph (my_mod.u0). (* Runs forever (> 1 min) *)
```

#### Coq Version

```
The Coq Proof Assistant, version 8.13+alpha (July 2020)
compiled on Jul 13 2020 21:04:48 with OCaml 4.10.0
```

**Comment by SkySkimmer** [comment]
Please test https://github.com/coq/coq/pull/12728

**Comment by SkySkimmer** [comment]
Also, if you run `Polymorphic Lemma foo : Type. exact Type. Qed.` after the Require, is the Qed slow?

**Comment by Lysxia** [comment]
Thanks, that fixes it.

> Also, if you run `Polymorphic Lemma foo : Type. exact Type. Qed.` after the Require, is the Qed slow?

No, `Qed` completes immediately, whether with or without that patch.
