### ISSUE TITLE
coqdoc links no longer work for Stdlib deployment

### ISSUE THREAD

**Issue by palmskog** [coq/coq#12699]
#### Description of the problem

In the Stdlib documentation, module names mentioned in `Require Import`s have previously been clickable, i.e., they are links that lead to the corresponding page for the module/file. However, these links have stopped working in Coq 8.12+beta1 and later.

Compare the following pages:
- https://coq.github.io/doc/V8.11.2/stdlib/Coq.Wellfounded.Wellfounded.html
- https://coq.github.io/doc/V8.12+beta1/stdlib/Coq.Wellfounded.Wellfounded.html
- https://coq.github.io/doc/master/stdlib/Coq.Wellfounded.Wellfounded.html

At the first URL, the modules names in sentences like:
```coq
Require Export Disjoint_Union.
```
are all HTML links. At the two other URLs, the same module names are not HTML links.

I don't know currently if this is an issue with coqdoc itself or with the options passed to coqdoc for generating Stdlib documentation.

#### Coq Version

Coq master, v8.12 and 8.12+beta1.

**Comment by Lysxia** [comment]
@herbelin did some work on coqdoc recently, that might have affected this.

**Comment by herbelin** [comment]
I would suspect an issue with building the stdlib on the web site, because, when built locally (`make doc-stdlib`), links are there, while, at the URLs given above, there are no links at all, even within a same file.

I don't know where is the recipe for exporting the stdlib to the web site.

**Comment by ejgallego** [comment]
Are the other links missing too, or only the import ones? There could be an issue with the dune rules for coqdoc.

**Comment by palmskog** [comment]
It seems like all the links are gone except the ones in the table of contents.

**Comment by ejgallego** [comment]
> It seems like all the links are gone except the ones in the table of contents.

Indeed that's a problem with the `*.glob` files; I need to address that :S 

Dune doesn't know about the produced `glob` files, so it cleans them up on rebuild. A workaround is to clean the `.vo` files; a fix is planned but it is pending on a refactoring of the handling of Coq flags themselves; Dune needs some logic to know how flags affect `.glob` file generation.

Meanwhile we can have the reference manual be built back with the non-hygienic rule.

**Comment by Zimmi48** [comment]
> Meanwhile we can have the reference manual be built back with the non-hygienic rule.

Yes, this is the simplest option for a short-term fix.

**Comment by ejgallego** [comment]
> Meanwhile we can have the reference manual be built back with the non-hygienic rule.

Not the reference manual but the coqdoc's stdlib part. The refman should be fine.

**Comment by SkySkimmer** [comment]
>Dune needs some logic to know how flags affect .glob file generation.

Can't we just say disabling glob files is illegal when using dune until it has the logic (so until then dune can assume they're always produced)?

**Comment by ejgallego** [comment]
> Can't we just say disabling glob files is illegal when using dune until it has the logic (so until then dune can assume they're always produced)?

Yup, but anyways I've written already all the flag hanlding code for native compute, glob, etc... I just need to push it upstream when I have a minute [really running short of time these last weeks :(]

**Comment by ejgallego** [comment]
This was fixed by #12712

**Comment by ejgallego** [comment]
Note that Rudi fixed this problem in dune 2.7.1, dune now will preserve `.glob` files.
