### ISSUE TITLE
[CI] base+async failure on bug_9517.v

### ISSUE THREAD

**Issue by gares** [coq/coq#12694]
I'm opening this issue to track this problem. I've seen this popping out from time to time, eg
  https://gitlab.com/coq/coq/-/jobs/639262132
error is
```
==========> TESTING bugs/closed/bug_9517.v <==========
File "./bugs/closed/bug_9517.v", line 12, characters 0-43:
Warning: This notation will not be used for printing as it is bound to a
single variable. [notation-bound-to-variable,parsing]
File "./bugs/closed/bug_9517.v", line 13, characters 14-15:
Error: Syntax error: [constr:expr] expected after '!' (in [constr:stmt]).

0m0.000000s 0m0.000000s
0m0.050000s 0m0.040000s
==========> FAILURE <==========
    bugs/closed/bug_9517.v...Error! (bug seems to be opened, please check)
```

I can't reproduce it locally and I can't see how "async-proofs" would have any impact on this test.

**Comment by herbelin** [comment]
This failure of `bug_9517.v` in #11841 is due to a change in #11841 itself, which I now fixed (the meaning of `x ident` is changed so that it excludes `_`, hence fails on parsing `_`). I don't think we need to look for an async-proofs problem.

**Comment by gares** [comment]
Good thanks!
