### ISSUE TITLE
CI performance-tests unstable

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#12703]
https://gitlab.com/coq/coq/-/jobs/643998903
https://gitlab.com/coq/coq/-/jobs/639687685
cc @JasonGross

**Comment by JasonGross** [comment]
No idea what's up with https://gitlab.com/coq/coq/-/jobs/643998903; maybe we are somehow making two simultaneous calls to `coq_makefile` and they are racing and writing invalid files?  The error message is
```
make[3]: *** No rule to make target 'perf-Sanity'.  Stop.
Makefile:59: recipe for target 'invoke-coqmakefile' failed
make[2]: *** [invoke-coqmakefile] Error 2
Makefile:62: recipe for target 'perf-Sanity' failed
make[1]: *** [perf-Sanity] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I'm similarly confused by https://gitlab.com/coq/coq/-/jobs/639687685, which is failing with
```
File "./rewrite_repeated_app_autorewrite_noop.v", line 2, characters 0-66:
Error: /builds/coq/coq/_build_ci/coq_performance_tests/PerformanceExperiments/rewrite_repeated_app_common.vo: premature end of file. Try to rebuild it.
```

I have, however, fixed the issue that is causing the same rule to be given multiple times, see https://github.com/coq-community/coq-performance-tests/issues/3

**Comment by JasonGross** [comment]
Actually, it seems like both of these might be races.  I believe the relevant race should hopefully be fixed by https://github.com/coq-community/coq-performance-tests/commit/759e3244e9404e6b5414340829eff3d1cfb2cd51.  Should we optimistically close this issue?
