### ISSUE TITLE
coqtop -time option produces messages containing exceptions and other strange things

### ISSUE THREAD

**Issue by jonleivent** [coq/coq#12711]
in 8.12beta1
The coqtop -time option can produce output such as:
```
Chars 8845 - 8871 [Top.??_#_7F404927~_~(*~Generic...] 0.004 secs (0.004u,0.s)
Chars 9101 - 9120 [Anomaly~"Uncaught~exception~No...] 0.008 secs (0.008u,0.s)
```
None of these messages appear when the same coq script is submitted to coqtop without the -time option.  Also, the execution of the script does not appear to be impacted despite the strange messages in the -time output.

**Comment by SkySkimmer** [comment]
Cannot reproduce: no example input

**Comment by jonleivent** [comment]
Here is a small example:
```Coq
Notation "!" := ltac:(tauto) (only parsing).

Example foo: True := !.
```
```
$ coqtop -time -batch -l timebug.v
Chars 0 - 44 [Notation~"!"~:=~_~(only~parsing).] 0. secs (0.u,0.s)
Chars 46 - 69 [Anomaly~"Uncaught~exception~No...] 0. secs (0.u,0.s)
```
The bug appears to have something to do with the unusual Notation.

**Comment by ejgallego** [comment]
The bug is likely due to print being called with the wrong environment + latest notation changes.

**Comment by SkySkimmer** [comment]
Cannot reproduce on master, I get
~~~
Chars 0 - 44 [Notation~"!"~:=~_~(only~parsing).] 0. secs (0.u,0.s)
Chars 46 - 69 [Example~foo~:~True~:=~!.] 0. secs (0.u,0.s)
~~~

Confirmed on 8.12.

**Comment by ejgallego** [comment]
Seems to work in `master` so IMHO we should close.
