### ISSUE TITLE
Serious coqdoc regression in 8.12+alpha

### ISSUE THREAD

**Issue by bcpierce00** [coq/coq#12742]
In 8.12+alpha, I am seeing the following misbehavior in list formatting: This source text

     (** The flow of ideas between logic and computer science has not been
         unidirectional: CS has also made important contributions to logic.
         One of these has been the development of software tools for
         helping construct proofs of logical propositions.  These tools
         fall into two broad categories:

            - _Automated theorem provers_ provide "push-button" operation:
              you give them a proposition and they return either _true_ or
              _false_ (or, sometimes, _don't know: ran out of time_).
              Although their capabilities are still limited to specific
              domains, they have matured tremendously in recent years and
              are used now in a multitude of settings.  Examples of such
              tools include SAT solvers, SMT solvers, and model checkers.

            - _Proof assistants_ are hybrid tools that automate the more
              routine aspects of building proofs while depending on human
              guidance for more difficult aspects.  Widely used proof
              assistants include Isabelle, Agda, Twelf, ACL2, PVS, and Coq,
              among many others.

typesets like this:

![image](https://user-images.githubusercontent.com/7014411/88345578-3aeef400-cd14-11ea-8489-c79014bb51fd.png)

This is a serious problem for Software Foundations.  Has it perhaps already been noticed and fixed??

**Comment by ejgallego** [comment]
Possible problematic commits:
- 52145601d33ee3fa81ed3e291f2e4db1c6c1d622

**Comment by bcpierce00** [comment]
Really?  From the comments, this seems to be about underscores, not dashes…

    - B

**Comment by Zimmi48** [comment]
I don't recall this issue being reported before. @coq/coqdoc-maintainers any idea of how to fix this very quickly? We were about to tag 8.12.0...

**Comment by herbelin** [comment]
Reverting 41a1d667f4783635e1332b45a6688078711b3907 seems to restore the previous behavior. I'm in meetings up to 5pm CEST, so I'll probably have no time to fix this commit.

**Comment by herbelin** [comment]
If someone wants to look at, the count of `check_start_list` seems wrong (it should find 8 while it now finds 0, thus believing that the second `-` is more indented than the first one).

**Comment by SkySkimmer** [comment]
Looks like this works
~~~diff
@@ -728,7 +728,7 @@ and doc_bol = parse
           else
             Output.section lev (fun () -> ignore (doc None (from_string s)));
 	    if eol then doc_bol lexbuf else doc None lexbuf }
-  | (space_nl* as s) ('-'+ as line)
+  | ((space_nl* nl)? as s) (space* '-'+ as line)
       { let nl_count = count_newlines s in
         match check_start_list line with
           | Neither -> backtrack_past_newline lexbuf; Lexing.new_line lexbuf; doc None lexbuf
~~~
