### ISSUE TITLE
coqdoc: notations are not escaped in the index

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#12752]
#### Description of the problem

Notations are not escaped in the generated `index.html`; this produces invalid HTML when symbols forbidden in HTML such as  `<` and `>` are involved:

```coq
Notation "x '+' y" := (and x y).
Notation "x '<' y" := (and x y).
Notation "'<h1>' 'Hello' 'there' '</h1>" := 0 (at level 200).
```

The third notation with `<h1>` gets interpreted in HTML:

![notation](https://user-images.githubusercontent.com/2515201/88413277-e5b0f200-cda8-11ea-92e8-e9d54e4ce61b.png)

#### Coq Version

```
This is coqdoc version 8.13+alpha, compiled on Jul 24 2020 13:24:11
```

**Comment by herbelin** [comment]
Should be fixed by #12754.

Question in passing: wouldn't it be more intuitive to output double quotes around the notation string in the index? Or is it better, and lighter, as it is?

**Comment by Lysxia** [comment]
I don't see the difference in intuitiveness quotes would make

**Comment by herbelin** [comment]
I was asking because when manipulating notations (in the `Notation` command, in the `Print` command, e.g. `Print "_ + _"`) double quotes are used. But if this is not shocking for you, let's keep it as it is, since it is lighter. Thanks for your feedback.
