### ISSUE TITLE
Renamed arguments get misaligned after closing doubly nested sections

### ISSUE THREAD

**Issue by jashug** [coq/coq#12755]
#### Description of the problem

When `Global Arguments ... : rename` is used within a section within another section, when the outer section is closed the names get messed up.

```coq
Section A.
Context {a : nat}.
Section B.
Context {b : nat}.

Definition foo (eq1 : a = a) (eq2 : b = b) (c : nat) : c = c := eq_refl.
Global Arguments foo _ _ d : rename.

End B.
About foo.
(*
foo : forall {b : nat}, a = a -> b = b -> forall c : nat, c = c
Arguments foo {b}%nat_scope eq1 eq2 d%nat_scope : rename
*)

End A.
About foo.
(*
foo : forall {a b : nat}, a = a -> b = b -> forall c : nat, c = c
Arguments foo {a eq1}%nat_scope eq2 d _%nat_scope : rename
*)

Check foo (eq1 := 3) (eq_refl 2) (eq_refl 3) 4.
```

See above how after `End A` the name `b` is dropped and all the names are shifted one place to the left.

#### Coq Version

Coq master https://github.com/coq/coq/commit/55f4095fe3c366a9f310584a55e2dc0605e5409c, but also appears to have existed for the past 9 years since the renaming feature was introduced in https://github.com/coq/coq/commit/39fd2b160dbbd6411dd05f52984f198338de300a.

#### Root cause

https://github.com/coq/coq/blob/55f4095fe3c366a9f310584a55e2dc0605e5409c/pretyping/arguments_renaming.ml#L46-L51

Here we only prepend the most recent section's variables to the list of original names.

**Comment by herbelin** [comment]
Fixed in #18393.
