### ISSUE TITLE
[request] Add a warning for non-underscore catchall cases

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12762]
Suppose I have the code
```coq
Inductive foo := a | b.

Definition bar (f : foo) :=
  match f with
  | a => 0
  | B => 1
  end.
```
This is fine, but if I extend the inductive with `| c`, then Coq won't tell me that I need to extend the `match`.  I propose that a warning is emitted in cases where there is a named catch-all case for a `match` where the variable is unused in the branch (so, e.g., `match f with a => b | B => B end` wouldn't trigger the warning).

**Comment by JasonGross** [comment]
Note, btw, that this came up in the wild in fiat-crypto: https://github.com/mit-plv/fiat-crypto/commit/e9ff2d0df975bf740a17fc103ecb22dac980e505
When transcribing a `match` from a different file, we forgot to qualify `TT` into `IR.TT`, resulting in what was previously a constructor becoming a catch-all case.

**Comment by proux01** [comment]
Note that this could have prevented #12483

**Comment by Zimmi48** [comment]
Maybe the new warning should be clearer on its rationale. Two users were wondering about it in https://github.com/coq-community/hydra-battles/pull/18. Suggestions for improving the message are welcome!
