### ISSUE TITLE
CoqIDE crashes on macOS with "coq-8.12.0-installer-macos.dmg"

### ISSUE THREAD

**Issue by orilahav** [coq/coq#12776]
On macOS, running the CoqIDE_8.12.0 application (installed from the supplied dmg) crashes immediately.

Using a terminal, I can see:

~ % /Applications/CoqIDE_8.12.0.app/Contents/MacOS/coqide
Don't know what to do with --xml_format=Ppcmds
See -help for the list of supported options

Must be something wrong with my configuration or related to previous installations (same thing did work on my laptop), but can't figure out what exactly.

**Comment by Zimmi48** [comment]
Which version of macOS do you have? This installer unfortunately requires macOS 10.13 or higher. We should probably document this in the release notes.

**Comment by orilahav** [comment]
10.15.6 (both in laptop where it worked out of the box, and in the desktop where it fails).

**Comment by herbelin** [comment]
Hi, could you try `/Applications/CoqIDE_8.12.0.app/Contents/MacOS/coqide -debug`?

**Comment by orilahav** [comment]
% /Applications/CoqIDE_8.12.0.app/Contents/MacOS/coqide -debug
(Spawn  ,77775) EXEC: coqtop -main-channel stdfds --xml_format=Ppcmds -async-proofs on -debug
(Spawn  ,77775) PID 77778
Don't know what to do with --xml_format=Ppcmds
See -help for the list of supported options
[DEBUG] Start eval_call Init None
[DEBUG] Starting emergency save of buffers in .crashcoqide files
[DEBUG] End emergency save

**Comment by herbelin** [comment]
That's strange. It should call `/Applications/CoqIDE_8.12.0.app/Contents/Resources/bin/coqidetop.opt`. Your preference file is probably broken. What do you have at line `cmd_coqtop` of your `coqiderc` file (in `~/.config/coq/`)? It should be `cmd_coqtop =` (no arguments).

At worst, erase your `coqiderc` to rebuild it from scratch.

**Comment by orilahav** [comment]
had:
`cmd_coqtop =`
erased the file, but nothing changes.
Are there other preferences to look at?

**Comment by herbelin** [comment]
Does it fail only in the terminal, i.e. does it work if you click on it (or if you do `open /Applications/CoqIDE_8.12.0.app`)?

A workaround could be to do `/Applications/CoqIDE_8.12.0.app/Contents/MacOS/coqide -coqtop /Applications/CoqIDE_8.12.0.app/Contents/Resources/bin/coqidetop.opt`.

**Comment by orilahav** [comment]
It fails also if I click on the application (or open the .app).
I tried from the terminal just to get the error message.

Your workaround works; although, I need to run the app directly for using "low resolution" (cf. https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/CoqIDE.20slowness.20on.20macOS).

**Comment by ejgallego** [comment]
The problem is that coqide is finding an old coqtop and using it, likely from 8.9 or so.

**Comment by ejgallego** [comment]
Likely if doesn't find it so it uses the one in path?

**Comment by herbelin** [comment]
But it is supposed to look for `coqidetop`, not `coqtop`, no (or am I becoming blind)?

**Comment by ejgallego** [comment]
I see your point, so indeed `coqtop` has to be set in some configuration variable I think.

**Comment by Blaisorblade** [comment]
If it's because of some environment variable, @orilahav could try clearing the environment with 
```
env -v -i HOME=$HOME/Applications/CoqIDE_8.12.0.app/Contents/MacOS/coqide
```

**Comment by Blaisorblade** [comment]
However, it'd be strange if this were set in environment variables (as opposed to user settings), because on Mac starting app from icons uses a rather clean environment. That could be tested by @orilahav creating a new user to their system and starting CoqIDE from that user.

**Comment by orilahav** [comment]
A new user worked.

I removed whatever I could find in my user settings:
 rm -fr Library/Application\ Support/*coq*
 rm -fr Library/ApplicationSupport/*coq*
 rm -fr Library/Saved\ Application\ State/*coq*
And now it works!

Thanks for the help! Not sure how I reached this unique misconfiguration.

**Comment by Blaisorblade** [comment]
Do you know which was your previous CoqIDE version? Maybe the config used to be valid before.
CoqIDE might want to log configuration loading (from files and variables) under -debug. Some programs (like Emacs) add options to ignore all config files, but adding more logging (so the user can fix things themselves) might be easier.

**Comment by orilahav** [comment]
I had 8.9.1 before.
(But I had the same previous version on the laptop, where I didn't encounter this problem)

**Comment by Zimmi48** [comment]
Should we close or do you @herbelin want to leave this open to try to make CoqIDE updates more robust? Maybe @orilahav is also willing to do more testing if necessary.
