### ISSUE TITLE
Int63 numbers are not captured by patterns in proofs

### ISSUE THREAD

**Issue by mgbedmar** [coq/coq#12770]
#### Description of the problem

Trying to capture an Int63 number X in a proof using a pattern fails with `Error: term X does not match any subterm in the goal`.

Example:

`Require Import Int63 ssreflect ssrfun ssrbool.`

`Lemma test : 43%int63 = (42 + 1)%int63.`
`Proof. set X := 43%int63. (* does not capture int63 *)`

#### Coq Version
Coq 8.11.2

**Comment by ppedrot** [comment]
`set` uses the legacy unification engine, so it's probably been forgotten to add the relevant parts in there.

**Comment by gares** [comment]
This is about the `set` of SSR, which uses ssrmatching that has never been ported to the new term constructors.
I guess it is sufficient to fix this: 
https://github.com/coq/coq/blob/e0b8b4684eaf76f897ac708ffddbb8e4977ac754/plugins/ssrmatching/ssrmatching.ml#L360-L362
and return `true` also on native int/float/arrays
