### ISSUE TITLE
lia regression on type alias

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#12791]
#### Description of the problem
The combination of a type alias for `nat` with a `let` construct makes the following example fail in 8.12:
```
Require Import Lia.

Definition t := nat.

Goal forall (a b: t), let c := a in b = a -> b = c.
Proof.
intros a b c H.
lia. (* this fails *)
```
However, it worked fine in Coq 8.11.2.

Maybe this is related to #11089

#### Coq Version
The Coq Proof Assistant, version 8.12.0 (July 2020)
compiled on Jul 24 2020 19:04:25 with OCaml 4.07.1

**Comment by Zimmi48** [comment]
Thanks for the report. This is likely related to #11370 or #11429. cc @fajb

**Comment by fajb** [comment]
The elimination of `let` was only performed when the type is declared to be injected into `Z`.
PR #12814 solves the issue by performing a convertibility check. Let's hope this is not too costly.
