### ISSUE TITLE
lia regression when adding an irrelevant term

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#12790]
#### Description of the problem
`lia` fails when adding an irrelevant non-linear term. For example:
```
Require Import Lia.

Goal forall (a b c d x: nat), 
S c = a - b -> x <= x + (S c) * d.
Proof.
intros a b c d x H.
lia. (* this fails *)
```
The above example does not have this issue in Coq 8.10.2.

#### Coq Version 
The Coq Proof Assistant, version 8.12.0 (July 2020)
compiled on Jul 24 2020 19:04:25 with OCaml 4.07.1

**Comment by Zimmi48** [comment]
This is a regression between 8.10 and 8.11. cc @fajb

**Comment by fajb** [comment]
Thanks for the report.
PR #12815 should solve the issue.

`lia` was applying the substitution c = a - b - 1
After that, `lia` was unable to deduce that  (S c) * d was positive.
The workaround is to deduce  c * d >= 0 before substituting.
