### ISSUE TITLE
Need a way to support commands accessing Stm history in XML interface

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12800]
Currently there are a few commands that access `Stm` history that are only available in `coqtop` and in Proof General (which uses `coqtop`) but not CoqIDE.  These are `Show Proof Diffs` (diffs on the `Show Proof` output) and `Show Goal`, which are executed in `Coqloop.process_toplevel_command`.  There's also an open issue #10020 to show diffs in the proof context in the `Show` command that might require handling that command similarly.

I'd like to address this in 8.13, adding support for these in the XML interface if not `coqtop` as well.  IIUC, @erikmd has someone working on finishing up the previously stalled XML interface for PG.  Losing support for these commands in PG with XML would delay the adoption and perhaps the completion of the PG XML changes.  Erik et al already added an optional window in PG to automatically display the `Show Proof Diffs` output for use in teaching Coq.

In #10020 I suggested a simple approach that @ejgallego doesn't like that a couple of the other developers thought was reasonable.  I don't mind doing something a bit different, but it's not reasonable to say that XML interface operations can never access Stm history.

@ejgallego how do you suggest we address this?  Perhaps we can figure it out in this issue.  If need be, we can discuss on a call when those resume in September.

cc: @gares

**Comment by gares** [comment]
I'm OK with adding messages to the XML protocol, but I don't think I'll have time for this.
The starting point would be to propose a patch for the ML data type here:
https://github.com/coq/coq/blob/ef08abec26c2f0017d1136870f8f99144e579538/ide/coqide/protocol/interface.ml#L239-L250
the the compiler will help you patch the code that needs to be patched.

**Comment by jfehrle** [comment]
Working on this now.  Given that I'm supporting 3 additional commands (Show Proof Diffs, Show Goal and Show) and that each takes about 20 changes to `xmlprotocol.ml`, is it reasonable to have these share a single handler that accepts a command?  Then I'd use `g_toplevel.mlg` to parse and filter to only accept these 3 commands.

Also, can I use `fake_ide` for testing?  Not sure if it still works or exactly what input it expects.  I'd like to see the return values.  I'm not able to build and run a modified CoqIDE right now to test my protocol addition.  When I run the test suite locally, it hangs on `TEST      ide/load.fake`

```
$ bin/fake_ide test-suite/ide/load.fake
Running: bin/coqidetop.opt --xml_format=Ppcmds
[pid 21367] Unexpected XML message
[pid 21367] Expected XML node: unit
[pid 21367] XML tree received: <option val="none"/>
^C
$ bin/fake_ide - test-suite/ide/load.fake
Running: bin/coqidetop.opt --xml_format=Ppcmds test-suite/ide/load.fake
[pid 24375] Unexpected XML message
[pid 24375] Expected XML node: unit
[pid 24375] XML tree received: <option val="none"/>
^C
```

**Comment by gares** [comment]
>  is it reasonable to have these share a single handler that accepts a command?

I guess so

> Also, can I use `fake_ide` for testing? Not sure if it still works or exactly what input it expects.

Yes you should, and you should add "commands syntax" for your new protocol messages, so that you put calls to your new messages in the .fake files and test how they behave.

I'm not sure I can help you on the error without your patch at hand. It seems a message that used to carry nothing (unit) is now carrying an option type... You can uncomment this code to debug this:
https://github.com/coq/coq/blob/daed771ff18978dea536b277e00c0ca0149129ee/ide/coqide/idetop.ml#L521-L526

**Comment by gares** [comment]
Sorry, the comments should be dropped. You can instead pass `-debug` (see `pr_debug_call` and `pr_debug_answer`).

**Comment by jfehrle** [comment]
My problem was that the index in `id_of_call` didn't match the order or my added entry in `calls`, so the `Init` got mapped to `About`.

Uncommenting line 521 above still works, BTW.

I finally got X Windows to work with Windows/WSL2, so I can now build and run CoqIDE in Ubuntu.  (There were several sets of instructions on how to set up the internal firewall to allow access, none of which worked for me.)

**Comment by jfehrle** [comment]
> > Also, can I use `fake_ide` for testing? Not sure if it still works or exactly what input it expects.
> 
> Yes you should, and you should add "commands syntax" for your new protocol messages, so that you put calls to your new messages in the .fake files and test how they behave.

As I mentioned, I haven't been able to get fake_ide to do anything useful.  Any ideas on that?

**Comment by gares** [comment]
No idea. It must be because of your setup since it is used by the test suite. Can you successfully run make test-suite?
