### ISSUE TITLE
Declaring Ltac2 Notation infix operators breaks everything

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12808]
#### Description of the problem

```coq
Require Import Ltac2.Ltac2.

Ltac2 Notation x(tactic) "+++" y(tactic) : 6 := x; y.
Ltac2 Notation x(tactic) "+++2" y(tactic) := x; y.
(* Error:
Syntax error: '+++' expected after [tactic:tac2expr level 5] (in [tactic:tac2expr]).
*)
```

#### Coq Version

8.11

**Comment by jfehrle** [comment]
`Ltac2 Notation x(tactic) "+++" y(tactic) : 999 := x; y.` is accepted without complaint.  That seems like a bug.

I take it that the 6 is the precedence for the notation, right?  What about right and left associativity and the other things defined in `syntax_modifier`?
