### ISSUE TITLE
Give user-friendly message for Ltac2 identifier that's not in lowercase

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12804]
The following definition:

```
   Ltac2 msg S(string) := print (of_string S).
```

gives the error `Unbound constructor S`.

Can this be changed to something more user-friendly like "Ltac2 identifiers must begin with a lowercase letter"?  I think the check would belong in the action for `syn_node` and maybe other places.

**Comment by ppedrot** [comment]
I don't think it's a good idea, the current error message is more informative than what you propose, and is semantic while your message is about syntax. Also, judging from the way you wrote it, I am not sure what you tried to write, because even with a lower-case ident, the parentheses do not correspond to anything meaningful here and can be dropped.

**Comment by JasonGross** [comment]
I think there is a bit of confusion here.  @jfehrle Note that the following parses and works fine:
```coq
Require Import Ltac2.Ltac2.
Ltac2 Type t := [ S ].
Ltac2 foo S := let x := S in ().
```
This is akin to
```coq
Require Import Ltac2.Ltac2.
Ltac2 foo () := ().
```
for matching on single-constructor types in the argument to a function.

However, @ppedrot I believe that this should be a syntax error, while currently it is accepted:
```coq
Require Import Ltac2.Ltac2.
Ltac2 Notation "foo" S(constr) := ().
```

**Comment by ppedrot** [comment]
> However, @ppedrot I believe that this should be a syntax error

I agree.

**Comment by jfehrle** [comment]
@JasonGross What does this mean?  "foo S" looks like defining a tactic with a single parameter.

```
Ltac2 Type t := [ S ].
Ltac2 foo S := let x := S in ().
```

**Comment by JasonGross** [comment]
In Gallina, it'd be written `Definition foo := fun 'S => ...`.  The more general form would be something like
```coq
Require Import Ltac2.Ltac2.
Ltac2 Type 'a box := [ Box ('a) ].
Ltac2 unbox (Box v) := v.
```

**Comment by JasonGross** [comment]
It's destructuring/matching on a constructor

**Comment by jfehrle** [comment]
It's new to me.  There's no direct equivalent in OCaml or Ltac1, is there?  There's no description yet of how patterns are handled in the `Ltac2 definitions` section.  How do you distinguish between a regular formal parameter and a constructor--is it solely by whether it's upper or lower case?

If `tac2pat*` can be explained briefly I will add that, but I don't want to spend a lot of time on that in the Ltac2 doc PR.

**Comment by ppedrot** [comment]
> There's no direct equivalent in OCaml

There is. OCaml has a notion of "irrefutable patterns" that can be bound as if they were variables, e.g. `fun (x, y) -> t`.

> There's no description yet of how patterns are handled

The prelude of the Ltac2 documentation mentions it's a ML, so up to the actual syntax details, there is nothing surprising in that respect.

**Comment by JasonGross** [comment]
> How do you distinguish between a regular formal parameter and a constructor--is it solely by whether it's upper or lower case?

Yes

**Comment by jfehrle** [comment]
> There is. OCaml has a notion of "irrefutable patterns" that can be bound as if they were variables, e.g. `fun (x, y) -> t`.

How would anyone know?  The word "irrefutable" doesn't appear in the 4.10 manual, nor does section 7.6 "Patterns" mention anything that appears to relate to that.

Back to Coq.  The Extended pattern matching chapter mentions irrefutable patterns in Gallina in the context of the `Definition` command.  Not the clearest description but somewhat helpful.  The first desugaring pattern is supported identically for Gallina, Ltac1 and Ltac2?  Looks like the second one (with `'p` is only supported in Gallina--is that how it should be?

BTW, I was wondering where this production of `constr` in `Print Grammar constr` comes from?  I see where the notation is reserved but I don't see where it's fully defined for use in type constructors.

```
| "40" LEFTA
  | SELF; "*"; NEXT ]
```

> The prelude of the Ltac2 documentation mentions it's a ML

Ah, that's not good enough for a reference manual.  Knowing ML shouldn't be a prerequisite for using Coq.  Nor should the reader need to search the web to learn about patterns.

**Comment by ppedrot** [comment]
I am closing this issue. @jfehrle you complaint about a comprehensive documentation of the Ltac2 syntax is valid, but it's quite unrelated to the original problem. You should probably make it a point of one of the generic issues you've already opene.
