### ISSUE TITLE
[extraction] Some top-level `Coq__*` definitions are used but not defined.

### ISSUE THREAD

**Issue by Mbodin** [coq/coq#12813]
#### Description of the problem

This bug is an almost exact clone of #2904, but on a much more recent version of Coq (8.10.1 instead of 8.4).
I’ve got a very large code base here, and it is difficult to reduce it, so I’m going to provide as many details as I can.
During an extraction the following snippet is generated Line 15 369:
```ocaml
module type Executable_Host =
 sig
  type host_function

  val host_function_eq_dec : host_function -> host_function -> bool

  type 'x host_event

  val host_ret : 'a1 -> 'a1 host_event

  val host_bind : 'a1 host_event -> ('a1 -> 'a2 host_event) -> 'a2 host_event

  val host_apply :
    host_function store_record -> host_function -> value0 list ->
    (host_function store_record * result) option host_event
 end

module Coq_convert_to_executable_host =
 functor (H:Executable_Host) ->
 struct
  type executable_host = H.host_function Coq__3.executable_host

  type store_record = H.host_function Coq__4.store_record

  (** val host_monad : __ H.host_event monad **)

  let host_monad =
    { ret = (fun _ -> H.host_ret); bind2 = (fun _ _ -> H.host_bind) }

  (** val executable_host_instance : executable_host **)

  let executable_host_instance =
    { Coq__5.host_monad = (Obj.magic host_monad); host_apply =
      (Obj.magic H.host_apply) }

(* ... *)

end
```
The issue is with this last definition `executable_host_instance`: `Coq__5` is used, but is never declared. This is the only usage of `Coq__5` across the 18 710 extracted lines. No instance of `Coq__5` appear in the `mli` file.

Note that the other `Coq__*` instances are both used and defined. For instance, in the `mli` file:
```ocaml
module Coq__4 : sig
 type 'host_function store_record = { s_funcs : 'host_function
                                                function_closure list;
                                      s_tables : tableinst list;
                                      s_mems : memory list;
                                      s_globals : global list }
end
include module type of struct include Coq__4 end
```
and in the `ml` file:
```ocaml

module Coq__4 = struct
 type 'host_function store_record = { s_funcs : 'host_function
                                                function_closure list;
                                      s_tables : tableinst list;
                                      s_mems : memory list;
                                      s_globals : global list }
end
include Coq__4
```

The source-code can be found here: https://github.com/WasmCert/WasmCert-Coq/tree/8149f89bd868f7be112d4e56bc10f1fc0321f39f
The issue has been reproduced in a third-party: https://travis-ci.org/github/WasmCert/WasmCert-Coq/jobs/716509579#L608
The source code is quite large. I can try minimising the code if needed.

The place of the Coq equivalent of the snippet above can be find there: https://github.com/WasmCert/WasmCert-Coq/blob/8149f89bd868f7be112d4e56bc10f1fc0321f39f/theories/host.v#L96

It is very difficult for me to understand what differentiate `Coq__5` (which is not extracted) from `Coq__3`.
If this is some help, here are where each of the `Coq__*` are used:
- `Coq__1` and `Coq__2` are both used in an unparameterised module (`Pos` and `TProp`).
- `Coq__3` and `Coq__5` are used in a parameterised module (that thus gets extracted to a functor). The Coq version of the module is called `convert_to_executable_host` and the OCaml one `Coq_convert_to_executable_host`.
- `Coq__4` is both used in a parameterised module (the same than `Coq__3` above) and an unparameterised one (`DummyHost`).
So it seems that `Coq__3` and `Coq__5` are very close one to each other, and yet one gets extracted and not the other.

Actually, looking further, it seems that `Coq__5` should be `Coq__3`!
`Coq__3` is defined as follows:
```ocaml
module Coq__3 = struct
 type 'host_function executable_host = { host_monad : __ monad;
                                         host_apply : ('host_function
                                                      store_record ->
                                                      'host_function ->
                                                      value0 list -> __) }
end
include Coq__3
```
It contains both the record declaration `executable_host` and its field `host_monad`… which what Coq meant to refer in `Coq__5.host_monad`. It seems that adding a line `module Coq__5 = Coq__3` after the definition of `Coq__3` solves the issue. Is this possible that `Coq__3` and `Coq__5` got mixed-up during the extraction?

#### Coq Version

```bash
$ coqc --version
The Coq Proof Assistant, version 8.10.1 (June 2020)
compiled on Jun 1 2020 17:32:00 with OCaml 4.08.1
```

**Comment by Mbodin** [comment]
I wanted to test my theory that the issue was that there were several values that were defined from the same module, and Coq only extracts one. In doing so, I found a minimal example:
```coq
Record test := make_test {
    proj1 : nat ;
    proj2 : nat
  }.

Module M.

Definition test := 1.
Definition proj1 := 2.
Definition proj2 := 2.

Definition test2 := make_test proj1 proj2.

End M.

From Coq Require Extraction.

Extraction Language OCaml.

Extraction "extract" M.
```

This file produces the following `mli` file, which is fine:
```ocaml
type nat =
| O
| S of nat

type test = { proj1 : nat; proj2 : nat }

module M :
 sig
  val test : nat

  val proj1 : nat

  val proj2 : nat

  val test2 : test
 end
```
And the following `ml` file, which is clearly wrong:
```ocaml
type nat =
| O
| S of nat

type test = { proj1 : nat; proj2 : nat }

module M =
 struct
  (** val test : nat **)

  let test =
    S O

  (** val proj1 : nat **)

  let proj1 =
    S (S O)

  (** val proj2 : nat **)

  let proj2 =
    S (S O)

  (** val test2 : test **)

  let test2 =
    { Coq__1.proj1 = proj1; Coq__2.proj2 = proj2 }
 end
```

This example is quite small. I’ve seen in https://github.com/coq/coq/pull/12429#issuecomment-662632889 that there will be some changes planned in the extraction. What about adding this minimal example in the test suite?

**Comment by Mbodin** [comment]
I just ran the example above in Coq 8.12 and got the exact wrong output.
```bash
$ $ coqc --version
The Coq Proof Assistant, version 8.12.0 (August 2020)
compiled on Aug 10 2020 15:14:23 with OCaml 4.10.0
```

**Comment by Mbodin** [comment]
OK. I think that I understand how to fix the issue.
In the function `add_duplicate` (defined in https://github.com/coq/coq/blob/master/plugins/extraction/common.ml#L319 ), we need to check first if it is not a projection. If it is, then we need to add a duplicate on the related type, and return the built duplicate. I’m trying to understand how to do this properly.

**Comment by Mbodin** [comment]
Note that I added a test in a commit above. This test is not nice as it only checks whether Coq runs fine, not whether the output of the extraction is accepted by OCaml. I don’t know how to write tests that call OCaml. Can somebody help? ☺

**Comment by jashug** [comment]
You can use the command `Extraction TestCompile M.`, documented [here in the reference manual](https://coq.inria.fr/refman/addendum/extraction.html#coq:cmd.extraction-testcompile).

Using that command fails on your example, reproducing this bug on my computer.

**Comment by Mbodin** [comment]
Oh, thanks! I wasn’t aware of this ☺ This is exactly what I was looking for.
