### ISSUE TITLE
Ltac2's exact is less powerful than Ltac1's exact

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12827]
#### Description of the problem

```coq
Existing Class True.
Existing Instance I.
Goal True. exact _. Qed.
Require Import Ltac2.Ltac2.
Require Import Ltac2.Notations.
Goal True. exact _. (* Error: Cannot infer this placeholder of type "True" (no type class instance
found).
*)
```
Perhaps `exact` needs to take `preterm` or whatever the Ltac2-equivalent of `uconstr` is and typecheck it with respect to the goal?

cc @ppedrot, is this solvable as Ltac2 currently stands, or do we need new primitives / types?

#### Coq Version

8.11

**Comment by Janno** [comment]
`lazy_match! goal with [ |- ?g ] => let evar := open_constr:(_ : $g) in exact $evar end` should work.

**Comment by Janno** [comment]
Oh, I realize the example is maybe a tad too minimal: you are looking for a way to allow arbitrary `_` in the term?

**Comment by JasonGross** [comment]
Yes, and to write a tactic / tactic notation that has this behavior.

**Comment by ppedrot** [comment]
Indeed, exact should probably take a `preterm`. We don't have a lot of API for those yet, so before making these changes it might be better to implement the former.

**Comment by ppedrot** [comment]
Note that since then, the OCaml exact tactic was modified to take a glob_constr indeed. It's mostly a matter of exposing that to the Ltac2 world.
