### ISSUE TITLE
Can numeral notation parsing/printing use vm_compute?

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#12828]
I have an issue with numeral parsing: when I put an OCaml trace at `Cbv.norm_head` I also get tracing of the numeral parsing, which seems to be terribly complicated. E.g. the trace for parsing the linear natural number "32" runs for almost *6 minutes* (on a decent CPU).
```
coqtop.byte
Drop.
#use "base_include";;
#trace Cbv.norm_head;;
go();;
Set Printing All.
Time Eval cbv in 32.
     = S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S ...)))))))))))))))))))))))
     : nat
Finished transaction in 342.399 secs (336.516u,0.411s) (successful)
```
This makes it harder to debug cbv issues (which I run into quite frequently). The solution is of cause to input and output terms without notations, but I wonder if one can't use vm_compute for numeral parsing. Since this seems to be complicated, this might anyway be a good idea. Also the input and output of numeral parsing should be simple, so the overhead for vm_compute should be small.
```
coqtop -v
The Coq Proof Assistant, version 8.12.0 (August 2020)
compiled on Aug 10 2020 18:01:35 with OCaml 4.07.1
```

**Comment by ppedrot** [comment]
We can have a try, but we need a good bench test for it. That said, I would be surprised if that would bring any gain. I'd bet that the overhead of vm_compute is likely to vastly exceed the gain in speed. Notations are typically reducing a lot of small terms where the bottleneck is not the reduction speed but the constant costs of change of representation.

**Comment by ppedrot** [comment]
Also, if you have a reproducible slow parsing term I'd be curious to have a look. The cbv machine deals poorly with a lot of binders in the context (O(n) variable access), but apart from that it should be algorithmically quick.

**Comment by MSoegtropIMC** [comment]
I guess one can profile the parser functions with cbv and vm_compute without actually doing the change. I was just astonished that tracing the parsing of 32 takes much longer than some rather involved computations.

Btw.: I meanwhile got around this: the obvious solution is not to use Eval but first parse and store the term, than enable the trace and then call cbv.

**Comment by MSoegtropIMC** [comment]
> Also, if you have a reproducible slow parsing term I'd be curious to have a look. The cbv machine deals poorly with a lot of binders in the context (O(n) variable access), but apart from that it should be algorithmically quick.

As I said: "32" takes 6 minutes with tracing on. I can count the number of times it went through Cbv.norm_head if this is interesting.

**Comment by JasonGross** [comment]
We cannot use the vm because it fails to fully reduce arguments to constructors that are parameters.  This is not much of an issue for the numeral notations shipped by the standard library, but it will be an issue for some numeral notations.  See https://github.com/coq/coq/issues/9840#issuecomment-477742419 and https://github.com/coq/coq/pull/9874, as well as the comment in the code: https://github.com/coq/coq/blob/a9786e88c8afe03cbe85cffbcce2767bd655048d/interp/notation.ml#L522-L526

**Comment by ppedrot** [comment]
@JasonGross this should be easy to tweak in the normalization algorithm though.

**Comment by JasonGross** [comment]
I'd be slightly worried about compatibility/performance, but if indeed this can be tweaked (perhaps a user-level setting for the default, and the ability to override that default when calling from OCaml/Ltac2?), then indeed the vm can be used for numeral notations

**Comment by ppedrot** [comment]
> I'd be slightly worried about compatibility/performance

It won't affect VM conversion, but it's true that for PHOAS it's probably going to be catastrophical...

> the vm can be used for numeral notations

@MSoegtropIMC your example is motivated by debug printing, but do you actually have an instance where vanilla Coq printing is prohibitively slow? Otherwise I don't think we should even try switching to the VM (let alone add parameter reduction to it).

**Comment by MSoegtropIMC** [comment]
> but do you actually have an instance where vanilla Coq printing is prohibitively slow?

The cbv trace of parsing 32 looks a bit suspicious, but I will have opportunity to test this when I test @VincentSe 's reals.

Since I meanwhile found a way to live with the status quo (first define terms, then enable the trace then call cbv), I close this for now.
