### ISSUE TITLE
"Ltac2 Notation" corner case

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12826]
You can make a mess with `Ltac2 Notation`.

```
Ltac2 Notation c(tactic) "match" := print (of_string "xx").
Ltac2 x s := print (of_string s).

(* Syntax error: 'match' expected after [tactic:tac2expr level 5] (in [tactic:tac2expr]). *)
(* error is on the ) *)

Ltac2 x s := print (of_string s) match.   (* Same message *)
```

Perhaps worth noting in the manual.

**Comment by ppedrot** [comment]
I am fairly sure this is not Ltac2-specific. Campl5 is fragile, and you it's easy to mess up with notations in general.

**Comment by ppedrot** [comment]
As argued, this applies to any camlp5 parsing rule, so closing.
