### ISSUE TITLE
Replace iris/lambda-rust in Coq CI by iris/examples

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#12836]
We'd like to replace lambda-rust in Coq CI by another of our repositories, [iris/examples](https://gitlab.mpi-sws.org/iris/examples/). lambda-rust doesn't see much activity recently, whereas new things are added to iris/examples semi-regularly. The last 2 Coq major version bumps both caused a (minor) incompatibility in iris/examples (see [this commit](https://gitlab.mpi-sws.org/iris/examples/-/commit/a6257e3482fd30f35e50d00fe0466edfb73485af) for the most recent one; the main point is tracked in [this std++ issue](https://gitlab.mpi-sws.org/iris/stdpp/-/issues/79)), so it seems to be a good sentinel for backwards compatibility. This is probably also caused by its very diverse coding style, because the different parts have been independently developed by different people with different levels of Iris and Coq experience.

Probably the biggest problem is that iris/examples has two extra dependencies besides Iris: autosubst, and our [string-ident ltac2 "plugin"](https://gitlab.mpi-sws.org/iris/examples/). This is easy via opam but could be a bit annoying with the CI setup.

@ppedrot (or whoever else would be the right person to ask), would this be okay for you, and what would it take to do this change?
Also Cc @robbertkrebbers.

**Comment by ppedrot** [comment]
I'm not involved in the CI maintenance, so I'd rather cc @coq/ci-maintainers

**Comment by SkySkimmer** [comment]
Why replace instead of add?

**Comment by RalfJung** [comment]
To not use up too many of your CI resources?

Also the two projects might require slightly different versions of Iris, so it would be non-trivial to test them both together.

**Comment by SkySkimmer** [comment]
>would this be okay for you

Should be OK

>what would it take to do this change

Replace https://github.com/coq/coq/blob/aa926429727f1f6b5ef07c8912f2618d53f6d155/dev/ci/ci-basic-overlay.sh#L65-L67 by the examples data
Rename file https://github.com/coq/coq/blob/aa926429727f1f6b5ef07c8912f2618d53f6d155/dev/ci/ci-lambda_rust.sh to `ci-iris.sh` and fix what it does
Also maybe https://github.com/coq/coq/blob/master/dev/ci/nix/lambda-rust.nix (not sure who uses that, cc @Zimmi48)
Adapt to the renaming in Makefile.ci and .gitlab-ci.yml

Build Coq, check that `make -f Makefile.ci ci-iris` works, ask if it doesn't and you can't tell what to do about it.

Commit, push, open PR.

**Comment by Zimmi48** [comment]
>Also maybe https://github.com/coq/coq/blob/master/dev/ci/nix/lambda-rust.nix

cc @vbgl

**Comment by RalfJung** [comment]
@SkySkimmer thanks!

I have no experience with `nix` files so I don't think I can edit those. But I can play with the shell script, and also adjust it to install autosubst and our ltac2-based plugin.

**Comment by vbgl** [comment]
The nix file just declares that lambda-rust depends on iris (and nothing else beyond Coq). If this is still true, there is no reason to change it.

If that file is useless, it may just be removed (just be careful to remove all references to it — IIRC there is exactly one such reference).

**Comment by RalfJung** [comment]
Who might be using that file? I'd have no way to tell if it is useless.^^

**Comment by vbgl** [comment]
> Who might be using that file?

Any contributors who make a change in Coq which breaks lambda-rust and
who feel brave enough to fix lambda-rust themselves.

In practice, I must have used it at least once (the initial motivation
for writing it). Maxime might be a potential user too (ping @maximedenes).

**Comment by maximedenes** [comment]
> Maxime might be a potential user too

Yes, I use it too, it is very convenient to write and test overlays (for Nix users).
