### ISSUE TITLE
Semantics of Export (intermediate) Module

### ISSUE THREAD

**Issue by gares** [coq/coq#12833]
```coq
Module A.
  Module B.
  Global Notation x := 4.
  End B.
  Export B.
End A.
About A.x. (* not a defined thing *)
```
Is this supposed to work?
CC @pi8027 @CohenCyril

**Comment by gares** [comment]
Let's summon @maximedenes

**Comment by SkySkimmer** [comment]
It's called `A.B.x` not `A.x`, export doesn't let you skip intermediate modules.

**Comment by gares** [comment]
Hum, indeed if I export A then `x` is there.
Is it documented, or you just knew this subtlety having hacked the code?

**Comment by ppedrot** [comment]
The semantics of `Export A` is to import A whenever the enclosing module is itself imported.

**Comment by gares** [comment]
I guess my intuition was that `Check A.x` is like `Import A. Check x.` but this is false.

**Comment by SkySkimmer** [comment]
BTW you example surprises me by using `Global` which is the default for Notation.

**Comment by maximedenes** [comment]
> I guess my intuition was that `Check A.x` is like `Import A. Check x.` but this is false.

Indeed, this doesn't seem true.

**Comment by CohenCyril** [comment]
I understand now, this is where name-spacing and kernel names are fundamentally incompatible.

**Comment by CohenCyril** [comment]
We'll keep hacking the module system like this then:
```coq
Module A.
  Notation x := 3.
End A.
Module Export OverloadA.
  Module A.
    Notation x := 4.
  End A.
End OverloadA.
About A.x.
```
