### ISSUE TITLE
coqchk reports names from inner modules of opaque modules as axioms

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12845]
#### Description of the problem

#5030 strikes again.

```bash
$ cat foo.v
```
```coq
Module Type A.
  Module B.
    Axiom t : Set.
  End B.
End A.

Module a : A.
  Module B.
    Definition t : Set := unit.
  End B.
End a.

Check a.B.t.
```
```bash
$ coqc -q -R . Top foo.v
a.B.t
     : Set
$ coqchk -silent -o -Q . Top foo.vo

CONTEXT SUMMARY
===============

* Theory: Set is predicative

* Axioms:
    Top.foo.a.B.t

* Constants/Inductives relying on type-in-type: <none>

* Constants/Inductives relying on unsafe (co)fixpoints: <none>

* Inductives whose positivity is assumed: <none>

```

By contrast:
```bash
$ cat bar.v
```
```coq
Module Type A.
  Module B.
    Axiom t : Set.
  End B.
End A.

Module a <: A.
  Module B.
    Definition t : Set := unit.
  End B.
End a.

Check a.B.t.
```
```bash
$ coqc -q -R . Top bar.v
a.B.t
     : Set
$ coqchk -silent -o -Q . Top bar.vo

CONTEXT SUMMARY
===============

* Theory: Set is predicative

* Axioms: <none>

* Constants/Inductives relying on type-in-type: <none>

* Constants/Inductives relying on unsafe (co)fixpoints: <none>

* Inductives whose positivity is assumed: <none>
```

cc @proux01 the author of #12076 and @ppedrot who seemed to be the main other person involved in the discussion

#### Coq Version

master / 8.13 / ef08abec26c2f0017d1136870f8f99144e579538

**Comment by ppedrot** [comment]
Well, the criterion was known to be neither sound nor complete, so ¯\_(ツ)_/¯

**Comment by JasonGross** [comment]
Shouldn't it be possible to just have the code recurse over inner modules or something?

**Comment by JasonGross** [comment]
Like, would it be enough to have
https://github.com/coq/coq/blob/aa926429727f1f6b5ef07c8912f2618d53f6d155/checker/mod_checking.ml#L103-L112
call itself recursively when it hits `SFBmodule`?

**Comment by proux01** [comment]
> Like, would it be enough to have [...] call itself recursively when it hits `SFBmodule`?

Quite probably yes (feel free to open a PR).

However, as noticed by Pierre Marie, this would remain incomplete (I wouldn't bet for unsound but he certainly knows better than me). Having something complete seems feasible but requires some work which I didn't found time for yet (unlikely to change in a near future unfortunately). So, if you want to dig into this, feel free to, but the best I can promise is a careful review (maybe could I trade it for a review of #12218 ;-) ).
Thanks for reporting anyway!
