### ISSUE TITLE
Package coqide in OPAM should depend on ocamlfind (explicitly)

### ISSUE THREAD

**Issue by yannl35133** [coq/coq#12858]
When a dune upgrade is available, it will recompile everything that depends on dune.
- ocamlfind depends on dune through graphics
- coqide depends on dune through lablgtk3-sourceview3

Therefore, opam will recompile both packages in unspecified order. For me, it tried to compile coqide before ocamlfind and, as every package is uninstalled before they start being reinstalled, an error occured.

**Comment by Zimmi48** [comment]
This issue requires three fixes:
- to the `coqide-server.opam` and `coqide.opam` files in this repository (cc @ejgallego)
- to the coqide packages in coq-opam-archive
- to the coqide packages in opam-repository

cc @RalfJung @Blaisorblade @palmskog for the last two.

**Comment by RalfJung** [comment]
Presumably this is because ocamlfind is a build dependency, and so it doesn't apply transitively like the others do? That makes sense.

**Comment by Blaisorblade** [comment]
Indeed, we already depend `"conf-findutils" {build}` in both coq and coqide packages, but only coq depends on `"ocamlfind" {build}`.

Semi-OT: should all those packages be recompiled for a dune upgrade, since dune is a _build_ dependency — in particular, a build tool? I surely wouldn't recompile anything if I upgraded `make`...

**Comment by Zimmi48** [comment]
Dune used to be marked as a build dependency in opam-repository, but it created troubles and it was changed.

**Comment by Zimmi48** [comment]
Cf. https://github.com/ocaml/opam-repository/issues/14185

**Comment by RalfJung** [comment]
Opened PRs:
* to the coqide packages in coq-opam-archive: https://github.com/coq/opam-coq-archive/pull/1411
* to the coqide packages in opam-repository: https://github.com/ocaml/opam-repository/pull/17084

**Comment by Zimmi48** [comment]
Thanks to Ralf, all that remains to fix are the opam files in this very repo.

**Comment by ejgallego** [comment]
I was trying to fix this, but indeed I don't understand why `coqide` does need ocamlfind, as far as I can tell it does not need it.

Only the `coq` package requires ocamlfind as it used in the configure script.

**Comment by ejgallego** [comment]
Note that it will become a runtime dependency soon as we will use it in the linker.

**Comment by ejgallego** [comment]
Indeed, when building with Dune ocamlfind is not needed, so the fix in the opam repos is enough.
