### ISSUE TITLE
Memory corruption while reducing fixpoints in vm_compute

### ISSUE THREAD

**Issue by silene** [coq/coq#12869]
While trying to fix #12636, I have come across this disturbing piece of code in `vm.ml`:

```ocaml
let reduce_fix k vf =
  let fb = first_fix vf in
  ...
  let et = offset_closure_fix fb (2*(ndef - 1)) in
  let ftyp = Array.map (fun c -> interprete c crazy_val et 0) fc_typ in
  (mk_fix_body k ndef fb, ftyp)
```

To give a bit of context, here is the code `offset_closure_fix`:

```c
value coq_offset_closure(value v, value offset){
  return (value)&Field(v, Int_val(offset));
}
```

In other words, `offset_closure_fix` returns a pointer inside a memory block. This is fine when it is used to compute the actual start of an infix closure (e.g., in `Vmvalues.first`). But here, the returned pointer directly points at the upvalues of a closure.

So, if the garbage collector ever happens to run (it will, since `interprete` is the bytecode interpreter), then it will wrongly believe that `et` points at the start of an OCaml value (it is in the OCaml heap) and mess with it.

I think the only reason this memory corruption is not widespread is that users only call `vm_compute` on reducible values. So, `Vm.reduce_fix` is never called in practice.

Am I missing something?

**Comment by ppedrot** [comment]
I think it's fine because we use the same representation as OCaml fixpoint closures, isn't it? That is, we have a big block of mutually recursive closures with INFIX_TAG at the start of every closure entry, so that the GC knows how to handle this situation. Also, I believe that fiat-crypto and friends do reduce open fixpoints in the VM when evaluating PHOAS trees (@JasonGross ?).

**Comment by ppedrot** [comment]
This is likely to evolve in a near future though, given https://github.com/ocaml/ocaml/pull/8984. Maybe #12636 is the right time to change the VM representation of mutual closures.

**Comment by silene** [comment]
> That is, we have a big block of mutually recursive closures with INFIX_TAG at the start of every closure entry, so that the GC knows how to handle this situation.

You missed my point. Offset `2*(ndef - 1)` does not point to the infix block of a mutually-defined closure; it points to the upvalues of the closure. But you are right, in the sense that a closure happens to be there (by sheer luck?), so the GC cannot be mistaken.

But that will not be true anymore once a fix for #12636 has landed. At that time, `et` will really point in the middle of nowhere.

To be clearer, it is not so much the representation of mutual closures that need to be changed (the OCaml representation is still fine), it is the way the `coq_env` variable is initialized when normalizing under lambdas (which is specific to Coq).

**Comment by JasonGross** [comment]
@ppedrot We sometimes feed expressions with bare `fix`points into the vm, but we never expect to get them out.  I can't tell whether or not this is what you're talking about.

**Comment by JasonGross** [comment]
@silene Was closing this issue a mistake?  It seems like you're saying that there's still a problem

**Comment by silene** [comment]
As pointed out by @ppedrot, there is currently no problem. The problem will only materialize once we modify the representation of closures (to follow the requirements of OCaml 4.12). So, it is not worth keeping this issue open since it is just a special case of #12636.
