### ISSUE TITLE
Ltac2 has no way to pass a local Ltac2 function to an Ltac1 function

### ISSUE THREAD

**Issue by jonleivent** [coq/coq#12871]
If an Ltac2 function is defined locally (via let-in), there does not seem to be any way to pass even the most basic such function (of type unit -> unit) back to Ltac1 as a callback.  This creates problems when attempting to incrementally convert libraries of utility tactics over to Ltac2.

One possibility for allowing this in a way that does not increase the loss of type-safety when interfacing Ltac1 and Ltac2 might be if nested quotations/antiquotations between the two languages could refer back to their own local environments.  Hence, something like
```Coq
Ltac2 foo ... :=
  let f (_:unit) :=  ... in ltac1:(...ltac2:(... f ()...)...)
```

**Comment by ppedrot** [comment]
You can do that with the `ltac1:(x |- ...)` syntax though?

**Comment by jonleivent** [comment]
With the `ltac1:(x |- ...)` syntax, the actual parameter supplied to x has to be of type `Ltac1.t` - and there is no way to convert an Ltac2 function of type such as `unit->unit` to a value of type `Ltac1.t`.

**Comment by ppedrot** [comment]
Wouldn't an Ltac2 function `abstract : (Ltac1.t ->Ltac1.t) -> Ltac1.t` be sufficient for your needs? This one looks reasonable to expose in the FFI.

**Comment by JasonGross** [comment]
Note that it perhaps shouldn't be named `abstract` given that `abstract` is already a tactical that we probably want access to in Ltac2.

**Comment by kyoDralliam** [comment]
how about `lambda` ?

**Comment by ppedrot** [comment]
I've called it `lam` in the patch I am writing.

**Comment by jonleivent** [comment]
Can it be extended to pass an arbitrary multi-arg typed Ltac2 function to Ltac1?  I could write Ltac1 wrappers so that multiple arguments are combined into a single tuple that becomes the arg, then separate them on the Ltac2 side before calling the target function, but wouldn't that be faster, easier on tactic developers, and more type safe if it was done internally?

**Comment by Armael** [comment]
@ppedrot told me (on zulip) that currification works "as expected" in Ltac1, so you can rather implement (in Ltac2) a function of type `int -> (Ltac1.t list -> Ltac1.t) -> Ltac1.t` on top of the `lam` function above, where the integer argument describes the arity of the function, and must correspond to the length of the list taken as argument.
