### ISSUE TITLE
Anomaly using `Admitted` for mutual fixpoint with differing+implicit arguments

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [coq/coq#12895]
#### Description of the problem

Under Coq 8.12, and current `master` (8.13+alpha), I get an anomaly in the following code:

```
Fixpoint bug_1 (e1 : nat) {struct e1}
  : nat
with bug_2 {H_imp : nat} (e2 : nat) {struct e2}
  : nat.
Proof.
  - exact e1.
  - exact e2.
Admitted.
```

This errors at the `Admitted`, with error message `Anomaly "File "interp/impargs.ml", line 378, characters 15-21: Assertion failed."`

Some experimenting suggests that the triggering condition is something roughly like:
- there is a mutual fixpoint, with two or more components;
- their interactive proof is concluded with `Admitted`;
- some *later* component of the mutual fixpoint has *more* implicit arguments than the first component;
- and *at least one* of the arguments of that component is implicit.
- This anomaly occurs under current `master`, bd4791ff, 8.13+alpha; also under 8.12.0, 558e8ea1.

In particular, in the example above:
- if `H_imp` is made explicit, then no error occurs
- if the implicit arg `H_imp` occurs in both components of the mutual fixpoint, or in just the first, then no error occurs 
- if the definition is completed to a `Defined` or `Qed`, then no error occurs
- when completing with `Admitted`, the error occurs regardless of how much proof (if any) has been given beforehand
- the specific types involved don’t seem to affect the error
- the `struct` annotations don’t seem to interact with the error
- in the original occurrence in the wild (reported at https://github.com/UniMath/TypeTheory/issues/182, arising from [Initiality.InterpretationLemmas.trivial_interpretation_ty](https://github.com/UniMath/TypeTheory/blob/a84fc71d116ff640f1e21a9a34301585e7c5caa8/TypeTheory/Initiality/InterpretationLemmas.v#L329)), the types of `e1`, `e2` were a genuinely mutually inductive pair of types.
- that original occurrence compiled fine under Coq 8.11, so presumably this bug didn’t occur there (though I haven’t downgraded to test this MWE under 8.11).

#### Coq Version

This MWE produces an anomaly under Coq bd4791ff (current `master`, at time of writing):

`The Coq Proof Assistant, version 8.13+alpha (August 2020) compiled on Aug 25 2020 9:37:00 with OCaml 4.05.0`

It also produces the same anomaly under Coq 558e8ea1 (8.12.0), compiled for UniMath.

**Comment by ejgallego** [comment]
It is highly probable that this is a regression for 8.12; let's see if the MWE produces a bisect.

**Comment by herbelin** [comment]
There seems to be a "critical" collision between the types of the two declarations in the `Admitted` case. Here is a variant without implicit arguments:
```
Fixpoint bug_1 (a:bool) (e1 : nat) {struct e1}
  : nat
with bug_2 (a:nat) (e2 : nat) {struct e2}
  : nat.
Proof.
  - exact e1.
  - exact e2.
Admitted.
Print bug_2.
(* [ bug_2 : bool -> nat -> nat ] *)
```

**Comment by ejgallego** [comment]
This is the commit to blame (79bcf1c0a22e736c4e2cae3460c35b3d9fca9aa0):
```
79bcf1c0a22e736c4e2cae3460c35b3d9fca9aa0 is the first bad commit
commit 79bcf1c0a22e736c4e2cae3460c35b3d9fca9aa0
Author: Emilio Jesus Gallego Arias <e+git@x80.org>
Date:   Sat Feb 29 15:25:42 2020 -0500

    [lemmas] Handle mutual lemmas more uniformly.
    
    We split the paths for mutual / non-mutual constants, and we enforce
    some further invariants, in particular we avoid messing around with
    the body of saved constants, and using the indirect accessor.
    
    This should be almost semantically equivalent to the previous code,
    including some questionable choices present there.
    
    In further cleanups we will move this code to Declare, which should
    hopefully help clarify some of the semantics.

 vernac/comFixpoint.ml   |   4 +-
 vernac/declareDef.ml    |   4 +-
 vernac/declareDef.mli   |   1 -
 vernac/lemmas.ml        | 221 +++++++++++++++++++++++++++++-------------------
 vernac/lemmas.mli       |   2 +-
 vernac/vernacentries.ml |   2 +-
 6 files changed, 142 insertions(+), 92 deletions(-)
```
