### ISSUE TITLE
lia fails with name mangling

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#12907]
#### Description of the problem

The following proof script fails:
```coq
From Coq Require Export Lia.
Set Mangle Names.
Lemma test (n : nat) : n <= 10 -> n <= 20.
Proof. lia. Qed.
```
It says
```
Error: The variable __ff was not found in the current environment.
```

#### Coq Version

Current Coq master

**Comment by RalfJung** [comment]
@SkySkimmer if I saw correcly you fixed omega; any idea how hard it would be to also fix lia?

**Comment by maximedenes** [comment]
@SkySkimmer Do you mind having a look at this one?

**Comment by jashug** [comment]
This was mentioned as part of an unrelated issue (#12676). My diagnosis of the problem from there:

In this case, the error comes from https://github.com/coq/coq/blob/d5a8bdc8f67b691dd39a27a9fe07a026d998fda3/theories/micromega/Lia.v#L23-L24
where we introduce a fresh name, and then use the non-refreshed name in the exact tactic. Shouldn't be too hard of a fix, though there may be other problems waiting after that one.

**Comment by jashug** [comment]
I'm working on a PR now.

**Comment by maximedenes** [comment]
@RalfJung ready for the next issue ;)
