### ISSUE TITLE
Numeral/String notations should support "only parsing" on non-inductive types

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12916]
It occurred to me while reading #12218 that it seems a bit unfortunate that `int63` needs a syntax plugin.  I think it would be nice to support something like
```coq
Numeral Notation int id_int (only parsing) : int63_scope.
```
where, when `only parsing` is given, the type need not be inductive (because we don't need to know any entry points for printing).

cc @proux01 (if you don't want to do this, I might take a stab at it myself when I get a chance)

**Comment by proux01** [comment]
Indeed. The `int63` plugin was removed by #13559. We should still do the same for primitive floats though.
