### ISSUE TITLE
Debug printers not getting installed

### ISSUE THREAD

**Issue by jashug** [coq/coq#12945]
#### Description of the problem

When I run `make coqide byte` and then `dev/ocamldebug-coq bin/coqtop.byte`, and `source db`, I get a few success messages ended by the error:
```
Error during code loading: error while linking /home/jasperh/coq/interp/interp.cma.
Reference to undefined global `Z'
```
And indeed many printers appear to have not been installed.

However, compilation seems to work and I can run `coqide` just fine.

Given the reference to `Z`, this might be related to #11742? @ejgallego 

#### Coq Version

Coq master 94d9fe2b6c, after `git clean -dxf`.

**Comment by herbelin** [comment]
Hi, here is a temporary workaround:
- add`load_printer zarith.cma` at the beginning of `dev/core.dbg`
- add `-I path-to-zarith` in `dev/ocamldebug-coq.run`
In my case (opam installation), the latter is `$CAMLIB/../zarith` (where $CAMLIB defined in `config/Makefile`) but I'm unsure about the robust way to refer to this directory.

I guess @ejgallego will know.

**Comment by jashug** [comment]
@SkySkimmer 
Even after #12958, this still isn't working for me unless I do the second step given by herbelin above.
I get a message `Cannot find file zarith.cma`, and then later `source db` ends with ```Reference to undefined global `Z'```.

**Comment by SkySkimmer** [comment]
Try adding `-I $(ocamlfind query -recursive -i-format zarith)` (NO QUOTES) to dev/ocamldebug-coq.run
If it works make a PR

**Comment by jashug** [comment]
Thanks, that worked.
