### ISSUE TITLE
"Error: _0 is already used." with name mangling

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#12944]
#### Description of the problem

The following causes a strange error:
```coq
From Coq Require Export Vector.

Global Set Mangle Names.

Lemma vlookup_middle {A n} (v : Vector.t A n) : True.
Proof.
  induction v as [|?? IHv].
```
It says
```
Error: _0 is already used.
```
This is odd because nothing asks for name `_0`, and why doesn't it just pick `_1` then?

The problem is that `IHv` above is also used as the name for the *fourth* variable in the 2nd branch of the induction. Somehow that confuses name assignment, and then the error message is also confusing.

I think the code should work though.

#### Coq Version

Latest coq master

**Comment by RalfJung** [comment]
Curiously, adding a `?` after `IHv` works around the problem.

**Comment by jashug** [comment]
I agree that this should work (unless we decide to force induction as clauses to give a full set of name/`?`s, one for each hypothesis). Curiously, with `Mangle Names` off and `induction v as [|? ? IHv]`, we get names `h n IHv IHIHv`, while with `induction v as [|? ? IHv ?]` we get `h n IHv IHv0` (and with four question marks, or no as clause at all, we get `h n v IHv`.

I don't immediately see where the bug is; I'm not grabbing a lock on this issue.

**Comment by jashug** [comment]
Here is a reduced example without `Mangle Names`, in case it might help in identifying the root cause:
```coq
Inductive test : Set := cons : forall (IHv : nat) (v : test), test.

Lemma test_induction (v : test) : True.
Proof.
  induction v as [? IHv].
  (* Fails with `IHv is already used.` *)
```
I'm not entirely confident this is the same issue though.

**Comment by jashug** [comment]
Ah, in the above example `induction v as [? v]` also fails.

**Comment by herbelin** [comment]
> Here is a reduced example without `Mangle Names`, in case it might help in identifying the root cause:
> 
> ```coq
> Inductive test : Set := cons : forall (IHv : nat) (v : test), test.
> 
> Lemma test_induction (v : test) : True.
> Proof.
>   induction v as [? IHv].
>   (* Fails with `IHv is already used.` *)
> ```

Relatively to this issue (thanks for noticing!), I made #12954, but this does not fix the `_0` issue.

**Comment by RalfJung** [comment]
@herbelin isn't it expected that `as [? IHv]` fails when `IHv` is already used? When I give an explicit name in a pattern, Coq should use that name or fail. It should not choose a different name. That would subvert the entire point of having a reliable proof script with predictable names!
