### ISSUE TITLE
coqdoc :  problem with "details"

### ISSUE THREAD

**Issue by Casteran** [coq/coq#12957]
#### Description of the problem

On V8.12.0, the following code generates an error with coqdoc -g.
Perhaps I didn't understand "details" specification ?

Pierre
```coq
Require Import Arith.

Lemma L : forall n p, n < p -> exists q:nat, p = q +  n.
Proof.
  intros n p H. induction H as [| m H [q Hq]].
  (* begin details *)
  exists 1; auto with arith.  
  exists (S q); cbn; now f_equal.
  (* end details *)
Qed.
```
~~~
>  coqc details.v
>  coqdoc -g details.v
Fatal error: exception Stdlib.Stack.Empty
~~~

**Comment by Casteran** [comment]
It looks like pasting my example on the bug tracker removed stars from the comments. But the code that generated the error is syntactically correct.

**Comment by Zimmi48** [comment]
cc @lthms

**Comment by lthms** [comment]
See #12772; should be fixed as soon as coq.8.12 is released!
