### ISSUE TITLE
8.12.0 build fails on s390x

### ISSUE THREAD

**Issue by rwmjones** [coq/coq#12967]
#### Description of the problem

The build of Coq 8.12.0 on s390x fails.  It works on all other architectures, and the failure appears to be a new one introduced since 8.12.0 was released.

Here is the failing build:
https://koji.fedoraproject.org/koji/taskinfo?taskID=50627125

The error is at the end of this very long log file:
https://kojipkgs.fedoraproject.org//work/tasks/7285/50627285/build.log

```
==========> FAILURE <==========
    success/auto.v...Error! (should be accepted)
FAILURES
    success/auto.v...Error! (should be accepted)
    success/bteauto.v...Error! (should be accepted)
    bugs/closed/bug_5127.v...Error! (bug seems to be opened, please check)
    bugs/opened/bug_3395.v...Error! (bug seems to be closed, please check)
    complexity/pattern.v...Error! (couldn't find a time measure)
```

#### Coq Version

8.12.0

**Comment by ppedrot** [comment]
Looks like a duplicate of #11395. My comment from that issue still holds.

**Comment by rwmjones** [comment]
Could be - I wonder why we've only just started to see it though.

I have disabled the test on s390x for now.  Whether anyone uses Coq on s390x, I don't know for sure, but I'd be highly surprised if anyone was.

**Comment by rwmjones** [comment]
We think this is a duplicate of #11395
