### ISSUE TITLE
Coq 8.12.0 loops forever on code that worked fine up until Coq 8.11

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#12971]
#### Description of the problem

[This declaration](https://gitlab.mpi-sws.org/iris/ora/-/blob/2d9c9ca3765f4ed81f0bd4a58b1d15f77e8b14ad/theories/algebra/ora.v#L30) worked fine for many Coq versions until Coq 8.11.2, but I just noticed that when using Coq 8.12.0, Coq just loops forever on that `Record ... .`.

To reproduce, clone that repository and run `make build-dep` to get the exact same versions of the dependencies as what I have (requires opam).

Cc @robbertkrebbers 

#### Coq Version

8.12.0

**Comment by RalfJung** [comment]
I managed to minimize this slightly, to this code that still depends on Iris:
```
From iris.algebra Require Export ofe monoid cmra numbers.
From stdpp Require Import finite.

Section mixin.
  Local Set Primitive Projections.
  Record OraMixin A `{Dist A, Equiv A, PCore A, Op A, Valid A, ValidN A} := {
    mixin_ora_pcore_idemp x cx : pcore x = Some cx → pcore cx ≡ Some cx;
  }.
End mixin.
```
On Coq 8.11, this passes. On Coq 8.12, it fails saying
```
Error:
Unable to satisfy the following constraints:
In environment:
OraMixin : ∀ A : Type, Dist A → Equiv A → PCore A → Op A → Valid A → ValidN A → Type
A : Type
H : Dist A
H0 : Equiv A
H1 : PCore A
H2 : Op A
H3 : Valid A
H4 : ValidN A
x : ?A
cx : ?A

?PCore : "PCore ?A"

?Equiv : "Equiv (option ?A)"

?PCore0 : "PCore ?A"
```

**Comment by RalfJung** [comment]
Adding a type annotation like `mixin_ora_pcore_idemp (x cx : A)` works around the minimized problem.

Something similar works for the main issue:
```coq
Section mixin.
  Context (A : Type).

  Implicit Types (x : A).
  Local Set Primitive Projections.

  Record OraMixin `{Dist A, Equiv A, PCore A, Op A, Valid A, ValidN A,
                      OraOrder A, OraOrderN A} := {
```
However, then the same file fails later, where our tactic `setoid_subst` now loops forever in a case that used to work fine.

For now, I am giving up on trying to port this to Coq 8.12, until someone chimes in who has an idea what might be happening here.

**Comment by RalfJung** [comment]
Oh, that `setoid_subst` already takes forever on Coq 8.11... we'll have to investigate that part in our side.

**Comment by SkySkimmer** [comment]
>I managed to minimize this slightly, to this code that still depends on Iris:

If you remove the section or unset primitive projections it starts working?

**Comment by SkySkimmer** [comment]
Does setting / unsetting universe polymorphism change anything?

**Comment by RalfJung** [comment]
> If you remove the section or unset primitive projections it starts working?

No, that makes no difference. This still fails with the same error:
```coq
From iris.algebra Require Export ofe cmra.

Record OraMixin A `{Dist A, Equiv A, PCore A, Op A, Valid A, ValidN A} := {
  mixin_ora_pcore_idemp x cx : pcore x = Some cx → pcore cx ≡ Some cx;
}.
```

> Does setting / unsetting universe polymorphism change anything?

(Would have been helpful to say how to test that, I never work with this option.)
It fails with with `Unset Universe Polymorphism.` and `Set Universe Polymorphism.`.

**Comment by robbertkrebbers** [comment]
I think this is just bad code. Due to the omission of type annotations for the variables, it's ambiguous, and I would not expect the behavior to be well-defined. Note that similar code in Iris (see https://gitlab.mpi-sws.org/iris/iris/-/blob/master/theories/algebra/cmra.v#L45) has type annotations.

> Oh, that setoid_subst already takes forever on Coq 8.11... we'll have to investigate that part in our side.

I can look into that. Can you create an Iris/std++ issue, preferably with a self-contained example?

**Comment by robbertkrebbers** [comment]
PS: The reason that you get a loop, is probably a missing `Hint Mode` for `OraOrder` and `OraOrderN`. With the right `Hint Mode`, I expect it to just fail, which would be the right behavior, since the code is ambiguous due to the omission of type annotations.

**Comment by RalfJung** [comment]
> Note that similar code in Iris (see https://gitlab.mpi-sws.org/iris/iris/-/blob/master/theories/algebra/cmra.v#L45) has type annotations.

That one does, but [this one](https://gitlab.mpi-sws.org/iris/iris/-/blob/96df79972159edd1581c9a30a6590ac2c73fbfdf/theories/algebra/ofe.v#L41) does not, and it still works.

But sure, we can add type annotations here as well. 

> The reason that you get a loop, is probably a missing Hint Mode for OraOrder and OraOrderN. With the right Hint Mode, I expect it to just fail, which would be the right behavior, since the code is ambiguous due to the omission of type annotations.

if you could add reasonable modes, that would be great. :)

**Comment by RalfJung** [comment]
After adding the type annotations, things behave like they did with Coq 8.11. Given what @robbertkrebbers said above, that seems like reasonable behavior, so I am going to close this issue. Thanks all!

**Comment by robbertkrebbers** [comment]
> That one does, but this one does not, and it still works.

I think that's more of a coincidence than a feature. I think we should add type annotations there too.

**Comment by SkySkimmer** [comment]
Looks related to https://github.com/coq/coq/pull/9996 (there is `Hint Mode PCore ! : typeclass_instances.` so after it the PCore parameter stops being used)
