### ISSUE TITLE
Primitive projections breaks ability to declare field of record as Existing Class

### ISSUE THREAD

**Issue by Alizter** [coq/coq#12975]
#### Description of the problem

Setting primitive projections breaks the ability to declare a field of a record as an `Existing Class`. Observe that this works on a record without Primitive Projections, but on a record with, it doesn't have the same behaviour. Coq just doesn't see that `myotherprop` is a class even though it has been declared so using `Existing Class`. 

```coq
Record foo :=
{
  myprop : Type ;
}.

Set Primitive Projections.

Record bar :=
{
  myotherprop : Type ;
}.


Existing Class myprop.
Existing Class myotherprop.

Instance : forall O, myprop O. Abort.
Fail Instance : forall (O : bar), myotherprop O.
```

#### Coq Version

Coq 8.12.0
Coq 8.13+alpha (September 2020)

**Comment by SkySkimmer** [comment]
See https://github.com/coq/coq/pull/9711
