### ISSUE TITLE
compact_P3

### ISSUE THREAD

**Issue by ruiminhe** [coq/coq#12982]
Hi

I tried doing

Require Import Reals.Rtopology. Print compact_P3. 

and got the following error

Anomaly "Uncaught exception Retyping.RetypeError(0)."
Please report at http://coq.inria.fr/bugs/.
Fetching opaque proofs from disk for Coq.Reals.Rtopology

**Comment by herbelin** [comment]
Hi @ruiminhe, could you give a bit more context? Which version of Coq, which conditions of reproducibility?

On my side, this command is working normally.

**Comment by ruiminhe** [comment]
Ah sorry my bad. It didn't work on 8.11.0 but works on 8.12.0

**Comment by ruiminhe** [comment]
(I had just entered "Require Import Reals.Rtopology. Print compact_P3." on a fresh coq screen in 8.11 and it didn't work, but works on 8.12) thanks!

**Comment by herbelin** [comment]
OK, I see. Then it is the same as #9644 which is indeed fixed. Thanks for the details!
