### ISSUE TITLE
Simply importing .v files from a folder is no longer possible

### ISSUE THREAD

**Issue by JoJoDeveloping** [coq/coq#12990]
Hello.

Let's say I want to split a coq file into two files.

It used to be that I could simply put files A.v and B.v into the same folder and then do (in B.v)
```
Add LoadPath "/path/to/where/my/file/was/kept".
Require Import A.
```

Now it however fails (in coqide 8.12.0) with `Syntax error: 'as' expected after [Prim.ne_string] (in [vernac:command]).`

Is this intended, and if yes, how can you simply import one ".v" file into another one now?

**Comment by ppedrot** [comment]
From the changes file:
```markdown
- **Removed:**
  Recursive OCaml loadpaths are not supported anymore; the command
  ``Add Rec ML Path`` has been removed; :cmd:`Add ML Path` is now the
  preferred one. We have also dropped support for the non-qualified
  version of the :cmd:`Add LoadPath` command, that is to say,
  the ``Add LoadPath dir`` version; now,
  you must always specify a prefix now using ``Add Loadpath dir as Prefix``
  (`#11618 <https://github.com/coq/coq/pull/11618>`_,
  by Emilio Jesus Gallego Arias).
```

That said, it is recommended against the use of explicit loadpath adding in files. Instead, the easiest mechanism around is to define a `_CoqProject` file with the relevant `-Q/-R` options and use `coq_makefile`.
