### ISSUE TITLE
Mangle Names can cause `intros ->` to fail

### ISSUE THREAD

**Issue by jashug** [coq/coq#13003]
#### Description of the problem

The following code fails with `Mangle Names` set, and succeeds with it unset.

```coq
Set Mangle Names.
Import EqNotations.
Lemma eq_sigT_sig_eq X P (x1 x2:X) H1 H2 :
  forall (E1 : x1=x2), rew E1 in H1 = H2 -> existT P x1 H1 = existT P x2 H2.
Proof.
  intros ->. (* Anomaly "File "kernel/typeops.ml", line 194, characters 15-21: Assertion failed." *)
  intros <-.
  reflexivity.
Defined.
```

The failing assertion is https://github.com/coq/coq/blob/cdfe69d6da6b32338ba74c9f599c74389089c9dd/kernel/typeops.ml#L194

The problem is likely in the implementation of `intros ->`, but it seems worrying that it can cause a failing kernel assertion.

I found this while working on `Logic/EqdepFacts.v` for #6781.

#### Coq Version

Coq master cdfe69d6da

**Comment by ppedrot** [comment]
Probably an instance of "yet another tactic that sends ill-typed terms to the kernel".
