### ISSUE TITLE
Ltac quotations are not printed.

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#13004]
#### Description
It appears that quotations that are registered through `Tacentries.create_ltac_quotation` are not properly printed. In some cases not printing the quotation results in a valid tactic term, but there are also cases where the resulting string is not a valid tactic. See the two examples below (I'm sure there are more).
```
Require Import Ltac2.Ltac2 Ltac2.Message.

Ltac t := ltac2:(print (of_string "hi")).
Ltac u := ident:(H).

Print t.
Print u.
```

#### Coq Version
```
You are running The Coq Proof Assistant, version 8.13+alpha (September 2020)
```

**Comment by herbelin** [comment]
Sometimes, there are implicit coercions between terms. Do we want to make these coercions explicit too?

@ppedrot: what do you think? Should we add e.g. an optional parameter to the `TacGeneric` constructor telling when this `TacGeneric` comes from a quotation and then to print this string?

**Comment by herbelin** [comment]
See #13028 for a fix.

**Comment by LasseBlaauwbroek** [comment]
Looks like a good solution to me. Thanks!
