### ISSUE TITLE
Strange example in `simple apply` documentation

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#13023]
The documentation of `simple apply` seems strange to me: https://coq.github.io/doc/master/refman/proof-engine/tactics.html#coq:tacv.simple-apply

It says:

> This behaves like apply but it reasons modulo conversion only on subterms that contain no variables to instantiate. For instance, the following example does not succeed because it would require the conversion of `id ?foo` and `O`.

> Example

```coq
Definition id (x : nat) := x.
Parameter H : forall y, id y = y.
Goal O = O.
Fail simple apply H.
(*
The command has indeed failed with message:
Unable to unify "id ?M160 = ?M160" with "0 = 0".
*)
```

But it does not seem true that it would require this conversion. Unification could also choose to instantiate `?foo` to `O` (because of the RHS of the equality), and only then convert `id O` and `O` (which are now ground).

I'm asking this because it turns out #991 breaks this example.

Could we get a clearer specification of `simple apply`?

Cc @coq/doc-maintainers @coq/tactics-maintainers @mattam82

**Comment by Zimmi48** [comment]
I don't think that @coq/doc-maintainers will be able to help here except to say that you are welcome to improve this doc and in particular to change the example to something that would characterize this tactic better.

**Comment by maximedenes** [comment]
Well, if I knew what the spec of `simple apply` was, I'd write the documentation indeed.

However, as it is, the manual contains a sentence that is just not true (regardless of what the tactic does): "For instance, the following example [...] would require the conversion [...]".

Let's see if @coq/tactics-maintainers can write a more sensible specification of `simple apply`. If not, I guess we should do something at the documentation level (like removing this example).

**Comment by herbelin** [comment]
> But it does not seem true that it would require this conversion. Unification could also choose to instantiate ?foo to O (because of the RHS of the equality), and only then convert id O and O (which are now ground).

It might be added in the doc that unification problems are treated in order (with `id ?foo = 0` causing a irreversible failure) as shown in the following example:
```
Definition id (x : nat) := x.
Parameter H : forall y :nat, y = id y.
Goal O = O.
simple apply H. (* succeeds because ?y is instantiated to 0 before the unification of `id ?y = 0` is treated *)
```

Alternatively, the following example does not involve the order:
```
Definition id (x : nat) := x.
Parameter H : forall y x :nat, id y = x.
Goal O = O.
Fail simple apply H. (* same failure as above w/o involving the order of unification problems *)
```
Simulating such an "ad hoc" behavior in evarconv may be difficult, if not vain. I guess it depends on the number of examples in the wild that rely on this very behavior.

**Comment by maximedenes** [comment]
Ok, so a simple fix would be to change the example and take @herbelin's last one, so that at least the difference between `apply` and `simple apply` in the example does not depend on the unspecified behavior of unification (and of course, that example is still valid after #991). Thanks for the suggestion.
