### ISSUE TITLE
[build] Configure should check for `zarith` version

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#13041]
#### Description of the problem

https://launchpadlibrarian.net/497864805/buildlog_ubuntu-bionic-amd64.coq_8.master~git~202009162234+21704-0~daily336-95f78398bb~ubuntu18.04.1_BUILDING.txt.gz

File "./theories/micromega/Lia.v", line 31, characters 23-36:
Error: Anomaly "Uncaught exception Division_by_zero."
Please report at http://coq.inria.fr/bugs/.

#### Coq Version

95f78398bb

**Comment by JasonGross** [comment]
Presumably this is due to #8743, switch to zarith; cc @ejgallego

**Comment by ejgallego** [comment]
`zarith` version _must_ be >= 1.10 , likely that's the issue.

We should improve configure to check version numbers.

**Comment by ejgallego** [comment]
```
Unpacking libzarith-ocaml (1.5-1) ...
```
yeah, that's way too old and buggy.

**Comment by JasonGross** [comment]
Okay, I'll backport a newer version of zarith, thanks.  And, indeed, the configure script should check the version number better.
