### ISSUE TITLE
Anomaly when inferring simple typeclass instance.

### ISSUE THREAD

**Issue by arthuraa** [coq/coq#13045]
#### Description of the problem

```coq
From Coq Require Import ssreflect.
From stdpp Require Import base gmap.
Goal False.
have: Inhabited (gmap nat nat) by [].
(* Toplevel input, characters 0-37: *)
(* > have: Inhabited (gmap nat nat) by []. *)
(* > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ *)
(* Error: *)
(* Anomaly *)
(* "tclZERO receiving critical error: Anomaly "Not an arity." Please report at http://coq.inria.fr/bugs/." *)
(* Please report at http://coq.inria.fr/bugs/. *)
```

Strangely, swapping the two import lines makes the anomaly go away (though typeclass inference still fails to find the `empty_inhabited` instance.)

#### Coq Version

8.12

**Comment by CohenCyril** [comment]
Ssreflect `have` does not perform typeclass inference, you may add a ltac in term `refine` to compensate.
I remember @gares had some ideas of how to integrate ssreflct `have` with typeclass inference more smoothly, meanwhile he already gave me the following trick:
https://github.com/math-comp/analysis/blob/9e270bd65004afc740da4fd805a7f06b3e0de075/theories/posnum.v#L45-L46

**Comment by arthuraa** [comment]
@CohenCyril Great to know about the `refine` trick!

**Comment by gares** [comment]
I don't understand my trick 🤣
Is `have : T := !! _.` the thing?

**Comment by SkySkimmer** [comment]
Anomaly probably from around https://github.com/coq/coq/blob/1c919ed6fa476f0f7a16d69e58989f3d75104910/plugins/ssr/ssrview.ml#L204-L209

**Comment by gares** [comment]
Well spot. But this is about the "external anomaly". There is still the internal one (there are 2 anomalies in the error message)

**Comment by SkySkimmer** [comment]
Actually the bad tclZERO looks like this one instead https://github.com/coq/coq/blob/1c919ed6fa476f0f7a16d69e58989f3d75104910/plugins/ltac/rewrite.ml#L2147-L2150

**Comment by SkySkimmer** [comment]
Similar anomaly, no ssr:
~~~coq
From stdpp Require Import base gmap.
Goal Inhabited (gmap nat nat).
  reflexivity.
~~~

**Comment by SkySkimmer** [comment]
Much reduced version:
~~~coq
#[universes(template)]
Inductive R (x:nat) (A:Type) : Type := C : A -> R x A.

#[universes(template)]
Inductive Box (A:Type) : Type := box : A -> Box A.

Goal Box (R 0 Set).
  reflexivity.
~~~
