### ISSUE TITLE
`Print HintDb` doesn't seem to update after `Remove Hints`

### ISSUE THREAD

**Issue by euisuny** [coq/coq#13089]
#### Description of the problem
Hi, it doesn't seem like the results for `Print HintDb` updates the list of hints after invoking `Remove Hints`.

In particular, I am sure that it has removed the hints because I tried doing the following:

```
Remove Hints <some_hint> : typeclass_instances
Print HintDb typeclass_instances (* The results still contain <some_hint> *)
```

And when I look at the debug trace for typeclasses search, it seems to have indeed removed the particular hint but the `Print HintDb` doesn't seem to display that the hint has been removed.

Is there another command than `Print HintDb` that outputs the updated list of hints / is this expected behavior?
Thanks!

#### Coq Version
8.11.2

**Comment by ejgallego** [comment]
Hello @euisuny , I cannot reproduce in `master`, would like to submit a concrete case?

**Comment by ppedrot** [comment]
No update, let's close.
