### ISSUE TITLE
Sentence splitting severely broken in Coqide 8.12.0

### ISSUE THREAD

**Issue by silene** [coq/coq#13091]
I have encountered several cases where Coqide is completely unusable in 8.12.0. In the example below, Coqide considers that the input file stops at `Proof`. It completely ignores what follows. In some other cases, it just ignores some sentences (which in turn can cause the wrong tactics to be applied to the wrong goals, hence infinite loops, @MSoegtropIMC).

```coq
Goal True.
Proof.
let vars := constr:((0)%nat) in
exact I.
Qed.
```

This is a severe regression with respect to 8.11.

**Comment by silene** [comment]
Reverting bcc790edb63af62022699c8005b522b45f0e81cd (and a6571b3ef7a13e996fbb07fbf7758aa7b3cc6a65) fixes the issue. 

According to #10481, this commit has already been reverted before, both in 8.10 and in 8.11. But, for some reason, it is still in 8.12 and master.

**Comment by silene** [comment]
By the way, one should not be under the impression that only power users doing ltac stuff are impacted. Even plain Coq scripts can trigger this bug, as shown by this snippet from Why3.

```coq
assert (NZ_d:((Zpos d) <> 0)%Z) by discriminate.
```

**Comment by Zimmi48** [comment]
This time, let's revert in master first and backport to v8.12 then. This will avoid the confusion shown in the linked issue.
