### ISSUE TITLE
Different ways to write tactics in GRAMMAR EXTEND vs TACTIC EXTEND

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13090]
I notice that the parser action code for GRAMMAR EXTEND is executed immediately after recognizing the production, while the action for TACTIC EXTEND is executed much later.

I expect this is intentional, but it appears to require two different ways of writing tactics:  one way for tactics such as `destruct` that are in GRAMMAR EXTEND and another way for tactics such as `trivial` that are in TACTIC EXTEND.  Is there a reason to have two mechanisms to do what is AFAIK the same thing?  If not, is it worth eventually changing to get to a single mechanism?

**Comment by jfehrle** [comment]
PS The delay in executing the TACTIC EXTEND is quite an unexpected way of handling a parser action.  Makes it much harder to build a parse tree!

**Comment by ppedrot** [comment]
I am not sure what you're trying to achieve. Parsing actions are only triggered when you're actually parsing a text, so you shouldn't rely on the immediate effects of the `GRAMMAR EXTEND` command. If it's happen that non-values put inside an argumentless branch have immediate observable effects, it's an implementation detail.

**Comment by jfehrle** [comment]
I'm trying to build a parse tree, which has many potential uses:
- As a cleaner way to gather parsing statistics.  This is an improvement on the approach I used in #10652 which you weren't thrilled by.
- Getting a full parse tree would make it possible for developers to gather, with simple code changes, much more specific statistics on how Coq constructs are used, e.g. how often does `apply` have an `in` clause, or how often any tactic has an `in` clause.
- To provide a `Parse <sentence>.` command that prints parse trees, useful for developers and users to understand how Coq parses it input.  It isn't always obvious.  This could be useful for writing tests of the parser as well.
- It could be used in a tool that identifies some types of compatibility issues and reports how many such issues were found.  It might be possible to automatically make fixes for some issues.
- It is a step toward making the parser reusable by third-party tools.  There are users who would like to parse Coq input but can't because it's too difficult.  I think I have a workable idea on how to do this.

The other way to do this would be to add additional information to `ty_entry` and `ty_tree`.  That seemed like it would be a good bit harder for me to understand with a more-complex implementation.

My prototype is in #13095.

So: can we change this so the parser action is invoked earlier?  Let me know your thoughts.
