### ISSUE TITLE
Coq ignores "only printing" when it comes after "only parsing"

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#13112]
#### Description of the problem

```coq
Reserved Notation "'HI'".
Notation "'HI'" := (O + O) (only parsing).
Check HI. (* 0 + 0 : nat *)
Notation "'HI'" := (O + O) (only printing).
Check HI. (* 0 + 0 : nat *)
```

I think the second one should display `HI` (or perhaps be an error).  Note that putting the `only printing` notation first works as expected.

cc @herbelin 

#### Coq Version

8.12

**Comment by herbelin** [comment]
As far as I can judge, this is fixed by #12950.
