### ISSUE TITLE
New recommended negative coindutive types don't work in Set 

### ISSUE THREAD

**Issue by roger-witte** [coq/coq#13136]
#### Description of the problem
```coq
CoInductive 𝕀 : Set := 𝕀bits : bool -> 𝕀 -> 𝕀.
(* Fine *)
CoInductive ℍ : Set := ℍbits (hh : bool) (ht : ℍ) : ℍ.
(* Fine *)
CoInductive Record 𝕁 : Set := {jh : bool; jt: 𝕁}.
(* Universe inconsistency. Cannot enforce Top.2 <= Set. *)
```

#### Coq Version

8.12.0
Windows 7SP1

**Comment by SkySkimmer** [comment]
The syntax is `CoInductive 𝕁 : Set := {jh : bool; jt: 𝕁}.`
`CoInductive Record` defines a coinductive called `Record`.

**Comment by Zimmi48** [comment]
Ouch, that's one example in favor of the "more keywords" team.
