### ISSUE TITLE
Parser doesn't execute all the expected parse action routines

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13149]
It appears that the parser doesn't always execute the parse action for some productions.  Although if that's the case, I expect that it would have been apparent a long while ago.  Is this Ltac doing something very odd?  How buggy is our parser?

Here's the evidence:
1. In `g_ltac.mlg`, add this `printf` to the action routine for `operconstr` (in GRAMMAR EXTEND):

```
    [ [ IDENT "ltac"; ":"; "("; tac = Pltac.tactic_expr; ")" ->
        { Printf.printf "REACHED operconstr -> \"ltac\" ... on line %d\n%!" loc.line_nb;
```

2.  Observe that `Init/Tauto.v` uses the `ltac:( ... )` construct 8 times.  AFAIK, this is the production for parsing that construct.  For example:

```
Ltac tauto := with_uniform_flags ltac:(fun flags => tauto_gen flags).
Ltac dtauto := with_power_flags ltac:(fun flags => tauto_gen flags).
```
3.  Do a `make -j 1`.  The message doesn't appear at all for `Tauto.v`:

```
OCAMLOPT -shared -o plugins/ltac/tauto_plugin.cmxs
COQC -noinit theories/Init/Tauto.v
OCAMLC -pack -o plugins/ltac/ltac_plugin.cmo
```

I see the message 185 times in the make output.  When I search all the `.v` files in the source tree, I get 
246 occurrences of `ltac:(`.

Is there an explanation?  Is this worth digging into?

**Comment by ppedrot** [comment]
It's not the same entry. The `ltac:(...)` from `Tauto` lives inside Ltac expressions, and the entry in `g_ltac.mlg` lives inside term expressions (i.e. tactic-in-terms). You could trigger it with `Definition foo := ltac:(exact tt)`.

**Comment by ppedrot** [comment]
Forgot to mention that the first one is generated by the call to `Tacentries.create_ltac_quotation` in `extraargs.mlg`.

**Comment by jfehrle** [comment]
Got it, thanks.  I'd like to refactor this at some point so these productions are created with the standard mlg mechanism rather than with OCaml.  Consistency would make them easier to find and understand, also saves having to handle them specially in `doc_grammar`.
