### ISSUE TITLE
Singleton class seemingly leads to subject reduction failure.

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#13146]
I think that the following is just a printing problem, but something strange definitely seems to be going on.
```
Inductive Box (X : Type) : Type :=
| b (x:X).

Class var := { X : Type }.

Definition x := fun T => (fun `(var) (x:X) => b X x) {| X := T |}.
Check x. (* x : forall T : Type, X -> Box X *)
(* Should be x : forall T : Type, T -> Box T

Eval cbv in let (x) := x unit tt in x. (* tt : X *)
```

#### Coq Version
Master

**Comment by ppedrot** [comment]
Looks fine to me. If you set printing all, you'll see that `X` has `Build_var T` as an implicit argument, so this hidden application is convertible to `T`.

**Comment by LasseBlaauwbroek** [comment]
Ah, yes, I just noticed that too. I'm being stupid. Sorry.
