### ISSUE TITLE
[performance] memtrace explorations

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#13161]
I am opening this issue to share / discuss about evaluation of Coq with `memtrace`; there is an excellent post explaining how to use it:

https://blog.janestreet.com/finding-memory-leaks-with-memtrace/

I have done a few experiments myself and the picture looks a bit discouraging, for example w.r.t. allocation in proofs due to the tactic engine, and some other strange spots that I cannot explain. This is likely known by some / most of the developers already, but maybe we could use the graphical tool to better identify some critical spots in the current implementation.

I was going to post some findings, but I'm afraid I don't understand the data well yet so I will refraind until I can gain a better understanding.

Patch to try in Coq master:
```patch
diff --git a/topbin/coqc_bin.ml b/topbin/coqc_bin.ml
index 2006aa2d0f..adea4ee55f 100644
--- a/topbin/coqc_bin.ml
+++ b/topbin/coqc_bin.ml
@@ -10,4 +10,5 @@
 
 (* Main coqc initialization *)
 let _ =
+  Memtrace.trace_if_requested ();
   Coqc.main ()
diff --git a/topbin/dune b/topbin/dune
index 46052c81e5..fcde1769c4 100644
--- a/topbin/dune
+++ b/topbin/dune
@@ -25,7 +25,7 @@
  (public_name coqc)
  (package coq)
  (modules coqc_bin)
- (libraries coq.toplevel)
+ (libraries coq.toplevel memtrace)
  (modes native byte)
  ; Adding -ccopt -flto to links options could be interesting, however,
  ; it doesn't work on Windows
```
Then, for example, if you want to try to compile file `Byte.v`, first make a copy to `MyByte.v` [that's to avoid issues with actifacts]. Then:
```
$ dune build theories/Strings/Byte.vo
$ MEMTRACE=trace-byte.tcr _build/install/default/bin/coqc MyByte.v
$ memtrace-viewer trace-byte.tcr
```

**Comment by ppedrot** [comment]
FTR, I regularly use the ancestor of this tool, namely the statistical profiler developed originally by J.-H. Jourdan (available for OCaml 4.06 and 4.07 from vanilla opam repos, if memory serves) . It's not as rich as what is described in this post UI-wise, but for rough approximations it does the job.

As hinted by @ejgallego, usually memory allocation is dominated by two processes:
- Huge batch allocations at module require time
- A heck of a lot of small allocations when in proof mode that only disappear at Qed time.

> some other strange spots that I cannot explain

@ejgallego Do you have more details on that?

**Comment by ejgallego** [comment]
> @ejgallego Do you have more details on that?

I suggest you see for yourself, for example in `Byte.v` , the tool reports 2GiB allocation in Hashset.find_or.loop, but if I rewrite this function to be imperative it goes away. Not that it matters perf wise. So I'm unsure if the tool is reporting correctly.

Also all the appearances in the profile of the `iter_constr` fucntions are hard for me to understand yet, but I'd guess they are due to sandboxing?

Allocation by the monad seems a bit more worrysome [a good example of this is List.v], but let me try with flambda.

**Comment by ppedrot** [comment]
> allocation in Hashset.find_or.loop
> Allocation by the monad

All of these allocations should be short-lived, so it probably doesn't matter in practice since we set the minor heap to be quite large by default.

> Also all the appearances in the profile of the iter_constr fucntions

No idea about this one, but higher-order functions tend to give weird callstacks.


> I suggest you see for yourself

I'll have a look.

**Comment by ejgallego** [comment]
See original updated post for instructions.
