### ISSUE TITLE
[printing] detyping a term with an untyped letin

### ISSUE THREAD

**Issue by gares** [coq/coq#13160]
```ocaml
  | BLetIn ->
      let c = detype d { flags with flg_isgoal = false } avoid env sigma (Option.get body) in
      (* Heuristic: we display the type if in Prop *)
      let s = try Retyping.get_sort_family_of (snd env) sigma ty with _ when !Flags.in_debugger || !Flags.in_toplevel -> InType (* Can fail because of sigma missing in debugger *) in
      let t = if s != InProp  && not !Flags.raw_print then None else Some (detype d { flags with flg_isgoal = false } avoid env sigma ty) in
      GLetIn (na', c, t, r)
```
Here `Retyping.get_sort_family_of`, if the input is an evar, raises an error which is only (abruptly) catched if we are in coqtop.
I think we should catch all retyping errors (and only these) unconditionally.

I hit this in Elpi where I want to detype a term which I did not pretype yet.

**Comment by gares** [comment]
CC @coq/parsing-maintainers . I'm OK preparing a simple PR making the heuristic more robust, if you agree.

**Comment by herbelin** [comment]
>  I think we should catch all retyping errors (and only these) unconditionally.

You may try... or to address only the case of an evar... I don't know, as you want.
