### ISSUE TITLE
vm_compute has existential crisis

### ISSUE THREAD

**Issue by hamlen** [coq/coq#13169]
#### Description of the problem

There is a bug in `vm_compute` involving existential variable contexts.  The vm seems to be reading the list of hypotheses backwards, with the result that it mismatches the type of the hypothesis at position _i_ with the type of the hypothesis at position _n-i_ (where _n_ is the number of hypotheses in context) when generating existential contexts.  Instantiating the existentials can then yield type-incorrect expressions, from which it is almost possible to prove False (but fortunately the kernel saves us at Qed).  Here is a minimal working example:

```
Goal False.
  set (H1:=I).
  set (x:=true).
  assert (H2: x = true) by reflexivity.
  set (y:=false).
  assert (H3: y = false) by reflexivity.
  clearbody H1 x y.
  eenough (H4: _ = false).
  vm_compute in H4.
  (* H4 now has "x:=y" in the evar context. *)
  2: exact H3.
  contradict H4. rewrite H2. discriminate.
  (* There are no more subgoals.  We have proved False. *)
Fail Qed.  (* thankfully detects the type error and fails *)
```

#### Coq Version

Tested on Coq 8.12.0, 8.11.2, 8.10.2, 8.9.1, and 8.8.2.  Bug does not seem to be present on 8.8.1, so seems to have been introduced in 8.8.2.

**Comment by ppedrot** [comment]
Indeed, the evar context is clearly reversed after step `vm_compute in H4.` This likely happens in vnorm, I remember we already had a similar problem at some point (see #8119). As already observed this is not a kernel soundness issue.

**Comment by hamlen** [comment]
> I remember we already had a similar problem at some point (see #8119).

Yes, more testing reveals that although the particular mwe above doesn't trigger the bug in v8.8.1, other examples raise the anomaly mentioned in #8119 on v8.8.1 and earlier.  So I'm unable to find any version of Coq in which `vm_compute` works correctly with evars.  This is unfortunate since we have a large project that is quite slow without `vm_compute`.

Is there any danger that this could impair the kernel via something like `vm_cast_no_check`?  I don't think so since all evars must be instantiated before `Qed`, but it's worrying.

**Comment by ppedrot** [comment]
> Is there any danger that this could impair the kernel via something like vm_cast_no_check?

No, the problem happens in VM normalization which lives outside of the kernel (and of the TCB for that matter). I'll write a patch.

**Comment by hamlen** [comment]
> I'll write a patch.

Thank you!
