### ISSUE TITLE
SSReflect abstract Error: Anomaly "Uncaught exception Option.IsNone."

### ISSUE THREAD

**Issue by jasoncarr0** [coq/coq#13213]
Sorry if this should be placed elsewhere, but it seems to be internal, and SSReflect is being distributed with the standard library. 

#### Description of the problem

This occurs instead of a proper error when using abstract incorrectly and selecting an existing constant. Minimal example:
```coq
From Coq Require Import ssreflect.
Theorem bad : True.
Proof.
  abstract: True. (* could also be anything, e.g. False *)
```

#### Coq Version

The Coq Proof Assistant, version 8.11.2

**Comment by Alizter** [comment]
Still an issue in coq 8.15+alpha.

**Comment by mrhaandi** [comment]
Current `master` properly reports an error `argument is not a hypothesis`. So, the original anomaly is solved.
