### ISSUE TITLE
Add perennial to Coq benchmarks

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#13221]
#### Description of the problem

In https://github.com/coq/coq/pull/12914, @ppedrot asked if there were other representative Iris-based benchmarks we could add besides lambda-rust. @tchajed then suggested Perennial, which I would not call representative, but it is certainly stress-testing Iris and has lots of slow proofs, so is probably a reasonable performance test. However, it is quite slow to build, taking more than 1h.

Would the Coq team be okay with adding Perennial to its benchmarks, and what would that take?

**Comment by ppedrot** [comment]
Assuming it has a properly working opam file, it's a one-line diff in the list of default packages used in the bench which appears as the `coq_opam_packages` variables in the `gitlab-bench.yml` file.

**Comment by RalfJung** [comment]
I do not think there is an opam file, but I could write one if that is required.
Does it have to be in an opam repository or can you directly pin the git repo?

**Comment by ppedrot** [comment]
We already ping the iris repo, so if it's in there it will be transparent.

**Comment by RalfJung** [comment]
I am not sure if @tchajed wants Perennial to be available in a general opam repository; the usual way to use it is to work directly with the git repository.

**Comment by tchajed** [comment]
The first step would be to add an opam config to the Perennial repo. Is it possible to use that directly @ppedrot by adding https://github.com/mit-pdos/perennial.git to `coq_opam_packages`?

I'm not opposed to having Perennial in an opam repo if that's needed for the benchmark setup, it's just something extra we would be maintaining.

**Comment by ppedrot** [comment]
@tchajed not directly in the variable, but we can pin that package by hand in the bench script.
