### ISSUE TITLE
Bad error message: "foo already exists", but does not exist

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#13249]
#### Description of the problem

The following code leads to a very confusing error message:
```
Global Generalizable All Variables.

Section test.
Context {A : Type}.
Context `{!foo A}.
```
It says
```
Error: foo already exists.
```
Which is not right, or at least not helpful -- the problem is actually caused by `foo` *not* existing. (I just got this error when I had a typo in my typeclass name. If a class named `foo` actually exists, there is no error.)

#### Coq Version

8.12.0

**Comment by silene** [comment]
I don't think there is any issue with the error message. (Indeed, `foo` does exist, because of `Generalizable All Variables`.) The bug comes from the fact that `{foo A}` fails to generate a fresh name for the hypothesis. For example, the following correctly generates a fresh name:
```coq
Context {foo} `{!foo A}.
```

**Comment by RalfJung** [comment]
The error message is certainly entirely unhelpful, so I think that is enough to make this a bug. ;)

>  (Indeed, foo does exist, because of Generalizable All Variables.) 

The error occurs when stepping over `Context `{!foo A}.`. `foo` does not exist *before that step*, so the error is something between wrong and misleading. Worse, I can never even reach the state where `foo` exists: there is no moment in this proof where `About foo.` shows a result. I think that is fairly strong evidence that `foo` does not exist in any sense that is useful for the user.

**Comment by silene** [comment]
So, I take it that you would prefer we fix the error message rather than the actual bug.

**Comment by RalfJung** [comment]
What about both?^^

I take it the issue with the error here is that the moment the name already exists is somewhere in the middle of executing this step? So the `already` makes sense locally, but makes little sense for the user when it is not clear any more what point in time this references.
