### ISSUE TITLE
Confusing error location on tactic failure

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#13241]
#### Description of the problem

A [Coq proof check on CI](https://gitlab.mpi-sws.org/iris/lambda-rust/-/jobs/98534) failed with the following error message:
```
File "./theories/base.v", line 7, characters 13-31:
Error: No applicable tactic.
Makefile.coq:719: recipe for target 'theories/lang/arc_cmra.vo' failed
make[2]: *** [theories/lang/arc_cmra.vo] Error 1
```
Note how Coq says that the error is in `./theories/base.v`, which is a file that does not even exist in this repository. As make says, the actual failure is in `theories/lang/arc_cmra.v`.

The failure occurs while executing the `done` tactic, which is defined in `stdpp.base`.  Looks like the Coq error reporting is getting confused and shows the tactic definition as the error location, instead of the place where the tactic is invoked. And then it additionally shows a not very helpful file path, relative to the stdpp repository instead of relative to where the current build is happening. (It might be useful to *also* show the tactic definition, but if you show only one location, then it certainly should be the top-level command in the proof script that actually failed. Also the filename should then clearly indicate that the error occurred in a file installed in `user-contrib`.)

#### Coq Version

```
name        coq
version     dev
source-hash 9db73ef1
```

**Comment by herbelin** [comment]
Thanks for the report. Yet another instance of #12223, #12773, #12992, #12774, #12999, apparently showing a case of indirection not yet tracked. Could you identify which occurrence of `done` in `arc_cmra.v` failed? Also, I thought that `done` was in `stdpp.tactics`. Could you identify to what "line 7, characters 13-31" exactly refers to?

**Comment by RalfJung** [comment]
[This is the `done` that failed](https://gitlab.mpi-sws.org/iris/lambda-rust/-/blob/36a7f77cfbd2d99153882ddef6d80cb913799433/theories/lang/arc_cmra.v#L373).

Good point about the filename making even less sense than I thought. No idea what that line 7 is about...

**Comment by herbelin** [comment]
@RalfJung: do you have a way to reproduce? I tried to compile the `masters/weak_mem` lambda-rust branch and it does not fail.

Or, better, could you isolate a simpler example?

**Comment by RalfJung** [comment]
> do you have a way to reproduce?

You probably need the exact right versions of all the dependencies... lambda-rust-weak_mem 36a7f77cfbd2d99153882ddef6d80cb913799433, and then
```
name        coq
version     dev
source-hash 9db73ef1
name        coq-stdpp
version     dev
source-hash b0b60193
name        coq-iris
version     dev
source-hash 402b0745
name        coq-orc11
version     dev
source-hash 1a4c68cc
name        coq-gpfsl
version     dev
source-hash e29403ca
```

> Or, better, could you isolate a simpler example?

I don't think I'll have the time for that this week, sorry.

**Comment by Zimmi48** [comment]
You could have a try at calling the bug minimizer in the cloud. Cf. https://github.com/coq/coq/wiki/Coqbot-minimize-feature

**Comment by herbelin** [comment]
A short example:
```
Ltac a := intro.
Ltac b := a.
Goal True.
b. (* Located on the second line *)
```
Note for @RalfJung: In the original report, `./theories/base.v` refers to the file in `orc11` which introduces an indirection on the definition of `done`.

Fixed in #13241

**Comment by RalfJung** [comment]
> ./theories/base.v refers to the file in orc11 which introduces an indirection on the definition of done.

Ah I see. Good catch!

**Comment by herbelin** [comment]
> You mean #13247 I assume.

Yes, number fixed.
