### ISSUE TITLE
Feature request, derive Prop rather than Type

### ISSUE THREAD

**Issue by gert-smolka** [coq/coq#13278]
## Description of the problem

The following code does not type check if the type ascription ": Prop" is removed.
It should be easy to derive Prop rather than Type.
The failure to derive Prop invalidates interesting smart matches.
See https://coq.discourse.group/t/bug-in-universe-inference/1093?u=gert-smolka.

```
Inductive even: nat -> Prop :=
| evenB: even 0
| evenS: forall n, even n -> even (S (S n)).

Goal even 1 -> False.
Proof.
  refine (fun a => match a in even n 
                   return match n with 1 => False | _ => True end : Prop
                   with evenB => I | evenS _ _ => I end).
Qed.
```

**Comment by herbelin** [comment]
Hi @gert-smolka, I also fell on this limitation in the past, thanks for reminding it. I made a proposal at #13290.
