### ISSUE TITLE
Documentation should specify what scientific notation on hexadecimal numbers means

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#13280]
#### Description of the problem

In https://github.com/coq/coq/blob/a12112c15cdcb0467d4cf5f5a7cfa639852ccd49/doc/sphinx/language/core/basic.rst#L114-L134

There is no description of the semantics of `e`/`E` nor `p`/`P`.  I know from common usage that `e`/`E` means `*10^`, and apparently (from experimentation) `p` means `*2^`.  Both of these should be documented.

cc @proux01

#### Coq Version

master

**Comment by G-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by JasonGross** [comment]
Yes, this seems reasonable

**Comment by JasonGross** [comment]
@G-Sheridan yes, that seems reasonable, thanks
