### ISSUE TITLE
Improve error message when "Arguments ... : clear implicit" is used with implicit annotations.

### ISSUE THREAD

**Issue by fakusb** [coq/coq#13283]
Sometimes, one wants to change which arguments of a constant are implicit which are not.

I just found out about the "rename" command because I wanted `clear implicit` to behave like `rename`. Before I always called Arguments twice: once to clear implicits, and once to set new.

Maybe one could improve the error message here:

````
Require Import Fin.

Fail Arguments Fin.of_nat_lt _ {_} _: clear implicits.
Arguments Fin.of_nat_lt _ {_} _: rename.
````

The Error is: `The "clear implicits" flag is incompatible with implicit annotations`
It could be: `The "clear implicits" flag is incompatible with implicit annotations. Use "rename" flag instead`

Alternatively, one could allow the failing command from above, so that `clear implicit` behaves like `rename`.

**Comment by Zimmi48** [comment]
FYI, there is a new manual page which presents the full `Arguments` command: https://coq.inria.fr/refman/language/extensions/arguments-command.html

As shown in the doc, you don't actually need any modifier to use the `Arguments` command. What you want to do should be done as:

```coq
Require Import Fin.

Arguments Fin.of_nat_lt _ {_} _.
```

- `clear implicits` is to make all arguments explicit, so it's normal that it is incompatible with some implicit argument declaration.
- `rename` is to allow renaming an argument; you do not need it in your case.

Example where `rename` is needed:

```coq
Require Import Fin.

Arguments Fin.of_nat_lt _ {m} _.
(* Error: Flag "rename" expected to rename n into m. *)
```

With this in mind, what do you suggest to improve the error message?

**Comment by Zimmi48** [comment]
Answering my own question. Maybe the error message could say "remove the clear implicits modifier to manually set the implicit status of each argument".

**Comment by fakusb** [comment]
I found the new manual page already very informative, and found the rename flag there.


Up to today, I thought that by itself, "_" just does not change anything about this argument.

So is the semantics as follows: ?

* If at least one `{ ..}` or `[ ... ]` annotation is used, all implicity annotations used in this `Arguments` command, and only they, are effctive.
* otherwise, implicity is left unchanged, unless `clear implicit` is set. (is this why the `assert`-warning exists?)

Or are there any flags that change this behaviour?


I did not find the part of the page that tells me that part of the semantics: 
Is it in the explanation of `name [% scope ]^?` ? And is "a formal parameter of the function `reference`" there synonymous with "a non-implicit argument of the function `reference`"?

If yes, maybe one should adjust this part of the documentation to say "declares `name` as an non-implicit argument

**Comment by Zimmi48** [comment]
Yes, I think you described the correct semantics.

It may be @jfehrle who introduced this "formal parameter" terminology to mean an argument of the function without excluding implicit arguments. But I think we should refrain from introducing terms that are not defined, so maybe this text needs a bit of change.

If, based on this information, you see how to improve the error message, or the documentation, or both, feel free to open a PR with a proposal.

**Comment by jfehrle** [comment]
I thought the distinction between formal parameters (those used in a function definition) and actual parameters (those used to call a function) was well known.

> we should refrain from introducing terms that are not defined, so maybe this text needs a bit of change.

You don't consider this a definition?

```(i.e. the parameter name used in the function definition)```

**Comment by Zimmi48** [comment]
>I thought the distinction between formal parameters (those used in a function definition) and actual parameters (those used to call a function) was well known.

Apparently this is well known at least in the Java world (https://chortle.ccsu.edu/java5/Notes/chap34A/ch34A_3.html) and the C++ world (https://stackoverflow.com/questions/18870156/what-is-a-formal-parameter).

I didn't know about it personally.

> You don't consider this a definition?
> 
> `(i.e. the parameter name used in the function definition)`

Oh, right!

**Comment by Zimmi48** [comment]
What was actually done to close this issue was to improve the documentation. Should we update the title to reflect that or reopen the issue until we also improve the error message?

**Comment by jfehrle** [comment]
As @Zimmi48 notes, #13293 only changed the documentation, so re-opening.
