### ISSUE TITLE
Infinite loop with implicit arguments, class and existing instance

### ISSUE THREAD

**Issue by roglo** [coq/coq#13291]
#### Description of the problem

The last line loops
~~~coq
Set Implicit Arguments.
Class toto T := { pouet : T }.
Record titi T (so : toto T) := { arghh : list T }.
Definition gloups T (so : toto T) := {| pouet := {| arghh := nil |} |}.
Existing Instance gloups.
Definition glop T {so : toto T} (P : titi so) := 42.
Theorem tagada : glop 1 = 0.
~~~

#### Coq Version

The Coq Proof Assistant, version 8.12.0 (November 2020)
compiled on Nov 1 2020 1:38:08 with OCaml 4.11.2+dev0-2020-08-31

But it is the same in version 8.11.

**Comment by SkySkimmer** [comment]
Not a bug, just a typeclass loop AFAICT. Not sure what you expected.

**Comment by roglo** [comment]
Yes it is a bug! A compiler must never loop, but answer an error message!

**Comment by roglo** [comment]
I have another example in my code of something perfectly well typed that loops.

**Comment by JasonGross** [comment]
Typeclass instances (like Ltac) are Turing complete.  There's no way to avoid loops in general.

**Comment by herbelin** [comment]
What about fixing `Set Typeclasses Depth` to some limit by default. After all, we could consider that it is to the experts to know that the limit can be deactivated if they need (like for `auto` and `eauto`).

**Comment by roglo** [comment]
I agree with @herbelin

**Comment by roglo** [comment]
What happens, in my example, that make the thing loop?

**Comment by JasonGross** [comment]
You can debug typeclass loops with `Set Typeclasses Debug.`.  In this case, typeclass resolution tries to infer an instance for `toto ?[T]`, sees the hint of `gloups : toto T -> toto T`, and applies it to the goal ad infinitum.  (In general, you want your typeclass instances to be an acyclic graph, or to emit `Hint Cut` to prevent loops, or else you want to be very, very careful about priorities.)

**Comment by roglo** [comment]
@JasonGross: ok, thanks. @Zimmi48 told me about trying out `Set Typeclasses Debug`, but I had not tested it yet. Testing it, the looping seems very visible indeed, even if I don't see what internally happens. All of this is a part of Coq I don't understand well. I just practice type classes to allow syntax extensions, like `"P+Q"` for a sum of two polynomials or two matrices. For the moment, the `Set Typeclasses Depth 100` makes the whole thing work and I am happy with that.

I would like also to apologize to several people about my first angry reactions about all of this. I understand better now. By the way, Camlp5 can also infinitely loop, since the syntax extensions are 100% user code, even if the ones provided in its library are not supposed to loop.
