### ISSUE TITLE
Notations don't resolve universes until use

### ISSUE THREAD

**Issue by jashug** [coq/coq#13303]
#### Description of the problem

As pointed out by @SkySkimmer in #13299, in the current system (both master and this PR) universe expression are unchanged by the intern phase and completely handled at the pretyping phase, but we should be resolving global universes in the intern phase.

#### Test Cases

```coq
Module M. Universe i. End M.
Module N. Universe i. End N.
Import M.
Notation foo := Type@{i (* M.i??? *)}.
Import N.
Check foo : Type@{M.i}. (* should NOT succeed *)
Fail Check foo : Type@{i (* N.i *)}. (* should succeed *)
```

```coq
Module M. Universe i. Notation foo := Type@{i}. End M.
Fail Definition foo1 := M.foo. (* should succeed, currently errors undeclared universe i *)
Fail Definition foo2@{i} : Type@{i} := M.foo. (* should succeed, currently errors universe inconsistency *)
```

**Comment by SkySkimmer** [comment]
@jashug do you think you'll work on this issue soon? Otherwise please remove your assignment.

**Comment by jashug** [comment]
@SkySkimmer I wish I would, but I won't. Thanks for pinging me.
