### ISSUE TITLE
Change in the strength of the tactic firstorder between 8.11.2 and 8.12.0? 

### ISSUE THREAD

**Issue by ianshil** [coq/coq#13306]
Hi, 

The following code goes through in CoqIDE 8.11.2: 

```
Require Import List Omega.
Import ListNotations.

Lemma firstorder_problem {T : Type} (X Y : list T) (a b : T) :
  X ++ [a] ++ b :: Y = (X ++ [a]) ++ [b] ++ Y.
Proof.
firstorder.
Qed.
```

While in CoqIDE 8.12.0 the tactic `firstorder` leaves the goal unchanged. Was that intended? 

Best,
Ian

**Comment by Zimmi48** [comment]
Yes, as mentioned in the [changelog](https://coq.inria.fr/refman/changes.html#tactics):

>**Changed:** The default tactic used by firstorder is `auto with core` instead of `auto with *`; see Decision procedures for details; old behavior can be reset by using the `-compat 8.12` command-line flag; to ease the migration of legacy code, the default solver can be set to `debug auto with *` with `Set Firstorder Solver debug auto with *` (#11760, by Vincent Laporte).

Let us know if you need additional help.

**Comment by ianshil** [comment]
@Zimmi48 Thank you for reply. I will get into the habit of reading the changelog from now on! ;-)
