### ISSUE TITLE
Coqdoc: verbatim mode ends at >> anywhere in the text, not just at begin of line

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#13304]
The reference manual says: "Verbatim material is introduced by a leading << and closed by >> __at the beginning of a line__." See [verbatim](https://coq.inria.fr/refman/using/tools/coqdoc.html?highlight=coqdoc#verbatim).

Actually verbatim mode is ended at a `>>` in the middle of the text, not just at the beginning of a line, which is a sever issue for documenting C code where `>>` is a common operator.

This is with Coq 8.12.0 release on Mac.

**Comment by herbelin** [comment]
Hi @MSoegtropIMC, apparently inlined verbatim was introduced in 2012 (893a3ac7b281) but not documented. I don't know what to do (between deactivating it or documenting it). What is your example? What happens if you put the C code between `[` `]`?

**Comment by MSoegtropIMC** [comment]
@herbelin : ah, so this is an undocumented feature and not a bug ;-)

I tried various combinations of [] and << >> as delimiter but none of them had a positive effect.

Here is an example:
```
(**
<<
uint32_t shift_right( uint32_t a, uint32_t shift )
{
    return a >> shift;
}
>>
*)
```
The `>>` in `a >> shift` is not shown, the shift is printed in a new line and with different font.

I would recommend to:
- remove inline verbatim with << and >> as delimiters
- add standard makrdown delimiters for block verbatim (triple back tick) and inline verbatim (single back tick). As far as I can tell the back tick is not commonly used in programming languages.
- possibly deprecate << and >> as block verbatim

**Comment by herbelin** [comment]
@MSoegtropIMC: in #13308, I'm proposing to simply avoid the two kinds of verbatim (block or oneliner) to overlap. This solves your issue and has the advantage of compatibility. Is it ok for you?
