### ISSUE TITLE
Search: string search tries to interpret strings as references.

### ISSUE THREAD

**Issue by chdoc** [coq/coq#13349]
#### Description of the problem

This is another regression of the new search command over ssrsearch: one can no longer search numbers as substrings of lemma names. 

```coq
Require List.
Search "eq" inside List.
Fail Search "1" inside List. 
Require ssrsearch.
Search "1" in List.
```
The Fail command fails with: `Unable to interpret "1" as a reference` which is strange given that this is supposed to search for substrings in lemma names. 

#### Coq Version

8.12.0

**Comment by Zimmi48** [comment]
This is indeed a deviation with respect to the specification which says that if a string is a substring of a valid identifier and no `% scope_key` is provided, then it searches for objects containing the string in their name.

**Comment by herbelin** [comment]
Thanks for the example! Fixed in #13351 (@Zimmi48: I put the 8.12.1 milestone but only in cade the releasing process is not started yet of course).

**Comment by chdoc** [comment]
@herbelin thanks, I was indeed hoping to sneak this into 8.12.1.

**Comment by Zimmi48** [comment]
8.12.1 is still waiting for the unsoundness bug fix to be merged, so there's still a little bit of time indeed.
