### ISSUE TITLE
Add ML Path is not compiled into .vo file

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#13344]
Steps to reproduce:
- Create a file `test_ocaml/test_ocaml.ml`, such that the directory `test_ocaml` is _not_ in Coq's ML load path, with the following contents:
```
let _ = print_endline "hi"
```
- Compile this file using `ocamlopt test_ocaml.ml -shared -o test_ocaml.cmxs`
- Create a file `LoadPathTest.v` (outside of the directory `test_ocaml`):
```
Add ML Path "test_ocaml".
Declare ML Module "test_ocaml".
```
- Compile this file using `coqc LoadPathTest.v`.
- The file should succesfully compile, and output "hi"
- Create a file `LoadPathTest2.v` with the contents ```Require Import LoadPathTest```.
- Compile using `coqc LoadPathTest2`. Now a load path error occurs. I would expect that the `Add ML Path` command is executed just as it was during compilation of the first file.

#### Coq Version
8.11 and 8.12

**Comment by LasseBlaauwbroek** [comment]
See [here](https://coq.discourse.group/t/how-to-properly-configure-the-ml-load-path-for-ocaml-packages-in-opam-projects/1109) for motivation for why I want to do this.

**Comment by silene** [comment]
Commands like `Add ML Path` are equivalent to passing options on the command line. They have never been stored in `.vo` files nor replayed on loading. I doubt there would be a consensus to change this behavior. Actually, the consensus is rather on just removing these antiquated commands. So, I am tentatively closing this report. Let us reconsider once people have reacted to your post.

**Comment by LasseBlaauwbroek** [comment]
Okay, in that case it might still be good to have some documentation on this behavior. It indeed seems to make these commands completely useless...

**Comment by silene** [comment]
These commands were meant to be used in the `coqrc` file or in the prelude sent by interactive systems (e.g., ProofGeneral). They really are just another way of passing command line arguments.

**Comment by LasseBlaauwbroek** [comment]
Fair enough, but documentation should still be warranted because this firmly falls into the area of unexpected behavior if one does not know the history of the commands.

**Comment by Zimmi48** [comment]
I agree with the need to clarify the documentation and apparently @herbelin too and he has already opened a PR. So reopening as a documentation issue.

**Comment by ejgallego** [comment]
That info could indeed be stored in the .vo file indeed, it is mostly useful for libraries that can be linked.

Actually if you use dune to build a theory depending on another theory, flags will be lost if that's installed globally as indeed we have no equivalent of the info stored in the cmxa file for OCaml.

So a variation of this problem does still exist. Will add to my todo list.

**Comment by ejgallego** [comment]
@LasseBlaauwbroek , I just read your discourse post and indeed I see you are exactly describing the problem I was referring to. Looking into it.

**Comment by herbelin** [comment]
I'm not sure I understand how robust to relocalisation a path stored in a `vo` can be, but if ever `Add ML Path` has an application in combination with OPAM's `subst` feature, the documentation given in this PR will have to be changed...

**Comment by Zimmi48** [comment]
I think your PR describes the current use case, so it's good to go as is IMHO.

**Comment by ejgallego** [comment]
> I'm not sure I understand how robust to relocalisation a path stored in a `vo` can be

Certainly that meta-data would be live somewhere else, and not in the form of path. But indeed it is something you need to let others know once you start having specified libraries. The only reason it works now when we install, is because Coq actually adds all of user-contrib to -I :)

> but if ever `Add ML Path` has an application in combination with OPAM's `subst` feature, the documentation given in this PR will have to be changed...

I'd say that's a temporary hack and we should be able to provide a better setup.
