### ISSUE TITLE
Make Primitive Arrays cumulative

### ISSUE THREAD

**Issue by fakusb** [coq/coq#13354]
In the current master branch, the primitive arrays in the PArray module are not cumulative, which means that functions operating on them probably need to be universe polymorphic in practice, e.g. the following needs the `Polymorphic`-annotation:

````
Require Import Array.PArray BinInt.
Require Import Int63.

Definition testArray : array nat := [| 1; 2; 4 | 0 : nat |].

Polymorphic Definition array_fold_right {A B : Type} (f: B -> A -> A) (a:A) (bs:array B) : A :=
  let size := length bs in
  fst (nat_rect (fun _ => (A*int)%type) (a,size-1)%int63
       (fun _ '(a',i)=> ( f (get bs i) a' ,pred i)) (Z.to_nat (Int63.to_Z size))).

Compute array_fold_right cons nil testArray.
````

Would it be a good Idea to make "array" cumulative?

**Comment by fakusb** [comment]
Note that afaik, "cumulative" currently only makes sense for inductive definitions.

**Comment by ppedrot** [comment]
Cumulativity makes sense for any type former. It so happens that we don't have that many type formers, but the type of array should definitely be cumulative. I don't think it's very hard to change though.

**Comment by ppedrot** [comment]
(Actually it might be even easier to allow more generally cumulativity for axioms that have an arity as type. We could mark them as a special kind of primitive inductive type or something.)

**Comment by Zimmi48** [comment]
Since primitive arrays are new in 8.13, is this something that should be fixed / changed before the release? I'm tentatively adding the milestone.

**Comment by ppedrot** [comment]
It's a nontrivial change to the kernel though, it might be dangerous to push so fast.

**Comment by ppedrot** [comment]
(Sorry, misclicked on the closing button.)

**Comment by SkySkimmer** [comment]
I'm looking into doing a change specific to array.
