### ISSUE TITLE
Anomaly: "not an arity"

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#13366]
#### Description of the problem

Minimized example:

```
Class Functor (F : Type -> Type) : Type :=
  fmap : F nat.

Lemma blah : sum fmap.
```

Output:

```
Anomaly "Not an arity." Please report at http://coq.inria.fr/bugs/.
```

#### Coq Version

Tested on 8.12, dev a10e7b3e47

**Comment by SkySkimmer** [comment]
It looks like a unification `?X nat <= Type` is postponed, leading retyping to break (in the usual template poly deep retyping).

This unification looks like it has a unique solution to me, could we avoid postponing it? @herbelin 

Until then I suppose we should extend the hack from 742ef62fe8050a6865d06bd644e30cbec0e7eb02, I'll make a PR.

**Comment by herbelin** [comment]
> It looks like a unification ?X nat <= Type

This one has a unique solution since `nat` cannot be used to build a sort, but if it were e.g.
```
Class Functor (F : Type -> Type) : Type :=
  fmap : F Type.

Lemma blah : sum fmap.
```
then, another solution would also be `fun x => x`.

> Until then I suppose we should extend the hack from 742ef62, I'll make a PR.

That seems a good idea.

A slightly more minimap example in passing:
```
Parameter fmap : forall (F:Type -> Type), F nat.
Check option (fmap _).
```
