### ISSUE TITLE
Coq opam files should use a valid SPDX identifier.

### ISSUE THREAD

**Issue by tchajed** [coq/coq#13372]
Coq does not clarify whether its license allows updates to the LGPL license. The opam file should use a valid SPDX identifier for the license: LGPL-2.1 has been deprecated and now https://spdx.org/licenses/ specifies that the license should be either LGPL-2.1-only or LGPL-2.1-or-later.

@Zimmi48 do you know if this is established already?

The reason this came up is that Homebrew's `brew audit --strict` now issues an error due to not using a valid SPDX identifier and I'm not sure which of these two to set it to in Homebrew.

**Comment by Zimmi48** [comment]
The answer is "LGPL-2.1-only" (even if I'm sad about it, of course).
This follows the fact that the headers (https://github.com/coq/coq/blob/master/dev/header.ml) do not contain the "or later" wording that would make it "LGPL-2.1-or-later".
You are right that we should fix the opam files that this repository contains. However, the one in the opam-repository are fine (see https://opam.ocaml.org/packages/coq/).

**Comment by Zimmi48** [comment]
I've edited the title because there is nothing to change in the `LICENSE` file itself.

**Comment by tchajed** [comment]
Cool, thanks @Zimmi48! That does definitively say what we should do for the Homebrew formula at least, so it solves my underlying issue.
