### ISSUE TITLE
Bug of `About` rendering to indicate implicit arguments (with utf8 forall)

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#13392]
#### Description of the problem

Functions with many arguments where some are implicit are rendered as follows in `About`:
```
left_id_L : ∀ (A : Type) (i : A) (f : A → A → A), LeftId eq i f → ∀ x : A, f i x = x

left_id_L is not universe polymorphic
Arguments left_id_L {A}%type_scope _ _%function_scope {H}
left_id_L is opaque
Expands to: Constant stdpp.base.left_id_L
```
Frequently, I find myself in the situation where I want to, for example, pass `x` explicitly -- so I need to figure out how many non-implicit arguments precede `x`. This is actually non-trivial to find out, as it is not immediately obvious where `x` is in the `Arguments` (or if it is in there at all, as in this case!). I need to match up the `Argument` with the given type, figure out which of them are implicit (note that some names occur only in `Arguments` and not in the type, such as `H`), and then count how many are *not* implicit.

It would help a lot if the type could be rendered more like how the lemma would actually be written in the source:
```
left_id_L : ∀ {A : Type} (i : A) (f : A → A → A), `{!LeftId eq i f} → ∀ x : A, f i x = x
```
Now it is immediately obvious that `x` is the third non-implicit parameter.

#### Coq Version

8.12.0

**Comment by SkySkimmer** [comment]
Isn't this already in 8.12? https://github.com/coq/coq/pull/11795

**Comment by Zimmi48** [comment]
Indeed, are you sure you tested this on 8.12.0 @RalfJung? In this case, it would likely be a bug and we would need a reproducible example.

**Comment by RalfJung** [comment]
> Isn't this already in 8.12? #11795

Oh, that's awesome. :)

But it does not seem to always work. Here's a reproducible example:
```coq
From Coq Require Export Morphisms RelationClasses List Bool Setoid Peano Utf8.

(** Throughout this development we use [stdpp_scope] for all general purpose
notations that do not belong to a more specific scope. *)
Declare Scope stdpp_scope.
Delimit Scope stdpp_scope with stdpp.
Global Open Scope stdpp_scope.

Notation "(=)" := eq (only parsing) : stdpp_scope.

Hint Extern 0 (_ = _) => reflexivity : core.
Hint Extern 100 (_ ≠ _) => discriminate : core.

Class LeftId {A} (R : relation A) (i : A) (f : A → A → A) : Prop :=
  left_id x : R (f i x) x.

Arguments left_id {_ _} _ _ {_} _ : assert.

Lemma left_id_L {A} i f `{!@LeftId A (=) i f} x : f i x = x.
Proof. auto. Qed.

About left_id_L.
```

**Comment by SkySkimmer** [comment]
The problem is the Utf8 forall notation.

**Comment by SkySkimmer** [comment]
Small example:
~~~coq
Notation "∀ x .. y , P" := (forall x, .. (forall y, P) ..)
  (at level 200, x binder, y binder, right associativity,
  format "'[  ' '[  ' ∀  x  ..  y ']' ,  '/' P ']'") : type_scope.

Definition id {A} (a:A) := a.
About id.
~~~

**Comment by SkySkimmer** [comment]
`Check ∀ {A : Type}, A -> A.` works fine so it should be possible to solve this.
Maybe @herbelin can guide us?

**Comment by herbelin** [comment]
>  Maybe @herbelin can guide us?

Hum, a priori not so trivial to do.

Either the insertion of implicit arguments mark in `constrextern.ml` is changed so as to be done on `glob_constr` before calling `extern`, or the implicit arguments have to be passed to `match_notation_constr` so that `Notation_ops.match_extended_binders` puts them on the binders of the notation.

Maybe option 1 would be the simplest solution, not so easy to say.
