### ISSUE TITLE
Arguments simpl never is ignored by subsequent definitions

### ISSUE THREAD

**Issue by CohenCyril** [coq/coq#13428]
#### Description of the problem

The problem occurred in https://github.com/math-comp/math-comp/pull/660
Here is a canonical example:
```coq
Arguments plus : simpl never.
Lemma test P : P (1 + 2).
simpl. (* P (1 + 2) as expected *)
match goal with |- P (_ + _) => idtac "ok" end.
Abort.

Definition plus' := plus.
Lemma test P : P (plus' 1 2).
simpl. (* P 3, not expected *)
Fail match goal with |- P (plus' _ _) => idtac "ok" end. (* Should succeed! *)
Fail match goal with |- P (plus _ _) => idtac "ok" end. (* or at least, this should succeed! *)
Abort.
```
Of course we can lock `plus'` again!
```coq
Arguments plus' : simpl never.
```
 But it is impossible/impractical for local definitions
```coq
Lemma test (P : nat -> Prop) : False.
pose (plus'' := plus').
assert (P (plus'' 1 2)).
simpl. (* P 3, not expected *)
Fail match goal with |- P (plus'' _ _) => idtac "ok" end. (* Should succeed! *)
Abort.
```

In constrast, ssreflect's `nosimpl` trick works perfectly:
```coq
Require Import ssreflect.

Definition nosimpl_plus := nosimpl plus.
Lemma test P : P (nosimpl_plus 1 2).
simpl. (* P (nosimpl_plus 1 2) as expected *)
match goal with |- P (nosimpl_plus _ _) => idtac "ok" end.
Abort.

Definition nosimpl_plus' := nosimpl_plus.
Lemma test P : P (nosimpl_plus' 1 2).
simpl. (* P (nosimpl_plus' 1 2) as expected *)
match goal with |- P (nosimpl_plus' _ _) => idtac "ok" end.
Abort.
```
ssreflect's `nosimpl` could even be used to compensate for this bug as in:
```coq
Lemma test (P : nat -> Prop) : False.
pose plus'' := nosimpl plus'.
have : P (plus'' 1 2).
simpl. (* P (plus'' 1 2) as expected *)
match goal with |- P (plus'' _ _) => idtac "ok" end.
Abort.
```
#### Coq Version

Coq 8.10 and above

**Comment by CohenCyril** [comment]
CC @gares

**Comment by CohenCyril** [comment]
BTW, ssreflect `nosimpl` does not resist `cbn`, while `Arguments : simpl never`  does and BTW resists this bug!
- I am never using `cbn`, so I'm wondering whether the behaviour of `simpl never` should be configurable for `cbn` (e.g. `cbn never` vs `simpl never` vs `cbn never, simpl never).
- I cannot turn the switch off (except by enclosing it inside a section), other switches have `clear` switches, but I cannot find the one to cancel a `simpl never`...

**Comment by Zimmi48** [comment]
> I am never using `cbn`

Is there any deep reason or just habit?

**Comment by gares** [comment]
I'm sorry, but `cbn` is not a better `simpl`. Unfortunately it does not work (it does not refold as it should) and IMO its broken in the design. There is even a flag, IIRC, to remap `/=` to `cbn`, but it simply can't happen. IMO we advertised `cbn` to our users a bit too early.

**Comment by Zimmi48** [comment]
The documentation for `simpl` and `cbn` still contains the following sentence: "The cbn tactic is claimed to be a more principled, faster and more predictable replacement for simpl." (the "claimed" was probably added more recently than the rest of the sentence). I would appreciate any doc PR from someone who knows the differences and the caveats to:
1. remove this sentence;
2. summarize quickly the differences and the caveats.

**Comment by CohenCyril** [comment]
Well @Zimmi48, as I just said, `cbn` expands `nosimpl` eagerly, and `nosimpl` is currently the mechanism in use in mathcomp to prevent simplifications, so I never used `cbn` until now. I think `cbn` cannot replace `simpl` in mathcomp right now because it expands local definitions a bit too eagerly for the current scripts (and maybe to allow for a reasonable control on the objects in the goal). However, whether we use `cbn` or `simpl` it is a bit embarrassing not be able to control the simplification behavior of local constants (as for global ones).

@gares do you have an example where `cbn` does not refold correctly? (I cannot find one myself)

**Comment by gares** [comment]
@maximedenes knows better. IIRC:
- cbn computes in "call by name" (and not call by need) so if you really have a long computation you wait
- cbn does not incur in one exponential behavior of simpl that is due to testing repeatedly if an argument does reduce to a constructor
- cbn "expects" arguments that don't change during recursion to come first, if it is not the case it has hard times refolding IIRC (you can see this problem in Pierre's thesis where "plus" is not defined the usual way)
- simpl does not use a reduction machine, so sharing computations is hard. some miscommunication made people thing that cbn would solve that (it is based on a VM) but does not, since it is by name

**Comment by gares** [comment]
>     * cbn "expects" arguments that don't change during recursion to come first, if it is not the case it has hard times refolding IIRC (you can see this problem in Pierre's thesis where "plus" is not defined the usual way)

I can't reproduce this behavior no more, so maybe it was fixed, or maybe my memory tricks me.

**Comment by ybertot** [comment]
I believe the check on the reduction behavior "simpl never" is bypassed because of the call to whd_betadeltazeta_stack at https://github.com/coq/coq/blob/5b15fce17d856dfbd51482f724ddf5e5f9646073/pretyping/tacred.ml#L272
It seems another reduction function would be needed here, one that at least checks that no function with "simpl never" is being unfolded in the delta steps.

**Comment by herbelin** [comment]
A few related questions:
- Would it be worth to take also into account `simpl nomatch` and the `/` and `!` modifiers for constants occurring in other constants? (That would probably require a bit of work, but that would also be consistent with checking `simpl never` on inner constants.)
- IIUC, `nosimpl` is statically inserted in the code while `simpl never` is treated dynamically; are there situations where it matters? I.e. would we ideally need both?
- `simpl` is still sometimes ignoring `simpl never`, see #18581, but taking it into account sems to introduce quite a lot of incompatibilities; I wonder what the experience of mathcomp would say on this question.
