### ISSUE TITLE
Coercion masks notation

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#13432]
```coq
Record word := { rep: Type }.

Coercion rep : word >-> Sortclass.

Axiom myword: word.

Axiom foo: myword.

Notation "'(_' 'BitVec' '32)'" := (rep myword).

About foo.
```

prints

```
foo : myword
```

Desired behavior: It should print

```
foo : (_ BitVec 32)
```

As a workaround, if I do `Set Printing Coercions.`, I get the desired output, but I'm not sure if I'd always want to print all coercions to make notations work.

Not sure if this is a bug or a feature though...

Coq version: 8.12.0

**Comment by herbelin** [comment]
Hi, this is indeed a regression of 8.12.0 and 8.12.1. Thanks for reporting. Fixed in #13436.
