### ISSUE TITLE
[windows] menhir is an addon

### ISSUE THREAD

**Issue by gares** [coq/coq#13452]
Apparently all "platform software", eg ocaml, dune, elpi, ... is not an addon, even if some addons require it.
Menhir is both "platform software" with an explicit version in the scripts, and an addon one can turn on/off.
I guess it should disappear from the addon menu, see #13449

**Comment by Zimmi48** [comment]
The addon part is menhirlib. It's a bit like Elpi and Coq-Elpi, except that the source code of menhirlib, which used to be separate, was merged into the menhir repository.

**Comment by silene** [comment]
I do not quite follow. Is that a bug that needs fixing? For 8.14?

**Comment by Zimmi48** [comment]
I think this bug is made obsolete by the removal of the Windows installer code from the Coq repo.
