### ISSUE TITLE
[windows][ci] installer names and CI names differ

### ISSUE THREAD

**Issue by gares** [coq/coq#13451]
This discrepancy complicates the release process a little, see https://github.com/coq/coq/pull/13449
```
  | sed -e 's/^aactactics$/aac_tactics/' \
        -e 's/^gappa$/gappa_plugin/' \
        -e 's/^HB$/elpi_hb/' \
        -e 's/^extlib$/ext_lib/' \
```

**Comment by silene** [comment]
The discrepancy is unfortunate, but it does not seem like fixing is especially needed, so postponing.

**Comment by gares** [comment]
I believe we can close this, since we don't build windows anymore and the platform is already based on opam names.
