### ISSUE TITLE
Admitted subgoals are described as unfocused subgoals

### ISSUE THREAD

**Issue by Nils-Lauermann** [coq/coq#13475]
#### Description of the problem

Admitting a subgoal and then closing all other subgoals will lead to the message:

> There are unfocused goals.

I found this rather confusing as I tried to focus these goals but wasn't able to.

See for example:
```
Lemma add_zero x:
    x + 0 = x.
Proof.
    induction x.
    - admit.
    - cbn. auto.
```

#### Coq Version

The Coq Proof Assistant, version 8.12.0 (October 2020)
compiled on Oct 9 2020 14:54:23 with OCaml 4.09.1

**Comment by Zimmi48** [comment]
Hum, are you really observing this behavior with Coq 8.12.0?? I just tested this code with that version and I get:

```
No more subgoals, but there are some goals you gave up:

0 + 0 = 0

You need to go back and solve them.
```

**Comment by fakusb** [comment]
It seems to be a vscoq bug.

**Comment by Zimmi48** [comment]
OK, please report here then: https://github.com/coq-community/vscoq/issues/
