### ISSUE TITLE
`replace` tactic subgoal reversed

### ISSUE THREAD

**Issue by vedgar** [coq/coq#13480]
#### Description of the problem

    Parameter a b: nat.
    Goal a = 1.
    replace a with b.

Second subgoal is then `b = a` instead of `a = b`.

The documentation says: `replace term with term’` replaces all free occurrences of `term` in the current goal with `term’` and generates an equality `term = term’` as a subgoal. So, not only this is inconvenient and nonintuitive, it is contrary to the documentation.

#### Coq Version

8.12.0 on Windows

**Comment by gares** [comment]
I add that replacing "cutrewrite" with "replace" as suggested in the doc of the upcoming 8.13 generates instances of this problem, eg the overlay for gappa I wrote yesterday https://gitlab.inria.fr/gappa/coq/-/merge_requests/1/diffs contains extra calls to `symmetry`. CC @Zimmi48

**Comment by vedgar** [comment]
Ah, so cutrewrite doesn't have that problem. Which is nice, but a) it's deprecated, b) it doesn't allow "by" preposition. I (and a lot of my students) would really like to say `replace A with B by apply L`, where L is a lemma saying A=B.

**Comment by Zimmi48** [comment]
We can open a PR changing the behavior of `replace` to see what it gives (since our CI builds many external projects). There is a high chance that it will break a number of projects, but we can still do the change and guard it by a compatibility flag. Then the decision becomes whether to turn the flag on or off by default.

As for the question of `cutrewrite`, it seems that we might have removed it too soon then. It's still time to revert the change in 8.13 to avoid having many users switching to `replace` only to get the behavior of `replace` changed in the next release.

**Comment by Zimmi48** [comment]
Test running at #13485.

**Comment by gares** [comment]
It's an extinction level catastrophe ;-)

**Comment by Zimmi48** [comment]
Well, actually we don't know since the stdlib doesn't build. Let me try to fix this and we'll see.

**Comment by ppedrot** [comment]
> Let me try to fix this and we'll see.

Good luck with that.

```
pm@ouranos:~/sources/coq$ git grep "\breplace\b" -- '*.v' | wc -l
1912
```

**Comment by gares** [comment]
(that is the rocket to mars ;-)

**Comment by gares** [comment]
If we want to do one thing for 8.13, is to signal that cutrewrite has to be replaced by replace+symmetry.

**Comment by Zimmi48** [comment]
Well, this patch does change the semantics as discussed on simple cases like the one in the OP, but it also breaks completely the behavior of `replace` in other cases. I'm not expert enough in these things to continue:

```diff
diff --git a/tactics/equality.ml b/tactics/equality.ml
index 486575d229..863aca2e43 100644
--- a/tactics/equality.ml
+++ b/tactics/equality.ml
@@ -684,7 +684,7 @@ let replace_by c1 c2 tac =
   replace_using_leibniz onConcl c2 c1 false false (Some tac)
 
 let replace_in_clause_maybe_by c1 c2 cl tac_opt =
-  replace_using_leibniz cl c2 c1 false false tac_opt
+  replace_using_leibniz cl c1 c2 true false tac_opt
 
 (* End of Eduardo's code. The rest of this file could be improved
    using the functions match_with_equation, etc that I defined
```

**Comment by Zimmi48** [comment]
> If we want to do one thing for 8.13, is to signal that cutrewrite has to be replaced by replace+symmetry.

`cutrewrite` was deprecated in 8.12 with a suggested replacement to use `replace` instead. In 8.13, it has been removed. Thus, it's going to be harder to suggest replacing it by `replace`+`symmetry`. I strongly think that we should revert the removal in `v8.13` and fix the deprecation message there so that it is more accurate.

As for the behavior of `replace`, if we can't change it, we'll have to fix the doc.

**Comment by SkySkimmer** [comment]
Ths patch does `replace c1 with c2 := old_replace c2 with c1` which is just swapping the order of arguments for the caller. You want to swap the order of the equality goal it generates.

**Comment by vedgar** [comment]
Would it be possible to have "replace <-" with semantics I proposed? Same as with rewrite, default would be -> with the current behaviour. I really think the "<-" semantics is more natural and it would be a pity not to have it.

**Comment by Zimmi48** [comment]
> Ths patch does `replace c1 with c2 := old_replace c2 with c1` which is just swapping the order of arguments for the caller. You want to swap the order of the equality goal it generates.

Despite the `l2r` argument flipped to `true`? Why does it work on the simple example in the OP?

**Comment by Zimmi48** [comment]
> Would it be possible to have "replace <-" with semantics I proposed? Same as with rewrite, default would be -> with the current behaviour. I really think the "<-" semantics is more natural and it would be a pity not to have it.

Yes, except I would call it `->` since it really is about left-to-right rewriting.

**Comment by silene** [comment]
By the way, rather than `replace + symmetry` (which is a non-local modification), a better replacement for `cutrewrite` is `cut + intros ->` (which is purely local). And in an ideal world, the replacement should have been `cut as ->`, which for some reason is not supported by Coq.

**Comment by Zimmi48** [comment]
Until not long ago, the recommended replacement was `enough x = y as ->`. This was changed following a discussion on Coq-Club because `replace`, contrary to this solution based on `enough`, supports the `in` clause. See https://github.com/coq/coq/pull/12841 and e-mail "cutrewrite" from July 18th, 2020 on Coq-Club. Anyway, I reiterate that the removal of `cutrewrite` can still (and probably should) be reverted in 8.13.

**Comment by gares** [comment]
Would you mind making a PR with the revert on master?

**Comment by Zimmi48** [comment]
OK

**Comment by Zimmi48** [comment]
Done. To fully resolve this issue, I suggest adding support (in 8.14) for `{| -> | <- |}` to `replace` and recommending `replace ->` as a replacement for `cutrewrite ->`. That way, we should be able to remove `cutrewrite` in 8.15.

WDYT @herbelin? (you were the one to deprecate the tactic in the first place)

**Comment by herbelin** [comment]
> Done. To fully resolve this issue, I suggest adding support (in 8.14) for `{| -> | <- |}` to `replace` and recommending `replace ->` as a replacement for `cutrewrite ->`. That way, we should be able to remove `cutrewrite` in 8.15.

That's a good idea.

**Comment by silene** [comment]
> I suggest adding support (in 8.14) for `{| -> | <- |}` to `replace`

So, the default for `rewrite` is `->`, but the default for `replace` is `<-`. Argl...

**Comment by vedgar** [comment]
Well, that's exactly why I wanted the default to be ->, but people who know more about user interface of Coq seemed to have different ideas. :-)

**Comment by herbelin** [comment]
> different ideas

Different ideas, or, maybe just constrained by compatibility!

This being said, it would be easy to provide an automatic translation. It is more that many users like to have developments which compile in different versions of Coq. This makes changes such as swapping the equality in `replace` difficult to put in place.

**Comment by vedgar** [comment]
Ah, now I see that the discussion is not about which behavior should be the default, but which arrow direction it should be symbolized by. To be clear, I understand that we'll probably need to keep the current behavior for compatibility, and new one will require an explicit arrow. Which arrow it will be, <- or ->, doesn't matter much to me.

Thanks for clarification!

**Comment by gares** [comment]
For this specific kind of transition, the "old flags" may work. I mean, a Set Replace Legacy Direction thing. We did it for SSR rewrite goal order, and new code is clean. Old code is ported with no pressure, it's just a line of code, no hurry to remove it from Coq.

**Comment by Zimmi48** [comment]
Yeah, I agree. First provide the `-> | <-` syntax and a flag to change the default, then change the default value of this flag, and then (possibly much later) deprecate the flag and eventually remove it.

**Comment by vedgar** [comment]
As far as I can see, replace is still not an adequate replacement for cutrewrite (though the warning I get seems to imply otherwise). The arrows were added, but only in the form which has nothing to do with replacing the current invokations of cutrewrite (at least it seems so to me).

Can I ask you to reconsider adding the -> flag to the "replace with" tactic form too? "replace -> A with B by apply L" reads much nicer than "replace A with B by (symmetry; apply L)".

**Comment by Zimmi48** [comment]
@vedgar Nothing has changed since our last interaction in this issue except that the documentation has been fixed to reflect the current behavior and extended to document the `replace -> | <-` form without `with` which already existed.
