### ISSUE TITLE
Set Mangle Names vs. compare tactic: variable diseq unbound anomaly

### ISSUE THREAD

**Issue by jonleivent** [coq/coq#13493]
In 8.12,
```Coq
Set Mangle Names.

Goal forall (m n:nat), True.
  intros m n. compare m n.
```
produces:
`Error: Anomaly "variable diseq unbound." Please report at http://coq.inria.fr/bugs/.`

**Comment by jonleivent** [comment]
As usual, when `Set Mangle Names` finds a bug, it's with static naming - in this case: `diseq`.  Hence the following, without `Set Mangle Names`:
```Coq
Goal forall (n m:nat), True.
  intros m n. pose proof I as diseq. compare m n.
```
Fails with: `Unable to unify "True" with "False".`

**Comment by jashug** [comment]
This seems to be fixed in master, with the small issue of an extra goal `(nat -> forall _1 : nat, {_1 = _1} + {_1 <> _1}) ->
{m = n} + {m <> n}` left over. I'm working on a fix now.
