### ISSUE TITLE
Set Mangle Names can attempt to reuse mangled name

### ISSUE THREAD

**Issue by jonleivent** [coq/coq#13499]
In 8.12,
```Coq

Set Mangle Names.

Goal forall (l:list nat), True.
  intro l. induction l as [|[] l].
```
fails with: `Error: _0 is already used.`  The error disappears if more identifiers are used in the intro pattern for `induction`.  For instance:
```Coq
Set Mangle Names.

Goal forall (l:list nat), True.
  intro l. induction l as [|[] l IHl].
```
works.

**Comment by jashug** [comment]
This doesn't seem to be a problem in master: succeeds with three goals `True`, `list nat -> True -> True` and `nat -> list nat -> True -> True` (or rather, roughly the result of `intros` on goals of those types).
