### ISSUE TITLE
Failure of subject reduction due to incompleteness in the type-checker

### ISSUE THREAD

**Issue by mattam82** [coq/coq#13495]
#### Description of the problem

The type-checker is incomplete in presence of cumulative inductive types, 
as realized while formalizing the completeness proof of PCUIC in MetaCoq 
(problem found by @MevenBertrand).

```
Universe u.
(* Constraint Set < u. *)
Polymorphic Cumulative Record pack@{u} := Pack { pack_type : Type@{u} }.
(* u is covariant *)

Polymorphic Definition pack_id@{u} (p : pack@{u}) : pack@{u} := 
  match p with
  | Pack T => Pack T
  end.
Definition packid_nat (p : pack@{Set}) := pack_id@{u} p.
(* No constraints: Set <= u *)

Fail Definition sr_breaks := Eval compute in packid_nat.
(* Incorrect elimination of "p" in the inductive type "pack":
  ill-formed elimination predicate. 
  
  This is because it tries to enforce Set = u
  *)
```

#### Coq Version

Coq 8.11, but all other versions with cumulative inductives are affected.
The problem lies in typeops.ml and inductive.ml#is_correct_arity. The arity of the predicate is checked to be correct using conversion while cumulativity is needed. A similar problem happens for branches.

**Comment by mattam82** [comment]
I'm working on a fix

**Comment by ppedrot** [comment]
All hail to MetaCoq, then. Is that the first serious bug found this way?

**Comment by mattam82** [comment]
It's the second, if you consider the completeness issue in #13465 !

**Comment by SkySkimmer** [comment]
This isn't inconsistency, failure of SR doesn't lead to proof of False
