### ISSUE TITLE
Errors and Warning Index in doc entries are not wrapped; jumping to an entry it becomes unreadable

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13504]
First noted here: https://github.com/coq/coq/pull/13482#discussion_r531186876

The error message index is a bit of a mess.
1. The entries are not wrapped (though you can jump to the text in the body to see the full text) and 
2. If you click on "n" at the top, the index becomes unreadable (no left/right scrollbar, so there's no way to scroll left).

![image](https://user-images.githubusercontent.com/1253341/100383956-caaef280-2fd3-11eb-9f54-284df5827fc6.png)

![image](https://user-images.githubusercontent.com/1253341/100384067-1eb9d700-2fd4-11eb-8956-c2c854272e55.png)

**Comment by Zimmi48** [comment]
cc @cpitclaudel in case that's an easy fix

**Comment by cpitclaudel** [comment]
```css
.indextable code {
    white-space: inherit;
}
```

this should be enough; potentially with a hanging indent to distinguish continuation lines (https://stackoverflow.com/questions/17158253/indent-starting-from-the-second-line-of-a-paragraph-with-css)

**Comment by cpitclaudel** [comment]
Btw this entry looks suspicious: ``Cannot find any non-recursive equality over :n:`‘ident’` ``

**Comment by jfehrle** [comment]
That will be fixed in #13470.

**Comment by jfehrle** [comment]
The `inherit` works, but it appears that `<code>` ignores `text-indent` so the indent on the 2nd, ... line doesn't.  It works if I edit the html and add `<div>` inside `<code>` and apply the setting to the `<div>`.  Do you have an idea hard it would be to get Sphinx to include an additional `<div>`?

This is the best I can do for indenting without the `<div>`.  Not so great.

![image](https://user-images.githubusercontent.com/1253341/100527517-07234f80-3188-11eb-88c7-af8d7672ca2c.png)

**Comment by cpitclaudel** [comment]
> The inherit works, but it appears that <code> ignores text-indent so the indent on the 2nd, ... line doesn't work.

`text-indent` controls just the first line indent, so what you're describing seems expected.  What looks do you want to achieve?

> This is the best I can do for indenting without the <div>. Not so great.

I suggested text-indent to get precisely that look, so that it's clear what is a continuation line and what isn't; if you tell me what look you would like I can help with the CSS.

**Comment by jfehrle** [comment]
First line at the left margin, following lines invented.

**Comment by Zimmi48** [comment]
> I suggested text-indent to get something like that, actually, to make it clear what is a continuation line and what isn't; if you tell me what look you would like I can help with the CSS.

I also like it that way (clearer that some error message is wrapped).

**Comment by cpitclaudel** [comment]
> First line at the left margin, following lines invented.

Use a positive padding and a negative text-indent (see the demo in the link I posted earlier)

**Comment by jfehrle** [comment]
That doesn't work, at least in Firefox. I probably need a `<div>`.

```
/* make the error message index readable */
.indextable code {
    white-space: inherit;  /* break long lines */
    padding-left: 2em; /* need both of these on a <div>, not <code> */
    text-indent: -2em;
}

/*
code {
    padding: 0 !important;      /* This padding doesn't make sense without a border * /
}
*/

```

![image](https://user-images.githubusercontent.com/1253341/100553268-c720a300-3241-11eb-952a-5bcf3f390def.png)

**Comment by jfehrle** [comment]
Chrome looks the same.

**Comment by Zimmi48** [comment]
If we can't fix it the way you'd like to see it, let's fix it the way Clément proposed.

**Comment by jfehrle** [comment]
I was waiting to see if @cpitclaudel had further comments.  If he can suggest a reasonable potential solution I will investigate it.  If it's too difficult, I'll go with the alternative.  The alternative is unattractive and not the usual format used in indexes, but it would be an improvement.

**Comment by cpitclaudel** [comment]
Sorry, missed your previous message:

```
.indextable code {
    white-space: inherit;
}

.indextable tr td + td {
    padding-left: 2em;
    text-indent: -2em;
}
```

Does this work?

**Comment by jfehrle** [comment]
That works, thanks!

An unrelated question: I wanted to have separate tactic index entries for `rewrite` and `rewrite *`, however it appears the indexing-generated linkname drops the `*` (since it's invalid in a linkname) and the `rewrite *` entry doesn't appear in the index.  `rewrite * x` will appear, though.  Can we control this, perhaps through syntax such as `:name: rewrite * <rewrite-star>`?

Here's an example of the invalid character deletion:

```
<a href="language/extensions/implicit-arguments.html#coq:exn.argument-name-is-a-trailing-implicit-so-it-can-t-be-
declared-non-maximal-please-use-instead-of">
<code class="xref">Argument ‘name’ is a trailing implicit, so it can&
#39;t be declared non maximal. Please use { } instead of [ ]</code></a>
```

**Comment by cpitclaudel** [comment]
>  Can we control this,

Yes, it should be possible.  But first we should generate a warning for this case: collisions that lead to missing index entries are not great.

**Comment by jfehrle** [comment]
Sure, but I can't find the code that maps the name to the tagname.  I don't see it in `coqdomain.py`.  And I don't know how I would pass an alternate tagname, either.

The link for the first `tacn` below ends with `#coq:tacn.rewrite`.  The full link is `http://localhost:63342/coq2/doc/sphinx/_build/html/proofs/writing-proofs/rewriting.html#coq:tacn.rewrite`
The second `tacn` ends with `#id1`.  The link is `http://localhost:63342/coq2/doc/sphinx/_build/html/proofs/writing-proofs/rewriting.html#id1`

```
.. tacn:: rewrite @term
   :name: rewrite

.. tacn:: rewrite *
   :name: rewrite *
```

**Comment by cpitclaudel** [comment]
> Sure, but I can't find the code that maps the name to the tagname. I don't see it in coqdomain.py. And I don't know how I would pass an alternate tagname, either.

I expect the tag name is what sphinx calls the "anchor", which we give to it in CoqSubdomainIndex.  We generate these anchors in two places AFAICT: 

```
    def _target_id(self, name):
        return 'grammar-token-{}'.format(nodes.make_id(name[1]))
```

and

````
    def _target_id(self, name):
        return make_target(self.objtype, nodes.make_id(name))
```

We can certainly make this marter to allow `rewrite * <rewrite-star>`.  But isn't it simpler to just change the name in this tacn to `rewrite-star`?

**Comment by jfehrle** [comment]
The index should should list `rewrite *`, not `rewrite-star`.  The latter would be a little confusing.

Ideally the `make_id` mapping would be invertible.  I could map unacceptable characters to, say, their octal values.  That's not quite invertible, but I expect would be good enough for our purposes.  That's simpler than adding syntax to `:name:` and adding an additional field to the data structure.  I think I'll try that.

**Comment by cpitclaudel** [comment]
Sorry, I forgot that :name: is used for index entries as well as links.

**Comment by jfehrle** [comment]
Ah, the fix is sooo simple: just `quote` to use HTML '%' escapes instead of `nodes.make_id`.  That makes it invertible.

**Comment by cpitclaudel** [comment]
I'm not sure that works: I don't think % is allowed in CSS identifiers.

**Comment by jfehrle** [comment]
Where would that be an issue?  It works in the index:

![image](https://user-images.githubusercontent.com/1253341/101085905-f5192680-3564-11eb-9567-66529516638f.png)

**Comment by jfehrle** [comment]
There's no need for our CSS to refer to a specific link anchor.
