### ISSUE TITLE
Is "Print <ltac tactic name>" useful in the long term?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13516]
The `Print` command lets you display tactics, for example.  This command seems most appropriate for a command-line interface such as `coqtop`, which is more a vestige for developer convenience rather than a primary user interface.  In a GUI, the more typical approach would be to jump to the definition in one of the editor windows.   (Usually there would be a "return to previous location" function, too).  This would also make comments adjacent to the definition visible to the user.

If and when CoqIDE and other important GUIs support jumping to the definition, would it still be worthwhile keeping this `Print` command?  Would removing it significantly simplify our code?

**Comment by herbelin** [comment]
Even when UI will be able to point directly to the source of a definition in a file, we can imagine that `Print Ltac` may still provide a rich (with colors, hyperlinks, ...) and/or formatted output. The code for printing tactics is also useful for debugging (e.g. in `Ltac Debug`) and the code for printing tactics used by `Print Ltac` is somehow a particular case.

**Comment by Zimmi48** [comment]
I tend to agree that the general `Print` command use case would be better served by a jump-to-definition IDE support (contrary to the `About` command which also adds information that can come from later `Arguments` command). However, most of the time, you want to print a definition from outside your own project (e.g., the standard library). Thus, jumping to a definition would require source files to be installed. It isn't the case today, is it?

**Comment by jfehrle** [comment]
> Thus, jumping to a definition would require source files to be installed. It isn't the case today, is it?

We could include the standard library source in the Coq distribution.  The .v files tend to be smaller than the .vo files.  Other packages could do the same.  Or the GUI could let the user configure the location of the source (maybe even github??) or give an error message.

**Comment by ppedrot** [comment]
> Print command use case would be better served by a jump-to-definition IDE

I cannot disagree more: printing a tactic is much more powerful than just reading its definition. First, because the interpretation of a tactic is context-dependent, so that you never know what it's using without fully grasping what's around. Second, printing of tactics (and terms for that matter) is subject to various options that can change the output and make specific info explicit.

**Comment by Zimmi48** [comment]
>Second, printing of tactics (and terms for that matter) is subject to various options that can change the output and make specific info explicit.

Right!
