### ISSUE TITLE
"Co-authored-by:" in commits problem (coqbot bug?)

### ISSUE THREAD

**Issue by mattam82** [coq/coq#13524]
#### Description of the problem

I noticed in the git history a few commits have Co-authored-by fields of the following form:
```
commit 50af46a596af607493ce46da782389e8a82e8354
Author: Emilio Jesús Gallego Arias <e@x80.org>
Date:   Wed Nov 18 23:25:17 2020 +0100

    [attributes] [doc] Documentation review by Théo.
    
    Co-authored-by: <Théo Zimmermann <theo.zimmermann@inria.fr>
```
Notice the `<` before Théo. This messes up `git-shortlog --group=trailer:Co-authored-by` for example. 
I'm not sure where this comes from though.

#### Coq Version

N/A

**Comment by herbelin** [comment]
In my case, I sometimes edit such fields (e.g. when they occur several times), so I may be responsible for such "human" mistakes if any, sorry.

**Comment by Zimmi48** [comment]
Given that the commit log only contains three occurrences of this issue and on three commits by @ejgallego, I would think this is a human mistake. Probably nothing to do then and the issue can be closed, unless you want us to introduce a linter check for this.

**Comment by mattam82** [comment]
No that's fine, as long as it could not be traced to a software bug.
