### ISSUE TITLE
coqc: -Q: no such file or directory; coqc thinks arguments are files/dirs

### ISSUE THREAD

**Issue by wonhyukchoi** [coq/coq#13555]
#### Description of the problem

When I try to compile files with coqc -Q . LF, I get the error:

```sh
$ coqc -Q . LF
coqc: -Q: no such file or directory
```

Likewise, the same occurs for something like 
```sh
$ coqc --print-version
coqc: --print-version: no such file or directory
```

#### Coq Version

Result of `coqtop -v`:

```
The Coq Proof Assistant, version 8.4pl6 (December 2020)
compiled on Dec 02 2020 23:06:36 with OCaml 4.02.0
```
I have to use `8.4.6` for legacy reasons.

Using Linux Mint 19.2 (Ubuntu 18.04) if that makes a difference.

**Comment by herbelin** [comment]
Hi @wonhyukchoi, option `-Q` is not available in Coq version 8.4.6. You can replace it with option `-R` which will probably roughly work the same for your purpose. Similarly, option `--print-version` is not available in Coq 8.4.6. Look instead at the header printed when running `coqtop`. Best regards.

**Comment by ppedrot** [comment]
@wonhyukchoi FTR, Coq 8.4 is a very, very old release, that came before the major 8.5 reworking. I don't know what you are trying to compile, but expect trouble ahead.

**Comment by Zimmi48** [comment]
@wonhyukchoi Feel free to ask support on our various channels. The best use of your time would probably be to port this legacy project you are working on to a more recent version. The best way to achieve this is probably to use some intermediary steps, like 8.6 with option `-compat 8.4`, then `-compat 8.5`, then no compat option, then 8.8 with option `-compat 8.6`, and so on.

However, the issue tracker is more about tracking issues with the current version(s) of Coq.
