### ISSUE TITLE
Add opt-in warning for implicit global "Instance"

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#13562]
#### Description of the problem

Recently, Coq master was equipped with a deprecation warning for a `Hint` that is implicitly global. @tchajed found a nice way to use that to add an explicit `Global` everywhere automatically; then the remaining `Hint` could be equipped with `Local`. We'd like to use the same approach for `Instance`. So would it be possible to get a warning (it can be off-by-default) for when an `Instance` is implicitly `Global`?

(I could also imagine this being useful for other things, such as `Notation`.)

**Comment by Zimmi48** [comment]
See also https://coq.discourse.group/t/change-of-default-locality-for-hint-commands-in-coq-8-13/1140/8

And the complaints of @charguer in #13532.

If you have a nicer way than the script shared by @ppedrot, feel free to share it with others :smiley:

**Comment by Zimmi48** [comment]
Unfortunately though, the `export` attribute is not yet supported by `Instance`. `Notation` is less of an issue since it is only used when the corresponding module is imported.

**Comment by RalfJung** [comment]
[Here is the script](https://gitlab.mpi-sws.org/iris/iris/-/merge_requests/594#note_60292) that Tej used.

> Unfortunately though, the export attribute is not yet supported by Instance

As far as I am concerned, that is entirely orthogonal. Even without `Export` existing, an unqualified `Instance` is bad because to figure out how "global" the instance is, you need to scroll all the way up through the file to determine if this is inside a `Section` or not. I'd prefer to avoid such non-local reasoning. That's why I'd like `Global Instance` to be explicit.

> Notation is less of an issue since it is only used when the corresponding module is imported.

It is an issue though because `Notation` inside a section disappear when the section ends; only `Notation` outside a section are available on import of the current module. So again, reviewing some PR it can be really hard to see if some notation is local or global.

**Comment by charguer** [comment]
One thing I don't like with the `Global` qualifier is that it hard codes for-ever the two-level hierarchy: there is a module (generally a file) that contain sections. And that's it. Are we sure that we'll never need, for larger development, a more general notion of scopes, allowing sections to be nested? In that case, what does  `Global` mean?

One could imagine attaching explicit scopes, in a similar way as in javascript you can exit several loops using `break mylabel`. But I think that would no go in the right long-term direction.

I instead argue for a view where hints are hooked to databases of hints (and more generally, databases of stuff such as coercions, notations, etc.), and it's the user responsibility to load explicitly the databases (this doesn't have to be heavy, if a proper mechanism for giving names to union of databases is available). With this approach, hints are never "exported" by modules, only databases are made available by modules and users may choose to import them. I think this approach would scale up much better and avoid creating unnecessary dependencies on hints that make adding/removing hints in libraries very problematic w.r.t. backward compatibility.

Concretely, when creating a hint, the only thing what matters would be to which databases it is hooked to. For every module and every section, two databases would be created by default: one for hints that are meant to be used inside that scope only, and one for hints that are meant to be used from outside. 

In particular, this approach allows one section to reload the same hints as another previous section (very useful in practice). It allows allows a section to declare a hint that is meant to be available throughout the rest of the file, but that should not be exported beyond the file. And it allows, from within a section, to register hints as being available from outside of the module.

**Comment by ppedrot** [comment]
@RalfJung I agree that the locality of a command depending on its section status is a pain in the neck. Not only for reviewing, it also makes hard to move code around. Unfortunately it'd be really non-backward compatible to change this behaviour...

**Comment by RalfJung** [comment]
@charguer That sounds like a great long-term plan that could be used to remove the implicit side-effects of Require`/`Import`, which would be quite amazing! Ideally this would lead to `Require`/`Import` having no side-effects at all except for making names available; I am not sure if this is possible with things like grammar extensions, but in principle it should be. (I assume by "database" you don't mean the existing "hint database" but something orthogonal to that.) However, this issue is about some much smaller steps that we can take without redoing the entire handling of imperative state in Coq.

@ppedrot It is also really backwards-incompatible to change the default outside sections from `Global` to `Extern`, and yet that seems to be the plan.

**Comment by Zimmi48** [comment]
> It is also really backwards-incompatible to change the default outside sections from `Global` to `Extern`, and yet that seems to be the plan.

It's `#[ export ]`. But indeed, since the plan is anyway to change the default locality outside section, we could decide to change it to `local` instead of changing it to `export`. Then, hint locality would always be local by default whether you are inside or outside a section. And library authors could select with attributes which hints to export outside the current module (preferably with `export` rather than with `global`).

Anyway, this question can be deferred to later (the actual time when the default is changed).

Regarding the warning for `Instance` without a locality attribute, I bet it shouldn't be too hard to proceed with the same plan as was done for most `Hint` commands in 8.13 and `Hint Rewrite` in 8.14. Since the discussion in #13394 goes toward postponing the next steps in the deprecation process because of `Hint Rewrite`, it would be nice to also take advantage of 8.14 to do the same for `Instance`. WDYT @SkySkimmer @ppedrot? Would that be doable in this time frame? I'm tentatively putting the 8.14 milestone on this issue.

**Comment by ppedrot** [comment]
I started implementing it for Instance and ended up doing yak shaving to try to get rid of the horrible belly dance we perform to handle non-local instances in sections. I'll have a try again with a more straightforward fix.

**Comment by SkySkimmer** [comment]
@ppedrot any news?

**Comment by ppedrot** [comment]
Nope, but I can force myself to write a quick and dirty patch before the 8.14 release.
