### ISSUE TITLE
change tactic: why is there `at @occs_nums` in both @conversion and @occurrences?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13567]
Perhaps the one in @conversion should be dropped?  Also applies to `change_no_check`.  Those are the only 2 tactics using @conversion.  Ltac2's version of @conversion omits this clause.

![image](https://user-images.githubusercontent.com/1253341/101122047-6deca280-35a6-11eb-92a9-4d813ae578dd.png)

![image](https://user-images.githubusercontent.com/1253341/101122096-852b9000-35a6-11eb-8d3a-d36d43770dce.png)

**Comment by JasonGross** [comment]
It looks like dropping the conversion one would prevent `change (1 + 1) at 1 with 2 in H`?

**Comment by jfehrle** [comment]
How would that be (or should that be) different from `change (1+1) with 2 in H at 1`?  @occurrences is used in 21 tactics and is more flexible than @conversion.

![image](https://user-images.githubusercontent.com/1253341/101136330-047a8d00-35c2-11eb-81a3-a75f0489b391.png)

**Comment by Zimmi48** [comment]
You should probably put backticks around `@conversion` and `@occurrences` to avoid pinging random GitHub users.

> How would that be (or should that be) different from `change (1+1) with 2 in H at 1`?

From my testing, it looks like they are exactly the same.

**Comment by jfehrle** [comment]
You think it's worth the trouble to change?  I see 2 uses in the standard library, 10 if tests are included.

**Comment by JasonGross** [comment]
On a tangentially related note, I always find it confusing whether I have to write `in H at 1` or `at 1 in H`.  I think furthermore that done tactics support both orders while other tactics support only one order.  (Perhaps `rewrite` supports both?). I think it would be better for order to not matter, and for the nesting to be allowed in both directions.

**Comment by jfehrle** [comment]
> I always find it confusing whether I have to write `in H at 1` or `at 1 in H`.

I think that's because the grammar for `change` is inconsistent with the other uses of `@occurrences`--that makes it harder to learn what is accepted where.  And we use `in` for multiple purposes.

Some tactics that accept some of their parameters in any order, but they're done by coding multiple parser productions.  It's awkward and I think error prone.  For example `rewrite *`.  `TACTIC EXTEND` is not as flexible as `GRAMMAR EXTEND`, which would permit combining the last 4 productions by making the keyword clauses optional.  But you still need at least 2 productions and the `by_arg_tac` has to be at the end.

In `GRAMMAR EXTEND`, you can define a general pattern such as `LIST0 [ "at" ... | "in" ... | "by" ... ]` with code to handle the case where a parameter is given twice, but applying that pattern everywhere and consistently would be a lot of work.  And there are reasons that this is a `TACTIC EXTEND`.  I don't think it's important to address now, if ever.


```
TACTIC EXTEND rewrite_star
| [ "rewrite" "*" orient(o) uconstr(c) "in" hyp(id) "at" occurrences(occ) by_arg_tac(tac) ] ->
    { rewrite_star ist (Some id) o (occurrences_of occ) c tac }
| [ "rewrite" "*" orient(o) uconstr(c) "at" occurrences(occ) "in" hyp(id) by_arg_tac(tac) ] ->
    { rewrite_star ist (Some id) o (occurrences_of occ) c tac }
| [ "rewrite" "*" orient(o) uconstr(c) "in" hyp(id) by_arg_tac(tac) ] ->
    { rewrite_star ist (Some id) o Locus.AllOccurrences c tac }
| [ "rewrite" "*" orient(o) uconstr(c) "at" occurrences(occ) by_arg_tac(tac) ] ->
    { rewrite_star ist None o (occurrences_of occ) c tac }
| [ "rewrite" "*" orient(o) uconstr(c) by_arg_tac(tac) ] ->
    { rewrite_star ist None o Locus.AllOccurrences c tac }
    END
```

**Comment by Zimmi48** [comment]
Should we try to deprecate the `at @occs_nums` form in `@conversion` then?
