### ISSUE TITLE
hnf on primitives raises an anomaly

### ISSUE THREAD

**Issue by mattam82** [coq/coq#13579]
#### Description of the problem

```
From Coq Require Import PrimFloat.
Definition f := of_int63 1.
Eval hnf in f.
```
raises
```
Anomaly "Uncaught exception Environ.NotEvaluableConst(_)."
```
with backtrace:
```
...
frame @ file "vernac/prettyp.ml", line 719, characters 13-34
frame @ file "vernac/vernacentries.ml", line 1604, characters 23-39
frame @ file "tactics/redexpr.ml", line 205, characters 29-40
frame @ file "pretyping/tacred.ml", line 980, characters 19-29
frame @ file "pretyping/tacred.ml", line 963, characters 10-53
frame @ file "pretyping/tacred.ml", line 563, characters 30-61
raise @ file "kernel/environ.ml", line 534, characters 21-62
```

`lazy`, `cbv`, etc do not seem to have the problem.

#### Coq Version

Tested in 8.11 and current master

**Comment by herbelin** [comment]
Do we need to ping someone in particular (@maximedenes or @proux01 have probably something to say)?

**Comment by proux01** [comment]
Arg, this strikes again. Thanks for pinging me, I'll have a look.

**Comment by proux01** [comment]
@mattam82 what is the expected result of `hnf` on primitive values: reduction like `lazy`, `cbv`,... or no reduction like `simpl`?

**Comment by mattam82** [comment]
I would think the head normal form of a primitive integer should be a primitive integer literal or an operators that is stuck, like for an inductive natural number. But maybe there's a reason simpl does not reduce them (at all?)

**Comment by silene** [comment]
Note that the issue does not even come from primitive values. It comes from registered operations, since even the following fails: `Eval hnf in Int63.add.`
