### ISSUE TITLE
Print Assumptions for vok

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#13589]
#### Description of the problem

The documentation of `vok` compilation makes it seem that if regular (`vo`) compilation succeeds, then so also does a `vos` + `vok` compilation.
However, `vok` produces an error on `Print Assumptions` when multiple files are involved.
As a result, `vok` is not useful in presence of such.

Suggestion: `vok` could produce a warning, that `Print Assumptions` is not useful, but otherwise do its job.

#### Example

`file1.v`:
```
Lemma hidden : False.
Proof. Admitted.

Lemma aux : False.
Proof. apply hidden. Qed.
```
`file2.v`:
```
Require file1.

Lemma main : False.
Proof. apply file1.aux. Qed.

Print Assumptions main. (* this fails *)
```
Commands:
```
 coqc -vos .\file1.v
 coqc -vos .\file2.v
 coqc -vok .\file2.v
```
Result:
```
File ".\file2.v", line 6, characters 0-23:
Error: Cannot access opaque delayed proof
```

#### Coq Version

The Coq Proof Assistant, version 8.12.1 (December 2020)
compiled on Dec 6 2020 13:40:33 with OCaml 4.07.1

**Comment by herbelin** [comment]
Hi @mrhaandi, did you discuss about this already on Zulip? I don't know who would be most expert to answer, maybe @gares, @charguer or @silene?

**Comment by mrhaandi** [comment]
> did you discuss about this already on Zulip?

This issue is currently not associated with any Zulip discussion.
My motivation is that `vok` verification is integrated into the CI of [coq-library-undecidability](https://github.com/uds-psl/coq-library-undecidability). This makes it impossible to have meaningful use of `Print Assumptions` in the library, e.g. verifying that some proof is constructive.

**Comment by charguer** [comment]
This print assumption issue has been totally overlooked.
I'll try to investigate how it could be fixed.

Should it issue a warning in vok mode? Eg "print assumptions feature not available when loading Vos files"?

**Comment by Blaisorblade** [comment]
@mrhaandi As a workaround, it's enough to ensure that `Print Assumptions` is not part of the library proper that is used with `make vok`.

For instance, I use `Print Assumptions` in a testcase:
https://github.com/Blaisorblade/dot-iris/blob/master/tests/test_used_axioms.v
https://github.com/Blaisorblade/dot-iris/blob/master/tests/test_used_axioms.ref

together with coq-iris's "unit test framework" for comparing the output of `tests/foo.v` files with `tests/foo.ref`:

https://github.com/Blaisorblade/dot-iris/blob/master/Makefile.coq.local
https://github.com/Blaisorblade/dot-iris/blob/master/test-normalizer.sed

**Comment by charguer** [comment]
@gares I'll leave it up to you to decide if a fix should go into 8.13 or not.

Besides, one thing that was not totally clear to me is why the compilation in -vos mode (which is similar to -vio in numerous ways) does not issue any warning/error on vernac commands. I guess that you somehow turn off "Print" commands for building vio files, but I wasn't sure where this happens in the code, and what exactly are the commands that are ignored. Perhaps we should document this better in the manual for vos compilation. Thanks

**Comment by ppedrot** [comment]
Print Assumption is not the only victim of this semantics, any function accessing the opaque body might fail. That includes extraction, printing and probably some other commands as well. It's not difficult to solve, but the "error" behaviour might make sense sometimes, so it's probably a good idea to govern it with a flag.

**Comment by SkySkimmer** [comment]
>the "error" behaviour might make sense sometimes, so it's probably a good idea to govern it with a flag.

Warnings already support turning into errors

**Comment by charguer** [comment]
@ppedrot your point about other potential accesses to opaque bodies makes total sense. However, I lack the necessary expertise to tell the list of commands that would be subject to this issue. Can you help?  Moreover, what is the desired behavior (silence, warning, errors) for each command would probably need to be discussed in a coqdev meeting.

**Comment by SkySkimmer** [comment]
>Besides, one thing that was not totally clear to me is why the compilation in -vos mode (which is similar to -vio in numerous ways) does not issue any warning/error on vernac commands.

There is special code to skip VtQuery commands which "may pierce opaque" in vio and vos mode: https://github.com/coq/coq/blob/1918f19cb43d6d4313276b167af38316b27879f2/stm/stm.ml#L2670-L2675

BTW the "may pierce opaque" check is some adhoc hack https://github.com/coq/coq/blob/1918f19cb43d6d4313276b167af38316b27879f2/stm/stm.ml#L134-L143
I don't think much attention has been put in keeping it accurate, and it's definitely not capable of dealing with external plugins.

**Comment by gares** [comment]
Indeed. But the idea is that *nothing should pierce opacity*

**Comment by gares** [comment]
My opinion is that `Print Assumptions` should not be in your library, in a .v file you compile.

IMO you should have separate file/snippet doing that, something like:
```make
check:
    echo "Require mylib. Print Assumptions." | coqtop
```

**Comment by charguer** [comment]
So, would it work as a short-term patch to simply add one line to the function `may_pierce_opaque` to add a case for `PrintAssumption` ?

**Comment by ppedrot** [comment]
I think that rather than messing with the STM, we should export a three-case inductive in `Global.body_of_constant` and friends representing no body, delayed body and available body and tweak all callers from here.

**Comment by charguer** [comment]
@ppedrot looks great. But note that contributing to this is totally beyond my expertise level.

**Comment by gares** [comment]
> So, would it work as a short-term patch to simply add one line to the function `may_pierce_opaque` to add a case for `PrintAssumption` ?

I think this is the best solution right now.

**Comment by charguer** [comment]
> There is special code to skip VtQuery commands which "may pierce opaque" in vio and vos mode

This test is on the result of `VCS.is_vio_doc ()`, which is true when building a `.vos`  file, but is false when building a `.vok` file (see `doc_type` in function `compile` from file `toplevel/ccompile.ml`).

Thus, extending the function  `may_pierce_opaque` would be insufficient. Thus, either we need a dedicated function for characterizing toplevel commands that should be ignored during a `.vok` build. Or, we decide that (at least for the time being) this matches exactly `may_pierce_opaque`, and in that case we just need to extend the test `VCS.is_vio_doc ()` with a condition `|| !Flags.load_vos_libraries`.  Would that work?

Btw, I think `may_pierce_opaque` already rules out all 'Print' command, which (in my limited understanding) includes 'Print Assumptions' commands. This would explain why the `.vos` compilation of a file with a 'Print Assumption' executes fine.

**Comment by gares** [comment]
I guess I prefer `VCS.is_vio_doc ()` to be fixed to also say yes when building vos.
I'm sorry I did not spot this discrepancy earlier, but building a .vio or a .vos should really be identical (but for the storing proof tasks part).

**Comment by gares** [comment]
(I'm actually surprised that when we build a .vos the document type is not Vio already)

**Comment by gares** [comment]
Sorry, I misread, you say .vok. I guess the `||` you propose is OK then.

**Comment by charguer** [comment]
@gares I've implemented the proposal. 
(Still remains to add an entry to the changelog, I guess details depend on whether it goes into 8.13 or not.)

@mrhaandi you could try the branch `fix-print-assumptions-wrt-vos` and see if you're able to compile your files using it.
