### ISSUE TITLE
nsatz in characteristic 2

### ISSUE THREAD

**Issue by TJ-Machado** [coq/coq#13594]
Nsatz is appears to be unable to solve relatively straightforward equations for integral domains with characteristic 2.

For instance in the following example we are unable to prove that `x + y == y + x` in **2**.
```
Require Import Nsatz.
Require Import Ring.
Require Import Ncring.

Instance bool_ro : @Ring_ops bool false true xorb
                             andb xorb id (@eq bool).
Defined.

Instance bool_ring : (@Ring _ _ _ _ _ _ _ _ bool_ro).
Proof.
  specialize (BoolTheory) as P.
  destruct P.
  constructor; try solve_proper; auto.
  - repeat constructor.
    + repeat intro; rewrite H; reflexivity.
    + repeat intro; rewrite H, H0; reflexivity.
  - intros; repeat rewrite (Rmul_comm z _); apply Rdistr_l.
Defined.

Instance bool_cri : (Cring (Rr:=bool_ring)).
Proof.
  specialize (BoolTheory) as P.
  destruct P; auto.
Defined.

Instance bool_ID : (Integral_domain (Rcr:=bool_cri)).
Proof.
  constructor.
  - intros; apply andb_false_iff; assumption.
  - intro.
    discriminate.
Defined.

(* The following is not solved by nsatz *)
Lemma foo :
  forall (x y : bool),
    (xorb x y) == (xorb y x).
Proof.
  nsatz.
Abort.
```

My coq version is 8.12.0.

**Comment by andres-erbsen** [comment]
It looks like this might be a reification issue, with `xorb` being interpreted as the subtraction operation (for which the goal is not a consequence of integral domain laws alone).

**Comment by andres-erbsen** [comment]
```coq
Require Import Nsatz.
Require Import Ring.
Require Import Ncring.
Require Import AdmitAxiom.

Definition sub : bool -> bool -> bool. exact xorb. Qed.

Instance bool_ro : @Ring_ops bool false true xorb
                             andb sub id (@eq bool).
Defined.

Instance bool_ring : (@Ring _ _ _ _ _ _ _ _ bool_ro).
Proof.
  specialize (BoolTheory) as P.
  destruct P.
  constructor; try solve_proper; auto.
  - repeat constructor.
    + repeat intro; rewrite H; reflexivity.
    + repeat intro; rewrite H, H0; reflexivity.
  - intros; repeat rewrite (Rmul_comm z _); apply Rdistr_l.
  - case proof_admitted.
Defined.

Instance bool_cri : (Cring (Rr:=bool_ring)).
Proof.
  specialize (BoolTheory) as P.
  destruct P; auto.
Defined.

Instance bool_ID : (Integral_domain (Rcr:=bool_cri)).
Proof.
  constructor.
  - intros; apply andb_false_iff; assumption.
  - intro.
    discriminate.
Defined.

(* The following is not solved by nsatz *)
Lemma foo :
  forall (x y : bool),
    (xorb x y) == (xorb y x).
Proof.
  nsatz.
Qed.

```
I am guessing this hack can be done without admit using `Hint Opaque` or some other mechanism to make subtraction opaque for reification.

**Comment by herbelin** [comment]
Informing @coq/nsatz-maintainers.

PS: despite being part of @coq/nsatz-maintainers, I'm not a specialist of `nsatz` and I'm not sure I would know exactly what should be done so that it works better. @andres-erbsen, if you have a suggestion to make (an `Hint Opaque` in some file?), don't hesitate.

**Comment by ppedrot** [comment]
Can't the `btauto` completeness theorem be used for this kind of specific use cases?

**Comment by thery** [comment]
@andres-erbsen  your diagnostic is right, as `xorb` is both the `+` and the `-` of your ring structure.
The polynomial equality `nsatz` is trying to prove  from your goal is `x - y = y - x` that it fails to 
prove since it does know that the characteristic is 2.
Still it seems there is something weird going on. When trying to build `x + y = y + x` with the term 
`xorb x (xorb 0 y) == xorb y (xorb 0 x)` `nsatz` is still uncapable to conclude while `cring` has no problem. I look into it.

**Comment by thery** [comment]
@andres-erbsen  Ok my mistake, it is just that I was missing the integral domain instance.
`xorb x (xorb 0 y) == xorb y (xorb 0 x)` is proved by nsatz. No problem.
 
Now if you want to prove your initial goal, you have to populate it with witnesses that the characteristic is 2. For example:
 
```
Lemma foo :
  forall (x y : bool), 
      xorb x (xorb 0 x) == 0 -> 
      xorb y (xorb 0 y) == 0 -> 
      xorb x y == xorb y x.
Proof. nsatz. Qed.
```

Hope this helps

**Comment by thery** [comment]
If there is no more question from @TJ-Machado I think we can close this issue
