### ISSUE TITLE
TC search in assumptions: opacity state sensitive to order of databases

### ISSUE THREAD

**Issue by Janno** [coq/coq#13600]
#### Description of the problem

In the proof script below adding the *empty* HintDb `poison` (with `Hint Constants Opaque`) in front of `typeclass_instances` makes the proof search fail because `+` in `3+2` is no longer considered transparent. Changing the order of `poison` and `typeclass_instances` works around this issue.

```coq
Create HintDb poison discriminated.
Hint Constants Opaque : poison.
Goal forall n, n = 3+2 -> n = 5.
  Fail typeclasses eauto with poison typeclass_instances.
  typeclasses eauto with typeclass_instances poison.
```

I am not sure what the right opacity setting should be for assumptions but the fact that the current behavior depends on the order of databases is definitely a bug, I think.

#### Coq Version
8.12.1

**Comment by Zimmi48** [comment]
As far as I recall this is documented and definitely not a bug.

**Comment by Janno** [comment]
Same behaviour with `Create HintDb poison` without `discriminated`.

**Comment by Janno** [comment]
> As far as I recall this is documented and definitely not a bug.

Oh, I didn't manage to find that documentation. I'll have another look.

**Comment by Zimmi48** [comment]
https://coq.inria.fr/refman/addendum/type-classes.html#coq:tacn.typeclasses-eauto

>When considering local hypotheses, we use the transparent state of the first hint database given. Using an empty database (created with Create HintDb for example) with unfoldable variables and constants as the first argument of typeclasses eauto hence makes resolution with the local hypotheses use full conversion during unification.

**Comment by Zimmi48** [comment]
We've also improved the documentation of transparency in the upcoming 8.13 version, see:
https://coq.github.io/doc/master/refman/proofs/automatic-tactics/auto.html#creating-hint-databases

And feel free to give feedback or open PRs if you see things that could be further improved / clarified.

**Comment by Janno** [comment]
I must have grepped for the wrong thing. The documentation is rather explicit here and reading it properly would have saved me a lot of time.. Thanks for pointing me to the right place! I'll read through the new documentation!
