### ISSUE TITLE
coq-doc package fails to install during local opam installation

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#13635]
#### Description of the problem

I'm using the Coq version as of PR https://github.com/coq/coq/pull/13624 (looks like this should be the case for `master` as well), but when I do local opam installation using the following commands

```shell
gh pr checkout 13624
opam install ./
```

I get Coq installed but `coq-doc` fails to do so with this error message:
> Package coq does not exist

Here is the log I see:
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
⊘ removed   coq-mathcomp-algebra.dev
⊘ removed   coq-mathcomp-fingroup.dev
⊘ removed   coq-mathcomp-ssreflect.dev
⊘ removed   coq.dev
∗ installed coq.dev
∗ installed coqide-server.dev
∗ installed coqide.dev
∗ installed coq-mathcomp-ssreflect.dev
[ERROR] The compilation of coq-doc failed at "/Users/anton/.opam/opam-init/hooks/sandbox.sh build dune build -p coq-doc -j 3 @install".
∗ installed coq-mathcomp-fingroup.dev
∗ installed coq-mathcomp-algebra.dev

#=== ERROR while compiling coq-doc.dev ========================================#
# context     2.0.7 | macos/x86_64 | ocaml-base-compiler.4.09.0 | pinned(git+file:///Users/anton/prj/coq/coq#master+fix13581-extraction-letin-in-ind-arity#31a25363)
# path        ~/.opam/coqdev4.09/.opam-switch/build/coq-doc.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p coq-doc -j 3 @install
# exit-code   1
# env-file    ~/.opam/log/coq-doc-96137-5df684.env
# output-file ~/.opam/log/coq-doc-96137-5df684.out
### output ###
# 29 |   (package coq)
# [...]
# Error: Package coq does not exist
# File "doc/stdlib/dune", line 25, characters 12-15:
# 25 |    (package coq))
#                  ^^^
# Error: Package coq does not exist
# File "doc/dune", line 44, characters 11-14:
# 44 |   (package coq)
#                 ^^^
# Error: Package coq does not exist
#         bash doc/stdlib/index-list.html
# Building file index-list.prehtml... Done



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build coq-doc dev
└─
┌─ The following changes have been performed
│ ↻ recompile coq                    dev
│ ↻ recompile coq-mathcomp-algebra   dev
│ ↻ recompile coq-mathcomp-fingroup  dev
│ ↻ recompile coq-mathcomp-ssreflect dev
│ ∗ install   coqide                 dev
│ ∗ install   coqide-server          dev
└─
```

This is also confirmed by @dmitromikh 

#### Coq Version

31a253639c8b5093c8d6e65db082e4aaca225c4a

**Comment by Zimmi48** [comment]
Yes. This is known and not planned to be fixed until Dune adds the support we need (for installing whole directories). These opam files inside the repository are not meant to be used. See #13578.

**Comment by anton-trunov** [comment]
I see, thanks for the pointer. Although, from the user prospective I'd say that local opam installation is a very nice feature. Sometimes there is a fix that is going to take a while to merge but this feature allows one to install Coq and a bunch of packages from a branch, continue working on your project and then switch to the `dev` version from opam when the fix is merged and eventually to a released version of Coq. I personally had to do this several times in the past couple of years.

**Comment by ejgallego** [comment]
Umm, that doesn't look related to the directory support right? The error is about a missing coq package.

**Comment by ejgallego** [comment]
Actually the package should install, but with most files missing.

**Comment by anton-trunov** [comment]
> that doesn't look related to the directory support

@ejgallego Could you expand a bit more?

**Comment by Zimmi48** [comment]
> I see, thanks for the pointer. Although, from the user prospective I'd say that local opam installation is a very nice feature. Sometimes there is a fix that is going to take a while to merge but this feature allows one to install Coq and a bunch of packages from a branch, continue working on your project and then switch to the `dev` version from opam when the fix is merged and eventually to a released version of Coq. I personally had to do this several times in the past couple of years.

But this use case has been supported forever with the core-dev repository. What made you want to install from the git repository?

**Comment by anton-trunov** [comment]
> What made you want to install from the git repository?

I need the version from this unmerged PR: https://github.com/coq/coq/pull/13624 which fixes a bug that does not let me to proceed with extraction.

**Comment by Zimmi48** [comment]
Ah I see, thanks! I definitely read the comments in this issue too fast! That sounds like a good use case that would be reasonable to support. I'll close my PR proposing to remove the opam files. You should be able to install all opam files but `coq-doc` until this is fixed.

**Comment by anton-trunov** [comment]
Many thanks, Théo!

**Comment by ejgallego** [comment]
This worked for me on a fresh opam switch and Python `venv` (with slightly upgraded deps)

However the coq-doc build is empty, so I will leave this open until a proper build is done.
