### ISSUE TITLE
ltac || fails to detect failure

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#13639]
#### Description of the problem
The `u || v` tactic composition fails to detect that `u` failed and does not try `v`.

#### Example
```coq
Definition fapp (n: nat) (f : nat -> nat) := f n.

Lemma fapp_comp {f: nat -> nat} {g: nat -> nat} {n: nat} :
  g (fapp n f) = g (f n).
Proof. reflexivity. Qed.

Lemma main {f : nat -> nat} {n m: nat} : n = m -> fapp n f = fapp m f.
Proof.
  intro H.
  (simple refine (eq_trans fapp_comp _)) || f_equal. (* this fails *)
  exact H.
Qed.
```
In the above example, `||` does not recognize that `(simple refine (eq_trans fapp_comp _))` failed and just fails without trying `f_equal`. 
Interestingly, replacing `||` by `+` makes the example work, so the problem cannot be ill syntax.
Also, `try (simple refine (eq_trans fapp_comp _)).` produces an error, which is unfortunate. 

- Associated [zulip discussion](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/when.20ltac.20try.20fails).

#### Coq Version
Tested on 
```
The Coq Proof Assistant, version 8.12.1 (December 2020)
compiled on Dec 6 2020 13:40:33 with OCaml 4.07.1
```
also on `8.14+alpha (December 2020)`.

**Comment by ppedrot** [comment]
So the culprit is not the tactic, so for once Ltac is not guilty of anything. The problem comes from the tactic wrapper at toplevel, which tries to solve unification constraints after the dot. As a workaround you can `Unset Solve Unification Constraints`.

**Comment by fakusb** [comment]
you can also call solve_constrains by hand after refine:
 `(simple refine (eq_trans fapp_comp _);solve_constraints) || f_equal.`

**Comment by JasonGross** [comment]
I'm inclined to resolve this bug as invalid?  Alternatively, perhaps Coq should clearly mark when the error comes from the final unification constraints being solved rather than from some tactic.

**Comment by Alizter** [comment]
So this is flagging that we need a user-end indication that the error came from unification not the tactic level?

**Comment by ppedrot** [comment]
I don't see how you can realize that. At best this is a documentation issue, but AFAIR it's actually correctly documented even though seemingly not advertised enough... I'd personally recommend closing as-is.
