### ISSUE TITLE
Coq 8.13 beta1 vscoq regression (incorrect goal display)

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#13657]
#### Description of the problem

When used with `Coq 8.13 beta1` after executing the following code
```
Goal True.
Proof.
  assert False. 
```
vscoq displays two goals both of which are (incorrectly) `True`.

Copy of: https://github.com/coq-community/vscoq/issues/190

#### Coq Version

The Coq Proof Assistant, version 8.13+beta1 (December 2020)
compiled on Dec 16 2020 16:52:34 with OCaml 4.11.1

This was reproduced under both Widows and Linux.

**Comment by fakusb** [comment]
After some preliminary debugging, the problem seems to be related to the fact that we have problems parsing the goal id of each goal that the xml protocol returns, which is `NaN`. I'm not yet able to check the exact xml that we get, so this theoretically could be on the vscoq-side.

**Comment by fakusb** [comment]
The problem is that the `<goal>` tag does contain an empty `<string>` as first child (the goal ID) in 8.12-beta1. In 8.12.0, this first child contained some number which could be used to identify the goal.

**Comment by fakusb** [comment]
The PR that made this fail is #13145. Most likely, this part:
https://github.com/coq/coq/pull/13145/files#diff-69d0d91143fdd0a86e418fc010a50c7a5c2490baea825b06b8534fdf6d4ae409R198

@herbelin @Zimmi48 can we keep the Goal.uid instead of taking "" if the user did not activate Print goal names?
Should we expect the goal ID to be a string instead of a number from now on?

**Comment by herbelin** [comment]
Thanks for pointing out the source of the change. I would need some time to check whether `""` or `Goal.uid` matters for CoqIDE.

**Comment by fakusb** [comment]
I could also try to investigate id we really need the proof id on the vscoq side. It might be easy to remove it there.

**Comment by gares** [comment]
Given the diff
```diff
-  let id = Goal.uid g in
+ let id = if Printer.print_goal_names () then Names.Id.to_string (Termops.evar_suggested_name g sigma) else "" in
```
I'd say that replacing `""` with `Goal.uid g` is OK, but you also have to fix the tests `if CString.is_empty id then` added in that PR.

**Comment by gares** [comment]
Unfortunately vscoq is not the only UI based on this protocol :-/

**Comment by gares** [comment]
I prepared a revert just in case, but I'd prefer the feature to be "fixed" before the release.
It would be great if someone could test if the revert PR above is *enough* to fix the problem

**Comment by fakusb** [comment]
#13145 would fix vscoq.
