### ISSUE TITLE
Error "Undeclared custom entry: dfrac" when Exporting module

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#13654]
#### Description of the problem

```coq
Module dfrac.
  Declare Custom Entry dfrac.
  Notation "{ dq }" := (dq) (in custom dfrac at level 1, dq constr).
End dfrac.

Module M1.
  Export dfrac.
  Notation "↦∗ dq" := (id dq) (at level 20, dq custom dfrac at level 1).
End M1.

Module M2.
  Export dfrac.
  Notation "$∗ dq" := (id dq) (at level 20, dq custom dfrac at level 1).
End M2.

Module M.
  Export M1.
  Export M2.
  (* Warning: Custom entry dfrac has been overriden. [custom-entry-overriden,parsing] *)
End M.

Import M.
(* Error: Undeclared custom entry: dfrac. *)
```

The module `dfrac` defines a custom entry, and both the modules `M1` and `M2` define a notion that involves the custom entry. Now, exporting both `M1` and `M2` is fine. However, when importing the module `M` that exports said modules, I get the error "Undeclared custom entry: dfrac".

Also, there is a warning when exporting `M2` in `M`. I don't understand that warning.

This code is obtained by reducing an actual bug we faced when trying to use custom entries in Iris, see https://gitlab.mpi-sws.org/iris/iris/-/merge_requests/554#note_61015.

```coq
From iris.heap_lang Require proofmode.

Module foo.
  Export iris.heap_lang.derived_laws.
  Export iris.heap_lang.primitive_laws.
End foo.

(* Undeclared custom entry: dfrac. *)
Export foo.
```

This requires the version of Iris in https://gitlab.mpi-sws.org/iris/iris/-/merge_requests/554

#### Coq Version

The Coq Proof Assistant, version 8.12.0 (September 2020)
compiled on Sep 15 2020 7:57:30 with OCaml 4.08.1

Probably not relevant, but that's on Debian Linux.

**Comment by robbertkrebbers** [comment]
Just tried, the same bug also occurs in Coq 8.13:

The Coq Proof Assistant, version 8.13+beta1 (December 2020)
compiled on Dec 17 2020 12:22:00 with OCaml 4.11.1

**Comment by robbertkrebbers** [comment]
I updated the issue with a less contrived minimal example that shows that this bug could happen in real Coq code.

**Comment by RalfJung** [comment]
The error can be avoided by doing `Declare Custom Entry dfrac.` or `Import dfrac.` right before `Import M.`... odd. Looks like the `Declare Custom Entry` effect is exported "through 1 level", but transitively.

**Comment by RalfJung** [comment]
Hm no it's not a "max 1 level" thing since removing the `Export M2.` in `M` also makes it work. I have no idea how to explain this.

Cc @herbelin

**Comment by charguer** [comment]
I'm being hit by exactly the same bug. In my case I was using several files:

A.v:
```
Declare Custom Entry trm.
```

B.v: 
```
Require Export A.
Notation "'foo'" := true (in custom trm).
```

C.v: 
```
Require Export A B. (* raises warning *)
Notation "'bar'" := false (in custom trm).
```

D.v: 
```
Require Export B C. (* raises error *)
```

Here, the work-around is to remove the redundant export (thought they should be perfectly legitimate).

**Comment by SkySkimmer** [comment]
Simpler example
~~~coq
Module dfrac.
  Declare Custom Entry dfrac.
End dfrac.

Module M1.
  Import dfrac.
  Notation "↦∗ dq" := (id dq) (at level 20, dq custom dfrac at level 1).
End M1.
Import M1.
~~~
For some reason Declare Custom Entry takes effect at import time, not require/end module time.

Also
~~~coq
Module dfrac.
  Module Inner.
    Declare Custom Entry dfrac.
  End Inner.
End dfrac.
Import dfrac.
Import Inner.
~~~
The `Import Inner` warns "Custom entry dfrac has been overridden" which seems wrong.

cc @herbelin

**Comment by RalfJung** [comment]
@herbelin did you have any chance to look at this? This bug is currently preventing us from using custom entries in Iris (and I just heard from @Janno that the bug is also causing a lot of trouble for him).

**Comment by Janno** [comment]
>  I just heard from @Janno that the bug is also causing a lot of trouble for him.

Indeed, I am suffering from this in https://github.com/Mtac2/Mtac2/pull/334 although I could work around it in Mtac2 itself. Not sure what the implications for (potential) users would be. 

(The custom entries feature is otherwise amazing and with 8.13 I was able to use it very productively.)
