### ISSUE TITLE
Clarification about proof diff start. and end. tags

### ISSUE THREAD

**Issue by j-hui** [coq/coq#13668]
Not so much a bug as a clarification about documentation.

The [XML protocol documentation](https://github.com/coq/coq/blob/master/dev/doc/xml-protocol.md#highlighting-text) indicates that proof diffs use `start.` and `end.` tags to mark the beginning and end of proof diff regions without needing to respect the nesting of other tags.

When reading this, I assumed that these would be used as self-closing tags. However, Coqtop produces XML where these tags contain content. What is the meaning of this?

#### Example

For example, Coqtop may produce the following:

```xml
<pp> <start.diff.added.bg/> c : <start.diff.added> <constr.variable> B </constr.variable> </start.diff.added> <end.diff.added> <constr.variable> x </constr.variable> </end.diff.added> <end.diff.added.bg/> </pp>
```

What does it mean for `B` to be contained within `<start.diff.added>`, and for `x` to be contained within `<end.diff.added>`?

I'm currently working on something that uses these, and for now I am simply interpreting the start tag of `start.diff.*` as the start tag, and the end tag of `end.diff.*` as the end tag, i.e.,

```xml
A<start.diff.added>B</start.diff.added>C
```

as

```xml
A<start.diff.added/>BC
```

and

```xml
A<end.diff.added>B</end.diff.added>C
```
as
```xml
AB<end.diff.added/>
```

But is this interpretation correct?

#### Coq Version

```
The Coq Proof Assistant, version 8.10.2 (October 2020)
compiled on Oct 15 2020 15:08:03 with OCaml 4.07.1
```

**Comment by gares** [comment]
Cc @jfehrle

**Comment by jfehrle** [comment]
Would you provide a (partial) proof that generates output similar to your example?

Your use of 8.10 is intentional?  8.13 will be out soon.

**Comment by j-hui** [comment]
Here is the proof I was testing with:

```coq
Set Diffs "on".

Example foo: forall (C: Prop) (T: Set) (B: T -> Prop),
  (exists x, C -> B x) -> C -> exists x, B x.
Proof.
  intros C T B H c.
  destruct H as [x H].
  exists x.
  apply H in c. (* <- *)
  exact c.
Qed.
```

But I observed this issue in other places as well (I just happened to pick that line to investgate).

> Your use of 8.10 is intentional? 8.13 will be out soon.

The choice was arbitrary, but I do hope to support all Coq versions where proof diffs are available (I'm adding this feature to Vim's Coqtail plugin).

**Comment by jfehrle** [comment]
I had to look at the full XML to make sense of your short version.  You can see this with `bin/coqide -xml-debug` in 8.13 or master.  The command-line option was recently added but the XML for diffs should be the same.  

Here's an excerpt of the XML output after `apply` corresponding to your example:

![image](https://user-images.githubusercontent.com/1253341/103040534-9a059e80-4528-11eb-83c4-aea3c352abc6.png)

```
                    <ppdoc val="tag">
                      <pair>
                        <string>start.diff.added.bg</string>
                        <ppdoc val="string">
                          <string></string>
                        </ppdoc>
                      </pair>
                    </ppdoc>
                    <ppdoc val="string">
                      <string>c</string>
                    </ppdoc>
                    <ppdoc val="string">
                      <string>&nbsp;:&nbsp;</string>
                    </ppdoc>
                    <ppdoc val="box">
                      <pair>
                        <ppbox val="hovbox">
                          <int>2</int>
                        </ppbox>
                        <ppdoc val="glue">
                          <list>

                            <ppdoc val="tag">
                              <pair>
                                <string>start.diff.added</string>
                                <ppdoc val="tag">
                                  <pair>
                                    <string>constr.variable</string>
                                    <ppdoc val="string">
                                      <string>B</string>
                                    </ppdoc>
                                  </pair>
                                </ppdoc>
                              </pair>
                            </ppdoc>
                            <ppdoc val="glue">
                              <list>
                                <ppdoc val="break">
                                  <pair>
                                    <int>1</int>
                                    <int>0</int>
                                  </pair>
                                </ppdoc>

                                <ppdoc val="tag">
                                  <pair>
                                    <string>end.diff.added</string>
                                    <ppdoc val="tag">
                                      <pair>
                                        <string>constr.variable</string>
                                        <ppdoc val="string">
                                          <string>x</string>
                                        </ppdoc>
                                      </pair>
                                    </ppdoc>
                                  </pair>
                                </ppdoc>
                              </list>
                            </ppdoc>
                          </list>
                        </ppdoc>
                      </pair>
                    </ppdoc>
                  </list>
                </ppdoc>

                <ppdoc val="tag">
                  <pair>
                    <string>end.diff.added.bg</string>
                    <ppdoc val="string">
                      <string></string>
                    </ppdoc>
                  </pair>
                </ppdoc>

```

> What does it mean for `B` to be contained within `<start.diff.added>`, and for `x` to be contained within `<end.diff.added>`?

It means that `B` should get the diff.added highlight and that `x` should not get it.  Any other strings appearing between these two tags should get the diff.added highlight, too.  Think of the tags as flipping state variables as you step through the XML in order.

**Comment by j-hui** [comment]
Thank you for looking into this! I notice the XML format looks quite a bit different compared to what I get from Coqtail/Coqidetop. Is that format specific to CoqIDE, or Coq 8.13, or am I missing something?

> It means that B should get the diff.added highlight and that x should not get it.

But in your screenshot from CoqIDE, isn't `x` also highlighted?

> Think of the tags as flipping state variables as you step through the XML in order.

This is also how I think of it, but I'm wondering precisely where the state flip happens---at the opening tag (e.g., `<start.diff.added>`) or the closing tag (e.g., `</start.diff.added>`).

**Comment by jfehrle** [comment]
> But in your screenshot from CoqIDE, isn't `x` also highlighted?

Good point.  Do what the code does, not what I say it does 🙂.  I haven't worked on this code for a while.  For an ending tag, it appears the highlight ends after any contents within. That avoids some empty tags.

The XML protocol hasn't changed significantly in the last couple releases AFAIK. Perhaps what you see is printed by a routine in Pp.ml before it's converted to XML, so a bit different. How exactly do you get it?

If it's a different code path, it's possible the encoding doesn't handle the diff tags correctly, in which case Coq would need a fix.

FWIW, Proof General currently interfaces in a different way through "coqtop -emacs", which we'd like to retire in favor of the XML interface.  We'd probably like to see Coqtail eventually use the XML interface, too.

**Comment by j-hui** [comment]
> For an ending tag, it appears the highlight ends after any contents within. That avoids some empty tags.
I think this lines up with what I had suspected, thanks! I guess I can close this issue now since that answers my question about the documentation.

> How exactly do you get it?
... To be honest, I'm not totally sure. This is just what Coqtail dumps when you turn on debugging. I always assumed that it's what it got directly from `coqidetop`. Perhaps @whonore may know more about this...

> We'd probably like to see Coqtail eventually use the XML interface, too.
As far as I'm aware, that's pretty much [what Coqtail is already doing](https://github.com/whonore/Coqtail/blob/master/python/xmlInterface.py#L1310). It doesn't use the `-emacs` interface.

**Comment by whonore** [comment]
@j-hui is right that Coqtail just gets XML directly from `coqidetop`. It looks like the difference in the XML output is due to the `--xml_format=Ppcmds` option that `coqide` [seems to use](https://github.com/coq/coq/blob/master/ide/coqide/coq.ml#L376), but Coqtail does not.
