### ISSUE TITLE
Ltac1 application of Ltac2 thunks fails to follow the standard rules of Ltac1 runtime-evaluation

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#13687]
#### Description of the problem

Consider the following difference between Ltac1 application of Ltac1 tactics and Ltac1 application of Ltac2 tactics:
```coq
Require Ltac2.Ltac2.

Ltac tac1 x := idtac "run 1".
Ltac2 tac2 x := Message.print (Message.of_string "run 2").
Ltac tac2 := ltac2:(x |- tac2 x).

Goal True.
  tac1 I. (* run 1 *)
  tac2 I. (* run 2 *)
  let _ := tac1 I in idtac. (* run 1 *)
  let _ := tac2 I in idtac. (* *) (* no output *)
  (* workaround *)
  let _ := match goal with _ => tac2 I end in idtac. (* run 2 *)
```

Is there a way to fix this without breaking or complicating everything @ppedrot ?

#### Coq Version

8.12

**Comment by ppedrot** [comment]
Unfortunately, it's fairly typical of Ltac1 runtime distinction of tactics vs everything else. The match goal trick is fairly standard to force the evaluation of its arguments.

We may make it the default behaviour but I am not sure that doing that is as expressive as the current situation. In that case you'd have to wrap the Ltac2 closure in an `idtac; ...` block, but then the interpreter might start doing weird things when you want to force it further. The documentation states that you shouldn't use the return value of the thunk, so with the right point of view, the current semantics forces you to rely on undefined behaviour *somehow*...

**Comment by JasonGross** [comment]
Hm, I guess we already see the same problem with `Tactic Notation` in just Ltac1:
```coq
Tactic Notation "tac3" constr(x) := idtac "run 3".
Goal True.
  let _ := tac3 I in idtac.
```
emits no output.

I don't *think* evaluating things early is any less expressive, since I think you can always add an `idtac; ` in front as you say.  What weird things are you imagining the interpreter might do?
