### ISSUE TITLE
Retyping.RetypeError(_) on Info 1 destruct [...]

### ISSUE THREAD

**Issue by elidupree** [coq/coq#13698]
#### Description of the problem

This code:
```coq
Require Import Lists.SetoidList.

Lemma Problem : forall (A : Type) (eqA : A -> A -> Prop) (x : A) (l : list A), NoDupA eqA (x::l) -> True.
  Info 1 destruct 1.
```
spits out this error when I run it in coqide:
```
Anomaly "Uncaught exception Retyping.RetypeError(_)."
Please report at http://coq.inria.fr/bugs/.
```

#### Coq Version

The Coq Proof Assistant, version 8.12.2 (December 2020)
compiled on Dec 26 2020 12:26:31 with OCaml 4.07.1

Running in coqide on Windows 10.

**Comment by Alizter** [comment]
Seems to be fixed in 8.13.
