### ISSUE TITLE
rewrite_strat should expose the primitive fix operator

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#13702]
#### Description of the problem

[The documentation](https://coq.inria.fr/refman/addendum/generalized-rewriting.html#definitions) states:
> A few of these are defined in terms of the others using a primitive fixpoint operator:
> - `try rewstrategy := choice rewstrategy id`
> - `any rewstrategy := fix ident. try (rewstrategy ; ident)`
> - `repeat rewstrategy := rewstrategy; any rewstrategy`
> - `bottomup rewstrategy := fix ident. (choice (progress (subterms ident)) rewstrategy) ; try ident`
> - `topdown rewstrategy := fix ident. (choice rewstrategy (progress (subterms ident))) ; try ident`
> - `innermost rewstrategy := fix ident. (choice (subterm ident) rewstrategy)`
> - `outermost rewstrategy := fix ident. (choice rewstrategy (subterm ident))`

I think there should be a primitive `fix` operator for rewrite strategies that users can use, and, in combination with https://github.com/coq/coq/issues/6110, these strategies should be defined in user-space rather than in OCaml.

cc @mattam82 

#### Coq Version

8.12

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/17509
