### ISSUE TITLE
Avoid alpha-renaming in projection types

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#13727]
#### Description of the problem

In a `Record` declaration, the first letter of the record is used as a variable name for such a record in the type of a projection, which may collide with other variables in the field type.

```coq
Record Adjunction :=
  { unit : forall {a}, a }.

About unit.
```

We get

```
Adunction -> forall a0, a0   (* i.e.,   forall (a : Adjunction), forall a0, a0 *)
```

instead of

```
Adjunction -> forall a, a
```

There is apparently no way to get that latter result other than painfully renaming each projection with `Arguments`.

Proposal: rename the record instead, so we get `unit : forall (a0 : Adjunction), forall a, a`. This is backwards compatible in the sense that if anyone somehow wanted the current behavior, they could just alpha rename their fields, avoiding the name collision while getting the same result.

Another idea would be to explicitly specify the new variable name via an annotation, but it's more syntactic noise.

#### Coq Version

Tested on Coq 8.12

**Comment by Lysxia** [comment]
I would volunteer to do this, and could use a hint where to look first.

**Comment by ppedrot** [comment]
`Record.declare_projections` looks like a good place to start.
