### ISSUE TITLE
Ltac2 syntax that triggers a call to Tac2core.apply?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13722]
IIUC, the code in [Tac2core.apply](https://github.com/coq/coq/blob/30f497eaf34f2cf641c3fe854fc9066ae19eea67/user-contrib/Ltac2/tac2core.ml#L1644-L1647) returns a parser action routine that [add_scope "seq"](https://github.com/coq/coq/blob/30f497eaf34f2cf641c3fe854fc9066ae19eea67/user-contrib/Ltac2/tac2core.ml#L1671-L1677) adds to the parser, but I've not been able to detect a call to `apply` with the following input.  What is an input that will invoke this?

```
From Ltac2 Require Import Ltac2.

Ltac2 Notation "intros2" s(seq("a", "b")) := intros.
intros2 a b.
```

**Comment by jfehrle** [comment]
Attn @ppedrot .

**Comment by ppedrot** [comment]
How do you track the calls to `apply`? It's returning an anonymous closure, so you won't see the name `apply` appear at runtime when this closure is actually triggered.

**Comment by jfehrle** [comment]
With a print statement at the beginning of `apply`.

**Comment by ppedrot** [comment]
If you put it *outside* of the closure, according to the code it should be evaluated at scope parsing time. I am not sure when that happens exactly, but it will be triggered somehow. If you put it inside the closure, it should be evaluated at parsing. Are you sure you're printing something that makes it to the standard output?

**Comment by jfehrle** [comment]
I should have been clearer in the description that I wanted to catch the call to the parser action routine returned by `apply`.  The `let () = add_scope "seq" begin fun toks` near the end of the file led me to look for it with the wrong input.

I didn't think to run the test suite yesterday.  Trying that now, I see there are 2 tests that use the production and call the action routine, for example `ltac2/binder.v` around line 14.  Problem solved, thanks for your help.
