### ISSUE TITLE
"Hint Rewrite" does not support visibility qualifiers

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#13724]
#### Description of the problem

Most `Hint` commands support `Local`/`Global` visibility qualifiers, but `Hint Rewrite` does not:
```
Lemma test: 0 = 0. Proof. reflexivity. Qed.
Global Hint Rewrite test.
(* Error: This command does not support this attribute: global. [unsupported-attributes,parsing] *)
```
Would be good to make the handling of these qualifiers consistent across `Hint` commands.

#### Coq Version

8.12.2

**Comment by Agnishom** [comment]
So are they local by default or global by default?

**Comment by Zimmi48** [comment]
@Agnishom As documented in https://coq.inria.fr/refman/proofs/automatic-tactics/auto.html#creating-hints, it is "local" by default inside sections and "global" by default outside (however, this will change to "export" by default outside sections in 8.18, and for this reason, recent versions of Coq warn when no explicit locality is provided).
