### ISSUE TITLE
Un-removable warning [unused-pattern-matching-variable] for pattern matching when using Functional Induction 

### ISSUE THREAD

**Issue by bschommer** [coq/coq#13739]
#### Description of the problem

I tried the new coq version 8.13 on CompCert and stumbled upon a new case for the warning `unused-pattern-matching-variable` which I could not resolve, since the variables that it reports do not exist in the pattern matching. I was able to reproduce the problem on a smaller test program:
````coq
Require Import BinNums.
Require Import FunInd.

Inductive test : Type :=
| Skip : test
| Stest : Z -> test
| Seq : test -> test -> test
| Sother : test.

Inductive test_class : Type :=
| CSkip
| Ctest (id: Z)
| Other.

Function foo (s: test) : test_class :=
  match s with
  | Skip => CSkip
  | Stest id => Ctest id
  | Seq s Skip => foo s
  | Seq Skip s => foo s
  | _ => Other
  end.
````

For this small snippet coqc reports:

````
File "./test.v", line 19, characters 8-9:
Warning: Unused variable s0 catches more than one case.
[unused-pattern-matching-variable,pattern-matching]
File "./test.v", line 20, characters 13-14:
Warning: Unused variable s0 catches more than one case.
[unused-pattern-matching-variable,pattern-matching]
File "./test.v", line 19, characters 8-9:
Warning: Unused variable s0 catches more than one case.
[unused-pattern-matching-variable,pattern-matching]
File "./test.v", line 20, characters 13-14:
Warning: Unused variable s0 catches more than one case.
[unused-pattern-matching-variable,pattern-matching]
File "./test.v", line 19, characters 8-9:
Warning: Unused variable s1 catches more than one case.
[unused-pattern-matching-variable,pattern-matching]
File "./test.v", line 20, characters 13-14:
Warning: Unused variable s1 catches more than one case.
[unused-pattern-matching-variable,pattern-matching]
File "./test.v", line 19, characters 8-9:
Warning: Unused variable s0 catches more than one case.
[unused-pattern-matching-variable,pattern-matching]
File "./test.v", line 20, characters 13-14:
Warning: Unused variable s0 catches more than one case.
[unused-pattern-matching-variable,pattern-matching]
````

#### Coq Version
8.13

**Comment by herbelin** [comment]
As far as this specific report is concerned, and as told in the CoqPL discussion today, `Function` could easily deactivate the warning. Informing @coq/funind-maintainers if ever they have time for it.

**Comment by xavierleroy** [comment]
Some `Function` definitions in CompCert also trigger this other warning:
```
Warning: Not a truly recursive fixpoint. [non-recursive,fixpoints]
```
The definition is not recursive indeed but maybe `Function` chooses to produce a `Fixpoint`.

**Comment by xavierleroy** [comment]
While we are at it, `Function solve_constraints ... { measure m arg } := ...` causes the following warning at extraction time:
```
Warning: The extraction is currently set to bypass opacity, the following
opaque constant bodies have been accessed
:  solve_constraints_terminate.
 [extraction-opaque-accessed,extraction]
```
Probably `solve_constraints_terminate` needs to be defined transparently.

**Comment by Matafou** [comment]
Yes Function produces a fixpoint on non recursive functions, historically this was not problem until recent coq versions made this forbidden.

It is probably not a big deal to change but I don't really understand the code of function anymore.
I will try to have a look if @forestjulien is not available.

**Comment by gares** [comment]
I believe it should be possible to locally disable the warning. These warnings are for the user, to help spot mistakes. Generated code should not raise them by design. Making the code generation smarter is also a possibility, but I'm not sure it is worth it (eg in order to name only used variables or decide between fix and Def one has to perform an occur check, doable but not free).

**Comment by Zimmi48** [comment]
If `Function` is meant to generate only recursive functions, then isn't it normal that a warning is raised when a user misuse it?
If `Function` is also supposed to support generating non-recursive functions, then isn't it a problem that it will insert a `fix` in the generated code? This does change the reduction behavior for instance...

**Comment by Matafou** [comment]
It is not the case. Function can generate non recursive function. Actually most of the time (except for non structural recursion) it delegate this definition to the standard mechanism and then generates the equation of the function and its induction principle, which in case of non recursive function is obviously more like a destruct principle.

**Question**: it seems there is currently no way to store the state of a warning flag (in order to restore it later) am I right? So I will add such a feature (or maybe something cleaner). Or did I miss something?

**Comment by Matafou** [comment]
@Zimmi48 Actually until now Function has always used the "Fixpoint" mechanism when delegating. Until recently IIUC Fixpoint behaved like Definition when given a non recursive definition. Now this has changed I think.

**Comment by Zimmi48** [comment]
AFAIK `Fixpoint` has always behaved the same (generates a `fix`). The only thing that changed is this new warning to prevent users from wrongly using it to generate non-recursive functions.

**Comment by Zimmi48** [comment]
What about fixing `Function` to use the right definition mechanism for non-recursive functions? You wouldn't have to store a warning for later. Or was this unrelated?

**Comment by Matafou** [comment]
Sorry I am mixing two subject.

I need to disable the warning about unused pattern variables, that is for sure. And I am struggling understanding how the warning mechanism works. From outside `cWarning.ml` one can only set all flags at once (`set_flags`)? And internally flags are actually stored as one big string? I will ask for help somewhere else to avoid polluting this thread anyways.

**Comment by Matafou** [comment]
@zimmi I propose this PR (I will push the typo you pointed) to remove these warnings, including the one about non truly recursive fix. Then I will try to call the Definition mechanism when needed. This may take more time and may also be slightly backward incompatible.

**Comment by Matafou** [comment]
> Some `Function` definitions in CompCert also trigger this other warning:
> 
> ```
> Warning: Not a truly recursive fixpoint. [non-recursive,fixpoints]
> ```
> 
> The definition is not recursive indeed but maybe `Function` chooses to produce a `Fixpoint`.

Hi @xavierleroy, Actually I did not manage to reproduce the non-recursive warning. Can you give more details please?

Actually I could trigger an real error  when using Functino to define non recursive functions where there is no recursive inductive argument. But I could trigger the warning only.

**Comment by bschommer** [comment]
> Hi @xavierleroy, Actually I did not manage to reproduce the non-recursive warning. Can you give more details please?
> 
> Actually I could trigger an real error when using Functino to define non recursive functions where there is no recursive inductive argument. But I could not trigger the warning only.

For example `combine_op` in [powerpc/CombineOp.v](https://github.com/AbsInt/CompCert/blob/25483cf1acce8695a438f4f2164b09fb1ecd9d2e/powerpc/CombineOp.v#L83). Also the other variants of this function in the other backends trigger the same warning.

**Comment by Matafou** [comment]
I am sorry I can't reproduce the non-recursive warning. With 8.13 8.12 or master (at least with `x86/CombineOp.v`). I checked and the warning are not silenced (while others are) in the makefile.
Can yout tell me which versions I should use please?

**Comment by bschommer** [comment]
8.13 and also 8.12, maybe try configuring CompCert for PowerPC instead of x86.
