### ISSUE TITLE
eapply with (name := ...) does not work with name mangling

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#13759]
#### Description of the problem

In adjusting Iris to work with name mangling, I am running into many cases where we are using `eapply lemma with (name := ...)` to avoid the dreaded `eapply (lemma _ _ _ _ _ _ _ ...)` where one always gets the number of `_` wrong. It seems this feature just never works with name mangling, I always get errors like

> Error: No such bound variable t1 (possible names are: _0, _1, _2, _3, _4, _5, _6, _7, _8, _9 and _10).

I tried using `eapply with (num := ...)` instead, but no matter the number I pick, Coq always rejects this with some type error. Also, using a name would be much better than using a number.

Here's a self-contained example:
```
Set Mangle Names.

Lemma test (x y : nat) : x = y.
Admitted.

Goal exists x, 2 = x.
Proof. eexists. eapply test with (y := 2). Qed.
```

We are still evaluating this, but it might well be that name mangling is unusable for us if we cannot find a way to still use named arguments in `eapply` -- that's just a tremendously useful feature.

Potentially related: https://github.com/coq/coq/issues/6029

#### Coq Version

Coq master

**Comment by jashug** [comment]
The Coq stdlib has the same problem, but this syntax is not used pervasively, so I've gotten away with changing things to `eapply (lemma _ _ _ _ _ _ _ ...)` (and there are usually only 2 or 3 implicit arguments).

The discussion in 6029 is indeed very relevant here. If `x` and `y` were implicit arguments, you could do `eapply (lemma (y := 2))`.

It looks like #13443 (cc @herbelin) would allow you to do `eapply (lemma (y := 2))` even when `y` is not implicit, or do something like `eapply (lemma (2 := 2))` if `y` is non dependent (see also coq/ceps#49).

**Comment by SkySkimmer** [comment]
If we brutally remove https://github.com/coq/coq/blob/9485db5e16edeaf408f73758f2e7f9531dc7d3e0/proofs/clenv.ml#L729 the example works, not sure of the implications though.

**Comment by SkySkimmer** [comment]
I tried removing that rename and the other one in clenv. While compiling the stdlib
- we get some "binder name xx occurs more than one in clause" (here I removed the error and just picked the first one in the list)
- "error: cannot create equation lemma" at https://github.com/coq/coq/blob/16765871394a81975047b37f15a902fcc112dc40/theories/FSets/FMapFullAVL.v#L709, funind needs to stop using the renamed names too

cf https://github.com/coq/coq/pull/13837
