### ISSUE TITLE
coqide --version causes coqidetop to die badly

### ISSUE THREAD

**Issue by DonaldKellett** [coq/coq#13752]
So I just installed the beta Snap version of the Coq platform on Ubuntu 20.04.1 LTS:

```bash
$ sudo snap install --beta coq-prover
```

After installation, I ran `coqide --version` to check the version of CoqIDE that was installed, but instead, I got an error message saying that "coqidetop died badly" with 3 windows open:

![Screenshot from 2021-01-16 21-24-39](https://user-images.githubusercontent.com/7777884/104813010-50675580-5841-11eb-8312-070e1bf9b893.png)

2 windows are the warning message "coqidetop died badly" and 1 window is the actual editor. Clicking on "Reset" does not solve the problem and clicking on the other two buttons to try to quit the program spawns _more_ windows with the same error message perfectly stacked on top of one another. In this case, it seems that the only way to quit the program is to hit `Ctrl-C` in the terminal.

In comparison, the deb version of CoqIDE from the `focal` repositories gives a much simpler error on `coqide --version` and exits immediately (with exit code 1):

```
Invalid character ' ' in identifier "The Coq Proof Assistant, version 8.11.0 (March 2020)".
```

While this doesn't seem to affect everyday usage of CoqIDE (I haven't tried stepping through my projects with it yet), I suppose this is unintended behavior?

**Comment by DonaldKellett** [comment]
> Can you confirm that CoqIDE works otherwise fine?

I just tried it with [a simple textbook exercise](https://github.com/DonaldKellett/plcc-ch2-long-division) as follows:

1. Download the repo
1. `cd` to the repo
1. Run `coq_makefile -f _CoqProject -o Makefile`
1. Open `Maps.v` in CoqIDE and step through the file till the end
1. Select `Compile > Make`

In the last step I get a "make failed" (all previous steps work as expected), and the messages window shows "/bin/sh: 1: make: not found":

![Screenshot from 2021-01-17 13-33-09](https://user-images.githubusercontent.com/7777884/104831976-8e5b8c80-58c8-11eb-853f-2ca0e2a4f439.png)

I reflexively typed `which make` in my terminal which gave `/usr/bin/make`, but then realized that Snaps are confined and therefore likely do not have access to binaries on my base system by default. Either way, it seems that `make` should be packaged into the Snap as well in order to facilitate building Coq projects within CoqIDE.

**Comment by gares** [comment]
Thanks, here the fix https://github.com/coq/platform/pull/65

**Comment by DonaldKellett** [comment]
I was about to say that the error was still there, but then it occurred to me to switch to `edge` and now make succeeds (for the same textbook exercise linked above), thanks for fixing it! Unfortunately I am not in a position to test the external libraries included in the package as my projects mostly use stuff from the Coq stdlib only.

**Comment by gares** [comment]
Thanks for testing! I moved version 10 to beta now.

**Comment by Zimmi48** [comment]
To come back to the original issue, there seems to be an 8.11 regression and an 8.12 regression:

In 8.10, `coqide --version` opens a window to show the version.
In 8.11, `coqide --version` fails with:

```
Invalid character ' ' in identifier "The Coq Proof Assistant, version 8.11.2 (January 1980)".
```

Note that `coqide --version foo.v` fails with:

```
Invalid character '.' in identifier "bla.vThe Coq Proof Assistant, version 8.11.2 (January 1980)".
```

In 8.12, `coqide --version` fails immediately and the return code is 248 (like in the test by Enrico).

I did my tests with the Nix version.

**Comment by gares** [comment]
Given that CoqIDE displays the version when the windows open, I propose to just remove the --version option.

**Comment by silene** [comment]
Why not just let CoqIDE handle the `--version` option? I cannot think of any good reason to pass it to `coqidetop`. (If the user wanted the version of `coqidetop`, they would have run `coqidetop --version`.) If CoqIDE ever becomes independent of Coq (I do not believe so, but some people do), then it will have to have its own `--version` option anyway.
