### ISSUE TITLE
There is no PDF manual in the release page of Coq 8.13.0

### ISSUE THREAD

**Issue by txyyss** [coq/coq#13767]
#### There is no PDF manual in the release page of Coq 8.13.0.

https://github.com/coq/coq/releases/tag/V8.13.0

**Comment by gares** [comment]
@Zimmi48 Should I publish it myself or you do it when you out it on Zenodo?

**Comment by Zimmi48** [comment]
I can take care of it if you want but it's fully independent of Zenodo.

**Comment by Zimmi48** [comment]
Fixed.

**Comment by gares** [comment]
Thanks for fixing this. If we don't want this bug to pop up again, maybe we should fix the release checklist. Eg: https://github.com/coq/coq/issues/12334 does not have an item for the PDF (this is why I thought it was part of the zenodo upload).

**Comment by Zimmi48** [comment]
Absolutely, I'll do this right now.
