### ISSUE TITLE
Calling Ltac2 within a Hint Extern body

### ISSUE THREAD

**Issue by jonleivent** [coq/coq#13784]
There currently (8.12.2) is no direct way to call an Ltac2 tactic within a Hint Extern and pass in the pattern bound variables of the hint.  Probably the easiest workaround is to ignore the pattern variables matched by the hint and re-match the goal within the ltac2 tactic:
```Coq
Hint Extern 42 (fun _ _ _) =>
ltac2:(match! goal with
          [ |- (fun ?a ?b ?c) ] => foo a; bar b; baz c
         end) : mydb.
```

An alternative would be to have `Hint Extern` accept Ltac2 directly when `Set Default Proof Mode` is `"Ltac2"`.  Or add a `Hint Extern2`.

**Comment by ppedrot** [comment]
What are you trying to achieve with this example? Even with Ltac1 you cannot write this as patterns need to be applied global references.

**Comment by ppedrot** [comment]
Furthermore, pattern variables are correctly bound in the tactic expression, so you can access them from the Ltac2 code using the bound variable feature of Ltac2 quotations. As a trivial example:
```
Require Import Ltac2.Ltac2.

Hint Extern 42 (list ?a) =>
  let f := ltac2:(a |-
    match Ltac1.to_constr a with
    | None => ()
    | Some c => Message.print (Message.of_constr c) end)
    in f a : foo.

Goal list nat.
Proof.
auto with foo. (* prints nat five times *)
```

**Comment by jonleivent** [comment]
I had an existing `Hint Extern` with 7 pattern vars.  I used the approach I mentioned of rematching the goal in Ltac2 instead of passing all 7 pattern vars across from Ltac1 into Ltac2 and matching out the `Ltac1.to_constr` option for each.  However, I'm finding the Ltac2 replacement is running slower than the previous Ltac1.  I'm debugging that now.

**Comment by ppedrot** [comment]
I think that the original bug can be considered closed.

**Comment by radrow** [comment]
Why was this closed? `Hint Extern` is still incompatible with Ltac2 and to me it's straight a missing feature or even a bug on its own. When I import Ltac2 I would expect it to be used everywhere by default.

**Comment by SkySkimmer** [comment]
See also https://github.com/coq/coq/pull/19690
