### ISSUE TITLE
rewrite at 2 fails even though there are 4 occurrences to rewrite.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#13780]
#### Description of the problem

```
(* In the following context: *)
Require Import Arith.
Require Setoid.
Goal (0 + 1) + 2 = 0 + (1 + 2).
intros.
(* The following tactic succeeds as expected: *)
rewrite Nat.add_comm at 1.
Undo.
(* But this one doesn't: *)
Fail rewrite Nat.add_comm at 2.
(* Even though this one does (there are in fact 4 occurrences that can be selected): *)
change (?x + ?y) with (y + x) at 2.
```

Can someone explains this behavior? It looks like a bug of rewrite to me.

#### Coq Version

8.12.1

**Comment by silene** [comment]
As far as I know, `rewrite` first instantiates the rewriting rule, and then looks for the specified occurrence. Here, there is only one occurrence of the left hand side of `add_comm (0 + 1) 2` in the whole term. We can discuss whether this behavior is sensible, but I very much doubt we can change it. So, tentatively closing.

**Comment by Zimmi48** [comment]
Thanks for the explanation. This behavior doesn't seem very sensible to me, but most importantly, it's not documented! I'm going to take care of this.

**Comment by silene** [comment]
> This behavior doesn't seem very sensible to me

I think most people would agree with you. Yet, even so, this behavior was also chosen for SSReflect (and it is documented there), because it was the only practical one. But to alleviate this issue, SSReflect adds a new stage when rewriting: 1. select candidate subterms, 2. instantiate rewriting rule, 3. count occurrences. The first stage (which is missing from vanilla `rewrite`) makes it possible to ignore the insanity of counting occurrences after instantiating the rewriting rule.

**Comment by Zimmi48** [comment]
Actually, this is only a limitation of the `at` clause (only implemented in setoid rewrite and SSReflect's `rewrite` from what I get from your last comment) and not one of the general occurrence selection mechanism. For instance, you can rewrite with the same lemma instantiated differently in different hypotheses:

```coq
Require Setoid.
Require Import Arith.
Goal 0 + 1 = 1 -> (0 + 1) + 2 = 0 + (1 + 2) -> True.
intros H1 H2.
(* The following tactic succeeds: *)
rewrite Nat.add_comm in H1, H2.
Undo.
(* While the following one fails as previously: *)
Fail rewrite Nat.add_comm in H1, H2 at 2.
```

**Comment by silene** [comment]
That is interesting. I did not know vanilla `rewrite in` was behaving like that. I would almost qualify as a bug the fact that it applies `eq_ind` several times. Note that SSReflect`s rewrite does not behave the same; `rewrite in` will perform a single instantiation of the rewriting rule and apply it to all the hypotheses at once.

**Comment by Zimmi48** [comment]
See #13789 for the addition to the documentation.
