### ISSUE TITLE
Syntax for `simpl` is inadequately documented

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#13803]
#### Description of the problem

The doc for `simpl` at https://coq.github.io/doc/master/refman/proofs/writing-proofs/rewriting.html?highlight=cbn#coq:tacn.cbn does not list `simpl in *` nor `simpl in |- *`.   I think `simpl` (and the reduction tactics more generally) take `goal_occurences`? cc @coq/doc-maintainers 

#### Coq Version

8.14+alpha

**Comment by jfehrle** [comment]
Yes, it is incomplete.  We're in the midst of revising the remainder of that chapter, which should be merged in a week or two.  Feel free to take a look at #13707, which has updated syntax for all the tactics in that chapter.  The correct syntax is:

`simpl {? @delta_flag } {? {| @reference_occs | @pattern_occs } } {? @occurrences }`
