### ISSUE TITLE
[LTac2] int div / mod

### ISSUE THREAD

**Issue by KyleDavidE** [coq/coq#13802]
#### Description of the problem

There are no division or modulo functions defined in `Ltac2.Int`, this is especially odd since the `Division_by_zero` exception is declared.

#### Coq Version

version 8.12.2, but from documentation this is clearly still an issue in 8.13

**Comment by samuelgruetter** [comment]
Here's one more user who was disappointed by not having integer division (nor bit shifts).
I guess the reason to not add it in a first pass was to avoid making a decision as to whether division should be truncating, flooring, or Euclidean?

**Comment by ppedrot** [comment]
I don't think so, just laziness from myself. We can inherit the same behaviour as the OCaml division, in any case, since that's going to be the easiest one to implement.

**Comment by ppedrot** [comment]
Fixed by #15637.
