### ISSUE TITLE
Warning on "-w -native-compiler-disabled -native-compiler ondemand"

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#13819]
Since -w was moved to the option injection system the warning is disabled after it was emitted.

**Comment by SkySkimmer** [comment]
This causes dune to spam warnings.

**Comment by Zimmi48** [comment]
Is there any solution beyond reverting the PR that did this change? Delaying the treatment of the `-native-compiler ondemand` after the one of options?

**Comment by ejgallego** [comment]
Maybe `-native-compiler ondemand` should not produce the warning in the first place?

**Comment by SkySkimmer** [comment]
>Maybe -native-compiler ondemand should not produce the warning in the first place?

That makes sense, if native isn't used in the file there's no problem and if it is then it will warn at the use point.

**Comment by SkySkimmer** [comment]
We would still get a warning for `on` though.
