### ISSUE TITLE
Include names of non-dependent arguments in `About` output?

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#13830]
#### Description of the problem

The new `Arguments` line in the output of `About` is one of my favorite improvements in new Coq versions (https://github.com/coq/coq/pull/10985).

One thing to make it even better would be to show the names of all arguments, even non-dependent ones.  Instead of this:

```
  Definition test' {A: Type} (a: A) := 1.
  About test'.
  (* Arguments test' {A}%type_scope _ *)

```

that:

```
  Definition test' {A: Type} (a: A) := 1.
  About test'.
  (* Arguments test' {A}%type_scope a *)

```

The current setup means that it's still sometimes necessary to go to the function definition to see the most readable signature.

cc @SkySkimmer 

#### Coq Version

8.13

**Comment by Zimmi48** [comment]
cc also @herbelin because this is related to CEP #49 and PR #11099.

**Comment by SkySkimmer** [comment]
Can those names be used for anything? For instance if I do `Check test' (a:=1)` Coq says there's no `a` argument.
IMO if they can't be used it would be misleading to print them.

**Comment by cpitclaudel** [comment]
They can be used in the `Arguments` command when setting implicit status and scopes, and Coq complains if one puts the wrong names without a `rename` flag.

```
Definition test {A: Type} (a: A) := 1.
Arguments test [A] b.
```
```
Error: Flag "rename" expected to rename a into b.
```

AFAICT the `(a := _)` syntax only works for implicit arguments, so it wouldn't be misleading: a plain `a` can't be used in `(a := _)` because it's not implicit.

**Comment by cpitclaudel** [comment]
I'm mostly arguing for this improvement because, besides printing the definition, there currently isn't a Coq command to show the names of non-dependent arguments of a Coq function or lemma.  Consider this:

```coq
substring : nat -> nat -> string -> string

substring is not universe polymorphic
Arguments substring (_ _)%nat_scope _%string_scope
substring is transparent
Expands to: Constant Coq.Strings.String.substring
```

How am I supposed to figure out which arguments `substring` takes?   
(FWIW, I wish Coq wouldn't use the `→` notation so eagerly and wouldn't rename variables when they are unused. `substring : forall (n m : nat) (s : string), string` would be infinitely more useful than `substring : nat -> nat -> string -> string`; I don't think it's a techincal issue, because internally the names are kept — they're even used when destructing for constructors).

Arguably I could print the term, but that only works if there are no implicit arguments, because printing a term loses implicit annotations:

```
array_index_nat_inbounds :
forall (width : Z) (word : Interface.word width),
word.ok word ->
forall (value : Type) (mem : map.map word value),
map.ok mem ->
forall (T : Type) (element : word -> T -> mem -> Prop) (size : word) 
  (default : T) (xs : list T) (start : word) (n : nat),
(n < Datatypes.length xs)%nat ->
Lift1Prop.iff1 (array element size start xs)
  (array element size start (List.firstn n xs) *
   (element (word.add start (word.of_Z (word.unsigned size * Z.of_nat n)))
      (List.hd default (List.skipn n xs)) *
    array element size
      (word.add (word.add start (word.of_Z (word.unsigned size * Z.of_nat n))) size)
      (List.skipn (S n) xs)))%sep

array_index_nat_inbounds is not universe polymorphic
Arguments array_index_nat_inbounds {width}%Z_scope {word word_ok} {value}%type_scope {mem
  mem_ok} {T}%type_scope _%function_scope _ {default} _%list_scope _ _%nat_scope
array_index_nat_inbounds is opaque
```

It takes me 30 seconds every time I use that lemma to figure out which arguments I need to pass, because I need to match the `Arguments` line against the type to figure out which ones are implicit.

**Comment by Zimmi48** [comment]
> Can those names be used for anything? For instance if I do `Check test' (a:=1)` Coq says there's no `a` argument.
> IMO if they can't be used it would be misleading to print them.

My point about linking to Hugo's CEP is precisely because this is what the CEP would allow.

Furthermore, while the `(a := _)` syntax is only for implicit arguments for now, the `with (a := _)` syntax of many tactics is not.

**Comment by cpitclaudel** [comment]
> Furthermore, while the (a := _) syntax is only for implicit arguments for now, the with (a := _) syntax of many tactics is not.

Ah, excellent point!

```coq
    About Nat.add_comm.
    (* Arguments Nat.add_comm (_ _)%nat_scope *)

    Goal 1 + 2 = 2 + 1.
      apply Nat.add_comm with (n := 1).
```

**Comment by herbelin** [comment]
Yes, in anticipation of coq/ceps#49 and of the `with` of `apply`, I'm supporting the wish (even if the `with` of `apply` has its own problems, like being sensitive to the names in the current context, but that's also something to change).

> `substring : forall (n m : nat) (s : string), string` would be infinitely more useful than `substring : nat -> nat -> string -> string`

Interesting remark. That would deserve collecting more opinions. Then, if decided, it would be easy to change.

**Comment by herbelin** [comment]
Wish granted in #14596.

**Comment by cpitclaudel** [comment]
Woohoo, thank Hugo!
