### ISSUE TITLE
vm_compute no longer reduces in presence of unified evars

### ISSUE THREAD

**Issue by silene** [coq/coq#13841]
Consider the following testcase:
```coq
Goal True.
evar (p : bool).
unify ?p true.
assert (orb p false = true).
vm_compute.
match goal with |- true = _ => idtac end.
(* Error: No matching clause for match. *)
```

Indeed, `vm_compute`  refuses to reduce `match` and `fix` involving this value, thus leaving the goal as `(if true then true else false) = true`.

All the other reduction engines (`lazy`, `cbv`, `native_compute`) properly reduce the goal to `true = true`.

Tactic `eval vm_compute` does not work any better, but strangely enough, `Eval vm_compute` does succeed.

This is a regression. It was introduced at some point between 8.9.1 and 8.11.1.

Note that 8.9.1 has some other bugs of its own:
```coq
Require Import List.
Goal True.
evar (l : list nat).
assert (List.length l = 0).
vm_compute.
apply eq_refl. (* Success?! *)
```

But due to the former bug, I do not know if the later one still exists.

**Comment by silene** [comment]
The culprit is 6b61b63bb8626827708024cbea1312a703a54124: "Remove and deprecate `nf_enter` et al."

It seems like "normalization" was not so "unnecessary" after all.

**Comment by silene** [comment]
In `plugins/ltac/tacinterp.ml`, changing
```ocaml
  (* Conversion *)
  | TacReduce (r,cl) ->
      Proofview.Goal.enter begin fun gl ->
```
into
```ocaml
  (* Conversion *)
  | TacReduce (r,cl) ->
      Proofview.Goal.nf_enter begin fun gl ->
```
fixes the bug.

**Comment by gares** [comment]
Nice catch, but I'm a bit worried taking this in a point release. IMO it is 8.14 material

**Comment by silene** [comment]
I was not suggesting that as a fix. It was just to point out that the main invariant of the proof engine (evars are normalized) is completely broken.

**Comment by ejgallego** [comment]
We actually had some issues with `TacReduce` which were handled in a prior PR to the nf_switch I believe, I wonder what is going on.

**Comment by gares** [comment]
>  invariant of the proof engine (evars are normalized) is completely broken.

When `EConstr.t` the invariant was turned from holding upfront to lazily enforced by the API.
So there must be some code using EConstr "unsafe" API down the road.

**Comment by ejgallego** [comment]
The problem is that `p` is a regular "named" var, and the normalization in `Vmconv.cbv_vm` doesn't normalize the goal env.

**Comment by silene** [comment]
> the normalization in `Vmconv.cbv_vm` doesn't normalize the goal env.

I am not sure to understand. What does `Vmconv.cbv_vm` do wrong that `Nativenorm.native_norm` does right? Should `Vmconv.cbv_vm` have called `EConstr.Unsafe.to_constr` like `Nativenorm.native_norm`?

**Comment by ejgallego** [comment]
I think native is actually applying the substitution of the local named variable `p` in the goal, but I'm not expert in this code:
```
  | Var id ->
    let open Context.Named.Declaration in
    begin match lookup_named id env with
      | LocalDef (_,t,_) ->
        aux env lvl init t
      | _ -> init
    end
```

**Comment by ejgallego** [comment]
With `nf_enter`:
```
env: 
     p := true : bool
```
without:
```
env: 
     p := ?X2 : bool
```

**Comment by ejgallego** [comment]
The way things are handled seem quite messy so I'm unsure what would be the right fix.

**Comment by silene** [comment]
If I understand correctly, the `native_compute` code calls `Evd.existential_opt_value0` when it encounters an evar, while the `vm_compute` naively assumes it is an actual evar. Making `vm_compute` calls `Evd.existential_opt_value0` fixes the issue.

**Comment by ejgallego** [comment]
> Making `vm_compute` calls `Evd.existential_opt_value0` fixes the issue.

Either that or either apply the evar-normalization to the goal context again.

**Comment by ejgallego** [comment]
[Before it was done by the call to `Evarutil.nf_evar_info` , which would normalize the named_context]

**Comment by silene** [comment]
> apply the evar-normalization to the goal context again.

I have come to the same conclusion. While I had originally used `nf_enter` to pinpoint the bug, it seems like this was in fact the correct solution. Indeed, calling `Evd.existential_opt_value0` is just way too ugly, since it introduces a circular dependency between the kernel and `Evd`. Sure, this can be solved by passing `Evd.existential_opt_value0` as an argument of every single function, as `native_compute` does, but that is just a hack. The kernel should not have to deal with this mess; when it is fed an evar, this should be an evar, not something else.

**Comment by ppedrot** [comment]
Eagerly reducing a goal is very expensive. I'd rather go for the higher-order API passing the expansion function. We already do that for kernel CClousre reduction.
