### ISSUE TITLE
Feature request: dfs flag for the `typeclasses eauto` tactic

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#13859]
#### Description of the problem

AFAICT there is no way to locally undo a global `Typeclasses eauto := (bfs)`: while one can write `typeclasses eauto bfs with xyz` to override the global default `dfs`, there no corresponding `typeclasses eauto dfs with xyz` to override a global `bfs` flag.

#### Coq Version

8.13

**Comment by Zimmi48** [comment]
This sounds good and should be relatively easy to implement. Feel free to go ahead and do it and ask for guidance if needed.

Note that we would like to eventually provide many more knobs to parameterize this tactic and I think we would benefit from relying on the attribute syntax to avoid the issue of the ordering or the combinatorial blow-up of many clauses. But for this particular one, there is already the `dfs` clause which is easy to extend to also accept `bfs`.

**Comment by cpitclaudel** [comment]
Thanks!  I don't expect I'll have time to get to it soon, so I hope someone beats me to it :)
