### ISSUE TITLE
Build coq-stdlib with coq_makefile

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#13888]
Hi all, this is an issue that summarizes a bit the discussion for having `coq-stdlib` built by `coq_makefile`as a regular package.

This should happen once we merge #12567 and #13617 , tho work is possible to start even today.

Doing this would reduce what basically is a duplication of the whole makefile code between the Coq build system and coq_makefile, and this way we would only have to maintain one.

Dune already builds the standard library almost as a regular package, so this work well, there are only a couple of modifications needed:

- `coqc` has to be called with the `-boot -noinit` for files in `theories/Init`
- an implicit dependency on `Init/Prelude.vo` has to be added.
- the install path has to be overridden, so files go to `theories` instead of `user-contrib`
- coq_makefile needs to gain the ability to place object files out of tree [generally useful]
- in order for the composed build of `coq-core` and `coq-stdlib` to work well, the bridge implemented in #13617 should be included in the `.local` Makefile too, a dependency on the binaries could be added too,
- optional, but very recommended, coq_makefile could use `ocamlfind` to find Coq libraries and paths.

I believe this is doable 100% using the local makefile file, but I need help from Coq makefile experts.

**Comment by ejgallego** [comment]
Seems there is no interest on this, closing.

**Comment by Alizter** [comment]
@ejgallego I wouldn't say that there is no interest in splitting the package further, but doing it with makefile probably won't happen.

**Comment by ejgallego** [comment]
> @ejgallego I wouldn't say that there is no interest in splitting the package further, but doing it with makefile probably won't happen.

Indeed maybe there is interest in stdlib refinements, however how is that related to this issue?

**Comment by Alizter** [comment]
Never mind, I think I got confused with the other stdlib package discussion.
