### ISSUE TITLE
Anomaly when using #[using=...]

### ISSUE THREAD

**Issue by CohenCyril** [coq/coq#13903]
#### Description of the problem

The following code snippet raises an anomaly.
```coq
Section test.
Variables (T : Type) (x : T).
#[using="x"] Definition test : unit := tt.
```
results in 
```
Error:
Anomaly
"File "kernel/term_typing.ml", line 274, characters 15-21: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

I spotted this while trying to fix an issue in https://github.com/math-comp/hierarchy-builder/pull/181 and was noticing the anomaly through the coq-elpi API. It turns out the problem is on the Coq side.

CC @gares 

#### Coq Version

Coq 8.13.0 and 8.13.1

**Comment by CohenCyril** [comment]
On the other hand if I pass `"T x"` then it works.

**Comment by CohenCyril** [comment]
Moreover it's not completely stable in its way of failing, eg. in the following `test1` succeeds but `test2` raises an anomaly.
```coq
Section test.
Variables (T : Type) (x y : T).
#[using="x"] Definition test1 : T := y. (* succeeds *)
#[using="x"] Definition test2 := y. (* anomaly *)
```

**Comment by gares** [comment]
It should be an error, you are right. It used to be a nice error at Qed time...

**Comment by CohenCyril** [comment]
Should there be a transitive closure option, like `#[using="x*"]` ... but it does not work.

**Comment by CohenCyril** [comment]
Actually, I thought the closure was automatic, as in:
```
Definition test3 : bool. Proof using x y f. exact (f y). Defined. (* succeeds !*)
#[using="x y f"] Definition test4 : bool := (f y). (* anomaly! *)
```

**Comment by gares** [comment]
It is clearly a bug

**Comment by SkySkimmer** [comment]
Basically the comment at https://github.com/coq/coq/blob/a40631f9fbcd0ef8c1a716010be48e3f650e8955/kernel/term_typing.ml#L273 is not actually true.
