### ISSUE TITLE
Autocompletion CoqIDE doesn't work since 8.11

### ISSUE THREAD

**Issue by amelieled** [coq/coq#13904]
The autocompletion menu disappears from Coq version 8.11.
Currently, if I run `opam pin add coq 8.10.0` then `coqide &`, I can see the autocompletion menu.
This menu disappears after running `opam pin add coq 8.11.0`

I'm on Debian but I think there is the same problem on Mac.

**Comment by herbelin** [comment]
Do you mean the auto-completion box in the Editor tab of the customization window obtained in menu Edit-Preferences?

From 8.11, it comes with an auxiliary box asking for auto-completion delay but it is still present for me, as shown in the following image:
<img width="793" alt="coqide-pref-autocompletion" src="https://user-images.githubusercontent.com/460771/110252695-f2c0d100-7f86-11eb-936b-ed25b400d05d.png">

How does it look for you?

**Comment by ppedrot** [comment]
No answer and I cannot reproduce. Let's close.
