### ISSUE TITLE
Is the type cast :> worth keeping?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13908]
While discussing #13707, others observed

> it looks like a feature that is too intricate and of limited use, that we could propose for removal instead of documenting it

and

> So `x :>` means `proj1_sig x` in Program mode when `x` is of type `sig _` (i.e., `x : { n : _ | _ }`) (technically, of a type that is unifiable with whatever is registered as `core.sig.type`), and in all other cases `x :>` is just `x`.

> Unlike the other cast nodes, it seems that `:>` does not persist past pretyping, i.e., does not show up as a cast node in the term the kernel sees.  (It in fact seems a bit unfortunate for the rest of the code to have to deal with `CastCoerce` when it seems like in fact there's no reason for it to be valid in the syntax layers post-pretyping.)  (I might be missing something, though.)

See the discussion at and above https://github.com/coq/coq/pull/13707#issuecomment-792012857

Should we keep this or maybe remove it?

**Comment by Zimmi48** [comment]
We should open a draft PR to test the impact of removing this syntax.

**Comment by JasonGross** [comment]
cc @mattam82 ? (Was the syntax your addition originally?)
