### ISSUE TITLE
Mutex deadlock when timeout SIGALRM signals fire.

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#13949]
#### Description of the problem

Steps to reproduce:
```
Ltac loop t := case t; loop t.
Lemma test (P : Prop) (b : bool) : P.
do 1000 ((timeout 1 loop b) || idtac "hi").
Qed.
```
Run this in `coqc` on master. After 5 to 10 minutes the `coqc` process will enter a Sleeping state and never exit. Tail of the `strace` log:
```
getitimer(ITIMER_REAL, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}) = 0
setitimer(ITIMER_REAL, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}) = 0
rt_sigaction(SIGALRM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fdea5efc960}, {sa_handler=0x55be595567b0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fdea5efc960}, 8) = 0
write(1, "hi\n", 3hi
)                     = 3
getitimer(ITIMER_REAL, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}) = 0
rt_sigaction(SIGALRM, {sa_handler=0x55be595567b0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fdea5efc960}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fdea5efc960}, 8) = 0
setitimer(ITIMER_REAL, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=1, tv_usec=0}}, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}) = 0
futex(0x55be5b56d450, FUTEX_WAIT_PRIVATE, 2, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
futex(0x55be5b56d450, FUTEX_WAIT_PRIVATE, 2, NULL
```
From the logs, it is clear that multiple threads are waiting on the same mutex. We have confirmed that this is a logic error in Coq by testing it on @ejgallego's simple_compiler branch: https://github.com/ejgallego/coq/commits/simple_compiler. The problem can be reproduced in commit https://github.com/ejgallego/coq/commit/2e0b53c5481534251651e6ef84a78043381fbd75, but dissapears in commit https://github.com/ejgallego/coq/commit/b155c69ee4781986979a8ec3f70bf05d6873343c where all usages of the Thread library have been removed.

The code that looks most suspicous to me are the mutexes in `exinfo.ml`.

See also the discussion here: https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Deadlock.20in.20OCaml.20runtime

**Comment by ppedrot** [comment]
> We have confirmed that this is a logic error

It could well be a logic error in OCaml itself. The fact that not linking Thread removes the bug doesn't mean that the problem lies in the Coq implementation. The Thread library notably tweaks the OCaml runtime...

**Comment by ejgallego** [comment]
> It could well be a logic error in OCaml itself. The fact that not linking Thread removes the bug doesn't mean that the problem lies in the Coq implementation. The Thread library notably tweaks the OCaml runtime...

I'd say try with `master` and remove the thread code in exninfo and see if the problem goes away. The code in exninfo is for sure suspicious so I wouldn't be surprised it is the culprit.

**Comment by ppedrot** [comment]
Shouldn't we just wrap the critical section in a try-with clause? IIUC, this could deadlock if an asynchronous exception is raised, which would be a typical situation triggered by a timeout...

**Comment by ejgallego** [comment]
> Shouldn't we just wrap the critical section in a try-with clause? IIUC, this could deadlock if an asynchronous exception is raised, which would be a typical situation triggered by a timeout...

Indeed that looks like a race, speaking from my ignorance of OCaml signal + exception handling which is quite tricky IIUC, it wouldn't hurt to get help from GMM or JHH.

But yes the situation:
```
Mutex.lock ...;
update_exn_table ...;
  {alarm raise}
Mutex.unlock ...
```
seems very possible as the update_table may trigger a patch that checks for pending in the OCaml runtime.

**Comment by ejgallego** [comment]
After a bit more thinking, I've come to the conclusion that we can only implement `exninfo` properly in C , but I may be wrong.

**Comment by ppedrot** [comment]
Currently, allocation-free code in OCaml shouldn't trigger asynchronous exceptions, and there will be a dedicated API for OCaml multicore, or so I heard. I really believe that you can implement this by careful exception wrapping.

**Comment by gadmm** [comment]
> there will be a dedicated API for OCaml multicore, or so I heard

What are you referring to?

> I really believe that you can implement this by careful exception wrapping.

I think so (although not officially supported).
