### ISSUE TITLE
Improve the error message for version mismatches

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#13943]
#### Description of the problem

The current message for version mismatches isn't very user-friendly:

```
Error: File ….vo has bad
magic number 1131376929 (expected 81000). It is corrupted or was compiled with another
version of Coq.
```

It would be a lot nicer to get the following:

```
Error: Trying to import module Xyz from …/Xyz.vo, but Xyz.vo was compiled with Coq snapshot 1131376929.  You are running Coq version 8.10.2; please recompile …/Xyz.v.
Alternatively, Xyz.vo might be corrupted.
```

Even without fancy nice-to-read version numbers, just clarifying which number is the current version and which number is the file's version would help. 

#### Coq Version

8.13

**Comment by Zimmi48** [comment]
Follow up of #12677 which came up with the current form of this error message.

**Comment by ppedrot** [comment]
This is a temporary situation. When you'll be running two different 8.13+ versions of Coq you should get a proper error. The current magic number is here to stay.

**Comment by ppedrot** [comment]
Hm, actually no. I had a look at the code and it's the same message. I am a bit confused because I am fairly sure I tweaked it to make it more readable at some point...

**Comment by ppedrot** [comment]
I believe that this is fixed on recent Coq versions.
