### ISSUE TITLE
When matching on closure, `_` does not match pattern argument

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#13959]
#### Description of the problem

When I match a term with the pattern `fun _ x => _`, I would expect it to match on all 2-argument closures and bind to whatever the name of the second argument is. However, if the closue is defined using a `'` pattern on the *first* argument, the match fails:
```
Lemma test : (fun '(x,y) z => z) = (fun (x:nat*nat) (z:nat) => z).
Proof.
  match goal with
  | |- ?pred = _ =>
    match pred with
    | fun _ x => _ => idtac
    | fun '(_,_) x => _ => fail (* changing this to idtac makes the script succeed *)
    end
  end.
```
This is a problem; how do I now write an ltac script that extracts the name of the second argument of the closure, no matter how it is defined? I am okay with assuming that the *second* argument is not a pattern argument (so we can assume that it has a well-defined name), but it should not matter how the *first* argument is defined.

#### Coq Version

8.13.0

**Comment by SkySkimmer** [comment]
`'` means it's a `fun x => match x`, not just a `fun`.

**Comment by RalfJung** [comment]
Hm... yeah that would explain the behavior, but it is somewhat unfortunate for writing this kind of automation. In this case it's not critical, we could fall back to using just `fresh` without trying to match the name of the closure, but in general this could become tricky.

**Comment by silene** [comment]
Closing, since it is working as expected.
