### ISSUE TITLE
Non-linearity of variables and notation scopes

### ISSUE THREAD

**Issue by gares** [coq/coq#13957]
```coq
Welcome to Coq 8.13.0 (February 2021)

Coq < Arguments conj {_ _} _ _%function.

Coq < Notation pp X := (conj X X).
Toplevel input, characters 23-24:
> Notation pp X := (conj X X).
>                        ^
Error: X is here used in the empty scope stack while it was elsewhere used in
scope function_scope
```

This is an oversimplified example, the real case is when I synthesize the RHS of the notation in coq-elpi and uses constants whose notation scopes were inferred automatically, so it is hard for me to predict it. Actually the notation passes the input X to two constants, one of which is has an argument of function type (hence the %function) while the other one is fully polymorphic (hence the absence of scope).

Is there a way to silence this error?

CC https://github.com/math-comp/hierarchy-builder/pull/179 @coq/extensible-syntax-maintainers

**Comment by jashug** [comment]
You can use `Notation pp X := (conj X%function X).` which makes both uses of `X` have the same scopes. The issue is what notations should be usable when parsing X. If you wanted the opposite choice, you could probably use a pair of arguments commands to unset and reset the scopes of conj around the notation.

**Comment by gares** [comment]
I would say the when conflicting scopes are found we should picking no one by default, and warn.
And let one put a scope around the argument to set it, as in `Notation pp X%function := (t X X)`, which would also silence the warning.

**Comment by gares** [comment]
I'll look into drafting a PR for my proposal, let's see how it goes.

**Comment by JasonGross** [comment]
As another workaround, if you want your notation to be only parsing, you can also do `Notation pp X := match X with Y => conj Y Y end.` or `Notation pp X := (match conj with C => C end X X).`
