### ISSUE TITLE
Lazy (short-circuiting) boolean operators for Ltac2

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#13964]
In https://github.com/coq/coq/pull/11765 @MSoegtropIMC wanted to add if-then-else and lazy boolean operators, but the PR was closed in favor of https://github.com/coq/coq/pull/13232, and it seems that the lazy boolean operators part was not pursued further.

It would be nice to be able to write `if a || b then ... else ...` and have `b` evaluated only if `a` is false, and similarly for `&&`.

Coq version: 8.13.0

**Comment by MSoegtropIMC** [comment]
I can add this separately.
