### ISSUE TITLE
Ltac2 should have `is_const`, `is_var`, etc tactics returning `bool`

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#13963]
I'd like to use the `is_const`, `is_var`, `is_evar` etc tactics in Ltac2.
I could implement them like this:

```coq
Ltac2 is_const(c: constr) :=
  match Constr.Unsafe.kind c with
  | Constr.Unsafe.Constant _ _ => true
  | _ => false
  end.
```

or like this

```coq
Ltac2 is_const(c: constr) :=
  Control.plus (fun _ => let _ := ltac1:(c |- is_const c) (Ltac1.of_constr c) in true) (fun _ => false).
```

but it would be better if they were in Ltac2's standard library.

Coq version: 8.13.0

**Comment by JasonGross** [comment]
I expect @ppedrot would accept a PR adding them to the standard library and implementing them via `Constr.Unsafe.kind`.
