### ISSUE TITLE
Notations prevent referencing hint databases

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#13975]
#### Version

Coq 8.12.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following attempt to reference hint database
with a name that looks like a notation fails unexpectedly.

```
Module Success.
Section Context.

Corollary id_equation_1 {A : Type} (x : A) : id x = x.
Proof. reflexivity. Qed.

Hint Rewrite @id_equation_1 : id.

Print Rewrite HintDb id.

Notation "'id'" := Datatypes.id : core_scope.

End Context.
End Success.

Module Failure.
Section Context.

Corollary id_equation_1 {A : Type} (x : A) : id x = x.
Proof. reflexivity. Qed.

Notation "'id'" := Datatypes.id : core_scope.

Hint Rewrite @id_equation_1 : id.

Print Rewrite HintDb id.

End Context.
End Failure.
```

```
Syntax error: '.' expected after [vernac:command] (in [vernac_aux]).
Syntax error: [prim:preident] expected after 'HintDb' (in [vernac:command]).
```

#### Notes

Changing `id` into `Datatypes.id` does not help,
because qualified names are not identifiers.

**Comment by ppedrot** [comment]
Yes, this is not very surprising. This report reminds me that we should have made hint databases use qualified names a long time ago...

**Comment by Zimmi48** [comment]
>This report reminds me that we should have made hint databases use qualified names a long time ago...

Everyone wants this, but what is the design and the transition plan exactly? And what does a qualified name mean for a hint database? Is the qualifier the name of the module the hint database is created in? And do you need to import this module to be able to extend this database? Is it related to the [namespace CEP](https://github.com/coq/ceps/pull/25)?

**Comment by ppedrot** [comment]
I am currently writing a PR that merely outputs a warning when implicitly declaring databases, and even that is non-trivial. I am quite afraid of what we're going to face when trying to get well-scoped databases...

**Comment by Tuplanolla** [comment]
As far as I know,
it is not even possible to create rewrite hint databases explicitly.
Should this be another issue?

```
(** Can explicitly create and print hint databases. *)

Create HintDb hdb.
Print HintDb hdb.

(** Cannot explicitly create or print nonexistent rewrite hint databases. *)

Fail Create Rewrite HintDb rhdb.
Fail Print Rewrite HintDb rhdb.

(** Cannot remove hints from implicitly created rewrite hint databases. *)

Hint Rewrite @eq_refl : rhdb.
Print Rewrite HintDb rhdb.
Remove Hints eq_refl : rhdb.
Print Rewrite HintDb rhdb.
```

```
Discriminated database
Unfoldable variable definitions: all
Unfoldable constant definitions: all
Cut: emp
For any goal ->

The command has indeed failed with message:
Syntax error: illegal begin of vernac.
The command has indeed failed with message:
Rewriting base rhdb does not exist.

Database rhdb
rewrite -> @eq_refl of type forall (A : Type) (x : A), x = x
Database rhdb
rewrite -> @eq_refl of type forall (A : Type) (x : A), x = x
```

**Comment by ppedrot** [comment]
Autorewrite is severly undermaintained and underimplemented. Do not hesitate to open an issue, even though it would probably be simpler to rewrite it from scratch.

**Comment by Tuplanolla** [comment]
Considering how the inbuilt reduction mechanisms are unreliable
(as seen in #4555, #7389, #13428, #13800, #13896) and
the reduction mechanism provided by the Equations plugin relies heavily on `autorewrite`
(as explained in its reference manual),
the situation is less than stellar from a user's perspective.

**Comment by SkySkimmer** [comment]
`Notation "'id'"` makes `id` a keyword and so it can't be used for identifiers any more. Maybe you want `Notation id` instead.
