### ISSUE TITLE
Ltac2 array literals?

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#13976]
The [manual](https://coq.inria.fr/refman/proof-engine/ltac2.html#term-syntax) says

> There is dedicated syntax for list and array literals.

And for printing, this seems indeed to be the case:

```coq
Require Import Ltac2.Ltac2.

Ltac2 Eval Array.of_list [ 3; 4; 5 ].
```
prints
```
- : int array = [| 3; 4; 5 |]
```

But for parsing, array literals don't seem to be supported:

```coq
Ltac2 Eval [| 1; 2; 3 |].
```

returns

```
Error: Syntax error: [ltac2_expr level 5] expected after '[' (in [ltac2_expr]).
```

What's cool though is that Ltac2's Notations are powerful enough to define this notation in Ltac2 itself (as long as one doesn't backtrack in the IDE and run into https://github.com/coq/coq/issues/12575...):

```coq
Ltac2 Notation "[|" l(list0(tactic(5), ";")) "|]" := Array.of_list l.

Ltac2 Eval [| 1; 2; 3 |].
```
prints
```
- : int array = [| 1; 2; 3 |]
```

But I guess this will call `Array.of_list` at runtime, and it would be better to make it a builtin feature that directly creates an Array literal?

Coq version: master (fcfeb5bc45febe1a05f44a0a77b43be6b6905f35)

**Comment by ppedrot** [comment]
The manual is wrong indeed. The main reason why I have not added this notation yet is that it clashes with other built-in notations like `tac > [| |]`. This means we have to pick another delimiter for array literals, which in turn is probably going to wreak token havoc somewhere else.

> But I guess this will call Array.of_list at runtime, and it would be better to make it a builtin feature that directly creates an Array literal?

I wouldn't worry about that (yet). Ltac2 is a glue language, so performance of this kind of primitives is not really at stake here. Unification and friends are orders of magnitude slower.

**Comment by samuelgruetter** [comment]
> it clashes with other built-in notations like `tac > [| |]`

Aah I see... But given that this notation is not the same as in Ltac1 anyways, I guess we could deviate even more? For instance, how about requiring users to write `tac > [ () | mytac () | () ]` instead of `tac > [| mytac () |]`? It always felt weird to me to that Ltac1 identifies "empty string" with "idtac" in some cases.

**Comment by ppedrot** [comment]
This wouldn't help because it's a tokenization issue, I believe. Last time I tried, adding the Ltac2 notation was breaking Ltac1 syntax, IIRC. I can try again to see if this vague recollection is correct.

**Comment by samuelgruetter** [comment]
Indeed, if I don't put the array notation inside a module, it breaks Ltac1 notation, but it seems that if the array notation is in an un-imported module, it's fine:

```coq
Require Import Ltac2.Ltac2.

Set Default Proof Mode "Classic".

Goal False /\ True /\ False.
Proof.
  (split; [|split]); [| constructor |].
Abort.

Module ArrayNotation.
  Ltac2 Notation "[|" l(list0(tactic(5), ";")) "|]" := Array.of_list l.
End ArrayNotation.

Goal False /\ True /\ False.
Proof.
  (split; [|split]); [| constructor |].
Abort.

Module UsingArrayNotation.
  Import ArrayNotation.
  Ltac2 Eval [| 1; 2; 3 |].
End UsingArrayNotation.
```

So maybe we could add the array notation to `Ltac2.Ltac2` by default, and provide an `Ltac2.Ltac2WithoutArrayNotation` to be used in those files that contain Ltac1 `...; [| ... |]` syntax?

**Comment by ppedrot** [comment]
I'd rather use the standard hack to ensure that we tokenize `[|` and `|]` as two tokens without a space for Ltac2 array literals. This would provide backwards compat and global Ltac2 notations at the same time.

**Comment by samuelgruetter** [comment]
That sounds great, I wasn't aware that there's a standard hack to achieve this!
