### ISSUE TITLE
Partial reduction (small-step evaluation?) of Coq terms

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#13983]
I keep running into this issue: Coq doesn't have a way to partially reduce a term: `simpl`, `cbn`, `cbv`, `vm_compute`, etc. all reduce as much as they can. (the first 3 are customizable, but not in a way that let's you reduce three levels on recursion on `plus` but no more).

Some contexts in which I need this feature:
- Teaching: I want to show my students that `2 + 2` → `1 + 3` → `0 + 4` → `4`. 
- Debugging: When my `interp` function returns `None` on a 500-nodes program AST, I have no way to know where things went wrong.
- Controlled reduction: I often want to unfold a just once, without having to prove an equation.
- VC generation: Sometimes for programming language semantics I use a Coq function to generate a strongest postcondition, and I want to mix steps of computation with steps of simplification to avoid exponential blow-up.
- Symbolic evaluation: (Basically the same as VC generation) I often write Coq functions to do symbolic evaluation on ASTs.  Being able to mix reduction with tactic evaluation would allow me to perform simplification while reducing.

This is just what I could think of in a few minutes; I'm sure other would have other uses for this feature.  I realize that there are issues around fixpoint refolding that make this nontrivial, and I also realize that this can to some extent be emulated using just `unfold`, but I'd be very interested in hearing opinions on feasibility.

I guess what I'd like is a sort of small-step interpreter?

**Comment by andres-erbsen** [comment]
See also #9039

**Comment by cpitclaudel** [comment]
Thanks @andres-erbsen, sorry for not finding this one.  Duplicate of #9039 then.
