### ISSUE TITLE
`Message.print` arbitrary Ltac2 values

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#13991]
It seems that `Ltac2 Eval` can print pretty much anything (unless it's of abstract type), and I've found this feature very useful.

However, I can't find a way to use this printing inside an Ltac2 function.
That is, I'd like to have a function `Message.of_any` taking any Ltac2 value and turning it into a printable message, so that I could uncomment that line below:

```coq
Require Import Ltac2.Ltac2.

Ltac2 foo () := List.map Env.path (Env.expand [@Datatypes; @nat]).

Ltac2 baz x := x.

Ltac2 bar () :=
  let v := foo () in
(*let _ := Message.print (Message.of_any v) in*)
  baz v.

Ltac2 Eval bar ().
```

**Comment by ppedrot** [comment]
You can't have a polymorphic printing function in ML. Best you can do is to use typeclasses to do compile-time dispatch, but that would be pretty heavy to reimplement in Ltac2.

**Comment by samuelgruetter** [comment]
Hmm I don't quite understand, what exactly prevents you from having

```coq
Ltac2 @ external print : 'a -> unit := "ltac2" "print_any".
```

and implementing it using the same printer that's already used for `Ltac2 Eval`?

**Comment by ppedrot** [comment]
You don't have the type information at runtime.

**Comment by samuelgruetter** [comment]
Aah I see. But could you make a `print` builtin primitive that's handled specially by the typechecker and only accepts values whose type is completely known statically?
I'm thinking of a typing rule like

```
Γ |- e : T       T contains no type variables
---------------------------------------------
Γ |- print e : unit
```

**Comment by ppedrot** [comment]
This is essentially a half-baked implementation of typeclasses, à la SML equality type...

**Comment by ppedrot** [comment]
Closing this as a WONTFIX.
