### ISSUE TITLE
print stacktrace for uncaught Ltac2 exceptions

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#13990]
Feature request: It would be nice to have a stack trace printed in case of uncaught Ltac2 exceptions.
Right now, only the value of the exception is printed, eg

```
Error: Uncaught Ltac2 exception: No_value
```
and the rest is left as an exercise for the user...

**Comment by ppedrot** [comment]
You just have to set the option `Ltac2 Backtrace`.

**Comment by samuelgruetter** [comment]
Awesome, thanks!
And it's even [documented](https://coq.inria.fr/refman/proof-engine/ltac2.html#debug). I guess the reason I didn't find it was that I was searching for "stack", "stack trace" and "stacktrace" rather than "backtrace".

**Comment by ppedrot** [comment]
Let's close then.
