### ISSUE TITLE
Ltac2: missing Ltac1.to_ident

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#13996]
#### Description of the problem

Ltac2 has some limited support for FFI with Ltac1, but there seems to be no way to turn an `Ltac2.Ltac1.t` into an `Ltac2.ident`. We have `to_constr` to turn such a dynamically typed Ltac1 value into an Ltac2 constr, but the equivalent for idents is missing. Would be good to have that added. :)

#### Coq Version

8.13.0

**Comment by RalfJung** [comment]
This is causing trouble in Iris because it prevents writing a `rename_by_string` tactic that takes an ident and a constr (of type `string`), and renames the given ident to the name determined by the constr: I'd like to pass the ident and the cosntr to Ltac2 and do everything there, but due to this limitation, that is not possible.

**Comment by RalfJung** [comment]
@ppedrot is there any particular reason that this is missing, or is it just an oversight?

**Comment by ppedrot** [comment]
No reason except that adding Ltac1 conversion functions is a bottomless pit. Every built-in notation creates new dynamic types, so if you wanted to manipulate those from Ltac2 you'd need the corresponding representation. I agree that ident are common enough to deserve such a function though.
