### ISSUE TITLE
"Tools/Coqtop arguments" gives "coqidetop died badly" and forces user to quit CoqIDE

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14000]
I see this in master.  8.13.0 is OK.

To reproduce:
- Select "Tools/Coqtop arguments" from the menu
- Make a trivial change such as adding an extra space, click "OK"

Result: "coqidetop died badly" dialog.  Selecting "Reset" immediately gives the same dialog, so the user is forced to quit CoqIDE.

**Comment by silene** [comment]
Reverting 470f5e063535f91ce0e95798d4aaadfefffb89e0 fixes the issue. @herbelin

**Comment by jfehrle** [comment]
Appears to have been fixed
