### ISSUE TITLE
Coqc cannot save `.vo` files containing primitive arrays obtained by `vm_compute`.

### ISSUE THREAD

**Issue by silene** [coq/coq#14006]
```coq
From Coq Require Import Int63 PArray.
Definition t : array nat := [| 1; 3; 2 | 4 |].
Definition vm_accu_set v := Eval vm_compute in t.[1 <- v].
```

```
File "./foo.v", line 3, characters 0-58:
Warning: Removed file ./foo.vo
Error: Anomaly "Uncaught exception Invalid_argument("output_value: abstract value (outside heap)")."
Please report at http://coq.inria.fr/bugs/.
```

Note that the computed array is correct, i.e., `vm_accu_set = fun v : nat => [| 1; v; 2 | 4 : nat |]`.

See also #14005.

**Comment by ppedrot** [comment]
This is a VM function, how does it happen that it is stored in the vo file?

**Comment by silene** [comment]
What do you mean "a VM function"? `vm_accu_set` is a perfectly fine Gallina term.

By the way, `vm_accu_set` does not even have to be saved. So, I am starting to wonder if it is not the rerooted array for `t` which Coq is unable to store on disk.

**Comment by ppedrot** [comment]
Barring dirty Obj-based hacks, OCaml shouldn't generate datatypes outside of the heap. So I suspect the VM is doing something wrong there, maybe allocating memory where it shouldn't. I'll try to get more info on the object being marshalled to see what happened.

**Comment by silene** [comment]
So, yes, forcing a rerooting of `t` by ending the file with
```coq
Eval vm_compute in t.[1].
```
is enough for Coq to successfully save the `.vo` file.

**Comment by ppedrot** [comment]
I am very confused. I thought that we never stored persistent arrays in vo files, since constr relies on a simple array representation. Do we happen to store persistent arrays in structured constants from the VM? I don't see otherwise where the datatypes we marshal may contain such data. (FTR, marshalling fails on the library segment, so it's not very informative.)

**Comment by ppedrot** [comment]
I suspect this snippet from Vmlambda is completely wrong:
```
let makearray args def =
  try
    let p = Array.map get_value args in
    Lval (val_of_parray @@ Parray.unsafe_of_array p (get_value def))
  with Not_found ->
    let ar = Lmakeblock(0, args) in (* build the ocaml array *)
    let kind = Lmakeblock(0, [|ar; def|]) in (* Parray.Array *)
    Lmakeblock(0,[|kind|]) (* the reference *)
```
It behaves as if persistent arrays were stable under structural equality (as in Vmvalues.eq_structured_values), when it's clearly not the case since it internally uses mutable memory.

**Comment by ppedrot** [comment]
I confirm that unconditionally taking the `Not_found` branch solves this issue.

**Comment by silene** [comment]
I do not understand. The body of the `try` construct builds a fresh primitive array of literal constants, while the `Not_found` branch builds a fresh primitive array using the bytecode interpreter to evaluate the (non-)constant values. Why would the body be incorrect? Or are you saying that the fresh array is being reused several times? (and thus not so fresh anymore?). Still, that does not explain to me why this would cause Coq to fail at serializing the `.vo` file.

**Comment by ppedrot** [comment]
The VM assumes that structured constants are insensitive to their location, and factorizes two objects that have the same data representation. Persistent arrays are not factorizable this way. What I believe happens is that a persistent array is replaced by another value that looks the same, then we brutally mutate this object, leading to essentially what amounts to a SEGFAULT only caught at vo marshalling tim.

**Comment by silene** [comment]
What about the following scenario:
1. `t` first points at `Array [|1;3;2|]`;
2. evaluating `t.[1 <- v]` causes a reroot, so `t` now points at `Update (Array [|1;RelAccu;2|], 1, 3)`;
3. Serialization encounters `RelAccu` and crashes.

This does not involve any kind of factorization. That is why I am not yet convinced by your interpretation.

**Comment by ppedrot** [comment]
This is possible indeed. But again it would also be caused by the fact we are storing mutable data where it does not belong. Object files are supposed to only contain pure data. There are a handful of deviations from this, and they are causing trouble, even if only minor (as in e.g. #11229).

**Comment by silene** [comment]
I now understand what you mean about `eq_structured_values`, and I agree that sharing mutable structures seem like a recipe for disaster. That said, due to the semi-persistency of primitive arrays, I do not think the issue can be observed from the logic, only from a performance point of view. In other words, it is impossible to distinguish `t := [|foo|], t' := [|foo|]` from `t := [|foo|], t' := t`, except for the fact that accessing one will slow accesses to the other one.

**Comment by silene** [comment]
I think I now understand what is going wrong and why your patch fixes it. The issue is not with the value of `t`; it is with the bytecode of `t`! (Sorry if that is what you have been saying all along.)

The bytecode of `t` is just `CONST foo; STOP`. When evaluating `t.[1 <- v]`, the value of `t` gets rerooted, which is fine. But since this value is `foo`, the evaluation is actually modifying the bytecode (!) of `t` as a side effect. At this point, no one cares about the bytecode of `t`. (And it is still perfectly fine anyway, thanks to the referential transparency of semi-persistent arrays.) No one cares, except for the marshaller, which then has to traverse some bytecode that looks a bit too crazy for its taste, since it does not know what referential transparency means.

That explains why `native_compute` is not suffering from this issue. Indeed, the native code is marshalled in a completely different way, namely `ocamlopt` and `Dynlink`.
