### ISSUE TITLE
[test-suite] Performance tests are flaky and should be removed from the test-suite.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#14014]
The current "performance" tests we have in the test suite have many problems:
- they are intrinsically flaky, in both false positives and negatives,
- they break some valid uses such as coverage instrumentation for the test-suite
- moreover even when they don't behave in a flaky manner, they are mostly useless due to the wide range required

Performance testing cannot be understood from the "yes/no" test-suite framework, but instead the critical performance paths should be turned into micro or macro benchmarks and properly tested in the benchmark suite.

I propose we block the addition of new such tests, and instead redirect efforts to improving the bench suite.

**Comment by JasonGross** [comment]
> * they break some valid uses such as coverage instrumentation for the test-suite

Can you elaborate on this?



> into micro or macro benchmarks and properly tested in the benchmark suite.

Are you talking about https://github.com/coq-community/coq-performance-tests or something else?

**Comment by ejgallego** [comment]
> Can you elaborate on this?

Coverage instrumentation makes coq slower so test suite fails, see coverage PR for examples.

> Are you talking about https://github.com/coq-community/coq-performance-tests or something else?

Yup, that could be cool, tho I think we should integrate with Coq and run regularly so we can track performance regressions precisely instead with the current, mostly useless method.

**Comment by ejgallego** [comment]
So we could have the CI to launch the microbenchmarks for each PR and fail if some of them are up to some threshold compared to master, that should work fine as these set of "core perf benchs" should run maybe in 30 mins.

I'd suggest using some infrastructure such as core-bench instead of rewriting our own.

**Comment by SkySkimmer** [comment]
I guess those tests were removed.

**Comment by ejgallego** [comment]
> I guess those tests were removed.

I still see `test/suite-complexity` in place.

**Comment by ejgallego** [comment]
> I guess those tests were removed.

I still see `test/suite-complexity` in place.
