### ISSUE TITLE
coqdep should give an error on non-existing and unreadable files

### ISSUE THREAD

**Issue by hendriktews** [coq/coq#14023]
For non-existing and also for unreadable files `coqdep` prints nothing and exits with status 0, as if everything was fine.

**Comment by ejgallego** [comment]
This is a duplicate, and not so easy to solve, see the original reports for more information, but note that this was inherited from ocamldep which does the same.

**Comment by hendriktews** [comment]
Maybe the original report is #10156? But there I don't see, why it would be difficult to solve.

**Comment by ejgallego** [comment]
You are changing the semantics of `coqdep` and quite a few utilities do depend on it, so that's going to be tricky unless we are lucky. Thanks for locating the original bug report!

**Comment by ejgallego** [comment]
duplicate of #10156

**Comment by hendriktews** [comment]
I start to doubt whether this is really a duplicate of #10156. In #10156 the problem is that `coqdep` emits a warning when it encounters `Requre a.` and cannot find a suitable `a.v`. The problem here is not that coqdep emits a warning. The problem here is that `coqdep` is silent when a file on the command line is not present or unreadable.

**Comment by ejgallego** [comment]
@hendriktews for sure this is the same than https://github.com/ocaml/ocaml/issues/8625 , I don't recall the details of the other bug tho, so I need to re-read it.

**Comment by hendriktews** [comment]
If there is consensus in #14024 that this issue should be fixed, shouldn't this issue then get reopened?

**Comment by ejgallego** [comment]
Sure feel free to reopen if you think that's the right thing.

**Comment by hendriktews** [comment]
> Sure feel free to reopen if you think that's the right thing.

I would have done so, but I can't.

**Comment by ejgallego** [comment]
> I would have done so, but I can't.

Oh sorry, I had assumed you had the rights to do so, that should be fixed now (once you accept the invite)
