### ISSUE TITLE
Anomaly "Uncaught exception Constr.DestKO." in `Add Zify UnOp`

### ISSUE THREAD

**Issue by pi8027** [coq/coq#14043]
#### Description of the problem

```coq
From Coq Require Import ZifyClasses Zify ZifyInst ZifyBool Lia.

Instance Op_bool_inj : UnOp (inj : bool -> bool) :=
  { TUOp := id; TUOpInj := fun _ => eq_refl }.
Fail Add Zify UnOp Op_bool_inj.
(* Anomaly "Uncaught exception Constr.DestKO." Please report at http://coq.inria.fr/bugs/. *)
```

#### Coq Version

master (It works with 8.13)

**Comment by pi8027** [comment]
This issue also breaks the [mczify](https://github.com/math-comp/mczify) library. So I will add it to Coq's CI after this issue get fixed.

**Comment by ppedrot** [comment]
Probably a side-effect of #11907.

**Comment by fajb** [comment]
I'am just seeing this now. This is bad. I suggest reverting #11907 :(
It was made with the wrong assumption that operators were only references.

**Comment by pi8027** [comment]
Ah, `inj` is a primitive projection, hence not a reference! Why it is defined in this way?

**Comment by pi8027** [comment]
I declared the above `UnOp` instance just to reduce some `simpl`, IIRC. So if there is a reason that the current design is better than before, I'm fine to remove them.

**Comment by fajb** [comment]
@pi8027 I have mixed feelings. Your example shows that indexing over references is not so much a good idea.
In your case, you want a primitive projection but providing the identify function over `bool` would fail for the same reason.
Isn't restricting operators to references too strong of a requirement?

I see two options:
1. index over constr (most of them will be references) - this solves the issue
2. index over references (reject your operator and provide an error message instead of   `DestKO`). 

I lean slightly towards 1. but no strong opinion.
What do you think?

**Comment by ppedrot** [comment]
At the risk of repeating myself, constr equality is very badly defined, and will lead to surprising behaviours if used for indexing. The problem of projection-indexing is also well-known, there has been recent work on the topic for canonical projections IIRC.

**Comment by pi8027** [comment]
@fajb IMO, defining a type of indices that includes both references and projections (as in the following, but ignore the last 3 cases) is the best solution (this is probably what @ppedrot says): https://github.com/coq/coq/blob/b78e6cfcb412d1c4e5902fb895c5ecaa0cb177ac/pretyping/structures.mli#L82-L87

**Comment by fajb** [comment]
Ok, let not index on constr.
Still, I do not get  the case for projections.
Why do you need to `Add Unop` the projection of `Inj_bool_bool` ?

**Comment by pi8027** [comment]
@fajb Because it is useful to define more `UnOp` and `BinOp` instances using Micromega and the `ltac:(...)` syntax. For example, to provide a `BinOp` instance of
```coq
Definition leq (m n : nat) := Nat.eqb (m - n) 0.
```
in the form of
```coq
Instance Op_leq : BinOp leq := { TBOp := Z.leb; TBOpInj := ltac:(...) }.
```
the proof of `forall (n m : nat), inj (leq n m) = Z.leb (inj n) (inj m)` is required in the above `...`. This proof can be done by `unfold leq; lia` if `inj` instances are provided.

A self-contained example compatible with Coq 8.13.2 is as follows:
```coq
From Coq Require Import ZArith ZifyClasses ZifyInst ZifyBool Lia.

Instance Op_bool_inj : UnOp (inj : bool -> bool) :=
  { TUOp := (fun x => x); TUOpInj := fun _ => eq_refl }.
Add Zify UnOp Op_bool_inj.

Instance Op_nat_inj : UnOp (inj : nat -> Z) := Op_Z_of_nat.
Add Zify UnOp Op_nat_inj.

Definition leq (m n : nat) := Nat.eqb (m - n) 0.

Instance Op_leq : BinOp leq :=
  { TBOp := Z.leb; TBOpInj := ltac:(unfold leq; lia) }.
```

**Comment by fajb** [comment]
@pi8027  I see. For the time being, I propose a quick fix.
PS: Re-inventing a novel datatype for Projection | GlobRef looks like a lot of boilerplate...
