### ISSUE TITLE
Coq's language of Sorts is too limited

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14052]
When all sorts have a least upper bound, it's not too bad that we can't have sort expressions, but it seems there's no way to ask for an object whose type is of sort `if b then SProp else Set`
```coq
Set Allow StrictProp.
Inductive sTrue : SProp := sI.
Check fun (b : bool) (x : if b return (if b then SProp else Set) then sTrue else nat) => _.
(* Error: In environment
b : bool
The term "if b as b return (if b then SProp else Set) then sTrue else nat" has type "if b then SProp else Set"
which should be Set, Prop or Type.
*)
```
I'd like to be able to make these sort of sort-polymorphic-ish definitions.  If we're adding lots of new sorts, perhaps it makes sense to also add a cumulative hierarchy of `Sort`s which do not admit any inductive types, where we have `Type_i : Sort_0` for all `i` (and the key property of a sort is that if you have `T : Sort` then you can write `fun x : T => ...`)

**Comment by SkySkimmer** [comment]
You may not have a binder which depending on how you fill free variables (`b` in the example) becomes relevant or irrelevant.

(Unless you `Set Cumulative StrictProp`, in which case proof irrelevance will be under detected.)

There are no plans to change this.
