### ISSUE TITLE
Docs for Coq's API doesn't show up

### ISSUE THREAD

**Issue by ju-sh** [coq/coq#14055]
Some pages of coq docs at [https://coq.github.io/doc/master/api/coq/](https://coq.github.io/doc/master/api/coq/) is not showing up.

Of the following,

 - coq dev
 - coq-core
 - coq-doc
 - coq-stdlib
 - coqide
 - coqide-server

only the pages for coq-core and coqide-server are appearing.

I guess some html files got removed somehow.

The site is being served using the files from [https://github.com/coq/doc](https://github.com/coq/doc), right?

I did a git bisect on that repo and when the repo went from commit [3e699607fd43265f7174896ca2c92ffd36e92be9](https://github.com/coq/doc/tree/3e699607fd43265f7174896ca2c92ffd36e92be9/master/api/coq) to commit [fc0810b9b58780346146f9d8591ebf29f9dfeb19](https://github.com/coq/doc/tree/fc0810b9b58780346146f9d8591ebf29f9dfeb19/master/api/coq), the html files stopped appearing.

Not sure if that's when it started to happen though.

But some links with the version number instead of 'master' seem to be working. Like https://coq.github.io/doc/v8.12/api/coq/Global/index.html

Or is the link with master intended to be a work in progress and the one to be read by users is the one with version number?

**Comment by ejgallego** [comment]
Sorry in master the package with the ml files is coq-core : https://coq.github.io/doc/master/api/coq-core/index.html

Where did you see the wrong link? I didn't spot any obvious one so I may close.

**Comment by Zimmi48** [comment]
>I guess some html files got removed somehow.

Nope, this is normal.

>The site is being served using the files from https://github.com/coq/doc, right?

Yes, but this one is only for (auto-)deployment, so it's not really worth looking at.

>Or is the link with master intended to be a work in progress and the one to be read by users is the one with version number?

It depends on whom you mean by "users". Users of the OCaml API are generally plugin writers, and they are definitely encouraged to keep up-to-date with the `master` version.

---

@ejgallego Do you know of an easy way to either (ideally both):
- remove the listing of the non OCaml library packages (coq, coq-stdlib, coqide, coq-doc) from this page: https://coq.github.io/doc/master/api/index.html
- add a text to the index pages of these packages explaining that there is nothing to see here?

This is not the first time since the split of coq into coq-core + coq-stdlib that we have confused users.

**Comment by ejgallego** [comment]
> add a text to the index pages of these packages explaining that there is nothing to see here?

Using the [`(documentation ...)`](https://dune.readthedocs.io/en/stable/documentation.html) stanza you can indeed override the `index.mld` file used for each package. Also there are many odoc options that can be passed.

I ddin't spend too much time thinking about this as odoc is still in heavy development adding new features etc... so I am personally waiting to see what kind of cool stuff they are gonna come up with.

> remove the listing of the non OCaml library packages (coq, coq-stdlib, coqide, coq-doc) from this page: https://coq.github.io/doc/master/api/index.html

I am not sure but I think we could modify the call to `dune build @doc` to only include the packages we want.

**Comment by Zimmi48** [comment]
I think we should do a quick fix with a short message so that people stop bumping into this issue even if we leave it to later to do something more advanced. So just the `documentation` stanza sounds like a good idea to me.

**Comment by Zimmi48** [comment]
Again a user who stumble on this: https://coq.zulipchat.com/#narrow/stream/237655-Miscellaneous/topic/coq.20api.20documentation.20on.20github
It's impressive how many confused users because of this coq-core + coq-stlib split. I'm going to try a hotfix with the `documentation` stanza now.

**Comment by ejgallego** [comment]
Thanks @Zimmi48 , indeed a small note would really help. Actually the reason I didn't improve more the documentation on the ML side and used a few more (doc) stanzas is (apart from time constraints) I was waiting for some more features on the odoc side that could help, plus the dune migration to see if we reorganize things a bit. But indeed there is plenty of room for improvement.

**Comment by ju-sh** [comment]
Hi. I had found the link by following the 'documentation of coq's api' link from the coq website towards the end of the page at https://coq.inria.fr/documentation (under 'Other documentation') and then clicking on the link for coq.

It now shows a message saying that it is a virtual package. Thanks for putting up the message! It will help other newbies nosing around like me.

(Sorry for bailing right after creating this issue. Had to run after some other stuff in between)

**Comment by Zimmi48** [comment]
>(Sorry for bailing right after creating this issue. Had to run after some other stuff in between)

No worries. In that case, we had already got all the information we needed from you.
