### ISSUE TITLE
Proposal to add lemmas to Q

### ISSUE THREAD

**Issue by koraa** [coq/coq#14066]
I propose adding the following lemmas to the standard library for Q:

```coq
Require Import Psatz.
Require Import QArith.

Lemma Qdiv_inj : forall (a b : Z) (d : positive),
  a=b <-> (a#d)==(b#d).
Proof.
  intros a b c.
  unfold Qeq. cbn. symmetry.
  apply Z.mul_cancel_r.
  lia.
Qed.

Lemma Qsimp : forall (a b c : Z),
  (0 < a)%Z ->
  (0 < c)%Z ->
  b#(Z.to_pos c) == a*b # Z.to_pos (a*c).
Proof.
  intros a b c hagt0 hcgt0.
  unfold Qeq. cbn. symmetry.
  rewrite Z2Pos.id.
  rewrite Z2Pos.id.
  lia. lia. lia.
Qed.

Lemma Qmulz : forall (a : Z) (b : positive) (c : Z),
  (a#b) * inject_Z c == a*c#b.
Proof.
  intros a b c.
  unfold Qeq. cbn.
  lia.
Qed.

Lemma Qeq_split : forall (a b : Z) (c d : positive),
  a = b -> c = d -> a#c == b#d.
Proof.
  intros a b c d Ha_eq_b Hc_eq_d.
  rewrite Ha_eq_b, Hc_eq_d.
  reflexivity.
Qed.
```

**Comment by Zimmi48** [comment]
@koraa When you already have code available, feel free to open a pull request directly. @coq/stdlib-maintainers may be able to orient you regarding which file to modify.

**Comment by MSoegtropIMC** [comment]
An especially difficult question is how to name such lemmas. A few thoughts on that:

- `Qdiv_inj` is not really about Qdiv - I would more call it Qnum_inj. For symmetry you should provide a similar lemma Qden_inj.
- `Qsimp`I would more call `Qreduce`- or looking at the direction of the equation more `Qexpand`. Also think about how lemmas can be applied. A lemma about Q whith only works when the denominator is `Z.to_pos c` might not be widely useable. If you make `c` positive, the left hand side would fit to any Q.
- `Qmulz`: This is a bit short for a rather special lemma. How about `Qmult_inject_Z_r` ? And maybe have a `Qmult_inject_Z_l` as well?
- `Qeq_split` : this is quite similar to your own lemma `Qdiv_inj` and probably should be named in a similar way. Maybe Qinj? And one can think about making it `a = b /\ c = d <-> a#c == b#d` for symmetry with the above `inj` lemmas and e.g. `Qmult_inj_r`.

**Comment by koraa** [comment]
> An especially difficult question is how to name such lemmas.

I've adjusted the names; feel free to continue discussing in the PR.

>     * `Qeq_split` : this is quite similar to your own lemma `Qdiv_inj` and probably should be named in a similar way. Maybe Qinj? And one can think about making it `a = b /\ c = d <-> a#c == b#d` for symmetry with the above `inj` lemmas and e.g. `Qmult_inj_r`.

That isn't correct though; e.g. `~(1#2 == 2#4 -> 1=2 /\ 2=4)`
