### ISSUE TITLE
schedule-vio-checking/check-vio-tasks should be tested

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#14074]
(or removed if not useful)

**Comment by ejgallego** [comment]
It is checked when doing `make QUICK=1` in gitlab ci (`build:quick`) , tho it is flaky as we have discussed a few times.

**Comment by SkySkimmer** [comment]
No, buld:quick checks schedule-vio2vo

**Comment by ejgallego** [comment]
Oh you are right, sorry.
