### ISSUE TITLE
Reduce verbosity of ANTLR warning when building refman.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#14106]
When building with `make` the `refman-html` target, we can get the following warning if our locally installed ANTLR version differs from the one that was used to generate the sources:

```
ANTLR runtime and generated code versions disagree: 4.8!=4.7.2
```

This wouldn't be an issue if this warning was not repeated endlessly, completely flooding the console output of this build. ~~AFAICT, the same doesn't happen when building with `make -f Makefile.dune`.~~ This is actually not true, the warning is flooded in both build modes. I just didn't notice it earlier because I used to have the right version of the tool.

cc @coq/doc-maintainers 

PS: do not fix before #13617 is merged if this requires changing the `Makefile.doc` file to avoid creating merge conflicts.

**Comment by Zimmi48** [comment]
@cpitclaudel You probably know what this is about. Any way we can get rid of this warning?

**Comment by cpitclaudel** [comment]
Does the following (untested) help if you put it in notations/parsing.py?

```
from antlr4 import Recognizer
def checkVersion_once(*args, **kwargs):
    Recognizer.checkVersion(*args, **kwargs)
    Recognizer.checkVersion = lambda *args, **kwargs: None
Recognizer.checkVersion = checkVersion_once
```

**Comment by Zimmi48** [comment]
Nice idea! Unfortunately no, it doesn't. I've also tried with just `Recognizer.checkVersion = lambda *args, **kwargs: None`, but it doesn't change anything.

**Comment by cpitclaudel** [comment]
Sorry, I should have tested it.  The import was wrong and the code didn't call the right original function.  Here you go:

```
from antlr4.Recognizer import Recognizer

check_version = Recognizer.checkVersion
def checkVersion_once(*args, **kwargs):
    check_version(*args, **kwargs)
    Recognizer.checkVersion = lambda *args, **kwargs: None
Recognizer.checkVersion = checkVersion_once
```

If you just want to silence all the warnings, do this:

```
from antlr4.Recognizer import Recognizer
Recognizer.checkVersion = lambda *args, **kwargs: None
```

**Comment by Zimmi48** [comment]
Thanks this works. Do you want to submit a PR or should I take care of it?

**Comment by cpitclaudel** [comment]
Please do, thanks!
