### ISSUE TITLE
Itemized lists are broken in the reference manual

### ISSUE THREAD

**Issue by pi8027** [coq/coq#14121]
#### Description of the problem

Itemized lists are flattened and their bullets disappear in the reference manual. For example:
- in the [master](https://coq.github.io/doc/master/refman/addendum/micromega.html#coq:tacn.zify) branch (wrong one):
  ![13:17:03 989451](https://user-images.githubusercontent.com/111003/114970857-35df5f80-9eb6-11eb-8f68-989e64f66cd7.png)
- in [8.13.2](https://coq.github.io/doc/V8.13.2/refman/addendum/micromega.html#coq:tacn.zify) and the v8.13 branch (right one):
  ![13:16:48 077193](https://user-images.githubusercontent.com/111003/114970817-24965300-9eb6-11eb-8a96-3e6d57a4c0d2.png)

#### Coq Version

master

**Comment by silene** [comment]
The `theme.css` file (which I suppose comes from Sphinx RTD) contains `li{list-style:none}`. Removing it is not enough since it also contains `ul,ol,dl{margin:0;padding:0;list-style:none;list-style-image:none}`.

**Comment by pi8027** [comment]
In 8.13.2, the following rule (in `theme.css`) applies here since the second selector `.rst-content .section ul li` matches. In master, `div` elements with `class="section"` have been replaced with `section` elements and this rule does not apply anymore.
```
.wy-plain-list-disc li,.rst-content .section ul li,.rst-content .toctree-wrapper ul li,article ul li{list-style:disc;margin-left:24px}
```

**Comment by pi8027** [comment]
See readthedocs/sphinx_rtd_theme#1115.

**Comment by Zimmi48** [comment]
IIUC your report and the issue you linked, this has to do with docutils 0.17. docutils is a Sphinx dependency that we don't pin explicitly when installing the latter with pip. Note that recent versions of Sphinx are marked as incompatible with docutils 0.17 but the ancient version 2.3.1 isn't (https://libraries.io/pypi/Sphinx/2.3.1). A simple fix for us would thus be to explicitly install and pin docutuils 0.16 in:
https://github.com/coq/coq/blob/faafe565b942736acc940c8374914fe0284b0b3d/dev/ci/docker/bionic_coq/Dockerfile#L27-L29

**Comment by Zimmi48** [comment]
BTW, that's not the only display problem in the master version of the manual.
Compare (master):
![Screenshot_2021-04-17 Introduction and Contents — Coq 8 14+alpha documentation](https://user-images.githubusercontent.com/1108325/115117347-52ef5d80-9f9e-11eb-8a1d-ca89085a0909.png)
and (8.13.2):
![Screenshot_2021-04-17 Introduction and Contents — Coq 8 13 2 documentation](https://user-images.githubusercontent.com/1108325/115117356-65699700-9f9e-11eb-9a16-906fc2cb5975.png)

I hope that's the same issue and that pinning docutils will fix it.
