### ISSUE TITLE
Fast name printing seemingly causes variable capture

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#14141]
#### Version

Coq 8.13.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following program leads to a proof state,
where the same name refers to two different variables.

```
Set Fast Name Printing.

Lemma le_succ_diag_r (n : nat) : n <= S n.
Proof.
  apply (nat_ind (fun p : nat => p <= S n)).
  - apply le_0_n.
  - Show 1. rename n into p. Show 1. Abort.
```

```
subgoal 1 is:

  n : nat
  ============================
  forall (n : nat) (H : n <= S n), S n <= S n

subgoal 1 is:

  p : nat
  ============================
  forall (n : nat) (H : n <= S p), S n <= S p
```

#### Notes

I did not notice fast name printing to be particularly fast.

**Comment by SkySkimmer** [comment]
@silene please don't assign other people

**Comment by silene** [comment]
Isn't the rule to assign people who introduced the bug?

**Comment by SkySkimmer** [comment]
No, the rule is to assign yourself if you're working on the issue.

My goal is to have assignments represent some actual intention to do something, assigning the bug introducer just means everyone else will skip looking at the issue even if they could fix it (and the assignee will probably do nothing).
