### ISSUE TITLE
Export attribute for existing instances

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#14155]
#### Version

Coq 8.13.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The reference manual says the following about the commands
`Existing Instance qualid ( hint_info ) ?` and
`Existing Instances ( qualid ) + ( | natural ) ?`.

> This is equivalent to `Hint Resolve ident : typeclass_instances`,
> except it registers instances for `Print Instances`.

This is not quite true,
because attributes are still rejected,
as the following program demonstrates.

```
From Coq Require Import Classes.RelationClasses.

Module Le.

Definition le_Reflexive : Reflexive le.
Proof. intros n. apply le_n. Qed.

Definition le_Transitive : Transitive le.
Proof.
  intros n p q lnp lpq. induction lpq as [| r lpr lnr].
  - apply lnp.
  - apply le_S. apply lnr. Qed.

Fail #[export] Existing Instances le_Reflexive le_Transitive.

#[export] Hint Resolve le_Reflexive le_Transitive : typeclass_instances.

End Le.

Fail Definition le_0_0 : 0 <= 0 := reflexivity 0.

Import Le.

Definition le_0_0 : 0 <= 0 := reflexivity 0.
```

```
The command has indeed failed with message:
export attribute not supported here
```

#### Notes

The `local` and `global` attributes work fine
with `Existing Instance` and `Existing Instances`.

**Comment by SkySkimmer** [comment]
Duplicate https://github.com/coq/coq/issues/3056
