### ISSUE TITLE
Coqdoc does not render Primitive declarations, ruining the documentation of PArray

### ISSUE THREAD

**Issue by xavierleroy** [coq/coq#14169]
#### Description of the problem

The page https://coq.inria.fr/distrib/current/stdlib/Coq.Array.PArray.html is incomplete and impossible to understand, because the following lines from the source file PArray.v are just omitted:
https://github.com/coq/coq/blob/d9e9a63f9f49768eee8b239812365ad1115b964f/theories/Array/PArray.v#L5-L23

#### Coq Version

Whichever is "current" at the time of this issue report.  It's getting difficult to know which Coq version is the one documented on coq.inria.fr.

**Comment by herbelin** [comment]
Hi @xleroy, indeed, the list of keywords recognized by coqdoc has not been maintained up-to-date for a while. I made #14170 as a quick fix.
