### ISSUE TITLE
strategy_level_or_var nonterminal

### ISSUE THREAD

**Issue by gares** [coq/coq#14163]
It seems spurious

![Screenshot from 2021-04-23 16-14-57](https://user-images.githubusercontent.com/1013846/115884526-4c099480-a44f-11eb-9425-4a6038960cd3.png)

CC @coq/doc-maintainers

**Comment by JasonGross** [comment]
It is necessary for passing around strategy levels as tactic arguments:
![image](https://user-images.githubusercontent.com/396076/115885803-4a73a880-a41e-11eb-98ef-5a005bb13a65.png)

**Comment by JasonGross** [comment]
I'm inclined to mark this as already fixed in master, since the `strategy_level_or_var` nonterminal has moved to the `with_strategy` tactic in the master version of the refman

**Comment by gares** [comment]
Ok
