### ISSUE TITLE
CoqIDE warning about ide/default.bindings

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#14181]
After the switch to dune for OCaml files, running CoqIDE results in a warning dialogue that says
```
Warning: the file 'ide/default.bindings' was not found in .
```
Note the empty directory after 'in'.

cc @ejgallego

**Comment by ejgallego** [comment]
Let me finish #14176 , then address this which is related to LOCAL indeed.

**Comment by ppedrot** [comment]
This was solved, let's close.
