### ISSUE TITLE
`auto` fails on goals whose shape exactly matches hints

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14190]
This is perhaps more a question of a design issue with `auto` than a bug.

```coq
Axiom foo : forall n m p : nat, n = p -> n = m.
Create HintDb mydb discriminated.
Global Hint Immediate foo : mydb.
Goal forall n m p : nat, n = p -> n = m.
  solve [ auto with mydb ]. (* fails *)
```

In my actual use case, I cannot use `eauto` because unification spins trying to unfold things that it should not unfold.  I can go mark those things as opaque (and that's probably what I'll go do now), but it's a real pain to have to indicate to Coq that it shouldn't unfold a bunch of things just to be able to use a hint whose shape *exactly* matches the goal I'm facing.

cc @mattam82

**Comment by JasonGross** [comment]
Furthermore, `eauto` doesn't even seem to respect `Hint Opaque`, so I'm forced to use `typeclasses eauto`

**Comment by ppedrot** [comment]
This does not look like a bug to me. By definition, `auto` does not instantiate binders not appearing in the conclusion when applying lemmas from the database. Here `p` is clearly not part of the conclusion so it'd need `eauto` to succeed instead. Maybe your bug about `eauto` unfolding stuff it shouldn't is the real one, although this might (?) have been solved by the recent changes around the dnet matching algorithm in 8.15.

**Comment by ppedrot** [comment]
I think that this report is INVALID.
