### ISSUE TITLE
.

### ISSUE THREAD

**Issue by houdamouhcine** [coq/coq#14192]

**Comment by ejgallego** [comment]
Hi @houdamouhcine , this is the Coq issue tracker which is mainly meant for bug reports about Coq itself, not so much as an user forum.

I'd recommend instead asking on some of the resources pointed at https://github.com/coq/coq#questions-and-discussion

**Comment by Zimmi48** [comment]
>I am learning Coq via the Coq 8.12.0 reference manual

Also, this is not the recommended approach. See this warning in the introduction of the manual:

>To learn Coq, beginners are advised to first start with a tutorial / book. Several such tutorials / books are listed at https://coq.inria.fr/documentation.

**Comment by houdamouhcine** [comment]
Thank you for the information.
