### ISSUE TITLE
Provide a way to run an executable without rebuilding

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14226]
Under Dune, is there a way to run an existing developer-compiled executable without rebuilding the code?  It appears that `dune exec -- dev/shim/coqide-prelude` always rebuilds.  Fairly often I want to run without a compile as I'm changing some code to check on the behavior or appearance--I don't always think to start the executable before I begin editing.

**Comment by Zimmi48** [comment]
Yes, I think you can just call `_build/default/dev/shim/coqide-prelude` directly. The `dune exec` thing is just a convenience for:
- not writing the `_build/default/` part,
- rebuilding if dependencies changed.

**Comment by ejgallego** [comment]
Indeed, you can call the shim, or hopefully soon calling the executable directly should work for all cases.

**Comment by jfehrle** [comment]
Yes, I can run it directly.  Would be nice to have a standard shortcut for that pathname--too hard to type.

**Comment by jfehrle** [comment]
Would be nice to mention in the hacking Coq or build-system.dune.md documents.  Beginners may not know where to look for binaries.

**Comment by ejgallego** [comment]
> Would be nice to mention in the hacking Coq or build-system.dune.md documents. Beginners may not know where to look for binaries.

It is mentioned, 5th paragraph devoted to explain it.

**Comment by ejgallego** [comment]
I'd suggest moving this issue to Dune as a feature request for `dune coq top`

**Comment by SkySkimmer** [comment]
You can also pass `--no-build` to dune exec (`dune exec --no-build -- command`)
