### ISSUE TITLE
CoqIDE syntax highlighting missing.  Dune-related?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14244]
The script should not be all black type.  Perhaps Dune-related?  This is on master after syncing.

![image](https://user-images.githubusercontent.com/1253341/116959149-8c3bf480-ac51-11eb-9459-8c6fcb189b3f.png)

**Comment by Zimmi48** [comment]
I can reproduce when building CoqIDE with `Makefile.make` (when building with `Makefile.dune`, I get proper colors). This is very likely related to the warning:

```
Warning: the file 'ide/default.bindings' was not found in .
```

reported in #14181.

**Comment by ppedrot** [comment]
Duplicate of #14181
