### ISSUE TITLE
Binding arguments to a scope vs local scope

### ISSUE THREAD

**Issue by olaure01** [coq/coq#14305]
As mentioned in the [documentation](https://coq.inria.fr/refman/language/extensions/arguments-command.html#binding-arguments-to-a-scope), when binding arguments to a scope:

> The effect of the scope is limited to the argument itself. It does not propagate to subterms

However the behavior happens to be different when using a local scope:
```coq
Parameter g : bool -> bool.
Check (g (true || false)).

Parameter h : option bool -> bool.
Fail Check (h (Some (true || false))).
Check (h (Some (true || false))%bool).
Arguments h _%bool.
Fail Check (h (Some (true || false))).
```
Is there a natural reason for that? is there a way to simulate the local-scope behavior at the arguments level?

**Comment by Blaisorblade** [comment]
> is there a way to simulate the local-scope behavior at the arguments level?

You cou your function in an abbreviation or notation that uses a scope annotation (what you call local scope). But the result can't be eta-reduced.

> Is there a natural reason for that?

`foo%bar` is a syntax to annotate the entire expression. `Arguments` (and `Bind Scope`) lets one setup context-directed scopes (and fake type-directed ones), with the idea that nested arguments might get different scopes from the context; you can annotate all your operators, or use Bind Scope to automate that. But as you notice, that breaks on polymorphic constructors, like `Some` in your example 😢 .
