### ISSUE TITLE
CoqIDE Visual Debugger should allow repeated F10 to step through tactics across files

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14325]
If I "step in" to a tactic whose definition is in another file, the buffer switches to that file.  After that, "step in" does nothing.  This is an unusably painful mode of interaction, because it means I have to switch back to the main file *for every single step*.  Instead, I should be able to hold down F10 and watch the debugger take steps.

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/14252#issuecomment-841492723_

**Comment by jfehrle** [comment]
I think your version doesn't have the changes I made to do this.

By the way, if you click on the arrow, the Messages will appear in a separate window.

![image](https://user-images.githubusercontent.com/1253341/118336493-b2ba2500-b4c6-11eb-8e63-f20658bd3dbd.png)

If you like, I could do a Zoom call so I can see how it behaves.  Just let me know when and send me a link by email.

**Comment by JasonGross** [comment]
Sent you an email, zoom call now?  I'm using 42a77a7adc9df7d6e29c96eeaaa9e541c0bf25b4

**Comment by jfehrle** [comment]
Yes, give me a minute.

**Comment by jfehrle** [comment]
The link for the Zoom call is?

>

**Comment by JasonGross** [comment]
https://mit.zoom.us/j/92719817488?pwd=YnpoYTRGR3ZuMUVicXUyNEhnQWhEZz09

**Comment by jfehrle** [comment]
Now fixed in #14252.  Also, the debugger function keys are now recognized in detached message panels, an alternate way to keep stepping.
