### ISSUE TITLE
Why is `eq_subrelation` not an instance?

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#14349]
#### Description of the problem

`eq_subrelation` is not declared as an instance, which makes it impossible to `setoid_rewrite` with `eq` under binders if only a `Proper` is available for some setoid relation.

For example, in Iris we like to do:

```coq
Lemma test `{Countable A} (X : gset A) (Φ Ψ : A → PROP) :
  (∀ x, Φ x = Ψ x) →
  ([∗ set] x ∈ X, Φ x) ⊣⊢ ([∗ set] x ∈ X, Ψ x).
Proof.
  intros Heq. Fail setoid_rewrite Heq. (* fails *)
Existing Instance eq_subrelation.
  setoid_rewrite Heq. (* works *)
```
For `[∗ set]` there is a `Proper (subrelation _ equiv ==> equiv)`, but we are rewriting with `eq`, so this needs `eq_subrelation eq equiv` to succeed.

Thanks to @RalfJung and @Janno we found out that that there used to be a `Hint Extern`, but that it was removed in b0e371b354ffdbf4a8572924602d04848020079e. That commit does not provide further information why it was removed. It seems that hint was broken though, and an `@` is needed to make it work:

```coq
Hint Extern 3 (subrelation (@eq _) ?R) => not_evar R ; class_apply @eq_subrelation.
```

@mattam82 Do you happen to recall why you removed this hint?

#### Coq Version

```
$ coqc --version
The Coq Proof Assistant, version 8.13.1 (March 2021)
compiled on Mar 13 2021 10:35:46 with OCaml 4.11.1
```

**Comment by mattam82** [comment]
It probably had the same problem that it created Reflexive ?R constraints resulting in undirected search, that is fixed in PR #13969

**Comment by robbertkrebbers** [comment]
Does that mean that post #13969 we can add back the instance?

**Comment by mattam82** [comment]
We could safely add back the instance using `ReflexiveProxy` which, in case the relation is not know, tries to infer a canonical one.

**Comment by robbertkrebbers** [comment]
`ReflexiveProxy` does not seem to exist, there's only `ProperProxy` :confused:

**Comment by robbertkrebbers** [comment]
Oh, that's new in #13969...

**Comment by mattam82** [comment]
In 13969 this is now taken care of by the `RewriteRelation` class.
