### ISSUE TITLE
`ltac_gen_subproof` axioms in `coqchk` output

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#14350]
When running `coqchk` on std++ we get a bunch of `ltac_gen_subproof` axioms:

```
* Axioms:
    Coq.micromega.ZifyInst.ltac_gen_subproof9
    Coq.micromega.ZifyInst.ltac_gen_subproof8
    Coq.micromega.ZifyInst.ltac_gen_subproof7
    Coq.micromega.ZifyInst.ltac_gen_subproof6
    Coq.micromega.ZifyInst.ltac_gen_subproof5
    Coq.micromega.ZifyInst.ltac_gen_subproof4
    Coq.micromega.ZifyInst.ltac_gen_subproof3
    Coq.micromega.ZifyInst.ltac_gen_subproof2
  ...
```

See also https://gitlab.mpi-sws.org/iris/stdpp/-/jobs/127683#L1051

Where are these coming from?

#### Coq Version

This appears with Coq master, for example, f16b7c75:

```
The Coq Proof Assistant, version 8.14+alpha
compiled with OCaml 4.08.1
```

/cc @RalfJung

**Comment by RalfJung** [comment]
This changed a while ago:
https://gitlab.mpi-sws.org/iris/stdpp/-/jobs/87869 is good,
https://gitlab.mpi-sws.org/iris/stdpp/-/jobs/87986 is bad.
That corresponds to this diff on our side: https://gitlab.mpi-sws.org/iris/stdpp/-/compare/b4688b8add529a7e16d9363c602eec8f8fede4ce...7e802184a5b2f741441f5d4a44744815dedae553 (I doubt this is the culprit).

It corresponds to this Coq diff: https://github.com/coq/coq/compare/94d9fe2b...daca8394.
My first guess would that https://github.com/coq/coq/commit/427e8cac2c267a7302b71979c0f1019598176e31 is responsible; Cc @ppedrot.

**Comment by SkySkimmer** [comment]
It's not stdpp related, you can see them eg in https://gitlab.com/coq/coq/-/jobs/1279085043#L1366

**Comment by SkySkimmer** [comment]
Duplicate https://github.com/coq/coq/issues/13324
