### ISSUE TITLE
"make ci-elpi" fails

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14361]
After an initial failure and `mkdir /home/proj/coq/_build_vo/default/bin`, I get:

```
make[1]: Entering directory '/home/proj/coq/_build_ci/elpi'
Using coq found in /home/proj/coq/_build_vo/default/bin/, from COQBIN or PATH
Makefile:62: Makefile.coq.conf: No such file or directory
make[1]: /home/proj/coq/_build_vo/default/bin///coq_makefile: Command not found
Makefile:49: recipe for target 'Makefile.coq.conf' failed
make[1]: *** [Makefile.coq.conf] Error 127
make[1]: Leaving directory '/home/proj/coq/_build_ci/elpi'
Makefile.ci:109: recipe for target 'ci-elpi' failed
make: *** [ci-elpi] Error 2
```

How can I get this to work?

**Comment by SkySkimmer** [comment]
Cannot reproduce
Why do you mkdir some random path?

**Comment by jfehrle** [comment]
Because the first time I ran it, it failed with

```ls: cannot access '/home/proj/coq/_build_vo/default/bin/': No such file or directory```

Perhaps I'm missing something here:

``
$ echo $COQBIN

$ echo $PATH
/home/jfehrle/.opam/4.07.1/bin:/home/jfehrle/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NGX:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Gradle/gradle-6.4.1/bin":/mnt/c/Users/jfehr/AppData/Local/Microsoft/WindowsApps:/snap/bin
```

**Comment by SkySkimmer** [comment]
You have to build coq before running the ci targets

**Comment by jfehrle** [comment]
I've been doing that.  I just rebased on master, but it still doesn't working.  After the build, the bin directory is still empty.

**Comment by Zimmi48** [comment]
If you build with `Makefile.dune`, you should remove the `_build_vo` directory.

**Comment by jfehrle** [comment]
OK, that works.  I've been using `Makefile.dune` except for a few things that AFAIK don't work there yet, such as building the Sphinx doc.  Maybe the dune build could give a warning if `_build_vo` exists--at least until the regular make isn't needed?
