### ISSUE TITLE
Dune equivalent to `make byte` and `make coqbinaries pluginsopt`

### ISSUE THREAD

**Issue by herbelin** [coq/coq#14394]
#### Description of the problem

[Opening an issue on the suggestion of @ejgallego]

Quite often, I test a feature on a file, modify the code, test the file again, modify the code, test the file again, etc. With make, I used to do `make byte` or `make coqbinaries pluginsopt`, since, in such cases, I expect the vo part of the initial state (or from other libraries that the file depends on) to be skipped because I know that they do not depend in practice on the changes I made to the binaries. How to do that with dune?

**Comment by SkySkimmer** [comment]
`dune build @check` and `dune build coq-core.install` respectively should work OK

**Comment by herbelin** [comment]
`dune build @check` compiles the `cmo`/`cmi` but does not build the binaries.

`dune build coq-core.install` seems to do what I want, thanks (thanks to @ejgallego too). I imagine this is due to the cache, but even native compilation seems to recompile minimalistically.

**Comment by Zimmi48** [comment]
This is also due to some specific OCaml flags (`-opaque` I think) being set in dev mode. If you were to use the release mode while developing, then the flags wouldn't be set and the recompilation would be much less minimalistic (similar to the former make-based build).

**Comment by ejgallego** [comment]
> `dune build coq-core.install` seems to do what I want, thanks (thanks to @ejgallego too). I imagine this is due to the cache, but even native compilation seems to recompile minimalistically.

As Théo mentions native compilation in dev mode is quite efficient, but still `dune build coq-core.install` is doing more that you want, so we may want to add a target that does exactly what you want, so I let you Hugo to consider whether we fix this after you gain some more experience.

In practice, I have found the workflow using native to be fast enough as not to care too much, depending your concrete case, dune may be already faster in native that the old system in byte.

As noted elsewhere, we hope that we can do this kind of "skip vo file rebuild" soon using cutoffs.
