### ISSUE TITLE
"sh dev/ci/ci-XXX.sh" should cause build of dependencies

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14396]
For example, `sh dev/ci/ci-fiat_crypto.sh` fails unless you've previously run `sh dev/ci/ci-rewriter.sh`.  Perhaps the script could include a quick check whether the `ci-rewriter` directory has been created.

**Comment by SkySkimmer** [comment]
You're supposed to use `make ci-bla`

**Comment by jfehrle** [comment]
That was not working for a while recently with the dune transition so I improvised.
