### ISSUE TITLE
[CoqIDE] Ltac Visual Debugger should display the messages of the tactic being debugged when stepping though other files

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14393]
Variant of https://github.com/coq/coq/issues/14329: insofar as the messages are used to print debugging information (evaluation of objects), they should be invariant across buffers while stepping in.
![image](https://user-images.githubusercontent.com/396076/119683990-238c0600-be12-11eb-8fc5-ef2dbf2dda28.png)
![image](https://user-images.githubusercontent.com/396076/119684029-2be44100-be12-11eb-87ed-ac8a1d0e5a2d.png)

#### Coq Version

e3e0a477cbdf8fff29d960581ac30d424adcbea1 of #14252

**Comment by jfehrle** [comment]
I suggest you detach the Messages panel of the primary script

**Comment by jfehrle** [comment]
... just click here.  Not sure the code change you suggest is needed.

![image](https://user-images.githubusercontent.com/1253341/119686179-ecf6c100-bdfa-11eb-93e9-bee29c1a0149.png)

**Comment by JasonGross** [comment]
Ah, neat, that works.  I think this should definitely be mentioned in the documentation of the visual debugger
