### ISSUE TITLE
No quick way to rebuild doc_grammar.exe

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14412]
EDITED

`make doc_gram_rsts` no longer rebuilds `doc_grammar.exe`--inconvenient if `doc_grammar.ml` has been modified.  You have to delete `doc_grammar.exe` to trigger rebuilding (yuck).

Furthermore `make -f Makefile.dune world` doesn't rebuild it, either.  You must delete `doc_grammar.exe` to get it to recompile.  Also, making `world` may compile much more than just `doc_grammar`, i.e. it is slow.

For example, note that `doc_grammar.ml` is newer than `doc_grammar.exe` and that neither timestamp changes:
```
$ find . -name "doc_grammar*" -exec ls -l {} \;
-rw-r--r-- 1 jfehrle jfehrle 72822 May 30 11:20 ./doc/tools/docgram/doc_grammar.ml
-rw-r--r-- 1 jfehrle jfehrle 86240 Apr 26 13:11 ./doc/tools/docgram/doc_grammar.cmo
-r--r--r-- 1 jfehrle jfehrle 72821 May 30 11:19 ./_build/default/doc/tools/docgram/doc_grammar.ml
-r-xr-xr-x 1 jfehrle jfehrle 2857336 May 30 11:19 ./_build/default/doc/tools/docgram/doc_grammar.exe

$ make -f Makefile.dune world
dune build  coq-core.install coq-stdlib.install coqide-server.install coqide.install

$ find . -name "doc_grammar*" -exec ls -l {} \;
total 76
-rw-r--r-- 1 jfehrle jfehrle 72822 May 30 11:20 ./doc/tools/docgram/doc_grammar.ml
-rw-r--r-- 1 jfehrle jfehrle 86240 Apr 26 13:11 ./doc/tools/docgram/doc_grammar.cmo
-r--r--r-- 1 jfehrle jfehrle 72821 May 30 11:19 ./_build/default/doc/tools/docgram/doc_grammar.ml
-r-xr-xr-x 1 jfehrle jfehrle 2857336 May 30 11:19 ./_build/default/doc/tools/docgram/doc_grammar.exe

```

Attn: @Zimmi48

**Comment by SkySkimmer** [comment]
doc_grammar.ml is not in ALL_ML_SOURCE_FILES https://github.com/coq/coq/blob/88d11d6b4ee97bae2287357113b1a3cceb038889/Makefile.common#L112-L114
so make does not see it as a dependency https://github.com/coq/coq/blob/88d11d6b4ee97bae2287357113b1a3cceb038889/Makefile.common#L206

**Comment by SkySkimmer** [comment]
>Furthermore make -f Makefile.dune world doesn't rebuild it, either. You must delete doc_grammar.exe to get it to recompile. Also, making world may compile much more than just doc_grammar, i.e. it is slow.

Makefile.dune `world` does not compile doc_grammar since it's not an installed product.

**Comment by jfehrle** [comment]
OK.  I'd be happy for now if `make doc_gram_rsts` still compiled it.
