### ISSUE TITLE
Failing "make doc_gram_rsts" deletes orderedGrammar

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14411]
make/dune should not be deleting files here!  It's particularly unpleasant to lose your changes because changes to orderedGrammar are often exactly why you're making this target.

```
$ make doc_gram_rsts
     :
Warning: Nonterminal where not included in .rst files
TOTAL Nonterminals not included = 71
1 error(s)
Makefile.doc:305: recipe for target 'doc/tools/docgram/orderedGrammar' failed
make[1]: *** [doc/tools/docgram/orderedGrammar] Error 1
make[1]: *** Deleting file 'doc/tools/docgram/orderedGrammar'
```

Attn: @Zimmi48

**Comment by SkySkimmer** [comment]
Please test https://github.com/coq/coq/pull/14414 (I tested myself but may have missed something)
