### ISSUE TITLE
Coq errors with native compiler errors in the absence of any use of the native compiler

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14427]
#### Description of the problem

The file
```coq
Declare ML Module "ltac_plugin".
Inductive False := .
Axiom proof_admitted : False.
Tactic Notation "admit" := abstract case proof_admitted.
```
With `/github/workspace/builds/coq/coq-failing/_install_ci/bin/coqc -q -nois /tmp/tmps_xayoyo.v` gives
```
File "/tmp/.coq-native/Ntmps_xayoyo.native", line 1:
Error: /github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/../coq-core/kernel/nativevalues.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
Error: Native compiler exited with status 2
```

I was under the impression that @ppedrot disabled compilation to native code when `-native-compiler ondemand` was deprecated in coqc, but this seems to indicate otherwise.  However, the deprecation message is not supressable and creates a lot of line noise that breaks the output tests of the bug minimizer, so I can't just enable it unconditionally.

I have not managed to reproduce this bug locally, but it seems deterministic (though I have yet to track down the trigger conditions), and it poses a severe problem for the bug minimizer. 

See also https://github.com/coq/coq/pull/12743#issuecomment-851702877 and https://github.com/coq-community/run-coq-bug-minimizer/runs/2713870945?check_suite_focus=true

#### Coq Version

master

**Comment by ppedrot** [comment]
For backwards compatibility, `coqc` behaves in 8.14 as in 8.13 regarding the native compilation option, except that it outputs a deprecation warning when given the `-native-compiler` option. You can remove the warning passing the corresponding `-w` option, this is what coq_makefile does.

In 8.15 `coqc` will probably stop producing native files at all, but we're not there yet.
