### ISSUE TITLE
Proof Diff Anomaly

### ISSUE THREAD

**Issue by whonore** [coq/coq#14425]
#### Description of the problem

In Coqtail and CoqIDE the following script prints `Anomaly "Uncaught exception Pp_diff.Diff_Failure("Unable to match goals between old and new proof states (5)")."` at the indicated line.

```coq
Set Diffs "on".

Variable A: Type.
Variable P: A -> Prop.

Lemma L1 (a b: A) :
  P b ->
  (P a /\ exists c, b = c).
Proof. Admitted.

Lemma L2 a :
  P a ->
  False.
Proof.
  intros HP.
  eapply L1 in HP as HP'.
  destruct HP' as (? & b & ?).
  subst.
  clear HP. (* <- Anomaly *)
```

#### Coq Version

8.13.2, master

**Comment by Zimmi48** [comment]
cc @jfehrle

**Comment by jfehrle** [comment]
Workaround: turn off proof diffs for this proof.  I will look into it.
