### ISSUE TITLE
Cumulative StrictProp, but SProp alias isn't cumulative

### ISSUE THREAD

**Issue by jonleivent** [coq/coq#14420]
in 8.13.2:
```Coq
Set Cumulative StrictProp.
Definition ok(x:SProp) : Type := x. (*SProp is cumulative*)
Definition sp := SProp. (*sp aliases SProp*)
Fail Definition bug(x:sp) : Type := x. (*sp is not cumulative*)
```
The failure is:
```
The command has indeed failed with message:
The term "fun x : sp => x" has type "sp -> sp"
while it is expected to have type "sp -> Type".
```

**Comment by ppedrot** [comment]
Cumulative SProp is but a hack to work around the pretyper. As such I don't think it will ever fixed. Rather, we should make the pretyper compatible with several universe hierarchies and there are plans for that.

**Comment by jonleivent** [comment]
My workaround to this is to use:
```Coq
Section Cumulative_SProp.
  Local Set Cumulative StrictProp.
  Definition sprop2prop(s:SProp) : Prop := s.
End Cumulative_SProp.
```
and then call sprop2prop explicitly where needed outside the section.  Is that OK?   At the very least, I limit my usage of `Set Cumulative StrictProp` and tag every usage with `sprop2prop`.

BTW: this is in a reflection mechanism that reifies sorts, with the requirement that it works whether or not `Cumulative StrictProp` is set.  Hence reifying and then denoting out `SProp` creates the problematic alias that lacks cumulativity.

**Comment by SkySkimmer** [comment]
Only you can say what is or isn't OK.
If you're explicitly tagging maybe you can use Box instead https://github.com/coq/coq/blob/ff1040ba5f1d7211f5353cfeb84bc72b9148cad5/theories/Logic/StrictProp.v#L16, it uses no special flags.

**Comment by jonleivent** [comment]
> Only you can say what is or isn't OK.

What I meant to ask was whether sprop2prop would lead to other problems with the current implementation or not.  I cannot use Box because that works with elements of SProp, not SProp itself.
