### ISSUE TITLE
`make -f Makefile.ci GITLAB_CI=1 ci-metacoq` does a lot of useless work when run twice

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14448]
If I add any CI target that depends on ci-metacoq, the test-suite is run a second time.  See https://gitlab.com/coq/coq/-/jobs/1316144597 for an example on #14445

cc @coq/ci-maintainers and ... @mattam82 ?

**Comment by JasonGross** [comment]
Note that this adds about an hour of overhead to any minimization job involving metacoq

**Comment by herbelin** [comment]
Maybe has @TheoWinterhalter informations about that.

**Comment by TheoWinterhalter** [comment]
I think CI was setup by @mattam82 and @yforster.

**Comment by SkySkimmer** [comment]
This is a metacoq issue, we are not responsible for their build system.
