### ISSUE TITLE
Regression (?) in localisation of errors in the middle of a sequence of symbols

### ISSUE THREAD

**Issue by herbelin** [coq/coq#14443]
#### Description of the problem

The "new" localisation of error messages looks less understandable than before. E.g.

```
Check forall .
(*
> Check forall .
>       ^^^^^^^^
Error:
Syntax error: [open_binders] expected after 'forall' (in [binder_constr]).
*)
```
before:
```
> Check forall .
>              ^
Error:
Syntax error: [constr:open_binders] expected after 'forall' (in [constr:binder_constr]).
```

What do others think? (It is an extension by 1 to the left.)

#### Coq Version

Since #14259.

**Comment by silene** [comment]
Given that the error message explicitly mentions the preceding token, having it spuriously localized is not too awful. Actually, it could even be considered as a feature. So, postponing.
