### ISSUE TITLE
Unexpected type class failure in the presence of Hint Mode

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#14441]
#### Description of the problem

@Blaisorblade tried to use `Hint Mode` for the `Equiv` class in std++/Iris but that attempt failed: some type annotations are needed because of unexpected type class failures.

Below I have included a minimized example: 

```coq
Require Import Utf8 Relation_Definitions.

Class Equiv A := equiv: relation A.
Hint Mode Equiv ! : typeclass_instances.

Class Lookup (K A M : Type) := lookup: K → M → option A.
Hint Mode Lookup ! - - : typeclass_instances.
Hint Mode Lookup - - ! : typeclass_instances.

Parameter list_equiv : ∀ A, Equiv A → Equiv (list A).
Parameter option_equiv : ∀ A, Equiv A → Equiv (option A).
Parameter list_lookup : ∀ A, Lookup nat A (list A).

Existing Instance list_equiv.
Existing Instance option_equiv.
Existing Instance list_lookup.

Set Typeclasses Debug.
(* fails *)
Fail Lemma list_equiv_lookup {A} `{Equiv A} (l k : list A) :
  equiv l k ↔ ∀ i, equiv (lookup i l) (lookup i k).
(*
?Equiv : "Equiv (option ?A)"

?Lookup : "Lookup ?K ?A (list A)"

?Lookup0 : "Lookup ?K ?A (list A)"
*)
```

This example is essentially the same as I used in #5735. We see that `Lookup ?K ?A (list A)` fails, while with mode `Lookup - - !` the instance `list_lookup` should be found.

In #5735, @maximedenes conjectured that the fix for #9058 should fix this example too, but that turns out to be not the case.

#### Coq Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.13.1 (March 2021)
compiled on Mar 13 2021 10:35:46 with OCaml 4.11.1
```

/cc @RalfJung @Blaisorblade

**Comment by RalfJung** [comment]
Cc @mattam82 who wrote the fix for #9058.

**Comment by SkySkimmer** [comment]
>We see that Lookup ?K ?A (list A) fails, while with mode Lookup - - ! the instance list_lookup should be found.

The problem was rather about the `Equiv (option ?A)` search which applied equiv_option but then failed to postpone.
See https://github.com/coq/coq/pull/14480

**Comment by robbertkrebbers** [comment]
Awesome, thanks for the fix!

**Comment by SkySkimmer** [comment]
See #13952
