### ISSUE TITLE
CoqIDE FAQ is installed to the wrong place

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14467]
[PR #14434] is incorrect, as it installs `/usr/doc/coqide/FAQ`, but `/usr/doc` is not a thing. It should be installing to `/usr/share/doc/coqide/FAQ`. See also https://launchpadlibrarian.net/542891987/buildlog_ubuntu-groovy-amd64.coq_8.master~git~202106082017+22408-0~daily357-b541ac00b5~ubuntu20.10.1_BUILDING.txt.gz

_Originally posted by @JasonGross in https://github.com/coq/coq/pull/14434#pullrequestreview-679054124_

**Comment by JasonGross** [comment]
cc @ejgallego

**Comment by ejgallego** [comment]
This doesn't look like a bug in Coq, but in your dune setup, which seems to be incorrectly configured.

**Comment by JasonGross** [comment]
This is the standard system dune on Ubuntu from the apt packages, how do I check if it's properly configured?

**Comment by ejgallego** [comment]
Duplicate of #14232
