### ISSUE TITLE
`End ModuleName` should not be allowed in proof mode

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#14476]
```coq
Module Type P.
  Parameter N: nat.
End P.

Module foo(p: P).
  Definition a(x: nat): nat. intros. exact (x + p.N). Defined.
  Definition b(x: nat): nat.
    refine (_ + p.N).
End foo.

exact x.
Defined.
```

results in

```
Error: Anomaly "File "clib/int.ml", line 46, characters 14-20: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

at the last `Defined`. It would be better if `End foo.` was rejected because we're still in proof mode there.

This example might seem made up, but it can also manifest itself as a puzzling usability issue (that's how I found it): If there are many `Definition`s that don't use proof mode after `End foo`, and then I want to start a lemma, it tells me `Error: Nested proofs are discouraged and not allowed by default. This error probably means that you forgot to close the last "Proof." with "Qed." or
"Defined.". If you really intended to use nested proofs, you can do so by turning the "Nested Proofs Allowed" flag on.`, which is a nice error message, but when I set out to find where I forgot a `Defined` or `Qed`, I skip modules, because the idea that it could be possible to `End` a module while still in proof mode is soooo beyond my imagination that I don't consider it at all, and need quite some time to figure out the issue 😅 

Coq version: 8.13.2

**Comment by SkySkimmer** [comment]
Fixed in master
