### ISSUE TITLE
"Print <notation>" is often very unhelpful

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#14486]
#### Description of the problem

`Print` is an absolutely amazing tool to figure out the underlying definition of a term, and use that go go on searching more lemmas about it. Sadly, when the term is a notation, `Print` is often very unhelpful: in Iris, `Print default` prints
```
Notation default := default
```
The information content of this output is exactly 0. ;) The actual definition inside std++ look as follows:
```
Notation default := (from_option id).
```
I think what happens here is that Coq uses the usual pretty-printing to show the body of the notation, but of course that matches the notation, removing all useful information.

Is there a way that `Print default` could treat the `default` notation (and maybe more) as "parsing only", so that it can actually show something useful?

#### Coq Version

8.13.2

**Comment by herbelin** [comment]
See #12777 which has some other examples.

I don't know what would be the best solution. We could for instance print the original body in its original printing context (but then not necessarily reparsable in the current context). We could add an option to `Print` to tell to prevent a given symbol or notation to be used on the right-hand side. Not sure what would be the best.

**Comment by Tuplanolla** [comment]
The unintuitive behavior of `Print`, `Check` and `About`
on all the different kinds of objects Coq provides
is a common source of confusion for beginners and
even a nuisance for experienced users.

Suppose I want to find the type, universe level and
structurally decreasing argument of `plus`.

```
Check plus.
(* Init.Nat.add
     : nat -> nat -> nat *)
(** Okay, but I still need more. *)
About plus.
(* Notation plus := Init.Nat.add
Expands to: Notation Coq.Init.Peano.plus *)
(** Of course, it was a notation, so this command was not helpful. *)
About Init.Nat.add.
(* Init.Nat.add : nat -> nat -> nat

Init.Nat.add is not universe polymorphic
Arguments Init.Nat.add (_ _)%nat_scope
Init.Nat.add is transparent
Expands to: Constant Coq.Init.Nat.add *)
(** Good to know, but I sill wanted more. *)
Print Init.Nat.add.
(* Init.Nat.add = 
fix add (n m : nat) {struct n} : nat := match n with
                                        | 0%nat => m
                                        | S p => S (add p m)
                                        end
     : nat -> nat -> nat

Arguments Init.Nat.add (_ _)%nat_scope *)
(** I got a bit more information than I needed, but alright. *)
```

Things go a different way if I try to do the same thing with `QDen`.

```
Check QDen.
(* Abbreviation is not applied enough. *)
(** Ah, it must be a more complicated notation. *)
About QDen.
(* Notation QDen p := (Z.pos (Qden p))
Expands to: Notation Coq.QArith.QArith_base.QDen *)
(** So, I needed to introduce some variables to find out the type. *)
Check QDen ?[p].
(* QDen ?p
     : Z
where
?p : [ |- Q] *)
(** So, I needed to introduce some variables to find out the type. *)
About Qden.
(* Qden : Q -> positive

Qden is not universe polymorphic
Arguments Qden _%Q_scope
Qden is transparent
Expands to: Constant Coq.QArith.QArith_base.Qden *)
(** Nice, but I needed one more thing. *)
Print Qden.
(* Qden = fun q : Q => let (_, Qden) := q in Qden
     : Q -> positive

Arguments Qden _%Q_scope *)
(** As it turns out, the definition is not even recursive. *)
```

On another day, I might see `exfalso` appear
in an error message and want to find out what it is.

```
Check exfalso.
(* The reference exfalso was not found in the current environment. *)
(** It does not have a type, so it is probably a module or a tactic. *)
About exfalso.
(* Ltac Coq.Init.Tactics.exfalso *)
(** Very well, but this did not help me see inside. *)
Print exfalso.
(* Ltac exfalso := elimtype False *)
(** This did not help either, but we can keep going. *)
Print elimtype.
(* Ltac elimtype $1 := <ltac_plugin::elimtype@0> *)
(** I guess there was never hope to begin with. *)
```

**Comment by RalfJung** [comment]
> We could add an option to Print to tell to prevent a given symbol or notation to be used on the right-hand side. Not sure what would be the best.

Ideally it would do that automatically for the symbol to be printed.

Though looking at https://github.com/coq/coq/issues/12777, when there are two definitions for the same thing, that might still not help.

**Comment by herbelin** [comment]
> Ideally it would do that automatically for the symbol to be printed.

It is already the case. So, your Iris example is most probably of a kind similar to what @Janno reported and @pi8027 analyzed [there](https://github.com/coq/coq/issues/12777#issuecomment-763918324).

**Comment by herbelin** [comment]
@Tuplanolla : what lesson would you like we retain? On my side I retain that `Ltac elimtype $1 := <ltac_plugin::elimtype@0>` is both non-informative and ugly (should typically be `elimtype is a primitive tactic`??).

Otherwise, I'm of course biaised by years of getting used to these 3 commands but it not clear-cut to me what you'd expect in each of the other cases.

Would you like e.g. that `About` and `Print` are more similar, to the exception of `Print` showing the body of the object when there is one?

**Comment by Tuplanolla** [comment]
> Would you like e.g. that `About` and `Print` are more similar, to the exception of `Print` showing the body of the object when there is one?

Yes, that would be nice.

**Comment by RalfJung** [comment]
> It is already the case. So, your Iris example is most probably of a kind similar to what @Janno reported and @pi8027 analyzed there.

Ah, yes, that seems likely.
How hard would it be to fix this issue? That would already help most cases where I encounter this in practice, I think.

**Comment by Blaisorblade** [comment]
> Otherwise, I'm of course biaised by years of getting used to these 3 commands but it not clear-cut to me what you'd expect in each of the other cases.

I'm not saying that's easy, but "something you could teach to a new Coq user in the first lesson" seems like a goal you'd want to reach.

In practice, I typically want a combination of (a) the entire text of the definition (including notations in modules!), up to code style improvements (b) the entire result of elaboration. OTOH, I wouldn't know how to fix Check for identifiers with maximally inserted arguments.

**Comment by pi8027** [comment]
Note that fixing this issue would also greatly help MathComp developers and users. With hierarchy-builder, this could even be crucial, I think.

**Comment by herbelin** [comment]
@RalfJung: could you check that #14493 fixes the issue (or else provide a self-contained example). At least, it fixes @pi8027's minimization of @Janno's [report](https://github.com/coq/coq/issues/12777#issuecomment-667026683) at #12777. For the record, the problem was tricky: a hash key field hidden in names was breaking the correct deactivation of the notation.

**Comment by RalfJung** [comment]
> OTOH, I wouldn't know how to fix Check for identifiers with maximally inserted arguments.

Why would one ever use `Check` anyway? Ever since I know `About`, I did not look back. I just wish I would have learned about `About` earlier. Probably the `Check` docs should point out that to get information about an identifier (including its type), `About` is strictly superior.

**Comment by RalfJung** [comment]
FWIW, in trying to find a small reproducible example for this I noticed something really strange: when I do `Print default` *twice*, the second time it prints the right thing...

**Comment by Blaisorblade** [comment]
> Why would one ever use Check anyway? 

For expressions. But maybe you don't really need two separate commands, just an `About` that switches to `Check` for expressions? Cc @Tuplanolla.

**Comment by Tuplanolla** [comment]
> But maybe you don't really need two separate commands, just an `About` that switches to `Check` for expressions?

Yes, that would be nice.

This is starting to sound more like a plea for a universal `What` command
that would tell you everything about anything,
which is not even that bad of an idea to be honest.

**Comment by Zimmi48** [comment]
I support the proposal to have a universal command (though I would keep the name `About` instead of inventing a new name to make the transition simpler).

One important requirement for this command to be truly universal is that it should look through all the "namespaces" and report on all the objects that could be designated by the provided name. Then, there could be specializations of `About` by relying on attributes to fine-tune its behavior (e.g., only show a subset of the information to emulate previous commands).

Example:

```coq
About exfalso. (* is about the tactic *)
Definition exfalso := 0.
About exfalso. (* is about the constant but should mention both the constant and the tactic *)
Print Ltac exfalso. (* could become `#[ ltac ] About exfalso` or whatever *)
```

**Comment by SkySkimmer** [comment]
Please don't merge Print and About, Print is often quite verbose.

**Comment by Zimmi48** [comment]
If that's the only reason for not merging the two, then we could have the default behavior of `About` be the one with the ideal verbosity and have the `Print` behavior be a variant that one needs to explicitly require (but the `About` command could tell the user that this variant is available). We could also consider making the output of `About` sufficiently structured so that the information that you are looking for is easy to spot even if a lot of information is printed...

**Comment by ejgallego** [comment]
The original issue seems fixed for me in `master`, `Print` correctly displays the abbreviation definition. For non-abbreviation notations `Print Notation` is in 8.17.

```coq
Coq < From stdpp Require Import option.
Coq < Print default.
Notation default := (from_option id)
```
