### ISSUE TITLE
Unable to get support for native compiler on 8.14

### ISSUE THREAD

**Issue by silene** [coq/coq#14507]
While trying to write Opam packages for Coq 8.14 (see coq/opam-coq-archive#1744), I stumbled upon the following issue. Despite having installed `coq-native` and the Opam package containing
```
build: [
  [ "./configure"
    ...
    "-native-compiler" "yes" {coq-native:installed} "no" {!coq-native:installed} ]
```
support for the native compiler was disabled:
```console
$ rlwrap coqtop
Welcome to Coq 8.14+alpha

Coq < Eval native_compute in (1 + 1).
Toplevel input, characters 0-31:
> Eval native_compute in (1 + 1).
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning: native_compute disabled at configure time; falling back to
vm_compute. [native-compute-disabled,native-compiler]
     = 2
     : nat

$ opam list
...
coq                      8.14.dev    Formal proof management system
coq-native               1           Package flag enabling coq's native-compiler
dune                     2.5.1       Fast, portable, and opinionated build syste
ocaml                    4.05.0      The OCaml compiler (virtual package)
...
```

**Comment by ppedrot** [comment]
Could it be an avatar of #14469? Native compilation is deactivated in dune mode.

**Comment by silene** [comment]
I am really confused. I have run `opam reinstall -v coq=8.14.dev` to be able to access the logs and now support for native compiler is there.

**Comment by silene** [comment]
And I have tried a third time just to be sure it was a spurious issue, and now it is broken again.

**Comment by silene** [comment]
Over five attempts, I got two successes and three failures. I give up trying to understand why the build is non-deterministic.

**Comment by silene** [comment]
Could it be that compiling native support succeeds only if there is already a version of 8.14 that is installed? That would explain why it failed at first, then succeeded when I did `reinstall`, then failed again when I did `remove` and `install`.

**Comment by SkySkimmer** [comment]
>And I have tried a third time just to be sure it was a spurious issue, and now it is broken again.

What did the logs say for that time (or any other logs for a broken install)? Specifically the configure call.

**Comment by silene** [comment]
Unfortunately, I cannot tell, because I was trying whether the `-v` flag could have had any impact on the build. (Everything becomes more complicated when the observation possibly modifies the behavior.)

**Comment by silene** [comment]
I have done another installation, this time in a fresh switch with a more recent Dune, and I was not able to reproduce the issue, so closing again.
