### ISSUE TITLE
Anomaly in module system, Module Type with Definition with Definition

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#14505]
The following code yields Anomaly "Uncaught exception Not_found."

```
Module Type TYPE.
  Parameter t : Type.
End TYPE.

Module Type A.
   Parameter t : Type.
   Parameter eqv : t -> t -> Prop.
 End A.

Module Type B (T: TYPE)
   := A with Definition t := T.t with Definition eqv := @eq T.t.
```

#### Coq Version
Coq version 8.13.0 or 8.13.2

**Comment by herbelin** [comment]
Thanks for the report! The anomaly is a bug in the error printer (as reported in #5622). There should not be an error in the first place though.

PR #14667 fixes the underlying problem (a Coq 8.8 regression wrt to declaration of universe constraints).
