### ISSUE TITLE
[coqnative] Command line help

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#14516]
The coqnative tool doesn't support the `--help` option.

**Comment by Alizter** [comment]
Also is missing a `man` page.

**Comment by Zimmi48** [comment]
@ppedrot it would be great if you could fix this for 8.14.

**Comment by Blaisorblade** [comment]
(Kudos for adding coqnative!) BTW, should the manual spell out whether build tools can already harness coqnative? From the text I guess not yet but it'd be good to know either way.

https://github.com/coq/coq/blob/b7d10ab0ca355e2d109d201b0c0827edb171c292/doc/sphinx/practical-tools/utilities.rst

**Comment by ppedrot** [comment]
@Blaisorblade In 8.14, `coq_makefile` already uses `coqnative`. I don't know if your question referred to external users with their own build systems, but if so the answer is yes. The basic interface of `coqnative` shouldn't change, at worst we will have to add new flags for specific native settings but that's about it.

**Comment by Blaisorblade** [comment]
@ppedrot I was just wondering how to build `cmxs`es separately, after the `vo`s are built, which seems the main point of `coqnative` — but apparently that's not supported, so I posted in #13035 instead.

**Comment by ppedrot** [comment]
What? That's the whole point of coqnative. Just call it on the vo file and you'll get the cmxs files...

**Comment by Blaisorblade** [comment]
But I'll never do that by hand, just like I never invoke coqc by hand. Anyway, my question is off-topic here.
