### ISSUE TITLE
"destruct n as ->." anomaly

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14520]
```
Goal forall n, n + 0 = n.
destruct n as ->.
```

In master: `Anomaly "Uncaught exception Not_found."`

In 8.13.0: `Disjunctive/conjunctive pattern expected.`

Same behavior for (e)case/(e)induction/* inversion*/edestruct.

**Comment by herbelin** [comment]
Yet another instance of #14530, fixed in #14532.
