### ISSUE TITLE
Coq accepts nonsensical file structure

### ISSUE THREAD

**Issue by Columbus240** [coq/coq#14550]
#### Description of the problem
Unfinished proofs and unsolved obligations are accepted by Coq.

Consider a file foo.v with content
```coq
Require Import Coq.Program.Tactics.
Program Definition bar : exists n, n = 0 := _.
```
Then compiling this file with `coqc` terminates without error.

It’d be useful if Coq emitted an error like "There are unsolved obligations, go back and solve them", or at least a warning.

If we enclose the definition of `bar` in a section, then we get an appropriate error.
```coq
Require Import Coq.Program.Tactics.
Section baz.
Program Definition bar : exists n, n = 0 := _.
End baz.
```

A slightly related issue, consider
```coq
Section foo.
  Variable (var : unit).
  Lemma bar : var = tt.
End foo.
Fail Admitted.
```
Is there a reason why Coq accepts the `End foo.`? As interactive user, we arrive in an irrecoverable state (at least coq gives no hint of how to resolve it).

#### Coq Version
v8.13.2

**Comment by Columbus240** [comment]
I’ve got a little trouble, trying to understand the code of Coq. The error about unsolved proofs at the end of compiling a file is generated by
https://github.com/coq/coq/blob/bfd27a18d1d4bc2d63272af6e0138fe4303a462b/toplevel/ccompile.ml#L98-L105
which is called on lines [146](https://github.com/coq/coq/blob/bfd27a18d1d4bc2d63272af6e0138fe4303a462b/toplevel/ccompile.ml#L146) and [187](https://github.com/coq/coq/blob/bfd27a18d1d4bc2d63272af6e0138fe4303a462b/toplevel/ccompile.ml#L187) of the same file.
There is a function which generates the other warning (when having unsolved obligations when running `End`). https://github.com/coq/coq/blob/a1fac381817d65f589c908a6c26a4062bebca7d7/vernac/declare.ml#L990-L1000
Ideally, I’d like to call `check_solved_obligations` from `check_pending_proofs` or from elsewhere in ccompile.ml. But where should I take the "program" from to call `check_solved_obligations` with? During the function `compile`, there is only a `Vernac.State.t` available, which seems incompatible and unrelated to the argument types of `check_solved_obligations`.

**Comment by Columbus240** [comment]
I got it now. Found out, that the `freeze_interp_state` and `unfreeze_interp_state` functions existed. Will submit a PR.

**Comment by Columbus240** [comment]
The second case allows creating anomalies:
```coq
Section foo.
  Lemma bar : nat.
     pose true as baz.
End foo.
destruct baz.
```

**Comment by ejgallego** [comment]
Note that all your example involving sections are fixed on master, for the non-section case, indeed we need to strengthen the check in coqc.

**Comment by Columbus240** [comment]
Thanks for the remark and having a look. I saw the code in master that should prevent the section case, but wondered why it didn’t work when trying it with v8.13.2. 😅

**Comment by Columbus240** [comment]
About testing, I made an "output" test for this. But am not sure, whether it’s correct.

**Comment by Blaisorblade** [comment]
Changed the description to be appropriately scarier since in #14552 some agreed this is a critical bug.
