### ISSUE TITLE
Strange timeout behaviour

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#14567]
~~~coq
Fail Timeout 1 Check Prop : Prop.
Check ltac:(repeat pose 0). (* or any other command which takes a while *)
~~~
After about 1s the `repeat` will timeout.

This is a real problem when the command would otherwise terminate ;)

This causes random timeouts with proof general and -noinit, because PG runs `Timeout 1 Print Grammar tactic.` (and coqtop implicitly catches the error from `tactic` not being defined)

NB: AFAICT no bug with `Timeout 1 Fail`

**Comment by ppedrot** [comment]
FTR, evaluating the first line kills CoqIDE with a "coqtop died badly" error.
