### ISSUE TITLE
Anomalies when closing a section too soon

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#14564]
#### Version

Coq 8.13.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following way to close a section too soon causes an assertion failure.

```
From Coq Require Import Relations.Relations.

Set Universe Polymorphism.

Section Context.

Context (A : Type) (f : relation A).

Goal subrelation f f.
Proof.

End Context.

hnf; auto. Qed.
```

```
Anomaly "Universe Top.1 undefined." Please report at http://coq.inria.fr/bugs/.
```

If you remove `Set Universe Polymorphism`, the anomaly will not occur,
although after `hnf; auto.` we will be treated with another anomaly.

```
Anomaly "Signature and its instance do not match."
Please report at http://coq.inria.fr/bugs/.
```

#### Notes

This may be a duplicate of #14001 or #14550,
although the observable result of this bug is slightly different.

**Comment by herbelin** [comment]
This seems indeed fixed (presumably by #13790 which fixed #14001 in 8.14).

Apparently an 8.13-specific bug actually.
