### ISSUE TITLE
`Remove Hints` should be called `Hint Remove`

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#14572]
#### Description of the problem

`Remove Hints` stands out in the following list:

```
Remove Hints
Hint Constants	
Hint Constructors	
Hint Cut	
Hint Extern	
Hint Immediate	
Hint Mode	
Hint Opaque	
Hint Resolve	
Hint Rewrite	
Hint Transparent	
Hint Unfold	
Hint Variables	
Hint View for	
Hint View for apply	
Hint View for move
```

Shouldn't it be called `Hint Remove` to be consistent with the other commands?

#### Coq Version

```
$ coqc --version
The Coq Proof Assistant, version 8.13.1 (March 2021)
compiled on Mar 13 2021 10:35:46 with OCaml 4.11.1
```

**Comment by cpitclaudel** [comment]
> Shouldn't it be called Hint Remove to be consistent with the other commands?

I don't think so: I'd expect `Hint Remove` to add a new hint of kind `Remove`, not to remove one (all the other `Hint X` commands add hints, so I'd say the change would make things *less* consistent).

**Comment by Zimmi48** [comment]
Since not everyone agrees that it would make things more consistent and this would anyway be disruptive for limited gain, maybe we can close this?
