### ISSUE TITLE
Permutation_app' has wrong priority

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#14571]
#### Description of the problem

Why is the priority of `Permutation_app' : Proper (Permutation ==> Permutation ==> Permutation) app` level 10? This is higher than the priority 5 of `proper_subrelation` in `Morphisms`, which means that when looking for `Proper (_ ==> _ ==> _) app` with one of the underscores being `Permutation` the tactic `proper_subrelation` is triggered before the instance `Permutation_app'` is used. As shown in https://gitlab.mpi-sws.org/iris/stdpp/-/issues/114, this can result in a blow-up in instance search during setoid rewriting:

```coq
From stdpp Require Import gmultiset.

Typeclasses eauto := debug.

Lemma test {A B} `{Countable A} `{Countable B}
      (xs : list (A * list B)) (X Y: gmultiset (A * list B)) :
  xs ++ elements (X ⊎ Y) ≡ₚ xs ++ elements X ++ elements Y.
Proof.
  Time rewrite gmultiset_elements_disj_union.
  (* Very slow: takes like 1 sec, produces a type class trace of 85.000 lines *)
Abort.

(** Remove this instance, since its priority is 10, which is above the priority 5 of [proper_relation] *)
Global Remove Hints Permutation_app' : typeclass_instances.
(** Add it with the right priority (default = 0, since the instance has no premises) *)
Existing Instance Permutation_app'.

Lemma test {A B} `{Countable A} `{Countable B}
      (xs : list (A * list B)) (X Y: gmultiset (A * list B)) :
  xs ++ elements (X ⊎ Y) ≡ₚ xs ++ elements X ++ elements Y.
Proof.
  Time rewrite gmultiset_elements_disj_union.
  (* Immediate: takes like 0.02 sec, produces a type class trace of 40 lines *)
Abort.
```

#### Coq Version

```
$ coqc --version 
The Coq Proof Assistant, version 8.13.1 (March 2021)
compiled on Mar 13 2021 10:35:46 with OCaml 4.11.1
```

The above example uses std++ dev.2021-06-28.1.ddce76d7. (With newer versions of std++ this problem might disappear since we might repair the priority of the instance in std++ until it's fixed in all versions of Coq that we support).

**Comment by robbertkrebbers** [comment]
See https://gitlab.mpi-sws.org/iris/stdpp/-/merge_requests/291 for the workaround in std++.

**Comment by SkySkimmer** [comment]
See a884f7dcebed71608f395fe140722790367089e2
~~~
isolate instances about Permutation and PermutationA which may slow rewrite

 After discovering a rewrite in Ergo that takes a loooong time due
 to a bad interaction with the instances of Permutation and PermutationA :

 - PermutationA is now in a separate file SetoidPermutation
 - File Permutation.v isn't Require'd by SetoidList anymore
   nor MergeSort.v, just the definitions in Sorted.v
 - Attempt to put a priority on these instances.
~~~
Perhaps it's only the `Proper (_ ==> iff)` and `Proper (_ ==> eq)` instances which need the priority, or perhaps the file separation is really enough?

**Comment by robbertkrebbers** [comment]
I would hope that only the `Proper (_ ==> eq)` instances need the priority.

However, it's very hard to say, especially since the fix in that commit seems very ad-hoc, and the problem might also be fixed by other improvements to setoids since 2012. (The interaction between type class instances for setoids is extraordinary subtle...)

**Comment by robbertkrebbers** [comment]
Ok, turns out we have the same issue for `::` in std++...

```coq
From stdpp Require Import gmultiset.

Lemma test {A B} `{Countable A} `{Countable B}
      (x : A * B) (X Y: gmultiset (A * B)) :
  x :: elements (X ⊎ Y)  ≡ₚ x :: (elements X ++ elements Y).
Proof.
  Set Typeclasses Debug.
  by rewrite gmultiset_elements_disj_union. (* SLOW *)
Abort.

Global Remove Hints Permutation_cons : typeclass_instances.
Existing Instance Permutation_cons.

Lemma test {A B} `{Countable A} `{Countable B}
      (x : A * B) (X Y: gmultiset (A * B)) :
  x :: elements (X ⊎ Y)  ≡ₚ x :: (elements X ++ elements Y).
Proof.
  Set Typeclasses Debug.
  by rewrite gmultiset_elements_disj_union. (* Immediate *)
Abort.
```
