### ISSUE TITLE
slow lia conversion 

### ISSUE THREAD

**Issue by fajb** [coq/coq#14604]
#### Description of the problem

There is an efficiency problem with `lia` conversion test.
This happens in real code (cc @fakusb )
Instead of performing an implicit conversion test, a workaround is to perform an explicit equality test.
This is shown on the example below.

```coq
Require Import ZArith Lia.

(* mul z n = Z.of_nat n * z *) 
Fixpoint mul (x:Z) (n : nat) : Z :=
match n with
| O => 0%Z
| S n => mul x n + 1 * x%Z
end.

Ltac zchecker2 :=
let __wit := fresh "__wit" in
let __varmap := fresh "__varmap" in
let __ff := fresh "__ff" in
intros __wit __varmap __ff;
match goal with
| |- ?G => replace G with (Tauto.eval_bf (ZMicromega.Zeval_formula (VarMap.find 0%Z __varmap)) __ff)
end ;
[  (apply (ZMicromega.ZTautoChecker_sound __ff __wit) ; vm_compute ; reflexivity)
   | reflexivity].

Lemma test: forall z : Z, (0 <= z)%Z -> (0 <= mul z 100)%Z.
Proof.
cbn -[Z.mul Z.add].
intros.
Fail Timeout 2 xlia zchecker.
Time xlia zchecker2. (* Finished transaction in 0.016 secs (0.016u,0.s) (successful) *)
Qed.
```
Question for experts (maybe @ppedrot   or @SkySkimmer): is-it normal for the conversion test to be very slow in this case?
If so,  is `zchecker2` a robust workaround  ?

#### Coq Version
8.13.1

**Comment by ppedrot** [comment]
If I read correctly the code, we're apply a soundness theorem that has a reified conclusion, and we implicitly rely on conversion when applying for the kernel to check that the reified goal and its evaluated form are convertible. Indeed, this looks like a bad idea since the conversion algorithm can be lead astray in the first case, trying to compare two huge partially evaluated terms. I don't know why replace succeeds faster, it's probably due to a difference set of flags, or the order in which the conversion problem is presented is different. I don't think this is very robust though. IIRC we in ring we have clever tricks to orient the kernel in the correct way, basically forbidding to evaluate the huge computational parts of the goal. cc @silene since I believe he is fairly knowledgeable on the topic.

**Comment by JasonGross** [comment]
My guess is that the difference is that the conversion test is sensitive to direction (converting `x` with `y` has different performance than converting `y` with `x`).  Inded, replacing `reflexivity` with `symmetry; reflexivity` results in a slowdown.  You should not rely on `zchecker2` as a work-around, and should instead issue something like `Strategy -100 [<every identifier used in Zeval_formula>]`.  That is, you should determine what the list of things is that must be unfolded to convert from the reified version to the unreified version, and instruct the kernel to unfold these things early.

I found that if I issue
```
Global Strategy -100 [VarMap.find ZMicromega.Zeval_formula ZMicromega.Zeval_op2 ZMicromega.Zeval_pop2 ZMicromega.Zeval_bop2 ZMicromega.Zeval_expr Tauto.eval_bf Tauto.eval_f Tauto.e_rtyp Tauto.eTT Tauto.eFF Tauto.eAND Tauto.eOR Tauto.eNOT Tauto.eIMPL Tauto.eIFF].
```
then `xlia zchecker` is instantaneous.

**Comment by silene** [comment]
I agree. `Strategy` is the best way to perform the conversion check of a reflection-based tactic. (It is far from perfect, but this is currently the closest we can get from manually guiding the conversion check.)

**Comment by fajb** [comment]
I was not aware of `Strategy`.
Thanks for the insight @JasonGross .
Is there a reason to set a level (-100) and not **expand** ?
I'll open a PR and do that.

**Comment by silene** [comment]
> Is there a reason to set a level (-100) and not expand ?

As far as the convertibility check is concerned, expand would also work. But expand is so strong that it might cause some slowdown at the time of applying `ZTautoChecker_sound`. (To be more precise, a negative level is expanded before a standard constant but after a let-in construct.) So, this needs testing.

**Comment by JasonGross** [comment]
Setting a negative level allows users to tweak conversation further.  Maybe someone needs these constants to be unfolded after some wrapper they define, for example.  But I don't have any particularly strong reason.

**Comment by fakusb** [comment]
Great, this solves one problem I had often, see this example that was slow before, but gets faster with the addition of `Strategy expand [ ZMicromega.Zeval_expr ]`.
