### ISSUE TITLE
Debugger part 3: missing source code location for some stack frames

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14649]
Using the code in #14644 and stepping through `ToFancyWithCasts.v` in `fiat_crypto` with a breakpoint at `Reify.v` line 254 ("=> ltac:(**let** P := (eval cbv delta [P'] in P') in'"), `tactic_debug.ml` gets a `Loc.t` of `None` for the highlighted stack frame.

@JasonGross Do you have any idea how the call to `reify_list` (in `Reify.v` line 679) differs from other calls to Ltac tactics?  That's the next frame down that says "??? LtacConstrInterp".  The callee appears to be just a few lines above in the same file.

![image](https://user-images.githubusercontent.com/1253341/125546759-db6dade0-3601-4f0f-9e50-8fb5e52a7dd7.png)

**Comment by JasonGross** [comment]
It looks like any tactic call located inside `ltac:(...)` inside a `constr:(...)` gets a location of None?  (And the enclosing `ltac:(....)` gets `??? LtacConstrInterp`?)  Presumably you'd get something similar with
```coq
Ltac foo := idtac "foo".
Ltac bar := idtac "bar"; foo.
Ltac baz := idtac "baz0"; let __ := constr:(ltac:(bar; exact I)) in idtac "baz1".
Goal True.
  baz.
```
on the call to `bar`?

Or are you asking about what in the Coq source code makes `constr:(... ltac:(...) ...)` special?

**Comment by jfehrle** [comment]
Sometimes it takes me a very long time to figure the Ltac internal details since there's still a lot I don't know about them--sometimes it takes me a couple hours to figure things out, sometimes more than a day or two.  I was hoping you might notice a helpful clue right away (but I wasn't counting on it).

I don't see the problem with your example.  Let me investigate this and some other glitches a bit more.  If I get stuck, perhaps you can help me create smaller examples.  And I'd be delighted for you to try out #14644 and give feedback.

![image](https://user-images.githubusercontent.com/1253341/125557960-e07b382d-9dc6-47dd-a829-495249eb7bd6.png)

![image](https://user-images.githubusercontent.com/1253341/125557990-10530ffd-ea62-42e0-8828-fc42a96b1842.png)

![image](https://user-images.githubusercontent.com/1253341/125558027-ca5d4f99-b00e-4cf7-82a1-10b9f07aa04d.png)

![image](https://user-images.githubusercontent.com/1253341/125558075-be012c1c-a9df-40de-9461-bd635f2f882b.png)

![image](https://user-images.githubusercontent.com/1253341/125558114-c8a5d64b-9c21-4956-a8c0-6d75ddd34546.png)

**Comment by jfehrle** [comment]
Fixed this.  I was mishandling the location info from LtacConstrInterp.
