### ISSUE TITLE
Fail Timeout produces codidetop died badly

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#14642]
#### Description of the problem
In CoqIDE 8.13.2 (tested under Windows) the following code trows `coqidetop died badly` on `Fail Timeout 1 congruence.`
It works as expected without `Fail` or without `Timeout 1`.
```coq
Fixpoint slow (n: nat): bool :=
  match n with
  | O => true
  | S m => andb (slow m) (slow (pred m))
  end.

Parameter f: nat -> nat.

Definition foo(n b: nat): Prop :=
   if slow n then (forall a, f a = f b) else True.

Goal forall a b, foo 27 b -> f a = f b.
Proof. Fail Timeout 1 congruence. Admitted.
```

**Comment by SkySkimmer** [comment]
Probably duplicate https://github.com/coq/coq/issues/14567

**Comment by mrhaandi** [comment]
> Probably duplicate #14567

Possibly. However, I was told that in proof general the above snipped worked fine.
Under Windows in CoqIDE `Fail Timeout 1 Check Prop : Prop.` works as expected.
