### ISSUE TITLE
Makefile.build should not have byte:world

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#14658]
This is just nonsense, either we should do the right calls to dune (I have no clue what they are) or remove the target.

**Comment by Zimmi48** [comment]
What is the difference between `./configure -byte-only && make byte` and `./configure -byte-only && make`?

**Comment by ejgallego** [comment]
> What is the difference between `./configure -byte-only && make byte` and `./configure -byte-only && make`?

None as of today, `make byte` is just an alias for `make world`.

Summarizing the discussion on the PR [which was very long]
- If the goal is to check all OCaml files as fast a possible, `make -f Makefile.dune check` is faster
- If you want to compile `.vo` files, it is almost always faster to use a native `coqc`
- Make-based compilation mode for native was much slower, but Dune in dev mode uses -opaque, largely negating the benefits of byte-only the moment you compile some .vo

So indeed, we kept support for `-byte-only`, but there is little motivation to actually keep it, if we look at the numbers.

**Comment by Zimmi48** [comment]
> So indeed, we kept support for `-byte-only`, but there is little motivation to actually keep it, if we look at the numbers.

I guess the `-byte-only` mode does make sense if you want to produce a portable Coq. But I agree with Gaëtan here: the alias `byte: world` should be removed (even if the `-byte-only` option of `configure` is kept).

**Comment by ejgallego** [comment]
> I guess the `-byte-only` mode does make sense if you want to produce a portable Coq.

What is a portable Coq? [Never heard of that sorry]

**Comment by Zimmi48** [comment]
OCaml bytecode is supposed to be portable (to machines where `ocamlrun` is present even if OCaml cannot compile to their native backend). That can also be useful to ensure that the same pre-built binary will work across a variety of machines. (Typical use case I have in mind is when distributing pre-compiled binaries to students. I have already done that in the context of OCaml teaching, but this was unrelated to Coq.)

**Comment by ejgallego** [comment]
> OCaml bytecode is supposed to be portable (to machines where `ocamlrun` is present even if OCaml cannot compile to their native backend). That can also be useful to ensure that the same pre-built binary will work across a variety of machines. (Typical use case I have in mind is when distributing pre-compiled binaries to students. I have already done that in the context of OCaml teaching, but this was unrelated to Coq.)

I'm much afraid this won't work for Coq without significant work as we have a whole C runtime the kernel links to; there are other issues also. IMHO would we like to support something like, `-byte-only` is not useful at all.
