### ISSUE TITLE
`Print Graph` conflicts with `Print`ing of terms called `Graph`.

### ISSUE THREAD

**Issue by Alizter** [coq/coq#14655]
#### Description of the problem

The vernacular command `Print Graph` stops users from printing terms called `Graph`. I think it should be replaced with something like `Print Coercion Graph`.

#### Coq Version

8.15+alpha

**Comment by herbelin** [comment]
This is not the only case of collision. The standard workaround is to use `Print Term Graph`.

**Comment by Zimmi48** [comment]
Indeed, I think these (many) collisions with `Print` commands are well-known and the workaround is already documented: https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#displaying

So I propose to close as "won't fix".
