### ISSUE TITLE
dune debug not working

### ISSUE THREAD

**Issue by Alizter** [coq/coq#14653]
In the `/dev/doc/build-system.dune.md` manual, it says to debug something built with dune do the following:
```
dune exec -- ./dev/dune_db coqtop
```

However I immediately get a permission error:
```
Error: execve: /home/ali/coq/_build/default/dev/dune_db: Permission denied
```
It seems the permissions for `_build/default/dev/dune_db` are funny.

cc @ejgallego 

### Coq version:
```
f684f34eed7889cbced249630e4ffe9306b1401b
```

**Comment by SkySkimmer** [comment]
That's a typo, should be `dune-dbg`

**Comment by Alizter** [comment]
Ah ok, it should be `dune-dbg.in`. I'll update the doc.

**Comment by Alizter** [comment]
Hmm, it seems that this all fine actually. I just have trouble reading. Closing.

**Comment by ejgallego** [comment]
Indeed, the correct line is `dune exec -- dev/dune-dbg coqc foo.v`
