### ISSUE TITLE
congruence loops on evar

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#14662]
#### Description of the problem

`congruence` loops on evar conclusion. Here is an overview over failing/working examples:
```coq
Goal False.
Proof.
  evar (e : Prop). assert e.
  { subst e. Fail Timeout 5 congruence. (* infinite loop *)
Abort.

Goal False.
Proof.
  evar (e : Prop). assert (e -> e).
  { subst e. Fail Timeout 5 congruence. (* infinite loop *)
Abort.

Goal False.
Proof.
  evar (e : Prop). assert (id e -> id e).
  { subst e. congruence. (* this works as expected *) }
Abort.  
```

This is also observed in #10210
Suggestion: `congruence` should fail gracefully (but not on all open goals, see third example).

Alternative minimal example:
```coq
Goal exists (x : Prop), x -> x.
Proof.
  eexists. Timeout 1 congruence.
Abort.
```

#### Coq Version
8.13.2

**Comment by mrhaandi** [comment]
The problem appears to be deeper (possibly in `repeat intro`):
```coq
Goal False.
Proof.
  evar (e : Prop). assert e.
  { subst e. Fail Timeout 1 repeat intro. (* infinite loop *)
Abort.
```

**Comment by herbelin** [comment]
What to do? It seems legitimate, when `intro`-ing, to force a goal evar to be a functional type?

**Comment by herbelin** [comment]
Actually, a possible solution in the OCaml code of `congruence` would be to do `tclREPEAT (tclTHEN (tclTRY hnf_in_concl)) intro` (i.e. reducing the head constant if any - e.g `not` - but without forcing expansion of evars).

**Comment by mrhaandi** [comment]
> Actually, a possible solution in the OCaml code of `congruence` would be to do `tclREPEAT (tclTHEN (tclTRY hnf_in_concl)) intro` (i.e. reducing the head constant if any - e.g `not` - but without forcing expansion of evars).

I agree. Since it fits the theme of PR #14650, I added the proposed fix (and a test case) there.

**Comment by mrhaandi** [comment]
The suggestion `tclREPEAT (tclTHEN (tclTRY hnf_in_concl)) intro` has disadvantages.
Consider `Goal let a := True in a.`.
`hnf; intros.` behaves differently from `repeat intro`.
I'm now looking at
`tclREPEAT (tclFIRST [intro; tclTHEN hnf_in_concl intro])`
