### ISSUE TITLE
Switch bench to iris/examples

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#14702]
With https://github.com/coq/coq/pull/12969 we switched the Coq CI to test iris/examples instead of lambda-rust. It was my expectation that with this change, lambda-rust no longer needs to be compatible with Coq master, so we stopped that CI job.

However, it looks like the Coq bench suite still uses lambda-rust, not iris/examples. I have no idea where that configuration is stored so it'd be great if someone could update this. :)

**Comment by ppedrot** [comment]
The bench relies on opam packages. Is there one for iris/examples?

**Comment by RalfJung** [comment]
Now there is: https://gitlab.mpi-sws.org/iris/opam/-/blob/master/packages/coq-iris-examples/coq-iris-examples.dev.2021-07-23.0.a24a93f3/opam

**Comment by RalfJung** [comment]
But note that this is a package for a particular git version of iris/examples. Does bench pin dependencies or should it use the latest versions? I am not sure what we did for lambda-rust here.
