### ISSUE TITLE
`tactic + number` is confusing

### ISSUE THREAD

**Issue by whonore** [coq/coq#14719]
#### Description of the problem

Tactics of the form `tac + [0-9]+` are accepted as long as `tac` doesn't fail, which can be confusing in cases like the following:

```coq
Definition x : nat.
Proof. exact 1 + 1. Defined.

Goal x = 1. (* not 2 *)
Proof. reflexivity. Qed.
```

Of course one can avoid this with parentheses and maybe it isn't technically a bug if `1` is somehow a valid tactic expression, but it's definitely surprising.

#### Coq Version

All recent (8.10-8.14) versions at least.

**Comment by ppedrot** [comment]
Typical (pun intended) class of problems solved by Ltac2.

**Comment by Alizter** [comment]
This seems to be a bug since `1` is not a valid ltac expression. `+` is definitely weird but you can do things like
```coq
Definition x : nat.
exact 1 + reflexivity.
```
which is correct but you can't do
```coq
Definition x : nat.
exact 1 + foo.
```
since `foo` is not an ltac expression. So what made coq think `1` is?

**Comment by SkySkimmer** [comment]
`foo` is an ltac expression, the error you get is not a syntax error (for instance `Fail exact 1 + foo.` is a suceeding command).

I don't know to what extent we could check genarg types in the intern phase, however that seems to be the only way to get an error here.

**Comment by JasonGross** [comment]
> So what made coq think `1` is?

`1` is a valid ltac expression, consider:
```coq
let x := 1 in fail x.
```

**Comment by ppedrot** [comment]
I think this is a WONTFIX, Ltac1 will never be typed statically.
