### ISSUE TITLE
How can adding a print statement in Genarg.create_arg make coqIDE blow up?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14739]
While trying to learn more about some internals, I added this print statement in `Genarg.create_arg`:

`Printf.printf "create_arg %s\n%!" name;`

and got the following very unexpected results:

* The console shows this output:

```
Handshake with proofworker:0 failed: Failure("Marshal.data_size: bad object")
Gtk-Message: 22:39:00.557: GtkDialog mapped without a transient parent. This is discouraged.
[DEBUG] Coqtop reader failed, resetting: Coq.TubeError("HUP")
Gtk-Message: 22:39:00.594: GtkDialog mapped without a transient parent. This is discouraged.
[DEBUG] Coqtop reader failed, resetting: Coq.TubeError("HUP")
   <repeat last 2 lines 14 times>
```

* 18 error dialogs pop up all at once, such as this one (the text "unit" varies):

![image](https://user-images.githubusercontent.com/1253341/127964288-5a7dd624-754c-41d2-bfa6-8399e56cd682.png)

* CoqIDE shows a bunch of sessions with odd names (perhaps a side effect of the dialogs?):

![image](https://user-images.githubusercontent.com/1253341/127964581-bc881b36-0a18-4b04-9a37-395ad828527d.png)

I don't see why a print statement would cause a marshalling error.  If I use `eprintf` there is no problem.  How is this happening?

What is the purpose of `Genarg` and `Dyn`?  I get that they're for registering some data but I don't see the bigger reason that they are used.

Thanks.

**Comment by SkySkimmer** [comment]
>I don't see why a print statement would cause a marshalling error. If I use eprintf there is no problem. How is this happening?

coqidetop communicates with coqide through stdout, so printing stuff breaks it.

**Comment by herbelin** [comment]
> What is the purpose of `Genarg` and `Dyn`?

Hi, they are a way to encapsulate different types and their methods under a common OCaml type. You already met genarg I think in vernac and tactic extensions. To each genarg are associated a type as AST ("raw"), a type as interpreted AST ("glob"), a type as typed object ("typed"), as well as, generally, a parsing rule, a printer rule, and interpretation methods ("intern" from raw to glob and "interp" from glob to typed).

**Comment by jfehrle** [comment]
> coqidetop communicates with coqide through stdout, so printing stuff breaks it.

Really?  I don't see how that's consistent with this behavior:
* I've been using `Printf.printf` routinely on the server side to debug CoqIDE without previously seeing anything like this
* The output for the printf in question appears on the console

**Comment by ppedrot** [comment]
You're probably printing at initialization time, and coqide does not like that because it's not expecting any messages before the handshake. In any case, I don't think that an issue is the right place to discuss this kind of situation since 1. it's introducing communication impedance and 2. it's not a Coq bug but a problem with dev code, so this would better be discussed on Zulip.

**Comment by jfehrle** [comment]
OK, thanks--though I did label this as a question.
