### ISSUE TITLE
coqide opam package does not have adequate system dependencies

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14769]
#### Description of the problem

`opam install coqide` says
```
The following system packages will first need to be installed:
    libcairo2-dev libexpat1-dev libgmp-dev libgtk-3-dev libgtksourceview-3.0-dev pkg-config
```
However, adwaita-icon-theme-full must also be installed (at least on Ubuntu) for all the icons to show up.

#### Coq Version

8.13.2

**Comment by Zimmi48** [comment]
From where are you installing the package? From the main `opam-repository` I suppose? The CoqIDE package depends on `conf-adwaita-icon-theme` which, according to https://github.com/ocaml/opam-repository/blob/master/packages/conf-adwaita-icon-theme/conf-adwaita-icon-theme.1/opam, should ensure that `adwaita-icon-theme` is installed on Ubuntu. Do you mean that this package should be fixed to install `adwaita-icon-theme-full` instead? In any case, that's probably an issue to report to the opam-repository maintainers at https://github.com/ocaml/opam-repository/issues.

**Comment by JasonGross** [comment]
CoqIDE, at least, requires `adwaita-icon-theme-full`.  I'm not sure whether this means that we need a separate conf package, or if the existing conf package should be changed, but certainly one of these needs to happen.

**Comment by Zimmi48** [comment]
OK. That's really something to ask the opam-repository maintainers. I don't think we can decide for them.
