### ISSUE TITLE
Number Notations incorrectly think that notations containing nested applications don't denote to references

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14806]
#### Description of the problem

```coq
Declare Scope foo_scope.
Module Good.
  Record aa (x  : Set) := { the_thing : Number.number }.
  Notation aa12 := (aa nat) (only parsing).
  Definition to_aa (n: Number.number) : aa12 := Build_aa _ n.
  Definition from_aa (x: aa12) : Number.number := the_thing _ x.
  Number Notation aa12 to_aa from_aa : foo_scope.
End Good.
Module Bad.
  Record aa (x : Set) := { the_thing : Number.number }.
  Notation aa12 := (aa (sum nat nat)) (only parsing).
  Definition to_aa (n: Number.number) : aa12 := Build_aa _ n.
  Definition from_aa (x: aa12) : Number.number := the_thing _ x.
  Number Notation aa12 to_aa from_aa : foo_scope. (* Error: aa12 is bound to a notation that does not denote a reference. *)
End Bad.
```

Workaround: make a `Definition` for the parameters (such as `sum nat nat`) and use that instead in the notation.

cc @herbelin @proux01 ?  I might take a look at this if I get a chance, but I imagine it's just that we need to add an extra case for app nodes somewhere in the conversion.

cc @andrew-appel

#### Coq Version

8.13

**Comment by JasonGross** [comment]
cc @coq/extensible-syntax-maintainers

**Comment by proux01** [comment]
> I might take a look at this if I get a chance, but I imagine it's just that we need to add an extra case for app nodes somewhere in the conversion.

Feel free to (I'll review your PR). But if I were to fix this myself, I'd probably just improve the error message, considering how easy it is to workaround.

**Comment by andrew-appel** [comment]
"Improving" the error message by advising the use of a horrible work-around is not very nice.  But really, why does Number Notation require that the first qualid be a designator of an Inductive type?  Why can't it just be a Definition?  That's really what I want in some cases.  The use of an abbreviation (as suggested in the reference manual) is just another work-around.

**Comment by proux01** [comment]
Thanks for your work, I acknowledge the bug should actually be fixed and I'm currently working on it.

Note that it seems that your `rebuild_float` function can be replaced by `erase` that already exists in Flocq.
