### ISSUE TITLE
Mutual fixpoints are not printed correctly

### ISSUE THREAD

**Issue by t6s** [coq/coq#14815]
#### Description of the problem

`Print <mutual-recursively defined ident>` does not print a valid term.
The keyword `fix` is wrongly overridden by `with`, thus the result looks like `with f ... with g ... for f`.

Example:
```
$ coqtop
Welcome to Coq 8.13.2 (April 2021)

Coq < Fixpoint f n := match n with S n => g n | O => O end with g n := match n with S n => f n | O => O end.
f is defined
g is defined
f, g are recursively defined (guarded respectively on 1st, 1st arguments)

Coq < Print f.
f =
with f (n : nat) : nat :=
  match n with
  | 0 => 0
  | S n0 => g n0
  end
with g (n : nat) : nat :=
  match n with
  | 0 => 0
  | S n0 => f n0
  end
for
f
     : nat -> nat

Arguments f _%nat_scope
```

#### Coq Version
Checked in 8.13.2 and github master.

#### Possible Fix

The following change in the printer addressed the issue in my example,
though I am not quite sure if this encompasses all cases.

```
diff --git a/printing/ppconstr.ml b/printing/ppconstr.ml
index 8da6642965..2fd0fffe07 100644
--- a/printing/ppconstr.ml
+++ b/printing/ppconstr.ml
@@ -461,7 +461,8 @@ let tag_var = tag Tag.variable
   let pr_recursive kw pr_decl id = function
     | [] -> anomaly (Pp.str "(co)fixpoint with no definition.")
     | [d1] -> pr_decl kw false d1
-    | dl ->
+    | d1::dl ->
+      pr_decl kw true d1 ++ fnl() ++
       prlist_with_sep (fun () -> fnl())
         (pr_decl "with" true) dl ++
         fnl() ++ keyword "for" ++ spc () ++ pr_id id
```

**Comment by herbelin** [comment]
Thanks a lot for your report. This is a regression introduced in 8.12 by d310030a70c (my bad, I'm verry sorry). Your patch is good. Since you already made the patch, would you be interested in submitting a pull request with a patch fixing the bug together with a test?
