### ISSUE TITLE
Anomaly when registering a float primitive without prior registration of #float64_type

### ISSUE THREAD

**Issue by herbelin** [coq/coq#14814]
#### Description of the problem

Probably a rather superficial problem but, in the default environment, the following raises an anomaly:
```
Primitive abs := #float64_abs.
```
Apparently, it expected a prior `Primitive float := #float64_type.`

Cc @proux01

#### Coq Version

master

**Comment by proux01** [comment]
@herbelin thanks for reporting this. We could indeed put a nicer error. However, I'm not convinced it is worth the effort. Indeed, these `Primitive` commands are expected to be used only in very specific files of standard libraries, not by the casual user. Moreover, if we add an error, we should document it which would IMHO just clutter the manual. So I'd rather do nothing and close this issue. But let me know if you have further arguments in favor of a proper error message.

**Comment by JasonGross** [comment]
Anomalies should be presumed-impossible cases, barring rogue plugin code, and efficiency concerns of low-level Ltac2 code aside.  I think there should be an error message here, and it's fine to leave it undocumented.

**Comment by herbelin** [comment]
Yes, anomalies are supposed to report broken invariants of the OCaml code. The OCaml code itself is supposed to be self-contained and not to rely on assumptions from the Coq level.

There are already errors in some cases e.g. `The type int must be registered before this construction can be typechecked` or `The type array must be registered before this construction can be typechecked`, so, it is just a matter of turning a few anomalies into errors.

**Comment by proux01** [comment]
Indeed, this should be fixed in #14831
