### ISSUE TITLE
`#[local] Ltac2 Set` should be supported

### ISSUE THREAD

**Issue by Janno** [coq/coq#14838]
EDIT: after https://github.com/coq/coq/pull/15275 it has become an "unsupported attribute" error

#### Description of the problem

In the following snippet, despite being marked `#[local]`, the mutation of `test` in `A` leaks into modules that import `A`.
```coq
From Ltac2 Require Import Ltac2.
Ltac2 mutable test := true.
Module A. #[local] Ltac2 Set test := false. End A.
Ltac2 Eval test.                (* original value, as expected. *)
Import A.
Ltac2 Eval test.                (* mutated value; unexpected! *)
```
In fact, `#[local]` seems to have no noticeable effect.

Here's another example. I am not really sure what happens here. I would expect `false, true, false` but we are seeing `true, true, false` which makes no sense to me. If `B` carries the side effect of mutating `test`, why isn't it mutated in `B` itself?
```coq
From Ltac2 Require Import Ltac2.
Ltac2 mutable test := true.
Module B.
  Module A. #[local] Ltac2 Set test := false. End A.
  Ltac2 Eval test.                (* original value, as expected. *)
End B.
Ltac2 Eval test.                (* original value, as expected. *)
Import B.
Ltac2 Eval test.                (* mutated value; unexpected! *)
```

As a workaround one can use sections to contain the mutation.

The problem was originally observed in multiple files, not modules, but I suspect the root cause is the same. If necessary I can add examples with multiple files (which are always more annoying to test).

#### Coq Version
8.13.2

**Comment by gmevel** [comment]
> As a workaround one can use sections to contain the mutation.

More precisely, sections appear to contain the mutation, with or without `#[local]`. So it seems that the attribute is silently ignored.

> The problem was originally observed in multiple files, not modules, but I suspect the root cause is the same.

For what’s worth, here is a multiple-file reproducing example.

```coq
(* a.v *)
From Ltac2 Require Import Ltac2.

Ltac2 mutable x := false.
#[local] Ltac2 Set x := true.
```

```coq
(* b.v *)
From Ltac2 Require Import Ltac2.

Require a.
Ltac2 Eval a.x. (* false *)

Import a.
Ltac2 Eval a.x. (* true *)
Ltac2 Eval x. (* true *)
```

The surprising behavior also manifests when `Ltac2 Set` is enclosed within a module:

```coq
(* a.v *)
From Ltac2 Require Import Ltac2.

Ltac2 mutable x := false.
Module mod.
  #[local] Ltac2 Set x := true.
End mod.
```

but not when within a section:

```coq
(* a.v *)
From Ltac2 Require Import Ltac2.

Ltac2 mutable x := false.
Section sec.
  Ltac2 Set x := true. (* note how #[local] is unneeded here *)
End sec.
```

**Comment by Alizter** [comment]
cc @ppedrot
