### ISSUE TITLE
Broken extraction for record

### ISSUE THREAD

**Issue by fajb** [coq/coq#14843]
#### Description of the problem
For the following, the extracted OCaml code does not compile:
```coq
Record r : Type := mk { f1 : unit -> unit; f2: unit -> unit }.

Module M.
Definition f1 (ti:unit) : unit := tt.
Definition f2 (ti:unit) : unit := tt.

Definition cf := mk f1 f2.

End M.
```
- Using `Separate Extraction`,
Modules `Coq__1` and `Coq__2` define the functions f1 and f2 for accessing the fields f1 and f2.
- Using `Extraction "file" M.cf`, the modules Coq__1, Coq__2 are not generated.
In both cases, we have 
```ocaml
let cf =  { Coq__1.f1 = f1; Coq__2.f2 = f2 }
```
and the error "Unbound record field Coq__1.f1" 
#### Coq Version
8.13.1 (also present in 8.9)

**Comment by herbelin** [comment]
Thanks for the report. Fixed in #17324.
