### ISSUE TITLE
Require Import and Export with filtered_import

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#14872]
#### Description of the problem

@Blaisorblade recently notified me of the new `filtered_import` feature (https://coq.inria.fr/distrib/V8.12.2/refman/language/core/modules.html#coq:cmd.import). This is great. (PS: It seems to be missing in the CHANGELOG).

It would be even greater it one could use it with `Require Import` and `Require Export` as well. For example, if one could write `Require Export StrictProp (Squash)`.

Currently you have to write (the more ugly):

```coq
Require StrictProp.
Export StrictProp (Squash).
```

#### Coq Version

```
The Coq Proof Assistant, version 8.13.1 (March 2021)
compiled on Mar 13 2021 10:35:46 with OCaml 4.11.1
```

**Comment by Blaisorblade** [comment]
FTR, see concerns around this question: https://github.com/coq/coq/pull/11820#issuecomment-606474927:

> The risk is to be a bit confusing because `Require Import Foo(mydef)` will bring all long names in Foo into scope. But I don't have a strong opinion.

But IMHO that's the expected semantics — `Require Import Foo(mydef)` seems equivalent to `Require Foo` + `Import Foo(mydef)` (it's not, for other reasons).

**Comment by SkySkimmer** [comment]
The current code is a bit hard to work with, but after https://github.com/coq/coq/pull/15347 this request may be doable.
