### ISSUE TITLE
Spurious new lines in the output of configure.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#14888]
#### Description of the problem

I ran `./configure -profile devel` and got the following lines in the output:

```
2.8.2 / 282            
Warning: You are using Dune < 2.9, the install procedure will not respect the -docdir and -configdir configure directives; please see dev/doc/INSTALL.make.md for more information
4.09.1 / 4091
You have OCaml 4.09.1. Good!
1.8.1 / 181
You have OCamlfind 1.8.1. Good!
You have native-code compilation. Good!
1.11 / 1110
You have the Zarith library 1.11 installed. Good!
3.1.1 / 311
```

I believe that all the lines of the form `XXX / XXX` are debug lines that weren't meant to be merged into master. Is that a correct interpretation @ejgallego?

#### Coq Version

cd8f5031c0915ca7d57287374dc36fde7d820a67

**Comment by ejgallego** [comment]
Ups sorry, indeed that was a bad rebase.
