### ISSUE TITLE
Unable to run suite tests locally

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14887]
After trying many permutations, I'm unable to usefully run the test suite locally (Ubuntu on WSL).

I did `./configure -profile devel` and `make -f Makefile.dune world` to set up.

Then, following the instructions in `build-system.dune.md`:
1. `make -C test-suite` runs the tests, but it appears that every test fails with `Error: Unable to locate library Prelude with prefix Coq.` (`COQLIB` not defined).
2. Running the same command after ```export COQLIB=`pwd` ``` in the top directory of the source tree gives the same messages
3. Trying `dune runtest`, many many tests get `Error: Cannot find plugins directory`
4. `COQLIB` pointing to `.../_build/default` is not different

Also, how can I run a single test presently?

**Comment by Zimmi48** [comment]
It seems that you are still confusing the two build procedures. You shouldn't run `./configure -profile devel` if your intent is to run `make -f Makefile.dune world`. The two procedures can only be used together up to a certain point. The test-suite is one of these points.

`make -C test-suite` after `make -f Makefile.dune world` (with no `./configure -profile devel`) will work just fine (I checked this and also checked that I could reproduce your problem if I had run `./configure -profile devel` before).

You shouldn't need to set up `COQLIB` manually (but if you did, setting it to `pwd` wouldn't make sense as the build outputs are under `_build/default`).

>Also, how can I run a single test presently?

Example:

```
make -C test-suite success/export_hint.v.log
```

(we should document this in the test-suite README)

**Comment by ejgallego** [comment]
Actually the profile devel thing should work or emit a warning, i had in my todo file as a bug.

**Comment by Zimmi48** [comment]
@ejgallego I let you put the labels back if you want to keep this open.

**Comment by jfehrle** [comment]
@Zimmi48 At a minimum, this should be clearly mentioned in our developer documentation for using dune.  How are others supposed to discover the limitation?  If such key details are communicated only in Zulip, emails or posts, they're not discoverable afterwards.  An error message for this case would be much better.

**Comment by Zimmi48** [comment]
At the moment, the [documentation](https://github.com/coq/coq/blob/master/INSTALL.md#choice-of-build-and-installation-procedure) contains:

>Note that mixing the two systems is not perfectly supported and may lead to confusing behavior.

I agree that this is probably insufficient and getting a clear error message would be much better. Probably what is being done in #14890.

**Comment by jfehrle** [comment]
Yeah.  Another part of it is that what works or doesn't work in Dune has been evolving rapidly (with some bugs along the way).  It's hard to keep track.

**Comment by jfehrle** [comment]
This is better, thanks.

Is there a way to get an incremental build of the test suite from Dune?  `make -f Makefile.dune test-suite` seems to always run the full test suite rather than just the out of date tests.  Due to some local file system issues, I get some random "Permission denied" errors that makes it unlikely a full run will succeed.  I can open another issue if you like.

**Comment by Zimmi48** [comment]
From Dune? Not yet (there is a plan to port the test-suite to Dune and this will happen then).
