### ISSUE TITLE
Wish: a Print Notation command

### ISSUE THREAD

**Issue by ana-borges** [coq/coq#14907]
#### Description of the problem

To my knowledge, there is no nice way of finding details about a notation, such as its associativity or priority.
We do have `Print Grammar constr.`, but that's a lot of information when you just want to find the associativity of a specific notation.

It would be nice to have a command, for example `Print Notation "+"`, that provides this kind of information.
The information available in the error message from trying to redefine a notation at a different level would already be nice.

See this [zulip discussion](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Command.20to.20know.20if.20notation.20is.20left.20or.20right.20assoc.20.3F).

#### Coq Version
8.14

**Comment by gares** [comment]
IMO we could improve Locate:
```
Coq < Locate "a + b".
Notation "x + y" := (Nat.add x y) : nat_scope (default interpretation)
Notation "x + y" := (sum x y) : type_scope
```

**Comment by Alizter** [comment]
>That's sadly bound to create quite a few compatibility problems IIUC how some UIs are using Locate :S

What exactly is the problem here? Isn't it up to the maintainers of those UIs to adapt to upstream changes?

**Comment by Zimmi48** [comment]
Agreed. We should not stop improving user facing commands because some tools use them programmatically.

**Comment by MSoegtropIMC** [comment]
There is `Print Grammar constr.` which prints the current grammar of Gallina terms.

**Comment by Alizter** [comment]
@MSoegtropIMC That was mentioned in the original post. The problem is that there is a lot of information there and no clear way to extract what you need.

**Comment by MSoegtropIMC** [comment]
Ah sorry, I missed this. I am happy with `Print Grammar constr` because in my experience it doesn't make that much sense to look at an isolated operator. The levels only make sense in connection with the levels of other operators. Also I like to diff the output of `Print Grammar constr` in different scoping environments.

**Comment by Zimmi48** [comment]
Related to #14486.
