### ISSUE TITLE
Inductives satisfying the refman's positivity criteria are rejected by the implementation (or, my math is wrong)

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#14938]
#### Description of the problem

I was reading through [this question](https://stackoverflow.com/questions/56143587/why-is-my-definition-not-allowed-because-of-strict-positivity) on StackOverflow.  Simplified, the example is this:

```coq
Inductive Inner (A : Type) : Type := inner : Inner bool -> Inner A.
Inductive Outer := outer : Inner Outer -> Outer.
```

(Ignore for a moment the fact that the first type is empty)
Coq rejects the second inductive:

```
Error: Non strictly positive occurrence of "Outer" in "Inner Outer -> Outer".
```

My math is likely wrong, but following the rules in the refman suggests that this type should not be rejected:

1. [Correctness rules](https://coq.inria.fr/refman/language/core/inductive.html#correctness-rules)
   ![image](https://user-images.githubusercontent.com/8181630/134818263-edc17df1-7694-4c57-b144-a101f87ae901.png)
2. [Positivity condition](https://coq.inria.fr/refman/language/core/inductive.html#positivity-condition)   
   ![image](https://user-images.githubusercontent.com/8181630/134818296-e5250c93-d136-4110-ad92-a2b2e1956011.png)
   Here,
   ```
   X = Outer
   T = forall x: Inner X, X
   ```
   So we're in the second case with
   ```
   U = Inner X
   V = X
   ```

   1. `V` is easy, so let's do that first:
      `V = (X)` falls in the first case, with no `t_i`, hence is positive for X
   2. For `U`: is `U = Inner X` [strictly positive](https://coq.inria.fr/refman/language/core/inductive.html#strict-positivity) wrt `X`?
      ![image](https://user-images.githubusercontent.com/8181630/134818417-9cf8f4a0-50d0-47b7-8f50-a4e4b74c0e70.png)
      Here,
      ```
      T = Inner X
      ```
      Hence we're in the last case: `T` converts to `(I a1)` (no `t_i`) with
      ```
      I = Inner
      a1 = X
      ```
      and `X` does not occur in the `t_i`, since there are no `t_i`.
      Do the instantiated types of the constructors satisfy the nested positivity condition?
      There is only one constructor:
      1. `inner : Inner bool -> Inner X.`
         Does this satisfy the [nested positivity condition](https://coq.inria.fr/refman/language/core/inductive.html#nested-positivity)?
         Here,
         ```
         T = forall x: Inner bool, Inner X.
         ```
         So we're in the second case with
         ```
         U = Inner bool
         V = Inner X
         ```
         1. `X` does not occur in `U`, so `X` is strictly positive in `U`.
         2. Does `V` satisfy the nested positivity condition for `X`?
            Here,
            ```
            T = Inner X
            ```
            Hence we're in the first case: `T` converts to `(I b1)` (no `u_i`) with
            ```
            I = Inner
            b1 = X
            ```
            There are no `u_i`, so `V` satisfies the nested positivity condition.

So, this looks valid, but Coq rejects it.  Is my math wrong, or is the positivity checker wrong, or is the manual wrong? (ordered by my mental model of relative likelihood ^^)

#### Coq Version

8.13

**Comment by SkySkimmer** [comment]
I think non-uniform parameters don't count as parameters for nested positivity. Not sure if doing otherwise leads to inconsistency.
I agree that the manual does not state this.

**Comment by herbelin** [comment]
Not clear to me that the restriction could not be relaxed.

For instance, the given example seems equivalent to:
```
Inductive InnerBool := innerBool : InnerBool -> InnerBool.
Inductive InnerOuter := innerOuter : InnerBool -> InnerOuter.
Inductive Outer := outer : InnerOuter -> Outer.
```
Would we consider a less degenerate example such as:
```
Inductive Inner (A : Type) :=
| base : Inner A
| inner : A -> Inner (option A) -> Inner A.
Inductive Outer := outer : Inner Outer -> Outer.
```
it seems we'd have an equivalence with:
```
Inductive InnerOuter : nat -> Type :=
| base n : Inner n
| innerOuter n : option^n Outer -> InnerOuter (S n) -> InnerOuter n
with Outer := outer : InnerOuter 0 -> Outer.
```
whose inhabitants may typically have the form `outer (innerOuter 0 (outer base) (innerOuter 1 (Some ...) base ))`.

At least superficially, this looks similar to Fu-Selinger recursive formulation of bushes. So, wondering whether a paper on truly nested inductive types such as [Johann-Polonsky](https://link.springer.com/content/pdf/10.1007%2F978-3-030-45231-5_18.pdf) might be relevant here.

In the meantime, #14967 fixes the reference manual.

**Comment by herbelin** [comment]
I convinced myself with a second-order encoding that recursively non-uniform parameters don't need to be avoided. That is, the doc can be kept as it is and the code can be made more permissive.

<details>
<summary>Second order encoding of outer</summary>
This is a simulation of:
```
Inductive Inner (A : Type) :=
| base : Inner A
| inner : A -> Inner (option A) -> Inner A.
Inductive Outer := outer : Inner Outer -> Outer.
```
using an impredicative encoding (I use `Prop` but it would work with impredicative set).

I generalize a bit: the monotone functor `F(B,C)` := `(base: 1) + (inner: B ⨉ C)` stands for the structure of the inductive type and the monotone functor `G(C)` := `option C` for the structure of non-uniform call.
```
Axiom F : Prop -> Prop -> Prop.
Axiom monFL : forall A B C : Prop, (A -> B) -> F A C -> F B C.
Axiom monFR : forall A B C : Prop, (A -> B) -> F C A -> F C B.
Axiom G : Prop -> Prop.
Axiom monG : forall A B : Prop, (A -> B) -> G A -> G B.

(* A recursive family over the positive functor F with one recursive call on G A
   which is non-uniform but positive *)
Definition Inner A :=
  forall P : Prop -> Prop,
  (forall A, F A (P (G A)) -> P A) ->
  P A.

(* The constructor of Inner *)
Definition inner A (i : F A (Inner (G A))) : Inner A :=
  fun P I => I _ (monFR (Inner (G A)) (P (G A)) _ (fun x => x P I : P (G A)) i).

(* An auxiliary lemma showing that Inner is monotone:
   recursive calls are in positions governed by of F and G which are monotone *)
Definition Innermon_aux (A B:Prop) (H : Prop -> Prop) (f : A -> H B) (i : Inner A): Inner (H B) :=
  fun P I => i
  (* Generalized inductive statement *)
  (fun X => forall (H:Prop->Prop) (f:X->H B), P (H B))
  (fun A x H f =>
   I (H B)
     (monFL _ _ _ f 
      (monFR (forall H : Prop -> Prop, (G A -> H B) -> P (H B)) _ A (fun a => a (fun X => G (H X))
       (monG _ _ f)) x))) H f.

Definition Innermon (A B:Prop) (f : A -> B) (i : Inner A): Inner B :=
  Innermon_aux A B (fun X => X) f i.

(* The type Outer *)
Definition Outer :=
  forall P : Prop,
  (Inner P -> P) ->
  P.

(* The constructor of Outer *)
Definition outer (i : Inner Outer) : Outer :=
  fun P O => O (Innermon _ _ (fun o => o P O) i).
```
So, shortly, non-uniform parameters in nested types should not be a problem as soon as the non-uniformity is monotone wrt the outer type. This monotonicity would be checked by the criterion given in the manual: "the (instantiated) types of constructor 𝐶𝑖{𝑝𝑗/𝑎𝑗}𝑗=1…𝑚 of 𝐼 satisfy the nested positivity condition for 𝑋" (for m the number of all parameters).
</details>

Agda treats recursively non-uniform parameters like the other parameters. They discussed about extending this to indices in agda/agda#3541, at least for indices which are variables used linearly. Agda also supports truly nested types by the way.

I'm going to change the code rather than the documentation.
