### ISSUE TITLE
Please accept `in` as a synonym of `inside` in `Search`

### ISSUE THREAD

**Issue by gares** [coq/coq#14930]
This would ease the transition of the old ssrsearch code.

**Comment by gares** [comment]
CC @herbelin #13760

**Comment by CohenCyril** [comment]
Please see my suggestion [here](https://github.com/coq/coq/pull/8855#issuecomment-616589269) to have the syntax `in:M` instead and the discussion in subsequent posts.

**Comment by herbelin** [comment]
Would be good yes.

I'm unsure to have time to do that in the very short time. Tell me if you want to give it a try in the meantime.
