### ISSUE TITLE
ssreflect pollutes notation precedence space for colon, again

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#14959]
#### Description of the problem

This seems to be #6078 again. VST defines a conflicting notation.

```coq
From Coq Require Import ssreflect.
From VST Require Import floyd.proofauto.
(*
Notation "_ : _" is already defined at level 100 with arguments constr
at next level, constr at level 100 while it is now required to be at level 26
with arguments constr at next level, constr at level 26.
*)
```

#### Coq Version

Coq 8.13

**Comment by Alizter** [comment]
That issue was closed but I don't think it was resolved. The gitblame states that https://github.com/coq/coq/blame/74a2cf7598ea07cce64090f7e2e0e5d008a7ea01/theories/ssr/ssreflect.v#L115 has been around for a while, so this is nothing new in that sense.
