### ISSUE TITLE
Documentation of .glob files.

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#14953]
#### Description of the problem

@xavierleroy mentioned here (https://github.com/coq/platform/issues/17) that he cannot commit to maintaining his coq2html tool because it relies on the `.glob` file format which is apparently undocumented. I think the `.glob` files are generally useful for various tools and should be documented.

A maintained documentation of the .glob format is a prerequisite for including coq2html in the Coq Platform.

#### Coq Version

latest

**Comment by ejgallego** [comment]
Duplicate of #4834
