### ISSUE TITLE
Derive JMeq_eq from eq_rect_eq

### ISSUE THREAD

**Issue by gjurgensen** [coq/coq#14970]
The `JMeq_eq` axiom (in `Coq.Logic.JMeq`) is equivalent to UIP and its various incarnations, such as `eq_rect_eq` (in `Coq.Logic.Eqdep`), which is independently axiomatized. It is redundant to accept both axiomatically. Therefore, I propose one axiom is removed and replaced with a derivation from the other.

I think it makes the most sense to remove the `JMeq_eq` axiom, and derive it from `eq_rect_eq`.

If anyone would like to see a prove that the two axioms are equivalent, I'd be happy to share mine (although, I assume this is already known; Dr. Chlipala comments on their equivalence in his text CPDT).

I'd also be happy to submit a pull request with my proposed redefinition of `JMeq_eq` if there is interest.

**Comment by SkySkimmer** [comment]
>I'd also be happy to submit a pull request with my proposed redefinition of JMeq_eq if there is interest.

Sounds good.
Maybe having a UIP axiom and deriving both JMeq_eq and eq_rect_eq from it would be nice instead though.

**Comment by gjurgensen** [comment]
I would also prefer a UIP axiom from which eq_rect_eq were derived. I'm not sure where the best place is to put that though. Perhaps in Coq.Logic.Eqdep, where eq_rect_eq is current declared?
