### ISSUE TITLE
Implicit arguments not correctly displayed by the Print command

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#15020]
Observed on bebefec4c1fe30e540d0cc17a1c2f5975661444d. The following snippet showcases the issue.
```
Arguments eq_rect {_ _} _ _ {_}.

About eq_rect.
(*
eq_rect :
forall {A : Type} {x : A} (P : A -> Type),
P x -> forall y : A, x = y -> P y
*)
```
This should display `forall {y : A}, ...` but the curly braces are missing from the output.

**Comment by herbelin** [comment]
Fixed in #18442: was a collision between the old and new (#15685) method for printing implicit arguments.
