### ISSUE TITLE
CoqIDE debugger needs "step over"

### ISSUE THREAD

**Issue by Alizter** [coq/coq#15033]
Currently there is only step in and continue, however there needs to be an option in between which steps over the current ltac definition (like a local continue). This is a feature that many other debuggers have.

**Comment by jfehrle** [comment]
Use CTRL-↓.  That's described in the documentation.  I didn't repeat it in the Debug menu.

CoqIDE was already a form of debugger.  CTRL-↓ works both on single tactics outside Ltac and as "Step over" within Ltac.  Probably worth making it more seamless, e.g. for consistency the user should be able to set a breakpoint on a simple tactic and have CoqIDE stop at that point.  That's not the case now.
