### ISSUE TITLE
Lexer ignores initial Loc.t offsets

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15087]
See the code changes in #14898.  In `Clexer.func`, the lexer ignores some of the offsets passed in with `loc`, so it's necessary to patch up the lexer-returned loc with this code (below) to return the correct offsets.  The line number is handled correctly.  IIRC some of the other returned character offsets were not correct but I couldn't figure out how to fix them.  The debugger currently only needs correct values for `bp`, `ep` and `line_nb`.  I don't recall whether this patch gives the correct `bol_pos`--it's from 6 months ago.

```
     let aloc = Loc.{loc with bol_pos = loc.bol_pos + bp_;
                                    bp = loc.bp + bp_;
                                    ep = loc.ep + bp_} in
```

The debugger needs this because each sentence passed by CoqIDE is a new invocation of the parser.  The `Loc.t`s in the AST need to be relative to the beginning of the buffer rather than relative to the beginning of the sentence.

**Comment by jfehrle** [comment]
Was not fixed.  See https://github.com/coq/coq/pull/17348#discussion_r1139535447

**Comment by ejgallego** [comment]
The bug indeed was fixed, see the PR documentation and test cases in order to get the right Lexer configuration (basically you need to set `Stream.count` correctly too)
