### ISSUE TITLE
Pose does not compute relevance correctly

### ISSUE THREAD

**Issue by kyoDralliam** [coq/coq#15091]
#### Description of the problem

The `pose` tactic does not seem to take irrelevance of SProp properly into account:

```coq
Inductive P : SProp := C.

Goal forall (f : P -> Type) (x : P), f x.
  intros f x.
  (* Works as expected *)
  Fail Fail change x with C.

  pose (t := C).
  (* Does not work ??? *)
  Fail change x with t.

  (* Works if we explicitly unfold *)
  let tu := eval unfold t in t in change x with tu.
```

[Discussion on zulip](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/SProp.2C.20pose.20and.20change), #15090 

#### Coq Version

coq 8.13

**Comment by ppedrot** [comment]
Fixed by #15090.
