### ISSUE TITLE
Attacks by introducing invisible source code using special Unicode characters

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#15117]
In this paper: (https://www.trojansource.codes/trojan-source.pdf) researchers from the University of Cambridge describe an attack which uses special Unicode characters to inject invisible or modified code. As far as I can tell any compiler taking Unicode input - as coqc - is affected by this.

There is an easy remedy, which is rejecting sources which contain such characters.

**Comment by Zimmi48** [comment]
There's a long discussion already on this topic at https://coq.gitlab.io/zulip-archive/stream/237977-Coq-users/topic/Finding.20an.20old.20Coq-club.20post.20on.20Pollack.20inconsistency.3F.html. Basically, the main message there is "there is nothing new in this paper".

Furthermore, this article https://research.swtch.com/trojan (mentioned in this thread) explains that there is no point in fixing this at the compiler level, but it's rather at the level of interfaces for code review (editors and GitHub) that this should be addressed. GitHub has already done a change relative to that: https://github.blog/changelog/2021-10-31-warning-about-bidirectional-unicode-text/

This is also related to the non-security model of Coq (see #14962) that we should document.

My suggestion is to close the present issue as "won't fix".

**Comment by ejgallego** [comment]
This is indeed folklore on the formal proofs community for a long time, in fact, you don't even need unicode, there are interesting ways to mis-represent the theorem you may want to prove so you could trick someone reading it.

For example, the feit-thomsom proof takes some measures against this by shipping a notation-free, reduced file, that while it is still not exactly the kernel term, gets much closer.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : thanks - I didn't know the term "Pollack (in)consistency" so I didn't read this thread - will do.

@ejgallego : I agree that it is easy to convince people of something wrong by abusing the notation system, but it is hard to sneak in something this way, because usually the notations would be reviewed as well.

My take on this is that it should be fixed in the UI tools *and* disallowed in compilers to be safe.

I will read the Zulip thread and let's continue the discussion there.
