### ISSUE TITLE
Ltac2: "now" tactic does not work in 8.14.0 (did in 8.13.2)

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#15122]
#### Description of the problem

In 8.14.0 the `now` tactic appears to be broken in Ltac2. It did work as expected in 8.13.2.

Here is an example which does work in 8.13.2 but not in 8.14.0:

```
Require Import Ltac2.Ltac2.
Require Import ZArith.
Require Import Reals.

Lemma Ltac2_now_regression : forall i:Z,
  (0 <= i <= 4294967295)%Z ->
  (0 <= IZR i <= 4294967295)%R.
Proof.
  intros i H.
  now split; apply IZR_le.
Qed.
```

In 8.14.0 this works:

```
Proof.
  intros i H.
  split; apply IZR_le; apply H.
Qed.
```

**Comment by ppedrot** [comment]
This is very weird, I can't think of anything that would have caused this change...

On a second thought, are you sure that your test for 8.13 was correct? The parsing rule of the `now` tactic is different in Ltac2 and Ltac1. In the former case, it parses as an application so you have to wrap the argument inside parentheses. On your example `now (split; apply IZR_le).` rightfully succeeds.

**Comment by MSoegtropIMC** [comment]
I am pretty sure. see:
```
bugs$ cat Ltac_now_8_13_2.v 
Require Import Ltac2.Ltac2.
Require Import ZArith.
Require Import Reals.

Lemma Ltac2_now_regression : forall i:Z,
  (0 <= i <= 4294967295)%Z ->
  (0 <= IZR i <= 4294967295)%R.
Proof.
  intros i H.
  now split; apply IZR_le.
Qed.

bugs$ opam switch __coq-platform.2021.09.0~8.13
bugs$ coqc --version
The Coq Proof Assistant, version 8.13.2 (October 2021)
compiled on Oct 19 2021 10:54:45 with OCaml 4.10.0
bugs$ coqc Ltac_now_8_13_2.v 

bugs$ opam switch __coq-platform.2021.09.0~8.14+beta2
bugs$ coqc --version
The Coq Proof Assistant, version 8.14.0
compiled with OCaml 4.10.0
bugs$ coqc Ltac_now_8_13_2.v 
File "./_build_vo/default//lib/coq/user-contrib/Ltac2/Notations.v", line 611, characters 29-33:
Error: Tactic failure: Cannot solve this goal.

bugs$
```

I can confirm that the parenthesis help. So you are saying it is a bug in 8.13.2 which made my code work and this has been fixed in 8.14.0?

**Comment by ppedrot** [comment]
Something has changed in the parsing of the now tactical. The following:
```
Ltac2 foo t := now split; t ().
Print Ltac2 foo.
```
gives in 8.13
```
foo : (unit -> 'a) -> unit
foo :=
  fun t =>
  let t :=
    fun _ =>
    let _ := let bnd := fun _ => Std.NoBindings in split0 false bnd in
    t () in
  now0 t
```
and in 8.14
```
foo : (unit -> 'a) -> 'a
foo :=
  fun t =>
  let _ :=
    let t :=
      fun _ => let bnd := fun _ => Std.NoBindings in split0 false bnd in
    now0 t in
  t ()
```
The first one is essentially `(now split); t ()` but the second one is `now (split; t ())`. I thought `now` was made to parse as an application since the inception of Ltac2 but I'm probably wrong?

**Comment by MSoegtropIMC** [comment]
Well according to the manual, the 8.13.2 behavior is correct. See: [now](https://coq.inria.fr/refman/proofs/automatic-tactics/auto.html#coq:tacn.now) and [ltac-expr](https://coq.inria.fr/refman/proof-engine/ltac.html#syntax)

`ltac-expr` includes `;`, so as I read this I would expect that `now a; b` parses as `now (a; b)` and not as `(now a) ; b`. The first would also make more sense since now solves the goal or fails, so that the `(now a) ; b` is not useful.

Was the change in ltac2 or somewhere else?

**Comment by SkySkimmer** [comment]
f6e393dae62afbb659eab64a530c0cf39403c495 is the first bad commit

**Comment by mattam82** [comment]
Hit the same problem in CertiCoq. You might prefer `now foo ; bar` to mean `(now foo) ; bar` but still have `now rewrite bar` be parsed right. Ah... syntax...
