### ISSUE TITLE
Cannot install Coq 8.14 via opam on macOS due to sandboxing + dune 2.x caching

### ISSUE THREAD

**Issue by tchajed** [coq/coq#15138]
#### Description of the problem

Running `opam install coq.8.14.0` with a fresh opam install on macOS 11.6 fails for me:

```
[ERROR] The compilation of coq.8.14.0 failed at "./configure -configdir /Users/tchajed/.opam/default/lib/coq/config
        -prefix /Users/tchajed/.opam/default -mandir /Users/tchajed/.opam/default/man -docdir
        /Users/tchajed/.opam/default/doc/coq -libdir /Users/tchajed/.opam/default/lib/coq -datadir
        /Users/tchajed/.opam/default/share/coq -coqide no -native-compiler no".

#=== ERROR while compiling coq.8.14.0 =========================================#
# context     2.1.0 | macos/x86_64 | ocaml.4.12.0 | https://opam.ocaml.org#c7b1bb0d
# path        ~/.opam/default/.opam-switch/build/coq.8.14.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure -configdir /Users/tchajed/.opam/default/lib/coq/config -prefix /Users/tchajed/.opam/default -mandir /Users/tchajed/.opam/default/man -docdir /Users/tchajed/.opam/default/doc/coq -libdir /Users/tchajed/.opam/default/lib/coq -datadir /Users/tchajed/.opam/default/share/coq -coqide no -native-compiler no
# exit-code   1
# env-file    ~/.opam/log/coq-31916-bb6357.env
# output-file ~/.opam/log/coq-31916-bb6357.out
### output ###
# Error: too many retries (100): waiting for beacon file
# "/Users/tchajed/.cache/dune/db/runtime/dune-cache-daemon/port" to be locked
# Error: empty output starting cache
```

If I start the dune cache manually with `dune cache start`, I get a slightly different error message:

```
# Error: connect: : Operation not permitted
```

`opam install coq.8.13.2` still works, and I can compile Coq from source, and Homebrew can still build the Coq bottle, so the issue seems to be a regression in Coq's opam build process specifically (maybe due to sandboxing?).

#### Coq Version

- opam 2.1.0
- dune 2.9.1
- coq 8.14.0
- macOS 11.6

**Comment by tchajed** [comment]
I can confirm that `opam install coq.8.14.0` works on Linux for me, so the problem does seem macOS specific.

**Comment by ejgallego** [comment]
Maybe you cache got corrupted? Can you try removing `/Users/tchajed/.cache/dune/` and trying again?

**Comment by tchajed** [comment]
I tried that and it didn't help.

**Comment by ejgallego** [comment]
@tchajed if you disable the cache in your `~/.config/dune`, does it work?

**Comment by tchajed** [comment]
That indeed fixes the problem, thanks! I didn't realize I had opted in to dune caching.

@ejgallego do you have an idea of where the bug could or should be fixed?

**Comment by ejgallego** [comment]
> @ejgallego do you have an idea of where the bug could or should be fixed?

I have seen some OSX problems indeed in the dune repos, do you get the same problem when running `configure` from Coq master? If so, we can file a bug dune upstream, I was about to release Dune 2.9.2, but maybe this bug warrants a fix.

**Comment by ejgallego** [comment]
Indeed, it was reported here https://github.com/ocaml/dune/issues/4575

Seems a pretty serious bug.

**Comment by tchajed** [comment]
No, I'm able to manually run `./configure` from master, with the exact some command line. The bug must be related to the sandboxing as far as I can tell.

Thanks for finding the bug report! I did a few searches but that bug didn't come up. I think we can close this bug.

**Comment by Blaisorblade** [comment]
Since this is _the_ remaining open issue on the topic, FWIW, we've rediscovered this and root-caused it in https://coq.zulipchat.com/#narrow/stream/237977-Coq-users and https://github.com/coq/platform/issues/189.

The problem is that opam sandboxing on Mac disabled network access, which is used by dune caching in 2.x.

All workarounds I know are problematic;
- in the dune config, one can set `(cache disabled)` during the build — which seems best since not much caching happens anyway;
- a probably worse option is setting `(cache-transport direct)` in the dune config temporarily, but this intereferes with concurrent dune execution according to docs;
- finally, one can disable opam sandboxing, or weaken it to allow internet access to local IPs by patching `~/.opam/opam-init/hooks/sandbox.sh`. I hope local IP means "localhost", but Mac's sandbox configuration language isn't really documented.

```diff
--- a/sandbox.sh	2021-12-04 12:45:38.543497117 +0100
+++ b/sandbox.sh	2021-12-04 12:45:32.690709502 +0100
@@ -2,7 +2,7 @@
 set -ue

 POL='(version 1)(allow default)(deny network*)(deny file-write*)'
-POL="$POL"'(allow network* (remote unix))'
+POL="$POL"'(allow network* (remote unix))(allow network* (local ip))'
 POL="$POL"'(allow file-write* (literal "/dev/null") (literal "/dev/dtracehelper"))'

 add_mounts() {
```
