### ISSUE TITLE
CoqIDE black screen 

### ISSUE THREAD

**Issue by ianshil** [coq/coq#15150]
I just reinstalled CoqIDE on my Mac (macOS Monterey 12.0.1)  via Opam as instructed there: https://coq.inria.fr/opam-using.html#coq-packages. 

So, I have installed coq.8.14.0 as well as coqide.8.14.0. 

Now, when I run the command "coqide" in the terminal, coqide opens in the following way:

<img width="1280" alt="Capture d’écran 2021-11-10 à 00 17 46" src="https://user-images.githubusercontent.com/73801439/140931378-fbe21e3e-ba54-4e6d-9208-6d5671b3cd78.png">

By moving my cursor around I can see that some functionalities are still there. I need to force coqide to shutdown every time. Also, I get the following error in the terminal: 

> (coqide:12693): Gtk-WARNING **: 00:17:16.372: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node header owner GtkNotebook)
> 
> (coqide:12693): Gtk-WARNING **: 00:17:16.372: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tabs owner GtkNotebook)
> 
> (coqide:12693): Gtk-WARNING **: 00:17:16.372: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)

What shall I do to fix this? 

(Note: the CoqIDE icon you see in the dock comes from a former install which I did not do through Opam, but this led to troubles.)

**Comment by Zimmi48** [comment]
Sorry to see that this was left unanswered for so long. Can you try to reinstall Coq and CoqIDE using the platform scripts (see the beginning of the documentation you linked to)? This will create a fresh opam switch.

**Comment by ianshil** [comment]
@Zimmi48 thanks for your answer. 

It seems that I did not have labgtk3 installed on my computer, so I had to install it. After this, I managed to solve the problem described above but encountered another one. For some reason, when I tried to open a .v file containing the Equations package, CoqIDE eventually died after a couple of seconds. It was very unpredictable: sometimes it crashed when I compiled the call to the Equations package, sometimes further, sometimes before. Extremely odd. 

In the end, I simply installed the entire Coq platform through the beginners instructions. Everything seems to be working fine now, apart from symbols (mainly Greek letters) present in old .v files which are making CoqIDE unhappy.

**Comment by Zimmi48** [comment]
The crash looks like #14352. Was it a platform-driven opam install or still a manual opam install? Which version of OCaml did you have if the latter? When you say that it works better with the platform "beginner instructions", do you mean by using the platform scripts or the macOS binary installer?

**Comment by ianshil** [comment]
Sorry for the poor terminology and explanations: I am not a computer scientist. 

It is indeed similar to #14352. I installed opam following the instructions there https://opam.ocaml.org/doc/Install.html (I used Homebrew). I am not sure about the OCaml version, but I guess that it must be the one being installed when running "brew install opam" 3 days ago. By "beginner instructions" I mean the installation process described in the section "Installation using the macOS DMG package" here https://github.com/coq/platform/blob/main/doc/README_macOS.md.

**Comment by Zimmi48** [comment]
You can get the OCaml version by running `ocamlc -v` from a terminal, possibly after doing `eval $(opam env)`.

**Comment by ianshil** [comment]
I uninstalled opam, and thought OCaml version coming with it was also deleted. But no, the .opam directory is still there, and the version of OCaml in it is 4.12.0.

**Comment by Zimmi48** [comment]
OK, thanks! Then, it was most likely the same issue as in #14352. Closing this one then.
