### ISSUE TITLE
"make -f Makefile.dune test-suite" gets ~100 failures with "File not found on loadpath" messages

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15189]
The warnings are also concerning--why is the test suite looking in `_build_vo`?  IIUC @SkySkimmer says that directory should be deleted if present.

For example, in `test-suite/output/RecordProjParameter.v`

```
Warning:
Cannot open directory /home/proj/coq/_build_vo/default/lib/coq/../coq-core/plugins
[cannot-open-dir,filesystem]
Error:
File not found on loadpath : ltac_plugin.cmxs
Loadpath: /home/proj/coq/test-suite:/home/proj/coq/_build_vo/default/lib/coq/user-contrib/Ltac2.
```

**Comment by SkySkimmer** [comment]
You probably tried to use configure and Makefile.dune together. Stop doing that.

**Comment by Zimmi48** [comment]
>Stop doing that.

Unfortunately, that can happen when needing to run targets such as `doc_gram_rsts`, so this means that devs have to remember to manually delete the `_build_vo` directory before running the test suite.

**Comment by SkySkimmer** [comment]
>Unfortunately, that can happen when needing to run targets such as doc_gram_rsts, so this means that devs have to remember to manually delete the _build_vo directory before running the test suite.

I agree that it's bad, especially considering deleting _build_vo is insufficient. We also need to `git clean -xf config/`.

**Comment by jfehrle** [comment]
Unsurprisingly, I run `doc_gram_rsts` very frequently.

**Comment by jfehrle** [comment]
I still see this problem when there's no _build_vo and after a `git clean -xf config/`.  The messages still refer to _build_vo as shown at the top.

**Comment by SkySkimmer** [comment]
I can't reproduce then.
Maybe making it possible to use the doc_gram targets without configure is a better use of time than debugging this. https://github.com/coq/coq/pull/15241

**Comment by jfehrle** [comment]
Something is generating the path `_build_vo/default` even after doing various cleans and not running `doc_gram_rsts` .  It has to be one of these.  Which ones do you think are most likely?

![image](https://user-images.githubusercontent.com/1253341/143294899-741c0fbc-86ac-44a5-9224-cc04143d4cec.png)

**Comment by SkySkimmer** [comment]
none of the above

**Comment by jfehrle** [comment]
Ah, looks like these files were the problem:

```
$ find . -name Makefile.conf
./test-suite/coq-makefile/arg/_test/Makefile.conf
./test-suite/coq-makefile/validate1/_test/Makefile.conf
./test-suite/coq-makefile/timing/aggregate/Makefile.conf
./test-suite/coq-makefile/timing/before/Makefile.conf
./test-suite/coq-makefile/timing/per-file-before/Makefile.conf
./test-suite/coq-makefile/timing/per-file-after/Makefile.conf
./test-suite/coq-makefile/timing/error/Makefile.conf
./test-suite/coq-makefile/timing/after/Makefile.conf
./test-suite/coq-makefile/latex1/_test/Makefile.conf
./test-suite/coq-makefile/extend-subdirs/_test/Makefile.conf
./test-suite/coq-makefile/emptyprefix/_test/Makefile.conf
./test-suite/coq-makefile/emptyprefix/_test/theories2/Makefile.conf
./test-suite/coq-makefile/missing-install/_test/_test/Makefile.conf
./test-suite/coq-makefile/merlin1/_test/Makefile.conf
./test-suite/coq-makefile/only/_test/Makefile.conf
./test-suite/coq-makefile/vio2vo/_test/Makefile.conf
./test-suite/coq-makefile/compat-subdirs/_test/Makefile.conf
./test-suite/coq-makefile/quick2vo/_test/Makefile.conf
./test-suite/coq-makefile/findlib-package/_test/Makefile.conf
./test-suite/misc/side-eff-leak-univs/Makefile.conf
./test-suite/misc/non-marshalable-state/Makefile.conf
./test-suite/misc/poly-capture-global-univs/Makefile.conf
./test-suite/misc/quotation_token/Makefile.conf
```

which contain the line `COQMF_DOCDIR=/home/proj/coq/_build_vo/default/share/doc/coq/`

`cd test-suite; make clean` doesn't remove these.  The one I looked at was dated 5/5/21.

**Comment by Zimmi48** [comment]
Is this a bug of the `clean` target of the test-suite Makefile then?

**Comment by SkySkimmer** [comment]
I don't see how those files can produce an error in test-suite/output/RecordProjParameter
even generally:
- The coq-makefile _test directories are cleanup up when executing the test so generally shouldn't be a problem
- The misc tests seem to run coq_makefile before the Makefile.conf can be used so also shouldn't be a problem
