### ISSUE TITLE
"make -f Makefile.dune test-suite" does not run unit tests

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15185]
For example, delete `proof_diffs_test.ml.log`, do the make.  No `proof_diffs_test.ml.log` is created until I do a `make unit-tests` from the `test-suite` directory.

OTOH, CI runs these tests, so I'm baffled.

**Comment by SkySkimmer** [comment]
`make -f Makefile.dune test-suite` puts everything in _build/.../test-suite not in test-suite

**Comment by jfehrle** [comment]
That makes sense.  But there's no makefile in `_build/.../test-suite/unit-tests so you can't run them from there, either.

**Comment by Zimmi48** [comment]
I think that the point that Gaëtan was trying to make is that unit-tests are run when calling `make -f Makefile.dune test-suite` and that your initial example is not relevant for this target.

Indeed, I just confirmed this by changing a unit test to make it fail, then re-running `make -f Makefile.dune test-suite`. I get an error:

```
BUILDING SUMMARY FILE
logs/unit-tests/clib/inteq.ml.log
TEST FAILED: clib-inteq0 (Int.equal on 0)
TEST SUCCEEDED: clib-inteq42
*** Ran 2 tests, with 1 successes and 1 failures ***
==========> FAILURE <==========
    unit-tests/clib/inteq.ml...Error!

FAILURES
    unit-tests/clib/inteq.ml...Error!
```

FTR, this was with the following patch:

```diff
diff --git a/test-suite/unit-tests/clib/inteq.ml b/test-suite/unit-tests/clib/inteq.ml
index 89717c79d5..eb9d34fbaf 100644
--- a/test-suite/unit-tests/clib/inteq.ml
+++ b/test-suite/unit-tests/clib/inteq.ml
@@ -4,7 +4,7 @@ let log_out_ch = open_log_out_ch __FILE__
 
 let eq0 = mk_bool_test "clib-inteq0"
             "Int.equal on 0"
-            (Int.equal 0 0)
+            (Int.equal 0 1)
 
 let eq42 = mk_bool_test "clib-inteq42"
              "Int.equal on 42"
```
