### ISSUE TITLE
"Package coq-core has multiple definitions in" warning from every unit test

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15188]
The warning makes me uneasy.  The first path is my build tree, the correct path.  The other is opam--I expect most developers will have opam installations so this noise or perhaps could cause problems.  Can we change the unit test framework so this warning doesn't appear.

```
$ make unit-tests
OCAMLC  unit-tests/src/utest.mli
OCAMLOPT  unit-tests/src/utest.ml
TEST      unit-tests/printing/proof_diffs_test.ml
findlib: [WARNING] Package coq-core has multiple definitions in /home/proj/coq/_build/default/../install/default/lib/coq-core/META, /home/jfehrle/.opam/4.07.1/lib/coq-core/META
    : 
```

**Comment by ejgallego** [comment]
This was solved by #15560 , note however that still building the unit tests require a `make world` , until we are able to merge the dune test suite port.
