### ISSUE TITLE
Second run of "make -f Makefile.dune test-suite" consistently hangs

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15190]
It fails on these (in `master`):

```
TEST      misc/non-marshalable-state.sh
FAILED    misc/non-marshalable-state.log
TEST      misc/quick-include.sh
TEST      ide/load.fake
TEST      ide/undo018.fake
```

It appears a `clean` is needed to clear the hang.  Not good for developer productivity.

**Comment by Zimmi48** [comment]
I cannot reproduce (with the environment that you get in `nix-shell` and a clean repository): the second run is instantaneous.

**Comment by jfehrle** [comment]
I get the same behavior as you on a fresh source tree.  But I'd like to understand what needs to be cleared out on my original source tree to make it work.  Suggestions?

**Comment by Zimmi48** [comment]
Hard to say, but I'd start by trying to remove `_build_vo` and running `git clean -xf config/` as was suggested in #15189. If that works, then we could close this one in favor of the other.

**Comment by jfehrle** [comment]
I didn't have a _build_vo.  I did the clean.  I don't see the hang at the moment.
