### ISSUE TITLE
Binding variables for applying a theorem should match those used in the theorem

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15227]
Binding variables for the theorem `Rle_trans : forall n m p : R, n <= m -> m <= p -> n <= p` are `r1`, `r2` and `r3` while the user would naturally expect them to be `n`, `m` and `p` as they appear in statement of the theorem.  This is a significant usability bug--another unnecessarily weird detail that could be made intuitive.  Not fun to document, either.

The following works correctly with `r2` but it fails if `m` is used:

```
Require Import RIneq.
Require Export Rpow_def.
Local Open Scope R_scope.
Infix "^" := pow : R_scope.

Goal forall (x y : R) (n : nat),
  x * x ^ n <= y * y ^ n.
intros x y n.
apply Rle_trans with (r2:= y * x ^ n).
```

`About Rle_trans.` shows `Rle_trans :
forall r1 r2 r3 : R, r1 <= r2 -> r2 <= r3 -> r1 <= r3`

I don't know how much scripts rely on these names.  At the least, there should be an option to control whether the current or IMHO correct identifiers are used to support migration.  The default could initially be either current or "correct" names--TBD.

(See initial discussion here: https://github.com/coq/coq/pull/15015#issuecomment-974707688)

**Comment by Zimmi48** [comment]
From where do you draw the information that `Rle_trans` has `n` `m` and `p` are variable names? The definition is here:

https://github.com/coq/coq/blob/bac30aa30b00cb9baa0e9d37cc0754cb6c064b01/theories/Reals/RIneq.v#L303

And uses `r1`, `r2` and `r3`. So all the behavior that you show seem consistent to me.

**Comment by jfehrle** [comment]
A further inconsistency is that `Nat.le_lt_trans` seems to work with the identifier `m`, as in `apply le_lt_trans with (m := N.to_nat b).` in `NDec.v`.  That's defined with `Register le_lt_trans as num.nat.le_lt_trans.` in `Lt.v`, though I don't understand what is being referenced in the ml code.

(For `lt_trans`, I don't even see a `Register`, another puzzle.)

**Comment by SkySkimmer** [comment]
> That's defined with Register le_lt_trans as num.nat.le_lt_trans

No, Register does not define anything. https://coq.github.io/doc/master/refman/proof-engine/vernacular-commands.html#coq:cmd.Register

**Comment by Zimmi48** [comment]
>A further inconsistency

Sure, but that's an inconsistency of the stdlib.

`le_lt_trans` gets registered for the benefit of the Funind plugin. It needs this theorem and not `lt_trans`, which is why the latter doesn't have a `Register` command.

**Comment by jfehrle** [comment]
Ah, I see.  I found the Theorem, not the Lemma by a text search.

**Comment by Zimmi48** [comment]
What I did to find this lemma was to rely on the module location provided by `About`.

**Comment by jfehrle** [comment]
It's seems odd that `About Nat.lt_trans.` doesn't tell you what file contains the definition.  The output is:

```
Nat.lt_trans :
forall n m p : nat, (n < m)%nat -> (m < p)%nat -> (n < p)%nat

Nat.lt_trans is not universe polymorphic
Arguments Nat.lt_trans (_ _ _)%nat_scope _ _
Nat.lt_trans is opaque
Expands to: Constant Coq.Arith.PeanoNat.Nat.lt_trans
```

It's actually in `NZOrder.v`.

Also, `About lt_trans.` should show the underlying definition rather than only telling you that it's a notation.  It seems likely that's the information the users wants to see.

```
Notation lt_trans := Nat.lt_trans
Expands to: Notation Coq.Arith.Lt.lt_trans
```

**Comment by jfehrle** [comment]
> What I did to find this lemma was to rely on the module location provided by `About`.

I could not remember that command name when I was looking for it earlier; I thought of "Print", "Show", "Locate", "Search".
