### ISSUE TITLE
Resetting coq moves scroll in coqide

### ISSUE THREAD

**Issue by Alizter** [coq/coq#15230]
#### Description of the problem

When pressing "Reset Coq" the window scrolls all the way up to the top. This is different to past behaviour where it wouldn't scroll the window. The cursor is still where it was so the scrolling seems completely unnecessary.

#### Coq Version
8.15

**Comment by ppedrot** [comment]
cc @jfehrle since it was probably introduced by the debugger PR.

**Comment by Alizter** [comment]
In general the scroll bar is pretty crazy. I am getting dizzy stepping through proofs today. The window is constantly scrolling up and down.

**Comment by ppedrot** [comment]
I agree that this is quite annoying.

**Comment by ppedrot** [comment]
I think in general we should revert all the changes that introduced scroll to the focused line when using navigation commands. This is highly disturbing.

**Comment by jfehrle** [comment]
This behavior may be platform dependent.  If I step through a proof with CTRL-DOWN, I get vertical scrolling as needed to keep the end of the green zone visible, but no wild jumping up and down.  What is your platform?  I have Ubuntu running in Windows/WSL, a virtual machine.

The reset could suppress scrolling to the beginning as a special case.

If the text in the script is wider than the scroll window, I see some left-to-right jumping that might be improved, but no double scrolling.
