### ISSUE TITLE
Error highlighting in CoqIDE is not correct in the presence of unicode characters (regression)

### ISSUE THREAD

**Issue by Alizter** [coq/coq#15235]
#### Description of the problem
I have been observing incorrect underlining for various errors. Here is an example showing some small displacement:
```coq
Axiom A : Type.
Axiom Hc : A -> Prop.

Theorem soundness φ : Hc φ -> forall M, Satisfies M φ.
```

In CoqIDE at least, Satisfies is not underlined correctly.

#### Coq Version
8.15

**Comment by SkySkimmer** [comment]
Can reproduce on coqide master, but not on coqide 8.11.2

**Comment by herbelin** [comment]
I could observe it too. The shift is apparently related to the number of utf8 symbols between the error and the end of the sentence. (This makes working with unicode a nightmare!)

Will investigate a bit but if ever it rings a bell to someone.

**Comment by herbelin** [comment]
I suspect that utf8 offset was simply mistakenly subtracted one extra time in f3f165b2c05. The following "intuitive" patch seems to work.
```
diff --git a/ide/coqide/coqOps.ml b/ide/coqide/coqOps.ml
index 8be90d6de3..5a2f273f9a 100644
--- a/ide/coqide/coqOps.ml
+++ b/ide/coqide/coqOps.ml
@@ -592,8 +592,8 @@ object(self)
     | Some loc ->
       let start, stop = Loc.unloc loc in
       buffer#apply_tag tag
-        ~start:(buffer#get_iter (`OFFSET (b2c phrase start)))
-        ~stop:(buffer#get_iter (`OFFSET (b2c phrase stop)))
+        ~start:(buffer#get_iter (`OFFSET start))
+        ~stop:(buffer#get_iter (`OFFSET stop))
 
   method private position_tag_at_sentence ?loc tag sentence =
     let start, stop, phrase = self#get_sentence sentence in
```
I don't know what the `` `OFFSET `` thing is doing so waiting for @jfehrle to know what would be the right fix.

**Comment by jfehrle** [comment]
By the way, I generally don't review all the issues that are filed, so I generally don't see them until someone tags me.  (In this case, at the last possible moment before the release.)

**Comment by herbelin** [comment]
> By the way, I generally don't review all the issues that are filed, so I generally don't see them until someone tags me. (In this case, at the last possible moment before the release.)

Sorry about that. @Alizter had detected a problem already more than one month ago but I observed it and saw @Alizter's report only yesterday. The corresponding commit was then also found only yesterday. In any case, it works perfectly with #15467, thanks a lot!
