### ISSUE TITLE
Broken build of 8.14.0 on bytecode-only architectures

### ISSUE THREAD

**Issue by SnarkBoojum** [coq/coq#15240]
I disabled a few architectures in the Debian package because its compilation fails on them. To fix those, I can either try patches from you on a problematic box, or you can request a temporary account and do it yourself ; see [how](https://wiki.debian.org/PorterBoxHowToUse).

The failure does look that awful ; here is what I have on MIPSEL (eller.debian.org):
```
File "topbin/dune", line 24, characters 7-15:
24 |  (name coqc_bin)
            ^^^^^^^^
Error: No rule found for topbin/coqc_bin.exe
```

In case it matters:
- camlp5 7.14
- dune 2.7.1
- lablgtk3 3.1.1
- ocaml 4.11.1
- ounit 2.2.3
- zarith 1.12

**Comment by Alizter** [comment]
cc @ejgallego

**Comment by SnarkBoojum** [comment]
The Debian package was using dune to build ; I tried to go back to make, but:

- make coq fails because Error: Don't know how to build _build/default/user-contrib/Ltac2/ltac2_plugin.cmxs ;
- make coqide fails because Error: No rule found for ide/coqide/idetop.exe ;

so in short, there seem to be two broken build systems.

**Comment by Alizter** [comment]
The (legacy) makefile is still using dune. Which targets are you calling in dune?

**Comment by SkySkimmer** [comment]
Hard to tell what exactly you tried, but building cmxs is impossible on byte-only archs.

**Comment by SnarkBoojum** [comment]
With dune:
```
        dune build -p coq-core,coq-stdlib,coqide-server,coqide --display=verbose
        dune build @stdlib-html --display=verbose
```
and with make:
```
        make coq coqide doc-stdlib-html
```

**Comment by SnarkBoojum** [comment]
> Hard to tell what exactly you tried, but building cmxs is impossible on byte-only archs.

Ah, my comment above might indeed not have been clear, since sentence and comment could be mistaken: "make coq" is the command which triggered trying to build a .cmxs file.

**Comment by SkySkimmer** [comment]
What's the build log?

**Comment by SnarkBoojum** [comment]
Here is the log when compiling on mipsel using make:

[coq.mipsel.log](https://github.com/coq/coq/files/7613369/coq.mipsel.log)

For the log of compiling on mipsel with dune: [see here](https://buildd.debian.org/status/fetch.php?pkg=coq&arch=mipsel&ver=8.14.0%2Bdfsg-5&stamp=1637047692&raw=0)

**Comment by SkySkimmer** [comment]
ah it's this rule
~~~
contrib-vo-fixup: contrib-vo $(BCONTEXT)/user-contrib/Ltac2/ltac2_plugin.cmxs
~~~
(btw this isn't present in 8.15)

Something like
~~~
ifeq ($(BEST),byte)
contrib-vo-fixup: contrib-vo $(BCONTEXT)/user-contrib/Ltac2/ltac2_plugin.cma
else
contrib-vo-fixup: contrib-vo $(BCONTEXT)/user-contrib/Ltac2/ltac2_plugin.cmxs
endif
~~~
may work. If it doesn't it may be easier to wait for 8.15 for the byte-only archs.

**Comment by SnarkBoojum** [comment]
When is 8.15 due?

**Comment by SnarkBoojum** [comment]
I'll try your suggestion, but notice that it *might* solve the "make coq" issue, but not the "make coqide" one.

(The porterbox I'm using is dead slow, so don't expect news before this evening)

**Comment by SkySkimmer** [comment]
>When is 8.15 due?

https://github.com/coq/coq/wiki/Release-Schedule-for-Coq-8.15

>I'll try your suggestion, but notice that it might solve the "make coq" issue, but not the "make coqide" one.

right
I guess TOPBINOPT and IDETOP need to be adapted in some way

**Comment by SnarkBoojum** [comment]
That's a long way forward ; I'd like to have a good coq in Debian must sooner than that!

**Comment by SnarkBoojum** [comment]
@SkySkimmer with your suggestion, **make coq** fails with:
```
File "topbin/dune", line 24, characters 7-15:
24 |  (name coqc_bin)
            ^^^^^^^^
Error: No rule found for topbin/coqc_bin.exe
```

and **make coqide** with:
```
File "ide/coqide/dune", line 12, characters 7-13:
12 |  (name idetop)
            ^^^^^^
Error: No rule found for ide/coqide/idetop.exe
```

because in both cases, the Makefile turns to dune for the job.

What can I do?

**Comment by SkySkimmer** [comment]
Maybe it would work to replace `native` with `best` in dune modes?

**Comment by ejgallego** [comment]
> Maybe it would work to replace `native` with `best` in dune modes?

Likely, tho the API is a bit different so we may need to introduce a conditional rule, not a big deal.

As we discussed on the Zulip thread, if we don't test this in CI is IMHO a loss of time.

**Comment by ejgallego** [comment]
The API that the coq toplevel uses, to support `Drop.` which works only on byte.

**Comment by Blaisorblade** [comment]
Re "Loss of time", is there any evidence that enough people want to use Coq on byte-only architectures to warrant supporting them? I'm just an (overly?) vocal user, but the Coq team cannot support everything, so IMHO this is a good candidate for a WONTFIX.

**Comment by SnarkBoojum** [comment]
Well, the Debian packager for why3 wants to drop the coq support for various reasons, and the fact that coq is working on a more restrictive set of architectures is one of them...

**Comment by ejgallego** [comment]
8.14 is maintenance mode so I'm afraid this won't be fixed. If the problem persist in 8.17 I'd be happy to have a look to it.
