### ISSUE TITLE
`native_compute` should not reuse filename suffixes

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#15263]
#### Description of the problem

At https://github.com/coq-community/coq-performance-tests/runs/3479329691?check_suite_focus=true#step:6:754, I see
```
Error: Dynlink error: The module `Coq_native13c5a0' is already loaded (either by the main program or a previously-dynlinked library)
```
@SkySkimmer [suggested on Zulip](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/Dynlink.20module.20already.20loaded/near/263050390) that Coq might be re-using the same filename multiple times.  It seems worth storing a hashset of used filenames and retrying if a filename has already been used.

#### Coq Version

8.12

**Comment by SkySkimmer** [comment]
We could also stop deleting them, or delete at exit instead of immediately after use.

**Comment by JasonGross** [comment]
Delete at exit sounds fine.  Neglecting to delete them fills up `/tmp` way too quickly, see https://github.com/coq/coq/issues/10495
