### ISSUE TITLE
doc contains coq errors

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#15264]
https://coq.github.io/doc/master/refman/user-extensions/syntax-extensions.html#use-of-notations-for-printing currently has 
~~~
    Identifier 'If' now a keyword
    Toplevel input, characters 43-55:
    > Notation "'If' c1 'then' c2 'else' c3" := (IF_then_else c1 c2 c3) (at level 200, right associativity, format "'[v   ' 'If'  c1 '/' '[' 'then'  c2  ']' '/' '[' 'else'  c3 ']' ']'").
    >                                            ^^^^^^^^^^^^
    Error: The reference IF_then_else was not found in the current environment.
~~~
for the first "format" example https://github.com/coq/coq/blob/8f58b50b642914007b0655cb180b72e07b351c40/doc/sphinx/user-extensions/syntax-extensions.rst?plain=1#L257-L261

**Comment by Zimmi48** [comment]
This section does not have a `fail` option. Does this mean that the error detection mechanism is broken then?

**Comment by Zimmi48** [comment]
It looks like it has been like this for a while (since 8.14.0 at least)!

**Comment by SkySkimmer** [comment]
039b2423cf7b85f2f5960dde6a1586f0f07cf9d0 has a raw Reset Initial instead of using coqtop:: reset
