### ISSUE TITLE
Unknown constructor name in a match-expression is accepted

### ISSUE THREAD

**Issue by akr** [coq/coq#15286]
#### Description of the problem

I found that Coq accepts an unknown constructor name in a match-expression.

```
% coqtop
Welcome to Coq 8.14.0

Coq < Check fun (x : bool) => match x with Foo => 0 end.
fun _ : bool => 0
     : bool -> nat

Coq < About Foo.
Foo not a defined object.

Coq < 
```

I think `match x with Foo => 0 end` should cause an error
because Foo is not defined.

#### Coq Version

```
% coqtop -v
The Coq Proof Assistant, version 8.14.0
compiled with OCaml 4.13.1
```

**Comment by SkySkimmer** [comment]
That's not a constructor name, it's a catch-all variable.

**Comment by akr** [comment]
Oh.  I didn't know the syntax.  Thank you.
