### ISSUE TITLE
Don't extract `comparison` to `int`

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#15280]
#### Description of the problem

`ExtrOcamlInt63` extracts `comparison = Eq | Lt | Gt` to `"int" [ "0" "-1" "1" ]`, while `ExtrOCamlZBigInt` assumes that `comparison` is extracted to an ADT, so they cannot be used together. I propose to not override the extraction of `comparison` at all.

While OCaml does use `int` as its standard comparison type, the possible values are explicitly underspecified (it's `0`/negative/positive rather than `0`/`-1`/`1`), so we need explicit conversion when interfacing with OCaml comparison functions anyway.

(Follow up of #13925)

#### Coq Version

dev

**Comment by herbelin** [comment]
> I propose to not override the extraction of comparison at all.

Looks good. Would you like to provide a PR (and otherwise I can do).

Cc @coq/extraction-maintainers for possible feedback.
