### ISSUE TITLE
VSCoq and Coq master

### ISSUE THREAD

**Issue by mattam82** [coq/coq#15282]
#### Description of the problem

Starting VSCode on a file in the current Coq master raises:

```
coqtop-stderr: [pid 41008] Unexpected XML message
[pid 41008] Expected XML node: int
[pid 41008] XML tree received: <bool val="false"/>
```

I suspect a change in the XML protocol 

#### Coq Version

master

**Comment by jfehrle** [comment]
I've never used vsCoq, so it would help if you could be slightly more specific.  If it makes vsCoq unusable and a change is needed in Coq, I want to get it into 8.15 if possible and time is short:
- "starting" meaning trying to execute the first tactic or command?
- It makes vsCoq unusable?
- Were you trying to use the debugger or had a `Set Ltac Debug.` in your script?
- What version of vsCoq/when built?


The debugger changed the parameters and reply for the "add tactic/command" message.
That should be an easy fix in VSCoq if that is the cause.  However, my impression was that
VSCoq was not using the XML protocol.  (8.14 also modified that same message but I have not
heard about any issue with VSCoq.)

Attn: VSCoq maintainers @maximedenes @fakusb

**Comment by SkySkimmer** [comment]
vscoq is using the xml protocol

**Comment by ejgallego** [comment]
Why don't we make the new add call a different one and we keep compat for now?

I have ideas if you are interested on how to avoid this in the future

**Comment by maximedenes** [comment]
I remember we used to have a very strict backward compatibility policy on the XML protocol, not even removing unused values. I missed a lot of the last months activity on Coq, so I'm wondering why that changed. Personally, I found it made sense given that most IDEs are lacking engineering manpower. But never mind, if a policy change was discussed and agreed, that's fine.

So now on the technical front, could you give pointers to a documentation explaining how an IDE can get the version of the XML protocol spoken by a given Coq installation, and another pointer to the protocol changelog, so that we deal with compatibility on the vscoq side? Thanks!

**Comment by Zimmi48** [comment]
No policy change was discussed.

**Comment by Zimmi48** [comment]
OTOH, I'm surprised that Coqtail didn't break if the protocol was changed. Coqtail now has tests in the Coq CI.

**Comment by jfehrle** [comment]
I did an overlay for Coqtail.

**Comment by jfehrle** [comment]
At the moment, I believe there's no way for the client to get the protocol version number.  Logically it should be on the `init` message but it wasn't done that way.  We need to add a new message sends the version.  vsCoq will need to send that message.  If it fails (i.e. against an earlier version of Coq), it needs to recognize that the failure means it's for an earlier version.  Subsequent protocol changes can then be handled more cleanly.

The version is at the top of `xmlprotocol.ml`.  Checking for an exact match is simple to implement but perhaps a bit rigid.

I will add the new message in Coq.

```
(** Protocol version of this file. This is the date of the last modification. *)
let protocol_version = "20210918"
```

```
[pid 10655] <call val="Init">
  <option val="none"/>
</call>
[pid 10655] <-- Init None
[pid 10655] --> GOOD 1
SENT --> <value val="good">
  <state_id val="1"/>
</value>
```

**Comment by jfehrle** [comment]
> Why don't we make the new add call a different one and we keep compat for now?

Perhaps, though it would require changing coqtail as well.

**Comment by ejgallego** [comment]
Yeah we can revert the coqtail overlay, that maybe is easier ?

**Comment by jfehrle** [comment]
The message was also changed in 8.14, so that would also need to change and it's associated coqtail version.  If we can live with the breakage for a few days, I think we can get to a better result.

**Comment by jfehrle** [comment]
`xml-protocol.md` describes the protocol at length.  `changes.md` mentions the protocol changes, but it's only 1 paragraph.

**Comment by jfehrle** [comment]
Correction: the About message returns the version number.  That should be sufficient to get vsCoq working again.

For later: If About also returns the version number of the last non-backward compatible version then clients would be able to cleanly verify that they have a protocol version while avoiding the need for any code change for backward-compatible protocol changes.

**Comment by fakusb** [comment]
I think vsCoq just called and parsed 'coqc -v' to 'check' for the current protocol version.
I can investigate the protocol change and adjust vsCoq in the next 4 days.

**Comment by jfehrle** [comment]
Note that 8.14 and 8.15 both need tweaks.

**Comment by fakusb** [comment]
You mean that in the xml protocol, there are changes in 8.14 (compared to 8.13), and new changes on 8.15? I did not notice that, I would have imagined that users of 8.14 would have opened an issue if vscoq core functionality breaks.

**Comment by fakusb** [comment]
@jfehrle Do you mean the changes to the LTac debugger? VSCoq does not support that afaik.

**Comment by jfehrle** [comment]
You can pass zero for the added values.  If you pass correct offsets you may need to adjust what text gets highlighted for parsing errors (if vsCoq does that).  Of course if/when vsCoq supports the debugger through the XML API they need to be correct.

**Comment by jfehrle** [comment]
> You mean that in the xml protocol, there are changes in 8.14 (compared to 8.13), and new changes on 8.15?

That's what I meant, but after double-checking, I see there was no incompatible protocol change in 8.14.  And I expect vsCoq doesn't use the added "Db_cmd" message.

**Comment by fakusb** [comment]
Could someone beta-test this backwards-compatible fix?
https://coq.zulipchat.com/#narrow/stream/237662-VsCoq-devs.20.26.20users/topic/VSCode.20and.20Coq.20master/near/264371039

**Comment by jfehrle** [comment]
@fakusb Thanks for fixing this.
