### ISSUE TITLE
The files installed by Coq depend on (?) the version of dune being used

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#15290]
My ubuntu package broke only on Ubuntu Jammy because the following files are no longer installed:
```
/usr/doc/coq-core/LICENSE
/usr/doc/coqide-server/README.md
/usr/doc/coqide-server/LICENSE
/usr/doc/coqide/odoc-pages/index.mld
/usr/doc/coqide/LICENSE
/usr/doc/coqide/README.md
/usr/doc/coqide/FAQ
```
I'm guessing this is because [Jammy uses dune 2.9](https://launchpadlibrarian.net/572182416/buildlog_ubuntu-jammy-amd64.coq_8.master~git~202112040134+22857-0~daily363-92847267c9~ubuntu22.04.1_BUILDING.txt.gz) while I'm [using dune 2.7](https://launchpadlibrarian.net/572182456/buildlog_ubuntu-focal-amd64.coq_8.master~git~202112040134+22857-0~daily355-92847267c9~ubuntu20.04.1_BUILDING.txt.gz) on older versions of Ubuntu.

Is this deliberate?

cc @ejgallego ?

**Comment by ejgallego** [comment]
I have no idea, but you should use the .install files to determine what is installed.
