### ISSUE TITLE
`bfs eauto` behaves as `dfs eauto`

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#15300]
#### Description of the problem

`bfs eauto` was introduced in 8.13 as a replacement for `eauto n p` which was an obscure syntax for the same thing. Looking at this code again in the objective to remove the deprecated syntax, I discover that the code that was written is wrong (AFAICT) and implements the same behavior of `dfs eauto`:

https://github.com/coq/coq/blob/41e83eb688c93b07134efcc2053de416eb1b7ed3/plugins/ltac/g_auto.mlg#L164

I had indicated that the boolean should have been `false` in https://github.com/coq/coq/pull/13381#discussion_r523776496, but I apparently reviewed the code too fast.

This bug also highlights the need for a test case (and the likely absence of users of this feature).

#### Coq Version

Since 8.13

**Comment by Zimmi48** [comment]
If it helps you work with the implementation, I would support the removal. But I would even skip the deprecation phase for a tactic that was added a couple versions ago and never correct... The sad thing is that I already proposed to remove this back in 8.6...

**Comment by ppedrot** [comment]
I personally strongly support removal, but we may ask about this at the next Coq call. What prevented it to be removed in 8.6?

**Comment by Zimmi48** [comment]
It was #332. Skimming quickly over the discussion, it seems that there were issues with the typeclasses eauto-based alternative at the time.

**Comment by ppedrot** [comment]
Ideally we could simply deprecated for the 8.15rc1 / 8.15.0 and remove it immediately in master... cc @SkySkimmer

**Comment by Zimmi48** [comment]
If we deprecate / remove `bfs eauto`, let's also do the same for the the `dfs eauto` syntax.

**Comment by SkySkimmer** [comment]
Too late for 8.15 IMO

**Comment by ppedrot** [comment]
The RM has spoken. Still, it's broken anyways so a fix would change the semantics, while a deprecation would be even more transparent...

**Comment by JasonGross** [comment]
Does typeclasses eauto even do bfs?  https://github.com/coq/coq/issues/3928 is still open (but I haven't rechecked it)

**Comment by mattam82** [comment]
I checked an #3928 is closed.

**Comment by Zimmi48** [comment]
The RM has agreed to put a deprecation message for `bfs eauto` in 8.15.0 (we should also update the one of `eauto n p` to tell people to use `typeclasses eauto bfs` instead). @ppedrot will you take care of it?

**Comment by Zimmi48** [comment]
I think we should also deprecate the `dfs eauto` syntax, but this can wait 8.16 since it does really hurt.
