### ISSUE TITLE
(ssr) Anomaly "Uncaught exception Not_found." following #13952

### ISSUE THREAD

**Issue by proux01** [coq/coq#15325]
MathComp Analysis https://github.com/math-comp/analysis/blob/a0631bcbd1da699845c3d7ec5b01981356f46222/theories/topology.v#L1037
raises
```
File "./theories/topology.v", line 1037, characters 0-67:
Error: Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.
```

Info: https://github.com/coq/coq/issues/15325#issuecomment-991157847

Here is the backtrace obtained with `-bt`
```
Raised at file "clib/int.ml", line 39, characters 14-29
Called from file "engine/evarutil.ml", line 691, characters 12-30
Called from file "engine/proofview.ml", line 167, characters 12-37
Called from file "engine/proofview.ml", line 1006, characters 16-49
Called from file "engine/proofview_monad.ml", line 218, characters 46-49
Called from file "engine/logic_monad.ml", line 359, characters 59-69
Called from file "engine/logic_monad.ml", line 117, characters 8-12
Called from file "engine/proofview.ml", line 234, characters 12-42
Called from file "proofs/proof.ml", line 381, characters 4-49
Called from file "proofs/proof.ml", line 500, characters 31-52
Called from file "vernac/comTactic.ml", line 46, characters 23-59
Called from file "vernac/declare.ml", line 1457, characters 20-33
Called from file "vernac/comTactic.ml", line 43, characters 23-442
Called from file "vernac/vernacextend.ml", line 163, characters 32-47
Called from file "vernac/vernacinterp.ml", line 20, characters 20-113
Called from file "vernac/vernacinterp.ml", line 199, characters 24-69
Called from file "lib/flags.ml", line 17, characters 14-17
Re-raised at file "clib/exninfo.ml", line 81, characters 4-38
Called from file "vernac/vernacinterp.ml", line 249, characters 18-43
Called from file "vernac/vernacinterp.ml", line 247, characters 6-279
Re-raised at file "clib/exninfo.ml", line 81, characters 4-38
Called from file "stm/stm.ml", line 2169, characters 20-47
Called from file "stm/stm.ml", line 2111, characters 10-14
Re-raised at file "clib/exninfo.ml", line 81, characters 4-38
Called from file "stm/stm.ml", line 964, characters 6-10
Re-raised at file "clib/exninfo.ml", line 81, characters 4-38
Called from file "stm/stm.ml", line 2320, characters 4-105
Called from file "stm/stm.ml", line 2421, characters 4-60
Re-raised at file "clib/exninfo.ml", line 81, characters 4-38
Called from file "toplevel/vernac.ml", line 68, characters 31-52
Re-raised at file "clib/exninfo.ml", line 81, characters 4-38
Called from file "lib/flags.ml", line 17, characters 14-17
Re-raised at file "clib/exninfo.ml", line 81, characters 4-38
Called from file "toplevel/vernac.ml", line 112, characters 8-69
Called from file "toplevel/vernac.ml", line 116, characters 6-19
Re-raised at file "clib/exninfo.ml", line 81, characters 4-38
Called from file "toplevel/vernac.ml", line 172, characters 30-94
Called from file "toplevel/ccompile.ml", line 146, characters 18-95
Called from file "toplevel/ccompile.ml", line 210, characters 2-59
Called from file "toplevel/coqc.ml", line 47, characters 2-100
Called from file "toplevel/coqc.ml", line 66, characters 4-36
```

A git bisect points to #13952 as the first commit exhibiting the anomaly.

#### Coq Version

8.15, master

**Comment by ppedrot** [comment]
@proux01 can we get a minimized example?

**Comment by proux01** [comment]
Is there an easy way to launch the minimizer on something not in the CI? (pinging @JasonGross maybe)

**Comment by proux01** [comment]
@ppedrot here it is
```coq
Require Import ssreflect.

Definition set T := T -> Prop.

Definition subset {T} (A B : set T) := forall t : T, A t -> B t.

Class Filter {T} (F : set (set T)) := {
  filterS : forall P Q : set T, subset P Q -> F P -> F Q
}.
(* Global Hint Mode Filter - ! : typeclass_instances. *)
(* everything works if we comment the above line *)

Lemma anomaly T (P Q : T -> Prop) F (FF : Filter F) (FP : F P) :
  (forall x, P x -> Q x) -> F Q.
Proof.
move=> /filterS.  (* Error: Anomaly "Uncaught exception Not_found." *)
exact.
Qed.
```

**Comment by JasonGross** [comment]
Let's try @coqbot minimize
```
opam install --deps-only coq-mathcomp-analysis
git clone https://github.com/math-comp/analysis.git
cd analysis
make
```

**Comment by proux01** [comment]
Maybe adding an opam update @coqbot minimize
```
opam update
opam install --deps-only coq-mathcomp-analysis
git clone https://github.com/math-comp/analysis.git
cd analysis
make
```

**Comment by proux01** [comment]
Oh, it's working on Coq 8.14, but indeed we need 8.15 or master branch to expose the bug.

**Comment by ppedrot** [comment]
@proux01 it works for me on master as of 04aef4f3c4eb3e32d18fc5219573a7218fcc5748.

**Comment by proux01** [comment]
My bad, I shouldn't have commented it in the first place.

**Comment by ppedrot** [comment]
I think that there is an easy fix which is just to ignore missing evars for shelving in the class search, but there probably is a deeper issue with the algorithm.

**Comment by JasonGross** [comment]
> Oh, it's working on Coq 8.14, but indeed we need 8.15 or master branch to expose the bug.

There's unfortunately no way to change the docker image used, but if you unpin the default version of Coq, you can tell it to install a different one.  Not sure if I have the syntax right (and is 8.15 even on opam yet?)
 @coqbot minimize
```
opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
opam update
opam pin remove coq
opam install --deps-only coq-mathcomp-analysis 'coq>8.15~'
git clone https://github.com/math-comp/analysis.git
cd analysis
make
```

**Comment by SkySkimmer** [comment]
There's already a small version at https://github.com/coq/coq/issues/15325#issuecomment-991102665

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/blob/96025b54d30285d314cde81ee1ede1aea2f288cc/plugins/ssr/ssrview.ml#L330 removes an evar which is in the shelf. Then `Proof.run_tactic` when it does `tclNEWSHELVED` is unhappy. Before #13952 I guess we didn't add this evar to the shelf.

An example without modes which fails before #13952:    
~~~coq
Require Import ssreflect.

Axioms A B D : Type.
Class C := {}.
Axiom f : C -> A -> B.
Axiom g : D -> C.

Local Hint Extern 0 C => apply g;shelve : typeclass_instances.

Lemma foo : A -> Type.
Proof.
  move=> /f. (* Not_found *)
Qed.
~~~
For this 636fe1deaf220f1c30821846343b3a70ef7a078c is the first bad commit.

**Comment by erikmd** [comment]
Hi, @proux01 just pointed me to this issue.

@JasonGross regarding the bug minimized, would it help to have a `coqorg/coq:8.15` image?
anyway I'll prepare this ASAP.

Meanwhile, maybe you could use `coqorg/coq:dev` instead (?) but in this case, maybe mathcomp-analysis does not compile regarding opam versions constraints.

**Comment by JasonGross** [comment]
> would it help to have a `coqorg/coq:8.15` image?

It would, but I need to find a way to address https://github.com/coq/bot/issues/183 before we can make use of an 8.15 image

**Comment by erikmd** [comment]
Ah OK, thanks @JasonGross for the reference!

Indeed, when `coqorg/coq:8.15` will go live, it won't be a synonymous of `coqorg/coq:latest` (till `8.15.0` is released)

**Comment by SkySkimmer** [comment]
@coq/ssreflect-maintainers what should be done about this?

**Comment by gares** [comment]
Hum, maybe Evd.remove is too low level. The idea of the code is that an unresolved evar was lambda-abstracted out, so it should be removed, not only from Evd, but also from any other data set about evers. I don't know what is the easiest: - be lenient about shelves pointing to non existing evars; - provide a more high level API to purge an evar; -make these data structure weak maps (and have the Gc purge what is garbage for real)

**Comment by ppedrot** [comment]
`Evd.remove` is really looking for trouble, you can't remove stuff without tracking the roots of the evar heap and we don't have any API for that. I'd be happy if we could get rid of that piece of code...

**Comment by gares** [comment]
where are the shelves? are they in the evar map?

**Comment by gares** [comment]
how do i save an old shelf and restore it?

**Comment by gares** [comment]
So it seems we can just use the old evarmap instead of calling remove. I'll try to see if I can put my hands the right one later today.

**Comment by gares** [comment]
I'm trying to fix this right now

**Comment by gares** [comment]
I did write a fix, please review the PR
