### ISSUE TITLE
Set Printing Parentheses doesn't show some parentheses

### ISSUE THREAD

**Issue by ana-borges** [coq/coq#15322]
#### Description of the problem

`Set Printing Parentheses` doesn't show some parentheses that I expected it to show. Here is an example:
```coq
Variables x y z : nat.

Notation "a `+ b" := (a + b) (at level 50, b at level 50).
Check (x `+ y `+ z).
(*
    x `+ y `+ z
         : nat
*)
Set Printing Parentheses.
Check (x `+ y `+ z).
(*
    x `+ y `+ z
         : nat
*)
(* Expected output:
    x `+ (y `+ z)
         : nat
*)
```

#### Coq Version

I tried with 8.12.2, 8.13.2, and 8.14.0.

**Comment by herbelin** [comment]
Thanks for noticing. There is a fix in PR #17844.
