### ISSUE TITLE
`Print Grammar` should be able to print custom entry grammars

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#15337]
#### Description of the problem

`Print Grammar constr` does not print the grammars of custom entries.  Either it should, or there should be a `Print Custom Grammar` command, or users should be able to do `Print Grammar custom:....` or similar (and it should be documented).

cc @herbelin @coq/parsing-maintainers 

#### Coq Version

8.14

**Comment by herbelin** [comment]
Hi @JasonGross, there is actually already a command `Print Custom Grammar foo` documented [here](https://coq.inria.fr/refman/user-extensions/syntax-extensions.html#coq:cmd.Print-Custom-Grammar) and which seems to do what you describe.

**Comment by JasonGross** [comment]
Ah, I missed that, sorry, and thanks!
