### ISSUE TITLE
feature request: entry-specific identifier/keyword disambiguation

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#15349]
#### Description of the problem

Is there any reason the following couldn't work?

```coq
Inductive cmd: Type := SSkip | SWhile(b: bool).
Declare Custom Entry ent.
Notation "'while' ( b ) { }" := (SWhile b) (in custom ent, b constr).
Notation "ent:( c )" := c (c custom ent).
Goal True.
  pose (ent:( while (true) { })).
  pose (while := true).
  (* Syntax error: [term level 200] expected after '(' (in [term]). *)
  pose (while : nat => while). (* edit: there is a typo on this line, corrected below *)
  (* Syntax error: [term level 200] expected after '(' (in [term]). *)
Abort.
```

#### Coq Version

8.14.1

**Comment by herbelin** [comment]
I agree, keywords should be handled locally to rules, and in particular locally to custom entries. Don't know who could work on it.

**Comment by andres-erbsen** [comment]
My limited understanding of the situation here is that dumb, early keyword detection is baked in deep, and trying to lift that restriction in general might not be easier than full scannerless parsing. However, perhaps this more limited wish could be granted by having a rule that expects an identifier but gets an alien keyword use the text of that keyword as an identifier anyway?

**Comment by herbelin** [comment]
> However, perhaps this more limited wish could be granted by having a rule that expects an identifier but gets an alien keyword use the text of that keyword as an identifier anyway?

In your case, `while` does not need to be a keyword indeed and one could provide a modifier to control which token is a keyword.

**Comment by samuelgruetter** [comment]
When I do `Print Grammar tactic.`, it seems that all Ltac keywords are IDENTs, eg `tryif` appears as `| IDENT "tryif"; SELF; "then"; SELF; "else"; SELF`, whereas in `Print Grammar constr.`, the Gallina keywords appear without IDENT, eg `if` appears as `| "if"; term LEVEL "200"; as_return_type; "then"; term LEVEL "200"; "else"; term LEVEL "200"`.

I guess this is the reason that using Ltac keywords in Gallina works:

```coq
Definition foo(tryif: nat) := tryif.
Goal False.
  pose (tryif := fun tryif: nat => tryif).
```

whereas using Gallina keywords in Ltac doesn't work:

```coq
Ltac foo if := if.
```

What would go wrong if we made all Gallina keywords IDENTs?

**Comment by herbelin** [comment]
> What would go wrong if we made all Gallina keywords IDENTs?

In your case nothing, and this is actually #14562 (available in 8.15).

In rules where an identifier serves as articulation point, as e.g. in `let x := constr in constr`, the `in` should be a keyword, otherwise this is parsed as the application of `constr` to the variable `in`, since the rule for application does not know that `in` should not be parsed as a term.

**Comment by samuelgruetter** [comment]
Aah awesome, thanks @herbelin for the explanation and the link!

**Comment by andres-erbsen** [comment]
Thank you for the pointer, looks like exactly what I wanted! The following passes on current master.

```coq
Inductive cmd: Type := SSkip | SWhile(b: bool).
Declare Custom Entry ent.
Notation "'while' ( b ) { }" := (SWhile b) (in custom ent, b constr).
Notation "ent:( c )" := c (c custom ent).
Goal True.
  pose (ent:( while (true) { })).
  pose (while := true).
  pose (fun while : nat => while).
Abort.
```
