### ISSUE TITLE
coqdep -exclude-dir behaviour

### ISSUE THREAD

**Issue by pjmkrpg** [coq/coq#15359]
#### Description of the problem

My project has the following architecture:
```
Bar/
├─ Bar.v
_CoqProject
Foo1.v
Foo2.v
```
```
% cat _CoqProject
-R Bar Bar
Foo1.v
Foo2.v
```
Now I want to generate the `.depend`  for the Foos that will be included in a Makefile, ignoring dependencies on `Bar` which is a large library with its own compilation scheme:
```
% coqdep -f _CoqProject -exclude-dir Bar
Foo1.vo Foo1.glob Foo1.v.beautified Foo1.required_vo: Foo1.v Bar/Bar.vo
Foo1.vio: Foo1.v Bar/Bar.vio
Foo2.vo Foo2.glob Foo2.v.beautified Foo2.required_vo: Foo2.v Foo1.vo
Foo2.vio: Foo2.v Foo1.vio
```
Why does `Bar/Bar.vo` still appears in the list of dependencies?

#### Coq Version
8.14.1

**Comment by SkySkimmer** [comment]
exclude-dir is about subdirectories, it doesn't cancel the directory directly given to -R

**Comment by pjmkrpg** [comment]
Thanks for your reply, I didn't understand the specification of `-exclude-dir`. (And to be honest I still cannot imagine a situation where this option can be useful). Anyways this is not an issue.

**Comment by SkySkimmer** [comment]
I guess some version control systems put subdirectories everywhere and we don't want to scan them.

**Comment by pjmkrpg** [comment]
Yes but they aren't scanned unless specified with `-R`, right?

**Comment by SkySkimmer** [comment]
Some projects have their v files at the root, so they do `-R . Foo`, then if `./_darcs` exists we skip it (`_darcs` is in the default exclude-dir list)

**Comment by pjmkrpg** [comment]
Ok so let say I  have the following files:
```
% cat _CoqProject
-R . Foo
Foo1.v
% cat Bar/Bar.v
Definition bar_val : nat := 4.
% cat Foo1.v
From Foo Require Import Bar.
Definition neuf := bar_val + 5.
```
I still can't ignore the dependencies on Bar files: 
```
% coqdep -f _CoqProject -exclude-dir Bar
Foo1.vo Foo1.glob Foo1.v.beautified Foo1.required_vo: Foo1.v Bar/Bar.vo
Foo1.vio: Foo1.v Bar/Bar.vio
```

**Comment by SkySkimmer** [comment]
It seems -exclude-dir needs to come first

**Comment by pjmkrpg** [comment]
Good point! It also seems to work in my initial case, ie. `coqdep -exclude-dir Bar -R Bar Bar`. Two suggestions thus:
1) update the usage string for this option of coqdep
2) in this particular case, hush the warning `library Bar is required from root Bar and has not been found in the loadpath` because this is precisely what we expect

**Comment by SkySkimmer** [comment]
But Bar.v really has not been found since we skipped Bar/, the warning is correct.
