### ISSUE TITLE
The `coq-native` opam flag does not enable the native compiler

### ISSUE THREAD

**Issue by pi8027** [coq/coq#15394]
#### Description of the problem

If I install Coq using the opam files in this repo, the `coq-native` flag does not enable the native compiler. The source of this issue is that `coq-core.opam` in this repo does not check the flag.

#### Coq Version

At least 8.15 and master.

**Comment by pi8027** [comment]
Ping @erikmd @ejgallego

**Comment by gares** [comment]
Would you mind trying #15459 , I'm not sure ci tests it right and I don't have time to test it myself.
