### ISSUE TITLE
Separation of parsing and execution

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#15409]
As mentioned in previous discussions, I made some technical experiments which make me believe it is possible to separate parsing and execution phases in Coq, at reasonable cost. This is a meta-issue explaining the approach and tracking progress.

# Why would we want that?

IDEs often need to reason on ASTs. Since execution of documents is often costly in Coq, having to wait in interaction loops degrades the experience. The typical behavior is: you work on a large file, in which you can navigate without trouble. Then you add a `Notation` or an `Import` command in the middle of the file. Suddenly, editing anything above the command requires re-executing before you can work again on the bottom of the document (or at least get useful feedback from the IDE, in a non-blocking model).

From the implementation standpoint, we anyway had to classify commands with parsing effects. But we don't have the proper separation of state that makes it possible to execute these effects without a full execution. In a way, we already pay the complexity but we don't get the benefits.

Other tools than IDEs can benefit greatly from being able to reliably parse Coq documents without executing them. For example, `coqdoc` could just call the parsing API.

# Why is it not so easy?

Remember that Coq has extensible parsing, meaning that some commands can change the grammar. So by a parsing phase, we really mean a _syntactic interpretation_ phase, where we parse text into an AST _and_ maintain the grammar up to date at each point of the document.

# What properties do we want?

Essentially, we want to refine the current vernac interpretation API:

```ocaml
val interp : Vernacstate.t -> Vernacexpr.vernac_control -> Vernacstate.t
```

into:

```ocaml
val synterp : Synterp.State.t -> Vernacexpr.vernac_control -> Synterp.State.t
val interp : Synterp.State.t -> Vernacstate.t -> Vernacexpr.vernac_control -> Vernacstate.t
```

Note that `interp` reads the syntactic interpretation state, but cannot write to it.

The API can be used for example in three ways:
- Folding `synterp` on a document, to get a full AST without executing the document (for example, for `coqdoc`).
- For each sentence, running `synterp` followed by `interp` (for example, for `coqtop`).
- Folding `synterp` on a document, then executing some commands by running `interp` (for example, for IDEs).

# What kind of patches are required?

- The `Notation` command interpretation has to be split in two (one for grammar extension, the other for notation interpretation) https://github.com/coq/coq/pull/15755
- `where` notations should not declare grammar extensions https://github.com/coq/coq/pull/15468
- Nametab state has to be split in two (syntactic interpretation needs to be able to resolve module names) https://github.com/coq/coq/pull/15756
- The summary needs a way to distinguish the part of the system state corresponding to the syntactic interpretation phase
- Module internalization needs to be separated from their interpretation, which requires term typing https://github.com/coq/coq/pull/15500
- Libstack and libobject traversal has to be separated in two, one for each phase
- Parsing effects of `Declare ML modules` on plugins declaring grammar rules have to be separated
- Vernac extensions need to be able to declare commands whose execution has parsing effects (example: `Tactic Notation`)
- `synterp` needs to be implemented as a new dispatch on vernacular expressions

# What could we try next?

Being able to resolve names without fully executing a document would also be a nice feature for IDEs and tools. We could study that next.

**Comment by ppedrot** [comment]
> syntactic interpretation needs to be able to resolve module names

That's just for `Require` and `Import` of modules, or is there something more to it?

**Comment by maximedenes** [comment]
There's `Include` too (and in turn, module aliasing, etc, of course).

**Comment by SkySkimmer** [comment]
>where notations should not declare grammar extensions

Isn't that already true?

**Comment by gares** [comment]
Why does `interp` need to read `Synterp.State.t`?

**Comment by maximedenes** [comment]
> > where notations should not declare grammar extensions
> 
> Isn't that already true?

No, it wasn't, for unknown reasons. Now fixed.

**Comment by maximedenes** [comment]
Closing as I got convinced this line of work cannot be integrated in a reasonable time frame.

**Comment by maximedenes** [comment]
Reopening now that it seems possible again.

**Comment by JasonGross** [comment]
> Why does `interp` need to read `Synterp.State.t`? (do we have commands that invoke the parser?)

`Load`, if it still exists, `Declare ML Module`, and perhaps `Drop` seem like they might need to invoke parsing on behind-the-scenes code.  In theory, we sufficiently fancy tactic scripting languages may want to inspect parsing state (for example if we ever want to extend MetaCoq to verify a Coq REPL it might be useful to have a shortcut for parsing strings as Coq does in the template monad).

Also, doesn't printing currently rely on the current parsing state?  Or is the printing part of notations and the like separated from the parsing part, so that it does not occur in the syntactic state?

**Comment by SkySkimmer** [comment]
I don't know if interp uses the parsing state, but the synterp state is a superset of that which also includes data necessary to generate the parsing state. For instance some module name stuff is in there so that when you `Import M` it knows which module to get notations from.
