### ISSUE TITLE
`apply...with` does not work any more with `(Combined) Scheme` since they have self-conflicting arguments

### ISSUE THREAD

**Issue by Blaisorblade** [coq/coq#15420]
#### Description of the problem

It seems #13837 breaks `apply ... with` for induction schemes (both normal and those produced by `Scheme` and by `Combined Scheme`); in practice that's mostly a problem for `Combined Scheme`s since the `induction` tactic works for everything else.

The problem is that argument names look like:
```
typed_mut_ind :
∀ (P : ctx → tm → ty → Prop) (P0 : ctx → ty → nat → ty → nat → Prop),
Arguments typed_mut_ind
  (P P f f f f f f f f f f f f f f f f f f f)%function_scope 
  Γ t t t
```

dot-iris@9f031fb6f956e900c846284f56d976e66f98b5fa shows a patch that was necessary. In that case `apply (term args)` is a reasonable (and better) alternative, but that alternative would be more annoying for datatypes declared in a `Section`.

I'm not sure what the best fix would be; here one could move the renaming that was done by `apply` into the code generator.
But I wonder whether top-level functions with argument name conflicts should at least trigger a warning.

#### Coq Version

8.15-rc1

**Comment by Blaisorblade** [comment]
@SkySkimmer I imagine you might want to review this; I would not myself consider it a blocker, especially this late, but your call.

**Comment by palmskog** [comment]
Here is a standalone example that works fine in 8.14 and below but breaks completely (on `elim H ...`) in 8.15+rc1 and later:
```coq
Inductive
  even    : nat->Prop :=
    evenO : even  O |
    evenS : forall n, odd n -> even (S n)
with
  odd    : nat->Prop :=
    oddS : forall n, even n -> odd (S n).

Scheme Even_induction := Minimality for even Sort Prop
with   Odd_induction  := Minimality for odd  Sort Prop.

Theorem even_plus_four : forall n:nat, even n -> even (4+n).
Proof.
 intros n H.
 elim H using Even_induction with (P0 := fun n => odd (4+n));
 simpl;repeat constructor;assumption.
Qed.
```
The error message is:
```coq
Error: No such bound variable P0 (possible names are: P, P and n).
```
Which to me is nonsensical because `Check Even_induction` shows:
```coq
Even_induction
     : forall P P0 : nat -> Prop,
       P 0 ->
       (forall n : nat, odd n -> P0 n -> P (S n)) ->
       (forall n : nat, even n -> P n -> P0 (S n)) ->
       forall n : nat, even n -> P n
```
There seems to be no sensible way to refactor this proof in 8.15+rc1 and later, for example, the following do not work:
- `induction H using (Even_induction _ (fun n => odd (4 + n))).`
- `elim H using (Even_induction _ (fun n => odd (4+n))).`
- `apply (Even_induction _ (fun n => odd (4 + n))).`

**Comment by Blaisorblade** [comment]
I agree with @palmskog but let me paste `About`’s output; `Check` lies, and `About` lies first in the type and tells the truth in `Arguments`. Since the type can’t be printed without renaming, Coq should just forbid this shadowing and stop `Scheme` from producing it.

```coq
About Even_induction.

Even_induction :
forall P P0 : nat -> Prop,
P 0 ->
(forall n : nat, odd n -> P0 n -> P (S n)) ->
(forall n : nat, even n -> P n -> P0 (S n)) -> forall n : nat, even n -> P n

Even_induction is not universe polymorphic
Arguments Even_induction (P P)%function_scope f (f f)%function_scope
  n%nat_scope e
Even_induction is transparent
Expands to: Constant min.Even_induction
```

**Comment by mattam82** [comment]
Agreed with @Blaisorblade here, (combined) scheme should not produce these argument names in the first place.

**Comment by mattam82** [comment]
Thanks @herbelin !
