### ISSUE TITLE
`typeclasses eauto with ..` is unaffected by `Strict Resolution`.

### ISSUE THREAD

**Issue by Janno** [coq/coq#15432]
#### Description of the problem

The code below shows inconsistencies in the behavior of different entry points to typeclass search w.r.t. `Strict Resolution`. I expect all of the queries to fail, yet the last one succeeds.
```coq
#[local] Set Typeclasses Strict Resolution.
Class C (P : Prop) (out : Prop) := { c : out -> P}.
#[refine] Instance : C True False := { c := _ }. abstract auto. Defined.
Goal exists q, C True q.
  eexists.
  Fail apply _.
  Fail typeclasses eauto.
  typeclasses eauto with typeclass_instances.
```

#### Coq Version
8.13.1, 8.14.0

**Comment by Alizter** [comment]
In fact all of the following give completely different traces:
```coq
#[local] Set Typeclasses Strict Resolution.
Class C (P : Prop) (out : Prop) := { c : out -> P}.
#[refine] Instance : C True False := { c := _ }. abstract auto. Defined.
Goal exists q, C True q.
  eexists.
  Set Typeclasses Debug.
  Fail exact _.
  Fail apply _.
  Fail typeclasses eauto.
  Fail typeclasses eauto with nocore.
  Succeed eapply _.
  Succeed typeclasses eauto with typeclass_instances.
```
8.16+alpha

**Comment by Janno** [comment]
I think the culprit is https://github.com/coq/coq/blob/91d796ecd11ba6880a4e4397cb14748eedf6ff73/tactics/class_tactics.ml#L315

combined with the fact that `typeclasses eauto with ...` disables `only_classes`. However, I suspect the latter would be fine on its own. I don't see why disabling `only_classes` should circumvent restrictions placed on classes at class definition time.
