### ISSUE TITLE
[setoid_rewrite] CMorphisms breaks rewriting in Prop

### ISSUE THREAD

**Issue by olaure01** [coq/coq#15435]
#### Description of the problem

```coq
Require Import Setoid Morphisms.

Parameter A: Type.
Parameter R: A -> A -> Prop.
#[local] Instance  HR: Transitive R. Admitted.

Lemma issue a b (H : R a b) : R a b.
  rewrite H.
Abort.
```
but failure when `CMorphisms` is imported instead of `Morphisms`:
```coq
Require Import Setoid CMorphisms.

Parameter A: Type.
Parameter R: A -> A -> Prop.
#[local] Instance  HR: Transitive R. Admitted.

Lemma issue a b (H : R a b) : R a b.
  Fail rewrite H.
Abort.
```

This is the remaining part of issue #7675 after PR #14137.

#### Coq Version

Coq 8.14.1 but also 8.16+alpha after #14137

**Comment by SkySkimmer** [comment]
That's because you're defining an instance of CRelationClasses.Transitive instead of RelationClasses.Transitive.
Not a bug AFAICT
