### ISSUE TITLE
Ltac: "only 2:" selector fails.

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15441]
Each of the following fail, although they work with "only 1:".  IIUC they should work with both 1 or 2.

```
Goal False -> True /\ True.
intros.
split.
only 2: once auto.   (* No such goal. *)
```

```
Ltac x := only 2: once auto; idtac.
Goal False -> True /\ True.
intros.
split.
x.   (* Ltac call to "x" failed.
         No such goal. *)
```

**Comment by SkySkimmer** [comment]
Not a bug, the default selector is `1:` and is applied around the whole tactic.

**Comment by jfehrle** [comment]
When is "only 2:" actually useful?  Having to say "all: only 2: once auto." and "all: x." in these examples makes "only" seem pretty useless.  At the least, the documentation for "only" should point out this behavior.

**Comment by SkySkimmer** [comment]
For when it's not a toplevel tactic, eg `foo; only 2: bar`
