### ISSUE TITLE
Legacy build warns cannot-open-dir

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#15482]
On my machine 
~~~bash
./configure -prefix /usr && make
~~~
says
~~~
Warning: Cannot open directory _build_vo/default//lib/coq/../coq-core/plugins
[cannot-open-dir,filesystem]
~~~
on every coqc execution

No idea why this doesn't happen in CI.

**Comment by herbelin** [comment]
I can reproduce. Apparently, `_build_vo/default//lib/coq/../coq-core` is a link to `_build/install/default/lib/coq-core` but `lib/coq-core` is not (yet?) created at the time of executing.
