### ISSUE TITLE
Lia very slow with exponential

### ISSUE THREAD

**Issue by thery** [coq/coq#15481]
#### Description of the problem

While checking this [reply](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/.E2.9C.94.20specification.20of.20the.20lia.20tactic.20on.20non-linear.20problems/near/267709899).
I have been trying this
```coq
Goal forall x : Z, 0 <= x ^ 2.
```
`lia` proves it immediately but it gets slower and slower as the exponential grows.
When testing
```coq
Goal forall x : Z, 0 <= x ^ 32.
```
my computer fan started making funny noise :wink:. Where the blow-up comes from?

#### Coq Version

coq8.14.0

**Comment by SkySkimmer** [comment]
What imports do I need to run these tests?

**Comment by thery** [comment]
```coq
Require Import ZArith Lia.

Open Scope Z_scope.

Goal forall x, 0 <= x ^ 32.
intros; lia.
```

**Comment by thery** [comment]
@fajb any idea why it becomes so slow?

**Comment by Alizter** [comment]
cc @coq/micromega-maintainers

**Comment by fajb** [comment]
I am aware that the algorithm which generates positivity constraints scales badly. 
@ppedrot made some optimisation but the algorithm is to blame for.
That would be the first thing to check but I am not sure this is the culprit.

I agree that this is bad...

**Comment by ppedrot** [comment]
FTR when this issue was submitted, I had a quick look at the microscopic side of the profiling, and didn't see anything in particular to blame. It looks more to me like a macroscopic effect, e.g. the set of constraints exploding or something like that, but I haven't had time to investigate.

**Comment by thery** [comment]
is there  a way to check if it does not generate 2^32 constraints?

**Comment by fajb** [comment]
There is no simple way. There are debug flags but you need to recompile Coq.

**Comment by ppedrot** [comment]
(We should probably expose them as an option, by the way.)

**Comment by thery** [comment]
is there an option to show the linear goal in Z, lia is trying solve after preprocessing?

**Comment by ppedrot** [comment]
There is an option `Dump Arith` that's supposed to output debug data in a tempfile but it doesn't seem to work for me.

**Comment by fajb** [comment]
`Dump Arith "prefix" ` works for me. It generates the goal to be solved. It is before pre-processing.
It should be used with `Unset Lia Cache`.

**Comment by thery** [comment]
What does it give for  `0<= x^8`?

**Comment by fajb** [comment]
@thery 
```
Require Import ZArith Lia. Open Scope Z_scope.
Goal forall (x1 : Z) 
(H0 : -1 + -x1^8 >= 0)
(H1 : -x1 >= 0)
(H2 : -1 + -x1 >= 0)
, False
.
Proof.
 intros. lia.
Qed.
```

**Comment by thery** [comment]
but this s not solvable pure linear arithmetic.

**Comment by ppedrot** [comment]
Not sure if it pushes the *schmilblick* forward but the certificate generated by lia and sent to zchecker is indeed exponential in the exponent size of the example. Obviously if it blows up before sending it to the certificate generator it's another story.

**Comment by fajb** [comment]
As noticed by @thery, this is not solvable by pure linear arithmetic.
Actually, 
```
0 <= x * (x * 1) 
``` is not solved by lia.
If you write instead `0 <= x^2`, `zify` kicks in -- this is desirable when the initial goal is in nat.
With the additional constraints, it is possible to perform interval analysis. This is the "bad" algorithm which seems to produce exponential proof terms.
