### ISSUE TITLE
Minimal zarith version for Coq 8.16.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#15496]
Since the integration of #15483, the lower bound version of the Coq dependency `zarith` is untested. We should (quickly) decide whether we want to officially drop support for zarith 1.10 (which triggers a bug in bedrock2), and update the Docker file so that the minimally supported version is tested. If we do drop support for zarith 1.10, we should update the documentation and write a changelog entry. If we do not drop support, then we should just inform the users that they might hit some bugs with this version and that upgrading can fix them.

Note that it is possible to test zarith 1.10 in the switch that doesn't build bedrock2 and a more recent zarith version in the switch that does.

FWIW the Nix CI currently tests zarith 1.12 as well.

**Comment by ppedrot** [comment]
Is this still relevant?

**Comment by Zimmi48** [comment]
Sure, the version bumped has not been documented:

https://github.com/coq/coq/blob/1fe4a32f4559f181cdbfc6e0436ab17fb8180f4c/INSTALL.md?plain=1#L25

And I don't think we have started testing zarith 1.10 in our CI again.

**Comment by ppedrot** [comment]
Fine, but then somebody needs to fix this quickly.

**Comment by Zimmi48** [comment]
This requires taking a decision though: bump the required version (and fix the doc) or fix the CI.

**Comment by ppedrot** [comment]
If bedrock2 is broken by zarith 1.10, I think that the only sane solution is to bump it to 1.12...

**Comment by Zimmi48** [comment]
Looking again at the PR discussion, this was rushed, but it looks like bumping to zarith 1.11 would have been sufficient to fix bedrock2, so making zarith 1.12 the lower bound doesn't actually sound that reasonable...

**Comment by Zimmi48** [comment]
@ejgallego has suggested anyway that even if we don't bump the required version, we should document that zarith 1.10 is problematic.

**Comment by Zimmi48** [comment]
That being said, zarith 1.12 is already more than one year old and is already the version available in both Debian stable and Ubuntu LTS so let's just admit that it's fine as a lower bound.
