### ISSUE TITLE
Feature wish: Emit warning or error when Hint command implicitly creates a hint DB

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#15522]
Today I misspelled the name of a hint DB in a `Hint` command, and then was surprised why my `eauto` did not work:

```coq
Inductive foo: Prop := mk_foo.

Create HintDb spelled_correctly.

Local Hint Constructors foo : spelled_incorrectly.

Goal foo.
  eauto with spelled_correctly.
```

Therefore, I have a feature wish: It would be useful if all the `Hint ...` commands emitted a warning (or even an error) if the specified hint DB has not previously been declared with `Create HintDb`.

Coq version: 8.15-rc1

**Comment by ppedrot** [comment]
This should probably be considered a duplicate of #4117.

**Comment by samuelgruetter** [comment]
> This should probably be considered a duplicate of #4117.

Indeed, https://github.com/coq/coq/issues/4117 just doesn't contain any of the keywords that I was searching for before opening this issue 😅

**Comment by herbelin** [comment]
This apparently reduces to first solving #8980/#5381 which precisely got some activity recently. It was proposed to have several variants of `Create HintDb` (either using attributes, or a specific syntax, then presumably something like `Create Transparent HintDb` and `Create Opaque HintDb` with `Create HintDb` defaulting to transparent).
