### ISSUE TITLE
Allow `Context (x := ...)` to take arguments

### ISSUE THREAD

**Issue by pi8027** [coq/coq#15523]
#### Description of the problem

The reference manual says that `Context` is "like `Variable`, but also allowing implicit variables, Implicit generalization, and let-binders". However, I cannot really replace `Let` with `Context` for readability reasons if it takes arguments. For example, I cannot write
```coq
Context (f (u : unit) := tt).
```
and instead have to write
```coq
Context (f := fun (u : unit) => tt).
```

#### Coq Version

8.15

**Comment by pi8027** [comment]
It seems that this syntax is shared with binders in terms. I'm not sure this feature request works but will prepare a PR anyway. https://github.com/coq/coq/blob/6b9da1044a57c88591c64086f5eeb30678038603/parsing/g_constr.mlg#L419-L456

**Comment by herbelin** [comment]
Hi @pi8027. For the reason that `(x y : t)` already means `(x : t) (y : t)` in binders, it seems difficult to implement `(x y := t)` as an equivalent for `(x := fun y => t)` in a way which is not too confusing for the reader.

PS: there are a couple of issues related to this question:
- #5298: ambiguity between `Theorem f a b : T` and `Parameter f a b : T` which mean different things
- #13416: how to let `Parameter f a b : T` behave like `Theorem f a b : T`
- #9412/#11390: issues with `Context` 

Different proposals are possible.

**Comment by pi8027** [comment]
@herbelin Thanks. That's certainly true. Maybe I should just close this issue.
