### ISSUE TITLE
Coq UTF8 \nabla - Lexer: Undefined token

### ISSUE THREAD

**Issue by elefthei** [coq/coq#15540]
#### Syntax Error: Lexer: Undefined token

From Coq Require Import Unicode.Utf8.
Definition ∇ := True.

#### Coq Version
The Coq Proof Assistant, version 8.14.0
compiled with OCaml 4.08.1

**Comment by herbelin** [comment]
This is expected because Nabla is a symbol. Only characters of the letter category (or from the number category for the subsequent characters) can be used in identifiers.

You could do the following though:
```
Definition nabla := True.
Notation "∇" := nabla.
Check ∇.
```

**Comment by elefthei** [comment]
I see, thank you.
