### ISSUE TITLE
Strange errors because Coq uses multiple processes for a simple script

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15564]
Using master, it appears that Coq is creating multiple processes to run this very simple script as shown by my debug statements.  The script works fine on 8.15.0 installed with the platform.  In the 2nd process, required initialization  of `ltac_debug_ref` by the top loop hasn't been done.  Of course the debugger isn't set up to work with multiple processes--is anything?

If I remove the `Qed.` (which would generate "Attempt to save an incomplete proof"), I don't get the "Option is None" message.

Something seems grievously broken. What was changed in master?  Suggestions?

```
Set Ltac Debug.
Goal 1 = 2 -> False /\ True.
intros.
split.
2: { auto. }
auto. Qed.
```

Instrumentation in DebugHook.ml:

```
module Intf = struct
  let set hooks = Printf.printf "set DebugHook pid = %d\n%!" (Unix.getpid ()); ltac_debug_ref := Some hooks
  let get () = Printf.printf "get DebugHook is None = %b pid = %d\n%!" (!ltac_debug_ref = None) (Unix.getpid ()); !ltac_debug_ref
```

Console output:

```
set DebugHook pid = 23207
get DebugHook is None = false pid = 23207
get DebugHook is None = false pid = 23207
get DebugHook is None = false pid = 23207
get DebugHook is None = true pid = 23210
get DebugHook is None = true pid = 23210
```

Below: line 298 is: `  let isTerminal () = (hook ()).isTerminal`
hook is:  `  let hook () = Option.get (DebugHook.Intf.get ())`

![image](https://user-images.githubusercontent.com/1253341/151488845-b1ffb27d-5047-4ac1-a8b8-9acfd9b03c2c.png)
<details backtrace>

![image](https://user-images.githubusercontent.com/1253341/151488773-1b7909ff-dc25-423c-9924-198ac21928c0.png)

</details>

**Comment by SkySkimmer** [comment]
coqide has always used multiple processes. Indeed I can reproduce on 8.15.0.

**Comment by jfehrle** [comment]
CoqIDE creates a process for each buffer.  Resetting a buffer spawns a new process.  AFAIK there should only be a single Coq process interpreting the script.  I've run the debugger repeatedly on big scripts for months (e.g. fiat_crypto) without incident like this.

I don't see the problem using Coq platform 8.15.0 on native windows.  I do see the problem when I do a local build of `v8.15` (WSL with Ubuntu).  Oddly, in the latter, the CoqIDE About box says it's `8.16+alpha`.  Not sure if that's related, a separate puzzle or important.  For the platform version, the about box says `8.15.0` as it should.

Have we changed requirements for dune, ocaml, etc. recently?

I'll dig in some more.

**Comment by SkySkimmer** [comment]
>CoqIDE creates a process for each buffer. Resetting a buffer spawns a new process. AFAIK there should only be a single Coq process interpreting the script.

There is a proof worker process for each proof that can be delegated when skipping past its Qed instead of going step by step.

**Comment by jfehrle** [comment]
Then I guess `Set Ltac Debug` should disable multiple workers.

The doc section "Asynchronous and Parallel Proof Processing" talks a lot about CoqIDE.  Maybe it should be a subsection of `Coq Integrated Development Environment`.  Is it relevant (and supported) for other IDEs?  @Zimmi48? 

![image](https://user-images.githubusercontent.com/1253341/151620326-f13cb26f-19ce-4212-8aea-ec1effcf39cb.png)

**Comment by Zimmi48** [comment]
Async proof processing is supported by the (experimental) PG async branch, and I think it is also supported by VSCoq and possibly by Coqtail (cc @maximedenes @fakusb @whonore). For this reason, it probably makes sense to keep it a separate section from CoqIDE in the refman.
