### ISSUE TITLE
Proposal for naming/organizing the functions for destructing/constructing abstractions or products wrt contexts

### ISSUE THREAD

**Issue by herbelin** [coq/coq#15562]
Hi, this is a proposal for (re-)organizing the functions for destructing/constructing abstractions or products over contexts, following a [remark](https://github.com/coq/coq/pull/15453#discussion_r787250431) by @mattam82.

## TL;DR:

The proposal is to standardize the naming of OCaml functions destructing sequences of abstractions or dependent products combined with let-ins, under the scheme:
- either {decompose_,strip_,}{lam,prod}{_n,}{_assum,_decls,}{_red,}
- or {it_}dest{Lambda,Prod}{_wo_LetIn,_or_LetIn,}{_red,}

and to update the current exceptions to the general rule (see proposition 1' below for details on the corresponding semantics).

## Current situation

As of now, we have the following decomposition functions
- decompose_lam [Term,EConstr]
- decompose_lam_n [Term] (unused), [Extraction] (on EConstr)
- decompose_lam_assum [Term,EConstr]
- decompose_lam_n_assum [Term,EConstr]
- decompose_lam_n_decls [Term,EConstr]
- decompose_prod [Term,EConstr]
- decompose_prod_n [Term]
- decompose_prod_assum [Term,EConstr]
- decompose_prod_n_assum [Term,EConstr] (works like decompose_lam_n_decls rather than like decompose_lam_n_assum)

The following functions return the body (i.e. snd (decompose_{lam,prod}{_n,_assum})
- strip_lam [Term]
- strip_lam_n [Term] (unused)
- strip_lam_assum [Term] (unused)
- strip_prod [Term] (unused)
- strip_prod_n [Term] (unused)
- strip_prod_assum [Term]

The following functions return the context (i.e. fst (decompose_{lam,prod}{_n,_assum})
- lam_assum [Term] (unused)
- lam_n_assum [Term] (unused)
- prod_assum [Term], [Hipattern] (on Econstr)
- prod_n_assum [Term]

Non-standard variants
- Nativenorm.decompose_prod/Vnorm.decompose_prod: destProd with reduction and name forcing
- decompose_prod_letin, ad hoc, used internally to termops.ml, I propose to make it local to termops.ml

Functions decomposing using whd-reduction
- dest_prod [Reduction], splay_prod [Reductionops]
- dest_prod_assum [Reduction], splay_prod_assum [Reductionops]
- splay_prod_n [Reductionops]
- dest_lam [Reduction], splay_lam [Reductionops]
- dest_lam_assum [Reduction]
- splay_lam_n [Reductionops]

#### Proposition 1

It does not make sense to strip both {lam,prod} and let-ins by counting only {lam,prod} without telling what to do with the remaining let-ins on the body. So, the proposition is to remove the current behavior of decompose_lam_n_assum and adopt the following:
- {lam,prod}{_n,}assum means removing *only* {lam,prod} (and counting only {lam,prod}) but returning a rel_context
- {lam,prod}{_n,}decls means removing {lam,prod} *and let-ins* and returning a rel_context
- {lam,prod}{_n,} means, like now, removing only {lam,prod} (and counting only {lam,prod}) and returning a list of assumptions)

This means:
- adding decompose_lam_decls as a replacement for the current semantics of decompose_lam_assum (i.e. including let-ins)
- renaming decompose_prod_n_assum into decompose_prod_n_decls, which is what it does according to this proposition
- adding a new decompose_prod_n_assum which works similarly to decompose_lam_n_assum
- otherwise, stopping decomposing let-ins in decompose_{lam,prod}{_n,}_assum (i.e. one needs the decls suffix to decompose let-ins)
- in particular the two existing occurrences of decompose_lam_n_assum disappears (the one in inductive.ml was a bug: it needed reduction, see #15453; the one in inv.ml is actually assuming no let-ins, i.e. the new proposed behavior fits)

#### Proposition 1'

Name all {lam,prod} decomposition functions using only two naming schemes:

- {decompose_,strip_,}{lam,prod}{_n,}{_assum,_decls,}{_red,} for multiple decomposition
- dest{Lambda,Prod}{_red,} for one-step decomposition

The meaning for {decompose_,strip_,} is the following:
- decompose: returns context and body
- strip: returns body
- nothing: returns context

The meaning for {_assum,_decls,} is as in proposition 1.

The meaning of {_n,} is to stop after n {assum,decls,} or to continue until there is no more {assum,decls}.

The meaning of _red is to additionally whd-reduce to find the {assum,decls,} (this requires to pass the environment)
- with assum or nothing, reduction is whd_all
- with decls, reduction is whd_allnolet

In particular:
- {dest,splay}_{lam,prod} are renamed to decompose_{lam,prod}_red
- splay_{lam,prod}_n are renamed to decompose_{lam,prod}_n_assum_red (assum because no let-ins)
- {dest,splay}_{lam,prod}_assum are renamed to decompose_{lam,prod}_decls_red (decls because let-ins are preserved)
- {decompose_,strip_,}{lam,prod}_assum are renamed to decompose_{lam,prod}_decls (decls because let-ins are preserved)

Note: An alternative to the decompose radical would be to use instead the prefix it_dest and to capitalize {lam,prod}. One would then respectively have: {it_}dest{Lambda,Prod}{_wo_LetIn,_or_LetIn,}{_red,}.

Note: An alternative to the suffix red could be a prefix whd (following the whd_all) or hnf (following the model of hnf_prod_applist).

Note: An alternative to renaming many "assum" to "decls" would be to keep "assum" and rename the only exception (namely decompose_lam_n_assum) in something else. However "decls" is better to mean both Lam/Prod and LetIn and "assum" to mean only Lam/Prod, consistently with the other uses of "assum" in the codebase, so even if it is more renaming, this seems better.

Note: should {lambda,prod}_app{list,vect}_assum be renamed into {lam,prod}_app{list,vect}_decls? Or maybe in {lam,prod}_app{list,vect}_context?

Note: should lam be replaced by lambda by consistency with Lambda/Prod?

#### Proposition 2

Move all Termops.{it_,}mk{Lambda,Prod}{,{_or,_wo}_Letin} etc. in EConstr where some already exist duplicated.

Incidentally, deprecate compose_lam [Term, EConstr] which is redundant with it_mkLambda.

#### Proposition 3

Termops has both extensions of Term and extensions of EConstr. A proposition is to create EConstrops out of Termops for what is relevant to EConstr and to keep in Termops only extensions of Term (i.e. constr related).

An alternative is to have only EConstr and to move the econstr part of Termops in EConstr.

**Comment by mattam82** [comment]
I think we can stay with `decompose` and `red`. I would like an EConstr/EConstrops module with everything together. Otherwise I think proposition 1 (uniformizing) is fine. In all case for the _n variants we're always only counting non-let-in declarations right?

**Comment by herbelin** [comment]
> In all case for the _n variants we're always only counting non-let-in declarations right?

- decompose_lam_n_assum doesn't count let-ins (but push them to the context)
- decompose_prod_n_assum and decompose_lam_n_decls do count letins (inconsistently, then)

All _n functions without _assum nor _decls don't count let-in (de facto).

In the proposal there is also the idea that if n does not include the count let-ins, then finding let-ins is an error, that is, if n does not count let-ins, then no let-in should be on the way when looking for n lam/prod (otherwise, there would be an ambiguity when after n lam/prod we find a let-in: does it belong to the context or to the body?). In practice, this seems to be what we want, that is, when we count the number of lam/prod excluding let-ins, it is because we have a term known to be without let-ins on the way.

> I think we can stay with `decompose` and `red`.

Yes, this seems more friendly. I don't why, I find the it_mkLambda_or_LetIn_red name frightening.

**Comment by mattam82** [comment]
Right, there is an ambiguity with the potential last let-in. If indeed we never need the ambiguous variant life is better :)
I'm not frightened by `_red` personally, I mean the function does reduction so better make it apparent in its name, I think it improves over `dest` and `splay` which are not as explicit.

**Comment by herbelin** [comment]
Since there is already `hnf_prod_applist` with a prefix `hnf_` which I find reasonably expressive, I'd be tempted to prefer it to a `_red` suffix considering that the latter looks also ambiguous (is it `redex`, `reduce`, `reduction`, a color, ...).

No objection on your side?
