### ISSUE TITLE
Proof Diff Anomaly

### ISSUE THREAD

**Issue by whonore** [coq/coq#15578]
#### Description of the problem

In Coqtail and CoqIDE the following script prints `Anomaly "Uncaught exception Failure("hd")"` at the indicated line. There is no anomaly if proof diffs are disabled.
Possibly related: #14425

```coq
Set Diffs "on".

Variable A: Type.

Inductive P : list A -> list A -> Prop :=
  | P1 : forall x xs, P xs (x :: xs)
  | P2 : forall x xs ys, P xs ys -> P xs (x :: ys).

Goal well_founded P.
Proof.
  red; enough (forall ys xs, P xs ys -> Acc P xs).
  - intros [].
    + admit.
    + eapply H.
      constructor. (* <- Anomaly "Uncaught exception Failure("hd")." *)
```

#### Coq Version

8.14, master (381b6e5aca8a21f9895784920d70f768d5851099)

**Comment by Zimmi48** [comment]
cc @jfehrle

**Comment by whonore** [comment]
Interestingly, running this script through coqtop does not print an anomaly. This would be fine except it means I can't use the bug minimizer script for these kinds of issues. Is there some command or set of flags I could use to make coqtop print the same error?

**Comment by jfehrle** [comment]
I think not.  `coqtop` checks that there are no foreground goals in a different code path.
