### ISSUE TITLE
[wish] External File

### ISSUE THREAD

**Issue by gares** [coq/coq#15600]
I need this for Coq-Elpi but other tools may benefit from it.
The problem is that a `file.v` file may need an external file `dep.xyx`, but `coqdep` does not know it.

Mock up of the desired feature.
```coq
External File "bla/dep.xyz" From some.load.path As x.

Elpi Accumulate File x. (* the command in need of dep.xyz *)
```
`x` is a name for an external file (valid in the scope of the current `file.v` file only) which has to be found in a directory mapped to `some.load.path` by `-R` and co, here for example `-R external/ some.load.path`.

`coqdep` would print stuff like `file.vo: file.v external/bla/dep.xyz`

`Elpi Accumulate` (or any other command in need of external files) would need to access some sort of DB which maps `x` to `("fullpath_upto_external" , "external/bla/dep.xyz")`. In particular the `fullpath_upto_external` is needed because PG and coqc/vscode behave differently, e.g. PG runs chdir to the dir containing `file.v`, and `Elpi Accumulate` does not want to care about this detail.

CC @ejgallego @Blaisorblade

**Comment by gares** [comment]
FTR, today Elpi users mitigate the issue of `coqdep` not spitting the right deps by adding lines like `file.v: external/dep.xyz` in `Makefile.local`. No workaround is known for `dune`.

**Comment by ejgallego** [comment]
Dune indeed relies on coqdep, you can use a hack by adding the file as a dependency of a generated .v file, but that's very ugly. It'd be very easy to add a `(extra_files ...)` field to `(coq.theory ...)` but IMHO fixing coqdep is better.

**Comment by gares** [comment]
Simpler design
```coq
External Dependency "file" From LoadPath foo.bar.
```

Here coqdep would just spit an extra dependency after resolving it.
I wonder if other forms may come in handy in the future, eg

```coq
External Dependency "z3" From Path. (* hammer *)
```

Not sure `dune` would be able to do anything sensible with a dep like `/usr/bin/z3` tough, so maybe this one should just check the presence of the external utility.

**Comment by ejgallego** [comment]
> Not sure `dune` would be able to do anything sensible with a dep like `/usr/bin/z3` tough, so maybe this one should just check the presence of the external utility.

In theory yes, this is for example how `ocamc` is tracked, for if the hash of it changes, it will (correctly) rebuild your whole project. Tho IMHO I wouldn't extend this proposal too much in that way, as these deps should not be managed by the user (but by the plugin requiring z3 registering properly)

I wonder about the syntax tho, how would `From LoadPath foo.bar Require File "file".` look instead?

**Comment by gares** [comment]
That would break a development with `File.v`.

Another point is being forward compatible. For example `Set External Dependency "foo.bar/some/path.xx"` is accepted in old Coq versions as well.

**Comment by ejgallego** [comment]
Oh indeed, so maybe something that starts with From as of uniformite but not require indeed.

> For example `Set External Dependency "foo.bar/some/path.xx"` is accepted in old Coq versions as well.

That could be a nice one!

**Comment by SkySkimmer** [comment]
What's wrong with the original proposal?

**Comment by gares** [comment]
> For forward-compatibility, is there a way to use attributes instead?

I've always thought so, but most standard commands are strict in the attributes they accept (they error on unknown attributes).

> `Set` has probably append semantics

Indeed. Maybe I could go for:

```coq
Set Extra Dependency "load.path/file/path". (* for fwd compat, Set sucks but well... *)
From load.path Declare Extra Dependency "file/path". (* if you don't care about old version *)
From load.path Declare Extra Dependency "file/path" As name. (* not in the first PR maybe, but doable *)
```
and maybe also a `... Dependencies "one" "two" ... `

**Comment by SkySkimmer** [comment]
>I've always thought so, but most standard commands are strict in the attributes they accept (they error on unknown attributes).

Unknown attribute is a warning (which defaults as error) so can be disabled.

**Comment by ejgallego** [comment]
Nothing wrong with the original proposal but IMHO it looks more consistent with the `From` at the beginning, last one by @gares looks very nice to me
