### ISSUE TITLE
`only printing` notations accept inexistent custom entries

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#15619]
The following example is accepted by Coq without any error:

```coq
Notation "[ x ]" := (id x) (x custom doesntexist, only printing).
```

Expected behavior: An error `Undeclared custom entry: doesntexist` should be raised.

Coq version: both master from a few weeks ago and 8.15-rc1 are affected.

**Comment by herbelin** [comment]
Thanks for reporting! Fixed in #15628.
