### ISSUE TITLE
[micromega] Segmentation fault if old cache not cleared after #15584

### ISSUE THREAD

**Issue by olaure01** [coq/coq#15629]
#### Description of the problem

Manual build by `make -f Makefile.dune world` fails with:
```
coqc theories/Arith/.Cantor.aux,theories/Arith/Cantor.{glob,vo} (got signal SEGV)
```

[EDIT] the other problem was due to a bad old makefile configuration not clearing `.lia.cache`, I delete it.

#### Coq Version
master on `Ubuntu 18.04`:
- fails on master
- OK at 293ee82

due to #15584?

**Comment by Alizter** [comment]
cc @coq/micromega-maintainers

**Comment by herbelin** [comment]
I just observed the same thing while compiling master. Cleaning the environment fixed the problem and I suspect an issue with dune cache (maybe an interference between lia's cache and dune's cache?). I did it with an `rm` but I believe the normal way to clear the dune cache is `dune cache trim --size=0B`.

**Comment by olaure01** [comment]
`dune cache trim --size=0B` is not enough to make it for me.

**Comment by SkySkimmer** [comment]
Does it reproduce with dune cache disabled?

**Comment by olaure01** [comment]
How to test it?

**Comment by herbelin** [comment]
Maybe the `git clean` and/or `dune clean` are also necessary to remove the `.lia.cache` and `.nia.cache` around?

You would also need to restart the opam installation with the cache cleared (or disabled) I guess.

**Comment by herbelin** [comment]
So, the conclusion is that one just needs to remove the `.lia.cache` and `.nia.cache`?

Maybe a test of compatibility of the lia cache format could be done to get a softer error than a segfault?

**Comment by olaure01** [comment]
@herbelin I agree that seems to be a matter of clearing cache. `dune` build works for me on master after `dune clean`.

**Comment by mattam82** [comment]
Same here, had to clear .lia.cache to avoid segfaults (in a non-dune build system).

**Comment by mattam82** [comment]
@JasonGross agreed, this will hit everyone using lia.
