### ISSUE TITLE
Documentation for `DECLARE PLUGIN "..."` string format

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#15631]
After the introduction of #15220, the string that is required to be inside of `DECLARE PLUGIN "..."` in `.mlg` files appears to be the public name of the plugin.

When one chooses another name, declared commands work properly, but declared tactics cannot be found (not sure why). It would be ideal if an error could be thrown when the wrong string is put for `DECLARE PLUGIN "..."` (or maybe we can just get rid of it altogether?). Otherwise, some documentation would be nice.

**Comment by gares** [comment]
I think I've attached the error to `Declare ML Module "xxx"` here:
https://github.com/coq/coq/blob/a44be146d5a8861d960ef0640a397266e03f443c/tools/coqdep_common.ml#L202

which already had to match `DECLARE PLUGIN "xxx"`. One could use the same error message/error detection code in coqpp:
https://github.com/coq/coq/blob/a44be146d5a8861d960ef0640a397266e03f443c/coqpp/coqpp_main.ml#L621

**Comment by Amit-Morade** [comment]
I would like to work on this

**Comment by SkySkimmer** [comment]
I think the documentation was added in https://github.com/coq/coq/pull/16644 and we should just close the issue actually.
