### ISSUE TITLE
Adding a Printf.printf causes CoqIDE to fail

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15648]
Adding printfs (e.g. for debugging) can cause CoqIDE to fail.  IIUC the startup code captures stdout from the coqidetop process and adds to the command line arguments.  For example, in `coqtop.ml`, this added printf causes a failure.  Also note it creates a "hi mom" buffer in CoqIDE.

```
let start_coq custom =
  Printf.printf "hi mom\n%!";
```
![image](https://user-images.githubusercontent.com/1253341/153075353-fd9df049-6afc-4cf0-9c0c-83a6dcdf0b33.png)

![image](https://user-images.githubusercontent.com/1253341/153075056-2360666c-316d-4571-8e70-a2773230ea2e.png)

**Comment by Alizter** [comment]
This is because coqide is interfacing with coqidetop no? So the "hi mom" is getting picked up by coqidetop and that errors?

**Comment by jfehrle** [comment]
The log file:

`Start eval_call Init Some("/home/proj/coq/hi mom.v")` is not good, nor is
`Handshake with proofworker:0 failed: Failure("Marshal.data_size: bad object")`

```
[DEBUG] Loading file starts
[DEBUG] Loading: get raw content
[DEBUG] Loading: convert content
[DEBUG] Input is UTF-8
[DEBUG] Loading: create view
(Spawn  ,20374) EXEC: /home/proj/coq/_build/default/dev/shim/../../../install/default/bin/coqidetop.opt -main-channel stdfds --xml_format=Ppcmds -async-proofs on -R /home/proj/empty-dir/mod1 Mod1 -I /home/proj/coq/_build/default/dev/shim/../../../install/default/lib -coqlib /home/proj/coq/_build/default/dev/shim/../..
(Spawn  ,20374) PID 20379
[DEBUG] Start eval_call Init Some("/home/proj/coq/hi mom.v")
[DEBUG] End eval_call
[DEBUG] Loading: stats
[DEBUG] Loading: fill buffer
[DEBUG] selection_bound moved
[DEBUG] Loading: success
[DEBUG] End of Coqide.main
Handshake with proofworker:0 failed: Failure("Marshal.data_size: bad object")
[DEBUG] Coqtop reader failed, resetting: Coq.TubeError("HUP")
```

**Comment by jfehrle** [comment]
> This is because coqide is interfacing with coqidetop no? So the "hi mom" is getting picked up by coqidetop and that errors?

coqidetop executes the Printf.  In Linux, communication between CoqIDE and coqidetop is over a socket.

**Comment by ppedrot** [comment]
FWIW, I routinely use `Printf.eprintf` for printf-debugging and AFAICT it doesn't cause issues with CoqIDE.

**Comment by silene** [comment]
> In Linux, communication between CoqIDE and coqidetop is over a socket.

No, it is not. On Linux, by default, Coqidetop is run with options `-main-channel stdfds`. As the name implies, it means that `stdin` and `stdout` are being used for communication. So, it is completely expected that writing garbage on `stdout` will break the protocol. There is no bug here.

And as Pierre-Marie already stated, the battle-hardened way of debugging things is plain `Printf.eprintf`.

**Comment by jfehrle** [comment]
> And as Pierre-Marie already stated, the battle-hardened way of debugging things is plain Printf.eprintf.

Inserting `Printf.printf ...` in, say, Tacinterp.vernac_debug (called for `Set Ltac Debug`) prints just splendidly.  I've been using this approach _all_ the time.  `eprintf` should be written down so it's discoverable.

But I'm completely puzzled by the process structure for the startup of CoqIDE:
2194 (coqide) creates 2199 (coqidetop.opt)
2199 creates 2202 (coqproofworker.opt)

So far so good.  But where do process numbers 2916 and 2915 come from to end up in "hi mom in **2916** (ppid **2195**)" in the buffer name??


```
COQIDE main pid = 2194

EXEC: /home/proj/coq/_build/default/dev/shim/../../../install/default/bin/coqidetop.opt -main-channel stdfds --xml_format=Ppcmds -async-proofs on -R /home/proj/empty-dir/mod1 Mod1 -I /home/proj/coq/_build/default/dev/shim/../../../install/default/lib -coqlib /home/proj/coq/_build/default/dev/shim/../..
spawn_pipe: pid 2194 created pid = 2199
IDETOP pid = 2199

EXEC: /home/proj/coq/_build/default/dev/shim/../../../install/default/bin/coqproofworker.opt -main-channel stdfds -R /home/proj/empty-dir/mod1 Mod1 -I /home/proj/coq/_build/default/dev/shim/../../../install/default/lib -coqlib /home/proj/coq/_build/default/dev/shim/../.. -worker-id proofworker:0 -async-proofs-worker-priority low
spawn_pipe: pid 2199 created pid = 2202
```

![image](https://user-images.githubusercontent.com/1253341/154211201-de9a59b7-987a-41db-b4b9-018594c0630d.png)

```
let start_coq custom =
      :
  Printf.printf "hi mom in %d (ppid %d)\n%!" (Unix.getpid ()) (Unix.getppid ()); (* opens a buffer but works *)
  custom.run ~opts custom_opts state
```

**Comment by silene** [comment]
The starting process looks as follows:
```
coqide
|`- sh -c
|    `- coqidetop -nois -batch
|`- sh -c
|    `- coqidetop -batch
 `- coqidetop -main-channel stdfds
     `- coqproofworker -main-channel stdfds
```
So, if `coqide` has PID 2194, then 2195 and 2196 are respectively the first `sh` and first `coqidetop`.

As for the purpose of the first two `coqidetop` instances, I am not quite sure. Given your experiment, the first one seems to be to recover the names of the files passed on the command line.

**Comment by jfehrle** [comment]
Whatever the underlying cause, it has some more serious symptoms that should be fixed.  

If I run `coqide -config` in 8.15.0, an empty window appears.  After perhaps a minute, the top menu appears and I see this message at the bottom of the panel, at which time the menu and toolbar appear with no `*scratch*` buffer.  If I try to create a new buffer, the GUI hangs.  Same thing for `-where`, though `-help` works as it should.

![image](https://user-images.githubusercontent.com/1253341/156874891-12b6caf6-7e0b-42a5-b447-2a04df166828.png)

If I run `dune exec -- dev/shim/coqide-prelude -config`, nothing is printed.  If I add a several second loop at the end of `Coqinit.print_query`, I see following all at once.  

![image](https://user-images.githubusercontent.com/1253341/156874470-f56668b6-c36c-4a32-ab79-b8aadd6bd4b3.png)
![image](https://user-images.githubusercontent.com/1253341/156874500-c37db51d-3c23-4de5-9c01-bdd327dfa885.png)
![image](https://user-images.githubusercontent.com/1253341/156874514-ee2706e6-02be-4921-b723-025779f7741d.png)
![image](https://user-images.githubusercontent.com/1253341/156874518-a691cdff-8c94-4fc6-bf31-51e4f7492ba4.png)
![image](https://user-images.githubusercontent.com/1253341/156874526-e114a2f2-c462-42b6-99ab-811131fc86b8.png)
![image](https://user-images.githubusercontent.com/1253341/156874537-6fdf8bec-2632-4391-81ee-449524e38686.png)
![image](https://user-images.githubusercontent.com/1253341/156874547-ebc913c5-73a6-47f4-b3b3-727b71b7bbce.png)

**Comment by ppedrot** [comment]
@jfehrle please reopen a distinct issue, the problem you describe is not related to the original one.
