### ISSUE TITLE
dune misses transitive dependencies of vo files on plugins

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#15649]
ie https://github.com/coq/coq/issues/10874 reopened by #15220

**Comment by ejgallego** [comment]
You mind copying a reproduction case so i can have a look at it next week?

**Comment by ejgallego** [comment]
I think I understand indeed what is going on now.

**Comment by gares** [comment]
> ie #10874 reopened by #15220

can someone explain how it happens?

**Comment by SkySkimmer** [comment]
Just reread the original issue

**Comment by gares** [comment]
Oh I see, I did remove the hash because I don't get my hands on the full path anymore. I need to check if findlib gives me access to that.

**Comment by ejgallego** [comment]
Note that dune could compute the transitive deps itself, and that has certain advantages, for example sandbox mode for rules works again.

But the downside is that the dep graph grows really gigantic!

**Comment by gares** [comment]
`Fl_package_base.query` seems to be a first step, but it is a bit low level. I will have to try.

**Comment by ejgallego** [comment]
@gares it is definitively possible to get the path so you can compute the hash, i guess we can ping Gerd if we have some questions

**Comment by gares** [comment]
I'm on it.

**Comment by SkySkimmer** [comment]
I just finished a patch ;)

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/15651
don't know if this is the same approach you were thinking of doing

**Comment by gares** [comment]
identical, but not finished yes... so there you go
