### ISSUE TITLE
Document how to work on Coq with VSCode 

### ISSUE THREAD

**Issue by Blaisorblade** [coq/coq#15684]
https://github.com/coq/coq/tree/master/dev/doc / https://github.com/coq/coq/wiki/DevelSetup don't cover VSCode yet, fixing that might be helpful.

**Comment by galois1** [comment]
Hi,
We added a section for vscode https://github.com/coq/coq/wiki/DevelSetup#vscode; does it help?

**Comment by Blaisorblade** [comment]
Thanks! But I get:

> An error occurred starting the language server `ocamllsp`. Sandbox initialization failed: `ocaml-lsp-server` is not installed in the current sandbox.

I imagine I need some combo of `opam user-setup`, installing X opam packages, running Y commands to generate `.merlin` files, and maybe more. Some of that might be shared across editors. Where are those docs?

**Comment by Alizter** [comment]
You need to `opam install ocaml-lsp-server`

**Comment by Blaisorblade** [comment]
Sounds great. And seems to work without `.merlin` files... From my POV this issue can be closed.
