### ISSUE TITLE
Ltac2 type errors do not rely on function signatures

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#15687]
```coq
Require Import Ltac2.Ltac2.

Ltac2 rec foo(i: int)(j: int) :=
  foo i (bar j)
(*^^^*)
with bar(i: int) :=
  Int.add (foo i (*i*)) 1.
```

results in an error at the *first* usage of `foo` saying `This function has type int -> int and is applied to too many arguments`, even though `foo` is declared to have *two* `int` arguments.
It seems that while typechecking the body of `foo`, its type is inferred from its usage in `bar`, but error messages would be more correct if its type was taken to be as annotated.

Desired behavior: The error should point to the first argument of `Int.add`, and say that it's of type `int -> 'a`, but an expression of type `int` was expected.

(I know that OCaml's typechecker sometimes has similar problems, but I still wonder if we can't do better than that...)

Coq version: 8.15-rc1

**Comment by ppedrot** [comment]
I tweaked the title because it sounded much more concerning than it actually is. Still a usability issue, but it's not a soundness bug in the typing algo.

**Comment by SkySkimmer** [comment]
It's also strange that we check the fixpoints in reverse order. Why do we fold_right at https://github.com/coq/coq/blob/302334cd0e3961a8476e8071ca4482318e0dce6f/plugins/ltac2/tac2intern.ml#L927 ?

**Comment by ppedrot** [comment]
No idea, it's really an implementation-specific detail. It only matters precisely for the kind of user issue at stake.
