### ISSUE TITLE
ill-typed `constr:(...)` in Ltac2 sometimes results in anomaly instead of typing error

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#15681]
When I try to build an ill-typed constr in Ltac2, I usually get a typing error. For instance,

```coq
Require Import Ltac2.Ltac2.

Definition foo{E: Type}(f: E -> E): nat := 0.

Ltac2 feed_one_to_foo () := constr:(foo 1).

Fail Ltac2 Eval feed_one_to_foo ().
```

results in

```
The command has indeed failed with message:
The term "1" has type "nat" while it is expected to have type "?E -> ?E".
```

which is very useful to debug my tactics.
However, if I do

```coq
Ltac2 feed_constr_to_foo(x: constr) := constr:(foo $x).

Ltac2 Eval feed_constr_to_foo constr:(fun (a: nat) => a + 1).  (* succeeds *)

Ltac2 Eval feed_constr_to_foo constr:(1).
```

I get

```
Error: Anomaly "Uncaught exception Evarconv.UnableToUnify(_, 1)."
Please report at http://coq.inria.fr/bugs/.
```

Desired behavior: It should also print a typing error like above.

Coq version: 8.15-rc1

/cc @ppedrot

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/blob/ed5f1f64398cf5f1148d5784a5689e18b1a1ee35/plugins/ltac2/tac2core.ml#L1505 needs to be in a try-catche converting the error to Pretype_errors.UnexpectedType
