### ISSUE TITLE
Ltac2 apply has issues with implicit arguments

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#15691]
#### Description of the problem

With Ltac2 the `apply` tactic has issues with implicit arguments as the following example shows:

```
Require Import Ltac2.Ltac2.

Require Import ZArith.
Open Scope Z_scope.
Lemma Z_add_bounds {amin a amax bmin b bmax : Z}:
  amin <= a <= amax ->
  bmin <= b <= bmax ->
  amin+bmin <= a+b <= amax+bmax.
Admitted.

Lemma foo l1 l2 v1 v2 u1 u2 : l1+l2 <= v1+v2 <= u1+u2.
Proof.
  Fail apply Z_add_bounds.
```
It results in
```
The command has indeed failed with message:
Cannot infer the implicit parameter amin of Z_add_bounds whose type is "Z" in
environment:
l1, l2, v1, v2, u1, u2 : Z
```
The same does work as expected if the `Require Import Ltac2.Ltac2.` is removed.

#### Coq Version

```
The Coq Proof Assistant, version 8.15.0
compiled with OCaml 4.10.2
```

**Comment by SkySkimmer** [comment]
the `apply` notation in Ltac2/Notations.v is doing `Std.apply true false [fun () => (constr:(Z_add_bounds), Std.NoBindings)] None.`, I guess it should be `open_constr`?

**Comment by ppedrot** [comment]
Probably.
