### ISSUE TITLE
string notations break on partial strings with anomaly

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#15709]
#### Description of the problem

```coq
Require Import Coq.Strings.String.
Require Import Coq.Strings.Ascii.
Check String "]".
```
gives
```
Error: Anomaly "Uncaught exception Invalid_argument("index out of bounds")." Please report at http://coq.inria.fr/bugs/.
```

This worked fine in Coq < 8.10; in 8.10 -- 8.13, it printed incorrectly as:
```
""%string
     : string -> string
```

The anomaly shows up since 8.14

#### Coq Version

8.14, also master 89c143ea69d9e615436e1227c720d6eb8fa5e487

**Comment by SkySkimmer** [comment]
Since b0f8e09c3212fa96934817e7ca99465cd634f57c which dropped a typing check.
