### ISSUE TITLE
README.md build instructions for plugin tutorials seem to be out of date

### ISSUE THREAD

**Issue by tlringer** [coq/coq#15718]
Hi all, I'm currently modifying the plugin tutorials so that i can release them as a class exercise. However, I am unable to build them using the instructions from the README.

I know at some point Coq ported most of the build system to Dune---how would one go about building the plugin tutorials, now? While `dune build` does not complain for me, I encounter a number of other problems:

* When I run `coqc Demo.v`, it still cannot load the tutorial even after I've built
* `dune install` and `dune build @install` do not work
* Trying to open Demo.v in CoqIDE gives a complaint about the line about `src/META.coq-plugin-tutorial` in the `_CoqProject` file, and does not open anything

I'm happy to update the README once I can get things building, but I can't right now.

Also, how would one build the tutorial if using not a local version of Coq, but a version of Coq from opam? Particularly if I copy the directory for plugins outside of the `coq` Github directly, to make a lab for students, then even `dune build` does not work.

Thanks!

**Comment by gares** [comment]
Yup, it seems the `plugin-tutorial:` target in `Makefile.doc` is overwriting it.
Funnily enough it is not my recent commit related to findlib that did that, but rather f590493defdae8a84e6c88ac981f89ac33744891

**Comment by tlringer** [comment]
Thanks. Indeed, looks like the ancient problem of my opam environment getting out of sync. Somehow still manage to make this mistake after so many years...

So I don't need this open after all (sorry!) but if it helps for the unrelated bug that you've found, feel free to leave it open.
