### ISSUE TITLE
Can only delete accepted input in CoqIDE

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#15725]
#### Version

Coq 8.15.0

#### Operating system

Red Hat Enterprise Linux Workstation 7.9

#### Description of the problem

The following actions demonstrate an annoying regression,
where any attempt to modify accepted text results in its deletion.

* Open CoqIDE.
* Insert `Goal False.` into the buffer.
* Navigate forward.
* Select `False`.
* Start writing `True` in its place.

Observe how inserting `T` deletes `False` and
the subsequent inputs result in `Goal rue.`
becoming the contents of the buffer.

**Comment by Zimmi48** [comment]
cc @jfehrle

**Comment by Alizter** [comment]
See https://github.com/coq/coq/issues/15675

**Comment by Tuplanolla** [comment]
Focus is not lost in this case.

**Comment by Alizter** [comment]
There are a few issues bundled in that thread, I meant specifically https://github.com/coq/coq/issues/15675#issuecomment-1047819351

**Comment by jfehrle** [comment]
#15714 will fix this.
