### ISSUE TITLE
make ignores `-j` when invoking dune

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#15730]
Coq's make-based install script has become very unfriendly.  It makes my machine lag by ignoring `-j` and spawning as many dune processes as I have CPUs, presumably because `dune` is not passed the same `-j1` flag?

cc @ejgallego

**Comment by herbelin** [comment]
Not an authoritative answer, but there are workarounds such as globally adding `(jobs 1)` in `.config/dune/config`, calling `Makefile.dune` with `DUNEOPT=-j1`, calling `Makefile.install` with `_DOPT=-j1`.

**Comment by ejgallego** [comment]
Yes we need to polish this; on the originis of the infrastructure, we understood that dune would get support for make's jobserver; but unfortunately in the end it was decided that such feature couldn't work well, so our original plan fell apart.

c.f. https://github.com/ocaml/dune/pull/4331

**Comment by ejgallego** [comment]
Note that I think we can improve this without having to implement the jobserver protocol in dune. Will provide more details next week.
