### ISSUE TITLE
CoqIDE ignores_CoqProject file options

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15749]
While the doc says "**CoqIDE**, Proof General, VsCoq and Coqtail all
understand `_CoqProject` files and can be used to invoke Coq with the desired options", it appears this doesn't work for CoqIDE, though it seems to call code that processes the file.

I created this `_CoqProject` in the root directory of my source tree:

```
-R _build_ci/fiat_crypto/src Crypto
-R _build_ci/rewriter/src/Rewriter Rewriter
-I _build_ci/rewriter/src/Rewriter/Util/plugins
```

These are the options I've been using all along as a test of the debugger.  They work just fine in the command line after `dune exec -- dev/shim/coqide-prelude`.  But if they're only in `_CoqProject` then they're not applied.  They don't appear in the command line used to create coqidetop:

`(Spawn  ,16816) EXEC: /home/proj/coq/_build/default/dev/shim/../../../install/default/bin/coqidetop.opt -main-channel stdfds --xml_format=Ppcmds -async-proofs on -I /home/proj/coq/_build/default/dev/shim/../../../install/default/lib -coqlib /home/proj/coq/_build/default/dev/shim/../..`

When I try to step through tactics, a require from `Rewriter` fails:

![image](https://user-images.githubusercontent.com/1253341/155928925-7c06daad-1944-48fa-b2d6-a77274adf0dc.png)

I tried all 3 settings below to no avail:

![image](https://user-images.githubusercontent.com/1253341/155929472-750918ba-469b-45f4-971f-f13af428b76b.png)

I thought that the project file would be a better way to pass the -R -Q and -I options.  (For discussion in a future issue/PR: CoqIDE should let you switch to a different _CoqProject from within the GUI rather than having to restart CoqIDE and point to a different _CoqProject file with a command line option.)

**Comment by jfehrle** [comment]
@gares, your thoughts?

**Comment by gares** [comment]
IIRC there is a caveat, like that the options are only used if the buffer is a .v file listed in the project. I believe this is not desirable, but may explain what you see.

**Comment by ppedrot** [comment]
Did you set correctly the "Default name for project file" option? On your screenshot it seems empty, which would explain why it doesn't work. You have to set it to `_CoqProject` or otherwise explicitly pass the `-f _CoqProject` option to CoqIDE.

**Comment by jfehrle** [comment]
It's set to _CoqProject, just obscured in the screenshot.

**Comment by jfehrle** [comment]
> IIRC there is a caveat, like that the options are only used if the buffer is a .v file listed in the project. I believe this is not desirable, but may explain what you see.

Adding `_build_ci/fiat_crypto/src/Rewriter/Passes/ToFancyWithCasts.v` at the end of `_CoqProject` makes no difference.  Time to look more closely at the code.

**Comment by jfehrle** [comment]
If you specify `-f` on the command line, it's applied unconditionally.  Maybe not ideal.
Otherwise, when you open an existing file, CoqIDE searches for the associated `_CoqProject` file, so opening `ToFancyWithCasts.v` in the buffer uses `_build_ci/fiat_crypto/_CoqProject` rather than the one I wanted.

If I open `bracket.v` then CoqIDE uses `_CoqProject` (both in `/home/proj/coq`).

**Comment by silene** [comment]
> the options are only used if the buffer is a .v file listed in the project. I believe this is not desirable, but may explain what you see.

Fortunately, that is not true. All of my projects use a single-line `_CoqProject` file (i.e., just `-R`) and Coqide works just fine. In fact, I have encountered the opposite issue with the `check-more` files of Flocq, for which I would prefer that Coqide ignores the broken logical path contained in `_CoqProject`. (But one can't have everything and I prefer the current behavior.)

> so opening `ToFancyWithCasts.v` in the buffer uses `_build_ci/fiat_crypto/_CoqProject` rather than the one I wanted.

I don't understand. Are you trying to open `_build_ci/fiat_crypto/src/Rewriter/Passes/ToFancyWithCasts.v` with Coqide? You should not.

**Comment by gares** [comment]
> Fortunately, that is not true.

I must then confuse CoqIDE with some other UI (I'm pretty sure I've seen this behavior).

**Comment by jfehrle** [comment]
> I don't understand. Are you trying to open `_build_ci/fiat_crypto/src/Rewriter/Passes/ToFancyWithCasts.v` with Coqide? You should not.

Exactly.  I run it as a test case for the debugger.  I'm not altering the code beyond inserting the line `Set Ltac Debug.`  Just viewing the file is also a normal thing to do, for which the _CoqProject settings are not important.  Anything else on "You should not"?

**Comment by jfehrle** [comment]
Digressing somewhat:

- It seems tedious to have to list every source file explicitly in the `_CoqProject` file.  If you add a new file, you have to remember to update `_CoqProject`.  Seems to me an obvious and useful enhancement would be to support wildcarding for path names, in particular supporting recursive wildcards, e.g. expanding `*.v` to `*.v`, `*/*.v`, `*/*/*.v`, etc.

- `_CoqProject` and the `COQPATH` environment variable don't do the same thing.  The first gets the first component of the logical name from the file while the second only uses the pathname below `COQPATH`.  For example (Print LoadPath output):

```
(* _CoqProject with "-R src Crypto" *)
Crypto.Curves /home/proj/coq/_build_ci/fiat_crypto/src/Curves

(* export COQPATH=_build_ci/fiat_crypto/src *)
Curves /home/proj/coq/_build_ci/fiat_crypto/src/Curves
```

If you have both of these for the same module, you get a flood of warnings in the log like this:
```
Warning: /home/proj/coq/_build_ci/fiat_crypto/src/Curves was previously bound
to Curves; it is remapped to Crypto.Curves
[overriding-logical-loadpath,loadpath]
```

Perhaps `COQPATH` should just go away?

**Comment by silene** [comment]
>  Anything else on "You should not"?

No, I don't have anything more to say. You are opening `_build_ci/fiat_crypto/src/Rewriter/Passes/ToFancyWithCasts.v`, so Coqide is parsing the options from `_build_ci/fiat_crypto/_CoqProject`. This is the expected behavior and there is no bug. I suppose the documentation could be made a bit clearer by mentioning that the project file is looked up in the closest ancestor directory, and thus modifying some other project file will not have much effect.

**Comment by jfehrle** [comment]
Just "a bit clearer"?  The documentation of configuration needs a lot of work.
