### ISSUE TITLE
How should the user configure their -R -Q and -I options for Coq Platform?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15750]
I installed the opam packages `coq-bignums` and `coq-coqprime`.  When I search in `~/.opam`, I find directories for those two names in two directories, `.opam/repo/coq-released/packages` and `.opam/repo/coq-extra-dev/packages`.  Both those directories also appear to contain (combined) about 600 packages such as `coq-vst` (and `coq-vst-32` and `coq-vst-64`) that don't appear in `opam list`.  I'm guessing that these were created when I installed Coq Platform.

- How are these directories different from what's shown in `opam list`?
- For configuring -R -Q and -I options to include these packages, how are users supposed to know the correct settings?  Of course, the doc should say something about what pathname to use.

IMHO we could make this easier for users as follows:
- There should be standard logical names assigned to each package in opam (overridable with in _CoqProject or on the command line)
- It should be sufficient to give the directory or the standard logical name in order to include a package in the load path.  (If -R -Q or -I is really needed, that info should come from _within_ each package, not from the user.  But even better than that, why shouldn't we automatically include all the logical names for the Coq opam packages in the loadpath automatically to make it really simple for users?  The logical name to opam package mapping would have to be published.  A list in a file would provide most of the value, but it could also be something more dynamic within the IDE (extracting the info from the list of packages).
- The mechanism should also work for packages that aren't in OPAM, in particular with a directory containing many packages.

@MSoegtropIMC and others, WDYT?

**Comment by MSoegtropIMC** [comment]
@jfehrle : the folders like .opam/repo/coq-released/packages contain only package definitions - a local copy of the package repo. `opam list` typically only lists installed packages. So what `opam list` shows is a subset of what is in the combination of these folders.

In general you shouldn't need any -Q -R or -I options for installed opam packages.

Coq Platform installs stuff via opam in a very normal way and whatever you install via Coq Platform follows the same rules as a normal opam install.

**Comment by jfehrle** [comment]
Ah, I didn't understand that the packages were being copied into `lib\coq\user-contrib` in the `coq` package.  I thought they remained separate in opam.

How are users supposed to know that the module name for `coq-bignums` is `Bignums` while `coq-tlc` is `TLC` and `coq-cmfl-basis` is `CMFL` (see excerpts below)?  At the least, we should describe how to determine this in the doc.  It would be nice if the IDE or a command showed the associated opam package name for installed packages.  Do you know if there a reasonable way to get this info from opam (maybe just as a text file)?  Or more dynamically?  It could be helpful to have an option on `Print LoadPath` that would only list the logical names (e.g. `Coq` but not all the 50+ modpaths under it).

> In general you shouldn't need any -Q -R or -I options for installed opam packages.

I'm curious whether `Rewriter` (as in #15749) could be made into an opam package since it needs a `-I` parameter.  A point to consider later.

`Print LoadPath` excerpt:
```
Logical Path / Physical path:
<> C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\share\coq
<> C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib
Bignums C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums
Bignums.BigN C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\BigN
Bignums.BigQ C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\BigQ
Bignums.BigZ C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\BigZ
Bignums.CyclicDouble C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\CyclicDouble
Bignums.plugin C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\plugin
Bignums.SpecViaQ C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\SpecViaQ
Bignums.SpecViaZ C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\SpecViaZ
CFML C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\CFML
TLC C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\TLC
```

```
$ opam list
# Packages matching: installed
# Name                    # Installed     # Synopsis
coq                       8.15.0          Formal proof management system
coq-bignums               8.15.0          Bignums, the Coq library of arbitrary large numbers
coq-cfml-basis            20220112        The CFML Basis library
coq-coqprime              1.1.1           Certifying prime numbers in Coq
coq-tlc                   20211215        TLC: A Library for Classical Coq
```

**Comment by MSoegtropIMC** [comment]
@jfehrle : there are a few methods:

- have a look at the user-contrib folder (it is easy to find via `coqc -where`) - it is usually not so crowded that one can't find things in there
- do e.g. `opam show coq-tlc` - the `logpath` tag is the Coq log path - most Coq packages have this, but this is just a convention, nothing technically enforced (afaik). This also works for not installed packages.
- the safest method is to call `opam show --list-files coq-tlc | head -n1

**Comment by MSoegtropIMC** [comment]
Regarding the `Rewriter package`: if it needs a -I option it should be fixed such that it doesn't. There are default paths where coq looks for files and things should be placed in these paths.

**Comment by jfehrle** [comment]
The `-I` option is fine for packages, for example Bignums has one, and I see there is a `lib/coq/user-contrib/Bignums/plugin` directory in the installed platform.  The issue is that  `Rewriter` (if it was to be made into an installable package) should use the standard pathname `Rewriter/plugin`?  Or something more/else?

**Comment by silene** [comment]
> The issue is that `Rewriter` (if it was to be made into an installable package) should use the standard pathname `Rewriter/plugin`? Or something more/else?

There is no standard path name. As long as the file is somewhere inside `user-contrib`, Coq will find it.

> If they put their new code directory into the platform installation, an `opam remove coq` would make them very unhappy. And perhaps just switching to a newer version of Coq would remove the directory.

First, `opam remove coq` only removes files that were installed by `opam install coq`, so those user files would not be removed. Second, even if they were removed, it would not be such a big loss. Indeed, `.vo` file are intimately related to a given version of Coq and trying to reuse them with a different version of Coq is a recipe for disaster.

Anyway, there are three places where Coq looks for installed files: `user-contrib`, `$COQPATH`, and `$XDG_DATA_HOME/coq` (and related directories such as `$XDG_DATA_DIRS` and `.local/share/coq`). So, if `user-contrib` is not suitable for a given Coq library, the user can always install it in one of the other two places. The issue with those is that the relation between `.vo` files and the version of Coq is lost, so it is a bit tedious when juggling between several Coq versions.

**Comment by jfehrle** [comment]
> Second, even if they were removed, it would not be such a big loss.

It would be if that's the only copy (e.g. that is also the git repository for the nifty new project).

**Comment by Zimmi48** [comment]
>It would be if that's the only copy (e.g. that is also the git repository for the nifty new project).

Creating a git repository under the opam root would be a terrible idea anyway.

**Comment by jfehrle** [comment]
What do the "<>" entries mean in `Print LoadPath`?  What are they good for?

```
Logical Path / Physical path:
<> C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\share\coq
<> C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib
<> C:\cygwin64_coq_platform\home\jfehr   (* current directory *)
```

If it's possible to load a .vo from the current directory, how would you do it?  `Import test_coqproject` didn't find `test_coqproject.vo` in the current directory.

**Comment by silene** [comment]
> What do the "<>" entries mean in `Print LoadPath`? What are they good for?

They are empty logical paths (also known as root logical paths). That way, the physical path `user-contrib/Foo` gets associated to the logical path `Foo`, rather than `Bar.Foo`.

> `Import test_coqproject` didn't find `test_coqproject.vo` in the current directory.

The `Import` and `Export` commands only deal with module visibility. They are completely unrelated to the file system. If you want to load a file, you need to use the `Require` command.

**Comment by jfehrle** [comment]
I guess the "<>" entries are used when `user-contrib` and `share/com` are first loaded and are ignored thereafter?

OK, `Require test_coqproject.` works to read from the current directory.  Is there a way to load file from a subdirectory of the current directory, e.g. `Foo/test_coqproject.*`?  I just tried that and it didn't work.

**Comment by silene** [comment]
> I guess the "<>" entries are used when `user-contrib` and `share/com` are first loaded and are ignored thereafter?

I don't understand this question. Directories are never loaded nor ignored. As I said, "<>" is just a way to display the empty string. Having these two characters is better than not showing anything. Coq could also have used two double quotes or a single point or a forward slash or whatever.

> I just tried that and it didn't work.

The current directory is not traversed recursively and that is on purpose. Since users are likely to run Coq from a random directory (e.g., from their home directory, I certainly do), this prevents Coq from trashing the whole file system. If you want to properly register the current directory as a physical path, you need to use `-R` or `-Q`, either on the command line or in a `_CoqProject` file.

**Comment by jfehrle** [comment]
Maybe this is clearer: At startup time, Coq adds loadpath entries for everything under user-contrib, such as the Bignums.  Once that's done, the <> entry is not used--for example if you drop new files into the directory, the LoadPath isn't updated.  Is that correct?

```
<> C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib
Bignums C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums
Bignums.BigN C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\BigN
Bignums.BigQ C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\BigQ
Bignums.BigZ C:\cygwin64_coq_platform\home\jfehr\.opam\__coq-platform.2022.01.0~8.15~preview1\lib\coq\user-contrib\Bignums\BigZ
```

**Comment by silene** [comment]
No, it is still used. I just tried it by first starting Coqtop, then dropping a `.vo` file into `user-contrib`, and finally `Require`-ing it, and it worked just fine. There is nothing special about empty logical paths, they are handled like non-empty ones.

Note that there is some caching mechanism to prevent Coq from traversing the file system every time the user types `Require`. So, Coq might not instantly notice new files or directories.

**Comment by silene** [comment]
Actually, I was wrong. For directories, the traversal is performed once and for all at startup time. If a library is installed or removed afterward, it will go unnoticed. For individual files, however, discovery is always performed on-the-fly (except for `coqc` which assumes that the filesystem does not change concurrently).
