### ISSUE TITLE
Anomaly found by following Chapter Basics: Functional Programming

### ISSUE THREAD

**Issue by castilma** [coq/coq#15785]
#### Description of the problem
I'm reading the first chapter, and after test_odd1 and 2, I get an anomaly
```
Module NatPlayground.
Inductive nat : Type :=
  | O
  | S (n : nat).

Fixpoint even (n:nat) : bool :=
  match n with
  | O => true
  | S O => false
  | S (S n') => even n'
  end.

Definition odd (n:nat) : bool :=
  (negb (even n)).

Example test_odd1: odd 1 = true.
Proof. simpl. reflexivity. Qed.

Example test_odd2: odd 4 = false.
Proof. simpl. reflexivity. Qed.


End NatPlayground.

```
After clicking 'Run to end' in coqide, I get 
```
Anomaly
"File "vernac/vernacextend.ml", line 77, characters 66-72: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
The term "4" has type "nat"
while it is expected to have type "NatPlayground.nat".
The term "4" has type "nat"
while it is expected to have type "NatPlayground.nat".
```

If you press Run to end again, it changes to:
```
There is nothing to end.
The term "4" has type "nat"
while it is expected to have type "NatPlayground.nat".
The term "4" has type "nat"
while it is expected to have type "NatPlayground.nat".
```

It seems, you cannot add Examples inside Modules?
Even though the book says: 

> We put this section in a module so that our own definition of natural numbers does not interfere with the one from the standard library. In the rest of the book, we'll want to use the standard library's.
Module [NatPlayground](https://softwarefoundations.cis.upenn.edu/lf-current/Basics.html#NatPlayground).

This sounds like it the following codes snippets should all be put inside a Module, and the decimal to NatPlayground.nat should work automatically, which it doesn't.

#### Coq Version
The Coq Proof Assistant, version 8.15.0
compiled with OCaml 4.13.1

**Comment by Alizter** [comment]
The anomaly is known and has to do with stepping through the entire erroneous proof in async mode. https://github.com/coq/coq/issues/14981

If you step through line by line you will see that there is an error in your code. The issue is that you have defined nat yourself, but have written numerals, which coq interprets as the old nat.

**Comment by SkySkimmer** [comment]
Duplicate https://github.com/coq/coq/issues/14981

**Comment by Alizter** [comment]
If you really want to use number notations for your nat however you could do something like this:
```coq
Module NatPlayground.
Inductive nat : Type :=
  | O
  | S (n : nat).

Fixpoint even (n:nat) : bool :=
  match n with
  | O => true
  | S O => false
  | S (S n') => even n'
  end.

Definition odd (n:nat) : bool :=
  (negb (even n)).

Fixpoint of_nat (n : Datatypes.nat) : nat :=
  match n with
  | Datatypes.O => O
  | Datatypes.S n => S (of_nat n)
  end.

Fixpoint to_nat (n : nat) : Datatypes.nat :=
  match n with
  | O => Datatypes.O
  | S n => Datatypes.S (to_nat n)
  end.

Definition to_int := fun x => Nat.to_num_int (to_nat x).
Definition of_int := fun x => option_map of_nat (Nat.of_num_int x).

Declare Scope myscope.
Open Scope myscope.
Number Notation nat of_int to_int : myscope.

Example test_odd1: odd 1 = true.
Proof. simpl. reflexivity. Qed.

Example test_odd2: odd 4 = false.
Proof. simpl. reflexivity. Qed.


End NatPlayground.

```

This simply converts your nat to the old nat and vice versa. Then we compose them with conversion functions for the old nat to something called Number.int. Then when we use the Number Notation command, Coq knows how to parse and print numbers. To do this we had to open a notation scope called myscope.

More information on number notation here: https://coq.inria.fr/refman/user-extensions/syntax-extensions.html#number-notations
