### ISSUE TITLE
CoqIDE shows substantial slow down (about 30x for large files) in 8.15

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#15786]
A measurement of the "Run to end" time for the Flocq file [Pff.v](https://gitlab.inria.fr/flocq/flocq/-/raw/master/src/Pff/Pff.v) in CoqIDE for various versions of Coq gave these results:
```
8.12: 3'40"
8.13: 2'40"
8.14: 2'00"
8.15: between 55' and 85' (it finished while I was at lunch)
```
All times are manually measured and approximately (+0s/-10s). All versions use the same OCaml 4.10.2 (I used Coq Platform 2022.01 to install the 4 versions).

As discussed here [Zulip](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Splitting.20CoqIDE.20-.20speed.20regression) the slow down might be quadratic with the length of the file, so that with "normal" files it is not that bad, but it is quite noticeable also with normal length files. The parsing part of a file with 100 definitions and lemmas takes 10..20s.

**Comment by MSoegtropIMC** [comment]
@jfehrle : FYI - it is likely an effect of the Ltac Debugger - see the Zulip discussion.

**Comment by ppedrot** [comment]
I am reopening this because even if #15787 removed the bulk of the issue, there is still a quadratic behaviour with the reverse translation `byte_off_to_buffer_off` which freezes my CoqIDE on big files.

**Comment by ppedrot** [comment]
OK, so it seems that #15467 not only introduced this quadratic behaviour, but it also screwed up the tooltip placement.

**Comment by ppedrot** [comment]
I'll try to fix this today so that the patch can go in 8.15.1.

**Comment by SkySkimmer** [comment]
postponed

**Comment by jfehrle** [comment]
#15996 fixed the secondary issue related to `byte_off_to_buffer_off`.  Pff.v runs in less than 2 minutes now.  Let me know if I've missed something.
