### ISSUE TITLE
Regression of lia in presence of primitive projections

### ISSUE THREAD

**Issue by rlepigre** [coq/coq#15791]
#### Description of the problem

The `lia` tactics fails to prove a goal that should be trivial in the following code. Generalizing the (inert and equal on both sides) sub-term that contains a primitive projection makes the goal solvable.
```coq
Require Import Coq.micromega.Lia.

Set Primitive Projections.

Definition R := nat.
Record S : Set := { regs : R -> nat }.

Record D := { state : Set }.
Definition Z : D := {| state := S |}.
Arguments state d.

Goal forall (n : nat) (r : R) (s : @state Z), regs s r <= regs s r + n.
Proof.
  intros.
  Fail lia. (* Succeeds if we remove [Set Primitive Projections]. *)
  generalize (regs s).
  lia.
Qed.
```

Note that this could be related to https://github.com/coq/coq/issues/9892, but that's not completely clear to me.

#### Coq Version

- 8.15.0 (+ a few patches from master)
- 8.14.1 (using jscoq) already has the problem.
- 8.13.2 __does not__ have the problem.

**Comment by Alizter** [comment]
cc @coq/micromega-maintainers

**Comment by fajb** [comment]
Hello, 
This is not  #9892. Here, this is `zify` which has problems with primitive projections.
It should inject the goal towards Z but does nothing...

**Comment by Janno** [comment]
First bad commit:

```
commit 122d6dd2b5a7df8f02851cd1de8bf770091cf10d
Author: BESSON Frederic <frederic.besson@inria.fr>
Date:   Fri Mar 5 11:58:20 2021 +0100

    [zify] Index by GlobRef instead constr
    
    Co-authored-by: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>

 plugins/micromega/zify.ml | 89 ++++++++++++++++++++++++++++-------------------
 1 file changed, 53 insertions(+), 36 deletions(-)
```
