### ISSUE TITLE
Anomaly with `-noinit` and `Compute`

### ISSUE THREAD

**Issue by Alizter** [coq/coq#15811]
Compute throws an anomaly when run with `-noinit`. 
```coq
Compute _.
```

```
Anomaly "File "lib/hook.ml", line 21, characters 11-17: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

**Comment by Alizter** [comment]
It seems then the fix will have to be part of a larger refactoring effort. cc @ppedrot have you got any plans in mind? I had a look through the code for red_expr and it seems those expressions are very tightly wound to ltac interpretation.

**Comment by ejgallego** [comment]
We tried a couple of times in the past @Alizter , it is doable, but cumbersome.
