### ISSUE TITLE
Strange bug where `auto` "finishes" the proof, after which `Qed` fails to typecheck the proof object.

### ISSUE THREAD

**Issue by jihgfee** [coq/coq#15814]
#### Description of the problem

I encountered a weird bug related to `auto`, where it produces a complete proof ("No more subgoals."),
while `Qed` fails to type check the proof object.
The following code captures the bug.
```coq
Inductive X := x.

Parameter X1 : X -> X.
Parameter X2 : X -> X.

Axiom Xeq : forall x, X1 x = X2 x.

Ltac Xtac :=
  match goal with
  | [ H : context[X1 _] |- _  ] => rewrite Xeq in H
  | [ |- context[X1 _] ] => rewrite Xeq
  end.

(* Qed succeeds before adding the hint and using [auto]. *)
Lemma succeeds x y :
  (True -> X1 x = y) -> X1 x = y /\ True.
Proof. auto. Qed.

Local Hint Extern 1 => Xtac : core.

(* Qed fails when using [auto]. *)
Lemma fails x y :
  (True -> X1 x = y) -> X1 x = y /\ True.
Proof. auto. Fail Qed. Admitted.

(* Qed succeeds when using [eauto] *)
Lemma succeeds1 x y :
  (True -> X1 x = y) -> X1 x = y /\ True.
Proof. eauto. Qed.

(* Qed succeeds when removing the conjunction and using [auto] *)
Lemma succeeds2 x y :
  (True -> X1 x = y) -> X1 x = y.
Proof. auto. Qed.

(* Qed succeeds when removing the implication and using [auto] *)
Lemma succeeds3 x y :
  X1 x = y -> X1 x = y /\ True.
Proof. auto. Qed.
```
The problem arises from the automatic "unification" of `X1 x` and `X2 x` using `Xeq`, which fires as a part of `auto`.
This is illustrated by Qed succeeding before adding the hint, but fails after.
For some reason, `eauto` works, as illustrated by `succeeds1`. Additionally, `auto` also works when removing either the trivial implication or the trivial conjunction, as also illustrated by `succeeds2` and `succeeds3`, respectively.

The error messages from the `Qed` that fails is:
```
The command has indeed failed with message:
Illegal application: 
The term "conj" of type "forall A B : Prop, A -> B -> A /\ B"
cannot be applied to the terms
 "X1 x = y" : "Prop"
 "True" : "Prop"
 "H0 I" : "X2 x = y"
 "I" : "True"
The 3rd term has type "X2 x = y" which should be coercible to 
"X1 x = y".
```

#### Coq Version

The Coq Proof Assistant, version 8.15.0
compiled with OCaml 4.12.0

**Comment by Alizter** [comment]
Seems to be a bug with the implementation of auto. For the record, eauto succeeds.

**Comment by SkySkimmer** [comment]
Simplified example 
~~~coq
Parameter X1 : nat.
Parameter X2 : nat.

Axiom Xeq : X1 = X2.

Ltac Xtac :=
  match goal with
  | [ H : context[X1] |- _  ] => rewrite Xeq in H
  end.

Local Hint Extern 1 => Xtac : core.

(* Qed fails when using [auto]. *)
Lemma fails y :
  (True -> X1 = y) -> X1 = y /\ True.
Proof.
  auto.
Qed.
~~~

**Comment by mrhaandi** [comment]
`auto` assumes that tactics cannot modify local hypotheses. The following example produces an `Anomaly "variable H unbound."`
```coq
Parameter P Q R : Prop.
Axiom (HQR : Q -> R).
Axiom (HP : P).

Ltac Xtac := match goal with [H : _ |- _] => clear H end.

Create HintDb db.
#[local] Hint Resolve HQR : db.
#[local] Hint Resolve HP : db.
#[local] Hint Extern 0 => Xtac : db.

Goal (P -> Q) -> R.
Proof.
  auto with db nocore.
Qed.
```
A potential fix is to reinitialize `local_db` if a hint touches the local hypotheses: https://github.com/coq/coq/pull/16302.

**Comment by mrhaandi** [comment]
The underlying reason for this bug is the same as in https://github.com/coq/coq/issues/6332.
