### ISSUE TITLE
coqide.dev runs hardly a few seconds on macOS

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#15857]
I just tried a dev build of today evening (d47ba657bb4ec33f44402142161610955194ae61) on macOS. I must say I can hardly manage to keep it alive for more than a few seconds.

I get crashes in

- file open dialog
- when doing the first step into code after opening a file

I tried about 10 times with different files and I don't think it did run for more than 5 seconds in any try.

I don't know if this is MacOS specific.

I have no such issues with 8.15.1!

**Comment by ppedrot** [comment]
Is it using the same lablgtk version? I don't see what would have changed in 8.15.1 that wouldn't be there as well in master. Most of the changes have been backported.

**Comment by MSoegtropIMC** [comment]
Indeed I have `coqide.8.15.1 lablgtk3.3.1.2` vs `coqide.dev lablgtk3.3.1.1` - let me fix this and retry.

**Comment by MSoegtropIMC** [comment]
Sorry, my bad. Indeed the lablgtk version makes a difference on macOS.

Was it known that lablgtk3.3.1.1 does not work on macOS?

**Comment by ppedrot** [comment]
This looks very much like #15486 so it might be duplicate.

**Comment by MSoegtropIMC** [comment]
Two notes on that:

- the version mentioned there did indeed use labgltk3.3.1.1 - see (https://github.com/coq/platform/blob/5d6bc015370fe22f41bca431ddad79fcae388676/package_picks/package-pick-8.14%7E2022.01.sh#L55) (which is not exactly the same, but a later tag).

- I have been using CoqIDE of this tag extensively and never saw an issue on macOS BigSur. The the situation seems to be more complex.

**Comment by MSoegtropIMC** [comment]
One more note:

- all these reports (in Coq and Coq Platform) where about opening preferences. For me CoqIDE crashed without opening preferences.

It might also be that this is a random compilation effect (rare but not unheard of). I can try switching hence and forth lablgtk to force a recompile and see what happens.
