### ISSUE TITLE
It should not take 200 seconds to run `Admitted`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#15858]
#### Description of the problem
In https://github.com/mit-plv/fiat-crypto/pull/1173/files#diff-0a7841db22fe2f52e8b832d49d801d1fb5fd44ef4e95ced2e867375da8599dffR3162 at line 3162 of src/Assembly/WithBedrock/Proofs.v, there's an `Admitted` that took over 200 seconds to run on Coq 8.14.0.  What is Coq doing?

(I'll update this with a permalink once the relevant PR in fiat-crypto is merged)
EDIT by skyskimmer: no need to wait https://github.com/mit-plv/fiat-crypto/blob/d35a2a87386be80a9b4095a61766d8524e35f3ab/src/Assembly/WithBedrock/Proofs.v#L3162

cc @ppedrot ?

#### Coq Version

8.14.0

**Comment by SkySkimmer** [comment]
Is it the same timing if you do Admitted immediately after Proof?

**Comment by JasonGross** [comment]
I will check, but I believe Admitted right after Proof is instantaneous

**Comment by JasonGross** [comment]
If I do `Admitted` immedaitely after `Proof`, it takes 0.005s.

**Comment by SkySkimmer** [comment]
What if you do `Unset Keep Admitted Variables.` before the admitted?

**Comment by JasonGross** [comment]
> What if you do `Unset Keep Admitted Variables.` before the admitted?

Do I have to do it before the beginning of the proof?  If I stick it right before `Admitted`, the `Admitted` is still slow (228.732 s, this time, the extra 28s probably due to variable workload of my machine?)
