### ISSUE TITLE
doc_gram_rsts wants to make changes

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#15850]
Running `make -f Makefile.dune doc_gram_rsts` produces this patch:
~~~diff
modified   doc/sphinx/proof-engine/vernacular-commands.rst
@@ -736,7 +736,7 @@ Extra Dependencies
 Dependencies on external files, i.e. non ``.v`` files, can be declared as
 follows:
 
-.. cmd:: From @dirpath Extra Dependency @string {? as @ident }
+.. cmd:: From @qualid Extra Dependency @string {? as @ident }
    :name: From … Dependency
 
    Adds an additional dependency of the current `.v`  file on an external file.  This
modified   doc/sphinx/user-extensions/syntax-extensions.rst
@@ -462,7 +462,7 @@ Displaying information about notations
 
    :flag:`Printing All` to disable other elements in addition to notations.
 
-.. cmd:: Print Notation @string {? in custom @ident }
+.. cmd:: Print Notation @string in custom @ident
 
    Displays information about the previously reserved notation string
    :token:`string`. :token:`ident`, if specified, is the name of the associated
~~~

**Comment by Zimmi48** [comment]
The first one dates from: b3c0fc985b20f47ec0461363b803a3b072b06a1e (#15650).
The second one dates from: bb7ec076b07a94f806a432a7c968428b4e0fabb3.

The first one is a good example: the ordered grammar says one thing and the refman says something different. So the problem is that the linter is broken because it should have failed on these PRs.

**Comment by Zimmi48** [comment]
FTR, the issue with the second one is that the ordered grammar contains:

```
| "Print" "Notation" string
| "Print" "Notation" string "in" "custom" ident
```

when it should contain:

```
| "Print" "Notation" @string OPT ( "in" "custom" ident )
```

In both PRs, this means that `common.edit_mlg` should have been edited to reflect what developers wanted to appear in the refman (but it wasn't).

**Comment by Zimmi48** [comment]
It indeed seems like the `doc_gram_verify` of `Makefile.dune` and `Makefile.make` is broken (gives 0 exit code when it shouldn't), but I have no idea for how long it has been the case.

**Comment by Zimmi48** [comment]
#15876 has fixed the issue but the problem with the broken `doc_gram_verify` target remains.

**Comment by jfehrle** [comment]
With the 2 print statements:

```
$ make -f Makefile.dune doc_gram
dune build  _build/default/doc/tools/docgram/doc_grammar.exe
      ocamlc doc/tools/docgram/.doc_grammar.eobjs/byte/dune__exe__Doc_grammar.{cmi,cmo,cmt}
    ocamlopt doc/tools/docgram/.doc_grammar.eobjs/native/dune__exe__Doc_grammar.{cmx,o}
    ocamlopt doc/tools/docgram/doc_grammar.exe
DOC_GRAM
rsts =
mlgs = parsing/g_constr.mlg
  parsing/g_prim.mlg
  toplevel/g_toplevel.mlg
  :
$ make -f Makefile.dune doc_gram_verify
dune build  _build/default/doc/tools/docgram/doc_grammar.exe
DOC_GRAM_VERIFY
rsts = doc/sphinx/language/gallina-specification-language.rst
  doc/sphinx/language/coq-library.rst
  doc/sphinx/language/module-system.rst
  : 
mlgs = parsing/g_constr.mlg
  parsing/g_prim.mlg
  toplevel/g_toplevel.mlg
  :
```

**Comment by Zimmi48** [comment]
Note that the issue here is with the `doc_gram_verify` target. Isn't it expected that `doc_gram` doesn't update the rst files? Isn't this the role of `doc_gram_rsts` (as documented)?

**Comment by jfehrle** [comment]
You're right, the details evaporate so quickly :-(.  Let me take another look.
