### ISSUE TITLE
CoqIDE highlighting doesn't reset properly on edit

### ISSUE THREAD

**Issue by Alizter** [coq/coq#15861]
Here is a highlighting issue observed on master:
![highlightingbug_28_03_2022](https://user-images.githubusercontent.com/8614547/160416256-39954e77-239d-4c45-aab4-c1f772dfc379.gif)

I would have expected the highlighting to backtrack to the sentence before.

cc @jfehrle @ppedrot 

---
Steps to reproduce:

1. Create two sentences:
```
Check nat.
Check nat.
```
2. step to end of document.
3. Delete period in second sentence.

**Comment by Alizter** [comment]
Here is the behaviour from 8.14.1 which I would consider expected.

![highlightingbug_28_03_2022_follow_up](https://user-images.githubusercontent.com/8614547/160462175-916a7b39-576a-43c6-a5a4-19ca1f205967.gif)

**Comment by Alizter** [comment]
With the first issue, I can no longer step down through the proof since the highlighting is "floating". Adding the period back in and trying to step down does nothing.

**Comment by Alizter** [comment]
The fact that I cannot continue to step down shows that the current behaviour is broken.
8.14:
![Peek 2022-03-28 19-26_before](https://user-images.githubusercontent.com/8614547/160462877-53c765cf-7c7c-4e0c-be68-1b4d5b2671d8.gif)

master:
![Peek 2022-03-28 19-25](https://user-images.githubusercontent.com/8614547/160462807-7467238a-c58e-42f0-89df-4e25e07fe34a.gif)

**Comment by jfehrle** [comment]
I meant describing it in words, only, so that one doesn't have to experiment to understand exactly what the incorrect behavior is.  I don't find the looping images all that helpful--they go at their own pace, a bit fast, and the point of the error is not clearly identified.  Comparing 2 looping images is not at all, I think, an easy mental operation.  Much more helpful to state the steps and show a still image or two.  Even after staring at it for a while, I can't concisely describe the bug.  "doesn't reset properly" is rather vague.

**Comment by Alizter** [comment]
@jfehrle  OK sorry for not being clear enough. Hopefully this is clearer:

When in the middle of a document, the highlighting goes to the last sentence terminator. This green highlighting indicates that Coq has checked this part of the document. When we edit a line that is highlighted, the expected behaviour is that the highlighting will reset the the line before.

Take the following document as an example:
```coq
Check nat.
Check nat.
Check nat.
```
It contains three sentences for Coq to step through. We will use this to demonstrate the problematic behaviour.

In 8.14, you can step down to the second line. The green highlighting will be for the first two lines. If you edit the second line, in this case remove the period, the highlighting will reset to only highlight the first line. This is to indicate that Coq has stepped back and undone the line. Now it should be possible to fix the line just edited, in our case adding the period again, and step through. Now the second line is again highlighted. In fact, we can continue down the document further allowing us to also eventually highlight the third line.

In current master the behaviour is different. If you highlight the first two lines by stepping down, and then edit the period on the second line, coq will not reset the highlighting to the first line, but simply remove the highlighting from where the period used to be. The rest of the second line is still highlighted however. Furthermore, adding the period back will result in a unhighlighted period (which is expected), but you will no longer be able to step down. In order to overcome this, you have to step up and then down again, allowing the sentence to be processed, and the document thereafter.

The second behaviour is not what the user expects and is not correct.

**Comment by jfehrle** [comment]
@ppedrot The bug first appears in f89a3298487f44181bbb6cbeed13fb599a04ffc6, "Clean up the interaction logic of the CoqIDE buffer manipulation."

The (initial?) problem is that deleting the period highlights the code incorrectly:

![image](https://user-images.githubusercontent.com/1253341/160710393-856634d6-74e8-412d-93e8-70fe3c4c24c2.png)

It looks like `mark_as_needed` marks "Check nat" as a sentence when it should not.  Maybe the sentence bounds should be updated first?

```
got key ' (65288, MOD2)
[DEBUG] begin_action_cb
[DEBUG] prev_insert moved
[DEBUG] delete_cb 20 21
[DEBUG] prev_insert moved
[DEBUG] end_action_cb
call_coq_or_cancel_action
[DEBUG] target deleted
[DEBUG] target moved

[DEBUG] Begin command processing
[DEBUG] Start eval_call SetOptions [(["Diffs"],on);(["Printing";"Coercions"],false);(["Printing";"Matching"],true);(["Printing";"Notations"],true);(["Printing";"Existential";"Instances"],false);(["Printing";"Unfocused"],false);(["Printing";"Goal";"Names"],false);(["Printing";"Parentheses"],false);(["Printing";"Implicit"],false);(["Printing";"All"],false);(["Printing";"Universes"],false)]
[DEBUG] End eval_call
[DEBUG] Handling coqtop answer
[DEBUG] Start eval_call Goal
[DEBUG] End eval_call
[DEBUG] Feedback Processed  on 3
[DEBUG] Marking  [ -4,  0](   10,   20) Check nat []
[DEBUG] Handling coqtop answer
[DEBUG] Start eval_call SetOptions [(["Diffs"],on);(["Printing";"Coercions"],false);(["Printing";"Matching"],true);(["Printing";"Notations"],true);(["Printing";"Existential";"Instances"],false);(["Printing";"Unfocused"],false);(["Printing";"Goal";"Names"],false);(["Printing";"Parentheses"],false);(["Printing";"Implicit"],false);(["Printing";"All"],false);(["Printing";"Universes"],false)]
[DEBUG] End eval_call
[DEBUG] Handling coqtop answer
[DEBUG] Start eval_call Evars
[DEBUG] End eval_call
[DEBUG] Feedback Processed  on 3
[DEBUG] Marking  [ -4,  0](   10,   20) Check nat []
[DEBUG] Handling coqtop answer
[DEBUG] Autosave time: 1648589119.
[DEBUG] Locale is UTF-8
```

**Comment by Tuplanolla** [comment]
A similar issue plagues situations,
where changing an accepted sentence
of the form `idtac.` into `idtac...` confuses the parser.

**Comment by Tuplanolla** [comment]
I opened #15873 about the other case.

**Comment by Alizter** [comment]
More related bugs:

Write some axioms/definition in the buffer, for example
```coq
Axiom A : Type.
```
Step down so it is highlighted. Next select everything and paste the following (replacing the content of the buffer):
```
Check A.
```
Step down, and see that this succeeds! Even though Axiom A is no longer in the buffer at all. The proof state seems to think it is.

**Comment by jfehrle** [comment]
Thanks.  We don't yet know if there's a common root cause or not.  Pasting into the buffer is a different use case than the original issue of highlighting.  The title alone should be very clear and specific on what it covers.
