### ISSUE TITLE
Basic plugin tutorial not working

### ISSUE THREAD

**Issue by dwarfmaster** [coq/coq#15870]
#### Description of the problem

I'm trying to write a simple coq plugin to add a tactic implemented in ocaml. I tried to follow the tutorial, but while I can add vernacular commands, the tactics I create is not added, ie it isn't found by `Locate Ltac`, doesn't appear in `Print Grammar tactic` and when I try to use it I get the error `The reference ... was not found in the current environment`.

In order to find what I did wrong, I cloned coq and tried to run `make` in the `doc/plugin_tutorial/tuto0` directory, but `coq_makefile` failed with error `Unknown option src/META.coq-plugin-tutorial`.

#### Coq Version

```shell
$ coqtop -v
The Coq Proof Assistant, version 8.15.0
compiled with OCaml 4.12.0
```

I am on NixOS, and I installed Coq with Nix.

**Comment by SkySkimmer** [comment]
You need to use the plugin tutorial from the exact version of Coq you're using.
In your case you're using 8.15 but you cloned master.

**Comment by SkySkimmer** [comment]
>I'm trying to write a simple coq plugin to add a tactic implemented in ocaml. I tried to follow the tutorial, but while I can add vernacular commands, the tactics I create is not added, ie it isn't found by Locate Ltac, doesn't appear in Print Grammar tactic and when I try to use it I get the error The reference ... was not found in the current environment.

Possibly a wrong or missing DECLARE PLUGIN.
