### ISSUE TITLE
Error message shows wrong type

### ISSUE THREAD

**Issue by yannl35133** [coq/coq#15905]
#### Description of the problem
```coq
Toplevel input, characters 35-46:
> Definition test : { i | False } := exist _ I I.
>                                    ^^^^^^^^^^^
Error:
The term "exist (fun _ : True => False) I I" has type 
"{_ : True | False}" while it is expected to have type 
"{_ : True | False}" (cannot satisfy constraint
"True" == "(fun _ : True => False) I"; cannot unify 
"True" and "False").
```

I would expect that `exist (fun _ : True => False) I I` has type `{_ : True | True}` and not `{_ : True | False}` as the error message appears to say.

#### Coq Version
The Coq Proof Assistant, version 8.15.1
compiled with OCaml 4.14.0
(also present is 8.14)

**Comment by SkySkimmer** [comment]
This is a problem with delayed constraints, it prints the problem constraint so I don't think we're going to improve on it.
