### ISSUE TITLE
Is the current directory when you start CoqIDE supposed to be part of the loadpath?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15902]
I see this code in `Coqloadpath.init_load_path` that suggests that .vo files in the current directory at startup time should be in the loadpath, but when I try it, I'm not able to load files from the current directory.  What is the expected behavior?  Should we support this, perhaps as an enhancement?

PS If this is supposed to be supported, there would also be the question of what effect, if any, the `Cd` command should have, or whether CoqIDE should have a way to change its current directory.

```
  let vo_loadpath =
    (* current directory (not recursively!) *)
    [ { unix_path = "."
      ; coq_path = Libnames.default_root_prefix
      ; implicit = false
      ; has_ml = true
      ; recursive = false
      } ] @
```

**Comment by jfehrle** [comment]
Ah, I was trying "Require Import test." instead of "Require Import Jimtest.test."  I was not expecting that at all.

```
Pwd.  (* /home/proj/installed-coq-platform/platform/Jimtest *)
Print LoadPath.  (* "Jimtest /home/proj/installed-coq-platform/platform/Jimtest *)
```

**Comment by Zimmi48** [comment]
If I recall correctly, this used to be the case or was the case at some point in the past but was disastrous for performance and also a source of many warnings when CoqIDE was started in, e.g., the home directory. So no, the current directory should not be added to the load path by default.

**Comment by Zimmi48** [comment]
See PR #6311, which closed #6153 and #5734.

**Comment by jfehrle** [comment]
It would be silly to recur through every subdirectory (users should have a _CoqProject), but .vo files only in the current directory should be workable if we wanted to support that.  However, one thing that baffles me is that the loadpath shows an entry "<> C:\Users\jfehr", which corresponds to the current directory but still nothing from there is loadable.  And that indeed appears to be a bug.

Also, I see this bizarre behavior (similar to other bizarre behavior I've reported a couple time, but that no one seems to think it a problem)  How does the current directory name "jimtest" become a buffer name??

```
/home/proj/coq2/jimtest$ dune exec -- ../dev/shim/coqide-prelude
Entering directory '/home/proj/coq2'
   configure config/Makefile,config/coq_config.{ml,py},config/dune.c_flags
```

![image](https://user-images.githubusercontent.com/1253341/161709991-ec2b5c82-d196-4be8-b1f3-f0cb20a662ee.png)

and shortly gets errors like this:

![image](https://user-images.githubusercontent.com/1253341/161710278-588fc2ea-5922-46a3-9c41-536e39413136.png)

**Comment by Zimmi48** [comment]
>but .vo files only in the current directory should be workable if we wanted to support that.

Yep, I don't know if we want to support this or not, but it would be definitely much more reasonable than what it used to do.

And indeed, the two things you mention are really weird bugs. On the other hand, I really don't know about this part of the code, so I cannot help with that.

**Comment by jfehrle** [comment]
Looks like loading from the current directory does work.  Not sure what I was doing wrong.

**Comment by Zimmi48** [comment]
Oh, so exactly as you were suggesting? Should we close this issue (and you can open new ones for the other bugs)?

**Comment by jfehrle** [comment]
At the moment, I don't see the strange behavior, either.  So closing.
