### ISSUE TITLE
Warning 58 [no-cmx-file]: no cmx file was found in path for module Zarith_version

### ISSUE THREAD

**Issue by Alizter** [coq/coq#15952]
When `dune build`ing coq after a `git clean -xffd` I always get this warning:
```
File "_none_", line 1:                      
Warning 58 [no-cmx-file]: no cmx file was found in path for module Zarith_version, and its interface was not compiled with -opaque
```

How do we fix this?

**Comment by SkySkimmer** [comment]
What zarith version?

**Comment by Alizter** [comment]
1.12

**Comment by SkySkimmer** [comment]
This seems to have come up before https://github.com/ocaml/num/issues/9

**Comment by Alizter** [comment]
Right so in https://github.com/coq/coq/commit/0d691b3ecb3073a88430a06ef9d026c53ba2692e we straight up ignore 58. Perhaps we should do this in dune-project too.

This obviously just ignores the problem, do we need to fix zarith for a real fix?

**Comment by ejgallego** [comment]
There is a dune bug about this, this is problem only in flambda, not a big deal tho.

**Comment by ejgallego** [comment]
I'm closing this as this can't be fixed in Coq, but should be forwarded to either dune, OCaml, or Zarith.
