### ISSUE TITLE
LaTeX documentation doesn't build with Sphinx 4.5.0

### ISSUE THREAD

**Issue by befeleme** [coq/coq#15956]
#### Description of the problem

When integrating Sphinx 4.5.0 to Fedora, we uncovered an issue with coq: the LaTeX documentation doesn't build correctly (as it did with previous Sphinx versions).
The investigation results were evaluated as likely regression in Sphinx and reported as https://github.com/sphinx-doc/sphinx/issues/10332. The issue in question contains the insights from the RPM build.

#### Coq Version

coq 8.15.1

**Comment by xgqt** [comment]
CC @xgqt
Today, trying to bump Coq to version 8.15.2 in Gentoo I had the same issue.
https://dpaste.com/7CER4L2KR

**Comment by SnarkBoojum** [comment]
Eh, trying to update coq-doc in Debian also brings [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012019) up.

I had no problem with the coq package since it doesn't contain the documentation for license reasons.

**Comment by mitya57** [comment]
This happens because coq was monkey-patching `visit_desc_signature` method of `sphinx.writers.latex.LaTeXTranslator`. I opened a PR to fix this: #16193.
