### ISSUE TITLE
`Search` fails after goals are solved 

### ISSUE THREAD

**Issue by whonore** [coq/coq#15972]
#### Description of the problem

The `Search` command fails with the message `[Focus] No such goal` if you try to use it after all goals are solved, but before `Qed`. The example below shows the positions where it succeeds and where it fails. This seems to be a regression introduced in 8.14 since in 8.13 there's no error message.

```coq
Search True. (* Ok *)
Goal True.
Proof.
  Search True. (* Ok *)
  exact I.
  Fail Search True. (* [Focus] No such goal. *)
Qed.
Search True. (* Ok *)

Goal True /\ True.
Proof.
  split.
  - exact I.
    Fail Search True. (* [Focus] No such goal *)
Abort.
```

This is trivial to work around, but it's a surprising error (at least to me) and I can't see a reason it shouldn't work in all of these positions. It's not a totally contrived issue since I did run into it in the wild when I tried to use a shortcut key to search for lemmas about the term under my cursor after completing a proof but before stepping forward to `Qed`. Based on [this test](https://github.com/coq/coq/blob/eb54217b0b30aeec542631e2b1e4b47dbdd32270/test-suite/output/Search.v#L23) it looks like this behavior is meant to keep `Search` from being used in non-existent goal contexts, which makes sense, but maybe it could just be relaxed to allow a bare `Search` with no goal identifier prefix to work even if the current goal is complete?

#### Coq Version

Error message confirmed in:
- 8.14.1
- 8.15.1
- [master](eb54217b0b30aeec542631e2b1e4b47dbdd32270)

Error message confirmed not in:
- 8.13.2

**Comment by SkySkimmer** [comment]
Probably due to https://github.com/coq/coq/commit/9374aeeda2a3bc64774753862eae39a8e8539bb7, the vernacentries part of the change is incorrect as `get_goal_or_global_context` can raise `NoSuchGoal`.
