### ISSUE TITLE
Archives have no index -- and then undefined references all around

### ISSUE THREAD

**Issue by SnarkBoojum** [coq/coq#16050]
I've been building the Debian package for coq using dune since months:
```
        dune build -p coq-core,coq-stdlib,coqide-server,coqide --display=verbose
        # we don't really have the full documentation
        dune build @stdlib-html --display=verbose
```

and everything has been looking ok, since I have based many other [coq-*](https://people.debian.org/~jpuydt/coq_platform.html) on it.

But now I'm trying to package coq-serapi, and things break left and right. Perhaps that's the first time I package something trying to link to the coq-core library...

First issue: building coq-serapi fails at the linking stage because many of the .a files in coq-core/ trigger the error "adding symbols: archive has no index; run ranlib to add one".

So I tried to run ranlib on them by hand on my system, thinking that was already something worth reporting upstream.

Hélas! Compiling coq-serapi now fails with a huge number of undefined references -- to the point I'm wondering if any symbol is found at all. Here is a very short selection of lines of the log:
```
/usr/bin/ld: serapi/serapi.a(serapi__Serapi_protocol.o): in function `camlSerapi__Serapi_protocol__info_of_ind_2932':
./_build/default/serapi/serapi_protocol.ml:511: undefined reference to `camlEnviron'
/usr/bin/ld: serapi/serapi.a(serapi__Serapi_protocol.o): in function `camlSerapi__Serapi_protocol__info_of_const_2937':
./_build/default/serapi/serapi_protocol.ml:514: undefined reference to `camlEnviron'
/usr/bin/ld: ./_build/default/serapi/serapi_protocol.ml:515: undefined reference to `camlEnviron'
/usr/bin/ld: ./_build/default/serapi/serapi_protocol.ml:519: undefined reference to `camlOption'
/usr/bin/ld: ./_build/default/serapi/serapi_protocol.ml:517: undefined reference to `camlGlobal'
/usr/bin/ld: ./_build/default/serapi/serapi_protocol.ml:518: undefined reference to `camlLibrary'
/usr/bin/ld: serapi/serapi.a(serapi__Serapi_protocol.o): in function `camlSerapi__Serapi_protocol__info_of_var_3017':
./_build/default/serapi/serapi_protocol.ml:521: undefined reference to `camlEnviron'
/usr/bin/ld: ./_build/default/serapi/serapi_protocol.ml:522: undefined reference to `camlContext'
/usr/bin/ld: ./_build/default/serapi/serapi_protocol.ml:524: undefined reference to `camlOption'
/usr/bin/ld: ./_build/default/serapi/serapi_protocol.ml:523: undefined reference to `camlContext'
/usr/bin/ld: serapi/serapi.a(serapi__Serapi_protocol.o): in function `camlSerapi__Serapi_protocol__info_of_constructor_3096':
./_build/default/serapi/serapi_protocol.ml:529: undefined reference to `camlTypeops'
/usr/bin/ld: serapi/serapi.a(serapi__Serapi_protocol.o): in function `camlSerapi__Serapi_protocol__info_of_id_3106':
./_build/default/serapi/serapi_protocol.ml:534: undefined reference to `camlLibnames'
/usr/bin/ld: ./_build/default/serapi/serapi_protocol.ml:536: undefined reference to `camlNametab'
```

Did I miss something obvious?

**Comment by SkySkimmer** [comment]
>and everything has been looking ok, since I have based many other coq-* on it.

>But now I'm trying to package coq-serapi, and things break left and right. Perhaps that's the first time I package something trying to link to the coq-core library...

Your list has eg aac-tactics which does link to coq-core

**Comment by SnarkBoojum** [comment]
And AAC_tactics works...

**Comment by SnarkBoojum** [comment]
That was a problem in the Debian packaging for Debian! Sorry for the noise.
