### ISSUE TITLE
Inconsistent classification of zeros

### ISSUE THREAD

**Issue by silene** [coq/coq#16096]
```coq
Require Import Floats.
Goal False.
now generalize (classify_spec 0).
Qed.
```
Found by @bobot.

**Comment by ppedrot** [comment]
The good news is that this was found before the 8.16 release...

**Comment by Zimmi48** [comment]
This is not an 8.16 regression though, so that shouldn't justify delaying 8.16+rc1, should it?

**Comment by ppedrot** [comment]
I'm not sure that tagging a RC with a known soundness bug is a very good idea. Obviously, that depends on the time that will be required to fix this issue, but AFAIU this is a trivial fix. Assuming somebody does write it. Any volunteer?

**Comment by Alizter** [comment]
This has been present since at least 8.11.0.

**Comment by Alizter** [comment]
These axioms lead to an inconsistency:
```coq
Axioms:
normfr_mantissa : float -> PrimInt63.int
ltb : float -> float -> bool
PrimInt63.lsr
  : PrimInt63.int ->
    PrimInt63.int -> PrimInt63.int
PrimInt63.land
  : PrimInt63.int ->
    PrimInt63.int -> PrimInt63.int
PrimInt63.int : Set
frshiftexp : float -> float * PrimInt63.int
float : Set
PrimInt63.eqb
  : PrimInt63.int -> PrimInt63.int -> bool
eqb : float -> float -> bool
div : float -> float -> float
classify_spec
  : forall x : float,
    classify x = SF64classify (Prim2SF x)
classify : float -> float_class
abs : float -> float
```

**Comment by silene** [comment]
> I don't know why we assume axioms in Floats though.

Because we have to. The only way to specify a primitive function in Coq is through an axiom. There is nothing specific about `Floats` here. Indeed, there are about 150 such axioms in Coq.

**Comment by proux01** [comment]
> I don't know why we assume axioms in Floats though. Garbage in garbage out IMO.

Because we don't have a formal proof of the floating point unit of the processor?

**Comment by SkySkimmer** [comment]
Most of those are primitives, I think classify_spec is the only non-reducing axiom.
In principle it could be a primitive too (reducing to eq_refl) but that would take more kernel work for not much gain.

**Comment by ppedrot** [comment]
I personally think that adding sources of non-canonicity in the theory is a wart, but I'm probably a minority. Ideally we should specify these things as SProp or something.

**Comment by proux01** [comment]
Probably, although I don't think this is much of an issue currently (but maybe just because most users are used to Prop).

**Comment by SkySkimmer** [comment]
For the ones where the property is decidable we can also go through an equality normalizer.

**Comment by Blaisorblade** [comment]
@SkySkimmer Is this also in scope for 8.15.2?

**Comment by Alizter** [comment]
@Blaisorblade Yep.
