### ISSUE TITLE
Add coq-http to CI

### ISSUE THREAD

**Issue by Alizter** [coq/coq#16093]
We should add https://github.com/liyishuai/coq-http to the CI.

As recommended here: https://github.com/coq/coq/pull/15333#discussion_r884178848. Although I am not sure we would be able to catch the issue with extraction on an older version of OCaml.

Which versions of OCaml are we using in the CI @coq/ci-maintainers?

**Comment by Zimmi48** [comment]
The flambda tests should be based on the edge switch from the docker image, so this should be fine.
