### ISSUE TITLE
occurrences clauses for local definition bodies are broken

### ISSUE THREAD

**Issue by hamlen** [coq/coq#16144]
Tactics that accept occurrences clauses for bodies of local definitions now report all occurrence numbers as invalid.  Here is an example:

    Goal True.
    set (x := 0).
    Succeed set (y := 0) in x.
    Fail set (y := 0) in x at 1.

The last line should succeed (and did succeed on older versions of Coq) but currently reports an invalid occurrence number as of 8.15.1.

**Comment by SkySkimmer** [comment]
Since e3968a275532d40009f4ed0e7ea8abbe783e034f (https://github.com/coq/coq/pull/13568)
