### ISSUE TITLE
`congruence` 8.16 regression (produces ill-typed terms)

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#16140]
#### Description of the problem

With `Coq 8.15.0` and `Coq 8.15.1` the tactic `congruence` fails in the following scenario.
However, with current `Coq 8.16.0+rc1` the tactic `congruence` succeeds by producing an ill-typed term, after which `Qed` fails. This is strictly worse than before.

```coq
Inductive wrap : unit -> Type :=
  wrapI : bool -> wrap tt.

Goal
  (@existT unit wrap tt (wrapI false)) =
  (@existT unit wrap tt (wrapI true)) -> False.
Proof.
  congruence. (* Fails with 8.15.0, 8.15.1 *)
  (* No more subgoals with 8.16.0+rc1 *)
Fail Qed. (* ill-typed term with 8.16.0+rc1, this is a regression *)
```

**Comment by SkySkimmer** [comment]
Since cea1e4d70d41757c1a71b0a9295e67ae94c3e692 (#15796)

**Comment by ppedrot** [comment]
The easy fix is to revert that PR, but this has just uncovered a bug in some other part of the code. This means that some call to `app_global_with_holes` is passing ill-typed arguments.

**Comment by mrhaandi** [comment]
> The easy fix is to revert that PR, but this has just uncovered a bug in some other part of the code. This means that some call to `app_global_with_holes` is passing ill-typed arguments.

As soon as terms get dependent (as in the example) `cctac.ml` https://github.com/coq/coq/blob/94963e85e3ac29324cdca0a30ae7afeb5704c572/plugins/cc/cctac.ml#L374 gives its best effort (which sometimes may still work) and happily starts building ill-typed terms based on `f_equal`. This is ok since in general we do not have dependent pair injectivity of the second projection. As long as the final term is checked, there is little harm done.

I thought about dealing with such cases in either of two ways.
1) In preprocessing exclude them from consideration. This could in fact strengthen/speed up `congruence` in some cases, but may incur a slow down in others.
2) Add more infrastructure for dependent pair injectivity based for types with unique identity proofs. This would be an interesting project, but quite some work with unclear payoff/potential tradeoffs.

A good way to proceed is revert the commit, add a test case, and add an explicit issue with the essentials of this discussion.

**Comment by mrhaandi** [comment]
To make it more precise and self-contained for the test suite, I further shrank the (ever so slightly dependent) example:
```coq
Inductive wrap : Type :=
  wrapI (u : unit) : match u with tt => bool end -> wrap.

Goal (wrapI tt false) = (wrapI tt true) -> False.
Proof.
  congruence. (* Fails with 8.15.0, 8.15.1 *)
  (* No more subgoals with 8.16.0+rc1 *)
Fail Qed. (* ill-typed term with 8.16.0+rc1, this is a regression *)
```

In the above example, the corresponding projection `build_selector` application used by `congruence` for `app_global_with_holes` in the `Inject (prf,cstr,nargs,argind)` case will produce an ill-typed term
https://github.com/coq/coq/blob/94963e85e3ac29324cdca0a30ae7afeb5704c572/plugins/cc/cctac.ml#L258

**Comment by mrhaandi** [comment]
As discussed, https://github.com/coq/coq/pull/16166 partially reverts https://github.com/coq/coq/pull/15796 and adds a regression test. I did not fully revert the corresponding changes, but only reverted `check_actual_type` back to `check`.
@ppedrot Could you verify that this suffices (I did not revert all your code back to `Tacmach` and `Termops`).
