### ISSUE TITLE
Allow side-effects for vernacs NOT classified as VtSideff

### ISSUE THREAD

**Issue by trilis** [coq/coq#16146]
#### Description of the problem

Currently, as I understand, all custom vernacs modifying parsing state (e.g. adding notations) need to be classified as `VtSideff`. However, some vernacs require another classification (such as `VtStartProof` or `VtQed`), and cannot be classified as `VtSideff`. I propose making possibility of side-effect independent of classification, so that one could create `VtStartProof` or `VtQed` vernac which can make side-effects. One way to do this can be to use pair `(old vernac classification, possibility of side-effect)` instead of current classification or something like that. To keep current extensions working, this possibility of side-effect can be set with some default value.

In my use case, I need to automatically add some notations for interactive definitions. To do this, I added custom vernac with classification `VtStartProof` and call my generating program as a hook after this definition ends. However, it looks like `Defined` does not work with parser-affecting side-effects, so these newly-added notations can be not found after definition in some environments (in IDE while interpreting-to-point and in coqc with async-proofs turned on). I tried to declare my custom vernac which overrides `Defined` and correctly works with side-effects, but it's not possible at the moment for two reasons : firstly, I am not able to classify this vernac as both `VtQed` and `VtSideff`, and secondly, because of #16076. 

As a workaround, I added in my plugin custom no-op vernac `Sync` with `VtSideff` classification, which serves as updating parser state. However, I need to add this vernac after each parser-modifying definition, and that is quite cumbersome.

#### Coq Version

8.15.1

**Comment by SkySkimmer** [comment]
Can't you reserve your notations?
