### ISSUE TITLE
Proofs that lack "Proof." are not parallelizable tasks for async processing

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#16150]
This reduces performance when processing in async mode.  Perhaps simple to fix?

![image](https://user-images.githubusercontent.com/1253341/172199664-27ce4194-e405-4904-9d4a-d9ad5f2d6ad8.png)

![image](https://user-images.githubusercontent.com/1253341/172199957-954130d1-2d96-414d-bc20-0c6ca1914b7f.png)

```
Ltac slow := do 2000000 do 1000 idtac.
Lemma Y: True. exact I. Qed.
Lemma A: True. slow. exact I. Qed.
```

Attn: @gares

**Comment by jfehrle** [comment]
`Set Suggest Proof Using.` reports such items as shown.  It this case it could just say `Proof.`.

```
The proof of exp_le_inv should start with one of the following commands:
Proof using . 
```

**Comment by Blaisorblade** [comment]
1. IIUC, this is currently on purpose, even if I never understood why. IIUC this would be easy to fix if you parsed `.v` files before execution, but that's not how the code is written today, tho people have been busy fixing things.
2. At least if you write `Set Default Proof Using "Type".`, then `Proof using.` and `Proof.` are equivalent, but IIRC that's not the default. I agree the suggestions often use bad style (I elaborate in https://github.com/coq/coq/issues/16151#issuecomment-1147779847).

**Comment by jfehrle** [comment]
An example of when `Proof using.` and `Proof.` are not equivalent:

![image](https://user-images.githubusercontent.com/1253341/172230243-c5c96713-42f1-41b7-8313-ae9ca2cc562c.png)

![image](https://user-images.githubusercontent.com/1253341/172230395-d8ea773c-d546-45ca-b3b6-0021dbbeeb7e.png)

**Comment by gares** [comment]
This is expected. The using modifier was added to declare which variable are used. Proof already existed, considering it a synonym of "using no variable" would have been a breaking change.

**Comment by jfehrle** [comment]
I don't see how that's a breaking change.  "Proof." appears to work in some cases.  But it doesn't matter...

I think [this](https://github.com/coq/coq/issues/16151#issuecomment-1149096394) is a much better approach.
