### ISSUE TITLE
[stdlib] unnecessarily weak modulo lemmas in Nat

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#16186]
#### Description of the problem

Performing `Search ((_ * _) mod _).` after `Require Import PeanoNat.` returns the following

```coq
Nat.mod_mul:
  forall a b : nat, b <> 0 -> (a * b) mod b = 0
Nat.mul_mod_idemp_l:
  forall a b n : nat, n <> 0 -> (a mod n * b) mod n = (a * b) mod n
Nat.mul_mod_idemp_r:
  forall a b n : nat, n <> 0 -> (a * (b mod n)) mod n = (a * b) mod n
Nat.mul_mod:
  forall a b n : nat, n <> 0 -> (a * b) mod n = (a mod n * (b mod n)) mod n
Nat.mul_mod_distr_l:
  forall a b c : nat, b <> 0 -> c <> 0 -> (c * a) mod (c * b) = c * (a mod b)
Nat.mul_mod_distr_r:
  forall a b c : nat, b <> 0 -> c <> 0 -> (a * c) mod (b * c) = a mod b * c
```

Interestingly, **all** of the above `_ <> 0` conditions are unnecessary.
This is shown by the following proofs.

```coq
Lemma mod_mul' a b : (a * b) mod b = 0.
Proof. now destruct b; [rewrite Nat.mul_0_r|apply Nat.mod_mul]. Qed.

Lemma mul_mod_idemp_l' a b n : (a mod n * b) mod n = (a * b) mod n.
Proof. now destruct n; [|apply Nat.mul_mod_idemp_l]. Qed.

Lemma mul_mod_idemp_r' a b n : (a * (b mod n)) mod n = (a * b) mod n.
Proof. now destruct n; [|apply Nat.mul_mod_idemp_r]. Qed.

Lemma mul_mod' a b n : (a * b) mod n = (a mod n * (b mod n)) mod n.
Proof. now destruct n; [|apply Nat.mul_mod]. Qed.

Lemma mul_mod_distr_l' a b c : (c * a) mod (c * b) = c * (a mod b).
Proof.
  now destruct b; destruct c; [|rewrite Nat.mul_0_r| |apply Nat.mul_mod_distr_l].
Qed.

Lemma mul_mod_distr_r' a b c : (a * c) mod (b * c) = a mod b * c.
Proof.
  now destruct b; destruct c; [repeat rewrite Nat.mul_0_r..|apply Nat.mul_mod_distr_r].
Qed.
```

Currently, sequential `rewrite` using the weak lemmas creates inconvenient subgoals.
It would be nice to have stronger statements in the standard library.

At times, `div` is even worse off https://github.com/coq/coq/issues/16186#issuecomment-1158576972

#### Coq Version
`The Coq Proof Assistant, version 8.15.2`

**Comment by Alizter** [comment]
I think this might be because the defintion of mod 0 was changed, and the old one needed these side conditions. I seem to recall that OCaml mod acting weird in this way.

**Comment by olaure01** [comment]
I did not follow #14086, but now that we have changed the definition of `mod`, I strongly support such a simplification of statements. The tricky part seems to be deprecation. Here are possible scenarios coming to my mind, I don't know which is best practice in such a situation:

- replace old statements by new ones (without touching names) once and for all;
- introduce new names for new statements (for example using `mod'` in names to refer to properties valid only with the new `mod` definition);
- same and mark old ones as deprecated;
- same and go then to a second phase where old deprecated names are used back for new simplified statements (with deprecation phase for new names).

**Comment by mrhaandi** [comment]
Maybe this opportunity can be used to, for example, reconsider existing
`Zmult_mod: forall a b n : Z, ((a * b) mod n)%Z = ((a mod n * (b mod n)) mod n)%Z` versus existing
`Z.mul_mod: forall a b n : Z, n <> 0%Z -> ((a * b) mod n)%Z = ((a mod n * (b mod n)) mod n)%Z` to provide best user experience.

**Comment by mrhaandi** [comment]
The case of `div` is even worse:
`Search (_/_/_)%Z.` returns
```coq
Zdiv_Zdiv: forall a b c : Z, (0 <= b)%Z -> (0 <= c)%Z -> (a / b / c)%Z = (a / (b * c))%Z
Z.div_div: forall a b c : Z, b <> 0%Z -> (0 < c)%Z -> (a / b / c)%Z = (a / (b * c))%Z
```
which both are strictly weaker than the following `div_div_full`

```coq
Lemma div_div_full : forall a b c : Z, (0 <= c)%Z ->
  (a / b / c)%Z = (a / (b * c))%Z.
Proof.
  intros a b c. destruct (Z.eq_decidable b 0) as [->|Hb].
  - now destruct a.
  - intros [Hc|<-]%Z.lt_eq_cases.
    + now apply Z.div_div.
    + now rewrite Z.mul_0_r, !Zdiv_0_r.
Qed.
```

`div_div_full` cannot be strengthened further to `c < 0` becase
`3 / 2 / (-1) = -1` which is not equal to `3 / (2 * (-1)) = -2`
