### ISSUE TITLE
coq  \  Syntax Error: Lexer: Undefined token

### ISSUE THREAD

**Issue by chenzhouf** [coq/coq#16191]
```coq
Lemma Ex_Lemma : forall x y,
  Ensemble x /\ Ensemble y -> exists f, Function f /\ dom( f ) = x /\
  ran( f ) = \{ λ z, exists u, u∈x /\ z = [u] × y \}.
```

Why the first "\\" in the third line is wrong ? The messages show "Syntax Error: Lexer: Undefined token". I am a neophyte in coq and thank you very much!

**Comment by SkySkimmer** [comment]
Because no notation is defined using `\{` so it doesn't exist in the grammar.
