### ISSUE TITLE
Assertion failed with universe checking turned off

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#16204]
#### Version

Coq 8.15.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.9

#### Description of the problem

The following program causes an anomaly.

```coq
Set Implicit Arguments.
Set Universe Polymorphism.
Unset Universe Checking.

Class IsProp (A : Type) : Prop :=
  irrel (x y : A) : x = y.

Class IsProofIrrel : Prop :=
  proof_irrel (A : Prop) :> IsProp A.

Class IsPropExt : Prop :=
  prop_ext (A B : Prop) (a : A <-> B) : A = B.

Class IsTypeExt : Prop :=
  type_ext (A B : Type) (f : A -> B) (g : B -> A)
  (r : forall x : A, g (f x) = x) (s : forall y : B, f (g y) = y) :
  A = B.

#[export] Instance anomaly
  `{IsProofIrrel} `{IsTypeExt} : IsPropExt.
Proof.
  intros A B [f g]. eapply (type_ext f g).
  - intros x. apply irrel.
  - intros y. apply irrel.
Qed.
```

```
Anomaly "File "kernel/univ.ml", line 882, characters 4-10: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

#### Notes

I am not sure whether an anomaly is something I should never see or
something I should expect to see if I turn off universe checking,
so I thought I might as well report this to inquire.

**Comment by Alizter** [comment]
An anomaly is an uncaught exception. This means that there is an exceptional case where no error message was written or something else went wrong. Please report all anomalies :-)

**Comment by SkySkimmer** [comment]
Seems fixed on master (probably https://github.com/coq/coq/pull/15863)
