### ISSUE TITLE
doc-stdlib-html target no longer works

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16253]
I use this target in my Debian scripts.  Was this the recent dune PR?  cc @ejgallego

**Comment by Alizter** [comment]
You want `stdlib-html`, if you need to be backwards compatible we could probably add a `doc-stdlib-html` target that does the same thing.

**Comment by JasonGross** [comment]
Backwards compatibility not necessary, thanks!

**Comment by ejgallego** [comment]
Keep in mind @JasonGross that the location of the docs artifacts have changed too.

The build setup for the docs has also changed, for example we now support building docs from an installed Coq and a few other things, please don't hesitate to ping us in Zulip if you have any question.
