### ISSUE TITLE
eauto disrespects hint cost

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#16282]
#### Description of the problem

Similarly to the (already fixed) https://github.com/coq/coq/issues/6195 `eauto` disrespects hint cost.

- `shelve` having high cost needs to be only uses as last resort.
- `auto` and `typeclasses eauto` correctly apply low-cost hints first and solve the goal.
- `eauto` jumps the gun and shelves the goal disrespecting hint cost.

```coq
Lemma TrueI : unit -> True.
Proof. easy. Qed.

#[local] Hint Extern 99 => shelve : db.
#[local] Hint Extern 0 (True) => apply TrueI : db.
#[local] Hint Extern 0 (unit) => exact tt : db.

Goal True.
Proof.
  Succeed (solve [unshelve auto with db nocore]).
  Succeed (solve [unshelve typeclasses eauto with db nocore]).
  Fail (solve [unshelve eauto with db nocore]).
Abort.
```

#### Coq Version

The Coq Proof Assistant, version 8.15.2
compiled with OCaml 4.14.0

**Comment by ppedrot** [comment]
See also #5163. The eauto tactic uses a homebrew priority algorithm, I think it considers that shelve solves the goal and thus has maximum priority.

**Comment by mrhaandi** [comment]
For the record, here is a workaround for the current "homebrew priority algorithm".
One can wrap the current goal with high cost and shelve only wrapped goals (also unwrapping them).
Therefore, if `eauto` can solve the goal, it does. Otherwise, after some effort, it shelves remaining subgoals.

```coq
Lemma TrueI : unit -> True.
Proof. easy. Qed.

#[local] Hint Extern 0 (True) => apply TrueI : db.
#[local] Hint Extern 0 (id ?x) => change x; shelve : db.
#[local] Hint Extern 99 => match goal with |- ?x => change (id x) end : db.

(* good effort, some subgoals remain *)
Goal True.
Proof.
  unshelve eauto with db nocore.
  exact tt.
Qed.

#[local] Hint Extern 0 (unit) => exact tt : db.

(* uniform behavior *)
Goal True.
Proof.
  Succeed (solve [unshelve auto with db nocore]).
  Succeed (solve [unshelve typeclasses eauto with db nocore]).
  Succeed (solve [unshelve eauto with db nocore]).
Abort.
```

**Comment by mrhaandi** [comment]
@ppedrot After looking at `eauto`, I do not consider https://github.com/coq/coq/issues/15558 to be a duplicate of https://github.com/coq/coq/issues/5163. Both #16282 and #15558 are about the actual estimated hint cost, whereas #5163 is about the way cost estimation leads to divergence.
I try to address the former aspect in PR https://github.com/coq/coq/pull/16286. The latter aspect (I think) will forever remain an open `eauto` bug for compatibility reasons.
