### ISSUE TITLE
Anomaly "Stm.join: tip not cached"

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16335]
#### Description of the problem

```coq
Goal True.
Proof.
```
gives
```
Error: Anomaly "Stm.join: tip not cached"
Please report at http://coq.inria.fr/bugs/.
```

cc @coq/stm-maintainers 

#### Coq Version

https://gitlab.com/coq/coq/-/jobs/2740357137/artifacts/download i.e. a17855e0870d17cd722adfd96b867be2de219445

**Comment by palmskog** [comment]
Another trigger for what is probably the same bug:
```coq
Class C := {}.
Local Instance I11 : C.
Local Ltac lt1 := auto.
```
when compiled this results in:
```
Error: Anomaly "Stm.join: tip not cached"
Please report at http://coq.inria.fr/bugs/.
```
