### ISSUE TITLE
Preferences dialog crashes CoqIDE on Mac M1

### ISSUE THREAD

**Issue by alexei-iliasov** [coq/coq#16343]
#### Description of the problem

The platform works quite well *so far* on MacOS 12.4 (M1 Pro) with one annoying exception of preferences crashing the tool. Hope something simple in the UI

#### Coq Version

8.15-2022.04

**Comment by ppedrot** [comment]
Duplicate of #16136

**Comment by orilahav** [comment]
Duplicate of https://github.com/coq/coq/issues/15486 as well
