### ISSUE TITLE
Version-conditional vernacular

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16351]
I'd like to have a vernacular modifier like `Comment Unless ( 8.16 <= COQ_VERSION < 8.17 ) Ltac foo := bar.`.  This would make version compatibility within a single file much easier in the future

**Comment by ejgallego** [comment]
There is already a discussion about this kind of conditional pre-processing in some other issue.

I still stand by my position that adding this to Coq is not the right thing to do.

**Comment by SkySkimmer** [comment]
Won'tfix

**Comment by JasonGross** [comment]
@ejgallego do you know what other issue?

And what again is the reason it's not right to add this to Coq?

Currently the status quo for projects that want to do version-based conditional compilation is that lots of code must be duplicated across copies of files, and/or that significant makefile magic needs to be added.  It'd be much nicer to have an easy way to make backwards-compatible overlays across all projects without needing to worry about adding infrastructure to projects.

**Comment by ejgallego** [comment]
> And what again is the reason it's not right to add this to Coq?

That adds a lot of complexity which we don't have the machinery to manage, just think user interfaces having to understand this. Moreover I am not sure we want to foster hellish conditional / spaguetti files; AFAICT this hasn't worked very well in other languages.

As of today, the intepretation of Coq commands has a semantics, so I think that any such proposal such propose a reasonable semantics in terms of an interpretation for the connectives, but see all the problems I mentioned in the other issues.

A pragma to version full files could be interesting, or document parts, but at the command level, this just injects a dependency on the version on each execution of the command, which seems excessive to me.

I am not sure what the case for supporting more than a few Coq versions is anyways; and if it is worth all this complex machinery. Not sure that it would be a priority IMO.

Note that in dune you can use `%{coq:version}` for example in Dune, to easily do that at the level of files.

**Comment by JasonGross** [comment]
> AFAICT this hasn't worked very well in other languages.

Are there horror stories from the C preprocessor or something?  (I'm not aware of this)

> so I think that any such proposal such propose a reasonable semantics in terms of an interpretation for the connectives, but see all the problems I mentioned in the other issues.
> 
> A pragma to version full files could be interesting, or document parts, but at the command level, this just injects a dependency on the version on each execution of the command, which seems excessive to me.

Indeed this essentially needs to be a modifier on lexing not on execution.  We do need some sort of connective or well-delimited block ending (perhaps just the standard end of sentence terminator `.`), and the semantics are that the conditional is treated exactly as `Comments` (or is it `Comment`?) if the condition fails (and so text inside is lexed and parsed as a comment not a command) or as whitespace if the condition passes.  Some version that attaches to document parts (a la `(* ... *)`) also seems fine if the syntax can be made to work.



> I am not sure what the case for supporting more than a few Coq versions is anyways; and if it is worth all this complex machinery. Not sure that it would be a priority IMO.

The case is decoupling packages built on Coq from Coq's package manager and release cycle.  If I want my project to be able to be built with Coq shipped in Ubuntu LTS or Debian stable, and I want my project tested by Coq's CI, then I have to manage all the versioning myself.  Ltac2 as of today does not even guarantee the ability to write performant code that will work on both master and the latest released version of Coq (cf the recent change to projections).

**Comment by ejgallego** [comment]
> Are there horror stories from the C preprocessor or something? (I'm not aware of this)

Horror stories with pre-processing have been there since I can remember, I can find plenty of recent discussions, e.g:

https://users.rust-lang.org/t/whats-your-stance-towards-conditional-compilation/82241

> Indeed this essentially needs to be a modifier on lexing not on execution. We do need some sort of connective or well-delimited block ending (perhaps just the standard end of sentence terminator .), and the semantics are that the conditional is treated exactly as Comments (or is it Comment?) if the condition fails (and so text inside is lexed and parsed as a comment not a command) or as whitespace if the condition passes. Some version that attaches to document parts (a la (* ... *)) also seems fine if the syntax can be made to work.

Note that Coq has not a standard sentence terminator `.` ; there are more technical problems with the above proposal.

I indeed believe that a some point a design could work OK, but at the cost of great complexity.

If you need this kind of stuff, why not to use some simple external pre-processor already existing?

> The case is decoupling packages built on Coq from Coq's package manager and release cycle. If I want my project to be able to be built with Coq shipped in Ubuntu LTS or Debian stable, and I want my project tested by Coq's CI, then I have to manage all the versioning myself. 

Yes, and for this purpose I think that version numbers are a really bad system, and moreover, I don't see how they avoid you "having to manage all the versioning yourself", you still do, this time in the form of `#ifdefs`.

For example, how would you encode a change that happens in Coq master? Versioning may work really poorly here.

It seems to me that using flags for this purpose would be already much better; that also has a clear model on the UI.

The reality of Debian or Ubuntu package management is at odds with the reality of complex package ecosystems such as the ones of OCaml, Lean, Coq, or Rust, which require an almost continous deployement model.
