### ISSUE TITLE
The destruct tactic misbehaves with inductive types having let-bindings in parameters

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#16390]
Small example on d6307ac0a27f139b731016922de1fa58ee1db83d.
```coq
Inductive foo (n := 0) := Foo.

Goal foo -> True.
Proof.
intros H.
destruct H. (* Cannot recognize an induction scheme. *)
```

**Comment by kyoDralliam** [comment]
`induction` also seem to misbehave in presence of let-bindings for records (witnessed on coq `8.16.1`)
```
Record foo (n := 0) := Foo {}.

Goal foo -> True.
Proof.
intros H.
induction H. (* Cannot recognize an induction scheme. *)
```

**Comment by ppedrot** [comment]
Yes, that's the same code. Note the somewhat related #17408, which should make the future fix easier to write.
