### ISSUE TITLE
apply in with non-casted metas results in an anomaly

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#16402]
Small reproducible snippet:
```coq
Goal True -> True.
Proof.
intros H.
apply (fun (f : True -> True) (n : True) => f n) in H.
(* Anomaly "in retyping: unknown meta 150." *)
```
The issue is present as of de96bfd67df02068c853155bd53264ad61ddab81, and was already there in Coq 8.8, the oldest version I had available on my computer. Basically, in `Tactics.clenv_refine_in` there is a missing `clenv_cast_meta`, and the term from the example hits right in the non-well-formed shape for refining terms.

This bug was found while observing similar behaviour handled correctly in the case of the `absurd` tactic.

**Comment by JasonGross** [comment]
> was already there in Coq 8.8, the oldest version I had available on my computer.

It is present already in v8.1, where it fails with `Anomaly: type_of: this is not a well-typed term. Please report.`.  (It is a syntax error in v8.0.)
