### ISSUE TITLE
Ltac2 stack traces

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16410]
#### Description of the problem

I'd like to have a global setting that enables stack trace printing for Ltac2 errors.  There should also be some support within the language for managing stack traces; in particular the `exn` type should be enriched with an optional stack trace that can then be manipulated in simple ways ("reraise the error with the explicit stack trace", "raise an error prepending the current frame to the stack", "raise an error starting the stack trace from scratch here"), and when stack-trace printing is disabled the stack-traces are always `None`.  This should not (I hope) add too much overhead (and I'm fine if it's the case that when we eventually get precompilation for Ltac2, changing this setting recompiles all Ltac2 tactics in scope).  But stack trace printing is essential for debugging.  (Having this will also pave the way for Ltac2 profiling, I believe.)

#### Coq Version

8.15

**Comment by Janno** [comment]
This comment here is very related: https://github.com/coq/coq/blob/master/plugins/ltac2/tac2ffi.ml#L249

The backtrace exist whenever `Set Ltac2 Backtrace` is enabled but they are thrown away whenever the exception passes the OCaml/Ltac2 boundary. (Raising an exception in Ltac2 always augments it with the current function stack on the OCaml side.)

**Comment by JasonGross** [comment]
Ah, neat, I was not aware of `Set Ltac2 Backtrace`.

Here's a small example of a case where the backtrace is thrown away where I would like to see a better backtrace:
```coq
Require Import Ltac2.Ltac2.
Set Ltac Backtrace. Set Ltac2 Backtrace.
Ltac2 foo0 () := '(_).
Ltac2 foo () := foo0 ().
Ltac bar := idtac; let v := constr:(ltac:(ltac2:(foo ()))) in exact v.
Set Default Proof Mode "Classic".
Goal True.
  bar.
  (* Error:
Backtrace:

In nested Ltac calls to "bar" and "_", last term evaluation failed.
Cannot infer an internal placeholder of type "Type".
*)
```

**Comment by Janno** [comment]
I think that error does not originate in Ltac2 but rather in Ltac1's `constr:()`. `'` in Ltac2 is `open_constr:()` IIRC and that accepts `_` just fine:
```
  Succeed ltac2:(let t := '(_) in ()).
```

**Comment by JasonGross** [comment]
Hmmm.

I don't suppose it's possible to get backtraces on anomalies?
```coq
Require Import Ltac2.Ltac2.
Ltac2 foo () := let v := Constr.Unsafe.make (Constr.Unsafe.Rel -1) in
                let x := Constr.Binder.make None 'True in
                let vv := Constr.Unsafe.make (Constr.Unsafe.App v (Array.of_list [v])) in
                let f := Constr.Unsafe.make (Constr.Unsafe.Lambda x vv) in
                let ff := Constr.Unsafe.make (Constr.Unsafe.App f (Array.of_list [f])) in
                Std.eval_hnf ff.
Set Ltac2 Backtrace.
Ltac2 Eval foo ().
(* Error: Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.
*)
```

**Comment by Janno** [comment]
No. You can only get the Ocaml backtrace. It would be an amazingly useful feature!

**Comment by SkySkimmer** [comment]
Is there an example of Ltac2 Backtrace actually working? Is it only for exceptions thrown by the ltac2 API ie Ltac2.Control.throw?

**Comment by JasonGross** [comment]
It works for exceptions from `Control.throw` and `Control.zero`, at the very least
