### ISSUE TITLE
Ltac2.Constr.Binder.make should give a nicer error message than `Anomaly "Uncaught exception Retyping.RetypeError(0)."`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16419]
#### Description of the problem

Here's some code producing a slightly different error message than the one in the title:
```coq
Require Import Ltac2.Ltac2.
Ltac2 Eval Constr.Binder.make None 'I.
(* Error: Anomaly "Uncaught exception Retyping.RetypeError(2)." *)
```

This should give me a nice error message about how `True` is not a Sort.  (And `Binder.make` isn't even an unsafe tactic)

#### Coq Version

8.15

**Comment by JasonGross** [comment]
The one in the title can be gotten with
```coq
Require Import Ltac2.Ltac2.
Ltac2 Eval let b := Constr.Binder.make None '(_ : Type) in ().
Ltac2 Eval let b := Constr.Binder.make None '_ in ().
(* Error: Anomaly "Uncaught exception Retyping.RetypeError(0)." Please report at http://coq.inria.fr/bugs/. *)
```
It would be nice to be able to make binders that are evars without having to have casts lying around, with something less hacky than
```coq
Ltac2 Eval let b := Constr.Binder.make None '(match _ return Type with ev => ev end) in ().
```

**Comment by SkySkimmer** [comment]
That sounds like we should have syntax for a elaboration-time-only cast.
