### ISSUE TITLE
Ltac2 `printf` should support "raw" formatting

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16417]
#### Description of the problem

`Ltac2 Eval`, `Print Ltac2`, and `idtac` can all handle printing objects of arbitrary sorts of values.  Please add support for such printing at runtime for ease of debugging and introspection.

#### Coq Version

8.15

**Comment by SkySkimmer** [comment]
Ltac2 Eval: toplevel printing has access to types, runtime printing does not, same as ocaml.

Print Ltac2 does not print objects, it prints compiled code.

idtac does some ltac1 nonsense.
