### ISSUE TITLE
`Print Assumptions` prints incorrect results in vos/vok builds

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#16411]
#### Description of the problem

It used to be the case that `Print Assumptions` in a vos/vok build would just error -- which makes sense, given that *all* proofs are opaque, so who knows where there are assumptions hiding.

However, since Coq 8.15, Coq instead prints
```
Closed under the global context
```
That is slightly concerning, because the proof *definitely* relies on some axioms! Reporting incorrect results, especially for a feature like this, seems pretty bad.

So, that should be fixed. But what would be even nicer is if `Print Assumptions` could actually work in vos/vok builds, by embedding enough information in `vos` files to know if there are any axioms used here. I am not sure if that is feasible though.

#### Coq Version

8.15.2

**Comment by Blaisorblade** [comment]
> by embedding enough information in vos files to know if there are any axioms used here. I am not sure if that is feasible though.

You mean vok not vos right? That makes sense. On voks `Print Assumptions` should also warn (briefly) about potential hidden universe inconsistencies, but yeah.

**Comment by RalfJung** [comment]
vok files don't contain any information, they are empty files to indicate that a check has been done.

**Comment by Blaisorblade** [comment]
Sure, but `vok` files are produced after proof checking, and adding info there is plausible (in the past we discussed designs where `vok` files would store entire proof terms).

OTOH, the goal of `vos` files is to describe interface _without_ processing proofs, so it seems impossible to deduce which axioms the proof _would_ use.

**Comment by RalfJung** [comment]
> OTOH, the goal of vos files is to describe interface without processing proofs, so it seems impossible to deduce which axioms the proof would use.

What I had in mind is to store whether a proof was `Admitted` or not.

But yeah I guess that's not actually enough, since we cannot walk the transitive dependencies... and having information in vok files (and importing that!) is a rather big change.

So I think for now this bug is mostly about stopping to print plainly incorrect information on `Print Assumptions`.

**Comment by Blaisorblade** [comment]
Agreed, and labeled accordingly — feel free to edit the description. 

> and having information in vok files (and importing that!) is a rather big change.

`Import` should _not_ load `vok` files — only `Print Assumptions` could conceivably do that, if Coq went for real separate typechecking (which indeed isn't in this issue).
