### ISSUE TITLE
Print Ltac2 Type

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16420]
I'd like to be able to write `Print Ltac2 Type exn`

**Comment by JasonGross** [comment]
It should work like `Print Ltac2`, but print the type definition (i.e., print things defined via `Ltac2 Type`)

**Comment by SkySkimmer** [comment]
So exn would show `Ltac2 Type exn := [ .. ].`?

**Comment by JasonGross** [comment]
Yep, ideally with all the constructors that have been added to it, along with their types / what I'd have to type into Coq to get a copy of the type as it currently is
