### ISSUE TITLE
For automation purposes what GUI framework does the current Coq IDE use?

### ISSUE THREAD

**Issue by enjoysmath** [coq/coq#16453]
What GUI framework does the current Coq IDE use to draw windows/widgets?   Is it Win32-based, UWP, .NET, Gtk, or other?

I'm writing a tool that works along side the IDE and would like to automate parts of the Coq IDE, for example, I want to target the scratch pad and paste code into it.

**Comment by Zimmi48** [comment]
This is Gtk (3). It's documented in the dependencies. That being said, if you want to write IDE enhancements, another strategy could be to write extensions for the VsCoq package for the VS Code plugin.

For what is worth, issues in this repository are generally only used to report bugs. If you want to start discussions / ask questions, you have plenty of spaces to do so, e.g., the Zulip chat, the Discourse forum, etc. See https://coq.inria.fr/community

**Comment by enjoysmath** [comment]
Oh, I hate VS Code!!!  I like the standalone IDE best.   Thanks!  And noted
about where to ask general questions.
