### ISSUE TITLE
Error reporting when building stdlib has too short paths

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#16469]
- put some error in a stdlib file, eg `theories/Init/Logic.v`
- dune build

the error will be reported as `File "./Logic.v", line XXX, characters XXX:` but should be `File "theories/Init/Logic.v", etc`

**Comment by ejgallego** [comment]
The simplest fix is to `(cd ...)` to the right directory before calling the rule, we go the infrastructure to adjust the paths already there.

Dune's OCaml API is a bit better in this aspect as it is not limited by having to associate the rules to a concrete directory, but indeed support for libraries that span in subdiretories was never superb due to OCaml not really supporting this.

**Comment by Alizter** [comment]
Dune's OCaml rules suffer from the exact same problem here, but their solution is to lex the OCaml error messages and update them as necessary.

**Comment by Alizter** [comment]
By the way, I believe Dune builds theories from a common directory whereas our rules call coqc in the same directory. Perhaps we could configure Coq (basically Cd) to relativize the file names for printing. It would give us more flexability where we want to call coqc.

**Comment by ppedrot** [comment]
I support this issue very much, it's very annoying to compile the code and get short (and sometime conflicting!) names that I have to expand manually with find, and check randomly in case of conflict.

**Comment by ejgallego** [comment]
> By the way, I believe Dune builds theories from a common directory whereas our rules call coqc in the same directory. Perhaps we could configure Coq (basically Cd) to relativize the file names for printing. It would give us more flexability where we want to call coqc.

Yes, Dune native `(coq.theory` does the right thing here, we should imitate it.

**Comment by SkySkimmer** [comment]
Fixed since https://github.com/coq/coq/pull/17334
