### ISSUE TITLE
Ltac2: Applying unit as a function gives assertion failed error

### ISSUE THREAD

**Issue by yiyunliu** [coq/coq#16504]
#### Description of the problem
Here's the example program:
```coq
From Ltac2 Require Import Ltac2.
Ltac2 Eval () 1.
```
Here's the error message:
```
File "./test4.v", line 2, characters 0-16:
Error:
Anomaly
"File "plugins/ltac2/tac2intern.ml", line 1132, characters 2-8: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

#### Coq Version
The Coq Proof Assistant, version 8.16.0
compiled with OCaml 4.14.0

I'm running Coq on Arch Linux (coq is installed through opam)

**Comment by SkySkimmer** [comment]
Duplicate https://github.com/coq/coq/issues/12820
(fixed in https://github.com/coq/coq/pull/16647)
