### ISSUE TITLE
Shelved goals can become impossible to unshelve

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#16513]
After `[foo] : simpl`, `foo` is no longer marked as shelved.  `Unshelve` won't make it visible.  

This doesn't happen with `[foo] : idtac` or `[foo] : auto`.

```coq
Goal forall n m:nat, m > 0 -> True /\ False.
intros.
split.
2: refine ?[foo].
[foo] : shelve.
Show Existentials.
  (* 
  Existential 1 = ?Goal : [n : nat  m : nat  H : m > 0 |- True]
  Existential 2 = ?foo : [n : nat  m : nat  H : m > 0 |- False] (shelved)
  *)
[foo] : simpl.
Show Existentials.
  (*
  Existential 1 = ?Goal : [n : nat  m : nat  H : m > 0 |- True]
  Existential 2 = ?foo : [n : nat  m : nat  H : m > 0 |- False]   NO LONGER SHELVED!
  *)
Unshelve.
Show Existentials.
  (*   foo IS NOT UNSHELVED!
  1 subgoal
  n, m : nat
  H : m > 0
  ______________________________________(1/1)
  True
  *)
```

attn: @Alizter

**Comment by Zimmi48** [comment]
Yes, that's 100% a bug. FTR, the `Grab Existential Variables` command that was removed in 8.15 was precisely kept around for a long time because of this kind of bugs. We were not aware of any remaining bugs at the time of the removal, but you've shown that they were not extinct.

**Comment by jfehrle** [comment]
"Shelved goal escapes the shelf" seems mighty cryptic.  The point is that after the tactic is applied, the goal is no longer marked as shelved in `Show Existentials` but it doesn't show up in the context, either.

**Comment by Zimmi48** [comment]
Shelved goal escapes the shelf means that the goal can become not accessible anymore, which is a serious bug now that `Grab Existential Variables` has been removed.

**Comment by jfehrle** [comment]
I understand that.  I was thinking of others who see this.  How about "Shelved goals can become impossible to unshelve"?  They're still accessible with an explicit goal selector `[ name ]`.

**Comment by Zimmi48** [comment]
>How about "Shelved goals can become impossible to unshelve"?

:+1: 

> Though they're still accessible with an explicit goal selector `[ name ]`.

Right, I had forgotten about this. To trigger the bug, you need a named goal, which means that it will still be accessible. But depending on what is the root cause for this bug, there may be instances that trigger it without a named goal, thus where the goal becomes completely inaccessible.

**Comment by SkySkimmer** [comment]
You need a named goal to trigger the bug, but there is no guarantee that the nonunshelvable resulting goal(s) will carry on the name. For instance if we do `refine _` instead of `simpl` the resulting goal has no name, and in general it's impossible to carry on the name since multiple goals may be generated eg `refine ((fun (x:nat) y  => y) _ _)` produces 2 goals and they can't use the same name.
So it is possible to make it truly unreachable.

**Comment by jfehrle** [comment]
> but there is no guarantee that the nonunshelvable resulting goal(s) will carry on the name.

> `refine ((fun (x:nat) y  => y) _ _)` produces 2 goals and they can't use the same name.

How about using the old name as a prefix to generate fresh names for the 2nd, 3rd, ... goals?  Could that be implemented in one place or would it have to be spread across the implementation of many tactics?
