### ISSUE TITLE
Anomaly "Evar ?X3577 was not declared. on `transparent_abstract`(?)

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16534]
#### Description of the problem

I've no idea what's going on here, maybe someone with more understanding of the code can make an example that's shorter than 12086 lines (or someone with more patience than I can do binary search on eliminating constructors of the relevant inductive to figure out which one is problematic, if it's not something silly like losing track of evars when there are too many of them).
[bug_anom_evar_not_declared_03.v.txt](https://github.com/coq/coq/files/9637878/bug_anom_evar_not_declared_03.v.txt)
[bug_anom_evar_not_declared_03.v.tar.gz](https://github.com/coq/coq/files/9637876/bug_anom_evar_not_declared_03.v.tar.gz)

#### Coq Version

8.15.0, also e946e6f4a927eb12cad3528433890fcbe2f5ec70

**Comment by SkySkimmer** [comment]
Reduced:
~~~coq
Ltac mk body :=
  let __ := match goal with
            | _ => simple notypeclasses refine (let X := _ in _);
                  [ transparent_abstract exact body |]
            end
  in
  idtac.


Goal True.
  let bla := open_constr:(_) in
  mk bla.
~~~

In the original `let bla` is `let raw_invert_bind_args0`, and
~~~coq
  let __ := match goal with
            | _ => simple notypeclasses refine (let name : ty := _ (* HERE *) in
                                                _);
                   [   transparent_abstract exact body using name
                   | ]
            end in
  lazymatch goal with
  | [ H := ?name |- _ ]
    => let __ := match goal with _ => clear H end in
       name
  end.
~~~
this ltac always returns the evar from the hole marked with `(* HERE *)`. This evar is defined to be the constant from transparent_abstract (maybe applied to stuff? it doesn't matter).
Then the second `mk` call runs `transparent_abstract` with `body` evaluating to that evar, but abstract drops all evars while running the tactic so we get Not_found.

**Comment by SkySkimmer** [comment]
You can work around this by doing eg
~~~coq
      let name := eval cbv beta in name in
       name
~~~
at the end of `mk`, the `eval cbv beta` will also evar normalize.

**Comment by JasonGross** [comment]
Fascinating, thanks for tracking this down

**Comment by SkySkimmer** [comment]
Fixed in master, probably by https://github.com/coq/coq/pull/17745
