### ISSUE TITLE
XML Protocol: `subgoals` does not respect `gf_mode = "short"` with proof diffs

### ISSUE THREAD

**Issue by whonore** [coq/coq#16564]
The `subgoals` command in the XML protocol is useful because it allows one to filter out unnecessary goal information. In particular, setting `gf_mode` to `"short"` stops the hypotheses from being reported, which is useful if one just wants to count the number of admitted or shelved goals. However, this flag is ignored if proof diffs are enabled.

The relevant function is [`process_goal_diffs`](https://github.com/coq/coq/blob/4ae56cf11346017939ec8966c96b9abf7462d288/ide/coqide/idetop.ml#L198) in `ide/coqide/idetop.ml`.
```ocaml
let process_goal short sigma g =
  let evi = Evd.find sigma g in
  let env = Evd.evar_filtered_env (Global.env ()) evi in
  let min_env = Environ.reset_context env in
  let name = if Printer.print_goal_names () then Some (Names.Id.to_string (Termops.evar_suggested_name env sigma g)) else None in
  let ccl =
    pr_letype_env ~goal_concl_style:true env sigma (Evd.evar_concl evi)
  in
  let process_hyp d (env,l) =
    let d' = CompactedDecl.to_named_context d in
      (List.fold_right Environ.push_named d' env,
       (pr_compacted_decl env sigma d) :: l) in
  let hyps =
    if short then [] else
      let (_env, hyps) =
        Context.Compacted.fold process_hyp
        (Termops.compact_named_context (Environ.named_context env)) ~init:(min_env,[])
      in
      hyps
  in
  { Interface.goal_hyp = List.rev hyps; Interface.goal_ccl = ccl; Interface.goal_id = Proof.goal_uid g; Interface.goal_name = name }


let process_goal_diffs diff_goal_map oldp nsigma ng =
  let env = Global.env () in
  let name = if Printer.print_goal_names () then Some (Names.Id.to_string (Termops.evar_suggested_name env nsigma ng)) else None in
  let og_s = match oldp, diff_goal_map with
  | Some oldp, Some diff_goal_map -> Proof_diffs.map_goal ng diff_goal_map
  | None, _ | _, None -> None
  in
  let (hyps_pp_list, concl_pp) = Proof_diffs.diff_goal ?og_s (Proof_diffs.make_goal env nsigma ng) in
  { Interface.goal_hyp = hyps_pp_list; Interface.goal_ccl = concl_pp;
    Interface.goal_id = Proof.goal_uid ng; Interface.goal_name = name }
```

It seems like it should be a fairly easy fix. Just do what `process_goal` does and return `[]` for `Interface.goal_hyp` if `short` is `true`. If this is, in fact, all that's necessary, I'd be willing to open a PR.

**Comment by Alizter** [comment]
cc @jfehrle

**Comment by jfehrle** [comment]
@whonore That should work, but do test it.

Completely off topic: do you expect Coqtail will support the visual Ltac debugger any time soon?  (Just curious)

**Comment by whonore** [comment]
> do you expect Coqtail will support the visual Ltac debugger any time soon? 

I hope so, I just need to find the time/motivation to play with it in CoqIDE a bit so I understand what it does and then look at the XML commands.

**Comment by jfehrle** [comment]
Let me know if you have questions when you get around to it.  I could demonstrate/explain it in a zoom session.

**Comment by jfehrle** [comment]
I wondered a bit about the use case:
1. Do users frequently have a large number of (admitted) goals?  Certainly individual goals/hypotheses can get _very_ large.
2. How does CoqTail use the number of goals without needing their values?  Is it routinely displaying the number of admitted goals?  I expect CoqTail always displays only the foreground goals.

**Comment by whonore** [comment]
1. The issue arises when the combined contexts of the unfocused, shelved, and admitted goals is large and the XML response to `Goal` explodes. So it could be many small ones or (more likely) a few large ones. I don’t have a specific example I can point to, but I have run into this in the wild a few times where I’m in the middle of a very large proof and every step starts having a noticeable delay. The initial case reported in #10623 came from working with Kami, which was producing lots of hypotheses with huge types. I imagine something like VST could have similar issues. 
2. Coqtail prints the number of unfocused, admitted, and shelved goals in addition the foreground goal. It also prints the conclusion of the next goal when the current one is complete.
