### ISSUE TITLE
`make world ; dune exec` recompiles stuff

### ISSUE THREAD

**Issue by gares** [coq/coq#16573]
I'm on master = fec24c7e6485cc18658929c24c3fa45bc7cdf773 and
```
make world
dune exec -- dev/shim/coqc-prelude test-suite/some/file.v
```
recompiles coqc.
@coq/build-maintainers Is this expected?

**Comment by gares** [comment]
Let me also add that it recompiles coqc, but not other files, eg:
```
 dune exec -- dev/shim/coqc-prelude test-suite/output/abstract_export_seff.v -async-proofs on
```
fails because of a mismatch, and only after
```
dune exec coqproofworker.opt
```
the former command works.

**Comment by Alizter** [comment]
The proof worker dependencies are not included in the shim. We could probably make a special shim with those deps included. What do you think @ejgallego

**Comment by gares** [comment]
So yes, then this issue is actually 2 issues:
- why does `world` not cover what `exec` needs
- missing dep of coqc on the workers (proof and tactic)

**Comment by gares** [comment]
> We could probably make a special shim with those deps included. What do you think @ejgallego?

Please, just add the deps to coqc, since coqc has a flag which requires them. It is just a few ml files...

**Comment by SkySkimmer** [comment]
Cannot reproduce. From clean state with cache disabled, `make world; echo HELLO; dune exec -- dev/shim/coqc-prelude test-suite/bugs/bug_12928.v -async-proofs on` says
~~~
(bla bla)
        coqc theories/Reals/.NewtonInt.aux,theories/Reals/NewtonInt.{glob,vo,vos}
        coqc theories/Reals/.Integration.aux,theories/Reals/Integration.{glob,vo,vos}
        coqc theories/Reals/.Reals.aux,theories/Reals/Reals.{glob,vo,vos}
        coqc theories/setoid_ring/.Rings_R.aux,theories/setoid_ring/Rings_R.{glob,vo,vos}
HELLO                                    
        bash dev/shim/coqc-prelude        
       chmod dev/shim/coqc-prelude     
~~~

**Comment by gares** [comment]
Well, I agree one cannot reproduce it from a clean start. But I did not dream, so I'll try to be more careful and see what I actually did to upset dune.

**Comment by ejgallego** [comment]
> The proof worker dependencies are not included in the shim. We could probably make a special shim with those deps included. What do you think @ejgallego?

Yes, they add some latency, but it is not too bad, maybe you can test in your laptop? If it is not too much we can even add them to the main build. Anyways I'm gonna try to optimize the binaries a bit more.

Regarding the main issue, without a build log, it is hard to do more.
