### ISSUE TITLE
CoqIDE feedback from Coq Community Survey 2022

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#16580]
There were a few questions about CoqIDE in the [Coq Community Survey 2022](https://coq.discourse.group/t/coq-community-survey-2022-results-part-i/1730). Here are the answers.

![CoqIDE satisfaction](https://thzimmer.gitlabpages.inria.fr/coq-survey-2022-assets/coqide-satisfaction-barplot.png)

![How long have you used CoqIDE?](https://thzimmer.gitlabpages.inria.fr/coq-survey-2022-assets/coqide-long-barplot.png)

![Do you use the template menu?](https://thzimmer.gitlabpages.inria.fr/coq-survey-2022-assets/coqide-template-barplot.png)

<summary>

Finally, there was one open text question "What improvements, bug fixes and new features would you most like to see in CoqIDE?" whose answers are:

<details>

1. Clean up of useless features. (template menu, make, etc).
Dune build support.
Performance improvements.

1. My feeling is that support for CoqIDE could be dropped if that would free up more manpower for VsCoq 

1. better help support and library support

1. A working dark mode (although it's been years since I used CoqIDE and perhaps one now exists).

1. I switched from CoqIDE to Proof General in 2013, since I did not manage to get Unicode input to work on CoqIDE back then. 

1. refactor tools or at least a find & replace in all open files

1. - Stop at the first error (like old versions of CoqIDE did).  Right now it tries to go to the end of the document, but it's actually difficult to locate the first error and move to it.  Just stop as soon as something is wrong.
   - Likewise, the "delay processing of some proofs until I click the gears icon" is not very useful and occasionally surprising.  I'd rather process proofs in order by default.

1. #13550

1. I think CoqIDE development time should just be spent on VsCoq. VsCode has so many features that would take a while to build out in CoqIDE. 

1. Proper text editor for GTK.

1. Allow selection of “view parentheses” from scripts, not menu (this used to be possible but was removed for some reason). Some kind of macro support for basic edits.

1. Enter queries Check, Print, etc in a separate buffer

1. I know how to use it but I do not use it that much - mostly when I need to do some couple-hour experiment on a Windows platform.

1. it seems fragile.
I don't care for the key bindings but haven't explored how to change them.

1. Unstable, issues with typeclass, outdated ?

1. support for opening and editing files other than *.v

1. Some colors aren't configurable, dark theme is not usable.

1. You support full Unicode in the main window, but every now and then when I write nonASCII character somewhere else (e.g. in Find/Replace dialog), CoqIDE just hangs and I lose everything I haven't saved. :-/
Also, when I run CoqIDE, I get the message "(coqide.exe:28008): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file 'C:\Coq\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache': No such file or directory

   This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > C:\Coq\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache
to make things work again for the time being."

   and I can't run that command (no file there).

1. It was crashing a lot (maybe it was coq)

1. The overall idea that to follow the proof you need to look at the proof state that is visualized when you 'step' in the right place is WRONG.
We need a proof language that is purposely verbose enough that we can understand the proof and how it work without the need of 'stepping' on the proof.
The proof source code should be sufficiently clear.
For example, tactiques could generate text that we had to cutpaste in our actual proof to make it work. In that way all the needed information could stay in the actual source code.

1. Automatic indentation

1. Consider implementing code autosaving and syntactic autocompletion.

1. 1. Code folding
   2. LaTeX support

1. More automation

1. I've got some issues to install CoqIDE on macos, so I moved to CoqTail that is a real improvement to me. CoqIDE is still my goto on a linux fresh install to get a quick start.

1. make easier entering unicode symbols
random freeze

1. it crashes regularly on macOS

1. A dark theme would be cool.

1. https://github.com/coq/coq/issues/14040

1. Launching CoqIDE on my Windows 10 machine fails, and makes the computer stuck for 1~2 minutes: huge delay in keyboard input, and Coq process staying in the system monitor.

1. It's not really usable on macOS so I'll refrain from commenting.

1. html-friendly proof visualization

   latex-style printing of equations

1. Better quality control for MS Windows - eg latest windows install package installs broken coqide

1. Don't crash on Windows (esp. with async-proofs on)!

1. I would like easy navigation as is available in emacs.  My productivity is much reduced in CoqIDE.  Probably just having a few of the basic functionalities of emacs, such as the same key bindings for the same commands would improve it significantly.

1. I wish for the the \mu-PG binding for Search to be C-c C-a C-s.  This is consistent with Proof General. 

1. Better scrolling (jump to error, find next often don't place right on the window)
More intuitive navigation (Ctrl-left and Ctrl-right are not inverses)

1. The colors cannot be changed and are quite difficult to see (on Linux Mint).

1. I don't really need/want a very fancy editor, and that's why I still use CoqIDE. There are some simple features that could be helpful:

   - File browser / easier way to open files (the open dialog is painful)
   - Terminal (so that I don't have to switch windows to run make)
   - Better search/replace

   Another reason why I always preferred CoqIDE over ProofGeneral is that in the same CoqIDE window, I can have Coq running on multiple buffers/files.

1. Basic IDE featers. Clickable identifiers, autocompletion, fuzzy search of lemmas. 

1. as decent as coqIDE is without a vim-like experience I don't plan to use it more. vscoq with its okay vim extension meets the minimum bar here, and trying to get a good proof assistent experience in Vim itself seems impossible, so I'm going to stick with vscoq.

1. Better display control for long goals: in case the goal does not fit in the windows, select which part is shown: top, bottom, start of the goal.

1. I would like not to lose the control on CoqIDE when I try to read a large chunck of Coq  code.

1. UTF8 support is broken, better notations, better default colors on all platforms

1. A cleaner/nicer UI would be great.

1. I have many ideas, but I'd like to hear what other users would like to see.

1. Performance!! In particular, an open bug from more than a year ago that has to do with labGTK.
I wish the performance of CoqIDE for simple things like typing and scrolling were comparable to those of modern editors.
In general, I feel like the IDE is important and requires more effort for Coq to be more usable and visible.
Personally, I prefer CoqIDE over all other alternatives.

1. Dark mode please

1. Use of multiple cores when interpreting to point or to the end.

1. - List of theorems/lemmas in currently open file, to easy navigate to
   - jump to definition

1. autocompletion sometimes feels sluggish / seems to eat keystrokes
other than that it's fine for what it is (it's not awesome, but I can't really point at concrete things to improve -- that's *way* better than most open source software by the way!)

1. - stability
   - tutorial how to configure GTK_IM_MODULE=uim (I've done it a few times and still don't remember)

1. Haven't really thought about these...

1. Better standard IDE features (indentation, highlighting, selection shortcuts, go to definition, etc.)

1. Vim bindings

1. I use CoqIDE only to show students who are in general not familiar with emacs.

1. No point : I only use coqide in teaching classes,not for myself  --> very basic use only.

1. I used CoqIDE during my first months learning Coq, then I switched to Emacs. The extra time spent learning basic Emacs pays off, because I do some actions more easily and I treat other files/languages from within the same editor.

1. Maybe syntax completion? I think CoqIDE had it at some point, but it either disappeared or I turned it off because it was shit.

1. Outdated, buggy, needs a rewrite.

1. As an easy improvement, working color schemes would be nice (dark color schemes have problems like issue #9611). As a more involved improvement, Vim emulation or at least proper mouseless navigation would be nice (current shortcut definitions lead to problems like issue #12170).

1. Top item: interact better with command-line builds using coqc. If I rebuild an imported file outside CoqIDE it would be great for it to notice and offer to reload, without losing my edit position. Also, it would be nice if trying to require a file that hasn't been built yet would pop it up in another CoqIDE window, and also in general for having multiple files open that interact with each other to work robustly. Right now (AFAIK anyway) if I have, say, one file full of module signatures and another with implementations, needing to change one of the signatures means opening that file in CoqIDE, building it there, adjusting interactively, saving, closing it, rebuilding in the command line, and then going back to the implementations. It would be nice to just be able to edit both files on the fly.

   Also (though I assume this is a gtksourceview problem) there's no way to reload a file that's open in CoqIDE but been changed behind its back, e.g. with a real editor or by rerunning some code generator.
</details>
</summary>

**Comment by SkySkimmer** [comment]
Not sure why this is an issue
