### ISSUE TITLE
Please JIT compile Ltac2 notations to avoid needless retyping

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16586]
#### Description of the problem

```coq
Require Import Coq.ZArith.ZArith.
Definition foo := Eval vm_compute in Z.div_eucl.
Require Import Ltac2.Ltac2.
Goal True.
  Time ltac1:(let v := (eval cbv delta [foo] in foo) in do 5 time do 100 (idtac; let _ := eval pattern v in v in idtac)).
  (* Tactic call ran for 0.276 secs (0.276u,0.s) (success)
Tactic call ran for 0.247 secs (0.247u,0.s) (success)
Tactic call ran for 0.222 secs (0.222u,0.s) (success)
Tactic call ran for 0.214 secs (0.214u,0.s) (success)
Tactic call ran for 0.234 secs (0.234u,0.s) (success)
Finished transaction in 1.199 secs (1.197u,0.002s) (successful)
 *)
  Time let v := (eval cbv delta [foo] in foo) in do 5 (time (do 100 (let _ := eval pattern $v in $v in ()))).
  (*
Tactic call ran for 0.214 secs (0.214u,0.s) (success)
Tactic call ran for 0.184 secs (0.184u,0.s) (success)
Tactic call ran for 0.26 secs (0.26u,0.s) (success)
Tactic call ran for 0.209 secs (0.209u,0.s) (success)
Tactic call ran for 0.223 secs (0.223u,0.s) (success)
Finished transaction in 1.096 secs (1.096u,0.s) (successful) *)
  Time let v := (eval cbv delta [foo] in foo) in do 5 (time (do 100 (let _ := Std.eval_pattern [(v, Std.AllOccurrences)] v in ()))).
  (*
Tactic call ran for 0.113 secs (0.113u,0.s) (success)
Tactic call ran for 0.094 secs (0.094u,0.s) (success)
Tactic call ran for 0.07 secs (0.07u,0.s) (success)
Tactic call ran for 0.073 secs (0.073u,0.s) (success)
Tactic call ran for 0.068 secs (0.068u,0.s) (success)
Finished transaction in 0.425 secs (0.425u,0.s) (successful)*)
```

I would really like to be able to write things like  `eval cbv beta delta [id] in $x` instead of `Std.eval_cbv { Std.rBeta := true; Std.rMatch := false; Std.rFix := false; Std.rCofix := false; Std.rZeta := false; Std.rDelta := false; Std.rConst := [reference:(id)] } x` and not have to worry about the performance cost.

#### Coq Version

8.15.0

**Comment by SkySkimmer** [comment]
How about writing `Ltac2 delta ids := { Std.rBeta := true; Std.rMatch := false; Std.rFix := false; Std.rCofix := false; Std.rZeta := false; Std.rDelta := false; Std.rConst := ids }.` once and then `Std.eval_cbv (delta [reference:(id)]) x`? or even write a notation for the delta flags if you don't like `reference:()`

**Comment by JasonGross** [comment]
My current solution is at https://github.com/mit-plv/rewriter/blob/447661334668ba1cc73753b294b306aa781e454e/src/Rewriter/Util/Tactics2/Notations.v#L4
```coq
Ltac2 Notation "strategy:(" s(strategy) ")" := s.
```
and then I can write `Std.eval_cbv (strategy:(delta [id])) x`.  It's still a bit verbose, though, and I'm not sure how to do a similar thing for `pattern`
https://github.com/coq/coq/blob/477c5aac7a92134de0c5660f9b9b71fcd06ed0e8/user-contrib/Ltac2/Notations.v#L423-L424
I guess I can write
```coq
Ltac2 Notation "occurrences:(" s(occurrences) ")" := s.
```
but `occurrences:()` isn't much better than `Std.AllOccurrences`...

**Comment by JasonGross** [comment]
But my point is that Ltac2 notations seem basically incompatible with performant code, and this seems like a straightforward fix that would help a lot in many cases (if perhaps not an easy fix)

**Comment by SkySkimmer** [comment]
Can't you just copy that notation, change the name a bit so it doesn't conflict and change constr to tactic?

**Comment by JasonGross** [comment]
Ah, yes, this would work well.  (And is also what @Janno suggested [here](https://coq.zulipchat.com/#narrow/stream/278935-Ltac2/topic/Performance.20worse.20than.20Ltac1/near/301691021), though I didn't understand it at the time.)  Why do these tactic notations default to `constr` while `lazy_match!` and `match!` default to `tactic`?  It seems like the better default version to have is the one that uses `tactic`.  (Also, why change the name rather than just shadowing the notation?)

**Comment by SkySkimmer** [comment]
You can shadow if you want
