### ISSUE TITLE
Bug? Should the rename tactic also update names in the proof term?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#16590]
Some users look at proof terms.  They may find the inconsistent names after using `rename` confusing.  Should we eventually fix this?  Is this technically difficult for some reason?

![image](https://user-images.githubusercontent.com/1253341/193377744-f326f04c-eb58-46b0-b07d-e8bc839171b0.png)

**Comment by ppedrot** [comment]
What does it even mean? We're talking about bound variables that can appear elsewhere in the term.

**Comment by Zimmi48** [comment]
So not technically feasible to fix then. Thanks for the answer!
