### ISSUE TITLE
"Proof Mode" should complain about an unknown proof mode just like "Set Default Proof Mode"

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#16602]
```
Fail Set Default Proof Mode "foo".

Goal True.
Fail Proof Mode "foo". (* The command has not failed! *)
```

**Comment by jfehrle** [comment]
My pleasure, thanks for letting me know.  The 8.17 documentation includes `Proof Mode` (from #16498) and it will be in the index.  8.17 will list almost all commands and tactics except for a number of SSR-specific items.  Some are not described and may never be.  No point in waiting for bug fixes, hence this issue.  (FWIW, `Default Proof Mode` is in Basic Proof Writing/Proof mode/Proof Modes, not the Ltac2 chapter.)

**Comment by jfehrle** [comment]
Much quicker to fix it than to document it.

In the words of the inimitable [H Ross Perot](https://en.wikipedia.org/wiki/Ross_Perot), billionaire third-party Presidential candidate in 1992 who made Bill Clinton the winner: "If you see a snake, just kill it - don't appoint a committee on snakes."  :smiley:

**Comment by Zimmi48** [comment]
That was before the global recognition of the biodiversity crisis I guess :laughing:
