### ISSUE TITLE
Bench script reports incorrect line numbers in some cases

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16633]
The line number in the bench report is wrong (cc @Alizter ?).  Line 78 is https://github.com/mit-plv/rewriter/blob/1d2dc36216ad110dcf49cf7ed2a05d2bbdd7546c/src/Rewriter/Rewriter/Examples/PerfTesting/SieveOfEratosthenes.v#L78
```coq
Notation extra_idents := (Z.eqb, orb, Z.gtb, PositiveSet.elements, @fst, @snd, PositiveSet.mem, Pos.succ, PositiveSet.add, List.fold_right, List.map, List.seq, Pos.mul, S, Pos.of_nat, Z.to_nat, Z.div, Z.pos, O, PositiveSet.empty) (only parsing).
```
and there's no way this is taking 15--30 seconds.  The correct line number is 80:
```coq
Time Make myrew := Rewriter For lemmas (with extra idents extra_idents) (with delta).
```
(And this file hasn't changed for over a year, so it's not that the numbers are off because the file changed underneath the bench runner.). Maybe the `Time` is messing things up???

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/16627#issuecomment-1273940263_

**Comment by Alizter** [comment]
@JasonGross The bench script just reads the line number as reported in the HTML timing file. Here is the relevant one: 
https://coq.gitlab.io/-/coq/-/jobs/3145546937/artifacts/_bench/html/coq-rewriter/src/Rewriter/Rewriter/Examples/PerfTesting/SieveOfEratosthenes.v.html

Looks like there might be two bugs. First he reported line number is offset (by 2) and second the highlighting is offset (by 1). I believe there is a timing python script that generates these HTML files right?

**Comment by JasonGross** [comment]
I think it's an OCaml script not a python script (original to math-comp maybe?).  My guess is that the `Time` is messing up the output of `coqc -time`, but I haven't looked into it

**Comment by SkySkimmer** [comment]
Line numbers are wrong from the 2nd line so it's not Time

**Comment by SkySkimmer** [comment]
Fixed in https://github.com/coq/coq/pull/17411
