### ISSUE TITLE
Outdated documentation on tactics/tacticals.mli

### ISSUE THREAD

**Issue by ckeller** [coq/coq#16637]
#### Description of the problem
The ocamldoc documentation in tactics/tacticals.mli still refers to `Tacticals.New`, which does not exist anymore.
Similarly, the documentation about deprecated features in proofs/tacmach.mli also refers to `New`.

#### Coq Version
Coq-8.15 and Coq-8.16

**Comment by Alizter** [comment]
cc @coq/tactics-maintainers

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/16638
