### ISSUE TITLE
coqdep doesn't recognize import_categories

### ISSUE THREAD

**Issue by Kaptch** [coq/coq#16673]
#### Description of the problem

import_categories feature works perfectly fine in coqtop, but produces an error message while using coqdep.

Example:
```
echo "Require Import -(notations) stdpp.base." > test.v
coqdep -R . Top ./test.v
```

Error message:
`*** Error: File "test.v",characters 15-16: Syntax error`

#### Coq Version

The Coq Proof Assistant, version 8.16.0
compiled with OCaml 4.12.1

Operating system:
Linux, NixOS

**Comment by SkySkimmer** [comment]
I guess https://github.com/coq/coq/commit/22fe0b06669c80f75032f6d509814534b7b5f525 missed the negated categories case

**Comment by Kaptch** [comment]
Thanks! I've opened a small pr #16676 for the related lines.
