### ISSUE TITLE
`par` should plausibly fall back to single-threaded behavior rather than raising Anomaly "Uncaught exception Failure("The spawned process did not connect back in 10.0s")."

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16698]
#### Description of the problem

```
# Usage: coqworker.opt --kind=[proof|query|tactic] $args
# got -main-channel
# File ".\src/Curves/Edwards/XYZT/Basic.v", line 124, characters 6-336:
# Error:
# Anomaly
# "Uncaught exception Failure("The spawned process did not connect back in 10.0s")."
# Please report at [http://coq.inria.fr/bugs/.](http://coq.inria.fr/bugs/)
# 
# make: *** [Makefile.coq:793: src/Curves/Edwards/XYZT/Basic.vo] Error 129
```
https://github.com/mit-plv/fiat-crypto/actions/runs/3281473086/jobs/5403532417#step:17:1812

_Originally posted by @andres-erbsen in https://github.com/mit-plv/fiat-crypto/issues/1394#issuecomment-1284232309_

(This is a transient error on Windows, idk if that's relevant)

#### Coq Version

8.17+alpha / dev (d1e1d3291d34c8eefdec13152434d4238cfb4e19)

**Comment by Alizter** [comment]
@ejgallego Is this because of the merge?

**Comment by ejgallego** [comment]
I don't know, likely not due to the nature of the error "transient on windows"

**Comment by JasonGross** [comment]
It's plausible that I'm wrong about it being a transient issue, and instead it's a recent Windows-only issue

**Comment by JasonGross** [comment]
Correction: this is not a transient issue.  `par` is no longer usable on Windows.  I'll open a new issue for the "par is broken" rather than "par should be more robust" bit, though.

**Comment by SkySkimmer** [comment]
I don't think this is especially useful and propose we close.
