### ISSUE TITLE
Adding a try block in a GTK callback fails

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#16701]
If I add `try () with _ -> ();` in a CoqIDE callback such as `Coqide.newfile` (the callback for clicking the File/New menu item),  the code following that line is not executed.  Based on other experiments, it appears that body of the try block is executed and the failure is in processing of the `with`.

My first guess is that the call stack isn't set up properly for the `try`.  (The calling GTK code is written in C.)  But it could be something else entirely.  I see this in both Windows and Linux executables.

Ouch.  I was not expecting this at all.

@herbelin @ppedrot @ejgallego Any thoughts?

**Comment by Alizter** [comment]
Its a bracketing problem. Try `(try () with _ -> ());`.

**Comment by jfehrle** [comment]
Your right, thanks.  I hate OCaml syntax.

**Comment by Alizter** [comment]
I've heard this issue described as a right-of-passage for OCaml devs. :-)

**Comment by jfehrle** [comment]
But it's so counter-intuitive that I stumble into repeating it periodically :-(.

**Comment by herbelin** [comment]
Some people argued for a [revised syntax](https://camlp5.github.io/doc/htmlc/revsynt.html) but it is certainly too late now...

**Comment by jfehrle** [comment]
I think issuing warnings when indentation doesn't match structure would do the trick, akin to Python.  I proposed that [here](https://discuss.ocaml.org/t/enhancement-request-a-warning-to-flag-misleading-indentation/8311) but the mob grossly underappreciated my proposal.
