### ISSUE TITLE
`par:` no longer works on Windows

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16709]
Correction: this is not a transient issue.  `par` is no longer usable on Windows.  I'll open a new issue for the "par is broken" rather than "par should be more robust" bit, though.

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/16698#issuecomment-1286259848_

#### Description of the problem

```
# Usage: coqworker.opt --kind=[proof|query|tactic] $args
# got -main-channel
# File ".\src/Curves/Edwards/XYZT/Basic.v", line 124, characters 6-336:
# Error:
# Anomaly
# "Uncaught exception Failure("The spawned process did not connect back in 10.0s")."
# Please report at [http://coq.inria.fr/bugs/.](http://coq.inria.fr/bugs/)
# 
# make: *** [Makefile.coq:793: src/Curves/Edwards/XYZT/Basic.vo] Error 129
```
https://github.com/mit-plv/fiat-crypto/actions/runs/3281473086/jobs/5403532417#step:17:1812

_Originally posted by @andres-erbsen in https://github.com/mit-plv/fiat-crypto/issues/1394#issuecomment-1284232309_

#### Coq Version

8.17+alpha / dev (d1e1d3291d34c8eefdec13152434d4238cfb4e19)

**Comment by SkySkimmer** [comment]
Please test https://github.com/coq/coq/pull/16711

**Comment by JasonGross** [comment]
> Please test #16711

This is a bit tricky for me, my windows box only builds Coq through wsl and the Fiat Crypto windows CI is opam based.  Is there a way to hack the Windows CI on that PR to also run (the equivalent of) `opam install coq-fiat-crypto.dev`?

**Comment by JasonGross** [comment]
Also, thank you!

**Comment by JasonGross** [comment]
#16711 improved things but was not enough, now we get
```
# Usage: coqworker.opt --kind=[proof|query|tactic] $args
# got -control-channel
# File ".\src/Curves/Edwards/XYZT/Basic.v", line 124, characters 6-336:
# Error:
# Anomaly
# "Uncaught exception Failure("The spawned process did not connect back in 10.0s")."
# Please report at [http://coq.inria.fr/bugs/.](http://coq.inria.fr/bugs/)
```

**Comment by JasonGross** [comment]
Looks like maybe you need to make the same change at
https://github.com/coq/coq/blob/bdeac27a428fb842bdf69d9082a8794ee150e6f4/lib/spawn.ml#L132-L133
?
