### ISSUE TITLE
Bench script sets too low a stack limit

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16702]
[Benching fiat-crypto-with-bedrock2 is] failing because the hard stack limit is less than 32768.  That this causes us to fail is a bug that I'll look into, but I think the bench shouldn't be so stingy with stack.

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/16697#issuecomment-1284770565_

**Comment by SkySkimmer** [comment]
I think 32k is already pretty high.

**Comment by JasonGross** [comment]
The limit currently is set to 16k.  Fiat Crypto requests 32k, because that's what's required by ocamlopt + flambda to compile big PHOASTs.  But what's the reason for setting the hard limit so low?  It seems fine to set the soft limit low, and let individual scripts set more if they need it.  Unless you're worried about adversarial packages on the bench?

**Comment by SkySkimmer** [comment]
Setting the hard limit was an oversight
see also https://github.com/coq/coq/pull/16695

**Comment by JasonGross** [comment]
Ah, I missed that

**Comment by JasonGross** [comment]
Fixed by https://github.com/coq/coq/pull/16695
