### ISSUE TITLE
Tactic failure with ssreflect when the goal is solvable by "apply _"

### ISSUE THREAD

**Issue by rlepigre** [coq/coq#16720]
#### Description of the problem

See the following example.
```coq
From Coq.Classes Require Import DecidableClass.
From Coq Require Import ssreflect ssrfun ssrbool.

Goal True.
Proof.
  (* Works as expected. *)
  Fail Fail have P_iff : (forall n, n = 0 <-> 0 = n).
Abort.

Goal forall (x y : bool), Decidable (eq x y).
Proof.
  Fail Fail apply _.
  (* Fails with: "Error: Tactic failure: Incorrect number of goals (expected 0 tactics)." *)
  Fail have P_iff : (forall n, n = 0 <-> 0 = n).
Abort.
```

This was further minimized by @Janno, to obtain the following (he is also currently bisecting).
```coq
From Coq Require Import ssreflect.
Class Trivial := trivial {}.
#[local] Existing Instance trivial.
Goal Trivial.
  Succeed assert True.
  Fail have: True.
Abort.
```

#### Coq Version

This fails on version 8.16.0, but used to work correctly in 8.15.1.

**Comment by Blaisorblade** [comment]
Oh, I ran into this too in a personal project — https://github.com/Blaisorblade/dot-iris/pull/419/commits/84dc39af6df0c81405576ba508866e5b083f9486.

That code also has a real example where `apply _` succeeds, but gives the wrong proof: mutually recursive instances.

**Comment by gares** [comment]
thanks for reporting

**Comment by gares** [comment]
I pushed a fix, let's see the mood of CI
