### ISSUE TITLE
findlib "... has multiple definitions" message in "make ci-equations" 

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#16751]
How do I know which one is used?  Developers should be able to do a clean compile even if there's an opam version of Coq installed, right?  If findlib picks the wrong one, what's the workaround?

```
CAMLOPT -c  src/principles.ml
findlib: [WARNING] Package coq-core has multiple definitions in
 /home/proj/coq2/_build/install/default/lib/coq-core/META,
 /home/jfehrle/.opam/__coq-platform.2022.01.0~8.15~beta1/lib/coq-core/META
```

**Comment by SkySkimmer** [comment]
Ask this sort of thing on zulip
