### ISSUE TITLE
Sphinx Documentation incorrectly renders `/\` as `/\\` and `\/` as `\\/`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16761]
@_**Anders Larsson|473655** [said](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/.E2.9C.94.20.2F.5C.5C.20typo.20or.20real.20syntax.3F/near/306516889):

Are the /\\\\ and \\\\/ operators real or just a typo?
 
![image](https://user-images.githubusercontent.com/396076/199136524-0fec892a-db5a-403b-9edf-01adcce09dfd.png)

From:
https://coq.inria.fr/distrib/current/refman/addendum/micromega.html#coq:flag.Nra-Cache

But here the operators looks normal:
https://coq.github.io/doc/V8.11.0/refman/addendum/micromega.html#coq:flag.nra-cache

cc @coq/doc-maintainers

**Comment by Alizter** [comment]
This has been solved in master.
