### ISSUE TITLE
`rewrite` fails when dealing with type aliases and polymorphic functions

### ISSUE THREAD

**Issue by tperami** [coq/coq#16786]
#### Description of the problem

If I have a type alias and a polymorphic function in the same context `rewrite` fails unexpectedly. This is a minimal example to show the problem:

```
  Definition nat2 := nat.
  Hypothesis f : forall {T}, T -> T.
  Parameter P : nat -> nat -> Prop.
  Hypothesis fP : forall a b : nat, f a = f b -> P a b.

  Lemma test2 (b : nat2) (a : nat) : f b = f a  -> P a b.
    intro H.
    apply fP.
    rewrite H. (* <-- fails *)
    reflexivity.
    Qed.
```
At the point of the message, the error is: `Error: Found no subterm matching "f b" in the current goal.`
and the context is:
```
  b : nat2
  a : nat
  H : f b = f a
  ============================
  f a = f b
```

At first glance I was very confused about how rewrite cannot find `f b`. In particular because `setoid_rewrite` has no problem doing it: replacing `rewrite H` by `setoid_rewrite H` makes the proof go smoothly.

It took me 3 hours of debugging to make up this minimal example, and now I think it is because `rewrite` is unable to unify `nat2` and `nat` when search for term to rewrite. Here is it try to rewrite `f nat2 b` but the instance in the goal is silently `f nat b` because it was created by apply `fP`. As a side remark this works:
 
```
Lemma test2 (b : nat2) (a : nat) : f b = f a  -> P a b.
  intro H.
  apply fP.
  assert (f a = f b). (* looks exactly the same as the actual goal *)
  - rewrite H. (* succeeds *)
    reflexivity.
  - assumption. (* and assumption agrees that the final goal and the asserted goal are the same up to unification*)
  Qed.
```

For me there is definitely a usability problem if typing itself is smarter than rewrite, both case of `f b` need the typing to change `nat2` in `nat` implicitly at some point, but if it's at a different point, then rewrite is unable to identify both terms. At least rewrite should have an error message that makes it clear what's happening instead of printing that it can't find a term that is obviously there.

#### Coq Version

I tested on both 8.14.0 and 8.16.0 and rewrite fails on both

**Comment by ppedrot** [comment]
You have hidden implicit arguments in the application of `f`. The rewrite lemma is not syntactically equal to the goal, hence the failure. By contrast, setoid_rewrite uses a more aggressive (but much slower) algorithm to find patterns, as it performs arbitrary conversion on closed terms.

**Comment by herbelin** [comment]
There is an option `Set Keyed Unification` which changes `rewrite` so that it uses more conversion on inner subterms (I don't know the full details though). Personally, I recommend to use it as it generally produces more intuitive results. (In the longer term, a technical work on providing an ideal `rewrite` combining what the various forms do in isolation should be done.)
```
Set Keyed Unification.
Definition nat2 := nat.
Hypothesis f : forall {T}, T -> T.
Parameter P : nat -> nat -> Prop.
Hypothesis fP : forall a b : nat, f a = f b -> P a b.

Lemma test2 (b : nat2) (a : nat) : f b = f a  -> P a b.
  intro H.
  apply fP.
  rewrite H. (* <-- works *)
  reflexivity.
  Qed.
```

**Comment by JasonGross** [comment]
I expect you can fix this with something like `Set Keyed Unification. Declare Equivalent Keys nat nat2.`. You might not even need the second command.

> For me there is definitely a usability problem if typing itself is smarter than rewrite

The trade-off here is that making rewrite smarter makes it unpredictably slower.

> At least rewrite should have an error message that makes it clear what's happening instead of printing that it can't find a term that is obviously there.

This I agree with.  I think the ideal behavior here is something like "if there's a subterm of the goal that prints the same as the pattern, rewrite should explain why it doesn't match".  This is potentially expensive, so plausibly it should only be computed when printing the error message at top level, and not when backtracking over the rewrite.  Alternatively, it might be enough to keep a list of subterms that match the head constant but not the rest of the (especially when using Keyed Unification).

Also, perhaps the error message for rewrite should suggest something like "If you think the subterm is present in the goal, try turning on Set Keyed Unification." when it's not on?

**Comment by tperami** [comment]
I did not know about `Set Keyed Unification`, maybe it should be mentioned in the error message when rewrite fails with an identical term as one that exists in the subgoal.
Weirdly, `Set Keyed Unification` does not seem to be transmitted when importing a module: If it set in a module it is not set in modules that import it. 
Other than that it more or less solved this problem. You do not need `Declare Equivalent Keys nat nat2` because as far as I understand it the key is `f` not `nat` or `nat2`

**Comment by herbelin** [comment]
> Weirdly, `Set Keyed Unification` does not seem to be transmitted when importing a module: If it set in a module it is not set in modules that import it.

If my reading of the [reference manual](https://coq.inria.fr/refman/language/core/modules.html#controlling-the-scope-of-commands-with-locality-attributes) is correct, the `#[export]` attribute would have an effect in this case.

**Comment by tperami** [comment]
Oh interesting, I didn't know that those attributes applied to `Set` commands.

**Comment by tperami** [comment]
Should this issue stay open as a tracker for improving rewrite error messages in this case, or do you want to close it?
