### ISSUE TITLE
Output notation not accepted as input

### ISSUE THREAD

**Issue by SnarkBoojum** [coq/coq#16785]
Following this Zulip discussion: https://coq.zulipchat.com/#narrow/stream/237664-math-comp-users/topic/.E2.9C.94.20Output.20not.20accepted.20as.20input

```
Require Import ssrbool.

Section Bug.

Variables a b c: bool.

Check a ==> b ==> c. (* gets displayed as [==> a, b => c] : bool -- no space!*)
Check [ ==> a, b => c]. (* is accepted, but note the space *)
Check [==> a, b => c]. (** without the space, as output: syntax error *)

End Bug.
```

It's probably a missing space somewhere in the output, since obviously the notation can work.

**Comment by proux01** [comment]
If you want to add a space in the output, I guess it's just a matter of adding a second space between `[` and `=>` there https://github.com/coq/coq/blob/1c739a0ddce17bda4198a5f988056019745213ca/theories/ssr/ssrbool.v#L465-L466 (I let you try). But I'm not sure that would be the preferred fix (there are no spaces for the similar notations for `/\`, `\/`, `&&` and `||`).

**Comment by SnarkBoojum** [comment]
Notice that:
```
Check [|| a, b | c ].
Check [ || a, b | c ].
```
both work... and even:
```
Check a || b || c || a || b || c.
```
doesn't trigger the use of those notations, so it's only for the implication that something unexpected and unwelcome happens.

**Comment by SnarkBoojum** [comment]
Comparing what's done for `&&`, `||`, `/\` and `\/` on the one hand and what's done for `==>` on the other hand, I see that in the first list, the notation for `[ op P1 op P2 ]` is defined first and then the other notations (hence a `only parsing` notation comes first), while for implication, it comes last.

Might this explain the issue?

**Comment by proux01** [comment]
> Notice that:
> 
> ```
> Check [|| a, b | c ].
> Check [ || a, b | c ].
> ```
> 
> both work...

Yes and I think we should expect the same with `==>`.

> and even:
> 
> ```
> Check a || b || c || a || b || c.
> ```
> 
> doesn't trigger the use of those notations,

That's expected due to associativity:

```Coq
a || b || c
```
is parsed as
```Coq
(a || b) || c
```
whereas
```Coq
a ==> b ==> c
```
is (as expected) parsed as
```Coq
a ==> (b ==> c)
```
(just try `Check a || (b || c).`)

> so it's only for the implication that something unexpected and unwelcome happens.

I agree, there seems to be some parsing issue, but no idea why.

**Comment by proux01** [comment]
> Comparing what's done for `&&`, `||`, `/\` and `\/` on the one hand and what's done for `==>` on the other hand, I see that in the first list, the notation for `[ op P1 op P2 ]` is defined first and then the other notations (hence a `only parsing` notation comes first), while for implication, it comes last.
> 
> Might this explain the issue?

You can try to permute them and see what happens. I doubt so however since, in term of parsing, everything should be in the `Reserved Notation` command (in Coq, the parsing is performed before giving an interpretation to the notation, the parser is modified by the `Reserved Notation` command, then the `Notation` only gives a meaning to the already parsed notation (where it becomes tricky is when both command are merged in a single `Notation` defining both parsing and interpretation rules (but we try to avoid that in mathcomp))).

**Comment by JasonGross** [comment]
Is there another reserved notation somewhere that starts with `[=` (without a space)?

**Comment by proux01** [comment]
No but there is the `[=]` intro pattern in Ltac (don't remember what that means, there is no such thing in ssreflect), that might be the explanation.

**Comment by JasonGross** [comment]
```
$ git grep '\[=' '*.mlg'
plugins/ltac/extratactics.mlg:  (* For the "as [= pat1 ... patn ]" syntax *)
plugins/ltac/extratactics.mlg:  (* To be sure that there is no confusion of syntax, we check that no [= ...] occurs
plugins/ltac/g_tactic.mlg:      | "[="; tc = intropatterns; "]" -> { IntroInjection tc } ] ]
plugins/ltac2/g_ltac2.mlg:      | "[="; tc = intropatterns; "]" -> { CAst.make ~loc @@ QIntroInjection tc } ] ]
plugins/ssr/ssrparser.mlg:   | test_nohidden; "[="; iorpat = ssriorpat; "]" -> {
jgross@JasonGross-X1:~/Documents/repos/coq$
```

**Comment by JasonGross** [comment]
Presumably these tokens need to be split into `"["; "="`?

**Comment by herbelin** [comment]
> No but there is the `[=]` intro pattern in Ltac (don't remember what that means, there is no such thing in ssreflect), that might be the explanation.

This is the injection pattern, whose syntax is different in ssreflect.

> Presumably these tokens need to be split into "["; "="?

That can be tried, but then, using a `check_no_space` to ensure they remain glued together at parsing time (see the example of `test_minus_nat` in `g_prim.mlg`).
