### ISSUE TITLE
CoqIDE does not save preferences on macOS

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#16814]
#### Description of the problem

on macOS Monterey (likely also on other versions), CoqIDE does not save the preferences any more. 

#### Coq Version

This is with "CoqIDE, version 8.16.0" including the [two patches in Coq Platform](https://github.com/coq/platform/tree/main/opam/opam-repository/packages/coqide/coqide.8.16.0/files):

**Comment by Zimmi48** [comment]
As discussed in https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/CoqIDE.3A.20store.20preferences.20does.20not.20work.20on.20Mac, it would be good to determine if it did work in older Coq versions with a fixed pango (https://gitlab.gnome.org/GNOME/pango/-/merge_requests/644) so that the preference menu doesn't make CoqIDE crash. This would help understand if this is a problem with newer versions of Coq or with newer versions of macOS. (My suspicion being that this is the latter.)

**Comment by MSoegtropIMC** [comment]
I fully agree. Just right now I don't have the time to do such tests myself.

**Comment by herbelin** [comment]
Saving preferences for CoqIDE master seems to work for me on Monterey (with #16581 fix for #16136), at least for the preference I tested (activation of µPG mode).

**Comment by MSoegtropIMC** [comment]
Okay, let me retest. I changed the font size and the modifier mapping for the navaigation keys - neither of which was saved.

Possibly I have some old settings files sitting around ...

**Comment by herbelin** [comment]
Both are saved for me (with 8.16 branch 97b52ad compiled locally). Configuration files are stored for me in `~/.config/coq/`.

If needed, I can test with the platform too.

**Comment by MSoegtropIMC** [comment]
@herbelin : the issue is that the `~/.config` folder is not created. If it exists, the `~/.config/coq` folder is created - otherwise not. On a plain new macOS a `~/.config` folder does not exist. If I manually create a `~/.config` folder, saving preferences does work.

I think the file location changed recently. Afair not that much in the past the files where saved somewhere under `~/Library`.

**Comment by herbelin** [comment]
Then, `Unix.mkdir` in `save_accel_pref` and `save_rc_pref` of `ide/coqide/preferences.ml` should be replaced by a recursive mkdir (or maybe return an error if the containing directory does not exist).

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : Maybe I also have time to test a local pango build, but this issue should be independent.

**Comment by Zimmi48** [comment]
>Maybe I also have time to test a local pango build, but this issue should be independent.

It's not so important now that the issue has been pinpointed.

**Comment by herbelin** [comment]
> @herbelin : are you doing a fix? Since the Coq Platform Mac CI is working again, I could probably also find the time to do it.

I did nothing yet so if you have time, don't hesitate.
