### ISSUE TITLE
coq no longer builds on old gcc

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#16830]
#### Description of the problem

It seems that #14519 broke the build of the VM on Ubuntu 14.04 with gcc ... 4.8.4?  (I can't quite tell if it's 4.8 or 4.9).  The full log is [here](https://launchpadlibrarian.net/634145272/buildlog_ubuntu-trusty-amd64.coq_8.master~git~202211171519+23634-0~daily385-e043c3e206~ubuntu14.04.1_BUILDING.txt.gz)

```
$ (cd _build/default/kernel/byterun && /usr/bin/x86_64-linux-gnu-gcc -fPIC -Wall -Wno-unused -g -O2 -msse2 -mfpmath=sse -g -I /usr/lib/ocaml -o coq_interp.o -c coq_interp.c)
In file included from coq_interp.c:51:0:
coq_uint63_native.h: In function ‘uint63_div21_aux’:
coq_uint63_native.h:145:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 63; ++i) {
   ^
coq_uint63_native.h:145:3: note: use option -std=c99 or -std=gnu99 to compile your code
```

cc @ejgallego as author of #14519

#### Coq Version

e043c3e206

**Comment by ejgallego** [comment]
That PR removed flags `-fno-strict-aliasing -fwrapv -pthread -D_FILE_OFFSET_BITS=64`, AFAICT it was on purpose, but maybe we need to add some?

**Comment by JasonGross** [comment]
Maybe one of those flags forces C99 or something? 
 Previous succeeding build log of a7ec416def [here](https://launchpadlibrarian.net/633958049/buildlog_ubuntu-trusty-amd64.coq_8.master~git~202211161519+23628-0~daily385-a7ec416def~ubuntu14.04.1_BUILDING.txt.gz), FWIW

**Comment by JasonGross** [comment]
If I'm reading [the doc](https://dune.readthedocs.io/en/stable/dune-files.html#use-standard-c-and-cxx-flags) correctly, previously it picked up flags from `ocamlc -config`.  Maybe OCaml was previously passing std=C99 on old gcc or something?

**Comment by JasonGross** [comment]
Does anything go wrong if we add some explicit `-std` flag?  (c99, gnu99, c11, gnu11, or w/e)?

**Comment by JasonGross** [comment]
I see on the successful build:
```
ocaml_config =
     { version = "4.11.1"
     ; standard_library_default = "/usr/lib/ocaml"
     ; standard_library = "/usr/lib/ocaml"
     ; standard_runtime = "the_standard_runtime_variable_was_deleted"
     ; ccomp_type = "cc"
     ; c_compiler = "x86_64-linux-gnu-gcc"
     ; ocamlc_cflags =
         [ "-std=gnu99"
         ; "-O2"
         ; "-fno-strict-aliasing"
         ; "-fwrapv"
         ; "-fno-builtin-memcmp"
         ; "-fPIC"
         ]
     ; ocamlc_cppflags = [ "-D_FILE_OFFSET_BITS=64"; "-D_REENTRANT" ]
     ; ocamlopt_cflags =
         [ "-std=gnu99"
         ; "-O2"
         ; "-fno-strict-aliasing"
         ; "-fwrapv"
         ; "-fno-builtin-memcmp"
         ; "-fPIC"
         ]
     ; ocamlopt_cppflags = [ "-D_FILE_OFFSET_BITS=64"; "-D_REENTRANT" ]
     ; bytecomp_c_compiler =
         [ "x86_64-linux-gnu-gcc"
         ; "-std=gnu99"
         ; "-O2"
         ; "-fno-strict-aliasing"
         ; "-fwrapv"
         ; "-fno-builtin-memcmp"
         ; "-fPIC"
         ; "-D_FILE_OFFSET_BITS=64"
         ; "-D_REENTRANT"
         ]
     ; bytecomp_c_libraries = [ "-lm"; "-ldl"; "-lpthread" ]
     ; native_c_compiler =
         [ "x86_64-linux-gnu-gcc"
         ; "-std=gnu99"
         ; "-O2"
         ; "-fno-strict-aliasing"
         ; "-fwrapv"
         ; "-fno-builtin-memcmp"
         ; "-fPIC"
         ; "-D_FILE_OFFSET_BITS=64"
         ; "-D_REENTRANT"
         ]
     ; native_c_libraries = [ "-lm"; "-ldl" ]
     ; cc_profile = []
     ; architecture = "amd64"
     ; model = "default"
     ; int_size = 63
     ; word_size = 64
     ; system = "linux"
     ; asm = [ "x86_64-linux-gnu-as" ]
     ; asm_cfi_supported = true
     ; with_frame_pointers = false
     ; ext_exe = ""
     ; ext_obj = ".o"
     ; ext_asm = ".s"
     ; ext_lib = ".a"
     ; ext_dll = ".so"
     ; os_type = "Unix"
     ; default_executable_name = "a.out"
     ; systhread_supported = true
     ; host = "x86_64-pc-linux-gnu"
     ; target = "x86_64-pc-linux-gnu"
     ; profiling = false
     ; flambda = false
     ; spacetime = false
     ; safe_string = true
     ; exec_magic_number = "Caml1999X028"
     ; cmi_magic_number = "Caml1999I028"
     ; cmo_magic_number = "Caml1999O028"
     ; cma_magic_number = "Caml1999A028"
     ; cmx_magic_number = "Caml1999Y028"
     ; cmxa_magic_number = "Caml1999Z028"
     ; ast_impl_magic_number = "Caml1999M028"
     ; ast_intf_magic_number = "Caml1999N028"
     ; cmxs_magic_number = "Caml1999D028"
     ; cmt_magic_number = "Caml1999T028"
     ; natdynlink_supported = true
     ; supports_shared_libraries = true
     ; windows_unicode = false
     }
 }
```

**Comment by JasonGross** [comment]
So maybe you want to add back some subset of `-std=gnu99 -O2 -fno-builtin-memcmp -fPIC -D_REENTRANT`?  But definitely at least `-std=gnu99`.  Also, did you bench that PR to see if removing `-O2` (or am I misreading?) changed performance?

**Comment by ejgallego** [comment]
Yup, happy to add the flags the vm maintainers would think work best, cc @silene

**Comment by silene** [comment]
Yes, we should pass `-std=gnu99` for GCC 4. For GCC 5 and later (and for non-GNU compilers), this is a poor idea though.

**Comment by JasonGross** [comment]
Is there a way to tell dune to pass the standard flags except the ones we want to exclude, rather than the other way around?  It seems there's useful compiler-specific logic

**Comment by ejgallego** [comment]
> Is there a way to tell dune to pass the standard flags except the ones we want to exclude, rather than the other way around? It seems there's useful compiler-specific logic

Yup, than can be done with `(:standard \ flag_to_remove1 flag_to_remove2)`
