### ISSUE TITLE
Anomaly creating definition for array literal

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#16832]
#### Description of the problem

```coq
Require Import PArray Uint63.
Check [| [| | 0x0 |] | [| | 0x0 |] : array int |]%uint63.
Definition x := [| [| | 0x0 |] | [| | 0x0 |] : array int |]%uint63.
(*
Anomaly "Uncaught exception Invalid_argument("index out of bounds")."
Please report at http://coq.inria.fr/bugs/.
*)
```

Found while minimizing https://github.com/coq/coq/issues/16829

#### Coq Version

8.16.0

**Comment by SkySkimmer** [comment]
In fact any empty array literal, eg `Definition foo := [| | 0 |].`
https://github.com/coq/coq/blob/e043c3e206f1f64303508e89b3501aade7f58a06/kernel/vmbytegen.ml#L759 gets a Lmakeblock with 0 args but comp_args assumes nonempty args
