### ISSUE TITLE
Are `hresolve_core` and `hget_evar` still useful?

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#16846]
`resolve_core` and `hget_evar` were added in 028cbb32785b559c637f77864ce5172e0255d0d0.

This webpage by @gilhur explains their purpose: https://sf.snu.ac.kr/gil.hur/Hpattern/readme.txt

Is this library still working / still used today and still relying on these internal tactics? If yes, we could document these tactics as internal and reference the use case. But we should also consider whether `hpattern` should be distributed more widely by being put into an opam package or even in the standard library.

**Comment by JasonGross** [comment]
It looks useful to me, though I've never actually tried it.  I'd be interested in having these tactics available in the standard library.  (What's their performance like?)

**Comment by JasonGross** [comment]
I'd also be curious to know more about @herbelin's

> PS: I used your ideas about hresolve_core to implement in trunk a version of destruct on terms with dependent type which select automatically the occurrences that must be abstracted, without having to use "pattern". Thanks again for the idea.

_Originally posted by @coqbot in https://github.com/coq/coq/issues/2616#issuecomment-337507876_
      
Perhaps there should be a variant/setting of `rewrite` that does this too?

**Comment by Zimmi48** [comment]
From https://github.com/snu-sf/paco/pull/47, it looks like `hpattern` used to be vendored in paco but was not used in this library.

**Comment by Zimmi48** [comment]
Even though @SkySkimmer identified that `hpattern` was vendored in paco, and through it, in VST, a GitHub search doesn't reveal any actual usage of the `hpattern` tactic provided there.
