### ISSUE TITLE
Tactic `head_of_constr` is not documented

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#16844]
It was introduced in fef54f7bae3342686e8005879ed89253ea19c3aa and it is used once in `theories/Classes/Morphisms.v` and `theories/Classes/CMorphisms.v`.

If it is useful, we should document it.

**Comment by ppedrot** [comment]
This tactic is internally generating ill-typed terms, it shouldn't even exist. Many of such internal tactics are just exposed blatantly to the user because there used not to be any easy way to hide them, but I believe that we should just make them local to the few internal modules that use them.

**Comment by Zimmi48** [comment]
How can you make them local if they are used in a v file?

Anyway, we can document as "internal, do not use" (and move it to the typeclass chapter instead of the Ltac chapter where it was inserted).

**Comment by ppedrot** [comment]
It's possible to declare Local Ltac definitions. The problem is historically that there was no way to define a tactic via ML code other than with what would amount to a tactic notation. Nowadays it's easy to do otherwise.
