### ISSUE TITLE
Declare Module: Anomaly "Uncaught exception Not_found." on master

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#16854]
Failing line: [`Declare Module eager : EagerDagDefinitions.`](https://github.com/mit-plv/fiat-crypto/blob/446067cf2dd2bbfc429999855e53002ab916c15f/src/Assembly/Symbolic.v#L1445)
[Error: Anomaly "Uncaught exception Not_found."](https://github.com/mit-plv/fiat-crypto/actions/runs/3492650442/jobs/5846655601#step:7:3639)
failed Nov 17, 2022 with e043c3e206f1f64303508e89b3501aade7f58a06; also [failed](https://github.com/mit-plv/fiat-crypto/actions/runs/3492650442/jobs/5846655601#step:7:3640) with be037486c27f29dc0bcfbfd742c0303af295e23f
[succeeded](https://github.com/mit-plv/fiat-crypto/actions/runs/3470364029/jobs/5823008265) Nov 16, 2022 with a7ec416deffe000008ce5006e4b75a5a118be0ca

There are [6 commits](https://github.com/coq/coq/commits/e043c3e206f1f64303508e89b3501aade7f58a06) between these two; based on commit messages my guess for the culprit is https://github.com/coq/coq/pull/16794: Update mod_delta in safe_typing.add_include (2d25fc54d1e54ae10d99082163d62ee684652a6d). I think the CI would have caught it if not for https://github.com/mit-plv/fiat-crypto/issues/1512

**Comment by andres-erbsen** [comment]
https://github.com/coq/coq/issues/16834

**Comment by JasonGross** [comment]
Duplicate of https://github.com/coq/coq/issues/16834
