### ISSUE TITLE
How to force native_compute to be vm_compute?

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#16889]
We recently started passing `-native-compiler no` to ensure that our developments never use native_compute, and avoid all the soundness bugs it has caused.

However we now realized that we are getting a deprecation message. Sadly that message is not very helpful:
```
Warning: The native-compiler option is deprecated. To compile native files
ahead of time, use the coqnative binary instead.
[deprecated-native-compiler-option,deprecated]
```
The [documentation](https://coq.inria.fr/refman/practical-tools/coq-commands.html#command-line-options) does not help either:
> Deprecated since version 8.14: This flag has been deprecated in favor of the [Split compilation of native computation files](https://coq.inria.fr/refman/practical-tools/utilities.html#coqnative) binary. The toolchain has been adapted to transparently rely on the latter, so if you use [Building a Coq project with coq_makefile](https://coq.inria.fr/refman/practical-tools/utilities.html#coq-makefile) there is nothing to do. Otherwise you should substitute calls to coqc -native-compiler yes to calls to coqc followed by coqnative on the resulting vo file.

So if I used to use `-native-compiler yes` I should now use `coqnative`, okay. But what if I used to use `-native-compiler no`, then what do I do now? The documentation explains that `-native-compiler no` will make `native_compute` be `vm_compute` no matter the compile-time configuration, which is what we want, but it does not explain how to achieve that effect without a deprecation warning.

Cc @robbertkrebbers @ppedrot (author of https://github.com/coq/coq/pull/14309)

**Comment by Blaisorblade** [comment]
AFAIK `[deprecated-native-compiler-option,deprecated]` is standard code for "disable/tweak with `-w -deprecated-native-compiler-option`", even though I've never seen docs pointing this out and I've picked it up by accident. Have you tried that option?

**Comment by Blaisorblade** [comment]
The docs I can find seem indeed insufficient:
- `-w` is mentioned in https://coq.inria.fr/refman/practical-tools/coq-commands.html#by-command-line-options
- https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#coq:opt.Warnings mentions `Set Warnings`

BTW, both talk about

> a comma-separated list of warning names or categories.

and my guess is that `deprecated-native-compiler-option` is a warning name, and `deprecated` is a warning category.

**Comment by ppedrot** [comment]
Are you sure that `-native-compiler no` passed to coqc actually disabled the native_compute feature? Rereading the comments in the PR I remember it was a mess, because there was a confusion between native compilation of libraries and the use of native compute.

**Comment by Zimmi48** [comment]
> Are you sure that `-native-compiler no` passed to coqc actually disabled the native_compute feature?

That corresponds to what I remember. cc @proux01 

This behavior is also consistent with the one of `-bytecode-compiler`. Probably we should only have deprecated `-native-compute yes` and `-native-compute ondemand` to later rebind `-native-compute yes` to mean just the default.

**Comment by RalfJung** [comment]
@Blaisorblade sure we can disable the warning, but I assume this warning means the flag will be removed in the future, so that's not really a solution.

> Are you sure that -native-compiler no passed to coqc actually disabled the native_compute feature?

We haven't tried it, but your [docs](https://coq.inria.fr/refman/practical-tools/coq-commands.html#command-line-options) say so.

**Comment by proux01** [comment]
> > Are you sure that `-native-compiler no` passed to coqc actually disabled the native_compute feature?
> 
> That corresponds to what I remember. cc @proux01

This is documented there https://coq.inria.fr/distrib/current/refman/practical-tools/coq-commands.html

> Setting no disables [native_compute](https://coq.inria.fr/distrib/current/refman/proofs/writing-proofs/equality.html#coq:tacn.native_compute) which defaults back to [vm_compute](https://coq.inria.fr/distrib/current/refman/proofs/writing-proofs/equality.html#coq:tacn.vm_compute); no files are precompiled.

**Comment by maximedenes** [comment]
> avoid all the soundness bugs it has caused

Just out of curiosity (nothing more), is it so clear that more bugs have historically been found in `native_compute` than `vm_compute`?

**Comment by ppedrot** [comment]
Judging from this conversation, I don't think we will remove the `-native-compiler` CLI option from coqc. That said, the current warning is still somewhat valid because its meaning will stop having anything to do with the compilation of libraries, it will only affect the `native_compute` tactic. So, maybe you should just ignore or deactivate the warning and pretend there is no problem.

Relatedly and unfortunately, there has been no progress on the coqmakefile / build system front so AFAICT we still can't change the semantics of the `-native-compiler` option.

**Comment by RalfJung** [comment]
I think it would also make sense to not show the warning with `-native-compiler no`.
