### ISSUE TITLE
`Uncaught exception Retyping.RetypeError` with `exact_no_check` in `Context` type

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#16908]
#### Description of the problem

I am not sure whether this is a bug (but if it is an intended behavior, there is no test for it).

```coq
Section __.
  Context (x : ltac:(exact_no_check tt)).
  (* Anomaly "Uncaught exception Retyping.RetypeError(2)."
     Please report at http://coq.inria.fr/bugs/. *)
End __.
Context (x : ltac:(exact_no_check tt)).
(* Anomaly "Uncaught exception Retyping.RetypeError(2)."
   Please report at http://coq.inria.fr/bugs/. *)
```

#### Coq Version

8.16.0

**Comment by SkySkimmer** [comment]
It's trying to get the relevance of the type, but it's not a type so it fails.
IMO not a bug, just an incorrect use of no_check

**Comment by JasonGross** [comment]
I think it being an anomaly is a bug.  Why not catch the exception here and give a proper error message?

**Comment by JasonGross** [comment]
(My view is that any anomaly that does not require plug-in code is always a bug.  Maybe we need an intermediate class of errors that is "you should not see this unless you are playing with unsafe primitives", but I think this should not be "anomaly")

**Comment by andres-erbsen** [comment]
I started out with this stance too; my uncertainty comes from having seen the acceptance of the wide range of anomalies due to unsafe-by-default use of ltac/ltac2 constrs ([ltac variable bypasses typechecking](https://github.com/coq/coq/issues?q=label%3A%22wellknown%3A+ltac+variable+bypasses+typechecking%22+)).

**Comment by SkySkimmer** [comment]
> I started out with this stance too; my uncertainty comes from having seen the acceptance of the wide range of anomalies due to unsafe-by-default use of ltac/ltac2 constrs (ltac variable bypasses typechecking).

That's more about not knowing how to fix it without losing the perf tradeoff. This issue is about deliberately and explictly unsafe operators. If you use unsafe operators wrong, it is not a coq bug.

>My view is that any anomaly that does not require plug-in code is always a bug. 

This is not true when you write your own no_check or any ltac2 "unsafe" uses.
