### ISSUE TITLE
Feature request: volatile casts

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#16917]
Sometimes we want to assign a type to an expression without leaving a trace in the term. This could be provided by "volatile casts", ie `e :> t` (syntax available since https://github.com/coq/coq/pull/13911) would pretype as `e : t` but return only the `e` component.

In other words `_ :> T` produces a fresh evar of type `T` without a cast around it, `None :> option nat` produces `@None nat`.

**Comment by andres-erbsen** [comment]
`match e return t with x => x end`
