### ISSUE TITLE
Deprecated Add LoadPath warning - workflow that uses it described here

### ISSUE THREAD

**Issue by aliak00** [coq/coq#16924]
#### Description of the problem

I have a deprecated warning while using Add LoadPath and was told to explain the workflow here if is an important feature.

I'm using vscode's VSCoq plugin to follow software foundations. And I've setup a directory to write source code in. The default samples say to use `coq_makefile -f _CoqProject *.v -o Makefile`. But that makes the directory with my source files extremely dirty, and virtually unbrowsable.

So to fix this, I implemented a specific structure:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/2638284/204641665-e9200bc0-149f-40b1-8e9c-67c01f2f5d01.png">

I have my source files in a folder named src

And I have a `build.sh` file that has the contents:

```
mkdir -p build
cp src/v1_01_basics.v build/
cp src/v1_01_basics_binary.v build/

coq_makefile -f _CoqProject build/*.v -o Makefile
make
```

And my _CoqProject has

```
-Q build LF
```

So this works nicely in that it creates a folder named build, moves the source files I want to be able to import in to there, and compiles those.

The thing I couldn't figure out though is how to import it without using `Add LoadPath`

So when working on the files in the src folder, if I want to import a file that was compiled, this seems to work:

```
Add LoadPath "build" as LF.
From LF Require Export v1_01_basics.
```

But that gives me the deprecated warning. If there's a way to be able to stay in vscode, and not litter my src directory and avoid `Add LoadPath` that would be quite awesome.

#### Coq Version

The Coq Proof Assistant, version 8.16.1
compiled with OCaml 4.14.0

**Comment by mrhaandi** [comment]
> and virtually unbrowsable

Alternatively, you can hide `*.vos`, `*.aux`, `*.glob` and so on files in the vscode file tree and vscode search. So it is clean to browse and interact with.

**Comment by SkySkimmer** [comment]
Shouldn't vscoq pick up the -Q from your _coqproject?

**Comment by mrhaandi** [comment]
> Would need to add some infrastructure to "clean" the build

With `git`, I use `git clean -fxd` to clean up a working state.

**Comment by ejgallego** [comment]
The feature request for coq_makefile / IDEs to use a separate dir is valid, however I think the `Add LoadPath` workaround is not something we'd like to support. As noted by Gaëtan you can update your `_CoqProject` file, or use Dune which supports hygienic builds.

**Comment by ana-borges** [comment]
Note that silencing a deprecation warning is just postponing the problem, since the feature might be removed later. Like Emilio suggests, [Dune](https://dune.readthedocs.io/en/stable/coq.html) has clean builds (and also caching and other nice features).

**Comment by Zimmi48** [comment]
> Note that silencing a deprecation warning is just postponing the problem, since the feature might be removed later. Like Emilio suggests, [Dune](https://dune.readthedocs.io/en/stable/coq.html) has clean builds (and also caching and other nice features).

And in fact, `Add LoadPath` has now been removed (in the upcoming 8.18 version).
