### ISSUE TITLE
"Create HintDb" clears any existing hint database with that name.

### ISSUE THREAD

**Issue by patrick-nicodemus** [coq/coq#16934]
If  `mydb` is an extant hint database, then "Create HintDb mydb" clears that database and replaces it with a new, empty hint database.

This behavior makes it very difficult to integrate two different libraries which define hint databases with the same names.

Some features of Coq depend on hint databases having specific names. If Library A wants to avoid importing Coq.Init, but still wants to use typeclass inference, they must define their own hintdb called "typeclass_instances." Now if Library B wants to import both Coq.Init and Library A, they have a dilemma, as whichever hintdb is imported first will cause the other to be cleared and overwritten.

"Create HintDb mydb" could raise a warning or error, or result in a no-op, so that Library B ends up with the union of the two original databases rather than one or the other.

**Comment by patrick-nicodemus** [comment]
The bug impacts the Coq-HoTT library and any other library which wants to use the -noinit compile flag, because it makes it unreasonably difficult to selectively draw on things from the standard library without screwing up the typeclass library.

The Coq-HoTT library is compiled with -noinit and does not load the standard library at any point. At the root of the project, a hint database named `typeclass_instances` is defined; many files in the project populate the database with hints. 

If a file anywhere in the project imports a file in the standard library, then the hint database in the standard library overwrites the one from the project, "zeroing it out" and populating it with the hints in the standard library.

This means that the standard library must be imported at the beginning of the file, before anything else, and so on in any file that imports that one, and so on, which is a mess.

**Comment by ppedrot** [comment]
Having a qualified name does really entail module-scoping, we could have a reserved prefix for statically defined dbs.

**Comment by ppedrot** [comment]
For the HoTT issue, I think there is an easy local fix: we can simply statically define the global dbs that are hardcoded in the tactic implementation. From what I gather, there are three dbs defined in the prelude: `core`, `typeclass_instances` and `rewrite`. These could be defined by the OCaml piece of code that relies on them instead.
