### ISSUE TITLE
vm_compute does not update compiled representation of goal variables when evar map changes

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#16957]
Hinted by https://github.com/coq/coq/pull/16870#issuecomment-1341329680 which says that turning https://github.com/coq/coq/blob/123133312f6befd1497273830a2134320a7b673d/pretyping/vnorm.ml#L217 into find_undefined fails with the assert false in fiat-crypto.

~~~coq
Goal True.
Proof.
  evar (x:nat).
  generalize (eq_refl:x = x).
  vm_compute.
  intros _.
  generalize (eq_refl:x + 1 = x + 1).
  let x := constr:(eq_refl : x = 0) in idtac.
  vm_compute.
  (* vm_compute still thinks variable x is defined to an undefined evar, so computes to a blocked fix *)

  Fail match goal with |- 1 = 1 -> True => idtac end.
  progress vm_compute.
  match goal with |- 1 = 1 -> True => idtac end.
~~~

more evil:
~~~coq
Goal False.
Proof.
  evar (x:nat).
  assert_succeeds (
      let y := constr:(eq_refl : x = 1) in
      generalize (eq_refl:x = x);
      vm_compute).
  (* vm_compute now believes x = 1 *)
  generalize (eq_refl:x = 0).
  vm_compute.
  intros H;inversion H.
Fail Qed.
~~~

The info which becomes incorrect is in the lazy_val in the named_context in the env. This means we cannot `clear x` to `pose` a different one or otherwise manipulate it other than by side effect, which means only through evars AFAIK.
As such it seems we can't mess with section variables or get an inconsistency to pass the kernel through this bug.

**Comment by silene** [comment]
In 8.16.1, there is a shorter reproducer, which I find a bit worrying:
```coq
Section S.
  Let x := 0.
  Definition foo : x = 1 := ltac:(vm_cast_no_check (eq_refl 1)).
End S.
```

**Comment by SkySkimmer** [comment]
and also fails on 8.16.1

**Comment by silene** [comment]
My mistake, I should have made sure to purge Coq between two experiments, which means that the following one succeeds:
```coq
Section S.
  Let x := 0.
  Definition foo : x = 1 := ltac:(change_no_check 0 with 1 in x; vm_compute; reflexivity).
  Back 1.
  Definition foo : x = 1 := ltac:(vm_cast_no_check (eq_refl 1)).
End S.
```

**Comment by silene** [comment]
And here is a variant without using `Back`:
```coq
Section S.
  Let x := 0.
  Fail Definition foo : x = 1 := ltac:(change_no_check 0 with 1 in x; vm_compute).
  Definition foo : x = 1 := ltac:(vm_cast_no_check (eq_refl 1)).
End S.
```
