### ISSUE TITLE
[coqide] Tooltip locations are broken in `master`

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#16987]
Open this file in coqide:
```
Definition a := 3.

Definition b := 3.  Variable n : nat.
```

Then hover under `Variable n : nat` , you will see no tooltip. If you hover over the first line, you can see that the tooltip tries to appear there.

This is due to a large mess in location handling, fix in #16978 

Note that this bug deals with the case where `coqops:attach_tooltip` is called, and the tooltip is attached incorrectly.

There is a different bug that also makes tooltips to go missing which is when the feedback comes without a `Stateid.t`, but in this case, `attach_tooltip` is never called in the first place.

**Comment by Zimmi48** [comment]
Regression from 8.15.

**Comment by ejgallego** [comment]
Fixed by #17382
