### ISSUE TITLE
Cannot unify terms in an SProp

### ISSUE THREAD

**Issue by patrick-nicodemus** [coq/coq#16983]
```
From HoTT Require Import Basics.
Set Cumulative StrictProp.

Section StrictProp.
  Context (P Q : SProp).
  Context (P_to_Q : forall _ : P, Q).
  Context (Q_to_P : forall _: Q, P).

  Definition PQ_Equiv : IsEquiv P_to_Q.
  Proof.
    (* Also tried "unshelve eapply Build_IsEquiv" 
        and "srapply Build_IsEquiv" *)
    unshelve refine (@Build_IsEquiv _ _ _ _ _ _ _).
    - (* Q -> P *) exact Q_to_P.
    - (* forall x : Q, P_to_Q (Q_to_P x)) = x  *)
      intro x.
      Fail reflexivity.
      Fail (change (P_to_Q (Q_to_P x)) with x).
      Fail unify (P_to_Q (Q_to_P x)) x.
```
It should be possible to unify `P_to_Q (Q_to_P x)` with `x` here.
This is Coq version 8.16.1 compiled with Ocaml 4.13.1.
_CoqProject is 
```
-arg -noinit
-arg -indices-matter
```

**Comment by SkySkimmer** [comment]
That's just a consequence of using Cumulative StrictProp

**Comment by patrick-nicodemus** [comment]
@SkySkimmer The error persists if you don't use Cumulative StrictProp. Now granted this code would fail to pass the QED because it's an SProp but it would be better if there was a more informative error message

**Comment by SkySkimmer** [comment]
Eventually we aim to remove the mplicit Cumulative SProp during elaboration, so you'll get an error at the Definition line
