### ISSUE TITLE
Refman broken Instance notation for Add Parametric Relation

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#17039]
In the Coq 8.16 reference manual, at https://coq.inria.fr/distrib/current/refman/addendum/generalized-rewriting.html#first-class-setoids-and-morphisms

it says "the declaration . . . Add Parametric Relation . . .  is equivalent to an instance declaration . . .
```
Instance (x1 : T1) ... (xn : Tn) => id : @Equivalence (A t1 ... tn) (Aeq t′1 ... t′m) :=
 .  .  .
```
However, Coq 8.16 does not accept an Instance declaration in this syntax.  What seems to work instead is,

```
Instance id (x1 : T1) ... (xn : Tn)  : @Equivalence (A t1 ... tn) (Aeq t′1 ... t′m) :=
 .  .  .
```

And, of course, the manual should say what scope (export, global, whatever) should be attached to the Instance, to be equivalent to an Add Parametric Relation declaration.

**Comment by Zimmi48** [comment]
From the code, it looks like the only supported localities currently are `local` and `global`:

https://github.com/coq/coq/blob/3dfa597540c0e4aa720c9af966f92b359a0c29f3/plugins/ltac/comRewrite.ml#L79-L87

And the default behavior is the classic "local inside sections, global outside sections":

https://github.com/coq/coq/blob/3dfa597540c0e4aa720c9af966f92b359a0c29f3/plugins/ltac/comRewrite.ml#L35-L41

**Comment by Zimmi48** [comment]
This information should probably be added here as well: https://coq.inria.fr/distrib/current/refman/addendum/generalized-rewriting.html#adding-new-relations-and-morphisms

**Comment by Zimmi48** [comment]
BTW, @ppedrot et al.: probably these commands should get `export` support as well.
