### ISSUE TITLE
Canonical instances keyed on `_` do not match `match` terms

### ISSUE THREAD

**Issue by Janno** [coq/coq#17079]
#### Description of the problem

The code below shows that `C_def` is not used for the `match` term in the line starting with `Fail` and that putting the `match` term in a `Definition` fixes the problem. This is unexpected to me since I am not aware of special rules around `match` terms in the (ideal) CS resolution algorithm.

```coq
Structure C := { i : nat }.
Canonical Structure C_add (a : C) (b : C) := {| i := a.(i) + b.(i) |}.
Canonical Structure C_def n := {| i := n |}.
Succeed Check fun (b:bool) (n:nat) => (eq_refl : (n + n = _.(i))).
Fail Check fun (b:bool) (n:nat) => (eq_refl : (match b with true => n | _ => 0 end + n = _.(i))).
Definition bla b n := match b with true => n | _ => 0 end. (* simple alias for the match term above *)
Succeed Check fun (b:bool) (n:nat) (x := _) => (eq_refl : (bla b n + n = x.(i))).
```

Unicoq disagrees about this and happily accepts the line prefixed with `Fail`.

#### Coq Version
8.12.2 (use `Fail Fail` instead of `Succeed`), 8.16.0

**Comment by Janno** [comment]
I've added the consortium label on behalf of Bedrock Systems.

**Comment by SkySkimmer** [comment]
>`Succeed Check fun (b:bool) (n:nat) (x := _) => (eq_refl : (bla b n + n = x.(i))).`

Not sure why you did `x:=_` for this one, it doesn't seem to be different from `_.(i)`

**Comment by Janno** [comment]
That wasn't on purpose. I think I was testing something with two occurrences of `_` and I wanted them to be the same.

**Comment by SkySkimmer** [comment]
Also why does the example have this C_add stuff? Isn't `eq_refl : match ... end = _.(i)` enough to show the problem?

**Comment by Janno** [comment]
Indeed. I guess this brings us to:
```coq
Structure C := { i : nat }.
Canonical Structure C_def n := {| i := n |}.
Succeed Check fun (b:bool) (n:nat) => eq_refl : n = _.(i).
Fail Check fun (b:bool) (n:nat) => eq_refl : match b with true => n | _ => 0 end = _.(i).
Definition bla b n := match b with true => n | _ => 0 end. (* simple alias for the match term above *)
Succeed Check fun (b:bool) (n:nat) => eq_refl : bla b n = _.(i).
```

**Comment by SkySkimmer** [comment]
NB old unification seems to handle it too (assuming the test I wrote tests what I think it tests)
~~~coq

Lemma aux P v : P v.(i).
Admitted.

Goal forall P b (n:nat), P match b with true => n | _ => 0 end.
Proof.
  intros.
  apply aux.
~~~
