### ISSUE TITLE
coqdoc unknown option '--index'

### ISSUE THREAD

**Issue by palmskog** [coq/coq#17072]
#### Description of the problem

The coqdoc option `--index` takes a string and provides the possibility of naming the index HTML file, e.g., `coqdoc --index indexpage file.v` creates `indexpage.html` for the index.

However, after running for example:
```shell
coqdoc --index idx
```
I now get the following error:
```shell
coqdoc: unknown option '--index'.
```

#### Coq Version

master commit c66a593ba124b96ec104273eb208904c6a9942be.

I determined locally that the problem first occurs after #15771 was merged, although I didn't do a "formal" bisection. It looks like we have no test for `coqdoc --index` in the test-suite.

**Comment by Alizter** [comment]
ping @artagnon
