### ISSUE TITLE
Small Inversion as a Tactic

### ISSUE THREAD

**Issue by mukeshtiwari** [coq/coq#17099]
#### Description of the problem
 I recently came to know about [small inversion trick](https://www-verimag.imag.fr/~monin/Publis/Docs/coq2.pdf). After digging a bit more I [found](http://gallium.inria.fr/blog/a-new-Coq-tactic-for-inversion/) that Thomas Braibant and Pierre Boutillier were implementing it in Coq. However, it seems that it never finished. It would be nice to have small inversion as a Coq tactic because it makes the dependent type programming painless. 

CC @JasonGross @dmxLarchey

**Comment by JasonGross** [comment]
Duplicate of #4989

**Comment by JasonGross** [comment]
See also https://github.com/coq/coq/issues/13323, https://github.com/coq/coq/issues/5021, https://github.com/coq/coq/issues/4891, https://github.com/coq/coq/pull/16097
