### ISSUE TITLE
`apply` doesn't understand `Prop` vs `SProp`

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#17108]
```
Axiom test : forall (P : Prop), P.
Lemma test2 : forall (P : SProp), P.
apply test.
Qed.
(* Illegal application: 
The term "test" of type "forall P : Prop, P"
cannot be applied to the term
 "forall P : SProp, P" : "SProp"
This term has type "SProp" which should be coercible to "Prop". *)
```

#### Coq Version
master

**Comment by ppedrot** [comment]
FTR there is quite a bit of work around SProp going on in master. Hopefully these bugs will eventually be solved, but do not hesitate to provide more test cases to increase coverage.

**Comment by ppedrot** [comment]
Hmm, but I misread your bug report. Why are you expecting it to succeed? There is no cumulativity relation between Prop and SProp, for foundational reasons.

**Comment by LasseBlaauwbroek** [comment]
I'm expecting `apply test` to fail.

**Comment by ppedrot** [comment]
Ah, then it is fixed in my branch that removes the cumulative SProp flag.

**Comment by herbelin** [comment]
> There is no cumulativity relation between Prop and SProp, for foundational reasons.

Are the consequences of assuming `SProp` subset of `Prop` the ones described in Section 4.5 of Gilbert-Cockx-Sozeau-Tabareau 2018 or are there other consequences to be aware of?
