### ISSUE TITLE
Coq unable to infer pattern with coercions when too simple

### ISSUE THREAD

**Issue by Alizter** [coq/coq#17137]
We can classify constructors of an inductive type by declaring its constructors mutually with the classified verions and then declaring the inclusion maps to be coercions. For the most part, this gives the illusion of having a single inductive type. However the following case demonstrates that Coq is able to match on a more complicated version with no issue, however a simple version with fewer constructors causes Coq to complain:

### Many constructors:
```coq
Inductive Num : Type :=
| pos : Pos -> Num
| neg : Neg -> Num
with Pos : Type :=
| a : Pos
| c : Pos
with Neg : Type :=
| b : Neg
.

Coercion pos : Pos >-> Num.
Coercion neg : Neg >-> Num.

From Coq Require Import String.
Local Open Scope string.
Definition name (x : Num) : string :=
  match x with
  | a => "a"
  | b => "b"
  | c => "c"
  end.
```

### Fewer constructors
```coq
Inductive Num : Type :=
| pos : Pos -> Num
| neg : Neg -> Num
with Pos : Type :=
| a : Pos
with Neg : Type :=
| b : Neg
.

Coercion pos : Pos >-> Num.
Coercion neg : Neg >-> Num.

From Coq Require Import String.
Local Open Scope string.
Definition name (x : Num) : string :=
  match x with
  | a => "a"
  | b => "b"
  end.
```

Coq complains with

```
Non exhaustive pattern-matching: no clause found for pattern neg _
```
Clearly this is not the case and should be fixed.

**Comment by herbelin** [comment]
The issue is that there is a special treatment for singleton types which ignore coercions. PR #17138 fixes the issue for pattern-matching with only one row, as above.

Here is a case that #17138 does not fix though:
```
Inductive Num : Type :=
| pos :> Pos -> Num
| neg :> Neg -> Num
with Pos : Type :=
| a : Pos
with Neg : Type :=
| b : Neg.

Check fun x y : Num => match x, y with
| x, a => 0
| a, b => 1
end.
```
It is wrongly compiled to:
```
fun _ y : Num => match y with
                 | pos a => 0
                 | neg b => 1
                 end
```
because it is assumed that `a` is irrefutable on the second row of the first line and that splitting on `a` in the first row is not needed.

On the contrary, the following should succeed but fails with `Pattern "b, b" is redundant in this clause`:
```
Fail Check fun x y : Num => match x, y with                                                                                             
| x, a => 0                                                                                                                             
| a, b => 1                                                                                                                             
| b, b => 2                                                                                                                             
end. 
```
