### ISSUE TITLE
#[local] Ltac2 tactics break Ltac2 backtrace printing

### ISSUE THREAD

**Issue by Janno** [coq/coq#17155]
#### Description of the problem

Ltac2 backtraces containing `#[local]` functions cannot be printed. I've been haunted by this bug for months and finally managed to accidentally reproduce it in a minimal setting.

```coq
From Ltac2 Require Import Ltac2.
Module M.
  #[local] Ltac2 f () := Control.throw (Invalid_argument None).
  Ltac2 g () := f ().
End M.
Fail Ltac2 Eval M.g ().         (* Fails, as expected. *)
Set Ltac2 Backtrace.
Fail Ltac2 Eval M.g ().         (* Anomaly "Uncaught exception Not_found." *)
```

#### Coq Version
8.16.0

**Comment by SkySkimmer** [comment]
Same on `Print Ltac2 M.g.`
