### ISSUE TITLE
Pure coq library has term that can't be typechecked without hanging+massive RAM usage.

### ISSUE THREAD

**Issue by tom-p-reichel** [coq/coq#17193]
Me, @InnovativeInventor found an unassuming term in `coq-ext-lib` (a pure Coq library with no Ocaml plugins) which causes Coq to hang and consume memory indefinitely (observed >25GB memory usage) when asked to typecheck the term.

####  Reproduction
Coq version `8.16.1`, extlib version `0.11.7`, term is `neg_lt_dec` from `ExtLib.Programming.Le`.

Here's a bash script that builds a minimal switch (named bug) and demonstrates the bug, tested on ArchLinux:

```bash
opam switch create bug --repos="default,coq=https://coq.inria.fr/opam/released" --packages="coq.8.16.1,coq-ext-lib.0.11.7"
eval $(opam env)
echo "Require Import ExtLib.Programming.Le. Check neg_lt_dec." > example.v
coqc example.v
```

**Comment by SkySkimmer** [comment]
Isn't it just typeclass resolution? https://github.com/coq-community/coq-ext-lib/blob/d48e6583c4fe01479f743ea21d9b921073cb3f5b/theories/Programming/Le.v#L42

**Comment by Janno** [comment]
I think this issue could benefit from a bit more discussion even though it is not a problem with the typechecker. 

One part of the TC search cycle is declared using `:>` so this might be an awareness/documentation issue.

```coq
Class LteWF T :=
{ lteWFLte :> Lte T
; lteWFPreOrder :> PreOrder lte
}.
```

The cycle is as follows: By using `:>` here, `lteWFLte` is turned into a hint for `Lte T`. Its only premise is `LteWF T` for which there exists an explicit instance `LteWF_Build` (https://github.com/coq-community/coq-ext-lib/blob/aea8ad3902b289107b73ad6a642b61df372e67d0/theories/Programming/Le.v#L30). `LteWF_Build` requires `Lte T` and thus the cycle is complete. The cycle is reasonably easy to to debug in this case using 
```coq 
Set Typeclasses Debug.
Fail Timeout 1 Check neg_lt_dec.
```

And it is worth noting that `Check @neg_lt_dec` (note the extra `@`) doesn't attempt to fill in the implicit arguments and can be used to quickly test if maybe TC search or some related mechanism is to blame.

The use of `:>` in `Class` has gotten people confused before and I think I've seen various discussions around it in different issues. I think the canonical documentation for the feature is in https://coq.inria.fr/refman/addendum/type-classes.html#substructures which unfortunately is just above (and thus out of sight) of what the browser jumps to when opening the documentation for `Class` (https://coq.inria.fr/refman/addendum/type-classes.html#coq:cmd.Class).

I wonder if the original intent here was to register `lteWFLte` as a coercion and not a hint? If not, one hacky way to work around the cycle could be using `Hint Cut` to forbid applying  `LteWF_Build` after `lteWFLte`.
