### ISSUE TITLE
Proof finisher weaker than `now`?

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#17201]
https://github.com/coq/coq/pull/17187#issuecomment-1415740086 @herbelin 
>Removal of useless now done (I had copied the code from a development which conventionally uses now in proof leaves, even when not strictly needed).

I wonder if we could provide a tactical which enforces no remaining goals like `now` but does not automatically try to solve goals when they are present.
I supose it would just be a simpler syntax for `solve`, without having to use brackets: `new_tactical tac := solve [ tac ]`

**Comment by ejgallego** [comment]
ssreflect's `by` is weaker than `now`, but still does some automatic things like `assumption`, `reflexitivity` etc...

IMVHO I think it is rare to want a pure closing terminator, you usually want one that does a bit of work as to avoid noise.

**Comment by ejgallego** [comment]
I find `by reflexivity` a PITA for example. For that ssreflect uses `by []` where the `[]` are supposed to imitate ∎

**Comment by herbelin** [comment]
Not sure, `solve` is the best word but a cheap and consistent solution would be to support the syntax `solve tac`.

Or `solved with tac`, but it is a bit long.

Or `easy tac`, or `done tac`, which both could both be presented as the non defective forms of `easy` or `done`.

**Comment by herbelin** [comment]
> I find `by reflexivity` a PITA for example. For that ssreflect uses `by []` where the `[]` are supposed to imitate ∎ (qed)

By the way, if that's the intent of this (somehow cryptic) syntax, why not to support also the utf8 syntax `by ∎`?

**Comment by herbelin** [comment]
> ssreflect's `by` is weaker than `now`

Are the exact differences documented somewhere? Since they are used most of the time in terminating position, it would maybe be not too disruptive to merge them?

**Comment by herbelin** [comment]
Actually, internally, there is `tclCOMPLETE`, so, it could also be `complete tac`.

**Comment by ejgallego** [comment]
> By the way, if that's the intent of this (somehow cryptic) syntax, why not to support also the utf8 syntax by ∎?

I guess at the time this was desgined, unicode support was not feasible; this is indeed better today so it could be done.

> Are the exact differences documented somewhere?

I'm unsure if it is written down, but I have seen the differences explained pretty carefully so they are well-known.

I'm not super-expert, but my understanding is that `now` is slower that `by` for very little practical gain.

> Since they are used most of the time in terminating position, it would maybe be not too disruptive to merge their semantics?

Maybe, I guess first thing to figure is really how much more powerful `now` is.

**Comment by silene** [comment]
There seems to be some misunderstanding as to what `by` does. It just invokes the user-defined tactic `done`. So, comparing the power and speed of `now` and `by` does not make much sense, unless you specify which implementation of `done` you are talking about (e.g., ssralg redefines `done`). For example, the following makes `by` just as powerful as `now`:
```coq
Ltac done := easy.
```

By the way, this also means that the following turns `by` into an answer to the original request:
```coq
Ltac done := fail.
```

In practice, the main difference between `easy` and the default implementation of `done` is that the latter is unable to prove `A /\ B -> A`, which means that the user has to manually decompose hypotheses beforehand.

**Comment by Villetaneuse** [comment]
> I'm unsure if it is written down, but I have seen the differences explained pretty carefully so they are well-known.
> 
> I'm not super-expert, but my understanding is that `now` is slower that `by` for very little practical gain.
> 
> > Since they are used most of the time in terminating position, it would maybe be not too disruptive to merge their semantics?
> 
> Maybe, I guess first thing to figure is really how much more powerful `now` is.

At the moment, I try hard to close every goal with a closing tactic and I use `now` very, very, very frequently... If it poses some performance issues it is a big deal (for instance, is it important to use some explicit `exact` or `apply` rather than `now` ?). However its proving power is very satisfying imho. I tried to open a discussion about compilation speed in zulip, but it got stuck https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Cost.20of.20automatic.20tactics.20during.20compilation
I still think it would be nice to have some guidelines for files which are compiled many times (e.g. the standard library).
But I am not an expert at all and lack time and knowledge to do this.

**Comment by Blaisorblade** [comment]
> In practice, the main difference between easy and the default implementation of done is that the latter is unable to prove A /\ B -> A, which means that the user has to manually decompose hypotheses beforehand.

The complaint I remember against `easy` (from @robbertkrebbers ) is that it attempts `solve [inversion H]` automatically on each hypothesis, but I haven't evaluated that myself, and appropriateness surely varies.

Is this loop even guaranteed to destruct all conjunctions before `inversion`?
```
  let rec use_hyps :=
    match goal with
    | H : _ /\ _ |- _  => exact H || (destruct_hyp H; use_hyps)
    | H : _ |- _ => solve [inversion H]
    | _ => idtac
    end in
```
