### ISSUE TITLE
Unused grammar nonterminals?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#17218]
AFAICT the following nonterminals are not used.  Can they be removed?  Thanks.

```
Warning: editedGrammar: Unreachable symbol 'one_open_binder'
Warning: editedGrammar: Unreachable symbol 'one_closed_binder'
Warning: editedGrammar: Unreachable symbol 'deprecated_number_modifier'
```

**Comment by herbelin** [comment]
The first two are crucially used for declaring notations with binders (see `vernac/egramcoq.ml`).

The third one seems to come from a deprecation in 2020 and is probably to remove at some point (introduced by @proux01).

**Comment by jfehrle** [comment]
Thanks, guys!

**Comment by jfehrle** [comment]
@herbelin should the syntax for the first two be documented, and if so, where?  Do users need to know about them or are they only used internally?

**Comment by herbelin** [comment]
Users don't need to know about the gramlib name of them. They are accessible at vernac level via the `binder` and `closed binder` entry modifiers of `Notation`.
