### ISSUE TITLE
Fiat-crypto timeouts

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#17222]
Fiat-crypto keeps timing out, and it's already long enough that I want to reduce the timeout and oppose increasing it.
Can we get a subset of it to run in CI?
If not then IMO we should remove it.

cc @JasonGross

**Comment by herbelin** [comment]
Fiat-crypto gave me sometimes interesting examples. I would prefer it is cut into two pieces.

**Comment by SkySkimmer** [comment]
Unless those pieces can be run in parallel it would still slow CI down too much IMO

**Comment by JasonGross** [comment]
What about running something like `make -j2 || make -j2 || make -j2 || make` on the CI?  Or writing a fancier script that processes the build log, finds the file that failed, and does something like `function recurse() { make -j2 || { make file-that-failed.vo && recurse; }; }`?  This would allow fiat-crypto to build mostly in parallel, while being more robust to memory errors, at the cost of a couple extra minutes here and there when we need to rebuild a file that failed from OOM.

**Comment by JasonGross** [comment]
Since when?

We merged a trivial change on April 26 that should not have changed timing, a minor change on April 21 that should have added less than a minute to the build, bumped dependencies on April 1, and made larger changes on March 19.  Did one of these cause the timeouts?

**Comment by SkySkimmer** [comment]
They don't happen for all runs so who knows

**Comment by andres-erbsen** [comment]
The last PR spent 133min in the fiat-crypto step, so it is not longer at the edge of a timeout.
