### ISSUE TITLE
Nested existential variables break expected semantics

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#17295]
Consider the following script.
```coq
Require Import Setoid.

Set Printing Existential Instances.

Axiom A : Type.
Axiom i : A.
Axiom Equal : A -> A -> Prop.
Axiom P : A -> Prop.

Axiom everything_equal : forall (j : A), Equal i j.

Instance b : Morphisms.Proper (Equal ==> Basics.impl) P. Admitted.

Lemma blah (H : P i) : True.
rewrite everything_equal in H.
Show Proof.
(*
(fun H : P i =>
 ?Goal@{H:=(fun lemma : Equal i ?Goal0@{H:=H} => b i ?Goal0@{H:=H} lemma)
             (everything_equal ?Goal0@{H:=H}) H}) 
*)
Show.
(* 
  H : P ?Goal0@{H:=H}
  ============================
  True 
*)
exact I.
Unshelve. exact i.
Qed.
```
The printed proof term looks acceptable at first sight. However, the printed proof state violates the semantics that I've always ascribed to existential instances. Granted, I'm not sure that a formal description of existential variables for Coq exists. However, I've always interpreted it such that terms in an existential instance should be typable in the current context. As such, in the existential variable `?Goal0@{H:=H}` of hypothesis `H` of the printed proof state, I would expect the instance term `H` to be typable in an empty context, which it isn't.

Am I interpreting the semantics wrong, or is this a bug?

**Comment by SkySkimmer** [comment]
That's a bug, eg you can get an error at Qed:
~~~coq
Axiom forget : P i -> A.
Lemma blah (H : P i) : True.
Proof.
  rewrite everything_equal in H.

  Unshelve.
  2: exact (forget H).

  pose proof H;
  exact I.
Qed.
(* error *)
~~~

**Comment by LasseBlaauwbroek** [comment]
This is what the typechecker has to say about it:
```coq
Lemma blah (H : P i) : True.
refine ?[g].
Check ((fun lemma : Equal i _ => b i _ lemma) (everything_equal _) H).
(*
(fun lemma : Equal i ?y@{H:=H} => b i ?y@{H:=H} lemma) (everything_equal ?y@{H:=H}) H
     : P ?y@{H:=H}
where
?y : [H : P i  lemma : Equal i ?y@{H:=H} |- A] (lemma cannot be used)
*)
Check (?g@{H:=(fun lemma : Equal i _ => b i _ lemma) (everything_equal _) H}).
(*
?g@{H:=(fun lemma : Equal i i => b i i lemma) (everything_equal i) H}
     : True
where
?g : [H : P i |- True]
*)
Abort.
```
So by putting the first term in an instance, the typechecker is able to infer that `?y` should be `i`. I'm not entirely sure why.

**Comment by LasseBlaauwbroek** [comment]
Okay, presumably what is going on is that when `setoid_rewrite` generates the term
```coq
(fun H : P i =>
 ?Goal@{H:=(fun lemma : Equal i ?Goal0@{H:=H} => b i ?Goal0@{H:=H} lemma)
             (everything_equal ?Goal0@{H:=H}) H}) 
```
it expects the subterm `(fun lemma : Equal i ?Goal0@{H:=H} => b i ?Goal0@{H:=H} lemma) (everything_equal ?Goal0@{H:=H}) H}` to be typed in the context of the original proof state where `H : P i`. But in reality, the subterm should be typed in the context associated with `?Goal`.

So this is a bug in how `setoid_rewrite` generates its terms?
