### ISSUE TITLE
Cancelation lemmas for multiplication on `nat` are missing

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#17354]
#### Description of the problem

There are lemmas `Z.mul_reg_{l,r}` for cancellation of multiplication on integers:

```
Z.mul_reg_l
     : ∀ n m p : Z, p ≠ 0 → p * n = p * m → n = m
Z.mul_reg_r
     : ∀ n m p : Z, p ≠ 0 → n * p = m * p → n = m
```

These lemmas also hold for `nat` but are missing in Coq's standard library.

Std++ includes versions these lemmas for `nat`, but it would be great to have them in Coq's standard library. See https://gitlab.mpi-sws.org/iris/stdpp/-/merge_requests/450 

#### Coq Version

```
The Coq Proof Assistant, version 8.16.1
compiled with OCaml 4.13.1
```

**Comment by olaure01** [comment]
Bidirectional versions exist:
```coq
PeanoNat.Nat.mul_cancel_l : forall n m p : nat, p <> 0 -> p * n = p * m <-> n = m
PeanoNat.Nat.mul_cancel_r : forall n m p : nat, p <> 0 -> n * p = m * p <-> n = m
```

**Comment by robbertkrebbers** [comment]
Good catch, I missed that.

Nonetheless, I think the request in this issue is useful since one often searches for lemmas involving `→`. Besides, the comments in the stdlib's `BinInt` file states:

```
(** TODO : to add in Numbers ? *)
```

https://github.com/coq/coq/blob/master/theories/ZArith/BinInt.v#L1281

**Comment by HaoYang670** [comment]
I'd like to take this.
