### ISSUE TITLE
coqtopide error of option -main-channel and -control-channel

### ISSUE THREAD

**Issue by Heersin** [coq/coq#17367]
#### Description of the problem
1. undocumented `-main-channel` and `-control-channel`, see https://github.com/coq/coq/issues/11296
2. Log reports : `coqtop-stderr: Error: host:portr:portw or stdfds expected after option -main-channel.` when specifying ipv6 address and port in `-main-channel` and `-control-channel` (::1:37797:44815 e.g.)

### Scenario
Running coq program in vscode with `vscoq` plugin, it keeps reporting `coqtop is not running`. the log of `coq-lsp` is as follows : 
```
Coqtop binPath is: /usr/bin/
starting coqtop
exec: /usr/bin/coqtop -v
Listening at ::1:44359
Listening at ::1:40015
Listening at ::1:33795
Listening at ::1:42671
Detected coqtop version 8.16.1
Coqtop version parsed into semver version 8.16.1
exec: /usr/bin/coqidetop.opt -main-channel ::1:40015:44359 -control-channel ::1:33795:42671 -async-proofs on -Q . LF -topfile file:///home/proof/coq/example1.v
coqtop started with pid 219504
coqtop-stderr: Error: host:portr:portw or stdfds expected after option -main-channel

coqtop exited with code: 1
onCoqClosed(coqtop closed with code: 1)
onCoqClosed(undefined)
coqtop closed with code: 1
Listening at ::1:33743
Listening at ::1:34573
Listening at ::1:35201
Listening at ::1:34915
```

It seems like those addresses were fetched from `net.createServer()`
```javascript
        this.mainChannelServer = net.createServer();
        this.mainChannelServer2 = net.createServer();
        this.controlChannelServer = net.createServer();
        this.controlChannelServer2 = net.createServer();
```

#### Coq Version
The Coq Proof Assistant, version 8.16.1
compiled with OCaml 4.12.1

**Comment by SkySkimmer** [comment]
This seems like a vscoq issue, not a coq issue.
In any case vscoq2 doesn't use coqidetop.
