### ISSUE TITLE
Error after Homebrew install - "Config file not found - neither /opt/homebrew/etc/findlib.conf nor the directory /opt/homebrew/etc/findlib.conf.d"

### ISSUE THREAD

**Issue by zbrasseaux** [coq/coq#17376]
#### Description of the problem

After installing, both `coqc` and `coqtop` give the following error message: 
    Error:
    Anomaly
    "Uncaught exception Failure("Config file not found - neither /opt/homebrew/etc/findlib.conf nor the directory /opt/homebrew/etc/findlib.conf.d")."
    Please report at http://coq.inria.fr/bugs/.

#### Coq Version

The Coq Proof Assistant, version 8.16.1
compiled with OCaml 4.14.0

OS: macOS 11.3.1 20E241 x86_64
Shell: zsh 5.8 
CPU: Apple M1

**Comment by herbelin** [comment]
The error is reported by `ocamlfind`. Had something wrong happened when installing it?

For me, the configuration file of brew-installed `ocamlfind` is in `/usr/local/etc/findlib.conf`. If the same, or in another place, you may set the variable `OCAMLFIND_CONF` to the actual path. See `man findlib.conf` for more.

Alternatively, you may try to reinstall the `ocaml-findlib` brew package.
