### ISSUE TITLE
Wrong instructions for install-from-source in 8.17rc1

### ISSUE THREAD

**Issue by xavierleroy** [coq/coq#17374]
In Coq 8.17rc1, `make help-install` says:
```
The Dune-based Coq build is split in packages; see Dune and dev/doc
documentation for more details. A quick install of Coq alone can done with

 ./configure -prefix <install_prefix>
 make dunestrap
 dune build -p coq-core,coq-stdlib && dune install coq-core coq-stdlib
```
When I follow these instructions, Coq is NOT installed in `<install_prefix>`, but overwrites the OPAM Coq package I have in my current OPAM switch, e.g. `$HOME/.opam/4.14.1/lib/coq`.  (Talk about a destructive install!)

This is definitely unwanted, and hard to clean up afterward, and should be prohibited by the Geneva convention.

**Comment by Zimmi48** [comment]
I think there is no way this can be fixed for 8.17.0 other than by fixing the documentation (which clearly should mention that `dune install` should be used with care with the right arguments).

cc @coq/build-maintainers

**Comment by xavierleroy** [comment]
> fixing the documentation (which clearly should mention that dune install should be used with care with the right arguments).

That would be great.  Thanks!

**Comment by Alizter** [comment]
I think we are just missing the `--prefix` argument to `dune install` in the doc. I don't think there is anyway for `dune install` to know this from how we configure Coq AFAIK.
