### ISSUE TITLE
Extraction is unsoundly allowed inside module functors

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#17395]
#### Description of the problem

```coq
Require Import Extraction.

Module Type S.
Parameter boo : forall {T}, T.
End S.

Module F (Import X : S).
  Definition bang :=
    @eq_rect bool true (fun b => if b then nat else unit -> unit) O false boo tt.
  Recursive Extraction bang. (* let bang = Obj.magic O Tt *)
  (* type unit0 =
     | Tt

     type nat =
     | O
     | S of nat

     (** val bang : unit0 **)
     let bang =
     Obj.magic O Tt
   *)
  (*
  $ ocamlc a.ml
  $ ./a.out
[1]    77507 segmentation fault (core dumped)  ./a.out
  *)

  Definition boom : unit -> unit := @Fix unit (fun _ _ => True) boo (fun _ => unit)
    (fun x rec => rec x boo).
  Compute boom tt.
  Extraction boom. (* let rec boom = boom *)
End F.
```

inside sections, `Extraction` says "You can't do that within a section." At least an informative and specific warning would be nice.

Both of these restrictions are a pity from the perspective of a wish for "extraction compute" that would not get stuck on opaque Wf proofs.

#### Coq Version

8.16.1

**Comment by herbelin** [comment]
What is the report about? The "unsoundness" is not related to working inside a functor, right? The unsoundness is related to extraction dropping an unsatisfiable propositional precondition as in the module-free variant:
```coq
Require Import Extraction.
Parameter boo : forall {T}, T.
Definition bang := @eq_rect bool true (fun b => if b then nat else unit -> unit) O false boo tt.
Recursive Extraction bang. (* "let bang = Obj.magic O Tt", similarly executing into a segfault *)
```
And, indeed, there is no contract of extraction that it is able to detect when a program relies on satisfiable assumptions (such as `boo` here). So, this is the responsibility of the programmer to use the extracted program in a consistent context.

Or is the report about `Warning: Extraction inside an opened module is experimental. In case of problem, close it first`? If so, the warning is relaxed in #17344.

And (apparently) the report is also about the message in sections: "You can't do that within a section." which should be more informative about the "that", right?

> Both of these restrictions are a pity from the perspective of a wish for "extraction compute" that would not get stuck on opaque Wf proofs.

I'm sorry but I'm unsure to get which restrictions you are exactly talking about? Are you talking about the warning in the functor and of the forbidding in a section, or of something else?

**Comment by herbelin** [comment]
I continued thinking to your use of a module. If the objective was to get some form of abstraction preventing the erasure of the unsatisfiable proposition, an approach like below is maybe (??) what you would like:
```coq
Require Import Extraction.
Parameter boo : forall {T}, T.
Extract Constant id  => "assert false" .
Definition bang := id (@eq_rect bool true (fun b => if b then nat else unit -> unit) O false boo) tt.
(* let id = assert false   let bang = Obj.magic id O Tt *)
```
