### ISSUE TITLE
Build instructions for global installation of Coq

### ISSUE THREAD

**Issue by kwilczek** [coq/coq#17413]
Dear All,

I'm trying to make an installation of `coq` available to each user on our students' server (multiuser Debian 11 server). In order to build the newest 8.16.1 version I tried to use Opam. The system version of Opam and other libraries is too old for the 8.16.1, so I created a switch and installed all required build dependencies. I ran `./configure -prefix /opt/coq.8.16.1 -coqide byte` and later I had to run `sudo dune install --prefix ...` to install the `coq` globally in `/opt`. In general it worked, but the `coq` has dependencies for Opam located in my home directory. When trying to run a `coqtop` as another user I get the followin error:

```
Error:
Anomaly
"Uncaught exception Failure("Config file not found - neither
/my/user/.opam/coq8161/lib/findlib.conf nor the directory
/my/user/.opam/coq8161
/lib/findlib.conf.d")."
```

My goal is to have `coq` available for all users in `/opt/coq.8.16.1`. Is there a flag for `./configure` I missed or maybe another setting? Can `coq` be build "statically", without such dependencies and installed globally? I cannot use `snap`.

**Comment by herbelin** [comment]
This seems to have some relation with #17376, where the configuration file of `ocamlfind` is not found at running time.

This seems related to 7fb95918 which delegated the finding of the path for the coq's library to `ocamlfind` (but `ocamlfind` is itself still dependent on the opam directory).

Possible workarounds could be to:
- call coqtop with option `-coqlib /opt/coq.8.16.1/lib` (or appropriate path)
- set the variable COQLIB to  /opt/coq.8.16.1/lib
- copy the `ocamlfind` configuration files from local opam to global `lib/findlib.conf.d`.

There are experts around who could better answer but:

>  Is there a flag for ./configure I missed

I would say no. coq depends on `ocamlfind` but `ocamlfind` is installed independently of coq.

> Can coq be build "statically"

Similiarly, `ocamlfind` is an external tool which has no reason to be statically built with coq.

**Comment by Zimmi48** [comment]
Debian already has packages for Coq 8.16.1 available: https://packages.debian.org/source/bookworm/coq (not in Debian 11, but maybe they would work on Debian 11). Have you considered using them instead of building from sources?

Another option would be to use Nix...

**Comment by kwilczek** [comment]
@Zimmi48 Yes, trying the Bookworm version was my first guess, but the dependencies are not met. I did not try Nix, I do not have any experience with it and cannot allow any tool to make automated changes to the system.

**Comment by Zimmi48** [comment]
Given his work on making a Coq installation relocatable (after being compiled with opam under Windows for the Coq Platform), @MSoegtropIMC might have some clues that could be of help.

**Comment by MSoegtropIMC** [comment]
@kwilczek : the Coq Platform creates snap installers for Linux which has similar issues. To make Coq relocatable, one needs an extension of ocamlfind which can be found here:



Note: currently the Coq Platform Snap CI is broken cause Ubuntu messed up the virtualisation system for snap

**Comment by MSoegtropIMC** [comment]
@kwilczek : as I said, you don't really need snap to use it. You can just take a standard Coq snap package and expand it to wherever you want, say under /opt/coq. With the relocation support I built in this should work (I test similar things regularly).

Of course if you need s specialised package list, you need snap installed to actually build snaps, but you don't need snap installed on the computer on which you want to use it.

Of course it does no harm to use snap "proper" either - it does e.g. handle system dependencies automatically for you.

Please note that LXD is broken, so you should use multipass as virtualisation system when building a snap.

Please also note that there are Debian packages for Coq and many parts of Coq Platform which we try to keep in sync with Coq Platform as much as possible.

**Comment by kwilczek** [comment]
> @kwilczek : as I said, you don't really need snap to use it. You can just take a standard Coq snap package and expand it to wherever you want, say under /opt/coq. With the relocation support I built in this should work (I test similar things regularly).

Ah, now I understand. I just tested it and it seems to work, also the IDE works wihtout problems. I mounted the `.snap` file and copied `coq-platform` directory as `/opt/coq.8.16.1`. I assume I do not need the rest of the snap contens.

This (maybe with some minor changes) could be the accepted way of minimal installation of the Coq without introducing additional dependencies in the system.

Thanks again, great work!

**Comment by ejgallego** [comment]
Hi @kwilczek , installing Coq requires an OCaml findlib toolchain to be available in order to run it. For a global install, this can be achieved in several ways:
1. use the OCaml version your distribution ships, this will place the OCaml in /usr/lib usually
2. use a custom OCaml version and put in the directory you would like, then use OCAMLFIND_CONF to point where it is.

You problem seems to stem from the fact that you compiled you own ocaml at `/home/myuser`, however Coq is not able to read that file with the user you are running it.

IMHO 1 would be the easiest for you, you can indeed compile then Coq using "system" OCaml with the usual `configure + build + install` cycle.

Note that while patching ocamlfind makes user experience easier, you can achieve a functional setup with envars too.

**Comment by kwilczek** [comment]
> Hi @kwilczek , 

Hi,

installing Coq requires an OCaml findlib toolchain to be available in order to run it. For a global install, this can be achieved in several ways:
> 
>     1. use the OCaml version your distribution ships, this will place the OCaml in /usr/lib usually
> 

I tried to do it in the first place, but system packages are too old. If I install `ocamlfind` using system `opam`, the environment is starting to use my private `ocaml`. This break things. It seems that I cannot do this using only the system packages.

>     2. use a custom OCaml version and put in the directory you would like, then use OCAMLFIND_CONF to point where it is.
> 

It would be a mess and an overkill I think. I already have Ocaml from the system repository. In general I do not need the second one -- I would only use it to support Coq. I mean, in general, this approach is quite difficult and requires hacks. I'm a fan of simplicity wherever possible and the solution that @MSoegtropIMC presented seems to be ideal for now. Coq inside the `.snap` is alredy built and more-or-less production ready. All dependencies are easily met in any modern Linux distro I think.

> 
> You problem seems to stem from the fact that you compiled you own ocaml at `/home/myuser`, however Coq is not able to read that file with the user you are running it.

Yes, that is the problem :)

**Comment by ejgallego** [comment]
`opam` doesn't support multi-user installs, so indeed trying to use it for this purpose is going to be tricky.

Is nix better in this respect? Anyways this is a package manager issue and not a Coq issue per-se.

Coq can be built and installed globally without a problem.
