### ISSUE TITLE
"Algebraic universe on the right" is underinformative and should specify where the algebraic universe is coming from

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#17464]
#### Description of the problem

Consider
```coq
Polymorphic Definition foo@{u} (x : Type@{u+1}) := x.
Definition bar (x : Type) := foo x.
(* Error: Algebraic universe on the right *)
```

The error message does not specify what the algebraic universe is, nor where it's coming from.  I ran into this because I accidentally wrote `Definition foo@{u} (A : Type@{u+1}) : Type@{u}` instead of `Definition foo@{u} (A : Type@{u}) : Type@{u+1}` in my code; the `u+1` is necessary to write code that works with both `Set Universe Checking` and `Unset Universe Checking`, and the thing I'm asking for here is that Coq give me a bit more help in finding where I made my mistake in writing algebraic universes.

#### Coq Version

8.16

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/issues/17464 locates the error on the `x` in `:= foo x`

**Comment by JasonGross** [comment]
> #17464 locates the error on the `x` in `:= foo x`

I take it you mean #17504?  (#17464 is this issue)

**Comment by SkySkimmer** [comment]
yes

**Comment by SkySkimmer** [comment]
(https://github.com/coq/coq/pull/17505 produces the same location but with a different message)
