### ISSUE TITLE
Recent change cause coqc to leak memory and fail

### ISSUE THREAD

**Issue by m-lindgren** [coq/coq#17461]
#### Description of the problem

A recent change to coq-dev broke UniMath/TypeTheory in the UniMath CI by causing compilation of one file to stall while memory consumption increased untill killed by the system. The same code compiled successfully with the coq-dev version available in docker-coq yesterday. 

To reproduce assuming you have an opam switch with coq-dev updated for today:
```
git clone https://github.com/UniMath/UniMath.git
cd UniMath
git clone https://github.com/UniMath/TypeTheory.git
dune build TypeTheory
```

This usually takes ~15 minutes for GitHub Actions to complete successfully, but some change to coq-dev in the past day or so cause it to fail on the file [DiscreteComprehensionCat.v](https://github.com/UniMath/TypeTheory/blob/master/TypeTheory/CompCats/DiscreteComprehensionCat.v). When building it locally the `coqc` process stalls on this file and memory consumption increases way beyond what it has ever done before (~30GB before my system killed it). 

Stepping through the problematic file with coqtop the issue seems to be triggered [here](https://github.com/UniMath/TypeTheory/blob/e7fc5a0c4564afc44b084d134e4110d447b68404/TypeTheory/CompCats/DiscreteComprehensionCat.v#L553).

Here's a recent failed CI run: https://github.com/UniMath/UniMath/actions/runs/4592094964/jobs/8118776466#step:6:818

#### Coq Version

The Coq Proof Assistant, version 8.18+alpha
compiled with OCaml 4.14.1

(Sorry, is there a way to get the specific git SHA that coqc is compiled from? 8.18+alpha doesn't seem very informative.)

**Comment by SkySkimmer** [comment]
Seems due to https://github.com/coq/coq/pull/17438

You can workaround by replacing the 2 `apply idpath` at https://github.com/UniMath/TypeTheory/blob/e7fc5a0c4564afc44b084d134e4110d447b68404/TypeTheory/CompCats/DiscreteComprehensionCat.v#L553-L554 with `exact idpath` or `intros;cbv;apply idpath`

**Comment by m-lindgren** [comment]
Thank you for looking into this so quickly. With the workaround applied everything is green on our side.

**Comment by JasonGross** [comment]
> Sorry, is there a way to get the specific git SHA that coqc is compiled from? 8.18+alpha doesn't seem very informative.

`true | coqtop` generally prints the sha for development versions, I believe.  e.g.,
```
Welcome to Coq JasonGross-X1:/home/jgross/Downloads/coq/coq-master/_build/default,master (85092c51e1bc2a123831c7ab4f5efa86d93116cd)

Coq <
```
on my machine
