### ISSUE TITLE
Dynlink Error when trying to add merlin-lib as dependency

### ISSUE THREAD

**Issue by alpaylan** [coq/coq#17490]
#### Description of the problem

I want to use `merlin-lib.kernel` as part of a project involving modifying the extraction plugin, I added it to the relevant `dune` file and ran `dune build -p coq-core,coq-stdlib,coq` as I received the following error

```
File "theories/extraction/Extraction.v", line 11, characters 0-66:
Error:
Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"dlopen(/Users/<project-path>/coq/_build/default/plugins/extraction/extraction_plugin.cmxs, 0x000A): symbol not found in flat namespace '_camlMerlin_kernel__Mconfig'\")")

```

My dune file is;

```
(library
 (name extraction_plugin)
 (public_name coq-core.plugins.extraction)
 (synopsis "Coq's extraction plugin")
 (libraries 
  coq-core.plugins.ltac 
  merlin-lib.kernel
 ))

(coq.pp (modules g_extraction))
```

#### Coq Version

I am using

```
The Coq Proof Assistant, version 8.18+alpha
compiled with OCaml 5.0.0
```

**Comment by SkySkimmer** [comment]
IIRC the stdlib currently loads plugins in legacy mode (no findlib) so the merlin dependency doesn't get loaded.
I don't remember why we do this (some issue trying to make it work with the build system I guess)

**Comment by SkySkimmer** [comment]
Not sure if there's a way to get coq to dynlink non plugin libraries currently. You can try `Declare ML Module "merlin-lib.kernel"` but IIRC Declare ML Module expects the thing it loads to end in .plugin somehow.
The easiest solutions I think are either to copy the extraction plugin outside the stdlib making it an external coq_makefile or dune plugin, or statically link merlin by adding it as a dependency to some statically linked part of coq.

**Comment by ejgallego** [comment]
> I don't remember why we do this (some issue trying to make it work with the build system I guess)

There were some problems and bugs with the way coqdep worked that prevented us to use the new method, but I think Rodolphe fixed all the bugs, so we can remove the legacy mode when we want. Dune rules as of Dune 3.7 I think should work, our own rules need the change to depend on the right META file so plugins can be found, as is done in Dune upstream.

**Comment by SkySkimmer** [comment]
Possibly related discussion at https://coq.zulipchat.com/#narrow/channel/237656-Coq-devs-.26-plugin-devs/topic/findlib.20loading.20and.20plugins.20checksum

My conclusion is that when `foo.v` contains `Declare ML Module "bar"` and bar depends on baz, and `foo2.v` contains `Require foo`,
- coqdep should say `foo.vo : bar.cmxs baz.cmxs` and `foo2.vo : foo.vo`
- coqc should embed the hashes of bar.cmxs and baz.cmxs in foo.vo and the hash of foo.vo in foo2.vo

Currently coqdep says `foo.vo : bar.cmxs` and `foo2.vo : foo.vo`, and coqc embeds the hash of bar.cmxs (but not baz.cmxs) in foo.vo and the hash of foo.vo in foo2.vo

also coqdep should stop looking for a mlpack and should only use findlib to find plugins

**Comment by ejgallego** [comment]
I share @SkySkimmer 's view, see the discussion indeed to find out more about the different tradeoffs.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/19857
