### ISSUE TITLE
<in exception printer>:<original exception: Anomaly "Uncaught exception Not_found." Please report

### ISSUE THREAD

**Issue by leonard-tokic** [coq/coq#17514]
#### Description of the problem
Matching against a simpe inductive type works in A, but gives `<in exception printer>:<original exception: Anomaly "Uncaught exception Not_found." Please report` in B:

```
Inductive leq (a:nat) : nat->Type :=
|leq_refl : leq a a
|leq_half_S (b:nat) (H:(leq a b)) : leq a (S b).

Definition A (l:(leq 0 0)) : (l=(leq_refl 0)) :=
match l with
|leq_refl _ => eq_refl
end.

Definition B (a:nat) (l:(leq a a)) : (l=(leq_refl a)) :=
match l with
|leq_refl _ => eq_refl
end.
```

#### Coq Version
The Coq Proof Assistant, version 8.16.1
compiled with OCaml 4.13.1

**Comment by ejgallego** [comment]
This works fine in master and 8.17

**Comment by SkySkimmer** [comment]
Possibly duplicate of https://github.com/coq/coq/issues/16745
