### ISSUE TITLE
Ltac2 should internally distinguish between int and boolean

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#17556]
Internally, Ltac2 should distinguish between int and boolean types so that the debugger can show `true` or `false` instead of `1` or `0`.  In the screenshot, `ev` in `exact0` is clearly a boolean.  `true` and `1` are not interchangeable in scripts.  That means adding a new case for`Tac2ffi.valexpr`.

![image](https://user-images.githubusercontent.com/1253341/235312679-5799cf63-3d89-4689-a517-25662faa85de.png)

**Comment by SkySkimmer** [comment]
This is how it's supposed to work, ltac2 values need typing information to be printed https://github.com/coq/coq/blob/afc4a72c536e96dfab3901f0503da5931fa597ab/plugins/ltac2/tac2print.mli#L51

Ltac2 bool is a regular user type https://github.com/coq/coq/blob/afc4a72c536e96dfab3901f0503da5931fa597ab/user-contrib/Ltac2/Init.v#L50

**Comment by jfehrle** [comment]
I need something like `Tac2print.pr_valexpr (Global.env ()) SIGMA valexpr TYPEXPR`?

- How do I get `TYPEXPR` (type `'a glb_typeexpr`) from a `valexpr`?  If that's not readily available, is it feasible to provide it later on?  
- How do I get `SIGMA`?  From the monoids somehow?   I see `Evd.get_extra_data sigma` in `Tac2interp.get_backtrace` but `sigma` is a function parameter, so not clear how I get that.  (I suppose passing an empty `evar_map` would work for some, maybe many cases.)  And it needs to have correct info even in the middle of an Ltac2 tactic.

FWIW `Tac2ffi.to_pp`, which calls `Tac2ffi.to_ext`, seems useless in its current form.  It only handles 1 of 8 variants in `valexpr`.  And it's distracting because its existence suggests that it is useful.

**Comment by ppedrot** [comment]
> How do I get TYPEXPR (type 'a glb_typeexpr) from a valexpr?

You can't. You need to pass it from somewhere else.

> How do I get SIGMA? From the monoids somehow?

(What do you mean by that? The last sentence doesn't make sense to me.) You can get it through the usual combinator tclEVARMAP.

> FWIW Tac2ffi.to_pp, which calls Tac2ffi.to_ext, seems useless in its current form.

It doesn't do what you think it does. It's used to project a custom-tagged value from Ltac2 runtime values, and has literally nothing to do with printing. All other functions in this API follow the same convention.

To be honest, I am afraid that writing a debugger for a language without understanding its runtime semantics is bound to result in concentrated nonsense. You should start doing that before writing a single line of code. FTR the Ltac2 runtime is inspired by the OCaml one, and follows a standard untyped cbv model with tagged values hosted in the implementation language (i.e. OCaml) where effects are implemented through a monadic encoding à la Moggi. I personally don't know if there is a meaningful (or at least humanly intelligible) notion of backtraces for arbitrary monads but I suspect some people looked into that, probably people in the delimited continuation or call-by-push-value communities.

In any case, I concur with @SkySkimmer that the original issue is explicitly not an issue, so closing again after having answered.

**Comment by jfehrle** [comment]
Does the tag in `ValExt : 'a Tac2dyn.Val.tag * 'a -> valexpr` give enough information to print its value (and if so, how)?  In particular, I think users will want to see the value of `constr`s.
