### ISSUE TITLE
coqdep error could not find META.* should not be fatal

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#17567]
It breaks minimization resumption, and moreover seems like its triggered spuriously

-------

I'm not sure this is a bug in the minimizer?  It seems just as likely that it's a bug in the runner infrastructure or in Coq itself, or perhaps in the way the rewriter is set up. The actual issue is that when minimization resumed, when it ran
```
/github/workspace/builds/coq/coq-passing/_install_ci/bin/coq_makefile COQC = /github/workspace/builds/coq/coq-passing/_install_ci/bin/coqc.orig COQDEP = /github/workspace/builds/coq/coq-passing/_install_ci/bin/coqdep -o Makefile44j2imgx.coq -R /github/workspace/builds/coq/coq-passing/_build_ci/rewriter/src/Rewriter Rewriter -Q /github/workspace/cwd Top -Q /github/workspace/builds/coq/coq-passing/_install_ci/lib/coq/user-contrib/Ltac2 Ltac2 -Q /github/workspace/builds/coq/coq-passing/_install_ci/lib/coq/user-contrib/Rewriter Rewriter -I /github/workspace/builds/coq/coq-passing/_build_ci/rewriter/src/Rewriter/Util/plugins -R /github/workspace/builds/coq/coq-passing/_build_ci/rewriter/src/Rewriter Rewriter -Q /github/workspace/cwd Top -Q /github/workspace/builds/coq/coq-passing/_install_ci/lib/coq/user-contrib/Ltac2 Ltac2 -Q /github/workspace/builds/coq/coq-passing/_install_ci/lib/coq/user-contrib/Rewriter Rewriter -I /github/workspace/builds/coq/coq-passing/_build_ci/rewriter/src/Rewriter/Util/plugins -arg -q -arg -w -arg +implicit-core-hint-db,+implicits-in-term,+non-reversible-notation,+deprecated-intros-until-0,+deprecated-focus,+unused-intro-pattern,+deprecated-hint-constr,+fragile-hint-constr,+variable-collision,+unexpected-implicit-declaration,+omega-is-deprecated,+deprecated-instantiate-syntax,+non-recursive,+deprecated-hint-rewrite-without-locality,+deprecated-hint-without-locality,+deprecated-instance-without-locality,+undeclared-scope,+deprecated-typeclasses-transparency-without-locality,+future-coercion-class-field,unsupported-attributes -arg -w -arg -notation-overridden,-unusable-identifier -arg -w -arg -notation-overridden -arg -w -arg -deprecated-native-compiler-option -arg -native-compiler -arg ondemand bug_01.v
```
followed by
```
make -k -f Makefile44j2imgx.coq KEEP_ERROR=1 bug_01.glob
```
the result was (after many "required file matches multiple file in path" warnings)
```
*** Error: 
in file bug_01.v, could not find META.coq-rewriter.
make: *** No rule to make target 'bug_01.glob'.
```
and as a result the minimizer was unable to understand the `Require`s.  So because `coqdep` fails fatally with this error, `make` never gets around to making the `.glob` file.

_Originally posted by @JasonGross in https://github.com/JasonGross/coq-tools/issues/156#issuecomment-1534055669_

cc @SkySkimmer @ejgallego ?

**Comment by JasonGross** [comment]
Logs from [the minimization run](https://github.com/coq-community/run-coq-bug-minimizer/actions/runs/4875978046/jobs/8698881794): [logs_1457.zip](https://github.com/coq/coq/files/11392752/logs_1457.zip)
Other artifacts:

[metadata.zip](https://github.com/coq/coq/files/11392759/metadata.zip)
[build.log.zip](https://github.com/coq/coq/files/11392760/build.log.zip)
[bug.v.zip](https://github.com/coq/coq/files/11392761/bug.v.zip)
[bug.log.zip](https://github.com/coq/coq/files/11392762/bug.log.zip)
[bug.verbose.log.7z.zip](https://github.com/coq/coq/files/11392771/bug.verbose.log.7z.zip)

**Comment by SkySkimmer** [comment]
It seems like it was a minimizer bug.
