### ISSUE TITLE
Anomaly if timeout is zero on Linux

### ISSUE THREAD

**Issue by Columbus240** [coq/coq#17579]
#### Description of the problem
Both `Timeout 0 Check nat.` and `Set Default Timeout 0. Check nat.` fail with the anomaly
`Error: Anomaly "Uncaught exception Unix.Unix_error(Unix.EINVAL, "setitimer", "")."`

To disable the `Default Timeout`, the correct command is `Unset Default Timeout.` as documented in the refman.

I think it'd be most natural if the argument to `Timeout` is required to be a positive natural number.
Two alternative solutions which both introduce a special case for zero:
* The timer is set, but the commands triggers a `Timeout!` error, no matter how long the command takes.
* No timer is set and no command triggers a `Timeout!` error. Treating it like infinity.

kind: anomaly

#### Coq Version
v8.18+alpha, Linux

**Comment by SkySkimmer** [comment]
Timeout 0 used to work with a behaviour of doing nothing AFAICT, but the synterp split means we deduct the synterp phase from 0 getting a negative value.

**Comment by Columbus240** [comment]
Thank you for fixing this bug and #17580!
