### ISSUE TITLE
field_simplify creates goal "False" in simple case

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#17584]
#### Description of the problem

I quite frequently run into the issue that `field_simplify` creates a goal `False` instead of some denominator <> 0 condition. Today I came across a particularly simple example:

```
Require Import Reals.

Open Scope R.

Goal forall (x y: R), x<>0 -> (y / x) * x = y.
intros.
(* field_simplify in goal works fine *)
field_simplify ((y / x) * x); [|assumption].
reflexivity.
Qed.

Goal forall (x y: R) (H: (y / x) * x = y), True.
intros.
(* field_simplify in hyp generates "False" as goal *)
field_simplify ((y / x) * x) in H.
Abort.

```

#### Coq Version

```
The Coq Proof Assistant, version 8.17.0
compiled with OCaml 4.14.1
```

**Comment by andres-erbsen** [comment]
The second goal has `x = 0` as a hypothesis:
```
x, y : R
H : x = 0

========================= (1 / 1)

False
```

**Comment by MSoegtropIMC** [comment]
Indeed. I have cases where `lra` cannot solve the resulting goal, but this can very well be an error on my side - I didn't look into the `False` goals.

So the behaviour of field appears to be correct, but it is not very nice for two reasons:
- the produced goals are different when rewriting in a hypothesis and in a goal, which is mildly confusing
- one has to make the goal the current goal to get sensible information about it, which costs time in proof development. Usually I first apply field, look at the resulting goals and then apply some more or less advanced tactics (usually one for all goals) to the goals produced by field. This is very efficient and only takes a few seconds per application of field.

**Comment by silene** [comment]
And this can be turned into an actual bug:
```coq
Goal forall x y, (/(x * y) = 0)%R -> True.
Proof. intros x y H.
field_simplify in H.
(* No product even after head-reduction. *)
```
