### ISSUE TITLE
Polymorphic Inductive Cumulativity causing match goal to distinguish "identical" terms

### ISSUE THREAD

**Issue by jlottes** [coq/coq#17593]
#### Description of the problem
```coq
Global Set Universe Polymorphism.
Global Set Polymorphic Inductive Cumulativity.

Record prd A B := pr { p1 : A ; p2 : B }.

Section foo.
  Universes i.
  Context {A:Type@{i}} (R:A -> A -> Prop) (op:prd A A -> A).
  Notation "x > y" := (R x y).
  Notation "x + y" := (op (pr _ _ x y)).
  Context (transitivity: forall x y z, x > y -> y > z -> x > z).

  Lemma foo x y z : x + y + z > y.
  Proof.
    refine (transitivity _ (x + y) _ _ _). 1: {
    Fail match goal with |- ?a + _ > ?a => idtac a end.
```
The "match goal" tactic succeeds if either universe polymorphism or polymorphic inductive cumulativity is turned off. At the point of failure, the proof state is
```
1 goal
A : Type
R : A -> A -> Prop
op : (prd A A) -> A
transitivity : forall x y z : A, (x > y) -> (y > z) -> x > z
x, y, z : A
______________________________________(1/1)
((x + y) + z) > (x + y)
```
and the expectation is for "match goal" to succeed with "?a" bound to "x + y". Turning on all low-level contents reveals the goal to be
```
R (op (pr@{i i} A A (op (pr@{i i} A A x y)) z)) (op (pr@{bug2.60 bug2.61} A A x y))
```
and so the two terms are not exactly identical, having different universe variables. Is it intended behavior for "match goal" to distinguish these terms? I'm not sure what a good resolution to this problem is: while I can change "(x + y)" to "op (pr@{i i} _ _ x y)" in the refine tactic to prevent the introduction of fresh universe variables, this feels rather unsatisfactory. The output of "Show Universes" at the point of failure is:
```
UNIVERSES:
 {bug2.61 bug2.60} |= i <= bug2.60
                      i <= bug2.61
ALGEBRAIC UNIVERSES:
 {bug2.59 bug2.58 bug2.57 bug2.52 bug2.51 bug2.50}
UNDEFINED UNIVERSES:
 bug2.61
 bug2.60
 bug2.59 := bug2.44
 bug2.58 := bug2.44
 bug2.57 := bug2.44
 bug2.56 := bug2.44
 bug2.55 := bug2.44
 bug2.54 := bug2.44
 bug2.53 := bug2.44
 bug2.52 := bug2.44
 bug2.51 := bug2.44
 bug2.50 := bug2.44
WEAK CONSTRAINTS:
 bug2.60 ~ i
 bug2.61 ~ i

Normalized constraints: 
```
and it seems to me that Coq already "knows" that these universe variables are or could be equivalent to "i".
#### Coq Version
8.17.0

**Comment by ppedrot** [comment]
There are many ways for terms to be equal, and no reason to use one over another. In your example, you use a non-linear pattern (`?a` appears twice) which is interpreted as syntactic equality where universes must be *the same*. They are unifiable as you observe, but they're not literally the same. I don't think there is a way to change this without wreaking havoc with backwards compatibility.

Note that non-linear patterns appearing across hypotheses or goal (e.g. match goal with [ H : ?X, H' : ?X |- ?X ] => ... end`) are checked for conversion, not syntactic equality. Conversion is again different from unification but closer to what you want with cumulativity.

As a workaround, you can expand the match:
```
    match goal with |- ?a + _ > ?b => match a with b => idtac a end end.
```
This works although I don't even remember the exact semantics of this construct, so I'll have to look at the code.

**Comment by SkySkimmer** [comment]
>They are unifiable as you observe, but they're not literally the same. 

In this case it is not important that they are unifiable because they are Irrelevant. So we can do https://github.com/coq/coq/pull/17600

**Comment by SkySkimmer** [comment]
I guess this is wontfix
