### ISSUE TITLE
Unexpected coqtop message.

### ISSUE THREAD

**Issue by akr** [coq/coq#17596]
#### Coq Version

```
% coqtop -v
The Coq Proof Assistant, version 8.17.0
compiled with OCaml 4.14.0
```

I found that the implicit arguments page in the Coq manual
https://coq.github.io/doc/master/refman/language/extensions/implicit-arguments.html#explicit-applications
shows the message after `Definition Relation := X -> X -> Prop.` as follows:

```
eq0_le0 is declared
Argument n is a trailing implicit, so it has been declared maximally
inserted.
eq0_le0' is declared
X is declared
Relation is defined
```

![eq0_le0_is_declared](https://github.com/coq/coq/assets/10538/b194dac1-1929-4ed5-8af2-5e237cbe57eb)

`Definition Relation := X -> X -> Prop.` does not declare `eq0_le0`, `n`, `eq0_le0'`, and `X`.
So, this message is very curious.

**Comment by SkySkimmer** [comment]
It seems to be related to the previous example block which does declare eq0_le0 etc but I don't understand why it gets repeated.
The code looks normal https://github.com/coq/coq/blob/269a26ea76a4e686e8744a23f4d86c3b6e831909/doc/sphinx/language/extensions/implicit-arguments.rst?plain=1#L371

**Comment by SkySkimmer** [comment]
Looks like it's because of the still open proof from `Goal forall A, compose id id = id (A:=A).`

**Comment by akr** [comment]
I see. "n is declared" is repeated as follows.

```
% coqtop
Welcome to Coq 8.17.0

Coq < Goal True.
1 goal
  
  ============================
  True

Unnamed_thm < Axiom n : nat.
n is declared

Unnamed_thm < Definition m := 0.
n is declared
m is defined
```
