### ISSUE TITLE
Ltac2 open_constr fails when multiple goals are focused

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#17608]
```
From Ltac2 Require Import Ltac2.
From Ltac2 Require Import Message.
Ltac2 msg s := print (of_string s).

Ltac2 u () := multi_match! 'True with
| _ => msg "multi_match"
end.
Goal True /\ True.
split; u ().   (* Uncaught Ltac2 exception: Not_focussed *)
```

However, multiple goals works as expected (and similar to Ltac1) for other constructs, e.g. for

```
Ltac2 u () := apply I; msg "simple".
Goal True /\ True.
split; u ().   (* No more goals *)
```

**Is this a bug or not yet implemented?
Will Ltac2 eventually support goal selectors?
What, if anything, should be documented about this for now?**

BTW, the standard spelling is "focused".  The interweb says:

```
  “Focused” and “focussed” are two spellings of the same word:

  Focused (one “s”) is the standard spelling of this term in modern English.
  Focussed (with a double “s”) is a rare variant spelling, although it is more
  common in British and Australian English than it is in American English.
```

**Comment by SkySkimmer** [comment]
Ltac2 already supports goal selectors.
Some tactics automatically focus, other tactics expect the caller to focus.
In this case it is not multi_match which focuses, it's the `'True` ie `open_constr:(True)`. The `apply` notation thunks the constr so it gets called in a focused context.
The doc should say that constr quotations expect to be called with exactly 1 goal under focus.

**Comment by jfehrle** [comment]
> Some tactics automatically focus, other tactics expect the caller to focus.

Is it only a few tactics (I'm guessing) that expect the caller to focus?  The doc should identify them.

Also, the Ltac2 chapter should have a subsection or paragraph explaining the focus considerations compared to Ltac1.  ("focus" is mentioned in passing in several places in the chapter.)
