### ISSUE TITLE
Ltac2 @ external questions

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#17609]
- What defines the types usable in `Ltac2 @ external`?  Is it (exactly) each XXX with a line `let t_XXX = coq_core "XXX"` in `tac2core.ml`?  Do we expect users will add additional types and additional externals, e.g. through a plugin?

- Is it possible to report the wrong number of parameters on line 3?

![image](https://github.com/coq/coq/assets/1253341/f7d05db9-c498-4902-a8b6-d7be4d3607db)

- Similarly, can the types of the parameters be checked on line 3 rather than when the code is called?  Also, it shouldn't be an "anomaly/Please report", it's a user error.

![image](https://github.com/coq/coq/assets/1253341/327801cc-cf0e-44c8-858a-6666e03821a0)

- Note: doc should mention use of list and array types (eg `int list` and `int array`)

**Comment by SkySkimmer** [comment]
This sort of question should really go in the zulip, not the github issues.
