### ISSUE TITLE
Anomaly "Uncaught exception Invalid_argument("String.create")." on some architectures

### ISSUE THREAD

**Issue by SnarkBoojum** [coq/coq#17749]
After the recent upload of Coq 8.17.0 to Debian, the build daemons notified me of some building issues with unimath - one is hurd crashing as usual, while the two others are the same problem both on i386 and armhf:
```
COQC UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/EquivalenceWhiskeredNonCurriedMonoidalCategories.v
File "./UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/EquivalenceWhiskeredNonCurriedMonoidalCategories.v", line 333, characters 2-10:
Error: Anomaly "Uncaught exception Invalid_argument("String.create")."
Please report at http://coq.inria.fr/bugs/.

make[4]: *** [build/CoqMakefile.make:844: UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/EquivalenceWhiskeredNonCurriedMonoidalCategories.vo] Error 129
make[4]: *** [UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/EquivalenceWhiskeredNonCurriedMonoidalCategories.vo] Deleting file 'UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/EquivalenceWhiskeredNonCurriedMonoidalCategories.glob'
make[3]: *** [build/CoqMakefile.make:410: all] Error 2
make[3]: Leaving directory '/<<PKGBUILDDIR>>'
make[2]: *** [Makefile:99: all] Error 2
```

The full logs can be found [here](https://buildd.debian.org/status/fetch.php?pkg=coq-unimath&arch=armhf&ver=20230420-2&stamp=1687036860&raw=0) and [there](https://buildd.debian.org/status/fetch.php?pkg=coq-unimath&arch=i386&ver=20230420-2&stamp=1687021761&raw=0).

Notice that it's not the pristine 8.17.0, but 8.17.0 and the workaround patch I mentioned in [this issue](//github.com/coq/coq/issues/17721).

**Comment by SkySkimmer** [comment]
Those are both 32bit platforms right?
What's the unimath version?

**Comment by SnarkBoojum** [comment]
I think they are 32bit indeed ; and the unimath version is 20230420.

If you need other versions (ocaml compiler or similar), you'll notice the logs list what packages are installed and which version.

**Comment by SkySkimmer** [comment]
So the error is on https://github.com/UniMath/UniMath/blob/v20230420/UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/EquivalenceWhiskeredNonCurriedMonoidalCategories.v#L333 (a Defined)

I'm guessing the generated VM bytecode is too large.

**Comment by SnarkBoojum** [comment]
It doesn't sound nice at all... ^_^'

**Comment by SkySkimmer** [comment]
Yeah it's probabky https://github.com/coq/coq/blob/3a7ef14c2cacc0d2ac618f8fba2b4b25ba201756/kernel/vmemitcodes.ml#L169

**Comment by SnarkBoojum** [comment]
Do I have a better course of action than disabling those architectures for the Debian package of unimath?

**Comment by ejgallego** [comment]
> Do I have a better course of action than disabling those architectures for the Debian package of unimath?

That seems like the best option to me, you could spend time trying to fix this, but what for? Anyone using unitmath is either on M1 or AMD64 (it will likely be unusable on others, even if it'd compile)

**Comment by SkySkimmer** [comment]
If you also catch Invalid_argument at https://github.com/coq/coq/blob/8768ba36dc650f7ded0df25028da8f45e48be03b/kernel/vmbytegen.ml#L896 it might work

**Comment by SnarkBoojum** [comment]
Adrien Nader pointed out to me that unimath has a [commit](https://github.com/UniMath/UniMath/commit/1716c078b00c18dcabf63f671e414d7ba33cb23c) which might work around the issue.
