### ISSUE TITLE
coq is not robust to async interruptions (typically memprof limits)

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#17760]
The check `Global.assert_not_synterp` relies on a flag that is not part of the summary.

Thus, it is not possible to recover safely from async interruptions. The flag setting should be protected with `Fun.finally` or equivalent.

**Comment by SkySkimmer** [comment]
It's set with Flags.with_option https://github.com/coq/coq/blob/76c04892fabfe9c0ce0bb0745e0ff5655e151828/vernac/synterp.ml#L529
which is basically Fun.finally isn't it?

**Comment by ejgallego** [comment]
There must be a problem with the way `Flags.with_option` is implemented as I can retrigger the problem reliably in the linked PR. `Flags.with_option` seems a bit strange, but indeed let me try to replace it with `Fun.protect`

**Comment by SkySkimmer** [comment]
I suspect there is problem with `noncritical` considering memprof exceptions to not be critical, so they get caught in some place.
Basically it needs to do something like https://github.com/coq/coq/blob/d41cc3a7709e29041623627d958dd8c71852b507/lib/cErrors.ml#L160

**Comment by ejgallego** [comment]
@SkySkimmer indeed this could be a solution; we could also get rid of the flag.

Tho, reviewing uses of `CErros.noncritical`, I have a problem seeing any really justified use for a catch_all exn clause in most of the code where it is used.

Only the toplevel / DM needs to deal with exceptions as the top part of the interpretation loop.

Should we make a code policy for this?

**Comment by ejgallego** [comment]
> Basically it needs to do something like

I agree that this is the right fix for 8.18 (and maybe for 8.17.2 even)

The main question is how we implement it, options I see are:
- move the `toplevel/dune` / `memtrace` hackery to `lib` and do the direct check
- extend the CErrors API to allow clients to mark extensions as must re-reraise

This is still a PITA but removing `noncritical` at all seems like a larger effort.

**Comment by SkySkimmer** [comment]
>extend the CErrors API to allow clients to mark extensions as must re-reraise

Does this have a risk of polluting backtraces? ie if noncritical becomes too complex would `with e when noncritical e -> let e = Exninfo.capture e in ...` stop working properly?

**Comment by ejgallego** [comment]
I don't know, I'm afraid my low-level OCaml expertise here is lacking.

**Comment by ejgallego** [comment]
I see the 8.18.0 milestone is closed but this bug has not been handled properly.

What should be done, IMHO this is critical for 8.18 uses and the fix number 1 easy enough.

**Comment by SkySkimmer** [comment]
@ejgallego if you want to make a PR I can review

**Comment by ejgallego** [comment]
Thanks @SkySkimmer , I will try to make a PR but I'm a bit short of time as of late.

**Comment by erikmd** [comment]
@SkySkimmer should this issue's milestone be updated to 8.19.2 ?
