### ISSUE TITLE
Anomaly when disabling a previously unbound notation in a custom grammar 

### ISSUE THREAD

**Issue by charguer** [coq/coq#17782]
In Coq 8.17.
```
Declare Custom Entry trm.
Disable Notation "'foo' _"  (in custom trm).
```
gives `Anomaly "Uncaught exception Not_found." `

If no custom entry is involved, a proper error message is produced: `Found no matching notation to enable or disable. `

**Comment by herbelin** [comment]
Thanks for noticing. Fixed by #17891.
