### ISSUE TITLE
Ltac2 imprecise typechecking errors in match branches

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#17869]
Consider the following snippet, where the user passes `h` instead of `[h]` to `Std.clear`:

```coq
Require Import Ltac2.Ltac2.

Goal True -> True.
  intros.
  lazy_match! goal with
  | [h: True |- _] => (* lots of code... *) Std.clear h (* more code... *)
  | [|- _] => (* lots of code... *) ()
  end.
```

It produces the following unhelpful error (whose location is the whole `lazy_match!` until the `end`):

```
Error: This expression has type
(((Pattern.match_kind * pattern) list * (Pattern.match_kind * pattern)) *
  (ident list array -> 'c -> 'b -> 'a -> unit)) list
but an expression was expected of type
(((Pattern.match_kind * Pattern.t) list * (Pattern.match_kind * Pattern.t)) *
  (ident array -> Pattern.context array -> constr array -> Pattern.context -> 'a)) list
```

(This is the error in Coq 8.16, and I assume that on master, it would be even a bit longer, because the lambdas [got one more argument for hyp bodies](https://github.com/coq/coq/commit/8ef791a2ab57f08794123f9dbcd057f7bb8c95e5))

Fixing such a trivial error should be really quick, but I actually had to comment out parts of my code in a binary-search fashion until I found the error.
User-friendlyness could certainly be better here: An error whose location is just the `h` which says:

```
Error: This expression has type ident but an expression was expected of type ident list
```

I was trying to browse the code to find out how to possibly improve these errors, and IIUC, these branch lambdas of type `(ident array -> Pattern.context array -> constr array -> Pattern.context -> 'a)` get constructed here:

https://github.com/coq/coq/blob/fa7eebcb7c96953b562a50b46efe65fe043ac4ac/plugins/ltac2/tac2quote.ml#L499-L503

Each of these 5 lines corresponds to one parameter of the branch lambda (but their order is reversed, and there's now one more for hyp bodies which is not present in my error message from 8.16), and it seems that the arguments of the lambda being constructed don't have type annotations: The first line constructs a `CTacFun` by passing it an untyped `CPatVar`, but could pass it a typed `CPatCnv` instead, and the following 4 invocations of `abstract_vars` don't pass in the optional `?typ` argument.
I believe that if all these five arguments had type annotations, the typing error would already occur inside the branch lambda rather than when passing the whole list of branch lambdas to `Pattern.lazy_goal_match0`, and would result in much more precise errors.

@ppedrot  or other Ltac2 experts, does that sound like a good direction to further explore? And also, is there some code that constructs Ltac2 type ASTs where I could learn how to build the ASTs for types like `ident array`, `Pattern.context array`, `constr array`?

**Comment by SkySkimmer** [comment]
Possibly if ltac2 typechecking used bidirectionality it might improve the error enough

**Comment by samuelgruetter** [comment]
> Possibly if ltac2 typechecking used bidirectionality it might improve the error enough

ah yes, and I guess bidirectionality would also improve other error messages quite a bit. Is bidirectional type checking for Ltac2 being planned?

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/17924

**Comment by SkySkimmer** [comment]
Bidirectionality alone wouldn't improve this message because the notation turns into essentially `let m := (fun h => clear h) in lazy_goal_match0 m`, but it makes the annotation easier as we can do `let m : ident -> _ := ... in m` instead of having to annotate the subterms.
