### ISSUE TITLE
Question: is it possible to call coqc to check parsing errors only ?

### ISSUE THREAD

**Issue by fblanqui** [coq/coq#17867]
#### Description of the problem

I have many big (generated) Coq files. Type-checking is too long. I would like to first check the absence of parsing errors. Is it possible?

**Comment by Zimmi48** [comment]
Since AFAIU parsing and execution was recently separated (#15409) for the benefit of VsCoq2, a way to do so might be to open these files in VsCoq2. I might be wrong, as I haven't tested it, but my understanding is that parsing errors should be flagged immediately.

**Comment by ejgallego** [comment]
@fblanqui you can use SerAPI for that, use `sercomp --mode=parse file.v`.

It is not perfect as it will sometimes execute stuff, so YMMV, but I think that in your case it will work fine as you are not likely to insert commands that force the full state in the middle of a .v file.

**Comment by fblanqui** [comment]
Thank you for your solutions. Using VsCode is not very convenient as I have very big files (up to 2.5 Go in total). I can split them in many smaller files but there will be many and each one will still be of several Mo. So I need a command line to automate parse checking before running type checking. sercomp seems to work well. When will this feature be included in coqc as well?

**Comment by fblanqui** [comment]
Hi @ejgallego . Your parser doesn't seem very efficient:
```
20:17 ~/src/hol2dk (rename) time coqc foo_part_750.v

real	1m53,540s
user	1m41,784s
sys	0m6,948s
20:19 ~/src/hol2dk (rename) time sercomp -Q .,"" --mode=parse foo_part_750.v

real	1m32,003s
user	1m23,567s
sys	0m6,379s
20:21 ~/src/hol2dk (rename) du -s foo_part_750.v
2,1M	foo_part_750.v
2,1M	total
```
Actually, what I just need is to check used identifiers only to make sure that they are all valid. Is there a precise description of valid identifiers somewhere?

**Comment by ejgallego** [comment]
@fblanqui can you upload the test file somewhere?

**Comment by ejgallego** [comment]
> Actually, what I just need is to check used identifiers only to make sure that they are all valid. Is there a precise description of valid identifiers somewhere?

I'm unsure if they are fully described in the manual, but the code that checks for them is here:
https://github.com/coq/coq/blob/master/clib/unicode.ml#L260

**Comment by ejgallego** [comment]
Note that the `unicode_refutation` function can be used from other tools, you need to depend on `coq-core.clib` findlib package for it.

**Comment by fblanqui** [comment]
http://files.inria.fr/blanqui/foo.tar.gz

**Comment by SkySkimmer** [comment]
>Actually, what I just need is to check used identifiers only to make sure that they are all valid. Is there a precise description of valid identifiers somewhere?

I don't think that's possible without full parsing. For instance if you see `foo \in bar` is the `\in` some notation or is it an invalid identifier?
