### ISSUE TITLE
Diminishing gains despite file-level parallelism

### ISSUE THREAD

**Issue by mrhaandi** [coq/coq#17901]
#### Description of the problem

`coq_makefile` provides good file-level parallelism for projects with little intra-dependencies.
One could expect a roughly an n-time speedup with `make -j n`.
However, in my experience this is not the case.
For example [coq-library-undecidability](https://github.com/uds-psl/coq-library-undecidability/tree/master) regarding its structure should scale well up to 16 threads.
Compiled with 16 workers, almost always all 16 threads are busy on a modern 16-threaded CPU.
Surprisingly, compilation time improvements are negligible beyond 4 workers (tested on mac, windows+wsl, and linux).
Out of 24GB RAM at most 8 GB is used (so this should be not an issue).
The opam switch and compilation runs entirely in a ramdisk to avoid hard drive overhead.
The opam switch is `--packages=ocaml-variants.4.14.1+options,ocaml-option-flambda`.

It is unclear whether some make, filesystem, or kernel operations are responsible for diminishing returns.

Here is the output of `time make -j n` for `n = 1, 2, 4, 8, 16, ~`:

```
make -j1   398,10s  user 37,83s  system 99%   cpu 7:16,60 total

make -j2   423,52s  user 43,82s  system 198%  cpu 3:54,94 total

make -j4   524,38s  user 59,75s  system 393%  cpu 2:28,51 total

make -j8   875,30s  user 120,23s system 770%  cpu 2:09,12 total

make -j16  1665,57s user 253,12s system 1359% cpu 2:21,17 total

make -j    1632,54s user 246,46s system 1310% cpu 2:23,41 total
```

#### Coq Version

```
The Coq Proof Assistant, version 8.19+alpha
compiled with OCaml 4.14.1
```

**Comment by JasonGross** [comment]
As I understand it, the performance gains of hyperthreading are very questionable, so in practice even if you have 16 logical cores, you will won't see a performance gain past 8 threads (and you may want to turn off hyperthreading to avoid unlucky scheduling of two Coq processes on the same physical core).  This seems to me a plausible explanation of why going from -j8 to -j16 just doubles user and system time without having much impact (10% slower) on wall clock time.

The lack of improvement from -j4 to -j8 demands more explanation.  Could you turn hyperthreading off*, make sure you don't have a browser or any other hungry processes running, and run the -j{1,2,4,8} numbers again?

Setting that aside, the 2x jump in system time suggests to me that Coq is competing on access to disk (every Coq process has to load the standard library, presumably even on ramdisk this is considered system time?  is Coq saturating the throughput of the ramdisk, or is it some sort of lock contention ...?).  But this only explains about 7--8 seconds of the missing improvement from -j4 to -j8.

The increasing time spent in user mode is also suspicious; if in fact every Coq process gets a physical core to itself, then the user time should be constant even as the number of workers increases.  This makes me suspect that you might be getting unlucky scheduling of processes on different hyperthreads but the same physical core?

*Here is a script that will let you turn hyperthreading on and off (in Linux, at least) (I believe authored by @andres-erbsen):
<details><summary><code>hyperthreading.sh</code></summary>

```sh
#!/bin/sh
set -eu

usage() {
  echo "USAGE: $0 <on|off>" ; exit 111
}

if [ "$#" -eq 0 ]; then
  usage
fi

case $1 in
   on)
     for f in "/sys/devices/system/cpu/cpu"[0-9]*/online; do
       echo 1 > "$f"
     done
     ;;
  off)
    cores=""
    for cpu in "/sys/devices/system/cpu/cpu"[0-9]* ; do
      if grep -vq '^1$' "$cpu/online" 2>/dev/null; then
        continue
      fi
      coreid=$(cat "$cpu/topology/core_id")
      if echo "$cores" | grep -- "$coreid" ; then
        echo 0 > "$cpu/online"
      fi
      cores=$(printf "$cores\n$coreid")
    done
    ;;
  *) usage
esac
```
</details>

**Comment by mrhaandi** [comment]
Possibly, the problem is as follows: `coq-library-undecidability` contains many small, fast, mostly independent files which heavily rely on the standard library. `iostat` does not show any IO problems while separate `coqc` processes cannot `Require Import` more than around `4` stlib references in parallel on a machine with 8 physical cores.

For example: I created a test project containing 16 `.v` files with just the line `Require Import Reals.`
For your convenience, here is the test project [test.zip](https://github.com/coq/coq/files/12206603/test.zip)
Here, parallel compilation scales very poorly:
```
make -j1  2,86s user 0,77s system 99% cpu 3,651 total
make -j2  3,04s user 0,88s system 193% cpu 2,028 total
make -j4  3,45s user 1,23s system 369% cpu 1,266 total
make -j8  4,92s user 2,05s system 704% cpu 0,990 total
make -j16  10,07s user 4,01s system 1272% cpu 1,106 total
```

For comparison, if the files each contain some busywork instead of `Imports`, e.g.
```
Lemma busy : True.
Proof.
  assert (100 * 100 = 100 * 100).
  cbn. repeat f_equal.
  assert (100 * 100 = 100 * 100).
  cbn. repeat f_equal.
  constructor.
Qed.
```
performance scales reasonably (but still not perfectly).
I am trying to find out how to disable loading stdlib via `_CoqProject`  for performance comparison.

**Comment by JasonGross** [comment]
> I am trying to find out how to disable loading stdlib via `_CoqProject` for performance comparison.

I think you want `-arg -noinit`

**Comment by mrhaandi** [comment]
I tried `-arg -noinit` (and tested that I do not have basic definitions such as `True`).
Now I am even more confused about the scaling (am I doing something incorrectly?).
I put into each file some computational busywork:
```
Fail Check True.

Inductive nat : Type :=
  | O : nat
  | S : forall (_ : nat), nat.

Inductive eq {A:Type} (x:A) : forall (_ : A), Prop :=
  eq_refl : eq x x.

Fixpoint ack (n m : nat) : nat :=
  match n with
  | O => S m
  | S p => let fix ackn (m : nat) :=
               match m with
               | O => ack p (S O)
               | S q => ack p (ackn q)
               end
           in ackn m
  end.

Definition N := S (S (S O)).
Definition M := S (S (S (S (S (S (S O)))))).

Time Fail Definition busy : eq (ack N M) (S (ack N M)) := eq_refl _.
```
The parallel compilation (while I am now on a weaker machine with 4 physical cores) does not truly scale beyond two workers.

**Comment by mrhaandi** [comment]
I also tested running `coqc` manually using
`cp f1.v f2.v && cp f1.v f3.v && cp f1.v f4.v && cp f1.v f5.v && cp f1.v f6.v && cp f1.v f7.v && cp f1.v f8.v && cp f1.v f9.v && cp f1.v f10.v && cp f1.v f11.v && cp f1.v f12.v && cp f1.v f13.v && cp f1.v f14.v && cp f1.v f15.v && cp f1.v f16.v`
and then for 2 workers
`time ((coqc f1.v -noinit & coqc f2.v -noinit) && (coqc f3.v -noinit & coqc f4.v -noinit) && (coqc f5.v -noinit & coqc f6.v -noinit) && (coqc f7.v -noinit & coqc f8.v -noinit) && (coqc f9.v -noinit & coqc f10.v -noinit) && (coqc f11.v -noinit & coqc f12.v -noinit) && (coqc f13.v -noinit & coqc f14.v -noinit) && (coqc f15.v -noinit & coqc f16.v -noinit))`
vs 4 workers
`time ((coqc f1.v -noinit & coqc f2.v -noinit & coqc f3.v -noinit & coqc f4.v -noinit) && (coqc f5.v -noinit & coqc f6.v -noinit & coqc f7.v -noinit & coqc f8.v -noinit) && (coqc f9.v -noinit & coqc f10.v -noinit & coqc f11.v -noinit & coqc f12.v -noinit) && (coqc f13.v -noinit & coqc f14.v -noinit & coqc f15.v -noinit & coqc f16.v -noinit))`
with little speedup (just a the `user` time increase, but not `real`).

Does unification set some global lock?

**Comment by ejgallego** [comment]
@mrhaandi , you can try to build your Coq project with `dune` and use `dune build --trace-file=my_trace.json`.

Then open it in a browser like https://ui.perfetto.dev/ , that should allow you to understand what in your build is causing retention.

**Comment by ejgallego** [comment]
Indeed, it seems that the file dependency structure does prevent more parallelism :( See attached trace.

[clu.json.gz](https://github.com/coq/coq/files/12207573/clu.json.gz)

**Comment by mrhaandi** [comment]
@ejgallego Thanks for the trace. I myself do not know how to use `dune` to build _CoqProject and [building-a-coq-project-with-dune](https://coq.inria.fr/distrib/current/refman/practical-tools/utilities.html#building-a-coq-project-with-dune) did not help me as much.
Maybe the issue at hand is somewhat convoluted due to multiple factors. Looking at the actual `coq-library-undecidability` the numbers (while a little unexpected) are not too bad.

What confuses me most is that in the constructed examples
- 16 times `Require Import Reals.`
- 16 times `eq_refl` with `-noinit`

the scaling is questionable, as if there is some IO race condition. Would a trace be of help there?

**Comment by JasonGross** [comment]
> Would a trace be of help there?

Does system time keep doubling even with noinit?  If so, I would be curious to know (maybe from `strace`) what sort of system calls are taking time.

Also, did you manage to turn off hyperthreading?  If hyperthreading is still on, I wouldn't be surprised by unlucky core scheduling

**Comment by mrhaandi** [comment]
> Also, did you manage to turn off hyperthreading?

Yes, hyperthreading is off.

> Does system time keep doubling even with noinit? 

Yes. Here is the most concise way I get strange results:
1) Create `f1.v` containing
```coq
Fail Check True.

Inductive nat : Type :=  O | S (n : nat).

Inductive eq {A:Type} (x:A) : forall (_ : A), Prop :=
  eq_refl : eq x x.

(* Ackermann function, k is a dummy to force normalization *)
Fixpoint ack (k n m : nat) : nat :=
  match n with
  | O => S
  | S p => fix ackn (m : nat) :=
      ack k p match m with O => S O | S q => ackn q end
  end m.

Definition N := (S O).
Definition M := ack O (S (S (S O))) (S (S (S (S (S (S (S (S O)))))))).

Time Definition busy : eq (ack O N M) (ack (S O) N M) := eq_refl _.
```
2. Copy the file 16 times:
`cp f1.v f2.v && cp f1.v f3.v && cp f1.v f4.v && cp f1.v f5.v && cp f1.v f6.v && cp f1.v f7.v && cp f1.v f8.v && cp f1.v f9.v && cp f1.v f10.v && cp f1.v f11.v && cp f1.v f12.v && cp f1.v f13.v && cp f1.v f14.v && cp f1.v f15.v && cp f1.v f16.v`
3. Run `coqc -noinit` with 2 workers:
`time ((coqc f1.v -noinit & coqc f2.v -noinit) && (coqc f3.v -noinit & coqc f4.v -noinit) && (coqc f5.v -noinit & coqc f6.v -noinit) && (coqc f7.v -noinit & coqc f8.v -noinit) && (coqc f9.v -noinit & coqc f10.v -noinit) && (coqc f11.v -noinit & coqc f12.v -noinit) && (coqc f13.v -noinit & coqc f14.v -noinit) && (coqc f15.v -noinit & coqc f16.v -noinit))`
the result is 16 times
`Finished transaction in 6.637 secs (6.539u,0.097s) (successful)`
4. Run `coqc` with 4 workers:
`time ((coqc f1.v -noinit & coqc f2.v -noinit & coqc f3.v -noinit & coqc f4.v -noinit) && (coqc f5.v -noinit & coqc f6.v -noinit & coqc f7.v -noinit & coqc f8.v -noinit) && (coqc f9.v -noinit & coqc f10.v -noinit & coqc f11.v -noinit & coqc f12.v -noinit) && (coqc f13.v -noinit & coqc f14.v -noinit & coqc f15.v -noinit & coqc f16.v -noinit))`
the result is 16 times
`Finished transaction in 10.128 secs (10.047u,0.08s) (successful)`
while I would have expected each file not to consume much more time than previously.
4. Run `coqc` with 6 workers:
`time ((coqc f1.v -noinit & coqc f2.v -noinit & coqc f3.v -noinit & coqc f4.v -noinit & coqc f5.v -noinit & coqc f6.v -noinit) && (coqc f7.v -noinit & coqc f8.v -noinit & coqc f9.v -noinit & coqc f10.v -noinit & coqc f11.v -noinit & coqc f12.v -noinit) && (coqc f13.v -noinit & coqc f14.v -noinit & coqc f15.v -noinit & coqc f16.v -noinit))`
the result is 16 times
`Finished transaction in 13.36 secs (13.248u,0.11s) (successful)`.
Again, on physical 6 cores with no background activity (and hyperthreading off) this is strange.

For your convenience: `coqc f1.v -noinit` strace output: [strace.log](https://github.com/coq/coq/files/12207810/strace.log)

**Comment by ejgallego** [comment]
`-noinit` will still scan a lot of files as it initializes `user-contrib` etc... Try `-boot` instead, which tells Coq not to do any library guess.

**Comment by ejgallego** [comment]
@mrhaandi you have a dune port for the 8.17 branch here, a few files fail to compile tho, not sure why (they don't seem excluded in the _CoqProject file)

I'm not sure I understand your scalability experiment, 16 independent files are compiled in parallel , but indeed, the start up cost is not trivial for small files, due to both `.vo` parsing (demarshalling) and filesystem scanning (to build the vo path).

[`fcc`](https://github.com/ejgallego/coq-lsp) is trying to setup a mode where both operations are cached.

**Comment by mrhaandi** [comment]
> `-noinit` will still scan a lot of files as it initializes `user-contrib` etc... Try `-boot` instead, which tells Coq not to do any library guess.

Adding `-boot` does not change the results and lack of scaling in the above example. Most time is spent in unification. However, the `strace` is much cleaner: [strace_boot.log](https://github.com/coq/coq/files/12207926/strace_boot.log)

**Comment by ppedrot** [comment]
I personally don't know of any cross-process lock that coqc would rely on. You should probably strace the processes to see what's going on.

**Comment by mrhaandi** [comment]
Possibly, the unification (see `eq_refl _` example) scaling problem is because it is somewhat RAM-intensive. While the CPU has enough cores, RAM bandwidth is limited.

Can the above example be modified to be less RAM-intensive?

**Comment by mrhaandi** [comment]
After more testing, all examples (except for `Require Import Reals.`) are limited by RAM performance.
For example, `coq-library-undecidability` scales better (and compiles much faster, despite many stdlib references) with faster RAM speeds.
I consider this particular issue closed.
