### ISSUE TITLE
`Notation ... := Eval ... in ...`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#17904]
Maybe we should add the ability to write
```coq
Notation foo := Eval cbv in bar.
```
where the `Eval` is to be evaluated eagerly.  I've wanted this in a couple of my other projects as well.

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/17898#issuecomment-1656027958_

**Comment by herbelin** [comment]
That's a good idea but that's not so direct to implement as notations are currently not typed. They don't go up to `constr` while reduction works on `constr`. So, that would require a special treatment.

**Comment by JasonGross** [comment]
I'd be quite happy with a version of this that required `bar` to be a constr and forbid the `Notation` from having any arguments.  (Even better would be a version that allowed arguments.)

Said another way, the treatment of `Notation name args := Eval redexpr in (value) (modifiers).` would be:
1. (optional) Create a named context with evars for the types of args
2. Interpret / intern `value` in this context, including typing, etc
3. Reduce with redexpr
4. Detype the result, turning evars into holes
5. Drop evars, etc, and attach the value to `name` as an alias

**Comment by SkySkimmer** [comment]
Why is Definition not working for you?

**Comment by JasonGross** [comment]
> Why is Definition not working for you?

Definitions are not used for printing.  The context from the original issue is literally impossible to do with `Definition` (construct a user-space way of writing the primitive float `nan` which is syntactically stable under reduction).

In cases where printing is not required, it should be sufficient to do
```coq
Definition foo0 := Eval redexpr in bar.
Notation foo := (ltac:(let x := eval cbv [foo0] in foo0 in exact x)) (only parsing).
```

Sorry for taking so long to respond.  Why close this as wontfix?

**Comment by SkySkimmer** [comment]
Doesn't that mean rather that the issue is nan not having a way to represent it in syntax?

**Comment by JasonGross** [comment]
Perhaps.  I don't quite recall what I wanted this for in my other projects.

**Comment by SkySkimmer** [comment]
We do have number notations which can do reduction then go back to glob level so maybe this could be reopened?
eg at intern time `1` (a `CPrim` constr_expr) gets turned into something like `of_uint (D1 Nil)`  (at constr type IIUC), put through cbv, then the result is turned back into glob_constr
(D1 Nil from Decimal, of_uint picked based on notation scopes and declared number notations)

**Comment by ErrWare** [comment]
> I don't quite recall what I wanted this for in my other projects.

I'll chime in with my use case. I'm reading a lot of MetaRocq to learn how the `terms` are structured. I've found it very helpful to make notations for the quoted terms as I understand them. Thus I have the following, which required evaluating, copying, and pasting each term:

```
Notation "'_prod_'" := ({| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "prod"); inductive_ind := 0 |}).
Notation "'_option_'" := (tInd {| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "option"); inductive_ind := 0 |} []).
Notation "'_list_'" := ({| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "list"); inductive_ind := 0 |}).
Notation "'_sProp_'" := (tSort sProp).

Notation "'_Some_'" := (tConstruct {| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "option"); inductive_ind := 0 |} 0 []).
Notation "'_None_'" := (tConstruct {| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "option"); inductive_ind := 0 |} 1 []).
Notation "'_exit_'" := (tInd {| inductive_mind := (MPfile ["Picinae_core"; "Picinae"], "exit"); inductive_ind := 0 |} []).
Notation "'_bool_'" := (tInd {| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "bool"); inductive_ind := 0 |} []).
Notation "'_Nmind_'" := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N").
Notation "'_N_'" := (tInd {| inductive_mind := _Nmind_; inductive_ind := 0 |} []).
Notation "'_positivemind_'" := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive").
Notation "'_true_'" := (tConstruct {| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "bool"); inductive_ind := 0 |} 0 []).
Notation "'_false_'" := (tConstruct {| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "bool"); inductive_ind := 0 |} 1 []).
```
