### ISSUE TITLE
`Z.to_euclidean_division_equations` should support `Z.divide`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#17918]
Mostly as a reminder to myself to implement this (though someone else is welcome to take it), it should be pretty easy to get `Z.to_euclidean_division_equations` to support `Z.divide`, which is defined as `Z.divide = fun x y : Z => exists z : Z, y = (z * x)%Z`, just by adding, e.g., `Ltac divide_to_equations_step` that does something like `match goal with | [ H : Z.divide _ _ |- _ ] => destruct H end`, then adding the corresponding helper tactics, in `theories/omega/PreOmega.v`

**Comment by doctor-kaliy** [comment]
Hello, I attempted to do this. Please review.
