### ISSUE TITLE
Ltac2.Printf.fprintf should support character escapes; Ltac2.Message should be able to print newlines

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#17931]
#### Description of the problem

There doesn't seem to be a way to print newlines easily in Ltac2.  I've tried
```coq
From Ltac2 Require Import Ltac2 Printf Message.
Ltac2 Eval printf "\n".
Ltac2 Eval printf "a

a".
Ltac2 Eval print "a

a".
```

I guess we should maybe add
```coq
Ltac2 lf () := String.make 1 (Char.of_int 10).
Ltac2 cr () := String.make 1 (Char.of_int 13).
```
But it would be nice to have a newline that is correctly handled across platforms (unless printing lf already turns into \r\n on windows?)

#### Coq Version

8.17

**Comment by SkySkimmer** [comment]
>unless printing lf already turns into \r\n on windows?

I believe it should as we open everything in text mode, although IIRC there are some issues which want that changed.

**Comment by SkySkimmer** [comment]
However note that PG seems to turn newlines into spaces:
~~~coq
From Ltac2 Require Import Ltac2 Printf Message.

Ltac2 the_string () := "a

a".

Ltac2 Eval Char.to_int (String.get (the_string()) 1).
(* proofgeneral: 32
   everything else(? tested coqc, coqtop, coqide): 10
*)
~~~

**Comment by JasonGross** [comment]
Duplicate of https://github.com/ProofGeneral/PG/issues/428
