### ISSUE TITLE
Issue a warning when a notation declares different levels for the same term

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#17985]
#### Description of the problem

I accidentally wrote something like that:
```
Reserved Notation "'<<<' A '>>>' e '<<<' B '>>>'" (A, B at level 200, e, B at level 55).
```
(The actual notation was a lot bigger.)
It took me a while to realize that I have `B` at two different levels; Coq seems to then prefer the first level given. Ideally it should warn (or error) though and tell the user that they are declaring different levels for the same term.

#### Coq Version
8.17.0

**Comment by herbelin** [comment]
Good point. I tried to raise an error in PR #17988. If it fails too often, we can still make a warning.
