### ISSUE TITLE
Documentation incorrectly claims that `#[warnings=...]` is supported by every command

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#17982]
> I think you should use a local `#[warning]` attribute instead:
> 
> [coq.github.io/doc/master/refman/language/core/basic.html#coq:attr.warnings](https://coq.github.io/doc/master/refman/language/core/basic.html#coq:attr.warnings)

Oh, wow, this is exactly what I was looking for.  But it doesn't work, and the documentation lies when it says "The following attribute is supported by every command:"
```coq
Module Foo. #[warnings="-notation-overridden"] Infix "+" := Nat.mul : nat_scope. End Foo.
(* Warning: This command does not support this attribute: warnings.
[unsupported-attributes,parsing,default] *)
```

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/17920#issuecomment-1696543674_

**Comment by SkySkimmer** [comment]
Probably got broken by the parsing separation
