### ISSUE TITLE
refine incorrectly clears hypotheses producing ill typed goal

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#18049]
A refine command that has worked just fine for many versions of Coq, through Coq 8.16, fails in a crazy way in Coq 8.17.

The first difference is that (in Coq 8.17.1) `refine (ex_intro _ _ eq_refl)` clears all the hypotheses above the line except those mentioned in the goal;  in 8.16, the hypotheses were not cleared.

Now, the crazy part:  `refine` can leave ill-scoped hypotheses above the line.
Here's an example.  Before calling `refine` I have,

```
rsh, sh : share
gv : globals
fi, ti : val
f_info : fun_info
outlier : outlier_t
from, to : nat
Delta_specs := abbreviate : Maps.PTree.t funspec
g' : LGraph
t_info' : thread_info
index : nat
sp_to : space
l : list (reptype space_type)
used_offset, index_offset : Z
FR := abbreviate : list mpred
H23 : graph_has_v g' (to, index)
RamL := abbreviate : list mpred
RamG := abbreviate : list mpred
J := fst (RamG, H23) : list mpred
______________________________________(1/1)
exists
  H : fold_right_sepcon J
      |-- fold_right_sepcon RamL
            * (fold_right_sepcon [vertex_rep (nth_sh g' to) g' (to, index)] -*
               fold_right_sepcon [graph_rep g']),
  ?w = Freezer.FRZRw_constr H
```

and after `refine (ex_intro _ _ eq_refl)` I have,
```
rsh, sh : share
gv : globals
fi, ti : val
f_info : fun_info
outlier : outlier_t
from, to : nat
Delta_specs := abbreviate : Maps.PTree.t funspec
g' : LGraph
t_info' : thread_info
index : nat
sp_to : space
l : list (reptype space_type)
used_offset, index_offset : Z
FR := abbreviate : list mpred
RamL := abbreviate : list mpred
RamG := abbreviate : list mpred
J := fst (RamG, H23) : list mpred
______________________________________(1/1)
fold_right_sepcon J
|-- fold_right_sepcon RamL
      * (fold_right_sepcon [vertex_rep (nth_sh g' to) g' (to, index)] -*
         fold_right_sepcon [graph_rep g'])
```
Notice that H23 is mentioned in J, but not defined anywhere.  That's crazy.
```
Check H23.
The reference H23 was not found in the current environment.
```

To reproduce this bug:
~~~bash
git clone https://github.com/CertiGraph/CertiGraph
cd CertiGraph
git checkout refine-bug
opam switch [Coq Platform 2023.08, or anything with Coq 8.17.1 and VST 2.12]
make -j CertiGC/refine_bug.vo
~~~
Now, if you examine the last few lines of refine_bug.vo in an IDE, you can see the behavior described above.

**Comment by JasonGross** [comment]
Maybe we can get a smaller self-contained example
@coqbot minimize coq.8.17.1
```bash
git clone git@github.com:CertiGraph/CertiGraph.git
cd CertiGraph
git checkout refine-bug
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by JasonGross** [comment]
Let's try again 
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/CertiGraph/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by JasonGross** [comment]
Third time's the charm? 
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/JasonGross/CertiGraph.git --branch=patch-1
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by JasonGross** [comment]
Apparently there was a bug in the runner script that causes it to fail on `.//foo/bar.v` paths.  Fixed by https://github.com/coq-community/run-coq-bug-minimizer/commit/a73787669bafab297428718f0fd34a888254b970
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/JasonGross/CertiGraph.git --branch=patch-1
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by JasonGross** [comment]
26 seconds is also not trivial, since it's running the file many times.

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by SkySkimmer** [comment]
It got much faster, maybe because I manually modified the file to avoid most of the tactics before the problem appears or maybe it just got through enough to speed up.
Anyway let's have another round

@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by JasonGross** [comment]
@SkySkimmer the message got corrupted somewhere.  The original error is
```
J
     : list mpred
File ".//CertiGC/refine_bug.v", line 1111, characters 6-9:
Error: The reference H23 was not found in the current environment.

make: *** [Makefile:217:
```
But the latest files since https://github.com/coq/coq/issues/18049#issuecomment-1729916772 are erroring with
```
File ".//CertiGC/refine_bug.v", line 719, characters 6-7:
Error: The reference J was not found in the current environment.
```

**Comment by SkySkimmer** [comment]
I hand minimized to something simpler

**Comment by SkySkimmer** [comment]
@coqbot minimize coq.8.17.1
```bash
git clone https://github.com/skyskimmer/CertiGraph.git --branch=refine-bug
cd CertiGraph
opam update -y
opam install -y coq-vst.2.12
make -j CertiGC/refine_bug.vo
```

**Comment by JasonGross** [comment]
@SkySkimmer The behavior in the latest version of the file, as I understand it, amounts to the following:
```coq
Goal forall (x : nat) (f : nat -> nat), exists v : nat, nat -> exists h : nat, v = f h.
Proof.
  intros.
  eexists.
  intro H23.
  set (J := fst (x, H23)).
  change x with J.
  refine (ex_intro _ _ eq_refl).
  Check J.
```
This behavior was already present in 8.16.1.  Unless the issue being tracked down here is that the instance of the existential has changed between 8.16 and 8.17?  (I don't have VST installed locally on my 8.16 copy of Coq, so it's a bit tricky for me to confirm this atm)

**Comment by JasonGross** [comment]
Using the script
```coq
  clear -RamG H23.
  move H23 at bottom.
  match goal with |- context[?v] => is_evar v; set (w := v) end.
  revert H23.
  clearbody w.
  revert w.
  lazymatch goal with |- forall w, @?P w => assert (exists w, P w) end; cbv beta.
  2: admit.
  Ltac tac RamG :=
    eexists;
    let H23 := fresh "H23" in
    let J := fresh "J" in
    intro H23;
    set (J := fst (RamG, H23));
    change RamG with J;
    refine (ex_intro _ _ eq_refl);
    lazymatch eval cbv delta [J] in J with
    | fst (?x, ?y) => assert_fails pose y
    end.
  repeat match goal with
         | [ H := _ |- _ ] => clearbody H; assert_succeeds tac RamG
         | [ H : _ |- _ ] => clear H; assert_succeeds tac RamG
         | [ H : _ |- _ ] => assert_fails constr_eq H RamG; revert H; assert_succeeds tac RamG
         end.
  repeat match goal with
         | [ |- context[?x] ] => generalize x; assert_succeeds tac RamG
         end.
  generalize dependent graph_rep; intros graph_rep RamG.
  change fold_right_sepcon with (fold_right sepcon emp).
  repeat match goal with
         | [ |- context[?x] ] => generalize x; assert_succeeds tac RamG
         end.
  generalize dependent mpred; intros mpred graph_rep RamG.
  cbv [VType].
  generalize dependent LGraph; intros LGraph g' graph_rep RamG.
  intros.
  repeat match goal with
         | [ |- context[?x] ] => generalize x; clear -RamG; assert_succeeds tac RamG
         end.
  intros.
  generalize dependent (@cons mpred (graph_rep g') nil); intros ? RamG.
  repeat match goal with
         | [ |- context[?x] ] => generalize x; clear -RamG; assert_succeeds tac RamG
         end.
  intros.
  generalize dependent (list mpred); intros.
  repeat match goal with
         | [ |- context[?x] ] => generalize x; clear -RamG; assert_succeeds tac RamG
         end.
  intros.
  repeat match goal with H : _ |- _ => revert H end.
```
I've reduced this to
```coq
Definition abbreviate {A} {x : A} := x.
Goal   forall (T2 : Type) (l : T2),
    let RamG : T2 := @abbreviate T2 l in
    forall (T0 : Type) (T1 : forall (_ : T0) (_ : T0), Type) (T : Type) (m : forall (_ : T) (_ : T), T)
           (m0 : forall _ : T0, T) (P : forall (_ : T) (_ : T), Prop)
           (f : forall (L1 G1 : T0) (F : T) (_ : P (m0 G1) (m (m0 L1) F)), T1 L1 G1)
           (t : T) (P0 : Prop) (RamG0 RamL : T0),
      @ex (T1 RamL RamG0)
        (fun w : T1 RamL RamG0 =>
           forall _ : P0,
             @ex (P (m0 RamG0) (m (m0 RamL) t))
               (fun H : P (m0 RamG0) (m (m0 RamL) t) => @eq (T1 RamL RamG0) w (f RamL RamG0 t H))).
  intros.
  eexists.
  intro H23.
  set (J := fst (RamG, H23)).
  change RamG with J.
  refine (ex_intro _ _ eq_refl).
  lazymatch eval cbv delta [J] in J with
  | fst (?x, ?y) => pose y
  end.
  (* Error: Cannot reinterpret "H23" in the current environment. *)
```

This is clearly a bug of some sort, but this behavior is already present in 8.16.1, so it seems that this is again an overminimization.  I'm out of time for the moment, but perhaps @SkySkimmer you can pursue something along the same lines to determine what the gap is between 8.16 and 8.17?  (I wish the infrastructure were in place to do two-version minimization and auto-timeout-resumption...)

**Comment by JasonGross** [comment]
@andrew-appel The clearing of hypotheses is not about what appears in the goal but about what appears in the context of `?w` (as determined by `Show Existentials.`).  When you do `refine (ex_intro _ _ eq_refl)`, Coq instantiates `?w` to `Freezer.FRZRw_constr H` and in doing so determines that `H` cannot possibly mention any context variable not present in the context of `?w`.  This is correct and necessary.  (Note that `J` is left because it reduces to something which is well-typed in the context of `?w`.  This leads to unfortunate goal display, but perhaps the only bug is that `J` is not pre-emptively reduced in the context of `H` until it is well-typed in the context of `?w`?)

Is it possible that the issue in your original example is not that `refine (ex_intro _ _ eq_refl)` clears context variables, but that the tactics before it introducing `?w` do so in a different order in 8.16 vs 8.17, so that in 8.16, so that the existential context of `?w` in 8.16 is larger than it is in 8.17?

**Comment by andrew-appel** [comment]
@JasonGross Thank you for the explanation.

Can I suggest that the reference manual, in explaining `refine`, should explain that hypotheses may be deleted from above the line, and under what circumstances that will happen?

I can confirm that something changed between Coq 8.16.1 and Coq 8.17.1.  The proof (in refine_bug.v) did work in Coq 8.16.1.   Perhaps it is as you say, the tactics before the `refine` introduced context variables in a different order.  Which, in some sense, is an unintended incompatibility bug in Coq 8.17.

**Comment by andrew-appel** [comment]
OK, I have narrowed down the difference even further.

```
Require Import VST.floyd.proofauto.
Goal TT |-- !! True.
auto.
```

In Coq 8.16, auto does not solve the goal, but `simple apply @TT_right` solves the goal.
In Coq 8.17, auto does solve the goal, and info_auto reports `simple apply @TT_right`.

This difference causes other things to flow differently, resulting in the behavior that I reported above.

**Comment by andrew-appel** [comment]
I think it is safe to close this issue now.  Thank you for the assistance.

**Comment by JasonGross** [comment]
Great, thanks for closing the loop on this @andrew-appel
