### ISSUE TITLE
build coq missing findlib

### ISSUE THREAD

**Issue by github-neilwong** [coq/coq#18054]
#### but the build is failure and the following is the operate steps, how should i do to fix this bug? Thanks.

 ./configure
You have OCaml 5.2.0+dev0-2023-04-11. Good!
You have OCamlfind 1.9.6. Good!
You have native-code compilation. Good!
You have the Zarith library 1.13 installed. Good!
Where should I install Coq [/usr/local]?
Where should I install the Coq library [/usr/local/lib/coq]?
Where should I install the Coqide configuration files [/etc/xdg/coq]?
Where should I install the Coqide data files [/usr/local/share/coq]?
Where should I install the Coq man pages [/usr/local/share/man]?
Where should I install documentation prefix path for all Coq packages [/usr/local/share/doc]?

  Architecture                : Linux
  Sys.os_type                 : Unix
  OCaml version               : 5.2.0+dev0-2023-04-11
  OCaml binaries in           : /usr/local/bin/
  OCaml library in            : /usr/local/lib/ocaml
  Web browser                 : firefox -remote "OpenURL(%s,new-tab)" || firefox %s &
  Coq web site                : http://coq.inria.fr/
  Bytecode VM enabled         : true
  Native Compiler enabled     : no

  Paths where installation is expected by Coq Makefile:
  - Coq is expected in /usr/local
  - the Coq library is expected in /usr/local/lib/coq
  - the Coqide configuration files is expected in /etc/xdg/coq
  - the Coqide data files is expected in /usr/local/share/coq
  - the Coq man pages is expected in /usr/local/share/man
  - documentation prefix path for all Coq packages is expected in /usr/local/share/doc

If anything is wrong above, please restart './configure'.

*Warning* To compile the system for a new architecture
          don't forget to do a 'make clean' before './configure'.

git branch
  master
* v8.18

make dunestrap
dune build  --root . theories_dune ltac2_dune
File "tools/dune_rule_gen/dune", line 5, characters 22-29:
5 |  (libraries coqdeplib findlib))
                          ^^^^^^^
Error: Library "findlib" not found.
-> required by library "coq_dune" in _build/default/tools/dune_rule_gen
-> required by executable gen_rules in tools/dune_rule_gen/dune:8
-> required by _build/default/tools/dune_rule_gen/gen_rules.exe
-> required by _build/default/theories_dune
Makefile:124: recipe for target '.dune-stamp' failed
make: *** [.dune-stamp] Error 1

####  ls -l /usr/local/lib/ocaml/site-lib/findlib/
total 1188
-rwxr-xr-x 1 root root 296594 Sep 15 07:10 findlib.a
-rwxr-xr-x 1 root root 320217 Sep 18 01:14 findlib.cma
-rwxr-xr-x 1 root root   6024 Sep 18 01:14 findlib.cmi
-rwxr-xr-x 1 root root   5845 Sep 15 07:10 findlib.cmxa
-rwxr-xr-x 1 root root 263640 Sep 15 07:10 findlib.cmxs
...

**Comment by SkySkimmer** [comment]
You need the libfindlib-ocaml-dev package for findlib

**Comment by github-neilwong** [comment]
#### how do i install this package ?

the following is my steps:

1. download findlib-1.9.6 package
2. ./configure

./configure
Welcome to findlib version 1.9.6
Configuring core...
Checking for #remove_directory...
Testing threading model...
systhread_supported: true
Testing DLLs...
Testing whether ppxopt can be supported...
Checking for ocamlc -opaque...
Checking for ocamlopt -g...
Configuring libraries...
unix: found (in +unix)
dynlink: found (in +dynlink)
bigarray: not present (possible since 4.08)
compiler-libs: found
dbm: not present (normal since 4.00)
graphics: not present (normal since 4.09)
num: not present (normal since 4.06)
ocamlbuild: not present (normal since 4.03)
ocamldoc: found (in +ocamldoc)
raw_spacetime: not present (normal since 4.12)
threads: found (in +threads)
str: found (in +str)
labltk: not present (normal since 4.02)
native dynlink: found
camlp4: not present (normal since OCaml-4.02)
bytes: found, installing fake library
Configuration for bytes written to site-lib-src/bytes/META
Detecting compiler arguments: (extractor built) ok

About the OCAML core installation:
    Standard library:      /usr/local/lib/ocaml
    Binaries:              /usr/local/bin
    Manual pages:          /usr/local/man
    Multi-threading type:  posix
The directory of site-specific packages will be
    site-lib:              /usr/local/lib/ocaml/site-lib
The configuration file is written to:
    findlib config file:   /usr/local/etc/findlib.conf
Software will be installed:
    Libraries:             in <site-lib>/findlib
    Binaries:              /usr/local/bin
    Manual pages:          /usr/local/man
    topfind script:        /usr/local/lib/ocaml
Topfind ppxopt support:    yes
Toolbox:                   no
Link custom runtime:       yes
Need bytes compatibility:  no

Configuration has been written to Makefile.config

You can now do 'make all', and optionally 'make opt', to build ocamlfind.

3. make all
4. sudo make install

#### you mean i lost some file? can you give me the filename ? thanks.

find /usr/local/lib/ocaml/site-lib/findlib/ -name "findlib*"
/usr/local/lib/ocaml/site-lib/findlib/
/usr/local/lib/ocaml/site-lib/findlib/findlib.cmxa
/usr/local/lib/ocaml/site-lib/findlib/findlib.a
/usr/local/lib/ocaml/site-lib/findlib/findlib.cmxs
/usr/local/lib/ocaml/site-lib/findlib/findlib_top.cmxa
/usr/local/lib/ocaml/site-lib/findlib/findlib_top.a
/usr/local/lib/ocaml/site-lib/findlib/findlib_top.cmxs
/usr/local/lib/ocaml/site-lib/findlib/findlib_dynload.cmxa
/usr/local/lib/ocaml/site-lib/findlib/findlib_dynload.a
/usr/local/lib/ocaml/site-lib/findlib/findlib_dynload.cmxs
/usr/local/lib/ocaml/site-lib/findlib/findlib.cmi
/usr/local/lib/ocaml/site-lib/findlib/findlib.mli
/usr/local/lib/ocaml/site-lib/findlib/findlib.cma
/usr/local/lib/ocaml/site-lib/findlib/findlib_config.cmi
/usr/local/lib/ocaml/site-lib/findlib/findlib_config.ml
/usr/local/lib/ocaml/site-lib/findlib/findlib_top.cma
/usr/local/lib/ocaml/site-lib/findlib/findlib_dynload.cma

**Comment by SkySkimmer** [comment]
Oh it's manually installed
I dont know it works then sorry

**Comment by Zimmi48** [comment]
Since Coq's configure said "You have OCamlfind 1.9.6. Good!", this means that both `which ocamlfind` and `ocamlfind -query findlib -format "%v"` succeeded (and the latter returned `1.9.6`). Therefore, this failure is very strange and makes me wonder if that could be a Dune bug. Maybe this should be forwarded to the Dune developers...

**Comment by ejgallego** [comment]
Hard to know if that's a bug, likely more like a problem with different OCaml installed and Dune not looking at the right place.

Coq's configure doesn't use dune-config to query for packages (yet), but the `ocamlfind` binaries that are in the path.

**Comment by ejgallego** [comment]
If @github-neilwong has installed Dune or ocamlfind by hand, they need to be sure the right `configure` settings are used in both.

Would be great to have better error messages etc... upstream of course.

**Comment by github-neilwong** [comment]
Now i used all release version and try again, met same error. 

ocaml:
git checkout 5.1
./configure
make 
sudo make install
ocaml --version
The OCaml toplevel, version 5.1.1+dev0-2023-09-14


dune:
git checkout 3.9
dune --version
3.9.3


findlib:
use 1.9.6 package
./configure
Welcome to findlib version 1.9.6
Configuring core...
Checking for #remove_directory...
Testing threading model...
systhread_supported: true
Testing DLLs...
Testing whether ppxopt can be supported...
Checking for ocamlc -opaque...
Checking for ocamlopt -g...
Configuring libraries...
unix: found (in +unix)
dynlink: found (in +dynlink)
bigarray: not present (possible since 4.08)
compiler-libs: found
dbm: not present (normal since 4.00)
graphics: not present (normal since 4.09)
num: not present (normal since 4.06)
ocamlbuild: package already present
ocamldoc: found (in +ocamldoc)
raw_spacetime: not present (normal since 4.12)
threads: found (in +threads)
str: found (in +str)
labltk: not present (normal since 4.02)
native dynlink: found
camlp4: not present (normal since OCaml-4.02)
bytes: found, installing fake library
Configuration for bytes written to site-lib-src/bytes/META
Detecting compiler arguments: (extractor built) ok

About the OCAML core installation:
    Standard library:      /usr/local/lib/ocaml
    Binaries:              /usr/local/bin
    Manual pages:          /usr/local/man
    Multi-threading type:  posix
The directory of site-specific packages will be
    site-lib:              /usr/local/lib/ocaml/site-lib
The configuration file is written to:
    findlib config file:   /usr/local/etc/findlib.conf
Software will be installed:
    Libraries:             in <site-lib>/findlib
    Binaries:              /usr/local/bin
    Manual pages:          /usr/local/man
    topfind script:        /usr/local/lib/ocaml
Topfind ppxopt support:    yes
Toolbox:                   no
Link custom runtime:       yes
Need bytes compatibility:  no

Configuration has been written to Makefile.config

You can now do 'make all', and optionally 'make opt', to build ocamlfind.
make all
make opt
sudo make install

 sudo make install
if [ "0" -eq 1 ]; then \
    for x in camlp4 dbm graphics labltk num ocamlbuild; do \
      if [ -f "/usr/local/lib/ocaml/site-lib/$x/META" ]; then \
        if ! grep -Fq '[distributed with Ocaml]' "//usr/local/lib/ocaml/site-lib/$x/META"; then \
          rm -f site-lib-src/$x/META; \
        fi; \
      fi; \
    done; \
    test -f "site-lib-src/num/META" || rm -f "site-lib-src/num-top/META"; \
  fi
echo 'SITELIB_META =' > Makefile.packages.in
for x in `ls site-lib-src`; do test ! -f "site-lib-src/$x/META" || echo $x >> Makefile.packages.in; done
tr '\n' ' ' < Makefile.packages.in > Makefile.packages
rm Makefile.packages.in
install -d "/usr/local/bin"
install -d "/usr/local/man"
make install-config
make[1]: Entering directory '/home/user/usr/project/coq/ocamlfind1.9.6/ocamlfind-findlib-1.9.6'
install -d "`dirname \"/usr/local/etc/findlib.conf\"`"
!!! Keeping old /usr/local/etc/findlib.conf !!!
test -f "/usr/local/etc/findlib.conf" || install -c findlib.conf "/usr/local/etc/findlib.conf"
make[1]: Leaving directory '/home/user/usr/project/coq/ocamlfind1.9.6/ocamlfind-findlib-1.9.6'
for p in findlib; do ( cd src/$p; make install ); done
make[1]: Entering directory '/home/user/usr/project/coq/ocamlfind1.9.6/ocamlfind-findlib-1.9.6/src/findlib'
install -d "/usr/local/lib/ocaml/site-lib/findlib"
install -d "/usr/local/bin"
test 1 -eq 0 || install -d "/usr/local/lib/ocaml"
test 1 -eq 0 || install -c topfind "/usr/local/lib/ocaml/"
files=` ../../tools/collect_files ../../Makefile.config \
findlib.cmi findlib.mli findlib.cma findlib.cmxa findlib.a findlib.cmxs \
findlib_config.cmi findlib_config.ml topfind.cmi topfind.mli \
fl_args.cmi fl_lint.cmi fl_meta.cmi fl_split.cmi fl_topo.cmi ocaml_args.cmi \
fl_package_base.mli fl_package_base.cmi fl_metascanner.mli fl_metascanner.cmi \
fl_metatoken.cmi findlib_top.cma findlib_top.cmxa findlib_top.a findlib_top.cmxs \
findlib_dynload.cma findlib_dynload.cmxa findlib_dynload.a findlib_dynload.cmxs fl_dynload.mli fl_dynload.cmi \
META` && \
install -c $files "/usr/local/lib/ocaml/site-lib/findlib/"
f="ocamlfind"; { test -f ocamlfind_opt && f="ocamlfind_opt"; }; \
install -c $f "/usr/local/bin/ocamlfind"
# the following "if" block is only needed for 4.00beta2
if [ 1 -eq 0 -a -f "/usr/local/lib/ocaml/compiler-libs/topdirs.cmi" ]; then \
    cd "/usr/local/lib/ocaml/compiler-libs/"; \
    install -c topdirs.cmi toploop.cmi "/usr/local/lib/ocaml/site-lib/findlib/"; \
fi
make[1]: Leaving directory '/home/user/usr/project/coq/ocamlfind1.9.6/ocamlfind-findlib-1.9.6/src/findlib'
make install-meta
make[1]: Entering directory '/home/user/usr/project/coq/ocamlfind1.9.6/ocamlfind-findlib-1.9.6'
for x in bytes ; do install -d "/usr/local/lib/ocaml/site-lib/$x"; install -c site-lib-src/$x/META "/usr/local/lib/ocaml/site-lib/$x/META.tmp" && mv "/usr/local/lib/ocaml/site-lib/$x/META.tmp" "/usr/local/lib/ocaml/site-lib/$x/META"; done
install -d "/usr/local/lib/ocaml/site-lib/findlib"; install -c Makefile.packages "/usr/local/lib/ocaml/site-lib/findlib/Makefile.packages"
make[1]: Leaving directory '/home/user/usr/project/coq/ocamlfind1.9.6/ocamlfind-findlib-1.9.6'
test ! -f 'site-lib-src/num-top/META' || { cd src/findlib; make install-num-top; }
test ! -f 'site-lib-src/camlp4/META' || install -c tools/safe_camlp4 "/usr/local/bin"
make install-doc
make[1]: Entering directory '/home/user/usr/project/coq/ocamlfind1.9.6/ocamlfind-findlib-1.9.6'
install -d "/usr/local/man/man1" "/usr/local/man/man3" "/usr/local/man/man5"
install -c doc/ref-man/ocamlfind.1 "/usr/local/man/man1"
install: cannot stat 'doc/ref-man/ocamlfind.1': No such file or directory
Makefile:74: recipe for target 'install-doc' failed
make[1]: [install-doc] Error 1 (ignored)
install -c doc/ref-man/META.5 doc/ref-man/site-lib.5 doc/ref-man/findlib.conf.5 "/usr/local/man/man5"
install: cannot stat 'doc/ref-man/META.5': No such file or directory
install: cannot stat 'doc/ref-man/site-lib.5': No such file or directory
install: cannot stat 'doc/ref-man/findlib.conf.5': No such file or directory
Makefile:74: recipe for target 'install-doc' failed
make[1]: [install-doc] Error 1 (ignored)
make[1]: Leaving directory '/home/user/usr/project/coq/ocamlfind1.9.6/ocamlfind-findlib-1.9.6'


install-doc have bug, but i think can ignore these errors.

coq v8.18

./configure
You have OCaml 5.1.1+dev0-2023-09-14. Good!
You have OCamlfind 1.9.6. Good!
You have native-code compilation. Good!
You have the Zarith library 1.13 installed. Good!
Where should I install Coq [/usr/local]?
Where should I install the Coq library [/usr/local/lib/coq]?
Where should I install the Coqide configuration files [/etc/xdg/coq]?
Where should I install the Coqide data files [/usr/local/share/coq]?
Where should I install the Coq man pages [/usr/local/share/man]?
Where should I install documentation prefix path for all Coq packages [/usr/local/share/doc]?

  Architecture                : Linux
  Sys.os_type                 : Unix
  OCaml version               : 5.1.1+dev0-2023-09-14
  OCaml binaries in           : /usr/local/bin/
  OCaml library in            : /usr/local/lib/ocaml
  Web browser                 : firefox -remote "OpenURL(%s,new-tab)" || firefox %s &
  Coq web site                : http://coq.inria.fr/
  Bytecode VM enabled         : true
  Native Compiler enabled     : no

  Paths where installation is expected by Coq Makefile:
  - Coq is expected in /usr/local
  - the Coq library is expected in /usr/local/lib/coq
  - the Coqide configuration files is expected in /etc/xdg/coq
  - the Coqide data files is expected in /usr/local/share/coq
  - the Coq man pages is expected in /usr/local/share/man
  - documentation prefix path for all Coq packages is expected in /usr/local/share/doc

If anything is wrong above, please restart './configure'.

*Warning* To compile the system for a new architecture
          don't forget to do a 'make clean' before './configure'.

make dunestrap
dune build  --root . theories_dune ltac2_dune
File "tools/dune_rule_gen/dune", line 5, characters 22-29:
5 |  (libraries coqdeplib findlib))
                          ^^^^^^^
Error: Library "findlib" not found.
-> required by library "coq_dune" in _build/default/tools/dune_rule_gen
-> required by executable gen_rules in tools/dune_rule_gen/dune:8
-> required by _build/default/tools/dune_rule_gen/gen_rules.exe
-> required by _build/default/theories_dune
Makefile:124: recipe for target '.dune-stamp' failed
make: *** [.dune-stamp] Error 1

**Comment by github-neilwong** [comment]
thanks @ejgallego , now i know the reason is because of site-lib path.

**findlib**

./configure -sitelib /usr/local/lib/ocaml

**Zarith**

./configure -installdir /usr/local/lib/ocaml

**build coq success**

 make dunestrap
dune build  --root . theories_dune ltac2_dune
touch .dune-stamp
cp -a _build/default/theories_dune theories/dune && chmod +w theories/dune
cp -a _build/default/ltac2_dune user-contrib/Ltac2/dune && chmod +w user-contrib/Ltac2/dune

**Comment by github-neilwong** [comment]
thanks @ejgallego , now i know the reason is because of site-lib path.

**findlib**

./configure -sitelib /usr/local/lib/ocaml

**Zarith**

./configure -installdir /usr/local/lib/ocaml

**build coq success**

 make dunestrap
dune build  --root . theories_dune ltac2_dune
touch .dune-stamp
cp -a _build/default/theories_dune theories/dune && chmod +w theories/dune
cp -a _build/default/ltac2_dune user-contrib/Ltac2/dune && chmod +w user-contrib/Ltac2/dune
