### ISSUE TITLE
ci-fiat_crypto_legacy produces too large log (many duplicated notation-overridden warnings)

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#18076]
eg https://gitlab.com/coq/coq/-/jobs/4981022207
>Job's log exceeded limit of 4194304 bytes.
Job execution will continue but no more output will be collected.

This means when it fails we can't see the error.

cc @JasonGross

**Comment by JasonGross** [comment]
Is it all notation-overridden warnings, or is something else clogging up the log?  I'm happy to change whatever needs changing to suppress the messages (removing Print lines or disabling the warnings).

**Comment by SkySkimmer** [comment]
It seems to be the notation-overridden.
They first appear on master in https://gitlab.com/coq/coq/-/jobs/4805270960 (previous master non cancelled pipeline is https://gitlab.com/coq/coq/-/jobs/4804663757, the 2 between are https://gitlab.com/coq/coq/-/pipelines/955720173 and https://gitlab.com/coq/coq/-/pipelines/955796822 which are unlikely to be related

@herbelin could https://github.com/coq/coq/pull/17907 somehow lead to increased notation-overridden warnings?
Also the warnings may be correct (I haven't looked) but they get repeated many times which is more questionable.

**Comment by herbelin** [comment]
This is indeed the plausible suspect, though I don't understand exactly why it warns for the overriding only now.

At least, the reason why there are repeated warnings is known: there are e.g. 393 copies of the notation "addcarryx_u64" in file `fiat_crypto_legacy/src/Compilers/Z/CNotations.v`.

**Comment by herbelin** [comment]
Can it be a change in the flags passed to Coq, i.e. that `-w "-notation-overridden"` stopped to be passed?

For instance, in the recent log, I see a legitimate warning `notation-overriden` in `src/Util/ParseTaps.v` which does not occur in the older log.

**Comment by SkySkimmer** [comment]
The f-l-c commit is https://github.com/mit-plv/fiat-crypto/commit/a2f5a5b0f033545669d30ec9839f5653a38c87bb in both jobs (grep for `commit ` in the log to see it)

**Comment by herbelin** [comment]
The problem has one way or another to be related to Makefiles. The job 4804663757 has no notation-overriden warning at all (even though there are actual overridings), so it is that the line `OTHERFLAGS += -w "-notation-overridden"` of the (sp2019latest) fiat-crypto Makefile has be taken into account.

When checking locally with `make ci-fiat_crypto_legacy` on commit 919f42954de8627053ccb661ba24178f339723ca (Aug 4, 8:41) which is supposed to be the one tested by the good 4804663757 job, I observe the bad behavior (i.e. that the warning is not taken into account).

The "bad" behavior is observed Aug 4, 10:04, on gitlab CI with commit d7f0d9f07d2957b6d979737b2e2ed1d8305796bb.

There are no commits on fiat-crypto on this period.

In addition to the presence or not of the notation-overriden warning, the logs also show these differences: printings of the form `COQC src/Util/ParseTaps.v` in the bad case, printings of the form `TIMEOUT -m 10000000 COQC src/Util/ParseTaps.v` in the good case. What can have caused this difference?

Regarding the overriden warning, a possibility I see is that the order of inclusion of Makefiles changed:
- fiat-crypto Makefile sets `OTHERFLAGS += -w "-notation-overridden"` while `Makefile.coq` sets `OTHERFLAGS := $(COQMF_OTHERFLAGS)` where `COQMF_OTHERFLAGS` is itself set in `Makefile-old.conf`
- in my local tests, when printed from `Makefile.coq`, the value of `OTHERFLAGS` does not include the warning but when printed from `Makefile`, it includes it, as if `Makefile.coq` had kept the value of `OTHERFLAGS` it had at inclusion time

Were there e.g. changes on Aug 4 in the setting of the CI which would e.g. have changed the semantics of `make`?

In any case, even if the exact reason remains unclear, an easy fix would be to add `-notation-overridden` directly to `COQMF_OTHERFLAGS` in the file `Makefile-old.conf` of fiat-crypto.

**Comment by SkySkimmer** [comment]
One of the PRs between the jobs is https://github.com/coq/coq/pull/17785 which changed the docker.
fcl runs on the edge image so maybe it got a new `make` with slightly different behaviour?

**Comment by herbelin** [comment]
I made my local tests with make 4.4.1. The release notes of 4.4.1 (Feb 23) lists an incompatibility, and the release notes of 4.4.0 (Oct 22) lists even more incompatibilities (but I'm not able to understand if it relates to the current problem).

**Comment by SkySkimmer** [comment]
Could be related to https://github.com/coq/coq/pull/16757
I'm pushing PR https://github.com/coq/coq/pull/18077 based on this idea, if it works then we know what's going on and have the fix.
