### ISSUE TITLE
`Print`/`About` should "see through" all notation consistently

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#18097]
#### Description of the problem

I like using `Print` to figure out how something is defined. However, when something is defined as a `Notation`, then Coq sometimes will only print the notation, but not what the notation expands to, which means I have to issue 2 (or more) print commands to finally get to the thing I actually care about.

This doesn't apply to all notation, e.g. `Print "="` works fine. However for notation aliases this is a problem: `Print pow` will just say `Notation pow := Nat.pow`, so now I have to go `Print Nat.pow` in a second query. Coq could really do that work for me and just show me how `Nat.pow` is defined, since that's what I was asking for.

The exact same applies to `About`, and possibly other commands as well.

#### Coq Version

8.16.1

**Comment by herbelin** [comment]
Granted in #18443, if ever interested in giving feedback.

**Comment by RalfJung** [comment]
Thanks a lot @herbelin  :)
