### ISSUE TITLE
"Print" works for some notations but not all.

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#18096]
#### Description of the problem

I recently noticed that `Print "="` works and prints `eq`, but `Print "<>"` does not work and just says
```
Unable to interpret "<>" as a reference.
```
Why can some notations be printed and others not? Is this a bug or somehow intended?

#### Coq Version
8.16.1

**Comment by SkySkimmer** [comment]
It works when the notation is basically just the reference (cf https://github.com/coq/coq/blob/41944f5551e076bc83fe4d42f4ce2c0b440c79f1/interp/notation.ml#L2364).
In the case of `"x = y" := (@eq _ x y)` this is the case but for `"x <> y" := (not (@eq _ x y))` it's not.

**Comment by RalfJung** [comment]
Oh I see... `Print "<>"` would have to print `not` and `eq` somehow but it's only supposed to print one thing. Yeah that makes sense, thanks!

**Comment by herbelin** [comment]
Maybe the message should be improved?

**Comment by RalfJung** [comment]
Yeah that would be a good idea.

**Comment by herbelin** [comment]
`Unable to non-ambiguously interpret "<>" as a reference.` ??

(At the same time, we should take some time to rethink the articulation between `Print`, `Check` and `About`. There was an issue about it but I don't find it again. It would also be possible to give a positive answer on `Print "<>"`, say `Notation "x <> y" := (not (eq x y))`.)

**Comment by RalfJung** [comment]
Those 3 I actually see as fairly different, but `Print` and `Locate` have a lot of overlap... also see https://github.com/coq/coq/issues/18097.

> Unable to non-ambiguously interpret "<>" as a reference. ??

What about something like
```
Unable to non-ambiguously interpret "<>" as a reference; found:
Notation "x <> y" := (not (eq x y)).
```

**Comment by herbelin** [comment]
OK, adopted, made #18104.
