### ISSUE TITLE
Any particular reason for cast to be defined this way? 

### ISSUE THREAD

**Issue by mukeshtiwari** [coq/coq#18103]
Hi everyone, 
I am wondering if there is a reason for `cast` [1] to defined in this way? We can simply write it in the following way:

```
Definition cast : 
  forall {m : nat}, 
  Fin.t m -> forall {n : nat}, m = n -> Fin.t n.
Proof.
  intros * v * Ha.
  refine 
    match Ha in _ = n return (Fin.t n)
    with 
    | eq_refl => v 
    end.
Defined.
```
and it extracts to the following OCaml code:
```
(** val cast : nat -> t -> nat -> t **)

let cast _ v _ =
  v
```

While the library code extracts to:
```
(** val cast : nat -> t -> nat -> t **)

let rec cast _ v n =
  match v with
  | F1 _ -> (match n with
	         | O -> assert false (* absurd case *)
             | S n' -> F1 n')
  | FS (n0, f) ->
    (match n with
     | O -> assert false (* absurd case *)
     | S n' -> FS (n', (cast n0 f n')))
```

Technically, both extracted functions are same but their complexity are different. The library code traverses the whole structure, while the above one is just an identity function (and more efficient).

[1]https://github.com/coq/coq/blob/a2bf79287d63f437937f3086fe19a72eaae58d96/theories/Vectors/Fin.v#L282

**Comment by JasonGross** [comment]
The existing `cast` has much better behavior inside Coq, where your proof of equality might be opaque and block reduction.  If you want the best of both worlds, you can define `cast` the way you write it, and then wrap the equality proof in something like `match Nat.eq_dec n m with left pf => pf | right npf => match npf argument with end end` to ensure that a transparent proof of equality is always used.  (But this requires a bit more reduction to see through than the structural cast.)

**Comment by mukeshtiwari** [comment]
Thanks @JasonGross! It definitely now makes sense to me. I am going to close the request.
