### ISSUE TITLE
No backtrace shown despite "Set Ltac Backtrace"

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#18119]
#### Description of the problem

Consider this code:
```
Set Ltac Backtrace.
Tactic Notation "run_tac" tactic(tac) := tac. (* <- bug *)

Goal forall n : nat, True.
Proof.
  intros n.
  run_tac (fun _ => destruct n as [|n']). (* line 7 *)
```
There's a bug in the marked line, that should be `tac ()`. When running this proof script, however, all that Coq prints is
```
File "/home/r/Dokumente/Unisachen/iris/stdpp/tests/tactics.v", line 7, characters 1-41:
Error: An unnamed user-defined tactic was not fully applied:
There is a missing argument for variable _,
no arguments at all were provided.
```
Line 7 might invoke a tactic that calls other tactics that span hundreds of lines, and currently it is near impossible to figure out where the error actually happens. I thought ltac backtraces would help with that, but `Set Ltac Backtrace` doesn't actually improve the output here.

#### Coq Version

8.18.0

**Comment by RalfJung** [comment]
Will this show a line number of where the error occurred?  (line 2 in the example)

**Comment by SkySkimmer** [comment]
Ltac Backtrace never does that AFAIK

**Comment by RalfJung** [comment]
Those would be very useful for debugging.
