### ISSUE TITLE
Failed to instantiate evar: Anomaly uncaught IllTypedInstance

### ISSUE THREAD

**Issue by xtreme-james-cooper** [coq/coq#18114]
#### Description of the problem

Minified code to reproduce:

```
Inductive vect : Type -> nat -> Type :=
  | Nil : forall {A : Type}, vect A 0
  | Cons : forall {A : Type} {n : nat}, A -> vect A n -> vect A (S n).

Fixpoint insert {A : Type} {n m : nat} (idx : m <= n) (a : A) (xs : vect A n) : vect A (S n). 
Admitted.

Inductive ty : Type :=
  | Base : ty
  | Arrow : ty -> ty -> ty.

Inductive expr {n : nat} : vect ty n -> ty -> Type :=
  | Con : forall {gam : vect ty n}, expr gam Base
  | Lam : forall {gam : vect ty n} {t1 t2 : ty}, expr (Cons t1 gam) t2 -> expr gam (Arrow t1 t2).

Fixpoint subst {t t' : ty} {n m : nat} {gam : vect ty n} {gam' : vect ty (S n)} (x : m <= n) (e' : expr gam t') (e : expr gam' t) : 
    gam' = insert x t' gam -> expr gam t.
  intro eq. induction e.
```

When it hits the induction, rather than splitting the goal, it fails with "Failed to instantiate evar: Anomaly
                            "Uncaught exception Evarsolve.IllTypedInstance(_, _, _)."
Please report at http://coq.inria.fr/bugs/." 

#### Coq Version

CoqIde 8.12.2, on a Mac OSX 13.6

**Comment by herbelin** [comment]
Versions ≥ 8.13 have no anomaly (probably due to #13380). I'm afraid there is no backport policy for bug fixes, so, the recommendation will be to use a more recent version of Coq :(
