### ISSUE TITLE
Anomaly "Uncaught exception Not_found." while casting a variable

### ISSUE THREAD

**Issue by rajdakin** [coq/coq#18127]
#### Description of the problem

This code:
```coq
Class Class1 (hom : Type) (c : hom) : Type := {
    var1 : hom -> Type;
    var2 : hom;
}.

Class Class2 {h c} (C : Class1 h c) (fmap : h -> h) := {
    var3 : var1 (fmap var2);
}.

Definition var3_cast : forall {h c C fm}, Class2 C fm -> var1 (fm var2) := @var3.
```
raises `Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/.`

Note that any of the following solve the issue:
- changing `Class` into `Record`
- forcing `C` (in the type of `var3_cast`) to be of type `Class1 h c`
- removing the parameter `c` from `Class1`
- extracting `hom` to be an `Axiom` instead of a parameter of `Class1`

#### Coq Version

```
$ coqtop -v 
> The Coq Proof Assistant, version 8.18.0
> compiled with OCaml 5.0.0
```
I use Arch linux.

**Comment by herbelin** [comment]
Introduced in 8.18. Presumably by 96181bd43c224f5fade0d5690d4b6750db29146c which should maybe consider also the case of the evar solved on the fly, or something like that.

**Comment by herbelin** [comment]
Indeed, the (probably naive) patch
```ocaml
diff --git a/pretyping/typeclasses.ml b/pretyping/typeclasses.ml
index f3c923c3a8..b3f8ce4889 100644
--- a/pretyping/typeclasses.ml
+++ b/pretyping/typeclasses.ml
@@ -245,7 +245,7 @@ let no_goals_or_obligations _ source =
 
 let has_typeclasses filter evd =
   let tcs = get_typeclass_evars evd in
-  let check ev = filter ev (lazy (snd (Evd.evar_source (Evd.find_undefined evd ev)))) in
+  let check ev = filter ev (lazy (let EvarInfo ev = Evd.find evd ev in (snd (Evd.evar_source ev)))) in
   Evar.Set.exists check tcs
 
 let get_filtered_typeclass_evars filter evd =
```
fixes the anomaly. Cc @ppedrot.

**Comment by SkySkimmer** [comment]
I think the correct fix is https://github.com/coq/coq/pull/18128

**Comment by herbelin** [comment]
> I think the correct fix is https://github.com/coq/coq/pull/18128

Looks indeed to fix a real issue...
