### ISSUE TITLE
Regression `setoid_rewrite` gives "Anomaly conversion was given unreduced term (FLambda)" since 8.18

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#18126]
#### Description of the problem

```coq
From Coq Require Export Morphisms Setoid Utf8.

Class Empty A := empty : A.

Class MapFold K A M := map_fold B : (K → A → B → B) → B → M → B.
Global Arguments map_fold {_ _ _ _ _}.

Class FinMap K M `{∀ A, Empty (M A), ∀ A, MapFold K A (M A)} := { }.

Definition map_filter {K A M} `{MapFold K A M, Empty M} (P : A → Prop) : M → M :=
  map_fold (λ k v m, m) empty.

Global Instance map_filter_proper {K A M} `{FinMap K M} (P : A → Prop) :
  Proper (@eq (M A) ==> eq) (map_filter P).
Proof. Admitted.

#[projections(primitive=yes)]
Record seal {A} (f : A) := { unseal : A; seal_eq : unseal = f }.
Global Arguments unseal {_ _}.

Record ofe := { ofe_car :> Type }.

Definition iProto (Σ V : Type) : ofe. Admitted.

Definition iProto_dual_def {Σ V} (p : iProto Σ V) : iProto Σ V := p.
Definition iProto_dual_aux : seal (@iProto_dual_def). Proof. eexists. reflexivity. Qed.
Definition iProto_dual : ∀ {Σ V}, iProto Σ V → iProto Σ V := iProto_dual_aux.(unseal).

Lemma test {Σ V} (p q q' : iProto Σ V) (Hq : q = q') :
  iProto_dual q = p.
Proof.
  Typeclasses eauto := debug.
  setoid_rewrite Hq.
```

The last line crashes Coq with "Anomaly "conversion was given unreduced term (FLambda)." Please report at http://coq.inria.fr/bugs/." So I am reporting this here.

We ran into this issue when updating one of the Iris projects to Coq 8.18, see https://gitlab.mpi-sws.org/iris/actris/-/jobs/252795 The above code is a minimized version of the actual issue we experience.

It appears the bug appears only when a number of things occur at the same time:

- The instance `map_filter_proper` is present (which appears to be entirely unrelated to the goal in which the rewrite happens)
- The record `seal` is primitive
- `iProto` uses the packed structure `ofe` instead of a mere `Type`

#### Coq Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.18.0
compiled with OCaml 4.13.1
```

**Comment by SkySkimmer** [comment]
89b0356d99596113d80ca7e9908ca3afada40515 strikes again

**Comment by Blaisorblade** [comment]
Should that just be reverted, or is the plan to fix all buggy users?
