### ISSUE TITLE
MacOS 14: lots of "ld: warning: -undefined suppress is deprecated" messages

### ISSUE THREAD

**Issue by pmetzger** [coq/coq#18134]
While building under MacOS 14, I get loads and loads of output like this:

```
(cd _build/default && /opt/local/bin/ocamlopt.opt -w -40 -g -O3 -unbox-closures -shared -linkall -I sysinit -o sysinit/sysinit.cmxs sysinit/sysinit.cmxa)
ld: warning: -undefined suppress is deprecated
ld: warning: -undefined suppress is deprecated
```

It's easy to reproduce; most of the files being built produce the message.

**Comment by ejgallego** [comment]
That certainly looks like an OCaml / MacOS / brew problem.

**Comment by pmetzger** [comment]
It's not brew. I'm the MacPorts coq package maintainer. And I haven't seen it while building other OCaml packages though it certainly could be an OCaml issue.

**Comment by pmetzger** [comment]
No. But I also don't have any idea how this is happening. It's very easily reproduced though.

**Comment by ejgallego** [comment]
I'm afraid there is little we can do from the Coq side.

**Comment by pmetzger** [comment]
I think I may give up on packaging Coq for MacPorts for now.

**Comment by ejgallego** [comment]
You didn't specify your `ocamlc -config`, maybe OCaml is too old for that version of MacOS ?

It seems MacOS is just a few days old so I wouldn't be surprised about compat problems.

Another thing that may help in this case is to be sure your whole ports tree is rebuilt from scratch, similar issues can happen if you happen to have a ports tree from MacOS 13 and you upgraded.

**Comment by pmetzger** [comment]
@ejgallego I'm one of the MacPorts maintainers. I maintain the OCaml toolchain stuff in MacPorts. We're running 4.14.1 which is more than new enough (we're waiting on 5 for a bit) and of course all the dependencies are freshly built. As I said, I'm the maintainer. But, I don't have infinite time.

**Comment by ejgallego** [comment]
@pmetzger I'm aware that you are the maintainer, and of course that no one has infinite time.

What I am not sure is how, at the Coq github org, we can help you with this concrete problem, which seems unrelated to Coq.

Is there anything else we could do?

If you suspect the Coq build system you can check `_build/log` and re-run any of the compile commands yourself, to call `ocamlopt` under a more controlled env.
