### ISSUE TITLE
Print Grammar ltac2 does not work

### ISSUE THREAD

**Issue by doside** [coq/coq#18137]
#### Description of the problem
I try using this command to print the grammar of ltac2, but it fails with message:
Unknown or unprintable grammar entry.

@coqbot minimize
```coq
From Ltac2 Require Import Ltac2.
Print Grammar ltac2.
```

#### Coq Version
coq version is 8.16, on Windows x86_64.

**Comment by SkySkimmer** [comment]
It's called ltac2_expr.

**Comment by doside** [comment]
Print Grammar ltac2_expr. 
it stil doesn't wotk.
I advise that a revise for the documentation in chapter 2.2.4 about the Print Grammar command is needed.

**Comment by SkySkimmer** [comment]
>coq version is 8.16

Your Coq is too old

**Comment by doside** [comment]
I feel sorry for that.
