### ISSUE TITLE
Tactics hresolve_core and hget_evar are mentioned in the 8.17 refman but not explained

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#18141]
In the Coq 8.17 reference manual (but not in the Coq 8.16 reference manual), these two tactics are listed without any explanation of what they do:

https://coq.inria.fr/doc/v8.17/refman/proofs/writing-proofs/equality.html?highlight=pattern#coq:tacn.hresolve_core

```
hresolve_core
hget_evar 
```

**Comment by SkySkimmer** [comment]
They got removed in 8.18
