### ISSUE TITLE
"Bug tracker" from coq.inria.fr home page is a broken link

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#18140]
From the home page,  coq.inria.fr,  clicking on "Bug tracker" leads to this page

https://coq.inria.fr/bugs/

which gives a 404 File not found error.

**Comment by Zimmi48** [comment]
Thanks for reporting. It looks like one of the many redirections that were broken with the migration of the website to GitHub Pages. I will fix by:

- adding the missing redirection
- changing the link on the homepage to be the direct link to GitHub issues.

**Comment by Zimmi48** [comment]
Closed by coq/coq.github.io@410acb8. Please use the bug tracker at https://github.com/coq/www/issues for reporting issues on the website in the future.
