### ISSUE TITLE
Failure of "only" selector

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#18222]
#### Description of the problem

![image](https://github.com/coq/coq/assets/1253341/ef98fd31-abd8-48a1-9c18-2b44f3bcbc56)

This should work.  Change `only 3: split` to `3: split` and it works.

#### Coq Version 8.18

```
Goal forall n: nat, (False /\ False) /\ (False /\ False).
split. only 1: split. only 3: split. idtac.
```

**Comment by jfehrle** [comment]
OTOH, `only 3:` works correctly within Ltac tactics:

![image](https://github.com/coq/coq/assets/1253341/54445153-1239-4ca3-a661-20910608b241)

**Comment by SkySkimmer** [comment]
The default goal selector is 1 so `only 3: split` actually means `1: (only 3: split)`
