### ISSUE TITLE
Spurious assumption in div_mod ?

### ISSUE THREAD

**Issue by fblanqui** [coq/coq#18244]
#### Description of the problem

In https://coq.inria.fr/doc/V8.18.0/stdlib/Coq.Arith.PeanoNat.html, div_mod has assumption `y<>0` while div_mod_eq has no such assumption.

**Comment by mrhaandi** [comment]
`y<>0` is a necessary assumption for a generic division/modulo implementation and the corresponding generic proof.
In Coq, division is total such that `x/0=0` with remainder `x`.
The standard library is written in a way that `div_mod` is derived from the axioms (and other division implementations from other projects do use this).
`div_mod_eq` is specific to the particular Coq implementation.

Possibly, this should be better documented.

**Comment by fblanqui** [comment]
Thanks. Yes, some comment would be welcome.
