### ISSUE TITLE
"eauto" fails to solve goal "P /\ Q" when "split; eauto" works

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#18269]
#### Description of the problem

Consider this code:
```coq
Inductive expr :=
  (* Base lambda calculus *)
  | Var (x : nat)
  | Lam (x : nat) (e : expr)
  | App (e1 e2 : expr)
  (* Products *)
  | Pair (e1 e2 : expr)
  | Proj1 (e : expr)
  | Proj2 (e : expr).

Inductive val :=
  | LamV (x : nat) (e : expr)
  | PairV (x : val) (y : val).

Fixpoint of_val (v : val) : expr :=
  match v with
  | LamV x e => Lam x e
  | PairV x y => Pair (of_val x) (of_val y)
  end.

Definition is_val e := exists v, e = of_val v.

(** We want [eauto] is unfold this definition so it can prove [is_val] goals. *)
#[export] Hint Unfold is_val : core.
(** This enables [eauto] to solve the following goal. *)
Goal forall v, is_val (of_val v).
Proof. eauto. Qed.

(** But somehow this fails?!? *)
Goal forall v1 v2, is_val (of_val v1) /\ is_val (of_val v2).
Proof. intros. eauto. Qed.
```
I expected that whenever `split; eauto` works, then `eauto` will also work since `eauto` understands conjunctions in the conclusion. But somehow, that is not the case, and eauto fails to solve the final goal. This seems like a bug to me?

Adding a lemma `is_val (of_val v)` as a hint resolves the problem, but I'd prefer if I didn't have to state such a lemma.

#### Coq Version

Coq 8.18.0

**Comment by SkySkimmer** [comment]
`split; eauto` doesn't solve the example on my machine though.

**Comment by SkySkimmer** [comment]
Maybe you meant `Goal forall v1 v2, is_val (of_val v1) /\ is_val (of_val v2).` where `eauto` doesn't solve but `split; eauto` does.
In this case `eauto 6` also solves so I guess it's just a depth issue.

**Comment by RalfJung** [comment]
Sorry, I updated the example.

You are right, `eauto 6` fixes it. I didn't realize this simple example already needs extra fuel. Sorry for that!

Would be nice if `debug eauto` could give some sort of indication that it is giving up because it ran out of fuel...
