### ISSUE TITLE
update-compat.py should add a deprecation category for the next version to deprecation.ml?

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#18301]
ie in https://github.com/coq/coq/blob/025c08e670226b65cb9676309c4975372c40c952/lib/deprecation.ml#L63

Not sure if we actually want to make it automatic though.

At least probably not quite yet considering the file is being modified eg in https://github.com/coq/coq/pull/18248 so the script would be annoying to maintain.

**Comment by ejgallego** [comment]
I prefer we don't add more Python to part of Coq's codebase I have to maintain, for multiple reasons, being the main one that I lack Python expertise, and another big one due to most Python scripts being just hackery that is, indeed, a PITA to maintain.
