### ISSUE TITLE
Levels of tactic notations no longer properly respected

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#18368]
Since #18220 it seems that tactic levels are no longer properly respected, as in the following case.
CC @herbelin. Is this intended? If so, what are the new semantics of these levels?

```coq
Tactic Notation (at level 4) "test" := idtac "A".
Tactic Notation (at level 5) "test" := idtac "B".

Goal True.
test. (* Prints A, used to print B *)
```

#### Coq Version

Since #18220

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/blob/118e5d793d73445baf6f41015ea952955cfd7906/plugins/ltac/tacentries.ml#L35 https://github.com/coq/coq/blob/118e5d793d73445baf6f41015ea952955cfd7906/plugins/ltac/tacentries.ml#L45 https://github.com/coq/coq/blob/118e5d793d73445baf6f41015ea952955cfd7906/plugins/ltac/tacentries.ml#L116-L117 seem incorrect after that PR

**Comment by herbelin** [comment]
I made https://github.com/herbelin/github-coq/tree/master%2Bfix-binder_tactic-after-pr18220 which:
- fixes some changes of reference manual which should have been done in #18220 but were forgotten there,
- fixes `tacentries.ml` as spotted by @SkySkimmer,
- eventually fully inlines `binder_tactic` (which I think is ok except for plugins that possibly refers to it).
