### ISSUE TITLE
match! can't match on user-defined constructors ("The reference XXX was not found in the current environment")

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#18387]
#### Description of the problem

The match! pattern can't find the user-defined constructor below.  Changing Mtrue/MFalse to true/false works.  A bug or am I confused?

Separately, it's curious that `Init.v` can use lower case for constructor names (e.g. `Ltac2 Type bool := [ true | false ].`) while they generate error messages elsewhere.

```
From Ltac2 Require Import Ltac2.

Ltac2 Type mybool := [ Mtrue | Mfalse ].
Ltac2 m s := Message.print (Message.of_string s).
Ltac2 y () :=
   match! 'Mtrue with      (* this MTrue is fine *)
   | Mtrue => m "true"    (* error on this line *)
   | Mfalse => m "false"
   end.

(* Error: The reference Mtrue was not found in the current environment *)  

#### Coq Version 8.19+

**Comment by Janno** [comment]
`'Mtrue` is `constr:(Mtrue)`. There is no such Gallina entity in the example. Are you looking for `match Mtrue with ..`?

**Comment by SkySkimmer** [comment]
You are confused between `match!` on gallina terms and `match` on ltac2 values.

>this MTrue is fine

This is incorrect, the error is on the other Mtrue because of the order in which the `match!` notation gets checked.

**Comment by jfehrle** [comment]
The foregoing was preliminary to my real question:  Internally, how does the match below tell whether h is `Foot` or `Fuss`?  The varmap value for h is a `ValInt` of 0 for `Foot` and a `ValBlk` containing only a `ValStr` for `Fuss`.

While true/false is represented by 0/1 (following the order in which the constructors were declared in `Init.v`), `Foot` has a value of 0 even if I reorder the constructors.

```
From Ltac2 Require Import Ltac2.
Set Ltac Debug.

Ltac2 Type foo := [ Fuss (string) | Foot ].
Ltac2 m s := Message.print (Message.of_string s).
Ltac2 y h :=
  let i := Foot in
  let j := false in
  match h with
  | Foot => m "Foot"
  | Fuss a => m "Fuss"; m a
  end;
  m "x".  (* breakpoint set here *)
Goal True.
y Foot.
y (Fuss "arg").
```

For `Foot`:

![image](https://github.com/coq/coq/assets/1253341/dfea7b8d-83e1-4a88-9882-5dd524dda2b2)

For `Fuss`:

![image](https://github.com/coq/coq/assets/1253341/8261b72a-bfa1-47cc-bbb4-cea771ca1d08)

**Comment by SkySkimmer** [comment]
Constructors without arguments are represented as ValInt, constructors with arguments are represented as ValBlk. The order between the 2 kinds of constructors doesn't actually matter, only the order between constructors of the same kind matters.

**Comment by SkySkimmer** [comment]
(Fuss is `ValBlk (0, [|the_arg|])`, if there's another constructor with arguments after it it will be `ValBlk (1, the_args)`)
