### ISSUE TITLE
[build] After #17534 Ltac2 and stdlib depend on each other mutually

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#18381]
#17534 adds a `Require Ltac2.Array` to `theories/Compat/Compat818.v`.

This makes the stdlib depend on Ltac2. Ltac2 already depends on the stdlib, by using for example `f_equal` in `Notations.v`, or by the  `ltac2` plugin depending on `ltac1` (see PR to decouple that).

This issue is not detected by the CI as we compile `Ltac2` and the `stdlib` as a "single" theory, but IMHO we should clarify what is going on here. There are 3 choices:

- we keep the current status quo, `stdlib` and `ltac2` are compiled jointly (and depend on each other liberally).
- we restore the status quo, in which Ltac2 depends on the stdlib, but not the other way. This could be done by splitting the compat file.
- we invert the status quo, and make the stdlib depend on ltac2.

What do you think folks cc @ppedrot @SkySkimmer

**Comment by SkySkimmer** [comment]
I think eventually we want to be able to use ltac2 in the stdlib. Whether that should be done as option 1 or as option 3 I don't know.
