### ISSUE TITLE
Wrong section for Dune entry in Changelog

### ISSUE THREAD

**Issue by olaure01** [coq/coq#18407]
#### Description of the problem

The [entry about Dune version](https://github.com/coq/coq/blob/master/doc/changelog/11-standard-library/18359-dune_35.rst) should probably be in [Infrastructure and dependencies](https://github.com/coq/coq/tree/master/doc/changelog/12-infrastructure-and-dependencies) rather than "Standard library".

**Comment by olaure01** [comment]
@ejgallego

**Comment by SkySkimmer** [comment]
That's master not 8.19

**Comment by olaure01** [comment]
> That's master not 8.19

Oups sorry, thanks.

**Comment by ejgallego** [comment]
I'm sorry, I think indeed I typed the wrong number. Thanks for the report!
