### ISSUE TITLE
Files like coq-core.install should be in .gitignore

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#18414]
I'm not sure what the complete list of files is, but right now I see
```
$ git status
On branch stratfix
Your branch is up to date with 'origin/stratfix'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        coq-core.install

nothing added to commit but untracked files present (use "git add" to track)
```
on a rebased master

**Comment by SkySkimmer** [comment]
That's strange, for me coq-core.install only exists in _build/default

**Comment by JasonGross** [comment]
I could believe I invoked some command wrong, I'll reopen if I can reproduce

**Comment by ejgallego** [comment]
@JasonGross dune will put .install files in the sources dir if `-p` is passed; this is due to a OPAM limitation.

We didn't worry too much as most devs usually build Coq in dev mode; indeed they could be added to `.gitignore` if that's an issue for you.

**Comment by JasonGross** [comment]
@ejgallego I think adding them to .gitignore would be good; I don't see any reason not to, and files that can be generated by any command should probably be ignored.  It's not a big deal though
