### ISSUE TITLE
regression in coqdoc 8.18.0 (--external stopped working)

### ISSUE THREAD

**Issue by brandenburg** [coq/coq#18434]
#### Description of the problem

It appears that `coqdoc` stopped honoring the `--external` flag in version 8.18.0. It still worked in 8.17.0. 

#### Coq Version

```
% coqtop -v
The Coq Proof Assistant, version 8.18.0
compiled with OCaml 4.14.1
```

#### Example

Example that reproduces the issue: [example.zip](https://github.com/coq/coq/files/13745761/example.zip)

Example file `test.v`: 

```coq
From mathcomp Require Import ssreflect ssrbool seq.

Section Foo.

  Variable bar : seq bool.

  Definition baz := foldl andb true.

End Foo.
```

Expectation: `coqdoc` should link `foldl` to [its definition](https://math-comp.github.io/htmldoc//mathcomp.ssreflect.seq.html#foldl). 

Actual behavior: no link is generated. 

#### Steps to Reproduce

1. Create the `Makefile` and tell `coqdoc` to link to mathcomp definitions:   
```
% coq_makefile -f _CoqProject -o Makefile COQDOCEXTRAFLAGS = "--external https://math-comp.github.io/htmldoc/ mathcomp"
```
2. Generate the HTML spec:  
```
% make html      
```
3. Check if `foldl` is linked to https://math-comp.github.io/htmldoc//mathcomp.ssreflect.seq.html#foldl  
```
% grep 'mathcomp.ssreflect.seq.html#foldl' html/example.test.html 
```

With Coq 8.18.0, I'm getting nothing and inspecting the file confirms that the identifier `foldl` is not linked to anything.

With Coq 8.17.0, I'm getting the below output and the link works as expected. (Reformatted for clarity.)

```
&nbsp;&nbsp;<span class="id" title="keyword">Definition</span>
<a id="baz" class="idref" href="#baz"><span class="id" title="definition">baz</span></a> := 
<a class="idref" href="https://math-comp.github.io/htmldoc//mathcomp.ssreflect.seq.html#foldl"><span class="id" title="definition">foldl</span></a>  <===== LINKED AS EXPECTED
<a class="idref" href="http://coq.inria.fr/distrib/V8.17.0/stdlib//Coq.Init.Datatypes.html#andb"><span class="id" title="definition">andb</span></a>
<a class="idref" href="http://coq.inria.fr/distrib/V8.17.0/stdlib//Coq.Init.Datatypes.html#true"><span class="id" title="constructor">true</span></a>.<br/>
```

**Comment by herbelin** [comment]
It should work if you swap the two arguments of `--external`. Otherwise, a PR is on the way (#18448).

**Comment by brandenburg** [comment]
Great, that's already helpful. Thank you for looking into it!
