### ISSUE TITLE
Documentation of Constr.mkCase is unclear

### ISSUE THREAD

**Issue by ckeller** [coq/coq#18495]
#### Description of the problem

The [documentation of `Constr.mkCase`](https://github.com/coq/coq/blob/master/kernel/constr.mli#L147) is really unclear. l.149-150 is not coherent in variable names, and there are 5 arguments whereas `mkCase` expects 7. Thus the types in `pcase` are not explained, in particular the `'constr array` and the types `Name.t Context.binder_annot array` appearing in `pcase_branch` and `pcase_return`.

And there is no documentation at all for [`EConstr.mkCase`](https://github.com/coq/coq/blob/master/engine/eConstr.mli#L155).

#### Coq Version

Master (but most problems have been present for a long time)

#### Remark
It would help me a lot if you can give me a short explanation now of `mkCase`, many thanks!

**Comment by SkySkimmer** [comment]
~~~ocaml
  case_info (* the name of the inductive being matched and some derived metadata *)
  * 'univs (* universe instance of the inductive being matched *)
  * 'constr array (* parameters of the inductive being matched *)
  * 'types pcase_return (* return clause "in ind _ i as x return bla": the name array is the names of the indices followed by the "as x" name, the relevance is the relevance of the return type *)
  * 'constr pcase_invert (* the indices of the inductive being matched (always NoInvert when not using the definitional UIP flag) *)
  * 'constr (* the value being matched *)
  * 'constr pcase_branch array (* the branches *)
~~~
So for instance `match foo in _ = b as e return P with eq_refl => bar end` with a universe polymorphic `eq` , `foo : @eq@{u} A x y` and `P:SProp` would be (where a string literal stands for its interpretation to the relevant type)
~~~ocaml
{ ci_ind = "Bla.eq"; metadata },
"@{u}",
[|"A"; "x"|],
(([|"b"; "e"|], "P"), Irrelevant),
NoInvert,
"foo",
[|([||], "bar")|]
~~~

**Comment by ckeller** [comment]
Thank you very much for your answer.
Suppose that the `in` and `as` clauses do not matter, e.g. if `l` is of type `list nat` and I have `match l return bool with ...` which corresponds to `match l as l' in list _ return bool`. Should I create fresh names?

**Comment by SkySkimmer** [comment]
Names in the kernel are only for printing, you can use Anonymous even if the variables are used. If the variables are not used then certainly Anonymous should work fine.

**Comment by ckeller** [comment]
Thank you again.
I wonder why in your example the 4th argument is not `(([|Anonymous;"b"; "e"|], "P"), Irrelevant)`? Isn't it a problem that the length of the list is not the number of parameters +1 ?
Also, if these names are used only for printing, then shouldn't `"P"` be a lambda, as the documentation suggest?

**Comment by SkySkimmer** [comment]
Parameters are not bound so they don't get names, only real indices get bound.

> Also, if these names are used only for printing, then shouldn't "P" be a lambda, as the documentation suggests?

Not sure which part of the doc you mean, but "P" hasn't been a lambda since 8.15

**Comment by SkySkimmer** [comment]
No, as rels. So if P is `f b e` with `f` a section variable, "P" is `mkApp (mkVar "f", [|mkRel 2; mkRel 1|])`

**Comment by ckeller** [comment]
Ok, thanks!
