### ISSUE TITLE
Module Import on functor causes Anomaly "Uncaught exception Not_found"

### ISSUE THREAD

**Issue by CircuitCraft42** [coq/coq#18504]
#### Description of the problem

I accidentally defined a functor with an `Import` specifier (it was a module that I converted into a functor):
```coq
Module Type SIG.
End SIG.

Module Import A (S:SIG).
End A.
```

Error occurs on `End A.`:

> `Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/.`

#### Coq Version

```
The Coq Proof Assistant, version 8.17.1
compiled with OCaml 4.14.1
```

**Comment by SkySkimmer** [comment]
I guess you mean `Module Import A (S:SIG).`?

**Comment by CircuitCraft42** [comment]
@SkySkimmer Yeah, oops.
