### ISSUE TITLE
Error: Conversion test raised an anomaly: Anomaly "in Univ.repr: Universe plugin.51 undefined."

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#18518]
> Fails QuickChick unit test on Coq dev: [QuickChick/QuickChick@`235f6f2`/test/plugin/plugin.v#L51](https://github.com/QuickChick/QuickChick/blob/235f6f2156b06239d10e971b7f229f18b73fb67c/test/plugin/plugin.v#L51)
> 
> > File "./plugin.v", line 51, characters 0-22:
> > Error: Conversion test raised an anomaly:
> > Anomaly "in Univ.repr: Universe plugin.51 undefined."

@JasonGross any idea regarding the new (Universe?) issue with QuickChick?
The failing example blocks this PR from being merged, otherwise IIUC would break Coq CI.

_Originally posted by @liyishuai in https://github.com/coq-community/coq-ext-lib/pull/136#issuecomment-1894359315_

Can we get coqbot to minimize it for us?  Something like 
@coqbot minimize coq.dev
```bash
git clone git@github.com:JasonGross/coq-ext-lib.git --branch=cumul
cd coq-ext-lib
opam pin add -y .
opam install -y coq-quickchick
```

_Originally posted by @JasonGross in https://github.com/coq-community/coq-ext-lib/issues/136#issuecomment-1899976562_

**Comment by JasonGross** [comment]
@coqbot minimize coq.dev
```bash
git clone https://github.com/JasonGross/coq-ext-lib.git --branch=cumul
cd coq-ext-lib
opam pin add -y .
opam install -y coq-quickchick
```

**Comment by JasonGross** [comment]
@coqbot minimize coq.dev
```bash
git clone https://github.com/JasonGross/coq-ext-lib.git --branch=cumul
cd coq-ext-lib
opam pin add -y .
opam install -y -vv -t coq-quickchick
```

**Comment by liyishuai** [comment]
Consider:
```shell
opam pin add -n .
opam install --deps-only -y coq-quickchick
make
make install
make tests
```

**Comment by JasonGross** [comment]
@coqbot minimize coq.dev
```bash
git clone https://github.com/JasonGross/coq-ext-lib.git --branch=cumul
cd coq-ext-lib
opam pin add -y .
cd ..
git clone https://github.com/QuickChick/QuickChick.git
cd QuickChick
opam pin add -n .
opam install --deps-only -y coq-quickchick
make
make install
make tests
```

**Comment by JasonGross** [comment]
Running [here](https://github.com/coq-community/run-coq-bug-minimizer/actions/runs/7622396346/job/20760378095), in case the minimizer is still having trouble responding.

**Comment by JasonGross** [comment]
Looks like an issue in QuickChick, so closing for now
