### ISSUE TITLE
Coq generates inaccurate glob information for the Context command

### ISSUE THREAD

**Issue by yoshihiro503** [coq/coq#18516]
#### Description of the problem

I suppose the path of the variable is incorrect in the glob file when using the Context command.

The glob file of the following coq code looks a bit wrong.
```Hoge.v
Section Sec.
Context (foo : nat).
Definition f := foo.
End Sec.
```

```Hoge.glob
DIGEST f2eaf1911fb0a5cbba737f02a91995ae
FHoge
sec 8:10 <> Sec
R28:30 Coq.Init.Datatypes <> nat ind
binder 22:24 <> foo:1
def 45:45 <> f
R50:52 Hoge <> Sec.foo var
R59:61 Hoge Sec <> sec
```
The variable `foo` is defined as a binder with the path `foo:1`, but is referenced of the path `Sec.foo` from the definition of `f`. I guess the both path should be `Sec.foo`.
This causes problems in `coqdoc` and `coq2html`, where links are not properly placed.

#### Coq Version

* Coq version 8.18.0
* OCaml version 4.14.1
* Ubuntu 22.04.2 LTS

**Comment by SkySkimmer** [comment]
We could also put in 8.19.1 (if there's one)
