### ISSUE TITLE
Notation for Strings without double quotes

### ISSUE THREAD

**Issue by vmurali** [coq/coq#18545]
Is it possible to allow declaring a string without double quotes? For instance, I want:

```
Notation "'Foo' someString%string_argument" := (Bar "someString"%string) (at level 20).
(* Foo 25 = Bar "25". *)
(* Foo xkcd = Bar "xkcd". *)
```

**Comment by SkySkimmer** [comment]
I don't think so.

**Comment by vmurali** [comment]
Is it possible to reopen this issue as a feature request instead of closing it ?
