### ISSUE TITLE
`Ltac2 @ external` should do some sort of static typechecking

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#18553]
I thought there was a lightweight check but apparently I was wrong.

_Originally posted by @ppedrot in https://github.com/coq/coq/pull/18551#discussion_r1465320799_

**Comment by SkySkimmer** [comment]
Won'tfix

**Comment by SkySkimmer** [comment]
(The attempt at https://github.com/coq/coq/pull/18638 was too heavy compared to its benefit and it seems unlikely that we can do much better)
