### ISSUE TITLE
Anomaly

### ISSUE THREAD

**Issue by jmikedupont2** [coq/coq#18567]
#### Description of the problem
[Skip to content](https://github.com/meta-introspector/UniMath/commit/6f9ec2b5e199b2bad911f173e271950e46e5984d#start-of-content)
File "./UniMath/Introspector/Unimathcore_refl2_coq.v", line 190, characters 0-23:
Error:
Anomaly
"File "kernel/safe_typing.ml", line 462, characters 2-8: Assertion failed."
Please report at http://coq.inria.fr/bugs/.

#### Coq Version

version 8.18.0
compiled with OCaml 4.12.1

**Comment by SkySkimmer** [comment]
Duplicate https://github.com/coq/coq/issues/18401
