### ISSUE TITLE
bad coq_makefile error message `In file "_CoqProject": No such file or directory`

### ISSUE THREAD

**Issue by alpaylan** [coq/coq#18598]
#### Description of the problem

Currently, when using `coq_makefile` with `_CoqProject`, if you have a typo in a filename, the error you get is below.

```
COQDEP VFILES
In file "_CoqProject": No such file or directory
coq_makefile -f _CoqProject -o Makefile
make: *** [all] Error 2
```

I think it would be beneficial to have the filename that does not exist, so the user can specifically focus on that.

#### Coq Version

The Coq Proof Assistant, version 8.15.0
compiled with OCaml 4.14.0~alpha1

**Comment by SkySkimmer** [comment]
Can't reproduce, if I have `_CoqProject` containing `foo.v` which doesn't exist I get
~~~
make[1]: *** No rule to make target 'foo.v', needed by 'foo.vo'.  Stop.
~~~

**Comment by SkySkimmer** [comment]
Please provide a full reproduction code

**Comment by SkySkimmer** [comment]
Please reopen if you can provide a way to reproduce the issue.
