### ISSUE TITLE
uncaught Not_found on ltac backtrace trace

### ISSUE THREAD

**Issue by jmikedupont2** [coq/coq#18600]
Turns out the workaround is 
commenting out 
`Set Ltac2 Backtrace.`

Error: Backtrace:
Backtrace:

Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.

See my branch in unimath that triggered this error 
https://github.com/UniMath/UniMath/pull/1833

**Comment by jmikedupont2** [comment]
here is the workaround https://github.com/UniMath/UniMath/pull/1834

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/18603

**Comment by jmikedupont2** [comment]
I have a backtrace here now  using master branch, let me try your branch.

```
File Edit Options Buffers Tools Complete In/Out Signals Help                       Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.                                        Raised at Int.Map.find in file "sub/coq/clib/int.ml", line 40, characters 14-29
Called from Evd.find in file "sub/coq/engine/evd.ml", line 666, characters 29-56
Called from Evd.expand_existential in file "sub/coq/engine/evd.ml", line 727, char\acters 21-35
Called from Namegen.visible_ids.visible_ids in file "sub/coq/engine/namegen.ml", l\
ine 319, characters 16-47                                                          Called from CArray.Fun1.iter in file "sub/coq/clib/cArray.ml", line 664, character\s 6-13
Called from Namegen.visible_ids in file "sub/coq/engine/namegen.ml", line 326, cha\
racters 11-26
```

**Comment by jmikedupont2** [comment]
Okay I've been testing this and I also have continued on that patch and did some more debug print so this is doing great and it works for my purposes the unimath actually fails on the newer version of this Coq but it's good enough for my purposes so it gives me the first section
