### ISSUE TITLE
CI failing in windows (Unbound value Glib.Io.channel_of_descr_socket)

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#18607]
eg https://github.com/SkySkimmer/coq/actions/runs/7742277991/job/21111031505
~~~
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed conf-findutils.1
-> installed conf-gmp.4
-> installed conf-pkg-config.3
-> installed conf-adwaita-icon-theme.2
-> installed conf-cairo.1
-> installed conf-gtk3.18
-> installed dep-glib-compiled-schemas.1.0
-> installed ocamlfind.1.9.5~relocatable
-> installed zarith.1.13
-> installed dune.3.13.0
-> installed camlp-streams.5.0.1
-> installed csexp.1.5.2
-> installed dune-configurator.3.13.0
-> installed cairo2.0.6.4
-> installed dep-gtksourceview3.24.11
-> installed conf-gtksourceview3.0+2
-> installed lablgtk3.3.1.4
-> installed lablgtk3-sourceview3.3.1.4
-> installed coq-core.dev
-> installed coqide-server.dev
Error:  The compilation of coqide failed at "C:\\ci\\cygwin64\\home\\runneradmin\\.opam\\CP.2023.03+b1~dev\\bin\\dune.exe build -p coqide -j 2 @install".
-> installed coq-stdlib.dev
-> installed coq.dev

#=== ERROR while compiling coqide.dev =========================================#
[...]

# (cd _build/default && C:\ci\cygwin64\home\runneradmin\.opam\CP.2023.03+b1~dev\bin\ocamlopt.opt.exe -w -40 -g -O3 -unbox-closures -I ide/coqide/.coqide_gui.objs/byte -I ide/coqide/.coqide_gui.objs/native -I C:/ci/cygwin64/home/runneradmin/.opam/CP.2023.03+b1~dev/lib/ocaml\threads -I C:\ci\cygwin64\home\runneradmin\.opam\CP.2023.03+b1~dev\lib\cairo2 -I C:\ci\cygwin64\home\runneradmin\.opam\CP.2[...]
# File "ide/coqide/coqide_WIN32.ml.in", line 51, characters 37-68:
# Error: Unbound value Glib.Io.channel_of_descr_socket
~~~
I see no channel_of_descr_socket  in https://github.com/garrigue/lablgtk/blob/lablgtk3/src/glib.mli (last changed 7 years ago) so I don't understand where it was supposed to come from but it did work in the past.

lablgtk3 3.1.4 is very recent so may be the cause but how?

cc @garrigue

**Comment by garrigue** [comment]
I suppose that CoqIDE is using a patched version of lablgtk3.
Looking at glib, there is indeed a function `g_io_channel_win32_new_stream_socket`, so this is just about wrapping it.
The best would be to upstream this change, but I don't know where the fork is. There might be other changes too.

**Comment by SkySkimmer** [comment]
There's https://github.com/fdopen/opam-repository-mingw/blob/696c4b27488b4b0d3ec3929dbe65565cb91764a1/packages/lablgtk3/lablgtk3.0.beta3/files/lablgtk-3.0.beta3.patch#L49 but there's no such patch for 3.1.3 in that opam repo, and 3.1.3 is what was used in successful job https://github.com/coq/coq/actions/runs/7695468942/job/20968397258?pr=18565

Maybe @MSoegtropIMC knows more?

**Comment by MSoegtropIMC** [comment]
I did some Windows compatibility patches around this function quite a few years back, but I honestly don't remember the details. Indeed the patch needs to be ported if there is a new lablgtk3 version.

Please note that we don't use the fdopen repo any more but https://github.com/ocaml-opam/opam-repository-mingw.git#sunset for Windows specific patches. Bit IMHO all these Windows specific patch repos should go away - opam is sufficiently flexible to say that a patch should only be used in Windows. So I would prefer if it is done in the main repo.

I have a really bad cold right now and can hardly count to 3, so I would appreciate if someone else could do this.

**Comment by MSoegtropIMC** [comment]
P.S.: doing this in the main repo also avoids such issues.

**Comment by SkySkimmer** [comment]
>Please note that we don't use the fdopen repo any more but ocaml-opam/opam-repository-mingw.git#sunset 

This has no patch for [3.1.3](https://github.com/ocaml-opam/opam-repository-mingw/tree/sunset/packages/lablgtk3/lablgtk3.3.1.3) either AFAICT so I don't understand how it worked

**Comment by SkySkimmer** [comment]
PR upstreaming the patch https://github.com/garrigue/lablgtk/pull/176

**Comment by MSoegtropIMC** [comment]
I will patch it in Coq Platform - it is unfortunate that this broke shortly after a release (I do not pin non coq packages, so this breaks released versions).

**Comment by MSoegtropIMC** [comment]
See https://github.com/coq/platform/pull/398

**Comment by SkySkimmer** [comment]
>See coq/platform#398

Seems to still fail https://github.com/SkySkimmer/coq/actions/runs/7798942306/job/21268663727 (same error)

**Comment by SkySkimmer** [comment]
@MSoegtropIMC IIUC our CI is still broken because we use the `coq-ci` branch of the platform which wasn't updated.

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : sorry for that - I keep losing this from the radar. I will update coq-ci to main now.

**Comment by MSoegtropIMC** [comment]
done.

**Comment by SkySkimmer** [comment]
Now it fails with
~~~
/usr/bin/bash: line 1: cd: platform: No such file or directory
ERROR .\dev\ci\platform\coq-pf-04-installer.bat failed
~~~
(https://github.com/coq/coq/actions/runs/7831097685/job/21366637776?pr=18640)

**Comment by MSoegtropIMC** [comment]
OK, this has to do with the path changes I did to build serapi on Windows - dune produces really long path names and I had to save as much as I can in the root paths.

Before the platform folder was "<cygwin_root>/home/<user>/platform" - now it is "<cygwin_root>/platform" or from cygwin's point of view it is now "/platform". This likely needs to be adjusted in the github action.

Note that also the opam folder changes from "<cygwin_root>/home/<user>/.opam" to "<cygwin_root>/opam", but this should not be used in the action.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/18645
