### ISSUE TITLE
`Declare ML Module'`s "valid plugin names" restrictions seem to make it impossible to import certain libraries.

### ISSUE THREAD

**Issue by tom-p-reichel** [coq/coq#18647]
#### Description of the problem

I am doing some plugin development and I have `ezcurl` as an OCaml dependency. When I `Declare ML Module` my plugin, it recursively loads the `ezcurl` dependency. However, the `ezcurl` dependency has an `ocurl` dependency, and *this* dependency is *not* automatically loaded.

(I suspect it has something to do with the fact that `ocurl` is primarily C bindings around libcurl and might have an unusual dune configuration.)

When `ocurl` is manually specified in the loadpath through command line options and a legacy-style import is done, my plugin runs as intended.

However, I do not want to manually specify the location of a valid findlib library-- I would like to use the findlib import. 

Unfortunately, the findlib name is "curl" and I can't just `Declare ML Module "curl".` because Coq considers a findlib name valid if and only if it contains a `.`, which "curl" doesn't:
https://github.com/coq/coq/blob/541eb9c0eafe7c8546563388df0f18f0a18b0942/vernac/mltop.ml#L41-L42

I can use the `Declare ML Module "a:b".` notation in order to provide both a findlib name and a file, but when both are provided, it seems like the *file is taken by default as the first case*, and the findlib argument is discarded:

https://github.com/coq/coq/blob/541eb9c0eafe7c8546563388df0f18f0a18b0942/vernac/mltop.ml#L171-L179 

In order to get unstuck it looks like I need for either

1) coq to flawlessly load recursive dependencies
2) coq to allow me to load libraries that aren't loaded automatically-- even when the name doesn't contain a `.`.

#### Coq Version

Coq 8.17.1, Linux, though I just referenced code in the main branch, so I think this has been the case for a long time.

**Comment by ejgallego** [comment]
> Unfortunately, the findlib name is "curl" and I can't just Declare ML Module "curl". because Coq considers a findlib name valid if and only if it contains a ., which "curl" doesn't:

Indeed, it was suggested to use a different command name for findlib loading modules, unfortunately this suggestion was discarded, so I'm unsure what can be done now :/

**Comment by SkySkimmer** [comment]
We could still introduce a findlib-only command, and either deprecate using findlib with Declare ML Module or just keep both around.

**Comment by tom-p-reichel** [comment]
> > I am doing some plugin development and I have ezcurl as an OCaml dependency. When I Declare ML Module my plugin, it recursively loads the ezcurl dependency. However, the ezcurl dependency has an ocurl dependency, and this dependency is not automatically loaded.
> 
> That means the Declare ML Module fails with a dynlink error right?

Yes:
```
Error:
Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"/home/tpr/.opam/proofdb/lib/coq/../coq-core/../ezcurl/core/ezcurl_core.cmxs: undefined symbol: caml_curl_easy_cleanup\")")
```

where `caml_curl_easy_cleanup` is from `ocurl`. 


> Indeed, it was suggested to use a different command name for findlib loading modules, unfortunately this suggestion was  discarded, so I'm unsure what can be done now :/ That seems like a design flaw that is not easy to workaround.

Some hours after I wrote this issue I found a very ugly but apparently functional (?) workaround. In `mltop.mli`,  there is no direct way to force a ML module to be loaded-- it seems that every hook available does a `.` check. However, as a plugin, we can still
1) force a legacy import using the `a:b` notation
2) access the entire Findlib library interface

so given an arbitrary findlib name, I can use findlib to look up its package directory and add it to the ml path. This causes legacy loading to work as if someone specified the `ocurl` load directory as an `-I` argument. 

```ocaml
let load_findlib s : unit =  Mltop.add_ml_dir (Findlib.package_directory s); Mltop.declare_ml_modules false [String.concat "" [s;":";s]]
```

If anyone else runs into this problem on a version of coq where this is an issue, they can try installing this repo I threw together as a dependency (https://github.com/tom-p-reichel/coq-kissloader), and then you should be able to:
```coq
Require Import kissloader.Kiss.

(* "findlib enhanced" legacy module import *)
Findlib Load "curl".

(* load your module that has the above dependency *)
Declare ML Module "...".
```
