### ISSUE TITLE
Syntax errors reported at a wrong location in CoqIDE

### ISSUE THREAD

**Issue by yannl35133** [coq/coq#18682]
#### Description of the problem

In CoqIDE, with the following code
```coq
_.
_
```
The syntax error is reported in the second line.
More generally, it looks like most if not all syntax errors are reported at the wrong location when the file is more than one line long.

coqc is not affected by this bug.

#### Affected Coq Versions
b3e2ddbe4e4ff708562a94c0adf119b3efa904e9 -- master
(I bisected)

**Comment by herbelin** [comment]
Fixed by #19040 (the cleanup started in b3e2ddbe4e4ff708562a94c0adf119b3efa904e9 and continued among others in 3a3de8fb484d89347379f4a9c387901714919a4a was missing a case where line numbers were not passed, thus causing a regression in 8.18).
