### ISSUE TITLE
`intros` tactic has no effect on the goal but it should

### ISSUE THREAD

**Issue by Halbaroth** [coq/coq#18704]
#### Description of the problem

The `intros` tactic has no effect on the goal in the following script:
```coq
Require Import Coq.Classes.RelationClasses.
Require Import Coq.Relations.Relation_Definitions.
Definition R : relation nat := fun _ _ => True.

Lemma Foo : Reflexive R.
Proof.
  intros.
```
The output of `Print Reflexive` is:
```coq
Reflexive =
fun (A : Type) (R : relation A) => forall x : A, R x x
     : forall A : Type, relation A -> Prop

Arguments Reflexive {A}%type_scope R
```
So, I expect that `intros` introduces a new term `x` in the context of proof. It works if I use `intros x`, `intro x` or `intro`.

Strangely, `intros` works if we refine an instance of the class:
```coq 
#[refine] Instance ReflexiveEq : Reflexive R := {}.
Proof.
  intros.
```

But it doesn't if we open directly the proof context:
```coq 
Instance ReflexiveEq : Reflexive R.
Proof.
  intros.
```

It's not a big issue as using `intros` without naming introduced terms isn't recommended but the fact that `intros` works in some contexts and doesn't in very similar ones is really disturbing.

#### Coq Version

I use `Coq 8.19.0` compiled with `OCaml 5.1.1`.

**Comment by SkySkimmer** [comment]
This is the expected behaviour, intros doesn't reduce the goal unless made necessary by its arguments.

**Comment by CohenCyril** [comment]
The feature you require is implemented by `move`. You can write `move; intros` or  `move=> *` to achieve what you want. e.g.
```coq
Require Import Coq.Classes.RelationClasses.
Require Import Coq.Relations.Relation_Definitions.
Definition R : relation nat := fun _ _ => True.

From Coq Require Import ssreflect.

Lemma Foo : Reflexive R.
Proof.
move; intros
Restart.
move=> *.
Abort.
```
