### ISSUE TITLE
coqchk Fatal Error: Anomaly "Missing VM table for library Coq.Strings.Ascii"

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#18777]
### Description of the problem

[coqchk is failing on fiat-crypto's CI](https://github.com/mit-plv/fiat-crypto/actions/runs/8113718536/job/22181800672) (does Coq's CI check coqchk?)
[logs_21293150386.zip](https://github.com/coq/coq/files/14576916/logs_21293150386.zip)

This is from two weeks ago (2024-03-01), and the last record we have of it working is from 2024-02-19.  @ppedrot do you know if there's some recent change to .vo files around the vm that might be causing Fatal Error: Anomaly "Missing VM table for library Coq.Strings.Ascii"

### Version of Coq where this bug occurs

master (139b6ce921c1670e59060d602b09c64754ba10e5)

### Last version of Coq where the bug did not occur

b3ce0023bfca26f63848e697df83536fe497d186

**Comment by ppedrot** [comment]
Indeed this is surely #17674. We probably don't load correctly the VM segment in coqchk, I think I forgot this and we don't test this feature in the CI. Incidentally, this also shows that coqchk with the VM on doesn't check any well-formedness of the VM data, even without taking arbitrary execution into account.

**Comment by JasonGross** [comment]
https://github.com/coq/coq/pull/18779 fixes the problem where CI fails to check this



> Incidentally, this also shows that coqchk with the VM on doesn't check any well-formedness of the VM data, even without taking arbitrary execution into account.

How does it show this?

**Comment by ppedrot** [comment]
The representation of VM data changed after the PR, so coqchk should have failed with a malformed input error rather than this anomaly.

**Comment by SkySkimmer** [comment]
The problem is that we do `check_module (module_of_lib lib); Safe_typing.import lib vmtab` and `import` does the Vmlibrary.link call but checking `lib` wants to use the vm data from `lib`.

**Comment by SkySkimmer** [comment]
Reduced:
~~~coq
Definition foo := 1.

Definition bar := eq_refl 1 <: foo = 1.
~~~
(fails with coqchk -bytecode-compiler yes)

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/18782
