### ISSUE TITLE
Mysterious slowness/loop? in tactic unification

### ISSUE THREAD

**Issue by Janno** [coq/coq#18799]
### Description of the problem

The two files in [this gist](https://gist.github.com/Janno/91fc68661c99eae1e7bcc983b5eabf4d) are almost identical except for a single argument in the last premise of the `Goal`:.

```patch
--- /tmp/fast.v	2024-03-14 17:14:22.243193546 +0100
+++ /tmp/slow.v	2024-03-14 17:14:25.697187325 +0100
@@ -57,7 +57,7 @@
     (G0 : @G ti _Σ Σ σ H H2) (to_code_nvs : code) (vcpusharedg : roundup_gname) (body : @mpredI ti _Σ)
     (recall_bit : bool)
     (novastateinv : forall (_ : @bm_dram_bm_aux_1_bm_dram_GlobalGName H0) (_ : @bm_dram_bm_aux_1_bm_dram_GlobalG ti _Σ Σ)
-                      (_ : @bm_cpu_GlobalG ti _Σ Σ) (_ : @G ti _Σ Σ σ H H2) (_ : roundup_gname)
+                      (_ : @bm_cpu_GlobalG ti _Σ Σ) (_ : @G ti _Σ Σ σ H H2) (_ : roundup_gname) (_ : code) 
                       (_ : bool) (_ : bool) (_ : bool), @mpredI ti _Σ)
     (ecInv0 : forall _ : bool, @mpredI ti _Σ)
     (_ : forall (a1 : ptr) (a3 : bool),
@@ -74,7 +74,7 @@
                              (@bi_sep (@mpredI ti _Σ) (Tr (@mpredI ti _Σ))
                                 (@bi_sep (@mpredI ti _Σ) (Tr (@mpredI ti _Σ))
                                    (@bi_sep (@mpredI ti _Σ)
-                                      (novastateinv H5 H7 H8 G0 vcpusharedg about_to_ipc_reply a3
+                                      (novastateinv H5 H7 H8 G0 vcpusharedg to_code_nvs about_to_ipc_reply a3
                                          past_recall_in_roundup_impl )
                                       (@__at_body ti _Σ Σ a1 (Tr _)))))))))))),
   @Timeless (bi_car (@mpredI ti _Σ))
@@ -90,8 +90,8 @@
                       (@bi_sep (@mpredI ti _Σ) (Tr (@mpredI ti _Σ))
                          (@bi_sep (@mpredI ti _Σ) (Tr (@mpredI ti _Σ))
                             (@bi_sep (@mpredI ti _Σ)
-                               (novastateinv H5 H7 H8 G0 vcpusharedg about_to_ipc_reply recall_bit
+                               (novastateinv H5 H7 H8 G0 vcpusharedg to_code_nvs about_to_ipc_reply recall_bit
                                   past_recall_in_roundup_impl ) body))))))))).
   intros * T.
-  Timeout 1 Fail autoapply T with typeclass_instances.
+  Timeout 10 autoapply T with typeclass_instances.
 End Test1.
```

slow.v takes as long as I was willing to wait, fast.v fails immediately.

Other small changes, such as removing other arguments of the function, show the same difference in behavior. Slight changes to the shape of the goal, order of conjuncts in `bi_sep`, etc., can also lead to the same drastic difference.

The behavior seems extremely counterintuitive. Removing an argument that has no further dependencies should not lead to such a drastic difference, I think.

The problem is not new but updating to 8.19 has somehow made us run into this for the first time. It's unclear what exactly changed. The test files in the gist are the result of my attempt to minimize the actual regression but once I start abstracting our definitions the slowdown also appears on 8.18. So the fact that it triggers more often in 8.19 is probably not very important.

### Version of Coq where this bug occurs

8.16, 8.18, 8.19

**Comment by ppedrot** [comment]
Isn't it just that the first case is unification on ground terms but not the second one? Ground unification is conversion (fast), but otherwise it just fires up arbitrary unification.

**Comment by Janno** [comment]
I am struggling to see how removing that one argument makes any different in groundedness.

**Comment by ppedrot** [comment]
Wait a sec, the variable `T` doesn't bind at all the same thing in the two variants on master. This is because dependency analysis is performed by the intro pattern `*`.

**Comment by ppedrot** [comment]
Same behaviour on 8.16 as on master. Indeed, the difference is not about apply, it's about `intros *` as you're applying two very different variables in both cases.

**Comment by Janno** [comment]
You are completely right. I've spent so many hours debugging this I've completely lost track of what the error messages were saying. I'll leave this open for a bit more in case I can actually come up with a good reproducing example.
