### ISSUE TITLE
assertion failed in stm (new_node)

### ISSUE THREAD

**Issue by M-krishna** [coq/coq#18825]
## Description of the problem
Getting an error message when I'm trying to execute the attached code.

## Error message
```Anomaly ""Assert_failure _vendor+v8.16+32bit/coq/stm/stm.ml:557:4"."```

The **Fixpoint** `leq'` works fine. But when I try to run `ltb'`, I'm getting the error message I attached above.

### Small Coq file to reproduce the bug

```coq
Fixpoint leq' (a b: nat): bool :=
  match a, b with
  | O, _ => true
  | S _, O => false
  | S m, S n => leq' m n
  end.

Definition ltb' (a b: nat): bool := negb (leq' a b).
```

### Version of Coq where this bug occurs

8.16

**Comment by ejgallego** [comment]
That's jsCoq. We can transfer the issue there, but indeed this will a won'tfix (solved by flèche-based jsCoq 2)

**Comment by ejgallego** [comment]
Note that this works on current https://coq.vercel.app/ , so indeed, I'd suggest closing.

[I think I understand why after many edits this fails, but no point on fixing it]

**Comment by M-krishna** [comment]
I'll move this to jscoq. Thanks for looking into this folks. Hence closing this.

**Comment by ejgallego** [comment]
Thanks to you @M-krishna !
