### ISSUE TITLE
BackTo some non-existing state yields anomaly on exception Stm.Vcs_aux.Expired

### ISSUE THREAD

**Issue by hendriktews** [coq/coq#18844]
### Description of the problem

In a freshly started coqtop, `BackTo 2.` (or some other number greater than 1) yields
```
Error: Anomaly "edit_at 2: Uncaught exception Stm.Vcs_aux.Expired.."
Please report at http://coq.inria.fr/bugs/.
```
I saw this in 8.16.1, 8.19.1, and 8.20+alpha git hash e74eb7ffd4818715d127ee77917114bf34add67f

### Version of Coq where this bug occurs

8.16.1, 8.19.1, 8.20+alpha git hash e74eb7ffd4818715d127ee77917114bf34add67f

**Comment by ejgallego** [comment]
My understanding of the STM API is that indeed that's not allowed.

@hendriktews in which scenario did you find this issue?

**Comment by hendriktews** [comment]
I submitted this because coqtop told me to report it.
IMO this is a minor issue and the command is nonsensical, maybe just convert it into a proper error message?
I encountered this when experimenting in Proof General with BackTo's to the current state (which seem to be permitted and work). Eventually I forgot to delete one BackTo and got the anomaly when asserting the file again.

**Comment by ejgallego** [comment]
Indeed as this is an API contract "violation", it makes more sense to produce an anomaly instead of an error (which is usually user-recoverable), but I don't have an opinion.

**Comment by hendriktews** [comment]
Your decision of course and please close as you see fit. However, as long as coqtop says "please report", users don't have a choice, they have to open an issue here, haven't they?

**Comment by ejgallego** [comment]
That's indeed a very valid observation, we do indeed have a mess in the anomaly use / setup.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/18862
