### ISSUE TITLE
Coq no longer build on i386

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#18908]
### Description of the problem

https://launchpad.net/~jgross-h/+archive/ubuntu/coq-master-daily/+build/28029267/+files/buildlog_ubuntu-bionic-i386.coq_8.master~git~202404061918+24796-0~daily397-98a2533388~ubuntu18.04.1_BUILDING.txt.gz, https://launchpadlibrarian.net/721272217/buildlog_ubuntu-bionic-i386.coq_8.master~git~202403261806+24768-0~daily397-6da9eb4dd2~ubuntu18.04.1_BUILDING.txt.gz

I'm not sure what the error message actually is

Successful log: https://launchpadlibrarian.net/721126784/buildlog_ubuntu-bionic-i386.coq_8.master~git~202403251807+24758-0~daily397-9a6801ab3f~ubuntu18.04.1_BUILDING.txt.gz

### Version of Coq where this bug occurs

98a2533388, 6da9eb4dd2

### Last version of Coq where the bug did not occur

9a6801ab3f

**Comment by JasonGross** [comment]
https://github.com/coq/coq/pull/18823 seems like a likely culprit

**Comment by SkySkimmer** [comment]
The error message seems to be
~~~
File "kernel/uint63.ml", line 1:
Error: The implementation kernel/uint63.ml
       does not match the interface kernel/.kernel.objs/byte/uint63.cmi:
       Type declarations do not match:
         type t = Int64.t
       is not included in
         type t [@@immediate64]
       The first is not a type that is always immediate on 64 bit platforms.
       File "kernel/uint63.mli", line 11, characters 0-22:
         Expected declaration
       File "kernel/uint63_31.ml", line 12, characters 0-16:
         Actual declaration
~~~
so indeed #18823 

Not sure what's different from base+32bit

**Comment by SkySkimmer** [comment]
and https://gitlab.inria.fr/coq/coq/-/jobs/3992671/artifacts/file/_install_ci/lib/coq-core/kernel/uint63.ml (base+32bit from #18823) is using Int64.t

**Comment by JasonGross** [comment]
> Not sure what's different from base+32bit (which passes)

The ppa claims to use ocaml-base-nox (4.11.1-4.1~bionic~ppa1), the CI job claims to use ocaml          4.09.0       The OCaml compiler (virtual package), and the PR description says "OCaml 4.09 ignores it but it may unlock some optimizations on >=4.10."

**Comment by SkySkimmer** [comment]
I guess the PR is incorrect and we should just revert then.

**Comment by JasonGross** [comment]
There's no way to condition based on the architecture?

**Comment by silene** [comment]
Supposedly, when compiling to bytecode (and thus when typing too), the compiler is unaware of whether the target is 32 bits or 64 bits. So, when it encounters `Int64.t`, it has to error out, because it might be compiling for a 64-bit target.

> There's no way to condition based on the architecture?

Sure, we could duplicate `kernel/uint63.mli` depending on the architecture, the same way we already duplicate `kernel/uint63.ml`. But I am not sure it is worth the effort.
