### ISSUE TITLE
Spurious failure of abstract after subgoals have been discarded in Coq 8.19.1

### ISSUE THREAD

**Issue by silene** [coq/coq#18948]
### Description of the problem

Once subgoals have been discarded, e.g., by closing a bracket in interactive mode, the `abstract` tactical is no longer usable. This is a regression with respect to older versions of Coq and potentially a duplicate of #18942.

### Small Coq file to reproduce the bug

```coq
Goal True /\ True.
split.
{ idtac. } (* implicit admit *)
abstract exact I. (* (in proof Unnamed_thm_subproof): Attempt to save a proof with given up goals. *)
```

### Version of Coq where this bug occurs

8.19.1

### Last version of Coq where the bug did not occur

8.17.1

**Comment by SkySkimmer** [comment]
Duplicate #18942
