### ISSUE TITLE
Impossible to build a custom toplevel

### ISSUE THREAD

**Issue by ckeller** [coq/coq#18984]
### Description of the problem

[This documentation](https://coq.inria.fr/doc/V8.19.0/refman/practical-tools/utilities.html#using-coq-as-a-library) seems outdated:

- if taken as is, it fails with `ocamlfind: Package `coq.toplevel' not found`
- when replacing `coq.toplevel` with `coq-core.toplevel`, it fails with `Error: I/O error: topbin/coqtop_bin.ml: No such file or directory`
- when placing in the source directory where `topbin` is, it fails with `Error: Could not find the .cmi file for interface topbin/coqtop_bin.mli`

After [discussing on Zulip](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Building.20a.20toplevel), it seems that the feature is not supported anymore.

### Version of Coq where this bug occurs

8.19.0

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/18993
