### ISSUE TITLE
Extracting a function with implicit arguments incorrectly adds them as explicit ones

### ISSUE THREAD

**Issue by toku-sa-n** [coq/coq#18982]
### Description of the problem

In the reproduction code, `let get n = n` should be extracted because `bar` is extracted as `type bar = nat`. Instead, the implicit argument is added as explicit ones, changing the meaning of the code.

### Small Coq file to reproduce the bug

```coq
Require Import Coq.extraction.Extraction.

Inductive bar : nat -> Type :=
  | mk_bar : forall n, bar n.

Definition get {n : nat} (p : bar n) := n.

Extraction get.

(*
(** val get : nat -> bar -> nat **)

let get n _ =
n
*)
```

### Version of Coq where this bug occurs

8.19.0

**Comment by SkySkimmer** [comment]
Not a bug. Coq implicit arguments have nothing to do with extraction.
