### ISSUE TITLE
Ltac2 confused if "From Ltac2 Require Import Ltac2." is after "Goal True."

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19013]
### Description of the problem

Incorrectly reports "The reference x was not found in the current environment." error.
It works fine if you move `Goal True` after the `Require`.

### Small Coq file to reproduce the bug

```coq
Goal True.

From Ltac2 Require Import Ltac2.
Ltac2 x () := apply I.
x ().  (* The reference x was not found in the current environment. *)
```

### Version of Coq where this bug occurs

8.19+ (master 5/10/24)

**Comment by SkySkimmer** [comment]
The proof mode doesn't change so it's still parsing ltac1 not ltac2.
