### ISSUE TITLE
Small bug with universe polymorphic primitive constants bearing a universe declaration

### ISSUE THREAD

**Issue by herbelin** [coq/coq#19099]
### Description of the problem

I noticed something strange in the registration of universe binders for universe polymorphic primitive constants (in `declare.ml`) and, indeed, it can trigger an anomaly (with some effort though).

(The problem is that the registration has lost the information that the constant is polymorphic, so, the universe is registered as if for a monomorphic constant).

### Small Coq file to reproduce the bug

```coq
Require Import Uint63.
Set Universe Polymorphism.
Primitive array := #array_type.
Primitive make@{u} : forall A:Type@{u}, int -> A -> array A := #array_make.
Print Universes Subgraph (Top.make.u).
(* Anomaly "Uncaught exception Not_found." *)
```

### Version of Coq where this bug occurs

8.15 to master

### Last version of Coq where the bug did not occur

8.14

**Comment by SkySkimmer** [comment]
Can be shorter and not need uint
~~~coq
Set Universe Polymorphism.
Primitive array@{u} : Type@{u} -> Type@{u} := #array_type.

Print Universes Subgraph (Top.array.u).
~~~

**Comment by herbelin** [comment]
Ok.

And interestingly, the anomaly is obtained with coqtop but not with coqc (so that the test in #19100 does not really check it).

**Comment by Alizter** [comment]
@herbelin If coqc accepts that, does coqchk also accept it?

**Comment by herbelin** [comment]
There is no "logical" bug around and actually, `coqc` does not accept it: it just returns the appropriate error while coqtop returns an anomaly. The bug is in the table registering names for universes ("nametab"), so that some parts of Coq do believe that `Top.array.u` really exists in the kernel but it actually does not exist in the kernel.
