### ISSUE TITLE
Optional memtrace dependency is not made visible to OPAM

### ISSUE THREAD

**Issue by Janno** [coq/coq#19103]
### Description of the problem

Installing `memtrace` and `coq` at the same time via `opam` can lead to coq being compiled without memtrace support. This can be fixed by re-installing coq afterwards but that is less than ideal. I don't know anything about opam but the manual mentions a `depopts` field that can probably be used to fix this. (I hope `opam` is smart enough to schedule the compilation of `coq-core` after that of `memtrace` if coq optionally depends on it.)

**Comment by Alizter** [comment]
opam should rebuild any depopts IIRC. For example, when you install coq-native it recompiles Coq.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/19112
