### ISSUE TITLE
Tooltips are mislocated in CoqIDE when multibyte UTF-8 characters are present

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19136]
### Description of the problem

![image](https://github.com/coq/coq/assets/1253341/b8f41580-a762-45e0-92e7-5515a29d315a)

The tooltip should be on "x", not on the period.

### Small Coq file to reproduce the bug

```coq
Definition α := x.
```

### Version of Coq where this bug occurs

8.19

**Comment by SkySkimmer** [comment]
not sure why it didn't autoclose, maybe because https://github.com/coq/coq/pull/19137 is in v8.19 not master
