### ISSUE TITLE
"destauto" tactic has a hard-coded dependency on a variable named "x"

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19167]
### Description of the problem

See https://github.com/coq/coq/issues/11537#issuecomment-2153682071

The dependency appears to be from the line `let cl = induction_arg_of_quantified_hyp (NamedHyp (Id.of_string "x"))` in `Internals.find_a_destructable_match`.  That line was added by @ppedrot in 60f6d46c, dated 2/23/16.  @ppedrot, perhaps you could take a look at it?

The tactic was originally added by Pierre Courtieu in f3a53027, dated 7/22/2010.  I have no opinion whether this a valuable tactic worth fixing.

See also #11537.

FWIW "destructible" is the correct spelling.

**Comment by ppedrot** [comment]
This tactic is now deprecated, I think we can just close this issue and let the other one open as a reminder.
