### ISSUE TITLE
casts incorrectly refresh universes

### ISSUE THREAD

**Issue by kyoDralliam** [coq/coq#19161]
### Description of the problem

Check introduce fresh universe variables in places where it looks reasonable to report a failure.

### Small Coq file to reproduce the bug

```coq
Set Universe Polymorphism.
Set Printing Universes.
Section test.
  Universe u.
  Check Type@{u} : Type@{Set+1}.
  Fail Definition a := Type@{u} : Type@{Set+1}.
  Fail Check (fun A  : Type@{Set+1} =>  A) Type@{u}.
End test.
```

### Version of Coq where this bug occurs

8.19.0

**Comment by SkySkimmer** [comment]
It's not Check, it's pretyping of cast https://github.com/coq/coq/blob/32533fb6fcdda3c085b25ff6a46a5dc3b3e50bd5/pretyping/pretyping.ml#L1345-L1346

**Comment by SkySkimmer** [comment]
It was introduced in 4a8c1e387bb0b971e651458319e77603d87b2d08 but not sure that was really the right thing to do.

**Comment by SkySkimmer** [comment]
Let's see if anything relies on i in CI https://github.com/coq/coq/pull/19196
