### ISSUE TITLE
The "apply" tactic generates an unexpected universe constraint (w.r.t. "refine")

### ISSUE THREAD

**Issue by boulme** [coq/coq#19221]
### Description of the problem

Below, in the "zarb" proof, if we use "apply eq_refl", the universe inference fails while typechecking the Goal at the end.
If we replace "apply eq_refl" close to "FIXME" comment by "refine (eq_refl _)", the universe issue disappears.

### Small Coq file to reproduce the bug

```coq
Module Type Foo.

  Axiom t: Type -> Type.

  Axiom mayRet: forall {A:Type}, t A -> A -> Prop.

End Foo.


Module Bar.

   Definition t (A:Type) := A.

   Definition mayRet {A:Type} (a b:A): Prop := a=b.

   Lemma zarb: forall A (k: t A) x, (forall r, mayRet k r -> r=x tt) -> k = x tt.
   Proof.
     intros A k x H; eapply (H k).
     apply eq_refl. (* FIXME: refine (eq_refl _). *)
   Qed.

End Bar.

Module A <: Foo := Bar.

Goal (A.t nat) = (A.t nat). (* The universe inference fails here *)
Proof.
  apply refl_equal.
Qed.
```

### Version of Coq where this bug occurs

8.19.1, 8.17.1, 8.16.1   (don't know for others)

**Comment by SkySkimmer** [comment]
simplified:
~~~coq

Definition mayRet {A:Type} (a b:A): Prop := a=b.

Lemma zarb A (k:  A) : mayRet k k.
Proof.

  Succeed  Constraint mayRet.u0 < eq.u0.

  apply eq_refl. (* FIXME: refine (eq_refl _). *)

  Fail Constraint mayRet.u0 < eq.u0.
~~~

**Comment by SkySkimmer** [comment]
We end up here https://github.com/coq/coq/blob/763fb02e538e8d0d8d5a88801b9b18fbe66260d8/pretyping/unification.ml#L1145 with m1 = eq and n1 = mayRet, so the types look like `forall (A:Type@{u}), ...` with `u` respectively eq.u0 and mayRet.u0 so they get equated.

If we had contravariance on forall domains we would get the already present constraint mayRet.u0 <= eq.u0.
However that still wouldn't be enough to work well with the future of template poly where no such constraint should appear.

**Comment by SkySkimmer** [comment]
Maybe it would make sense to drop the constraints from the types (ie check compatibility ignoring universes), we should only need that the types have the same shape so that eg record eta expansion doesn't go wrong.

**Comment by SkySkimmer** [comment]
(new unification / refine recognizes that `eq` is rigid so it more eagerly reduces the mayRet side)
