### ISSUE TITLE
Feature request: underscores for sort variables

### ISSUE THREAD

**Issue by jpoiret** [coq/coq#19241]
### Is your feature request related to a problem?

For a definition like
```coq
Inductive eq@{s s'|u|} {A : Type@{s|u}} (a : A) : A -> Type@{s'|u} :=
  refl : eq a a.
```

we would like to be able to write `eq@{_ Type|_}` and let Coq infer the first sort, just like for universes.

**Comment by SkySkimmer** [comment]
This seems to already work in 8.19 and master:
~~~coq
Polymorphic Definition foo@{q q'|u +|+} : Type@{q|u} := forall T, T.

Check foo@{_ Type| _ _ }.
~~~
