### ISSUE TITLE
Inconsistency when evaluating Uint63 addmuldiv primitive

### ISSUE THREAD

**Issue by mkarup** [coq/coq#19402]
### Description of the problem

The expression `addmuldiv 64 42 42` evaluates to 0 when using `native_compute` / `cbn` / `cbv `, which I think(?) is the correct result, while it evaluates to 42 when using `Compute` and `vm_compute`, enabling a proof of `False`.

System: Linux (Fedora) x86-64
OCaml compiler version: 4.14.1

### Small Coq file to reproduce the bug

```coq
From Coq Require Import Uint63.
Open Scope uint63.

Eval native_compute in (addmuldiv 64 42 42). (* 0 *)
Eval cbn in (addmuldiv 64 42 42).            (* 0 *)
Eval cbv in (addmuldiv 64 42 42).            (* 0 *)

Eval vm_compute in (addmuldiv 64 42 42).     (* 42 *)
Compute (addmuldiv 64 42 42).                (* 42 *)
```

### Version of Coq where this bug occurs

8.17.1, 8.19.2

**Comment by ppedrot** [comment]
Can reproduce on master (11308c2307f239f7b660262077d665db650d0002).

**Comment by ppedrot** [comment]
cc @silene

**Comment by silene** [comment]
Indeed, the C code assumes that the shift is between 0 and 63. And looking at the OCaml code (i.e., `cbn`, `cbv`, `native_compute`), I am not convinced it is completely correct either. Indeed, OCaml's shifts, while better behaved than C' shifts, are still quite strange (e.g., `1 lsl min_int`).
