### ISSUE TITLE
coqchk: Fatal Error: Failure: Validation failed: sum: unexpected tag (in tag=0).

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#19455]
### Description of the problem

```

[intern /home/coq/.opam/4.13.1+flambda/lib/coq/theories/btauto/Reflect.vo ...
Context: vmlibrary/fld=1/vm_to_patch/fld=3/vm_non_subst_reloc/tag=8/fld=0/vm_caml_prim/tag=0
#0(#0(#0(1,1),#0(0,0),#0(1,0),#0(2,2),#0(3,2),#0(4,1),#0(5,2),#0(6,3)),1,9)
 failed!]

Fatal Error: Failure: Validation failed: sum: unexpected tag (in tag=0).
             Please report at http://coq.inria.fr/bugs/.
```
https://github.com/mit-plv/fiat-crypto/actions/runs/10257603888/job/28385335727#step:8:3825

Fiat Crypto CI is now failing to validate, but it looks like this should reproduce with just the standard library.  (Doesn't Coq CI check coqchk though?). I take it there was some PR in the past couple months that updated coqc and forgot to update coqchk?
https://github.com/mit-plv/fiat-crypto/actions/workflows/coq-docker.yml?query=branch%3Amaster says the CI succeeded on Jun 11 and failed on Jun 17, was there a PR merged in that window that fits the bill?

### Version of Coq where this bug occurs

3ee9cc1727dcd9f6031688016c7a8b472db22175

### Last version of Coq where the bug did not occur

b57e3f41d9d074ff41605cb82720d4da5a38bedc

**Comment by SkySkimmer** [comment]
#18973 is the only PR merged in that range which seems like it could affect VM validation

**Comment by SkySkimmer** [comment]
>Doesn't Coq CI check coqchk though?

By default coqchk ignores the VM data.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/19456

**Comment by JasonGross** [comment]
> > Doesn't Coq CI check coqchk though?
> 
> By default coqchk ignores the VM data.

Maybe we should enable the VM on the CI?

**Comment by ppedrot** [comment]
While we're talking about this, I think the way we handle the VM in the checker is completely nonsensical. Basically we trust whatever code found in the vo, which could execute arbitrary commands. We should probably instead recompile the bytecode on the fly when allowing the VM in the checker. It shouldn't be *that* expensive and it's much less crazy from a "checker" point of view.
