### ISSUE TITLE
Incorrect universe instance equality for constrexpr (used for mutual inductives checking that params are the same)

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#19462]
From https://coq.discourse.group/t/a-question-on-defining-mutually-inductive-types-with-universe-polymorphism/2397
~~~coq
Set Universe Polymorphism.
Inductive T1@{a c} (A:Type@{a})		:Type@{c} :=
.

Inductive S1a@{a b c d} (A:Type@{a})  (B:Type@{b}) (P : B -> T1@{a c} A) : Type@{d} :=
    with S1b (A:Type@{a})  (B:Type@{b}) (P : B -> T1@{a c} A)  : Type@{d} :=.
(*
Parameters should be syntactically the same for each inductive type.
Type "S1a" has parameters "(A : Type@{a}) (B : Type@{b}) (P : B -> T1@{a c} A)"
but type "S1b" has parameters "(A : Type@{a}) (B : Type@{b}) (P : B -> T1@{a c} A)".
*)
~~~

The problem is using Stdlib.(=) (polymorphic structural equality) at https://github.com/coq/coq/blob/77ae01107e4b115f5cb79e50e24bac4e1c04b05c/interp/constrexpr_ops.ml#L134 
Since the values contain different locations it incorrectly returns `false`.

**Comment by ppedrot** [comment]
One more reason to ban polymorphic equality from our codebase?
