### ISSUE TITLE
Ltac1 should give an error for repeated function formal parameters

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19486]
### Description of the problem

Very similar to #19485: Repeating the same formal parameter (e.g. "a" below) in an Ltac1 function definition is accepted even though it makes no sense. It should give an error. There are two cases (lines 1 and 4).

![image](https://github.com/user-attachments/assets/3fa57afd-fa40-4e40-998d-ab9389263af3)

### Small Coq file to reproduce the bug

```coq
Ltac x a a := idtac a.  (* bug *)
Goal True.
x 1 2.  (* prints "1" *)
let x := (fun a a => idtac a) in x 3 4.  (* bug *)
```

### Version of Coq where this bug occurs

8.21 alpha

**Comment by SkySkimmer** [comment]
>even though it makes no sense

It does make sense, it's just a function which ignores its first argument. We're not looking to add new features to ltac1 so closing this wontfix.
