### ISSUE TITLE
Ltac2 should warn unused variable for repeated function formal parameters

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19485]
### Description of the problem

Repeating the same formal parameter (e.g. "a" below) in an Ltac2 function definition is accepted even though it makes no sense.  It should give an error.  There are two cases (lines 5 and 7).

![image](https://github.com/user-attachments/assets/5e4fbd93-6a2c-4702-9424-f75d035ef086)

### Small Coq file to reproduce the bug

```coq
From Ltac2 Require Import Ltac2.
From Ltac2 Require Import Message.
Ltac2 m s := Message.print (Message.of_string s).

Ltac2 x a a := m a.  (* should complain *)
Goal True.
let x := (fun a a => m a) in x "y" "z".  (* prints "z"; should complain *)
```

### Version of Coq where this bug occurs

8.21 alpha

**Comment by SkySkimmer** [comment]
It should be warning that the first `a` is unused, not raising an error.

**Comment by ppedrot** [comment]
> it makes no sense

It does make perfect sense, this is literally just α-conversion. We allow in in Gallina and it's a staple of λ-calculus, so even though I agree it deserves a warning it's quite an exaggeration to deny it meaning.
