### ISSUE TITLE
Loss of sharing in 8.20

### ISSUE THREAD

**Issue by silene** [coq/coq#19529]
### Description of the problem

Some sub-terms that were physically equal in previous versions of Coq are now distinct. I have noticed the issue in one of my plugins. Until 8.19, it was recognizing the type `a <= b <= c` (i.e., `a <= b /\ b <= c`) by doing a quick equality check on the two occurrences of `b`. Since 8.20, it requires a full term comparison to recognize the type. Fixing my plugins is easy enough (and in hindsight, it was a mistake of me to take this sharing for granted.). But this loss of sharing might be the sign that something went wrong between 8.19 and 8.20, which could have an adverse effect on the performance of Coq.

### Version of Coq where this bug occurs

8.20.0

### Last version of Coq where the bug did not occur

8.19.2

**Comment by SkySkimmer** [comment]
also possible that binders are getting unshared from https://github.com/coq/coq/commit/f74df97bff97d3867eab87a5bbe985f3f4229f40 (#18859)
I think that would require `b` to contain the binders to matter, is that the case in your issue?

**Comment by silene** [comment]
Yes, it is about terms produced by the kernel. And their types have kind of been obtained by a reduction (e.g., `let x := b in => a <= x <= c`), so having some sharing seems natural, even in the absence of hash-consing. And now that you mention it, the loss of sharing indeed seems to occur only when the shared term contains a binder (e.g., `b` is `foo (fun v => bar)`).

I will try to create a small reproducer next week.

**Comment by SkySkimmer** [comment]
You can also try the big reproducer with https://github.com/coq/coq/pull/19539 (it should cherry pick cleanly on 8.20)

**Comment by SkySkimmer** [comment]
Fixed by https://github.com/coq/coq/pull/19539
