### ISSUE TITLE
Incorrect warning about notation conflict between "term" and "term as pattern"

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#19541]
### Description of the problem

The code shown below produces this warning:
```
Warning: Notations "{[ _ ]}" defined at level 1 with arguments constr at level 200 and "{[ _ | _ ]}"
defined at level 1 with arguments constr  as pattern at level 200 have incompatible prefixes.
One of them will likely not work. [notation-incompatible-prefix,parsing,default]
```
However, as far as I understand the explanation given by Thibaut Pérami [over here](https://gitlab.mpi-sws.org/iris/stdpp/-/issues/216#note_104616), this should not be a grammar conflict: `as pattern` is supposed to mean "parse like a term, but then convert the term to a pattern later". And indeed both notations work just fine together.

So, I think the warning is wrong and should not be shown in this case. Or am I misunderstanding something?

### Small Coq file to reproduce the bug

```coq
Class Singleton A B := singleton: A -> B.
Notation "{[ x ]}" := (singleton x) (at level 1, x at level 200).

Record propset (A : Type) : Type := PropSet { propset_car : A -> Prop }.
Notation "{[ x | P ]}" := (PropSet (fun x => P))
  (at level 1, x at level 200 as pattern, format "{[  x  |  P  ]}").
```

### Version of Coq where this bug occurs

8.20.0

**Comment by RalfJung** [comment]
The warning got introduced by https://github.com/coq/coq/pull/19049.
Cc @herbelin @proux01

**Comment by RalfJung** [comment]
I'm afraid I don't think this has been entirely fixed... building std++ with latest `coq.dev` still shows this warning:
```
File "./stdpp/propset.v", line 14, characters 0-128:
Warning: Notations "{[ _ ]}" defined at level 1 with arguments constr
and "{[ _ | _ ]}" defined at level 1 with arguments constr  as pattern
at level 200 have incompatible prefixes. One of them will likely not work.
[notation-incompatible-prefix,parsing,default]
COQTEST [ref diff ignored] tests/propset.v (ref: tests/propset.ref)
File "/home/r/Dokumente/Unisachen/iris/stdpp/tests/propset.v", line 1, characters 0-34:
Warning: Notations "{[ _ ]}" defined at level 1 with arguments constr
and "{[ _ | _ ]}" defined at level 1 with arguments constr  as pattern
at level 200 have incompatible prefixes. One of them will likely not work.
[notation-incompatible-prefix,parsing,default]
```

**Comment by RalfJung** [comment]
Here's a reproducer:
```
Reserved Notation "{[ x ]}"  (at level 1).
Reserved Notation "{[ x | P ]}"
  (at level 1, x at level 200 as pattern, format "{[  x  |  P  ]}").
```

**Comment by RalfJung** [comment]
I guess the difference to the original example is the missing explicit `x at level 200` in the first notation -- maybe we have to adjust our notation?

Would be good if the error could say what the actually relevant difference is, currently one has to read the message extremely carefully to realize that one time it says "with arguments constr" and the other time "with arguments constr as pattern at level 200".

**Comment by RalfJung** [comment]
> the usual ambiguity between constr and constr at level 200 

I'm not aware of this ambiguity so if you could point me to some issues or other documents explaining more, that'd be great. :)

The new warnings are awesome btw! Hard to read as they may be, they definitely beat just randomly guessing whether two notations will work with each other or not.

**Comment by proux01** [comment]
I mean things like https://github.com/coq/coq/issues/19631
