### ISSUE TITLE
Proof universe constraints leak from Admitted

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#19566]
~~~coq
Universes u v.

Lemma foo : Type@{u}.
Proof.
  exact Type@{v}.
Admitted.

Check Type@{u} : Type@{v}.
(* should succeed *)
~~~
since https://github.com/coq/coq/commit/3b4cf49e39ccb506aeb317aab818dc2fdc828175
Indeed the save_admitted change seems wrong (stops using initial_euctx)

cc @herbelin

**Comment by herbelin** [comment]
I would say that it is a design choice. Should `Admitted` discard the effects of the partial proof or take them into account. For instance, `Admitted` takes `clear` into account:
```coq
Section S.
Variable a:nat.
Theorem b1 : True.
clear a.
Admitted.
Theorem b2 : True.
Admitted.
End S.
Print b1. (* b1 : True *)
Print b2. (* b2 : nat -> True *)
```
I'm ok with both options.

**Comment by herbelin** [comment]
One more thing: the commit message for 3b4cf49e39cc does not mention the change, so I apparently did not consider the change to be significant enough. #19564 shows however that is significant.

**Comment by andres-erbsen** [comment]
At the same time, section-variable usage in the partial proof is not taken into account. Is that a bug too?
