### ISSUE TITLE
8.20 seems to break stdpp for me

### ISSUE THREAD

**Issue by jibnew** [coq/coq#19560]
### Description of the problem

I had 8.19.2 working fine.
Upon issuing
```
opam pin add coq 8.20.0
```
I get the response
```
[NOTE] Package coq used to be pinned to version 8.19.2
coq is now pinned to version 8.20.0

The following actions will be performed:
=== remove 1 package
  ⊘ coq-stdpp     1.10.0                    [conflicts with coq]
=== upgrade 4 packages
  ↗ coq           8.19.2 to 8.20.0 (pinned)
  ↗ coq-core      8.19.2 to 8.20.0          [required by coq]
  ↗ coq-stdlib    8.19.2 to 8.20.0          [required by coq]
  ↗ coqide-server 8.19.2 to 8.20.0          [required by coq]

Proceed with ⊘ 1 removal and ↗ 4 upgrades? [y/n] y
```
and indeed if I go ahead and proceed with it, after that some of my code that relies on stdpp stops working.

All this happens in wsl,
```
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.4169
```
and neofetch from inside wsl says (among less relevant things)
```
OS: Ubuntu 23.10 on Windows 10 x86_64
Kernel: 5.15.153.1-microsoft-standard-WSL2
Shell: bash 5.2.15
Terminal: wslbridge2-back
CPU: 13th Gen Intel i7-13620H (16) @ 2.918GHz
GPU: 2859:00:00.0 Microsoft Corporation Basic Render Driver
Memory: 407MiB / 11964MiB
```
opam --version returns 2.2.0

### Version of Coq where this bug occurs

8.20.0

### Last version of Coq where the bug did not occur

8.19.2

**Comment by tchajed** [comment]
What error do you get when you say "some of my code that relies on stdpp stops working"? Can you try the master branch of stdpp and see if that works?

**Comment by jibnew** [comment]
> What error do you get when you say "some of my code that relies on stdpp stops working"? Can you try the master branch of stdpp and see if that works?

I am embarrassed and don't even know whether I must be embarrassed. It works now. I don't remember what was the error, I only remember it involved stdpp.
I am also confused - seemingly I don't have stdpp now.
Anyway, seems like the issue can be closed. Sorry.

**Comment by tchajed** [comment]
Please don't be embarrassed, no harm done!

Sometimes in the process of giving instructions to reproduce the bug you'll find the bug goes away, either for mysterious reasons or because you missed some step before.
