### ISSUE TITLE
[coqdep] path relativization doesn't work for some Windows setups

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#19579]
### Description of the problem

The root of this issue is the following dune bug: https://github.com/ocaml/dune/issues/5833

Due to this bug, Dune fails when a rule depends on an absolute path that is inside the workspace. This is a terrible bug, but indeed signals the difficulty of mapping absolute to relative paths and viceversa in Unix envs.

The timeline for this bug is,
- #15220: introduced findlib loading mode, but without coordination with Dune, several important and extremely time-consuming fixes came in #15991 , #16073, #16075, #16115, #16428, #16658
- After these fixes, and adding support for this mode to dune upstream (https://github.com/ocaml/dune/pull/6167), we were hit by the dune bug. The problem is that coqdep will query findlib for the path of the `.cmxs` file, however `findlib`  will always return an absolute path, triggering the bug.
- Rodolphe added a workaround in coqdep (#17270, #18165), that indeed will try to turn the absolute paths from `findlib` in relative paths.

It seems that two problems do remain:
- path relativization doesn't work properly on windows, due to `C:\` path format
- path relativization may be used on libraries that are not in the build workspace.

Gaëtan pushed a workaround for the second issue at https://github.com/coq/coq/pull/18385 , however I'm not sure that is enough.

IMHO, these issues are easy to fix properly (and add tests).

**Comment by MSoegtropIMC** [comment]
@ejgallego : thank you for the detailed write up. I must admit that I got lost in the interdependencies of various issues in various tools, but your explanation is very clear.

**Comment by MSoegtropIMC** [comment]
I will take care of the coqdep issue.

**Comment by ejgallego** [comment]
Note that there is multi-platform tested code for making path relatives around in OCaml already, so maybe we can just reuse it? An example is https://github.com/ocaml/dune/blob/main/otherlibs/stdune/src/path_intf.ml / https://github.com/ocaml/dune/blob/main/otherlibs/stdune/src/path.mli

**Comment by MSoegtropIMC** [comment]
Thanks for the pointers! If you already have a detailed plan on how to change it (I didn't look at it as yet), we can also do it such that you do the change and I test it and approve it then.
