### ISSUE TITLE
"Disable Notation" is very verbose

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#19574]
Say I want to use unicode notation, except for `∨` since it is too similar to `v`. I might use something like
```
Disable Notation "_ ∨ _".
```

However, now when I run `make`, I will get a *lot* of this in the output:
```
The following notations have been disabled:
Notation "x ∨ y" := (or x y) : type_scope
```

This shouldn't happen -- the `make` output shouldn't spam the terminal with information about which notation has been disabled. (That doesn't happen for other output, like "foo has been defined", either.)

Cc @herbelin

**Comment by SkySkimmer** [comment]
Should be fixed since https://github.com/coq/coq/pull/18627

**Comment by RalfJung** [comment]
Ah, I should have mentioned this was on 8.18.0 -- so yeah that's possible. Thanks!
