### ISSUE TITLE
Rewrite rules complain about non-existant universe variable

### ISSUE THREAD

**Issue by Alizter** [coq/coq#19591]
In this example (8.20):
```coq

From Coq Require Import Prelude.
Global Set Asymmetric Patterns.
Unset Universe Polymorphism.

Inductive paths@{} {A : Set} (a : A) : A -> Set :=
  idpath : paths a a.

Notation "x = y" := (paths x y) : type_scope.
Local Open Scope type_scope.

Symbol ap : forall {A B : Set} (f : A -> B) {x y : A}
  (p : x = y), f x = f y.
Rewrite Rule ap_comp :=
| @ap@{} ?A ?P ?f _ _ (@idpath@{} _ ?a) => @idpath@{} ?P (?f ?a).

```

I've explicitly removed universe polymorphism, however rewrite rules are complaining that:
```
Error:
Universe level v appears in the replacement but does not appear in the pattern.
```
What universe `v` is it talking about? This also appears with universe polymorphism.

cc @yannl35133

**Comment by yannl35133** [comment]
Are you sure you're running the 8.20 release ? I can't reproduce (this is accepted without warning for me)

**Comment by Alizter** [comment]
Try this:
```coq
From Coq Require Import Prelude.

Global Set Universe Polymorphism.
Global Set Asymmetric Patterns.

Inductive paths {A : Type} (a : A) : forall (x : A), Type :=
  idpath : paths a a.
  About paths.

Symbol ap : forall {A B : Type} (f : forall (x :A), B) {x y : A}
  (p : paths x y), paths (f x) (f y).
Rewrite Rule ap_comp :=
| @ap ?A ?P ?f _ _ (@idpath _ ?a) => @idpath ?P (?f ?a).
```

**Comment by Alizter** [comment]
Also it seems I cannot add unvierse annotations inside patterns like:
```
| @ap@{u v} ?A ?P ?f _ _ (@idpath@{u} _ ?a) => @idpath@{u} ?P (?f ?a).
```
```
Undeclared universe: u.;
```

**Comment by yannl35133** [comment]
Input for universe variables is bad; it's going to be changed for the new version.
Meanwhile, every time you match on universe variables, add `+` at the end to make the list of declared universe variables extensible

**Comment by Alizter** [comment]
@yannl35133 I completely missed this syntax when reading the reference. That probably clears up my issue so I can define this correctly.
