### ISSUE TITLE
[regression] Coq 8.20 says "cannot be used as a hint" but the same hint worked fine with Coq 8.18

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#19629]
The problem concerns [this line](https://gitlab.mpi-sws.org/iris/simuliris/-/blob/df78e928a8931181279b430cf8d5f17953e919b3/theories/logic/satisfiable.v#L33) in Simuliris, specifically the `eauto using sat_mono, equiv_entails_1_1, equiv_entails_1_2`. In Coq 8.18, this line works fine. In Coq 8.20, it says
```
Error: @sat_mono cannot be used as a hint.
```
removing the hint does not fix the problem -- it seems like 8.18 was able to use this as a hint just fine, and it is actually needed to complete the proof, but in 8.20 it now refuses to use this as a hint?

I haven't been able to minimize this yet.

**Comment by SkySkimmer** [comment]
In the changelog:
>Changed: syntactic global references passed through the using clauses of auto-like tactics are now handled as plain references rather than interpreted terms. In particular, their typeclass arguments will not be inferred. In general, the previous behaviour can be emulated by replacing auto using foo with pose proof foo; auto (#18909, by Pierre-Marie Pédrot).

**Comment by RalfJung** [comment]
Ah, I didn't realize that this is what happens here. Thanks!
