### ISSUE TITLE
-time changes the timing

### ISSUE THREAD

**Issue by Tragicus** [coq/coq#19689]
### Description of the problem

Adding the `-time` option may dramatically change the output of a `Time` command.
This happens with Coq/Rocq at [`Tragicus:cs-save-key`](https://github.com/Tragicus/coq/tree/cs-save-key) and mathcomp [`Tragicus:algebra/mathcomp/algebra/poly.v`](https://github.com/Tragicus/math-comp/blob/fd65d141b3cbb8adc2f81b927a85355af52e4822/mathcomp/algebra/poly.v#L929), adding a `Time` at the beginning of the line. With the `coqc` command used by the makefile, the `Time` command responds `0.00x secs`, whereas adding `-time` to the `coqc` command yields the output `0.1xx secs`. The regular output of `coqc` with the `-time` option also shows the `0.1xx secs`.
Note that this does not happen with Coq/Rocq at `master` (805747bad2) or mathcomp at `master` (c16d2b0e).
What is happening here and how can I get consistent outputs ?

**Comment by SkySkimmer** [comment]
It may be spending time printing the command to show the preview.
Or maybe it's capturing a real computation time that Time doesn't (but that line doesn't seem likely to do that).

**Comment by Tragicus** [comment]
Should not the printing be done after after getting the computation time ? And then why does it affect both `Time` and `coqc -time` the same way, and why does it happen exactly with these branches?

**Comment by SkySkimmer** [comment]
>Should not the printing be done after after getting the computation time ? 

yes
IDK what's going on then

**Comment by silene** [comment]
You are only measuring a difference of one tenth of a second, right? Then, it might just be the cost of the garbage collector. Since `-time` produces a lot of output, it causes a lot of memory churn, which in turn triggers the garbage collector earlier.

**Comment by Tragicus** [comment]
Does that mean the GC triggers at different times in the run without `-time`, so that I observe the same global compile time, but the lines that are slow are different?

**Comment by SkySkimmer** [comment]
>This happens with Coq/Rocq at Tragicus:cs-save-key and mathcomp Tragicus:algebra/mathcomp/algebra/poly.v, 

I can't reproduce with those commits on my machine, with or without -time I get 0.002s from Time

**Comment by SkySkimmer** [comment]
Can you reproduce on a reduced file like
~~~

From mathcomp Require Import ssreflect ssrbool eqtype.
From mathcomp Require Import ssralg.
From mathcomp Require Import poly.

Import GRing.Theory.
Local Open Scope ring_scope.

Section PolynomialTheory.

Variable R : ringType.
Implicit Types (p q : {poly R}).

Lemma lead_coef_monicM p q : p \is monic -> lead_coef (p * q) = lead_coef q.
Proof.
Time have [-> | nz_q] := eqVneq q 0; first by rewrite mulr0.
by move/monicP=> mon_p; rewrite lead_coef_proper_mul mon_p mul1r ?lead_coef_eq0.
Qed.

End PolynomialTheory.
~~~
?

**Comment by silene** [comment]
> Does that mean the GC triggers at different times in the run without -time, so that I observe the same global compile time, but the lines that are slow are different?

Yes and no. The lines will indeed be different. But the global compile time might also be a bit larger. Indeed, since the GC is being run earlier, it might also end up being run more often. You can add `Print Debug GC` at the end of your file to know how many times the GC was run.

**Comment by Tragicus** [comment]
> > This happens with Coq/Rocq at Tragicus:cs-save-key and mathcomp Tragicus:algebra/mathcomp/algebra/poly.v,
> 
> I can't reproduce with those commits on my machine, with or without -time I get 0.002s from Time

Interesting, do you think this is worth trying with a more precise configuration (at least Coq should be at `eeeedcc6fb` and mathcomp at fd65d141)?

**Comment by Tragicus** [comment]
> > Does that mean the GC triggers at different times in the run without -time, so that I observe the same global compile time, but the lines that are slow are different?
> 
> Yes and no. The lines will indeed be different. But the global compile time might also be a bit larger. Indeed, since the GC is being run earlier, it might also end up being run more often. You can add `Print Debug GC` at the end of your file to know how many times the GC was run.

Here are the outputs:
- without `-time`:
```
minor words: 560846815.
promoted words: 18068621.
major words: 37376282.
minor_collections: 24
major_collections: 3
heap_words: 39961600
heap_chunks: 24
live_words: 35263991
live_blocks: 9697615
free_words: 4683185
free_blocks: 5
largest_free: 4624140
fragments: 14424
compactions: 0
top_heap_words: 39961600
stack_size: 312
```
- with `-time`
- ```
- minor words: 562631359.
promoted words: 17762475.
major words: 37069934.
minor_collections: 24
major_collections: 3
heap_words: 39961600
heap_chunks: 24
live_words: 34987848
live_blocks: 9620701
free_words: 4958769
free_blocks: 10
largest_free: 4865181
fragments: 14983
compactions: 0
top_heap_words: 39961600
stack_size: 312
```
They are indeed different, but I do not know enough to tell if that is significant enough.

**Comment by tchajed** [comment]
To see if GC is the culprit I would instead do a `Optimize Heap.` (which runs a full garbage collection) before the command. If the command after that then has the same timing with `Time` vs `-time`, the difference you're seeing is because of a difference in GC status. (You may also want to time the two `Optimize Heap` commands.)

**Comment by Tragicus** [comment]
With `Optimize Heap`, both commands take `0.00x` seconds, so it does indeed look like the GC causes the difference I observed. Funilly enough, it takes longer (`1.874s`) without `-time` than with it (`1.616`s).
Thank you for the help.
