### ISSUE TITLE
Can't "unfold" in *auto tactics

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19718]
### Description of the problem

**Let me revise this before you spend any time looking at it.  The example is not convincing as is.**

The unfold in the Hint Extern below should have worked.  The Hint Unfold should also have worked (though not both!).

### Small Rocq / Coq file to reproduce the bug

```coq
Theorem foobar : 1=1.
reflexivity.
Defined.

Hint Unfold foobar : plus.
Hint Extern 1 => idtac "unfold"; unfold foobar; idtac "after" : plus.

Goal foobar = foobar.
eauto 1 with plus nocore.  (* goal is still foobar = foobar
                              unfold
                              after *)
unfold foobar.             (* goal is eq_refl = eq_refl *)
```

### Version of Rocq / Coq where this bug occurs

9.0 alpha

**Comment by JasonGross** [comment]
`eauto` does nothing when it cannot fully solve the goal.  This behavior is documented, right?  I expect
```coq
Theorem foobar : 1=1.
reflexivity.
Defined.

Hint Unfold foobar : plus.
Hint Extern 1 => idtac "unfold"; unfold foobar; idtac "after"; shelve : plus.

Goal foobar = foobar.
unshelve (eauto 1 with plus nocore).
```
does what you want

**Comment by jfehrle** [comment]
Let me tweak the example tomorrow.  This one is not convincing as is.  I did some tests that are convincing IINM.

**Comment by jfehrle** [comment]
Indeed, (in part) I had not expected that `unfold` would succeed when it doesn't change the goal.  That should be in the doc.  I suspect that  applies to all the conversion rule tactics (lazy, cbv, simpl, ...)
