### ISSUE TITLE
"Create HintDb" drops existing hintdb with the given name

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19729]
### Description of the problem

The example creates a new, empty core database.  The command should give an error or a warning.  If removing an existing hintdb is useful, there should be a separate command for that, e.g. `Remove HintDb` or `Replace HintDb`.  Usually you wouldn't expect that a create command will remove an existing object.

### Small Rocq / Coq file to reproduce the bug

```coq
Create HintDb core.
Print HintDb core.

(*
Non-discriminated database
Unfoldable variable definitions: all
Unfoldable constant definitions: all
Unfoldable projection definitions: all
Cut: emp
For any goal ->   

*)
```

### Version of Rocq / Coq where this bug occurs

8.21 alpha

**Comment by ppedrot** [comment]
Duplicate of #16934
