### ISSUE TITLE
Primitive tactic to get the body of a hypothesis

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#19746]
### Is your feature request related to a problem?

It seems like https://github.com/coq/coq/pull/19023#issuecomment-2430131594 would be a bit more concise if expressed in terms of a `value of` tactic, which seems like a useful primitive to have.

### Proposed solution

It could be implemented as `eval cbv delta1 [x] in x` where `delta1` is from https://github.com/coq/coq/issues/9039 and the reduction engine should be optimized to avoid recursing into the body of `x`

### Alternative solutions

Allow the user to keep writing the more verbose version

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/19630
