### ISSUE TITLE
*auto tries tactics that don't unify with the goal - discrimination network (performance issue)

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19770]
### Description of the problem

`0+1+1 = 3` doesn't unify with `bar`, therefore the discrimination network should not find any matches and *auto should not try any tactics.  However IINM, the lines in the output containing "exact bar" for both `auto` and `tc eauto` indicate that the DN thinks there is indeed a match.  You can doublecheck by instrumenting `Hints.lookup_tacs`, which shows that `l'` is not empty (which it should be).

If there are multiple tactics in the head constant group, *auto may unnecessarily try all of them.  So there may be a noticeable performance impact.

We should create a test to verify the correct behavior when this is fixed.

### Small Rocq / Coq file to reproduce the bug

```coq
Theorem bar: 1+1+1=3.  reflexivity.  Defined.

Create HintDb db discriminated.
Hint Resolve bar : db.
Set Typeclasses Debug Verbosity 2.

Goal 0+1+1=3.
(* bug, shouldn't call tactic *)
Fail progress debug auto with db nocore.
  (* debug auto: *)
  * assumption. (*fail*)
  * intro. (*fail*)
  * exact bar (in db). (*fail*)

Fail typeclasses eauto with db nocore.
  1: looking for (0 + 1 + 1 = 3) without backtracking
  1.1: exact bar on (0 + 1 + 1 = 3) failed with: Unable to unify "1 + 1 + 1 = 3" with "0 + 1 + 1 = 3".
  1: no match for (0 + 1 + 1 = 3), 1 possibilities
  Goal 1 has no more solutions, returning exception: Proof-search
```

### Version of Rocq / Coq where this bug occurs

9.0 alpha

**Comment by ppedrot** [comment]
That's not a bug, this is the spec of discriminated matching. Everything transparent in the db is up-to potential conversion. Writing a hint database that scales requires conscious engineering w.r.t. the opacity of the involved constants.

**Comment by jfehrle** [comment]
If there really is a spec for discriminated matching, where can I find it?  Even so, how is this useful behavior?  There's nothing in these expressions to unfold, whether opaque or transparent.

If "not planned" means you don't want to spend time on this, perhaps I will look at at some point.
