### ISSUE TITLE
`tc eauto` fails to backtrack on evar assignment

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#19821]
### Description of the problem

The debug output shows that `tc eauto` does an `apply 1` but then doesn't backtrack on that and try `apply 2`, (which would give a goal of `2 = 2`, then provable with `reflexivity`).  `tc eauto` should be able to prove this very simple theorem.

### Small Rocq / Coq file to reproduce the bug

```coq
Hint Extern 1 => apply 1 : db.
Hint Extern 2 => apply 2 : db.
Hint Extern 3 => reflexivity : db.

Set Typeclasses Debug Verbosity 2.

Goal exists n:nat, n = 2.
eexists _.
Unshelve.
all: swap 1 2.  (* nat   ?n = 2 *)
typeclasses eauto with db.
(* 1 = 2 - used the first hint *)
(*
Starting resolution with 1 goal(s) under focus and 0 shelved goal(s) in regular mode, unbounded
Launching resolution fixpoint on 1 goals: ?X5 : nat
Calling fixpoint on : 1 initial goals, 0 stuck goals and 0 non-stuck failures kept with no progress made in this run.
Stuck: 
Failed: 
Initial: Goal 1 evar: ?X5 status: initial
considering goal 1 of status initial
1: looking for nat with backtracking
1.1: (*external*) apply 1 on nat, 0 subgoal(s)
1.1: after (*external*) apply 1 finished, 0 goals are shelved and unsolved ( )
Goal 1 has a success, continuing resolution
Calling fixpoint on : 0 initial goals, 0 stuck goals and 0 non-stuck failures kept with progress made in this run.
Stuck: 
Failed: 
Initial: 
Result goals after fixpoint: 0 goals: 
after eauto_tac_stuck: 0 goals: 
*)
Qed.  (* incomplete proof *)
```

### Version of Rocq / Coq where this bug occurs

9.0 alpha

**Comment by jfehrle** [comment]
I tried to figure out whether it's possible to backtrack a goal after it's been completed.  It doesn't seem to be possible using Ltac constructs:

```
Ltac pr_numgoals := let n := numgoals in idtac n " goals".
Goal exists n:nat, n = 2.
eexists _.
Unshelve.
all: swap 1 2.
(* apply 0; idtac "x"; fail. (* loses first goal *) *)
(* try (apply 0; fail).  (* loses first goal *) *)
(* all: idtac "foo"; [idtac "a" | idtac "b"]. (* no change; incorrect number of goals *) *)

all: try ((* pr_numgoals; *) idtac "y"; [ apply 0 | idtac "x"(* fail *) ]).
  (* no change; probably incorrect # of goals (message not shown) *)

all: try (pr_numgoals; [ apply 0 ; fail ]).
  (* loses first goal *)
```

I don't know whether the monad backtracking mechanism can handle this case.  Ltac `try` is defined as `let tclTRY t = tclORELSE0 t (tclUNIT ())`; `tclORELSE0` starts with `tclINDEPENDENT`, so it's not going to help.

If the current monads can't handle this cleanly, perhaps there could be two flavors of exceptions for monad backtracking: the current one and a new one to go back to the point just before the last evar was defined.  (Easy for me to say, I don't know if this is a workable approach.)

I believe you need this ability to let proof search solve SAT problems.  AFAICT SAT solvers guess variable values and then backtrack on the ones that turn out to be wrong (i.e. unsolvable with that assignment).

**Comment by SkySkimmer** [comment]
You only run tc eauto on the `nat` goal which is indeed solved, why would it backtrack?
