### ISSUE TITLE
A failing tactic with "all" seletor looses variable values.

### ISSUE THREAD

**Issue by yaitskov** [coq/coq#19866]
### Is your feature request related to a problem?

```coq
Require Import Ascii.

Theorem foo :
  forall a : ascii, (eqb a "q"%char) = false.
Proof.
  intros a.
  destruct a.
  - destruct b. all: reflexivity.
```

`*response*` buffer:
> Error: In environment
> b0, b1, b2, b3, b4, b5, b6 : bool
> Unable to unify "false" with "(Ascii true b0 b1 b2 b3 b4 b5 b6 =? "q")%char".
> 

destruct all reflexivity instantiates variables b0, b1, ... b6 and, eventually,  on some combination corresponding to letter 'q' it fails to unify. Values of variables b0, b1, ... b6 are not shown to the user and the user has to guess them.

### Proposed solution

Print values of all instantiated variables in the error message when tactic with fails.

### Additional context

Coq 8.20.0

**Comment by SkySkimmer** [comment]
>destruct all reflexivity instantiates variables b0, b1, ... b6

no it does not.
