### ISSUE TITLE
New Coq releases are missing a Last-modified header

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#5973]
Running `wget -N` on the GitHub Coq releases gives me something like:
```
wget -N https://github.com/coq/coq/archive/V8.7.0.tar.gz
--2017-10-18 10:26:59--  https://github.com/coq/coq/archive/V8.7.0.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/coq/coq/tar.gz/V8.7.0 [following]
--2017-10-18 10:26:59--  https://codeload.github.com/coq/coq/tar.gz/V8.7.0
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5629204 (5.4M) [application/x-gzip]
Saving to: ‘V8.7.0.tar.gz’

V8.7.0.tar.gz                             100%[=====================================================================================>]   5.37M  --.-KB/s    in 0.1s

Last-modified header missing -- time-stamps turned off.
2017-10-18 10:26:59 (42.8 MB/s) - ‘V8.7.0.tar.gz’ saved [5629204/5629204]
```
This means I can't use `wget -N` to download all of the releases without downloading lots of extra data.  Could Coq either mirror the release packages on coq.inria.fr, or configure GitHub to send last-modified headers?

**Comment by maximedenes** [comment]
I'm not sure I follow. Those archives correspond to tags, and we never modify them. So why do you need that information?

**Comment by JasonGross** [comment]
I guess I could instead condition on whether or not the file exists when grabbing sources.

**Comment by Zimmi48** [comment]
If your goal is to grab the tarball of the sources then indeed, they are automatically generated by Coq based on the tag so they will never change (apart possibly the data-compression ratio if GitHub suddenly decides to, but then our sha512 would be broken so someone could detect this).

**Comment by maximedenes** [comment]
Ok, so I'll close this issue.
