### ISSUE TITLE
Coq release management scripts must be shared and the processes must be documented

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#5976]
- [x] @maximedenes should share his pull request merging script
- [x] I should share my backporting script
- [ ] @maximedenes should share the script to upload the release to the website (apparently these do not exist yet)
- [x] We should create a release management documentation.

**Comment by psteckler** [comment]
Where should this documentation live?

**Comment by Zimmi48** [comment]
In `dev/doc` I would say, with the scripts in `dev/tools` and a link from `CONTRIBUTING.md`.
This is not unrelated to #5986.

**Comment by Zimmi48** [comment]
What is the script or command-line used to generate the list of contributors to one given version? @mattam82?
If it is a script, it should be shared as well and if it's a command-line, it could be included in the documentation at #6057.

**Comment by mattam82** [comment]
No script, ad-hoc command line, which one did you use?
Le jeu. 16 nov. 2017 à 13:13, Théo Zimmermann <notifications@github.com> a
écrit :

**Comment by mattam82** [comment]
Oh nevermind, I guess you used the list for Zenodo, I’ll try to dig up the
incantation.

**Comment by Zimmi48** [comment]
I'll close this now. The missing checkbox corresponds to a script that doesn't exist yet. See also https://github.com/orgs/coq/projects/2#card-10471352
