### ISSUE TITLE
bugs/opened/3263.v is non-deterministic

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#5981]
In [this AppVeyor run](https://ci.appveyor.com/project/coq/coq/build/master~537/job/ho0iwmmr2ey189on), [bugs/opened/3263.v](https://github.com/coq/coq/blob/master/test-suite/bugs/opened/3263.v) failed.
But in [this other AppVeyor run on the same commit](https://ci.appveyor.com/project/coq/coq/build/master~539/job/8ewgirptq6o2k7sm), the test passed.

Given that this is an "open" bug, maybe we could just remove this test to solve the problem.

#### Failure log (edit to complete)

- on AppVeyor on 2017-10-19

**Comment by ejgallego** [comment]
https://github.com/coq/coq/blob/master/test-suite/bugs/opened/3263.v
