### ISSUE TITLE
test-suite/success/paralleltac.v is non-deterministic

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#5983]
[`test-suite/success/paralleltac.v`](https://github.com/coq/coq/blob/master/test-suite/success/paralleltac.v) succeeded on [a first Travis build](https://travis-ci.org/coq/coq/builds/226960068) but failed on [a second build after an empty commit](https://travis-ci.org/coq/coq/jobs/227525341).

#### Failure log (edit to complete)

- On Travis on 2017-05-01.
- On AppVeyor on 2017-12-11.
- On AppVeyor on 2017-12-14.
- On AppVeyor on 2017-12-22.

**Comment by Zimmi48** [comment]
Another occurrence of failure of this test, this time on AppVeyor, gives more information on the reason of the failure: https://ci.appveyor.com/project/coq/coq/build/master~1410#L4954

```
File "C:\projects\coq\test-suite\success/paralleltac.v", line 58, characters 0-31:
Error:
Anomaly
"Uncaught exception Failure("The spawned process did not connect back in 2.0s")."
Please report at http://coq.inria.fr/bugs/.
```

@gares Assigning to you since the test is about `par:`.

**Comment by gares** [comment]
Well, this mesage just means that coqtop starts a worker, but it takes more than 2 seconds for the worker to open a socket connection with master.  This can only mean that the machine is trashing (2s to start coqtop).

If this arbitrary time out is pestering the tests, we can make the hard-coded time limit overrideable, but I guess we are just passing a too high value of `-j` to make.

**Comment by Zimmi48** [comment]
OK. Then given how infrequent this failure has been, I'll simply close this issue. However, let's continue to log such failures here and we'll reopen if we find that this is really a problem.

**Comment by psteckler** [comment]
>  trashing

Forgive me, but the word should be "thrashing".

**Comment by Zimmi48** [comment]
I had another occurrence today (https://ci.appveyor.com/project/Zimmi48/coq/build/v8.7~208), so it is not as infrequent as I thought (could have become more frequent recently, it seems the timing tests also have a higher failure rate these days). Anyways, reopening, we need to be more robust.

**Comment by Zimmi48** [comment]
New occurrence: https://ci.appveyor.com/project/coq/coq/build/master~1638

**Comment by Zimmi48** [comment]
New occurrence: https://ci.appveyor.com/project/coq/coq/build/master~4567#L3681

**Comment by Zimmi48** [comment]
It clearly occurs almost always when running the test-suite on Windows. Given how unsupported this parallel stuff is on Windows, why do we even bother running this test file on Windows?
@gares Can we make it skipped on Windows?

**Comment by ejgallego** [comment]
Yup, hard to say; a recent build on `master` succeeded so it
 is still non-deterministic. I opened #7588 to investigate more, but I'd be surprised if that's the cause.

**Comment by ejgallego** [comment]
Something we do on Gitlab is to print some information about the machine we are running the jobs in; this has been proved to be very valuable [at least to me] as I could identify why some problems happened.

I dunno how to do that on Win.

**Comment by Zimmi48** [comment]
Yet another failure example: https://ci.appveyor.com/project/coq/coq/build/master~4643
Note that even if the bug report was initially about `success/paralleltac.v`, the same problem is now occurring with many other test files.

**Comment by Zimmi48** [comment]
BTW, I just checked the history of these failures, and it started the day before I merged the toplevel binary PR (three such spurious failures before the PR was merged). So it really looks unrelated. It's more likely to be due to some changes on the AppVeyor side and it makes sense (I think) to get rid of this failure by just allowing for a longer timeout, like we do in #7533.

**Comment by gares** [comment]
Did we try -j1?

**Comment by Zimmi48** [comment]
I don't think there were any tentative to fix this problem besides mine.
