### ISSUE TITLE
output-modulo-time/ltacprof_cutoff.v is non deterministic

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#5985]
[`output-modulo-time/ltacprof_cutoff.v`](https://github.com/coq/coq/blob/master/test-suite/output-modulo-time/ltacprof_cutoff.v) failed randomly [on GitLab](https://gitlab.com/SkySkimmer/coq/-/jobs/17569286).

#### Failure log (edit to complete)

- On GitLab on 2017-05-31

**Comment by Zimmi48** [comment]
Related (I guess): `output-modulo-time/ltacprof_abstract.v` failed on Travis today.

**Comment by SkySkimmer** [comment]
Happens in CI and reproduced locally:
```diff
==========> TESTING output-modulo-time/ltacprof_abstract.v <==========
--- /tmp/coqcheck.mIRrVL	2017-12-19 12:11:58.693685594 +0100
+++ /tmp/coqcheck.0IdaN3	2017-12-19 12:11:58.693685594 +0100
@@ -7,6 +7,9 @@
 abstract (sleep; constructor) ---------%%       1s
 constructor ---------------------------%%       1s
 constructor -------------------------%%       1s
+sleep ---------------------------------%%       0s
+sleep -------------------------------%%       0s
+sleep' ------------------------------%%       0s
 sleep' --------------------------------%%       1s
 sleep' ------------------------------%%       1s
 tactic                                   local  total   calls       max 
0m0.000000s 0m0.000000s
0m0.850000s 0m0.120000s
==========> FAILURE <==========
    output-modulo-time/ltacprof_abstract.v...Error! (unexpected output)
```

**Comment by ejgallego** [comment]
Seems to be failing all over the place, @Zimmi48 would you mind pushing a quick fix disabling the test so CI works while the issue is resolved?

**Comment by SkySkimmer** [comment]
ltacprof_abstract is failing because it's new and came parallel to some other PR impacting this stuff, likely #6411.

**Comment by Zimmi48** [comment]
In this case, sorry for polluting this issue which something that is not actually related.

**Comment by Zimmi48** [comment]
https://gitlab.com/coq/coq/-/jobs/138267403

**Comment by Zimmi48** [comment]
https://gitlab.com/coq/coq/-/jobs/163268015

**Comment by Zimmi48** [comment]
https://gitlab.com/coq/coq/-/jobs/171241794

**Comment by Zimmi48** [comment]
https://gitlab.com/coq/coq/-/jobs/171499322

**Comment by Zimmi48** [comment]
This is one of our last regularly failing test.
