### ISSUE TITLE
Windows installer should not embed mingw make

### ISSUE THREAD

**Issue by gares** [coq/coq#5987]
When building math-comp on windows I made the following steps:
```bash
# export PATH=/cygdrive/c/Coq64/bin
# make
```
This failed in ways that are hard to imagine (i.e. even the way the win shell chops the command line into arguments is different..).

The good news is that once I run `rm /cygdrive/c/Coq64/bin/make.exe` then `make` did just work.

Given that such `make.exe` binary does not run the makefiles generated by `coq_makefile`, well... I guess we could just not ship it.

**Comment by Zimmi48** [comment]
Why the `component: IDE` flag?

**Comment by gares** [comment]
Beucase I believe the make.exe was put there in order to be able to click on the "build project" button in CoqIDE. Such buttun, IIRC, executes "make" (assuming many things...among which the fact that make exists).

Anyway, `component: windows-installer` would be my pick, but I've only found `component: installation` that seems a bit too wide.

**Comment by Zimmi48** [comment]
OK, these components are inherited from Bugzilla but feel free to edit them. Also, now that these are labels, feel free to use several components at once.

**Comment by maximedenes** [comment]
> Beucase I believe the make.exe was put there in order to be able to click on the "build project" button in CoqIDE. Such buttun, IIRC, executes "make" (assuming many things...among which the fact that make exists).

So what happens now if the user clicks on the button?

**Comment by MSoegtropIMC** [comment]
Hi,

I guess something like make only works if one has an OCaml system in the path.

I am working on a simple shell which can be used by make and the OCaml system command. This should fix most of the Windows shell issues and enable easy to use OCaml tools, native compute and make. As soon as I am finished with this, I will budnel OCaml with Coq.

I don't care much what is done with make until this shell is in. I use this make successfully with slightly patched makefiles, but if it makes life easier for people who have OCaml isnatlled if this is removed, it is probably better to remove it for now.

Best regards,

Michael

**Comment by Zimmi48** [comment]
Are there people who use the "build project" button successfully on Windows? If yes, would there be a way to fix your issue without breaking this button for these users?

**Comment by MSoegtropIMC** [comment]
Dear Théo,

I use the build project feature, but with manually patched make files. The main issue with make is shell compatibility. I am working on a simple but in those parts it implements posix compliant shell (written in plain C). I plan to use this in make as well as the OCaml system command. This should fix 99% of the issues with make and also enable native compute on Windows. 

I plan to finish this in January.

Best regards,

Michael
