### ISSUE TITLE
The error message "has type "Type@{Top.4}" which should be coercible to  "Type@{Coq.Init.Datatypes.23}"." is wrong

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#5997]
See, for example, #5996.  In cases where the types correctly don't line up because of universes, there's generally a note about universe inconsistencies and constraints.  I think the cases where there is no such note should be anomalies, or, at least, have more explanation; IIUC, this means that the kernel did not receive the constraints it was supposed to receive.  The only valid instance of this I can think of is:
```coq
Goal Type.
  exact_no_check Type.
Defined.
```

So, at the very least, the error message should probably mention something about likely culprits being `vm_cast_no_check`, `native_cast_no_check`, `exact_no_check`, and buggy tactics (which should be reported).

**Comment by SkySkimmer** [comment]
Duplicate https://github.com/coq/coq/issues/17420
