### ISSUE TITLE
Rename the bug files in the test-suite so that they match their github name?

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6001]
Would it be easy to mechanically rename the bug files in the test-suite so that they match the name in github issues?

**Comment by Zimmi48** [comment]
Yes, I used the following script:

```
while read line; do
  old=`echo $line | cut -f 1 -d ','`
  new=`echo $line | cut -f 2 -d ' '`
  if [ "$old" != "$new" ] && [ -e ${old}.v ]; then
    git mv ${old}.v ${new}.v
  fi
done < ~/Downloads/bugzilla2github.log
```

And re-used the trace of the migration script (`bugzilla2github.log`) as input.

See #6002.
