### ISSUE TITLE
Duplicate file `vernac/topfmt.cmi` installed for coq and coqide

### ISSUE THREAD

**Issue by zorun** [coq/coq#6006]
Starting from coq 8.7, `usr/lib/coq/vernac/topfmt.cmi` is installed by both the `make install-coq` and `make install-coqide` targets.

This is an issue because I build coq as two separate packages (`coq` and `coqide`) and they can't have duplicate files.

This is how I package `coq`:

```
# The second target is needed to install coqidetop.cmxs (needed for some
# frontend other than coqide, for instance coquille)
make COQINSTALLPREFIX="$pkgdir" install-coq install-ide-toploop
rm -f "${pkgdir}/usr/share/man/man1/coqide.1"
```

And how I package `coqide` (including the workaround for `topfmt.cmi`):

```
make COQINSTALLPREFIX="$pkgdir" install-coqide
install -D -m 644 -t "${pkgdir}/usr/share/man/man1/" man/coqide.1
# Remove toploop files installed by "install-ide-toploop" in the main package
rm -f "${pkgdir}/usr/lib/coq/toploop"/coqidetop.{cma,cmxs}
# In coq 8.7 this file is installed both by install-coq and install-coqide, remove the duplicate.
rm -f "${pkgdir}/usr/lib/coq/vernac/topfmt.cmi"
```

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/coq#n46

**Comment by Zimmi48** [comment]
The man page workaround that your packages show is related to #6307.

**Comment by Zimmi48** [comment]
Sorry that this wasn't addressed yet.
If you know the science of Makefile, you are welcome to propose a fix through a pull request though.

**Comment by ejgallego** [comment]
Unassigning, this is solved by using Dune, but a fix for make may still be needed.
