### ISSUE TITLE
eq_true vs is_true

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6012]
I'm looking for feedback about using `eq_true` vs `is_true`.
```
Inductive eq_true : bool -> Prop :=  is_eq_true : eq_true true.
Definition is_true b :=b = true.
```
The former, being a proper inductive type, seems to carry more contents in that it cannot be unfolded, hence cannot be confused with "... = true", cannot loose its role as a coercion if used such.

Both works the same wrt to `rewrite`.

Any return of experience about using one or the other?

**Comment by JasonGross** [comment]
I have only ever used `is_true`, not `eq_true`.  Here is something that works only with `is_true` and not with `eq_true`:

```coq
Require Import Coq.Init.Logic Coq.Bool.Bool.

Goal forall b b', is_true (b || b') -> True.
  intros b b' H.
  apply orb_true_iff in H.
```

I frequently end up splitting apart boolean equalities, so being able to easily apply lemmas about boolean combinators to turn them into `Prop` combinators is important.

**Comment by herbelin** [comment]
This is the point of my questions. `is_true` and `= true` are convertible (the same way say as `iff A B` and `and (A -> B) (B -> A)` are convertible). Do we have more to gain in conceptually isolating the coercion from `bool` to `Prop` (meaning that `orb_true_iff` would be `eq_true (b1 || b2) <-> eq_true b1 \/ eq_true b2` and your example work) or do we have interest in allowing more gateways between the coercion from `bool` to `Prop`  and Boolean equality. For instance, if one wants more gateways, one could also make that a lemma, say `true = b` is automatically applicable on a goal `is_true b`, since there are no reasons that `b = true` and `true = b` behave differently wrt (the concept of) a coercion from `bool` to `Prop`.

**Comment by JasonGross** [comment]
I am generally a fan of more convertibility / more coercions (see also #2481, #3119, #3179, #3190, #3191, #3301, #3512, #3927, #5291, #5293).  I've yet to see a convincing reason to isolate the coercion conceptually, other than, perhaps, more strongly enforcing a consistent schema for how to give things types.

> For instance, if one wants more gateways, one could also make that a lemma, say `true = b` is automatically applicable on a goal `is_true b`

How would you do this?  Certainly, you could define `is_true' b := true = b`, and make a coercion from `is_true'` to `is_true`, but I don't think you can coerce from `@eq bool true` to `is_true'` without running afoul of the uniform inheritance condition.

**Comment by herbelin** [comment]
> I am generally a fan of more convertibility / more coercions (see also #2481, #3119, #3179, #3190, #3191, #3301, #3512, #3927, #5291, #5293). I've yet to see a convincing reason to isolate the coercion conceptually, other than, perhaps, more strongly enforcing a consistent schema for how to give things types.

I'm unsure to understand well what you mean, especially by "enforcing a consistent schema for how to give things types". But anyway, about the second part:

> How would you do this? Certainly, you could define is_true' b := true = b, and make a coercion from is_true' to is_true, but I don't think you can coerce from @eq bool true to is_true' without running afoul of the uniform inheritance condition.

I was not thinking at using exactly the current mechanism of coercions, but rather at a generalization of things like what @zimmi48 studied in January, pushing more deeply the reasoning up to symmetry in the internals of Coq, starting with `apply`.

The first level, addressing problems of the form `T <= U` is to make the coercion function (so-called `Coercion.inh_conv_coerce_to`) supports a larger class of subtyping problems, including symmetry, but also what ssreflect calls views.

And, even if not useful for symmetry, to have a second level generalizing unification so that it solves equations up to Leibniz's equality, i.e. answering to questions of the form `t == u` by possibly returning a non-trivial "transport" from `t` to `u`.
