### ISSUE TITLE
"Anomaly: Uncaught exception Not_found" after eapply introduces UNBOUND_REL in evar contexts

### ISSUE THREAD

**Issue by Armael** [coq/coq#6016]
#### Version
Observed with both Coq 8.6 and 8.7

#### Operating system
Linux

#### Description of the problem
The following snippet reproduces the problem:
```
Hypothesis L: forall (x : nat * nat) (f g : nat -> nat -> nat),
    f (fst x) (snd x) = g (fst x) (snd x) ->
    (let (y,z) := x in f y z) = (let (y,z) := x in g y z).

Hypothesis LL: forall A B (f g : A -> B),
    (forall x, f x = g x) ->
    True.

Goal True.
  refine (let f1 := (fun '(x, y) => _) : (nat * nat) -> nat in _).
  refine (let f2 := (fun '(x, y) => _) : (nat * nat) -> nat in _).

  apply (@LL _ _ f1 f2).
  intro x. eapply L. simpl.
Abort.
```
The final `eapply` produces a goal with evars with `_UNBOUND_REL_1` and `_UNBOUND_REL_2` in their context. Which makes tactics (e.g. simpl) crash with `Anomaly: Uncaught exception Not_found`

**Comment by psteckler** [comment]
Hmmm, let me suggest again the idea of putting locations in exceptions, which would help here.

The `Not_found` exception here, as in #5761, is raised in `Context.Rel.lookup`, but the calling context differs. Here, that's called from `Tacred.unsafe_reference_opt_value`, which is called from the `match` in `Tacred.compute_consteval_direct`. There should probably be exn handlers in the clauses in `unsafe_reference_opt_value`.

**Comment by psteckler** [comment]
Yes, in this case, the backtrace is useful. But the anomaly message could have immediately printed out the exception source.

**Comment by maximedenes** [comment]
Isn't it what `coqtop -debug` does?

**Comment by ejgallego** [comment]
> But the anomaly message could have immediately printed out the exception source.

It is a matter of tradeoffs, keep in mind that not every exception will result in a fatal error, so recording that info has certainly a cost.

**Comment by ejgallego** [comment]
Backtraces inside some monads are sometimes lost, that would be interesting to fix indeed.

**Comment by ppedrot** [comment]
@ejgallego I didn't find anything about this in the literature, but every monad should come with its own notion of backtraces. Backtraces as lists reify the context of call-by-value applications, but if you change the effects then you have to change the corresponding notion of backtraces. I don't quite know how to do that properly though.

**Comment by ejgallego** [comment]
Very interesting thought, thanks @ppedrot ; indeed I think that is the direction to move forward in order to improve debugging of the tactics.

**Comment by ejgallego** [comment]
As we once discussed in person, it would have been interesting to have actually encoded the tactics in a free way. We will likely try something like that for the STM.

**Comment by psteckler** [comment]
If you have `e1 >>= e2 >>= e3`, would the backtrace be `e3 ; e2; e1`? Could `bind` be equipped with the machinery to update the backtrace?

**Comment by ejgallego** [comment]
> If you have e1 >>= e2 >>= e3, would the backtrace be e3 ; e2; e1?

I don't think so, but before, where is the exception raised?

**Comment by psteckler** [comment]
Let's suppose `e3` raises an exception. Wouldn't it be useful to know that you got there via `e1` and `e2`?

**Comment by ejgallego** [comment]
> Wouldn't it be useful to know that you got there via e1 and e2?

Depending on the monad you would interpreted `e1 >>= e2 >>= e3` as
```
f () = ...
e1;
e2;
e3;
```
in an imperative language, so indeed the backtrace should be `C[f] ++ e3`

**Comment by psteckler** [comment]
What is the context `C[ ]` here?

**Comment by ejgallego** [comment]
The backtrace belonging to `f`.

**Comment by psteckler** [comment]
FWIW, the `_UNBOUND_REL`s are created by the two `refine`s, and get propagated. Maybe that was obvious.

**Comment by ejgallego** [comment]
This is fixed in master.
