### ISSUE TITLE
GHC.Prim.Any becomes GHC.Exts.Any for Haskell extraction to GHC 8.2

### ISSUE THREAD

**Issue by bmsherman** [coq/coq#6022]
The Coq code to extract to Haskell makes use of any `Any` datatype, which in GHC is defined as `GHC.Prim.Any`:

https://github.com/coq/coq/blob/master/plugins/extraction/haskell.ml#L61-L81

However, beginning with GHC 8.2, this definition has been moved to `GHC.Base` or `GHC.Exts`, so that `Any` should be defined as `GHC.Base.Any`. It does not appear that this change is backwards compatible with older versions of GHC, so the definition must case-split based on GHC version. See a relevant discussion regarding the change made to GHC:

https://ghc.haskell.org/trac/ghc/ticket/10886

@tchajed has developed a patch that fixes this error.

**Comment by psteckler** [comment]
Should the extractor target the newest GHC, or maybe offer the ability to choose a version?

**Comment by tchajed** [comment]
We figured out that `GHC.Base.Any` works in both GHC 8.0.1 and 8.2.1, so we now have a simple solution that's backwards compatible. I'll send a PR soon.
