### ISSUE TITLE
Problem with recursive notations

### ISSUE THREAD

**Issue by SimonBoulier** [coq/coq#6032]
#### Version & OS
8.7.0 on linux

#### Description of the problem

The following code:
```
Notation "( x ; .. ; y ; z )" := (pair x .. (pair y z) .. ).
Goal nat * (nat * nat).
  refine (_ ; _ ; _).
```
Fails with:
```
Error: Syntax error: ';' or ';' expected (in [constr:operconstr]).
```
While those two variations are ok:
```
Notation "( x ; .. ; y ;; z )" := (pair x .. (pair y z) .. ).
Goal nat * (nat * nat).
  refine (_ ; _ ;; _).
```
```
Notation "( x ; y ; .. ; z )" := (pair .. (pair x y) .. z).
Goal (nat * nat) * nat.
  refine (_ ; _ ; _).
```

**Comment by herbelin** [comment]
Hi @SimonBoulier, this is fixed in #834 which was unfortunately not scheduled for 8.7. So, I'll guess you'll have to wait for 8.8 or apply the PR yourself, or work with the development branch which contains it. Sorry about that. Hugo

**Comment by ejgallego** [comment]
I am thus closing this issue, indeed sorry about that.

**Comment by SimonBoulier** [comment]
Ok, thanks.
