### ISSUE TITLE
Option `Asymmetric Patterns` is not documented

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6034]
#### Version

8.7.dev

#### Operating system
Linux

#### Description of the problem

The option `Asymmetric Patterns` exists, and it does something, but it is not mentioned at https://coq.inria.fr/refman/option-index.html.

**Comment by jff** [comment]
This seems to be done (see https://coq.inria.fr/refman/language/extensions/match.html#coq:flag.Asymmetric-Patterns)

I think that this issue can be closed.
