### ISSUE TITLE
Provide `Generalizable All Variables` without an effect on `Instance`

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6042]
#### Version

8.7.dev

#### Operating system
Linux

#### Description of the problem

Currently, running `Generalizable All Variables.` has two effects:

* Unbound variables in `` ` `` binders are automatically generalized, as documented at https://coq.inria.fr/distrib/current/refman/gallina-ext.html#hevea_command71
* The type of an `Instance` is automatically generalized. This is not documented, and surprising.

We would like to use the first feature, but not have it affect `instance`. There should be a variant of `Generalizable All Variables.` that does not affect `Instance`.

**Comment by SkySkimmer** [comment]
@Zimmi48 @mattam82 what's this assignment based on?

**Comment by Zimmi48** [comment]
It was based on the old Bugzilla semantics. This bug is open for anyone who wants to tackle it.

**Comment by RalfJung** [comment]
FWIW, this is still an issue in Coq 8.9.  By mere accident, I found a few occasions where we accidentally rely on this "feature".

**Comment by RalfJung** [comment]
Also from https://github.com/coq/coq/pull/6319#issuecomment-349388725 I learned that one can actually add `!` to a TC instance declaration to get less generalization. But @SkySkimmer this does not actually seem to disable generalization entirely -- the following compiles:
```
Class C (n: nat) := T: True.

Generalizable All Variables.

Instance I1: !C n.
Proof. now intros. Qed.
```
