### ISSUE TITLE
`wit_constr` methods in ltac plugin vs in main executable?

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6050]
Hi, this is basically a question for @ppedrot which I don't know where to raise (in particular, gitter is too volatile).

In #982, I allow declaration of custom entries for `constr`. @RalfJung asked if these entries could be used in `Tactic Notation`. I find it a legitimate use and I'm working on it.

These grammar extensions are primarily ltac-independent, so, not implemented in the ltac plugin, but, eventually, I want to use them in the ltac plugin, which means declaring `intern`/`interp`/`subst` methods for them. (Note even that in practise, these `intern`/`interp`/`subst` are exactly the ones for `constr` - or, probably even better, for `open_constr`)

Where to do the corresponding `intern`/`interp`/`subst` registration?

The `intern`/`interp`/`subst` infrastructure is currently in `Genintern` (`interp`) and `Geninterp` (`engine`) but all the effective declarations are in the ltac plugin.

On the other side, many generic arguments, starting with `constr`, are defined early, in `Stdarg` (`interp`), independently of ltac.

The main question is: Would it make sense to move the `intern`/`interp`/`subst` functions for the arguments defined in `Stdarg` outside the ltac plugin?

The question is not independent of ltac2. For instance, does ltac2 use the same interpretation function for the standard arguments or different ones? What can be factorized? What should be keep distinct?

As a side remark: I would be delighted that my work be ltac2 compatible, meaning here that if something of current Coq is going to be subsumed by ltac2, I would be happy to contribute to target ltac2 rather than ltac, or, even better, I would be happy that my work could target both ltac1 and ltac2 whenever possible.

**Comment by ppedrot** [comment]
> The main question is: Would it make sense to move the intern/interp/subst functions for the arguments defined in Stdarg outside the ltac plugin?

Short answer: No. An important part of Genarg is Ltac-specific. It happens that many generic arguments lie down in the hierarchy becauses of intricacies with the internalization and pretyping phase, but ultimately Genarg should be split into VernacArg and TacticArg, and the latter moved up into the Ltac plugin.

> The question is not independent of ltac2. For instance, does ltac2 use the same interpretation function for the standard arguments or different ones? What can be factorized? What should be keep distinct?

It's not using Genargs, although it does reuse a few interpretation functions for e.g. constrs for instance. Which can be a pain, because I have to work around code designed for Ltac quirks.

> As a side remark: I would be delighted that my work be ltac2 compatible, meaning here that if something of current Coq is going to be subsumed by ltac2, I would be happy to contribute to target ltac2 rather than ltac, or, even better, I would be happy that my work could target both ltac1 and ltac2 whenever possible.

The two code bases are essentially distinct. It may be still early for that, but I'd advise conservatism for Ltac1, i.e. fixing easy-to-fix bugs but leaving architectural issues alone, hoping that Ltac2 finalization and adoption is not so far.

**Comment by herbelin** [comment]
> Short answer: No. An important part of Genarg is Ltac-specific. It happens that many generic arguments lie down in the hierarchy becauses of intricacies with the internalization and pretyping phase, but ultimately Genarg should be split into VernacArg and TacticArg, and the latter moved up into the Ltac plugin.

My question was too general then. I'm particularly talking about `constr`. I provide custom entries in the main executable (say `metasyntax.ml` and `egramcoq.ml`). When I declare a new custom entry I want it to be usable in `Tactic Notation`. Where do I register the`intern/interp/subst` functions for the new entry (even if for telling that it has to be `intern/interp/subst`-ed like `open_constr`)?

Currently, the `intern/interp/subst` functions for `open_constr` are in the `ltac` plugin. I need to be able to call them from, say `egramcoq.ml`. Do I use a `Hook`? Do I move the methods for `open_constr` outside of `ltac`?

> Ltac2 finalization and adoption is not so far.

Do you have a transition strategy in mind?

**Comment by maximedenes** [comment]
@ppedrot would you mind answering the last questions raised by @herbelin so that we can close this issue? Thanks!

**Comment by SkySkimmer** [comment]
@ppedrot ping

**Comment by ppedrot** [comment]
Given that the motivation was to implement custom entries, the object of the question has become void anyways. We can thus close.

**Comment by herbelin** [comment]
I don't understand how the last comment answers Ralf's request but, missing time, let's close this.

**Comment by RalfJung** [comment]
The request, in general, is not even specific to custom entries -- for example, we have an `iAssert` tactic that takes a `constr` argument that *always* will be an Iris assertion, and hence should be parsed in the scope `%I`. Currently users have to write `iAssert (some ∗ term)%I`. For regular `Notation`, it is possible to have the `%I` as part of the notation so users do not have to write it, but sadly, that is not possible for `Tactic Notation`. This would be a very useful feature.

**Comment by ppedrot** [comment]
I don't see how it's related to @herbelin 's question though which is primarily about administrative issues about the code. As a matter of fact, Ltac2 already implements this feature and never had to mess with the architecture of generic arguments, so it would be easy to implement in Ltac1.

**Comment by herbelin** [comment]
> Ltac2 already implements this feature

I tried
```
From Ltac2 Require Import Ltac2.
Declare Custom Entry foo.
Ltac2 Notation "bar" x(foo) := x.
```
and got an `Unknown scope foo`.

**Comment by ppedrot** [comment]
Scopes are not custom entries.

**Comment by herbelin** [comment]
Anyway, even doing so, this would then be intern/interp/subst as a constr I guess (I did not check).

**Comment by ppedrot** [comment]
@RalfJung ask for a way to have notation entries for *terms* with a systematically open scope. As I said, Ltac2 provides this as an optional argument of the `constr` Ltac2 notation scope (and similarly for other `constr`-like scopes). I have no idea of what you're trying to do nor say in the two posts above. Notations as in the `Notation` command only make sense for Gallina terms. Same things for `Notation` scopes.

**Comment by herbelin** [comment]
I misunderstood @RalfJung's wish (which was then #4381).
