### ISSUE TITLE
CoqIde clutters working directory with auxiliary files

### ISSUE THREAD

**Issue by elazarg** [coq/coq#6053]
#### Version
version 8.7.0

#### Operating system
Windows

#### Description of the problem
Using CoqIde, the working directory is cluttered with files, for each file `x.v`: `x.vo`, `.x.aux`, `x.glob`

It would be nice to be able to configure a `build` directory where CoqIde can put these files.

**Comment by ppedrot** [comment]
@elazarg Did you use a call to the Make command of CoqIDE or something similar? AFAIK CoqIDE shouldn't decide to compile files of its own...

**Comment by elazarg** [comment]
@ppedrot I am using "Compile Buffer" when it's working, and when it's not, I am compiling it from the command line. However, the issue is not the creation of files, but the fact that the IDE `Require`s them to be there - it wouldn't look elsewhere.

**Comment by ppedrot** [comment]
@elazarg What is the structure of your Coq development? The standard way is to have a `_CoqProject` file (sometimes also called `Make`) that adds the relevant paths to the environment. In general you shouldn't have to call "Compile Buffer" whatsoever (which is quite buggy BTW).

**Comment by elazarg** [comment]
I am using flat structure. I couldn't find the documentation for `_CoqProject` format, and the IDE does not give useful errors on any of the `Compile` options (I understand this is a known bug in Windows).

I would like to keep the flat structure, and add a `build` folder to contain any non-`.v` file needed.

**Comment by Zimmi48** [comment]
If you move compilation outputs to the build directory does CoqIDE manage to load them if run with option `-R . Foo`?
