### ISSUE TITLE
MacOS tests on Travis sometimes fail.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6059]
The MacOS test-suite Travis build sometimes fail with something along the following lines:

```
/bin/sh: /bin/sh: cannot execute binary file
make[2]: *** [bugs/closed/1519.v.log] Error 126
make[2]: *** Waiting for unfinished jobs....
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [test-suite] Error 2
make: *** [submake] Error 2
/Users/travis/.travis/job_stages: line 57: shell_session_update: command not found
```

This trace is from a [failed build](https://travis-ci.org/coq/coq/jobs/295768247) on 2017-11-01.

My understanding is that the last line can be ignored (such lines also show after successful builds, and we avoid any problems with them by resetting `set +e` at the end of the Travis script). The really problematic line seems to be the first one.

This issue generally occurs in the middle of the test-suite run, e.g. on the above example the test had run for 18 minutes.

**Comment by mattam82** [comment]
Same happens here:

https://travis-ci.org/mattam82/coq/builds/304641290?utm_source=email&utm_medium=notification

**Comment by Zimmi48** [comment]
It had been a long time since I hadn't seen this error but it just happened again:

https://travis-ci.org/coq/coq/jobs/358373711#L5198-L5203
```
/bin/sh: /bin/sh: cannot execute binary file
make[2]: *** [bugs/closed/5323.v.log] Error 126
make[2]: *** Waiting for unfinished jobs....
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [test-suite] Error 2
make: *** [submake] Error 2
```

We should report this upstream (to TravisCI) but I don't really know what to tell them...

**Comment by ejgallego** [comment]
This could be due by many factors including an _out of memory_ or _out of storage_ condition in the container. I guess that unless it becomes more frequent we can just ignore it for now.
