### ISSUE TITLE
Documented semantics of Ltac expression evaluation are wrong

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6095]
#### Version

8.7.0

#### Description of the problem

[The documentation](https://coq.inria.fr/refman/ltac.html) contains many instances like this:

> #### Sequence
>
> A sequence is an expression of the following form:
>
>  _expr1 ; expr2_
>
> The expressions _expr1_ and _expr2_ are evaluated to _v1_ and _v2_ which have to be tactic values. The tactic _v1_ is then applied and _v2_ is applied to the goals generated by the application of _v1_. Sequence is left-associative.

I count three bugs in this paragraph, but the one I'm pointing to here is that evaluating _expr2_ to _v2_ happens *after* applying _v1_ to the goal, not before.  This is evidenced by the fact that `(idtac + shelve); constr:(1).` succeeds in shelving the goal, and `cut True; (let v := match goal with |- ?G => idtac G end in idtac).` displays two goals, not one.  Many other tactics have this same documentation issue.

(Other bugs in this paragraph: (1) Sequence is fully associative, not left-associative; (2) _v2_ need not be a tactic value if _v1_ has at least one success which leaves no remaining subgoals.)

**Comment by psteckler** [comment]
I'll have a PR for this particular bit.

If there are other documentation pieces with flaws, I can add those.

**Comment by psteckler** [comment]
Created #6300.
