### ISSUE TITLE
Ltac call to "case (ssrcasearg) (ssrclauses)" failed. Conversion test raised an anomaly

### ISSUE THREAD

**Issue by erikmd** [coq/coq#6106]
#### Version

The Coq Proof Assistant, version 8.7.0 (November 2017)
compiled on Nov 7 2017 10:41:15 with OCaml 4.02.3

#### Operating system

GNU/Linux Debian 9.2 amd64

#### Description of the problem

I tried compiling a specific commit of Multinomials with Coq 8.7, namely
https://github.com/math-comp/multinomials/commit/5b46e50983ee68dd1b6932e7e4a3bfc1113e7360
(which already compiles [with Coq 8.5](https://travis-ci.org/CoqEAL/CoqEAL/jobs/298479845#L758) and [with Coq 8.6](https://travis-ci.org/CoqEAL/CoqEAL/jobs/298479844#L758))
but with Coq 8.7 and MathComp 1.6.4 I got the error
```
File "./finmap/finmap.v", line 2297, characters 0-72:
Error:
Ltac call to "by (ssrhintarg)" failed.
Conversion test raised an anomalyAnomaly
                                 "Universe SsrMultinomials.finmap.1382 undefined."
                                 Please report at http://coq.inria.fr/bugs/.
```

I extracted below a minimal working example to reproduce the bug (but the error message is not exactly the same). And maybe it could be further minified in order not to rely on eqtype/ssrnat/seq/finset/fintype...

```
From mathcomp Require Import ssreflect ssrfun ssrbool eqtype ssrnat seq finset fintype.

Lemma domf_cat_MWE (K : finType) (V : Type) (f g : V) (domf : V -> {set K}) (x : K) :
  (x \notin domf g) && (x \in domf f) || (x \in domf g) = (x \in domf f) || (x \in domf g).
case: (boolP (_ \in _)).
(* Toplevel input, characters 0-23: *)
(* > case: (boolP (_ \in _)). *)
(* > ^^^^^^^^^^^^^^^^^^^^^^^ *)
(* Error: *)
(* Ltac call to "case (ssrcasearg) (ssrclauses)" failed. *)
(* Conversion test raised an anomalyAnomaly "Universe Top.8 undefined."  *)
(* Please report at http://coq.inria.fr/bugs/. *)
Abort.
```

**Comment by ppedrot** [comment]
This definitely looks like a universe constraint leak. I'd bet this is due to the crazy evarmap surgery performed in ssreflect. If I'm right (and I have faith I actually am), another argument to convince @maximedenes and @gares that such a practice is nonsense.

**Comment by gares** [comment]
Thanks for reporting, I'll look into that.

**Comment by gares** [comment]
Smaller example:
```
Require Import ssreflect.

Lemma domf_cat_MWE (K : Type) (V : Type) (f : V) (domf : V -> list K) (x : K) :
  (cons x (domf f) = domf f).
case: ((fun x : Type => fun w : x => w) _ (cons _ _)).
```

**Comment by gares** [comment]
Looks like it is the constraints coming from the pretyping of the argument of case that are lost:
```
Require Import ssreflect.
Definition K := nat.
Definition V := bool.
Definition xxx := Type.
Lemma domf_cat_MWE  (f : V) (domf : V -> list K) (x : K) :
  (cons x (domf f) = domf f).
case: ((fun (x : _) (w : x) => w) (list K) (cons _ _)).
```
indeed if one places `xxx` as the type of `x` the error goes away.

**Comment by gares** [comment]
I think the bugultimately comes from ssrmatching.ml4 line 1297
```
        do_once r (fun () -> c, Evd.empty_evar_universe_context);
```
Unfortunately the code was not structured in a way to let the real ustate percolate there... 
I'll try a fix tomorrow.

**Comment by strub** [comment]
For the record, see math-comp/finmap#15.

**Comment by gares** [comment]
Dear @erikmd , I think the commit above fixes the issue but I've only tested it in the reduced examples here. If you have a minute, please test it in your real use case.

**Comment by herbelin** [comment]
BTW: two (non directly related) questions about the error messages:
1. I don't remember: do we want to ask reporting anomalies raised by conversion? And, if yes, why to turn it into an error then?
2. Some colon and space is missing (but I'm going to submit a PR for it)

**Comment by mattam82** [comment]
@herbelin You're right, it should be an anomaly not an error but AFAI remember we needed to backtrack on conv anomalies in w_unify because of the FO heuristic which could produce ill-typed unification problems and send two terms of different types to conversion, and that needs to be fixed first.

**Comment by herbelin** [comment]
Yes, this is what I vaguely remembered too. Do you think it would be "safe" to move the handling of the anomaly to `w_unify` then?

**Comment by mattam82** [comment]
It would be equivalent I think.

**Comment by herbelin** [comment]
Shall we try the move (in master)? (Or would unifall make this anyway obsolete?)

**Comment by mattam82** [comment]
It will make it obsolete but I'm for the move still.

**Comment by erikmd** [comment]
Dear @gares, thanks a lot for the fix!
I've just started compiling gares/coq@bcc047e4792174e9507293ce1ccca12bfe2a4bf9 and I'll keep you informed.

**Comment by erikmd** [comment]
@gares I successfully compiled Coq and MathComp (cloning your fork, adding the appropriate `opam` files & running `opam pin -n add coq -k git .#HEAD` ; `opam install -j4 coq coq-mathcomp-field.1.6.4`) and the commit math-comp/multinomials@5b46e509 that had triggered the anomaly now compiles smoothly.
(At the same time @strub submitted an opam package for Multinomials that compiles with 8.5+8.6+8.7.0 :)
Thank you all! Erik

**Comment by Zimmi48** [comment]
@gares Did you ever submit a PR with this fix?

**Comment by maximedenes** [comment]
I think I'm the culprit here. I had found a limitation in gares' patch and never made a PR with a more complete fix. Adding it to my todo list.

**Comment by SkySkimmer** [comment]
Reopening because we didn't merge a regression test AFAICT.

**Comment by SkySkimmer** [comment]
This was kept open waiting for a test for years, may as well close.
