### ISSUE TITLE
`Redirect` does not redirect typeclass resolution log in 8.7

### ISSUE THREAD

**Issue by vzaliva** [coq/coq#6130]
#### Version

8.7.0

#### Operating system

Linux

#### Description of the problem

The following used to produce log.txt.out file with typeclass resolution log unde Coq-8.6.
Under 8.7 it does not redirect to file but rather prints to output. The file created but it is empty.

```
Typeclasses eauto := debug.
Redirect "log.txt" setoid_rewrite Rule.

```

**Comment by ejgallego** [comment]
Yup this is a TODO that I forgot to close, sorry.

**Comment by ejgallego** [comment]
@vzaliva you have a self-contained test-case we need to run?

**Comment by vzaliva** [comment]
Maybe not the shortest possible example but I have this one handy and just added "Redirect" to it to illustrate the problem. When run the file 'log.out' is empty.

```
Require Import Coq.Relations.Relation_Definitions.
Require Import ProofIrrelevance.
Require Import FunctionalExtensionality.
Require Import Coq.Program.Basics.
Require Import Setoid.
Require Import Morphisms.
Require Import Classes.Morphisms_Prop.

Section Ex.

  Parameter R: relation nat.
  Instance R_reflexive: Reflexive R. Admitted.
  Instance R_trasitive: Transitive R. Admitted.
  Definition Rext := pointwise_relation nat R.

  Parameter a: nat -> nat.
  Instance a_proper: Proper (R ==> R) (a). Admitted.
  Instance compose_proper: Proper (Rext ==> Rext ==> Rext) (compose). Admitted.

  Open Scope program_scope.

  Lemma Bar (b: nat -> nat) (C: forall x, b x < 10): Rext (a ∘ b) b. Admitted.

  Goal (forall (m n: nat) (c: nat -> nat -> nat) (bm: Proper (R ==> R ==> R) (c)),
           Rext ((fun x => a ∘ (c x)) m) (c 1)).
  Proof.
    intros m n c cm.
    Typeclasses eauto := debug.
    Redirect "log" setoid_rewrite Bar.
  Admitted.
End Ex.

```

**Comment by ejgallego** [comment]
A temporary fix will be merged in `master/8.7.1`, but however we hope to ship a more complete on in 8.8.

**Comment by ejgallego** [comment]
Reopening so keep track of the 8.8 patch.

**Comment by maximedenes** [comment]
@ejgallego Any update on this?

**Comment by ejgallego** [comment]
This was assigned by a medium priority to my queue which seems to mean these days "years away". I've temporally bumped the priority to high I'll see what I can do.

**Comment by ejgallego** [comment]
On the other hand, IIRC the temporarily fix means that we can safely delay this for now, the workaround in 8.8 is a hack but we can live with it.

**Comment by Zimmi48** [comment]
Then it's not really a regression anymore, right? We could reconsider the labeling...

**Comment by ejgallego** [comment]
I think this is still a regression, even if the original report is fixed I think there are still some cases where things don't work properly.

**Comment by ejgallego** [comment]
This seems fixed in `master`, likely by some toplevel cleanup.
