### ISSUE TITLE
CoqIDE 8.7.0 incompatible with LablGTK 2.18.6 and OCaml 4.06.0

### ISSUE THREAD

**Issue by xavierleroy** [coq/coq#6140]
It's all in the title:
```
$ opam switch 4.06.0
$ opam install coqide=8.7.0
# File "ide/ideutils.ml", line 376, characters 38-74:
# Error: This expression has type string but an expression was expected of type
#          bytes
# make[1]: *** [ide/ideutils.cmx] Error 2
```

**Comment by maximedenes** [comment]
Hi Xavier,

Thanks for the report! I believe this is addressed by https://github.com/coq/coq/pull/6045

So it probably means we'll have to release 8.7.1 reasonably soon.

**Comment by Zimmi48** [comment]
> So it probably means we'll have to release 8.7.1 reasonably soon.

I'd like indeed to release 8.7.1 reasonably soon but won't do it before at least #5975 and #5998 are solved.

**Comment by ejgallego** [comment]
By the way the opam package should depend on `num` for 4.06.0.

**Comment by xavierleroy** [comment]
@maximedenes: thanks for the feedback and the good news.

@ejgallego: the Coq package already depends on `num`, I took care of adding that dependency in several versions of the Coq package up to 8.6 myself, and apparently 8.6.1 and 8.7.0 are OK too.
