### ISSUE TITLE
Anomaly "True Future.t were created for opaque constants even if -async-proofs is off"

### ISSUE THREAD

**Issue by eponier** [coq/coq#6152]
#### Version
master (8.8+alpha)

#### Operating system
Ubuntu 16.04

#### Description of the problem
I tried to parse entirely a file containing
```
Module Type Sig.
  Parameter P : nat -> Prop.
  Parameter P_true : forall n, P n.
End Sig.

Module M <: Sig.
  Definition P (n:nat) := True.
  Lemma P_true : forall (b:bool), P (if b then 1 else 0).
  Proof.
    intros. constructor.
  Qed.
End M.
```

I got the anomaly
`Anomaly "True Future.t were created for opaque constants even if -async-proofs is off"`

**Comment by ejgallego** [comment]
@Zimmi48 did you test that in 8.7, and thus you placed the regression tag?
@eponier what do you exactly mean by "I tried to parse"? You called `coqc`?

**Comment by Zimmi48** [comment]
> did you test that in 8.7, and thus you placed the regression tag?

Yes.

**Comment by Zimmi48** [comment]
> what do you exactly mean by "I tried to parse"? You called coqc?

Use the button "evaluate buffer" in CoqIDE to trigger the anomaly.

**Comment by ejgallego** [comment]
Ok thanks.

**Comment by ejgallego** [comment]
This is 99% likely to be caused by my flags reorganization PR. For some reason a flag that used to be set in CoqIDE is not set now. Will have a look.

**Comment by eponier** [comment]
@Zimmi48 correctly interpreted what I meant.
