### ISSUE TITLE
coqide -R depends on the directory its called from

### ISSUE THREAD

**Issue by dailler** [coq/coq#6153]
#### Description of the problem

I encounter problems when passing the '-R' option to Coqide. When I switch directory, the command is not behaving the same (ie: I am not able to load my library).
The command I am using is the following:
`coqide -R /home/sdailler/test_coq/some_lib/ MyLib /home/sdailler/test_coq/b.v`

If I launch this command from test_coq, I can see that my library is loaded with following command in Coqide:
`Print LoadPath.`

which yields:
Logical Path:                 Physical path:
MyLib                         /home/sdailler/test_coq/some_lib
[...]

When using the exact same command to launch Coqide from my home, I cannot see "MyLib".
Attached is a tarball containing the files I am using.
[test_coq.tar.gz](https://github.com/coq/coq/files/1471152/test_coq.tar.gz)

Am I missing something obvious ?

**Comment by psteckler** [comment]
`MyLib` does not show up in the LoadPath for any directory except for `test_lib`.

Invoking coqtop 8.6.1 directly from the command line with the `-R` flag from any directory, the LoadPath always includes `MyLib`, suggesting that CoqIDE is doing something funny.

**Comment by psteckler** [comment]
CoqIDE 8.7 behaves the same.

**Comment by psteckler** [comment]
CoqIDE is passing the same arguments to coqtop, regardless of the pwd. Maybe it's to do with the `-ideslave` mode of coqtop. Investigating.

**Comment by psteckler** [comment]
I tried the same experiment with PG/xml, by putting the `-R` flag in a `_CoqProject` file. I can verify the flag is getting passed to coqtop via `ps` (and it's also getting passed from CoqIDE, regardless of directory).

In that case, `MyLib` always shows up in the `Print LoadPath` output, regardless of the directory I start emacs from.

The arguments passed to coqtop are basically the same from PG/xml and CoqIDE, except that CoqIDE passes `--xml_format=Ppcmds`.

**Comment by psteckler** [comment]
When CoqIDE is run from a dir other than `test_coq`, I see via debugging statements I added:
```
Adding loading path, physical: /home/steck/tmp/test_coq/some_lib logical: some_lib
```
which apparently overwrites what the `-R` command is doing. (This is `add_load_path` in `library/loadpath.ml`.)

**Comment by Zimmi48** [comment]
So that's again the crazy `Add LoadPath` feature of CoqIDE! My suggestion: let's get rid of it.

**Comment by Zimmi48** [comment]
See also #5734.

Good job on finding the cause of the bug BTW!

**Comment by psteckler** [comment]
> So that's again the crazy Add LoadPath feature of CoqIDE!

Yes, I commented out that command which happens on startup, and `MyLib` shows up regardless of where CoqIDE is started from.

@gares Should we get rid of this command, or make it conditional on something else?

**Comment by psteckler** [comment]
@gares Any thoughts on removing the `Add LoadPath` from the CoqIDE startup?

**Comment by Zimmi48** [comment]
@herbelin Maybe you want to express your opinion on this question as well. Would you be okay with removing the `Add LoadPath` from CoqIDE start-up?

**Comment by herbelin** [comment]
I am.

**Comment by psteckler** [comment]
Created #6311.
