### ISSUE TITLE
AppVeyor hanging on some test file.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6154]
IIRC we have removed the `interactive` series of tests from AppVeyor because of the frequent hanging that was observed (and made the overall test fail). AFAIK the underlying problem has not been fixed yet.

I've just observed a similar problem on `bugs/closed/1918.v` [here](https://ci.appveyor.com/project/coq/coq/build/master~854) and [here](https://ci.appveyor.com/project/coq/coq/build/master~853).
This test did not change so something else must have that made it more fragile.

**Comment by maximedenes** [comment]
@gares and I have investigated related issues. I hope to help fixing the underlying problems soon, but there are more pressing things to fix on Windows at the moment.

**Comment by Zimmi48** [comment]
@maximedenes Would be interesting to have a new look at this in the light of the recent experiments with Windows and GitLab CI...

**Comment by SkySkimmer** [comment]
They are running in azure.

**Comment by Zimmi48** [comment]
Perfect, then this issue can be closed soon.
