### ISSUE TITLE
Notations silently drop universe instances

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#6157]
eg
``` coq
Set Printing Universes.
Polymorphic Definition typ@{i} := Type@{i}.
Notation "\ i" := typ@{i} (at level 0).

Universes i j. Constraint i < j.

Check \ j : \ i. 
(*typ@{Top.5} : typ@{Top.4}
     : typ@{Top.4}
(* Top.4 Top.5 |= Top.5 < Top.4
                   *)*)
```

As far as I can tell the notation declaration is equivalent to `Notation "\ i" := typ (at level 0)`.

`Notation "\ i" := Type@{i}` does not bind `i` as a universe so the universe instance `@{i}` is about whatever universe is bound to `i` where the notation is used (possibly error if no such universe is bound and strict declaration is on).

Related to #5727.

**Comment by herbelin** [comment]
Yes, clearly something to do here. Maybe not completely trivial but probably not to complicated either, by imitating what is done for other kinds of parsing/printing annotation (such as `x bigint`).

The "Variable i does not occur in the right-hand side" warning helps to see that `i` is actually unbound but adding an error when seeing the `@{i}` might also help until #5727 is done.
