### ISSUE TITLE
coqc -quick infinite loops on abstract within a transparent proof

### ISSUE THREAD

**Issue by tchajed** [coq/coq#6165]
#### Version

commit a2b02cb9142984b

#### Operating system

macOS

#### Description of the problem

The following works fine with `coqc` but doesn't work with `coqc -quick`, from what looks like an infinite loop in the STM (which you can produce by removing the timeout):

```coq
Goal True.
  abstract exact I.
Timeout 1 Defined.
```

**Comment by tchajed** [comment]
Finished a git bisect: 848bc5b5fc366a is the first bad commit

**Comment by tchajed** [comment]
@ejgallego I self-assigned this because I intended to work on it, but I'd appreciate if you could review the fix.

**Comment by ejgallego** [comment]
Sure, thanks @tchajed ; I am surprised by the result of the bisect [I have one going own so I'll confirm].

This part of the system is particularly tricky and we've been talking about some redesign for a while, good luck!
