### ISSUE TITLE
Add LoadPath ".". ==> Infinite Loop in CoqIDE

### ISSUE THREAD

**Issue by kevinsullivan** [coq/coq#6174]
CoqIDE 8.6.1

OSX

IDE goes into infinite loop: "Coq is computing"

**Comment by Zimmi48** [comment]
What folder are you in? Is it your home folder or some other folder that contains lots of repositories. Can you try the same thing in a nearly empty repository?

**Comment by kevinsullivan** [comment]
I'm in a folder that contains my entire project, just a few small .v files.

**Comment by herbelin** [comment]
Then, could you give more context on how to reproduce what you observe?

**Comment by Zimmi48** [comment]
From your comment on the other issue, I understand that you usually open CoqIDE from the menu. Was it the case here as well? In that case, the "current" folder might not be what you think and the fact that you first opened a file in a specific folder does not change this.

**Comment by ppedrot** [comment]
FTR, we discussed at some point about deprecating the `Add LoadPath` command. It should only be used as a workaround in coqtop in extrem cases, and never in any user interface. Maybe it's time to properly deprecate it.

**Comment by Zimmi48** [comment]
BTW on this specific issue, we didn't get any answer from @kevinsullivan but I'm pretty sure that the issue comes from a misunderstanding of what "." represents when CoqIDE is opened from the menu. Therefore, I'm closing this bug report as invalid.
