### ISSUE TITLE
inconsistent loading of functional induction plugin?

### ISSUE THREAD

**Issue by lennartberinger** [coq/coq#6176]
#### Version
8.7.0 compiled with Ocaml 4.05.0

#### Operating system
Ubuntu 17.10

#### Description of the problem

It appears that the need for, and loading of this plugin is somewhat nondeterministic:
I have two copies of a development (CompCert), in different directories, obtained by manually copying all files from one directory to the other. The development contains a file (lib/Intv.v) that contains
a use of functional induction, but not a "Require Import FunInd" yet (since CompCert hasn't been ported to 8.7)
In directory A, the file processes fine, under Coqide (8.7) and coqc (compcert's make).
In directory B, interactive processing and compilation fail at the functional induction command, and succeed only after the "Require Import FunInd". line is added  

Any idea what may cause the discrepancy between the 2 settings? I used separate coqide invocations for the 2 directories, so it's not that the plugin had already been loaded for directory A. Indeed, processing B's file in the same coqide window after A's copy has been processed also leads to the failure. I suspect most people will port their development lazily, i.e. repeat "recompile and fix what's broken." but it seems this approach will not lead to a robust code base, if the error is only occasionally flagged.

**Comment by ejgallego** [comment]
Note that compcert has been ported to 8.7. So you may need to look to your setup with more care, somehow in one of them funind is being loaded.

**Comment by lennartberinger** [comment]
Argh. it seems some subsidiary file that contains the needed
Import statement wasn't merged correctly. (compcert's master on github indeed has been ported)

**Comment by ejgallego** [comment]
Yeah that transition was a bit rough for everyone, sorry about it.
