### ISSUE TITLE
File "checker/checker.ml", line 1:  Error: Corrupted compiled interface

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6177]
Here is a build error that we observe from time to time on Travis:

```
OCAMLOPT  checker/print.ml
OCAMLC    checker/checker.ml
File "checker/checker.ml", line 1:
Error: Corrupted compiled interface
checker/print.cmi
make[1]: *** [checker/checker.cmo] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/travis/build/Zimmi48/coq'
make: *** [submake] Error 2
```

Here is an example: https://travis-ci.org/Zimmi48/coq/jobs/303541408

It was my understanding that this error could happen when building byte and native targets in parallel but I don't think that this is the case here... Or is there an unwanted dependency on byte in the checker?

Note that this build error is always happening in the checker.

**Comment by ejgallego** [comment]
I see this often.

**Comment by SkySkimmer** [comment]
I think I figured it out, see #6265.
