### ISSUE TITLE
Design Bug ? wrt Library names, Makefiles, compilation, CoqIDE Imports.

### ISSUE THREAD

**Issue by kevinsullivan** [coq/coq#6179]
#### Description of the problem

1. Foo.v contains one line, Require Import Bar.
2. Bar.v contains one line, Definition x := 1.
3. In a directory containing these two files, I type "coq_makefile *.v > makefile" then "make".
4. The code compiles, producing this output
COQDEP foo.v
COQDEP bar.v
COQC bar.v
COQC foo.v
5. I start CoqIDE. 
6. I open foo.v.
7. I try to run the Require Import Line. I get this error:
Error: The file /Users/sullivan/.../bar.vo contains library Top.bar and not library bar
8. I change "Require Import bar" to "Require Import Top.bar". Then I get this error:
Error: Cannot find a physical path bound to logical path matching suffix Top.

I'm guessing this behavior is "as specified." But it's really confusing. I'd call it a design bug. I looked at the documentation and it's not obvious how to get CoqIDE to handle the namespace issues here.
I don't want to add hardwired load paths, as this project is shared via GitHub and so won't always live at one absolute path. (And per a related Issue that I've posted, adding "." as a LoadPath sends the IDE into an infinite loop.)

I'm stuck.

**Comment by herbelin** [comment]
I'm not an expert in `coq_makefile`, but it seems that `coq_makefile` basically forces the user to set a `-R` or `-Q` option, otherwise it automatically sets `-R . Top`, which forces in turn to call `coqide` with the same option. So, two solutions on your side, either pass `-Q . SomeName` (or `-R . SomeName`) to `coq_makefile` and the same option to `coqide`, or pass `-R . Top` to `coqide`.

I'm adding @silene to the discussion in case he has better to propose.

**Comment by Zimmi48** [comment]
:+1:

This is a question that comes often. I guess the documentation should be improved to include what you just said. Or this could go in the FAQ (but first I think the FAQ should be moved to the wiki - on this topic I will open a separate issue).

**Comment by kevinsullivan** [comment]
Thanks all.  Yes, "pass -R . Top to coqide" works. I generally keep CoqIDE pinned in my toolbar. I guess my workflow will just have to change to invoking it from the command line. And YES: updating documentation would be great. Marking as resolved.

**Comment by eponier** [comment]
@kevinsullivan  Just a small precision. If you put the `-R` option in a file named `_CoqProject` in the same directory as your file, it is detected and parsed by CoqIDE automatically and you can still invoke it graphically.

**Comment by kevinsullivan** [comment]
Thank you. Suggest to document along with the rest when updating docs.
--Kevin

**Comment by ejgallego** [comment]
#14067 could be maybe extended to handle this.
