### ISSUE TITLE
`get_goal_context`, `give_me_the_proof` and friends should be deprecated and/or removed.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6182]
All these functions are used to extract the "global" proof state, and IMHO it is crucial we at least deprecate them for 8.8 so they can be removed at a later stage.

The existence of a "global" proof state is one of the biggest headaches if we want to keep hacking on parallel proof support.

This is not an easy task and will require quite a bit of work, however it is doable:
- [x] Printing uses `get_current_context` in many places (see #6173) , however it is doable to do so.
- [x] `Optimize Proof` should not depend on the global state, however, turning it into a tactic seems to be less powerful than it should. #6197 #6199 redefine `VERNAC COMMAND EXTEND` to have a functional variant.
- [x] Vernac interpretation should thread the `Proof.proof`, this is doable now and in progress, however a lot of places to thread.
- [x] A particular tricky point is tactics depending on the name of the proofs, `get_current_proof_name`, I have no idea what is the proper fix here.
- [x] Some plugins and part of the code like to `discard` the current proof. That should be threaded in.

**Comment by ppedrot** [comment]
@ejgallego It's not possible to turn `Optimize Proof` into a tactic because of the semantics of evar-refinement. Actually, I think that even as a command it is unsound but it's uncommon enough not to be an issue in practice.

**Comment by ejgallego** [comment]
@ppedrot so what should be done then? I am keeping it as a command, but using a new `VERNAC EXTEND FUNCTIONAL COMMAND` that will explicitly pass and return state, a start is in #6183

**Comment by ppedrot** [comment]
@ejgallego Looks like the right way. That said, I'd rather add a flag to obtain the deprecated macro, like e.g. `VERNAC EXTEND IMPERATIVE COMMAND` rather than the other way around. Indeed we're going to remove the non-functional one at some point (hopefully).

**Comment by ejgallego** [comment]
> rather than the other way around.

Yeah but that would break compatibility with all the current plugins, right? I'm afraid we are bound to issue a deprecation first if possible, so I guess the current form will have to stand for "imperative".

**Comment by ejgallego** [comment]
Indeed we can do without breaking backwards compatibility, but users of the imperative interface will pay [a small] performance cost.

**Comment by ppedrot** [comment]
It's quite easy to port all macros, a sed would be enough, wouldn't it?

**Comment by ejgallego** [comment]
It is not about hardness but about out of tree plugins.

**Comment by ejgallego** [comment]
Ok so #6197 #6199 remove one of the most serious roadblockers. Now we can even proceed in parallel adding a `Proof.proof` parameter to command that use it.

**Comment by ejgallego** [comment]
cc: #7196

**Comment by ejgallego** [comment]
Will be fixed by https://github.com/coq/coq/pull/9129
