### ISSUE TITLE
[ci] Adapt to CoLoR moving to git.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6194]
As of today `CoLoR`'s CI is a bit of an odd animal as it is still hosted in a svn repository and we have to patch it manually.

However, CoLoR upstream has expressed their intention to move to git [and likely Github], so this issue is created to track the changes to the CI, as well as to be sure CoLoR upstream implements a branching strategy that we can use.

**Comment by fblanqui** [comment]
Hi. CoLoR is now on Github on https://github.com/fblanqui/color . Best regards, Frédéric.
