### ISSUE TITLE
Wrong extraction when Extract Inductive is applied on a non-infix function with two arguments.

### ISSUE THREAD

**Issue by Mbodin** [coq/coq#6212]
#### Version

Coq has been installed through opam. Here is the result of “coqtop -v”:
The Coq Proof Assistant, version 8.6 (November 2017)
compiled on Nov 21 2017 11:46:23 with OCaml 4.04.0

#### Operating system

I am running Linux. Here is the result of “uname -a”:
Linux tupungato 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Description of the problem

Consider the following minimal example. It uses the Flocq library (the opam package coq-flocq must be installed) and extracts a simple term.
``` coq
Require Flocq.Appli.Fappli_IEEE Flocq.Appli.Fappli_IEEE_bits.

Definition test := Fappli_IEEE.F754_nan false 1.

Extract Inductive Fappli_IEEE.full_float => "float" [
    "(fun s -> if s then (-0.) else (0.))"
    "(fun s -> if s then neg_infinity else infinity)"
    "(fun (b, p) -> nan)"
    "(fun (s, m, e) -> failwith ""FIXME: No extraction from binary float allowed yet."")"
  ].

Extraction "test.ml" test.
```
Here is the resulting OCaml:
``` ocaml
type bool =
| True
| False

type positive =
| XI of positive
| XO of positive
| XH

type z =
| Z0
| Zpos of positive
| Zneg of positive

(** val test : float **)

let test =
  Falsefun (b, p) -> nanXH
```
This last line is extremely surprising. It seems to have replaced the opening parenthesis by the first argument and the closing parenthesis by the second.
For comparison, if we replace the "(fun (b, p) -> nan)" by  "fun (b, p) -> nan", it produces the following definition (which obviously doesn’t compile):
``` ocaml
let test =
  fun (b, p) -> nan (False, XH)
```
I have no idea why this is happening, but this behaviour seems quite unusual :-\ Is it due to the “nan” special identifier?

Best,
Martin Bodin.

**Comment by Mbodin** [comment]
I found a workaround, but there is definitively something wrong somewhere (which is why I am not closing the issue) :-\

The following file works as expected:
``` coq
Require Flocq.Appli.Fappli_IEEE Flocq.Appli.Fappli_IEEE_bits.

Definition test := Fappli_IEEE.F754_nan false 1.

Extract Inductive Fappli_IEEE.full_float => "float" [
    "(fun s -> if s then (-0.) else (0.))"
    "(fun s -> if s then neg_infinity else infinity)"
    "let f = fun (b, p) -> nan in f"
    "(fun (s, m, e) -> failwith ""FIXME: No extraction from binary float allowed yet."")"
  ].

Extraction "test.ml" test.
```
And results in the following file:
``` ocaml
type bool =
| True
| False

type positive =
| XI of positive
| XO of positive
| XH

type z =
| Z0
| Zpos of positive
| Zneg of positive

(** val test : float **)

let test =
  let f = fun (b, p) -> nan in f (False, XH)
```
Best,
Martin Bodin.

**Comment by herbelin** [comment]
A reduced example:
```coq
Require Import Extraction.
Inductive I := C : bool -> bool -> I.
Definition test := C true false.
Extract Inductive I => "foo" [ "(fun (b, p) -> bar)" ].
Extraction "test.ml" test.
```
The bug concerns all code surrounded by parentheses for a two-argument constructor: such code is wrongly recognized as an operator to be printed infix, so, as you found yourselves, removing the parentheses resolved the problem.

**Comment by psteckler** [comment]
@herbelin you are going to fix this one?

**Comment by psteckler** [comment]
Is a solution to consider `(fun ... )` as not-infix?

**Comment by SkySkimmer** [comment]
Infix operators in ocaml must start with one of `+*-/=><&|$@^%` or be the `::` (possibly I missed some, I took this from andromeda which we based on ocaml). So teach extraction to recognize that in addition to parentheses.

**Comment by psteckler** [comment]
The relevant code is at https://github.com/coq/coq/blob/b75beb248873db7d9ab8e4a078022b2ed0edcd36/plugins/extraction/ocaml.ml#L103

**Comment by herbelin** [comment]
@psteckler:
> @herbelin you are going to fix this one?

No. Please go ahead (I suspect that @letouzey will not refuse some help).

**Comment by psteckler** [comment]
I should have a PR soon.

**Comment by psteckler** [comment]
Created #6220.
