### ISSUE TITLE
Coercion fails w/out an indication 

### ISSUE THREAD

**Issue by eluuk** [coq/coq#6215]
#### Version
8.7.0

#### Operating system
Linux

#### Description of the problem

```coq
Inductive T := a | b | c.
Let t := fun x => match x with c => False | _ => True end.
Definition ni := @sig T t.
Parameter r:> ni -> T.
Check exist t a I: ni.
Print Graph. (*[r] : ni >-> T*)
Check r (exist t a I): T.
Check exist t a I: T.
(*Error: The term "@exist T t a I" has type "@sig T t"
 while it is expected to have type "T".*)
```

AFAIU a coercion should either work or give some indication (a warning, not displayed w/ Print Graph, etc.) if it does not. So why does it fail?

**Comment by ppedrot** [comment]
This fails because `exist t a I` has not type `ni` but `@sig T t`. The latter is convertible to the former, but not syntactically equal, thus the coercion is not found. I'm afraid this is an invalid bug report...

**Comment by Zimmi48** [comment]
Closing then. Feel free to reopen if someone has something to add.
