### ISSUE TITLE
How to get a summary of why CI fails?

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6229]
This is to continue a discussion started at [PR#876](https://github.com/coq/coq/pull/876#issuecomment-346630279).

When seeing a red cross signalling a failure of Travis or Appveyor in the [list of PRs](https://github.com/coq/coq/pulls), it is tedious to know what the cause of the error, and frustrating when this error happens to often be an error not related to the PR itself, such as timeout, opam failure, missing shell script, network failure, ...

Travis and gitlab send mails for tests made on personal branches (with the gitlab mails incidentally more detailed as shown by @SkySkimmer).

Can these mails e.g. be used to report the status on the main PR page? Or at least to report a more precise status in the "check" subwindow at the bottom of individual PR pages?

**Comment by mattam82** [comment]
The gitlab mail seems like it has everything we need.

**Comment by Zimmi48** [comment]
Incidentally, this is linked to https://github.com/travis-ci/travis-ci/issues/8171, https://github.com/travis-ci/travis-ci/issues/8136 and https://github.com/travis-ci/travis-ci/issues/5035.

**Comment by mattam82** [comment]
https://github.com/wizeline/travieso seems to do the detailed reporting

**Comment by Zimmi48** [comment]
I like very much the detailed reporting by CircleCI. If we decide after testing it for some time that it is a good fit for us, this means that we can close the issue without installing any external service like Travieso.

**Comment by ejgallego** [comment]
Thanks the work of many people this issue is now solved.
