### ISSUE TITLE
Plugin-defined vernacs should check for locality support.

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#6239]
This issue is a reminder that we should make sure that commands not expecting the `Local`/`Global` prefixes do fail when it is provided.

Ideally, this should be part of the work on attributes. But since https://github.com/coq/coq/pull/6197 removed the checks in place for commands defined by plugins, we may need to put back some ad-hoc checks if attributes don't make it to 8.8.

**Comment by ejgallego** [comment]
Unless you work at the parsing level [by not adding the corresponding `Local` rules] I'm afraid that the goal of this PR is not possible to realize reliably, in the sense that the old check `hey_i_am_using_locality ()` does guarantee nothing other than yes, somebody added that bit of useless code, but still, the implementation of the vernac can ignore the value of the flag thus giving a sense of false "security".

So I'm all for refining parsing rules, but against adding such useless checks again.

**Comment by maximedenes** [comment]
I think you are mixing two things a bit here. The old checks were certainly not done properly (in fact, the user could see it was still executing the command, only to backtrack after it!). So there's no way we are going to put such crazy checks back in place.

However, we still have the freedom to do the checks at interpretation time (but before running the command, not after :D) if the parsing rules are a bit too imprecise. With a generic syntax for extensible attributes, we will probably have to do that way, in fact.

**Comment by ejgallego** [comment]
We will see, I don't understand what you mean by "checks at interpretation time" but I am in general skeptical of such "use" checks.

> With a generic syntax for extensible attributes, we will probably have to do that way, in fact.

Uh "generic", "extensible", I hope I am not in a Blockchain seminar.

**Comment by ejgallego** [comment]
That is to say, I'd rather take "correct", "efficient", and "simple" over "generic" and "extensible".

**Comment by ejgallego** [comment]
Good find !

**Comment by maximedenes** [comment]
@ejgallego Do you think you can fix this?

**Comment by gares** [comment]
It seems `FUNCTIONAL VERNAC COMMAND EXTEND` cannot yet fully replace `VERNAC COMMAND EXTEND` so the issue is still open.

**Comment by ejgallego** [comment]
I am not sure what you want me to do here, what is the concrete bug?

Checking that a function "uses" an argument is well, futile.

**Comment by ejgallego** [comment]
Due to the complexity this requires to be implemented properly, this seems like 8.10 material to me.

**Comment by SkySkimmer** [comment]
#8515 + passing plugins to .mlg will close this.

**Comment by ejgallego** [comment]
You agree to defer this @maximedenes ?

**Comment by maximedenes** [comment]
> You agree to defer this @maximedenes ?

Yes!

**Comment by maximedenes** [comment]
I think this is fixed with the new attribute system.
