### ISSUE TITLE
Would there be a way to have an overview of where an intervention from us is needed?

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6245]
For several reasons, it would be convenient to have an easy overview of what we need to do so that others (and often us on the rebound) are not blocked.

- on `needs: rebase` or `needs: fixing` label, there is often but not always a message, or we miss it, and sometimes we discover it only by chance. This delays PRs, we do the rebase, new PRs are merged while travis is working again, new rebases are necessary, this is suboptimal. I would need a dashboard which I can consult say once a day which tells me what is pending on me.
- I receive a lot of mails; if I don't treat them in the day, there is a high probability that something I was asked to do gets forgotten. With such a dashboard, I could have a summary of what I'm expected to do even after a few days elapsed
- more generally, in a model where synchronization and communication matters, as in the model we are trying to set up, it is as important to provide good working conditions to the others as to oneself.

What could be done?

The top [Pull requests](https://github.com/pulls) menu tells where we are assignees, and where we are expected to do a review. This could be a first step.

Would it make sense to use the assignee field more often, as a general field to communicate that "something", whatever it is, is expected from the assignee?

It is already possible to have several assignees per PR. So, would it possible, using lthe language of labels, to give a non ambiguous meanings to such "assignations"?

For instance, an assignation to the author of the PR would mean look at the `needs: rebase` or `needs: overlay`, or `needs: fixing` label to know what it means.

For an assignation to a PR which is not ours, the meaning could be found in the comments or in a label `needs:feedback`, or `needs: discussion`, or `needs: review`, etc.

Could that work or would it be a too tricky use of the assignee field?

In any case, whatever the way it is implemented, the question is: how to have an easy way to know what we have to do so that the work of others is not blocked by us, and on the rebound, that our own work is not blocked either?

**Comment by SkySkimmer** [comment]
>For instance, an assignation to the author of the PR would mean look at the needs: rebase or needs: overlay, or needs: fixing label to know what it means.

I like this. Note that for `needs: fixing` the assignment is not always to the author(s) of the PR, eg when I got a fix from @mattam82 for #1033.

For review there's already a specific request review field.

For feedback/discussion it's not always targeted enough to assign specific people, but sometimes it may be.
