### ISSUE TITLE
Makefile not insensitive to environment

### ISSUE THREAD

**Issue by mattam82** [coq/coq#6255]
#### Operating system

Platform Independent

#### Description of the problem

I'm seeing compilation problems with `make` that indicate that we're not using the information about ocaml/ocamlfind/etc.. that are set at `./configure` time of Coq and instead rely on non-canonical paths for these tools. Typical workflow to reproduce: 

``./configure && make && opam switch blah && eval `opam config env` && touch kernel/univ.ml && make``

**Comment by psteckler** [comment]
Shouldn't you re-run `configure` after doing an `opam switch`?

**Comment by Zimmi48** [comment]
That's what I always do after updating my environment.

**Comment by ejgallego** [comment]
This can also be solved by #6857 as it provides a workspace that understands OPAM switches.
