### ISSUE TITLE
Regression in testing Locality flag

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6260]
This is a reminder, suggested in #6197, that something has to be done to alert when a locality modifier is not effective, as e.g. in:
```coq
Require Import FunInd.
Local Function f (n : nat) := n.
```
I put `blocker` as suggested in #6197. Maybe this is a bit exaggerated, strictly speaking, but I guess it is to signal that we have not to forget.

**Comment by Zimmi48** [comment]
Duplicate of #6239

**Comment by herbelin** [comment]
Oups, sorry for noise.
