### ISSUE TITLE
On the use of whitespace "linting"

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6268]
There are still open PRs about linting (#6211, #6225) and a diversity of opinions have been expressed (the position of @ejgallego moved and is now "I'm personally happy with [a strict linter] now that I've added to my git config a [strict check](http://www.rpcurnow.force9.co.uk/git/tdl.git/hooks/pre-commit) wrt whitespace.", @gares: "the linter is nitpicking on futile style issue", @maximedenes: "what is the technical problem with leaving trailing whitespaces?", @zimmi48: "I wish we had something as https://blog.golang.org/go-fmt-your-code for OCaml", @skyskimmer: "I've been growing more friendly with the idea of 1 big commit", ...).

In particular:

- do we need such spacing linting? should it be mandatory?
- if yes, which kind of checks do we want? only no tab in indentations or also trailing spaces?
- do we enforce a layout rule stepwise or once for all and preserving the rule?
- do we recommend using a pre-commit?

Are we ready for taking a decision? For instance, if we do one big commit, recommend using a pre-commit hook (so that it is transparent for those who don't really care), with no tab in indentations as well as no trailing spaces, the lint test as a necessary green light for merging, and the suggestion to use `-w` option to `git blame`, would there be oppositions?

(Edited for refinement)

**Comment by SkySkimmer** [comment]
No tab in indentation makes automatic indent work better. I don't care about trailing space personally, it's in the linter because it's enabled by default by git and I didn't decide to remove it.

**Comment by Zimmi48** [comment]
BTW I've just found out that there already exists a formatter for OCaml code (it's just one month old): https://github.com/ocaml-ppx/ocamlformat
ATM it does not support objects nor camlp5 but if we found this tool satisfactory we could very well decide to use it only on the files which it supports (which would still be the majority).

**Comment by SkySkimmer** [comment]
That's interesting but first we would need to enable warning 50.

**Comment by ejgallego** [comment]
My opinion: things are fine as now, no large commits.

**Comment by JasonGross** [comment]
My personal opinion: Coq should supply a pre-commit git hook script that runs the linter locally, and put instructions for setting it up somewhere; I'm ambivalent to a big commit (have inclinations in both directions), and in favor of both tab and trailing whitespace checking.

**Comment by mattam82** [comment]
My opinion and @herbelin 's apparently: we do not care which strict or lax policy we have, large commit or not, but a decision seems in order. I think in the end we'll all end up with the linter pre-hook anyway so I'm in favor of making it strict (as is it now, agree @ejgallego ?). People seem really ambivalent about the large commit so I'd refrain for now and maybe do it later if we see fit.

**Comment by herbelin** [comment]
So, @mattam82's proposal as a compromise?

**Comment by maximedenes** [comment]
> I'm in favor of making it strict

Fine, then I'm going to apply a strict policy for PR merging, as I already started to do, and will close #6211.

**Comment by maximedenes** [comment]
Unless people want to say more, I'm going to close this issue soon.

**Comment by ejgallego** [comment]
> So, @mattam82's proposal as a compromise?

Sounds good, even if would personally allow the RM to merge commits only failing on the linter, the load of a rebase is not worth it IMHO.

**Comment by maximedenes** [comment]
> Sounds good, even if would personally allow the RM to merge commits only failing on the linter, the load of a rebase is not worth it IMHO.

I'm also fine with that, but if that is the policy, then the linter should be moved to allowed failures. I don't want to spend my time inspecting failures that we end up ignoring.

**Comment by ejgallego** [comment]
Things are never binary, and policies should never be "strict, specially in RM.

We have agreed on a strict policy, and the check should remain in main. However I would expect a sensible merger to be able to optimize the process and avoid pointless loads in the testing system, as it often done today.

**Comment by maximedenes** [comment]
Apart from the number of dependencies of a PR, what could indicate whether it make sense to fix whitespace, or not? In any case, it will trigger another build, right?

**Comment by ejgallego** [comment]
Never mind, I am failing to explain to what I meant.

**Comment by maximedenes** [comment]
Honestly, I'm failing to fully grasp your point of view on this since the start where you requested exceptions, then regretted, then requested other exceptions. If you want to explain more, feel free to do it.

Here is my point of view: indeed, many RM policies have to be flexible. And that's why they are time consuming. But it turns out that, at least with the current state of the code, I would like to spend my time on other things than managing whitespace problems.

**Comment by herbelin** [comment]
I'm fine with the current state, and I suspect that others, even @ejgallego, are also enough ok with the decision, but I'd like to make a suggestion for the next times, namely that for such kind of decision, a deadline is given, so that everyone can clearly feel that he had the opportunity to say what s/he had still to say.

Somehow, I'm guilty here in not having myself proposed a deadline to the discussion, but I will try to think for the next time at rather saying things like "So, @mattam82's proposal as a compromise? If noone has anything more to add by Thursday 1pm GMT, it seems reasonable to me to consider that this is adopted."

**Comment by mattam82** [comment]
Indeed, a deadline seems only fair.

**Comment by Zimmi48** [comment]
Looks like we can close now that the linter is handling this for us.
