### ISSUE TITLE
setoid_rewrite hangs

### ISSUE THREAD

**Issue by vzaliva** [coq/coq#6272]
#### Version
```
The Coq Proof Assistant, version 8.7.0 (November 2017)
compiled on Nov 2 2017 11:32:40 with OCaml 4.05.0
```
#### Operating system

Linux

#### Description of the problem

I have a problem when `setoid_rewrite` just hangs forever without going into typeclass resolution or producing an error. By that I mean adding `Typeclasses eauto := debug.` does not start to produce any output. I waited for 48 hours on fast machine.

What I am doing here is rewriting under bindings, and I expect Coq to to a rewrite and create a sub-goal in a form `forall j (j<2), op_Vforall_P ...` I was able to do something similar on simpler examples.

I was able to simulate this behavior with some LTAC automation and then applying the original rewriting lemma `rewrite_Reduction_ScatHUnion_max_zero`.

The problem is a part of a big project and I did my best to isolate it by removing as much irrelevant code as possible. I left all typeclass instances in case they are relevant here.

In the attached file the problem is located at the very end, after "BEGIN: problem" comment. It is followed by a commented statements which simulate actions of failed 'setoid_rewrite'.

[bug1.v.txt](https://github.com/coq/coq/files/1511009/bug1.v.txt)

**Comment by ejgallego** [comment]
Did that happen in v8.6? Note that you can pass `-debug` to Coq and then press Ctrl-C to get a backtracke  in most of the cases.

Unfortunately the recipe for reproducing your bug is quite large so I am not able to do this myself.

**Comment by vzaliva** [comment]
I have encountered this problem in the new code I wrote after I switched to 8.7. So I do not know if this is the case for 8.6.

Let me know if there is anything else I can provide to help to diagnose this. I've spent two days minimizing this example :) I am very interested in seeing this fixed as I may need to do more rewrites like this in the future...

**Comment by vzaliva** [comment]
I forgot to mention that the example depends on 3 libraries, available in OPAM:

`opam install coq-color coq-ext-lib coq-math-classes `

**Comment by vzaliva** [comment]
I did `coqc -debug bug1.v &> debug.txt`. Please see attached the output.
[debug.txt](https://github.com/coq/coq/files/1511091/debug.txt)

**Comment by ejgallego** [comment]
You are missing the Ctrl-C to see the backtrace.

**Comment by JasonGross** [comment]
Note that `setoid_rewrite` unfolds terms to find a location to rewrite.  Without looking at your code, I suspect Coq is stuck doing reduction on some large term.  What happens if you issue `Opaque ....` with a list of all the constants that show up in your goal which you don't want `setoid_rewrite` to unfold?

**Comment by vzaliva** [comment]
@JasonGross following your suggestion I tried to mark as opaque pretty much every term used in the goal. It does not seem to make a difference. The only exception, if I mark `SHCompose` as opaque. In this case rewrite immediately fails with the message:
```
Error:
Found no subterm matching "liftM_HOperator Monoid_RthetaFlags
                             (HReduction minmax.max 0)
                           ⊚ Scatter Monoid_RthetaFlags ?i 0 ⊚ 
                           ?s" in the current goal.
```

I am unsure how to interpret or use this result.

**Comment by vzaliva** [comment]
@ejgallego I pressed Ctrl-C when recording debug.txt posted above. For some reason, it is missing the stack trace. It might be due to the fact that I have opam-installed coq? Perhaps stack trace is generated only in debug versions built from source?

**Comment by JasonGross** [comment]
@vzaliva That means that `setoid_rewrite` is unfolding `SHCompose` and trying to find something to rewrite with there, and that without unfolding `SHCompose`, it can't find a place to rewrite.  Do you want `setoid_rewrite` to unfold `SHCompose`?  If so, what happens if you manually `unfold SHCompose` and then mark everything that now shows up in the goal as `Opaque`?  If not, then you want to try to debug why `setoid_rewrite` is not finding an occurrence that you think it should find.  (Either way, this supports my hypothesis that it is spending time in reduction.)

**Comment by vzaliva** [comment]
@JasonGross We are onto something with unfolding `SHCompose` here. Doing 'unfold SHCompose' expands the original goal which when printed takes 32 lines to 54750 lines(!) However it does this just in 1 minute or so. Trying to apply rewrite to unfolded result takes a long time. It supposed to fail, but I need to wait and see.

Based on these findings I see 3 venues to examine:

1. Why it generates such huge expression? It might be a normal expansion based on the way I defined things. In this case, it is my problem. On the other hand, it could be some Coq unfolding quirk in such case it might need to be fixed in Coq. [Action: I will take a look how this expression gets so big and will report here]

2. Even though the unfolded expression is huge, the rewrite should eventually fail. Is it reasonable for it not to terminate in 48 hours as original rewrite did? [Action: I will leave it running overnight and will report if it fails, as expected, in reasonable time after SHCompose has been unfolded]

3. As for me there is a practical question how to do these kinds of rewrites. I do not want to unfold SHCompose and I suspect setod_rewrite should work if it is marked as opaque. `SHCompose` is a special operator composition I defined. The goal is a big chain of compositions with some of them under a binder. The rewrite lemma I am trying to apply is also expressed in terms of SHCompose. At a first glance, it should work with if SHCompose declared opaque. Not sure why it does not.

**Comment by mattam82** [comment]
Try a Hint Opaque SHCompose : rewrite
Le mer. 29 nov. 2017 à 07:57, Vadim Zaliva <notifications@github.com> a
écrit :

**Comment by ejgallego** [comment]
@vzaliva it could also be that your Ctrl-C is catched by some exception handler that should not.

**Comment by vzaliva** [comment]
@mattam82 thanks! Quick update: I tried it. Usual 'rewrite' does not work with hint or without. It fails to find expression under binder and fails quickly with "nothing to rewrite". I use "setoid_rewrite" instead so I tried:

```
          Hint Opaque SHCompose: rewrite.
          setoid_rewrite rewrite_Reduction_ScatHUnion_max_zero with
              (fm := Monoid_RthetaFlags)
              (m := 4%nat)
              (n := 1%nat).
```

The result is pretty much the same as with just "Opaque SHCompose": it fails quickly with "Tactic failure: setoid rewrite failed: Nothing to rewrite."

**Comment by vzaliva** [comment]
Maybe my workaround in LTAC will give an idea where 'setoid_rewrite' fails?

```
          match goal with
          | [ |- context G [ mkSHOperatorFamily _ _ _ _ ?f ]] =>
            match f with
            | (fun j jc => UnSafeCast (?torewrite ⊚ ?rest )) =>
              setoid_replace
                (mkSHOperatorFamily _ _ _ _ f) with
                  (mkSHOperatorFamily _ _ _ _
                                      (fun (j:nat) (jc:j<2) => UnSafeCast rest))
            end
          end.
          all:revgoals.
          f_equiv.
          intros j jc.
          f_equiv.

          apply rewrite_Reduction_ScatHUnion_max_zero.

```

Basically I isolate the expression which I want to rewrite and do 'setoid_replace' on it and later apply my rewrite lemma to satisfly

**Comment by vzaliva** [comment]
I looked into this further. Now rewrite taking forever seems to caused by term unfolding producing 54 thousand lines goal. I suspect if I wait long enough it would eventually terminate. So this part is not a bug. However, there is a still underlying unsolved problem with this rewrite which now I can demonstrate with more clear example. I will open a separate issue for it to avoid confusion.
