### ISSUE TITLE
Commit 07f947d backported from #6190 on v8.7 changes the signature of Command.declare_assumption

### ISSUE THREAD

**Issue by gares** [coq/coq#6279]
### Version branch v8.7 (07f947d)

The way you declare an axiom changed in the v8.7 branch.
This mean I can't provide a single source code for coq-elpi in 8.7.0 and (what will be) 8.7.1.
This is the code using the API: https://github.com/LPCIC/coq-elpi/blob/master/src/coq_elpi_API.ml#L408
This is the travis job displaying the failure: https://travis-ci.org/LPCIC/coq-elpi/jobs/308882063

**Comment by gares** [comment]
I don't think I'm the only one "declaring axioms" from an ML plugin, given the recent messages on coq-dev...

**Comment by gares** [comment]
I think that until the day where we will have a well define API, any change touching .mli files should not be merged in the table branch, especially if there is no other way to achieve the same functionality (i.e. have code that works on all minor releases)

**Comment by Zimmi48** [comment]
Sorry about that. Indeed, that's a problem. I don't know what @SkySkimmer thinks, but if no solution can be found, we may just revert this merge.

However, I'm a bit surprised. I didn't find this `declare_assumptions` in `API.mli`. If this is the right way to declare an axiom from an ML plugin, it should be exported, right?

**Comment by SkySkimmer** [comment]
There's no API.mli in 8.7 ^^
PR incoming.

**Comment by Zimmi48** [comment]
> any change touching .mli files should not be merged in the stable branch

Looks like a reasonable criterion. It could still touch a `.mli` file but only to add optional arguments...

**Comment by Zimmi48** [comment]
Using `git log -p V8.7.0..v8.7 *.mli` to check how much this criterion was respected in the past, I can see just one other breaking change in the `.mli` files in commit 321dbbabc22ae2bfcc461754c1ad5183cdc2658c. Is this one fine? (@ppedrot?)

**Comment by SkySkimmer** [comment]
`cs_pattern_of_constr` sounds like a pretty internal kind of thing.

**Comment by ppedrot** [comment]
Assuming people respect the API, that should be fine...

**Comment by Zimmi48** [comment]
This assumption is too strong XD, otherwise this issue wouldn't be open.

**Comment by gares** [comment]
Well, first he API is not there in 8.7, second the API.mli in master was generated when the code I linked did not even exist, so I'm not surprised it is not there.  Finally, my point is that I'm happy to call another function, if any, that works on all 8.7.x serie...

I have not yet ported elpi to master, and then I'll propose additions to the API if needed.
