### ISSUE TITLE
File .csdp.cache is modified by executing the micromega test files under MacOS X

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6286]
The calls to `psatz` are modifying the micromega test-suite cache under MacOS X.

I could debug up to this point:

The call to [`Marshal.from_channel`](https://github.com/coq/coq/blob/e80e40120e9e65362d5dfae12e0200ecf1beaea6/plugins/micromega/persistent_cache.ml#L92) eventually raises a `Failure("input_value: truncated object")` which leads to [rebuild](https://github.com/coq/coq/blob/e80e40120e9e65362d5dfae12e0200ecf1beaea6/plugins/micromega/persistent_cache.ml#L170-L173) the cache.

The cache worked well to answer the requests of the test suite. I don't know why something goes wrong at the end of the reading.

Then, if the file is reconstructed differently, this seems because the items of the hash table are not pushed in the same order. Maybe this is normal. There are probably no reasons for `iter` in `Hashtbl`to iter in the same order as the items were pushed in the hash-table.

So, the primary cause seems to be the (unexpected?) `Failure("input_value: truncated object")`.

Any expert in marshalling / micromega? Pinging at least @fajb.

Added: I could reproduce the behavior on a short example: on MacOS X, `Marshal.from_channel` seems to return `Failure("input_value: truncated object")` on end of file rather than `End_of_file`.

**Comment by herbelin** [comment]
Well, this is OCaml [bug 7142](https://caml.inria.fr/mantis/view.php?id=7142), introduced somewhere around 4.03.0 and fixed by @mlasson's  OCaml's [PR#639](https://github.com/ocaml/ocaml/pull/639) in (iiuc) OCaml 4.04.0.

So, this does not seem MacOS X specific but 4.03.X specific.

Concretely, since some of us are apparently using 4.03, maybe could we patch `plugins/micromega/persistent_cache.ml` in the meantime (or live with the bug and `git co test-suite/.csdp.cache` systematically? Any opinion?

**Comment by Zimmi48** [comment]
If this bug only affects developers using OCaml 4.03.0, maybe another solution is just not to use this version of OCaml. When we decide to move away from OCaml 4.02, we may just as well jump directly to OCaml 4.04. What is your reason for using this particular version of OCaml?

**Comment by herbelin** [comment]
No, particular reasons. But it is probably not bad that a diversity of versions are used by developers, so that we have more real life testing of the versions announced to be supported. (On the other side, I shall probably switch to 4.06 to have the debugging of packed files fixed.)

**Comment by mattam82** [comment]
What's the patch like ?

**Comment by herbelin** [comment]
A robust one, we'll have to think... A quick one is to treat `Failure("input_value: truncated object")` the same as `End_of_file` in `Persistent_cache.read_key_elem`, but I don't know how robust it is wrt asynchronous writes to the cache.

Actually, maybe the rebuild of the cache made on `Failure("input_value: truncated object")` is idempotent and just committing the rebuild of the cache would work!

**Comment by herbelin** [comment]
> Actually, maybe the rebuild of the cache is idempotent

Seems no, since the file has already been re-committed 4 times and it still giving different results. One would need more debugging... rebuilding a hashtable from the list obtained by folding on the hashtable does not seem idempotent. Interesting algorithmic puzzle...

**Comment by ppedrot** [comment]
There is probably an interaction with the fact that hash tables can contain elements several times. In the relevant code, keys are all present twice. Could somebody on MacOS try with `Hasthbl.replace` instead of `Hashtbl.add`?

**Comment by herbelin** [comment]
Indeed, this fixes the problem. Well done!

See PR #6322 for the implementation of the fix.
