### ISSUE TITLE
Provide a flag to compile *only* CoqIDE

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6296]
Currently, `opam install coqide` recompiles the entire standard library. That's just silly. There should be a `./configure -coqide only` flag, or similar.

**Comment by maximedenes** [comment]
Why do you need a `configure` flag? Isn't there a `Makefile` target for it already?

**Comment by RalfJung** [comment]
Oh, right, the opam package actually does
```
  [make "-j%{jobs}%" "coqide-files"]
  [make "-j%{jobs}%" "coqide-opt"]
```
But IIRC, I still saw the stdlib scroll by when I ran `opam install -vv coqide`. I will check again, maybe I mixed this up with some other output.

**Comment by maximedenes** [comment]
Wasn't that just `coqdep`?

**Comment by ppedrot** [comment]
On my machine at least it doesn't compile the stdlib.

**Comment by RalfJung** [comment]
You are right, it just runs `coqdep`. Sorry for the noise.
