### ISSUE TITLE
Anomaly: Incorrect universe Set ...

### ISSUE THREAD

**Issue by ramsdell** [coq/coq#6297]
#### Version

$ coqc -v
The Coq Proof Assistant, version 8.6.1 (October 2017)
compiled on Oct 30 2017 14:48:59 with OCaml 4.04.0

#### Operating system

MacOS Sierra 10.12.6

#### Description of the problem

Compiling this source file:
```coq

Record LTS: Set :=
    lts { St:   Set; (* Set of states *)
          init: St; (* Initial state *)
          step: St -> nat -> St -> bool }.

```
Produces this message:
```

Anomaly:
Incorrect universe Set declared for inductive type, inferred level is max(
Prop, Set+1). Please report at http://coq.inria.fr/bugs/.
```

**Comment by mattam82** [comment]
Indeed. It should be an error instead of an anomaly. But it is an error, you cannot have a Set inside a Set

**Comment by herbelin** [comment]
@mattam82, or @SkySkimmer: do you plan to do a fix (or shall I do one quickly while my mind is focussed on it)?

**Comment by SkySkimmer** [comment]
It seems I forgot to make the PR for 8acf323...

**Comment by SkySkimmer** [comment]
No wait it is there #6298.

**Comment by herbelin** [comment]
Ah, is this #6298? My mistake, I did not have seen it yet.
