### ISSUE TITLE
`make install` installs coqide manpage with `-coqide no`

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6307]
#### Version

8.7.dev

#### Operating system

Linux

#### Description of the problem

* `./configure -prefix ... -coqide no`
* `make`
* `make install`

This installs the coqide manpage. Should that really happen? This means that the coq opam package installs the coqide man page, which does not make much sense.
Ideally, the coqide manpage should just be installed by `make  "install-ide-bin"  "install-ide-files"  "install-ide-info"  "install-ide-devfiles"` (command taken from the coqide opam package).

**Comment by Zimmi48** [comment]
Sorry for not having addressed this yet.
Feel free to propose a fix if you see how to make it though.

**Comment by RalfJung** [comment]
I don't have any good ideas, sorry.

**Comment by maximedenes** [comment]
No assignee, so removing the milestone.

**Comment by ejgallego** [comment]
> No assignee, so removing the milestone.

That is a bit strange, the fact a bug didn't get (yet) an assignee doesn't mean that it shouldn't be solved before a particular milestone. In particular this one seems that should be marked 8.8.

**Comment by maximedenes** [comment]
> That is a bit strange, the fact a bug didn't get (yet) an assignee doesn't mean that it shouldn't be solved before a particular milestone. In particular this one seems that should be marked 8.8.

The milestone should reflect the schedule of the assignee. If we don't have an assignee, how is it going to be solved anyway? We can mark it as high priority, though, maybe that's what you mean.

**Comment by maximedenes** [comment]
In this particular case, I can have a look at it, though, and schedule it.

**Comment by ejgallego** [comment]
This is one possible interpretation but not by any means the only one. Often, RM needs to understand which bugs should be fixed for the next release, in order to _assign_ the work itself.

**Comment by maximedenes** [comment]
@ejgallego does the Dune build solves this? Under which condition does it install man pages? Does it clearly separate Coq's man pages from CoqIDE's ?

**Comment by ejgallego** [comment]
> @ejgallego does the Dune build solves this?

I am not sure if it solves it today, but it should.

> Under which condition does it install man pages?

Manpages are installed in package `foo` when the install stanza `(install ...)` is present.

> Does it clearly separate Coq's man pages from CoqIDE's ?

Yup, they should go in different packages. See: #8802

**Comment by ejgallego** [comment]
Note that as of today Dune has a small bug in the install of manpages sections which should be solved in the next update. [They usually release every 2 weeks]

**Comment by maximedenes** [comment]
Sure, that's fine. Can you let me know when this issue gets fixed on the Dune build? It should be enough to close it. Thanks!

**Comment by ejgallego** [comment]
Bug added to Dune tracking issue #8052
