### ISSUE TITLE
`Evd.define` is either of the wrong type or shouldn't be used by the current users.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6310]
So far `Evd.define` is called by `pretyping` quite a few times, however in all cases the incoming argument is of `EConstr.t` type, whereas the function expects a `Constr.t` type.

This is IMHO a critical bug [could be a design bug or just a use bug], as in all cases the conversion is morally wrong as `Constr.t` terms are not allowed to contain existential variables anymore. See also #6308

**Comment by maximedenes** [comment]
WG discussion: we'll try to fix it but not a blocker.

**Comment by ejgallego** [comment]
Note that #7136 fixes this.

**Comment by ejgallego** [comment]
Cool to see this fixed, thanks!
