### ISSUE TITLE
Bugzilla Migration script mistranslated bugzilla comment links

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6314]
#### Description of the problem

In, e.g., #5448, there are many comment links in the original of the form [`https://coq.inria.fr/bugs/show_bug.cgi?id=5448#c48`](https://coq.inria.fr/bugs/show_bug.cgi?id=5448#c48) (displayed as "[comment #48](https://coq.inria.fr/bugs/show_bug.cgi?id=5448#c48)" in bugzilla) which got translated as `comment [BZ#48](https://github.com/coq/coq/issues?q=is%3Aissue%20%22Original%20bug%20ID%3A%20BZ%2348%22)` which is incorrect.

**Comment by ejgallego** [comment]
A quick emacs macro fixes those.

**Comment by JasonGross** [comment]
Uh, I'm viewing GitHub in Chrome (or sometimes on my android phone), not in emacs, presently.

**Comment by ejgallego** [comment]
I edit github comments in emacs using the "Edit with Emacs" extension.

**Comment by Zimmi48** [comment]
Yeah, sorry about that. I thought I had included some protections against this in the script but apparently that didn't work. Whenever I see this, I fix it by hand but if people want to do a massive fix, feel free to look into it. It would require, browsing through the entire comment base through GitHub API, and replacing this type of strings automatically. However ideally, one would want the link to be to the corresponding comment on GitHub (we don't want to introduce links to Bugzilla that might be dead in a few months from now). This would require some more API calls to get the identifier of the corresponding comment.

**Comment by SkySkimmer** [comment]
Too hard to fix
