### ISSUE TITLE
Printers for ocamldebug not loading

### ISSUE THREAD

**Issue by psteckler** [coq/coq#6325]
#### Version 

master

#### Operating system

Linux x64

#### Description of the problem

In emacs, run `camldebug` on coqtop.byte using `dev/ocamldebug-coq` script. In the debugger, run `source db`. There's an error about the `Profile` module. I ran a `git clean -dfx` before the build, so there should have been no filecruft to cause an error.

For comparison, a clean build of Coq 8.7 allows all the printers to load successfully.

**Comment by psteckler** [comment]
I think I built master with OCaml 4.06, which may be relevant.

**Comment by SkySkimmer** [comment]
Would it help with this sort of conflict with OCaml module names if we compiled with mlpack files? Maybe just clib/lib if the rest has issues?

**Comment by ejgallego** [comment]
#6038 renames `Profile` to `CProfile` so that should help.

**Comment by psteckler** [comment]
FWIW, building today's `master` with 4.05 allows the printers to load successfully.

**Comment by psteckler** [comment]
When I reported this bug, I was running `4.06.0+fp` from OPAM. I tried again with plain `4.06.0` from OPAM and, yes, the bug is there. So there's something different between `4.05.0` and `4.06.0`.

**Comment by psteckler** [comment]
Works with 4.06 and today's `master`. So closing.
