### ISSUE TITLE
auto does not use hypotheses created by the assert tactic in external hints.

### ISSUE THREAD

**Issue by cstolze** [coq/coq#6332]
#### Version
The Coq Proof Assistant, version 8.7.0 (November 2017)

#### Operating system
Fedora

#### Description of the problem
In this example, `auto 10` calls `tac` which create a hypothesis `HH`, which should be used by `auto`, but it doesn't work.
```
Section test.
  Variable (A : Type) (a b : A) (P : A -> Prop).
  Hypothesis H : forall b : A, P b -> P a.
  Hypothesis H' : P b.

  Ltac tac := assert (HH: P b -> P a) by (apply (H b)); clear H; idtac "OK".
  Hint Extern 1 => tac.

  Goal P a.
    auto 10. (* Prints "OK", but does not solve the goal *)
    tac. (* works properly *)
    auto 2. (* works properly *)
  Qed.
End test.
```

**Comment by Zimmi48** [comment]
Interestingly this is one more example of discrepancy between `auto` on the one hand, and `eauto` and `typeclasses eauto with core` on the other hand (which both work in this example).
