### ISSUE TITLE
Add Search Blacklist on module names

### ISSUE THREAD

**Issue by gares** [coq/coq#6333]
`Add Search Blacklist "foo"` lets one prune lemmas that have "foo" somewhere in their name.
It seems it does not work with module names, E.g. if I place my dirty lemmas in a module called `Private`
then `Search` returns `Private.lemma` even if I blacklist `"Private"`.

It would be nice for the blacklist to use the full name of a lemma, not just its label.

**Comment by SkySkimmer** [comment]
Cannot reproduce
~~~coq
Add Search Blacklist "bla".

Module bla.
  Definition x := I.
End bla.

Module bar.
  Definition x := I.
End bar.

Search True.
(* bar.x: True
I: True
True_sind: forall P : SProp, P -> True -> P
True_rec: forall P : Set, P -> True -> P
True_ind: forall P : Prop, P -> True -> P
True_rect: forall P : Type, P -> True -> P
*)
~~~

**Comment by gares** [comment]
Was it fixed? We should git blame^W praise and close this issue then...
