### ISSUE TITLE
coq_makefile no longer supports `-Q . ""` even though coqc does

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6350]
#### Version

8.7.0

#### Operating system

Linux

#### Description of the problem

I discovered this today when I had [coq-tools](https://github.com/JasonGross/coq-tools)'s travis start testing 8.7.0.  The issue is that `Makefile.conf` contains
```
COQMF_COQLIBS =  -Q .
COQMF_COQLIBS_NOML = -Q .
```
and so, e.g., with `A.v`, `coqc` gets invoked as `coqc -Q . A.v` rather than as `coqc -Q . "" A.v` as it should.

**Comment by gares** [comment]
Hum, I guess the regression is there.
Still I don't get your use case. In particular now that we impose the use of `From`, packages should always have a root.

The fix is to contemplate empty strings in here
  https://github.com/coq/coq/blob/master/tools/coq_makefile.ml#L117

**Comment by SkySkimmer** [comment]
> Still I don't get your use case. In particular now that we impose the use of From, packages should always have a root.

We don't actually impose that.

**Comment by Zimmi48** [comment]
Indeed, we don't. What made you think that we did @gares?

**Comment by JasonGross** [comment]
> Still I don't get your use case.

I don't have one in particular.  It just so happened that one of the coq-tools' test-suite files used `-Q . ""`.  I've changed it to not do that, under the assumption that this won't be fixed soon.  If it does get fixed, I can revert https://github.com/JasonGross/coq-tools/commit/7124c3a4e7c40af0484bffa1cdb955ecda04be4b when 8.7.1 is released.

**Comment by gares** [comment]
Hum, I'm pretty sure coq_makefile gives you warning if your project has no root.
Note that the `From X Require Y` business was added to disambiguate `Y` but it only works if
user-contribs is populated of subdirectories (`X` in the example above). So I expect all project to either `-R theories/ X` or `-Q theories/ X`... in both cases things are installed in `coq-contribs/X`... if `X` is null, then they end up in the root of `coq-contribs` and that is not a good idea.

Hence I asked for the usecase, and indeed there is no usecase...

**Comment by gares** [comment]
The bug is there, IMHO an error should be given.

**Comment by Zimmi48** [comment]
IIUC this bug is minor because there is no use case. So it's fine if this one misses 8.7.2 but it would still be good to fix.

**Comment by nomeata** [comment]
This has just come up in a project of mine. We have some generated files in, say `generated/` and some manual files in, say, `theories/`, but we want the contents of both directories to be part of the top-level Coq module name space. So we used to have
```
-Q ../generated ""
```
in the `_CoqProject` file of `theories`.

How should we do this under the new regime?

**Comment by nomeata** [comment]
Ha,
```
-Q ../generated ''
```
works. But that is some serious code-smell there :-)

**Comment by nomeata** [comment]
Hmpf, but that does not work with `coqide` :-(

**Comment by Zimmi48** [comment]
@gares Given the recent comments, do you think something can be done to help alleviate this bug? (It would have to be a quick fix, today, to make it into 8.7.2.)

**Comment by nomeata** [comment]
A only mildly educated guess would be that changing this line 
https://github.com/coq/coq/blob/master/tools/coq_makefile.ml#L127
from
```
let quote s = if String.contains s ' ' then "'" ^ s ^ "'" else s
```
to (pseudo-code, I am not fluent in OCaml)
```
let quote s = if String.contains s ' ' || String.null s then "'" ^ s ^ "'" else s
```
might fix it.

**Comment by nomeata** [comment]
(I’ll try to create a PR)
