### ISSUE TITLE
Install target generates many warnings when `-native-compiler=no`.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6354]
#### Version
Coq 8.8+alpha [7b40908bfbc255d51384e88a73fa5d98380b237f]

#### Operating system
Linux / Ubuntu + OPAM / OCaml 4.06.0

#### Description of the problem

When doing `./configure -prefix=u -native-compiler=no && make && make install` , `master` will generate lots of warnings of the form:
```
install: cannot stat 'plugins/fourier/.coq-native/NCoq_fourier_Fourier_util.o': No such file or directory
```
I couldn't observe this in `v8.7`.

**Comment by advorkin** [comment]
Hello,

We are having the same problem.    

Getting 910 cannot stat messages. Ex.
install: cannot stat 'theories/Reals/.coq-native/NCoq_Reals_DiscrR.o': No such file or directory

Using options -bytecode-compiler no -native-compiler yes

Thank you!

**Comment by advorkin** [comment]
I'm having the same problem with 8.7.1 and -native-compiler yes.  8.7.0 worked...  I would appreciate your advice.  Thank you.

**Comment by SkySkimmer** [comment]
Should be fixed by https://github.com/coq/coq/pull/7593
