### ISSUE TITLE
[ci] make ci-$foo should set NJOBS if not provided by the user.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6357]
Currently, the CI scripts use a global variable `NJOBS` that is set usually by travis.

However, when calling `make ci-foo` , the variable won't be defined causing some calls to happen with `-j`, with the consequent problem for the user.

We should do something about this, either setting a default in the makefile, or making a more robust system for parallel build specification.

This is known to have bitten many people including @aspiwack

**Comment by JasonGross** [comment]
If we can, let's have the submakes inherit parallelism from the initial make target (I think prefixing rules that call shell scripts with `+` does this?), and then we can remove the pattern of passing `-j${NJOBS}` anywhere but in `.travis.yml`.

**Comment by ejgallego** [comment]
The problem is this is not only about `make` also `opam` and maybe some other tools want to use `NJOBS`.

**Comment by ejgallego** [comment]
For example coquelicot uses its own make system, not integrated with make, etc... A bit of a pain...

**Comment by ejgallego** [comment]
This was fixed by #6641 right?

**Comment by SkySkimmer** [comment]
Yes.
