### ISSUE TITLE
Private universes for opaque constants

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#6367]
Consider the following script:
```coq
Set Universe Polymorphism.
Set Printing Universes.

Inductive nat := O | S (n : nat).

Record prod (A B : Type) := { fst : A; snd : B }.

Lemma nat_prod_rect@{i j+} (A:nat -> Type@{i}) (B:nat->Type@{j} )
      (ab0 : prod (A O) (B O))
      (sab : forall n, prod (A n) (B n) -> prod (A (S n)) (B (S n)))
  : forall n, prod (A n) (B n).
Proof.
  induction n.
  - exact ab0.
  - apply sab;exact IHn.
Qed.

Print nat_prod_rect.

(* nat_prod_rect@{i j Top.20} =
fun (A : nat -> Type@{i}) (B : nat -> Type@{j}) (ab0 : prod@{i j} (A O) (B O))
  (sab : forall n : nat, prod@{i j} (A n) (B n) -> prod@{i j} (A (S n)) (B (S n)))
  (n : nat) =>
nat_rect@{Top.20} (fun n0 : nat => prod@{i j} (A n0) (B n0)) ab0
  (fun (n0 : nat) (IHn : prod@{i j} (A n0) (B n0)) => sab n0 IHn) n
     : forall (A : nat -> Type@{i}) (B : nat -> Type@{j}),
       prod@{i j} (A O) (B O) ->
       (forall n : nat, prod@{i j} (A n) (B n) -> prod@{i j} (A (S n)) (B (S n))) ->
       forall n : nat, prod@{i j} (A n) (B n)
(* i j Top.20 |= i <= Top.20
                 j <= Top.20
                  *)

prod_rect is universe polymorphic
Argument scopes are [function_scope function_scope _ function_scope _]
*)
```

`Top.20` appears only in the body of the opaque constant `nat_prod_rect`. Since the constraints involving it are always satisfiable it is only relevant when typechecking the inside of the constant. As such we would like to avoid having to produce it when using the constant.
In other words we should have `nat_prod_rect@{i j} : ... = ... (* i j |=  with private Top.20 |= i, j <= Top.20 ` which when used is instantiated with only the universes `i` and `j` appearing in its type.

In general the universes appearing only in the body could be involved in constraints like `i < Top.20 < j`, in that case the constraints visible from outside should be the ones obtained by transitivity (`i < j`) essentially like c93d5094b did to remove universes which didn't appear at all.

This kind of situation appears in the wild and can lead to blowup in the amount of universes. For instance in HoTTClasses I manually instantiated them with a monomorphic universe `Ularge` (and `Uhuge` when more was needed).

If I understood correctly what @ejgallego told me on gitter this may help with removing the remotecounter and using ordinary state stuff to generate universe names.

**Comment by ejgallego** [comment]
> If I understood correctly what @ejgallego told me on gitter this may help with removing the remotecounter and using ordinary state stuff to generate universe names.

I am not sure but certainly this shouldn't hurt. I think the remote counter is there as to ensure that generated universes are in sync, in particular when replaying a `Definition`, but I don't fully grasp all the details thou.

**Comment by SkySkimmer** [comment]
Done in #8850, I forgot I made an issue for this.
