### ISSUE TITLE
makefile rule gallinahtml fails

### ISSUE THREAD

**Issue by Bromind** [coq/coq#6387]
#### Version

8.7.0 (probably previous too)

#### Operating system

Linux (probably all)

#### Description of the problem

The following:
```
$ coq_makefile -o makefile *.v
$ make gallineahtml
```
fails with:
```
coqdoc: g: no such file
make: *** [makefile:403: html] Error 1
```

**Comment by Zimmi48** [comment]
Fix merged, thanks!
