### ISSUE TITLE
"-natdynlink no" not enough for plugin debugging

### ISSUE THREAD

**Issue by psteckler** [coq/coq#6390]
#### Version
8.8+alpha, 0275b58

#### Operating system

`Linux felafel 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

#### Description of the problem

Building Coq with `configure -natdynlink no` gets you statically-linked plugins, but it's not enough to debug them effectively.

Using `camldebug` from within Emacs, `info modules` shows, for example, `Ltac_plugin.Tacarg`, but no other modules from the Ltac plugin are visible. If I set a breakpoint on a line within `Tacarg`, in fact, the debugger breaks elsewhere within Ltac.

@ppedrot and @ejgallego have mentioned their own ways to statically link plugins (both in the Coq distribution and others), maybe those allow effective debugging.

**Comment by ejgallego** [comment]
You can try with #6038

**Comment by psteckler** [comment]
> You can try with #6038

Not building for me, when applied to today's `master`

**Comment by psteckler** [comment]
Applying #6038 doesn't seem to change the visibility of modules within statically-linked plugins (enabled by the `-natdynlink no` flag to `configure). As before, for each plugin, there is one module that appears visible (via `info modules`). But setting a breakpoint in the Ltac plugin module, for example, gives funny results:
```
(ocd) break @ Ltac_plugin.Tacarg 5
Breakpoint 1 at 6558864: file plugins/ltac/tactic_option.ml, line 12, characters 37-53
```
That is, the actual breakpoint is not in the specified file.

**Comment by ejgallego** [comment]
With #6038 you need to build the toplevel in a special way, try as we mentioned:
```shell
ocamlbuild opt -linkall -linkpkg -rectypes -thread -package coq.ltac toplevel/coqtop_bin.ml -o coqtop
```
to get a new toplevel.

**Comment by SkySkimmer** [comment]
s/ocamlbuild/ocamlfind/ ?

**Comment by ejgallego** [comment]
Yup, recipe fixed. As I said, it needs some fine tuning.

**Comment by psteckler** [comment]
I get `Package `coq.ltac' not found`. Is there something special to build the package?

**Comment by psteckler** [comment]
With the command above, I get a message about a missing `coq.intf`. Is there something special to build these as packages?

**Comment by ejgallego** [comment]
Ah, indeed, you need to export `OCAMLPATH=path_of_your_coq_build`.

**Comment by ejgallego** [comment]
I tend to have custom `findlib.conf` files so I forget about this stuff.

**Comment by psteckler** [comment]
Because you need a byte version for `ocamldebug`, I was able to run the above command, subbing `ocamlc` for `opt`, producing a `coqtop.byte`. I had to run `make byte` first.

Configuring with `-natdynlink no`, that `coqtop.byte` fails with `Fatal error: cannot load shared library dllcoqrun`. 

Omitting that flag (that is, using the `-natdynlink yes` default), the `coqtop.byte` runs fine -- but the visibility of plugin modules is limited as before from within `ocamldebug`.

Maybe things work well with the native-code `coqtop` in gdb -- but that's not so useful, at least until `libmonda` is working better (it hasn't been updated since last year).

**Comment by ejgallego** [comment]
> Configuring with -natdynlink no, that coqtop.byte fails with Fatal error: cannot load shared library dllcoqrun.

Ha, that's a problem of the META file, you can set the path manually. However, that shouldn't matter, if you passed to the "dynlink" version the `coq.ltac` flag, the plugin should be statically linked, so indeed it is visible, at least in that coqtop I can do stuff with the `Ltac` prefix.

**Comment by psteckler** [comment]
Yes, in `gdb` I can see Ltac stuff with dynlink+static-ltac `coqtop`.

**Comment by ejgallego** [comment]
So is that an improvement over the previous situation? Please keep me posted as I am not familiar at all.

Something interesting to look at too is backtraces. Coq is using its own method, I am not so sure it is superior to OCaml's anymore.

**Comment by psteckler** [comment]
With the byte version of dynlink+static-ltac, the Ltac stuff is not visible in `ocamldebug`. Opening that `coqtop.byte` in Emacs, I can see the linked Ltac modules (Ltac_plugin.Tacinterp, etc.). Something is missing to make those modules visible.

**Comment by psteckler** [comment]
> So is that an improvement over the previous situation?

For `gdb`, yes. Sometimes using `gdb` is useful. For `ocamldebug`, there's no change. 

I thought that maybe there's a missing `-g` somewhere, but haven't been able to find it.

**Comment by herbelin** [comment]
What do you mean by "the Ltac stuff is not visible in ocamldebug" and "opening that coqtop.byte in Emacs, I can see the linked Ltac modules"? I mean, what do you do to observe this?

**Comment by psteckler** [comment]
> What do you mean by "the Ltac stuff is not visible in ocamldebug"
```
(ocd) info modules
Used modules:
... Ltac_plugin.Tacarg ...
```
but nothing else. And:
```
break @ Ltac_plugin.Tacinterp 43
Can't find any event there.
```
(same if I don't qualify `Tacinterp`).

> "opening that coqtop.byte in Emacs, I can see the linked Ltac modules"?

Opening the byte-code file `coqtop.byte` in Emacs, I see things like:
```
320@\260@5Ltac_plugin.TacinterpA^A2\315@ABC\260@4Ltac_plugin.TacsubstA^A0L\320\320\320@\260@8Ltac_plugin.Tactic_debugA^A1
```
so there are symbolic references to those modules contained in the binary.

**Comment by herbelin** [comment]
Which version of OCaml are you using? Registration of packed modules is bugged in OCaml prior to 4.06.0 (only the first module of the pack is registered, and breakpoints should be given relatively to this first module: If the pack contains `A`, `B`, and `C` in this order and you want to add a breakpoint in `C`, you need to declare the breakpoint for `A` and adding the whole size of modules `A` and `B` to the offset in `C`, as if the files were concatenated into a single big file with name the name of the first file).

**Comment by psteckler** [comment]
@herbelin Thanks! Using offsets is kind of painful, but compiling with 4.06 and `-natdynlink no`, I can see all the modules in `Ltac_plugin`.

The method of @ejgallego  is still useful if I've compiled with dynamic plugins, and want to create another top-level with a static plugin.
