### ISSUE TITLE
Record error messages should be improved.

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#6394]
```
Record foo (T : Type) :=
  { ops1 : T -> T -> T;
    ops2 : T -> T -> T }.

Definition x :=
  {| ops1 := Nat.add |}.
```

Coq replies:
```
Cannot infer this placeholder of type "nat -> nat -> nat".
```

Of course, I want the name of the missing fields.

**Comment by ppedrot** [comment]
Looks like we're heading towards another extension of the `evar_kind` type...

**Comment by maximedenes** [comment]
> Looks like we're heading towards another extension of the evar_kind type...

C'est grave, docteur?

**Comment by ppedrot** [comment]
It wouldn't be if we only used this type for printing purposes. Unluckily, there are parts of the code that rely on it for control, like typeclasses and the infamous `pattern_of_constr` IIRC.

**Comment by maximedenes** [comment]
Another example:

```
Structure foo := Bar.
```
coq says:

The Record keyword is for types defined using the syntax { ... }.

...

**Comment by bollu** [comment]
@ppedrot, Can I have some help regarding getting started on this bug?
