### ISSUE TITLE
CoqIDE's "Fully check the document" not working properly

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#6399]
```
Goal False.
exact I.
Qed.
```

I click "go to end", CoqIDE complains. Then I click "fully check the document" and Coq says: `All proof terms checked by the kernel`...

**Comment by ppedrot** [comment]
Hum, you still have the error highlighted in red... Obviously the phrasing of the error is wrong, but what would you say? *Everything highlighted in green has been checked* or something?

**Comment by maximedenes** [comment]
IIRC If you change the line, the red disappears and then you really have no indication that it was not actually rechecked.

**Comment by ejgallego** [comment]
That's an UI issue I guess.

**Comment by maximedenes** [comment]
@Zimmi48 What does the disapproval mean? Do you want me to update the title of this issue? That would be fine with me.

**Comment by Zimmi48** [comment]
That's not a disapproval. A disapproval would have been 👎 That's a confused emoji 😕, as in I don't really get what is your problem. But I'll just remove my reactions, and leave this issue alone.

**Comment by maximedenes** [comment]
Ah thanks, I'm a beginner with those emoji. No problem in any case. This is just a UI issue indeed (I think), but a pretty serious one IMHO.

**Comment by ejgallego** [comment]
That may well stem from a problem in the protocol, `finish` doesn't take any parameter so it is very hard to know what has exactly deep-checked. Fixing it is on the plan. IMHO this is a valid issue but a minor one.

**Comment by psteckler** [comment]
PG/xml does this:
```
(when (and (= error-count 0)
                   (= incomplete-count 0)
                   (> coq-last-incomplete-count 0)
                   ;; bad approximation to "user hasn't done anything since Check'ing"                                                                                                                                                
                   (= coq-last-processed-count processed-count))
             (message "All proof terms checked by the kernel"))
```
Meaning, there are no errors, at least one `Qed` was marked incomplete, now all `Qed`s are complete, and (roughly) the user hasn't hit `Check` twice in a row.

**Comment by Alizter** [comment]
Seems to be fixed.
