### ISSUE TITLE
Recursive definition ill-formed: issues with split, combine, fst, snd.

### ISSUE THREAD

**Issue by alexiturcotte** [coq/coq#6408]
#### Description of the problem

I'm running into a recursive definition ill-formed error when dealing with lists of pairs. The code snippet I've included below shows off the error (myFuncNotCorrect). Here, it's possible to write the function in a different way to get it to work (myFuncCorrect), but some of my current work is a little more complicated, and I don't see an easy way to express my function alternatively. 

```
Require Export List.

Import ListNotations.

(* Both functions here should take a list of pairs (say, (x, y)) of nats, 
   and produce a list of pairs with 1 added to the first element of 
   each pair (so, (x+1, y)).
*)

(* This function works, no errors. *)
Fixpoint myFuncCorrect (l : list (nat * nat)) : list (nat * nat) :=
  match l with
  | [] => []
  | aThing :: restAList => (S (fst aThing), (snd aThing)) :: myFuncCorrect restAList
  end
.

(* This function doesn't compile, I've included the error message below. *)
Fixpoint myFuncNotCorrect (l : list (nat * nat)) : list (nat * nat) :=
  match l with
  | [] => []
  | aThing :: restAList => (S (fst aThing), (snd aThing)) ::
                           myFuncNotCorrect (combine (fst (split restAList))
                                                     (snd (split restAList)))
  end
.

(* Error message:

Error:
Recursive definition of myFuncNotCorrect is ill-formed.
In environment
myNotAlsoCorrect : list (nat * nat) -> list (nat * nat)
l : list (nat * nat)
aThing : nat * nat
restAList : list (nat * nat)
Recursive call to myFuncNotCorrect has principal argument equal to
"combine (fst (split restAList)) (snd (split restAList))" instead of
"restAList".
Recursive definition is:
"fun l : list (nat * nat) =>
 match l with
 | [] => []
 | aThing :: restAList =>
     (S (fst aThing), snd aThing)
     :: myFuncAlsoCorrect
          (combine (fst (split restAList)) (snd (split restAList)))
 end".

*)
```
The most annoying thing about this error is the following line: Recursive call to myFuncNotCorrect has principal argument equal to "combine (fst (split restAList)) (snd (split restAList))" instead of "restAList". If L is a list of pairs, then (combine (fst (split L)) (snd (split L))) is the same as L. It seems like Coq should be able to pick up that the argument is decreasing.

Was this issue addressed in a version of Coq > 8.6.1? If so, sorry about wasting your time! 

If you need any additional information, let me know. Thank you for your time.

**Comment by SkySkimmer** [comment]
>If L is a list of pairs, then (combine (fst (split L)) (snd (split L))) is the same as L.

Only provably, ie `Fail Check fun L => eq_refl : L = (combine (fst (split L)) (snd (split L))).`.

Your function is simply not recursing on syntactically smaller elements. You can use `Program Fixpoint` with a measure for this sort of thing, see https://coq.inria.fr/distrib/current/refman/program.html#hevea_command290

**Comment by alexiturcotte** [comment]
Right, gotcha. I looked into Program Fixpoint, and it does the trick. Thanks!
