### ISSUE TITLE
Recursive definition ill-formed: error with recursion over lists of pairs (using split, combine, fst)

### ISSUE THREAD

**Issue by emarteca** [coq/coq#6409]
#### Description of the problem

Given the following simple example:

``` 
Require Export List.
Import ListNotations.

Inductive x : Type :=
| x_nat : nat -> x
| x_combo : list (x*nat) -> x.

Inductive garbReturn : Type :=
| gNat : nat -> garbReturn
| gList : list garbReturn -> garbReturn.
```

The following fixpoint fails (error given after the function) :
```
Fixpoint simplListRec (x1 : x) {struct x1}: garbReturn :=
  match x1 with
  | x_nat n => gNat n
  | x_combo L => gList (List.map( simplListRec) (fst (split L)))
  end.

(* Error:
Recursive definition of simplListRec is ill-formed.
In environment
simplListRec : x -> garbReturn
x1 : x
L : list (x * nat)
map : list x -> list garbReturn
l : list x
a : x
t : list x
Recursive call to simplListRec has principal argument equal to "a" instead of
"L".
Recursive definition is:
"fun x1 : x =>
 match x1 with
 | x_nat n => gNat n
 | x_combo L => gList (map simplListRec (fst (split L)))
 end".*)
```
This function can be written equivalently as (which also fails, with a similar error):
```
Fixpoint simplListRec (x1 : x) {struct x1}: garbReturn :=
  match x1 with
  | x_nat n => gNat n
  | x_combo L => gList (helperFun L)
  end
with helperFun (k : list (x*nat)): list garbReturn :=
  match k with
  | [] => []
  | (x, n) :: kRest => (simplListRec x) :: (helperFun kRest)
  end.

(*Error:
Recursive definition of helperFun is ill-formed.
In environment
simplListRec : x -> garbReturn
helperFun : list (x * nat) -> list garbReturn
k : list (x * nat)
p : x * nat
kRest : list (x * nat)
x : x
n : nat
Recursive call to simplListRec has principal argument equal to "x" instead of
"kRest".
Recursive definition is:
"fun k : list (x * nat) =>
 match k with
 | [] => []
 | (x0, _) :: kRest => simplListRec x0 :: helperFun kRest
 end".*)
```

This should work, as it is recursing over x. However, it seems that Coq doesn't realize that this argument is decreasing, perhaps because it is a list of pairs.

This is a simple example I came up with to demonstrate the issue, but actually I've run into it several times in a more complicated project. The first time I fixed it by representing the list of pairs as a pair of parallel lists, but this time I do not think this solution will work, and I actually need a list of pairs.

Thanks for your time!

**Comment by Zimmi48** [comment]
I only had a quick look but this issue looks quite close to #6408 which was posted just before by someone from the same city, likely the same class in the same University...

**Comment by emarteca** [comment]
Ah! Yes, thanks! I looked into it a bit more and I think the problem I was experiencing has something to do with this http://adam.chlipala.net/cpdt/html/GeneralRec.html

Thank you!

**Comment by Zimmi48** [comment]
I suppose you reopened accidentally, so closing again.
