### ISSUE TITLE
Canonical Structure errors produce messages about futures

### ISSUE THREAD

**Issue by psteckler** [coq/coq#6420]
#### Version

version 8.8+alpha (2c2a080)

#### Operating system

`Linux felafel 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

#### Description of the problem

If `Canonical Structure` fails, in addition to the expected error message, there can be messages about futures:
```
Record Foo := MkFoo { field1 : nat; field2 : nat -> nat }.
Canonical Structure a := MkFoo.
```
The current error message is "a is not a structure object" (but see #6418). Before the error message is printed, coqtop prints 
```
Future: no fix_exn.
You have probably created a Future.computation from a value without 
   passing the ~fix_exn argument.  
You probably want to chain with an already existing future instead.
```
These messages are printed to stderr. With vanilla PG, they're only visisble in the \*coq\* buffer; with CoqIDE, they're visible in the terminal, if CoqIDE is started from the terminal.

**Comment by Zimmi48** [comment]
@ejgallego Did you notice this issue report? (I'm tagging you but you may not be the only competent person.) This has been blocking #6418 for a while.

**Comment by ejgallego** [comment]
I think this is just an instance of #5479 , maybe @gares can think of quick workaround but otherwise the fix is far from trivial as IMHO it requires a whole redesign of the document scheduling code [which is more or less planned and agree upon]

**Comment by Alizter** [comment]
Doesn't seem to be an issue anymore. cc @ppedrot can you confirm since you cleaned up futures last IIRC?

**Comment by ejgallego** [comment]
Many cleanups went into futures since the date of the original report, we can close this.
