### ISSUE TITLE
CoqIDE's "replace all" should replace all

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#6426]
Today it silently ignores some occurrences when they are in areas of some colors (I haven't checked which ones).

**Comment by psteckler** [comment]
The `replace_all` code is in `wg_Find.ml`.  It's just a loop that starts at the beginning of the buffer, finds the next occurrence of the item to be replaced, deletes it, inserts the replacement. Nothing about colors that I see. It's using an OCaml `Str.search_forward` regexp search.

**Comment by maximedenes** [comment]
You can reproduce with the following script:
```
Lemma foo : False.
idtac.
exact I.
idtac.
Qed.
```

click on "go to end", then "replace all" `idtac` with `bar`. Only the first occurrence will be replaced.

**Comment by psteckler** [comment]
> You can reproduce with the following script:

Confirmed.

**Comment by psteckler** [comment]
The 2nd `idtac` is marked as not editable. You can't even edit it manually. 

The color represents the "processing" phase in the XML protocol.

A solution would be to mark everything editable, do the replace, restore the un-editability.

**Comment by maximedenes** [comment]
Ok, so this seems to be another protocol issue. I thought there was a way to edit all areas, and invalidate if necessary. But maybe not.

**Comment by psteckler** [comment]
The `delete_interactive` method indicates success or failure, there could be a message printed for the case where it fails.

**Comment by psteckler** [comment]
I wouldn't say it's a protocol issue, it's how CoqIDE is using the protocol. PG/xml allows the replacement of both occurrences in this example (via `replace-string`).

**Comment by psteckler** [comment]
> delete_interactive method indicates success or failure

In fact, it seems always to return `true`

**Comment by psteckler** [comment]
As noted in PR #6575, the non-editability of certain regions is due to the "processing" tag. I can remove those tags in Replace All, but not sure that's a good idea. There may be code that relies on the tags being there. The solution in that PR is to not do the replacement, but give an accurate count of how many were replaced. 

It would be possible to also give a count of how many occurrences were skipped.

**Comment by maximedenes** [comment]
Ok, the CoqIDE behavior seems unavoidable. The real issues is the existence of non-editable areas. #6575 is good enough for the specific UI problem reported here, so let's close.
