### ISSUE TITLE
Ltac2 should not need -bypass-API

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6442]
#### Version

Master

#### Description of the problem

Ltac2 requires -bypass-API.  This causes me a great deal of pain when I tried to compile my Ltac2 code to OCaml + TACTIC EXTEND.  Please add all the things used by Ltac2 (such as next_ident_away_from) to the API.

**Comment by Zimmi48** [comment]
This question is irrelevant now that the API is gone.
