### ISSUE TITLE
Future of Coq's internal `Backtrace` module

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6446]
I am using OCaml's native backtraces for some stuff and indeed they seem better than what Coq does provide via it's private `Backtrace` module. In particular, I see inlined functions. I also see the logic monad operations.

Should we update this module to use newer features? Should we just get rid of it?

**Comment by ppedrot** [comment]
This module was introduced to work around a missing API in OCaml. AFAIR we need to switch to a more recent version of OCaml to be able to remove it.

**Comment by maximedenes** [comment]
What version would it require?

**Comment by ppedrot** [comment]
I thought that it was OCaml 4.03, but actually I was wrong and it turns out from the documentation 4.02.0 is enough. So actually it's already possible to perform the move.

**Comment by ejgallego** [comment]
Note also the point about using OCaml's native `reraise`, but if I am not mistaken there were some problems. It also requires 4.03 I think.

```
external reraise : exn -> 'a = "%reraise"
```

**Comment by eponier** [comment]
There is a function `raise_with_backtrace` in `Printexc` that allows to raise an exception with a specific backtrace, but it requires 4.05.0 (see https://github.com/gasche/ocaml-releases-change-explanation/wiki/4.05.0-changes-explanation#debugging-and-profiling).

**Comment by ejgallego** [comment]
Ok, so we are ready for this; how should be proceed to migrate?

Is is enough to change:
```ocaml
with exn ->
    let reraise = CErrors.push exn in
    (* cleanup *)
    iraise reraise
```
to
```ocaml
with exn ->
   (* cleanup *)
   reraise exn
```

**Comment by gares** [comment]
I think so
