### ISSUE TITLE
CoqIDE should say whether it finds occurrences or not

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#6452]
Search doesn't say when it find no occurrences or wraps. It should also say the total number of occurrences, and the index of the current one.

Similarly, replace all should say how many occurrences were replaced.

**Comment by psteckler** [comment]
The existing search mechanism doesn't count occurrences. It could be added, by traversing the entire buffer, but that would slow things down.

It's easy enough to add messages about wrapping and when no occurrence is found.

**Comment by psteckler** [comment]
Created #6575.
