### ISSUE TITLE
Cannot compile on Alpine Linux

### ISSUE THREAD

**Issue by jpdeplaix** [coq/coq#6456]
#### Version

8.7.1

#### Operating system

Alpine Linux

#### Description of the problem

Build log: https://ci.ocaml.io/log/saved/docker-build-878d7161cbb7dc0cb7017e707691b00b/5c570611fc719b6d04a67af6ba50050e09f4ac50
On Alpine Linux the compilation fails with: ```Don’t know how to compute MD5 checksums…```
This is because ```md5sum --version``` is not a valid command on Alpine, and thus fails.

If you are using Docker, you can have access to a testing environment on Alpine by running:
```docker run -it ocaml/opam:alpine-3.6_ocaml-4.05.0_flambda```

**Comment by ejgallego** [comment]
IMO that's closer to a bug in Alpine than in Coq. Coq needs a working `md5sum` command and it seems Alpine one is broken.

Anyways, where is the man page of Alpine's md5sum so we can add a workaround?

**Comment by ejgallego** [comment]
Psss, so it seems that Alpine doesn't either ship a working `diff` command. IMHO we can't support such restricted environments, feel free to submit a patch to make Coq work thou.

**Comment by Zimmi48** [comment]
I don't understand the principle of adding a "won't fix" label without closing the issue, even less while submitting a PR.

**Comment by maximedenes** [comment]
@jpdeplaix Can you say more about your use case? I don't think we claimed to support Alpine Linux.

**Comment by Zimmi48** [comment]
It seems that the use case has something to do with OPAM CI, see https://github.com/coq/coq/pull/6458#issuecomment-352299296.

**Comment by ejgallego** [comment]
> I don't understand the principle of adding a "won't fix" label without closing the issue, even less while submitting a PR.

This means that I strongly disagree with having to support broken systems; however I'd rather have the OPAM CI working on Coq and not lose more time on this.

**Comment by Zimmi48** [comment]
I understand and share your disagreement, but that's not a "won't fix" then.

**Comment by ejgallego** [comment]
"Compile on Alpine Linux" is a won't fix, as even if we include the patch for configure we won't guarantee we can compile with non standard [as in de-facto standard] C libraries.

**Comment by xavierleroy** [comment]
Alpine Linux is popular with people who make virtual machines and Docker containers because it is much more lightweight than other Linux distributions.  But this comes at the cost of a C library and userland utilities that are less comfortable than the GNU stuff that comes standard in other Linux distributions.  OCaml should shield Coq from the C library issues (but see https://caml.inria.fr/mantis/view.php?id=7562 for an OCaml-on-Alpine issue, although on a rather exotic architecture).  Concerning userland utilities, I'm split between considering Alpine Linux hopeless or trying to support it with more elbow grease.

**Comment by jpdeplaix** [comment]
@maximedenes There is no ""use cases"" as I don't personally use Coq that much but rather something that I consider is worth taking care of. It seems to me that handling "standard" tools (i.e. busybox) is a good thing for portability in any case. This does not require a huge effort (for the current problem at least), just tiny bits and pieces here and there to avoid relying too much on GNU-based tools.

Otherwise, what @xavierleroy said.

**Comment by Zimmi48** [comment]
I'm backporting #6234 and #6466 and this should allow to close this in 8.7.2.

**Comment by Zimmi48** [comment]
Done (a while ago).
