### ISSUE TITLE
Use `Sys.backend_type` to check for Native/Byte modes.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6457]
In the current build system, we do a hack to initialize the `ML` toplevel if building `coqtop.byte`. However, OCaml >= 4.04.0 provides us with `Sys.backend_type` so we can remove the hack and match on that to see if we are in a bytecode build.

**Comment by ejgallego** [comment]
I have created the `needs: newer ocaml` so we can keep track of all the improvements that can be done once we raise the minimum supported OCaml version.

**Comment by ppedrot** [comment]
As discussed offline, this function is already available in the `Dynlink` module of OCaml. I think it's easy to use that one because AFAIU we always require dynamic link nowadays.

**Comment by psteckler** [comment]
> we always require dynamic link nowadays

Even if `-natdynlink no` is given to `configure`?

**Comment by psteckler** [comment]
Where is that build hack, BTW?

**Comment by ejgallego** [comment]
@psteckler the build hack is in `Makefile.build`

**Comment by psteckler** [comment]
The `Dynlink` function is `is_native`.

**Comment by maximedenes** [comment]
@ejgallego Can we close this?

**Comment by maximedenes** [comment]
Oh, I got it wrong, it's only the label that needs to be removed, probably.

**Comment by ejgallego** [comment]
The report is valid, but this is a bit more complicated than it looks due to linking, I am not sure how we will proceed here as the build system has to be involved too.We may need a newer OCaml or not, but I'd like to improve the current `Drop` handling a bit.

**Comment by ejgallego** [comment]
Maybe the proper way is to make `Drop` support a plugin that is only compiled for byte-only.

**Comment by ejgallego** [comment]
We have a few cases like this, and indeed using `Dynlink` introduces a spurious dependency so let's keep track of this for when we update OCaml.

**Comment by ejgallego** [comment]
Indeed I think we can close this, `compiler-libs` is not available in byte builds so even using the flag won't help.
