### ISSUE TITLE
Over-generalization in `match`

### ISSUE THREAD

**Issue by pedagand** [coq/coq#6464]
#### Version

The Coq Proof Assistant, version 8.7.0 (October 2017)
compiled on Oct 24 2017 8:28:22 with OCaml 4.05.0

#### Operating system

`Linux 4.13.0-1-amd64 #1 SMP Debian 4.13.4-2 (2017-10-15) x86_64 GNU/Linux`

#### Description of the problem

When doing incremental development with `refine`, functional arguments are sometimes over-generalized (replacing a constructor index with a meta-variable), which prevents dependent matches (such as the ones used in small inversion) from working.

For example, the following example fails:

```
Inductive foo : nat -> Type :=
| fz : foo 0
| fs : forall {n}, foo (S n).

Definition test (n : nat) : foo n -> nat.
Fail refine (
  match n with
  | 0 => 
    fun f => 
      match f in foo n return match n with 0 => nat | S _ => unit end with
      | fz => 0
      | fs => tt
      end
  | S n => 
    fun f =>
      match f in foo n return match n with 0 => unit | S _ => nat end with
      | fz => tt
      | fs => 42
      end
  end).
```

One way to fix it is to manually annotate the first `f`:

```
refine (
  match n with
  | 0 => 
    fun (f: foo 0) => 
      match f in foo n return match n with 0 => nat | S _ => unit end with
      | fz => 0
      | fs => tt
      end
  | S n => 
    fun f =>
      match f in foo n return match n with 0 => unit | S _ => nat end with
      | fz => tt
      | fs => 42
      end
  end).
``` 
Note that it is not necessary to annotate the second one (no idea why). 

In this _particular_ case, writing the full term directly (without annotation) works 

```
Definition test (n : nat) : foo n -> nat :=
  match n with
  | 0 => 
    fun f => 
      match f in foo n return match n with 0 => nat | S _ => unit end with
      | fz => 0
      | fs => tt
      end
  | S n => 
    fun f =>
      match f in foo n return match n with 0 => unit | S _ => nat end with
      | fz => tt
      | fs => 42
      end
  end.
```
but if we generalize the goal slightly, it breaks again:

```
Fail Definition test_bug (n : nat) : bool -> foo n -> nat :=
  match n with
  | 0 => 
    fun b f => 
      match f in foo n return match n with 0 => nat | S _ => unit end with
      | fz => 0
      | fs => tt
      end
  | S _ => 
    fun b f =>
      match f in foo n return match n with 0 => unit | S _ => nat end with
      | fz => tt
      | fs => 42
      end
  end.
```

Once again, this breaks _only_ on the `0`/`fz` case, not in the `S`/`fs` case. Explicitly annotating the `0` case as before fixes the problem.

**Comment by SkySkimmer** [comment]
Works since 8.10

**Comment by SkySkimmer** [comment]
Actually let's have a test suite entry for this.
