### ISSUE TITLE
Anomaly: Uncaught exception Not_found. in stdlib quote plugin when the interpretation function is not imported

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6467]
#### Version

8.7.0

#### Description of the problem

```coq
Require Import Coq.quote.Quote.
Module M.
  Inductive term :=
  | tand : term -> term -> term
  | tval : Prop -> term.
End M.
Module D.
  Import M.
  Fixpoint interp (t : term) :=
    match t with
    | tand x y => and (interp x) (interp y)
    | tval p => p
    end.
End D.
Module T.
  Import M D.
  Ltac quote_pose term :=
    quote interp in term using (fun v => pose v).
End T.

Module success.
  Import D.
  Goal True.
    T.quote_pose (True /\ True).
  Abort.
End success.

Module failure.
  Goal True.
    T.quote_pose (True /\ True). (* Error:                                                                                                                                                                  
In nested Ltac calls to "T.quote_pose" and                                                                                                                                                                  
"quote (ident) in (constr) using (tactic)", last call failed.                                                                                                                                               
Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/. *)
```

**Comment by ppedrot** [comment]
There is a conjuction of two problems here.
- The `Tacmach.New.pf_global`, which happens to be used only by Quote, is somewhat buggy because it raises a `Not_found` exception through a ad-hoc call to internalization to check that a variable is bound.
- The `quote` tactic is using an indentifier as argument, while it should use a global reference instead.

It is rather easy to fix anyways, but I thought that `quote` was one of the most unmaintained plugins from the Coq archive and implicitly deprecated...

**Comment by JasonGross** [comment]
> but I thought that quote was one of the most unmaintained plugins from the Coq archive and implicitly deprecated...

I'm benchmarking all the methods of reification I can think of, and when I read about this one in CPDT, I figured I'd include it.

**Comment by ppedrot** [comment]
What should we do then? Properly deprecate quote?

**Comment by maximedenes** [comment]
What are people expected to use instead?

**Comment by ppedrot** [comment]
Template-coq?

**Comment by ppedrot** [comment]
The quote pluging has been removed from Coq, so closing.
