### ISSUE TITLE
coq_makefile does not print warnings nor error messages about its arguments

### ISSUE THREAD

**Issue by Matafou** [coq/coq#6486]
#### Version
8.7.1

#### Operating system
linux debian

#### Description of the problem

on a shell do the following

coq_makefile -install foo -install bar

This should raise an error "-install set more than once.".
The error is raised, and coq_makefile indeed exits with code 1, but the message is never printed. The same happens for all errors of this kind.

After looking at the code it seems that lib/coqProject_file.ml uses feeders for its output but tools/coq_makefile.ml (a standalone program) makes use of it but does not use feeders nor declares any feeder. So messages get lost in limbs.

To fix this properly we should probably switch coq_makefile.ml to feeders, but we can also let things like this and just declare a feeder in coq_makefile.ml.

I must say that putting everything in mutable records is pretty hype and neat but also quite painful to debug, and the fact that this bug was not detected when coqProject_file.ml was ported to feeders does not advocate for it... But I may be simply too old^H^H^Hgrumpy.

**Comment by Zimmi48** [comment]
I think this is fixed in master: `coq_makefile -install foo -install bar` now prints `Error: invalid option "foo" passed to -install.`
