### ISSUE TITLE
Provide a way for make doc to use installed Coq for its dependencies.

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6505]
Coq should provide a make target that builds only documentation, so that we can offer a `coq-doc` opam package. Also see https://github.com/coq/coq/issues/4855.

**Comment by herbelin** [comment]
Maybe I did not understand the question, but isn't `make doc` what you'd like to do? This builds all of:
- the reference manual
- the "tutorial"
- the tutorial on inductive types
- the coqdoc-ization of the standard library

(Notice in particular that this needs to recompile all the standard library.)

**Comment by RalfJung** [comment]
> this needs to recompile all the standard library

That's pretty annoying for the opam use case... we want to have the documentation in a separate package so that the main coq package doesn't have to depend on sphinx or whatever. If all this needs is the .vo files, can't it use the ones that are installed?

**Comment by Zimmi48** [comment]
Indeed, it should be theoretically doable to make the doc OPAM package depend on the Coq OPAM package and reuse the installed `.vo`. It will probably require tweaking the make targets, but I think that is a good strategy.

**Comment by SkySkimmer** [comment]
The sphinx part is quite easy:
- point COQBIN to the installed coq at https://github.com/coq/coq/blob/7dd881fc72d62eb0c1f1e5063eb3a8ed268fb5d5/Makefile.doc#L54
- remove -boot at https://github.com/coq/coq/blob/7dd881fc72d62eb0c1f1e5063eb3a8ed268fb5d5/doc/tools/coqrst/repl/coqtop.py#L45

**Comment by ejgallego** [comment]
See also #16198

**Comment by Zimmi48** [comment]
The related issue precisely indicates that the present issue is solved since the Dune consolidation PR. It is the other case (building the doc with a non-installed Coq) that has become more complicated. Thus, a coq-doc package could now be introduced in the core-dev repo.

**Comment by ejgallego** [comment]
Yes, let's close this as "completed" as it works now (and in fact this is how the CI builds the manual)

Note that with recent dune directory targets work pretty reasonably, so maybe for 8.18 we should dump the `coq-doc` dune dep and finally fix https://github.com/coq/coq/issues/4855
