### ISSUE TITLE
A wrong proof in Coq standard library CEquivalence.v

### ISSUE THREAD

**Issue by jimyu94** [coq/coq#6508]
#### Description of the problem

I got an error when verifying the file `theories/Classes/CEquivalence.v`. When I ran `intros A R sa x y z Hxy Hyz.` (line 59), I got the error message `No product even after head-reduction.`

**Comment by ppedrot** [comment]
What do you mean by verifying? Are you loading it with CoqIDE or ProofGeneral, or are you compiling it through coqtop (e.g. via make)?

**Comment by jimyu94** [comment]
I mean loading it with CoqIDE v 8.7.1.

**Comment by ppedrot** [comment]
Then you're probably missing a `-top` command to specify that the file you're compiling is part of the Coq stdlib. There is a little bit of trickery to bootstrap the rewriting mechanism that relies on hardwired names. But anyways you shouldn't be opening that file if you're not modifying the stdlib...

**Comment by jimyu94** [comment]
@ppedrot I see. Thank you!

**Comment by ejgallego** [comment]
I can reproduce this, and indeed a non-editable file looks like a bug to me. If the file needs some weird magic it should be at least documented.

> But anyways you shouldn't be opening that file if you're not modifying the stdlib...

Eh? I'd say that of course any user is welcome to open stdlib files and try to play with them.

**Comment by herbelin** [comment]
Yes, the black magic is to open the file with the extra option `-top Coq.Classes.Equivalence`. This is because the file depends on the tactic `transitivity` which itself depends on notions defined in this file.

A comment in the file would indeed be useful (if ever we can easily maintain it in sync).

**Comment by SkySkimmer** [comment]
Maybe there's a way to make coqide do the magic without user intervention (using a _CoqProject I guess, I'm not sure how possible it is). We could also put in the emacs local variables to get PG to work.

**Comment by herbelin** [comment]
Would not know how to do it at once, but maybe possible indeed.

**Comment by jimyu94** [comment]
What shall I do if I use `coqtop -ideslave -main-channel stdfds` and feed the sentences from `CEquivalence.v` one by one? It seems there's no proper places to insert the command `-top`.

**Comment by herbelin** [comment]
@jimyu94: replying to your comment which I received by mail (even if I don't see it on the web page).

> What shall I do if I use coqtop -ideslave -main-channel stdfds and feed the
sentences from CEquivalence.v one by one? It seems there's no proper places to
insert the command -top.

I'm not familiar with the way you are feeding `coqtop -ideslave` with sentences one by one, but `coqtop` accepts `-top` so, I guess `coqtop -ideslave -main-channel stdfds -top Coq.Classes.Equivalence` would work.

**Comment by jimyu94** [comment]
@herbelin Thank you! I tried your command and it does work!

**Comment by Zimmi48** [comment]
@SkySkimmer I believe that @JasonGross has already modified a `.dir-local.el` file to do that (following interaction with me). Unfortunately, it is not editor-agnostic.

**Comment by jimyu94** [comment]
@herbelin I found this doesn't work for half of the Coq standard .v files. For example, `coqtop -ideslave -main-channel stdfds -top Coq.Init.Wf`

```
Error during initialization: 
Error: Cannot load a library with the same name as the current one.
```

**Comment by SkySkimmer** [comment]
We have _CoqProject for it all now AFAIK
