### ISSUE TITLE
CoqIDE 8.7.1 for macOS crashes upon copy / pasting

### ISSUE THREAD

**Issue by jimyu94** [coq/coq#6509]
#### Description of the problem

The CoqIDE crushes every time when I hit `cmd + C`. The IDE I install is from `https://github.com/coq/coq/releases/download/V8.7.1/coq-8.7.1-installer-macos.dmg`.

**Comment by caizixian** [comment]
Can confirm this

**Comment by Zimmi48** [comment]
Thank you for the report. Has this bug appeared since you installed Coq 8.7.1 and not before (assuming you previously had Coq 8.7.0 installed). Does the bug goes away if you reinstall Coq 8.7.0?

@caizixian Do you have the same macOS version or a different one ?

**Comment by herbelin** [comment]
I can also reproduce under MacOS X 10.11.1. Cmd-C quits 8.7.1. No problem with 8.7.0 though.

**Comment by herbelin** [comment]
Note: I cannot reproduce with a CoqIDE 8.7.1 built locally. What versions of OCaml, LablGTK2, GTK+ were used for the downloadable MacOS X image? (Don't know if the info is useful, but, for the record, I compile locally with ocaml 4.03.0, lablgtk2 2.18.4, GTK+ 2.24.31.)

Also, Cmd-v, Cmd-x, Cmd-h quits as well. The other Cmd-lowercase-letter seem to work as expected (in particular Cmd-q quits... but as expected).

**Comment by Zimmi48** [comment]
gtk+ 2.24.31 was used as well (installed with homebrew)
OCaml 4.02.3, lablgtk 2.16.0 and lablgtk-extras 1.5 were used (installed with OPAM)

For Coq 8.7.0, lablgtk-extras 1.6 was installed via OPAM, and the version of lablgtk was left unspecified, but it is likely that it was already >= 2.18.

#6045 introduced these precise version requirements.

@herbelin Can you test if downgrading lablgtk allows you to reproduce the issue in your locally compiled CoqIDE?

**Comment by Zimmi48** [comment]
OK in fact I was able to reproduce the problem (a segmentation fault) on Linux with lablgtk 2.16.0 and lablgtk-extras 1.6. So the problem is really linked to this old version of lablgtk that we should never have used and not to macOS at all.

**Comment by Zimmi48** [comment]
The problem is still there in lablgtk 2.18.2 and goes away starting with 2.18.3. So we should tighten our requirements.
As for fixing the issue with the shipped package, I propose to relaunch a new build and update the package we distribute *without* creating a new release (the code of Coq does not change). @maximedenes Would you be OK with that? Of course, I'll also send an announcement on Coq-Club about this.

**Comment by mattam82** [comment]
@Zimmi48 that sounds good to me. I don't see any link with lablgtk-extras, why mention it here? IIUC only lablgtk > 2.18.3 should be supported by coqide? (Locally I have 2.18.6 and everything is fine)

**Comment by Zimmi48** [comment]
I have no idea what lablgtk-extras is about. I was just being super specific. But yes, the issue clearly comes from lablgtk < 2.18.3, not from lablgtk-extras.

**Comment by ejgallego** [comment]
`lablgtk-extras` ships the source code editing widget.

**Comment by mattam82** [comment]
But I don't need to install it to get coqide, so... ?

**Comment by ejgallego** [comment]
I think bumping to 2.18.3 in all platforms is OK, 

> But I don't need to install it to get coqide, so... ?

Umm, you need to install it to build CoqIDE.

**Comment by mattam82** [comment]
I really doubt that, or it's somehow built in lablgtk:
# Installed packages for 4.06.0:
base-bigarray          base  Bigarray library distributed with the OCaml compile
base-threads           base  Threads library distributed with the OCaml compiler
base-unix              base  Unix library distributed with the OCaml compiler
camlp5                 7.03  Preprocessor-pretty-printer of OCaml
conf-gtksourceview        2  Virtual package relying on a GtkSourceView system i
conf-m4                   1  Virtual package relying on m4
coq                 8.7.1+1  Formal proof management system.
coq-equations       1.0+8.7  A function definition package for Coq
coqide                8.7.1  IDE of the Coq formal proof management system.
lablgtk              2.18.6  OCaml interface to GTK+
num                     1.1  The legacy Num library for arbitrary-precision inte
ocamlfind           1.7.3-1  A library manager for OCaml

**Comment by herbelin** [comment]
The CHANGES file in lablgtk 2.18.3 suggests that this is this [bug](https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1425&group_id=220&atid=1033). If this hypothesis is the right one, this started from OCaml 4.02 and might explain why we didn't observe (or at least why I didn't remember we may have) problems with old lablgtk at a time where OCaml was itself older.

**Comment by tdunning** [comment]
>  I propose to relaunch a new build and update the package we distribute without creating a new release (the code of Coq does not change). 

Hopefully, this will still get a new version number even if it doesn't have any changes to Coq.

Otherwise, users (especially naive ones like me) will be *very* confused about whether the bug is fixed.

**Comment by ejgallego** [comment]
In fact why not make this Coq 8.7.2? Releasing should be extremely cheap so this is a good moment to test the current infrastructure.

**Comment by Zimmi48** [comment]
Can someone test the new (unsigned) Coq 8.7.1 package at https://bintray.com/coq/coq/download_file?file_path=CoqIDE_8.7.1.dmg?

> In fact why not make this Coq 8.7.2? Releasing should be extremely cheap so this is a good moment to test the current infrastructure.

Releasing is not *that* cheap. I don't see the point in creating a new tag, new Windows packages, signing them, updating the Zenodo record, the documentation on the website, and asking package maintainers to update the OPAM, MacPort, Nix, etc packages, all this for a bug that is *not* in Coq.

> Hopefully, this will still get a new version number even if it doesn't have any changes to Coq.
>
> Otherwise, users (especially naive ones like me) will be very confused about whether the bug is fixed.

I'm not sure I understand what will be confusing. The dysfunctional MacOS package will be removed and the new one will be uploaded with a note saying that it was updated on e.g. January 2nd to avoid a usability bug coming from an outdated version of a dependency. A news item will be added to the website and an announcement will be sent to Coq-Club. Users that had not downloaded the package yet will never see the bug and users that did will just have to re-download and re-install. What benefit would the new version number bring?

**Comment by herbelin** [comment]
>Can someone test the new (unsigned) Coq 8.7.1 package at https://bintray.com/coq/coq/download_file?file_path=CoqIDE_8.7.1.dmg?

This seems to work normally, and with the copy-pasting bug fixed!

> The dysfunctional MacOS package will be removed and the new one will be uploaded with a note saying that it was updated (...).

For a package downloadable automatically, it is generally considered to be confusing to change the contents of a package name. Even if this precise package is maybe not intended to be automatically copied somewhere else (thus losing the accompanying notice), it might also be difficult for someone to remember if s/he downloaded a package before or after the date of change, and thus to determine "intensionally" rather than "observationally" whether her/his copy of the package is the buggy one or not.

At some time, we added extra suffixes of the form `-1` to specific distribution packages to deal with this kind of situations (I vaguely remember such a problem for an - old time - broken rpm package). But I don't know how this complies with current standard version naming schemes.

Happy new Gregorian year in passing (though still in the [Coq](https://en.wikipedia.org/wiki/Rooster_(zodiac)) year)!

**Comment by tdunning** [comment]
It is considered very bad software practice to change the bits associated
with a release tag. The idea of immutable releases is important in the face
of caching and systems that manage packages.

There are many downstream consumers of any moderately popular software and
you can't pretend to be able to contact all of them with a message to
re-download the software. You can't even pretend that they will get the new
bits if you do contact them unless the new bits have a new name.

At the very least, you should give a new release tag to coqide.

**Comment by ejgallego** [comment]
> Releasing is not that cheap. I don't see the point in creating a new tag, new Windows packages, signing them, updating the Zenodo record, the documentation on the website, and asking package maintainers to update the OPAM, MacPort, Nix, etc packages, all this for a bug that is not in Coq.

Then we should aim to make it cheaper. The bug is in Coq, and still unfixed, as we declared an incorrect GTK version dependency.

**Comment by Zimmi48** [comment]
Alright then the package will get a new number, either 8.7.1-1 or 8.7.2. In the latter case though, it will take *much* longer. Whereas if we just go for 8.7.1-1, we can release it today or tomorrow (basically the package is ready, we just need to sign it).

**Comment by mattam82** [comment]
I think the -1 option is fine
Le mar. 2 janv. 2018 à 11:37, Théo Zimmermann <notifications@github.com> a
écrit :

**Comment by Zimmi48** [comment]
@maximedenes (who has the power of signing packages) is on vacation right now. He's aware that his involvement is required. If he can find some time to sign the package during the week, he'll do it and we'll release `coq-8.7.1-1-macos.dmg`. At the latest, this will be done on Monday.

**Comment by jimyu94** [comment]
Yes. Now the `cmd + C` does its job. Thanks!

**Comment by Zimmi48** [comment]
Thank you for testing. I'll send the announcement today.

**Comment by caizixian** [comment]
I tried the new release today, and it looks good to me.

**Comment by howsiwei** [comment]
Should this update be included in https://coq.inria.fr/distrib/8.7.1/files/ which homebrew is using?

**Comment by Zimmi48** [comment]
@howsiwei Sure, it should. However, AFAIK the homebrew package doesn't contain CoqIDE and is not concerned by this bug which was an issue in the package, not in Coq sources.
