### ISSUE TITLE
Coq doesn't find Nix-installed Num library for OCaml 4.06

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6513]
#### Version

8.8+alpha (7e319ad03aba413f3165b848eaf821b364f9291b)

#### Operating system

Linux / NixOS

#### Description of the problem

As reported by @jwiegley today on Gitter, compiling Coq with OCaml 4.06 provided with Nix seems to hit an issue.

To reproduce, first apply the following patch to `default.nix`:

```diff
diff --git a/default.nix b/default.nix
index 3dd24bac4..1c438f47a 100644
--- a/default.nix
+++ b/default.nix
@@ -34,6 +34,7 @@ stdenv.mkDerivation rec {
 
     # Coq dependencies
     ocaml
+    ocamlPackages.num
     findlib
     camlp5_strict
 
@@ -56,7 +57,7 @@ stdenv.mkDerivation rec {
   ] else []) ++ (if lib.inNixShell then [
     ocamlPackages.merlin
     ocamlPackages.ocpIndent
-    ocamlPackages.ocp-index
+    # ocamlPackages.ocp-index
   ] else []);
 
   src =
```

The dependency on the Num library is otherwise missing, and ocp-index does not seem to compile in current `<nixpkgs>` (version NixOS/nixpkgs@93829f1b031a66c093865910b1e8823c6b59c720) with OCaml 4.06.

Then run `nix-shell --arg ocamlPackages "with import <nixpkgs> {}; ocaml-ng.ocamlPackages_4_06"`.
In the shell, we can see the library Num is found by ocamlfind:

```
$ ocamlfind query num
/nix/store/nkrk7hfp7xx3j0h4bl7dpvxm574p7mj4-ocaml4.06.0-num-1.1/lib/ocaml/4.06.0/site-lib/num
```
and configure runs without trouble:
```
$ ./configure -local
You have OCaml 4.06.0. Good!
You have OCamlfind 1.7.3. Good!
You have Camlp5 7.03. Good!
You have native-code compilation. Good!
You have the Num library installed. Good!
LablGtk2 found (via ocamlfind, 2.18.6), with native threads:
=> native CoqIde will be built.
```
but launching the compilation fails with:
```
OCAMLC    plugins/micromega/sos_types.mli
File "plugins/micromega/sos_types.mli", line 15, characters 11-18:
Error: Unbound module Num
```
which seems to indicate that the Makefile doesn't know how to find the Num library (probably doesn't use ocamlfind for this).

**Comment by jwiegley** [comment]
Thank you @Zimmi48, that's my exact problem.  Also, I've posted two pull requests to nixpkgs so that `-make-doc yes` will work for the Coq build.

**Comment by ejgallego** [comment]
Umm, Coq's makefile does indeed use `ocamlfind` to locate `num`, I'm afraid you'll have to provide better debug info using `make VERBOSE=1`.

**Comment by vbgl** [comment]
The issue is that plugins `micromega` and `nsatz` use the `unix` and `num` libraries but do not search for them: they expect to find them as part of the standard library. However, starting from OCaml 4.06, according to the [Change log](https://github.com/ocaml/ocaml/blob/0c68cd1055b4f6e9992f04a2acc5c6b4918ea0ae/Changes#L188), `num` is no longer part of the standard library.

```
"…/ocamlfind" ocamlc -thread -rectypes -w +a-4-9-27-41-42-44-45-48-50 -bin-annot -safe-string   -I clib -I lib -I API -open API -I plugins/omega -I plugins/romega -I plugins/micromega -I plugins/quote -I plugins/setoid_ring -I plugins/extraction -I plugins/fourier -I plugins/cc -I plugins/funind -I plugins/firstorder -I plugins/derive -I plugins/rtauto -I plugins/nsatz -I plugins/syntax -I plugins/btauto -I plugins/ssrmatching -I plugins/ltac -I plugins/ssr -I "/nix/store/4rz93ra16sz871vc2zz7w9izkjy3ysmi-camlp5-7.03/lib/ocaml/4.06.0/site-lib/camlp5" -g  -c plugins/micromega/sos_types.mli
File "plugins/micromega/sos_types.mli", line 15, characters 11-18:
Error: Unbound module Num
```

The makefile indeed uses `ocamlfind`, but without the required `-package num` argument.

**Comment by jwiegley** [comment]
Thank you. With this fix, I can now build `master` under Nix by using this overlay:

```
self: pkgs: rec {

coq_HEAD = pkgs.stdenv.lib.overrideDerivation coq_8_7_override (attrs: rec {
  version = "8.8";
  name = "coq-${version}-pre";
  coq-version = "${version}";
  src = ~/oss/coq;
  buildInputs = attrs.buildInputs
    ++ (with pkgs; [ ocaml-ng.ocamlPackages_4_06.num
                     texFull hevea fig2dev imagemagick_light ]);
  preConfigure = ''
    configureFlagsArray=(
      -with-doc no
      -coqide no
    )
  '';
});

coqPackages_HEAD = pkgs.mkCoqPackages coq_HEAD;

}
```

**Comment by Zimmi48** [comment]
@jwiegley Why not use `nix-build --arg ocamlPackages "(import <nixpkgs> {}).ocaml-ng.ocamlPackages_4_06" --arg doCheck false --arg buildIde false` thanks to the `default.nix` file provided? It works just as well.
