### ISSUE TITLE
constr: error in Ltac tactic?

### ISSUE THREAD

**Issue by william-lawvere** [coq/coq#6514]
#### Version

8.7

#### Operating system
Mac

#### Description of the problem

I'm not sure why the `constr:` notation in this tactic 

```
Ltac inList x xs :=
  match xs with
  | (x, _) => constr:true
  | (_, ?xs') => inList x xs'
  | _ => constr:false
  end.
```

leads to the following error:

`line 3, characters 20-21
Syntax error: 'end' expected after [match_list] (in [tactic:tactic_expr]).`

**Comment by SkySkimmer** [comment]
CHANGES says:
>Changes from V8.5 to V8.6beta1
==============================
>- Tactic scopes in Ltac like constr: and ltac: now require parentheses around
  their argument.

**Comment by william-lawvere** [comment]
Thanks!
