### ISSUE TITLE
download.camlcity.org unresponsive, makes AppVeyor fail

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6520]
camlcity.org is down (again) and this makes the packaging jobs on AppVeyor fail (because they download findlib from this site). Could we work around this untrustworthy website that hosts findlib?

**Comment by Zimmi48** [comment]
Could we just use https://opam.ocaml.org/archives/ocamlfind.1.5.6+opam.tar.gz instead? Less likely to be down and the packages are probably the same. I can't check though since camlcity is still down.

**Comment by Zimmi48** [comment]
They chose their time wisely! Camlcity.org is down again!

**Comment by Zimmi48** [comment]
BTW there is also a new (very recent, likely unrelated, issue with test-suite builds on AppVeyor reaching the 1h limit and failing). It happened suddenly on all PRs.

**Comment by ejgallego** [comment]
Ouch that is bad, somebody with a windows VM should try to reproduce. We are not testing performance in Windows at all [and barely on Linux] so I wouldn't be surprised of some regression.

**Comment by Zimmi48** [comment]
I wouldn't have been surprised if there was some regression but it is extremely unlikely in this case because it really happened suddenly on all PRs while the latest master build was green. So I think the problem comes from AppVeyor itself. Moreover, it seems that in all cases, the hang is *after* the test-suite results.

**Comment by Zimmi48** [comment]
Windows test-suite builds are currently failing (cf. https://ci.appveyor.com/project/coq/coq/build/master~3700/job/0f6u7t4m7w2jowig for instance) because both  http://download.camlcity.org/download/findlib-1.8.0.tar.gz and http://download2.camlcity.org/download/findlib-1.8.0.tar.gz are currently inaccessible. These are probably the most unreliable web-servers I know of!
