### ISSUE TITLE
 Anomaly "Evar ?X25 was not declared." when using Program Lemma

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#6529]
#### Version
The Coq Proof Assistant, version 8.7.1 (December 2017)
compiled on Dec 16 2017 22:25:15 with OCaml 4.05.0

#### Operating system
Arch Linux

#### Description of the problem
Running the following code through `coqc` results in an error.
```
Require Import Vector Program.

Program Definition append_nil_def :=
  forall A n (ls: t A n), append ls (nil A) = ls. (* Works *)

Lemma append_nil : append_nil_def. (* Works *)
Proof.
Admitted.

Program Lemma append_nil' :
  forall A n (ls: t A n), append ls (nil A) = ls.
(* Error: Anomaly "Evar ?X25 was not declared." Please report at http://coq.inria.fr/bugs/. *)
```

**Comment by Zimmi48** [comment]
@mattam82 You self-assigned this issue and marked it as high priority. Will you have time to fix it for 8.7.2 (release date scheduled 8.7.2, so all corresponding PRs should be ready several days before this date).

**Comment by mattam82** [comment]
I’ll try that, thanks for the reminder

**Comment by Zimmi48** [comment]
If the fix is not submitted on Monday, it probably won't end up in 8.7.2.

**Comment by mattam82** [comment]
Ok
