### ISSUE TITLE
`refine _` can take arbitrarily long (even without typeclasses)

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6539]
#### Version

8.8+alpha (e2d1c676b23a335b4fb8a528c99dfca2b82a1a39)

#### Operating system

Linux

#### Description of the problem

(See Also #3280)

I think `refine _`, as a no-op, should always be basically instantaneous, regardless of the size of the goal.

```coq
Fixpoint twos (n : nat) (A : Type) :=
  match n with
    | 0 => A
    | S n' => twos n' (prod A A)
  end.

Tactic Notation "display" string(tacname) tactic3(tac) :=
  match goal with |- let n := ?k in _ => idtac k "Time" tacname end;
  lazy [twos];
  time tac ().

Notation "'hide'" := (_ = _) : type_scope.

Goal let n := 21 in twos n Set = twos n Set.
  display "refine _" (fun _ => lazymatch goal with |- ?G => refine _ end). (* 4.195 *) Undo.
```

**Comment by ppedrot** [comment]
This is due to `refine` performing a βι-normalization of the goal, for a mix of compatibility and intuitiveness. If you don't want that, use the dedicated `simple refine` tactic. In particular, I think this bug report is invalid.

**Comment by psteckler** [comment]
The description of `simple refine` says:
> It does not perform any beta-reduction either. 

Why does this succeed:

```
Goal ((fun x => x) True).
  simple refine I.
Qed.
```

**Comment by ppedrot** [comment]
@psteckler This is correct, as `I : (fun x => x) True`, and there wouldn't any sane way to prevent that thankfully. What the documentation means is that *the generated subgoals* are not in βι normal form.

**Comment by psteckler** [comment]
I see, thanks.

**Comment by JasonGross** [comment]
Ah, indeed, using simple refine makes sense.  There seems to be no way to use it from Ltac2, though?
