### ISSUE TITLE
Vernac classifier fails on "all : Check 1."

### ISSUE THREAD

**Issue by blefloch** [coq/coq#6563]
With version 8.6 (January 2018) compiled on Jan 6 2018 14:9:57 with OCaml 4.01.0, on Ubuntu 14.04.5 LTS, running the following interactively or through `coqc` 
```coq
Goal True /\ True.
split.
all : Check 1.
```
gives
> File "./test.v", line 3, characters 0-14:
> Anomaly:
> File "stm/vernac_classifier.ml", line 223, characters 23-29: Assertion failed.
> Please report at http://coq.inria.fr/bugs/.

Obviously the right code would have been to type `Check 1.` instead of `all : Check 1.`

**Comment by SkySkimmer** [comment]
>With version 8.6 

Current stable is 8.7 which says "Error: Query commands only support the single numbered goal selector."

**Comment by blefloch** [comment]
Sorry, I followed instructions at https://coq.inria.fr/opam/www/using.html a bit too literally when installing: it provides code to install 8.6.  See issue https://github.com/coq/www/issues/58

**Comment by ejgallego** [comment]
Indeed, sorry for the error in the webpage.
