### ISSUE TITLE
Coq no longer builds CoqIDE with liblablgtk2-ocaml on Ubuntu

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6585]
#### Version

v8.7, master

#### Operating system

Ubuntu (tested on Bionic, Artful, Zesty, Xenial, Trusty, Precise)

#### Description of the problem

The `./configure` script seems to mis-identify the version of `lablgtk2` when it's installed from the liblablgtk2-ocaml package, resulting in CoqIDE not being built:
See for example [this buildlog from bionic on launchpad](https://launchpadlibrarian.net/353424761/buildlog_ubuntu-bionic-i386.coq_8.master~git~201801140203+18666-0~daily307~ubuntu18.04.1_BUILDING.txt.gz):

>     Selecting previously unselected package liblablgtk2-ocaml.
>     Preparing to unpack .../142-liblablgtk2-ocaml_2.18.5+dfsg-1build1_i386.deb ...
>     Unpacking liblablgtk2-ocaml (2.18.5+dfsg-1build1) ...
>     ...
>     Selecting previously unselected package liblablgtk2-ocaml-dev.
>     Preparing to unpack .../148-liblablgtk2-ocaml-dev_2.18.5+dfsg-1build1_i386.deb ...
>     Unpacking liblablgtk2-ocaml-dev (2.18.5+dfsg-1build1) ...
>     ...
>     Setting up liblablgtk2-ocaml (2.18.5+dfsg-1build1) ...
>     ...
>     Setting up liblablgtk2-ocaml-dev (2.18.5+dfsg-1build1) ...
>     ...
>     ./configure -arch Linux -prefix /usr -mandir /usr/share/man -configdir /etc/xdg/coq -emacslib /usr/share/emacs/site-lisp/coq -browser "/usr/bin/x-www-browser %s &" -with-doc no -vmbyteflags "-dllib,-lcoqrun"
>     You have OCaml 4.05.0. Good!
>     You have OCamlfind 1.7.3. Good!
>     You have Camlp5 7.01. Good!
>     You have native-code compilation. Good!
>     LablGtk2 found (via ocamlfind, 2.16.0), but too old (required >= 2.18.3, found 2.16.0):
>     => no CoqIde will be built.
>     
>       Architecture                : Linux
>       Coq VM bytecode link flags  : -dllib -lcoqrun
>       Other bytecode link flags   : 
>       OCaml version               : 4.05.0
>       OCaml binaries in           : /usr/bin/
>       OCaml library in            : /usr/lib/ocaml
>       OCaml flambda flags         : 
>       Camlp5 version              : 7.01
>       Camlp5 binaries in          : /usr/bin
>       Camlp5 library in           : +camlp5
>       Native dynamic link support : true
>       CoqIde                      : no
>       Documentation               : None
>       Web browser                 : /usr/bin/x-www-browser %s &
>       Coq web site                : http://coq.inria.fr/
>       Bytecode VM enabled         : true
>       Native Compiler enabled     : true
>     
>       Paths for true installation:
>       - the Coq binaries will be copied in /usr/bin
>       - the Coq library will be copied in /usr/lib/coq
>       - the Coqide configuration files will be copied in /etc/xdg/coq
>       - the Coqide data files will be copied in /usr/share/coq
>       - the Coq man pages will be copied in /usr/share/man
>       - the Coq documentation will be copied in /usr/share/doc/coq
>       - the Coq Emacs mode will be copied in /usr/share/emacs/site-lisp/coq
>       - the Coqdoc LaTeX files will be copied in /usr/share/texmf/tex/latex/misc
>     
>     If anything is wrong above, please restart './configure'.
>     
>     *Warning* To compile the system for a new architecture
>               don't forget to do a 'make clean' before './configure'.

**Comment by Zimmi48** [comment]
General rule: no "blocker" label without a milestone.

Can you confirm that locally installing `lablgtk.2.18.5` with OPAM then running `ocamlfind query -format "%v" lablgtk2` reports the incorrect version? If yes, that will confirm that the bug is in lablgtk (a recurring one apparently since 2.18.3 also reports 2.18.0).

**Comment by JasonGross** [comment]
Locally:
```
$ opam install lablgtk.2.18.5
[NOTE] Package lablgtk is already installed (current version is 2.18.5).
$ ocamlfind query -format "%v" lablgtk2
2.18.4
```
But see also https://bugs.launchpad.net/ubuntu/+source/lablgtk2/+bug/1577236 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822949

**Comment by Zimmi48** [comment]
Hum OK. Well, my impression about this is that these are upstream bugs that ought to be fixed upstream (Ubuntu / Debian bugs to be more specific). One workaround could be a configure option to disable the version check. Another workaround is not to rely on this version info and instead go back to some heuristic. However, I won't spend time on this. If you, or someone else, is willing, please go ahead and propose a solution.

**Comment by psteckler** [comment]
So running `ocamlfind` at the command line reports a different `lablgtk2` version than when it's run from `configure`? 

Maybe different versions of `ocamlfind` are being run? To make them the same, you could run
```
  configure -ocamlfind `which ocamlfind`
```

**Comment by JasonGross** [comment]
@psteckler No, these are different machines, with lablgtk installed in different manners.

@Zimmi48 I think we should warn rather than error on getting version `2.16.0` on Linux (which is what all of the debian packages seem to be hard-coded to).

**Comment by ejgallego** [comment]
Indeed, given the bugs we must just warn the user but don't abort configure..
