### ISSUE TITLE
Anomaly: Unknown tactic alias: Coq.Init.Notations.auto_#_#_#_4C69D510

### ISSUE THREAD

**Issue by eluuk** [coq/coq#6592]
#### Version

8.7.1

#### Operating system

Linux

#### Description of the problem

Got the following dump on my Midnight Commander shell where I run coqide:

> 14027:proofworker:5:0] Slave: critical exception: Anomaly: Unknown tactic alias: Coq.Init.Notations.auto_#_#_#_4C69D510. Please
> report at http://coq.inria.fr/bugs/.
> 14135:proofworker:8:0] Slave: critical exception: Anomaly: Unknown tactic alias: Coq.Init.Notations.auto_#_#_#_4C69D510. Please
> report at http://coq.inria.fr/bugs/.

A bit later I noticed a weird behavior: upon closing coqide, it reopened another instances of itself ca. 5 times (had to close my (AFAIK only) coqide instance 5 times). That was more or less it (and I probably can't reproduce it)

**Comment by ejgallego** [comment]
Without a proof script to try to reproduce this it is going to be harder to investigate.

**Comment by eluuk** [comment]
As the dump might have been there for hours before I noticed (w/ a lot of code run during this time), it's very difficult to connect it w/ a specific code of mine

**Comment by Zimmi48** [comment]
Let's close this until someone can reproduce.
