### ISSUE TITLE
error message "The system cannot find the path specified."  about coqide

### ISSUE THREAD

**Issue by darenme** [coq/coq#6603]
#### Version
8.5pl2 and 8.7.1

#### Operating system
windows10 1709

#### Description of the problem
I installed coq, and I can type coqtop cammand in cmd. but when I type coqide, I always get this

> Coqtop exited
> Command was: ""C:\Coq\bin\coqtop.exe" -nois -filteropts "
> Answer was: The system cannot find the path specified.
![error](https://user-images.githubusercontent.com/18227489/35044319-e49d27e2-fbca-11e7-9abb-6ae4e11663b9.png)

**Comment by ejgallego** [comment]
How did you install Coq. Did you use the provided installer?

**Comment by darenme** [comment]
Thank you for reply.
I installed coq via the installer from this link https://github.com/coq/coq/releases/tag/V8.7.1.
Is this about the env variable of path in win10? but I have manually put the path like "C:\Coq\bin" 
in the path env, why it seems that the coq-ide  cannot find the coqtop cammand?

**Comment by arvand** [comment]
I modified coqtop in preferences and now I'm stuck with it! even when I uninstall and re-install coq the problem won't go away!!
Does anybody know where the preferences are stored?

**Comment by darenme** [comment]
Thank guys, stderr's answer in this link https://superuser.com/questions/727316/error-in-command-line-the-system-cannot-find-the-path-specified solved my problem. It has nothing to do with Coq, my bad :(
