### ISSUE TITLE
Replace Rlist by list R

### ISSUE THREAD

**Issue by amahboubi** [coq/coq#6607]
https://github.com/coq/coq/blob/4d8903c06fd9fd2aca793da8bb55448906347a8c/theories/Reals/RList.v#L13

**Comment by amahboubi** [comment]
This is specially annoying since the constructors are named nil and cons. Importing Reals hence overrides the polymorphic versions.

**Comment by maximedenes** [comment]
Hi @amahboubi 

How about sending a PR patching this? If there is no technical drawback to switching to the polymorphic version, I'd bet this should be a consensual change.

**Comment by amahboubi** [comment]
Ok, I'll do that.
