### ISSUE TITLE
Anomaly on fixpoint with primitive projections

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#6621]
```coq
Set Primitive Projections.

Axiom positive : Set.
Axiom xH : positive.
Inductive Z : Set := pos : positive -> Z.

Record Q : Set := Qmake { Qnum : Z }.

Record Qc : Set := Qcmake { this :> Q ; }.

Definition Q2Qc (q:Q) : Qc := Qcmake q.

Axiom pmul : positive -> positive -> positive.

Definition Zmul x y :=
  match x, y with
    | pos x', pos y' => pos (pmul x' y')
  end.

Definition Qmult := fun x y : Q => Qmake (Zmul (Qnum x) (Qnum y)) .

Notation Q1 := {| Qnum := pos xH |}.

Definition Qcmult (x y : Qc) := Q2Qc (Qmult x y).
Infix "*" := Qcmult.

Fixpoint Qcpower (q:Qc) (n:nat) {struct q} : Qc :=
  match n with
    | O => Q2Qc Q1
    | S n => q * (Qcpower q n)
  end.
(* Error:
Anomaly
"File "kernel/declareops.ml", line 211, characters 2-8: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
*)
```
https://github.com/coq/coq/blob/9aa2464375c1515aa64df7dc910e2f324e34c82f/kernel/declareops.ml#L172

This is related to and possibly fixed by #407. It is present in 8.7.

**Comment by mattam82** [comment]
Yes, a priori the kernel would disallow the { struct q } annotation,
ensuring the structural argument is indeed a Rec.
Le ven. 19 janv. 2018 à 13:01, Gaëtan Gilbert <notifications@github.com> a
écrit :

**Comment by SkySkimmer** [comment]
Note that we also get the anomaly if we omit the struct annotation, because when guessing the structural argument we don't catch assertion failures.

**Comment by maximedenes** [comment]
I found a problem in the code of the subterm relation for primitive projections, just by accident. It turns out the fix also fixes this bug. Will open a PR.
