### ISSUE TITLE
Derive Plugin gives "Error: Anomaly "more than one statement."" on abstract

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6631]
#### Version

8.8+alpha

#### Description of the problem

```coq
Require Import Coq.derive.Derive.

Derive f SuchThat (f = 1 + 1) As feq.
Proof.
  transitivity 2.
  2:abstract vm_cast_no_check (eq_refl 2).
  (* Error: Anomaly "more than one statement."
Please report at http://coq.inria.fr/bugs/. *)
```

**Comment by JasonGross** [comment]
No, `vm_cast_no_check` is fine.  Note that it also breaks with
```coq
Require Import Coq.derive.Derive.
Require Import Coq.Compat.AdmitAxiom.

Derive f SuchThat (f = 1 + 1) As feq.
Proof.
  transitivity 2.
  2:admit.
```

The anomaly with `abstract` is already present in 8.5beta1, and the derive plugin does not seem to be present in 8.4pl6...

**Comment by aspiwack** [comment]
Right. This doesn't sound terribly hard to fix. Let's just take the first open thingy as the name instead of requiring that there is only one.

**Comment by JasonGross** [comment]
Great!  Shall I expect a PR from you fixing this soon?  (Or are you wanting me to make one?)
