### ISSUE TITLE
Incorrect generalization

### ISSUE THREAD

**Issue by arthuraa** [coq/coq#6634]
#### Version

8.7.0

#### Operating system

Ubuntu 16.04

#### Description of the problem

Consider the following snippet:

```
From Coq Require Import ssreflect.

Lemma normalizeP (p : tt = tt) : p = p.
Proof.
move: {2} tt p. (* Weird *)
Abort.
```

After executing the first line, the goal becomes the ill-typed term

```
forall (u : unit) (p : @eq unit tt u), @eq (@eq unit tt tt) p p
```

That is, the type of `p` does not match the type expected by `@eq (@eq unit tt tt)`. I expected this to be caught by the generalization in `move`.

**Comment by gares** [comment]
I guess we don't type check the resulting goal (as we do in, say, `elim`) :-/
