### ISSUE TITLE
Fail to build coq 8.7.1 with ocaml 4.06

### ISSUE THREAD

**Issue by zorun** [coq/coq#6638]
I am trying to update the Arch Linux package against ocaml 4.06 https://www.archlinux.org/packages/community/x86_64/coq/

I already fixed the issue reported in #6513 (by applying 8e7b876b6d9f3d4131e3b7e969f8e1943154df4c and packaging `ocaml-num`)

However there is still a build issue further on:

```
COQMKTOP -o bin/coqtop
findlib: [WARNING] Interface profile.cmi occurs in several directories: /usr/lib/ocaml/compiler-libs, lib
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/lib/ocaml, /usr/lib/ocaml/compiler-libs
File "/tmp/coqmain9aadf4.ml", line 1:
Error: Cannot find file nums.cmxa
make[1]: *** [Makefile.build:391: bin/coqtop] Error 2
make[1]: Leaving directory '/build/coq/src/coq-8.7.1'
make: *** [Makefile:159: submake] Error 2
```

`nums.cmxa` exists in `/usr/lib/ocaml/num/` thanks to https://www.archlinux.org/packages/community/x86_64/ocaml-num/ (see the file list).  For this `ocaml-num` package I used the findlib installation method from this commit https://github.com/ocaml/num/commit/7dd5e935aaa2b902585b3b2d0e55ad9b2442fff0

Full build log: https://paste.aliens-lyon.fr/kcX

Any idea?  I looked at other distributions but it seems that nobody is packaging ocaml 4.06 yet.

**Comment by zorun** [comment]
The build goes fine with latest master.  I haven't been able to identify a commit in master that could fix this issue.

Next attempt: v8.7 branch, to see if the mysterious fix has already been backported.

**Comment by zorun** [comment]
Build also fails with v8.7 branch.

The difference between master and v8.7 can probably be explained by 598e3ae4a8eb8d9bce316e13d71ee48d9ba1a01f ("[build] Remove coqmktop in favor of ocamlfind")

I am now building 8.7.1 with a backported version of this patch.

**Comment by zorun** [comment]
598e3ae4a8eb8d9bce316e13d71ee48d9ba1a01f was indeed a good lead!

I have backported it to 8.7 (fixing a few simple conflicts, the result is at https://github.com/zorun/coq/commit/93b6f5cdc264944a2f16714494da45f6255036c5) and it now builds fine :)

@Zimmi48 do you think backporting such a large change to 8.7 is desirable?  Maybe there is a simpler way?
I tried to manually backport the various additions of `-package num` from 598e3ae4a8eb8d9bce316e13d71ee48d9ba1a01f but failed to obtain a working build.

**Comment by zorun** [comment]
Adding @ejgallego to the discussion

**Comment by Zimmi48** [comment]
Thanks a lot @zorun for your detailed investigation!
Indeed, normally this commit is a no-go for backporting because it removes existing functionality.
@ejgallego Do you understand what is going on and how to prepare a lighter fix for the v8.7 branch?

**Comment by ejgallego** [comment]
@Zimmi48 I'm much afraid that this looks like a case of Arch packagers being too strict in packaging guidelines and thus deviating from the recommended `num` compatibility guidelines from OCaml upstream. This looks similar to the Nix problem I think.

We could indeed try to prepare a fix by locating `num` using `ocamlfind`, but not sure how invasive it will be.

**Comment by Zimmi48** [comment]
> We could indeed try to prepare a fix by locating num using ocamlfind, but not sure how invasive it will be.

But I thought that had already be done to fix #6513 (and backported).

**Comment by juergenhoetzel** [comment]
> @Zimmi48 I'm much afraid that this looks like a case of Arch packagers being too strict in packaging guidelines and thus deviating from the recommended num compatibility guidelines from OCaml upstream.

Could you provide a link to the **num compatibility guidelines from OCaml upstream** ? I did not find any guidelines. Thanks.

**Comment by ejgallego** [comment]
> Could you provide a link to the num compatibility guidelines from OCaml upstream ? I did not find any guidelines. Thanks.

I don't recall where the exact discussion took place [and I'm a bit busy to search for it], but basically the guideline is to keep installing `num.cma{,x}` in the old location `ocamlc -where`, not under their own dir as most packages do. See the makefile https://github.com/ocaml/num/blob/master/src/Makefile

**Comment by juergenhoetzel** [comment]
> I don't recall where the exact discussion took place [and I'm a bit busy to search for it], but basically the guideline is to keep installing num.cma{,x} in the old location ocamlc -where, not under their own dir as most packages do. See the makefile https://github.com/ocaml/num/blob/master/src/Makefile

Thanks for the hint!

@zorun I second that. This will probably prevent compilation failures of  many AUR packages.

**Comment by zorun** [comment]
Yes, I saw the two install methods for Num, but the default "compatibility" method is not usable for packaging, because it ignores `DESTDIR`.  This is why I opted for the second method which seemed much cleaner and standard.

I will give it a try with the "compatibility" method and improve Num's build system for packaging.  But in general Arch Linux tends not to like to keep old things around :)

**Comment by ejgallego** [comment]
Maybe a symlink would work @zorun . Indeed that's not an optimal situation but a few legacy packages may become broken. [Not too many on the other hand as most of the OCaml ecosystem should be using ocamlfind by now I guess]

**Comment by ejgallego** [comment]
#6669 should help with this.

**Comment by Zimmi48** [comment]
@zorun Could you test in your setup and confirm?

**Comment by zorun** [comment]
@ejgallego @Zimmi48 nice! It works and is much less invasive than 598e3ae4a8eb8d9bce316e13d71ee48d9ba1a01f .  Merging that patch to 8.7 is a good idea :+1:

**Comment by ejgallego** [comment]
One week ago I submitted 8.7.1 with the patch to OPAM, however, as nobody wants to merge the PR https://github.com/ocaml/opam-repository/pull/11327 we couldn't see more testing.

**Comment by Zimmi48** [comment]
Patch merged.

**Comment by zorun** [comment]
8.7.2 builds fine, thanks :+1:
