### ISSUE TITLE
VST is now compatible with CompCert 3.2 and thus it should be possible to share the build in CircleCI.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6639]
According to the recent release announcement of VST, it is now compatible with the latest release of CompCert (it used to depend on an older branch that they maintained). The sources of CompCert within the VST repository have been updated to reflect this.
If VST is also compatible with CompCert master (probably the case), it would be good to build CompCert only once in CircleCI tests (and thus have VST depend on the CompCert build).

**Comment by SkySkimmer** [comment]
>If VST is also compatible with CompCert master

The compcert in their repo has the latest compcert commit so it should be. https://github.com/PrincetonUniversity/VST/commit/5902c937543742119be211f0d9498231731c62a9

**Comment by ejgallego** [comment]
I'm not sure this is a good idea as VST doesn't track CompCert's master AFAICT.

**Comment by Zimmi48** [comment]
> I'm not sure this is a good idea as VST doesn't track CompCert's master AFAICT.

Yeah, well. I agree that this probably means trouble one of these days (hopefully, not too soon because CompCert is not expected to break its API all the time). However in the meantime, saving precious build time on the CI is an important aspect. This could also mean not having to duplicate a compatibility fix PR on both CompCert and VST repositories.

**Comment by ejgallego** [comment]
> This could also mean not having to duplicate a compatibility fix PR on both CompCert and VST repositories.

IMHO this is all upstream stuff and not our business. If we are short on CI capacity we should increase it, not start relying on hacking complex upstream projects.

**Comment by Zimmi48** [comment]
Not something we can do at the current time with GitLab CI.
