### ISSUE TITLE
dev/doc/proof-engine.md talks about `Sigma` (that is not there anymore)

### ISSUE THREAD

**Issue by gares** [coq/coq#6640]
There is a long example in such document, it still mentions `Sigma`

**Comment by maximedenes** [comment]
@ppedrot Can you update the milestone to reflect your current schedule?

**Comment by ppedrot** [comment]
I don't think it's a really pressing matter, moving it to 8.9, we'll backport it if desperately needed.

**Comment by ejgallego** [comment]
Fixed by https://github.com/coq/coq/pull/8809
