### ISSUE TITLE
coq_makefile: Provide a way to pass extra flags to coqdoc (and other tools)

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6659]
#### Version

8.7, master

#### Operating system
Linux

#### Description of the problem

There is currently no good way to pass extra flags (e.g., `-extern`) to coqdoc when running `make html`. Looking at the Makefile, the command that's run is
```
	$(HIDE)$(COQDOC) \
		-toc $(COQDOCFLAGS) -html $(GAL) $(COQDOCLIBS) -d html $(VFILES)
```
So, I expected I can do `COQDOCFLAGS="-extern ..." make html`, but that would totally break everything because the default is
```
COQDOCFLAGS?=-interpolate -utf8 $(COQLIBS_NOML)
```
So, I actually need to do `COQDOCFLAGS="-interpolate -utf8 $(COQLIBS_NOML) -extern ..." make html` and cope that `COQLIBS_NOML` never gets renamed. Ugh.

So, what was the intention of the design here? This is not actually unique to coqdoc; `COQFLAGS` and `COQCHKFLAGS` also have default values and thus are not suited for passing in extra flags in a stable way. I'm happy to help with the implementation, but this needs some design work for what the intended API even is, and ideally somehow who understands the intention of the current API :D

EDIT: Curiously, `COQDOCLIBS` is *not* set. So it would actually be suited for my purpose. The name doesn't make it sound like that's the intention, though.

**Comment by gares** [comment]
I guess the two use cases (add/override) make sense.
I'd say to systematically use, for each and every `FOO`,
```
FOOEXTRAFLAGS?=
FOOFLAGS?= -default flags $FOOEXTRAFLAGS
```
I think that `FOOFLAGS` and `FOOEXTRAFLAGS` should be settable both at the command line and in the `Makefile.conf.local`, where the command line has precesence (I guess it should just work, but it needs to be tested).

**Comment by gares** [comment]
Now that I think about it I'd refine this as follows.

In `Makefile.conf`
```
FOODEFAULTFLAGS=-default flags
```
In `Makefile.in`
```
FOOEXTRAFLAGS?=
FOOFLAGS?= $FOODEFAULTFLAGS $FOOEXTRAFLAGS
```
In this way the default flags can be used by a third party

**Comment by gares** [comment]
Does this make sense to you? Would that suffice?

**Comment by RalfJung** [comment]
> I guess the two use cases (add/override) make sense.

For the `-interpolate -utf8`, I agree. But for the `$(COQLIBS_NOML)`, that seems like a different category -- nothing will work of that's not passed, right? Feels like that should be in `COQDOCLIBS`, not in `COQDOCFLAGS`.

Re: your proposal, I don't think I understand the purpose of that third `COQMF_*` variable. Why not just set `FOOFLAGS ?= -default flags` in `Makefile.conf`?

**Comment by gares** [comment]
I think `COQLIBS_NOML` should be passed directly to the `COQDOC` invocation, i.e. put outside of `COQDOCFLAGS`.

wrt the `.conf` file I see it as a file just holding values as spit by Coq and meant to be included (all variables are in the `COQMF_` namespace). All the logic (to make a variable overridable, extensible,..) should go in `CoqMakefile.in`.

**Comment by RalfJung** [comment]
> wrt the .conf file I see it as a file just holding values as spit by Coq and meant to be included (all variables are in the COQMF_ namespace).

So the idea is that the actual `Makefile` is always the same, and all the differences are factored into `Makefile.conf`?

**Comment by RalfJung** [comment]
I just realized even for Coq itself the provided flags are not usable. I wanted to write a script that compiles some existing Coq development but adds an additional directory to the library path -- the kind of thing you'd do with `CLFAGS=-Idir` for a C compiler. Turns out coq_makefile pre-initializes all variables that are passed to `coqc` based on `_CoqProject`; the only thing I can do is overwrite what is in there and then of course things don't compile.

**Comment by gares** [comment]
> adds an additional directory to the library path

This is the purpose of the "design" discussed in this issue, i.e. to pass FOOFLAGS to override completely FOO or to pass FOOEXTRAFLAGS to append to FOO.

Are you saying you need to *prepend* extra flags?

**Comment by RalfJung** [comment]
I guess the order does not matter. I just somehow thought that at least for library paths, there already was a solution...

I guess you are right, and this is a duplicate. Sorry.

Also, I realized I forgot to comment on one thing you said:
> wrt the .conf file I see it as a file just holding values as spit by Coq and meant to be included (all variables are in the COQMF_ namespace). All the logic (to make a variable overridable, extensible,..) should go in CoqMakefile.in.

The maybe it should just be called `COQMF_FOO` or `COQMF_FOOFLAGS`? After all, these are the flags as set by coq_makefile. "default" sound like it's a Coq-level default, whereas there is indeed project-specific configuration in there (`COQMF_COQLIBS =  -Q theories iris`, for example). Also a comment in `.conf` would be helpful saying that these variables are NOT supposed to be overriden.

**Comment by gares** [comment]
ok

BTW, in the initial message you say you may want/have-time to implement this.
Is it still the case? (if so please change the assignee)

**Comment by RalfJung** [comment]
I said I'm happy to *help*.^^

But yes, I could give it a try.

**Comment by RalfJung** [comment]
First attempt: https://github.com/coq/coq/pull/7025
