### ISSUE TITLE
Anomaly with universe polymorphism

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#6678]
On:
```coq
Set Universe Polymorphism.
Definition U@{i} := @id Type@{i+1} Type@{i}.
```
coq's master spits out:
```
Conversion test raised an anomaly:
Anomaly "Unable to handle arbitrary u+k <= v constraints."
Please report at http://coq.inria.fr/bugs/.
```

Hard to tell if this is a duplicate report or not given the number of similar but different problems.

**Comment by ppedrot** [comment]
I think this is a defect of the syntax allowing to write algebraic universes. We should sanitize the user's input before sending that to unification.

**Comment by SkySkimmer** [comment]
This issue is equivalent to https://github.com/coq/coq/issues/10423 in favour of which I close this.
