### ISSUE TITLE
`make vio2vo` does not do anything

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6691]
#### Version

Git master

#### Operating system
Linux

#### Description of the problem

* `git clone https://gitlab.mpi-sws.org/robbertkrebbers/coq-stdpp.git`
* `make quick -j8`
* `make vio2vo J=8`

The last command returns immediately and does nothing: `ls theories` shows no `.vo` files.
I reproduced this in a smaller project that doesn't mess with `coq_makefile`'s output.

With Coq 8.7, everything still works as expected.

**Comment by RalfJung** [comment]
FWIW, calling `coqc -schedule-vio2vo 2 foobaridontexist.vio` also returns immediately with exit code 0. So yeah, something is very wrong here.

**Comment by ejgallego** [comment]
Fix pending.
