### ISSUE TITLE
`make uninstall` and `make clean` can leave stale finds behind

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6692]
#### Version

All of them

#### Operating system
All of them

#### Description of the problem

`make uninstall` deletes exactly the files that `make install` would create. Unfortunately, this clashes very badly with a workflow like the following:
* `make install`
* `git pull` # renames some files
* `make install`
Now we get strange problems elsewhere because the old versions of the renamed files are still sitting around. We try to fix this with...
* `make uninstall && make install`
... but it doesn't help. We have to manually go find those files and delete them.

`make clean` has a similar issue: It will never remove the old `.vo` files belonging to the now-renamed files. However, Coq will still happily load those files and cause havoc.

One way to fix this would be for `make clean` to delete `*.vo` recursively within the current directory (or to finally put those generated files in a separate directory so that they don't pollute the source folders, and then just delete that directory). For `make uninstall`, this is harder because there's less of a "canonical directory" which has to be cleaned. If the `_CoqProject` has exactly one line like `-Q theories stdpp`, then deleting the `stdpp` folder works just right, but what if there is no or multiple such lines?

**Comment by ejgallego** [comment]
This is actually an issue in coq_makefile, not in Coq's own makefiles. But indeed, there is little we can do to solve this, TTBOMK make doesn't just have the capabilities to proper fix this bug, it is a known limitation.

**Comment by Alizter** [comment]
OK, In which case it is irrelevant what happens in dune IMO. This is still therefore an issue for coq_makefile, if it can be patched or not is another question.

**Comment by Alizter** [comment]
A workaround for this could be to use `git clean -xffdn` to see what will get deleted and `git clean -xffd` to delete it.

**Comment by RalfJung** [comment]
coq_makefile has the concept of a unique "install root", right? So `make uninstall` could clean that root.

But FWIW, I am using opam these days so this is no longer an issue (except of course that opam, too, often doesn't properly clean up, but that is an opam bug: https://github.com/ocaml/opam/issues/4419). @robbertkrebbers still uses `make install` directly AFAIK so he'd know better how much of a problem this is in practice.
