### ISSUE TITLE
native_compute error message when not finding the OCaml compiler should be improved (and not be an anomaly).

### ISSUE THREAD

**Issue by mgttlinger** [coq/coq#6699]
#### Version

> The Coq Proof Assistant, version 8.7.1 (December 2017)
> compiled on Dec 18 2017 21:18:25 with OCaml 4.04.2

#### Operating system

> `Linux 4.9.76 #1-NixOS SMP Wed Jan 10 08:29:55 UTC 2018 x86_64 GNU/Linux`

#### Description of the problem

Below code fails to evaluate in `native_compute` but works fine in `vm_compute`

Produces error:
> Error: Anomaly "Compilation failure."
> Please report at http://coq.inria.fr/bugs/. 

```coq
Section Demo.
  Class P m := {propv : nat -> m}.
  Inductive T := t_p : nat -> T.
  Instance tp : P T := {|propv := t_p|}.

  Parameter p : nat.
  
  Eval vm_compute in (propv 5).
  Eval vm_compute in (propv p).
  Eval native_compute in (propv p). (* compiler error *)
  Eval native_compute in (propv 5). (* compiler error *)
End Demo.
```

**Comment by ppedrot** [comment]
Works for me on master (55b2a4e0c24d691b71256c91ed54e245efce340b) with OCaml 4.04.0+fp.

**Comment by mgttlinger** [comment]
Ohhhh I have a suspicion... What exactly is native compute doing? Does it try to invoke external executables like e.g. an OCAML compiler?

**Comment by ppedrot** [comment]
Indeed, it calls the OCaml compiler.

**Comment by mgttlinger** [comment]
Ok, then this is likely an issue with the nix derivation. Can you point me to where/how/what executables coq tries to invoke so I can get this fixed or open an issue against nix?

**Comment by ppedrot** [comment]
The compiler is called in `kernel/nativecode.ml` and relies on the `ocamlfind` command that has been generated at configure time and is stored in the file `config/coq_config.ml`.

**Comment by mgttlinger** [comment]
Also the error message could maybe be improved here, saying "executable ... missing" ore something along those lines instead of "Anomaly Failure".

**Comment by mgttlinger** [comment]
Hmmm the executable paths in the generated config look good but I'm fairly certain that this is an issue with the derivation unless coq tries to invoke executables from `$PATH` or with hardcoded path outside of that config so I'm going to open an issue against nix.

**Comment by Zimmi48** [comment]
I agree that the error message is pretty bad.

**Comment by psteckler** [comment]
In fact, Coq prints a warning that the compiler has exited with code 127, which represents "command not found". In PG and PG/xml, that message is quickly overwritten by the anomaly message. In CoqIDE, both are visible.

**Comment by Zimmi48** [comment]
Yes, but exit code 127 is cryptic to users ;-)

**Comment by siddharthist** [comment]
I also encountered this issue with Nix+Coq 8.8:
```
$ coqc --version
The Coq Proof Assistant, version 8.8.1 (July 2018)
compiled on Jul 4 2018 0:02:52 with OCaml 4.05.0
```
```
COQC Patch.v
File "./Patch.v", line 158, characters 6-64:
Warning: Native compiler exited with status 127
[native-compiler-failed,native-compiler]
File "./Patch.v", line 158, characters 6-64:
Error: Anomaly "Compilation failure."
Please report at http://coq.inria.fr/bugs/.
```

**Comment by Zimmi48** [comment]
@siddharthist Note the workaround given by @vbgl in https://github.com/NixOS/nixpkgs/issues/34657#issuecomment-363536327 (`nix-shell -p coq coq.ocaml`).

**Comment by ejgallego** [comment]
In my opinion the native compiler should abstract away all the functionality it needs from Ocaml into a module, and we will move that out of the kernel to a support library. [Maybe coqfind?]
