### ISSUE TITLE
Typeclass resolution does not properly run on goal of a tactic-in-term

### ISSUE THREAD

**Issue by tchajed** [coq/coq#6701]
#### Version

The Coq Proof Assistant, version 8.8+alpha (February 2018)
compiled on Feb 1 2018 11:34:36 with OCaml 4.06.0

#### Operating system

OS X 10.11

#### Description of the problem

Typeclass resolution does not run to finish typing the goal of a tactic-in-term, resulting in the tactic seeing an incomplete goal.

```coq
Ltac pgoal :=
  match goal with
  | |- ?g => idtac g
  end.

(** fail if there are evars in the goal *)
Ltac no_evars :=
  lazymatch goal with
  | |- ?g => try (has_evar g; fail 2 "has evars")
  end.

Class subsetable A :=
  { subset : A -> Prop }.

Instance units : subsetable unit :=
  {| subset := fun _ => True; |}.

Set Printing Implicit.
Set Typeclasses Debug.

Goal False.
  (* typeclass resolution fills in the single instance *)
  assert {x | subset x} as H by
        (pgoal; no_evars; admit).
  (* the goal type has uninstantiated typeclasses (and hence [no_evars] fails) *)
  Fail let x := constr:(ltac:(pgoal; no_evars) :
                          {x | subset x}) in
       idtac x.
```

**Comment by tchajed** [comment]
Thanks to @anishathalye for helping to reduce this bug and identify the underlying issue!

**Comment by Zimmi48** [comment]
The bug is present since 8.5.
The use of `ltac:()` in the `by` clause of `assert` is a bit weird. Why is this accepted and why do you need it?

**Comment by tchajed** [comment]
That's a copy-paste oddity; I think this just ensures that that term is parsed as a tactic and isn't an issue. It's unnecessary for this example, where I just wanted to illustrate another way to do something similar that does work.

**Comment by SkySkimmer** [comment]
I think this is the intended behaviour.
