### ISSUE TITLE
Ltac match on `{x & ?P}` fails to parse

### ISSUE THREAD

**Issue by anishathalye** [coq/coq#6709]
#### Version

Coq 8.7.1

#### Operating system

macOS 10.13.2 (High Sierra)

#### Description of the problem

An Ltac match on `{x & ?P}` fails to parse. This issue is demonstrated in the following example:

```coq
Ltac ex_1 :=
  match goal with
  | |- {x : _ | ?P} => idtac
  end.

Ltac ex_2 :=
  match goal with
  | |- {x | ?P} => idtac
  end.

Ltac ex_3 :=
  match goal with
  | |- {x : _ & ?P} => idtac
  end.

(*
Ltac ex_4 :=
  match goal with
  | |- {x & ?P} => idtac
  end.
*)

(*

ex_4 fails to parse, with the following error message:

Error:
Syntax error: ':' or '|' or '}' expected after [constr:operconstr level 99] (in [constr:operconstr]).

*)
```

**Comment by tchajed** [comment]
This actually doesn't have anything to do with Ltac - there simply isn't a notation `{x & P}` for `sigT P` in the standard library, even though there is `{x | P}` for `sig`.

I'm checking to see if adding the notation breaks anything; I'll submit a PR if it seems to work.
