### ISSUE TITLE
`Set Typeclasses Unique Instances` does not seem to be working

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#6714]
#### Version

8.7.1

#### Operating system

Linux

#### Description of the problem

According to the manual, `Set Typeclasses Unique Instances` makes sure that "when a solution to the typeclass goal of this class is found, we never backtrack on it, assuming that it is canonical". As the example below shows, I do not think it's actually doing that.

```
Set Typeclasses Unique Instances.

Class Foo (x y : bool) := {}.
Class Bar (x y : bool) := {}.
Class Bax (x : bool) := {}.

Instance bar_1 : Bar true false.
Instance bar_2 : Bar true true.

Instance bax_1 : Bax false.

Instance foo x y : Bar x y -> Bax y -> Foo x y.

Typeclasses eauto := debug.

Check (_ : Foo true _).
```

According to the type class debug output, this will:

1. First use the instance `foo`, which gives rise to goals `Bar true ?x` and `Bax ?x`
2. Solve `Bar true ?x` using `bar_2`, thus unifying `?x` with `false`.
3. Try to solve `Bax false`
4. Since that fails, it backtracks to (2) by solving `Bar true ?x` again using another instance.

When `Set Typeclasses Unique Instances` is enabled, it should not backtrack.

**Comment by robbertkrebbers** [comment]
FWIW: I think an option to control backtracking would be super useful. I recently noticed that some failing tactics in Iris are excessively slow because Coq is backtracking like crazy, see https://gitlab.mpi-sws.org/FP/iris-coq/merge_requests/112

As a temporary workaround I came up with the following hack:

```coq
(** The type class [NoBackTrack P] can be used to establish [P] without ever
backtracking on the instance of [P] that has been found. Backtracking may
normally happen when [P] contains evars that could be instanciated in different
ways depending on which instance is picked, and type class search somewhere else
depends on this evar.

The proper way of handling this would be by setting Coq's option
`Typeclasses Unique Instances`. However, this option seems to be broken, see Coq
issue #6714.

See https://gitlab.mpi-sws.org/FP/iris-coq/merge_requests/112 for a rationale
of this type class. *)
Class NoBackTrack (P : Prop) := { no_backtrack : P }.
Hint Extern 0 (NoBackTrack _) => constructor; apply _ : typeclass_instances.
```

**Comment by mattam82** [comment]
The semantics is maybe not what you want indeed, it's supposed to not backtrack on evar-free goals only, hence the decision to backtrack on the application of bar_2.

**Comment by maximedenes** [comment]
@mattam82 Can you say a bit more about what motivated such semantics?

**Comment by mattam82** [comment]
Ignorance of that use case I suppose :) It seems this could be linked to mode declarations.
Here the bar_1 and bar_2 are overlapping on their first argument and disjoint on the second one. The idea of Unique Instances was to say: I know I'm going to make non-overlapping instances so don't even try other instances once one has matched, as no other will apply.

**Comment by robbertkrebbers** [comment]
> Ignorance of that use case I suppose :) It seems this could be linked to mode declarations.
Linking this to mode declarations would be a great idea. Basically, often we have type classes like:

```coq
C (input : A) (output : B)
```

Using the current mode declarations, we can express which parameters are the inputs and outputs. But what we really want is to also specify which outputs may be non-deterministic, i.e. whenever a subsequent class depends on that output, whether it should backtrack in case of failure.

> The idea of Unique Instances was to say: I know I'm going to make non-overlapping instances so don't even try other instances once one has matched, as no other will apply.
Do you have any use case of that?

**Comment by mattam82** [comment]
> Using the current mode declarations, we can express which parameters are the inputs and outputs. But what we really want is to also specify which outputs may be non-deterministic, i.e. whenever a subsequent class depends on that output, whether it should backtrack in case of failure.

So we'd need a new modality on modes to express that? We'd have "-" for single output (functional dependency basically, we might even want to specify subsets of inputs here as in Haskell fundeps) and "*" for non-deterministic output?

> > The idea of Unique Instances was to say: I know I'm going to make non-overlapping instances so don't even try other instances once one has matched, as no other will apply.

> Do you have any use case of that?

Actually I should refine this to "the non-overlapping instances I will define are benign":
typically supporting both `Eq A -> Eq (list A)` and a specific `Eq (list nat)` instance avoiding backtracking on `Eq (list nat)` goals.

**Comment by maximedenes** [comment]
Where would the specific instance on `Eq (list nat)` come from in this use case?

**Comment by mattam82** [comment]
The user woud have written it. Examples like this are in MathClasses

**Comment by maximedenes** [comment]
Sure, but in that specific example, it looks like an error to have defined the specific instance when a more general one was available. Or maybe there were motivations to do so, but that may be an XY problem then.

**Comment by mattam82** [comment]
The motivation is to use an observationally equivalent but more efficient version of an operation AFAIR

**Comment by maximedenes** [comment]
But then, the chosen solution seems to matter... Doesn't it contradict the spirit of this flag? I.e. what would prevent it from picking the more general but also less efficient version?

**Comment by maximedenes** [comment]
I think it would be worth digging a bit in the motivation use cases, to see if we want to resolve this issue by modifying the semantics of this flag, or by adding a new one.

**Comment by maximedenes** [comment]
> I.e. what would prevent it from picking the more general but also less efficient version?

I guess you can use priorities for that.

**Comment by mattam82** [comment]
In that case it was using priorities (even implicitely, as the specific instance has no premise compared to the general one), but this doesn't in itself prevent backtracking.

**Comment by mattam82** [comment]
Maybe there's a more explicit way to specify this indeed.

**Comment by maximedenes** [comment]
@RalfJung @robbertkrebbers so what should I do about this? I guess we could make the documentation of this option clearer. As for your use case, do you need #6285, #7661, something else?

**Comment by robbertkrebbers** [comment]
I'm not very convinced that the current `Set Typeclasses Unique Instances` is useful, but regardless, it would be good if the documentation were improved.

https://github.com/coq/coq/pull/7661 sounds like a something that's helpful. It would be nice if one could also say that all instances of a certain type class are non-backtracking, instead of one having to say that for each individual instance.

**Comment by maximedenes** [comment]
> I'm not very convinced that the current `Set Typeclasses Unique Instances` is useful

You mean we should extend it to also cover scenario 1 above?

**Comment by maximedenes** [comment]
@robbertkrebbers ping

**Comment by robbertkrebbers** [comment]
Any idea if #7661 covers scenario 1? If so, I think I would be happy.

Nit: If it does, it appears we have to say `NonBacktracking` for each instance, which I why I said it would be nice to have a flag at the level of a class.

**Comment by RalfJung** [comment]
There was some discussion earlier in this thread to use `Hint Mode` declarations to determine which "outputs" can be backtraced on. That also seems like a nice option?

**Comment by robbertkrebbers** [comment]
An interesting observation related to @RalfJung's previous point:

- `Hint Mode` is currently at the the level of classes.
- `NonBacktracking` is currently at the level of instances.

Arguably, you want to be able to have both of these at both the level of classes (where you can give the `Hint Mode` and backtracking behavior for all instances of that class) and at the level of individual instances (to overwrite the class-level behavior).

**Comment by SkySkimmer** [comment]
@robbertkrebbers does this match what you mean for scenario 1? (where `Instance foo : C ! priority` is the syntax for a non-backtracking instance, and `Type foo` is like `Check foo` but forces all evars to be resolved)
~~~coq
Class E (a b : nat) := e{}.

Class C (a b : nat) := c{}.

Class D (a:nat) := d{}.

Instance d2 : D 2 := {}.

Instance c2 : C 0 2 | 10 := {}.

Instance exy (a b:nat) `{C a b} `{D b} : E a b := {}.

Module Back.
  Instance c0 : C 0 0 | 1 := {}.
  Type _ : E _ _.
End Back.

Module NoBack.
  Type _ : E _ _.
  Instance c0 : C 0 0 ! 1 := {}.
  Fail Type _ : E _ _.
  Type _ : C 0 0.
End NoBack.
~~~
I got it to work based on #7661 (and added it to its test suite)

**Comment by SkySkimmer** [comment]
@robbertkrebbers ping

**Comment by robbertkrebbers** [comment]
@SkySkimmer This example seems to make a lot of sense. I will try #7661 on Iris once it's rebased on Coq master.

**Comment by SkySkimmer** [comment]
Rebased.

**Comment by robbertkrebbers** [comment]
Awesome. I will try this out after the POPL deadline is passed.

**Comment by maximedenes** [comment]
@robbertkrebbers Would you mind giving it a try, so that we can schedule some work on this if required? Thanks!

**Comment by robbertkrebbers** [comment]
Sorry for the very delayed response. Deadlines, switching jobs, trying to buy a house, and vacation caught up (and are still catching up) on me.

I tried to implement to `TCNoBackTrack` class from std++ using #7661, and don't think I get the intended behavior. See https://gitlab.mpi-sws.org/iris/stdpp/-/blob/master/theories/base.v#L58 for the description of that type class, and its current hacky implementation.

```coq
Class TCNoBackTrack (P : Prop) := make_tc_no_backtrack { tc_no_backtrack : P }.
Existing Instance make_tc_no_backtrack ! 0.

Class C (n : nat) := {}.
Instance c_1 : C 1 | 10 := {}.
Instance c_2 : C 2 | 1 := {}.

Class D (n : nat) := {}.
Instance d_1 : D 1 := {}.

Class E (n : nat) := {}.
Instance foo {n} : TCNoBackTrack (C n) → D n → E n := {}.

Typeclasses eauto := debug.
Check (_ : E _).

(*

1: looking for (E ?n) with backtracking
1.1: simple apply @foo on (E ?n), 2 subgoal(s)
1.1-1 : (TCNoBackTrack (C ?n))
1.1-1: looking for (TCNoBackTrack (C ?n)) with backtracking
1.1-1.1: simple apply make_tc_no_backtrack on (TCNoBackTrack (C ?n)), 1 subgoal(s)
1.1-1.1-1 : (C ?n)
1.1-1.1-1: looking for (C ?n) with backtracking
1.1-1.1-1.1: exact c_2 on (C ?n), 0 subgoal(s)
1.1-2 : (D 2)
1.1-2: looking for (D 2) without backtracking
1.1-2: no match for (D 2), 0 possibilities
1.1-1.1-1.2: exact c_1 on (C ?n), 0 subgoal(s)
1.1-2 : (D 1)
1.1-2: looking for (D 1) without backtracking
1.1-2.1: exact d_1 on (D 1), 0 subgoal(s)
Finished run 1 of resolution.
foo {| tc_no_backtrack := c_1 |} d_1 : E 1
     : E 1
*)
```

We see here that it first finds `c_2`, but then still backtracks to find `c_1`. I would expect that the `! 0` in the instance for `make_tc_no_backtrack` should prevent that.

**Comment by SkySkimmer** [comment]
OK that sounds more like cuts (https://github.com/coq/coq/pull/6285) than non backtracking hints, let's see if we can revive that PR.

**Comment by SkySkimmer** [comment]
@robbertkrebbers I'm confused about the goal of this issue, eg what's unsatisfactory about your current TCNoBackTrack implementation through Hint Extern.

Maybe you're looking for a way to declare a class such that it's always searched as though it were wrapped in TCNoBackTrack? ie being able to write `Magic Command C. Instance foo {n} : C n -> D n -> E n := {}.` and getting the same result as `Instance foo {n} : TCNoBackTrack (C n) -> D n -> E n := {}.`

**Comment by robbertkrebbers** [comment]
> @robbertkrebbers I'm confused about the goal of this issue, eg what's unsatisfactory about your current TCNoBackTrack implementation through Hint Extern.

It starts a new invocation of type class search, so the log of `Typeclasses eauto := debug` becomes a big mess.

**Comment by robbertkrebbers** [comment]
But do I understand correctly that the idea of #7661 is that backtracking points are removed for just the `NoBackTracking` nodes in the proof search tree. Even if the proof search for a `NoBackTracking` node succeeds, it still might backtrack on its children?

**Comment by SkySkimmer** [comment]
>But do I understand correctly that the idea of #7661 is that backtracking points are removed for just the NoBackTracking nodes in the proof search tree. So, even if the proof search for a NoBackTracking node succeeds, it still might backtrack on its children?

yes

**Comment by SkySkimmer** [comment]
>It starts a new invocation of type class search, so the log of Typeclasses eauto := debug becomes a big mess.

#6285 exposes more complicated Hint Extern so doesn't solve this problem. We would need to treat nonbacktracking in a more primitive way, or maybe somehow pass the debug state to subcalls of TC inference.

**Comment by SkySkimmer** [comment]
@robbertkrebbers 
I feel we should have a live talk about how this issue should be solved, probably involving @mattam82 
Would that be possible for the two of you?

**Comment by robbertkrebbers** [comment]
> @robbertkrebbers
> I feel we should have a live talk about how this issue should be solved, probably involving @mattam82
> Would that be possible for the two of you?

I would be happy to have such a chat. Preferably after the PLDI deadline, 20 Nov, then my availability is quite flexible.

**Comment by Blaisorblade** [comment]
FWIW, a problem with `TCNoBacktrack` is that it's super-fragile.

1. _If_ a class `C' args` has any fallback instances, then all users must use `C args := TCNoBacktrack (C' args)`. Should you declare `Instance : C args.`, you'd break the scheme.
2. This usually is _not_ a detectable problem — until you add _some_ goal using classes `C'` _and_ `D`, where searches for `D` can fail and cause backtracking on `C'`.
3. Are priorities really necessary? They come up when translating into typeclasses pretty basic programs — such as matches with fallbacks.
```
Variant flag := A | B | C.
match (x : flag) with
| A => 1
| _ => 0
end.
```

I guess Prolog-style cuts would subsume this?
