### ISSUE TITLE
Error in manual with specialize_eqs

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#6717]
In the online manual:

https://coq.inria.fr/distrib/current/refman/tactic-examples.html

search for `specialize_eqs` and you will find an example with what seems to be an unexpected error:

```
Coq <   specialize_eqs IHterm.
Toplevel input, characters 2-23:
>   specialize_eqs IHterm.
>   ^^^^^^^^^^^^^^^^^^^^^
Error:
Ltac call to "specialize_eqs (var)" failed.
Specialization not allowed on dependent hypotheses
```

Noticed by @Chobbes when porting to Sphinx.

Can a tactic expert confirm if this is an unexpected error?

**Comment by Zimmi48** [comment]
This appears to be a regression between 8.5pl3 and 8.6beta1:
- https://coq.inria.fr/distrib/8.5pl3/refman/Reference-Manual012.html
- https://coq.inria.fr/distrib/8.6beta1/refman/Reference-Manual012.html

**Comment by mattam82** [comment]
Yes it's unexpected, IHterm is not even dependent.

**Comment by mattam82** [comment]
Apparently concurrent labelling does not take the "lub" of labels on github :)

**Comment by maximedenes** [comment]
@mattam82 please update the milestone to reflect your current schedule on this.

**Comment by maximedenes** [comment]
@mattam82 ping

**Comment by maximedenes** [comment]
The milestone never got updated so removing it. @mattam82 please add one that reflects your schedule.

**Comment by Zimmi48** [comment]
This has been fixed. However, there is now no mention of `specialize_eqs` in the reference manual. See #9706.
