### ISSUE TITLE
Automate benchmarking

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6727]
We should have a bot that is triggered by the use of the `needs: benchmark` flag. When it sees it, it launches a bench for the corresponding PR. When the bench finishes, it posts the results as a comment and removes the flag.

**Comment by ejgallego** [comment]
That's cool!

**Comment by Zimmi48** [comment]
Moved to coq/bot#8.

**Comment by ejgallego** [comment]
I think we will need some coq support for this so maybe a tracker issue should be kept around, but indeed this way also works.
