### ISSUE TITLE
opam init hangs

### ISSUE THREAD

**Issue by jeremydaw** [coq/coq#6746]
#### Operating system

$ uname -a
Linux cecs-042179 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#### Description of the problem
following instructions on https://coq.inria.fr/opam/www/using.html
running opam init -n --comp=4.01.0 -j 2

got output 
[WARNING] /home/users/jeremy/opam-coq.8.6 exists and is not empty
Proceed ? [Y/n] Y
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!

=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Processing: [default: http]
at which point nothing further happened

NB the warning line above didn't happen the first time I had tried this

**Comment by Zimmi48** [comment]
I'm afraid that it's not a problem for us to solve. The Opam issue tracker is there: https://github.com/ocaml/opam/issues. But without more details, I don't think they will be able to help you. Also note that this instructions are actually incorrect as you need OCaml 4.02.3 to install Coq (see https://github.com/coq/www/issues/58).

**Comment by hartmut27** [comment]
I've apt-get purged my opam from ubuntu distribution and reinstalled opam from current binary distribution, this solved the hang problem when doing `opam install xyz` in my case.
