### ISSUE TITLE
Failure in tactic does not print the place the tactic is called

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6750]
#### Version

master

#### Operating system
Linux

#### Description of the problem

For some kinds of tactics failures, Coq prints an error like
```
File "/home/r/Dokumente/Unisachen/iris/coq/theories/proofmode/tactics.v", line 631, characters 47-61:
Error:
Unable to satisfy the following constraints:
In environment:
Λ : language
Σ : gFunctors
irisG0 : irisG Λ Σ
s1, s2 : stuckness
H : s1 ⊑ s2
e : expr Λ
E1, E2 : coPset
HE : E1 ⊆ E2
Φ : val Λ → iProp Σ
Ψ : val Λ → uPredI (iResUR Σ)
v : val Λ
Heqo : to_val e = Some v

?PROP : "sbi"

?H : "BUpd ?PROP"

?H0 : "FUpd ?PROP"

?H1 : "FUpdFacts ?PROP"
```
Can you guess the file and line that actually triggered this error? Right, it's `theories/program_logic/weakestpre.v` line 220. The file and line given by Coq may be on the call stack at this point, not sure.

I have previously tried and failed to get a small example for this, now it happened again in Iris:
* `git clone https://gitlab.mpi-sws.org/FP/iris-coq && cd iris-coq`
* `git checkout ralf/coqbug/ltac-stacktrace`
* `make build-dep && make`

The offending tactic call is `iApply (fupd_mask_mono E1 _)` in `wp_strong_mono`.

**Comment by SkySkimmer** [comment]
This should be fixed since db7a5a4a2d200d5d1d8b2e1aa3056fee2fb12b85  (8.15)
