### ISSUE TITLE
Coq fails to import .v(i)o files created atfer it was started

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#6751]
#### Version

master

#### Operating system
Linux

#### Description of the problem

In ProofGeneral, open a file with some dependencies and run it. PG will compile the dependencies, but Coq still fails to import them.

@ejgallego says this has something to do with a "file cache" or so.

**Comment by ejgallego** [comment]
Indeed it is very likely that I reverted the logic of the `System.trust_file_cache` flag. This flag is supposed to indicate when to recheck the filesystem for a file.

We should have a look to see if the logic is correct when we have a minute.

**Comment by gares** [comment]
Can you prepare a PR @SkySkimmer ? Indeed it seems `batch_mode = not trust_file_cache` while the PR forgets the `not`

**Comment by SkySkimmer** [comment]
OK.

**Comment by ejgallego** [comment]
> it seems batch_mode = not trust_file_cache while the PR forgets the not

Umm, that seems strange, `batch_mode = true` should imply `trust_file_cache = true`.

**Comment by SkySkimmer** [comment]
OK so the logic is inverted at initialization time, not use time.

Gaëtan Gilbert

**Comment by ejgallego** [comment]
Oh indeed, it looks like it.
