### ISSUE TITLE
Anomaly when attempting to generalize a value

### ISSUE THREAD

**Issue by HugoCP** [coq/coq#6774]
#### Version

Coq 8.7.1, with CoqIDE

#### Operating system

Windows 10

#### Description of the problem

I'm messing around with types and i've ran across the following anomaly.
I do not know if the generalization i'm attempting is even possible or not, but from other tests i've done, it seems it isn't.
Rest of the issue is sample code that generates the bug.

```coq

Definition huh (b:bool) := if b then Set else Prop.
Definition lol b: huh b := if b return huh b then nat else True.
Goal (lol true) * unit.
generalize true. (* Fails with Anomaly "Uncaught exception Reduction.NotArity."
Please report at http://coq.inria.fr/bugs/. *)
```

**Comment by herbelin** [comment]
Thanks for reporting. A fix is available as PR#6776.

Note: this concerns a part of the code (template polymorphism) which shall soon be subsumed by another feature (full polymorphism with cumulativity), but still a fix is available in the meantime.
