### ISSUE TITLE
ocamlfind: Package `camlp5.gramlib' not found

### ISSUE THREAD

**Issue by roglo** [coq/coq#6782]
#### Description of the problem

As a developper of Camlp5, I had to update it to make it compatible with ocaml 4.06. I did it, locally. I had to compile and install Num and findlib. Now, compiling Coq trunk, I get, after some compilation the message:

ocamlfind: Package `camlp5.gramlib' not found

What is that?

**Comment by maximedenes** [comment]
Did you register your local copy of camlp5 for ocamlfind?

**Comment by roglo** [comment]
No, why?

**Comment by maximedenes** [comment]
Because that seems to be the source of the error above.

**Comment by roglo** [comment]
So I need to know how ocamlfind works to compile coq when I make changes in Camlp5?

**Comment by maximedenes** [comment]
Yes.

**Comment by Zimmi48** [comment]
Since the call to `ocamlfind` will be in Coq makefile, the best way is probably to extend some environment variable (maybe `$OCAMLPATH`) so that `ocamlfind` can find where to look for `camlp5`.

**Comment by maximedenes** [comment]
I don't think there's an issue on Coq's side, so I'm going to close this. Feel free to reopen if you do see a bug.

**Comment by roglo** [comment]
I do
  OCAMLPATH=$(dirname $(which camlp5))/../lib/ocaml/camlp5 make
But I still have the message
COQMKTOP -o bin/coqtop
ocamlfind: Package `camlp5.gramlib' not found

**Comment by ejgallego** [comment]
LIkely the issue is that you don't point `OCAMLPATH` to the location where the correct `META` file is. You `camlp5` working dir likely has not generated the `META` file from `META.tpl`

I know is a bit annoying, but we are moving to managing the few dependencies with `ocamlfind`, tool which is standard and has been around for a while. Once you get used to it the benefits outweigh the annoyance. Note also that you can configure a permanent `OCAMLPATH` in `findlib.conf`.

**Comment by ejgallego** [comment]
Indeed I think that if @roglo is using `master`, then the current `INSTALL` instructions should be improved. In particular we should specify that Coq needs now both `camlp5` and `num` correctly registered with `ocamlfind` [and provide some hints on how to do so].

**Comment by Zimmi48** [comment]
Yes, let's reopen as a documentation bug then.

**Comment by ejgallego** [comment]
Makes sense. Reminder, both `CHANGES` and `INSTALL` should likely be updated.

**Comment by mikeshulman** [comment]
What is the status of this issue?  I got this same error message after the HoTT Coq library updated to a recent version of Coq and I tried to compile the latter.  Is there somewhere that I can find instructions for fixing it?

**Comment by ejgallego** [comment]
@mikeshulman what's your operating system? How did you install OCaml?

**Comment by ejgallego** [comment]
But basically you need to properly install camlp5 and register with the `findlib` OCaml package manager. Usually this is taken care of by your distribution.

**Comment by mikeshulman** [comment]
Ubuntu 16.04.4 LTS; campl5 installed through apt.

**Comment by mikeshulman** [comment]
Ah, I think I figured it out.  My ocaml was installed via opam, but my camlp5 was installed via apt.  Installing camlp5 via opam instead seems to have fixed the problem.

Now I have another problem, though... but at least this one is gone.

**Comment by ejgallego** [comment]
> My ocaml was installed via opam, but my camlp5 was installed via apt

Yeah I think these live then in different namespaces. Note tho that if you have installed camlp5 using `apt` then you also have an OCaml "system" compiler.

I do recommend one or the other, that is to say, either install everything via `apt`, or remove all the ocaml packages [but opam] from `apt` and use OPAM.

**Comment by mikeshulman** [comment]
> if you have installed camlp5 using apt then you also have an OCaml "system" compiler.

In my case this was true, but Ubuntu did let me uninstall the `ocaml` package without uninstalling the `camlp5` package.

**Comment by ejgallego** [comment]
Maybe it is because the OCaml compiler is in `ocaml-base-nox` ?

**Comment by mikeshulman** [comment]
Yes, probably.  (-:O
