### ISSUE TITLE
coqchk should specify where it found ill-typed terms, and finish with a newline

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6797]
#### Version

8.8+alpha

#### Description of the problem

When trying to track down https://github.com/coq/coq/pull/734#issuecomment-363485311 and passing a hundred or so `.vo` files to `coqchk`, I see
```
====== ill-typed term ====
application head= Cons((HoTT.Basics.Overture.ap),Var(1) Var(1))
head type=
  (A:Type(Var(1)))
   (B:Type(Var(1)))
    (f:(#2->#2))
...
is not convertible with
...
====== universes ====
Var(1) = Var(0)
Var(0) < Var(2)
Set <= Var(2)
    <= Var(1)
    <= Var(0)
Prop < Set
Fatal Error: Type error:
CantApplyBadType at argument 6Makefile:915: recipe for target 'validate' failed
make: *** [validate] Error 1
```

There are two issues with this:
1. I don't know which .vo file / constant the ill-typed term showed up in.  I'd like `coqchk` to give me the kernel name of the `Definition` that is ill-typed.
2. There is no trailing newline, which makes the output a bit hard to read

**Comment by ejgallego** [comment]
Umm, `fatal_error` does indeed print a newline:
```ocaml
let fatal_error info anomaly =
  flush_all (); Format.eprintf "@[Fatal Error: @[%a@]@]@\n%!" Pp.pp_with info; flush_all ();
  exit (if anomaly then 129 else 1)
```
Maybe I'm misunderstanding you?

Anyways, it should be a matter of tweaking the above function.

**Comment by ejgallego** [comment]
Instead of modifying the core error code, I suggest you use the verbose flag.

It should already provide you with information about the `.vo` file (see `check_one_lib`). Similarly, `check_constant_declaration` will print the name of the checked definition.

**Comment by JasonGross** [comment]
`-verbose` is not a valid option, but I see now that if I don't pass `-silent` (as the `validate` target does), then the last line of `checking cst:` does indeed print the name of the function.  I'll open a separate issue for newlines
