### ISSUE TITLE
Anomaly "cvtac's exception: "Anomaly: rewrite rule not an application""

### ISSUE THREAD

**Issue by akr** [coq/coq#6804]
#### Version

The Coq Proof Assistant, version 8.7.0 (November 2017)
compiled on Nov 3 2017 20:38:16 with OCaml 4.05.0

#### Operating system

Debian GNU/Linux 9.3 (stretch)

#### Description of the problem

```
From mathcomp Require Import ssreflect.
Definition f (x : unit) := True.
Goal True.
rewrite (_ : True = f _).
```

The above code produces following error.

```
Anomaly "cvtac's exception: "Anomaly: rewrite rule not an application"" 
Please report at http://coq.inria.fr/bugs/.
```

**Comment by Zimmi48** [comment]
Note that as of 8.7, you can also do:

```coq
From Coq Require Import ssreflect.
Definition f (x : unit) := True.
Goal True.
rewrite (_ : True = f _).
```

which also triggers the anomaly and qualifies this as an actual Coq bug.

**Comment by Zimmi48** [comment]
The faulty line is here: https://github.com/coq/coq/blob/aec63ba9c8f6840d98ba731640a786138d836343/plugins/ssr/ssrequality.ml#L376

Shouldn't this just be turned into a user-error?

**Comment by LasseBlaauwbroek** [comment]
Additional testscases:
```
From Coq Require Import ssreflect.
Definition f (x : unit) := True.
Goal exists (x : unit), forall (y : True = f x), True.
eexists ?[x]. intros.
Succeed rewrite y.
Succeed rewrite (y : _).
Succeed rewrite (y : True = _).
Succeed rewrite (y : True = f ?x).
rewrite (y : True = f _).
```
