### ISSUE TITLE
Update dev/ci/README.md to reflect current situation

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6807]
- [x] The current documentation for CI at dev/ci/README.md should be updated to reflect the current situation with CircleCI and Travis.
- [x] Reference to CI in CONTRIBUTING should probably be made platform-agnostic.
- [x] https://github.com/coq/coq/wiki/Jenkins should be merged into or at least linked from the README.
- [ ] Document macOS / Windows runners.
- [x] Update dev/ci/docker/README.md to reflect the current situation.

I'm assigning to myself not to forget about it but feel free to take over.

**Comment by anton-trunov** [comment]
It is probably worth mentioning a project with dependencies (like SSReflect) as an example in `dev/ci/README.md`.

**Comment by ejgallego** [comment]
Documentation about the windows runners and INRIA cloudstack is also missing.

**Comment by ejgallego** [comment]
IMHO this looks pretty good, I dunno if some small change would be needed, but we are almost done here.

The future Azure setup should be documented properly.

**Comment by ejgallego** [comment]
> * 
> * [ ]  https://github.com/coq/coq/wiki/Jenkins should be merged into or at least linked from the README.

Jenkins is documented in `CONTRIBUTING`. I dunno what if we should add more.

**Comment by Zimmi48** [comment]
Indeed, if you are happy with this setup, I am happy too.
