### ISSUE TITLE
coq-commits-owner@lists.gforge.inria.fr bounces to contributors

### ISSUE THREAD

**Issue by nomeata** [coq/coq#6810]
This is a infrastructure bug: When a a pull request is merged, something sends commit messages to `coq-commits@lists.gforge.inria.fr` with the author as the sender, but these are rejected, and the author gets a reject message like
```
Vous n'êtes pas autorisé à envoyer des messages sur cette liste,
votre message a été automatiquement rejeté. Si vous pensez que
votre message a été rejeté par erreur, veuillez contacter le
gestionnaire de la liste à l'adresse
coq-commits-owner@lists.gforge.inria.fr.
```

Presumably this is a misconfiguration and the mailing list should accept all commit notification mails, independent of who authored the git commit.

**Comment by Zimmi48** [comment]
Absolutely, this is a misconfiguration. But last time that this was discussed it was decided instead that this mailing list served no purpose anymore and that it should just be killed. Thank you for raising attention on this topic!

**Comment by ejgallego** [comment]
@Zimmi48 did we decide that? I think that some people found value on the list, [myself included]

**Comment by Zimmi48** [comment]
It was discussed informally between @herbelin and @maximedenes, with @letouzey agreeing on the conclusion. Do you want to keep this list? If yes, it should be possible to plug it directly on GitHub instead of depending on the forge and fixing this permission problem at the same time.

**Comment by ejgallego** [comment]
The list is convenient to me as it provides a linear stream of commits so it is easy to see what is going into to master in chronological merging time. That being said, I'd be happy with any other solution.

Maybe the easiest fix is to make the git commit hook to properly set the sender? [A 1 minute operation]

**Comment by Zimmi48** [comment]
> The list is convenient to me as it provides a linear stream of commits so it is easy to see what is going into to master in chronological merging time.

If it's useful to you, then it should be kept.

> Maybe the easiest fix is to make the git commit hook to properly set the sender? [A 1 minute operation]

That's one solution. I guess that's @letouzey who has access to this commit hook. Maybe also @maximedenes and other people with access to the server.
Another solution would be to remove this hook and set it up from GitHub. The address to set a e-mail hook on GitHub is here: https://github.com/coq/coq/settings/hooks/new?service=email. It requires providing a secret to auto-approve the e-mail. It should be possible for list administrators to produce such secret.

**Comment by letouzey** [comment]
I've updated the git-notifier hook to use `coq-commits@lists.gforge.inria.fr` as sender email. We'll see at the next push if that works well.

PS: No @ejgallego, in whole this kind of task is **not** a 1 minute operation. Please show a little respect to administrative tasks and to the persons trying to perform them well. Please.

**Comment by ejgallego** [comment]
@letouzey take it easy man, relax a bit please <3. Disrespect is only in your mind, that phrase only means that the task should be easy, which **it is**.

Having been a BOFH^W sysadmin myself since _1998_ , I am perfectly well aware of how funny "administrative talks" are.

**Comment by ejgallego** [comment]
And thank you for the `git-notifier` update!

**Comment by Zimmi48** [comment]
Let's close this, then and reopen if the fix didn't work.

**Comment by ejgallego** [comment]
If you think that could be worth it, testing the hook should be possible by calling the `notifier` under the right account and with the right parameters [that is to say, pointing to a commit of someone not in the ML]
