### ISSUE TITLE
[travis] ci-elpi dependencies are broken

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6811]
The Travis target for `ci-elpi` tries to install `ppx_versioned_tool ocamlfind=1.4.1` however:
```
The following dependencies couldn't be met:
  - ppx_tools_versioned -> ocamlfind >= 1.5.0
Your request can't be satisfied:
  - Conflicting version constraints for ocamlfind
```
it seems that someone needs to bump ocamlfind for elpi.

**Comment by Zimmi48** [comment]
@gares Could you acknowledge and fix quickly? Having Travis CI broken is very annoying.

**Comment by gares** [comment]
Is setting `FINDLIB_VER=1.5.0` in `.travis.yml` a viable fix?
I don't know why it worked before (the PR did pass travis right?)

**Comment by ejgallego** [comment]
> Is setting FINDLIB_VER=1.5.0 in .travis.yml a viable fix?

Yes, setting it in the `ci-elpi` line should do the trick. I didn't fix it myself as I don't know what the elpi dependencies are.

**Comment by ejgallego** [comment]
> I don't know why it worked before (the PR did pass Travis right?)

The PR did pass Travis due to older OPAM setups being able to work with the old ocamlib. Now, some ppx OPAM packages have been updated and opam cannot find an installable set of packages anymore.

This is a good example of what having many external dependencies may be like.

[Yeah that's a strange model for someone used to apt :) ]

**Comment by Zimmi48** [comment]
Did it really pass on Travis? I'm not sure because Travis doesn't test this on PR anymore (because it duplicates CircleCI tests).
Anyways, thanks for the fix.

**Comment by ejgallego** [comment]
It did pass on CircleCI, which indeed raises some questions. Is Circle not using the same package constraints than Travis?

Note that my previous comment was wrong and I've corrected it.

**Comment by Zimmi48** [comment]
> Is Circle not using the same package constraints than Travis?

That should be checked indeed.

**Comment by SkySkimmer** [comment]
circle doesn't constrain findlib.

**Comment by Zimmi48** [comment]
It would be better for the two settings to be the same. It's normal to constrain versions when we test compatibility with the versions documented as minimum requirements. However, we should consider removing all version constraints for targets testing external developments.

**Comment by ejgallego** [comment]
grrr I was wrong about my suggestion, opam fails with `no such package ocamlfind.`

The `1.5.0` version also failed, maybe we should tweak the vars so that the dot is only added when it is not the empty string?

**Comment by Zimmi48** [comment]
The way to do it would be to include the dot as part of the environment variable indeed.

**Comment by gares** [comment]
right, I'll try to fix it in my pr
