### ISSUE TITLE
Coercion to Funclass should apply bound scopes to arguments

### ISSUE THREAD

**Issue by jashug** [coq/coq#6813]
#### Version

8.7.0 and 8.8+alpha

#### Description of the problem

```
Context (A B C : Type).
Context (a : A) (b : B) (f : A -> B -> C).
Notation "#" := b : B_scope.
Delimit Scope B_scope with BS.

Fail Arguments a _%B_scope.

Arguments f _ _%B_scope.
Coercion f : A >-> Funclass.

Check (a b).
Fail Check (a #).
Check (a #%BS).

Arguments Scope a [B_scope].
Check (a b).
```

The deprecated `Arguments Scope` command was able to give extra scopes, which were used after coercion to `Funclass`. (and also if the return type became a function after more computation, but that is neither here nor there)
This seems a reasonable feature, but would make more sense to me if the scopes were on the coercion itself.

**Comment by jashug** [comment]
This is used for example in mathcomp:
https://github.com/math-comp/math-comp/blob/master/mathcomp/character/mxrepresentation.v#L290-L296
```
Structure mx_representation G n :=
  MxRepresentation { repr_mx :> gT -> 'M_n; _ : mx_repr G repr_mx }.

Variables (G : {group gT}) (n : nat) (rG : mx_representation G n).
Arguments Scope rG [group_scope].

Lemma repr_mx1 : rG 1 = 1%:M.
```

**Comment by maximedenes** [comment]
You can write: `Arguments a _%B_scope : extra scopes`. The error message should probably mention it.

**Comment by jashug** [comment]
Indeed, that is probably good enough (that option has been documented since this issue was opened).
