### ISSUE TITLE
trying to install coq, [ERROR] No package matches coq.8.7.

### ISSUE THREAD

**Issue by jeremydaw** [coq/coq#6815]
#### Description of the problem

Following instructions at 
https://coq.inria.fr/opam/www/using.html
I find the opam install coq.8.7 step faiils.
Running 
 opam install -vv --debug coq.8.7
I get the following output
00:00.006  SYSTEM                  locking /home/users/jeremy/opam-coq.8.7/lock
00:00.007  STATE                   LOAD-STATE(switch-lock)
00:00.489  CUDF                    Checking version of criteria accepted by the external solver
00:00.766  SYSTEM                  [log-23326-4438d8] (in 0.004s) aspcud -v
00:00.766  CUDF                    Solver is aspcud > 1.9: using latest version criteria
00:00.827  STATE                   Loaded /home/users/jeremy/opam-coq.8.7/state.cache in 0.060s
00:01.166  STATE                   ROOT      : /home/users/jeremy/opam-coq.8.7
00:01.166  STATE                   SWITCH    : 4.02.3
00:01.166  STATE                   COMPILER  : 4.02.3
00:01.166  STATE                   COMPILERS : { 3.07, 3.07+1, 3.07+2, 3.08.0, 3.08.1, 3.08.2, 3.08.3, 3.08.4, 3.09.0, 3.09.1, 3.09.1+metaocaml, 3.09.2, 3.09.3, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.11.2, 3.12.0, 3.12.1, 4.00.0, 4.00.0+debug-runtime, 4.00.0+fp, 4.00.1, 4.00.1+BER, 4.00.1+PIC, 4.00.1+annot, 4.00.1+debug-runtime, 4.00.1+french, 4.00.1+mirage-unix, 4.00.1+mirage-xen, 4.00.1+open-types, 4.00.1+raspberrypi, 4.00.1+short-types, 4.01.0, 4.01.0+32bit, 4.01.0+BER, 4.01.0+PIC, 4.01.0+armv6-freebsd, 4.01.0+fp, 4.01.0+lsb, 4.01.0+musl, 4.01.0+musl+static, 4.01.0+open-types, 4.01.0+profile, 4.02.0, 4.02.0+PIC, 4.02.0+improved-errors, 4.02.0+modular-implicits, 4.02.0+rc1, 4.02.0+trunk, 4.02.1, 4.02.1+32bit, 4.02.1+BER, 4.02.1+PIC, 4.02.1+fp, 4.02.1+modular-implicits-ber, 4.02.1+musl, 4.02.1+musl+static, 4.02.2, 4.02.2+improved-errors, 4.02.2+rc1, 4.02.3, 4.02.3+32bit, 4.02.3+PIC, 4.02.3+buckle-1, 4.02.3+buckle-master, 4.02.3+bytecode-only, 4.02.3+curried-constr, 4.02.3+fp, 4.02.3+musl, 4.02.3+musl+static, 4.02.3+termux, 4.03.0, 4.03.0+32bit, 4.03.0+beta1, 4.03.0+beta1+flambda, 4.03.0+beta1-no-debug, 4.03.0+beta2, 4.03.0+beta2+flambda, 4.03.0+beta2-no-debug, 4.03.0+fPIC, 4.03.0+flambda, 4.03.0+fp, 4.03.0+fp+flambda, 4.03.0+statistical-memprof, 4.03.0+termux, 4.03.0+trunk, 4.03.0+trunk+flambda, 4.03.0+trunk+fp, 4.03.0+trunk+fp+flambda, 4.04.0, 4.04.0+32bit, 4.04.0+BER, 4.04.0+afl, 4.04.0+beta1, 4.04.0+beta1+flambda, 4.04.0+beta2, 4.04.0+beta2+flambda, 4.04.0+bytecode-only, 4.04.0+copatterns, 4.04.0+fPIC, 4.04.0+flambda, 4.04.0+fp, 4.04.0+fp+flambda, 4.04.0+safe-string, 4.04.0+spacetime, 4.04.0+termux, 4.04.0+trunk+forced_lto, 4.04.1, 4.04.1+32bit, 4.04.1+bytecode-only, 4.04.1+fPIC, 4.04.1+flambda, 4.04.1+fp, 4.04.1+fp+flambda, 4.04.1+safe-string, 4.04.1+spacetime, 4.04.2, 4.04.2+32bit, 4.04.2+bytecode-only, 4.04.2+fPIC, 4.04.2+flambda, 4.04.2+fp, 4.04.2+fp+flambda, 4.04.2+safe-string, 4.04.2+spacetime, 4.04.2+statistical-memprof, 4.05.0, 4.05.0+32bit, 4.05.0+afl, 4.05.0+beta1, 4.05.0+beta1+flambda, 4.05.0+beta2, 4.05.0+beta2+flambda, 4.05.0+beta3, 4.05.0+flambda, 4.05.0+lto, 4.05.0+musl+static+flambda, 4.05.0+rc1, 4.05.0+rc1+flambda, 4.05.0+safe-string, 4.05.0+spacetime, 4.05.0+statistical-memprof, 4.05.0+trunk, 4.05.0+trunk+afl, 4.05.0+trunk+flambda, 4.05.0+trunk+fp, 4.05.0+trunk+fp+flambda, 4.05.0+trunk+safe-string, 4.06.0, 4.06.0+32bit, 4.06.0+afl, 4.06.0+beta1, 4.06.0+beta1+afl, 4.06.0+beta1+default-unsafe-string, 4.06.0+beta1+flambda, 4.06.0+beta1+force-safe-string, 4.06.0+beta1+fp, 4.06.0+beta1+fp+flambda, 4.06.0+beta2, 4.06.0+beta2+afl, 4.06.0+beta2+default-unsafe-string, 4.06.0+beta2+flambda, 4.06.0+beta2+force-safe-string, 4.06.0+beta2+fp, 4.06.0+beta2+fp+flambda, 4.06.0+default-unsafe-string, 4.06.0+flambda, 4.06.0+flambda+no-flat-float-array, 4.06.0+force-safe-string, 4.06.0+fp, 4.06.0+fp+flambda, 4.06.0+musl+static+flambda, 4.06.0+rc1, 4.06.0+rc1+afl, 4.06.0+rc1+default-unsafe-string, 4.06.0+rc1+flambda, 4.06.0+rc1+force-safe-string, 4.06.0+rc1+fp, 4.06.0+rc1+fp+flambda, 4.06.0+spacetime, 4.06.0+statistical-memprof, 4.06.1, 4.06.1+afl, 4.06.1+default-unsafe-string, 4.06.1+flambda, 4.06.1+force-safe-string, 4.06.1+fp, 4.06.1+fp+flambda, 4.06.1+musl+static+flambda, 4.06.1+rc1, 4.06.1+rc1+afl, 4.06.1+rc1+default-unsafe-string, 4.06.1+rc1+flambda, 4.06.1+rc1+force-safe-string, 4.06.1+rc1+fp, 4.06.1+rc1+fp+flambda, 4.06.1+rc2, 4.06.1+rc2+afl, 4.06.1+rc2+default-unsafe-string, 4.06.1+rc2+flambda, 4.06.1+rc2+force-safe-string, 4.06.1+rc2+fp, 4.06.1+rc2+fp+flambda, 4.06.1+trunk, 4.06.1+trunk+afl, 4.06.1+trunk+flambda, 4.06.1+trunk+fp, 4.06.1+trunk+fp+flambda, 4.06.1+trunk+safe-string, 4.07.0+trunk, 4.07.0+trunk+afl, 4.07.0+trunk+flambda, 4.07.0+trunk+fp, 4.07.0+trunk+fp+flambda, 4.07.0+trunk+unsafe-string, system }
00:01.166  STATE                   REPOS     : { coq-released, default }
00:01.166  STATE                   PACKAGES  : 8767 packages
00:01.166  STATE                   INSTALLED : { base-bigarray.base, base-ocamlbuild.base, base-threads.base, base-unix.base }
00:01.166  STATE                   ROOTS     : { base-bigarray.base, base-ocamlbuild.base, base-threads.base, base-unix.base }
00:01.166  STATE                   REINSTALL : {}
00:01.166  STATE                   State switch-lock loaded in 0.216s
00:01.222  SYSTEM                  locking /home/users/jeremy/opam-coq.8.7/4.02.3/lock
00:01.222  STATE                   LOAD-STATE(install)
00:01.246  STATE                   Loaded /home/users/jeremy/opam-coq.8.7/state.cache in 0.024s
00:01.607  STATE                   ROOT      : /home/users/jeremy/opam-coq.8.7
00:01.607  STATE                   SWITCH    : 4.02.3
00:01.607  STATE                   COMPILER  : 4.02.3
00:01.607  STATE                   COMPILERS : { 3.07, 3.07+1, 3.07+2, 3.08.0, 3.08.1, 3.08.2, 3.08.3, 3.08.4, 3.09.0, 3.09.1, 3.09.1+metaocaml, 3.09.2, 3.09.3, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.11.2, 3.12.0, 3.12.1, 4.00.0, 4.00.0+debug-runtime, 4.00.0+fp, 4.00.1, 4.00.1+BER, 4.00.1+PIC, 4.00.1+annot, 4.00.1+debug-runtime, 4.00.1+french, 4.00.1+mirage-unix, 4.00.1+mirage-xen, 4.00.1+open-types, 4.00.1+raspberrypi, 4.00.1+short-types, 4.01.0, 4.01.0+32bit, 4.01.0+BER, 4.01.0+PIC, 4.01.0+armv6-freebsd, 4.01.0+fp, 4.01.0+lsb, 4.01.0+musl, 4.01.0+musl+static, 4.01.0+open-types, 4.01.0+profile, 4.02.0, 4.02.0+PIC, 4.02.0+improved-errors, 4.02.0+modular-implicits, 4.02.0+rc1, 4.02.0+trunk, 4.02.1, 4.02.1+32bit, 4.02.1+BER, 4.02.1+PIC, 4.02.1+fp, 4.02.1+modular-implicits-ber, 4.02.1+musl, 4.02.1+musl+static, 4.02.2, 4.02.2+improved-errors, 4.02.2+rc1, 4.02.3, 4.02.3+32bit, 4.02.3+PIC, 4.02.3+buckle-1, 4.02.3+buckle-master, 4.02.3+bytecode-only, 4.02.3+curried-constr, 4.02.3+fp, 4.02.3+musl, 4.02.3+musl+static, 4.02.3+termux, 4.03.0, 4.03.0+32bit, 4.03.0+beta1, 4.03.0+beta1+flambda, 4.03.0+beta1-no-debug, 4.03.0+beta2, 4.03.0+beta2+flambda, 4.03.0+beta2-no-debug, 4.03.0+fPIC, 4.03.0+flambda, 4.03.0+fp, 4.03.0+fp+flambda, 4.03.0+statistical-memprof, 4.03.0+termux, 4.03.0+trunk, 4.03.0+trunk+flambda, 4.03.0+trunk+fp, 4.03.0+trunk+fp+flambda, 4.04.0, 4.04.0+32bit, 4.04.0+BER, 4.04.0+afl, 4.04.0+beta1, 4.04.0+beta1+flambda, 4.04.0+beta2, 4.04.0+beta2+flambda, 4.04.0+bytecode-only, 4.04.0+copatterns, 4.04.0+fPIC, 4.04.0+flambda, 4.04.0+fp, 4.04.0+fp+flambda, 4.04.0+safe-string, 4.04.0+spacetime, 4.04.0+termux, 4.04.0+trunk+forced_lto, 4.04.1, 4.04.1+32bit, 4.04.1+bytecode-only, 4.04.1+fPIC, 4.04.1+flambda, 4.04.1+fp, 4.04.1+fp+flambda, 4.04.1+safe-string, 4.04.1+spacetime, 4.04.2, 4.04.2+32bit, 4.04.2+bytecode-only, 4.04.2+fPIC, 4.04.2+flambda, 4.04.2+fp, 4.04.2+fp+flambda, 4.04.2+safe-string, 4.04.2+spacetime, 4.04.2+statistical-memprof, 4.05.0, 4.05.0+32bit, 4.05.0+afl, 4.05.0+beta1, 4.05.0+beta1+flambda, 4.05.0+beta2, 4.05.0+beta2+flambda, 4.05.0+beta3, 4.05.0+flambda, 4.05.0+lto, 4.05.0+musl+static+flambda, 4.05.0+rc1, 4.05.0+rc1+flambda, 4.05.0+safe-string, 4.05.0+spacetime, 4.05.0+statistical-memprof, 4.05.0+trunk, 4.05.0+trunk+afl, 4.05.0+trunk+flambda, 4.05.0+trunk+fp, 4.05.0+trunk+fp+flambda, 4.05.0+trunk+safe-string, 4.06.0, 4.06.0+32bit, 4.06.0+afl, 4.06.0+beta1, 4.06.0+beta1+afl, 4.06.0+beta1+default-unsafe-string, 4.06.0+beta1+flambda, 4.06.0+beta1+force-safe-string, 4.06.0+beta1+fp, 4.06.0+beta1+fp+flambda, 4.06.0+beta2, 4.06.0+beta2+afl, 4.06.0+beta2+default-unsafe-string, 4.06.0+beta2+flambda, 4.06.0+beta2+force-safe-string, 4.06.0+beta2+fp, 4.06.0+beta2+fp+flambda, 4.06.0+default-unsafe-string, 4.06.0+flambda, 4.06.0+flambda+no-flat-float-array, 4.06.0+force-safe-string, 4.06.0+fp, 4.06.0+fp+flambda, 4.06.0+musl+static+flambda, 4.06.0+rc1, 4.06.0+rc1+afl, 4.06.0+rc1+default-unsafe-string, 4.06.0+rc1+flambda, 4.06.0+rc1+force-safe-string, 4.06.0+rc1+fp, 4.06.0+rc1+fp+flambda, 4.06.0+spacetime, 4.06.0+statistical-memprof, 4.06.1, 4.06.1+afl, 4.06.1+default-unsafe-string, 4.06.1+flambda, 4.06.1+force-safe-string, 4.06.1+fp, 4.06.1+fp+flambda, 4.06.1+musl+static+flambda, 4.06.1+rc1, 4.06.1+rc1+afl, 4.06.1+rc1+default-unsafe-string, 4.06.1+rc1+flambda, 4.06.1+rc1+force-safe-string, 4.06.1+rc1+fp, 4.06.1+rc1+fp+flambda, 4.06.1+rc2, 4.06.1+rc2+afl, 4.06.1+rc2+default-unsafe-string, 4.06.1+rc2+flambda, 4.06.1+rc2+force-safe-string, 4.06.1+rc2+fp, 4.06.1+rc2+fp+flambda, 4.06.1+trunk, 4.06.1+trunk+afl, 4.06.1+trunk+flambda, 4.06.1+trunk+fp, 4.06.1+trunk+fp+flambda, 4.06.1+trunk+safe-string, 4.07.0+trunk, 4.07.0+trunk+afl, 4.07.0+trunk+flambda, 4.07.0+trunk+fp, 4.07.0+trunk+fp+flambda, 4.07.0+trunk+unsafe-string, system }
00:01.608  STATE                   REPOS     : { coq-released, default }
00:01.608  STATE                   PACKAGES  : 8767 packages
00:01.608  STATE                   INSTALLED : { base-bigarray.base, base-ocamlbuild.base, base-threads.base, base-unix.base }
00:01.608  STATE                   ROOTS     : { base-bigarray.base, base-ocamlbuild.base, base-threads.base, base-unix.base }
00:01.608  STATE                   REINSTALL : {}
00:01.608  STATE                   State install loaded in 0.172s
00:01.664  FILE(export)            Wrote ~/opam-coq.8.7/4.02.3/backup/state-20180122071812.export in 0.000s
[ERROR] No package matches coq.8.7.
00:01.781  STATE                   LOAD-STATE(switch-backup-err)
00:01.802  STATE                   Loaded /home/users/jeremy/opam-coq.8.7/state.cache in 0.020s
00:02.122  STATE                   ROOT      : /home/users/jeremy/opam-coq.8.7
00:02.122  STATE                   SWITCH    : 4.02.3
00:02.122  STATE                   COMPILER  : 4.02.3
00:02.122  STATE                   COMPILERS : { 3.07, 3.07+1, 3.07+2, 3.08.0, 3.08.1, 3.08.2, 3.08.3, 3.08.4, 3.09.0, 3.09.1, 3.09.1+metaocaml, 3.09.2, 3.09.3, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.11.2, 3.12.0, 3.12.1, 4.00.0, 4.00.0+debug-runtime, 4.00.0+fp, 4.00.1, 4.00.1+BER, 4.00.1+PIC, 4.00.1+annot, 4.00.1+debug-runtime, 4.00.1+french, 4.00.1+mirage-unix, 4.00.1+mirage-xen, 4.00.1+open-types, 4.00.1+raspberrypi, 4.00.1+short-types, 4.01.0, 4.01.0+32bit, 4.01.0+BER, 4.01.0+PIC, 4.01.0+armv6-freebsd, 4.01.0+fp, 4.01.0+lsb, 4.01.0+musl, 4.01.0+musl+static, 4.01.0+open-types, 4.01.0+profile, 4.02.0, 4.02.0+PIC, 4.02.0+improved-errors, 4.02.0+modular-implicits, 4.02.0+rc1, 4.02.0+trunk, 4.02.1, 4.02.1+32bit, 4.02.1+BER, 4.02.1+PIC, 4.02.1+fp, 4.02.1+modular-implicits-ber, 4.02.1+musl, 4.02.1+musl+static, 4.02.2, 4.02.2+improved-errors, 4.02.2+rc1, 4.02.3, 4.02.3+32bit, 4.02.3+PIC, 4.02.3+buckle-1, 4.02.3+buckle-master, 4.02.3+bytecode-only, 4.02.3+curried-constr, 4.02.3+fp, 4.02.3+musl, 4.02.3+musl+static, 4.02.3+termux, 4.03.0, 4.03.0+32bit, 4.03.0+beta1, 4.03.0+beta1+flambda, 4.03.0+beta1-no-debug, 4.03.0+beta2, 4.03.0+beta2+flambda, 4.03.0+beta2-no-debug, 4.03.0+fPIC, 4.03.0+flambda, 4.03.0+fp, 4.03.0+fp+flambda, 4.03.0+statistical-memprof, 4.03.0+termux, 4.03.0+trunk, 4.03.0+trunk+flambda, 4.03.0+trunk+fp, 4.03.0+trunk+fp+flambda, 4.04.0, 4.04.0+32bit, 4.04.0+BER, 4.04.0+afl, 4.04.0+beta1, 4.04.0+beta1+flambda, 4.04.0+beta2, 4.04.0+beta2+flambda, 4.04.0+bytecode-only, 4.04.0+copatterns, 4.04.0+fPIC, 4.04.0+flambda, 4.04.0+fp, 4.04.0+fp+flambda, 4.04.0+safe-string, 4.04.0+spacetime, 4.04.0+termux, 4.04.0+trunk+forced_lto, 4.04.1, 4.04.1+32bit, 4.04.1+bytecode-only, 4.04.1+fPIC, 4.04.1+flambda, 4.04.1+fp, 4.04.1+fp+flambda, 4.04.1+safe-string, 4.04.1+spacetime, 4.04.2, 4.04.2+32bit, 4.04.2+bytecode-only, 4.04.2+fPIC, 4.04.2+flambda, 4.04.2+fp, 4.04.2+fp+flambda, 4.04.2+safe-string, 4.04.2+spacetime, 4.04.2+statistical-memprof, 4.05.0, 4.05.0+32bit, 4.05.0+afl, 4.05.0+beta1, 4.05.0+beta1+flambda, 4.05.0+beta2, 4.05.0+beta2+flambda, 4.05.0+beta3, 4.05.0+flambda, 4.05.0+lto, 4.05.0+musl+static+flambda, 4.05.0+rc1, 4.05.0+rc1+flambda, 4.05.0+safe-string, 4.05.0+spacetime, 4.05.0+statistical-memprof, 4.05.0+trunk, 4.05.0+trunk+afl, 4.05.0+trunk+flambda, 4.05.0+trunk+fp, 4.05.0+trunk+fp+flambda, 4.05.0+trunk+safe-string, 4.06.0, 4.06.0+32bit, 4.06.0+afl, 4.06.0+beta1, 4.06.0+beta1+afl, 4.06.0+beta1+default-unsafe-string, 4.06.0+beta1+flambda, 4.06.0+beta1+force-safe-string, 4.06.0+beta1+fp, 4.06.0+beta1+fp+flambda, 4.06.0+beta2, 4.06.0+beta2+afl, 4.06.0+beta2+default-unsafe-string, 4.06.0+beta2+flambda, 4.06.0+beta2+force-safe-string, 4.06.0+beta2+fp, 4.06.0+beta2+fp+flambda, 4.06.0+default-unsafe-string, 4.06.0+flambda, 4.06.0+flambda+no-flat-float-array, 4.06.0+force-safe-string, 4.06.0+fp, 4.06.0+fp+flambda, 4.06.0+musl+static+flambda, 4.06.0+rc1, 4.06.0+rc1+afl, 4.06.0+rc1+default-unsafe-string, 4.06.0+rc1+flambda, 4.06.0+rc1+force-safe-string, 4.06.0+rc1+fp, 4.06.0+rc1+fp+flambda, 4.06.0+spacetime, 4.06.0+statistical-memprof, 4.06.1, 4.06.1+afl, 4.06.1+default-unsafe-string, 4.06.1+flambda, 4.06.1+force-safe-string, 4.06.1+fp, 4.06.1+fp+flambda, 4.06.1+musl+static+flambda, 4.06.1+rc1, 4.06.1+rc1+afl, 4.06.1+rc1+default-unsafe-string, 4.06.1+rc1+flambda, 4.06.1+rc1+force-safe-string, 4.06.1+rc1+fp, 4.06.1+rc1+fp+flambda, 4.06.1+rc2, 4.06.1+rc2+afl, 4.06.1+rc2+default-unsafe-string, 4.06.1+rc2+flambda, 4.06.1+rc2+force-safe-string, 4.06.1+rc2+fp, 4.06.1+rc2+fp+flambda, 4.06.1+trunk, 4.06.1+trunk+afl, 4.06.1+trunk+flambda, 4.06.1+trunk+fp, 4.06.1+trunk+fp+flambda, 4.06.1+trunk+safe-string, 4.07.0+trunk, 4.07.0+trunk+afl, 4.07.0+trunk+flambda, 4.07.0+trunk+fp, 4.07.0+trunk+fp+flambda, 4.07.0+trunk+unsafe-string, system }
00:02.122  STATE                   REPOS     : { coq-released, default }
00:02.122  STATE                   PACKAGES  : 8767 packages
00:02.122  STATE                   INSTALLED : { base-bigarray.base, base-ocamlbuild.base, base-threads.base, base-unix.base }
00:02.122  STATE                   ROOTS     : { base-bigarray.base, base-ocamlbuild.base, base-threads.base, base-unix.base }
00:02.122  STATE                   REINSTALL : {}
00:02.122  STATE                   State switch-backup-err loaded in 0.156s
00:02.122  SYSTEM                  rm /home/users/jeremy/opam-coq.8.7/4.02.3/backup/state-20180122071812.export
00:02.198  SYSTEM                  Lock released on /home/users/jeremy/opam-coq.8.7/4.02.3/lock
00:02.198  SYSTEM                  Lock released on /home/users/jeremy/opam-coq.8.7/lock
'opam install -vv --debug coq.8.7' failed.

Sorry I can't tell if this is an issue with opam or coq

**Comment by Zimmi48** [comment]
Try `opam update && opam install coq.8.7.2` instead.

**Comment by Zimmi48** [comment]
Thanks for the report! I have updated the documentation page you linked to.
