### ISSUE TITLE
`omega with` is undocumented

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6829]
#### Version

8.7.1

#### Description of the problem

I cannot find documentation for `omega with Z`, `omega with nat`, `omega with *` in the refman (https://coq.inria.fr/refman/omega.html and https://coq.inria.fr/refman/tactics.html seem to contain no mentions of `omega with`).  See https://github.com/coq/coq/issues/4657#issuecomment-368109170 .

**Comment by letouzey** [comment]
Indeed. Also related to #4805 for `zify` (and also `romega`).

Let us first finish the ongoing transition of the documentation to Sphinx, in order not to redo this twice (or lose it during the transition).

In the meantime, the interested users could have a look at [PreOmega.v](../blob/master/plugins/omega/PreOmega.v) (in particular the top comment) and [g_omega.ml4](../blob/master/plugins/omega/g_omega.ml4).

**Comment by Zimmi48** [comment]
Given that the transition to Sphinx is going to be tight for 8.8+beta1, I'll put the 8.8.0 milestone on this issue and the other one to remind to do this right after the transition.

**Comment by Zimmi48** [comment]
@letouzey Now that the Sphinx migration is done, it could be the right time to handle this and other documentation issues.

**Comment by maximedenes** [comment]
> @letouzey Now that the Sphinx migration is done, it could be the right time to handle this and other documentation issues.

but if you don't have time, please update the milestone accordingly

**Comment by maximedenes** [comment]
Didn't hear back, removing the milestone.

**Comment by ppedrot** [comment]
Fixed by #11288.
