### ISSUE TITLE
Complete the doc of Coq parsing mechanism?

### ISSUE THREAD

**Issue by jianwolf** [coq/coq#6832]
Hi! I would like to understand the Coq parser very much! Could you please fill in the document below?
https://github.com/coq/coq/blob/e3124e098ef8170dac2b348b91757a7034bc4999/parsing/doc.tex

Thanks a lot!

**Comment by herbelin** [comment]
Hum, I don't know yet if I can do that. What typical questions would you like to be answered?

**Comment by jianwolf** [comment]
I would like to know the overall process of the parser, with some critical decisions explained (e.g., whether the parser is static or dynamic, and why). Thanks!

**Comment by herbelin** [comment]
Coq uses Camlp5 as parsing engine. It is an extensible parsing engine. The rules given in files `*.ml4` (e.g. `parsing/g_constr.ml4` for the grammar of terms, `parsing/g_vernac.ml4` for the grammar of main commands) are statically defined and linked to the main executable.

The rules (statically) defined in the `*.ml4` files of plugins, e.g. `plugins/ltac/g_tactic.ml4` are loaded dynamically when the corresponding module is (dynamically) loaded.

Additionally, the grammar of term and tactics can be extended dynamically by the user using the `Notation` and `Tactic Notation` commands.

Does it answer your question? Do you have other questions?

**Comment by jianwolf** [comment]
Yes, this works! Thanks for your answer!

**Comment by herbelin** [comment]
You're welcome.
