### ISSUE TITLE
Anomaly: Universe Var(1) undefined.

### ISSUE THREAD

**Issue by stepchowfun** [coq/coq#6839]
#### Version

```
The Coq Proof Assistant, version 8.6 (December 2016)
compiled on Dec 8 2016 16:33:2 with OCaml 4.02.3
```

#### Operating system

Mac OS 10.13.3 High Sierra

#### Description of the problem

Coq told me to report this error:

```
File "./coq/CategoryTheory/Category.v", line 182, characters 0-4:
Anomaly: Universe Var(1) undefined. Please report at
http://coq.inria.fr/bugs/.
```

Here's an example failure: https://travis-ci.org/stepchowfun/coq-fun/builds/346208396

And here's a commit demonstrating the problem: https://github.com/stepchowfun/coq-fun/tree/976f7330c835aa515ff91c253077cc4b19c91d3c

I apologize that the example isn't self contained. I'm not sure what's actually triggering the bug. I suspect it might be related to universe polymorphism. Thanks for looking into this! :]

**Comment by SkySkimmer** [comment]
Fixed in 8.7 (current stable).
