### ISSUE TITLE
Compatibility notations do not have the same semantics as normal notations (or only parsing notations).

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6840]
#### Version

8.8+alpha (current master)

#### Description of the problem

```coq
Notation "[ x ]" := (cons x nil) : list_scope.
Notation "[ x ; .. ; y ]" := (cons x .. (cons y nil) ..) (compat "8.6") : list_scope.

Variable Foo : nat -> nat.

Delimit Scope Foo_scope with F.

Notation " [ x ] " := (Foo x) : Foo_scope.

Check ([1] : nat)%F.
```

works.

```coq
Notation "[ x ]" := (cons x nil) : list_scope.
Notation "[ x ; .. ; y ]" := (cons x .. (cons y nil) ..) : list_scope.

Variable Foo : nat -> nat.

Delimit Scope Foo_scope with F.

Notation " [ x ] " := (Foo x) : Foo_scope.

Check ([1] : nat)%F.
```

doesn't.

```coq
Notation "[ x ]" := (cons x nil) : list_scope.
Notation "[ x ; .. ; y ]" := (cons x .. (cons y nil) ..) (only parsing) : list_scope.

Variable Foo : nat -> nat.

Delimit Scope Foo_scope with F.

Notation " [ x ] " := (Foo x) : Foo_scope.

Check ([1] : nat)%F.
```

doesn't either.

I thought the compatibility annotation was just about emitting warnings but apparently it changes also the semantics. I don't know if that's wanted or not.

**Comment by JasonGross** [comment]
This is deliberate.  Compatibility notations are so that when you issue `-compat`, you get the notations.  I knew this when I added the compat list notations, and the effect is exactly what was intended; I don't know if other notations were added with the same knowledge.

**Comment by Zimmi48** [comment]
OK thanks for the explanation. But why does the following works then? Isn't it an inconsistency?

```coq
Parameter bar : Prop.
Notation foo := bar (compat "8.6").
Check foo.
```

**Comment by Zimmi48** [comment]
If I understand correctly, there are compatibility notations and compatibility aliases with the same syntax but not the same semantics and this is were my confusion comes from.

**Comment by JasonGross** [comment]
Ah, that seems plausible.  Are there any compatibility notations other than the list ones which are not aliases?  (It's possible that I asked for the compatibility notation behavior when changing the list notations; the goal was to make `-compat` mimic 8.4 behavior even in the corner cases, as closely as possible, while allowing better behavior in 8.5.)

**Comment by Zimmi48** [comment]
If that's the only use case, we should probably clean the code now. I'll look into it. Could you also have a fresh look at #6791?

**Comment by JasonGross** [comment]
There's a lot there, but I'll try to take a look by Friday

**Comment by Zimmi48** [comment]
OK so the original commit introducing compatibility notations is f93f073df630bb46ddd07802026c0326dc72dafd and corresponds to what I had in mind (compatibility aliases that are activated even outside of compatibility mode).

**Comment by Zimmi48** [comment]
OK so my archeology finally allowed me to find the origin of the inconsistency. It was indeed because of you @JasonGross, see #4798. Apparently, this was even discussed in the issue thread right after the "fix" was implemented.

**Comment by Zimmi48** [comment]
Let me express that I now regret deeply putting my hands into the compatibility notation world...
