### ISSUE TITLE
Wiki garbage collection

### ISSUE THREAD

**Issue by gares** [coq/coq#6842]
As per CoqWG held on 26.2.2018 we are removing pages that are outdated, broken, ...
This issue is there to track progress and tag pages that are borderline. 

A TODO list has the following form:
#### Your Name
https://github.com/coq/coq/wiki/AppFwdRev 
...
https://github.com/coq/coq/wiki/AppFwdRev  
You should visit the page and do one of the following:
- remove the page (and remove the todo item)
- keep the page (and remove the todo item)
- keep the page (and keep the link)
When you are done, just write DONE near your name

@gares @maximedenes @ybertot @vbgl @ejgallego @ppedrot @mattam82 @Zimmi48 @SkySkimmer 

--------
##### Enrico
[AbstractingOverTheTermLeadsToATermWhichIsIllTyped](https://github.com/coq/coq/wiki/AbstractingOverTheTermLeadsToATermWhichIsIllTyped)
[AppFwdRev](https://github.com/coq/coq/wiki/AppFwdRev)
[ArbitraryArity](https://github.com/coq/coq/wiki/ArbitraryArity)
[ArithmeticExpressionParser](https://github.com/coq/coq/wiki/ArithmeticExpressionParser)
[AUGER_Annotations](https://github.com/coq/coq/wiki/AUGER_Annotations)
[AUGER_Enumerates](https://github.com/coq/coq/wiki/AUGER_Enumerates)
[AUGER_ExtractionTuto](https://github.com/coq/coq/wiki/AUGER_ExtractionTuto)
[AUGER_LinearLogic](https://github.com/coq/coq/wiki/AUGER_LinearLogic)
[AUGER_Monad](https://github.com/coq/coq/wiki/AUGER_Monad)
[AUGER_Notations](https://github.com/coq/coq/wiki/AUGER_Notations)
[BindingRepresentation](https://github.com/coq/coq/wiki/BindingRepresentation)
[BugzillaVsOtherTools](https://github.com/coq/coq/wiki/BugzillaVsOtherTools)
[BuildingCoqOnMac](https://github.com/coq/coq/wiki/BuildingCoqOnMac)
[Case-Studies](https://github.com/coq/coq/wiki/Case-Studies)
[CleanDuplicatedHypothesis](https://github.com/coq/coq/wiki/CleanDuplicatedHypothesis)
[Cocorico!FrontPage](https://github.com/coq/coq/wiki/Cocorico!FrontPage)
[ComparisonWithOtherSystems](https://github.com/coq/coq/wiki/ComparisonWithOtherSystems)
[Configuration-of-CoqIDE](https://github.com/coq/coq/wiki/Configuration-of-CoqIDE)
[Configuration of Proof General](https://github.com/coq/coq/wiki/Configuration%20of%20Proof%20General)
[CoqAndAxioms](https://github.com/coq/coq/wiki/CoqAndAxioms)
[CoqCodingSprint](https://github.com/coq/coq/wiki/CoqCodingSprint)
[CoqCS1](https://github.com/coq/coq/wiki/CoqCodingSprint/CoqCS1)
[CoqCS1-bsp](https://github.com/coq/coq/wiki/CoqCodingSprint/CoqCS1-bsp)
[CoqCS1-log](https://github.com/coq/coq/wiki/CoqCodingSprint/CoqCS1-log)

##### Maxime
[CoqCS2](https://github.com/coq/coq/wiki/CoqCodingSprint/CoqCS2)
[CoqCustomizationHowTo2006](https://github.com/coq/coq/wiki/CoqCustomizationHowTo2006)
[CoqDevelopment](https://github.com/coq/coq/wiki/CoqDevelopment)
[CoqWG20140131](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20140131)
[CoqWG20140404](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20140404)
[CoqWG20140606](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20140606)
[CoqWG20140905](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20140905)
[CoqWG20141023](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20141023)
[CoqWG20150106](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20150106)
[CoqWG20150324](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20150324)
[CoqWG20150512](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20150512)
[CoqWG20150708](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20150708)
[CoqWG20150915](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20150915)
[CoqWG20151125](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20151125)
[CoqWG20160216](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20160216)
[CoqWG20160415](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20160415)
[CoqWG20160531](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20160531)
[CoqWG20160928](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20160928)
[CoqWG20161214](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20161214)
[CoqWG20170306](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20170306)
[CoqWG20170523](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20170523)
[CoqWG20171003](https://github.com/coq/coq/wiki/CoqDevelopment/CoqWG20171003)
[CRADT20090324](https://github.com/coq/coq/wiki/CoqDevelopment/CRADT20090324)
[CRADT20090630](https://github.com/coq/coq/wiki/CoqDevelopment/CRADT20090630)
[CRADT20100202](https://github.com/coq/coq/wiki/CoqDevelopment/CRADT20100202)

##### Yves
[CRADTCommunication20090323](https://github.com/coq/coq/wiki/CoqDevelopment/CRADTCommunication20090323)
[CRGTCoq20081010](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20081010)
[CRGTCoq20081118](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20081118)
[CRGTCoq20090116](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20090116)
[CRGTCoq20090323](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20090323)
[CRGTCoq20090704](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20090704)
[CRGTCoq20091103](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20091103)
[CRGTCoq20100113](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20100113)
[CRGTCoq20100426](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20100426)
[CRGTCoq20100920](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20100920)
[CRGTCoq20101217](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20101217)
[CRGTCoq20110414](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20110414)
[CRGTCoq20110706](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20110706)
[CRGTCoq20120119](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20120119)
[CRGTCoq20120920](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20120920)
[CRGTCoq20130214](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20130214)
[CRGTCoq20130709](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20130709)
[CRGTCoq20131126](https://github.com/coq/coq/wiki/CoqDevelopment/CRGTCoq20131126)
[DesignNewTacticLanguage](https://github.com/coq/coq/wiki/CoqDevelopment/DesignNewTacticLanguage)
[Maintainers](https://github.com/coq/coq/wiki/CoqDevelopment/Maintainers)
[OPAM](https://github.com/coq/coq/wiki/CoqDevelopment/OPAM)
[Public](https://github.com/coq/coq/wiki/CoqDevelopment/Public)
[RaccourcisPourDevelopperSousEmacs](https://github.com/coq/coq/wiki/CoqDevelopment/RaccourcisPourDevelopperSousEmacs)
[RegressionTest](https://github.com/coq/coq/wiki/CoqDevelopment/RegressionTest)
[Roadmap86](https://github.com/coq/coq/wiki/CoqDevelopment/Roadmap86)

##### Vincent (Done)
[Roadmap87](https://github.com/coq/coq/wiki/Roadmap87)
[SourceTreeGuide](https://github.com/coq/coq/wiki/SourceTreeGuide)
[TODO](https://github.com/coq/coq/wiki/TODO)
[UnificationProblems](https://github.com/coq/coq/wiki/UnificationProblems)
[UsersDiscussion88](https://github.com/coq/coq/wiki/UsersDiscussion88)
[Coqdoc](https://github.com/coq/coq/wiki/Coqdoc)
[CoqIde](https://github.com/coq/coq/wiki/CoqIde)
[CoqIDE_crashes_under_KDE](https://github.com/coq/coq/wiki/CoqIDE_crashes_under_KDE)
[CoqIDEWishes](https://github.com/coq/coq/wiki/CoqIDEWishes)
[CoqImplementorsWorkshop](https://github.com/coq/coq/wiki/CoqImplementorsWorkshop)
[CoqIW2016](https://github.com/coq/coq/wiki/CoqIW2016)
[CoqIW2016-log](https://github.com/coq/coq/wiki/CoqIW2016-log)
[CoqIW2017](https://github.com/coq/coq/wiki/CoqIW2017)
[CoqIW2017log](https://github.com/coq/coq/wiki/CoqIW2017log)
[CoqInTheClassroom](https://github.com/coq/coq/wiki/CoqInTheClassroom)
[CoqInTheClassroomInitial](https://github.com/coq/coq/wiki/CoqInTheClassroomInitial)
[CoqNewbie](https://github.com/coq/coq/wiki/CoqNewbie)
[CoqNewbieQuestions](https://github.com/coq/coq/wiki/CoqNewbieQuestions)
[CoqPaths](https://github.com/coq/coq/wiki/CoqPaths)
[CoqPearls](https://github.com/coq/coq/wiki/CoqPearls)
[CoqSource](https://github.com/coq/coq/wiki/CoqSource)
[CoqStyle](https://github.com/coq/coq/wiki/CoqStyle)
[CoqTerminationDiscussion](https://github.com/coq/coq/wiki/CoqTerminationDiscussion)
[CoqWG20171812](https://github.com/coq/coq/wiki/CoqWG20171218)
[Coq-Working-Groups](https://github.com/coq/coq/wiki/Coq-Working-Groups)

##### Matthieu
[CoRN](https://github.com/coq/coq/wiki/CoRN)
[DependentInversion](https://github.com/coq/coq/wiki/DependentInversion)
[DevelopmentArchive](https://github.com/coq/coq/wiki/DevelopmentArchive)
[Development-questions](https://github.com/coq/coq/wiki/Development-questions)
[DevelopmentTutorial](https://github.com/coq/coq/wiki/DevelopmentTutorial)
[DevelSetup](https://github.com/coq/coq/wiki/DevelSetup)
[Discussion_on_content_and_structure_of_Cocorico!](https://github.com/coq/coq/wiki/Discussion_on_content_and_structure_of_Cocorico!)
[Documentation](https://github.com/coq/coq/wiki/Documentation)
[Eqdep_dec_Type](https://github.com/coq/coq/wiki/Eqdep_dec_Type)
[EqualityFreeInversion](https://github.com/coq/coq/wiki/EqualityFreeInversion)
[evar_match](https://github.com/coq/coq/wiki/evar_match)
[ExcludedMiddleOnNegativeFormulasFromCoqRealAxioms](https://github.com/coq/coq/wiki/ExcludedMiddleOnNegativeFormulasFromCoqRealAxioms)
[ExistentialVariablesInEapply](https://github.com/coq/coq/wiki/ExistentialVariablesInEapply)
[ExistsConsideredHarmful](https://github.com/coq/coq/wiki/ExistsConsideredHarmful)
[ExistsFromPropToSet](https://github.com/coq/coq/wiki/ExistsFromPropToSet)
[extensional_equality](https://github.com/coq/coq/wiki/extensional_equality)
[Extraction](https://github.com/coq/coq/wiki/Extraction)
[ExtractionNameTricks](https://github.com/coq/coq/wiki/ExtractionNameTricks)
[FalseEqAcc](https://github.com/coq/coq/wiki/FalseEqAcc)
[FixpointFiniteTypes](https://github.com/coq/coq/wiki/FixpointFiniteTypes)
[Folding tactics](https://github.com/coq/coq/wiki/Folding%20tactics)
[_Footer](https://github.com/coq/coq/wiki/_Footer)
[FormalizedAndVerified](https://github.com/coq/coq/wiki/FormalizedAndVerified)
[FrequentlyAskedQuestions](https://github.com/coq/coq/wiki/FrequentlyAskedQuestions)
[GenericTactics](https://github.com/coq/coq/wiki/GenericTactics)

##### Theo
[GuardConditionProblem](https://github.com/coq/coq/wiki/GuardConditionProblem)
[GUIWishes](https://github.com/coq/coq/wiki/GUIWishes)
[HandMul](https://github.com/coq/coq/wiki/HandMul)
[HourOfCoq](https://github.com/coq/coq/wiki/HourOfCoq)
[HowToContributeToTheStandardLibrary](https://github.com/coq/coq/wiki/HowToContributeToTheStandardLibrary)
[Induction-over-a-type-containing-pairs](https://github.com/coq/coq/wiki/Induction-over-a-type-containing-pairs)
[InductionWithSelfDefinedCases](https://github.com/coq/coq/wiki/InductionWithSelfDefinedCases)
[Inductive-and-Co-Inductive-Types](https://github.com/coq/coq/wiki/Inductive-and-Co-Inductive-Types)
[InductiveFiniteTypes](https://github.com/coq/coq/wiki/InductiveFiniteTypes)
[InTac](https://github.com/coq/coq/wiki/InTac)
[IntensionalEquality](https://github.com/coq/coq/wiki/IntensionalEquality)
[IteratedFiniteTypes](https://github.com/coq/coq/wiki/IteratedFiniteTypes)
[Jenkins](https://github.com/coq/coq/wiki/Jenkins)
[LagrangesTheorem](https://github.com/coq/coq/wiki/LagrangesTheorem)
[LhsRhsTactic](https://github.com/coq/coq/wiki/LhsRhsTactic)

##### Cyprien
[MatchAsInReturn](https://github.com/coq/coq/wiki/MatchAsInReturn)
[OtherContents](https://github.com/coq/coq/wiki/OtherContents)

##### Pierre Marie (DONE)
[Other Coq Resources](https://github.com/coq/coq/wiki/Other%20Coq%20Resources)
[Performance](https://github.com/coq/coq/wiki/Performance)
[Plugin-Developer-Program](https://github.com/coq/coq/wiki/Plugin-Developer-Program)
[PortingTo8-7](https://github.com/coq/coq/wiki/PortingTo8-7)
[PortingToCoqV8.7](https://github.com/coq/coq/wiki/PortingToCoqV8.7)
[Presentation](https://github.com/coq/coq/wiki/Presentation)
[ProjectIdeas](https://github.com/coq/coq/wiki/ProjectIdeas)
[Proof General Error Color](https://github.com/coq/coq/wiki/Proof%20General%20Error%20Color)
[Proof General Missing Proof State](https://github.com/coq/coq/wiki/Proof%20General%20Missing%20Proof%20State)
[ProofTermsConsideredHarmful](https://github.com/coq/coq/wiki/ProofTermsConsideredHarmful)
[Prop_or_Set](https://github.com/coq/coq/wiki/Prop_or_Set)
[PropsGuardingIotaReduction](https://github.com/coq/coq/wiki/PropsGuardingIotaReduction)
[Publishing-Tools](https://github.com/coq/coq/wiki/Publishing-Tools)
[QuickSort](https://github.com/coq/coq/wiki/QuickSort)
[RecordsNotModules](https://github.com/coq/coq/wiki/RecordsNotModules)
[ReflectionOnStandardLibrary](https://github.com/coq/coq/wiki/ReflectionOnStandardLibrary)
[Require_Import_and_Require_Export](https://github.com/coq/coq/wiki/Require_Import_and_Require_Export)
[RingTactics](https://github.com/coq/coq/wiki/RingTactics)
[Roadmaps](https://github.com/coq/coq/wiki/Roadmaps)
[Setoids](https://github.com/coq/coq/wiki/Setoids)
[SquareRootTwo](https://github.com/coq/coq/wiki/SquareRootTwo)
[StandardLibrary](https://github.com/coq/coq/wiki/StandardLibrary)
[Syntax-and-Notations](https://github.com/coq/coq/wiki/Syntax-and-Notations)

##### Emilio

[UTF8Module](https://github.com/coq/coq/wiki/UTF8Module)
[WikiMigration](https://github.com/coq/coq/wiki/WikiMigration)
[Wishes](https://github.com/coq/coq/wiki/Wishes)
[Wishes-for-Camlp5](https://github.com/coq/coq/wiki/Wishes-for-Camlp5)
[WTypeInsteadOfInductiveTypes](https://github.com/coq/coq/wiki/WTypeInsteadOfInductiveTypes)
[WtypesInCoq](https://github.com/coq/coq/wiki/WtypesInCoq)
[XComposeAndNotations](https://github.com/coq/coq/wiki/XComposeAndNotations)
[XCompose_symbols](https://github.com/coq/coq/wiki/XCompose_symbols)
[ZInterfacePackage](https://github.com/coq/coq/wiki/ZInterfacePackage)

**Comment by gares** [comment]
@cmangin I forgot to mention you, sorry

**Comment by SkySkimmer** [comment]
I'm removing all the Users-* pages, if you think that's a mistake resurrect them from git history.

**Comment by gares** [comment]
Sorry, URLs with a "directory" in it got wrong, these pages do exist, just serach for them

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/wiki/Tactics-Written-in-OCaml looks outdated (mllib for plugins, itarget files, some crazy makefile manipulation), could someone knowledgeable with plugins update it?

**Comment by Zimmi48** [comment]
It was recently mentioned on Coq-Club. I wanted to reply but did not get to it. As I also said in https://github.com/coq/coq/issues/5681#issuecomment-337556231, when a page contains only (or mostly) code, I don't think it is wise to keep it in the wiki. It sounds like this kind of documentation should be in the code base instead and thus regularly tested and updated...

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/wiki/evar_match is another example ocaml tactic for redundancy.

**Comment by gares** [comment]
> NotFinitePrimes:

remove, is Coq 8.7, and such a result is part of current libraries (it is even the showcase of jscoq).

> Organizing Large Proofs:

It contains

> Since Coq version 8.2, the best way of organizing a large proof is probably using C-zar, Coq's
> DeclarativeProof language

I think it should be removed

**Comment by gares** [comment]
> https://github.com/coq/coq/wiki/evar_match

remove, it is `V82` API (pre tactic monad, pre EConstr)...

**Comment by gares** [comment]
> Tactics-Written-in-OCaml

We definitely need a page on this topic but this one:
- wrong build system (inside Coq, not by using coq_makefile)
- the code is V82 API

**Comment by Zimmi48** [comment]
Some clean-up has happened following this issue. I don't think we are expecting more to be done on this specific aspect of the clean-up for now, so closing.
