### ISSUE TITLE
Pre Commit hook is broken.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6858]
Steps to reproduce:

- edit `Makefile.ide`
- commit
- see how all your tabs are incorrectly converted into spaces.

I am sorry I didn't have the time to comment in the pre-commit PR, but IMHO, we are going too far with the automatic `pre-commit` hook.

**Comment by Zimmi48** [comment]
If you don't want the pre-commit hook, you can replace it by an empty pre-commit hook in your `.git/hooks`.

**Comment by SkySkimmer** [comment]
Cannot reproduce.
eg 
```bash
$ printf "bob:\n\techo bob\n" >> Makefile.ide
$ git add Makefile.ide
$ git commit -m bob
[master 97be0909a0] bob
 1 file changed, 2 insertions(+)
$ make bob
(dependency stuff)
echo bob
bob
```
No whitespace errors detected, new target (with new tab) works.

**Comment by maximedenes** [comment]
@SkySkimmer maybe you should try adding a line with a tab

**Comment by Zimmi48** [comment]
That's what he did just above

**Comment by gares** [comment]
[troll]: How much time was spent on the white space business? How much benefit did we get?

**Comment by ejgallego** [comment]
I think installed the `pre-commit` hook on `configure` is still a bit aggressive, but I can live with installing an empty one. 

However tabs being removed from `Makefile` is a bug. I can reproduce as of now, just edit a tab-indented line in `Makefile.build` and commit. The tab is gone.

**Comment by ejgallego** [comment]
> [troll]: How much time was spent on the white space business? How much benefit did we get?

IMHO the benefit was great, the visual inconsistencies of tabs and extra spacing is really distracting for me, so know at least I know these are gone in new code, and you can already feel it.

I guess some people is more "OC" about code aesthetics, so YMMV.

**Comment by Zimmi48** [comment]
> However tabs being removed from Makefile is a bug. I can reproduce as of now, just edit a tab-indented line in Makefile.build and commit. The tab is gone.

I did exactly that and it didn't do anything. The tabs do not show up in the diff (they show as spaces) but the tab appears to still be there in the file.

**Comment by ejgallego** [comment]
I dunno, I just reproduced it unconciously. Will try to do detailed step by step instructions.

**Comment by ejgallego** [comment]
So the problem was indeed on my end, some leftover configuration in `coq/.git/config`.
