### ISSUE TITLE
Parsing Error after dropping to Ocaml Shell

### ISSUE THREAD

**Issue by psacawa** [coq/coq#6872]
#### Version
EDIT (fix wrong version):
The Coq Proof Assistant, version 8.8+alpha (February 2018)
compiled on Feb 27 2018 20:58:39 with OCaml 4.04.0
#### Operating system
Ubuntu Linux 17.10.1

#### Description of the problem
Failure of Coq to parse commands after using `Drop.` then `go();;` while in the middle of a proof.
**Steps to reproduce**
- clone coq
- `make world byte`
- (from repo's root) `rlwrap ./bin/coqtop.byte -coqlib ./` (as an aside, how can I get `coqtop.byte` to find the libraries automatically?)
- Start any proof environment (e.g. `Goal True.`)
- `Drop.`
- `#use "include";;`
- `go();;`
- Use any command, e.g. `Show.`

The result is an error looking like this

`Error:
Currently, the parsing api only supports parsing at the tip of the document.
You wanted to parse at: 1 but the current tip is: 2`

Searching the repo traces this back to `smt/smt.ml`, but I cannot find any data in `dev/doc` that would help me understand the error.

**Comment by psacawa** [comment]
It seems the error is also elicited by almost any behaviour modifying the Coq environment, e.g.
- `Definition x := 1.`
- `Drop.`
- `go();;`
- `Print All.`

produces an analogous error:

    Error:
    Currently, the parsing api only supports parsing at the tip of the document.
    You wanted to parse at: 1 but the current tip is: 2`


        Ocaml toplevel with Coq printers and utilities (use go();; to exit)

The last line welcoming to the ocaml toplevel seems the key thing.

**Comment by ejgallego** [comment]
Can you try on `master`?

**Comment by ejgallego** [comment]
> The Coq Proof Assistant, version 8.6 (July 2017)

Note about the version, that's not master.

> how can I get coqtop.byte to find the libraries automatically?)

I think that passing `-local` to `configure` should do the trick.

Indeed, the bug is confirmed, somehow the new span introduced by `Drop.` is not taken into account by the shell, should be easy to fix.

**Comment by ejgallego** [comment]
See https://github.com/coq/coq/pull/6873

**Comment by psacawa** [comment]
Sorry about the confusion regarding master. I accidentally took that data from the system install of `coq`.
The actual version was
`The Coq Proof Assistant, version 8.8+alpha (February 2018)`
`compiled on Feb 27 2018 20:58:39 with OCaml 4.04.0`
will edit

**Comment by ejgallego** [comment]
Patch is reasonably small you can directly apply it:
```
diff --git a/toplevel/coqloop.ml b/toplevel/coqloop.ml
index ae0b94476..e6985926e 100644
--- a/toplevel/coqloop.ml
+++ b/toplevel/coqloop.ml
@@ -353,7 +353,12 @@ let rec loop ~time ~state =
        not possible due exceptions. *)
     in vernac_loop ~state
   with
-    | CErrors.Drop -> state
+    | CErrors.Drop ->
+      (* Due to using exceptions as a form of control, state here goes
+         out of sync as [do_vernac] will never return. We must thus do
+         this hack until we make `Drop` a toplevel-only command. See
+         bug #6872. *)
+      { state with sid = Stm.get_current_state ~doc:state.doc }
     | CErrors.Quit -> exit 0
     | any ->
       top_stderr (str "Anomaly: main loop exited with exception: " ++
```

**Comment by psacawa** [comment]
That ejgallego, this seems to ameliorate the problem, but I can still produce a failure with the following coq session, reproduced entirely below (there is no `#use "include";;` because it's in my `.ocamlinit`):
```
Welcome to Coq demiurg:/home/psacawa/Kody/ocaml/coq,master (e3124e098ef8170dac2b348b91757a7034bc4999)
Coq < Parameter x:nat.
x is declared
Coq < Drop.
        OCaml version 4.04.0
# go ();;
Coq < Check x.
        Ocaml toplevel with Coq printers and utilities (use go();; to exit)
x
     : nat
Coq < Drop.
- : Vernac.State.t =
{Vernac.State.doc = <abstr>; sid = <abstr>; proof = None}
# go ();;
Coq < Check x.
Error:
Currently, the parsing api only supports parsing at the tip of the document.
You wanted to parse at: 2 but the current tip is: 4
```

**Comment by ejgallego** [comment]
Ahh, you are correct, the drop state has to be kept into `Coqloop` itself as this is what `go ()` uses. PR updated.

**Comment by psacawa** [comment]
Thanks, ejgallego, this works in my repo.
