### ISSUE TITLE
Improve error message for fixpoints that are actually non-recursive

### ISSUE THREAD

**Issue by mattam82** [coq/coq#6875]
#### Version

Any

#### Operating system

Any

#### Description of the problem

Non-recursive fixpoints are currently allowed, which breaks parametricity and is non-uniform with mutual fixpoints which are checked to be really mutual.
We should generalize the check for really mutual fixpoint definitions and improve the error message.
See PR #407

**Comment by mattam82** [comment]
We should enforce this in the kernel I think.

**Comment by SkySkimmer** [comment]
>is non-uniform with mutual fixpoints which are checked to be really mutual.

This is currently just a warning (`non-full-mutual`).

Isn't it possible to substitute away the recursivity?
`(fun f => fix F x := match x with 0 => 0 | S x => f (F x) end) (fun x => 1)` reduces to 
`fix F x := match x with 0 => 0 | S x => 1 end`
So a kernel check would remove SR.

**Comment by maximedenes** [comment]
He he, nice example @SkySkimmer.

**Comment by SkySkimmer** [comment]
no bug here AFAICT
