### ISSUE TITLE
Unify coq_makefile and coqdep argument handling

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#6877]
In #6851 coqdep learns to get .v files from a _CoqProject-formatted file. We could go farther and also have coqdep get other files and options from it.

The main issue with doing so is properly handling coq_makefile invocations with both command line options and a project file, where the command line options need to be separated for passing to coqdep.

#6851 also puts the origin of options in the `project` record so this should be feasible.

cc @gares

**Comment by ejgallego** [comment]
I am tempted to close this as "won'tfix"; coqdep is usually called from Dune / coq_makefile and IMHO it should just be a minimal wrapper to parse coq files and spit deps out; Dune coq_makefile should call coqdep with the right flags and interpret it's output correctly; IMO no point on duplicating functionality here as the build tools need to be aware of project files anyways.

WDYT @SkySkimmer

**Comment by SkySkimmer** [comment]
I don't mind.

**Comment by ejgallego** [comment]
Could be also handled in #14059
