### ISSUE TITLE
agda style PRAGMA BUILTIN ?

### ISSUE THREAD

**Issue by spitters** [coq/coq#6890]
We would like to have a *maintainable* way of changing e.g. Coq's logic.
For instance, for the inclusion of Equations in HoTT:
https://github.com/HoTT/HoTT/issues/895

**Comment by Zimmi48** [comment]
Hi @sampablokuper, more details for those who don't know PRAGMA BUILTIN would be very appreciated.
Looking at the discussion you linked to, it seems that it somehow relates to #186. Is that right?

**Comment by spitters** [comment]
https://agda.readthedocs.io/en/v2.5.3/language/built-ins.html

Yes, #186 is related! @ejgallego has made quite some progress in this direction already, but I don't think it's completely finished yet.

**Comment by Zimmi48** [comment]
Indeed, so is it just related or is it exactly the problem that #186 is supposed to be solving? (Looking at the new link gives me this impression. Just to be sure.)

**Comment by spitters** [comment]
Thanks. Indeed, the same technique will work here, I hope. 
However, I don't think #186 deals with the Equations plugin (or does it?)

**Comment by mattam82** [comment]
Nope. Indeed, we should rather work on #186 which should provide a general enough mechanism. @spitters if your student has a little time to devote to this I'd be happy to help, but it seems from the status of #186 that some expert diagnostic is needed first. I'll try to give it a shot, this is now top priority on my TODO (but the ICFP deadline is coming :)

**Comment by Zimmi48** [comment]
> this is now top priority on my TODO

Really? But you already had so much to do for 8.8!

**Comment by mattam82** [comment]
Well, all of that is top priority :)

**Comment by mattam82** [comment]
To give you an idea, my TODO is like this right now:

*** TODO [#A] Credits for 8.8

*** TODO [#A] Unifall benchmark and history

*** Hint cut/Hint ExternIf

*** PR 6824 review
*** TODO [#B] PR 186
*** PR on cumulative inductive types conversion
    Adapt checker.

*** Check the milestone on my PRs

*** Singleton classes? Still useful?

**Comment by ejgallego** [comment]
#186 indeed is very ambitious but I think I can envision a plan to get some important part of it committed. Basically, the PR is almost ready, last time I tried seriously only one line in HoTT was giving me trouble.

**Comment by spitters** [comment]
@ejgallego That would be a great simplification.

**Comment by andreaslyn** [comment]
Hi @mattam82 and @spitters. I am Andreas. I would like to look into this issue. I have an idea of what needs to be done. As i understand it: This issue is about implementing a kind of pragma feature which can be used in the stdlib to instruct Coq where definitions of core builtin constants are located. One of the goals with this is to use it with Equations, rather than the current hard coded paths. Later when issue #186 is fixed we should be able to add these pragmas to the Coq-HoTT stdlib and Equations should work there as well. Correct?

**Comment by spitters** [comment]
#186  should be an alternative to pragmas.
It would be great if you could find the lemmas in HoTT corresponding to the constants needed for Equations; see HoTT/HoTT#895.

**Comment by andreaslyn** [comment]
I can do that.

**Comment by spitters** [comment]
@mattam82 Did you get around to looking at this? It would be good if we could continue porting math-classes.

**Comment by spitters** [comment]
@ejgallego @mattam82, 
@andreaslyn is making progress and porting math-classes. With 8.8 out of the way, what's the best way to proceed?

**Comment by spitters** [comment]
@ejgallego @mattam82, 
@andreaslyn is making progress and porting math-classes. With 8.8 out of the way, what's the best way to proceed?

**Comment by ejgallego** [comment]
Fixed by #186
