### ISSUE TITLE
Insecure download links in Windows install scripts

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6891]
Some of the download links in the Windows install scripts are HTTP and not HTTPS. It should be updated to use always HTTPS or verify checksums after download.

**Comment by MSoegtropIMC** [comment]
A short update: I decided to keep secure hashes of all downloaded components, regardless if they are downloaded via https, http or ftp, in our repository and check these. This does not include things downloaded by the Cygwin setup program. This could be done as well, but it changes frequently and would be a lot of maintenance effort.

**Comment by MSoegtropIMC** [comment]
This is deprecated with Coq Platform.

**Comment by MSoegtropIMC** [comment]
The PR which removed the old build scripts and switched to Coq Platform was (#13598).
