### ISSUE TITLE
lia does not handle renaming of types well.

### ISSUE THREAD

**Issue by FlorianSteinberg** [coq/coq#6936]
#### Version
8.7

#### Operating system
n\a

#### Description of the problem

lia does not handle renaming of types well. Here is a minimal working example:

```
Require Import Psatz Arith.

Definition N := nat.
Lemma ex (n : N):
	n <= 0 -> n = 0.
Proof.
intros.
Fail lia.
unfold N in n.
Fail lia.
unfold N.
lia.
Qed.
```

**Comment by pi8027** [comment]
Duplicate of #4717.

**Comment by ppedrot** [comment]
Let's close then.
