### ISSUE TITLE
Unexpected error during scheme creation: Anomaly "Uncaught exception Type_errors.TypeError(_, _)."

### ISSUE THREAD

**Issue by silene** [coq/coq#6951]
#### Version

8.8

#### Description of the problem

```
Record float2 : Set := Float2 { Fnum : unit }.
Scheme Equality for float2.

Unexpected error during scheme creation:
Anomaly "Uncaught exception Type_errors.TypeError(_, _)."
```

This is a regression with respect to Coq 8.7.

**Comment by silene** [comment]
Bisection says 7ceed3c76e5ac752321827300f80ee974acbb54c (PR #407).

**Comment by maximedenes** [comment]
Ouch!

**Comment by maximedenes** [comment]
@mattam82 can you have a look at it?

@silene does this code come from Flocq? I'm surprised we didn't catch this with CI.

**Comment by SkySkimmer** [comment]
Looks like https://github.com/cartazio/gappa-coq/blob/master/src/Gappa_tree.v#L517

**Comment by silene** [comment]
That is right, it comes from Gappa, which is not in the CI because its plugin breaks every time someone touches the kernel or pretyper.

**Comment by Zimmi48** [comment]
Well Equations, Ltac2 and Elpi also break pretty often...

**Comment by maximedenes** [comment]
@mattam82 can you update the milestone to reflect your schedule? Thanks!

**Comment by maximedenes** [comment]
@mattam82 ping

**Comment by maximedenes** [comment]
@mattam82 This was a serious regression IMHO. Any chance you prepare a fix this morning?

**Comment by ppedrot** [comment]
I think I can try to come up with a fix in a hurry, if needed.

**Comment by ppedrot** [comment]
@maximedenes #7260 is a quick, hopefully correct fix.
