### ISSUE TITLE
document of "elim term1 using term2" describes term2 as "elimination predicate"

### ISSUE THREAD

**Issue by akr** [coq/coq#6980]
#### Version

```
% coqtop -v  
The Coq Proof Assistant, version 8.7.2 (March 2018)
compiled on Mar 13 2018 2:25:05 with OCaml 4.05.0
```

#### Operating system

```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch
```

#### Description of the problem

I think the document of "elim term1 using term2" contains a mistake.

The following description says term2 as "elimination predicate" but
"elimination predicate" means "return" clause of "match".
I think it should be "induction scheme" or "induction principle".

```
elim term1 using term2
elim term1 using term2 with bindings_list

Allows the user to give explicitly an elimination predicate term2 that is not the standard one for the underlying inductive type of term1. The bindings_list clause allows instantiating premises of the type of term2.
```

https://coq.inria.fr/refman/tactics.html#hevea_tactic93
https://github.com/coq/coq/blob/master/doc/refman/RefMan-tac.tex#L1982

"elimination predicate" is described in
https://coq.inria.fr/refman/cases.html

**Comment by Zimmi48** [comment]
Good suggestion: I created #7070.
This chapter and this part in particular could still be improved a lot.
For such kind of improvements, feel free to open pull requests directly in the future.
