### ISSUE TITLE
Canonical Structures break coercions

### ISSUE THREAD

**Issue by eluuk** [coq/coq#7012]
#### Version

8.7.2

#### Operating system

Linux

#### Description of the problem

In the code below, Canonical Structures break coercions (Print Graph shows the coercion exists, but it does nothing)

```
Parameter X Y: nat -> Set.
Structure CX := cx {g: nat -> Set}.
Canonical Structure cx_x: CX := cx X.
Canonical Structure cx_x': CX := cx Y.
Parameter u: X 0.
Check u: g cx_x 0.

Parameter xu: nat.
Parameter df:> forall {x y}, g x y -> g x xu.
Fail Check u: g cx_x xu. (*why?*)
Fail Check u: X xu. (*why?*)
Check df u: X xu.

Parameter f:> forall {x}, X x -> X xu.
Check u: g cx_x xu.
Check u: X xu.

Print Graph.
(* [@df] : g >-> g
[@f] : X >-> X *)

```

**Comment by silene** [comment]
What makes you think it is a bug? As shown by `Print Graph`, `df` is a coercion from type head `g` to type head `g`. When you check `u : g cx_x xu`, you need to unify type head `X` with type head `g` (or type head `X` after reduction). There is no such coercion in the graph. It is only after you have added `f` to the graph that there is one. If you do `Check (u : g cx_x 0) : g cx_x xu`, then you need to unify type head `g` with type head `g` and Coq successfully finds the coercion `df`.
