### ISSUE TITLE
Polymorphic cumulativity and function eta break subject reduction

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7015]
Present in 8.7 and current master.
```coq
Set Universe Polymorphism.
Set Polymorphic Inductive Cumulativity.
Set Printing Universes.

(* in the real world foo@{i} might be [@paths@{i} nat] I guess *)
Inductive foo : nat -> Type :=.

(* on [refl (fun x => f x)] this computes to [refl f] *)
Definition eta_out {A B} (f g : forall x : A, B x) (e : (fun x => f x) = (fun x => g x)) : f = g.
Proof.
  change (f = g) in e. destruct e;reflexivity.
Defined.

Section univs.
  Universes i j.
  Constraint i < j. (* constraint not needed in master *)

  Definition one : (fun n => foo@{i} n) = fun n => foo@{j} n := eq_refl.

  Definition two : foo@{i} = foo@{j} := eta_out _ _ one.

  Fail Definition two' : foo@{i} = foo@{j} := Eval compute in two.

  (* Failure of SR doesn't just mean that the type changes, sometimes
     we lose being well-typed entirely. *)
  Definition three := @eq_refl (foo@{i} = foo@{j}) two.
  Fail Definition four := Eval compute in three.
End univs.
```

**Comment by mattam82** [comment]
There seems to be a bug in the implementation if we don’t apply  cumulativity in this case to accept `two’` to be inhabited by `eq_refl`. Same thing for lists, conversion by cumulativity should also apply in partially applied cases to be stable by eta. @amintimany any idea how to fix/justify this?

**Comment by herbelin** [comment]
Side comment: in CoqIDE, when evaluating directly to the end, `one` fails.

**Comment by herbelin** [comment]
A question by curiosity:
- With `Constraint i < j`, `one` is inferred to be `eq_refl (fun n : nat => foo@{i} n)`.
- If I remove the `Constraint i < j`, then `one` enforces `i = j`.
- If I change it to `Constraint j < i`, `one` is still inferred to be `eq_refl (fun n : nat => foo@{i} n)`.

I would spontaneously suspect some arbitrariness in the order in which unification treats problems, as it is common to see. So, just wondering what is our degree of freedom, e.g. if `eq_refl (fun n : nat => foo@{j} n)` could be obtained in the latter case?

**Comment by SkySkimmer** [comment]
That's outdated, in master removing the constraint should not enforce i = j.

**Comment by herbelin** [comment]
Actually, I'm confused. If I do:
```coq
Set Universe Polymorphism.
Set Polymorphic Inductive Cumulativity.
Section univs.
Universes i j.
Constraint j < i.
Inductive bar : Type :=.
Check fun x : bar@{i} => x : bar@{j}.
```
It is a bit strange to have the last line succeeding knowing the constraint `j < i`.

**Comment by JasonGross** [comment]
@herbelin What is confusing about that?  Note that it fails if you give `bar` a large inhabitant, e.g., `Inductive bar := v (_ : Type).`.  To me, the typechecking problem you give says "all inhabitants of `bar@{i}` are also inhabitants of `bar@{j}`, which is true, because `bar@{i}` is equivalent to `bar@{Set}` for all `i`.

Another example of this sort of thing is this one:
```coq
Set Universe Polymorphism.
Set Polymorphic Inductive Cumulativity.
Inductive eq (A : Type) (x : A) : A -> Prop := eq_refl : @eq A x x.
Set Printing Universes.
Print eq.
Section univs.
  Universes i j.
  Constraint j < i.
  Check fun x : @eq@{i} nat 0 0 => x : @eq@{j} nat 0 0.
```
Since `nat` lives in `Set`, everything about equality at `nat` is determined by `Set`-level things (or maybe at most `Set+1`-level things, and so I expect the universe I give `@eq` to not matter.

**Comment by amintimany** [comment]
@mattam82 I am a bit confused. I though we already handle these cases. I remember we had a discussion about this last year. We can handle partially applied inductives and constructors exactly by eta expanding them. I expect ```two'``` to go through because by it should by eta expanding both sides.

**Comment by amintimany** [comment]
I guess I see. Before cumulativity if conversion failed we never went back and eta expanded inductives or constructors because that wouldn't change the situation. But in presence of cumulativity I think we should (or change the algorithm to consider the eta expanded version).

**Comment by herbelin** [comment]
@jasongross: I agree with that. @skyskimmer: thanks, I missed that.

To continue with naive questions (which maybe have been already answered at a previous time), is there a way to tell that a definition does not depend on a variable after closing of section. If I do:
```coq
Set Universe Polymorphism.
Set Polymorphic Inductive Cumulativity.
Inductive foo : Type :=.
Section univs.
Universes i j.
Definition one : foo@{i} = foo@{i} := eq_refl.
End univs.
Print one.
```
I get that `one` depends on `j`. Even if I do `Definition one@{i k} : foo@{i} = foo@{i} :> Type@{k} := eq_refl.`, the two section-local variables `i` and `j` remain quantified over `one` which now depends on 4 variables (with the second `i` renamed).

In passing, if I do `Definition one@{i} : foo@{i} = foo@{i} :> Type@{i+1} := eq_refl@{}.`, I get an 
anomaly (though probably not a big deal as I guess it could just instead be turned into an error).

**Comment by amintimany** [comment]
@herbelin This is indeed a problem of sections and universe polymorphism. Currently every definition in a section gets all universes! We tried to relax this last year together with @mattam82 by doing an analysis at the end of the section. However, that broke STM and we just left it there.

**Comment by gares** [comment]
> However, that broke STM and we just left it there.

Can you be more explicit?

**Comment by amintimany** [comment]
@gares I remember we discussed this at that point. I think we were forcing the body of constants before they were fully processed which broke when async processing. The bug caused some of the tests in the ```test-suite/vio``` to freeze because they are processed by ```-quick```.

**Comment by amintimany** [comment]
@gares this is the commit that broke things [https://github.com/amintimany/coq/commit/11c94ea9567ed11302e62f08633c92497a370cff](https://github.com/amintimany/coq/commit/11c94ea9567ed11302e62f08633c92497a370cff). You even made a pull request that we didn't discuss further [https://github.com/amintimany/coq/pull/1](https://github.com/amintimany/coq/pull/1)

**Comment by gares** [comment]
The example by @SkySkimmer looks very close to https://github.com/coq/coq/pull/613#issuecomment-309508576

**Comment by gares** [comment]
@amintimany the code you point to is not there anymore (not in that form) and my PR is against that code so I'm not so sure how you made the test suite go trough.

Wrt the bug by @herbelin the problem seems to be that the *hack* I use in the STM to detect "Set Universe Polymorphism" has not been extended to "Set Polymorphic Inductive Cumulativity".
  https://github.com/coq/coq/blob/master/stm/vernac_classifier.ml#L58

**Comment by amintimany** [comment]
> @amintimany the code you point to is not there anymore (not in that form) and my PR is against that code so I'm not so sure how you made the test suite go trough.

@gares, We didn't include this code in the PR at the end. That's why the problem that @herbelin mentioned above is still there.

> Wrt the bug by @herbelin the problem seems to be that the hack I use in the STM to detect "Set Universe Polymorphism" has not been extended to "Set Polymorphic Inductive Cumulativity".
> https://github.com/coq/coq/blob/master/stm/vernac_classifier.ml#L58

`Set Polymorphic Inductive Cumulativity` is a separate option and only works if `Set Universe Polymorphism` is also activated. So I am a bit confused!

**Comment by maximedenes** [comment]
> only works if Set Universe Polymorphism is also activated

That's not true.

```
$ echo "Fail Set Polymorphic Inductive Cumulativity." | coqtop
Error: The command has not failed!
```

**Comment by amintimany** [comment]
@maximedenes The option is enabled but if both options are not enabled at the same time it shouldn't work!

**Comment by maximedenes** [comment]
> it shouldn't work

What does it mean concretely? What does it do then?

**Comment by SkySkimmer** [comment]
The issue is that the cumulativity flag is read at parsing time so the stm needs to set it before parsing the rest of the document.

**Comment by amintimany** [comment]
> > it shouldn't work

> What does it mean concretely? What does it do then?

@maximedenes  This is documented in the manual [https://coq.inria.fr/refman/universes.html#sec885](https://coq.inria.fr/refman/universes.html#sec885).

**Comment by gares** [comment]
> So I am a bit confused!

The STM needs to know which sentences alter the parser.
The `Set Polymorphic Inductive Cumulativity` one does:
   https://github.com/coq/coq/blob/master/parsing/g_vernac.ml4#L173
but is not classified as such (`VtNow`)
   https://github.com/coq/coq/blob/master/stm/vernac_classifier.ml#L58

**Comment by SkySkimmer** [comment]
Let's move STM discussion to #7016.

**Comment by SkySkimmer** [comment]
I was thinking we might be able to have some more variance info for the arguments to handle this, but we need to be complete somehow and that doesn't seem possible with static variance. ie consider this modified example:
~~~coq
Set Universe Polymorphism.
Set Polymorphic Inductive Cumulativity.
Set Printing Universes.

Inductive foo@{i j} (b:bool) (x:if b return Type@{j} then Type@{i} else nat) : Type@{i} := .

(* on [refl (fun x => f x)] this computes to [refl f] *)
Definition eta_out {A B} (f g : forall x : A, B x) (e : (fun x => f x) = (fun x => g x)) : f = g.
Proof.
  change (f = g) in e. destruct e;reflexivity.
Defined.

Section univs.
  Universes i j k.
  Constraint i < j. (* constraint not needed in master *)

  Definition one : (fun n => foo@{i k} false n) = fun n => foo@{j k} false n := eq_refl.

  Definition two : foo@{i k} false = foo@{j k} false := eta_out _ _ one.

  Fail Definition two' : foo@{i k} = foo@{j k} := Eval compute in two.

  (* Failure of SR doesn't just mean that the type changes, sometimes
     we lose being well-typed entirely. *)
  Definition three := @eq_refl (foo@{i k} false = foo@{j k} false) two.
  Fail Definition four := Eval compute in three.
End univs.
~~~
The eta expansion of `foo@{i k} false` is irrelevant in `i`, and this relies on reduction in the type of the 2nd argument specifically when the 1st is `false`.

**Comment by SkySkimmer** [comment]
Actually
~~~coq
  Fail Definition two' : foo@{i k} = foo@{j k} := Eval compute in two.
~~~
this isn't a problem as `foo@{i k} = foo@{j k}` is ill-typed (with `i <> j`).

Not sure if that means we could do something smart or if it's just a bad example.

**Comment by mattam82** [comment]
two' is just a bad example indeed, you "eta-reduced" a bit too much.
