### ISSUE TITLE
ssr: applying an overloaded lemma as a view takes too long

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#7026]
#### Version

Coq 8.7.2 compiled with OCaml 4.06.0
Coq 8.8+alpha compiled with OCaml 4.06.1 (coq.dev OPAM package)

#### Operating system

macOS 10.13.3 High Sierra

#### Description of the problem

The self-contained example is in [this gist](https://gist.github.com/anton-trunov/6c9fd2d821a7f8a56959dac95a0a0d30).
The code is a minimized version of the heap cancellation algorithm from "How to Make Ad Hoc Proof Automation Less Ad Hoc" by G. Gonthier, B. Ziliani, A. Nanevski and D. Dreyer (sect. 4).

```coq
Example stress 
  (h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16 : heap) :
  valid (h1 :+ h2 :+ h3 :+ h4 :+ h5 :+ h6 :+ h7 :+ h8 :+ h9 :+ h10 :+ h11 :+ h12 :+ h13 :+ h14 :+ h15) ->

  h1 :+ h2 :+ h3 :+ h4 :+ h5 :+ h6 :+ h7 :+ h8 :+ h9 :+ h10 :+ h11 :+ h12 :+ h13 :+  h14 :+ h15
=
  h1 :+ h2 :+ h3 :+ h4 :+ h5 :+ h6 :+ h7 :+ h8 :+ h9 :+ h10 :+ h11 :+ h12 :+ h13 :+  h16 ->

  h15 :+ h14 = h16.
move=>D.
(* Slow -- 4 secs on my machine and hogs gigabytes of RAM
   Running time and memory consumption seem to grow exponentially with adding more variables
 *)
Time move/(cancelR D)=>/=->.

Restart.

(* If we explicitly supply H, then it's much faster -- 0.3 secs on my machine *)
move=>D H.
Time move: (cancelR D H)=>/=->.
by [].
Qed.
```

The original code from the paper was tested with Coq 8.4. This minimized example runs for about 1 second in both cases under Coq 8.4.5 and SSReflect 1.5.0.

**Comment by ejgallego** [comment]
@anton-trunov could you get some profiling data? [see `dev/doc/profiling` and please file bugs for all the missing bits]

It is also this slow in 8.5? 8.6? I would be great to try to track when the regression did take place.

**Comment by ppedrot** [comment]
That's ssreflect trying to recognize applied inductive types using a function that has not been designed for that. I'll write a quick fix.

**Comment by anton-trunov** [comment]
@ejgallego The last time I checked profiling does not work on macOS (or at least I don't know how to set it up without virtualization). Should I file this as an issue?

**Comment by ejgallego** [comment]
> @ejgallego The last time I checked profiling does not work on macOS (or at least I don't know how to set it up without virtualization). Should I file this as an issue?

Of course feel free, even if think it'd be more practical to use the time improving profiling support in Linux.
