### ISSUE TITLE
coqc -schedule-vio-checking mostly doesn't work

### ISSUE THREAD

**Issue by zeldovich** [coq/coq#7044]
#### Version

8.8+alpha (commit ef0fc7730df3cb585b621955010115407d80d2e7)

#### Operating system

Linux (ocaml 4.04.0, kernel 4.13)

#### Description of the problem

```
% cat > Test.v <<EOM
Theorem foo : True.
Proof.
Admitted.
EOM
% coqc -q -quick Test.v
% coqc -q -schedule-vio-checking 1 Test.vio

Error: Can't find file Test.v on loadpath


Error:
Anomaly
"Uncaught exception Failure("The spawned process did not connect back in 2.0s")."
Please report at http://coq.inria.fr/bugs/.

```

**Comment by zeldovich** [comment]
One thing I forgot to mention is that this behavior appears to depend on the size of the `.vio` file.  In particular, in the `Test.v` example from my report above, the `.vio` file is somewhat large (600KB).  On the other hand, if `Test.v` is empty, the resulting `.vio` file is small (1.5KB), and `coqc -schedule-vio-checking` does not report an error.

**Comment by ejgallego** [comment]
@zeldovich have you had success with any previous Coq version?

**Comment by ejgallego** [comment]
Yup, it seems to work in 8.7, likely some missing initialization flag in the toplevel.

**Comment by maximedenes** [comment]
@ejgallego This is tagged as a 8.8.0 blocker. What is your ETA for the fix?

**Comment by ejgallego** [comment]
Can have a look before Monday, it must be something silly (cc: @gares in case he wants to add another set of eyes).

**Comment by gares** [comment]
This fixes it, but I want you to write the final patch.
It seems that in the code path I've fixed below there is no initialization whatsoever (it may make sense to not call `Stm.new_doc`, but some of its code mush be run and I've no idea if the 2 lines I've added are enough... they are for this example).

```diff
diff --git a/toplevel/coqtop.ml b/toplevel/coqtop.ml
index a08cfa9f48..800f58ce29 100644
--- a/toplevel/coqtop.ml
+++ b/toplevel/coqtop.ml
@@ -308,6 +308,8 @@ let compile_files opts =
 (* VIO Dispatching                                                            *)
 (******************************************************************************)
 let check_vio_tasks opts =
+  let iload_path = build_load_path opts in
+  List.iter Mltop.add_coq_path iload_path;
   let rc =
     List.fold_left (fun acc t -> Vio_checking.check_vio t && acc)
       true (List.rev opts.vio_tasks) in
```
