### ISSUE TITLE
ssr: no error message when removing non-existing assumption with a clear switch

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#7050]
#### Version

Coq 8.8+alpha (ef0fc77)

#### Operating system

macOS 10.13.3 High Sierra

#### Description of the problem

Coq does _not_ complain about the undefined name in the clear switch: 

```coq
Example foo : True -> True.
Proof.
move=> {NO_SUCH_NAME} _.
Abort.
```

Coq 8.7.2 outputs an error message in this case:
```
> move=> {NO_SUCH_NAME} _.
> ^^^^^^^^^^^^^^^^^^^^^^^
Error:
Ltac call to "move (ssrmovearg) (ssrclauses)" failed.
No assumption is named NO_SUCH_NAME
```

**Comment by gares** [comment]
Thanks for reporting
