### ISSUE TITLE
How to prepare efficiently the release notes?

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7058]
Twice in a row the preparation of release notes has taken time and has contributed to a delayed beta (8.7+beta1 and 8.8+beta1). How to make the preparation process more efficient?

CHANGES are a good source to look for changes worth to be advertised in the release notes (and now with the PR template they are very infrequently forgotten) but they contain incomplete information: we don't store the author's name in particular.
@maximedenes suggested using a "major feature" label to help triage features to be included in the release notes. It could also be called otherwise like "todo: release notes" so that it is clearer that it's not just about features but also major redesigns, bug fixes and performance improvements... I don't have an opinion whether this is a good solution to this problem.

In any case, I'm opening this issue as a reminder because obviously our process for the release notes isn't currently a good one but since Maxime and I are stepping down for the next (8.9) release, it will be the role of @silene (the RM for 8.9) and @mattam82 (the coordinator of the development team) to decide how to proceed.

(For what worked well, I need to finish writing the release doc.)

Side-notes:
- @mattam82 you used the wrong first commit for 8.8 which gives (IIRC) a slightly different list of contributors. To get the right commit, just use the tag `V8.8+alpha`.
- BTW the tag `V8.9+alpha` has not yet been put AFAICS. Who puts it? I can do it, or @maximedenes or @silene...
- to get an even more accurate list of contributors we should not forget to set the actual author of the commit when we commit on behalf of someone else (I'm thinking in particular of Clément's work for the Sphinx architecture, the Sphinx porting work by various people, Pierre reusing some code first provided by Daniel de Rauglaudre, etc). The command to do that is simple: `git commit --author=<author@example.com>`

**Comment by ejgallego** [comment]
Note that GitHub also supports the [Co-Author](https://help.github.com/articles/creating-a-commit-with-multiple-authors/) method.

**Comment by gares** [comment]
What do you mean by release notes? The credits?

**Comment by Zimmi48** [comment]
I like your view of this @gares and for point 2, we can still credit the authors of the major features in the release notes (in the GitHub release section). Maybe that would be enough.

OTOH, the credits chapter is a good read for someone who wants some history. It's certainly much easier to read than CHANGES.

**Comment by silene** [comment]
> the tag V8.9+alpha has not yet been put AFAICS

Where can I find the definition of the alpha tag for Coq? I never expected that an alpha tag for 8.9 would be put so soon in the development, and certainly not before there even is a 8.9 branch.

**Comment by Zimmi48** [comment]
The release doc is still WIP so please bear with me but the idea of this tag is to mark the very first commit in master and not in v8.8. It was invented for Maxime's development version number PR (that is still unfinished after one full year). The reason for providing such git tag is because the goal of this PR is to use `git describe` to get a version number such as `8.9+alpha-1206-f5gj6hd` for a given development snapshot.

**Comment by SkySkimmer** [comment]
Is this issue still needed?

**Comment by Zimmi48** [comment]
Hum, no I don't think so since the release summary preparation is now moved in the period between the rc and the final release.
