### ISSUE TITLE
coq_makefile TIMED=y output can get intermingled with other text when using -j

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7063]
#### Version

8.7

#### Operating system
Linux

#### Description of the problem

I found lines that look like the following in our build logs:
```
tthheoeroireise/sb/absie/_flioxgpioci/nlti b(/rfeaanlc:y _updates_from_vs (real: 2.55, 2.55u,s eurs:e r: 2.392.35,, s yssy:s :0.19 , 0.15m, emme:m : 534480 529520k ok)o
```
What happens here is that we run with `TIMED=y -j10`, and sometimes (rarely), two of the jobs print their times at the same time and the output gets all messed up.

**Comment by SkySkimmer** [comment]
make's option -O should help with that

Gaëtan Gilbert

**Comment by RalfJung** [comment]
Ah, I did not know about that option, thanks! I added it to our CI. I have not found an explicit statement that this also applies to stderr, but from <https://www.gnu.org/software/make/manual/html_node/Terminal-Output.html> it seems that it does?

**Comment by SkySkimmer** [comment]
Considering
 >GNU make will set the MAKE_TERMOUT and MAKE_TERMERR environment 
 >variables before invoking any commands. Tools which would like to 
 >determine whether standard or error output (respectively) will be 
 >displayed on a terminal can check these environment variables to 
 >determine if they exist and contain a non-empty value.

it certainly redirects stderr

Gaëtan Gilbert

**Comment by RalfJung** [comment]
Great, I guess this can be closed then.
