### ISSUE TITLE
Windows build: strip in lablgtk build can fail randomly

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#7081]
#### Version

All version since 8.5

#### Operating system

Windows

#### Description of the problem

In the windows build symbols are stripped from the lablgtk dll, because otherwise flexdll goes wild. 

$TARGET_ARCH-strip.exe --strip-unneeded src/dlllablgtk2.dll

The dll is locked in Windows for a short time after creation and if a strip is done during this time, the strip fails. With some logging changes this leads to reproducible errors, otherwise this exits only rarely. Fix is to strip during link phase right away with

ocamlmklib -ldopt "-link -Wl,-s"

-ldopt is the okamlmklib linker prefix option
-link is the flexlink linker prefix option
-Wl, is the gcc (linker driver) linker prefix option
-s is the gnu linker option for stripping symbols

Will do a pull request as soon as the script clean up is merged.

**Comment by MSoegtropIMC** [comment]
@gares : can you please review the urgency for this?

Essentially this leads to random failures of the Windows builds on appveyor. Right now such failures are rare but in the past rather minimal changes (especially in logging) did lead to almost 100% failure cause of this.

It is a small change and I can quickly do it, but in case it is not urgent I want to wait for #6809 and/or after 8.8.

**Comment by Zimmi48** [comment]
This shouldn't be a blocker for 8.8 AFAICT. But it would still be good to fix quite soon.

**Comment by gares** [comment]
The sooner we fix it, the better. I agree with @Zimmi48 , it cannot block 8.8.. unless the final commit of 8.8 triggers the issue... and in that case we don't need a label to spot it ;-)

**Comment by MSoegtropIMC** [comment]
O.k, I will prepare a pull request immediately after #6809 is merged (it would likely conflict with it).
Then you have it in case ...

**Comment by MSoegtropIMC** [comment]
Sorry was polishing my Coq skills (got a bit rusted lately) and it is way addictive ;-)
Will do this Wednesday morning.
