### ISSUE TITLE
Coq crashes when inserting `Transparent` in a proof.

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#7088]
To reproduce (on coq/coq@01b7de3a673eb89cea61442c4db721aad9520c9f for example), open CoqIDE on a file containing:

```
Lemma foo : True.
Proof.
(* Transparent id. *)
exact 3.
Qed.
```

then "go to end". Uncomment the `Transparent` command, change `exact 3` into `exact I` and "go to end" again.

@gares is working on a fix

**Comment by gares** [comment]
Is there are a way to test if "id" is opaque? I can't reproduce the bug with fake_ide, and I was trying to make a test (knowing if the transparency attribute has leaked is a way to test I'm using the new code path).

**Comment by gares** [comment]
nevermind, I will use `Arguments`
