### ISSUE TITLE
Coqdoc: make theorem, lemma, definitions clickable to recieve hyperlinks to them

### ISSUE THREAD

**Issue by bollu** [coq/coq#7093]
#### Version
8.7.1

#### Operating system
Ubuntu 14.04

#### Description of the problem

Currently, the only way to get a hyperlink to a particular theorem / definition / lemma is to go to a site of *use*, and then click on it to receive the corresponding hyperlink.

For example, a random theorem from compcert: [`perm_dec`](http://compcert.inria.fr/doc/html/Memory.html#Mem.perm_dec)

To get the hyperlink, I expanded a proof and clicked on the link to `perm_dec` *in the unrelated proof*.

It would be awesome if we could get hyperlinks *directly* by clicking next to the theorem. Perhaps there could be a small symbol on the left margin? The way Github does with the paper clip icon on [`README.md`](https://github.com/coq/coq#documentation) - hover on any of the headings, the paperclip icon appears.

This is possible in Agda AFAIK - For example, [take a look at this example](https://mazzo.li/posts/AgdaSort.html#7214), where we can click on the `Rel` to receive a hyperlink.

I would be happy to give implementing this a shot, if someone could point me in the right direction :)

**Comment by maximedenes** [comment]
This report is probably valid, but note that CompCert's documentation was precisely not generated using coqdoc.

**Comment by herbelin** [comment]
This was trivial to do and it is now done in #12026.
