### ISSUE TITLE
[dev tools] merge-pr.sh doesn't understand --help

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7097]
Please add a `--help` option.

**Comment by ejgallego** [comment]
I guess we'd like to use a proper library for command-line argument parsing, I am not sure what's preferred in Python.

**Comment by SkySkimmer** [comment]
>I guess we'd like to use a proper library for command-line argument parsing, I am not sure what's preferred in Python.

merge-pr.sh is not python.

**Comment by gares** [comment]
As of today it takes no options, and if you pass no arguments it tells you what it expects.
I think the request is a bit overkill

**Comment by herbelin** [comment]
Hesitating to open a new issue for minor `merge-pr.sh` questions and remarks:
- I noticed that it requires git >= 2.7 (for `git remote get-url`)
- I don't know well the differences between `git@github.com:coq/coq` and `https://github.com:coq/coq.git`. Is it important that the origin points to the former exclusively?

Extra note: using gpg on MacOS [was not](https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0) out of the box.

**Comment by herbelin** [comment]
@Zimmi48: Is it expected that the script apparently does not check if the local `master` branch is synchronized with `origin`?

**Comment by Zimmi48** [comment]
Right now it doesn't check indeed but that would be a good check to add.

**Comment by Zimmi48** [comment]
I think it is OK to close this issue as a won't fix (for the original wish).
@herbelin's further comments have been addressed as part of #7102.
