### ISSUE TITLE
[dev tools] merge-pr.sh please provide a way to override REMOTE_URL

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7098]
Some of us may have a different `origin` branch as a safety measure, so it'd be useful to have:
```
merge-pr.sh --remote=official-gh-write-permissions
```

**Comment by Zimmi48** [comment]
If the command line arguments are becoming too complex, it's going to be a hell in bash. The way to override could also be with an environment variable:
`REMOTE=blabla merge-pr.sh`

Note that I also have a safety measure in place but it is a different one: `master` tracks `upstream/master` but my `.gitconfig` contains:

```
[remote]
        pushdefault = origin
```

so by default `git push` always pushes on my fork, and I need `git push upstream` to push to the main repo.

**Comment by ejgallego** [comment]
Indeed, I can also just ignore the warning if you think this change is not worth it.

**Comment by Zimmi48** [comment]
No, that's not what I am saying and I am a bit surprised that you could ignore it and that it worked. The remote of the local branch is used to fetch the pull request so in principle, if it doesn't point to the official Coq repository, you cannot use it to merge a PR on Coq...

**Comment by ejgallego** [comment]
It is pointing to the official Coq repository but in read-only mode.

**Comment by Zimmi48** [comment]
Then I think I understand the problem: cf. #7102
