### ISSUE TITLE
`coqc` reports errors with a location in another file

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#7100]
Tested with coq/coq@01b7de3a673eb89cea61442c4db721aad9520c9f

Steps to reproduce:
```
cat <<EOF > A.v
Ltac foo := apply I.
EOF

cat <<EOF > B.v
Require Import A.
Goal False.
foo.
EOF

coqc A.v
coqc B.v
```

The error message when compiling `B.v` is:
```
File "./A.v", line 1, characters 18-19:
Error: Unable to unify "True" with "False".
```

**Comment by maximedenes** [comment]
@ejgallego do you think that could be due to one of the recent refactorings on locations?

**Comment by ejgallego** [comment]
There has been a lot of movement in the location handling, and not only in my side. I guess we need a bisect, I'll launch one.

In my case, unless I did some mistake, my commits should not introduce an observable change in location propagation [but who knows, maybe I added some extra `?loc` somewhere if thought that'd be a good idea].

**Comment by ejgallego** [comment]
So in fact the first thing that came to my head was PR #1051 and to my surprise it is the one the bisect returns:
```
commit 7f816f00fed5ee7c7e94bd5f02a88880cdfa96aa (HEAD)
Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
Date:   Sat May 6 11:41:33 2017 +0200

    Using an algebraic type for distinguishing toplevel input from location in file.
```
ccing @herbelin as the author of 7f816f00fed5ee7c7e94bd5f02a88880cdfa96aa

**Comment by gares** [comment]
I reviewed the PR again, and I don't see the error :-/

**Comment by ejgallego** [comment]
Likely the change in the semantics of `Loc.merge`

**Comment by ejgallego** [comment]
If you have `SerAPI` master you can easily see how the AST locations are parsed thou.

**Comment by ejgallego** [comment]
The constructor of `parsable` is strange tho.

**Comment by ejgallego** [comment]
This is how the file is read in 8.7:
```lisp
Adding 1 lines
 File "B.v", line 1, characters 0-17:
 (VernacRequire () (false)
  ((Ident
    ((((fname B.v) (line_nb 1) (bol_pos 0) (line_nb_last 1) 
       (bol_pos_last 0) (bp 15) (ep 16)))
     (Id A)))))
Adding 1 lines
 File "B.v", line 2, characters 0-11:
 (VernacGoal
  ((v
    (CRef
     (Ident
      ((((fname B.v) (line_nb 2) (bol_pos 18) (line_nb_last 2)
         (bol_pos_last 18) (bp 23) (ep 28)))
       (Id False)))
     ()))
   (loc
    (((fname B.v) (line_nb 2) (bol_pos 18) (line_nb_last 2) 
      (bol_pos_last 18) (bp 23) (ep 28))))))
 File "B.v", line 3, characters 0-4:
 (VernacExtend (VernacSolve 0)
  ((GenArg raw (OptArg (ExtraArg ltac_selector)) ())
   (GenArg raw (OptArg (ExtraArg ltac_info)) ())
   (GenArg raw (ExtraArg tactic)
    (TacArg
     ((((fname B.v) (line_nb 3) (bol_pos 30) (line_nb_last 3)
        (bol_pos_last 30) (bp 30) (ep 33)))
      (TacCall
       ((((fname B.v) (line_nb 3) (bol_pos 30) (line_nb_last 3)
          (bol_pos_last 30) (bp 30) (ep 33)))
        ((Ident
          ((((fname B.v) (line_nb 3) (bol_pos 30) 
             (line_nb_last 3) (bol_pos_last 30) (bp 30) 
             (ep 33)))
           (Id foo)))
         ()))))))
   (GenArg raw (ExtraArg ltac_use_default) false)))
```

this is how it is read in 8.8:
```lisp
 File "B.v", line 1, characters 0-17:
 (VernacExpr ()
  (VernacRequire () (false)
   (((v (Ident (Id A)))
     (loc
      (((fname (InFile B.v)) (line_nb 1) (bol_pos 0) 
        (line_nb_last 1) (bol_pos_last 0) (bp 15) 
        (ep 16))))))))
Adding 1 lines
 File "B.v", line 2, characters 0-11:
 (VernacExpr ()
  (VernacDefinition (NoDischarge Definition)
   (((v Anonymous)
     (loc
      (((fname (InFile B.v)) (line_nb 2) (bol_pos 18) 
        (line_nb_last 2) (bol_pos_last 18) (bp 18) 
        (ep 28)))))
    ())
   (ProveBody ()
    ((v
      (CRef
       ((v (Ident (Id False)))
        (loc
         (((fname (InFile B.v)) (line_nb 2) (bol_pos 18) 
           (line_nb_last 2) (bol_pos_last 18) (bp 23) 
           (ep 28)))))
       ()))
     (loc
      (((fname (InFile B.v)) (line_nb 2) (bol_pos 18) 
        (line_nb_last 2) (bol_pos_last 18) (bp 23) 
        (ep 28))))))))
Adding 1 lines
 File "B.v", line 3, characters 0-4:
 (VernacExpr ()
  (VernacExtend (VernacSolve 0)
   ((GenArg raw (OptArg (ExtraArg ltac_selector)) ())
    (GenArg raw (OptArg (ExtraArg ltac_info)) ())
    (GenArg raw (ExtraArg tactic)
     (TacArg
      ((((fname (InFile B.v)) (line_nb 3) (bol_pos 30) 
         (line_nb_last 3) (bol_pos_last 30) (bp 30) 
         (ep 33)))
       (TacCall
        ((((fname (InFile B.v)) (line_nb 3) (bol_pos 30) 
           (line_nb_last 3) (bol_pos_last 30) (bp 30) 
           (ep 33)))
         (((v (Ident (Id foo)))
           (loc
            (((fname (InFile B.v)) (line_nb 3) (bol_pos 30) 
              (line_nb_last 3) (bol_pos_last 30) (bp 30) 
              (ep 33)))))
          ()))))))
    (GenArg raw (ExtraArg ltac_use_default) false))))
```

**Comment by herbelin** [comment]
That's indeed a bit worrying, sorry about that.

In 8.7, we were able to merge locations coming from different files without noticing it (i.e. if the location of `I` in `A.v` had been strictly included in the location of `foo` in `B.v`, then, one would have reported about the location of `I` in `A.v` but pretending it is in `B.v`). I introduced a test that the file is the same before merging locations but I did not catch the failure coming from this test :(

By the way, I wonder: what should be the expected message? Should it be just as before
```coq
File "./B.v", line 3, characters 0-3:
Error:
In nested Ltac calls to "foo" and "apply I", last call failed.
Unable to unify "True" with "False".
```
or should it mention also the position of the code of the tactic which failed. I feel that Ltac (Ltac2?) debugging would be easier if the location of the source of the tactic were also given, as in the following possibility:
```coq
File "./B.v", line 3, characters 0-3:
Error:
In nested Ltac calls to "foo" and "apply I", last call failed.
Unable to unify "True" with "False".
Failing position in the source of `foo`: file "./A.v", line 1, characters 18-19.
```
Or maybe it would be too confusing?

**Comment by ejgallego** [comment]
I am not sure `Loc.merge` should be throwing an exception. IMVHO exception / error handling is messy enough as it is as to add more cases. As highlighted by this bug the exception was lost, and OCaml lacks the proper type features to make this principled over a codebase of 100.000 of lines using `Loc.t`.

IMHO one of the few "big checkpoints for PRs" should indeed be that new code doesn't introduce exceptions.

I suggest we either make `Loc.merge` into an option type, or think a bit more about what the semantics for merge should be.
