### ISSUE TITLE
Purpose of the 8.9+alpha1 milestone.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7122]
Right now, we have three active milestones: `8.8.0`, `8.9+alpha1` and `8.9`. While the purpose of the first one should be pretty clear (it's for things which are targeted at 8.8.0 and thus should be backported to v8.8 before the release), the two other seem quite redundant and there is some confusion on their respective use.

The `8.9+alpha1` milestone was created a few weeks ago by @ejgallego following a comment of mine on Gitter: https://gitter.im/coq/coq?at=5aa0feede4d1c63604d6d8b1

However my personal feeling is that it was not a very good idea to create this milestone without attaching a clear semantics to it. In particular, right now it has no due date which seems to me like a bad idea.

In my mind there were two ideas:
- We should avoid having just one freeze one week before the beta and everyone rushing to get their PRs in. My proposal was to have several freezes (starting maybe one month before the beta), the first one being for the most API-invasive PRs and down to very small features for the last one. However, if @silene confirms is willingness to be the RM for 8.9, it should be his decision alone how to proceed on this.
- Some developers need deadlines. Thus we could setup some intermediary deadlines but it's not clear how this would work if these deadlines are not actual dead-lines (i.e. one can miss them without any consequence). So I'm not so convinced by this idea anymore.

Two more comments showing how confusing this intermediary milestone is for everyone:
- https://github.com/coq/coq/issues/6954#issuecomment-372694777
- https://github.com/coq/coq/issues/4398#issuecomment-377274868

So let's discuss these ideas but unless we can see a clear advantage to this, we should probably merge the two milestones together.

Some info about how milestones were handled during the 8.7 period:
- There was a `8.7` milestone which was eventually renamed into `8.7+beta1` when the freeze was approaching; the same happened with the `8.8` milestone. The idea here is these were initially "blurry" deadlines but when the beta was approaching it was becoming more concrete...
- `8.7.0` / `8.8.0` were created to mark what would go in the final release but happened after the beta (BTW the initial `8.7.0` milestone was renamed `8.7+beta2` milestone when it became clear that there would be a second beta and a new `8.7.0` milestone was created).

Milestones are useful to manage the release, but also to go back and look at what got in there. I'm not sure they will be useful to manage more fine-grained work organization.

**Comment by herbelin** [comment]
> Some developers need deadlines. Thus we could setup some intermediary deadlines but it's not clear how this would work if these deadlines are not actual dead-lines (i.e. one can miss them without any consequence). So I'm not so convinced by this idea anymore.

Being one of those whom deadlines help, as already said, I learnt the lesson of the 8.8 misunderstanding and stopped thinking at a freeze date as a date for feature convergence. I proposed at some time that we could have feature convergence deadlines based on some objectives on which we specifically concentrate for some delimited period of time, but, if it does not echo to somebody else interests, I'll manage my "beta" deadlines (and their "alpha" margin) myself. In particular, I'm ok with the idea that for an "alpha" to make sense, more than one person would have to be interested.

Otherwise, about possibly adopting in some cases a feature-oriented approach, maybe a good example of is the translation of the reference manuall to sphinx. This is obviously a matter of joint/concerted convergence between a freeze and a feature.

**Comment by ejgallego** [comment]
I created that milestone as to have a "8.8+beta1" equivalent for 8.9 when remilestoning bugs, that is.

Indeed I wanted to avoid putting all my issues / PR in 8.9 then just to move them back to `8.9+beta1`. So IMHO the milestone should be kept, and a date and maybe a rename done by the RM.

**Comment by Zimmi48** [comment]
Well I'm very unhappy of the way the Sphinx migration was coordinated and that it had to be finished between the beta and the final release so don't get me started on this topic ;-)

**Comment by silene** [comment]
> However, if @silene confirms is willingness to be the RM for 8.9, it should be his decision alone how to proceed on this.

As I explained during the phone call, I intend to keep the procedure quite simple. At the time I branch for 8.9, either a pull request is in, or it is not. I will obviously backport bugfixes after branching, but I will be more inclined to revert large pull requests from the branch than to merge new ones. If contributors feel that tags help them to better organize their work, that is fine with me, but I will certainly not use them as a criteria for inclusion.

**Comment by ejgallego** [comment]
So I guess @silene then you should close this bug with the resolution you deem fit. A milestone is something associated to a date, so indeed you could keep a milestone for the branching date and other for the release date, or else remove them altogether.

**Comment by Zimmi48** [comment]
Done. All issues / PRs in the 8.9+alpha1 milestone have been moved back to the 8.9 milestone and the 8.9+alpha1 milestone has been removed.

**Comment by ejgallego** [comment]
> it shall be removed in favor of the way @maximedenes and I did it during the last two releases.

I don't understand,  in the last release you had a `beta1` milestone, right?

**Comment by Zimmi48** [comment]
Quoting myself from the initial comment in this issue:

> There was a `8.7` milestone which was eventually renamed into `8.7+beta1` when the freeze was approaching; the same happened with the `8.8` milestone. The idea here is these were initially "blurry" deadlines but when the beta was approaching it was becoming more concrete...

This should be made clear in the release doc.

**Comment by ejgallego** [comment]
I am sorry but I don't understand / see the point of having a milestone just to rename it later. This is like the most confusing thing one can do. If you plan to rename it, use the right name from the start.

**Comment by Zimmi48** [comment]
OK, let's rename it right now.
