### ISSUE TITLE
Find all regressions of Sphinx migration due to porting outdated chapters.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7123]
What remains to be done to complete the Sphinx migration?

For my part, I have reviewed all the post-beta migration PRs (using each time the second commit to try to spot regressions that could have happened during the migration). I haven't done so for what was merged before the beta.

There is a real risk of having lost things during the migration because the people who ported the chapters often started from an outdated version. Even if I have already spotted some of these regressions, I may have missed some (in particular small changes which are not a complete addition / removal of a paragraph). To make sure that there are no such regressions, the only way is IMHO for each ported chapter:
1. Determine what version was used for porting the chapter (8.7.0, 8.7.1, 8.7.2, more recent or even earlier?)
2. Take the commit log between this version (or the diff), e.g.: `git diff V8.7.0..1f2a922d52251f79a11d75c2205e6827a07e591b -- doc/refman/RefMan-xxx.tex`
3. Ensure (preferably on the rendered version) that the ported chapter did not lose any of these updates.

This is an important work which can be split between developers.

Other things to check before the final release: *moved to the GitHub project*

**Comment by maximedenes** [comment]
Please add these items in https://github.com/coq/coq/projects/16

**Comment by Zimmi48** [comment]
I can add the four items about the index but the goal of this issue is to coordinate on the first part (backporting changes that came to the refman after the version that was ported). This is something that needs to be split between many developers to be doable and a GitHub project has proved to be an efficient way of organizing one's work (or two people's work) but certainly not a way to coordinate at a larger scale (in particular, cards without corresponding issues cannot be assigned).

**Comment by ejgallego** [comment]
Yup so lets open a set of issues with the precise review instructions for each chapter, it's better if someone who is familiar with the Sphinx migration does it.

**Comment by Zimmi48** [comment]
No, I don't think that a bunch of issues is needed here. I apparently failed to express myself correctly. But a Sphinx migration issue has been lacking all along (should have been created back at the beginning of the 8.8 porting effort).

**Comment by Zimmi48** [comment]
I think it is now completely unrealistic to think that this can be fixed for 8.8.0 but let's not forget about it. I'll try to give more precise guidelines.
