### ISSUE TITLE
Warning message "Ignoring implicit status" does not provide line number

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#7124]
#### Description of the problem

The warning message "Ignoring implicit status of product binder cs and following binders"
does not say what file name and line number, unlike most warning messages.  That makes it difficult
to track down!   (If you fix this one, perhaps search the source code for all other warning messages with
the same problem.)

```
(* in VST,  floyd/closed_lemmas.v, any version between January 1 and March 29, 2018 *)
Definition expr_closed_wrt_lvars (S: ident -> Prop) (e: expr) : Prop :=
  forall {cs: compspecs} rho ve',
     (forall i, S i \/ Map.get (ve_of rho) i = Map.get ve' i) ->
     eval_expr e rho = eval_expr e (mkEnviron (ge_of rho) ve' (te_of rho)).
```

**Comment by herbelin** [comment]
Is anyone already on it? A priori very simple to do.

**Comment by maximedenes** [comment]
I'm having a look at it.

**Comment by maximedenes** [comment]
See #7129. We still have a few other direct calls to `Feedback.msg_warning` that should be audited.
