### ISSUE TITLE
error with no safe_id attached: Cannot undo.

### ISSUE THREAD

**Issue by Gurkenglas** [coq/coq#7137]
#### Version

CoqIDE 8.8+beta1

("You can get this information by running `coqtop -v`." <- I don't know how to do that from the Coq Ide.)

#### Operating system

Windows 10 64-bit

#### Description of the problem

This file:

``` Undo. ```

throws:

Anomaly "error with no safe_id attached: Cannot undo." Please report at http://coq.inria.fr/bugs/.

That site is down, so I came here.

**Comment by SkySkimmer** [comment]
>That site is down, so I came here.

http://coq.inria.fr/bugs/ redirects here so it's fine ;)

**Comment by Zimmi48** [comment]
Duplicated in #7353.
