### ISSUE TITLE
Vernacular commands should never emit Error: Currently, the parsing api only supports parsing at the tip of the document.  You wanted to parse at: 3 but the current tip is: 2023

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7142]
#### Version

8.8+beta1

#### Operating system

Linux

#### Description of the problem

If, after triggering #7140, I try to execute any command, I get an error message like "Error: Currently, the parsing api only supports parsing at the tip of the document.  You wanted to parse at: 3 but the current tip is: 2023".  This results in me having to quit Coq and restart it from scratch if I ever want to interrupt printing, which is unreasonable.

**Comment by ejgallego** [comment]
This is fixed in `master`, second, after an anomaly, the system is in random state so we cannot guarantee that you can continue your session.

**Comment by ejgallego** [comment]
On the other hand master may enjoy of a small tweak as to guard goal printing better.

**Comment by ejgallego** [comment]
After thinking a bit more, I consider this bug valid, but not as critical as it looks as the desynch in master will be corrected after a bit [in a sense it is a problem of the proof protocol the toplevel/emacs use]
