### ISSUE TITLE
Extraction generates "assert false" at top level

### ISSUE THREAD

**Issue by akr** [coq/coq#7191]
#### Version

```
% coqtop -v
The Coq Proof Assistant, version 8.7.2 (March 2018)
compiled on Mar 13 2018 2:25:05 with OCaml 4.05.0
```

#### Operating system

```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```

#### Description of the problem

Extraction generates "assert false" at top level as follows.

```
Definition f (x : False) : bool -> bool := match x with end.
Definition g (f : False -> bool -> bool) := tt.
Definition h (_ : unit) := g f.
Require Extraction.
Require ExtrOcamlBasic.
Recursive Extraction h.
(*
type __ = Obj.t

(** val f : bool -> bool **)

let f =
  assert false (* absurd case *)

(** val g : (__ -> bool -> bool) -> unit **)

let g _ =
  ()

(** val h : unit -> unit **)

let h _ =
  g (fun _ -> f)
*)
```

The problem is "let f = assert false" which raises
an exception at defining this program.
If the exception is raised at invocation time of f, we can use "h"
without problem (because "h" doesn't invokes "f").

I think it should have an argument as "let f _ = assert false".
Actually following example works fine.
It differs that "f" returns bool instead of bool->bool.

```
Definition f (x : False) : bool := match x with end.
Definition g (f : False -> bool) := tt.
Definition h (_ : unit) := g f.
Require Extraction.
Require ExtrOcamlBasic.
Recursive Extraction h.
```

**Comment by pi8027** [comment]
This condition seems to be wrong. I will investigate how it works.
https://github.com/coq/coq/blob/c70412ec8b0bb34b7a5607c07d34607a147d834c/plugins/extraction/mlutil.ml#L357

**Comment by pi8027** [comment]
I did some investigation of this today. The body of `f` is η-expanded by `Extraction.extract_std_constant` then η-reduced by `Mlutil.simpl`. So we need to fix `Mlutil.simpl.`
