### ISSUE TITLE
Print Assumptions confused by nested modules

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#7192]
#### Operating system: Windows
In the following program, `Print Assumptions E.D.f` should report "closed" but wrongly believes that `E.D.f` is an axiom.

```
Definition a := True.

Module Type B.
Axiom f : Prop.
End B.

Module Type C.
Declare Module D : B.
End C.

Module E: C.
Module D <: B.
Definition f := a.
End D.
End E.

Print Assumptions E.D.f.
  (* Axioms: 
      E.D.f : Prop
  *)
Print Assumptions a.
  (* Closed under the global context *)
```

**Comment by herbelin** [comment]
Hi @andrew-appel, I think you mean `E <: C`. Otherwise your redefinition of `D` is not taken into account.

**Comment by andrew-appel** [comment]
But I claim that E.D.f is supported by a proof, that is, "a" is a witness for "f", and therefore "f" is not an assumption.  I should be able to have an opaque module that has a proof, a witness, for its implementation.

**Comment by herbelin** [comment]
You're right, this is a bug. `Print Assumptions` looks at the implementation of modules (bypassing the apparent signature) but it does so only at the first level of nesting. This should be extended to submodules.
