### ISSUE TITLE
Module Type and universe polymorphism

### ISSUE THREAD

**Issue by davidnowak** [coq/coq#7204]
#### Version

8.7.2

#### Description of the problem

The code :

    Set Universe Polymorphism.
    
    Module Type FOO.
    Parameter t : Type -> Type.
    End FOO.
    
    Module Foo <: FOO.
    Definition t (A : Type) : Type := A.
    End Foo.

gives the error :

    Signature components for label t do not match:
     the expected (polymorphic) constraints do not imply "Top.3 <= Top.4
                                                         ".

There is no error if universe polymorphism is not set.

**Comment by SkySkimmer** [comment]
This is intended behaviour. Module type `FOO` has a constant `t@{u v} : Type@{u} -> Type@{v}` which is defined for any 2 universes, but in `Foo` it is only defined when `u < v`.
You can restrict the module type by telling it about these constraints:
```coq
(* Syntax introduced in 8.8 *)
Parameter t@{u v|u < v} : Type@{u} -> Type@{v}.

(* going through sections for 8.7 *)
Section Sec.
Universes u v.
Constraint u < v.
Parameter t : Type@{u} -> Type@{v}.
End Sec.
```
