### ISSUE TITLE
MacOS test-suite job started failing a few hours ago

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7206]
First failure on `master`: https://travis-ci.org/coq/coq/jobs/364005459

```
==> Downloading https://homebrew.bintray.com/bottles/gnu-time-1.9.sierra.bottle.tar.gz
==> Pouring gnu-time-1.9.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gnu-time/1.9: 9 files, 116.3KB
The command "brew install opam gnu-time" failed and exited with 1 during .
```

It seems that `opam` was installed correctly (before) and that the installation fails during the `gnu-time` install step but without an error message.

**Comment by Zimmi48** [comment]
Actually the error is rather in the installation of `opam`: its listed dependencies changed between the last successful build from `ocaml, ocamlbuild, camlp4, clingo, aspcud` to `ocaml, ocamlbuild, camlp4, gdbm, openssl, sqlite, python@2, clingo, aspcud`.

And the failure is in the installation of Python:

```
==> Installing opam dependency: python@2
==> Downloading https://homebrew.bintray.com/bottles/python@2-2.7.14_3.sierra.bottle.1.tar.gz
==> Pouring python@2-2.7.14_3.sierra.bottle.1.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-2
Target /usr/local/bin/2to3-2
is a symlink belonging to python. You can unlink it:
  brew unlink python
To force the link and overwrite all conflicting files:
  brew link --overwrite python@2
```

**Comment by Zimmi48** [comment]
And the culprit is: https://github.com/Homebrew/homebrew-core/pull/26289/files#diff-37519cd632d87df0a1be3ca7de23228e

**Comment by Zimmi48** [comment]
I hate Homebrew!

**Comment by ejgallego** [comment]
> I hate Homebrew!

Is there any other alternative?

**Comment by maximedenes** [comment]
> Is there any other alternative?

I'm pretty sure you're waiting for @Zimmi48 or I to say "of course, there's Nix", so I won't say it :)

**Comment by ejgallego** [comment]
Oh if Nix for OSX works, why not?

**Comment by Zimmi48** [comment]
> I'm pretty sure you're waiting for @Zimmi48 or I to say "of course, there's Nix", so I won't say it :)

Actually, I was expecting @maximedenes to say it. That's why I didn't ;-)
Rethinking the CI to use Nix instead of OPAM / brew is not in my priorities but of course I would support it if someone submitted a patch.
