### ISSUE TITLE
install complains because of a few not compiled ml files

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7214]
eg in https://gitlab.com/SkySkimmer/coq/-/jobs/62215853
```
install: cannot stat 'clib/deque.cmi': No such file or directory
...
install: cannot stat 'clib/deque.cmx': No such file or directory
install: cannot stat 'plugins/extraction/big.cmx': No such file or directory
install: cannot stat 'toplevel/coqtop_byte_bin.cmx': No such file or directory
```
deque has never been used, not sure about the others.

**Comment by Zimmi48** [comment]
Which version? Is it a new bug or an older one? 8.9-regression?

**Comment by fbrausse** [comment]
Same warnings for the released version 8.8.0 (on Gentoo, `GNU Make 4.2.1`, `Camlp5 version 6.17 (ocaml 4.04.2)`) when executing `make && make install`

For v8.7.2 (tarball from the inria mirror) I get these:
```
/usr/bin/install: cannot stat 'plugins/extraction/big.cmx': No such file or directory
/usr/bin/install: cannot stat 'revision': No such file or directory
```

**Comment by ejgallego** [comment]
That's bug #6354

**Comment by andrew-appel** [comment]
This bug is blocking the installation of Coq 8.8.0 on our Linux servers.  Is there a recommended workaround?

**Comment by SkySkimmer** [comment]
>This bug is blocking the installation of Coq 8.8.0 on our Linux servers. Is there a recommended workaround?

See #7406.
