### ISSUE TITLE
Name resolution not the same with coqc or coqtop

### ISSUE THREAD

**Issue by vbgl** [coq/coq#7226]
#### Version

```
The Coq Proof Assistant, version 8.8+alpha (April 2018)
compiled on Apr 12 2018 8:58:44 with OCaml 4.05.0
```

#### Operating system

OS X 10.11.6 (15G20015)

#### Description of the problem

I’ve two modules with the same name, one of them being from a third-party library. The second one uses the first one; some partially qualified names are resolved differently by `coqtop` (to the other module) and by `coqc` (to the current module). Here is a full example.

`L/a.v`:
```
Definition x := True.
```

`a.v`:
```
From Library Require Import a.

Definition x := False.

Lemma test : x = a.x.
Proof. reflexivity. Qed.
```

```
coqc -R L Library L/a
coqc -R L Library a
coqtop -R L Library -l ./a.v
Welcome to Coq 8.8+alpha (April 2018)
File "./a.v", line 6, characters 7-18:
Error: Unable to unify "a.x" with "x".
```

**Comment by ejgallego** [comment]
Is that a regression?

**Comment by vbgl** [comment]
```
Welcome to Coq 8.7.2 (April 2018)
Error during initialization: File "./a.v", line 6, characters 7-18:
Error: Unable to unify "a.x" with "x".
```

```
Welcome to Coq 8.6.1 (April 2018)
Error during initialization:
File "./a.v", line 6, characters 7-18:
Error: Unable to unify "a.x" with "x".
```

```
Welcome to Coq 8.5pl3 (April 2018)
Error during initialization:
File "./a.v", line 6, characters 7-18:
Error: Unable to unify "a.x" with "x".
```

```
Welcome to Coq 8.4pl6 (April 2018)
Error during initialization:
File "./a.v", line 1, characters 0-30:
Error: Unknown command of the non proof-editing mode.
```

After fixing the `From …` line, I still get the same error (unable to unify…) with Coq 8.4.

**Comment by herbelin** [comment]
The command `coqc` is interpreting a module `A` within `A`. The command `coqtop` is loading the file within a module conventionally named `Top`. Try adding `-top A` to the `coqtop` invocation to tell it to load within a module named `A`.

**Comment by vbgl** [comment]
Indeed, adding `-top a` on the command line for `coqtop` makes both `coqtop` and `coqc` behave in the same way.

Should ProofGeneral (and other IDEs) invoke `coqtop` with such a `-top` flag? In other words, is this issue a ProofGeneral one?

**Comment by ejgallego** [comment]
> Should ProofGeneral (and other IDEs) invoke coqtop with such a -top flag? In other words, is this issue a ProofGeneral one?

IMHO the `-top` flag is deprecated for IDEs, in the sense that it is in the init document call where the module name should be specified.

Indeed, IDEs should properly initialize a document, but until we don't add full file support to them it is kind of a moot point. SerAPI does tho provide partial support and a new init call is coming to it; however some other pieces are missing to properly implement file-backed interactive buffers. [Such as proper error handling, for example.]

**Comment by ejgallego** [comment]
This got as improved as we could with the introduction of `-topifle` in #8991
