### ISSUE TITLE
coq/MERGING.md is incorrect

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7232]
#### Version

57c1eb50c370c894fda1a62ca27d7210982ac3fd

#### Operating system

Linux

#### Description of the problem

MERGING.md says to use `dev/tools/merge-pr XXXX`, but that is an error, and the command should actually be `./dev/tools/merge-pr.sh`.

**Comment by Zimmi48** [comment]
Yes this was noticed before and there is an open PR fixing this already. If you locate it, feel free to edit the top comment to auto close this issue when it is merged.
