### ISSUE TITLE
appcontext removed in 8.8?

### ISSUE THREAD

**Issue by Chobbes** [coq/coq#7243]
#### Version

The Coq Proof Assistant, version 8.8+beta1 (March 2018)
compiled on Mar 28 2018 7:01:51 with OCaml 4.05.0

#### Operating system

Linux

#### Description of the problem

Hi there! I noticed that appcontext seems to have been removed in this release? I believe it has been marked as deprecated for a while, so I suspect it was intentionally removed, however there is no mention of this in CHANGES. I think that this should be added to the CHANGES file just in case people get confused about this upon upgrading (like I did)!

I found this by trying to build Paco:

``
coqdep -c -slash -R . Paco "pacotacuser.v" > "pacotacuser.v.d" || ( RV=$?; rm -f "pacotacuser.v.d"; exit ${RV} )
warning: option -slash has no effect and is deprecated.
coqc  -q  -R . Paco   pacotacuser
File "./pacotacuser.v", line 84, characters 18-19:
Error: Syntax error: ',' or '|-' expected (in [match_context_rule]).
``

**Comment by Zimmi48** [comment]
Indeed it was removed in #6169. And sorry about forgetting to add a mention in CHANGES.
