### ISSUE TITLE
Standardize handling of implicit arguments of inductive types in constructors

### ISSUE THREAD

**Issue by jashug** [coq/coq#7253]
#### Version
Coq 8.8+beta1

#### Description of the problem

Implicit parameters of inductive types get by default the parameter value in their definition, rather than being inferred. This leads to behavior like the below:

```coq
Fail Inductive foo {A : Set} (a : A) : Set :=
  sup : foo 3 -> foo a
.
(*
In environment
foo : forall A : Set, A -> Set
A : Set
a : A
The term "3" has type "nat"
while it is expected to have type 
"A".
*)

Inductive foo {A : Set} (a : A) : Set :=
  sup : foo (A:=nat) 3 -> foo a
.
(* succeeds *)
```

I think this is rather unintuitive. On the other hand, it allows to write things like
```
Inductive bar {A : Set} : Set
  := sup_bar : A -> bar -> bar.
```
without having to specify the parameter of bar in either the parameters or the conclusion of `sup_bar`.

In the conclusion, the we are restricted to `bar (A := A)`, but in the parameters, we can take `bar (A := B)`, turning `A` into a non-uniform parameter.

This is also the root cause of some of the problems in https://github.com/coq/coq/issues/6786

This behavior is caused by https://github.com/coq/coq/blob/15331729aaab16678c2f7e29dd391f72df53d76e/interp/constrintern.ml#L59-L61

My inclination is to remove this behavior, reducing the code complexity and standardizing how implicit arguments work. I don't know how often it is used in practice, so looking at the CI should be informative.

**Comment by jashug** [comment]
If the implicit argument is not inferable, options like `Set Implicit Arguments` won't make it implicit. So to get any benefit from this, it seems like the user would have to manually set some non-inferable parameter implicit with curly brace binders. If that is the only relevant case, this seems an unhelpful feature.

**Comment by jashug** [comment]
So this is actually used with some frequency in practice.
See failures in https://travis-ci.org/jashug/coq/builds/366674182

In most of the cases I looked at, if we could add as unification constraints that the parameters in the conclusion are `Rel i` (for known `i`), there would be no problem.

Summoning @mattam82 to ask how hard that would be.

**Comment by jashug** [comment]
Computing the head-normal form of constructors doesn't happen until the kernel, but we would need to compute that much to get access to the parameters, in order to add unification constraints before solving.

I suppose that requires either moving the computation of the head normal form out of the kernel (which introduces more places to break the invariant) or duplicating computing the head normal form: once before running unification and once after in the kernel (potentially slow).

On the other hand, I'm convinced that using unification is the right solution here, rather than the current hack.

**Comment by herbelin** [comment]
@jashug: I don't know what you have in mind when you say that you could implement the feature with unification. In any case, I believe that it is still possible to fix the current issue at the level of `constrintern.ml` by a minor change, namely by `reset_hidden_inductive_implicit_test`-ing as soon as going in contravariant position of a dependent product (e.g. in `intern_local_binder_aux`) and by not adding the implicit arguments when the check is deactivated.

**Comment by jashug** [comment]
Consider the below example. With `A` implicit, why should there be a difference between `@I _ a` and `I a`?
```
Fail Inductive I {A} : A -> Type := C a : @I _ a.
Inductive I {A} : A -> Type := C a : I a.
```

What I propose by unification is, if the type of `C` is internalized to `forall A (a : ?T), @I ?S a` we add the unification constraint `?S = A`. From the type of `I`, we also have the constraint `?T = ?S`, so this now has a unique solution.

**Comment by jashug** [comment]
This is really a different subsystem, but behaviour like this could also be eliminated with a head-reduction pass before the kernel:
```coq
Definition id {A : Type} (a : A) := a.
Inductive I1 := C1 : _.
Inductive I2 := C2 : id I2.
Fail Inductive I3 := C3 : id _.
```
See https://github.com/coq/coq/blob/c291a8829556dc2a61fcacc08b34e1d68d66b89e/vernac/comInductive.ml#L40-L52
which performs a weak version of unification even before internalization, but doesn't reduce.

**Comment by herbelin** [comment]
So, instead of adding arguments on the fly at "intern" time, to match the conclusion of the constructor with its expected form. Sounds like a good idea, indeed.

**Comment by jashug** [comment]
I had a go at using unification, see #7254.

**Comment by jashug** [comment]
One change using unification gives is that type-class search now runs before these parameters are filled in.
(what calls type-class resolution?) That broke compcert, with the example:
```
Class Linker (A : Type) := {
  linkorder : A -> A -> Prop
}.

Inductive globdef (F V : Type) : Type :=
  | Gfun (f : F)
.
Arguments Gfun [F V].

Inductive linkorder_def {F V : Type}
  {LF : Linker F} {LV : Linker V}
  : globdef F V -> globdef F V -> Prop :=
  | linkorder_def_fun : forall fd1 fd2,
      linkorder fd1 fd2 ->
      linkorder_def (Gfun fd1) (Gfun fd2)
.
(*
In environment
linkorder_def :
forall F V : Type,
Linker F ->
Linker V ->
globdef F V -> globdef F V -> Prop
F : Type
V : Type
LF : Linker F
LV : Linker V
fd1 : V
fd2 : V
l : linkorder fd1 fd2
Unable to unify "linkorder_def V V LV LV"
with "linkorder_def F V LF LV".
*)
```

But it turns out fiat-crypto, fiat-parsers, and software foundations (in a negative example) at least are relying on the heuristic implementation (manually turning non-inferable parameters implicit, and relying on them being inserted as uniform parameters).

My opinion is that changing to unify with the expected conclusion is a more principled implementation that avoids unintuitive failures such as
`Fail Inductive foo {A : Set} (a : A) : Set := sup : foo 3 -> foo a.`
`Fail Inductive I {A} : A -> Type := C a : @I _ a.` and
`Fail Inductive I3 := C3 : id _.`

But it is clearly not a change without consequences.
