### ISSUE TITLE
ssr: anomaly occurs when trying to rewrite with a logical equivalence

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#7255]
#### Version

Coq master (4c466c429902d0ef0bd0da0f42e1a3b6d9f7d32a)

#### Operating system

macOS 10.13.3 High Sierra

#### Description of the problem

Please consider the following minimized example:

```coq
From Coq Require Import ssreflect Setoid.

Structure SEProp := {prop_of : Prop; _ : prop_of <-> True}.

Fact anomaly: forall P : SEProp, prop_of P.
Proof.
move=> [P E].
rewrite E.
```

`rewrite E` produces an anomaly:

>Error: Anomaly "cvtac's exception: Pretype_errors.PretypeError(_, _, _)"
>Please report at http://coq.inria.fr/bugs/.

Obverse that if I simplify the goal, then the anomaly goes away:
```coq
Fact no_anomaly: forall P : SEProp, prop_of P.
Proof. by move=> [P /= ->]. Qed.
```

Also, it seems that the usage of SSReflect is essential here, because 
```coq
From Coq Require Import Setoid.
Structure SEProp := {prop_of : Prop; _ : prop_of <-> True}.

Fact no_anomaly2: forall P : SEProp, prop_of P.
Proof. intros [P E]. Fail rewrite E. Abort.
```

results in the following error message:

> build_signature: no constraint can apply on a dependent argument

**Comment by ejgallego** [comment]
@anton-trunov can you check if this is a regression? Thanks.

**Comment by anton-trunov** [comment]
@ejgallego With Coq 8.7.2 instead of the anomaly it outputs:
```
Error:
Ltac call to "rewrite (ssrrwargs) (ssrclauses)" failed.
Illegal application: 
The term "Build_SEProp" of type
 "forall prop_of : Prop, prop_of <-> True -> SEProp"
cannot be applied to the terms
 "_pattern_value_" : "Prop"
 "E" : "P <-> True"
The 2nd term has type "P <-> True" which should be coercible to
 "_pattern_value_ <-> True".
```

**Comment by anton-trunov** [comment]
I can bisect to pinpoint the issue, but closer to the end of this week.

**Comment by ejgallego** [comment]
Thanks @anton-trunov , so do you consider the 8.7.2 behavior correct? If so, that looks like a regression.

**Comment by anton-trunov** [comment]
@ejgallego Oh, sorry I forgot to mention that. Yes, I consider the 8.7.2 behavior correct because if the rewrite succeeded we would get the following state:
```coq
  E : P <-> True
=========
prop_of (Build_SEProp True E).
```
but `Build_SEProp True E` is ill-typed.

I've learned about that anomaly by accident -- I initially forgot to put `/=` between destruction and rewrite.
