### ISSUE TITLE
Improve CHANGES for #7025

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7258]
#7025 broke a part of fiat which we don't test in CI because COQFLAGS does not include COQLIBS anymore.

This change should be made explicit.

**Comment by maximedenes** [comment]
@gares or @RalfJung could you add a `CHANGES` entry ASAP? Thanks!

**Comment by RalfJung** [comment]
PR submitted: https://github.com/coq/coq/pull/7263

No idea if that is right...

**Comment by maximedenes** [comment]
I believe the milestone is wrong here, as this is a 8.9 bug.
