### ISSUE TITLE
ssr: the order of imports affects rewrite tactic

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#7283]
#### Version

Coq 8.8.beta (6a929e8b94fc95f81699668cea95bc4b91ec67ca)

#### Operating system

macOS 10.13.3 High Sierra

#### Description of the problem

The following piece of code

```coq
From mathcomp Require Import eqtype seq.
From Coq Require Import ssreflect ssrbool.

Lemma foo (A : eqType) (x : A) : x \in [:: x].
Proof.
Fail rewrite inE.
Abort.
```

fails with 

>Error:
>Ltac call to "rewrite (ssrrwargs) (ssrclauses)" failed.
>The LHS of `inE` does not match any subterm of the goal

However, if the imports are in their "natural" order
```coq
From Coq Require Import ssreflect ssrbool.
From mathcomp Require Import eqtype seq.
```

then that rewrite works.

We hit this issue when trying to use this new `Export Set` feature.

**Comment by gares** [comment]
I know nothing about `Export Set` but here the problem is that `inE` is defined in 2 files you import. Hence the order matters: if fails because you get the `inE` from `ssrbool` rather than the one from `seq` (the one from `seq` extends the one from `ssrbool` so you always want to use the latter).

I guess that if you write `seq.inE` things will work.

**Comment by anton-trunov** [comment]
Oh, yes, you are right it works. I was thinking you used some other extension mechanism. But now that I checked I can see that the order of imports indeed matters. Thank you!

**Comment by anton-trunov** [comment]
@gares Btw, may I ask if there is a reason why `inE` couldn't have been implemented via canonical structures? (My guess is if that was possible the order of imports wouldn't have mattered).

**Comment by gares** [comment]
I think you may be right, IIRC some rewrite rules like `unlock` are indeed made "generic" thanks to CS.

Still multi rules like `inE` are very simple to understand (just nested pairs of equations), while for CS you need a black belt, that you probably have right now, but still...

**Comment by anton-trunov** [comment]
@gares Thanks a lot! Some food for thought...
