### ISSUE TITLE
Guarded relies on non-ground EConstr

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#7286]
Since the merge of #6454, the `Guarded` command is essentially useless, because it relies on term normalization that contain evars, and raises an anomaly as soon as there is an open goal.

```
Goal True.
Guarded.
(** Anomaly "grounding a non evar-free term" *)
```

**Comment by ejgallego** [comment]
Maybe #6874 is also related to this?

**Comment by ejgallego** [comment]
Running with `-debug` will blame the corresponding call to `to_constr` that is not setting the flag.
