### ISSUE TITLE
Links to addendum section of documentation are broken

### ISSUE THREAD

**Issue by yforster** [coq/coq#7307]
The URL of the program section in the documentation used to be [https://coq.inria.fr/refman/program.html](https://coq.inria.fr/refman/program.html). This is the link that still comes up when googling `Coq program`.

The new URL seems to be [https://coq.inria.fr/refman/addendum/program.html](https://coq.inria.fr/refman/addendum/program.html). 

The same problem holds for instance for the type classes chapter. Maybe it would make sense to "symlink" the old URLs to the new locations? Google might learn where the new pages are located soon enough, but I assume that loads of lecture notes and even some papers still contain hard links to the old URLs.

**Comment by maximedenes** [comment]
> lecture notes and even some papers still contain hard links to the old URLs.

You mean they would contain hard link to URLs that don't specify the version? That would sound like a bad practice: there is no reason why the content and/or the URL would be stable as new versions of Coq are released. 

The documentation of Program for previous versions can be accessed for example at https://coq.inria.fr/distrib/V8.7.2/refman/program.html

**Comment by yforster** [comment]
I agree that it's bad practice, but my guess is that it's also common practice. A quick Google search came up with e.g. https://softwarefoundations.cis.upenn.edu/draft/qc-current/Typeclasses.html and https://www.cs.uoregon.edu/research/summerschool/summer14/lectures/zdancewic-sf-lec01.pdf

**Comment by maximedenes** [comment]
@Zimmi48 I'm fine with trying to address them, but what should we do concretely? I can't really guess what versions they are looking for in general, so a redirection doesn't seem to be the right tool. We can read and fix standard material like the one mentioned by @yforster, is that what you mean?

**Comment by Zimmi48** [comment]
You don't need to fix every link! But it is pretty clear what https://coq.inria.fr/refman/program.html should redirect to. In fact, I deeply regret that parts appear in the URL given how we should reorganize those chapters: user-extensions and addendum, seriously?

**Comment by Zimmi48** [comment]
Also the links to the indexes (as remarked by @cmangin on Gitter).

**Comment by samuelgruetter** [comment]
This is a quite serious issue IMHO: Links which existed before, e.g. https://coq.inria.fr/refman/tactics.html now return 404 page not found.
Links from Google search results and from people's browser history now don't work any more.
This should be fixed! Wouldn't it be easy to just add a redirect for each chapter whose URL changed, as follows:

```
https://coq.inria.fr/refman/tactics.html -> https://coq.inria.fr/refman/proof-engine/tactics.html
https://coq.inria.fr/refman/program.html -> https://coq.inria.fr/refman/addendum/program.html
etc ...
```

**Comment by Zimmi48** [comment]
It would be easy. I do not have access to this server to do it myself. But I hope that someone who has does it very soon.

**Comment by Zimmi48** [comment]
FTR I now have access to the server but I don't have any experience with setting up redirection. If someone told me what to add in an `.htaccess` or similar file, I can do it.

**Comment by Zimmi48** [comment]
The website (and thus the manual) is going to be moved to GitHub pages. The redirects should then work a bit differently. @vbgl You might consider putting this in your post-migration to-do...

Or, given that most of the web has probably healed itself already by now, we could just close this.

**Comment by Zimmi48** [comment]
I'm going to close this as this is probably much less of an issue now that it was just after the migration. FTR, in the future, I would like the URL of the refman to work a bit differently: the "current" URL should redirect explicitly (and not silently) to the current version of the refman (then links don't break). And we could consider adding a warning (like is done e.g. here https://zenodo.org/record/1133970) to signal when this is not the latest version of the manual.
