### ISSUE TITLE
Pretty-printing of examples in the manual can make them wrong…

### ISSUE THREAD

**Issue by vbgl** [coq/coq#7308]
See for instance: https://coq.inria.fr/distrib/current/refman/user-extensions/syntax-extensions.html#locating-notations

The source reads (`doc/sphinx/user-extensions/syntax-extensions.rst`):
```
   Locate "exists".
```

After rendering:
```
<dt><span class="coqdoc-keyword">Locate</span><span> “exists”.</span></dt>
```

Strait quotation marks (`"` U+0022) from the source of the manual are transformed into left or right double quotation marks (`“` U+201C or `”` U+201D).

(Let me take this opportunity to also point out that putting `Locate` in the `keyword` class is misleading, as it is not a keyword.)

I’ve observed similar transformations involving other characters (e.g., `'`, `‘`, and `’`).

**Comment by herbelin** [comment]
A comment about the side question:

> (Let me take this opportunity to also point out that putting Locate in the keyword class is misleading, as it is not a keyword.)

This is a good question which has many related discussions... Both positions make sense. This is a keyword in the sense that it is part of the vocabulary of commands. For instance, it has to be highlighted by any highlighting tool of .v files. But this is not technically a keyword in the sense that it is not forbidden to use it as an identifier.

Maybe do we need to introduce a new category, say "weak keyword"? Or, going the other way round, to call "strong keywords" the subset of those which cannot be used as ident, or something like that.

Don't know what others think though.

**Comment by gares** [comment]
IMO "Locate" should be a (real) keyword as all other Capitalized words.
The reason is that would make parsing way more robust in face of editions: today if you remove a . the document may be parsed in a completely different way just because `intros x Qed.` is a perfectly valid sentence (and it would not be the case if `Qed` was a keyword).

**Comment by Zimmi48** [comment]
FTR the core issue here has been fixed already. The keyword discussion should happen elsewhere (maybe on Discourse).
