### ISSUE TITLE
intuitive usage of assert_succeds and assert_fails does have side effects

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#7313]
#### Version

~~~~~~~~~
The Coq Proof Assistant, version 8.8.0 (April 2018)
compiled on Apr 18 2018 14:30:24 with OCaml 4.06.0
~~~~~~~~~

#### Operating system

Arch Linux, up to date as of yesterday.

#### Description of the problem

https://github.com/coq/coq/blob/8c1d71db6b1eb95e67874417cc94f1d9728aff92/CHANGES#L105 says

> - Added tactics "assert_succeeds tac" and "assert_fails tac" to ensure
>   properties of the executation of a tactic **without keeping the effect
>   of the execution.**

(emphasis mine) which leads me to believe that the following should succeed, but it fails:

~~~~~~~~~~~~~~~~~
Goal True.
  assert_succeeds (let x := open_constr:(_:False) in idtac).
  exact I.
Qed. (* Error: Attempt to save a proof with shelved goals (in proof Unnamed_thm) *)

Goal True.
  assert_fails (let x := open_constr:(_:False) in fail).
  exact I.
Qed. (* Error: Attempt to save a proof with shelved goals (in proof Unnamed_thm) *)
~~~~~~~~~~~~~~~~~

@JasonGross

**Comment by JasonGross** [comment]
I think this is merely a case of Ltac semantics being surprising.  Your `let x := open_constr:(_:False) in` gets evaluated *before* the tactic is passed to `assert_succeeds` / `assert_fails`.  So it's still true that the execution of the tactic passed to `assert_succeeds` / `assert_fails` does not leave over side effects (even if the evaluation of your tactic expression to a tactic is side-effectful).  Both your proofs go through if you precede the `let` with `idtac; `.

I move to close this bug as invalid (though perhaps we should also have a label called `ltac semantics are confusing`?).

**Comment by andres-erbsen** [comment]
O-kay, I agree that I missed the point here. What are the cases where it is safe not to prefix a tactic argument to another tactic by `idtac`?

**Comment by JasonGross** [comment]
> What are the cases where it is safe not to prefix a tactic argument to another tactic by `idtac`?

1. When the "tactic" argument returns a constr
2. When you are relying on the side effect happening at the call site and not at the invocation site.  (Yes, it is possible to write tactics like this, no I don't advise it.)
3. When the "tactic" you're passing it to is written in OCaml and does introspection on the Ltac syntax tree of the tactic argument (but why would anyone ever do this?)
4. When the outer tactic is not a tactic notation and the tactic argument is currently just an identifier, and you forget to wrap `ltac:()` around it (solution: use `ltac:(idtac; ...)` rather than just `(idtac; ...)`)

I think that's it?

**Comment by andres-erbsen** [comment]
I am not sure I understand 4. Do you mean anything other than it is fine to pass tactic identifiers (but not notations) into tactic identifiers (but not notations)?

**Comment by JasonGross** [comment]
By 4, I mean this:
```coq
Ltac foo := idtac.
Ltac bar x := x.
Goal True.
  bar foo. (* success *)
  bar (idtac; foo). (* syntax error *)
  bar ltac:(idtac; foo). (* success *)
```
If `bar` were a tactic notation taking a `tactic` argument, all three would succeed.  Hence the transformation `f x` -> `f (idtac; x)` sometimes leads to syntax errors, in exactly the cases where `x` is a tactic identifier and `f` is not a tactic notation.

**Comment by andres-erbsen** [comment]
well-known workaroundable ltac1 issue fixed in ltac2
