### ISSUE TITLE
coqchk Include with primitive projections broken

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7329]
Found in the wild in HoTT.

```coq
Set Primitive Projections.

Module M.
  Record Box := box { unbox : Type }.

  Axiom foo : Box.
  Axiom baz : unbox foo -> unbox foo.
End M.

Include M.
```
causes
```
Fatal Error: Anomaly "Uncaught exception Reduction.NotConvertible."
             Please report at http://coq.inria.fr/bugs/.
```

**Comment by SkySkimmer** [comment]
and hidden behind that:
```coq

Set Primitive Projections.

Module M.
  Module Bar.
    Record Box := box { unbox : Type }.

    Axiom foo : Box.
    Axiom baz : unbox foo -> unbox foo.
  End Bar.
End M.

Include M.
```
causes
```
Fatal Error: User error: Signature components for label Box do not match
```
I don't know how to fix this.

**Comment by SkySkimmer** [comment]
(at 152440f46f I have a commit fixing the first example but I don't know if it's the right way to do so, and it does nothing for the second)

**Comment by ppedrot** [comment]
AFAICT there are two bugs here.

First I think that `eq_table_key` should be comparing using the canonical constant names, not the user names. Constants with the same canonical name are indeed convertible by what amounts to a trivial δ unfolding. Same thing for the projection case of `compare_stacks`.

Even fixing that doesn't seem to make the example go through. There is a check that looks very strange in the subtyping relation of records, which in addition uses another user name equality check...

**Comment by ppedrot** [comment]
FTR there is a `env_inductives_eq` field in the checker environments, purportedly used for equivalence of inductive types. If I understand the code correctly, the checker doesn't actually check anything though, if a type claims to be an alias of another one it blindly adds it to this equivalence table. But anyways we should use this to check convertibility of inductive types, constructors and projections.
