### ISSUE TITLE
fiat-parsers sometimes runs out of memory on gitlab

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7332]
eg https://gitlab.com/SkySkimmer/coq/-/jobs/64459644 (rerun succeeded https://gitlab.com/SkySkimmer/coq/-/jobs/64482707) and https://gitlab.com/SkySkimmer/coq/-/jobs/64170698
cc @JasonGross

**Comment by ejgallego** [comment]
I think this is in a sense invalid, or at least badly phrased; we don't tag the `fiat-parsers` job properly so of course, when a weaker runner is picked the build fails I think.

**Comment by SkySkimmer** [comment]
I only have shared runners enabled since yours kept failing though

Gaëtan Gilbert

**Comment by ejgallego** [comment]
I was talking about tags available for shared runners, you can use `2gb` I think; if in one fails and in other it doesn't it means we are not selecting properly.

As for my runners, you can remove `pau` but keep using kaguya; it seems that some user really trashes `pau` and docker dies, will investigate but anyways @maximedenes is supposed to come with a dedicated machine soon.

**Comment by ejgallego** [comment]
Didn't see that in a long time, closing.
