### ISSUE TITLE
Secondary maintainer for Makefile needed.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7345]
The two listed maintainers for the build system (`Makefile`) are currently @letouzey and @maximedenes.
@letouzey is unresponsive at the present time and @maximedenes said it was a mistake that his name was put as a secondary maintainer, so this needs to be fixed so that there is a secondary maintainer who can act in the absence of the first one.
For instance, #6033 would need to get merged by this person.
@ejgallego are you OK to be designated as the secondary maintainer for the `Makefile`?

https://github.com/coq/coq/blob/72d6d5e87759b62dcd9974c87bf59496d27e10b0/.github/CODEOWNERS#L293-L294

**Comment by ejgallego** [comment]
I am OK but my make-fu is pretty bad.

**Comment by ejgallego** [comment]
This also doesn't solve the problem that I am going to submit quite a few build-related PR so I need someone to review and merge. I could actually go see Pierre in person to work together if that's gonna work better for him.

**Comment by Zimmi48** [comment]
Yeah, it only solves part of the problem.
