### ISSUE TITLE
Syntax Error while working through Logic.v in Software Foundations Book

### ISSUE THREAD

**Issue by twoquarterrican** [coq/coq#7352]
#### Version
8.8.0

#### Operating system
Windows

#### Description of the problem

I am working through Software Foundations book. I am getting an error when trying to load the Fixpoint definition for `In` [here](https://softwarefoundations.cis.upenn.edu/current/lf-current/Logic.html#lab179).

In short, the block it is trying to evaluate is
```Fixpoint In {A : Type} (x : A) (l : list A) : Prop :=
match l with
  | [] => False
  | x' :: l' => x' = x \/ In x l'
 end.
```
But I get this error: `Syntax error: 'end' expected after [branches] (in [match_constr]).` 

In addition the ide highlights in red the left bracket (`[`) in the third line above.

I have tried: 
1. Recompiling the dependent files and the Logic.v file in CoqIDE
2. Recompiling the dependent files and the Logic.v file in the command prompt.

I have attempted to do the same from Proof General in emacs, but I cannot currently get that to install correctly. I will update if I can get it to work.

Note: this first occured in version 8.6, then I upgraded to 8.8 and tried to resolve the issue.

**Comment by herbelin** [comment]
@twoquarterrican: Apparently, the notation `"[ ]"` is not correctly registered at the time you are asking to use it.

It should have been loaded by the command `Require Export Tactics` (at the top of the `Logic.v` file) via the `Require Export Poly` in `Tactics.v`, as the notation for `[]`, namely `Notation "[ ]" := nil` is defined in file `Poly.v`.

What possibly happens is the following: `Tactics.v` is a common file name which exists also twice in the standard library. Depending on your environment, maybe the wrong `Tactics` file is loaded. When processing the file line by line, check the warning at the time of `Require Export Tactics`, what does it tell?

**Comment by maximedenes** [comment]
@herbelin Shouldn't we write `From Coq Require Export Tactics` to avoid such tricky scenarios?

**Comment by maximedenes** [comment]
Or an even more precise qualification, if it exists twice in stdlib.

**Comment by herbelin** [comment]
Yes, but it is `sf` which should do that, because it is the `Tactics.v` from `sf` which has to be loaded.

And note that `sf` has thus also its own `Logic.v`, and its own `List.v`...

**Comment by SkySkimmer** [comment]
@twoquarterrican did you compile SF? This is the first point where SF differs enough from the standard library to break when the Require'd modules are from the standard library (I tested this).
Is there a SF bug tracker somewhere?

**Comment by dh6713** [comment]
If you're using the [] notation, shouldn't you Import ListNotations yourself and not rely on something else to expose it?

**Comment by twoquarterrican** [comment]
@herbelin 

> When processing the file line by line, check the warning at the time of Require Export Tactics, what does it tell?
```
Tactics.vo has been found in
[ C:\Coq\lib\theories\Program ;
  C:\Coq\lib\theories\Init ];
loading C:\Coq\lib\theories\Program\Tactics.vo
[ambiguous-file-name,filesystem]
```
Looks like you are right. It did not pick up the Software Foundations version of Tactics.v.

---

@SkySkimmer 

>  did you compile SF?

I am not sure I understand the question. My interpretation was to go all the way back to Basics.v and recompile everything from Software Foundations.  
- I used the gui on Basics.v (Compile / Compile Buffer) and verified that Buffer.vo file has a new modified date. 
- I next went to Induction.v and ran Compile / Compile Buffer from the ide and noticed the modified date on Induction.vo did not change.
- I next  stepped through Induction.v
  - I got no message when stepping over `Require Export Basics.`
  - I got the error `The reference evenb was not found in the current
environment.` when Induction.v made a reference to `evenb`
  - I verified that `evenb` is defined in Basics.v
Conclusion: I believe this means SF does not compile. But this surprises me because I have previously had no problems until Logic.v, so this may be a red herring. I may be doing something else wrong.  I hope that answers your question.

----

If there is something I missed that I should try from the other comments, please let me know.

**Comment by SkySkimmer** [comment]
Maybe coqide had problems picking up the _coqproject?
