### ISSUE TITLE
Anomaly "error with no safe_id attached: Cannot undo." in coqtop

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#7353]
#### Version

Coq 8.8.0

#### Operating system

macOS 10.13.3 High Sierra

#### Description of the problem

Here is a `coqtop` session:
```
$  coqtop
Welcome to Coq 8.8.0 (April 2018)

Coq < Undo.
Toplevel input, characters 0-5:
> Undo.
> ^^^^^
Error: Anomaly "error with no safe_id attached: Cannot undo."
Please report at http://coq.inria.fr/bugs/.
```

**Comment by anton-trunov** [comment]
This seems like a regression, since Coq 8.7.2 does not produce an anomaly:
```
$ coqtop
Welcome to Coq 8.7.2 (February 2018)

Coq < Undo.
Toplevel input, characters 0-5:
> Undo.
> ^^^^^
Error: Cannot undo
```

**Comment by Zimmi48** [comment]
This problem is very annoying. I don't understand that it was completely ignored by STM maintainers...

**Comment by gares** [comment]
As reported the bug gives an anomaly rather than an error. And the anomaly still display the error message. All this in a debug tool. To my eyes the priority on this is low.

**Comment by Zimmi48** [comment]
@gares Why doesn't it work in the case that was reported in a duplicate bug report?

```
Definition foo := 1.
Definition bar := 2.
Undo.
(*Error: Anomaly "error with no safe_id attached: Cannot undo."
Please report at http://coq.inria.fr/bugs/.
*)
```

And did you notice the other duplicate bug report saying that it happens as well in CoqIDE?

**Comment by Zimmi48** [comment]
OK, sorry I was confused on the expected behavior of `Undo`. For some reason, I thought `Undo` and `Back` were equivalent. I hadn't realized that `Undo` was only supposed to be used within a proof.

Note that `.. coqtop::` sphinx blocks can be passed the option `undo` which is supposed to allow them to have no effect on the rest of the document. It works by adding `Undo n.` at the end of the block where `n` is the number of sentences in the block. @cpitclaudel were you aware of this limitation? It can be very confusing...

**Comment by cpitclaudel** [comment]
Nope, I wasn't aware of it.  We should change the `undo` flag to issue `Back n` instead of `Undo n`, if that works.

**Comment by ejgallego** [comment]
> So I don't see any good solution other than reimplementing coqrst on top of SerAPI (not an option unfortunately with the doc within the main repo and SerAPI out of it), the XML protocol or the future LSP...

Umm, already in the Sphinx issue I warned a bit about this approach as coqtop is not really a good server for `coqrst`, however Clément rightfully pointed out that it would be good to use it so we would be more faithful to the user.

I am not sure this last point is so important tho; IMHO providing a `toplevel` friendly for `coqrst` should be easy [see the size of `coqc` in #8690 ] What is your exact use case?

**Comment by gares** [comment]
Ftr the STM is perfectly able to implement the Undo you want, and it was even exposing it. The @herbelin asked to behave  as in 8.4 and that is the current semantics (up to the safe id message that is a bug introduced when the Undo classifier was reworked by @ejgallego I believe).

**Comment by jeremydaw** [comment]
same bug is present on Coq 8.8.2 (January 2019)

**Comment by ejgallego** [comment]
Fixed in master.
