### ISSUE TITLE
Developer documentation needed for the Sphinx manual

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7360]
It would be good to have a developer documentation (`doc/sphinx/README.md`) explaining some basics about Sphinx, linking to the appropriate generic Sphinx documentation, explaining *all* Coq-Sphinx peculiarities and giving recommendation on how to extend / improve the Coq reference manual.

Of course, starting with something incomplete and improving it step by step would be OK.

Since @maximedenes is pretty busy ATM, @cpitclaudel would you be OK to take care of this? (I personally can't because I don't understand enough about Sphinx yet.)

Steps:

- [x] Create `doc/sphinx/README.md`.
- [x] Migrate relevant Emacs code to `dev/tools/coqdev.el`.
- [ ] Remove `doc/sphinx/MIGRATING`.

**Comment by cpitclaudel** [comment]
I don't expect I'll have time until this week-end, but I could try to give it a shot this week-end.
Was there docs for the LaTeX manual that I should draw inspiration from?

**Comment by Zimmi48** [comment]
There is no hurry, this week-end is good.
And no, unfortunately, there was no such developer doc for the LaTeX manual. So the Sphinx migration is a good opportunity to make things even better ;-)
Can I add you to the contributors team of the Coq organization so as to be able to assign this issue to you?

**Comment by Zimmi48** [comment]
Note that I can't assign the issue to you until you click on the validation link in the invite you should have received.
