### ISSUE TITLE
nested proofs cause uncaught exception

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#7362]
#### Description of the problem
Nested proofs cause Anomaly "Uncaught exception Not_found"

Check out any commit of VST between (probably) 2017 and 25 April 2018,
`make fcf/Blist.vo`
(this should not take very long)
and get the following error message:

```
File ".\fcf/Blist.v", line 640, characters 4-83:
Warning: Nested proofs are deprecated and will stop working in a future Coq
version [deprecated-nested-proofs,deprecated]
File ".\fcf/Blist.v", line 644, characters 2-6:
Error: Anomaly "Uncaught exception Not_found."
```

**Comment by SkySkimmer** [comment]
Too annoying to reproduce for a not-very-supported feature.
