### ISSUE TITLE
Latex packages for building coq doc

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7377]
What are the latex packages necessary to compile Coq documentation?

In dev/doc/setup.txt and INSTALL.doc we say that for debian-like distributions package texlive-math-extra is used to compile the doc, but this package is not provided in ubuntu 18.04 (just released) or current debian.

Also with sphinx the latex we use has been reduced so the packages used may have reduced too.

**Comment by ejgallego** [comment]
I'd bet that `texlive-math-extra` can be safely removed. Let me do a doc build and I see.

**Comment by ejgallego** [comment]
Docs build fine in 17.10 without that package; as for Sphinx, I got success but had still to install `sphinxcontrib-bibtex` by hand, 18.04 will include this package so we can test again when it is released.

**Comment by ejgallego** [comment]
So I suggest we try a 18.04 build without `pip3` but adding the https://packages.ubuntu.com/bionic/python3-sphinxcontrib.bibtex package and basic texlive + hevea which is still needed.
