### ISSUE TITLE
Minimal OCaml version for Coq 8.10

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7380]
After Ubuntu Bionic has been released, and after quite a few versions requiring OCaml 4.02.3, it seems to me that it is time for us to raise the lower bound in our OCaml version to 4.05.0.

At the time 8.9 is released, few people should still be in a distro shipping 4.02.3, and those that are will be better served without a doubt by using OPAM. Moving to 4.05.0 will allow us to clean quite a bit of stuff. Debian Buster should also ship with Coq 8.9 and OCaml 4.05.0.

Most of the infrastructure is ready, once we agree, we will push the correspoding changes.

**Comment by SkySkimmer** [comment]
(debian testing is also on 05)

Gaëtan Gilbert

**Comment by gares** [comment]
IIRC 4.05 had some issue with the ppx ecosystem. Maybe it is solve now, I don't know. 4.06 has no problems AFAICT.

**Comment by ejgallego** [comment]
> IIRC 4.05 had some issue with the ppx ecosystem.

Should not have more issues than 4.02.3 tho, but if that's true you better raise this point to debian-ocaml.

**Comment by ejgallego** [comment]
This is my proposal for 8.9: use 4.02.3, and announce that 8.10 will require OCaml 4.05.0

**Comment by ejgallego** [comment]
So I propose we take the decision soon as to be able to properly schedule 4.05 changes; I think 8.10 makes sense. So far an informal poll of core developers seems to return a positive support of this change. However, I am more concerned about users.

I thus do propose we write a mail to Coq Club announcing the 8.10 change to 4.05 and hearing back from users to see if there would be some blocker problem.

WDYT?

**Comment by Zimmi48** [comment]
I don't believe that this kind of decision requires user input. The only users who could possibly care about the OCaml version are plugin developers but we already impose on them much more drastic changes than an OCaml version update.

**Comment by ejgallego** [comment]
Ummm, I am not sure, users may need to install a newer OCaml version to use Coq, so I don't see the harm in asking if anyone has a specific reason to keep using an old OCaml env.

**Comment by ejgallego** [comment]
I think that no harm in announcing this in coq-club ; do we all agree on using 4.05 for 8.10 ?

**Comment by JasonGross** [comment]
I think this might break the ability to use Coq on Travis without opam.  I'm still in the process of backporting the OCaml packages needed to build Coq, but it looks like there's a new dependency on ocamlbuild, but the versions of the ocaml packages that know how to talk to ocamlbuild seem to depend on newer versions of debhelper, which I can't seem to backport to trusty (which is the newest ubuntu that travis can run), because it depends on dpkg, which build-depends on debhelper.  I'm still trying to figure out if there's some combination of source packages that I can backport which will all build, but it's an enormous pain.

**Comment by Zimmi48** [comment]
>I think this might break the ability to use Coq on Travis without opam.

Well, not quite. There is the Nix way too.

>Alternatively, if Coq would publish docker images of the latest builds, as well as released versions, I could stop trying to build Coq on trusty.

See #7753.

**Comment by ejgallego** [comment]
> I think this might break the ability to use Coq on Travis without opam.

Yeah that's a problem, tho I think however it is more of Travis problem than our problem. Surprising that there aren't more modern versions of OCaml available.

**Comment by JasonGross** [comment]
It's because Travis ships the LTS Ubuntu release from 2014, and 4.05 only showed up in the April 2018 Ubuntu release

**Comment by ejgallego** [comment]
I mean that there are no packages for trusty

**Comment by JasonGross** [comment]
I have successfully backported packages for OCaml 4.05 and other relevant Coq dependencies to precise, trusty, and xenial, so I'll be able to fix my travis builds if this gets merged.

**Comment by ejgallego** [comment]
> I have successfully backported packages for OCaml 4.05 and other relevant Coq dependencies to precise, trusty, and xenial, so I'll be able to fix my travis builds if this gets merged.

Good to know @JasonGross ; note that you could also use the Docker image we hope to provide soon.

**Comment by ejgallego** [comment]
So in fact you may want to comment in #7753 @JasonGross ?

**Comment by JasonGross** [comment]
Argh, this is causing me a great deal of trouble.  The HoTT repo relies on the opam package, which is an enormous pain to port, because it has something like a dozen dependencies.  Some of which fail to build when I backport them, like [rpm](https://bugs.launchpad.net/ubuntu/+source/rpm/+bug/1800411) and [jsonm](https://bugs.launchpad.net/ubuntu/+source/jsonm/+bug/1800410). >.<

**Comment by Zimmi48** [comment]
>The HoTT repo relies on the opam package

You mean on the Debian package?

**Comment by Zimmi48** [comment]
@JasonGross Maybe you can try to use the new Docker image that @erikmd created for HoTT's CI (see https://github.com/coq-community/docker-coq).
