### ISSUE TITLE
Gitlab should have stronger cache invalidation

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7382]
As done for Circle, gitlab should have stronger cache invalidation. In particular, the `key` entry should depend on a hash of the gitlab configuration file and the stage.

**Comment by SkySkimmer** [comment]
>In particular, the key entry should depend on a hash of the gitlab configuration file and the stage.

I don't see how that's possible.

**Comment by ejgallego** [comment]
I guess we'd need to request a `CI_CONFIG_HASH` variable. `CI_CONFIG-PATH` does already exist but I am not sure we can set the hash at the right time.

**Comment by ejgallego** [comment]
Aha: https://gitlab.com/gitlab-org/gitlab-ce/issues/40750

**Comment by SkySkimmer** [comment]
I think we're going to use a docker image instead of cache eventually, and until then manually changing the key should work.
