### ISSUE TITLE
[ci] [gitlab] Create custom bionic docker build image.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7383]
In #7381, we set the base image to `ubuntu:bionic`. This is good but not good enough, as the base image is missing the set of apt packages that we need in latter phases, thus for example when the build phase is trigerred `apt` has to be run again to install the dependencies [which the cached .opam depends on]

We should indeed create an `ubuntu:bionic-coqbuild` image that includes the apt packages so indeed all the remaining setup work is just to do the `.opam` cache and we are ready to rumble.

**Comment by SkySkimmer** [comment]
Why not put the opam stuff in the image too?

**Comment by Zimmi48** [comment]
Why not use a Nix image instead? https://hub.docker.com/r/nixorg/nix/

**Comment by Zimmi48** [comment]
@aspiwack who pointed me to this (made for Tweag.io) told me to looks at the `circleci` one.

**Comment by SkySkimmer** [comment]
>@aspiwack who pointed me to this (made for Tweag.io) told me to look at the circleci one.

We should definitely be able to share images between gitlab and circle.

>Why not use a Nix image instead? https://hub.docker.com/r/nixorg/nix/

Whoever makes the image will pick their favrite base I think.

**Comment by ejgallego** [comment]
> Why not put the opam stuff in the image too?

Our testing switches such as compilers depend on the image; as we discussed it seems we cannot have a fine enough image selection for now.

As for the base, the CI world is fully dominated by Ubuntu/Debian for now, I also do prefer our base testing system to be Ubuntu as it is by far a more popular choice among users.

**Comment by SkySkimmer** [comment]
>Our testing switches such as compilers depend on the image; as we discussed it seems we cannot have a fine enough image selection for now.

I don't remember discussing such a thing.

**Comment by ejgallego** [comment]
We did discuss, but the short story is that it seems you cannot do:
```
image: ubuntu:bionic:coq:$(STAGE)
```

**Comment by ejgallego** [comment]
In fact the way we are currently handling `EXTRA_PACKAGES` will give us headaches at some point as it is set differently for boot than for build/test.

**Comment by ejgallego** [comment]
Still OPAM changes a bit too frequently for my taste, and it is adequatedly managed by the cache IMHO, so I propose we take care of `apt` / base packages as a first step.

**Comment by ejgallego** [comment]
I think that for now, and given the current user base of distributions we will keep our main images based on Ubuntu / Debian stable + OPAM. In particular that's the easiest way to manage beta OCaml compiler as of today.

That being said I think it is not a problem to add an extra Nix image to the pipeline if people want to test it there.
