### ISSUE TITLE
3441.v non deterministic

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7388]
https://gitlab.com/coq/coq/-/jobs/65545311

**Comment by Zimmi48** [comment]
I had a new occurrence: https://gitlab.com/Zimmi48/coq/-/jobs/73460133
Three already reported non-deterministic tests failed because of `Timeout` (see also #7383, #5982).

**Comment by Zimmi48** [comment]
https://gitlab.com/coq/coq/-/jobs/136470246

Related to the discussion on timeout at: #7483
