### ISSUE TITLE
eapply triggers Anomaly "Uncaught exception Not_found."

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7392]
#### Version

Coq master

#### Operating system
Linux

#### Description of the problem
 The following code triggers an anomaly:

```coq
From Coq Require Import Utf8.

Class ElimInv {X Y : Type} (Pout : X → Y) (Pclose : X → option Y) :=
  elim_inv : False.

Class IntoAcc {X Y : Type} (E1 E2 : nat) (α β : X → Y) :=
  into_acc : False.

Global Instance elim_inv_acc_with_close {X Y : Type} E1 E2 α β (foo : nat → nat → Y → Y) :
  IntoAcc E1 E2 α β →
  ElimInv (X:=X) (Y:=Y) α (λ x, Some (foo E1 E2 (β x))).
Proof. intros []. Qed. 

Lemma tac_inv_elim {X Y : Type} Pout Pclose :
  ElimInv (X:=X) (Y:=Y) Pout Pclose →
  False.
Proof. intros []. Qed.

Global Instance into_acc_na E n :
  IntoAcc (X:=unit) (Y:=nat) E E (λ _, 0) (λ _, 5 + n).
Proof. Admitted.

Goal False.
eapply tac_inv_elim with (Pclose:=(λ xx, Some _)).
eapply @elim_inv_acc_with_close.
eapply @into_acc_na. (* EXPLOSION *)
```
This seem to be related to the fact that `into_acc_na` unifies `E1` and `E2` -- if I change that instance to make the two `E` independent, the anomaly goes away.

I originally ran into this during Iris development, and got a different error message:
```
Error: Unable to unify "?E2" with "?E1@{x:=_UNBOUND_REL_1}" as
 "?E1@{x:=_UNBOUND_REL_1}" contains local variables.
```
I am not sure if that's actually a different problem, but for now I can't really make progress on minimizing the original issue.

**Comment by RalfJung** [comment]
Now here is something really strange... if I change the `into_acc_na` instance to
```
Global Instance into_acc_na E1 E2 n :
  E1 = E2 →
  IntoAcc (X:=unit) (Y:=nat) E1 EE2 (λ _, 0) (λ _, 5 + n).
```
then the last `eapply` succeeds and turns the goal from
```
  IntoAcc ?E1@{x:=_UNBOUND_REL_1} ?E2@{x:=_UNBOUND_REL_1} ?Pout ?β@{x:=_UNBOUND_REL_1}
```
into
```
  ?E1@{x:=_UNBOUND_REL_1} = ?E20
```
Notice how the right-hand side should be `?E2@{x:=_UNBOUND_REL_1}` but instead is `?E20`! On that goal, `reflexivity` fails saying
```
Error: Unable to unify "?E20" with "?E1@{x:=_UNBOUND_REL_1}" as
 "?E1@{x:=_UNBOUND_REL_1}" contains local variables.
```

**Comment by ppedrot** [comment]
Probably a bug for @herbelin.

**Comment by ppedrot** [comment]
The source of the problem seems to be the untyped coercion of metas to evars, because `E1`, `E2` and `β` are wrongly believed to be living in the context `x : X ⊢` when they should be otherwise living in the empty context.

**Comment by SkySkimmer** [comment]
It also doesn't on 8.16

**Comment by RalfJung** [comment]
I guess it got fixed at some point in the last 4 years, nice. :)
Would still be good to add a test, though.

**Comment by Alizter** [comment]
Was fixed in https://github.com/coq/coq/issues/7586 for the related issue https://github.com/coq/coq/issues/7586. Funnily enough the test is named `bug_7392.v`. I'll rename it and add this one instead.
