### ISSUE TITLE
Error when using std++ and Equations: "Uncaught exception Environ.NotEvaluableConst(0)."

### ISSUE THREAD

**Issue by jad-hamza** [coq/coq#7398]
#### Version

8.7.2

#### Operating system

Debian

#### Description of the problem

Hello, I have an error on the following code:

```coq
Require Import stdpp.set.

Require Equations.Equations.

Set Program Mode.

Inductive List (T: Type).
Definition Cons_type (T: Type) : Type := { l: List T | true }.
Definition tail (T: Type) (src: Cons_type T) : List T. Admitted.

Equations forall1 (T: Type) (l: List T) (p: T -> bool): bool := 
forall1 T l p by rec 0 lt :=
forall1 T l p := forall1 T (tail T l) p.

Admit Obligations.
```

I obtain:
```
Error: Anomaly "Uncaught exception Environ.NotEvaluableConst(0)."
Please report at http://coq.inria.fr/bugs/.
```

[std++](https://gitlab.mpi-sws.org/robbertkrebbers/coq-stdpp) reports having side effects on the Program mode, and removing the Import at the top indeed prevents the error in the end. I'm not sure this is really a bug, or merely an incompatibility between Program/Equations and std++, and I wasn't sure where to post the issue (here, in coq-equations, or in coq-stdpp). Any workaround?

Thank you

**Comment by jad-hamza** [comment]
I obtained the same error on the following file, this time without std++. (Coq version 8.8.0) 

```coq
Require Import Equations.Equations.

Inductive type: Set :=
  | T_bool: type
  | T_prod: type -> type -> type.

Equations transport (t: nat) (T: type): Prop :=
  transport t T by rec 0 lt :=

  transport t T_bool := True;

  transport t (T_prod U V) :=
    transport t U /\
    transport t V.

Admit Obligations.
(* Error: Anomaly "Uncaught exception Environ.NotEvaluableConst(0)."
Please report at http://coq.inria.fr/bugs/. *)
```

**Comment by TDiazT** [comment]
I came across the same error but different setting (I was trying to define some nested recursion with well founded relation).


**Version**
The Coq Proof Assistant, version 8.8.1 (September 2018)
compiled on Sep 28 2018 9:36:10 with OCaml 4.02.3

**Operating system**
Mac OS X 10.14


**Example**
An example (simpler than my actual case but similar in a sense):

```
Require Import List.
Import ListNotations.
From Equations Require Import Equations.

 Definition β (lst : list nat) : list nat :=
     filter (fun elt => false) lst.
   
  Equations failing (lst : list nat) : list nat :=
    failing lst by rec (length lst) lt :=
      failing [] => [];
      failing (cons hd tl) <= hd => {                     
      | 1 := (failing (1 :: (β tl))) ++ (failing tl) ;
      | _ := [] 
      }.
  Admit Obligations.

(* Error: Anomaly "Uncaught exception Environ.NotEvaluableConst(0)." Please report at http://coq.inria.fr/bugs/. *)
```

**Other**
I defined the same but with `Program Fixpoint` and it passes.

**Comment by jad-hamza** [comment]
I couldn't reproduce these issues on master. For @TDiazT's example, the syntax seems incompatible with the current version, but when doing a `match hd with` (in the second case of `failing`), I couldn't reproduce the issue either.

**Comment by ppedrot** [comment]
Should we close then? BTW Equation-specific bugs should rather be reported on the [Equations bugtracker](https://github.com/mattam82/Coq-Equations/issues).

**Comment by jad-hamza** [comment]
Sure!
