### ISSUE TITLE
Error when using wildcards in VERNAC COMMAND EXTEND

### ISSUE THREAD

**Issue by ybertot** [coq/coq#7404]
#### Description of the problem

When using a wildcard in the parsing side of a VERNAC COMMAND EXTEND directive, I get
an error message:
File "src/g_tuto1.ml4", line 1:
Parse error: [args] or ']' expected (in [rule])

When replacing this wildcard by a variable, I only get a warning saying that this variable is unused.

The code can be seen at:

https://github.com/ybertot/plugin_tutorials/tree/error_on_wildcard_in_VERNAC_EXTEND

in sub-directory tuto1, just type `make` with coq8.8.0 binaries in your path.

**Comment by herbelin** [comment]
Hi @ybertot, this behavior is indeed a bit unfortunate. It can be changed by adding (twice) a case for `_` in `vernacextend.mlp`, in the `args` [grammar entry](https://github.com/coq/coq/blob/7dd881fc72d62eb0c1f1e5063eb3a8ed268fb5d5/grammar/vernacextend.mlp#L216), and similarly in `tacticextend.mlp` and `argextend.mlp`.

**Comment by ppedrot** [comment]
I think that at some point you could simply write `constr` for `constr(_)`. Not sure if still working though.

**Comment by ppedrot** [comment]
Nowadays you shouldn't get a warning if the variable is not used, so you can just write any variable. I don't think this kind of dev-targeted macro needs this kind of additional syntactic sugar, so closing.
