### ISSUE TITLE
Problem in bibliography

### ISSUE THREAD

**Issue by fblanqui** [coq/coq#7405]
On https://coq.inria.fr/distrib/current/refman/zebibliography.html
there are various "\sf"'s:

[Del00] | D. Delahaye. A Tactic Language for the System \sf Coq. In Proceedings of Logic for Programming and Automated Reasoning (LPAR), Reunion Island, volume 1955 of Lecture Notes in Computer Science, 85–95. Sprin-ger-Verlag, November 2000. URL: \sf ftp://ftp.inria.fr/INRIA/Projects/coq/David.Delahaye/papers/\sf LPAR2000-ltac.ps.gz.

Perhaps in other places. I didn't check.

**Comment by Zimmi48** [comment]
Fixed
