### ISSUE TITLE
META file is not installed in /usr/lib/ocaml

### ISSUE THREAD

**Issue by zorun** [coq/coq#7411]
Following-up on #7296 but with a slightly different issue with META files

#### Version

8.8.0

#### Operating system

Arch Linux

#### Description of the problem

After #7296 I am now calling install-meta, and it does install the META file.

However, it is located in `/usr/lib/coq/META`, and ocamlfind does not find it:

```
$ ocamlfind query coq
ocamlfind: Package `coq' not found
```

It should probably be installed in `/usr/lib/ocaml/coq/` so that ocamlfind finds it by default.

Downstream bug report: https://bugs.archlinux.org/task/58203

**Comment by Zimmi48** [comment]
We have a number of configure options related to install:

```
  -bindir <dir>               Where to install bin files
  -libdir <dir>               Where to install lib files
  -configdir <dir>            Where to install config files
  -datadir <dir>              Where to install data files
  -mandir <dir>               Where to install man files
  -docdir <dir>               Where to install doc files
  -emacslib <dir>             Where to install emacs files
  -coqdocdir <dir>            Where to install Coqdoc style files
```

It would be easy to add `-metadir <dir>` and it would fix this issue whatever people think of as the right default location...
Files to adapt are `configure.ml` and `Makefile.install`.

**Comment by ejgallego** [comment]
Umm, let me have a look at this.

**Comment by ejgallego** [comment]
Umm, so we don't have the notion of a separate library dir for OCaml and Coq vo files, and indeed this is tricky to do and I don't expect to support it in the near future.

You could indeed create a symlink or use, as @Zimmi48 points out, the `-libdir` option.

IMHO that's the right choice as once #7312 and #6857 are implemented it is likely that indeed Coq libraries are installed into a separate path [maybe `/usr/lib/coq/$LIB`, WDYT?

**Comment by ejgallego** [comment]
@zorun I see nothing more I can do for now here; thus I'm removing my assignement; please leave feedback here or better in any of the issues above.

**Comment by ejgallego** [comment]
Closing as this is correctly solved TTBOMK in both Dune and Make.
