### ISSUE TITLE
coqdep: spurious warning with -f

### ISSUE THREAD

**Issue by gares** [coq/coq#7413]
```shell
gares@gargamel:~/COQ/coq/foo$ cat > _CoqProject
-I src 
-R theories Foo

src/a.ml
gares@gargamel:~/COQ/coq/foo$ touch src/a.ml
touch: cannot touch 'src/a.ml': No such file or directory
gares@gargamel:~/COQ/coq/foo$ mkdir src
gares@gargamel:~/COQ/coq/foo$ mkdir theories
gares@gargamel:~/COQ/coq/foo$ touch src/a.ml
gares@gargamel:~/COQ/coq/foo$ ../bin/coqdep -f _CoqProject 
*** Warning: a.ml already found in src (discarding src/a.ml)
gares@gargamel:~/COQ/coq/foo$ 
```

I suspect this is related to #6851

**Comment by gares** [comment]
@SkySkimmer please assign it to me if it does not ring a bell.
IMO the path specified with `-I` is considered twice.

**Comment by SkySkimmer** [comment]
It's the same as in 8.7 doing `coqdep src/a.ml -I src/` (which prints the same warning).
Possible fixes:
- have coqdep only read .v files from coqproject (this causes weird semantics for people using coqdep with -f and -c)
- don't print a warning when we see the same file twice from different sources. (so eg `coqdep src/a.ml src/a.ml` would not warn. We can bikeshed about the equivalence we use, eg should `coqdep src/a.ml "$PWD/src/a.ml"` warn, etc)

**Comment by SkySkimmer** [comment]
>have coqdep only read .v files from coqproject

(to be specific I mean ignoring non-v files, but still reading -I etc)

**Comment by SkySkimmer** [comment]
Anyways please pick one or 2 changes to do.

**Comment by gares** [comment]
I tried to understand the code emitting the warning, that was added in 21a1c8abdd5807427849c34875c294cb6ad7d899 and refiend in 229dd629d2425750ec4e4ea5598804745979b6d2 .

To my understanding:
I list `a.ml` in my `_CoqProject` to tell `coq_makefile` to build it.
I add `-I whatever` to tell `coq_makefile` to pass it to `ocamlc` when compiling and `coqc` when compiling `.v` files that may `Declare ML Module`.
I expect all my `.ml` files be in paths listed with `-I`.
I may list more paths with `-I`, eg to use an external library, and such library may have `.cm*` files that are named like mines. So maybe this the is reason of existence of the warning?

I guess option 2 makes more sense, but before writing code I'd like @herbelin to try to recall why the warning was put in place.

**Comment by gares** [comment]
Oh, BTW, there is a missing `\n` in the usage message for `-f`

**Comment by herbelin** [comment]
Afair, the warning was to inform about different files referred the same in different locations. In the case above, it is not relevant to warn for two references to the very same file. So, I would support solution 2 from @skyskimmer.

**Comment by ybertot** [comment]
I also support solution 2
