### ISSUE TITLE
Need owner for test-suite infrastructure and specific components

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7426]
Currently, the test-suite has no owner because it would be more spam than anything each time someone adds a test file in `bugs/` (same is true for `CHANGES` for instance). However, there are a few infrastructure or documentation files in `test-suite/` that are not modified so often and would deserve an owner:

- `Makefile`
- `save-logs.sh`
- `_CoqProject`
- `README`

Who would be volunteer to be an owner for these files? Let me propose a few names: @gares @herbelin  @JasonGross @SkySkimmer. We need two volunteers.

Furthermore, Jim has continued Paul's work to add a unit-test framework to the test-suite in #6808 and there are two new small infrastructure files introduced there in `test-suite/unit-tests/src/` who would also need owners (potentially the same people). There is the idea however that tests in the `unit-test/` folder will be organized component-wise and the maintainers for each component will naturally become the owners of the unit tests for this component.

More generally, the test-suite is already partially organized by components and there seem to be a will (see #7227) to go further in a component-based hierarchy. Thus, some current and upcoming test folders could have owners who would naturally be the same as for the corresponding component. This should avoid any spurious review requests. The folders already concerned are `coqchk` `coqdoc` `coq-makefile` `coqwc` `ide` `interactive` `micromega` `modules` `stm` `typeclasses` and `vio`. All these folders should naturally have owners. To this, we can soon add `ssr` (see #7227).

Even if it is not a "component" I feel like the `complexity` folder would also need an owner (@herbelin?).

**Comment by gares** [comment]
I can take Makefile _CoqProject and README, just because if I do #7227 well then I've to rewrite half of the Makefile... I think I'll try to find a minute to write a PR about that. After that you can put my name on these 3 files.

For save-logs, I've really no idea.

**Comment by Zimmi48** [comment]
@gares In the meantime, would you like to review the changes done to `test-suite/Makefile` in #6808?

> For `save-logs`, I've really no idea.

This file was created by @SkySkimmer so I guess it would make sense to have him be the primary code owner for it.

**Comment by herbelin** [comment]
I can take `complexity`, but maybe @zimmi48, would you like to take it (you might somehow be more responsive than me).

**Comment by Zimmi48** [comment]
Unfortunately, I don't have any experience with it so I think it is good you have it.

**Comment by herbelin** [comment]
I did not follow if a PR updating CODEOWNERS was finally made addressing this issue, but, to answer on the principle: c'est en forgeant qu'on devient forgeron!

**Comment by Zimmi48** [comment]
Nope, I didn't push any PR yet. I'm kind of waiting on #6808 and #7227 to get merged first.
