### ISSUE TITLE
Multiple "install: cannot stat '*.cmx': No such file or directory" error messages - installation

### ISSUE THREAD

**Issue by advorkin** [coq/coq#7429]
Versions:
8.7.1
8.7.2
8.8.0

Springdale Linux 7.3 (Redhat based)

OCaml 4.05.0. 
OCamlfind 1.7.3. 
Camlp5 7.00. 

All compilations "-native-compiler yes" and "-native-compiler no" fail with the following error messages.  Altogether there are 910 of them.

example:
install: cannot stat 'vernac/vernacstate.cmx': No such file or directory

I've tried https://github.com/coq/coq/pull/7406, but it didn't help.

This is a showstopper as we cannot install any coq versions at this point.

Please advise.

Thank you!

You have OCaml 4.05.0. Good!
You have OCamlfind 1.7.3. Good!
You have Camlp5 7.00. Good!
CoqIde manually disabled:
=> no CoqIde will be built.
  Architecture                : Linux
  Coq VM bytecode link flags  : -dllib -lcoqrun -dllpath /usr/local/coq/8.8.0/lib/coq/kernel/byterun
  Other bytecode link flags   :
  OCaml version               : 4.05.0
  OCaml binaries in           : /usr/local/Ocaml/4.05.0/bin/
  OCaml library in            : /usr/local/Ocaml/4.05.0/lib/ocaml
  OCaml flambda flags         :
  Camlp5 version              : 7.00
  Camlp5 binaries in          : /usr/local/Ocaml/4.05.0/bin
  Camlp5 library in           : +camlp5
  CoqIde                      : no
  Documentation               : None
  Web browser                 : xdg-open %s
  Coq web site                : http://coq.inria.fr/
  Bytecode VM enabled         : false
  Native Compiler enabled     : true

**Comment by maximedenes** [comment]
Hi,

Is it an error or a warning that you get? What's the exit code?

**Comment by advorkin** [comment]
Thank you!

install: cannot stat 'vernac/vernacstate.cmx': No such file or directory
make[1]: *** [install-devfiles] Error 1
make[1]: Leaving directory `/var/tmp/coq-8.8.0'
make: *** [submake] Error 2

**Comment by maximedenes** [comment]
Can you share the commands you used to build?

**Comment by advorkin** [comment]
I have tried from the command line:
./configure -prefix=/usr/local/coq/8.8.0/ -native-compiler=yes && make && make install

I'm also trying to create RPM and have used the following.  doc options are not working, but it's not priority right now and can be ignored.  I know some of the options are incorrect.

./configure -prefix /usr/local/coq/8.8.0 -libdir /usr/local/coq/8.8.0/lib/coq -bindir /usr/local/coq/8.8.0/bin -mandir /usr/local/coq/8.8.0/share/man -docdir /usr/local/coq/8.8.0/share/doc -camlp5dir /usr/local/Ocaml/4.05.0/lib/ocaml/camlp5 -configdir /etc/xdg/coq -emacslib /usr/local/coq/8.8.0/share/emacs -lablgtkdir /usr/lib64/ocaml/lablgtk2 -coqdocdir /usr/local/coq/8.8.0/share//texmf/tex/latex -coqide no -byte-only -browser 'xdg-open %s' -with-doc no -bytecode-compiler no -native-compiler yes

**Comment by SkySkimmer** [comment]
Why -byte-only? Your configure output is also not mentioning having native code compilation available (unrelated to -native-compiler, I'm talking about ocamlopt).
Our install targets probably break when native is not available.

**Comment by advorkin** [comment]
$ ocamlopt --version
4.05.0
 $ ./configure -prefix=/usr/local/coq/latest/ -native-compiler=yes
You have OCaml 4.05.0. Good!
You have OCamlfind 1.7.3. Good!
You have Camlp5 7.00. Good!
Cannot find the native-code library of camlp5.
Only the bytecode version of Coq will be available.

How come it's not finding ocamlopt...? What am I doing wrong?  I really appreciate your help with this.

**Comment by SkySkimmer** [comment]
It's complaining about camlp5. How is your camlp5 installed?

**Comment by advorkin** [comment]
Is there anything specific I can look for?  I am sorry, not very familiar with it.

From build.log:
./configure
Resulting configuration file (config/Makefile.cnf):
MODE=S
EXE=
OPT=.opt
EXT_OBJ=.o
EXT_LIB=.a
OVERSION=4.05.0
VERSION=7.00
VERSDIR=
OTOP=$(TOP)/ocaml_stuff/4.05.0
OCAMLC_W_Y="-w y"
WARNERR="-g"
NO_PR_DIR=--no-print-directory
OLIBDIR=/usr/local/Ocaml/4.05.0/lib/ocaml
OCLIBDIR=/usr/local/Ocaml/4.05.0/lib/ocaml/compiler-libs
BINDIR=/usr/local/Ocaml/4.05.0/bin
LIBDIR=/usr/local/Ocaml/4.05.0/lib/ocaml
MANDIR=/usr/local/Ocaml/4.05.0/man
OCAMLN=ocaml
CAMLP5N=camlp5

**Comment by SkySkimmer** [comment]
I mean is it from opam or something else?

**Comment by advorkin** [comment]
No, we built our own RPM, so from source.

**Comment by advorkin** [comment]
I just rebuilt camlp5 with different options and gramlib.cmxa is now present.  I will try to build coq again and will let you know.  Thank you for your quick response and help!

**Comment by advorkin** [comment]
Got "You have native-code compilation. Good!"

Thank you!  Will update you with an outcome.

**Comment by advorkin** [comment]
Success!  Thank you for all your help.  I really appreciate it.  I'll go ahead and close the ticket.  Have a wonderful weekend.

**Comment by SkySkimmer** [comment]
We're still broken when native compilation isn't available so reopening.
