### ISSUE TITLE
Using `Parameter` to register typeclass instances

### ISSUE THREAD

**Issue by vzaliva** [coq/coq#7431]
I have noticed the following difference between 8.8 and 8.7:

Consider the following code:

```
Class C A := foo: A.
Instance C1: C nat. Admitted.
Parameter C2: C nat.
Print Instances C.

```

Under 8.7.1 in prints:

```
C2 : C nat
C1 : C nat

```
While under 8.0 it shows only C1:

```
C1 : C nat
```

Is it the intentional change or a regression? If former, what would be the recommended way to assume presence of some typelcass instances (outside of a section)? `Context`? `Instance ... Admitted`?

**Comment by SkySkimmer** [comment]
This is intended, see CHANGES:
>- The `Axiom` command does not automatically declare axioms as instances when
  their type is a class. Previous behavior can be restored using `Set
  Typeclasses Axioms Are Instances`.

Instance + Admitted works. You can also use Parameter + Existing Instance, or Declare Instance. (or the option mentioned in CHANGES)
