### ISSUE TITLE
[sphinx] Grammar token @term points to the SSR chapter

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7432]
In the tactics chapter, when clicking on `term` in a tactic definition, we get to https://coq.inria.fr/refman/proof-engine/ssreflect-proof-language.html#grammar-token-term which is obviously not what we wanted.

**Comment by maximedenes** [comment]
I believe this is due to a bug of the `::=` extension implemented by @psteckler. But I haven't confirmed it.

**Comment by gares** [comment]
My guess is that `@term` points to the last occurrence of `term +=`, and that happens to be in the SSR chapter.

The desired semantics is clearly that:
- in the index one has 1 entry per `+=`, eg term page 1, also page 2 and 3
- each occurrence of `@term` links to the *first* occurrence of the non terminal `term`, ie page 1 in my example

**Comment by maximedenes** [comment]
I'm not sure that's really what we want. It would mean sometimes you click on a `@term` for an SSR tactic, and you get a partial grammar not showing the SSR extensions...

**Comment by herbelin** [comment]
BTW, about the syntax `if term is pattern then term else term`, could someone check if doing `Import IfNotations` fulfils the same objective.

**Comment by Zimmi48** [comment]
So this issue would in fact be solved by finally moving all the grammar extensions from SSR in the main code? ;-)

**Comment by Zimmi48** [comment]
@cpitclaudel Maybe you have an idea on how to fix this? As a quick fix I propose to always point to the first definition of the grammar entry (i.e. the one not in the SSR chapter). As a longer term fix, I propose to never have this kind of duplication of grammar definition in the reference manual.

**Comment by cpitclaudel** [comment]
> As a quick fix I propose to always point to the first definition of the grammar entry (i.e. the one not in the SSR chapter). 

Agreed, and I have code for that as part of my LaTeX build.  (Maxime's right about the cause)

> As a longer term fix, I propose to never have this kind of duplication of grammar definition in the reference manual.

Agreed too.

**Comment by Zimmi48** [comment]
Cool! I'd like to have 8.8.1 released ASAP so would it be possible for you to extract this fix and post it as a PR soon?

**Comment by Zimmi48** [comment]
@cpitclaudel If you could extract this quick fix this would be great? Otherwise, maybe you can just point me to your branch and I'll try to dig up the fix.

**Comment by cpitclaudel** [comment]
Sorry, I'm traveling to PLDI, so I likely won't have too much time before the end of next week. The relevant commit is at https://github.com/cpitclaudel/coq/commit/a483fb8c59ae77788e619164cd74fbc1ddd6ff6c
