### ISSUE TITLE
Error while compiling with opam

### ISSUE THREAD

**Issue by pe200012** [coq/coq#7441]
#### Version

ocaml 4.06.0

#### Operating system
Fedora 26 x64

#### Description of the problem

When I executed
<pre>opam install coq</pre>
,It showed
<pre>#=== ERROR while compiling coq.8.8.0 ==========================================#
# context      2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.06.0 | https://opam.ocaml.org/2.0#fe8c00af
# path         ~/.opam/4.06.0/.opam-switch/build/coq.8.8.0
# command      /usr/bin/make -j3
# exit-code    2
# env-file     ~/.opam/log/coq-2720-335865.env
# output-file  ~/.opam/log/coq-2720-335865.out
### output ###
# [...]
# Warning: Native compiler failed with error: Cannot allocate memory
# [native-compiler-failed,native-compiler]
# File "./theories/FSets/FSetProperties.v", line 1171, characters 0-18:
# Warning: Removed file ./theories/FSets/FSetProperties.vo
# 
# Error: Could not compile the library to native code.
# 
# make[1]: *** [Makefile.build:750：theories/Numbers/Cyclic/Int31/Cyclic31.vo] 错误 1
# make[1]: *** 正在等待未完成的任务....
# make[1]: *** [Makefile.build:750：theories/FSets/FSetProperties.vo] 错误 1
# make[1]: 离开目录“/home/pe200012/.opam/4.06.0/.opam-switch/build/coq.8.8.0”
# make: *** [Makefile:190：submake] 错误 2
</pre>

**Comment by ejgallego** [comment]
Uh, how much memory does your system have?

**Comment by pe200012** [comment]
4G, is that not enough?

**Comment by pe200012** [comment]
It says "unlimited".

**Comment by ejgallego** [comment]
I have no idea @pe200012 , weird. Next step I suggest is you try to build Coq directly, using a recent opam switch. By curiosity, can you paste the output of Coq's `configure`?

**Comment by Zimmi48** [comment]
@pe200012 Did you try several times and it failed with the same error? If not, chances are re-running the command will succeed the next time. But thanks for reporting anyways.

**Comment by pe200012** [comment]
It has failed since I tried update Coq from 8.5~beta.@Zimmi48

**Comment by ejgallego** [comment]
This kind of error can also be due to incorrect path's, configure, etc... So please create a fresh 4.06.1 switch and post all the relevant information.

**Comment by pe200012** [comment]
@ejgallego 
Coq's `configure`

<pre>
- You have OCaml 4.06.0. Good!
- You have OCamlfind 1.8.0. Good!
- You have Camlp5 7.05. Good!
- You have native-code compilation. Good!
- You have the Num library installed. Good!
- CoqIde manually disabled:
- => no CoqIde will be built.
- 
-   Architecture                : Linux
-   Coq VM bytecode link flags  : -dllib -lcoqrun -dllpath /home/pe200012/.opam/4.06.0/lib/coq/kernel/byterun
-   Other bytecode link flags   : 
-   OCaml version               : 4.06.0
-   OCaml binaries in           : /home/pe200012/.opam/4.06.0/bin/
-   OCaml library in            : /home/pe200012/.opam/4.06.0/lib/ocaml
-   OCaml flambda flags         : 
-   Camlp5 version              : 7.05
-   Camlp5 binaries in          : /home/pe200012/.opam/4.06.0/bin
-   Camlp5 library in           : /home/pe200012/.opam/4.06.0/lib/camlp5
-   Native dynamic link support : true
-   CoqIde                      : no
-   Documentation               : None
-   Web browser                 : firefox -remote "OpenURL(%s,new-tab)" || firefox %s &
-   Coq web site                : http://coq.inria.fr/
-   Bytecode VM enabled         : true
-   Native Compiler enabled     : true
- 
-   Paths for true installation:
-   - the Coq binaries will be copied in /home/pe200012/.opam/4.06.0/bin
-   - the Coq library will be copied in /home/pe200012/.opam/4.06.0/lib/coq
-   - the Coqide configuration files will be copied in /home/pe200012/.opam/4.06.0/lib/coq/config
-   - the Coqide data files will be copied in /home/pe200012/.opam/4.06.0/share/coq
-   - the Coq man pages will be copied in /home/pe200012/.opam/4.06.0/man
-   - the Coq documentation will be copied in /home/pe200012/.opam/4.06.0/doc
-   - the Coq Emacs mode will be copied in /home/pe200012/.opam/4.06.0/share/emacs/site-lisp
-   - the Coqdoc LaTeX files will be copied in /home/pe200012/.opam/4.06.0/share/texmf/tex/latex/misc
- 
- If anything is wrong above, please restart './configure'.</pre>

**Comment by Zimmi48** [comment]
@ejgallego Here's the bug you are talking about:  #5517

**Comment by Zimmi48** [comment]
But this only happens when using several threads (and hyperthreading). Does `opam` uses several threads by default?

**Comment by ejgallego** [comment]
Yeah maybe I was not explicit, but I suggested @pe200012 to use `make` , without any `-j ` option. This is important here!

Also, be sure your system load is low. But indeed, I'd say you need the microcode update.
