### ISSUE TITLE
-o option has stopped working for directories

### ISSUE THREAD

**Issue by chrisd1977** [coq/coq#7447]
8.8.0

Linux

Since I updated to coq 8.8.0, the -o option is no longer working like it used to. I am using this option to have a separate build directory, so my Makefile produces a command like coqc -R . Lib -o build/directory/file.vo directory/file.v. This used to work but this is no longer the case. Instead it creates file.vo in the same directory as file.v.

**Comment by ejgallego** [comment]
That may be my fault, hard to say; will look into it later this week but would be great if someone has the cycles to bisect it.

**Comment by SkySkimmer** [comment]
Looks like 675a1dc401eb9a5540ba5bc9a522c1f84d4c3d54 disconnected the -o 
argument

Gaëtan Gilbert

**Comment by ejgallego** [comment]
Thanks, will have a look

**Comment by ejgallego** [comment]
@chrisd1977 #7456 should fix the issue, sorry for the problem; let us know if you have more trouble.
