### ISSUE TITLE
New anomaly with Program Definition

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7448]
#### Version

8.9+alpha (6c8b00e47334f60f200256d45a5542fa80ce4b12)

#### Description of the problem

```
Require Program.Tactics.
Program Definition foo := _.
```

gives:

```
Anomaly "grounding a non evar-free term"
```

In `v8.8` (0c88f3b50d6e213fc7bfb02525c4e349a630275c and 8.8.0), it gives:

```
Cannot infer an internal placeholder of type "Type".
```

Putting the 8.9+beta1 milestone because someone should probably self-assign this.

**Comment by Zimmi48** [comment]
Indeed, I missed this. It seems to be the same. @ejgallego can you confirm this by closing the present issue? Also, you should probably set the 8.9+beta1 milestone on the other one.

**Comment by ejgallego** [comment]
That's indeed very easy to fix, just add the flag to the blaming function. For example here, I do:
```
$ echo 'Require Program.Tactics. Program Definition foo := _.' | bin/coqtop -debug

> Require Program.Tactics. Program Definition foo := _.
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Anomaly "in econstr: grounding a non evar-free term"
Please report at http://coq.inria.fr/bugs/.
frame @ file "toplevel/vernac.ml", line 172, characters 2-60
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 600, characters 33-68
raise @ file "pervasives.ml", line 32, characters 17-33
frame @ file "stm/stm.ml", line 2629, characters 4-60
frame @ file "stm/stm.ml", line 2519, characters 4-105
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 935, characters 6-10
frame @ file "stm/stm.ml", line 2392, characters 16-43
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 1088, characters 12-91
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacentries.ml", line 2332, characters 4-36
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
raise @ unknown
frame @ file "vernac/vernacentries.ml", line 2299, characters 8-666
frame @ file "lib/flags.ml", line 99, characters 20-44
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
frame @ file "vernac/comDefinition.ml", line 121, characters 18-92
raise @ unknown
frame @ file "engine/universes.ml", line 664, characters 17-30
raise @ file "lib/loc.ml", line 89, characters 16-23
```
so that means that the function to blame is `vernac/comDefinition.ml:121`:
```ocaml
        | None -> EConstr.to_constr evd (Retyping.get_type_of env evd (EConstr.of_constr c))
```
Just add `abort_on_undefined_evars:false` and that should fix it.

I am not closing this issue as indeed there could be other sources of problematic cases in that bug.

**Comment by ejgallego** [comment]
@anton-trunov can you do a PR fixing that function and likely line 93 too?

**Comment by ejgallego** [comment]
Well, OK, I'll take care of it, I have it patched already.

**Comment by anton-trunov** [comment]
@ejgallego Great, thanks! This has been a blocker for me. I couldn't properly test our library (not fcsl-pcm, but the extended one). Looking forward for the fix.

**Comment by ejgallego** [comment]
Done in #7449

**Comment by ejgallego** [comment]
You may find more issues, but they should be easy to fix [note that this is code enable only on developer builds]

As they are quite easy to fix, [find a `to_constr` using the backtrace add the missing flag], I suggest that you directly submit PRs with the fix instead of issues.

**Comment by anton-trunov** [comment]
@ejgallego Thanks. Will activate the developer build mode.
