### ISSUE TITLE
Anomaly when attempting to use an empty Context

### ISSUE THREAD

**Issue by siddharthist** [coq/coq#7452]
#### Version
Coq 8.8, see file for more information.

#### Operating system
NixOS

#### Description of the problem

While working on UniMath, I noticed that the following file produces an anomaly: https://github.com/siddharthist/UniMath/blob/b1f3fbbc5f0811af714f4c71645701caac3a98cb/UniMath/CategoryTheory/Subcategory/Limits.v

Using Jason's (amazing!) bug isolator, I was able to minimize it to the following:
```coq
(* -*- mode: coq; coq-prog-args: ("-indices-matter" "-type-in-type" "-noinit" "-w" "-notation-overridden,-local-declaration,+uniform-inheritance,-deprecated-option" "-R" "." "UniMath" "-top" "Limits") -*- *)
(* File reduced by coq-bug-finder from original input, then from 190 lines to 4 lines, then from 20 lines to 4 lines *)
(* coqc version 8.8.0 (May 2018) compiled on May 7 2018 12:51:22 with OCaml 4.05.0
   coqtop version 8.8.0 (May 2018) *)

Context .
```
I can confirm that when replacing the original file with that one line, the same error occurs.

Naturally, that line doesn't make any sense! I'll have to fix it in my pull request. But it might be nicer to have Coq give a better error message, with a line number etc.

**Comment by SkySkimmer** [comment]
#7453
