### ISSUE TITLE
PDF Version of Reference Manual mentioned on website

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#7454]
#### Description of the problem
https://coq.inria.fr/documentation says "A PDF version of the Reference Manual is available on the release page.".  Following the link to https://github.com/coq/coq/releases/tag/V8.8.0, I see nothing obviously related to a PDF file.

If we're still offering a PDF version, please make it clearer how to get it.  If not, please remove the website comment.  (And I think it's still useful until we work out any Sphinx kinks.)

**Comment by Zimmi48** [comment]
Thanks for the report! We don't provide it anymore. So this should be fixed. See coq/www#68.

It doesn't mean we can't debate whether we should provide a PDF but it should be its own issue then.
