### ISSUE TITLE
Sphinx search for "Show Proof

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#7455]
#### Description of the problem
In https://coq.inria.fr/distrib/current/refman/, when I search for `Show Proof` or `"Show Proof"`, the 2 pages of results don't include the following, which seems the obvious thing someone would look for:

![image](https://user-images.githubusercontent.com/1253341/39728341-56aa7132-520b-11e8-9782-2e8834fb6d58.png)

**Comment by Zimmi48** [comment]
Thanks for the report. This was primarily due to the absence of indices for these commands. See #7461 for a fix. BTW, when searching for commands, I recommend using the command index, at the bottom of the left side-bar.

**Comment by jfehrle** [comment]
By the way, are we pushing changes to the documentation to the website immediately or will they wait until the next minor release?  If there are a significant number of changes being made due to the Sphinx conversion, it might be good to push immediately if that's not difficult to do.  Just a thought.

**Comment by Zimmi48** [comment]
Until now changes had been pushed only at release time. The problem is that this is still a manual process. Ideally I'd like to have some continuous deployment in place so that changes to the stable branch are pushed to the "current" online version of the manual and changes to the master branch are pushed to a new "dev" online version.

**Comment by maximedenes** [comment]
> By the way, are we pushing changes to the documentation to the website immediately or will they wait until the next minor release? If there are a significant number of changes being made due to the Sphinx conversion, it might be good to push immediately if that's not difficult to do. Just a thought.

IIUC, that would require classifying documentation changes (documentation fixes vs documented changes in Coq).

**Comment by Zimmi48** [comment]
@maximedenes Nope. That's unnecessary. That's the job of the backporting step. I suppose you didn't see my comment right above yours.

**Comment by Zimmi48** [comment]
In coq/www#69, I'm using the canonical address for GitLab CI artifacts to direct people to a development version of the reference manual.
