### ISSUE TITLE
#7456 ([toplevel] Don't ignore output filename provided by user in -o) should have a test case in the test-suite

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7457]
Adding an issue for this as requested by https://github.com/coq/coq/pull/7456#issuecomment-387233510

Probably the thing to do is to find the right category/folder for it, and add a custom `run.sh` script (as in the `coq-makefile` folder and the timing tests therein) to run `coqc` with `-o` on a dummy file and check that it creates a `.vo` file in the right place.

**Comment by ejgallego** [comment]
Thanks!

**Comment by ejgallego** [comment]
Not sure I can take this right away so letting other take over if they want.
