### ISSUE TITLE
Close STM 2.0

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7458]
As noted by @maximedenes the [STM 2.0 project page](https://github.com/coq/coq/projects/1) has gone stray and it serves no useful purpose anymore.

I am thus requesting we close the project, or someone takes over it.

**Comment by ejgallego** [comment]
There are 2 or 3 open PR trying to achieve that, I'm not sure how that is related to this issue.

**Comment by maximedenes** [comment]
Weren't those PR related with the STM 2.0 idea? Maybe it is just not clear to me what STM 2.0 is.

**Comment by ejgallego** [comment]
Closing now, of course you are all welcome to reopen.
