### ISSUE TITLE
The dates on the copyright notice at the bottom of the reference manual are wrong

### ISSUE THREAD

**Issue by amintimany** [coq/coq#7460]
The copyright notice at the bottom of [https://coq.inria.fr/refman/](https://coq.inria.fr/refman/#) right now says ```© Copyright 1999-1970, Inria.```. I'm not sure what the correct dates should be and hence I didn't try to create a pull request.

**Comment by Zimmi48** [comment]
The dates should be 1999-2018.

Duplicate of #7378
