### ISSUE TITLE
Linter reports whitespace issues not fixed by `git rebase --whitespace=fix`

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#7463]
Previous discussions on the linter has concluded that whitespace linting was mainly about aesthetics, IIUC.

I think it is fine to care about aesthetics, as long as the cost is low or non-existent. Running `git rebase --whitespace=fix` as part of my PR workflow is fine IMHO.

However, the linter currently reports "whitespace errors" which are not fixed by that `git` command, like a blank line at the end of a file. So please let me know if a command fixing all issues reported by the linter exists, and if not, what checks we should disable to make it true.

**Comment by maximedenes** [comment]
Note that it is also not fixed by the pre-commit hook.

**Comment by Zimmi48** [comment]
See also my comment there:

> I'm for this change if we can ensure that this criterion (no file with no newline at the end) can be enforced in the future.

**Comment by maximedenes** [comment]
Sorry, what is the link between #986 and this issue?

**Comment by Zimmi48** [comment]
Sorry, I didn't made the link explicit: the linter tests that there is *exactly* one newline at EOF. It could be made less strict to test that there is *at least* one newline at EOF (that's the really important part that #986 addressed) but that's not going to solve the problem that the pre-commit hook doesn't handle this automatically.

**Comment by gares** [comment]
> I think it is fine to care about aesthetics, as long as the cost is low or non-existent.

If we count the number of issues, rants, patches the white space linter has generated so far we can only reach the conclusion that:
- the (already payed) cost of this aesthetic was not low nor 0
- the expected future cost is hard to predict, since it was believed to be low or 0 from the start, and it was not.

We can either admit we are masochists and continue along the path to absolute beauty, or realize that what we are doing is losing time and stop.

**Comment by maximedenes** [comment]
I think it is already pretty obvious that we are masochists :)

**Comment by Zimmi48** [comment]
We are scientists: we experiment... on ourselves.

**Comment by SkySkimmer** [comment]
Let's just remove the aesthetic check #7464.

**Comment by gares** [comment]
> We are scientists

We may even revive the linter one day...

![It could work!](https://upload.wikimedia.org/wikipedia/it/thumb/f/f9/Frankenstein_Junior_scena_4.jpg/640px-Frankenstein_Junior_scena_4.jpg)
