### ISSUE TITLE
Anomaly: Inconsistent substitution of recursive notation.

### ISSUE THREAD

**Issue by Janno** [coq/coq#7474]
#### Version
8.7.1

#### Description of the problem

The following code throws an anomaly:

`Inconsistent substitution of recursive notation.`

```coq
Definition nothing {A} (a : A) (n : nat) := tt.

Notation "'test' b" :=
  (nothing ((fun x => .. ((fun z => true)) ..)) b) (at level 91).

Check test 1.
```

I don't know why it's letting me use the recursive notation syntax here as this notation is not recursive at all.

**Comment by ejgallego** [comment]
Fixed in 8.8.
