### ISSUE TITLE
Codesigning in `Makefile`

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7476]
There is some special code in the makefile to sign OSX binaries [see `LINKMETADATA` et friends]

However, @maximedenes mentioned that the signing does happen today at the package level, so I wonder what's going on. Is that dead code?

There is no real documentation for this feature other than 9b0dbb30d653bf35145e1e77f0fecfc9d79aa81d .

I have opened PR #7475 to see how the packages look now.

**Comment by ejgallego** [comment]
At least CI-wise the removal of such signing step seems to have no effect, I guess we'll need some testing from OSX users.

**Comment by maximedenes** [comment]
I think @vbgl can take over as part of the work on the packaging infrastructure for 8.10.
