### ISSUE TITLE
Timing tool should be upgraded to python3.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7485]
#### Version

Current master 83b2e3430da9ba6d234a78c5b2910070c13d4152 but it has always been the case IIRC.

#### Operating system

NixOS 18.03.132021.c0c5571ec1a (Impala) but it was also the case with older versions of this system.

#### Description of the problem

The log is:

```
+ set -e
++ dirname ./run.sh
+ cd .
++ cd ../../../..
++ pwd
+ COQLIB=/home/theo/coq
+ export COQLIB
+ ./001-correct-diff-sorting-order/run.sh
+ set -e
++ dirname ./001-correct-diff-sorting-order/run.sh
+ cd ./001-correct-diff-sorting-order
+ /home/theo/coq/tools/make-both-time-files.py time-of-build-after.log.in time-of-build-before.log.in time-of-build-both.log
Traceback (most recent call last):
  File "/home/theo/coq/tools/make-both-time-files.py", line 13, in <module>
    left_dict = get_times(args[1])
  File "/home/theo/coq/tools/TimeFileMaker.py", line 44, in get_times
    lines = f.read()
  File "/nix/store/128m147iv3n0dnlq1pwd2pjfqxlsaisk-python3-3.6.4-env/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1396: ordinal not in range(128)
==========> FAILURE <==========
    coq-makefile/timing/run.sh...Error!
```

I'm using the dependencies provided by `default.nix`. Is this reproducible on other system when inside `nix-shell` (possibly with option `--pure`)? @maximedenes Since you are also on NixOS, have you had the same failures?

CC @JasonGross

**Comment by JasonGross** [comment]
Seems like it might be a python2/python3 issue?

**Comment by JasonGross** [comment]
If you change `#!/usr/bin/env python` to `#!/usr/bin/env python2` at the top of the .py files, does that fix things?

**Comment by Zimmi48** [comment]
Indeed, this is it. But I don't like this. In https://github.com/coq/coq/pull/745#issuecomment-307182016 you claimed that these timing scripts were compatible with both python2 and python3. I guess it was true at the time but then it changed over time. Anyways, given that our Sphinx infrastructure depends on python3, I would really like to avoid depending both on python2 and python3 in Coq.

**Comment by JasonGross** [comment]
Yeah, or possibly I only tested them on a very limited range of tests which didn't have any non-ascii

**Comment by Zimmi48** [comment]
Quoting from #7652:

> I don't presently have the time to port these to python3, but my guess is that if you update the file/Unicode handing, that'll be the only change necessary. I coded them in python2 mostly from habit.
