### ISSUE TITLE
Ltac match ignores universe annotations

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7492]
```coq
Universes i j.
Constraint i < j.
Goal False.
Proof.
  match constr:(Type@{i}) with Type@{j} => idtac end.
Abort.
```
(note that it does distinguish Prop/Set/Type)

**Comment by JasonGross** [comment]
Another test, to check that `match` does not have side effects.  I think both matches here should succeed. 
 (I could be convinced that both should fail (in which case `match constr:(Type@{i} with Type => idtac end` should still succeed, and the rule would be that we check compatibility between flexible (non-user) universes, and equality between user-given universes)), but it's not okay to have one succeed and the other fail:
```coq
Universes i j k.
Constraint i < j.
Goal False.
Proof.
  match constr:(Type@{i}) with Type@{k} => idtac end.
  match constr:(Type@{j}) with Type@{k} => idtac end.
Abort.
```

**Comment by ppedrot** [comment]
I would personally implement a `match` that does *not* perform any kind of unification, and promote the use of a proper unifying `constr_eq` function instead. That is consistent with my view of the non-linear matching of variables from #5366.

**Comment by SkySkimmer** [comment]
Now says "unexpected universe in pattern"
