### ISSUE TITLE
coqdep with _CoqProject warns about redundant .ml files

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#7494]
Tested with coq 8.8.

To add ocaml files to `_CoqProject`, the example in the manual uses the `-I` option and lists each file.

https://coq.inria.fr/distrib/current/refman/practical-tools/utilities.html#building-a-coq-project-with-coq-makefile

However we get warnings when `make` generates `.coqdeps.d`: `coqdep` somehow sees the same files twice, once via `-I`, once via the explicit list.

### Steps to reproduce

```
# Minimal setup
mkdir src
touch src/a.ml src/b.ml
echo "-I src/ src/a.ml src/b.ml" > _CoqProject

# Build
coq_makefile -f _CoqProject -o Makefile
make
```

Output:

```
COQDEP VFILES
*** Warning: b.ml already found in src (discarding src/b.ml)
*** Warning: a.ml already found in src (discarding src/a.ml)
CAMLDEP src/b.ml
CAMLDEP src/a.ml
```

Expected output: without the warnings.

---

The command that actually generates the warnings is:

```
coqdep -f _CoqProject
```

And I noticed that passing the `_CoqProject` parameters directly to `coq_makefile` doesn't cause the warnings:

```
coq_makefile -I src/ src/a.ml src/b.ml -o Makefile
make
```

because the `coqdep` command becomes:

```
coqdep -I src/
```

So another question is: shouldn't these two `coq_makefile` commands produce the same `Makefile`?

**Comment by SkySkimmer** [comment]
See #7413
