### ISSUE TITLE
coqdoc parsing problem

### ISSUE THREAD

**Issue by jimyu94** [coq/coq#7497]
#### Version
8.7.1

#### Operating system
CentOS

#### Description of the problem

Please see the link https://stackoverflow.com/questions/49501140/what-is-the-evalop-in-coq-compcert

**Comment by herbelin** [comment]
Hi @jimyu94, would you have a way to reproduce it? I tried to apply `coqdoc` on a simple file with only `Ltac EvalOp := idtac.` and I did not notice any problem.
