### ISSUE TITLE
ENOMEM on `par: abstract` should not leave over subgoals

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7523]
#### Version

master (8.9+alpha)

#### Operating system

Linux

#### Description of the problem

If a subprocess of coqc spawned via `par: abstract` is terminated with ENOMEM, the parent process happily leaves the goal over.  It should instead result in the `par:` tactical failing with a Coq-generated out-of-memory error.

See https://github.com/coq/coq/pull/7514#discussion_r188141367
cc @gares @ejgallego

**Comment by SkySkimmer** [comment]
Duplicate https://github.com/coq/coq/issues/16732
