### ISSUE TITLE
[ci] INRIA Cloud meta issue.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7534]
This is an issue to track progress in using the INRIA Cloud. Ideally, we would spawn runners dynamically as needed, but I am not sure the INRIA infrastructure can take images in the format we'd like. At the very least we should have a core runner using docker machine coordinating the rest, and maybe dynamically balancing them.

Critical point:
- the windows runners are insecure due their use of shell, this makes packages created by such runners not usable, we should disable artifacts until the runner can be reinstalled and properly secured.

Some points to consider:

- Scripts for runner management should be created.
- docker machine or kubernetes could be used for automatic management.

Related: #7344 #7528

**Comment by ejgallego** [comment]
In case this is not clear, the INRIA windows runners must be considered as compromised as of today; not urgent, but certainly not low priority either.

**Comment by maximedenes** [comment]
I won't have time to work on it for some time. Any volunteer?

**Comment by ejgallego** [comment]
I think that's not urgent, for now let's not advertise the artifacts on the build until we figure out a better strategy to install the windows workers.

**Comment by ejgallego** [comment]
Something that is not clear is if the windows scripts are using -j2

**Comment by ejgallego** [comment]
For the moment we are moving away from INRIA cloud, I'll subsume this issue by #9401
