### ISSUE TITLE
`make clean` should not fail on a fresh clone

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7542]
#### Version

8.9+alpha (5281317cb558f2b9aa6f854b9c7aeb617beba8e6)

#### Operating system

Linux

#### Description of the problem

`make clean` should succeed on a fresh clone.  Since a2f4a43833a29a5ede5905225b814c33e3a46132, it says
```
make -C test-suite clean
make[1]: Entering directory '/home/jgross/Documents/repos/coq-temp/test-suite'
Makefile:28: ../config/Makefile: No such file or directory
make[1]: *** No rule to make target '../config/Makefile'.  Stop.
make[1]: Leaving directory '/home/jgross/Documents/repos/coq-temp/test-suite'
Makefile:216: recipe for target 'indepclean' failed
make: *** [indepclean] Error 2
```

`git bisect` says:

> a2f4a43833a29a5ede5905225b814c33e3a46132 is the first bad commit
> commit a2f4a43833a29a5ede5905225b814c33e3a46132
> Author: Paul Steckler <steck@stecksoft.com>
> Date:   Fri Feb 23 14:23:19 2018 -0500
> 
>    add unit tests to test suite
> 
> ```
> :100644 100644 e2a97b3a121dde0aac31a64802a53dfba31b17ac f1960ba684548bda3fae4c1d80f435be49406e96 M      .gitignore
> :100644 100644 dbe152b5b5d37493bbd2ecefea95f5fd05a4b67e 44d24eaa28b75bf37c395099707771306ebb6eff M      .travis.yml
> :100644 100644 793afb661ec7b08b6129ff02279424fdb59cdfbf f914de5a61dc9d89f37be313850c6a0a4b305f72 M      Makefile
> :100644 100644 eed41fbe71cdad0cfb8fe1355a7b82beed9efbf4 f3b39ff2608e38a64ce62a000757beaa475a7eff M      Makefile.common
> :040000 040000 c57b6a5071bcfdefdbe6252d5fdd7ea40ce8f63c 62bf595f35c595a26d61ff1eb29ea1e23ad472c7 M      dev
> :040000 040000 a2a4fe38e37973706681359d520fa8bc433463dd 4ca11cc640035fed631b961e50eefda9bcf98d33 M      test-suite
> ```
> bisect run success

**Comment by JasonGross** [comment]
This was caught by my debian packaging script, btw.

Could we add a test for this?  e.g., before building Coq, run `make clean` on the fresh clone in ci?

**Comment by ejgallego** [comment]
> Could we add a test for this? e.g., before building Coq, run make clean on the fresh clone in ci?

This makes sense to me.
