### ISSUE TITLE
Operator <? is defined with 4 different levels / associativities in standard library

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#7549]
The operator <? is defined in the standard library at different places as follows:

theories\Init\Nat.v(90):                     Infix "<?" := ltb     (at level 70) : nat_scope.
theories\Arith\PeanoNat.v(759):              Infix "<?" := Nat.ltb (at level 70) : nat_scope.
theories\Numbers\Natural\Peano\NPeano.v(93): Infix "<?" := Nat.ltb (at level 70) : nat_scope.

theories\NArith\BinNat.v(952):               Infix "<?" := N.ltb   (at level 70, no associativity) : N_scope.
theories\NArith\BinNatDef.v(140):            Infix "<?" := ltb     (at level 70, no associativity) : N_scope.
theories\PArith\BinPos.v(1881):              Infix "<?" := Pos.ltb (at level 70, no associativity) : positive_scope.
theories\PArith\BinPosDef.v(307):            Infix "<?" := ltb     (at level 70, no associativity) : positive_scope.
theories\ZArith\BinInt.v(1262):              Infix "<?" := Z.ltb   (at level 70, no associativity) : Z_scope.
theories\ZArith\BinIntDef.v(217):            Infix "<?" := ltb     (at level 70, no associativity) : Z_scope.

theories\Structures\Orders.v(199):           Infix "<?" := E.ltb   (at level 35).

theories\ZArith\Int.v(73):                   Infix "<?" := ltb.

Since the parser does not support changing the definition of an operator, this means that all libraries with different definitions (or at least the notation sin there) are incompatible and cannot be loaded together. I would say this is a bug.

Coq Version 8.8.0

Unless someone feels responsible for this, I can fix this (and other operators as well). I would set everything to (at level 70, no associativity).

Of cause this might breaks some code out there.

**Comment by SkySkimmer** [comment]
Fixed by 528dd28a48dd7b1898212e2aae9b43bb19fb91cc
