### ISSUE TITLE
Typecheck fails with two evars but with enough information

### ISSUE THREAD

**Issue by joonwonc** [coq/coq#7553]
#### Version

8.8.0

#### Operating system 

Any

#### Description of the problem

- Minimized example: https://gist.github.com/joonwonc/cb710d01f6b04ea6846d9999cf4df44d
- Typecheck fails when at least two evars are given, but with enough information about them. It succeeds when generating subterms with [open_constr] first, each has a single evar now, and composing them later.

**Comment by SkySkimmer** [comment]
Gist is 404
