### ISSUE TITLE
Broken link for Delahaye paper on LTAC

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#7576]
The link referencing the LTAC paper in https://coq.inria.fr/distrib/current/refman/zebibliography.html#del00 is broken.  Is it still available?

**Comment by jfehrle** [comment]
A quick search using the paper's title turns up a PDF at https://pdfs.semanticscholar.org/51e8/2c766a9fb5d476c00dbe96530a5b4c0ded92.pdf

**Comment by Zimmi48** [comment]
There's also a PDF on his personal webpage: http://www.lirmm.fr/~delahaye/papers/ltac%20(LPAR%2700).pdf
Just removing the link could be a good fix given how easy it is to look for the paper by its name...

**Comment by jfehrle** [comment]
That would be unfriendly.  The reference is used in the second sentence of the LTAC section of the manual and it seems to be providing an essential introduction that's not in the documentation:

`If you want to know more regarding this language and especially about its foundations, you can refer to [Del00]. `

**Comment by jfehrle** [comment]
Given its significance, it seems like something that should perhaps be replicated on the Coq website.  The PDF is so-so: the pages are too rendered too small, a little hard to read (2+ inch margins all around).
