### ISSUE TITLE
`kind:meta` should have a description

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7579]
What issues should `kind: meta` apply to?  (Other than this one, which talks about `kind: meta` itself.)  E.g., does it apply to issues about PR templates and GitHub labels, or is that just `kind: infrastructure`?

**Comment by ejgallego** [comment]
meta for example applies to #6477

**Comment by Zimmi48** [comment]
I think @SkySkimmer created this label but I would say it applies to issues that more organizational and less about code. I don't have a good suggestion for a description yet...

**Comment by SkySkimmer** [comment]
I put in a thing.
