### ISSUE TITLE
`make install` on fiat-crypto on Windows emits `/bin/sh: /cygdrive/d/Coq-8.8/bin/coqtop: Argument list too long`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7584]
#### Version

8.8.0

#### Operating system

Windows 10

#### Description of the problem

If you put a few thousand files in `_CoqProject`, then `make install` will emit
```
/bin/sh: /cygdrive/d/Coq-8.8/bin/coqtop: Argument list too long
```
because the function
```make
# helpers
vo_to_obj = $(addsuffix .o,\
  $(filter-out Warning: Error:,\
  $(shell $(COQTOP) -q -noinit -batch -quiet -print-mod-uid $(1))))
```
is invoked on `$(VOFILES)`, and this is too many arguments for `coqtop`.

**Comment by eponier** [comment]
As far as I can tell, this is not too many arguments for `coqtop`, but too many arguments for the shell.

**Comment by SkySkimmer** [comment]
Note that Coq's makefile has 
```make
vo_to_obj = $(foreach vo,$(1),$(dir $(vo)).coq-native/$(subst /,_,$(patsubst theories/%,NCoq_%,$(patsubst plugins/%,NCoq_%,$(vo:.vo=.o)))))
```
Is that the same thing except without calling shell/coqtop?

**Comment by JasonGross** [comment]
Sure, it is too many arguments for cygwin shell to pass to coqtop.

**Comment by JasonGross** [comment]
> Is that the same thing except without calling shell/coqtop?

That seems specialized to `-R theories Coq - R plugins Coq` or something, no?

**Comment by Zimmi48** [comment]
Is anyone working on this? Otherwise, I'll remove from the 8.8.1 milestone.

**Comment by Zimmi48** [comment]
Removing from the milestone.
