### ISSUE TITLE
Error: Anomaly "Uncaught exception Not_found" with existential variables

### ISSUE THREAD

**Issue by jad-hamza** [coq/coq#7586]
#### Version

8.8.0

#### Operating system

Debian

#### Description of the problem

Maybe a duplicate of https://github.com/coq/coq/issues/7392

```Coq
Require Import Coq.Lists.List.

Parameter term: Set.

Inductive relation: list nat -> term -> Prop :=
| ER: forall l t S,
    (forall x: nat, ~In x S -> relation l t) ->
    relation l t
.

Inductive relation2: nat -> Prop :=
| ER2: forall n,
    relation2 n ->
    relation2 (S n)
.

Lemma l:
  forall l t,
    relation l t ->
    forall n l',
      relation2 n ->
      relation l' t.
Proof.
  induction 1; intuition.
  - apply ER with (l' ++ S); intuition.
    eapply H0.
    + admit.
    + intuition.
      rewrite in_app_iff in *.
      intuition.
      apply ER2.
      simpl in *. (* Error: Anomaly "Uncaught exception Not_found." *)
```

**Comment by ppedrot** [comment]
Implementing `In` as an axiom still triggers the bug, but removing the import of the List module makes it disappear. There is something fishy going on.

**Comment by jad-hamza** [comment]
The `rewrite in_app_iff in *` seems crucial as well

**Comment by ppedrot** [comment]
Yes, I think setoid_rewrite is creating an ill-typed evar. I'll post a smaller example.

**Comment by ppedrot** [comment]
Here is a small example. The Setoid module is needed to rewrite under the implication. The anomaly raised by simpl is merely an indication that something is wrong. The actual problem is that the goal is ill-typed as it contains an evar with a variable argument that does not exist in the context.
```
Require Setoid.

Axiom axm : False <-> True.

Inductive R : nat -> Prop := ER : forall n, R n -> R (S n).

Goal
  (forall (n : nat), R n -> False) ->
  (True -> False) ->
  False.
Proof.
intros H0 H1.
eapply H0.
rewrite -> axm in H1.
clear H1.
apply ER.
simpl.
```

**Comment by ppedrot** [comment]
Even simpler, no need to rewrite, clearing is enough.
```
Inductive R : nat -> Prop := ER : forall n, R n -> R (S n).

Goal (forall (n : nat), R n -> False) -> True -> False.
Proof.
intros H0 H1.
eapply H0.
clear H1.
apply ER.
simpl.
```

**Comment by jad-hamza** [comment]
Thanks for investigating

**Comment by ppedrot** [comment]
Found the bug, and wrote a patch: it's due to the unification using the unfiltered environment when it should have filtered it first. I'm going to see whether the patch breaks anything.
