### ISSUE TITLE
[question] Memory use and toplevel binaries.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7588]
In #6859 , the model for the STM workers was changed from "one binary + 3 loadable plugins" to "4 binaries".

I did some informal memory measurements and I couldn't indeed see any noticeable impact, but IMHO this issue should be better understood before we release 8.9.

If it turns out that the new strategy is wasteful w.r.t. memory use, I will indeed add back to `coqtop` the capability to load plugins, which should be really easy.

IMHO, `coqidetop` doesn't have that problem so it makes sense to stay as a separate binary indeed.

**Comment by gares** [comment]
I see no reason why the new setup would consume more memory, or be slower at startup

**Comment by ejgallego** [comment]
At least in Linux, RO sections of the same binary will be shared.

**Comment by ejgallego** [comment]
I just did the test, this is not a problem, in fact 8.9 has a slightly better memory footprint.
