### ISSUE TITLE
refine should be better at using BIDI to infer match return clauses

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7605]
#### Version

8.8.0

#### Description of the problem

I think the `refine` in the second example here should succeed:
```coq
Axiom admit : forall {T}, T.
Definition foo (x : nat) : x + 1 = 1 + x
  := match x with
     | O => eq_refl 1
     | S x' => admit
     end. (* success *)
Definition bar (x : nat) : x + 1 = 1 + x.
  refine match x with
         | O => eq_refl 1
         | S x' => admit
         end. (* Error:
Ltac call to "refine (uconstr)" failed.
In environment
x : nat
The term "eq_refl" has type "1 = 1" while it is expected to have type
 "?n@{x1:=0} + 1 = 1 + ?n0@{x1:=0}".
 *)
```

It's quite annoying to have to include complicated return clauses just to be able to fill in the holes one at a time with `refine`.

cc @herbelin (apologies if this is a duplicate of some bug fixed by #262)

**Comment by ejgallego** [comment]
Does it improve if you set the program mode on?

**Comment by JasonGross** [comment]
@ejgallego Is there a `program refine` tactic?  Being in an obligation does not change the behavior of refine, but if what you're asking is if the following works, it does
```coq
Require Import Program.
Program Definition foo (x : nat) : x + 1 = 1 + x
  := match x with
     | O => eq_refl 1
     | S x' => _
     end.
```

**Comment by ejgallego** [comment]
The type inference system already has a nicer bidirectional inference mode, but it is not enabled by default due to compatibility reasons. It is independent from the rest of program.

See bug #6216

**Comment by ejgallego** [comment]
So I think you can do `Set Program Mode` [or something close to this] to enable the new goodies in your development. And of course a flag could be added to `refine`, but IMHO we should just move forward with #6216 and make the new modes the default, performance allowing.

**Comment by JasonGross** [comment]
I do not want `Set Program Mode`.  Here are some things that I dislike about `Set Program Mode`:
1. It breaks `Fixpoint foo (x : nat) : nat.` (error message: `Error: Program Fixpoint needs defined bodies.`)
2. It needlessly complicates the bodies of simple `match` statements, e.g.,
```coq
Set Program Mode.
Fixpoint foo (x : nat) : x + 1 = 1 + x
  := match x with
     | O => eq_refl 1
     | S x' => f_equal S (foo x')
     end.
Print foo.
(* foo = 
fix foo (x : nat) : x + 1 = 1 + x :=
  let program_branch_0 : 0 = x -> 0 + 1 = 1 + 0 := fun _ : 0 = x => eq_refl in
  let program_branch_1 : forall x' : nat, S x' = x -> S x' + 1 = 1 + S x' :=
    fun (x' : nat) (_ : S x' = x) => f_equal S (foo x') in
  match x as x' return (x' = x -> x' + 1 = 1 + x') with
  | 0 => program_branch_0
  | S x' => program_branch_1 x'
  end eq_refl
     : forall x : nat, x + 1 = 1 + x
*)
```

So, yes, `Set Program Mode` makes the `refine` go through, but it leaves over the wrong goals (goals that have extra equality hypotheses and casts).

**Comment by ejgallego** [comment]
Note that I was not advocating the use of program mode itself, just pointing out the possibility.

To me a flag controlling the bidi inference would be very well received, and it would provide a path to enable it by default.

**Comment by SkySkimmer** [comment]
Works since 8.10

**Comment by SkySkimmer** [comment]
(Probably duplicate https://github.com/coq/coq/issues/6464)
