### ISSUE TITLE
Coq compilation: What is and where is num ?

### ISSUE THREAD

**Issue by mprevot** [coq/coq#7608]
#### Version
8.8.0
#### Operating system 
Linux ubuntu 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
#### Description of the problem
./configure fails like this:

> 
> You have OCaml 4.06.1. Good!
> You have OCamlfind 1.8.0. Good!
> You have Camlp5 7.01. Good!
> You have native-code compilation. Good!
> Num library not installed, required for OCaml 4.06 or later
> Configuration script failed!

However it was not mentionned of any `Num` in INSTALL. Is it this one : [https://opam.ocaml.org/packages/num/](https://opam.ocaml.org/packages/num/) ?

**Comment by ppedrot** [comment]
Indeed, that's this package. Probably needs to be documented I guess.

**Comment by ejgallego** [comment]
Good point, `num` used to be included with OCaml but now it is a separate library, we need to update the README indeed.

**Comment by ejgallego** [comment]
Good point again, for CoqIDE tho the dependencies are documented in INSTALL.ide. Not optimal IMHO.

**Comment by Zimmi48** [comment]
File `INSTALL` at the root of the repository / archive, contains:

```
   Opam (https://opam.ocaml.org/) is recommended to install ocaml and
   the corresponding packages.

   $ opam install ocamlfind camlp5 lablgtk-extras

   should get you a reasonable OCaml environment to compile Coq.
```
I believe that `camlp5.gramlib` is included in `camlp5` and `lablgtk2` is a dependency of `lablgtk-extras` so the only actually missing package is `num`, right?

**Comment by ejgallego** [comment]
> is num, right?

Yup, tho the dependency on `lablgtk-extras` is technically speaking wrong, it should be `lablgtk conf-gtksourceview`.

**Comment by Zimmi48** [comment]
Should we change this as well?

**Comment by ejgallego** [comment]
Sure that would be more accurate and IMHO better future-proof.

**Comment by RalfJung** [comment]
For future people finding this via google, you might be running into https://github.com/ocaml/opam-repository/issues/10925. Try `opam uninstall num; opam reinstall ocamlfind`.
