### ISSUE TITLE
coqide doesn't display correctly

### ISSUE THREAD

**Issue by mprevot** [coq/coq#7610]
#### Version

The Coq Proof Assistant, version 8.8.0 (May 2018)
compiled on May 26 2018 22:42:57 with OCaml 4.06.1

#### Operating system

Linux ubuntu 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#### Description of the problem

I can't see icons of the toolbar. I can't the icons in the menu items too (except the red ones).

![coqide](https://user-images.githubusercontent.com/8375354/40580415-d73f5024-613d-11e8-81cd-f400e8b45d5f.jpg)

**Comment by ejgallego** [comment]
Umm, I guess you've installed CoqIDE using OPAM? Are you using the default Ubuntu Gnome Desktop?

**Comment by ejgallego** [comment]
Also be careful if you are using OPAM not to install any OCaml package using `apt`.

Sadly, the Coq packages distributed with Ubuntu/Debian are basically unmaintained.

**Comment by ejgallego** [comment]
By the way if you are using OPAM I recommend doing `opam install coqide`.

**Comment by mprevot** [comment]
I compiled the 8.8.0 release tonight.

I'm using KDE.

I installed opam and then the rest from opam, except few dependencies with apt.

If use `opam install coqide`, what will happen with the binaries I just installed (coqide is in /usr/local/bin as expected) ?

What if I want this to be available to all my users ?

**Comment by mprevot** [comment]
I'm using sources (opam, coq. ocaml) or apt when it's up to date. Anyway, `opam install coqide` fails: [7611](https://github.com/coq/coq/issues/7611)

**Comment by mprevot** [comment]
I just tried with the apt package, it installed coq 8.6, and we got the same problem.

**Comment by ejgallego** [comment]
This seems to be a problem of a missing gtk icon theme. Does the problem go away if you install `gnome-desktop`?

**Comment by ejgallego** [comment]
This is indeed a packaging problem, we have confirmed the bug in other systems. Installing `gnome-desktop` (or a gtk-icon theme) should fix; please reopen if the issue persists.

**Comment by Zimmi48** [comment]
The issue with the apt package could be considered a Debian bug and reported there.
The issue with the opam / source install could be considered a documentation bug: @ejgallego, you could maybe add a note about this in `INSTALL`.

**Comment by SorinS** [comment]
Had the same issue on MacOSX using brew. I had to do:
brew install gnome-icon-theme
and now my coqide has icons. HTH...

**Comment by YumaVlaicu** [comment]
> Had the same issue on MacOSX using brew. I had to do:
> brew install gnome-icon-theme
> and now my coqide has icons. HTH...

I had the same issue there are only tofu icons when I installed coqide using opam (ver. 2.0.6) but @SorinS's solution worked on my mac!
By the way, when I installed coqide using *brew* (ver. 2.2.14) before, it worked properly.
Note that brew's *gnome-icon-theme* and opam's *conf-gnome-icon-theme3* are installed!

**Comment by vzhn** [comment]
Same issue on Red Hat Enterprise Linux distribution

**Comment by vzhn** [comment]
Please reopen.

**Comment by Zimmi48** [comment]
@vzhn As expressed above, if you are using your distribution's package manager, this is an issue with your distribution's package and you should report the bug to the distribution maintainers. If you have this issue when building Coq with opam, it could be an opam packaging issue, but I doubt it given that the opam file now explicitly depends on `conf-adwaita-icon-theme`, which [declares depexts for many distributions, including RHEL](https://github.com/ocaml/opam-repository/blob/master/packages/conf-adwaita-icon-theme/conf-adwaita-icon-theme.2/opam).

**Comment by vzhn** [comment]
Thank you @Zimmi48

**Comment by mprevot** [comment]
On ubuntu 23.04, `sudo apt install adwaita-icon-theme` does not help.
