### ISSUE TITLE
opam install coqide fails

### ISSUE THREAD

**Issue by mprevot** [coq/coq#7611]
#### Version

opam:
context     2.0.0~rc2 | linux/x86_64 | ocaml-base-compiler.4.06.1 | https://opam.ocaml.org/2.0#b36f28db

#### Operating system

Linux ubuntu 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#### Description of the problem

As suggested in [#7610](https://github.com/coq/coq/issues/7610), I gave a try to installing coq/coqide through opam, but this fails.

> <><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> [coq.8.8.0] downloaded from cache at https://opam.ocaml.org/2.0/cache
> [coqide.8.8.0] downloaded from cache at https://opam.ocaml.org/2.0/cache
> 
> <><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> [ERROR] The compilation of coq failed at "/home/mprevot/.opam/opam-init/hooks/sandbox.sh build make -j1".
> 
> === ERROR while compiling coq.8.8.0 ==========================================#
>  context     2.0.0~rc2 | linux/x86_64 | ocaml-base-compiler.4.06.1 | https://opam.ocaml.org/2.0#b36f28db
>  path        ~/.opam/default/.opam-switch/build/coq.8.8.0
>  command     ~/.opam/opam-init/hooks/sandbox.sh build make -j1
>  exit-code   2
>  env-file    ~/.opam/log/coq-65198-2c871f.env
>  output-file ~/.opam/log/coq-65198-2c871f.out
> ## output ###
>  [...]
>  15 states, 827 transitions, table size 3398 bytes
>  tr -d "\r" < kernel/byterun/coq_instruct.h | sed -n -e '/^enum/p' -e 's/,//g' -e '/^  /p' | \
>  awk -f kernel/make-opcodes > "kernel/copcodes.ml" || (RV=$?; rm -f "kernel/copcodes.ml"; exit ${RV})
>  OCAMLLIBDEP  plugins/MLLIBFILES plugins/MLPACKFILES
>  OCAMLC -c grammar/q_util.mli
>  File "grammar/q_util.mli", line 30, characters 29-39:
>  Error: Unbound module MLast
>  Makefile.build:375: recipe for target 'grammar/q_util.cmi' failed
>  make[1]: *** [grammar/q_util.cmi] Error 2
>  make[1]: Leaving directory '/home/user/.opam/default/.opam-switch/build/coq.8.8.0'
>  Makefile:190: recipe for target 'submake' failed
>  make: *** [submake] Error 2

**Comment by ejgallego** [comment]
Sorry for the lack of response. Is this still an issue? If so please reopen.
