### ISSUE TITLE
`Create HintDb` has no effect for autorewrite hint bases

### ISSUE THREAD

**Issue by Armael** [coq/coq#7630]
#### Version
Coq 8.8

#### Description of the problem
```
Goal True.
  Create HintDb foo.
  autorewrite with foo.
```

```
Ltac call to "autorewrite with (ne_preident_list) (clause_dft_concl)" failed.
Rewriting base foo does not exist.
```

This is likely due to the fact that autorewrite hint bases are maintained separately from the auto hints. Still, it is somewhat problematic to not be able to create upfront a new autorewrite hint base.

**Comment by JasonGross** [comment]
I seem to recall `Create Rewrite HintDb` or `Create RewriteDb` being a thing, though I might be mixing up ` Create` and ` Print`?

**Comment by Zimmi48** [comment]
Closing in favor of the duplicate #14028.
