### ISSUE TITLE
autoapply is incorrectly documented but maybe we should fix the syntax instead

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7632]
#### Version

8.8.0

#### Description of the problem

https://coq.inria.fr/refman/addendum/type-classes.html#coq:tacn.autoapply says the syntax is `autoapply term with ident` but the actual syntax is `autoapply term using ident`.
However, we can notice that the actual syntax is inconsistent with the general practice of having `with` as a keyword for hint databases and `using` to add specific lemmas.
So maybe instead of fixing the doc, we should change the syntax and deprecate the current one...

cc @mattam82

**Comment by maximedenes** [comment]
@mattam82 what's your take on this?

**Comment by mattam82** [comment]
We should rather fix the syntax
