### ISSUE TITLE
Instance loses location information

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7636]
```coq
Require Import ZArith.

Class Foo (z : Z -> Z -> Z).

Lemma foo0 : Foo Zmin. Abort.
Instance foo : Foo Zmax.
```
prints
```
File "/tmp/foo.v", line 6, characters 0-22:
Warning: Zmin is Z.min [compatibility-notation,deprecated]
Warning: Zmax is Z.max [compatibility-notation,deprecated]
```
ie the second warning has no location.

Errors get the location of the whole command for Instance.

**Comment by herbelin** [comment]
Fixed by #7681 except the general problem about locating warnings from `Instance` at least with the location of the sentence. Probably stm-related (while trying to print the warning, the `Stm.get_ast` in `Coqloop.extract_default_loc` fails to find the corresponding `id`).
