### ISSUE TITLE
Provide an id to allow matching goals in prior proof steps with the corresponding goal in a later proof step

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#7653]
#### Description of the problem

Currently there's no easy way to match a goal in a prior proof step with the current proof step--even if the goals are unchanged.  The current proof diff code (#6801) deals with this crudely--it compares the first focused goal in the old and new proof.  This is frequently correct, but there are common use cases where the new first goal is not a transformation of the old first goal, in which case showing diffs is not really useful.  Also, some tactics modify multiple goals--it would be nice to show diffs on all goals that have changed but there's no easy way to know which ones should be compared.

If a proof step converts G -> G' , both goals should have the same id (maybe call is "ancestry id"?).

**Comment by ejgallego** [comment]
Indeed that would be great, however it is a bit tricky to implement due to the primitive proof engine not having a refine primitive, so for those using `tclEVARS` is a bit hard to track what happened.

We need to think about this.

**Comment by Zimmi48** [comment]
Indeed, it's far from trivial. Currently we can only provide a very basic notion of relationship between goals: which one generated which. It has been considered for a long time by @herbelin and me and maybe some others to add a notion of side-goals and main goal, but there is no such thing right now.

> If a proof step converts G -> G' , both goals should have the same id (maybe call is "ancestry id"?).

Well, no, because a goal G can generate several sub-goals and then you would end up with all your goals sharing the same id. What you could want is each goal having an id (they actually already have one) and each goal storing the id of its parent (not currently done).

**Comment by jfehrle** [comment]
> Well, no, because a goal G can generate several sub-goals and then you would end up with all your goals sharing the same id. What you could want is each goal having an id (they actually already have one) and each goal storing the id of its parent (not currently done).

I had supposed that new goals could be distinguished from existing goals and hence could be assigned a new id and that the id would simply be copied when G -> G'.  But that distinction may not possible to make.  Doing it as you suggest is reasonable.

**Comment by Zimmi48** [comment]
When a goal is refined into several subgoals, the corresponding hole (existential variable) is instantiated with a term containing several new holes. No hole has a particular status with respect to the previous one. At least, not in the current model. As I was explaining, @herbelin and I considered tagging these hints with "main goal" or "side goal" annotations, but even in this case, there could be several main goals.

E.g. if I want to prove `A /\ B` and I do `split`, the two subgoals are `A` and `B`. It wouldn't make much sense to consider only one of them the main goal. On the other hand, when I use the rewrite tactic and must prove pre-conditions, these are side goals.

**Comment by jfehrle** [comment]
Could you perhaps infer old goal/new goal relationships using the proof expression (i.e. what you see from "Show Proof.")?  The path from the root of the expression to the "?Goal999@" elements within seem to be preserved between proof steps.

(a wild guess)

**Comment by Zimmi48** [comment]
Yes, I think so, but storing the parent id at the time of creating the children existential variables (sub-goals) looks conceptually simpler to me. Each existential variable has some information attached to it:

https://github.com/coq/coq/blob/f6538f1a7f8ad2bdc0bc446d4ca35078d55d63ee/engine/evd.mli#L90-L107

and in particular the `evar_source` field contain information that can be in the following sum type:

https://github.com/coq/coq/blob/f6538f1a7f8ad2bdc0bc446d4ca35078d55d63ee/engine/evar_kinds.ml#L25-L38

You can see that there is a `GoalEvar` constructor that could be extended to take as argument the id of its parent.

**Comment by jfehrle** [comment]
>Indeed, it's far from trivial.

Is it the design that's non-trivial or that it requires touching many bits of code?  Is it something I might make progress on if someone could point me in the right direction and keep me on the right path?

(Extracting the information from the proof seems conceptually simple and like something I might be able to work out.  But not elegant--doing it the hard way.)

**Comment by jfehrle** [comment]
#8247 solved this problem.  Unchanged goal ids are preserved.  That makes it possible to identify the parent goal by matching the old and new proof expressions.
