### ISSUE TITLE
The error message for "Local Local Lemma A." changed in 8.9

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7659]
#### Version

8.9+alpha

#### Description of the problem

The error message for `Local Local Lemma A.` used to be `Syntax error: [vernac_poly] expected after 'Local' (in [vernac]).` (in 8.8.0) and it has become `No focused proof (No proof-editing in progress).` (in 8.9+alpha).
It is a weird error message...

**Comment by ejgallego** [comment]
This is fixed on master.
