### ISSUE TITLE
Plugin API for defining terms is confusing

### ISSUE THREAD

**Issue by tlringer** [coq/coq#7665]
#### Version

Coq 8.8

#### Description of the problem

As a plugin developer, when figuring out how to define a term (`do_definition` or `declare_definition`), I could not determine what all of the arguments were for, and so copied the code from an existing plugin. That plugin was incorrect as well, so I was not managing my universe constraints properly, nor was I using `Global.env ()`. This manifested with mysterious errors I could not debug until the implementors workshop.

Yves has great boilerplate code in [his tutorial](https://github.com/ybertot/plugin_tutorials/blob/master/tuto1/src/simple_declare.ml), but I don't think it's realistic to ask plugin developers to find this and rehash it always. It would be good to integrate this into the API itself. Furthermore, it's not always sufficient to use that (sometimes, for example, my plugin defines canonical structures); it would also be good to better document what all of the arguments do so that it is easier to interact with them.

**Comment by ejgallego** [comment]
cc: #7155

**Comment by SkySkimmer** [comment]
I am slowly considering the idea of having some higher level datatype which would be like the `_entry` stuff but using econstr, containing an evar map and other data like the universe declaration etc.
Then the code path for defining something would be 
~~~
(now)
interp terms -> mess with universes -> send to declareDef

(then)
interp terms -> send to declareDef (messes with universes for you)
~~~
cc https://github.com/coq/coq/issues/7669 https://github.com/coq/coq/pull/7530

**Comment by ejgallego** [comment]
IMHO this is much improved by recent work, to the point we could consider closing it.

**Comment by ejgallego** [comment]
Indeed I think this is much improved, please open API-specific issues to improve more.
