### ISSUE TITLE
Cannot build Coq when coqtop is running

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#7666]
#### Version

Coq master ac0bb15616550d00f5e6e7d6239e3b7ff2632975

#### Operating system

Linux

#### Description of the problem

If I build coq while `coqtop` is running, I get:

```
cp bin/coqtop.opt bin/coqtop
cp: cannot create regular file 'bin/coqtop': Text file busy
```

I believe this is a regression. Previously we used `ocamlopt` directly and it could write `coqtop` in such a scenario.

**Comment by SkySkimmer** [comment]
If cp --remove-destination exists on mac it should fix the issue.

Gaëtan Gilbert

**Comment by ejgallego** [comment]
Another fix is to abandon the new, more regular naming scheme.

**Comment by ejgallego** [comment]
Thinking about it we should indeed remove `coqtop` from local builds at all, and only create it on install.

Local scritps should use `COQTOPBEST`.

**Comment by ejgallego** [comment]
I guess that Gaëtan suggestion is the way to go, at least in the short term. We could also do `rm -f && cp`

**Comment by ejgallego** [comment]
I think the right thing to do is to imitate `ocamlopt` indeed, just add `rm -f` before the copy.
