### ISSUE TITLE
Instances from functor arguments

### ISSUE THREAD

**Issue by vbgl** [coq/coq#7667]
I observe a regression between 8.7 and 8.8. Here is an example code:

```
Class Class (T: Type) := w : T.

Lemma m {T} {c: Class T} : w = w.
Proof. reflexivity. Qed.

Module Type T.
  Parameter t : Type.
  Parameter c : Class t.
End T.

Module F(M: T).
  Check w.
  Lemma bug : w = w.
  Proof. exact m. Qed.
End F.
```

With 8.6 or 8.7, `Check` shows:
```
w
     : M.t
```

With 8.8 and master, it shows:
```
w
     : ?T
where
?T : [ |- Type]
?Class : [ |- Class ?T]
```

and then checking the lemma statement fails with the following message:
```
File "./a.v", line 13, characters 2-20:
Error:
Unable to satisfy the following constraints:

?Class : "Class ?A"

?A : "Type"

?Class0 : "Class ?A"
```

Note that adding `Import M.` or `Include M.` within the module `F` does not seem to change anything.

**Comment by ppedrot** [comment]
This is just a side-effect of 0ad26633a4589d77de1f864733d1d953dab9ea91, which deactivates the implicit instance declaration of axioms, and thus also of functor arguments. I don't know whether this is intended or not in this case (although I'd tend to believe it was), so better summoning @SkySkimmer.

**Comment by Zimmi48** [comment]
It is intended, well documented in CHANGES (I believe) but it has confused lots of people.

**Comment by mattam82** [comment]
Ah right. The proper fix is to Declare Instance in the module type right?
— Matthieu
Le ven. 1 juin 2018 à 14:15, Théo Zimmermann <notifications@github.com> a
écrit :

**Comment by SkySkimmer** [comment]
yes

Gaëtan Gilbert
