### ISSUE TITLE
Installation with ocaml 4.05.0

### ISSUE THREAD

**Issue by Gbury** [coq/coq#7678]
#### Version

8.8.0

#### Operating system

Linux

#### Description of the problem

Installation using opam seems broken under ocaml 4.05.0 because of num:

```
#=== ERROR while compiling coq.8.8.0 ==========================================#
# context      2.0.0~beta4 | linux/x86_64 | ocaml-base-compiler.4.05.0 | https://opam.ocaml.org/2.0#b51ed1f5
# path         ~/.opam/default/.opam-switch/build/coq.8.8.0
# command      make -j7
# exit-code    2
# env-file     ~/.opam/log/coq-17498-e7966f.env
# output-file  ~/.opam/log/coq-17498-e7966f.out
### output ###
# [...]
# OCAMLC    kernel/byterun/coq_fix_code.c
# OCAMLC    kernel/byterun/coq_memory.c
# OCAMLC    kernel/byterun/coq_values.c
# OCAMLC    kernel/byterun/coq_interp.c
# OCAMLC    plugins/ltac/tauto.mli
# OCAMLC    plugins/fourier/fourier.ml
# OCAMLC    plugins/micromega/sos_types.mli
# ocamlfind: Package `num' not found
# make[1]: *** [Makefile.build:603: plugins/micromega/sos_types.cmi] Error 2
# make[1]: *** Waiting for unfinished jobs....
# make[1]: Leaving directory '/home/guigui/.opam/default/.opam-switch/build/coq.8.8.0'
# make: *** [Makefile:190: submake] Error 2
```

For reference the `num` compatibility opam package is installed (version 0, since `Num` is still part of the distribution in 4.05.0 if I'm not mistaken).

**Comment by ejgallego** [comment]
Which distribution are you using? What does `ocamlfind list | grep num` return ?

**Comment by Gbury** [comment]
I'm on archlinux, but use exclusively opam to handle ocaml packages.
I don't have any `num` ocamlfind package (in 4.05.0, `Num` is still shipped with the compiler and thus needs no external package in order to be called), not even a dummy one, which explains why it isn't found. Could it be a problem with the `num` opam package ?

**Comment by ejgallego** [comment]
If you are using opam you need to install the dummy `num` package indeed.

**Comment by Gbury** [comment]
Sorry if I wasn't clear:
- the `num` opam package **is** installed
- it doesn't seem to have installed any ocamlfind package though

**Comment by ejgallego** [comment]
What does `ocamlfind list | grep num` say?

**Comment by ejgallego** [comment]
and what does `opam show num` say? Hard to debug without actual command output.

**Comment by Gbury** [comment]
Sorry for the delay:

```
$ opam info num
=-=- num: information on all versions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
name                   num
all-installed-versions 0 [default 4.05.0+spacetime]
all-versions           0  1.0  1.1

=-=- Version-specific details -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
version      0
repository   default
homepage:    https://github.com/ocaml/ocaml
bug-reports: http://caml.inria.fr/mantis/
dev-repo:    git+https://github.com/ocaml/ocaml.git
authors:     "Valérie Ménissier-Morain" "Pierre Weis" "Xavier Leroy"
license:     LGPL-2 with OCaml linking exception
depends:     "ocaml" {< "4.06.0"} "base-num"
synopsis     The Num library for arbitrary-precision integer and rational arithmetic
```

```
$ ocamlfind list | grep num
ppx_deriving.enum   (version: 4.2.1)
```

**Comment by Gbury** [comment]
More likely, it seems that the `num` **opam** package is indeed required by Coq in its opam description. However, it seems that the version of `num` installed (version 0) does not create a `num` **ocamlfind** package (not even a dummy one that does not actually link anything), which is required by the build system of Coq, and thus ocamlbuild rightly complain that it can't find the `num` **ocamlfind** package.

It seems there are other versions of the `num` package available on opam (i.e versions 1.0 and 1.1 according to the `opam info num` output line 4), maybe one of them actually installs a dummy `num` package on ocaml versions < 4.06 (at least that's my understanding of how compatibility packages should work for features that are separated from the compiler distribution).

In any case, the install through `opam` currently seems broken in this specific case, so it should probably warrant some added version constraint somewhere (probably `num >= 1.0` if I'm right) to fix it.

**Comment by Zimmi48** [comment]
> More likely, it seems that the num opam package is indeed required by Coq in its opam description. 

This seems OK. But I'm wondering whether this:

> a num ocamlfind package (not even a dummy one that does not actually link anything) is required by the build system of Coq

was wise from us. If we want compatibility with OCaml < 4.06, we should not need the num package in this case...

**Comment by ejgallego** [comment]
> If we want compatibility with OCaml < 4.06, we should not need the num package in this case...

I dunno what's up with the OP system, but `num` is a valid package in all ocaml versions >= 4.02.3 [I think, for sure in 4.05.0]. The fact that is distributed with the compiler means little, so are `unix`, `str` and quite a few others ocamlfind packages.

It seems `ocamlfind` installation is botched or the OP has some install problems.

**Comment by Zimmi48** [comment]
Oh indeed, so it's the num part of the standard library which is improperly registered. Guillaume, how did you install OCaml? With Opam or is it a system install?

**Comment by Gbury** [comment]
Ocaml was installed with opam (though a beta version of opam2).

**Comment by ejgallego** [comment]
It seems your Ocaml install install is broken so you should indeed open a bug to the OPAM 2 OCaml package.

**Comment by Zimmi48** [comment]
Maybe you should start by trying again from a fresh root though.

**Comment by Gbury** [comment]
Okay, so indeed reinstalling the switch fixed it, sorry for all the noise.
