### ISSUE TITLE
configure warning message on wrong version of lablgtk is misformatted

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7685]
#### Version

master

#### Operating system

Linus

#### Description of the problem
The `2.16.0` should not be at the end.
```
Warning: Your installed lablgtk reports as .
It is possible that the installed version is actually more recent
but reports an incorrect version. If the installed version is
actually more recent than 2.18.3, that's fine; if it is not,

CoqIDE will compile but may be very unstable.2.16.0
```
See https://launchpadlibrarian.net/372764910/buildlog_ubuntu-artful-amd64.coq_8.master~git~201806011556+19159-0~daily309~ubuntu17.10.1_BUILDING.txt.gz

**Comment by herbelin** [comment]
A subtle bug apparently due to c4bc671db43. An interesting puzzle in how to add arguments to an `printf`-like function of unknown arity. Don't know how to solve it though (expect than by giving `warn0`, `warn1`, `warn2` functions).
