### ISSUE TITLE
@mattam82 is overloaded

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7694]
It is very important to have good reactivity from all the component maintainers.

@mattam82 has:
- [13 opened authored PRs](https://github.com/coq/coq/pulls/mattam82). At least 12 of them are waiting from an action from him.
- [14 assigned PRs](https://github.com/coq/coq/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+assignee%3Amattam82+-author%3Amattam82+). Only 2 of them are waiting from an action from the author.
- [49 PRs awaiting a review from him](https://github.com/coq/coq/pulls/review-requested/mattam82). More than half of them are without assignee which could indicate that he's the natural assignee for them. Only 5 of them are already assigned to him so already counted in the previous list.
- [160 assigned issues](https://github.com/coq/coq/issues/assigned/mattam82). [31 of them](https://github.com/coq/coq/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+assignee%3Amattam82+-author%3Acoqbot+) were opened after the GitHub migration (and so the assignment was not automatic).

The CODEOWNER file puts @mattam82 in charge of `pretyping/`, `vernac/`, the typeclass system and the classes, program, relations and setoids theory files.
He's also a secondary maintainer for the universes, `parsing/`, `printing/`, `tactics/`, the `Wellfounded/` theory files and the coqdoc tool.

Obviously this is more than he's able to cope with so we should relieve him of some tasks to help him be more reactive on the remaining ones.

@mattam82 What would you want to keep the responsibility for and what would you like to delegate to someone else?

----

For comparison, Hugo has 39 opened PRs, 3 PRs assigned to him, 4 PRs waiting for a review from him, 16 issues assigned to him (and still open) since the GitHub migration (and 48 still open from before the migration). Maxime has 20 opened PRs, 26 assigned PRs, 26 PRs waiting for a review from him (only 3 of them being without an assignee, and 19 of them being assigned to him, so in the previous list), 22 issues assigned to him (and still open) since the GitHub migration (and 26 from before the migration). Pierre-Marie has 12 PRs opened (most of them waiting from an action from Matthieu or Maxime), 14 assigned PRs (most of them waiting from an action from the author), 9 PRs with a request for review (most of them not being ready), 19 issues assigned from after the migration and 44 from before.

**Comment by ppedrot** [comment]
This might be temporary though, last time I heard about that his laptop screen was broken. Not sure whether it has been fixed in the meantime.

**Comment by Zimmi48** [comment]
He couldn't merge any PR during the CIW because he used his older laptop but it was more than just this 😉

**Comment by Zimmi48** [comment]
Not long after this issue was posted there was a big peak of activity and @mattam82 merged 12 PRs. Nonetheless, there are still 44 PRs where his review was requested, including 25 without an assignee.

@mattam82 Do you think you are going to work you way through the backlog or would you rather have some of the burden be taken away from you?

**Comment by Zimmi48** [comment]
Closing for lack of response.
