### ISSUE TITLE
Proof of False through modules and algebraic universes

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7695]
```coq
Require Import Hurkens.

Universes i j k.
Module Type T.
  Parameter T1 : Type@{i+1}.
  Parameter e : Type@{j} = T1 : Type@{k}.
End T.

Module M.
  Definition T1 := Type@{j}.
  Definition e : Type@{j} = T1 : Type@{k} := eq_refl.
End M.

Module F (A:T).
  Definition bad := TypeNeqSmallType.paradox _ A.e.
End F.

Module X := F M.
Check X.bad.
(* X.bad
     : False
*)
Print Assumptions X.bad.
(* Closed under the global context *)
```
The checker does catch this one (ill-typed term: CantApplyBadType).

#7490 blocks it for coqtop.

**Comment by mattam82** [comment]
Scary, can you explain the bug a bit more. Is it due to allowing algebraics in T1's declaration only?

**Comment by SkySkimmer** [comment]
There's a hack around https://github.com/coq/coq/blob/0a829c6ac232b0ea786716709b0d01c707548089/kernel/subtyping.ml#L285-L287 where we assume that algebraic universes are from inference and so skip checking that they're in a cumulativity relation.
#7490 is more a workaround than a fix.

**Comment by mattam82** [comment]
I see. That part is still here and probably broken.

**Comment by ppedrot** [comment]
Nice one.

**Comment by Zimmi48** [comment]
Is there anyone working on fixing this?

**Comment by Zimmi48** [comment]
@SkySkimmer @mattam82 @ppedrot What should we do about this?

**Comment by SkySkimmer** [comment]
In fact the same hack for inductives has a comment https://github.com/coq/coq/blob/0a829c6ac232b0ea786716709b0d01c707548089/kernel/subtyping.ml#L152-L157
>in short, we would need the actual graph of 
        constraints as input while type checking is currently designed 
       to output a set of constraints instead

I guess in the old days conversion didn't look at the ugraph.
So it shouldn't be necessary and I'll try removing it. It will fail with "unable to handle arbitrary constraint" or some such if you try to use subtyping with wrongly annotated definitions but that's better than an unsound hack.
