### ISSUE TITLE
Improve plugin loader as to allow plugins that link to external dependencies.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7698]
As we have discussed some other time (see #683), the current situation of linking libraries to plugins seems to be a bit dangerous. In particular, the problematic scenario is:

- plugins `A`, `B`, both depend on library `foo`, however `foo` is not linked into `coqtop`.

The correct behavior here is that Coq should indeed load `foo` before loading `A`, thus `B` can reuse this copy of `B`. Linking `foo` into `A` and `B`, which was the approach advocated until now will create problems and stop working in future OCaml versions starting with 4.08.

Implementing a plugin loader in Coq is not trivial, however thanks to work done in `findlib`, `Dune`, and `Frama-C`, we can use the `Findlib_dynload` API to achieve this without too much effort.

See the following links for more context:
- https://discuss.ocaml.org/t/dune-problems-using-dynlink-plugins/2874
- https://github.com/ocaml/dune/issues/1544
- http://projects.camlcity.org/projects/dl/findlib-1.8.0/doc/ref-html/lib/Fl_dynload.html
- https://dune.readthedocs.io/en/latest/advanced-topics.html?highlight=dynlink#dynamic-loading-of-packages

**Comment by ejgallego** [comment]
@gares wrote in #8667 :

> My position is that it is OCaml that should implement dynamic linking properly. What it currently does is "delayed static linking" that is not at all the same thing. I'm against writing a loader inside coqtop (assuming it is possible). Given that, as of today, the scenario described in #7698 is not real, but just hypothetic, I would ignore the issue.

I'd like to add that this issue is not hypothetical even in today Coq's. In fact, the `micromega` plugin depends on `num`, and due to Coq not having its own loader we have to statically link `num` to the coqtop binary as to avoid the problem mentioned above.

So indeed that's a serious issue IMHO.

**Comment by gares** [comment]
You could also make a num_plugin.cmxs out of num.cmxa, have a num.v Declare ML Module "num_plugin" and have extraction.v / nsatz.v Require num.
In this way the chain of dependencies is going to load things once and in the correct order.

What I'm against is to write code in coqtop that guesses that exaction_plugins.cmxs needs the Num module and that loads some num.cmxs on the fly (that would be a loader).

Having the dependency chain of cmxs re-use the one of .vo is boring, but way simpler. I can't tell if it is a complete solution or not.

**Comment by ejgallego** [comment]
> You could also make a num_plugin.cmxs out of num.cmxa, have a num.v Declare ML Module "num_plugin" and have extraction.v / nsatz.v Require num.

That's another choice, however it gets cumbersome when you have `lwt`, `sexplib`, `yojson` etc... in scope. And you also have the critical problem that plugins using the OCaml libraries have to share the same "base" plugins.

So I cannot say I am a fan of this hack.

> In this way the chain of dependencies is going to load things once and in the correct order.

Only if the programmer doesn't do a mistake with the linking order. This is not easy in complex plugins.

> What I'm against is to write code in coqtop that guesses that exaction_plugins.cmxs needs the Num module and that loads some num.cmxs on the fly (that would be a loader).

It is not clear to me why? I am not a fan either but it seems to me that it is the lesser of the following evils:
- the fake plugin hack,
- having plugins working by luck like as today,
- hoping support from OCaml upstream.

Such loader would only need to do `List.iter load_ml_lib plugins.deps` and that's it.

**Comment by ejgallego** [comment]
Anyways, I don't have a good solution to this problem yet, but my point wrt issue was to state that we have a _real_ problem, and IMHO, a serious one.

**Comment by ejgallego** [comment]
> Where do you get `plugins.deps` and how do you check a module is not loaded twice?

We'd have to maintain a list of course, but this is already done now. But indeed I do agree that this has to be done with coordination from OCaml upstream. This issue just documents the issue for now, to me the solution is not clear. Obviously if upstream would solve that for us then great.

**Comment by Zimmi48** [comment]
Would `plugins.deps` be part of your upcoming package format? Since you were talking about basing this on Dune files, can we just use the dependency list in there?

**Comment by ejgallego** [comment]
> Would `plugins.deps` be part of your upcoming package format? Since you were talking about basing this on Dune files, can we just use the dependency list in there?

Indeed that would a way to do it, but likely may need lower-level support from the linker; I'll ask the OCaml folks.

I don't think this issue, even if serious, is urgent tho. We can live for a while with the current situation, but indeed, we should support rich linking of plugins in the medium-term IMO.

**Comment by ejgallego** [comment]
It turns out that the recommended, and IMHO correct, solution here is indeed to implement a proper plugin loader; fortunately `findlib` has the right setup and Dune supports it out-of-the-box; see updated main issue message.

**Comment by lthms** [comment]
Hi. I was wondering what is the status of this issue. We have encountered this issue in our own development, and the solution proposed in the “Writing Coq plugins with dune” tutorial can be quite trick to implement in practices (e.g., to deal with long transitive dependencies chain).

**Comment by ejgallego** [comment]
@lthms as of today indeed you need to use some form of `-linkall` which is hacky, and breaks with OCaml 4.08 . Fortunately the status of this feature is quite advanced, I already have a prototype and once we move the core build to Dune it will just work. [For example SerAPI does already uses Fl_dynload to manage plugin deps chains and it works fine]

**Comment by lthms** [comment]
We are looking forward to see the “It Just Works”™ solution. :) If you need any help, eg. to test the proposed solution, feel free to say so. No promises, but I would I least try!

**Comment by Alizter** [comment]
@lthms FYI #15220 has been merged closing this issue.
