### ISSUE TITLE
Notation aliases for Lets are broken

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7700]
#### Version

8.8.0

#### Description of the problem

This should work
```coq
Section foo.
  Let x := Set.
  Notation y := x.
  Check y. (* Error: The reference y was not found in the current environment. *)
```

**Comment by herbelin** [comment]
This is actually not only `Let` but `Variable` also. Surprisingly enough this is a serious missing case of the algorithm for globalization of variables which has remained non reported for more than a decade. Fixed by #7761.
