### ISSUE TITLE
Launching `coqide` through `PATH` fails.

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#7704]
#### Version

Coq master 1136dde7b523047e6091d6e6decb45183e42fc21

#### Operating system

Linux

#### Description of the problem

When launching CoqIDE using a path that is not relative to the current directory nor absolute, the worker fails to connect back in 10s, and I get an error message saying Coq is dead.

Example:

```
/absolute/path/to/coqide
```

works

```
bin/coqide
```

when current directory is the Coq root, also works, but:

```
coqide
```

when `coqide` is in `PATH` typically fails.

I guess some wrong assumptions were done in some path handling code. This behavior seems like a regression, I'm pretty sure it used to work.

**Comment by SkySkimmer** [comment]
I mentioned this in #7520 maybe we should pull out the one line fix.

**Comment by gares** [comment]
This works (in 8.8):
```
gares@gargamel:~/COQ/wt/v8.8$ PATH=$PWD/bin:$PATH coqide
```

I guess it is #6859 but I did not bisect

**Comment by gares** [comment]
The current code does not seem to fully resolve the name of the executable `coqide` before replacing it with `coqidetop`

**Comment by gares** [comment]
Nor it searches it in the `PATH` AFAICT

**Comment by ejgallego** [comment]
Yeah for sure the current code needs am improvement, I will try to list all the cases as there are many to see if a second try gets it right

**Comment by maximedenes** [comment]
> Yeah for sure the current code needs am improvement, I will try to list all the cases as there are many to see if a second try gets it right

You should at least get it right with 1- an absolute path 2- a path relative to pwd 3- a path resolved using `PATH`.

And it should work under Windows (no assumptions on the extension).

**Comment by ejgallego** [comment]
The tricky part is to prevent a build that is still not finished to pick the wrong idetop if some other is in the path.
