### ISSUE TITLE
Include Ltac2 and Equations in the Windows package

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7707]
I think it would be good to encourage our users to start testing what we see as a future replacement of things like Ltac, Funind, Program... So I suggest we distribute Ltac2 0.1 and Equations 1.0 in the Windows packages for 8.8.1 like we did with Bigumns in 8.7.2.

cc @gares @MSoegtropIMC @ppedrot @mattam82 @cmangin

**Comment by MSoegtropIMC** [comment]
When is the deadline for 8.8.1? I am way busy this week, but end of next week I have some time (and also wanted to work on some of my other issues).

**Comment by andres-erbsen** [comment]
I would love to start using Ltac2 (and perhaps Equations, though I have not experience what it does). Is there a recommended way of doing this on Linux -- i.e., I would be looking to write a package file in the style of https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/coq?

**Comment by ppedrot** [comment]
@andres-erbsen There is already an opam file in Ltac2, so that you can simply `opam add pin` the git repository.

**Comment by andres-erbsen** [comment]
opam is not an option

**Comment by maximedenes** [comment]
I can make a Nix package if you like.

**Comment by andres-erbsen** [comment]
thanks @maximedenes, that would do the trick. I am just looking for something to scavange for simple install instructions

**Comment by JasonGross** [comment]
If you don't have opam and build Coq yourself (or have access to the ocaml that built Coq), you can clone the git repo and run `make && make install`.  I generally look to Coq's ci or the opam config for build instructions (e.g., opam-coq-archive or the opam file should describe which branch/tag to use for the relevant version of Coq). The Coq-makefile-generated Makefile has install and remove targets for the user-contrib folder of the Coq install, which is where these things get placed.  Is that enough information to write your package file or install manually?

**Comment by gares** [comment]
> So I suggest we distribute

I've nothing against

> I think I am mostly looked for "supported" installation instructions with configurable destination directories and dependency locations, where "supported" means that somebody else is testing the same installation procedure both on its own and as a dependency of some other plugin

I'm not a big fan of OPAM per se, but it does exactly what you say. If the author of Ltac2 says run `opam pin...` then I guess it works and install things where appropriate (the OPAM root you are using) and I guess it counts a "supported installation procedure"

Can you explain why OPAM is not an option and why nix is, for example?

**Comment by andres-erbsen** [comment]
My apologies for making difficult requests without explanation. The requirement that is making me avoid opam is to build binary packages separately on different hosts and then almost-instantly install them on a development or CI system and have them work together. So in theory I could try making one "package" for everything from opam, and I would be willing to try that if so recommended here. Currently Coq and Ltac1 are considered the same package and this works fine.

**Comment by JasonGross** [comment]
To answer the concrete question, Ltac2 (as other `coq_makefile`-based projects) finds the location of `coqc` via the `COQBIN` environment variable; I believe the `coq_makefile` binary remembers the paths that it was configured with and dumps them in a `.conf` file when executed; and the install directory can be changed at install time with the `DESTDIR` environment variable (which defaults to something like `$PREFIX/lib/coq`).

**Comment by gares** [comment]
If we are talking about coq packages, then they install all their stuff in `...lib/coq/user-contribs/$PKG`.
Superposing 2 $PKG on a single host does not seem harder than doing a `scp -r`.

Sure, a package manager that knows about binary packages would be better...

**Comment by Zimmi48** [comment]
> When is the deadline for 8.8.1?

There are a few critical bugs to fix but as soon as they are fixed (and I hope it won't take long). I'd like to do the release.

**Comment by Zimmi48** [comment]
Now that all critical bugs have been fixed (at least in PRs), the 8.8.1 release is only days away. So if we want to have this ready in time, it should be addressed quite soon. @MSoegtropIMC you self-assigned this: do you want to take care of this or would you rather have someone else do it?

**Comment by MSoegtropIMC** [comment]
My plan is to give it a try on Thu/Fri. I can't promise I can finish it until end of this week.
I didn't start on it as yet and don't mind if someone else is doing this, but I am also happy to do it myself.

**Comment by mattam82** [comment]
I guess it would make sense to have a bugfix release of Equations as well,
since a lot was fixed since v1.0. I'll get to it.

**Comment by MSoegtropIMC** [comment]
@ppedrot : one question: how should I map Coq versions to Ltac-2 versions? The options I see are:

1.) give the version of Ltac-2 on the command line when building (e.g. -addon=ltac2-8.8)
2.) always use master for Ltac-2
3.) use sed to convert Coq version numbers to Ltac-2 version numbers
4.) use a version mapping table (which would then have to be extended for each new coq version)
5.) use an extra file (say ltac2-version.txt) which just gives the matching version of Ltac-2 (which would have to be updated when a new version of Ltac-2 is made). This file could also contain the complete source URL
6.) use some already existing mechanism for such problems I don't know of

Ideas welcome!

**Comment by Zimmi48** [comment]
Always use master when building Ltac2 on master, but this needs to be configurable and in `v8.8` we'll use the 0.1 tag that @ppedrot has recently produced. So solution 5, with the complete source URL sounds good.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : ok. I think it would be best to create folder "plugin_version" for such files. As an extension of option 5 I would suggest to have scripts in there which get the Coq version as argument and produce the URL to stdout. One can then have a simple echo in there or something more advanced (like checking if Coq is master or something else).

Should I create the plugin version folder under /dev/build (rather than /dev/build/windows) ? Or is there a better place?

**Comment by Zimmi48** [comment]
This sounds right.

**Comment by MSoegtropIMC** [comment]
I got ltac2 and equations compiled and tested (in CoqIDE) - it works fine.

Just one remaining question: should the plugins and addons (like bignum) be separately selectable items in the installer, or just one for plugins and one for addons?

**Comment by Zimmi48** [comment]
What is your definition of an addon? To me bignum is a plugin. Ideally yes, the installer would list the various optional plugins and the user could pick the exact set they want, but I don't think it's such a big deal if this fine-grained selection is not available (at least for now, given how small these plugins are).

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : Sorry, my use of the word addon was bad. I meant plugin vs. library. Probably both together are addons. I didn't look into bignums, I was assuming it is just a Coq library (no OCaml parts).

**Comment by MSoegtropIMC** [comment]
@ppedrot : Just a note: Ltac-2 master/HEAD doesn't compile with coq master/HEAD. Ltac-2 8.8 with Coq 8.8.0 works fine.

@mattam82 : Equations master/HEAD doesn't compile with coq master/HEAD. Equations 8.8 with Coq 8.8.0 works fine.

Since neither is built in CI, the machinery can still be integrated, but it would be nicer to fix this.

I am not sure if this should be enabled in CI as soon as it does build with master.

**Comment by Zimmi48** [comment]
Both are supposed to build with master: https://gitlab.com/coq/coq/pipelines/23930966
Are you sure that you have the latest version of Coq master?

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I did a pull around noon, but I will try again ...

**Comment by mattam82** [comment]
Are you using the github source for Equations or the 1.0 package?

**Comment by MSoegtropIMC** [comment]
@mattam82 : I tried https://github.com/mattam82/Coq-Equations/archive/master.zip.
My Coq version is from yesterday evening:

commit 31e13998542941040343cb81787a1d7c865d5b65 (upstream/master, origin/master, origin/HEAD, master)
Merge: 1098604f5 7ae07d738
Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
Date:   Thu Jun 14 15:21:19 2018 +0200

**Comment by mattam82** [comment]
I don't know about master, but here's a link to a v1.1 version for 8.8: https://github.com/mattam82/Coq-Equations/archive/v1.1-8.8.tar.gz

**Comment by Zimmi48** [comment]
No, the same method should work for equations as well.

**Comment by mattam82** [comment]
That’s fine today indeed.
Le ven. 15 juin 2018 à 20:56, Théo Zimmermann <notifications@github.com> a
écrit :
