### ISSUE TITLE
The stdlib HTML documentation is ugly when not on Coq's website

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7720]
#### Version

8.8 / 8.9

#### Description of the problem

Here is a link to the latest build of the Stdlib HTML documentation:
https://gitlab.com/coq/coq/-/jobs/artifacts/master/file/_install_ci/share/doc/coq/html/stdlib/index.html?job=build:base

As you can see, no CSS is shipped with it, and this makes the whole thing really ugly. Furthermore, the links at the top of the index page are relative and only make sense when this page is shipped as part of the Coq website.

Until this is fixed, I don't see much point in having the default `install-doc` target install this HTML doc.

**Comment by ejgallego** [comment]
> Until this is fixed, I don't see much point in having the default install-doc target install this HTML doc.

I agree with the problem, however I suggest we keep the install in the CI so we can test it actually doesn't regress more.

Also, hiding the problem may not be a good strategy to have it fixed.

**Comment by Zimmi48** [comment]
Actually a duplicate of #5268.
