### ISSUE TITLE
vm_compute segfaults with universe polymorphism

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7723]
#### Version

8.8.0

#### Description of the problem

```coq
Set Universe Polymorphism.

Inductive decision_tree : Type := .

Fixpoint first_satisfying_helper {A B} (f : A -> option B) (ls : list A) : option B
  := match ls with
     | nil => None
     | cons x xs
       => match f x with
          | Some v => Some v
          | None => first_satisfying_helper f xs
          end
     end.

Axiom admit : forall {T}, T.
Definition dtree4 : option decision_tree :=
  match first_satisfying_helper (fun pat : nat => Some pat) (cons 0 nil)
  with
  | Some _ => admit
  | None => admit
  end
.
Definition dtree'' := Eval vm_compute in dtree4. (* segfault *)
```

More involved example, with other relevant error messages, coming up soon.

cc @maximedenes @SkySkimmer @mattam82

**Comment by SkySkimmer** [comment]
Further reduced 
```coq
Set Universe Polymorphism.

Definition dtree4  :=
  match Some 0
  with
  | Some _ => Type
  | None => Set
  end
.

Definition dtree'' := Eval vm_compute in dtree4. (* segfault *)
```
With byte compiled Coq it says "Anomaly "Parsing virtual machine value expected universe level, got Vprod."

**Comment by JasonGross** [comment]
Here's the extended test case that originally triggered this, and gives the anomaly even with the opt-compiled version:
[bug_vm_segfault_07.v.txt](https://github.com/coq/coq/files/2078021/bug_vm_segfault_07.v.txt)

**Comment by maximedenes** [comment]
Indeed, something seriously wrong is going on in the universe handling code introduced in 8.5. Here's a proof of `False`:

```coq
Require Import Hurkens.
Polymorphic Inductive unit := tt.

Polymorphic Definition foo :=
  let x := id tt in (x, x, Type).

Lemma bad : False.
  refine (TypeNeqSmallType.paradox (snd foo) _).
  vm_compute.
  reflexivity.
Qed.

Print Assumptions bad.
```

**Comment by maximedenes** [comment]
`native_compute` is not impacted, it uses a less optimized but safer approach for binding local universes.
