### ISSUE TITLE
There should be `Set Intuition Solver` like `Set Firstorder Solver`

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7725]
#### Version

8.8.0

#### Description of the problem

It is very unfortunate that `intuition` means `intuition auto with *`.  It seems like adding this option would be a step towards making the default behavior here easier to change, as I suggest in #7724.

**Comment by JasonGross** [comment]
See also #4949, #8175

**Comment by SkySkimmer** [comment]
This can probably be done fairly easily by changing https://github.com/coq/coq/blob/d47ba657bb4ec33f44402142161610955194ae61/theories/Init/Tauto.v#L104
to 
~~~coq
Ltac intuition_solver := auto with *.
Ltac intuition := with_uniform_flags ltac:(fun flags => intuition_gen flags ltac:(intuition_solver)).
~~~
then the Set is `Ltac intuition_solver ::= other tactic.`

**Comment by JasonGross** [comment]
Oh, neat!  Yes, we should do this.  Probably we want `ltac:(idtac; intuition_solver)`, though, so if someone starts the solver with a `match` things don't go awry
