### ISSUE TITLE
Interrupting printing completely borks coqtop

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7729]
#### Version

8.8.0

#### Operating system

Linux

#### Description of the problem

Consider the code
```coq
Require Import Coq.ZArith.ZArith.

Definition foo := Eval vm_compute in List.repeat Z.div_eucl 20.
Set Printing Depth 1000000.
Set Printing All.
Print foo.
```
In ProofGeneral: Execute up to the `Set Printing All.`  Then execute the `Print foo.`, wait a second or two or three (until the `*coq*` buffer starts showing output).  Then spam `C-c` to send `SIGINT` to Coq.  Then execute any command, such as `Check 1.` or `Reset Initial.` or even just something silly like `R.`.  I get
```coq
Error:
Currently, the parsing api only supports parsing at the tip of the document.
You wanted to parse at: 1 but the current tip is: 63
```

cc @ejgallego @gares 

See Also: #5120

**Comment by SkySkimmer** [comment]
Seems fixed
