### ISSUE TITLE
`make clean` doesn't clean enough

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7732]
#### Version

master

#### Operating system

Linux

#### Description of the problem

I just had a build failure in Coq after doing `git pull`: Running `./configure -local && make clean && nmk` would give
```
File "_none_", line 1:
Error: Unbound module Pcoq.Vernac_
Makefile.build:689: recipe for target 'parsing/g_proofs.cmo' failed
```
To fix this, I had to run `rm parsing/g_proofs.ml parsing/g_vernac.ml`. If these are generated files (which it seems they are), `make clean` should have removed them.

**Comment by herbelin** [comment]
I'm unsure `make clean` is intended to track files which changed from a git revision of the archive to another.

**Comment by RalfJung** [comment]
Well, the usual expectation for build systems is that I can always do `git pull && make` and that will work. I consider any build system where that is not the case broken. In fact, for the purposes of a `git bisect`, this should usually even work when going *back* in history -- and it does for most, if not all, projects I have been working with so far.

Coq already has me do `git pull && make clean && make` in many cases, and before I knew about this quirk of Coq's build system, I wasted some time on figuring out why the build was broken. But that one should certainly work, I would argue very strongly.

**Comment by Zimmi48** [comment]
As discussed on Gitter, this is a problem that will be fixed when doing hygienic builds using Dune (see #6857).
@ejgallego is planning to get this PR finished and merged around the middle of next week.

**Comment by ejgallego** [comment]
Will likely delay a bit due to travel but indeed, I decided to use a tool that doesn't have this problem and can understand dependency tracking better that we do now so these problems should happen; of course tweaking our makefiles so we improve this would be also super, but I lack the required skills to do so.

**Comment by ejgallego** [comment]
Also fixed by using Dune.
