### ISSUE TITLE
Cross-Crypto consistently fails in Travis

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7734]
Cross-Crypto consistently fails in Travis with the following error:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
Cf.
- https://travis-ci.org/coq/coq/jobs/388297264
- https://travis-ci.org/coq/coq/jobs/388451339
- https://travis-ci.org/coq/coq/jobs/388455810
- https://travis-ci.org/coq/coq/jobs/388487999
- https://travis-ci.org/coq/coq/jobs/388726072

it doesn't appear to be an issue in GitLab CI.
We should either fix this by adding `travis_wait` to the configuration, or by removing Cross-Crypto from Travis.

**Comment by ejgallego** [comment]
Yeah any of the choices would work.
