### ISSUE TITLE
How to ensure that the Coq snippets in the manual are not broken?

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7755]
It has been a long standing problem that the Coq examples in the manual can sometimes become outdated without us noticing; they can even start failing suddenly. The problem was there with coq-tex and still exists in the Sphinx based manual.

A solution that has been proposed and never implemented is to forbid failures (cc @silene @maximedenes). There are a few places where we want to show Coq failing, but it could still be done using `Fail` (although the output with `Fail` is less advanced, in particular it doesn't show the failure location).

Yet, I fear that this mechanism would still be too simple to catch a lot of problems: when we describe the supposed output in terms more complex than "this works" or "this fails". That's why I'm currently considering that we should instead have a system that is closer to how the test-suite `output/` system works, especially after @SkySkimmer's improvement in #7663. We would store the output along side the input. We could even use the stored outputs by default instead of regenerating them (it would allow the `sphinx` target not to depend on `world`) and have a distinct target (included in `test-suite`) that would regenerate outputs and check them against what was stored (plus an additional target to "approve" new outputs after careful review, also useful when we add a new example).

**Comment by RalfJung** [comment]
Some prior work on this area:

In python, people write code in their docstrings like this:
```
    >>> [factorial(n) for n in range(6)]
    [1, 1, 2, 6, 24, 120]
    >>> [factorial(long(n)) for n in range(6)]
    [1, 1, 2, 6, 24, 120]
```
The `>>>` is recognized as being a comment to execute, the next line is the expected output. I don't know the tool that is used to actually run the tests.

In Rust, docstrings can look like this:
```
/// # Examples
///
/// ```
/// let x = factorial(6);
/// assert_eq!(x, 120);
/// ```
```
Then, `cargo test` already knows how to extract the tests from the inline docs and run them. You can add `should_panic` after the opening ```` ``` ```` to indicate that this should compile but not succeed when run, or `compile_fail` to indicate that it shouldn't even compile.

This doesn't seem very specific to inline docs, so some similar mechanism could probably also be used for Coq's refman.

**Comment by jfehrle** [comment]
A bit off topic: It would be interesting to show diffs in the examples.  I have code to generate HTML with diff tags that could be adapted for that purpose.

**Comment by Zimmi48** [comment]
Absolutely! In some selected cases, it could be very useful. We could consider adding a `diff` option to `.. coqtop::`
cc-ing @cpitclaudel (who I should have cc-ed from the beginning of this issue anyways).

**Comment by Zimmi48** [comment]
For future reference, the solution that was chosen is to fail when a command fails in a snippet, unless an option is passed. This doesn't go as far as checking that the output is unchanged, together with a good promote rule. This is left as future work for whoever wants to address it.
