### ISSUE TITLE
Make target coqbinaries only rebuilds coqtop.opt, not coqtop

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7758]
#### Version

Coq 8.9+alpha

#### Operating system

Windows and Linux

#### Description of the problem

Since #6859, running `make` will generate two identical binaries `bin/coqtop` and `bin/coqtop.opt`. However, changing something then running `make coqbinaries` will only regenerate `bin/coqtop.opt`, leaving `bin/coqtop` unchanged.

cc @ejgallego

**Comment by jfehrle** [comment]
I's like to understand the difference between coqtop and coqtop.opt.  Seems to me we should keep `coqtop` for the executable name.

**Comment by ejgallego** [comment]
`coqtop` is supposed to point out to the "best" version available. In systems with a native compiler this will be `coqtop.opt` in others `coqtop.byte`. The new naming is more uniform. A symlink poses some problems.

I dunno if we support systems without a native compiler by the way, I am not sure somebody has tested Coq in such setup in quite a long time.

**Comment by herbelin** [comment]
> I am not sure somebody has tested Coq in such setup in quite a long time.

Debian used to systematically test Coq on a variety of architectures, including some without native compilation, and for the little story, including some which revealed architecture-specific behaviors of OCaml. Don't know if they still do. (@gares do you know?)

**Comment by ejgallego** [comment]
@herbelin Debian is still at 8.6 so this is what I mean, we have been developing lots of stuff but no recent testing on some archs.

**Comment by herbelin** [comment]
Why don't Debian maintainers of Coq package the latest version?

**Comment by ejgallego** [comment]
> Why don't Debian maintainers of Coq package the latest version?

I asked this question at the CIW and it is mainly due to lack of time; some time ago I did some packages using their scripts but using a different tool that IMO should allow to push upstream versions more easily, hopefully I can push it some day.

**Comment by Zimmi48** [comment]
> Why don't Debian maintainers of Coq package the latest version?

Who are they anyways? Maintainers of package archives for other systems (ArchLinux, MacPorts, Nix) are way more reactive to newer Coq versions. I can't see why people on Debian sid can't benefit from the latest Coq version. (And why people on stable can't benefit from the latest patch-level version.)

**Comment by herbelin** [comment]
The four names listed at https://packages.debian.org/sid/coq are actually (very) close colleagues.

**Comment by jfehrle** [comment]
> However, changing something then running `make binaries` will only regenerate

Should say `make coqbinaries`, right?

**Comment by jfehrle** [comment]
Should all 4 of these binaries listed in TOPBIN be copied from `*.opt.exe` to `*.exe`?  Or just coqtop?
Seems a simple enough change--I could do it.  I'd probably rename TOPBIN to TOPBINOPT, though.

```
bin/coqtop.opt.exe
bin/coqproofworker.opt.exe
bin/coqtacticworker.opt.exe
bin/coqqueryworker.opt.exe
```

Current code below, just need to add $(COQTOPEXE) on the first line.  And add rules for the other 3 binaries if needed: 
```
coqbinaries: $(TOPBIN) $(CHICKEN) $(CSDPCERT) $(FAKEIDE)

# Special rule for coqtop
$(COQTOPEXE): $(TOPBIN:.opt=.$(BEST))
	cp $< $@
```

**Comment by Zimmi48** [comment]
No, I think it was done like this on purpose (@ejgallego?)

**Comment by ejgallego** [comment]
The other 3 binaries are internal so indeed I guess the explicit naming is preferrable.

**Comment by jfehrle** [comment]
I'll create a PR.

Another detail I'd like to clean up at the same time:  On Windows, these commands show useless cryptic messages in the build output such as `true bin/coqidetop.opt.exe`.

```
	$(STRIP) $@
	$(CODESIGN) $@
```

The following hides the messages but would need to be repeated in several places.  Is there a clean way to have the condition only in one place?

```
ifneq ($(STRIP), true)
	$(SHOW)'STRIP $@'
	$(HIDE)$(STRIP) $@
endif
ifneq ($(CODESIGN), true)
	$(SHOW)'CODESIGN $@'
	$(HIDE)$(CODESIGN) $@
endif
```

**Comment by SkySkimmer** [comment]
>The following hides the messages but would need to be repeated in several places. Is there a clean way to have the condition only in one place?

In configure.ml instead of writing `"true"` write `$(HIDE)true` (I didn't actually test).

**Comment by jfehrle** [comment]
$(HIDE)true works fine on my Windows system but blows up on the build system.  Any other ideas?

https://travis-ci.org/jfehrle/coq/jobs/398110703
```
OCAMLBEST -o bin/coqwc
/bin/sh: 1: @true: not found
make[1]: *** [bin/coq-tex] Error 127
make[1]: *** Waiting for unfinished jobs....
/bin/sh: 1: @true: not found
make[1]: *** [bin/coqwc] Error 127
make[1]: Leaving directory `/home/travis/build/jfehrle/coq'
make: *** [submake] Error 2
```

**Comment by SkySkimmer** [comment]
Because of the use in bestocaml `$(OCAMLOPT) $(MLINCLUDES) $(OPTFLAGS) $(LINKMETADATA) -o $@ -linkpkg $(1) $^ && $(STRIP) $@ && $(CODESIGN) $@` which is in the middle of the command. 

>Any other ideas?

Not right now.

**Comment by JasonGross** [comment]
You could create two variables, one to be used in sequences of commands, the other to be used at the beginning of lines, and only hide the beginning-of-line ones.
