### ISSUE TITLE
Re-defining notation should complain about changed format specifier

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7766]
#### Version

8.8.0

#### Operating system
Linux

#### Description of the problem

Consider the following code:
```
Notation "∀ x .. y , P" := (forall x, .. (forall y, P) ..)
  (at level 200, x binder, y binder, right associativity,
  format "'[  ' ∀  x  ..  y ']' ,  P") : type_scope.

Notation "∀ x .. y , P" := (forall x, .. (forall y, P) ..)
  (at level 200, x binder, y binder, right associativity,
   format "∀ x .. y , P") : type_scope.

Lemma test : forall (x : nat), x = x. Proof.
(* Prints: ∀ x : nat, x = x *)
```
Notice that the second `Notation` uses all the same levels, but a different format specifier. As the final lemma shows, that is ignored.

If the level is given in an inconsistent way, Coq shows an error. A similar error should be shown when re-defining a notation attempts to change the format specifier.

**Comment by RalfJung** [comment]
Related: https://github.com/coq/coq/issues/6082

**Comment by RalfJung** [comment]
Maybe, for the sake of making it easier to import libraries that share notation, there should be a warning but not an error when this case occurs.

**Comment by JasonGross** [comment]
I think the actual behavior should be that, if given, the new format overrides the old one, possibly with a warning similar to the notation-overridden one.

**Comment by RalfJung** [comment]
Given that import order is pretty unpredictable, I think that will make the actual format used pretty much random.

**Comment by JasonGross** [comment]
Much more important is that I want to be able to override formats interactively.  If I import a notation with a given format, I should be able to override the format in the current file.  And if I want to control import order, I can `Import` the modules that I care about one-by-one.
