### ISSUE TITLE
Missing FAQ: Reference for differences between Canonical Structures and Typeclasses

### ISSUE THREAD

**Issue by bollu** [coq/coq#7788]
I was hoping for an authoritative reference for canonical structures v/s typeclasses. Unfortunately, this does not exist as of yet in the Coq FAQ.

##### Previous discussions 
- [Mailing list thread](http://coq-club.inria.narkive.com/TBVZVe4O/typeclasses-vs-canonical-instances)
- [Software foundations discussion: Advice from Experts](https://softwarefoundations.cis.upenn.edu/draft/qc-current/Typeclasses.html)
- [Canonical structures for the working Coq user: section on related work](https://hal.inria.fr/hal-00816703v1/document)

The current status as I understand is:

- `mathcomp` uses canonical structures.
- `typeclass` mechanism uses more powerful (?) unification rules, but is also harder to control. 
- Coq typeclasses allow multiple instances, unlike Haskell typeclasses.
- Debugging typeclasses is harder due to their greater power.

**Comment by bollu** [comment]
Done, added a section to the FAQ called ["Typeclasses and Canonical Structures"](https://github.com/coq/coq/wiki/Typeclasses-and-Canonical-Structures)

**Comment by bollu** [comment]
Re-opening to ask the Typelcasses v/s Canonical Structures experts to add to the wiki page :)

Ping @CohenCyril @gares @amahboubi

**Comment by gares** [comment]
Thanks for contributing the page! I'll try to add some info, but you already list both the paper and the book @amahboubi and I wrote, so there is not much to add on my side.

I think I will try to write a short paragraph on my current "view" and research plan on the topic. I think I can present the problem and the two mechanisms in a unified way by making appeal to logic programming. It may help some readers to understand what is going on, I hope.
