### ISSUE TITLE
Anomaly Universe undefined

### ISSUE THREAD

**Issue by jad-hamza** [coq/coq#7792]
#### Version

8.8.0
coq-stdpp dev.2018-06-10.1.aa942ca8
coq-equations branch 8.8 commit 0fd38655ad6bab24e1d59552a5aea26bd23b6782

#### Operating system

Debian

#### Description of the problem

[universes.zip](https://github.com/coq/coq/files/2095301/universes.zip)

Sorry for the non-reduced example. Running `make` takes around 6 minutes 30, and the last `Qed` ends in the following error message.

```
File "./universes.v", line 377, characters 30-34:
Error: Anomaly "Universe SLC.universes.1891 undefined."
```

**Comment by mattam82** [comment]
It might be linked to a bug I found in obligations recently: https://github.com/coq/coq/pull/7775

**Comment by ppedrot** [comment]
If anything, this is an Equations bug. The reported test is not compiling on a recent Coq either. If this has not been fixed yet, report it to the Equations bug tracker with an updated test. Meanwhile I am closing it here.

**Comment by mattam82** [comment]
@SkySkimmer likely this was an obligations/equations bug. As far as I can tell this is fixed in Equations's master now (although the code changed a bit, the universe example goes through). Fine with closing.
