### ISSUE TITLE
[win] use COQINSTALLPREFIX in build scripts

### ISSUE THREAD

**Issue by gares** [coq/coq#7796]
See https://github.com/coq/coq/pull/7241#issuecomment-396855223

The relevant comment from 7241 is:

What I think is possible to do in the windows build script is to (up to minor details):
```
./configure -prefix ./
make
make install COQINSTALLPREFIX=/cygdrive/c/coq_install
```
rather than the current
```
./configure -prefix ./
make
./configure -prefix /cygdrive/c/coq_install
make install
```

**Comment by MSoegtropIMC** [comment]
This is deprecated with Coq Platform.

**Comment by MSoegtropIMC** [comment]
The PR which removed the old build scripts and switched to Coq Platform was (#13598).
