### ISSUE TITLE
autounfold's behavior depends on file names

### ISSUE THREAD

**Issue by Armael** [coq/coq#7812]
#### Version

Coq 8.8.0

#### Description of the problem

Consider the two following files (the second one depends on the first one). Checking them using proofgeneral/coqide works fine, but when using `coqc`, the last proof of the second file fails (because the autounfold does not unfold anything in that case).

Amusingly, **this depends on the filename of the second script!** If I rename `Bar_foo_baz.v` to `Bar.v`, `Foo_bar.v` or `Foo_bar_baz.v`, everything works fine again. An other name that makes the issue appear is `Simple_sparse_proof.v` instead of `Bar_foo_baz.v`, which was the actual original filename.

`Foo.v`
```coq
Definition binary A := A -> A -> Prop.

Definition inter A (R1 R2 : binary A): binary A :=
  fun (x y:A) => R1 x y /\ R2 x y.
```

`Bar_foo_baz.v`
```coq
Parameter node : Type.
Parameter graph : Type.
Parameter has_edge : graph -> node -> node -> Prop.
Implicit Types x y z : node.
Implicit Types G : graph.

Require Foo.

Parameter mem : forall A, A -> list A -> Prop.
Hypothesis mem_nil : forall x, mem node x nil = False.

Definition notin (l: list node): node -> node -> Prop :=
  fun x y => ~ mem node x l /\ ~ mem node y l.

Definition edge_notin G l : node -> node -> Prop :=
  Foo.inter node (has_edge G) (notin l).

Hint Unfold Foo.inter notin edge_notin : rel_crush.

Lemma edge_notin_nil G : forall x y, edge_notin G nil x y <-> has_edge G x y.
Proof.
  intros. autounfold with rel_crush. rewrite !mem_nil. tauto.
Qed.
```

**Comment by ejgallego** [comment]
Thanks @Armael , it is not very uncommon to see such kind of situations sadly; we should also try to figure out if 8.7 and 8.6 suffer from the same problem; this could be well a regression.

**Comment by Armael** [comment]
What's causing these kind of bugs? Also, is there a known workaround, apart from renaming the script file?

**Comment by ejgallego** [comment]
Likely if you use the `-top` command line option the bug may go away.

**Comment by mattam82** [comment]
It could be that autounfold performs the unfoldings in different orders if it is based on a constant set for example

**Comment by Armael** [comment]
@mattam82 ah! this seems to be the case indeed! using `repeat autounfold ...` instead of just `autounfold` "fixes" the script. But why would the behavior of autounfold change depending on the filename?

**Comment by ejgallego** [comment]
Good catch @mattam82 , indeed PG/CoqIde set a different module name from `coqc` [which is IMHO something we need to solve] , and that triggers the autounfold problem.

**Comment by Armael** [comment]
Isn't the fact that autounfold is order dependent and does not unfold everything that is in its base a bug in itself?

**Comment by mattam82** [comment]
Certainly
