### ISSUE TITLE
Feature Request: let open record in

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#7834]
I would like to be able to write something like `let open myrecordvalue in ...` as a shorthand for `let (a, b, c) myrecordvalue in ...` when `myrecordvalue` has fields `a`,`b`, `c`.

~~~~~
Module foo.
  Record foo := { a : nat ; b : bool }.
End foo.
Notation foo := foo.foo.

Check (fun (f:foo) => let (a,b) := f in a).
Check (fun (f:foo) => ltac:(destruct f; exact a)). (* ugly hack, doesn't work if projections are in scope *)
Check (fun (f:foo) => let open f in a).
~~~~~

Granting this and https://github.com/coq/coq/issues/7781 and https://github.com/coq/coq/issues/7810 would probably work for many of the use cases that https://github.com/coq/coq/issues/7808 was meant for.

**Comment by andres-erbsen** [comment]
The lack of a import mechanism for first-class objects is still a pain point in my use of Coq. Did something specific happen that triggered the closing of these issues now, or is it just a general cleanup of old and inactive tickets?

**Comment by SkySkimmer** [comment]
General cleanup

**Comment by ejgallego** [comment]
Indeed keeping this tickets open may not be very productive if they are not going to be addressed.

On the other hand the tickets are valid; maybe we should put them under a tag or project "valid-but-not-addressed" ?

**Comment by ejgallego** [comment]
I always understood `won'tfix` as "we reject this feature".
