### ISSUE TITLE
tools/inferior-coq.el uses next-line instead of forward-line

### ISSUE THREAD

**Issue by pmetzger** [coq/coq#7836]
#### Version

8.8.0

#### Description of the problem

In inferior-coq.el, we see:

```elisp
(defun coq-send-line ()
  "Send the current line to the Coq process."
  (interactive)
  (save-excursion
    (end-of-line)
    (let ((end (point)))
      (beginning-of-line)
      (coq-send-region (point) end)))
  (next-line 1))
```

`next-line` is for interactive use only, and the proper function to use is `forward-line`. Because of this, error messages are now printed during initialization in emacs 26, which is rather irritating.

**Comment by ejgallego** [comment]
I guess a PR would be straightforward?

**Comment by pmetzger** [comment]
At another time it might be but I can't do one right now. It's a one word change, though...

**Comment by Zimmi48** [comment]
So there are still people using these modes?! Would you mind telling a bit more about your use case? (I.e. why not use Proof-General instead?)

**Comment by pmetzger** [comment]
I'm not using it, I use proof general, but things like OPAM install it, and the error messages are annoying. If you don't want to make the one word change to the file, that's fine, but why not remove the thing entirely if it's so discouraged that a one word fix is a problem?

**Comment by Zimmi48** [comment]
Oh no, I'm fine with doing the one word change. But since I have wanted to remove this for a while now, I was interested to hear about use cases if there were some.

**Comment by pmetzger** [comment]
I have no use for it. If you wanted to get rid of it, it would not make me the least bit unhappy.

_That_ said, I would recommend getting the Proof General people a decent OPAM file so that one can auto-install their stuff along with Coq. Having to do your configuration by hand is unpleasant. This is unrelated to the current issue though.

**Comment by Zimmi48** [comment]
I think the Proof-General people are working at making their stuff available through Melpa. Having a OPAM file wouldn't make much sense since there's not the least bit of OCaml in Proof-General. It's not comparable to merlin.
Anyways, I've opened two PRs: one to fix this issue in 8.8.1 and one to remove these modes in 8.9.

**Comment by pmetzger** [comment]
"Having a OPAM file wouldn't make much sense since there's not the least bit of OCaml in Proof-General. It's not comparable to merlin" — there's no ocaml in Tuareg either, but it's available via opam. But this is a different issue.

**Comment by maximedenes** [comment]
Well, this is an obvious drawback of using ad-hoc package managers (as opposed to apt or Nix), but I'm not sure there is a good solution. Having redundant packages between melpa and OPAM can also easily lead to configuration issues.

**Comment by pmetzger** [comment]
It could, though right now Tuareg is available from both and it causes few problems in practice. Emacs users tend to be sophisticated.
