### ISSUE TITLE
Test-suite should use file names that are valid for `coqc`

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#7853]
Today, we run the test suite by feeding files on the `coqtop` input. We would like instead (at least for some of the tests), to run `coqc`, to test the native compiler and the checker. However, the file names starting with numbers are not accepted by `coqc`, and we use a lot in the test suite.

What should be done? Allow such file names or renaming the files in the test suite? I imagine it can be confusing to have modules with number-only identifiers, like `x.1`. So maybe the second solution?

**Comment by JasonGross** [comment]
My intuition is to just rename the files in the test-suite.  Or else just pass `-top Top` to `coqc`; would that work?

Note also that we'll need to close sections and modules and proofs in many of the files; IIRC, the test-suite allows unterminated sections/modules/proofs.

**Comment by maximedenes** [comment]
@vbgl I had forgotten this report, you may want to mention it on your PR that fixes it :)
