### ISSUE TITLE
Native compilation triggers segmentation fault under flambda optimizations

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#7854]
#### Version

Coq 8.8

#### Operating system

Debian SID amd64, OCaml 4.06.1+flambda

#### Description of the problem

Confirming the suspicions of #7750, Coq native compilation is unsound w.r.t. OCaml semantics, and the optimizations performed by the `flambda` flag might cause serious errors. For instance, the following snippet triggers a SEGFAULT.
```
Set Primitive Projections.

CoInductive stream (A : Type) := cons {
  hd : A;
  tl : stream A;
}.

CoFixpoint const {A} (x : A) := cons A x (const x).

Check (@eq_refl _ tt <<: tl unit (const tt) = const tt).
```
I did not try to generate a proof of False, but I believe this is serious enough to deserve a critical label.

**Comment by maximedenes** [comment]
Thanks for minimizing, did you see what was incorrect in the generated code?

**Comment by ppedrot** [comment]
Very hard to tell, as far as my mental model goes I cannot see anything specific in the OCaml code, the bug is probably hidden in the intermediate representation.

**Comment by maximedenes** [comment]
Maybe we could ask flambda experts?

**Comment by ppedrot** [comment]
I am trying to write a patch to hide the transparent definition of `Nativevalues.t` and rely on explicit casts for application. Hopefully this should be enough.

**Comment by maximedenes** [comment]
Ok, but make sure those explicit casts don't break optimizations of the compiler without flambda. It was the whole point of the current `t = t -> t` setup.

**Comment by ppedrot** [comment]
The casts are really just Obj.magic under the hood, the typing only uses a phantom argument for encoding arities.

**Comment by maximedenes** [comment]
> The casts are really just Obj.magic under the hood, the typing only uses a phantom argument for encoding arities.

Yes, but it doesn't mean that it is transparent w.r.t. all optimizations of the compiler, if performed at high level passes. But it can be tested by comparing the output assembly on some large enough examples.

**Comment by ppedrot** [comment]
Wow. I don't understand, but doesn't look like it has anything to do with Coq itself. The `-shared` flag is enough to trigger a segmentation fault. Step to reproduce:
```
ocamlopt -v
# The OCaml native-code compiler, version 4.06.1
touch foo.ml
ocamlfind opt -shared foo.ml  -o foo
./foo
# Segmentation fault
```
Why some conversions do not trigger the error is beyond my comprehension though...

Can anyone reproduce?

**Comment by SkySkimmer** [comment]
>Wow. I don't understand, but doesn't look like it has anything to do with Coq itself. The -shared flag is enough to trigger a segmentation fault. Step to reproduce:

Reproduced 4.06.0 non flambda

**Comment by ppedrot** [comment]
Wait, forget it, that's stupid, this is not supposed to be an executable but a dynamically linked library. No wonder why it explodes.

**Comment by ppedrot** [comment]
[Here is](https://github.com/coq/coq/files/2117226/bug.zip) a reproductible example extracted from the failing Coq code. You have to adapt COQLIB in `script.sh` to the proper path for it to work and then execute the `test` binary produced by the compilation. If that helps...

**Comment by ppedrot** [comment]
And [here is](https://github.com/coq/coq/files/2117291/bug.zip) a self-contained example that does not even link to Coq. I inlined the minimal amount of Nativevalues needed, which is enough to play with the files.

**Comment by ppedrot** [comment]
@maximedenes So it seems that with flambda the accumulation mechanism doesn't work as intended. In the case of `const_Nbug_const`, applying it to `Construct_Nbug_unit_0_0` results in a closure where the initial environment of `const_Nbug_const` is dropped, leading to an ill-formed accumulator.

That is, if
```
const_Nbug_const := Clos(code, Acofix (...))
```
then
```
const_Nbug_const Construct_Nbug_unit_0_0 := Clos(code, 0)
```
which is definitely wrong, as one would like instead
```
Clos(code, Acofix (...), 0)
```

I'll try to provide a minimal example of this phenomenon.

**Comment by ppedrot** [comment]
Here is a really self-contained snippet that acts as a shibboleth between the two behaviours:
```
type t = t -> t
    
type accumulator

type atom = int 

let accumulate_tag = 0

let accumulate_code (k:accumulator) (x:t) =
  let o = Obj.repr k in
  let osize = Obj.size o in
  let r = Obj.new_block accumulate_tag (osize + 1) in
  for i = 0 to osize - 1 do
    Obj.set_field r i (Obj.field o i)
  done;
  Obj.set_field r osize (Obj.repr x);
  (Obj.obj r:t)

let rec accumulate (x:t) =
  accumulate_code (Obj.magic accumulate) x

let mk_accu_gen rcode (a:atom) =
  let r = Obj.new_block 0 3 in
  Obj.set_field r 0 (Obj.field (Obj.magic rcode) 0);
  Obj.set_field r 1 (Obj.field (Obj.magic rcode) 1);
  Obj.set_field r 2 (Obj.magic a);
  (Obj.magic r:t)

let mk_cofix_accu =
  mk_accu_gen accumulate 0xdead

let v = Nativev.mk_cofix_accu (Obj.magic 0xbeef : Nativev.t)

let () =
  let obj = Obj.repr v in
  assert (Obj.size obj == 4);
  let f = Obj.field obj 2 in
  assert (Obj.is_int f);
  assert ((Obj.magic f : int) == 0xdead)
```
Without flambda, one gets
```
v := (tag = 0)[code, 1, 0xdead, 0xbeef]
```
while with flambda one gets
```
v := (tag = 0)[code, 1, 0xbeef]
```

**Comment by lthls** [comment]
In `accumulate`, the function is lifted to a global constant by flambda and the `(Obj.magic accumulate)` parameter to `accumulate_code` is replaced by a pointer to the globally allocated closure.
So when you call `accumulate` through a custom closure (like the one created by `mk_cofix_accu`), `accumulate_code` always extends the original closure, not the one it got called from.

Here is a version that seems to work (at least with flambda 4.06.0):
```ocaml
type t = t -> t

type accumulator

type atom = int 

let accumulate_tag = 0

let accumulate_code (k:accumulator) (x:t) =
  let o = Obj.repr k in
  let osize = Obj.size o in
  let r = Obj.new_block accumulate_tag (osize + 1) in
  for i = 0 to osize - 1 do
    Obj.set_field r i (Obj.field o i)
  done;
  Obj.set_field r osize (Obj.repr x);
  (Obj.obj r:t)

let [@inline never] mk_accumulate ign =
  let rec accumulate (x:t) =
    ignore (Sys.opaque_identity ign);
    accumulate_code (Obj.magic accumulate) x
  in
  accumulate

let mk_accu_gen rcode (a:atom) =
  let r = Obj.new_block 0 3 in
  Obj.set_field r 0 (Obj.field (Obj.magic rcode) 0);
  Obj.set_field r 1 (Obj.field (Obj.magic rcode) 1);
  Obj.set_field r 2 (Obj.magic a);
  (Obj.magic r:t)

let mk_cofix_accu =
  mk_accu_gen (mk_accumulate ()) 0xdead

let v = mk_cofix_accu (Obj.magic 0xbeef : t)

let () =
  let obj = Obj.repr v in
  assert (Obj.size obj == 4);
  let f = Obj.field obj 2 in
  assert (Obj.is_int f);
  assert ((Obj.magic f : int) == 0xdead)
```

This forces `accumulate` to access itself through its closure instead of a global symbol.
There is no guarantee that this will stay the case for future versions of flambda, however.

**Comment by chambart** [comment]
To state the problem clearly, this code assumes some representation for the closures. The compiler assumption is that a closure is opaque and can only be applied and nothing else. Some problems can be triggered if you mess with closures, with and without flambda. You were lucky not to trigger it before. I'm not going to support anything remotely like that on function as this would prevent far too many optimizations opportunities.

But that's not a problem, since there is a perfectly decent way to access a function closure: from inside the function. The trick to access it from outside is to add a second 'entry point' to the function.

```OCaml
let accu, data, apply =

  let r = Obj.new_block 0 1 in

  let rec f acc (x:Obj.t) =
    if x == r then
      Obj.repr acc
    else
      Obj.repr (f (x :: acc))
  in
  let accu = Obj.repr (f []) in

  let data acc = (Obj.obj acc : Obj.t -> Obj.t list) r in

  let apply acc v = (Obj.obj acc : Obj.t -> Obj.t) v in
  accu, data, apply
```

Since `r` is allocated as a mutable value, the compiler is not allowed to share it with anything else, hence `x == r` won't ever be true for any value produced outside this scope.
