### ISSUE TITLE
Wrong line number for a warning

### ISSUE THREAD

**Issue by fblanqui** [coq/coq#7862]
#### Version

The Coq Proof Assistant, version 8.8.0 (May 2018)
compiled on May 2 2018 21:29:03 with OCaml 4.06.1

#### Operating system

Linux 6600Fred 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Description of the problem

Using https://github.com/fblanqui/color:

COQC Coccinelle/term_orderings/rpo.v
File "./Coccinelle/term_orderings/rpo.v", line 3480, characters 0-188:
Warning: Unused introduction pattern: IH [unused-intro-pattern,tactics]

1380: intros p l1 l2 E;
1381: functional induction (equiv_eval_list p l1 l2) as 
1382: [ 
1383: | H1 H2 t1 l1 H3 t2 l2 H4 H IH
1384: | H1 H2 t1 l1 H3 t2 l2 H4 H IH
1385: | H1 H2 t1 l1 H3 t2 l2 H4 H IH
1386:| l1 l2 H1 H2 H3 H4 H].

**Comment by fblanqui** [comment]
This is the second occurrence of IH, line 1384, that is unused.

**Comment by fblanqui** [comment]
See color commit d2ff19f24dd56be7bae8a835e58bb62a32fb81d6.

**Comment by SkySkimmer** [comment]
Too old to reproduce
