### ISSUE TITLE
Lia struggles with goals in `Type`

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#7887]
`lia` fails on the following goal:

```coq
Require Import Lia.

Axiom P : nat -> Set.

Goal forall n : nat, n < 0 -> P n.
intros. lia.
```

while `omega` succeeds. Coq complains about a type error, so I believe the fix should not be too hard, I'll have a look.

**Comment by maximedenes** [comment]
The bug is due to `mkProp` on the following line:

https://github.com/coq/coq/blob/e7b406fb8996b31a3283ed80f3e964ebe69b05ab/plugins/micromega/coq_micromega.ml#L1240

Shouldn't be too hard to fix, but we need to properly thread the `evar_map`.

**Comment by SkySkimmer** [comment]
Might need #7369 to do it properly.

**Comment by maximedenes** [comment]
> Might need #7369 to do it properly.

I see, this is much trickier than I thought. Maybe I can anticipate whether the goal is in `Prop` or not, and generate the universe accordingly.

**Comment by fajb** [comment]
The error is not reported at the right place -- lia should fail much earlier because it only understands propositional logic i.e. Prop.
To cover such goals, I would propose to apply exfalso  during pre-processing.

**Comment by rnrand** [comment]
This is breaking a lot of proofs for me in my ongoing attempt to migrate from `omega` to `lia`. 

(Though an `exfalso; lia` has so far been enough to handle this.)

Does any of the ongoing work on `lia` address this?

**Comment by fajb** [comment]
PR #9856 should solve the issue.
In the meantime, the following Ltac may help:
```
Ltac exfalso_if_Type :=
  match goal with
  |  |- ?G =>     match type of G with
                       | Prop => idtac
                       |  _   => exfalso
                     end 
end.

Ltac liat := exfalso_if_Type ; lia.
```
