### ISSUE TITLE
Specific install steps in Windows build script.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7896]
I've just learned about:

https://github.com/coq/coq/blob/df35025b2be4a0dc9aadecc0e3110a21012683cf/dev/build/windows/makecoq_mingw.sh#L1124-L1140

I don't think any reason can justify having these specific install steps on Windows only. If these files should be installed, please adapt `Makefile.install` to your liking, then remove these lines from the Windows script.

As for:

https://github.com/coq/coq/blob/df35025b2be4a0dc9aadecc0e3110a21012683cf/dev/build/windows/makecoq_mingw.sh#L1096-L1122

Not all Linux distributions will have these files already there by default, so it could be interesting to install them in any case.

And about:

https://github.com/coq/coq/blob/df35025b2be4a0dc9aadecc0e3110a21012683cf/dev/build/windows/makecoq_mingw.sh#L1082-L1094

I'm not sure but I thought these files were installed by `Makefile.install` already.

Only:

https://github.com/coq/coq/blob/df35025b2be4a0dc9aadecc0e3110a21012683cf/dev/build/windows/makecoq_mingw.sh#L1015-L1080

looks like really specific Windows things that make sense to have there.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : this are indeed all historic artifacts from the time I tried to get a proper Windows install without touching Coq itself ...

Another thing which needs to be done is a clear separation between the old scripts which could build various versions (including those which don't have these scripts in github) and newer ones which can only build one specific version. I think it is best to test the scripts from 8.6 if they can build 8.4 ... 8.6 and from now on remove everything which is only there for compatbility with old version (like the || true above).

**Comment by MSoegtropIMC** [comment]
This is deprecated with Coq Platform.

**Comment by MSoegtropIMC** [comment]
The PR which removed the old build scripts and switched to Coq Platform was (#13598).
