### ISSUE TITLE
The checker does not check the primitive record info

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7909]
https://github.com/coq/coq/blob/7836f9319f17a642921cbf9b153077fc195ca8e1/checker/indtypes.ml#L613
There's probably a way to craft a vo which lets people prove false without complaint from the checker using this.

**Comment by maximedenes** [comment]
@SkySkimmer isn't this fixed after the checker refactorings?

**Comment by SkySkimmer** [comment]
Yes

**Comment by SkySkimmer** [comment]
We have no infrastructure for crafting bad vos so not bothering to make a test.
