### ISSUE TITLE
strange universe inconsistency in Coq 8.8 (removed template poly for constants)

### ISSUE THREAD

**Issue by orilahav** [coq/coq#7930]
8.8

mac os

#### Description of the problem

```
Require Import Relation_Definitions.
Require Import FMapPositive.


Inductive foo := mk: Type -> foo.

Definition bar := PositiveMap.t foo.

Definition bar' :=  mk (relation nat).
```

The definition of bar' produces an unexpected universe inconsistency.
Changing "relation nat" to "nat -> nat -> Prop" avoids the problem.
Seems to work well in Coq 8.7.

**Comment by Zimmi48** [comment]
@SkySkimmer @mattam82 This seems to be a regression from 8.8. What is your assessment of its priority level?

**Comment by SkySkimmer** [comment]
Probably the template polymorphism definition removal.

**Comment by ppedrot** [comment]
I second @SkySkimmer's analysis.

**Comment by SkySkimmer** [comment]
Note we can't do `Notation t := tree` because module subtyping expects a constant `t`.

**Comment by Zimmi48** [comment]
Not a regression but an intended change then? Can you explain the workaround?

**Comment by SkySkimmer** [comment]
I guess we could do https://github.com/coq/coq/commit/3750bc4332263a83217983b23a0ce0e519faa497 but it's not very satisfying.

**Comment by SkySkimmer** [comment]
Eventually the tree stuff may be made universe polymorphic
