### ISSUE TITLE
request: focus on *goal* in coqide

### ISSUE THREAD

**Issue by orilahav** [coq/coq#7931]
8.8.

mac os

#### Description of the problem

Every step in coqide moves the focus back to the beginning of the hypotheses list.
This can be very frustrating when working with long list of hypotheses, as it requires scrolling back down after every step. Would be much better if it'd focus on the first goal.

**Comment by Zimmi48** [comment]
As remarked in #7932, this used to be the case, so this is actually a regression (of 8.6).

**Comment by nomeata** [comment]
Hmm, I upgraded to 8.8.1 eagerly for this change, but it seems it scrolls to the *end* of the first goal, rather to the beginning. With very large goals, I would expect to still see 
```
______________________________________(1/21)
```

Maybe the logic should be something like (in descending order of priority) “Always show the above line; show as much of the first goal; show as much of the first context”
