### ISSUE TITLE
counter-intuitive behavior when passing evar names to tactics

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#7938]
#### Version

~~~~~
The Coq Proof Assistant, version 8.8.0 (May 2018)
compiled on May 3 2018 7:11:49 with OCaml 4.06.0
~~~~~

#### Operating system

Arch Linux, up to date as of a week ago.

#### Description of the problem

The intuitive behavior for `set ?[e]` would be to set `?e`, but it sets the entire goal. The behavior of `pattern` with evar names is also evading my intuition but I have not investigated it yet.

~~~~~{.v}
Goal exists n : nat, n = n.
  eexists.
  set ?[n] as x.
  match goal with |- x = x => idtac end.
  (* Toplevel input, characters 15-53: *)
  (* > match goal with |- x = x => idtac end. *)
  (* > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ *)
  (* Error: No matching clauses for match. *)
  Fail match goal with |- x => idtac end.
  (* Toplevel input, characters 0-39: *)
  (* > Fail match goal with |- x => idtac end. *)
  (* > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ *)
  (* Error: The command has not failed! *)
Abort.
~~~~~

**Comment by ppedrot** [comment]
Your script should read instead:
```
Goal exists n : nat, n = n.
  eexists ?[n].
  set ?n as x.
```

**Comment by andres-erbsen** [comment]
Does it mean that there is no way to reference evars with auto-generated names?

**Comment by ppedrot** [comment]
Indeed, and this is a conscious choice.

**Comment by herbelin** [comment]
Not sure what you mean by "no way to reference evars with auto-generated names".

You can do:
```coq
Goal exists n : nat, n = n.
eexists.
match goal with |- context [ ?t ] => is_evar t; set t as x end.
```
You can also do:
```coq
Goal exists n : nat, n = n.
eexists ?[n].
set ?n as x.
```
It is not implemented but one could also consider the following as an intuitive feature to provide:
```coq
Goal exists n : nat, n = n.
let n := fresh in eexists ?[n]; set ?n as x.
```
or maybe even (virtually, because only functions can currently be defined in Ltac2):
```coq
Goal exists n : nat, n = n.
Ltac2 n := Fresh.fresh (Fresh.Free.of_ids []) @H.
eexists ?[n].
set ?[n] as x.
```

**Comment by JasonGross** [comment]
I think it's correct to say that there's no way to reference, by name, evars with auto-generated names.

**Comment by herbelin** [comment]
Ah then, yes, this is the "conscious choice" mentioned by @ppedrot. But we can imagine a mechanism using `fresh` as a handle on an auto-generated name.
