### ISSUE TITLE
"make coqbinaries" should rebuild .ml files in plugins

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#7944]
#### Description of the problem

If I modify the interface for a base code module, say stm/stm.ml, then do a `make coqbinaries` and try to run coqtop, I get an error such as the one shown because `make coqbinaries` doesn't recompile `plugins/*/*.ml`.  This forces me to do a full `make` that rebuilds all the .vo files--_much_ slower.  AFAIK the point of `make coqbinaries` is to have a quicker build when you know the .vo files won't change.  The current behavior defeats this goal.

```
$ bin/coqtop.opt.exe
Welcome to Coq DESKTOP-MMPNVGH:/cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq,diffs (ae37f1da63c0d0c64a1a1da84f82d340c4db0488)
Error:
while loading
C:\Users\Jim.DESKTOP-MMPNVGH\Documents\coqSource\coq\plugins\ltac\ltac_plugin.cmxs:
interface mismatch on Stm
```

**Comment by jfehrle** [comment]
Looks like all that's needed for this is to generate the list of plugin .cmxs files and make them targets for coqbinaries.  And the list of .cmxs files is `plugins/*/*.mlpack`, replacing "mlpack" with "cmxs".

**Comment by SkySkimmer** [comment]
Why not use the coqocaml target instead?

**Comment by jfehrle** [comment]
Ah, good idea.  Often hard to discover these things.

**Comment by Zimmi48** [comment]
See alsoo #7208
