### ISSUE TITLE
8.8.1 dmg/mac binary?

### ISSUE THREAD

**Issue by brianmorton** [coq/coq#7963]
Release notes say there is one, but didn't find one on the releases page. Is this just an oversight or is there somewhere else they are being released now?

**Comment by Zimmi48** [comment]
Coq 8.8.1 has not been officially released yet, sorry for having inadvertently published the release notes.
The packages are in the process of getting signed and should be available by Monday at the latest.

**Comment by Zimmi48** [comment]
I can't "unpublish" the release but I did clarify the section about packages in the meantime.

**Comment by ejgallego** [comment]
> I can't "unpublish" the release but I did clarify the section about packages in the meantime.

You can delete the release actually.

**Comment by Zimmi48** [comment]
No, I thought I could but I can't find a way. If you know how to do it, feel free to do it, but please copy-paste the content in a new draft release then.

**Comment by ejgallego** [comment]
Go here, and you will see "Delete" https://github.com/coq/coq/releases/tag/V8.8.1

**Comment by Zimmi48** [comment]
Oh, indeed. Thanks!
