### ISSUE TITLE
Local Hints should not be global

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#7970]
#### Version

8.8.0

#### Description of the problem

In 8.7, this code errors on `Local Hint`.  In 8.8, it succeeds without even a warning.  This is wrong.

```coq
Module A.
  Axiom bad : 1 = 0.
  Local Hint Rewrite bad.
End A.
Goal 0 = 1.
  autorewrite with core; reflexivity.
Qed.
```

**Comment by Zimmi48** [comment]
Tagging @vbgl as this is likely to be related to the preliminary work on attributes.

**Comment by SkySkimmer** [comment]
Fixed in some attribute refactoring.
