### ISSUE TITLE
ProofGeneral fails where coqc succeeds, with overriding-logical-loadpath

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#7980]
#### Description of the problem

I have a development in which I deliberately use overlapping loadpaths, with messages such as,
```
Warning: /n/fs/fac/appel/loadpath-issue/A was previously bound to P.A; it is
remapped to A [overriding-logical-loadpath,loadpath]
```

I can build my system just fine with coqc, but ProofGeneral does not work: it is confused by the overlapping loadpaths.

I have reproduced the problem in the attached,
[loadpath-issue.zip](https://github.com/coq/coq/files/2156782/loadpath-issue.zip)

This contains 3 tiny Coq files, a one-line _CoqProject file, and a 4-line Makefile.  If you say "make", then Crox.vo builds just fine, but within Proof General, the second line of Crox.v gives the message,
`Error: Unable to locate library Foo.`

By the way, CoqIDE on cygwin works just fine, agrees with coqc.

**Comment by Matafou** [comment]
thnks for submitting.

**Comment by Matafou** [comment]
fixed in PG github master.
