### ISSUE TITLE
Spacing issue in printing sigT notation with patterns

### ISSUE THREAD

**Issue by cryslith** [coq/coq#7987]
#### Version

8.8.0

#### Description of the problem

Printing the sigT notation `{ ' pat : A & P }` does not print a space after the ampersand.  For some reason this does not occur with sig notation `{ ' pat : A | P }`.

```
(* & spaced badly *)
Check {'(a, b) : nat * nat & a = b}. (* {'(a, b) : nat * nat &a = b} *)
Check {'(a, b) : nat * nat & a = b & a = b}. (* {'(a, b) : nat * nat &a = b &a = b} *)

(* | is spaced properly but & is wrong *)
Check {'(a, b) : nat * nat | a = b}. (* {'(a, b) : nat * nat | a = b} *)
Check {'(a, b) : nat * nat | a = b & a = b}. (* {'(a, b) : nat * nat | a = b &a = b} *)

(* Fine without patterns *)
Check {a : nat & a = 0}. (* {a : nat & a = 0} *)
```

#### Expected behavior

There should be a space after all ampersands when printing the above cases.

**Comment by SkySkimmer** [comment]
Seems fixed since 8.12
