### ISSUE TITLE
Coq compilation fail

### ISSUE THREAD

**Issue by hfehrmann** [coq/coq#7999]
#### Version
8.8.0

#### Operating system
Ubuntu 16.04 LTS 64-bit

#### Description of the problem
Doing a fresh install the process fail doing on the make. I'm including the trace of compilation plus the configure used to compile. It fails for both `make` and `make world`

[conf.txt](https://github.com/coq/coq/files/2165605/conf.txt)
[trace.txt](https://github.com/coq/coq/files/2165578/trace.txt)

**Comment by hfehrmann** [comment]
It seems to be the second. Coq 8.7.2 works just fine.

**Comment by ejgallego** [comment]
Please reopen if the issue persists.
