### ISSUE TITLE
Wrong URLs in xml-protocol.md

### ISSUE THREAD

**Issue by rnarkk** [coq/coq#8017]
Hi,

I've come across wrong URLs in https://github.com/coq/coq/blob/master/dev/doc/xml-protocol.md that says [`ide/interface.mli`](https://github.com/coq/coq/blob/master/ide/interface.mli) and [`dev/doc/changes.txt`](https://github.com/coq/coq/blob/master/dev/doc/changes.txt) but both return 404. I guess the latter should be https://github.com/coq/coq/blob/master/dev/doc/changes.md (extension has changed) but am not sure which file corresponds to the former ([`ide/protocol/interface.ml`](https://github.com/coq/coq/blob/master/ide/protocol/interface.ml)?). Would someone tell me? Thanks.

**Comment by Zimmi48** [comment]
Both of your guesses are right. Would you mind submitting a pull request fixing this? Thanks!

**Comment by rnarkk** [comment]
Thank you @Zimmi48, sure, I just submitted the pull request so please check it out!
