### ISSUE TITLE
coqpp: locations and tooling

### ISSUE THREAD

**Issue by gares** [coq/coq#8018]
I'm writing this after a discussion with @maximedenes.
- It seems `coqpp` does not put in the generated text pragmas as `#line 123 "origfile.mlg"` hence locations are lost and error are signaled on the generated file, not on the original file
- It also seems that `coqpp` is not used as in `ocamlc -pp coqpp` hence it leaves around generated files but it does not need to

**Comment by ejgallego** [comment]
> It also seems that coqpp is not used as in ocamlc -pp coqpp hence it leaves around generated files but it does not need to

That's a matter of style, this is what was done with `camlp5` AFAICT; dev-wise, you want to look at the intermediary files often.

**Comment by maximedenes** [comment]
@ppedrot any progress on that? Not having locations is a very serious regression w.r.t. camlp5.

**Comment by SkySkimmer** [comment]
>That's a matter of style, this is what was done with `camlp5` AFAICT; dev-wise, you want to look at the intermediary files often.

I guess instead of READABLE_ML4 we should have KEEP_GENERATED. I don't think you often look at the binary camlp5 output.

**Comment by ejgallego** [comment]
> I guess instead of READABLE_ML4 we should have KEEP_GENERATED. I don't think you often look at the binary camlp5 output.

That mostly matters for the workflow of the dependency rules, the dependency chain is different and so is parallelism. In the Dune version we will surely keep the generated files for now as it simpler [and they don't bother as they are placed in _build].

**Comment by Zimmi48** [comment]
I'm moving this to 8.10+beta1 because the PR fixing this was merged in this milestone but if this regression is concerning for 8.9, maybe it should be backported...

**Comment by Zimmi48** [comment]
I take this as a no.
