### ISSUE TITLE
Doc of "assert_succeeds" and "assert_fails" should ideally be explained at a high level.

### ISSUE THREAD

**Issue by charguer** [coq/coq#8033]
The index incorrectly references the tactic as "assert_suceed" with a single "c".
https://coq.inria.fr/refman/coq-tacindex.html

By the way, the documentation of "assert_succeeds" and "assert_fails" should ideally be explained at a high level, independently of their implementation.
"Coq provides a derived tactic to check that a tactic fails" does not quite describe the arguments, the return value and the (absence of) sided-effects of the tactic.

https://coq.inria.fr/refman/proof-engine/ltac.html#coq:tacn.assert-suceeds

Thanks

**Comment by charguer** [comment]
https://github.com/coq/coq/pull/8035

**Comment by maximedenes** [comment]
Please mention the issue in the PR commit message, and this issue will be closed at merging time.

**Comment by maximedenes** [comment]
A typical message would be "Fix #8033: Tactic assert-suceeds has a typo in its name in the manual"

**Comment by charguer** [comment]
Ok, I'm not sure how to fix things at this stage (a dummy commit does not seem ideal?), but if you could handle it for this time, I'll do my best to follow the guidelines on my next PR. Sorry about that

**Comment by ejgallego** [comment]
@charguer just amend the commit and force-push.

**Comment by charguer** [comment]
Sorry guys for being such a beginner. Please take it easy on me, you probably don't want to discourage me from submitting further PRs :)

**Comment by maximedenes** [comment]
> Sorry guys for being such a beginner. Please take it easy on me, you probably don't want to discourage me from submitting further PRs :)

No worries at all, your PR is very welcome and having to edit a commit message is not a big deal, don't worry. You can do it if you want to learn (just `git commit --amend`), or I can take care of it.

**Comment by jfehrle** [comment]
The description of these two tactics was updated some time ago, I think addressing the second part of your report.  Feel free to reopen and comment further if you wish.
