### ISSUE TITLE
Broken link with spaces in manual

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8039]
#### Version

8.8.1

#### Description of the problem

The page https://coq.inria.fr/refman/language/gallina-extensions.html has the text
```
(see`http://standards.freedesktop.org/basedir- spec/basedir-spec-latest.html`_
```
which looks like a couple of spacing issues.  (missing space after `see`, confusing `_` at the end, wrong space after `basedir-`)

**Comment by Zimmi48** [comment]
Already fixed in #7965. One thing I have to work on is to update the refman continuously and not just at release time.
