### ISSUE TITLE
Windows packaging builds are overly verbose.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8045]
Windows packaging builds are overly verbose and include things such as decompression / untarring logs; NSIS debug information, etc... which makes them very hard to read, and waste quite a lot of space.

Please, provide less verbose logging by default, and if necessary, provide a debug option or upload an artifact.

**Comment by MSoegtropIMC** [comment]
Well I think ignoring information you don't need is less troublesome than conjuring information you don't have out of thin air. I think rerunning jobs to get additional information is not a good solution. I think this way much more time (and resources) are wasted than by having verbose log files. But the system already has log files in an extra folder, so this could be uploaded as artifact instead.

I generally like the set -x of the main script for debugging, but I could put this into a log file as well (it currently isn't).

What would you like to see in the logs? Just module start / end messages and the last few lines of error messages?

**Comment by Zimmi48** [comment]
Indeed, I would support putting a bit less in the logs that are displayed and storing the rest of the logs as build artifacts. I don't have any good suggestion on what to keep / what to remove.

**Comment by ejgallego** [comment]
Example: https://gitlab.com/coq/coq/-/jobs/107883687

It is literally hard to understand what is going on with the current log format.

**Comment by Zimmi48** [comment]
Indeed, it's a bit hard to read because of artifact upload but the log verbosity is otherwise a problem solved. Maybe there should be a bit of documentation (in `dev/ci/README.md`) mentioning that most of the log is to be browsed through artifacts.

**Comment by ejgallego** [comment]
> most of the log is to be browsed through artifacts.

Please don't fix this issue like that. Some of us just want to click and have a single message telling us what went wrong with the build. Logs are OK for those needing the details.

I think the issue is simple, when a build goes wrong, there is only 1 relevant piece of information, the rest is just making the person looking at the logs lose their time.

**Comment by MSoegtropIMC** [comment]
@ejgallego : would you consider this as fixed meanwhile? There have been some PRs integrated to improve the logging, most notably to put all more verbose logging into separate files and upload them as artifacts.

**Comment by ejgallego** [comment]
IMHO we still have plenty of room to improve, so I'd like this to be open. It still takes me a lot of time to navigate the logs, and on top of that I have to open a file; compared to the setup we have on Linux + Dune for example this can get better.

It may make sense to add a flag so that the default CI build is silent, but you can turn it verbose from the web interface.

**Comment by MSoegtropIMC** [comment]
In my opinion the main verbose thing is the artifact upload. I kept it like this for a while because it failed frequently, but it is stable now and I could remove it.

For other things, could you be more concrete, e.g. take a snip of the log and tell what you would like to see instead?

Did I understand it right that you don't like the "logfiles as artifacts" method? I guess you would like to have the tail of the log of the failing process in the end. Is this the main thing you would need?

I hardly need more than 30 seconds to get to the cause of a build failure, but of cause I wrote these scripts and know how to browse the information. Is it maybe a question of documentation?

**Comment by MSoegtropIMC** [comment]
@ejgallego : I think the difference between a makefile calling a compiler and this here is that this is a bunch of nested rather complicated batch files and shell scripts and it does fail in the scripts as well, not only when compiling. I need some way to debug this. It wouldn't be good to safe 20 seconds for some errors but add 2 hours of extra effort for other errors. But I agree that this needs to be a good compromise and that the status quo possibly is not a good compromise. But just outputting super compact progress and error messages wouldn't be a good compromise either.

One could put some more stuff into log files. Btw.: the cygwin installation messages used to be send to a log file. Someone else redirected them to the console, likely for some good reason.

I see what I can do to make it shorter, but I hope you understand the problem: ignoring data you don't need is (up to a certain limit) much less work than reconstructing data you need but don't have.

**Comment by MSoegtropIMC** [comment]
To give an example: this error (which has been discussed today):
```
+16:38:29 for addon in $COQ_ADDONS
+16:38:29 make_addon_aactactics
+16:38:29 installer_addon_dependency aac
+16:38:29 build_prep_overlay aactactics
+16:38:29 urlvar=aactactics_CI_ARCHIVEURL
+16:38:29 gitvar=aactactics_CI_GITURL
+16:38:29 refvar=aactactics_CI_REF
/cygdrive/c/ci/cygwin64_31227_26923\build\makecoq_mingw.sh: line 421: !urlvar: unbound variable
```
would have been much harder to analyze without the shell exec log. here we can see that urlvar has been set to aactactics_CI_ARCHIVEURL correctly, so we can conclude that aactactics_CI_ARCHIVEURL has not been set. From the error message alone (!urlvar: unbound variable) this is much harder to guess.

**Comment by ejgallego** [comment]
I think that's easy to solve in a few ways. For example the way this works in Dune is that we have a `_build/log` but console output is only detailed for the failing command. Very rarely we need to see the log; that saves 30 seconds of log inspection which is a lot.

So concerning this bug, this is how I would like the windows output to look ideally:
```
[download] Cygwin 4.2
[install] Cygwin 4.2
[download] Coq
[build] Coq
[install] Coq
...
[download] ltac2
[build] ltac2
Error in [build] ltac2:
File foo.ml:12 .... <insert compiler error here>
[build failed, uploading artifacts]
```
and then store the detailed log as an artifact if you need it. For developing / verbose output you can add a variable to the `gitlab` file, then have it by default in dev trees, I do this often.

**Comment by MSoegtropIMC** [comment]
This is deprecated with Coq Platform (which uses opam :-)

**Comment by MSoegtropIMC** [comment]
The PR which removed the old build scripts and switched to Coq Platform was (#13598).
