### ISSUE TITLE
Move Windows test-suite to GitLab CI and get rid of AppVeyor.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#8078]
AppVeyor is now consistently failing on all builds, again! (Mostly 1h timeouts)

@maximedenes How reasonable would it be to move the Windows test-suite to GitLab CI? If I understand correctly, the main limitation is the number of VMs we have access to.

**Comment by maximedenes** [comment]
I don't know, can you measure the current load? We shouldn't count on more VMs from the Inria CloudStack, because we need to create macOS VMs and it will almost exhaust our limited quota.

**Comment by Zimmi48** [comment]
I see. So this would mean adding a new build and putting more load on existing Windows runners.
At this very moment, we have 10 jobs (i.e. 5 pipelines) in the queue on GitLab CI (not started) and they are all Windows. On the other hand, we have 6 jobs in the queue on AppVeyor, and this correspond to the observation that AppVeyor usually finishes after GitLab CI.
How many VMs can we have and how many are we currently using for Windows? I don't think we should have half Windows and half macOS VMs given that we could have 3 Windows jobs for only one macOS job (assuming we keep Travis for running the test-suite on macOS).
Another option would be to stop running the 32 bit packaging job on PRs given that both packaging jobs usually fail at the same time and succeed at the same time.

**Comment by maximedenes** [comment]
How clear is it that appveyor has lower availability than Inria's CloudStack?

**Comment by SkySkimmer** [comment]
On gitlab we could put the test suite and the packaging in the same job without worrying about 1h timeouts right? Is that the only reason they were separate?

**Comment by Zimmi48** [comment]
> How clear is it that appveyor has lower availability than Inria's CloudStack?

It's not fully clear but what I really want to address is the unreliability of AppVeyor and not the availability level. AppVeyor gives us a single job at the time and we have about 5 Windows runners IIUC.

> On gitlab we could put the test suite and the packaging in the same job without worrying about 1h timeouts right? Is that the only reason they were separate?

I believe you are right.

**Comment by Zimmi48** [comment]
Another difference is that the test-suite is currently depending on OPAM but the packaging jobs are not (this difference may be seen as a bad idea though).

**Comment by ejgallego** [comment]
I am not sure I understand the point about OPAM [is done on purpose so we test both setups], but I don't see ourselves abandoning AppVeyor at least until the INRIA CI setup is properly secured.

**Comment by Zimmi48** [comment]
My understanding is that OPAM is simply easier to use to install all the dependencies of the test suite but not reliable enough to generate the packages yet.

**Comment by ejgallego** [comment]
Anyways removing AppVeyor is going to be hard as it is the only free way users can test their development branches on Windows. Same problem applies to Travis.

**Comment by Zimmi48** [comment]
True but in practice how many people except myself have activated AppVeyor on their forks?

**Comment by SkySkimmer** [comment]
I activated it for a while when it was relatively new but it kept spamming failures so I removed it.

**Comment by Zimmi48** [comment]
AppVeyor is always behind and so frequently failing due to timeouts that everybody ignores its output. The consequence is that we can break the test-suite on Windows without realizing it as just happened in #8692. This makes it of very high priority to move the test-suite run on Windows to GitLab CI. Ideally, we would combine add the test-suite run to the Windows package jobs (since there are no hard time limits on GitLab CI and doing so would avoid building Coq twice) but the current setup (on AppVeyor) uses OPAM to install some dependencies of the test-suite (like ounit).

@MSoegtropIMC Do you have an opinion on this?

**Comment by ejgallego** [comment]
> AppVeyor is always behind and so frequently failing due to timeouts that everybody ignores its output. 

I do agree that we should improve its running time; failure frequency doesn't feel so bad I think but I guess I don't have data.

> The consequence is that we can break the test-suite on Windows without realizing it as just happened in #8692.

This was done because the PR was merged without waiting for the CI to complete even if the author warned "I don't know if this works". So IMHO, not the fault of Appveyor. And yes, I do merge quite often without waiting for Appveyor but changes to make are good candidates to wait,

> This makes it of very high priority to move the test-suite run on Windows to GitLab CI. Ideally, we would add the test-suite run to the Windows packaging jobs (since there are no hard time limits on GitLab CI and doing so would avoid building Coq twice) but the current setup (on AppVeyor) uses OPAM to install some dependencies of the test-suite (like ounit).

As of today, and more after seeing the situation with Gitlab Windows workers, note that I oppose to remove Appveyor. When I have a minute I will make it run faster so timeouts are not so much of an issue.

Of course, let's keep improving the GitLab setup.

**Comment by MSoegtropIMC** [comment]
I think having fewer CI providers makes the CI and possibly also Coq easier to maintain as a community - simply because there is less to learn.

Also I think that the Windows testing should concentrate on the Windows Coq we actually distribute - I am not sure what the appveyor version does test. This doesn't mean that we should not also test that the Windows Opam version at least builds. 

I would suggest to make a stream lined Windows build (with pre built Ocaml e.g. as docker image) and run it in phase one and do tests and build of the plugins in step 2 and build the installer as a step 3 (which should be quite quick then).

Of cause my view on this is rather subjective.

**Comment by ejgallego** [comment]
Doing more on Gitlab CI is fine, however Appveyor does provide a very valuable service to contributors in the form of free workers, it also supports Docker on Windows which is not the case on Gitlab. So I think it is going to stay for a while [I will likely switch it to Dune and get OPAM from Docker, that should save 20 mins of the build at minimum].

The Windows build tested in Appveyor is very close to one we try in Gitlab CI IIUC.

**Comment by Zimmi48** [comment]
>Appveyor does provide a very valuable service to contributors in the form of free workers

Not enough of them though. That's was my initial point. We are waiting too long to get CI results from AppVeyor compared to the rest, and thus we get used to not waiting.

>it also supports Docker on Windows which is not the case on Gitlab

That's the first time I hear you say this. Has something changed?

**Comment by ejgallego** [comment]
> Not enough of them though. That's was my initial point. We are waiting too long to get CI results from AppVeyor compared to the rest, and thus we get used to not waiting.

Well, we can make the build faster, or ask Appveyor for sponsorship. The things is that we are not going to shut down a valuable service without a replacement; in fact, given the timeframe we have we should instead shut down the Windows GitLab workers for the reasons we discussed in private.

> That's the first time I hear you say this. Has something changed?

I am not sure I understand what you mean.

**Comment by ejgallego** [comment]
Note that for example we could implement the build cache https://www.appveyor.com/docs/build-cache/ and that should speed up builds quite a bit too.

I am busy so I won't do it this week, but feel free to take on it.

**Comment by ejgallego** [comment]
Sorry guys with the delay on this, #8729 should fix this but a hard-to-debug path problem with the test-suite on windows is delaying it a lot [as I cannot debug windows too efficiently]

**Comment by ejgallego** [comment]
We could implement some temporal countermeasure for now, like disabling the checker or the test suite until we get back; but IMHO removing appveyor is not good until we run test suite on win again.

**Comment by MSoegtropIMC** [comment]
@ejgallego : shall I look into this? Since I am using windows in office (not privately btw.) it might be easier for me to debug issues. Is there already a branch or PR?

**Comment by Zimmi48** [comment]
Didn't you disable the checker already?

**Comment by ejgallego** [comment]
> @ejgallego : shall I look into this? Since I am using windows in office (not privately btw.) it might be easier for me to debug issues. Is there already a branch or PR?

Yup this is indeed #8421 , you will see that we need to pass `coqlib` to makefile however there are some problems as standard bash path tools won't work. Shouldn't be hard to fix tho, but I don't have the cycles now.

> @ejgallego Didn't you disable the checker already?

A recent PR has made the test-suite run the checked on most test cases.

**Comment by SkySkimmer** [comment]
I'm looking into running the (minimally adapted) appveyor script on azure right now.
After 21 iterations I finally got it to run opam ;)

**Comment by ejgallego** [comment]
What's azure? Why not Travis on win?

**Comment by ejgallego** [comment]
Anyways finishing #8421 is going to be for sure less effort.

**Comment by SkySkimmer** [comment]
> What's azure? Why not Travis on win?

More workers AFAICT

Gaëtan Gilbert

**Comment by ejgallego** [comment]
By the way the decision to merge the test-suite PR when we knew it would broke appveyor was maybe not the bst.

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : do you install cygwin with a batchfile upfront (as we do on gitlab)?

**Comment by SkySkimmer** [comment]
See https://github.com/SkySkimmer/coq/blob/azure-pipelines/azure-pipelines.yml

**Comment by MSoegtropIMC** [comment]
@ejgallego : ok, I will take care of this. It might require the kind of tricks I do in my scripts with WFMT (C:\a\b) MFMT (C:/a/b) and CFMT (/cygdrive/c/a/b). Almost all Windows programs can handle WFMT and MFMT but since bash can't (easily) handle WFMT I am usually using MFMT paths when passing them to a MinGW or other Window app from a bash.

**Comment by ejgallego** [comment]
It doesn't require any complicated trick, the issue is relatively simple [how does the coq_makefile part of the test suite locate the installed coqlib] The best way is to use indeed a small OCaml program to compute the right path, but the thing is that the test-suite makefile is quite messy and have some design problems when it comes to path management / subdirs.

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : It doesn't look like you actually install MinGW gcc or binutils, so you might end up using cygwin binutils, but I have no idea what opam does automatically. I have this in my setup script:
```
    -P mingw64-%ARCH%-binutils,mingw64-%ARCH%-gcc-core,mingw64-%ARCH%-gcc-g++,mingw64-%ARCH%-pkg-config,mingw64-%ARCH%-windows_default_manifest ^
    -P mingw64-%ARCH%-headers,mingw64-%ARCH%-runtime,mingw64-%ARCH%-pthreads,mingw64-%ARCH%-zlib ^
```

**Comment by SkySkimmer** [comment]
Mingw is supposed to be installed on the runner but I guess it's not the right part or right version.

**Comment by MSoegtropIMC** [comment]
I would definitely recommend to explicitly install the MinGW cygwin packages in the cygwin you use - for me this proved to be very reliable.

**Comment by SkySkimmer** [comment]
>I have this in my setup script:

Thanks, that seems to work. PR soon.

**Comment by Zimmi48** [comment]
I think so, yes. Azure pipelines have resolved this issue.

**Comment by SkySkimmer** [comment]
We haven't removed appveyor yet though?

**Comment by Zimmi48** [comment]
#9468
