### ISSUE TITLE
setoid_rewrite finds wrong subterm to rewrite in for trivial problems in 8.9+alpha that succeeded in 8.8

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8080]
#### Version

8.9+alpha (02fe76c0c1c3f01c6fb4310dd4450b35f43005da)

#### Description of the problem

This code works in 8.8.1, but fails in somewhat-recent master:
```coq
(* -*- mode: coq; coq-prog-args: ("-emacs" "-R" "." "Crypto" "-R" "../bbv/" "bbv" "-R" "../coqprime/src/Coqprime" "Coqprime" "-top" "Arithmetic" "-R" "." "Top") -*- *)
(* File reduced by coq-bug-finder from original input, then from 4345 lines to 410 lines, then from 376 lines to 34 lines, then from 44 lines to 22 lines, then from 32 lines to 22 lines *)
(* coqc version 8.9+alpha (July 2018) compiled on Jul 2 2018 12:06:11 with OCaml 4.02.3
   coqtop version jagro.cam.corp.google.com:/usr/local/google/home/jagro/Downloads/coq/coq-master,master (02fe76c0c1c3f01c6fb4310dd4450b35f43005da) *)
Require Import Coq.Lists.List.
Require Import Coq.Classes.Morphisms.

Axiom pointwise_map : forall {A B}, Proper ((pointwise_relation _ eq) ==> eq ==> eq) (@List.map A B).
Axiom flat_map_singleton : forall A B (f : A -> B) (xs : list A), flat_map (fun x => cons (f x) nil) xs = map f xs.
Existing Instance pointwise_map.
Goal forall (ls : list (list nat)) ls', map (fun t => flat_map (fun x => x::nil) t) ls = ls'.
  intros.
  setoid_rewrite flat_map_singleton.
  (* Error:
Ltac call to "setoid_rewrite (orient) (glob_constr_with_bindings)" failed.
Tactic failure: setoid rewrite failed: Failed to progress.
*)
```

cc @mattam82

**Comment by JasonGross** [comment]
git bisect says
> 2c7fb44684b26d9c9aea0794b9f0d52088337477 is the first bad commit
> commit 2c7fb44684b26d9c9aea0794b9f0d52088337477
> Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
> Date:   Sat Mar 17 15:23:55 2018 +0100
>
>    Fixes #7011 (Fix/CoFix were not considered in tactic unification).
> 
>     :040000 040000 6d71983a951aad030eeb03643de2306dc9b053c5 72cfbeaa123f8ac5ce3eaa2054c305ac21c1984b M      pretyping
>     :040000 040000 8cc5c05f6b609200c859409f84e81f7de4a91cd4 f5fa5d9f179b2a6adbf58fd8816a67e941561c5e M      test-suite

**Comment by JasonGross** [comment]
cc @herbelin

**Comment by silene** [comment]
This seems bad. The behavior of `setoid_rewrite` should not depend on whether `flat_map` is defined recursively or not.

@herbelin Is there something we can do for 8.9? Should I revert the patch on the branch?

**Comment by herbelin** [comment]
> @herbelin Is there something we can do for 8.9? Should I revert the patch on the branch?

Having `fix` and `cofix` in `unification.ml` like we have all other constructions seems natural but at the same time `unification.ml` is probably going to be progressively deprecated. In any case, no time to investigate why this breaks `setoid_rewrite`, so reverting is ok if you prefer (and thus renouncing also to #7011).

**Comment by silene** [comment]
I am a bit torn on this one. The fact that #7013 caused no issue in the tracked external developments seems to mean that it is not as bad as it seems. So, I might keep the commit around, just so that #7011 stays closed.

Naive suggestion from someone who does not understand the code: What would happen if we were to replace `reduce curenvnb pb opt substn cM cN` by `unify_not_same_head curenvnb pb opt substn cM cN`? Would we get the best of both worlds? (Disclaimer: I am well aware that the suffix `not_same_head` might it look like a very dumb proposal, in the long run.)

**Comment by SkySkimmer** [comment]
>Failed to progress.

Does that mean the issue is not that it fails to find a subterm but rather that it recognizes that flat_map_singleton is a reflexive identity?

**Comment by SkySkimmer** [comment]
With `F := (fun t => flat_map (fun x => x::nil) t)`, it's discovering that `map F ls` is convertible to `flat_map (fun x => cons (F x) nil) ls` and then rewriting that to get back to the start.
Other than putting `Hint Constants Opaque : rewrite` I don't see what can be done about this.
Let's see what the compat impact would be https://github.com/coq/coq/pull/15588

**Comment by maximedenes** [comment]
@gares Do you have an idea of what the "ssreflect rewrite" way would be, to find a trade-off here?

**Comment by gares** [comment]
It does not rewrite under binders, so it would be something like `under map_eq do rewrite flat_map_singleton`. That should work (also we don't call unification, rather evarconv).

I'm no so sure this helps.

**Comment by SkySkimmer** [comment]
We may also consider why it works when we do 
~~~coq
Lemma foo (ls : list (list nat)) (t:list nat) : map id ls = ls /\ flat_map (fun x => x::nil) t = t.
  setoid_rewrite flat_map_singleton.
~~~
in other words why in `choice` https://github.com/coq/coq/blob/b67243eb4ba711e7a7790416fb08fda99c5c0b80/plugins/ltac/rewrite.ml#L1341-L1347 `Identity` is considered a success?

**Comment by SkySkimmer** [comment]
Or alternatively should `rewrite_with` https://github.com/coq/coq/blob/b67243eb4ba711e7a7790416fb08fda99c5c0b80/plugins/ltac/rewrite.ml#L1453 use `progress app` instead of `app`?
