### ISSUE TITLE
Eval ... in performs universe minimization even when this is useless

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#8091]
#### Version

Coq 8.9

#### Description of the problem

The following script displays the issue:
```
Set Universe Polymorphism.
Unset Universe Minimization ToSet.

Inductive prod@{i j} (A : Type@{i}) (B : Type@{j}) := pair : A -> B -> prod A B.

Definition fst@{i j} {A B} (p : prod@{i j} A B) := match p with pair _ _ x _ => x end.

Ltac generate n :=
match n with
| 0 => constr:(Type)
| S ?n =>
  let r := generate n in
  constr:(pair _ _ Type r)
end.

Definition foo := ltac:(let n := generate 1000 in exact n).

Time Eval lazy in fst foo.
```
The last command takes about one second on my machine even though the reduction in itself is instantaneaous. The reason is that Coq is performing universe minimization just for the sake of it.

**Comment by SkySkimmer** [comment]
Isn't it rather that Eval should print the universe context like Check does?

**Comment by andres-erbsen** [comment]
Why does universe minimization with 1000 universes take an entire second to begin with? Perhaps it would be good to make a test case that shows that time even after this issue is fixed?

**Comment by SkySkimmer** [comment]
`generate n` produces something like `4 * n + 2` universes
Whether that makes it more reasonable is up to you.
