### ISSUE TITLE
[documentation] Description of Variant set term looks weird

### ISSUE THREAD

**Issue by jashug** [coq/coq#8129]
In https://coq.inria.fr/distrib/current/refman/proof-engine/tactics.html#coq:tacn.set,
the description of `Variant set term` looks like 
```
Variant set term
Variant This behaves as :n:`set(ident := term)` but :n:`ident` is generated by
Variant Coq. This variant also supports an occurrence clause.
```
(it has a Variant prefix for each line)

This should be an easy fix for someone who understands the documentation system.
@Zimmi48

**Comment by JasonGross** [comment]
Is it missing a(n extra) blank line between the syntax line and the body paragraph?
