### ISSUE TITLE
Illegal application: not coercible

### ISSUE THREAD

**Issue by jashug** [coq/coq#8131]
#### Version

8.8+beta1 (tag V8.8.0) and master 32415df

#### Description of the problem

```coq
Axiom list : Type -> Type.
Axiom inj : forall {T}, T -> list T.
Axiom Admit : forall {T : Type}, T.

Definition foo :=
  let bar : forall T, list _ -> nat := Admit in
  fun T (x : T) => bar _ (inj x).
(*
Illegal application: 
The term "bar" of type
 "forall T : Type@{Top.9}, list T -> nat"
cannot be applied to the terms
 "T" : "Type@{Top.8}"
 "inj x" : "list T"
The 1st term has type "Type@{Top.8}"
which should be coercible to "Type@{Top.9}".
*)
```

Replacing either of the underscores in `foo` with `T` lets the definition go through.
The error message seems wrong, since I would expect just getting a constraint `Top.8 = Top.9`. (or possibly `<=`?)

**Comment by ppedrot** [comment]
Works for me on 1820f40590ec358b40e3a9c444f80c5283e55292, so closing.
