### ISSUE TITLE
Proof diff mode incorrectly renders hypotheses

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8132]
```
coqtop -diffs on
> Goal True. pose 3.
1 subgoal
  n := nat : nat
  ============================
  True
```

**Comment by jfehrle** [comment]
Looks like I have the wrong code for the ":= ..." part of the hypothesis string on the second line below.  This makes the ":= ..." part identical to the ": ..." part (4th line).  Perhaps you can tell me what the correct code is?  I don't know much about this part yet.

FWIW, I didn't know how to produce a hypothesis with ":=" in it until today.

Thanks.

printing/proof_diffs.ml:280
```
    let mid = match body with
    | Some x -> str " := " ++ pp_of_type env sigma ty ++ str " : "
    | None -> str " : " in
    let ts = pp_of_type env sigma ty in
    let rhs_pp = mid ++ ts in
```

**Comment by ejgallego** [comment]
It is just a regular term, you can print it in the usual way.

**Comment by jfehrle** [comment]
Ah, pretty trivial after I dug into it--and after a couple false starts.

**Comment by tchajed** [comment]
Why is this high priority? The worst it can do is confuse a user.

**Comment by ejgallego** [comment]
Clearly we can't release with such a critical printing bug

**Comment by Zimmi48** [comment]
If we can't release, then the right priority is "blocker". I believe the "high priority" assessment is the right one though, given that this will only happen if a user uses the `-diffs` option.

**Comment by gares** [comment]
Not showing the body of a let-in makes the system unusable, IMO.
Sure you can turn this feature off, but shipping a broken new feature is not particularly nice.

Anyway there is plenty of time to fix that, I raise the priority so that we don't forget doing it.

**Comment by maximedenes** [comment]
It's been agreed in the past that it's up to the RM to raise priority to blocker. So until we see what @silene wants to do, let's stick with high. This is theoretical anyway, since I'm sure we can fix it quickly.
