### ISSUE TITLE
CoqIDE displays diffs even if nobody told it to do so

### ISSUE THREAD

**Issue by gares** [coq/coq#8146]
The CHANGES file says:
```
- coqtop and coqide can now highlight the differences between proof steps
  in color. This can be enabled from the command line or the
  "Set Diffs on|off|removed" command. Please see the documentation for
  details.  Showing diffs in Proof General requires small changes to PG
  (under discussion).
```
but here I see the diffs and I did not pass any options, nor write `Set...` in my document.

**Comment by ppedrot** [comment]
#8141 fixes this.

**Comment by gares** [comment]
Also, the syntax is `Set Diffs "on"` (the argument is a string).

**Comment by jfehrle** [comment]
> Also, the syntax is Set Diffs "on" (the argument is a string).

Yeah, the command requires quotes.  The OS command argument doesn't require them.  I'll adjust the Changes to reflect this.
