### ISSUE TITLE
CoqIDE queries are completely broken when Diff option is deactivated

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#8165]
#### Version

8.9

#### Description of the problem

None of CoqIDE queries (as found in the Query menu) work after evaluating `Set Diffs "off"`. They all fail complaining about the fact the proof is not focussed. It seems that #8141 solves this as a unexpected side-effect.

**Comment by ejgallego** [comment]
So this is solved now?

**Comment by ppedrot** [comment]
I guess so...
