### ISSUE TITLE
Documentation doesn't explain clearly enough how to use options and the difference between flags and options.

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8178]
#### Description of the problem

The command `Set Printing Compact Contexts on." is documented but not accepted in Coqtop.  Should be made to work or removed from the doc.  If the option is removed, references to it in the comments before Printer.bld_sign_env and pr_context_limit_compact and use of the option value in Printer.should_compact should also be removed.

https://coq.inria.fr/distrib/current/refman/proof-engine/vernacular-commands.html?highlight=compact#coq:opt.printing-compact-contexts

```
Unnamed_thm < Set Printing Compact Contexts on.
Toplevel input, characters 0-33:
> Set Printing Compact Contexts on.
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning: There is no option Printing Compact Contexts on.
[unknown-option,option]
```

**Comment by Zimmi48** [comment]
The correct way to call the option is `Set Printing Compact Contexts.`
I don't see the "on" part in the documentation you linked.

**Comment by jfehrle** [comment]
OK, fair enough, not a bug in the option.

On the other hand, I've read parts of the doc about setting flags and options more than a couple times, and they're still surprisingly confusing for what should be a simple topic.  The doc doesn't usefully define the differences between flags and options.  The syntax for setting them is identical (or at least confusingly similar).  Are flags predefined (not user-defined)?  And if so, shouldn't the doc have a flags index at the beginning of the document?  Or have a combined index of flags and options and identify which are which-if it really matters.

The general documentation for setting an option **only** shows the following form.  It does not show the form Set _option_ at all (which **is** shown for flags).

![image](https://user-images.githubusercontent.com/1253341/43348002-e1e6e15a-91c5-11e8-8200-4d06a7a0b5c2.png)

I think might be friendlier to show _Set_unset_ with a hyperlink to the full syntax (Local, Global, Export) instead of _Option_ in all the option boxes.

![image](https://user-images.githubusercontent.com/1253341/43348285-55939f98-91c7-11e8-8bec-eb90f83d586e.png)

It would also help if the parsing and error messages were a bit friendlier (less misleading), for example it sure would help the user to say that the "on" is extraneous.

```
> Set Printing Compact Contexts on.
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning: There is no option Printing Compact Contexts on.
[unknown-option,option]
```

or that something is missing:

```
> Set Printing Compact.
> ^^^^^^^^^^^^^^^^^^^^^
Warning: There is no option Printing Compact. [unknown-option,option]
```

Do you think that's worth fixing anytime soon?

**Comment by herbelin** [comment]
About your last point, do you mean being able to provide messages like `Did you mean "Set Printing Compact Contexts"`? That would be cool indeed.

**Comment by Zimmi48** [comment]
Reopening as a more general documentation issue.

**Comment by jfehrle** [comment]
> do you mean being able to provide messages like `Did you mean "Set Printing Compact Contexts"`?

That's one possibility.  What's feasible depends on how the grammar is available programmatically and how hard it is to tweak the parser's error handling.  Perhaps some of the code used for the OCaml compiler's similar feature could be adapted (e.g. picking the most similar strings).

Other possibilities include:
- For input such as `Set Printing.` or `Set Printing ?.` or `Help Set Printing.`, show the possible valid completions (there are about 20).
- For input such as `rewrite ?.`, show the syntax alternatives with non-terminal symbols, e.g. `rewrite <term>`, `rewrite <- <term>`, `rewrite <term> in <clause>`.  (This would have some interesting usability questions to consider, e.g. what non-terminal symbols are not expanded.  Also the grammar in the code may not be written in the most understandable form for the user.)

Autocomplete, akin to the Linux command line, may not be not helpful enough to be worth the effort.  Plus there would likely be significant differences in implementation/behavior across the various UIs (coqtop, CoqIDE and PG).

(Rambling: It would be nice to have a line-editing function akin to the Linux shell in coqtop--but do enough people use coqtop to make it worth considering?)

**Comment by jfehrle** [comment]
Anton--thanks, very handy tool!

**Comment by Zimmi48** [comment]
Note that @cpitclaudel's company-coq Emacs minor mode provides auto-completion and it was one of the motivation for the new format of the reference manual (for machines to be able to extract information from it more easily).

**Comment by herbelin** [comment]
> I sometimes use coqtop with rlwrap like so: $ rlwrap coqtop

And to support OCaml-based software, I'm using `ledit` (*), but `rlwrap` is very good indeed.

(*) with `-x`, `-u` and `-h` options (which I believe should be the default).

**Comment by jfehrle** [comment]
I plan to work on this soon.  Here's what I have in mind.  @Zimmi48 et al, let me know if this is agreeable before I do the work.

- Revise description of flags and options: flags are boolean and are used with `Set`, `Unset` and `Test`.  options have non boolean values and are used with `Set` and `Test`
- The `option index` has both flags and options.  Check that they are clearly distinguished.  Maybe rename the index for clarity.
- The following is a flag.  The minimal change is that It should say `flag`.  But we should discuss whether seeing `Option` and `Flag` everywhere is best for users.  (As I said above) If we show those words, they should link back to the explanation that one takes Set/Unset/Test and the other takes Set/Test.  Or maybe better just to show `Set|Test` instead of `Option`.
![image](https://user-images.githubusercontent.com/1253341/44942337-39149400-ad7c-11e8-9d9d-1be2392bc636.png)
- Fix the following issues with showing options:
= No way to use standard syntax metacharacters `[` and `]` in the description (Sphinx error)
= No way to link to `Diffs` in the text because it wants to match the entire description string rather than just `Diffs`

![image](https://user-images.githubusercontent.com/1253341/44942258-cacfd180-ad7b-11e8-98c3-1ab915deab52.png)

- Look at improving the messages for unknown options.  (OK, that's not doc.)

**Comment by Zimmi48** [comment]
That would be super cool @jfehrle :heart: 
Thank you so much for deciding to tackle this. We (@maximedenes and I) have noticed this lack of distinction between flags and options during the Sphinx migration later phases and we were bothered but there was so much to do that we couldn't tackle it.

**Comment by jfehrle** [comment]
> Note that @cpitclaudel's company-coq Emacs minor mode provides auto-completion and it was one of the motivation for the new format of the reference manual (for machines to be able to extract information from it more easily).

What does it extract?  If it's merely a list of valid options and commands, that might be better done by a command that prints that info.  Surely it would be simpler to extract information from that command's output than from the .rst or .html files.

**Comment by Zimmi48** [comment]
It can also print the corresponding doc, so it makes sense to use the .rst files I guess.

**Comment by jfehrle** [comment]
I'd like to enhance the syntax notation a little.  I need Antlr, and not just the runtime.  It was not immediately obvious from http://www.antlr.org/download.html how I do that for Python.  Do you know?  I've already installed `antlr4-python3-runtime` with pip3.

I can add this info to doc/README.md

**Comment by Zimmi48** [comment]
@jfehrle #8439 fixed this, right?

**Comment by jfehrle** [comment]
#8439 covered most of it.  Still a couple of good ideas for future improvements here, though.
