### ISSUE TITLE
Local inductives are imported by Import

### ISSUE THREAD

**Issue by tchajed** [coq/coq#8186]
#### Version

```text
The Coq Proof Assistant, version 8.9+alpha (July 2018)
compiled on Jul 26 2018 9:23:02 with OCaml 4.06.0
```

commit 85d5f45d7a5374

#### Operating system

macOS 10.13.6

#### Description of the problem

`Local Inductive T` in a module should ensure that importing the module does not make `T` or its constructors available (they still need to be qualified). This is what the [documentation for `Import`](https://coq.inria.fr/refman/language/gallina-extensions.html#coq:cmd.import) says and what I'd expect, and it's what happens for definitions and theorems.

As a result there's no way to avoid polluting the namespace with inductive names when importing.

In addition, for records the projections are also not made local. This is at least avoidable by defining the projections manually as `[Local Definition]`s, but I think it should be fixed as well.

```coq
Module M.
  Local Inductive T := mkT.
End M.

Module ImportM.
  Import M.
  (* both of these should fail; these should both require qualification, specifically
     M.T and M.mkT *)
  Check T.
  Check mkT.
End Import M.
```

**Comment by Zimmi48** [comment]
@maximedenes has been interested in scoping lately so might want to take this.
