### ISSUE TITLE
Refinement and universe polymorphism

### ISSUE THREAD

**Issue by cstolze** [coq/coq#8193]
#### Description of the problem:
The refiner seems to have a problem with flexible universe levels.

```
Definition id (A : Type) (x : A) : A := x.

Check (id (forall A, _) id). (* works *)

Check (id _ id).
(*
Error:
The term "id" has type "forall A : Type, A -> A"
while it is expected to have type "?A"
(unable to find a well-typed instantiation for "?A": cannot ensure that
"Type@{Top.1+1}" is a subtype of "Type@{Top.1}").
*)
```

**Comment by JasonGross** [comment]
I am inclined to close this bug as invalid.  Both `Check`s go through fine if you `Set Universe Polymorphism`, and, as currently given, the first `Check` cheats with eta-expansion and gives `id (forall A : Type, A -> A) (fun A : Type => id A)` with your eta-expanded `A : Type` in a strictly lower universe than `id`.

**Comment by mattam82** [comment]
Indeed, id _ id cannot typecheck in non-polymorphic mode and in the first example it coerces to a lower instance of id
