### ISSUE TITLE
Module signature components do not match error sometimes prints ?? instead of types

### ISSUE THREAD

**Issue by tchajed** [coq/coq#8206]
#### Version

```
The Coq Proof Assistant, version 8.9+alpha (July 2018)
compiled on Jul 26 2018 9:23:02 with OCaml 4.06.0
```

commit 68447a7c22

#### Operating system

macOS 10.13.6

#### Description of the problem

It seems like if a module type mismatch has the following properties, the type prints as "??" instead of being properly printed:
- the module being defined or its type have module parameters
- the type in question involves a definition from a module parameter
- the parameter appears in the type position of a binder
- and the binder's argument is actually used dependently in the function type.

I tried several simpler examples and the types printed correctly.

Note that this bug is triggered for the expected and actual types independently.

```
Module Type Args.
  Axiom T:Type.
End Args.

Module Type T (A:Args).
  Axiom n: forall (x:A.T), x <> x.
End T.

Module I (A:Args) <: T A.
  Definition n : forall (x:A.T), x = x := fun x => eq_refl.
End I.
(* fails correctly, but error message is:
Error: Signature components for label n do not match: expected type
"??" but found type "??".
 *)
```

**Comment by samuelgruetter** [comment]
This is still happens in Coq 8.11.0.

It's a bit unfortunate because we use module signature checks for teaching Coq, to make sure students didn't accidentally change the lemmas they're proving.
Here's our minimized example:

```coq
(* This is in a file the students don't edit: *)
Require Import Coq.Arith.Arith.
Module Type Sig.
  Parameter add: nat -> nat -> nat.
  Axiom homework: forall (a b: nat), add a b = add b a.
End Sig.

(* This is in a file the students edit: *)
Module Impl.
  Definition add(a b: nat) := Nat.add a b.
  (* Student fixes a:=0 to see if they can solve this simpler case,
     and forget to change it back. *)
  Theorem homework: forall (a b: nat), add 0 b = add b 0.
  Proof. intros. unfold add. rewrite Nat.add_0_r. reflexivity. Qed.
End Impl.

(* This is in a file the students don't edit, but if they run
   "make" on their computer, this file is compiled, and the
   students should understand the error message. *)
Module Checking.
  Module M : Sig := Impl.
(* Error: Signature components for label homework do not match: expected type "??" but found type "??". *)
```

/cc @andres-erbsen

**Comment by tchajed** [comment]
To add to what @samuelgruetter said, more specifically [FRAP](http://adam.chlipala.net/frap/) uses module types as signatures for what a homework solution should be, which seems like an important use case.

**Comment by JasonGross** [comment]
Note that the original example now works in master (92a294ca53752b61b0270a719826ffc759a25e8d) , but @samuelgruetter 's example still gives `??`.

**Comment by ppedrot** [comment]
Here is a self-contained reduct of @samuelgruetter's bug.
```
Module Type Sig.
  Parameter add: nat -> nat -> nat.
  Axiom homework: forall (a b: nat), add a b = add b a.
End Sig.

Module Impl.
  Definition add(a b: nat) := plus a b.
  Axiom homework: forall (a b: nat), add 0 b = add b 0.
End Impl.

Module M : Sig := Impl.
```
The problem is that the function `Namegen.visible_ids` tries to compute the set of names appearing in the type of `Impl.homework`, but the function `Impl.add` has no user-facing name at the time of the invocation. Interestingly, the `Not_found` exception is caught when in debug mode or toplevel, which indicates an intent of trying to work around the issue. I don't know why we don't merely ignore the name in this case...
