### ISSUE TITLE
Nix build doesn't mirror that in nixpkgs

### ISSUE THREAD

**Issue by siddharthist** [coq/coq#8227]
The `.nix` file in this repo is great and makes my life a lot easier, but there is one pain point: it doesn't closely match [the one in nixpkgs](https://github.com/NixOS/nixpkgs/blob/61bd4d7225742469ed0ada4b4fa27e1559b60cbc/pkgs/applications/science/logic/coq/default.nix).

For instance, the latter [defines some passthru variables](https://github.com/NixOS/nixpkgs/blob/61bd4d7225742469ed0ada4b4fa27e1559b60cbc/pkgs/applications/science/logic/coq/default.nix#L39-L40) that aren't present in the one in this repo:
```coq
    inherit coq-version camlp5;
    inherit (ocamlPackages) ocaml findlib num;
```
and [does something involving `findlib`](https://github.com/NixOS/nixpkgs/blob/61bd4d7225742469ed0ada4b4fa27e1559b60cbc/pkgs/applications/science/logic/coq/default.nix#L131).

Is there any reason for these builds to be different? Is there a way of sharing code between these two repos so that they are as close as possible? 

cc: @Zimmi48

**Comment by siddharthist** [comment]
As a temporary workaround, one can use (something like) the following:
```nix
  coq = {
    "8.7"    = pkgs.coq_8_7;
    "8.8"    = pkgs.coq_8_8;
    "master" = with pkgs;
      (callPackage (fetchTarball "https://github.com/coq/coq/tarball/master") { }).overrideAttrs
        (oldAttrs: {
          # See https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/science/logic/coq/default.nix
          camlp5 = ocamlPackages.camlp5_strict;
          inherit (ocamlPackages) ocaml findlib num;
          coq-version = "8.9-alpha";
        });
  }."${coq-version}";
```

**Comment by Zimmi48** [comment]
- [x] PR submitted which adds `ocamlPackages` to the nixpkgs derivation (more general).
- [x] The postInstall step involving findlib is now also in Coq's `default.nix`.
- [ ] Provide a `coq-version` attribute. I'm not yet clear on what we want to put in there because I'm not sure what is the use case. In your example you put `8.9-alpha` but the nixpkgs version would be only `8.9`...

**Comment by vbgl** [comment]
The `setupHook` attribute is missing too.

The `coq-version` attribute currently has two uses in `nixpkgs`: automatically populate the `COQPATH` environment variable (through the setup-hook); decide whether a package is available for a particular version of Coq.

**Comment by Zimmi48** [comment]
Indeed, I would be glad to have a setup hook (it would avoid this kind of things: https://github.com/coq-community/lemma-overloading/blob/161ea51d52556ca6f78d7f76554492209dbdd112/default.nix#L23). I just doesn't understand these things well yet.
