### ISSUE TITLE
do n constructor takes O(n^2) time

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#8238]
#### Version

~~~~~
<!-- You can get this information by running `coqtop -v`. -->
The Coq Proof Assistant, version 8.8.1 (July 2018)
compiled on Jul 5 2018 7:25:50 with OCaml 4.06.0
~~~~~

#### Operating system

Arch Linux, up to date as of this week. `Linux ashryn 4.17.13-arch1-1-ARCH #1 SMP PREEMPT Mon Aug 6 23:06:31 UTC 2018 x86_64 GNU/Linux`

#### Description of the problem

Creating n constructors using tactics takes O(n^2) time. The proof object is also of quadratic size, so this may not be fixable. Nevertheless, this essential problem comes up with Hoare-style program logics where each econstructor applies the proof rule for one step in the program, so speedups for any limited form of this pattern would be very useful.

~~~~~
Fixpoint fin (n : Datatypes.nat) : Type :=
  match n with
  | O => unit
  | S n => option (fin n)
  end.

Goal fin 2000. Time repeat constructor. (* 4s *) Time Qed. (* 6s *)
~~~~~

**Comment by JasonGross** [comment]
I'm inclined to mark this bug as invalid.  Here is an example where `do n constructor` is linear time:
```coq
Goal list unit.
  Time do 100 (constructor 2; [ constructor | ]). (* Finished transaction in 0.014 secs (0.015u,0.s) (successful) *)
  Undo. Time do 1000 (constructor 2; [ constructor | ]). (* Finished transaction in 0.175 secs (0.171u,0.004s) (successful) *)
  Undo. Time do 10000 (constructor 2; [ constructor | ]). (* Finished transaction in 1.037 secs (1.02u,0.02s) (successful) *)
```
So it seems like what you are hitting is "quadratically-sized proof terms take quadratic time to build, even even when there is enough duplication that an easy linear-size representation exists".  Perhaps you want to rename the bug to something like that?

**Comment by andres-erbsen** [comment]
My bad, I should have tried to minimize the example harder. I am not yet desperate enough to ask for speedups based on sharing of representations of duplicated subterms, so I'm closing this.
