### ISSUE TITLE
Feature Request: way to prove (A /\ B /\ ...) in linear time

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#8239]
I would like to have a way to prove goals of the form `A /\ B /\ C /\ ...` in linear time, assuming each clause can be proven in constant time, but without assuming anything about the structure of the clauses. Concretely, I would like to solve the goals generated by the following script:

~~~~~
n = 10000
print("Goal forall" + " ".join("(P%d : Prop) (p%d : P%d)" %(d,d,d) for d in range(n)) +
        ",\n" + "/\\".join("P%d"%d for d in range(n)) +
        ".\n Time (* YOUR PROOF HERE *) intros; repeat (split || assumption). Time Qed.")
~~~~~

This seems like an obvious thing to be able to do, but after pondering over it for a while, I do not see a way. For particular `A`, `B`..., a reflective procedure that understands them could probably be executed and checked in linear time, but a general (and hopefully more lightweight) solution would be very appreciated.

**Comment by andres-erbsen** [comment]
Here is an idea, based on https://github.com/coq/coq/issues/8238#issuecomment-412354756

~~~~~
Inductive pfl :=
| nil
| pf (P : Prop) (_ : P) (_ : pfl).
Fixpoint pflt (pfs : pfl) :=
  match pfs with
  | nil => True
  | pf P _ pfs => P /\ pflt pfs
  end.
Fixpoint pflv (pfs : pfl) : pflt pfs :=
  match pfs with
  | nil => I
  | pf P p pfs => conj p (pflv pfs)
  end.


Goal forall (P1 : Prop) (p1:P1) (P2:Prop) (p2:P2) (P3:Prop) (p3:P3), P1 /\ P2 /\ P3 /\ True.
  intros.
  refine (pflv (pf _ _ (pf _ _ (pf _ _ nil)))); assumption.
  Set Printing All.
  Show Proof.
Defined.
Eval cbv [Unnamed_thm] in Unnamed_thm.
Eval cbv in Unnamed_thm.
~~~~~

**Comment by ppedrot** [comment]
I don't think it is up to the Coq devs to come up with efficient ways to solve user-specific problems, but to the external library devs. Furthermore it seems you solved your problem yourself, so I'd personally close this report. Feel free to reopen it if you want to argue against.

**Comment by andres-erbsen** [comment]
I'm fine with it being closed, but as-is the example I gave does not actually run in linear time.

**Comment by cpitclaudel** [comment]
> I don't think it is up to the Coq devs to come up with efficient ways to solve user-specific problems

I agree, except when there are no library-side solutions.  Are there any here?

I created https://github.com/coq/coq/issues/11111 as a related issue.
