### ISSUE TITLE
omega doesn't correctly use posed hypotheses

### ISSUE THREAD

**Issue by emarzion** [coq/coq#8267]
#### Version
8.8.0

#### Operating system
Windows Subsystem for Linux (Ubuntu 16.04) on Windows 10

#### Description of the problem

I recently upgraded from 8.7.2 to 8.8.0 and suddenly I'm encountering issues using the `omega` tactic when the necessary hypotheses have been introducted using `pose`.  For instance:

```
Require Import Omega.

Variable n : nat.
Hypothesis n_nz :  n <> 0.

Lemma n_pos : n > 0.
Proof.
  pose n_nz.
  Fail omega. (* Omega can't solve this system *)
```

**Comment by Zimmi48** [comment]
Thanks for the report. There were a few improvements made to the `omega` tactic in 8.8 (#768, #876), so the regression could have been introduced there.
As an alternative, you can use `lia` (which is anyways going to be the recommended replacement in the next version). It solves your goal in both Coq 8.7 and 8.8.

**Comment by pi8027** [comment]
`omega` has been removed in favor of `lia`, and `lia` works fine in this case. Let's close.
