### ISSUE TITLE
Modifier configuration take precedence on accelerator keymap since Coq 8.6

### ISSUE THREAD

**Issue by newca12** [coq/coq#8269]
#### Version

8.8.1

#### Operating system

macOS 10.13.6

#### Description of the problem

```coq
Require Import Arith List.

Fixpoint insert (cmp: nat -> nat -> bool)(x : nat)(l : list nat) :=
  match l with
    nil => x::nil
	| a ::l' => if cmp x a then x::a::l' else a::insert cmp x l'
  end.

Fixpoint sort (cmp : nat -> nat -> bool) (l : list nat) :=
  match l with nil => nil | x :: l' => insert cmp x (sort cmp l') end.

Definition sort_increasing := sort leb.

Compute sort_increasing (3::4::2::1::11::nil).
```
 is displayed like this with coqIde 8.8.1

```
     = @cons nat (S O)
         (@cons nat (S (S O))
            (@cons nat (S (S (S O)))
               (@cons nat (S (S (S (S O))))
                  (@cons nat
                     (S
                        (S
                           (S
                              (S
                                 (S
                                 (S
                                 (S
                                 (S (S (S (S O)))))))))))
                     (@nil nat)))))
     : list nat
```
and like this with coqIde 8.8.0
```
     = 1 :: 2 :: 3 :: 4 :: 11 :: nil
     : list nat
```

**Comment by Zimmi48** [comment]
I'm on Linux, not macOS, but I cannot reproduce what you are seeing, are you sure you didn't accidentally changed some of the printing options in the View menu? Because this is what you get if you activate "Display all low-level content" (you may want to check also what the keyboard shortcut for this is, to make sure you didn't actually hit it).

**Comment by newca12** [comment]
Oups, sorry. You are right.
shift + alt + L is the usual keyboard shortcut for the pipe character on macOS.
Issue can be closed. Thank for your fast answer.

**Comment by Zimmi48** [comment]
Maybe we should consider changing this default keyboard for macOS users though, WDYT?
I have no idea how this would be done but maybe @ppedrot knows.

**Comment by newca12** [comment]
I dig this a bit and interestingly it turn out to be a real bug.
A correct binding file for MacOS exist : https://github.com/coq/coq/blob/master/ide/MacOS/default_accel_map
This file is written as is (with Primary unresolved) in ~/Library/Application Support/coq/ on the first close of the coq application.
```
...
(gtk_accel_path "<Actions>/Templates/Definition" "<Primary><Shift>d")
...
(gtk_accel_path "<Actions>/View/Display all low-level contents" "<Shift><Control>l")
```
Then the file is rewritten on the second close of the coq application (with Primary resolved **but wrong bindings**)
```
...
(gtk_accel_path "<Actions>/Templates/Definition" "<Shift><Control>d")
...
; (gtk_accel_path "<Actions>/View/Display all low-level contents" "<Shift><Alt>l")
; (gtk_accel_path "<Actions>/View/Display all basic low-level contents" "<Shift><Alt>a")
```

**Comment by newca12** [comment]
Some more informations : 
The bug was introduced with Coq 8.6. All subsequent versions are affected. **Coq 8.5pl3 is OK**.

Steps to reproduce : 

1. rm -rf ~/Library/Application\ Support/coq/

1. Launch Coq 8.6+ and close it to generate ~/Library/Application\ Support/coq/coqide.keys and ~/Library/Application\ Support/coq/coqiderc

1. ```cat ~/Library/Application\ Support/coq/coqide.keys | grep low```show bindings are OK
```
(gtk_accel_path "<Actions>/View/Display all low-level contents" "<Shift><Control>l")
(gtk_accel_path "<Actions>/View/Display all basic low-level contents" "<Shift><Control>a")
```
4. Again Launch Coq 8.6+ and close it. Now ```cat ~/Library/Application\ Support/coq/coqide.keys | grep low``` **show that coqide.keys is rewritten with wrong bindings**
```
; (gtk_accel_path "<Actions>/View/Display all low-level contents" "<Shift><Alt>l")
; (gtk_accel_path "<Actions>/View/Display all basic low-level contents" "<Shift><Alt>a")
```

The same procedure with Coq 8.5pl3 show correct bindings after step 4. (coqide.key is also rewritten but with good bindings)

**Comment by herbelin** [comment]
What you get in the second case is more than a change of bindings. It is a deactivation of the line (there is a `;`).

The change of behavior apparently comes from 7df076130 which propagates to the "AccelMap" hard-wired preferences for the menus. But I don't understand well enough gtk code to know when these hard-wired preferences are used (in particular, when is the command `pref#connect#changed ~callback:cb` supposed to be called?).

What might be involved also is a competition between the file `coqiderc` and the file `coqide.keys`. At first use, there is no file, so `coqiderc` is created with field `modifier_for_display = "<Alt><Shift>"` and `coqide.keys` is created with modifiers `<Shift><Control>`. At second use, `coqiderc` is found and its binding is used and propagated to `coqide.keys`.

**Comment by newca12** [comment]
Indeed, I have compiled Coqide from sources and removing thoses lines https://github.com/coq/coq/blob/master/ide/preferences.ml#L339-L343 fix the issue.
Seem the callback are called after the preferences are loaded so the menu are indeed loaded with hard wired preferences that are then saved on quit and that's why coqide.keys is badly modified.

**Comment by newca12** [comment]
I just noticed that this behaviour is the same for all platforms. Please remove macOS Label.
Whatever is the configuration defined in coqide.keys, the modifier configured in coqiderc will take precedence. I guess this is annoying for user of all platforms that want to customize their menu and this also make shortcuts on MacOS barely usable with the default settings and no proper configuration possible. Since this new behaviour come with Coq 8.6, I am a bit surprise to not see open issue about that. That has now been done :-)

**Comment by Zimmi48** [comment]
@newca12 If the solution is as simple as removing these lines, could you open a PR doing this? It will be easier to get @ppedrot's attention this way.

**Comment by newca12** [comment]
@Zimmi48 removing these lines will remove the "dynamic modifier" feature that allow us to change the modifiers without restarting CoqIDE. A lesser evil from my point of view but I guess not everyone will agree with this.

**Comment by Zimmi48** [comment]
OK thanks for the explanation. Indeed, it would be better if a solution could be found without this drawback...
