### ISSUE TITLE
Implementing primitive floats (binary64 floating-point numbers)

### ISSUE THREAD

**Issue by erikmd** [coq/coq#8276]
Dear Coq developers,

We open this issue to keep you informed of some on-going work on implementing primitive floats in Coq.

This work was done by Guillaume Bertholon (@Sakarah) during his internship with Pierre Roux (@proux01) and myself (@erikmd).

The current development can be found here: https://github.com/validsdp/coq/tree/primitive-floats
(it compiles with `./configure -native-compiler no`  (`native_compute` support not yet implemented))

We briefly summarize below the motivations of this work and the design questions we already started tackling:

### Motivations

We'd like to increase Coq computing power to be able to handle complex algorithms in validated numerics (and use them in proofs by reflection). We already see a few developments that could benefit from such primitive floats:
- http://coq-interval.gforge.inria.fr/
- https://github.com/validsdp/validsdp
and this would more generally open the way to Coq-verified versions of algorithms such as the ones implemented in:
- http://www.ti3.tu-harburg.de/rump/intlab/

Currently, the above Coq developments emulate floating-point computations by relying on integer computations. Such operations appear to be about three order of magnitudes slower than primitive FPU operations.

### Workflow

I briefly discussed with @maximedenes at the Coq IW, and he later advised me to base our work upon his primitive-integers implementation (https://github.com/maximedenes/coq/tree/primitive-integers)

Here are the main steps we followed:
1. define a minimal working interface for the IEEE 754-2008 binary64 format
1. define a fully-specified spec w.r.t. a minimal excerpt of Flocq (http://flocq.gforge.inria.fr/)
1. prepare a compatibility layer that could later be added to Flocq
1. hence the choice of the specification type presented below
1. implementation for `compute` and `vm_compute`, at the OCaml and C levels
1. run some benchmarks.

### Focus on the specification type for floats

We discussed with Guillaume Melquiond (@silene) the design of this type and tested several versions.

The current version (file EmulatedFloat.v) is a trade-off. To sum up, it is the same as the `full_float` type in Flocq (file IEEE754/Binary.v) except that NaN payloads are ignored:

```
Inductive emulated_float :=
  | E754_zero : bool -> emulated_float
  | E754_infinity : bool -> emulated_float
  | E754_nan : emulated_float
  | E754_finite : bool -> positive -> Z -> emulated_float.
```

Specification of the operations is then mostly borrowed from Flocq.

Subtle points identified:
- NaNs: their payload is hardware-dependent, meaning some hardware could produce one value and another a different one, which could easily lead to a proof of False
- comparison: do not use IEEE-754 comparison for Leibniz equality (doesn't distinguish +0 and -0 whereas 1/+0 = +oo and 1/-0 = -oo are easily distinguished)
- primitive int63 are unsigned, this does require some care when using them as interface.

@silene also suggested two different versions:

(1)
```
Inductive foo_float : Set :=
  | NaN | PInf | NInf | PZero | NZero
  | Finite (s : bool) (m : positive) (e : Z) : foo_float.
```

and
(2)
```
Inductive foo_float : Set :=
  | NaN | PInf | NInf | PZero | NZero
  | Finite (s : bool) (mh ml e : int31) : foo_float
```

which could be adapted to
(2a)
```
Inductive foo_float : Set :=
  | NaN | PInf | NInf | PZero | NZero
  | Finite (s : bool) (m e : int63) : foo_float
```

but we did not chose these at the current stage of the implementation.
(2) would make the addition more painful to specify with int31/63 (due to wild shiftings).
(1) could be chosen later to avoid boxing/allocating for values +/- Inf and Zero.

Although these may offer performance gains in conversions, this type is expected to be used for specification rather than effective computations.
Maybe another interface should be designed for effective computations (but do we really need it? We already have efficient comparison, is_{nan,zero,infinity} as well as mantissa/exponent extraction and conversion functions).

### Primitive operations

The following primitive operations are implemented (file FloatNative.v):

- `opp : float -> float`
- `abs : float -> float`
- `compare : float -> float -> option comparison`
- `mul, add, sub, div : float -> float -> float`
- `sqrt : float -> float`
- `of_int63 : int -> float`  (rounds value if necessary)
- `normfr_mantissa : float -> int`
  (if input has absolute value in [0.5, 1), return its mantissa, sign is ignored)
- `frshiftexp : float -> float * int`
  (`frshiftexp f` gives `(m, e)` with |m| in [0.5, 1) and f = m * 2^(e-shift))
- `ldshiftexp : float -> int -> float`  (ldshiftexp f e = f * 2^(e-shift))

Anything missing?

The last four operations enable to implement `Prim2EF : float -> emulated_float`
and `EF2Prim : emulated_float -> float`(file FloatOps.v),
used to write the axioms to specify primitive operations (file FloatAxioms.v).

### Benchmarks

We ran some benchmark on a matrix Cholesky decomposition
(file posdef_check.v in https://github.com/validsdp/validsdp/tree/posdef_check)

We roughly observed a speedup of a factor about 50 compared to operations emulated with primitive integers in Coq master. Note that @maximedenes's primitive-integers already offered a speedup of about a factor 2 compared to master.

| matrix    | prim-int | prim-float | speedup |
| --------- | --------:| ----------:| -------:|
| 25 × 25   | 0.051 s  | 0.007 s    | 7.29    |
| 50 × 50   | 0.304 s  | 0.020 s    | 15.20   |
| 75 × 75   | 1.394 s  | 0.051 s    | 27.33   |
| 100 × 100 | 2.738 s  | 0.102 s    | 26.84   |
| 125 × 125 | 4.525 s  | 0.184 s    | 24.59   |
| 150 × 150 | 7.590 s  | 0.299 s    | 25.38   |
| 175 × 175 | 12.008 s | 0.474 s    | 25.33   |
| 200 × 200 | 18.658 s | 0.709 s    | 26.32   |
| 225 × 225 | 25.488 s | 0.967 s    | 26.36   |
| 250 × 250 | 35.593 s | 1.381 s    | 25.77   |
| 275 × 275 | 47.634 s | 1.778 s    | 26.79   |
| 300 × 300 | 62.790 s | 2.345 s    | 26.78   |
| 325 × 325 | 79.595 s | 2.931 s    | 27.16   |
| 350 × 350 | 99.556 s | 3.620 s    | 27.50   |

### Other question

Pretty-printing and parsing of floating-point values raises interesting questions. An easy solution would be to parse/print floats in hexadecimal format (e.g., `0xcp-3`) but this is ugly and perfectly unreadable for humans. A decimal format (e.g., `1.5`) would be more readable.
It is known that using 17 digits while printing binary64 guarantees `parse \circ print : float -> float` to be the identity although `parse` is of course not injective.

Currently `rawnnumeral` interpreters parse integers represented as `string * sign` and interpreters not handling signs just raise an error.
Would it make sense to extend this to decimal numbers as `string * sign * int` (e.g., `1.5` would give `("15", true, -1)` (BTW, the convention for signs here is the reverse of that of the IEEE-754 standard)) such that interpreters only handling integers would just raise an error in case of negative exponent?

**Comment by silene** [comment]
> Anything missing?

- `roundToIntegral: mode -> float -> float`
- `convertToIntegral: mode -> float -> int` (possibly only for `mode_ZR`)
- `nextUp: float -> float` (and possibly `nextDown: float -> float`)
- `class: float -> (NaN | PInf | NInf | PZero | NZero | PFinite | NFinite)` (and possibly `| Psubn | NSubn` to match 754)

`class` can be (and is) emulated with the current interface, but the cost seems prohibitive for such a cheap operation. The other operations cannot be reasonably emulated with the current interface. (But `nextDown` can be trivially emulated once `nextUp` is here, and `convertToIntegral` can be painfully emulated once `roundToIntegral` is here.) I am not sure what the behavior of `convertToIntegral` should be for negative numbers.

Also, I am not too fond of the return type of `compare`, as it means allocating and then matching twice. I would prefer a return type that makes a Coq implementation of `min` and `max`  fast.

> define a fully-specified spec w.r.t. a minimal excerpt of Flocq

Note that a few functions were changed in Flocq master (mostly reordered the branches to make sure they had good computational properties). The new behavior is provably equivalent, but no need to diverge here. So, you should keep in mind to update your specification at some point.

> Pretty-printing of floating-point values

What is the current behavior of your code?

Anyway, nice piece of work.

**Comment by proux01** [comment]
Thanks for your comments.

You're right, we should add `class`, `round_to_int` and `convert_to_int` (for the last one, the easiest solution might be to return the absolute value, since `int` are unsigned).

> the return type of `compare`

Indeed, we should rather return a type like `NotComparable | Lt | Eq | Gt` which would avoid boxing and the two successive matches.

> Note that a few functions were changed in Flocq master

I should update the spec.

> What is the current behavior of your code?

Parsing is not yet implemented and printing is currently just a call to the OCaml function `string_of_float` (except for nan which are signed in OCaml).

**Comment by erikmd** [comment]
FYI we recently refined our benchmarks to profile individual arithmetic operations (+ and ×), and we obtained the following speedup:
- 500x for addition using vm_compute (between emulated floats using @maximedenes's primitive-integers, and primitive binary64 floats)
- 800x for multiplication using vm_compute (likewise)
