### ISSUE TITLE
CoqIDE freezes deterministically

### ISSUE THREAD

**Issue by Zeimer** [coq/coq#8283]
#### Version

The Coq Proof Assistant, version 8.8.1 (August 2018)
compiled on Aug 16 2018 22:07:07 with OCaml 4.05.0

#### Operating system

Ubuntu 18.04

#### Description of the problem

Take a look at this code:

```coq
Require Import List.
Import ListNotations.

(* Find the index of the first element of the list that satisfies the
   predicate. *)
Fixpoint findIndex {A : Type} (p : A -> bool) (l : list A) : option nat :=
match l with
    | [] => None
    | h :: t =>
        if p h
        then Some 0
        else
          match findIndex p t with
              | Some n => Some (S n)
              | None => None
          end
end.

(* Something that should resemble right fold. *)
Fixpoint foldr
  {A B : Type} (f : A -> B -> B) (b : B) (l : list A) : B :=
match l with
    | [] => b
    | h :: t => f h (foldr f b t)
end.

(* Implementation of findIndex using foldr. It's incorrect, but that
   shouldn't matter. *)
Definition findIndexF
  {A : Type} (p : A -> bool) (l : list A) : option nat :=
    foldr (fun h t => if p h then Some 0 else t) None l.

Lemma findIndexF_spec :
  forall (A : Type) (p : A -> bool) (l : list A),
    findIndexF p l = findIndex p l.
Proof.
  unfold findIndexF. induction l as [| h t]; cbn.
    reflexivity.
    destruct (p h). (* FREEZE *)
```

It shouldn't pose any problems (besides the fact that the theorem is not true), but doing ```destruct (p h)``` makes CoqIDE freeze forever. This issue is not present when trying to prove this using coqtop.

Does anybody experience the same problem?

**Comment by gares** [comment]
It is not reproducible here, on master  ga62ab4903d

**Comment by Zimmi48** [comment]
I couldn't reproduce with CoqIDE 8.8.1 installed using Nix (on Linux/NixOS).
I assume you installed Coq and CoqIDE using OPAM?
Can you try temporarily moving `.config/coq` to see if it is connected in anyways to your configuration files?

**Comment by Zeimer** [comment]
@Zimmi48 

Yes, I installed using OPAM. Moving ```.config/coq``` didn't help.

**Comment by ejgallego** [comment]
Start the IDE with -debug and -stm-debug and post the relevant portions of the log.

**Comment by ejgallego** [comment]
This has gone stale, please reopen if more help is needed.
