### ISSUE TITLE
Install instructions need updating

### ISSUE THREAD

**Issue by spitters** [coq/coq#8294]
This page is still about 8.7.2.
https://coq.inria.fr/opam/www/using.html

**Comment by spitters** [comment]
Maybe the page should also include install instructions for PG.

**Comment by Zimmi48** [comment]
cc @gares

**Comment by Zimmi48** [comment]
@spitters Why would this page include install instructions for PG? This page is specifically about opam.

**Comment by spitters** [comment]
It also contains:
```
opam install coqide
```

Why not:
```
opam install proofgeneral

**Comment by spitters** [comment]
I seem to have picked it up here:
https://github.com/EasyCrypt/opam/tree/master/packages

I could imagine doing something similar in coq opam

**Comment by Zimmi48** [comment]
It has been suggested before and I have personally rejected this idea because Proof-General is neither an OCaml or dependent on an OCaml program, but in the end it should be Proof-General maintainers' call (cc @Matafou @cpitclaudel). Anyways, if there must be a lengthy discussion on this question, it should probably happen on PG's own issue tracker.

**Comment by cpitclaudel** [comment]
We're putting PG on MELPA (the PR was opened yesterday by @erikmd!) :)
It could be useful to add a link to installation instructions.

**Comment by erikmd** [comment]
@cpitclaudel
> It could be useful to add a link to installation instructions.

+1; and as soon as the MELPA PR will be merged upstream I'll update the ProofGeneral website, so maybe https://coq.inria.fr/opam/www/using.html could just point to one of these URLs:
- https://proofgeneral.github.io or
- https://proofgeneral.github.io/#quick-installation-instructions

**Comment by erikmd** [comment]
And beyond MELPA, there is an open issue regarding an opam package for PG: https://github.com/ProofGeneral/PG/issues/369

As @Zimmi48 said
> Proof-General is neither an OCaml or dependent on an OCaml program

so like Théo I was also hesitant at first to consider an OPAM package for PG, but after all it is quite similar to `tuareg-mode`, which is both on MELPA and OPAM… so we could just as well do the same for PG :)

**Comment by Zimmi48** [comment]
See https://github.com/coq/opam-coq-archive/pull/400.

**Comment by Zimmi48** [comment]
And https://github.com/coq/opam-coq-archive/pull/401.

**Comment by erikmd** [comment]
@spitters @Zimmi48 @SkySkimmer Just to follow-up the remarks raised in this issue, ProofGeneral is now on MELPA (http://melpa.org/#/proof-general) and the installation instructions have been updated (https://proofgeneral.github.io/#quick-installation-instructions).
Anyway we'll do soon an announcement of this new installation procedure.
Cc @cpitclaudel @Matafou
