### ISSUE TITLE
rewrite ?INVALID_NAME does not fail but it should

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#8299]
#### Version

master (c66c27781c555ec7301300cbf0d0342394c03981)

#### Operating system

macOS 10.13.6

#### Description of the problem

This fails to fail both in vanilla Coq and SSReflect:

```coq
Goal 0 = 1.
Fail Fail rewrite ?INVALID_NAME.
Abort.
```

The script above should produce an error like so:
> The reference `INVALID_NAME` was not found in the current environment.

**Comment by JasonGross** [comment]
Note that this would break code like
```coq
induction n as [|n IHn]; rewrite ?IHn.
```
Also, what do you want to happen for
```coq
Goal 0 = 1 -> 0 = 1.
  intro H.
  let H2 := constr:(H) in
  clear H;
  rewrite ?H2.
```

**Comment by anton-trunov** [comment]
@JasonGross Oh, you are right, thank you for the examples. I guess I was just annoyed by my typo at the of the day :) We should probably put it in the manual.

Checking if the name is completely unrelated (e.g. does not present in any subgoal, etc.) would be too expensive/complicated, right?

**Comment by anton-trunov** [comment]
It might be the job of a linter to warn the user about such things.

This should probably be closed (but feel free to reopen if it makes sense).

**Comment by gares** [comment]
When rewire will be ported to the tactic monad I believe I will be able to fail if ?lem has no effect on all branches. In that case you want an error. Today the v82 tactic API makes it impossible to code such a check.

**Comment by anton-trunov** [comment]
@gares Awesome! Thank you.
