### ISSUE TITLE
Anomaly "Unable to handle arbitrary u+k <= v constraints" w/ universes

### ISSUE THREAD

**Issue by eluuk** [coq/coq#8310]
#### Version

8.8.1

#### Operating system

Linux

#### Description of the problem

(* Not sure if this is a duplicate but.. *)

Check ltac:(let U := constr:(Type) in apply U).

(* Conversion test raised an anomaly:
Anomaly "Unable to handle arbitrary u+k <= v constraints."

Note: You get the anomaly w/ apply, eapply and eexact; w/ exact and refine it works *)

**Comment by SkySkimmer** [comment]
Just `Check ltac:(apply Type).` is enough to get the error. I guess there's a missing refresh somewhere.
