### ISSUE TITLE
Modules: include definitions in type into module in module type ascription

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#8317]
This is a feature request based on the discussion on coq-club with subject "module "best practices"?".

Module types cannot only contain declarations, but also definitions, e.g. definitions of inductive types or functions. When a module is typed with a module type containing definitions, all definitions from the module type must be repeated in the module. This can be done with an include of the module type, but this does not work if the module type contains both definitions and parameters, because the parameters must be defined in the module.

Below are a few examples. Regarding a discussion why it makes sense to include definitions in a module type, please refer to the mentioned forum discussion.

````
Module Type MOD1.
  Definition t:=nat.
End MOD1.

Module Mod1a <: MOD1.
  (* This should be superflous *)
  Definition t:=nat.
End Mod1a.

Module Mod1b <: MOD1.
  (* This should be superflous *)
  Include MOD1.
End Mod1b.

(*
Module Mod1c <: MOD1.
End Mod1c.
Fails with "The field t is missing in Top.Mod1c."
Since the Definition is in the module type, this need not fail.
*)

Module Type MOD2.
  Definition tdef:=nat.
  Parameter tpar:Type.
End MOD2.

Module Mod2a <: MOD2.
  (* This should be superflous *)
  Definition tdef:=nat.
  (* This is required *)
  Definition tpar:=nat.
End Mod2a.

Module Mod2b <: MOD2.
  (* Can only include both, definitions and parameters or none. *)
  Include MOD2.
  (* Fails with "tpar already exists."
  Definition tpar:=nat.
  *)
  (* Also cause of the include the Parameter tpar is in the Module as well (as Parameter)
     and need not be defined, which is problematic *)
End Mod2b.
````

**Comment by anderslundstedt** [comment]
Here is the mentioned Coq-Club discussion:

https://sympa.inria.fr/sympa/arc/coq-club/2018-08/msg00035.html


And here is some previous Coq-Club discussion:

https://sympa.inria.fr/sympa/arc/coq-club/2017-10/msg00036.html

**Comment by JasonGross** [comment]
It seems like there are two things you might be requesting here.

If you are requesting that, at module-closing time, any missing identifiers which were given `Definition`s in the `Module Type`(s) are included automatically, that seems mostly sane.  (Though if there are two module type ascriptions for the same module, and they have definitions for the same identifier which are unifiable but syntactically distinct, how do you pick which one to include.  That is, what should be the behavior of
```coq
Definition mynat := nat.
Module Type MOD1.
  Definition t := nat.
End MOD1.
Module Type MOD2.
  Definition t := mynat.
End MOD2.
Module Mod1 <: MOD1 <: MOD2.
End Mod1.
Print Mod1.t. (* nat, or mynat? *)
```
?)

---
If you are asking for the definitions to be included at module opening time, I don't see how this can work without breaking code, or making the module system even more ad-hoc and dynamic.  Consider this code:
```coq
Module Type MOD1.
  Definition t:=nat.
  Parameter x : t.
End MOD1.

Module Type MOD2.
  Definition t := nat.
End MOD2.

Module Mod1 <: MOD1.
  Definition t := nat.
  Definition x : t := 1.
End Mod1.

Module Mod2 <: MOD2.
  Include Mod1.
End Mod2.
```
I think your proposal breaks this, because it'll make `Include Mod1` fail with the fact that `t` is already defined.  And if the `Include Mod1` ought not fail, then ... you are asking that it be fine to redefine definitions with the same name but a syntactically equal body modulo equality of universes?  Note that this still loses expressivity, because it forbids things like
```coq
Module Type MOD1.
  Definition t:=nat.
End MOD1.

Definition mynat := nat.

Module Mod1 <: MOD1.
  Definition t := mynat.
End Mod1.
```
But if you go modulo unification rather than syntactic equality, then you can make self-referential definitions which loop under `cbv` (but not `lazy`), without fixpoints, and have other strange behavior.  It might even be the case that this would increase the expressivity / logical of Coq, for example, by allowing you to give the right type to the recursor on a faked inductive-recursive definition.

It's also not clear to me how you expect something like this to behave, if you don't have to give the `Definition`s:
```coq
Module Type MOD1.
  Parameter t : Set.
  Definition t2 := (t * t)%type.
  Parameter t2v : t2.
End MOD1.

Module Mod1 <: MOD1.
  Definition t := nat.
  Definition t2 := (t * t)%type.
  Definition t2v : t2 := (1, 1).
End Mod1.
```

**Comment by JasonGross** [comment]
Also, note that having modules with syntactically different definitions than those ascribed by their module types is useful and is in use in the wild.  See https://github.com/coq/coq/issues/3115#issuecomment-337515689:
```coq
Module Export Def.
  Axiom A : Type.
  Axiom B : Type.
End Def.
Definition C (b : bool) := if b then A else B.
Module Type DefSig.
  Definition A := C true.
End DefSig.
Module CoerT (P : DefSig).
  Identity Coercion coer : P.A >-> C.
End CoerT.
Module Export CoerAT := CoerT Def.

Check ((_ : A) : C _).
```

**Comment by JasonGross** [comment]
What should `Include Definitions` do when there is a definition which depends on an axiom?

I think that if type ascriptions have a default include-meaning, it should be "include missing definitions".  The other variants don't really make sense in use cases like `Module M := X <: Y.` (which, IIRC, is valid).

More generally, I think `Include`, `Import`, and `Export` should be able to be more fine-grained, and support selecting which things to include/export/import.

**Comment by MSoegtropIMC** [comment]
You are right - Include Definitions does only make sense together with module type ascription, so that axioms must be defined in the module.

I have to think about the include missing. Maybe it is a good option, but in general I like more "rigid" mechanisms.

**Comment by SkySkimmer** [comment]
Maybe just a command to get a specific definition from a module type with the previous definitions instanciated using the module currently being defined?
~~~coq
Module Type TT.
Parameter T : Type.
Definition idt : T -> T := fun x => x.
End TT.

Module M.
Definition T := nat.
Magic TT.idt. (* idt is defined *) (** syntax tbd **)
Print idt. (* M.idt : M.T -> M.T = fun x => x *)
End M.
~~~
If you have a bunch of definitions in the module type you have to write a command for each but that's not so bad, and unlike `Include Missing` it won't do silly things if you forget to put in the alternate definition you intended. ie
~~~
Module M' :> TT.
Include Missing TT. (* add an axiom *)
End M'.

Module M'' :> TT.
Fail Magic TT.idt. (* error missing T *)
(* I don't know how to abort modules, it might not even be possible *)
~~~

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : I think both would be very useful, a "one definition at a time" solution and a "take all" solution. The main reason why I am after a "take all" solution is maintainability. Essentially if a module type contains definitions, one is forced to copy these definitions into a module ascribed to this module type. If one extends a module type, one might want to have this inclusion somehow automated.

Pondering about Jason's comments, I think what I really want is:

**Include Definitions from MT:** behaves as if all definitions from the given module type (or module) are copied verbatim in the current module. If this gives an error either because axioms are yet undefined or because things are doubly defined, this gives an error (as Include does today). I don't think that this would have any impact on the basic semantics of Coq, since one could copy and paste the definitions over. This command should (semantically) do nothing else.

**Include Valid from MT:** This includes everything from a module type (or module) which is valid at the current point, that is its prerequisites are already defined and the definition itself is not yet defined.

**Include Valid Definitions from MT: ** as above, but just includes Definitions.

**Include ID from MT:** just includes definition ID (as SkySkimmer suggested)

If syntactic sugar for Includes in the module type ascription makes sense I have meanwhile severe doubts. In many cases the place where the Include Definitions is done is important. Prerequisites have to be defined before and stuff which needs this has to come after it. So I think syntactic sugar in the module type ascription would only help in trivial cases. I think one would have at least to be able to control if something is included at the beginning or end of the module, which would make the syntax pretty heavy.

It might even happen that two Include Valid Definitions of one module type make sense. Say you have a parameter A, a definition B depending on A, a parameter C depending on B and a definition D depending on D. Then in a module with this type one could define A, Include Valid Definitions to get B, define C and then do another Include Valid Definitions to get D.

I don't think that any of this would have any impacts on Coq's basic sematics. Semantically the effect of these commands should be to copy stuff from the module type to the module in case it is valid. Maybe I am a bit naive about how definable valid is - I am assuming that "doesn't give an error" would be good enough, but I can imagine that it might get more complicated than this.

**Comment by SkySkimmer** [comment]
>Essentially if a module type contains definitions, one is forced to copy these definitions into a module ascribed to this module type. If one extends a module type, one might want to have this inclusion somehow automated.

My point is that I suspect such automation would lead to mistakes ;)

>I don't think that any of this would have any impacts on Coq's basic sematics. Semantically the effect of these commands should be to copy stuff from the module type to the module in case it is valid. Maybe I am a bit naive about how definable valid is - I am assuming that "doesn't give an error" would be good enough, but I can imagine that it might get more complicated than this.

The mechanism should certainly live outside the kernel.

**Comment by MSoegtropIMC** [comment]
> My point is that I suspect such automation would lead to mistakes ;)

It depends on the situation. I think itshould be left to the user to decide what is less effort, changing a lot of module definitions (during development of something new it can be frequent) are debug strange effects. For this reason I think both is required, individual inclusion and bulk inclusion.

**Comment by jwiegley** [comment]
I ran into exactly this same problem today: I have been working on an axiomatic system for LTL, which provides a Module Type that depends on a few parameters and axioms, but then "provides" a host of definitions and theorems defined and proven in terms of those parameters and axioms. What I'd like is that once a module author provides those required data, all of the definitions and theorems become available and usable. At present it looks like I'd actually have to repeat all the theorems -- verbatim -- for them to be available in the module.

**Comment by MSoegtropIMC** [comment]
@jwiegley : I think it should be possible to put the definitions in a separate module (not a module type) then.

Things get more tricky if one has definitions and parameters which depend on each other, say you have a parameter which defines some simple type, a definition which constructs a more elaborate type from this parameter and then another parameter which uses this type in its signature and so on. But as @JasonGross and @SkySkimmer pointed out above, in such cases it is difficult to avoid some automatism doing silly things.

So after experimenting with this a few more years I came to the conclusion that one can live with the system as is by using more fine grain modules and module types for implementation and then defining some big modules or module types which put everything together.

**Comment by jwiegley** [comment]
I was able to achieve the desired result using a separate `Facts` style module, thank you!

**Comment by MSoegtropIMC** [comment]
> I was able to achieve the desired result using a separate Facts style module, thank you!

I am happy I could help!

I guess we should close this issue and I should create a personal issue on writing better documentation for the module system or maybe even a longer chapter in SF.

If someone thinks we should keep this issue, please reopen.

**Comment by Zimmi48** [comment]
The modules chapter of the reference manual is in dire need of improvement (both to make it more understandable and to include best practices tips). If you're willing to invest time on this, I'd be happy to discuss this with you.

**Comment by MSoegtropIMC** [comment]
Right now all my free bandwidth is bound by the Coq Platform project - I hope this will change within two or three months. I need to ass all the new packages now.

I have some good examples for the module system I can share, but I think they are much too long for the reference manual. Let me see what I can come up with. I think part of the story should also be to discuss the pros and cons of modules, records, type classes and canonical structures. I think the reference manual should have some "product comparison chart" for these. The same applies to the various tactic languages + reflective techniques.

It would indeed be great if we could discuss this as soon as I have something! I put an entry on my ToDo list.

**Comment by Zimmi48** [comment]
>I think part of the story should also be to discuss the pros and cons of modules, records, type classes and canonical structures. I think the reference manual should have some "product comparison chart" for these. The same applies to the various tactic languages + reflective techniques.

:+1:
