### ISSUE TITLE
evar tactic is not well understood in Ltac definitions

### ISSUE THREAD

**Issue by Matafou** [coq/coq#8319]
#### Version
 8.8.1
#### Operating system
Linux
#### Description of the problem

The evar(x:y) tactic makes two things: it creates an evar ?x of type y AND a hypothesis x :=?x : y. The latter thing seems unknown to Ltac programming language: 
 
```
Fail Ltac Tac :=
  evar(ev:False);
    elim ev.    (* The reference ev was not found in the current environment. *)

(* whereas the same code works in a proof. *)
Goal True.
Proof.
  evar(ev:False);
    elim ev.
Qed.
```
There is an unstaisfaying workaround: use the fact that the evar created is the last thing in the proof environment.

Cheers

**Comment by andres-erbsen** [comment]
My recommendation would be to avoid calling `evar` altogether and use `let ev := open_constr:((_:False)) in elim ev`, manually calling `pose` with the evar if necessary.

**Comment by Matafou** [comment]
Thanks! Indeed this is a clean workaround.

Why would it be a bad idea to call evar(ev:False)? (and why is it not a wrapper to your solution by the way?

**Comment by JasonGross** [comment]
The evar tactic actually does three things; it also gives a name to the evar, which can cause complexity issues.   So it is more like `epose (?[ev] : False) as ev`.

Note, by the way, that this also works:
```coq
Ltac Tac :=
  let ev := fresh "ev" in
  evar(ev:False);
  elim ev.
```

**Comment by Matafou** [comment]
I see, thanks for the explanation.

Is it still a bug or should I close it?
