### ISSUE TITLE
Deprecate command Show Script.

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8320]
The description for the `Show Script` command seems incomplete.  `<Your Tactic Text here>` is just a placeholder.  See .../coq/doc/sphinx/_build/html/proof-engine/proof-handling.html#coq:cmdv.show-script

@Zimmi48's opinion: "nobody uses it nowadays and we could just remove it"

For example, when I try the command, I get this:

```
Proof.
(intros n E).
(inversion E as [| n' E']).
-
 exists 0.
 reflexivity.

-
 (simpl).
 (auto; auto).
```

**Comment by gares** [comment]
I agree with @Zimmi48 , it had one user, that told me he now uses proof general, making this command dead code.

**Comment by Zimmi48** [comment]
Let's deprecate in 8.9, at least.

**Comment by vbgl** [comment]
Is somebody working on this?

**Comment by gares** [comment]
I'm not, please deprecate it if you have the time
