### ISSUE TITLE
Add more useful addons to the Windows Installer

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#8321]
Add some more useful addons to the Windows installer.

I frequently (or at least occassionally) use:
- Princeton VST + the required CompCert tools
- QuickChick
- Menhir and Mnehir Coq library
- math components + ssreflect
- coquelicot
- aactactics

**Comment by Zimmi48** [comment]
When it was just about including a few small plugins with the Coq Windows installer, it was quite reasonable to add this to the build time but of course with larger developments like VST, it becomes more complicated. What we would need ideally would be a generic framework to build a Windows installer for any package in the Coq index. And such various builds could be executed in parallel. The Windows users would just have to download from the website the installers for whatever package they are interested in.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : yes, this is my plan. But I can't get there all in one step. My mid term plan is to have an automated developer setup, which allows to compile plugins for a given Coq version and second to have an installer with downloadable plugins.

Maybe mid term I will also switch to opam. For the developer environment I plan to provide both: opam and my scripts.

**Comment by Zimmi48** [comment]
This issue has been completed and should be closed, right?

**Comment by MSoegtropIMC** [comment]
Yes - meanwhile this is all included.
