### ISSUE TITLE
Windows build: change .zip to .tar.gz where possible

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#8327]
This is about dev/build/windows/makecoq_mingw.sh

Some external components are supplied as source zip file. unzip does not support root path stripping, so currently files are moved after an unzip. The move afterwards seems to be a bit unreliable on Windows. So I want to replace all .zip files with .tar.gz files where possible (e.g. downloaded from github).

**Comment by MSoegtropIMC** [comment]
This is deprecated with Coq Platform.

**Comment by ejgallego** [comment]
> This is deprecated with Coq Platform.

I didn't see the commit removing the windows runners from `.gitlab-ci.yml`, did I miss it?

**Comment by ejgallego** [comment]
> I didn't see the commit removing the windows runners from `.gitlab-ci.yml`, did I miss it?

Well indeed I pulled and the code is there; that seems very strange to me, I never heard of "deprecating a bug".

You either fix the problem, and reference the fix in the commit, or keep the bug open.

IMVHO closing bugs like this is not a good practice.

**Comment by MSoegtropIMC** [comment]
The complete set of scripts this issue is about is gone, including the specific script named in the first line of the issue.

The Windows build in CI is now based on the Coq platform scripts, and these use opam, so they don't handle source tar balls directly any more - they leave this to opam. So the problem described in this issue doesn't exist any more either.

**Comment by MSoegtropIMC** [comment]
P.S.: the PR was (https://github.com/coq/coq/pull/13598)

But one can't really say that this PR fixed this issue. This issue went into non existence by switching to a different build technology.

**Comment by ejgallego** [comment]
Oh indeed, thanks, I misunderstood this.

I'd definitively say that sending an issue into non-existence is fixing it.

**Comment by MSoegtropIMC** [comment]
"fixing" or "deprecating" - I should have mentioned the PR removing the legacy Windows build system right away to make this clearer.
