### ISSUE TITLE
Regression in menhir-lib from 8.8.1 to current master

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#8328]
#### Version

Master 2018 August 26th
https://github.com/coq/coq/commit/56b355e9e3e0394625cc40084f7cf11a949ebb29

#### Operating system

MinGW built on cygwin64 on Windows 10 64

#### Description of the problem

menhir-lib does build fine with 8.8.1 but it doesn not build with master. The error log is attached.

[coq-menhirlib-20180530-make.err.txt](https://github.com/coq/coq/files/2321566/coq-menhirlib-20180530-make.err.txt)

The version of menhir-lib I use is (as fa as I can tell) the latest:

https://gitlab.inria.fr/fpottier/coq-menhirlib/-/archive/20180530/coq-menhirlib-20180530.tar.gz

**Comment by Zimmi48** [comment]
menhirlib is not part of the external projects that are tested in our CI, so I wouldn't automatically consider this a regression. We could have it added to our CI after it is fixed for compatibility with 8.9.
cc @fpottier
see also https://github.com/coq/coq/tree/master/dev/ci#information-for-external-library--plugin-authors

**Comment by Zimmi48** [comment]
Oh sorry I hadn't seen yet that you were saying the same thing in #8328. Maybe not necessary to have two separate issues on this topic though.

**Comment by fpottier** [comment]
Jacques-Henri (@jhjourdan) is the author and maintainer of coq-menhirlib. Hopefully he will be able to have a look and propose a fix.

**Comment by fpottier** [comment]
Oh, I just noticed that Michael (@MSoegtropIMC) has sent us a patch. Thanks! I will check it and merge it.

**Comment by MSoegtropIMC** [comment]
Yes, I just submitted a patch. The issue is an undocumented use of the fix tactic (with the ident argument missing). One simply has to supply the argument.

@Zimmi48 : I see it as separate steps to fix it (this issue) and to add it to CI since I am sure nobody objects to fixing this but I am not sure if we agree to have it in CI. For the Coq Windows build I have a patch. We can still close both issues with one PR in case.

I guess it is generally ok to report issues with external components as Coq issues? Should we have a separate label for such issues? Sort of "soft-regression"?

**Comment by Zimmi48** [comment]
>The issue is an undocumented use of the fix tactic (with the ident argument missing). One simply has to supply the argument.

So indeed, it is then not a regression but a conscious change.

>I guess it is generally ok to report issues with external components as Coq issues?

It is preferable when possible to open these issues on the external project issue tracker (as you just did in https://gitlab.inria.fr/fpottier/coq-menhirlib/issues/3).

>I see it as separate steps to fix it (this issue) and to add it to CI since I am sure nobody objects to fixing this but I am not sure if we agree to have it in CI.

OK let's close this as this was moved to https://gitlab.inria.fr/fpottier/coq-menhirlib/issues/3 and use #8328 to continue the discussion on adding menhirlib to CI.
