### ISSUE TITLE
Windows CI is not stable cause of cygwin reuse

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#8335]
As the various pipeline runs for PR #8322 show, the windows CI fails randomly because randomly Cygwin installations are reused. I am not sure under which conditions cygwin installations are reused - it doesn't seem to be the case always, otherwise it would always fail.

The solution discussed with @Zimmi48 in #8322 is to delete the cygwin and target folders at the beginning of the build. There might be a bit more to it, because I think the aritfact upload happens after the script exits. So it would be bad if the next job would start and delete the artifacts - not sure how this is handled. On the other hand I guess the artifact upload is still part of the build job and the next one doesn't start before the upload is finished - anyhow one has to test this.

**Comment by Zimmi48** [comment]
>So it would be bad if the next job would start and delete the artifacts - not sure how this is handled. On the other hand I guess the artifact upload is still part of the build job and the next one doesn't start before the upload is finished - anyhow one has to test this.

I would be surprised if the next job started before artifact upload is complete.

**Comment by MSoegtropIMC** [comment]
This has been fixed by #8604.
