### ISSUE TITLE
ci-sf.sh no longer requires sed commands

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8337]
#### Version

master

#### Description of the problem

A manual inspection of https://www.cis.upenn.edu/~bcpierce/sf/lf-current/lf.tgz , https://www.cis.upenn.edu/~bcpierce/sf/plf-current/plf.tgz , and https://www.cis.upenn.edu/~bcpierce/sf/vfa-current/vfa.tgz shows that all three `sed` hacks in `ci-sf.sh` have been merged upstream, and are thus no longer required.

**Comment by ejgallego** [comment]
Thanks @JasonGross
