### ISSUE TITLE
check-owners.sh incorrectly labels user-overlays as being owned by ci-maintainers

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8338]
#### Version

8.9+alpha

#### Description of the problem

```
$ ./dev/tools/check-owners-pr.sh  8064 | head -1
From https://github.com/coq/coq
 * branch            refs/pull/8064/head -> FETCH_HEAD
 * branch            master     -> FETCH_HEAD
dev/ci/user-overlays/jasongross-numeral-notation-4.sh: @coq/ci-maintainers
```
However, user-overlays are labeled as being owned by `@ghost` in `.github/CODEOWNERS`.

**Comment by SkySkimmer** [comment]
The way github displays code owner info has improved so maybe we should delete these scripts.

**Comment by Zimmi48** [comment]
Yes, I never use them anymore, and the contributing guide recommends using what GitHub displays.
