### ISSUE TITLE
Tactic Notation single-goal when taking an argument of type ident.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#8342]
#### Version

8.8.1

#### Description of the problem

```
Tactic Notation "count" := let n := numgoals in idtac n.
Tactic Notation "count_constr" constr(x) := let n := numgoals in idtac n.
Tactic Notation "count_uconstr" uconstr(x) := let n := numgoals in idtac n.
Tactic Notation "count_ident" ident(x) := let n := numgoals in idtac n.
Tactic Notation "count_int" integer(x) := let n := numgoals in idtac n.
Ltac count_tac := let n := numgoals in idtac n.
Ltac count_tac_constr x := let n := numgoals in idtac n.

Goal True /\ True.
split; count. (* 2 *) Undo.
split; count_constr True. (* 1 1 *) Undo.
split; count_uconstr True. (* 1 1 *) Undo.
split; count_ident blabla. (* 1 1 *) Undo.
split; count_int 1. (* 2 *) Undo.
split; count_tac. (* 2 *) Undo.
split; count_tac_constr True. (* 1 1 *)
```

I can understand why, as soon as a tactic takes a term as argument, it needs a context to type this argument, thus it becomes single-goal and uses the context of the current goal.

However:
- This is not documented (I've browsed the Ltac chapter and the Tactic Notations section of the manual). This is really bad given how surprising this behavior can look.
- It doesn't make any sense when a Tactic Notation that takes an ident or a reference (or a uconstr) as argument is also restricted to single-goal.
- There is already an inconsistency since integer arguments do not make the tactic single-goal. So changing the behavior of Tactic Notations with ident and reference would not create any new inconsistency and would only make things more sensible.

**Comment by ppedrot** [comment]
IIRC for ident and references, I am afraid that the current implementation tries to cast them to a variable from the context, so it does require focussing on the goal, unluckily.

**Comment by Zimmi48** [comment]
It seems reasonable to consider this a won't-fix for Ltac1. Ltac2 gives much more control over this kind of stuff and will allow implementing such things without pain.
