### ISSUE TITLE
Error: Anomaly "A universe comparison can only happen between variables." (in inductive type)

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8364]
#### Version

8.8.1

#### Description of the problem

```coq

Definition map {A B} (f:A -> B) :=
  fix map l :=
  match l with nil => nil | cons x xs => cons (f x) (map xs) end.

Fixpoint tuple (l : list Type) : Type :=
  match l with
  | cons x nil => x
  | cons x xs => prod x (tuple xs)
  | nil => unit
  end.

Inductive stack : Type -> Type :=
| Stack T foos :
  tuple (map stack foos) ->
  stack T.
(* Error: Anomaly "A universe comparison can only happen between variables."
Please report at http://coq.inria.fr/bugs/. *)
```

**Comment by anton-trunov** [comment]
I cannot reproduce the issue with Coq 8.8.1.

My system is macOS 10.13.6:

```shell
$ opam switch
...
coq.8.8.1  C 4.07.0+flambda  Official release 4.07.0 with flambda activated
...
$ coqtop -v
The Coq Proof Assistant, version 8.8.1 (July 2018)
compiled on Jul 11 2018 12:45:39 with OCaml 4.07.0
$ coqc issue_8364.v
$ echo $!
0
```

**Comment by JasonGross** [comment]
Sorry, I must have overwritten the most important part when pasting the error message into the code.  I've updated the initial report with the inductive that actually triggers the error.

**Comment by SkySkimmer** [comment]
This is something to do with the hack we use to get algebraics in the type of inductive types (eg `prod A B : Type@{max ...}`).
I don't know what kind of solution we need but you can do `Inductive stack : Type -> Type@{_} := ...` to work around it.
