### ISSUE TITLE
Show some Coq error messages with diffs

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8366]
#### Description of the problem
A couple people suggested it would be useful to apply the underlying diff code to some Coq error messages.  For example, messages like "X is of type \<long expression1> but should be of type \<long expression2>"

I'd appreciate nominations of specific messages to apply diff to.  Please include a complete and reasonably short script that generates the error.  Thanks.

**Comment by herbelin** [comment]
@jfehrle: The messages that needs a diff are already supposed to use a function `Himsg.display_eq`, so, I guess that it would be enough to replace this function by a more elaborate one.
