### ISSUE TITLE
Anomaly when using pattern-matching under lambda

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#8369]
#### Version

master (bf1446294dba45d3ea9b7bb39d2fc96617848c03)

#### Operating system

macOS 10.13.6

#### Description of the problem

```coq
Definition foo := fun '(u, v) p2 => (u, v).
```

master (bf1446294dba45d3ea9b7bb39d2fc96617848c03): 
> Error: Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/.

Coq 8.8.1:
> Error: Cannot infer an internal placeholder of type "Type" in environment:
> pat, p0 : ?T0 * ?T1

**Comment by herbelin** [comment]
See #8373. This was due to a problem in printing the error message. With the fix, the error is:
```
> Definition foo := fun '(u, v) p2 => (u, v).
>                   ^^^^^^^^^^^^^^^^^^^^^^^^
Error: Cannot infer
the domain of a subterm of type "Type" in the partial instance 
"?T@{pat:=pat; p0:=pat} -> ?T0 * ?T1" found for the type of this
pattern-matching problem in environment:
pat, p0 : ?T0 * ?T1
```
Maybe not a crystal clear message (e.g. where do `pat` and `p0` come from, and why a line break after "infer") but better than an anomaly...
