### ISSUE TITLE
Instructions for overlays do not work

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8375]
#### Version

8.9+alpha

#### Description of the problem

The instructions for overlays say:
> If the fork is not on the same platform (e.g. GitHub instead of GitLab), it is
necessary to redefine the `_CI_ARCHIVEURL` variable as well.

But this is misleading.  I have
```bash
if [ "$CI_PULL_REQUEST" = "8064" ] || [ "$CI_BRANCH" = "numeral-notation-4" ]; then
    HoTT_CI_REF=fix-for-numeral-notations
    HoTT_CI_GITURL=https://github.com/JasonGross/HoTT
fi
```
and in [this build](https://gitlab.com/coq/coq/-/jobs/93836648), it issues
```bash
wget https://github.com/HoTT/HoTT/archive/fix-for-numeral-notations.tar.gz
```
which is wrong.  So it seems the `_CI_ARCHIVEURL` variable always needs to be redefined.  I believe #8348 is the culprit.

cc @Zimmi48

**Comment by SkySkimmer** [comment]
We could revert 0be785a5832177efa4ec396a421a4eb367b81914

**Comment by Zimmi48** [comment]
@SkySkimmer only the part changing `ci-common.sh` right? Do you think that's the best solution? If yes, I can open a PR.

**Comment by Zimmi48** [comment]
What was the point of sourcing `ci-basic-overlay.sh` before BTW?

**Comment by SkySkimmer** [comment]
IIRC I wanted to simplify the `: ${foo:=bar}` to `foo=bar` but someone 
didn't want it so it just ended up quoted.

Gaëtan Gilbert
