### ISSUE TITLE
Anonymous Sections

### ISSUE THREAD

**Issue by whxvd** [coq/coq#8377]
#### Description of the problem
Sections must be named. The workaround
```
Section always_the_same.
End always_the_same.

Section always_the_same.
End always_the_same.
```
makes Coq complain: `Error: always_the_same already exists.`

The Reference Manual (Extensions of Gallina » Section mechanism) does not mention a rationale for or use of a name.

If a name is indeed needed (internally), it could be something like the position of the section in the file by default.

**Comment by SkySkimmer** [comment]
Fixed in master.
