### ISSUE TITLE
In coqIDE, none of the Queries menu items appear to do anything

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8379]
#### Description of the problem
Click any of the items in the Query menu.  Nothing happens.  At all.

It would be more efficient to have only a single menu item under Queries that does nothing :-)

**Comment by Zimmi48** [comment]
If I write `True` and I select it, then I click any of the Check / About / Print / Locate queries, it does what would be expected. Print Assumptions also works once you have selected something. How you have to guess that you first need to select something to run the query, I don't know.
The Search query gives me "Syntax error: [searchabout_query] expected after 'Search' (in [vernac:query_command])." in the Message output window.

**Comment by olekgierczak** [comment]
Any fix for the "Syntax error: [searchabout_query] expected after 'Search' (in [vernac:query_command])."? Search query even after selecting something gives me nothing but this error.

**Comment by eponier** [comment]
I confirm @olekgierczak's comment. Search query seems broken using the Queries menu or the shortcut (ctrl + shift + k), and not only on Windows. I'm using CoqIde 8.8.1 under Fedora 29. And I think I already had strange results with CoqIde 8.7, but not an error though, rather some results that appeared by typing `Search ident.` but not when using the shortcut.

**Comment by ppedrot** [comment]
I fixed that in 6eba9ffea648aace40261aa6abb5f138cad27d2d (#8166), actually. Not sure whether it was marked as backportable.

**Comment by ppedrot** [comment]
OK, so it should be fixed in 8.8.2 then. Please reopen if not the case.

**Comment by eponier** [comment]
Thanks, I will check, but please note that this issue was originally a documentation issue from @jfehrle , and that point has not been correct yet.
