### ISSUE TITLE
Removing deprecated notations

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#8383]
Since 8.8, some compatibility aliases are emitting deprecation warnings. The fixes in projects that use them are trivial and clearly explained in the warning message: the typical example is replacing `Nsucc` with `N.succ`.
In order to remove `-compat 8.6` in 8.9, we need projects we test in CI to first fix their code to build with `-w "+compatibility-notation"`.
If that's too much to ask, we could also change the way these deprecation warnings are emitted to make them independent of the compat system (see #8382) and postpone the removal of these aliases to later.

**Comment by Zimmi48** [comment]
Explaining the issues at stake with a bit of history:

A long time ago (before the 8.4 release, see https://coq.inria.fr/refman/credits.html#credits-version-8-4), Pierre Letouzey @letouzey reorganized much of the standard library, in particular around Numbers. At that time, compatibility aliases were defined (see f93f073df630bb46ddd07802026c0326dc72dafd) but no warning was emitted by default.

When the warning system (June 2016) was redesigned by Maxime Dénès @maximedenes, this warning was activated by default https://github.com/coq/coq/pull/213/files#diff-4645088d79e0fb58d1ace8f02414dfdf then disabled again by default before the 8.6 release (Oct 2016, d180279aa934dfbb3fd97e707675b55f464f14ef, "in many cases these new names are too painful").

In #375 (Nov 2016), Guillaume Melquiond @silene launched a clean-up movement with a new rule "only keep the compatibility switches for the two last versions" which was adopted at the Coq WG and has been followed since. The question of the 8.3 compatibility aliases was not tackled at that time (https://github.com/coq/coq/pull/375#issuecomment-288990361). To avoid tackling it, a new `VOld` flag was defined https://github.com/coq/coq/pull/375/files#diff-23261a82e4cac62686c2751549bf1d33.

After the 8.7 release, Hugo Herbelin @herbelin opened two PRs that he never finished #884 (Turning warning for deprecated notations on) and #887 (Remove support for 8.5 compatibility). However, there was no support for #884 and in fact the Coq WG even decided that the compatibility aliases should be undeprecated. Nonetheless, Hugo expressed in #887 that it was time to get rid of the `VOld` flag.

Because no progress was being made, and because I really needed to remove support for 8.5 compatibility to avoid useless work as part of my work on typeclasses eauto (#721), I decided to take over these two PRs (#6791), which is something that I regretted afterwards (I should have not got involved with the compatibility alias debate and kept the `VOld` flag because I lost a lot of precious time and I ended up not making progress on #721). As part of these clean-ups, I undeprecated compatibility aliases (i.e. I turned compatibility aliases into normal "only parsing" notations) as had been decided. And yet, *a user*, Jason Gross @JasonGross, told me to keep some of these deprecations (for easy to fix and non-debatable ones where the fix is just to add a dot, and a few others). Given the removal of `VOld`, the 8.3 compatibility aliases became 8.6 compatibility aliases, and the deprecation warning was turned on. Since then, it has been ignored by a lot of users.

Now, we are preparing the 8.9 release and it becomes time to remove compatibility support for 8.6 (#8374). Yet, this means getting rid of all these compatibility aliases. That's why we need library authors to start doing the renaming. The deprecation warnings should make this task easy but if it's not, please raise your concerns.

Note that I have been using the wording "compatibility aliases" because there is a difference in behavior of these aliases compared to other compatibility notations which are only available when running with `-compat X.X` (see #6840). @JasonGross claims that compatibility aliases should also work in the same way and I support this but we need another way of deprecating stuff from the standard library from now on (see #8382) that can be independent of the compatibility system (this would be useful for library authors too).

**Comment by maximedenes** [comment]
So did we end up not following what had been decided in the WG? I don't see the point of propagating these deprecations, since the current library is basically unmaintained.

**Comment by herbelin** [comment]
> since the current library is basically unmaintained.

In which sense are you saying that it is unmaintained? There are PRs about the stdlib which we accept, there is a lot of TODOs about how to improve it, including your ambitious project of stdlib2, so why are you saying that it is unmaintained?

**Comment by maximedenes** [comment]
> There are PRs about the stdlib which we accept

That's being "not dead", not "maintained".

> including your ambitious project of stdlib2

The project there is to make another library.

**Comment by herbelin** [comment]
You are not answering my question. What would it mean "maintained" for you?

> The project there is to make another library.

With which task force? With which ideas? With which contents?

**Comment by ejgallego** [comment]
Can we stop the off-topic? Thanks folks. @maximedenes you could indeed have kept the non-constructive comment for yourself this time.

**Comment by maximedenes** [comment]
Ok, I was trying to understand why we were pushing these deprecations, and even recently notified external projects that they should work on updating their code. I thought it was not in line with what had been decided, but I have only fuzzy memories of it, so I could very well be wrong. Since it is seen as non-constructive, I'll stop commenting on it, as I don't care much.

**Comment by ejgallego** [comment]
> I was trying to understand why we were pushing these deprecations, and even recently notified external projects that they should work on updating their code.

Note that understanding this is important, however I am sure we can understand it without having to set a level for stdlib maintainership.

**Comment by herbelin** [comment]
@maximedenes: I'm however taking note that, once more, you start making claims and flee at the time of giving explanations.

**Comment by ejgallego** [comment]
> @maximedenes: I'm however taking note that, once more, you start making claims and flee at the time of giving explanations.

@herbelin it was my request to stop the offtopic discussion; if you want folks to keep discussing this please do it in private.

**Comment by herbelin** [comment]
@ejgallego: I'm done, and shall welcome an explanation from @maximedenes offline.

**Comment by ejgallego** [comment]
> So did we end up not following what had been decided in the WG? I don't see the point of propagating these deprecations, since the current library is basically unmaintained.

So @maximedenes what you wanted to say here could be translated more as:

"So the actual proposal differs from the what we agreed on the WG. Is this a sensible plan? What are the plans for that particular part of library? Should we backtrack on the WG decision?"

**Comment by ejgallego** [comment]
> @ejgallego: I'm done, and shall welcome an explanation from @maximedenes offline.

Thanks @herbelin , thanks @maximedenes ; now let's see what's the correct path to go with the actual issue.

**Comment by maximedenes** [comment]
> "So the actual proposal differs from the what we agreed on the WG. Is this a sensible plan? What are the plans for that particular part of library? Should we backtrack on the WG decision?"

Yes, although I was just asking the question, because I'm not sure if we diverged from what had been decided or not. If yes, indeed, I guess it would make sense to understand what the current plans are.

**Comment by Zimmi48** [comment]
Thanks for flooding this issue folks. It is a really important one to which I've pointed many users so I would have appreciated if you had not trashed it (also think about the image that you are giving of the development team). (And thanks @ejgallego for trying to calm people down.)

Indeed, the decision of the WG was not followed to the letter because of the feedback of @JasonGross but I think it was followed in the spirit because the decision was not related to the question of whether the stdlib was unmaintained or dying but to the question of whether there was a consensus around these new names (that's why we undeprecated every alias for which the proposed replacement was non-consensual).

In any case, you @maximedenes should have been aware of this given that you approved and merged this PR... (#6791)

**Comment by maximedenes** [comment]
> In any case, you @maximedenes should have been aware of this given that you approved and merged this PR... (#6791)

Right, I'm not surprised I forgot about something I merged :) What is a bit tricky, is that the PR you mention actually removes deprecation. So it is not easy to see the complement, i.e. what stayed deprecated. So I don't think that part was really reviewed. Jason wrote about `Z.foo`, `N.foo` and `Pos.foo`, when it only added a dot. Does it reflect what stayed as deprecated? Or was there more?

**Comment by Zimmi48** [comment]
>Jason wrote about Z.foo, N.foo and Pos.foo, when it only added a dot. Does it reflect what stayed as deprecated? Or was there more?

Right, so it reflects most of it although `Pfoo` becomes `Pos.foo` so it adds a bit more than a dot. The only other things are stuff that he specifically requested regarding `sigT` vs `sigS` and `existT` vs `existS`.

**Comment by gares** [comment]
FTR math-comp/math-comp#223 currently failing on 8.7 and 8.8, works fine on master and 8.6.

**Comment by Zimmi48** [comment]
@gares See https://github.com/fblanqui/color/pull/10#issuecomment-418288139. Even if the error you get in Travis is cryptic, this might have something to do with this.

**Comment by gares** [comment]
It may be a bug in coq_makefile, introduced with cmf2.0 and fixed in master ... I'll follow your advice and remove the change to the build system and if it works merge.

**Comment by Zimmi48** [comment]
@silene I'd like you to take a stand on this PR given that you were the one to introduce the compat removal process, that you are the current RM and that you are the maintainer of Flocq.

**Comment by Zimmi48** [comment]
@JasonGross After porting (or trying to port) some projects myself, I feel like the removal of these deprecated notations is putting a heavy burden on library maintainers (especially those that emits hundreds of such warnings) for little gain, which could even delay the adoption of 8.9. So I see two possible ways out:
- provide a script that will use the compatibility-notation warnings emitted by Coq 8.8 to automatically fix projects;
- backtrack on the removal of the compatibility notations (and remove the deprecation warnings entirely).

Since you were the one that insisted for keeping some of these notations as deprecated when we turned the warning on, I suppose you would have a preference for the first solution, but is it possible to write such a script?

**Comment by JasonGross** [comment]
I do have a (weak) preference for the first one.  Writing a perfect script is quite hard (probably requires parsing the .glob files, so that we don't, e.g., replace `Definition sigS_string := "sigS"%string.` with `Definition sigT_string := "sigT"%string.`), but writing a simple one is quite easy.  If we have a list of all the identifiers and their replacements, then we can do something like
```
sed 's/\(^\|[^[:alnum:]_]\)sigS\([^[:alnum:]_]\|$\)/\1sigT\2/g'
```
for each identifier removed.  Here is such a script (untested), which I generated most of via
```
git show db25c5058c506f8f792e6356b3bae0457a94bb5a | grep compat | grep -o '^-Notation [[:alnum:]_\.]* := [[:alnum:]_\.]*' | sed s',^-Notation \([[:alnum:]_\.]*\) := \([[:alnum:]_\.]*\),-e '"'"'s/\\(^\\|[^[:alnum:]_]\\)\1\\([^[:alnum:]_]\\|$\\)/\\1\2\\2/g'"'"',g'
```

[update.sh.txt](https://github.com/coq/coq/files/2402057/update.sh.txt)

It is not perfect (it will generate both false-positives and false-negatives), but it should take care of most of the issues (and can easily be adapted to specific cases that it doesn't take care of on first pass).  Do you want to try this on mathcomp, etc?

**Comment by Zimmi48** [comment]
Math-Comp is already fixed and was not a big issue (not many warnings). Corn and Flocq both generate hundreds (or thousands) of warnings and will be the real tests. I will try that script and report on my impression.

**Comment by Zimmi48** [comment]
Though what I was suggesting was to piggy-back on the warnings emitted by Coq given that they are shown on stderr and provide, the line number, the character location, the term to replace and the term to replace it with.

**Comment by JasonGross** [comment]
@Zimmi48 That doesn't work in all cases, because the warning system misreports character locations.  e.g., on `Notation foo := nat_compare.`, it claims the location as characters 0-28, i.e., the whole line.  (And we can't just do the search-and-replace, because `Notation foo := Compare_dec.nat_compare.` will report as `nat_compare` being deprecated, at location the-entire-line.)  Anyway, here is a script that will do the replacement from the warning output, with a very simple sanity check:
```python
#!/usr/bin/env python2
from __future__ import with_statement
import sys, re, os

SANITY_CHECK=True

def backup(fname, ext='.bak', recursive=True):
    if not os.path.exists(fname): return
    if recursive: backup(fname + ext, ext=ext)
    os.rename(fname, fname + ext)

if __name__ == '__main__':
    log = sys.stdin.read().replace('\n', ' ')
    warnings = re.findall(r'File "([^"]*)", line ([0-9]*), characters ([0-9]*)-([0-9]*):\s*Warning: ([^ ]*)\s+is\s+([^ ]*)\s*.compatibility-notation,deprecated.',
                          log)
    reps = {}
    for fname, line, start, end, cur, rep in warnings:
        if fname not in reps.keys(): reps[fname] = []
        # line numbers are 1-indexed in Coq, 0-indexed in python; character numbers are 0-indexed in both
        reps[fname].append((int(line)-1, int(start), int(end), cur, rep))
    for fname, freps in reps.items():
        print('Updating %d identifiers in %s...' % (len(freps), fname))
        with open(fname, 'r') as f:
            lines = f.readlines()
        # reverse the replacements, so that if there are two on the same line, we replace the latter one first
        for linenum, start, end, cur, rep in reversed(freps):
            if SANITY_CHECK and ' ' in lines[linenum][start:end]:
                print('NOT replacing %s (%s) with %s' % (repr(lines[linenum][start:end]), cur, repr(rep)))
            else:
                lines[linenum] = lines[linenum][:start] + rep + lines[linenum][end:]
        backup(fname)
        with open(fname, 'w') as f:
            f.writelines(lines)
```

**Comment by Zimmi48** [comment]
Thanks Jason! I'll test both scripts and compare their reliability.

**Comment by JasonGross** [comment]
Updated version of python script:
```python
#!/usr/bin/env python2
from __future__ import with_statement
import sys, re, os

SANITY_CHECK=True
APPROX=True

def backup(fname, ext='.bak', recursive=True):
    if not os.path.exists(fname): return
    if recursive: backup(fname + ext, ext=ext)
    os.rename(fname, fname + ext)

if __name__ == '__main__':
    log = sys.stdin.read().replace('\n', ' ')
    warnings = re.findall(r'File "([^"]*)", line ([0-9]*), characters ([0-9]*)-([0-9]*):\s*Warning: ([^ ]*)\s+is\s+([^ ]*)\s*.compatibility-notation,deprecated.',
                          log)
    reps = {}
    for fname, line, start, end, cur, rep in warnings:
        if fname not in reps.keys(): reps[fname] = []
        # line numbers are 1-indexed in Coq, 0-indexed in python; character numbers are 0-indexed in both
        reps[fname].append((int(line)-1, int(start), int(end), cur, rep))
    for fname, freps in reps.items():
        print('Updating %d identifiers in %s...' % (len(freps), fname))
        with open(fname, 'r') as f:
            lines = f.readlines()
        # reverse the replacements, so that if there are two on the same line, we replace the latter one first
        for linenum, start, end, cur, rep in reversed(freps):
            if SANITY_CHECK and ' ' in lines[linenum][start:end]:
                if APPROX and cur in lines[linenum][start:end]:
                    print('APPROX: replacing %s with %s in %s' % (cur, rep, repr(lines[linenum][start:end])))
                    lines[linenum] = lines[linenum][:start] + lines[linenum][start:end].replace(cur, rep) + lines[linenum][end:]
                elif APPROX and cur in lines[linenum]:
                    print('APPROX: replacing %s with %s in %s (because it does not show up in %s)' % (cur, rep, repr(lines[linenum]), repr(lines[linenum][start:end])))
                    lines[linenum] = lines[linenum].replace(cur, rep)
                else:
                    print('NOT replacing %s (%s) with %s' % (repr(lines[linenum][start:end]), cur, repr(rep)))
            else:
                lines[linenum] = lines[linenum][:start] + rep + lines[linenum][end:]
        backup(fname)
        with open(fname, 'w') as f:
            f.writelines(lines)
```

**Comment by eponier** [comment]
I wanted to give it a try too. I wrote a python3 script based on @JasonGross 's initial script. The tests on corn and flocq went on pretty well (4 changes to do manually for corn, 0 for flocq). Sorry for the duplicate effort, but I was not sure if I had the motivation to finish my script properly.

```
#!/usr/bin/env python3
import sys, re, os
from collections import defaultdict

# Usage: ./convert.py logfile
# Uses the warnings in logfile to locate compatibility notation warnings,
# then search and replace to use the correct notations.

if __name__ == '__main__':
    if len(sys.argv) <= 1:
        print("Add a log file to the command line", file=sys.stderr)
        exit (-1)
    logfile = sys.argv[1]
    # process warnings one by one
    repl = defaultdict(list)
    with open(logfile) as fin:
        while True:
            # search for a line of the form "File ..." followed by another
            # line of the form "Warning ..."
            line = fin.readline()
            if not line:
                break
            warning1 = re.search(r'File "([^"]*)", line ([0-9]*), characters ([0-9]*)-([0-9]*):', line)
            if not warning1:
                continue
            line = fin.readline ()
            # the "[compatibility-notation,deprecated]" part may be rejected
            # to a third line
            warning2 = re.search(r'Warning: ([^ ]*)\s+is\s+([^ ]*)(?:\n|\s*.compatibility-notation,deprecated.)', line)
            if not warning2:
                continue
            filename = warning1.group(1)
            line = warning1.group(2)
            old_notation = warning2.group(1)
            new_notation = warning2.group(2)
            print('File {} at line {}: {} should be written {}.'
                    .format(filename, line,old_notation,new_notation))

            # line numbers are 1-indexed in Coq, 0-indexed in python
            # character numbers are 0-indexed in both
            numline = int(line) - 1
            last_char = int(warning1.group(4))
            repl[filename].append((numline, old_notation, new_notation, last_char))

    for filename, l in repl.items():

        # for each file, we correct warnings line by line
        with open(filename, 'r') as vfile:
            data = vfile.readlines()

    
        for numline, old_notation, new_notation, last_char in l:
            # When notation appears in multiline tactics, the line reported is
            # the starting line of the tactic, thus the notation may
            # be on a following line. In this case, though, the last character
            # is greater than the length of the line, so we can detect it.
            # When this occurs, we try to
            # find the corresponding notation in the following lines. Cannot
            # blindly rely on nb_sub = 0 to detect such cases, since, for some
            # reason, some warnings appear twice (and here we perform as many
            # substitutions as we can, we could try to perform at most one for
            # each warning to be more precise).
            while True:
                data[numline], nb_sub = re.subn(r'\b{}\b'.format(old_notation),
                                                new_notation, data[numline])

                if nb_sub > 0 or last_char < len(data[numline]):
                    break
                last_char -= len(data[numline])
                numline += 1
                assert (numline < len(data))

        with open(filename, 'w') as vfile:
            vfile.writelines( data )
```

**Comment by Zimmi48** [comment]
Thanks @JasonGross @eponier! You even saved me some work by testing already.
@eponier Could you open a PR on https://github.com/coq-community/corn with your patched version? As for the fixed flocq, if you push it somewhere, we can ask @silene to pull it.

**Comment by eponier** [comment]
Ok, I will do this evening.

**Comment by JasonGross** [comment]
Should we put the script in a gist somewhere and mention it in the changelog / the releasing doc when we merge the removal of compat notations?

**Comment by JasonGross** [comment]
To be clear, I'm talking about @eponier 's script; even my updated script does not handle multiline warnings.  (Though if you want to make the script a bit more robust, you could do some test to see if the character report is correct and not do find and replace in that case, e.g., test if the character locations are within the current line and define a substring that contains no spaces and `endswith` the name that is deprecated.)

**Comment by Zimmi48** [comment]
I think @eponier's script is robust enough given the result they got on large examples. Yes, it should be put in a gist with precise documentation on how to run it (i.e. making it explicit to run Coq 8.8 and how to redirect the make output so that the script can use it, etc.). Then PR #8374 should include a CHANGES entry explaining that the compat notations were removed, that people should use the compatibility-notation warnings from Coq 8.8 to prepare migrating to Coq 8.9 and that if they have more than a couple, they can consider using the script at this URL that will handle the change for them.

**Comment by eponier** [comment]
@Zimmi48 I opened a PR on https://github.com/coq-community/corn. I forked flocq on https://github.com/eponier/flocq and pushed the changes there.

**Comment by Zimmi48** [comment]
Thanks a lot @eponier! @silene could you pull https://github.com/eponier/flocq?

**Comment by Zimmi48** [comment]
Yes, indeed. I am just not aware of any bug tracker for coquelicot. But it only has 6 instances to fix so this should be straightforward.

**Comment by Zimmi48** [comment]
The removal of the compatibility notations from Flocq is not going to happen before the 8.9 release and therefore they cannot be removed from Coq 8.9 either. Let's make sure we properly advertise these warnings and the script fixing them so that it can be done in Coq 8.10.

**Comment by JasonGross** [comment]
@Zimmi48 How should we advertise the warnings and the script?  Should something (a CHANGES entry?) be added to #8634 ?

**Comment by Zimmi48** [comment]
Probably yes.

**Comment by JasonGross** [comment]
I've created a PR updating `CHANGES` at #8648.  I'm not confident in the wording, etc, but I figured it was better to create the PR than to not do so.

**Comment by Zimmi48** [comment]
In #8648, I requested that the gist be created, with documentation. It should also probably contain attribution to both you and @eponier.

@eponier: Do you want to be attributed by full name?

**Comment by eponier** [comment]
I wanted to take a look at @JasonGross 's suggestions for improvement. I can add the documentation too.

Should we create issues for the strange behaviours observed here? For the duplication of warnings, there is already https://github.com/coq/coq/issues/7128, but should we report the multiline warnings? They seem to occur with `unfold`, but not e.g. `fold`. Is `unfold` a special case, as suggested in https://github.com/coq/coq/issues/7128 about warning duplication?

@Zimmi48 I think it's preferable. I have just added my full name to my profile. It was available in the commits anyway.

**Comment by Zimmi48** [comment]
Did you mean to cite #7861? In any case, yes please open issues but I can't say that they will get fixed (when I tried with #7861, people were not happy with my solution, and I can understand this).

**Comment by eponier** [comment]
Oh, yes, I cited the wrong issue, I was indeed talking of https://github.com/coq/coq/issues/7861.

**Comment by herbelin** [comment]
@JasonGross @eponier: thanks a lot for the upgrading script. I used it with great success on [coq contribs](https://github.com/coq-contribs). The only "bug" I observed was the replacement of `Zeven.Zquot2` by `Zeven.Z.quot2` instead of `Z.quot2` but the bug is actually at the level of the warning which should have mentioned `Zeven.Z.quot2` instead of `Zquot2`.

It is a pity I did not try it earlier. We could have prevented more migration issues.

Side question to whose having taken care of the release: is the script visible enough? Shouldn't it be linked from the 8.10 release page? At minima, can I do something myself to help in this direction?

**Comment by Zimmi48** [comment]
>Side question to whose having taken care of the release: is the script visible enough? Shouldn't it be linked from the 8.10 release page? At minima, can I do something myself to help in this direction?

It is already quite well advertised in the release notes IMHO. Both in the 8.9 and 8.10 release notes, with a special highlight in 8.9.

**Comment by herbelin** [comment]
OK, I can indeed find it in the corresponding item at "https://coq.github.io/doc/V8.10.0/refman/changes.html#version-8-10". (Now struggling with a change related to coercions... suspectingly related to the order of imports but unsure yet.)

**Comment by Zimmi48** [comment]
Quite likely indeed!
