### ISSUE TITLE
`unshelve` is not documented

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8386]
#### Version

8.8.1

#### Description of the problem

I don't see `unshelve` listed in https://coq.inria.fr/refman/coq-tacindex.html#cap-u  (Sorry if this is a duplicate and it's been solved in master/8.8.2)

**Comment by Zimmi48** [comment]
Indeed, I recently saw this as part of a larger issue on undocumented tactics and I don't think it has been solved yet. However, if you are going to put a milestone, you also need an assignee. Are you willing to take care of documenting this?

**Comment by ejgallego** [comment]
cc: #6292

**Comment by Zimmi48** [comment]
Actually a duplicate of #4508.
