### ISSUE TITLE
A scope problem due to not using correct -top

### ISSUE THREAD

**Issue by pi8027** [coq/coq#8388]
#### Version

8.8.1 compiled with OCaml 4.07.0

#### Operating system

Debian GNU/Linux 9.5 (stretch)

#### Description of the problem

I have tried to hide some auxiliary definitions and lemmas for some tactics by using modules and found a scoping problem with Ltac in modules.

When I run the following proof script (which should be named `test1.v`) with Proof General and coqtop, the output of `tac` is `inside`. However, the output of `coqc test1.v` is `outside`. It seems to be an ambiguity problem of globalization.
```
Module test1.

Ltac tac' := idtac "inside".

End test1.

Ltac tac' := idtac "outside".

Ltac tac := test1.tac'.

Goal False.
Proof.
tac.
Abort.
```

**Comment by SkySkimmer** [comment]
This is an issue with PG (and coqide) not using the right -top. ie when running interactively without the -top command line option you get 
~~~coq
Definition foo := 0.

About foo.
(* Expands to: Constant Top.foo *)
~~~
but when compiling bar.v you get `(* Expands to: Constant bar.foo *)`.

I don't know if there's an issue for this on the PG repo.

**Comment by pi8027** [comment]
Thanks @SkySkimmer.

I renamed this issue and understood that it is not problem of Ltac. Here is another example:
```
Module test2.

Definition x := 1.

End test2.

Definition x := 2.

Definition y := test1.x.

Eval compute in y.
```

**Comment by pi8027** [comment]
I didn't follow the status of this issue, but solutions seem to be provided in #8991 and https://github.com/ProofGeneral/PG/issues/407. Thank you so much @SkySkimmer.
