### ISSUE TITLE
Error: `autounfold` tactic's behavior depends on a name of logical directory

### ISSUE THREAD

**Issue by anlun** [coq/coq#8390]
#### Version
8.8.1

#### Operating system
Linux (also reproduced on mac)

#### Description of the problem

`autounfold` tactic's behavior depends on a name of logical directory.

Consider `Main.v`:
```
Definition t := True.
Definition aabbcc := t.

Hint Unfold aabbcc : db.
Hint Unfold t : db.

Goal aabbcc.
Proof.
  autounfold with db.
  Show.
Admitted.
```

In the snippet, we expect that `autounfold` unfolds both definitions.
However, it unfolds only "aabbcc" if we compile the file by `coqc -R . G Main.v`:
```
1 subgoal

  ============================
  t 
```
and unfolds both definitions if we compile the file by `coqc -R . F Main.v`:
```
1 subgoal

  ============================
  True
```

**Comment by ppedrot** [comment]
Duplicate of #7812
