### ISSUE TITLE
Pcoq.Gram.entry_parse removed without any deprecation stage

### ISSUE THREAD

**Issue by silene** [coq/coq#8397]
#### Version

8.9

#### Description of the problem

Removed by commit ef29c0a927728d9cf4a45bc3c26d2393d753184e with the comment "It is unlikely that they are used by external plugins." Found by trying to compile an external plugin.

**Comment by Zimmi48** [comment]
@silene I suppose you meant to add the 8.9+beta1 milestone to it (I don't know otherwise how you can track these issues and make sure they are closed in time).

**Comment by silene** [comment]
Actually, I wanted to use the 8.9.0 milestone (which I have yet to create), but the 8.9+beta1 one is fine too.

**Comment by Zimmi48** [comment]
@silene The milestone actually already exists because someone (I don't remember who) requested it earlier on.

**Comment by silene** [comment]
No longer relevant since 8.9 has sailed.
