### ISSUE TITLE
Infinite loop in zify with dependent types

### ISSUE THREAD

**Issue by silene** [coq/coq#8399]
#### Version

8.8

#### Description of the problem

```
Require Import ZArith.
Record radix : Set := Build_radix
  { radix_val : Z;  radix_prop : (2 <=? radix_val)%Z = true }.
Lemma foo p Hp (beta := Build_radix (Zpos (xO p)) Hp) : False.
Fail Timeout 1 zify.
```

`zify_positive` creates the same hypothesis `(0 < 2 * Z.pos p)%Z` over and over, until Coq dies from memory exhaustion.

**Comment by vbgl** [comment]
After the rewrite of `zify` in #9856, it no longer loops on this example.
