### ISSUE TITLE
[doc] multiple coqdoc.css in the source tree

### ISSUE THREAD

**Issue by gares** [coq/coq#8404]
```shell
$ find . -name coqdoc.css | xargs md5sum
1a2707d6ae8e074cce4442c496552d50  ./tools/coqdoc/coqdoc.css
1ea9c912f98d7b5094f3f3232ead4b06  ./doc/common/styles/html/coqremote/sites/all/themes/coq/coqdoc.css
b975f72cc3bfebd7de424decd20014ba  ./doc/sphinx/coqdoc.css
2e5e585faaf1f01c4f1704e9a63b1ebc  ./doc/sphinx/_static/coqdoc.css
```

IIRC I'm the one that added the coqremote, since we don't use the regular coqdoc.css on the website (why?). The two about Sphinx.. I've no clue @maximedenes 

Bottom line, I'd like to tweak the css to make the doc of plugins/ssr/*.v look decent.

**Comment by Zimmi48** [comment]
Now this command gives:

```
b975f72cc3bfebd7de424decd20014ba  ./coqdoc.css
2e5e585faaf1f01c4f1704e9a63b1ebc  ./_static/coqdoc.css
```

**Comment by Zimmi48** [comment]
In the whole repo:

```
1a2707d6ae8e074cce4442c496552d50  ./tools/coqdoc/coqdoc.css
b975f72cc3bfebd7de424decd20014ba  ./doc/sphinx/coqdoc.css
2e5e585faaf1f01c4f1704e9a63b1ebc  ./doc/sphinx/_static/coqdoc.css
1ea9c912f98d7b5094f3f3232ead4b06  ./doc/common/styles/html/coqremote/sites/all/themes/coq/coqdoc.css
```

It seems that `tools/coqdoc/coqdoc.css`, `doc/sphinx/coqdoc.css` and `doc/common/styles/html/coqremote/sites/all/themes/coq/coqdoc.css` are identical up to whitespace. There should be only one and copy rules. On the other hand `doc/sphinx/_static/coqdoc.css` is very different and should probably be renamed.

**Comment by herbelin** [comment]
The one in `doc/common/styles/html/coqremote/sites/all/themes/coq/coqdoc.css` was used for some `serve-refman` target. This target disappeared in 72c35b31.

I would say that the reference, used by `coqdoc`, is the one in `tools/coqdoc` (even if some cleaning of deprecated lines should probably done), but I don't know the motivation for the other two.

**Comment by Zimmi48** [comment]
Thanks @Lysxia and @herbelin for bumping this issue which I had forgotten. I had arrived to the same conclusion and recently opened #11928.
