### ISSUE TITLE
Welcome flood from Coqide

### ISSUE THREAD

**Issue by silene** [coq/coq#8410]
#### Version

8.9

#### Description of the problem

Whenever a new tab is created, or whenever a buffer is retracted, Coqide displays on the standard error output the string `Welcome to Coq version (revision)`, which might amount to tens of lines at the end of a standard proof session.

**Comment by ejgallego** [comment]
This is likely due to the `-quiet` flag.

**Comment by gares** [comment]
This is a bit cryptic, can you elaborate and point to a fix?

**Comment by silene** [comment]
This regression was introduced by a2e34cd42ef6a4327e701416114c6b8b85a173d6:

    [ide] Don't set `quiet` on start.
    
    This makes `coqidetop` behavior consistent with the one of
    `coqtop`.
    
    This was likely needed in the past when Coq used to print all kind of
    stuff to stdout, including goal display. Now, it is not the case
    anymore and this flag mainly controls printing verbosity.

**Comment by ejgallego** [comment]
Sorry if I was not clear, I knew precisely which commit caused this, as we had the discussion we decided to disable the `-quiet` flag in `coqidetop`, as before it had a quite inconsistent behavior and we had a special flag just for printing fail.

If we enable `-quiet` again, the welcome message will be gone, however some other output will be also gone, for example, messages about `Fail`.

So we don't have a solution that makes everyone happy and I am against introducing a special, IDE-specific flag for random bits of display.

**Comment by ejgallego** [comment]
Ok, so finally a solution that doesn't make me too unhappy came to my mind, see #8826 @silene WDYT?

IMHO while not a perfect solution yet, it should indeed help taming this issue and other option-related alike.

**Comment by eponier** [comment]
I have just tested a recent CoqIDE (8.10 branch and master), and it seems to me that the "welcome flood" is there again. Is this normal? Shouldn't one of the linked PRs have solved the issue?

**Comment by ejgallego** [comment]
Nope, this is still pending, sorry; I'll get to it ASAP.

**Comment by maximedenes** [comment]
> Nope, this is still pending, sorry; I'll get to it ASAP.

@ejgallego can you give an ETA?

**Comment by maximedenes** [comment]
@ejgallego I just saw now that you silently removed your assignment. What does it mean?

**Comment by ejgallego** [comment]
It means I didn't plan to donate more time for this, but yeah I've reconsidered as I know what to do and is only 2 minutes.
