### ISSUE TITLE
opam package `coq.dev` broken in opam 1

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#8431]
#### Version

master

#### Operating system
Linux

#### Description of the problem

`opam install coq.dev` is broken on our CI:
```
[coq: dune build] Command started
[ERROR] The compilation of coq failed at "dune build @vodeps".
[WARNING] Directory /builds/FP/LambdaRust-coq/opamroot/system/lib/coq is not
          empty, not removing

#=== ERROR while installing coq.dev ===========================================#
# opam-version         1.2.2
# os                   linux
# command              dune build @vodeps
# path                 /builds/FP/LambdaRust-coq/opamroot/system/build/coq.dev
# compiler             system (4.02.3)
# exit-code            1
# env-file             /builds/FP/LambdaRust-coq/opamroot/system/build/coq.dev/coq-2451-736596.env
# stdout-file          /builds/FP/LambdaRust-coq/opamroot/system/build/coq.dev/coq-2451-736596.out
# stderr-file          /builds/FP/LambdaRust-coq/opamroot/system/build/coq.dev/coq-2451-736596.err
### stderr ###
# => no CoqIde will be built.
# [...]
#   Bytecode VM enabled         : true
#   Native Compiler enabled     : true
# 
#   Local build, no installation...
# 
# If anything is wrong above, please restart './configure'.
# 
# *Warning* To compile the system for a new architecture
#           don't forget to do a 'make clean' before './configure'.
```
Seems like the transition to dune was not done properly in all places?

**Comment by RalfJung** [comment]
Strangely, it is working fine on my system with opam 2. So maybe this is an opam-1-only issue?

**Comment by RalfJung** [comment]
The verbose log shows an actual error message:
```
+ dune "build" "@vodeps" (CWD=/builds/FP/iris-coq/opamroot/system/build/coq.dev)
-       ocamlc tools/.coq_dune.eobjs/coq_dune.{cmi,cmo,cmt} (exit 2)
- (cd _build/default && /usr/bin/ocamlc -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -rectypes -w -9-27-50 -g -bin-annot -I tools/.coq_dune.eobjs -no-alias-deps -o tools/.coq_dune.eobjs/coq_dune.cmo -c -impl tools/coq_dune.ml)
- File "tools/coq_dune.ml", line 184, characters 55-71:
- Error: Unbound value remove_extension
-        ocaml config/coq_config.ml
```
However, I have no idea how to interpret this. @ejgallego?

**Comment by ejgallego** [comment]
I am very surprised opam picks the `coq.opam` file, I understood this was not supposed to happen, right? [It should have picked the `opam` file]

In general `dev` packages are a headache and I understand these days `pin add $pkg --dev` is preferred; but I guess the best path of action given the point of the release we are at here is to fix `coq_dune`.

**Comment by ejgallego** [comment]
Ok, fix implemented. I was hopeful that we would branch and require 4.05 in 8.10 so this wouldn't be needed, but a bit of cut&paste doesn't hurt.

**Comment by RalfJung** [comment]
Ah indeed, my laptop is on Debian testing with ocaml 4.05 but CI is on Debian stable with ocaml 4.03.

> I am very surprised opam picks the coq.opam file, I understood this was not supposed to happen, right? 

I think it should use the opam file at https://github.com/coq/opam-coq-archive/tree/master/core-dev/packages/coq.dev, is that not what is happening?

**Comment by ejgallego** [comment]
> I think it should use the opam file at https://github.com/coq/opam-coq-archive/tree/master/core-dev/packages/coq.dev, is that not what is happening?

Yeah, I thought so but somehow it is now using the newly added `coq.opam` file which is intended for Dune use. The thing is that the `coq.opam` file will be likely removed in Dune 1.2 as we will instead declare `(package coq)` in `dune-project` and let the build system generate the `opam` stuff indeed.

**Comment by ejgallego** [comment]
> Why does the coq.opam file even exist?

Dune needs the file to define packages. This is scheduled to be lifted.

> Can we get rid of it until dune is considered the default build system? Because the fact remains that dune is used by opam 1 dev builds, and I guess we have to hope it will not be used when opam 1 gets the source from a tarball.

It would be a serious bug in OPAM if a non-dev build uses any other file than the one provided by the repository. In my view the problem is that the whole notion of `dev` package is broken. The most we could do is to modify `coq.opam` so that it doesn't Dune for building, but I don't deem that necessary.

**Comment by anton-trunov** [comment]
> In my view the problem is that the whole notion of dev package is broken. 

@ejgallego Hi Emilio! Out of curiosity, why it is broken in your opinion? Isn't it just like building stuff from `master` and living on the edge?

**Comment by RalfJung** [comment]
Unfortunately, our CI is still failing.  Now it says
```
# dune: option `-p' needs an argument
# Usage: dune build [OPTION]... [TARGET]...
# Try `dune build --help' or `dune --help' for more information.
```

**Comment by Zimmi48** [comment]
The problem *might* be that a dependency constraint on dune (>= 1.1) was forgotten in the `coq.opam` file.

**Comment by ejgallego** [comment]
> @ejgallego Hi Emilio! Out of curiosity, why it is broken in your opinion? Isn't it just like building stuff from master and living on the edge?

Well, I find that `add $package --pin dev` may be preferred, but the main problem is that updates are very inconsistent and it takes some effort to make versioning right. Also, very strange stuff happens like this one, why on earth is OPAM not using the `dev` file in the repository?

That being said, things can be worked out. In this case the problem seems that `package` is not defined so definitively we need an opam expert to know what is going on.

**Comment by ejgallego** [comment]
> # dune: option `-p' needs an argument

It seems the package field is not defined, I have no clue why OPAM does this, but you may try adding `package: "coq"` to the opam file.

**Comment by ejgallego** [comment]
> It seems the package field is not defined, I have no clue why OPAM does this, but you may try adding package: "coq" to the opam file.

Pfff, there is an obvious typo in the opam file, fixing...

**Comment by ejgallego** [comment]
It's a long story but due to a variety of reasons it is going to take a bit of effort to get a working opam install with Dune [Coq does really strange stuff with regards to ML paths for example]

My advice is to revert the OPAM file to one that uses `make` for now; it is unfortunate that the `opam` file in the `dev` package is not used.

**Comment by ejgallego** [comment]
> My advice is to revert the OPAM file to one that uses make for now; it is unfortunate that the opam file in the dev package is not used.

I am gonna be busy these next days, please feel free to submit a PR doing this.

**Comment by ejgallego** [comment]
Despite #8443 an additional couple of tweaks to installation of tools are needed so the resulting opam package can compile most contribs, the PR has been ready for a few days, will submit asap I reach my computer.
