### ISSUE TITLE
CoqIDE: Incorrect links in Help menu

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#8440]
On CoqIDE 8.8.1

`Help > Browse Coq Manual` sends me to https://coq.inria.fr/distrib/8.8.1/refman/ which is not found. The correct URL is https://coq.inria.fr/distrib/V8.8.1/refman/ (same for the Coq Library link)

**Comment by Zimmi48** [comment]
Thanks for the report. This has already been fixed in #8333 and backported to v8.8. This will be part of 8.8.2.
