### ISSUE TITLE
coq_makefile does not support -noinit flag

### ISSUE THREAD

**Issue by ruibaptista** [coq/coq#8450]
I am using Coq 8.8.1 for Windows. This is a feature request. coq_makefile supports neither the -noinit nor the -nois flags. CoqIDE does not support the -nois flag.

**Comment by Zimmi48** [comment]
I just tried `coqide -nois` and this worked. I would be surprised that this was a Windows-only problem.
As for `coq_makefile`, it supports a generic `-arg` option to send any given option to Coq, so `-arg "-nois"` should normally work.

@gares AFAICS `-arg` is not in the reference manual.

**Comment by gares** [comment]
You are right. It is printed by -h I believe.

**Comment by ruibaptista** [comment]
You are right. Thank you.

**Comment by Zimmi48** [comment]
See #8453.
