### ISSUE TITLE
[ssr] ssrpattern failure: variable n unbound

### ISSUE THREAD

**Issue by beta-ziliani** [coq/coq#8454]
#### Version
8.7.2 and 8.8.1

#### Operating system
Ubuntu 18.04

#### Description of the problem

The following fails with `Anomaly "Evar ?X5 was not declared`.  On an unrelated note, I don't understand this tactic, and there seems to be no documentation about it.

```
Require Import ssrmatching.ssrmatching.
Goal (if true then true else false) = true.
Proof.
  ssrpattern (if true then true else _).
```

**Comment by gares** [comment]
It should behave like `set := pattern`. It was added when only ssrmatching was part of Coq, eg SSR `set` was not there.

Here it seems that:
- the pattern is iota-reduced
- it matches the guard of the if in the goal
- a variable in the original pattern stays unresolved
(if you put "true" in place of "_" you see it capture the guard and the then branch).

I'll improve the error message, but I'm afraid you minimized your real bug too much...

**Comment by beta-ziliani** [comment]
I see. Is there a reason to it be iota-reduced?
What I really need is a way to abstract a term from another, using a term with evars that should be instantiated during the match. Do you have a recommendation for that?

**Comment by gares** [comment]
The iota reduction step has always been there, it predates my involvement in SSR so I can just speculate it is there to compensate for some "cruft" generated by type inference. Maybe @ggonthier or @amahboubi remember the exact reason. FTR the reduction is documented here https://coq.inria.fr/distrib/current/refman/proof-engine/ssreflect-proof-language.html#rewrite-redex-selection

I believe you are using the right tactic even if in this specific case the iota reduction makes you pattern silly. Also note that the goal is beta-iota (not delta) reduced by many tactics. Hence it is quite uncommon to have iota-redexes in the goal.

**Comment by beta-ziliani** [comment]
Let me take some more minutes from you @gares : why the following fails with `Error: Anomaly "variable n unbound.`

````
Goal forall n, match n with 0 => 0 | _ => 0 end = 0.
Proof.
  intro n.
  ssrpattern (match _ with 0 => _ | S n' => _ end).
````

**Comment by beta-ziliani** [comment]
If I change the last line to `ssrpattern (X in X = _)` it fails the same. This sounds like a real bug.

**Comment by gares** [comment]
It is a bug ;-)

https://github.com/coq/coq/blob/master/plugins/ssrmatching/ssrmatching.ml#L1369 should use `pf_env gl` and not `Global.env ()` in which `n` is not defined.

`set foobar := (match _ with 0 => _ | S n' => _ end).` works :-/

**Comment by beta-ziliani** [comment]
I'm lost now, why set doesn't use ssrpattern?
