### ISSUE TITLE
Anomaly: Not enough abstraction in fix body.

### ISSUE THREAD

**Issue by georgydunaev** [coq/coq#8459]
#### Version
8.8.1
#### Operating system
Debian 9 Stretch
#### Description of the problem

I am verifying theorems about the first order logic in Coq.
My crucial aim is to prove universal instantiation for vectors, i.e. exactly this lemma:
```coq
Lemma all_then_some (A:Type) : 
 forall (n:nat) (p:Fin.t (S n))
  (v : Vector.t bool (S n))
  (H : (Vector.fold_left orb false v) = false), 
 (Vector.nth v p) = false.

```
The link below contains the proved variant for Lists and almost proved variant for Vectors.

https://gist.github.com/georgydunaev/878cef33b2ed9614ab08e396ee73bb1b

The last theorem raises an anomaly and asks me to report. (I had to use "apply rect" because destruct caused usual error "Abstracting over the terms "n0" and "p" leads to a term … ")

(some additional information (about what was my aim) may be found in 
https://stackoverflow.com/questions/52247356/reasoning-about-the-boolean-vector-in-coq-based-on-the-value-of-its-sum-kind/52265988#52265988  )

**Comment by ppedrot** [comment]
A slightly smaller example:
```
Require Import Coq.Vectors.Vector.

Axiom exfalso : False.

Fixpoint all_then_someV (n:nat) (l:Vector.t bool n) {struct l}:
(Vector.fold_left orb false l) = false ->
(forall p, (Vector.nth l p  ) = false).
Proof.
intros.
destruct l.
inversion p.
revert h l H.
set (P := fun n p => forall (h : bool) (l : t bool n),
fold_left orb false (cons bool h n l) = false -> @eq bool (@nth bool (S n) (cons bool h n l) p) false).
revert n p.
fix loop 1.
unshelve eapply (@Fin.rectS P).
+ elim exfalso.
+ unfold P.
  intros.
  eapply all_then_someV.
  exact H0.
Defined.
```

**Comment by SkySkimmer** [comment]
Note if after `fix loop 1` you do `intros n;revert n` the anomaly goes away.

**Comment by ppedrot** [comment]
I think that `Inductive.check_nested_fix_body` should work on the whnf of its argument. Here it tries to destruct a lambda where it is only an application that reduces to a lambda. This might trigger loops though, dunno what to think about this.

**Comment by SkySkimmer** [comment]
Maybe I messed up but when I tried doing a whd_all the anomaly was still there.
