### ISSUE TITLE
[ci] Download of branch tarballs loses commit hash information.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8461]
https://github.com/coq/coq/pull/8348 introduced a more convenient download method for CI testing; however, when downloading a branch [for example, `master`], the scripts will build a URL using the branch name so the CI log won't contain information about the exact hash being tested.

In order to improve this, we should instead use `git ls-remote` and download an archive corresponding to a concrete hash, as hinted in #8348

**Comment by gares** [comment]
Doesn't the file name sent by github (or the root directory) contain the commit hash? I must have seen that somewhere.

**Comment by Zimmi48** [comment]
Possibly. Unfortunately we strip it in the current setting. But that could be another option to solve this issue.
