### ISSUE TITLE
Enlarging the size of the maintainer group and reducing the amount of responsibilities per developer.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#8476]
I'm opening this issue following a comment by @maximedenes at https://github.com/coq/coq/pull/7109#issuecomment-420934446. This is also related to #7694 and #8458.

For better reactivity, it would be good if developers were in charge of less components. I would like to encourage developers that are having a hard time taking care of all the PRs they are responsible of to step down from the components where they are not the only ones to have the required knowledge. Of course, this means that we should extend the number of maintainers. We should try to find contributors who can join the maintainer group and become code owners for component they have sufficient knowledge of. For more flexibility, it seems like it would be useful to more generally switch to code owner teams like we did for doc, CI and Nix.

**Comment by Zimmi48** [comment]
I myself am starting to feel quite overloaded with the things I am supposed to review. In particular, I'm the secondary code owner for Dune and thus I review all Dune PRs since they all come from @ejgallego. I would be delighted if we could form a dune-team and add more people to it (e.g. users of Coq who are interested in Dune as well) so that I can be less reactive. I see that @anton-trunov shows some interest in testing Dune. @anton-trunov Would you be OK to be part of such team? (See the merging doc at https://github.com/coq/coq/blob/master/dev/doc/MERGING.md; note it is not yet updated to account for the more and more common case of code owner teams that replace the primary-secondary model.)

**Comment by ejgallego** [comment]
Thanks @Zimmi48 , indeed I was feeling concerned about all the load I was putting on you :/

**Comment by Zimmi48** [comment]
@jfehrle Would you like to join the @coq/doc-maintainers team? It seems to me that you are now among the ones that know the documentation format and conventions quite well. You would only take care of the PRs that you are willing and feeling confident to review of course.

**Comment by jfehrle** [comment]
Sure.  I could help review for correct formatting as you suggest.  I could also review copy for clarity, standard English usage, etc.--though in some cases it may be easier for me to make the changes myself rather than (perhaps tediously) describe all the changes the submitter should make.  We can figure out the mechanics of doing that when we have a PR that would benefit from that.

Hopefully this won't mean a large flood of new email.  And it might be helpful if someone drew my attention to specific PRs that I could usefully review.

Regarding the team idea, maybe it would be useful to identify a lead person for each team who can help match reviewers to PRs and check that PRs get attention within a reasonable amount of time.  If a team has 3-4 or more maintainers, I think it's too easy for everyone to think someone else will handle the review.  Also it's not necessary for everyone on a team to review every PR, and it may not be ideal for github to put the entire team on every PR in their area.

**Comment by Zimmi48** [comment]
>easier for me to make the changes myself rather than (perhaps tediously) describe all the changes the submitter should make

GitHub has a new nice functionality to allow reviewers to do just that

>Hopefully this won't mean a large flood of new email. And it might be helpful if someone drew my attention to specific PRs that I could usefully review.

We can backtrack if you feel it is too much.

>Also  it's not necessary for everyone on a team to review every PR, and it  may not be ideal for github to put the entire team on every PR in their  area.

GitHub considers the PR reviewed by the team as soon as it has been reviewed by one member. Our experience is that it is working well in practice.

**Comment by SkySkimmer** [comment]
>GitHub has a new nice functionality to allow reviewers to do just that

We've been able to directly push to PRs longer than that (and it's much cleaner for changes that are more than 1liners I think), the main obstacle to using it is some sort of social resistance to pushing on other people's branches IMO.

**Comment by herbelin** [comment]
> the main obstacle to using it is some sort of social resistance to pushing on other people's branches IMO.

That would be convenient yes, but this also requires a protocol. I often push-force on my PR branches and that may override commits from others without noticing it. (When it effectively happened once, I could recover the commit hashes and re-pick them though.)

**Comment by SkySkimmer** [comment]
I use magit where the -f shortcut is actually --force-with-lease (see man git push), so that's not something I worry about. Non magit users may still have issues I guess.

**Comment by Zimmi48** [comment]
GitHub also added recently the displaying of the previous and the new commit in the timeline when people force-push so recovering is made even easier.

**Comment by Zimmi48** [comment]
Anyways, @jfehrle I'm adding you to the team. Let me know how it goes.

Regarding:
>Regarding the team idea, maybe it would be useful to identify a lead person for each team who can help match reviewers to PRs and check that PRs get attention within a reasonable amount of time.

I am this kind of lead person for the doc team right now, expanding the team is more about giving more chances to PRs to get merged quickly when I am less available (like last week).

**Comment by jfehrle** [comment]
>> Hopefully this won't mean a large flood of new email. And it might be helpful if someone drew my attention to specific PRs that I could usefully review.

> We can backtrack if you feel it is too much.

Well, in the last 13 hours I've gotten 53 messages about PRs that, judging from the subject line, are not things I have an opinion on or specific interest in.  It seems adding me to the maintainers list turned on getting all messages for the repository, which is too much--maybe not a good default.  I would like to get messages related to PRs that I've authored, am mentioned in, or require review by doc-maintainers.

I just turned off this setting:

![image](https://user-images.githubusercontent.com/1253341/48960488-de757900-ef21-11e8-8e7b-bd5c9ee66560.png)

but I didn't remove

![image](https://user-images.githubusercontent.com/1253341/48960493-ee8d5880-ef21-11e8-9923-b9b134900685.png)

I'll see if that does the right thing.

**Comment by jfehrle** [comment]
>>GitHub has a new nice functionality to allow reviewers to [let reviewers make changes to PRs]

> ... the main obstacle to using it is some sort of social resistance to pushing on other people's branches IMO.

We generally don't want developers to self-review and merge their own PRs.  If a reviewer makes changes to a PR, when should that mean getting another reviewer involved?  Should we just leave this as a judgement call for the first reviewer?

**Comment by SkySkimmer** [comment]
>I just turned off this setting:

That only affects what will happen if you get push access to other repos.
Use the "unwatch" button near the top of the page (next to "star" and "fork" buttons).

**Comment by Zimmi48** [comment]
Indeed, I am sorry that it made you "watch" the Coq repository. I didn't think it would given that you were already part of the pushers team. Please "unwatch" as suggested by @SkySkimmer and you will only receive notifications for threads where you are mentioned, that you subscribed to, or PRs where you are requested a review as documentation owner (this still includes most "feature" PRs however but that should still be a much lower number of notifications).

**Comment by jfehrle** [comment]
> We can backtrack if you feel it is too much.

It appears that if I'm selected as a possible reviewer, I automatically receive emails for every comment posted to those messages.  17 messages in the last 15 hours.  If possible, I'd like to keep receiving the review request messages but not get messages for every comment unless I've commented myself.  Is that doable?

In looking over a few of the PRs, I don't really know enough to review changes to the content (as opposed to formatting).  In that case, I shouldn't approve the PR on behalf of coq-maintainers, should I?  I can still comment on formatting, though, or say "formatting looks OK".

(Also, isn't there some place in the website that shows everything you're down for as a reviewer?)

**Comment by ejgallego** [comment]
I'm much afraid the only solution to manage github mail if you participate in an active is to either add filter [this can be done very precisely] or to disable mail altogether.

**Comment by Zimmi48** [comment]
>"formatting looks OK"

This would still be useful since the other people reviewing the PR are often able to review the content but not the formatting.

>(Also, isn't there some place in the website that shows everything you're down for as a reviewer?)

Did you mean "everything you've done"? If this is a question of crediting, this is indeed an important question that Emilio is trying to address in #9103. If this is a more practical question, I need to understand better what you mean.

Regarding finer-grained e-mail notifications, you may untick a few checkboxes in "Email notification preferences" in https://github.com/settings/notifications. However, this will apply both to the PRs where you were requested a review *and* the PRs which you authored. Unfortunately, GitHub doesn't allow much more than this. This is why people like me who are not keen of fine-tuning their mailbox prefer to use web notifications only.

**Comment by jfehrle** [comment]
> Did you mean "everything you've done"?

I meant every PR for which I'm a potential reviewer.  I'd like a screen that I can periodically examine to see what PRs I should consider reviewing.  Way too easy to lose track of things in email.  (FWIW, I have 109450 unread messages in my Outlook mailbox, dating back to 2003 :-)

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pulls/review-requested/jfehrle

**Comment by Zimmi48** [comment]
Also: https://github.com/pulls/review-requested (across repositories, accessible via the "Pull requests" link in the top GitHub bar).

**Comment by SkySkimmer** [comment]
We have moved on from the individual maintainer model, if there are still problems they deserve a new issue. Closing.
