### ISSUE TITLE
Add Sphinx "{| ... }"notation for syntax alternatives, e.g. for "A | B"

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8482]
#### Description of the problem

We need a Sphinx notation to represent alternatives in command/option syntax.  The best we can do at the moment uses parentheses, not so great:

![image](https://user-images.githubusercontent.com/1253341/45582860-316ce900-b86c-11e8-844f-f69f47852884.png)

I got the notation `{|  ... }` to work for HTML output with a very tiny change, but I'm not set up to test or modify the latex output option (Windows, lack of disk space).  I hope someone can pick up where I left off.

For example (look at the part after `Set @option`): 

```
.. cmd:: {? Local | Global | Export } Set @option {| @num | @string }
```

which renders as:

![image](https://user-images.githubusercontent.com/1253341/45258980-8b0a7a80-b377-11e8-9ce4-79adf3b628cb.png)

and IMHO looks a lot better.

**Comment by jfehrle** [comment]
The changes:

TacticNotations.g:
![image](https://user-images.githubusercontent.com/1253341/45582898-18186c80-b86d-11e8-9f86-bd13779f9b8d.png)

sphinx.py:
![image](https://user-images.githubusercontent.com/1253341/45582905-30888700-b86d-11e8-94ad-af149a9d241e.png)

README.rst:
![image](https://user-images.githubusercontent.com/1253341/45582923-6d547e00-b86d-11e8-8d24-149f1cd4becf.png)

Then run Antlr to update the parser.

**Comment by Zimmi48** [comment]
@cpitclaudel Following our discussion on Gitter, I took the liberty to assign you to this issue.

**Comment by cpitclaudel** [comment]
Ah, sorry, I missed this issue.  The syntax proposal is good, but I ended up needing a much larger change to be able to customize the way the `|` displays (which is important, because we want to distinguish between a literal `|` and an alternative.  I'll open a PR soon.
