### ISSUE TITLE
Type Classes Extracted to Type Classes in Haskell

### ISSUE THREAD

**Issue by HuStmpHrrr** [coq/coq#8484]
#### Version

$ coqtop -v
The Coq Proof Assistant, version 8.8.1 (August 2018)
compiled on Aug 29 2018 15:49:48 with OCaml 4.04.0

#### Operating system

$ uname -a
Linux rsg-pc326 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#### Description of the problem

The current extraction functionalities do not fully use the machinery from the Haskell language. Specifically, type classes can be extracted as type class definitions as well. Sure due to difference of between power of type systems, it might not always viable, but it would be nice to have at least a Vernacular command to instruct the extractor, or even better, some easy ones can be automatically done by Coq.

**Comment by SkySkimmer** [comment]
It's not really possible IMO. They share a name but they're not the same thing.

**Comment by JasonGross** [comment]
> Is there someplace where we can read about how extraction is implemented in coq?

There is some documentation at https://github.com/coq/coq/blob/master/plugins/extraction/README, and a bit more sprinkled throughout https://github.com/coq/coq/blob/master/plugins/extraction/extraction.ml.  I'll let @coq/extraction-maintainers comment more.

> Is it really gallina -> miniml -> language?

I think so.

> And what makes the Coq type class different? Could there be some overlap even if they are not same?

I think the relevant differences are

Coq | Haskell
-----|--------
non-unique instances allowed | only unique instances
can be either records or definitions | only (G)ADTs can be classes
instances can be inferred at elaboration time |
typeclasses can be filled without explicitly declaring any instances | typeclasses can only be filled with top-level instances
instances must be explicitly passed at runtime | instances cannot be given explicitly by the user

It's really the last point (or last two points) which makes Coq typeclasses incompatible with Haskell typeclasses.  Coq typeclasses are really just normal arguments with some extra hints to the elaboration/inference mechanism to allow inferring them automatically, while Haskell typeclasses, as I understand them, cannot be treated as normal arguments to functions.

Nothing in theory prevents extraction from emitting `class` and `instance` declarations, but there is no way to define a complete translation from Coq code to Haskell code that makes use of such classes and instances.
