### ISSUE TITLE
[api] [regression] Critical `pre_env` component `globals` has disappeared in 8.9

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8495]
In 8.8:
```
type globals = {
  env_constants : constant_key Cmap_env.t;
  env_inductives : mind_key Mindmap_env.t;
  env_modules : module_body MPmap.t;
  env_modtypes : module_type_body MPmap.t}
```
In 8.9/8.10:
```
type globals
```
this is a core API and breaks most of my developments.

**Comment by ejgallego** [comment]
This is an example of a bug that would have a hard time following the rule "no milestone without assignee", isn't it?.

Another one is for example #8027

**Comment by Zimmi48** [comment]
Indeed, this rule can bear a few exceptions.

**Comment by silene** [comment]
> This is an example of a bug that would have a hard time following the rule "no milestone without assignee", isn't it?

What is the reason for not assigning @SkySkimmer ?

**Comment by ejgallego** [comment]
There was a PR fixing this issue, it was however not accepted but the issue remains.

**Comment by vbgl** [comment]
Is there someone willing to address this issue soon before the 8.10 release? Otherwise I’ll postpone it. Thanks.

**Comment by ejgallego** [comment]
@vbgl so far we didn't agree on what the API for clients that need to use the environment should be, see discussion at #8228 , IMVHO we should bring back the old API until a new one is established [people is now using Obj.magic!] but if not I guess we can just postpone this, it's been already broken in 8.9

**Comment by ppedrot** [comment]
This has been solved, right? Closing.
