### ISSUE TITLE
[api] Deprecation of datatype constructors is incomplete.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8498]
Cleanup and modularization commits deprecated a few types that were either aliases or have been moved to a different place in the hierarchy. Unfortunately, deprecating the type doesn't deprecate its constructors. That means that plugins cannot just fix all the deprecation warnings and still work when the types are removed.

Thus, deprecation warning for most constructors whose types are deprecated must be added before the release.

@gasche , is there a way to place an attribute in a `type = ...` declaration such that the type and its constructors will be deprecated simultaneously?

**Comment by ejgallego** [comment]
#8499 is an example of what should systematically be done.

**Comment by gasche** [comment]
cc @alainfrish; I think that the feature wish is, when marking a variant/record declaration as deprecated, also mark the variants/fields as deprecated (also in the case of the re-export of an existing variant/record).
