### ISSUE TITLE
#8387 should be backported to v8.9

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8507]
#### Version

v8.9

#### Description of the problem

https://github.com/coq/coq/pull/8387 should be backported to the v8.9 (and then most of #8374 on top of that)

**Comment by ejgallego** [comment]
Up to now, these kind of issues where not necessary as the milestone should hint the RM what needs to be done

**Comment by JasonGross** [comment]
I think part of the complication here is that #8387 was merged before v8.9 was branched, but v8.9 was branched from a commit prior to #8387.

**Comment by Zimmi48** [comment]
Another complication is that #8387 was part of the 8.8.2 milestone. As soon as I put the 8.8.2 tag (hopefully tomorrow or on Monday) I'm going to open a PR backporting to v8.9 everything that is part of 8.8.2 and not in v8.9 yet.

**Comment by Zimmi48** [comment]
Fixed in #8583.
