### ISSUE TITLE
Addon dependency management in Windows installer

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#8528]
This is a follow up on the discussion in PR #8322.

Currently there is no dependency checking in the installer, so one can end up with an installation where addons required by another addon are not installed.

The goal is to automatically check dependencies in the NSIS installer.

**Comment by MSoegtropIMC** [comment]
I reopened it, because it also needs to go into master.
This will take a short while, because I must first properly add the addons in master (#8322).

**Comment by Zimmi48** [comment]
Well, I was assuming that you would include it in master from the beginning. Anyways, if this must be kept open, please remove the 8.8.2 milestone.

**Comment by MSoegtropIMC** [comment]
Fixed (in master) by #8322
