### ISSUE TITLE
Print Assumption anomaly (Assumptions of a parameter in a Module). kind: anomaly

### ISSUE THREAD

**Issue by georgydunaev** [coq/coq#8532]
#### Version
The Coq Proof Assistant, version 8.8.1 (September 2018)
compiled on Sep 5 2018 13:38:41 with OCaml 4.02.3

#### Operating system
Debian GNU/Linux 9 (stretch) 64-bit

#### Description of the problem

This code raises an anomaly.
```
Module Type Typ.
  Parameter Inline(10) t : Type.
End Typ.
Module  Terms_mod (SetVars : Typ).
Print Assumptions SetVars.t.
End Terms_mod.
```
It was discovered during the use of Coq.Structures.Equalities library.

> Anomaly
> "File "vernac/assumptions.ml", line 74, characters 19-25: Assertion failed."
> Please report at http://coq.inria.fr/bugs/.
>

Maybe this tiny example has no sense, but this anomaly leads to impossibility of showing the assumptions of the soundness theorem in my project:
https://github.com/georgydunaev/VerifiedMathFoundations/commit/a2e7ab6269c60cc172ddf49fd4dfafc04668bc71
Shall I do it in a different way?

**Comment by herbelin** [comment]
Thanks a lot for reporting this regression. A fix is available in #8535.
