### ISSUE TITLE
Full table of contents not shown at all in the on-screen table of contents

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8538]
#### Description of the problem

The reference manual includes a full table of contents under https://coq.inria.fr/distrib/current/refman/#table-of-contents, however that doesn't appear anywhere in the on-screen table of contents.  It should be shown--it is a standard part of almost all non-fiction books.  In fact, it should be a top-level entry even if that requires splitting the .rst file.

`Table of Contents` is part of the `Introduction` section but it doesn't show in the on-screen TOC on the left side:

![image](https://user-images.githubusercontent.com/1253341/45931141-3a218700-bf1e-11e8-8b96-c8507230c944.png)

**Comment by jfehrle** [comment]
PS It seems rather unconventional to have the indexes appear first in the table of contents.  No doubt this was intentional, but what was the thinking?

**Comment by anton-trunov** [comment]
> PS It seems rather unconventional to have the indexes appear first in the table of contents. No doubt this was intentional, but what was the thinking?

Hi @jfehrle. Issue #7764 is relevant here.

**Comment by Zimmi48** [comment]
IIRC the fact that the table of content doesn't appear as a section of the introduction chapter is a Sphinx bug, not something that we can do anything about. That being said, I feel like this TOC is much more important in the PDF version than in the HTML version which already has the left-bar TOC. Thus, I propose to close as "won't fix".

**Comment by jfehrle** [comment]
Well, at times I do want to skim the full table of contents, especially when I can't find some concept in the index.  The left-bar TOC is not conducive to skimming: you have to click to expand each chapter and subsection to see nested items, which appear in a relatively small section of the window.

Let me see if I can get it to work.

**Comment by jfehrle** [comment]
I have it working, save for two minor details:

- I want to add "Introduction" and "License" as top-level sections similar to "Credits", but I don't quite understand how to set up a file similar to `credit-wrapper.t`.  Can you explain when you have time?
- Incremental sphinx build doesn't pick up the change for the TOC; I had to `touch` the .rst files for them to show the change.  Fixing that is a nice-to-have.

![image](https://user-images.githubusercontent.com/1253341/45969761-87b6f600-bfe9-11e8-903a-f636876575c5.png)

**Comment by Zimmi48** [comment]
I'll leave it to @cpitclaudel to give you advice on this (but after we resolve the problems blocking 8.8.2 as this has lower priority :wink:).

**Comment by Zimmi48** [comment]
@jfehrle This is mostly solved, isn't it?

**Comment by jfehrle** [comment]
yup.
