### ISSUE TITLE
Notation printing bug when a notation exists both lonely and in scope

### ISSUE THREAD

**Issue by herbelin** [coq/coq#8551]
#### Version

All versions 8.X.

#### Description of the problem
```coq
Notation "# x" := (S x) (at level 20) : nat_scope.
Notation "# x" := (Some x).
Check fun x => (# x)%nat.
(* 
fun x : nat => # x
     : nat -> nat
*)
```
The printer fails to see that the default interpretation of the notation is the lonely notation: a `%nat` is missing around `# x`.

Fix coming as part of #8187.

**Comment by gares** [comment]
@herbelin is this fixed?
