### ISSUE TITLE
A transition path from Ltac to Ltac2?

### ISSUE THREAD

**Issue by herbelin** [coq/coq#8557]
Ltac1 and Ltac2 have different front-end in the sense that Ltac1 syntax has more implicit information than Ltac2 syntax (in the order of evaluation, in the use of coercions between arguments, in the use of the concrete syntax of tactics, ...)

I was wondering though whether it would make sense to plug Ltac1 interpreter on top of Ltac2 interpreter, and, maybe even also to reuse Ltac2 type-checker to type Ltac1 with automatic insertion of coercions.

This is certainly a bit naive view, but, would it be an interesting direction worth then to concentrate on the details of the feasibility of such migration path?

**Comment by ppedrot** [comment]
Migration is, I believe, quite easy if you stay in a reasonable fragment. On a typical proof (non-ssr) it is only a matter of cosmetic syntactic changes. There is a `Lists.v` example file in the Ltac2 tests.

Obviously if you start doing fancy stuff à la @JasonGross it is another matter, but for that you can already plug Ltac1 into Ltac2 in an incremental way through `ltac1:(...)` and `ltac2:(...)`. Writing a dynamically typed API to manipulate Ltac1 values from Ltac2 is easy, I should be doing that at some point, but it is going to make explicit the fact that Ltac1 runtime is *special*.

**Comment by JasonGross** [comment]
I still think the most annoying missing feature, syntax-wise, of Ltac2 is `idtac`/`printf`

**Comment by HuStmpHrrr** [comment]
Apologies if I am super uninformed. Is there any documentation on Ltac2, or is there going to be one when corresponding version releases, ideally in reference manual?

**Comment by ppedrot** [comment]
Currently Ltac2 is not released as a part of Coq, but the [Ltac2 repo](https://github.com/ppedrot/ltac2) does contain a bit of (terse) documentation.

**Comment by herbelin** [comment]
> There is a `Lists.v` example file in the Ltac2 tests.

I could not find it. You intend [here](https://github.com/ppedrot/ltac2/tree/master/tests)?

> Migration is, I believe, quite easy if you stay in a reasonable fragment.

My question is the other way round. I'm convinced by the type-checker of Ltac2. I find the ability to define proper Ltac2 types natural and powerful (rather than using an encoding in `constr`). I like the principled way with which Ltac2 is written. But I would like also to understand how to combine these advantages with Ltac1 syntax (whatever "special" or improvable it is) so that a transparent migration of the existing basis of Ltac1 code to the Ltac2 engine is possible. Probably, we would encounter subtleties to fix in corners by trying this approach, but, precisely, that could only be beneficial for the existing basis of Ltac1 code (as an example, binding Ltac1 syntax to Ltac2 would allow to insert coercions in Ltac1 code already at typing time).

**Comment by ppedrot** [comment]
I think we can close this.
