### ISSUE TITLE
STM: sending back a fat state

### ISSUE THREAD

**Issue by silene** [coq/coq#8609]
If we ever decide to be less noisy about fat states, here is a small script to test it, as it causes the warning to appear systematically.

```coq
Goal Prop.
Proof.
set (a := Prop).
Qed.
```

**Comment by gares** [comment]
I totally agree: #8643

**Comment by gares** [comment]
This is the check https://github.com/coq/coq/blob/master/stm/stm.ml#L1587
This is the safe_env comparison that fails https://github.com/coq/coq/blob/master/stm/stm.ml#L921
