### ISSUE TITLE
index.html.rst changes should force rebuilding every html file

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8619]
#### Description of the problem

index.html.rst changes should force rebuilding every html file since the short TOC is included in every html, but the incremental `make sphinx` doesn't check this dependency. This may be in the Sphinx code.  I didn't try to localize the problem.

To reproduce:

1. Complete a successful `make sphinx`.
2. Move the `license` entry before the `credits` entry in `index.html.rst`.
3. make sphinx

Make output:

```building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index
```

`.../coq/doc/sphinx/_build/html/index.html` shows the change of order, but the other chapters don't: 

![image](https://user-images.githubusercontent.com/1253341/46328869-ace5ce80-c5be-11e8-8ce7-859e5626615f.png)

![image](https://user-images.githubusercontent.com/1253341/46328919-0817c100-c5bf-11e8-9c00-c92a3a37286d.png)

Making a trivial change in `gallina-specification-language.rst` and rerunning `make sphinx` will show the new order for that chapter.

**Comment by jfehrle** [comment]
Filed per @cpitclaudel

**Comment by cpitclaudel** [comment]
I was suggesting a Sphinx bug report, not a Coq one ^^

**Comment by jfehrle** [comment]
Ah, you didn't say "a Sphinx bug"...
