### ISSUE TITLE
non-release coqtop stopped reporting its current commit

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#8621]
#### Version

$ coqtop --version
The Coq Proof Assistant, version 8.10+alpha (October 2018)
compiled on Oct 1 2018 23:35:50 with OCaml 4.07.0

It comes from a fresh OPAM `dev` installation. Basing on the time I started installation of the switch, it is either a7ba3df749df51ffdddce055bb630346522d88b0 or 05786b23cf0d031c93998c59f6f2f94d6049b027.

#### Operating system

```shell
$ head -1 /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
```

#### Description of the problem

`echo | coqtop` used to show git commit `coqtop` was built from, but it stopped:

```
$ echo | coqtop
Welcome to Coq 8.10+alpha (October 2018)

Coq < Coq < 
```

**Comment by Zimmi48** [comment]
Are you sue it used to do this? I think this worked only when you did this using a `coqtop` compiled from a git clone.

**Comment by anton-trunov** [comment]
Absolutely!

This is from my work laptop (macOS):

```shell
$ opam list | grep coq
coq                    dev          pinned to version dev at git+https://github.com/coq/coq.git
coq-mathcomp-ssreflect dev          Small Scale Reflection
coqide                 dev          IDE of the Coq formal proof management system.

$ coqtop --version
The Coq Proof Assistant, version 8.10+alpha (September 2018)
compiled on Sep 26 2018 12:03:30 with OCaml 4.06.1
$ echo | coqtop
Welcome to Coq guests-2-28.imdea:/Users/antontrunov/.opam/coq.dev/.opam-switch/build/coq.dev,master (b7cd70b5732d43280fc646115cd8597f2e844f95)

Coq < Coq <
```

**Comment by anton-trunov** [comment]
OPAM coq.dev uses Dune now. Can this be the reason? (CC @ejgallego)

**Comment by Zimmi48** [comment]
Ah right. It could absolutely be the reason.

**Comment by ejgallego** [comment]
Indeed, @anton-trunov , can you see if the version that works has a `revision` file in the `$lib/coq` folder?

I was planning to fix this in a different way but I can indeed make the Dune packages to generate the revision file if that's what the old packages were using.

**Comment by anton-trunov** [comment]
It does

```shell
$ cat /Users/antontrunov/.opam/coq.dev/lib/coq/revision
guests-2-28.imdea:/Users/antontrunov/.opam/coq.dev/.opam-switch/build/coq.dev,master
b7cd70b5732d43280fc646115cd8597f2e844f95
```

**Comment by ejgallego** [comment]
@anton-trunov https://github.com/coq/coq/pull/8627 should fix the issue, testing now.

**Comment by ejgallego** [comment]
Tested, it works.
