### ISSUE TITLE
practical-tools/utilities.rst "using coq as a library" is broken

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#8628]
kind: doc, infrasturcure
version: master as of an hour ago.
OS: Arch Linux, up to date as of yesterday

I tried to build a statically linked coq+ltac package following https://github.com/coq/coq/blob/4f85e540349004d4f9388a90061fc4a1541d9c40/doc/sphinx/practical-tools/utilities.rst#using-coq-as-a-library and it seems that it no longer works that way. I tried a bunch of not that educated guesses, and got stuck at `ocamlfind ocamlopt -thread -rectypes -linkall -linkpkg -package coq.toplevel -package coq.plugins.ltac -o my_toplevel.native` which succeeds but produces a binary that does nothing.

**Comment by Zimmi48** [comment]
cc @ejgallego 
I think you wrote that part.

**Comment by ejgallego** [comment]
Umm, well, you need a `main.ml` file such as https://github.com/coq/coq/blob/master/topbin/coqtop_bin.ml as to start a toplevel shell indeed.

**Comment by ejgallego** [comment]
So in fact the documentation is correct [well, it has some spurious `\` from the port from LaTeX] but you are not following it.

**Comment by andres-erbsen** [comment]
The documentation points to `toplevel/coqtop_bin.ml` which does not exist

**Comment by ejgallego** [comment]
Doc has been fixed in #8629
