### ISSUE TITLE
#6524 wrongly postponed to 8.10

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8633]
I already indicated in a coq-dev mail that #6524 must go into 8.9 or else API will be broken without notice.

It is not an option to defer the deprecation, the necessary imperative structures to support the deprecated API simply won't be there in 8.10.

**Comment by ejgallego** [comment]
Moreover, the PR help fixing a widespread critical issue found in plugin code, which like to call the printers in these files whereas they are only for internal / debug use.

**Comment by silene** [comment]
> It is not an option to defer the deprecation, the necessary imperative structures to support the deprecated API simply won't be there in 8.10.

So, you are saying that you merged something into master before even waiting that the deprecation warning went into 8.9? And now I am supposed to fix that mess?

**Comment by ejgallego** [comment]
> So, you are saying that you merged something into master before even waiting that the deprecation warning went into 8.9? And now I am supposed to fix that mess?

It is not merged yet but we certainly hope that we are not going to delay all the plans for 8.10 due to this trivial deprecation notices not getting in.

**Comment by ejgallego** [comment]
It would help if you were more communicate, as for a start, why against our advice you choose not to include #6524 in 8.9 , as request by mail in the category of "critical to get in".

**Comment by silene** [comment]
A deprecation notice does not qualify as critical for me. (But I am sure the next release manager will have a different opinion on that matter.) Anyway, I will backport #6524 . (Though I have to fix the many conflicts first.) But people should realize that adding more and more requests for backports is exhausting my time and pushing back the release. It has been repeated at the last two (three?) working groups that September 1st would be the branching point for 8.9.

**Comment by ejgallego** [comment]
> I have to fix the many conflicts first.

I will gladly provide a backport of the essential deprecation part if that would save your time. It is common for past release managers to request a backport from the author if there are conflicts.

> It has been repeated at the last two (three?) working groups that September 1st would be the branching point for 8.9.

Well, is the release plan written somewhere? Because words fly with wind, and certainly not even the milestones have a date set, so it is hard to remember if we said Sep. 1st or Oct 1st.

In past releases we used https://github.com/coq/roadmaps and it was very useful.

**Comment by Zimmi48** [comment]
Note that in the past some deprecation notices that were forgotten in the beta were backported between the beta and the final release. I just mean that it isn't the end of the world if something doesn't get in before the beta as long as we don't lose the track of it.

**Comment by silene** [comment]
Merged as of e28dce187c055141682cec56d0d8193470a24a5f.

**Comment by ejgallego** [comment]
Merci !
