### ISSUE TITLE
Missing documentation for sphinx installation

### ISSUE THREAD

**Issue by charguer** [coq/coq#8641]
I have not found the documentation for the installation of sphinx, which is needed for compiling the new documentation. This information probably should go in the main INSTALL file, (e.g. instructions for CoqIDE are also there).

I have tried (on Ubuntu):
```
  sudo apt-get install python3-sphinx python-pip
  pip install --user sphinxcontrib-bibtex sphinx-rtd-theme-0.4.1
```
but I'm still getting stuck with at least two kind of errors, first missing file encoding information e.g. at the head of file tools/coqrst/repl/coqtop.py and aisicolors.py, and second this error:
```
  File "/home/charguer/shared/mycoq2/doc/tools/coqrst/repl/coqtop.py", line 37
    def __init__(self, coqtop_bin=None, color=False, args=None) -> str:
  SyntaxError: invalid syntax
```
I might not be using the right version of python or packages, but I'm lacking information on what's needed.

**Comment by Zimmi48** [comment]
You need to look into https://github.com/coq/coq/blob/master/doc/README.md. This documentation is linked from the README of Coq. If you have trouble with this documentation please let us know but I don't know how it could possibly be put in clearer light.

**Comment by Alizter** [comment]
Documentation looks up to date to me. Please reopen if you feel otherwise.

**Comment by Alizter** [comment]
@Zimmi48 Can you confirm?

**Comment by Zimmi48** [comment]
I've opened a PR to add the link that I proposed. But indeed, the installation instructions exist and are accurate.
