### ISSUE TITLE
Coqide doesn't start (opam2/macos)

### ISSUE THREAD

**Issue by vsiles** [coq/coq#8682]
#### Version
The Coq Proof Assistant, version 8.8.1 (October 2018)
compiled on Oct 9 2018 15:33:00 with OCaml 4.02.3

#### Operating system
Macos Sierra / opam 2

#### Description of the problem

Hi ! I just installed a fresh opam2 (from brew) and coq (from https://coq.inria.fr/opam/www/using.html). `coqc` and `coqtop` seem to work fine, but `coqide` does not display anything. I also have no output at all on the console. If I kill it, I get:
```
$ coqide
^Cgtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
```

If I try to give some arguments like `--help`, I still don't see anything, and I can't ^c it, I have to use `kill pid`.

Any suggestions on how to solve/diagnose the issue ?

Best,
V.

**Comment by ejgallego** [comment]
Hi @vsiles , I am not expert on Mac, can you see if using master helps:
```
opam pin add coq https://github.com/coq/coq.git
opam pin add coqide https://github.com/coq/coq.git
```

**Comment by vsiles** [comment]
I'm not used to opam yet, but I managed to update ocaml to the required version, and your first command fails with:
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] The compilation of coq failed at "/Users/vsiles/opam-coq.8.8.1/opam-init/hooks/sandbox.sh build
        dune build -p coq -j 7".

#=== ERROR while compiling coq.8.8.1 ==========================================#
# context     2.0.0 | macos/x86_64 | ocaml-base-compiler.4.05.0 | pinned(git+https://github.com/coq/coq.git#59de2827)
# path        ~/opam-coq.8.8.1/4.02.3/.opam-switch/build/coq.8.8.1
# command     ~/opam-coq.8.8.1/opam-init/hooks/sandbox.sh build dune build -p coq -j 7
# exit-code   1
# env-file    ~/opam-coq.8.8.1/log/coq-46401-d0f245.env
# output-file ~/opam-coq.8.8.1/log/coq-46401-d0f245.out
### output ###
# [...]
# Warning:
# Cannot open /Users/vsiles/opam-coq.8.8.1/4.02.3/.opam-switch/build/coq.8.8.1/_build/install/default/theories
# [cannot-open-path,filesystem]
# While loading initial state:
# Warning:
# Cannot open /Users/vsiles/opam-coq.8.8.1/4.02.3/.opam-switch/build/coq.8.8.1/_build/install/default/plugins
# [cannot-open-path,filesystem]
# File "./theories/Init/Notations.v", line 128, characters 0-32:
# Error:
# File not found on loadpath : ltac_plugin.cmxs
# Loadpath: /Users/vsiles/opam-coq.8.8.1/4.02.3/.opam-switch/build/coq.8.8.1/_build/default
#
```

**Comment by ejgallego** [comment]
Can you try with OCaml 4.05.0? Coq master needs that version I'm afraid.

**Comment by ejgallego** [comment]
But already you gave us a big hint. Try to install coq Indeed in a more modern switch such as 4.07.0 it is likely that such an ancient gtk / ocaml version is problematic

**Comment by vsiles** [comment]
I'll try to update ocaml and let you know

**Comment by ejgallego** [comment]
opam switch create 4.07.0 should do the trick

**Comment by vsiles** [comment]
I installed 4.06.1 because 4.07 doesn't work atm and I have the same behavior:
```

$ opam list
# Packages matching: installed
# Name              # Installed       # Synopsis
base-bigarray       base
base-threads        base
base-unix           base
camlp5              7.06.10-g84ce6cc4 Preprocessor-pretty-printer of OCaml
conf-gtksourceview  2                 Virtual package relying on a GtkSourceView system installation
conf-m4             1                 Virtual package relying on m4
conf-pkg-config     1.1               Virtual package relying on pkg-config installation
coq                 8.8.2             Formal proof management system.
coqide              8.8.2             IDE of the Coq formal proof management system.
lablgtk             2.18.6            OCaml interface to GTK+
num                 1.1               The legacy Num library for arbitrary-precision integer and rational
ocaml               4.06.1            The OCaml compiler (virtual package)
ocaml-base-compiler 4.06.1            Official 4.06.1 release
ocamlfind           1.8.0             A library manager for OCaml
```

**Comment by ejgallego** [comment]
So that's not with master, right? If so please try with master (using pinning) please. Also, report what does `coqide -debug -stm-debug` output please.

**Comment by vsiles** [comment]
I thought it was, but I'll double check.

**Comment by vsiles** [comment]
The compilation fails as before with 4.06 and 4.07

```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
⊘ removed   coqide.8.8.2
⊘ removed   coq.8.8.2
∗ installed dune.1.3.0
[ERROR] The compilation of coq failed at "/Users/vsiles/opam-coq.8.8.1/opam-init/hooks/sandbox.sh build
        dune build -p coq -j 7".

#=== ERROR while compiling coq.8.8.2 ==========================================#
# context     2.0.0 | macos/x86_64 | ocaml-base-compiler.4.06.1 | pinned(git+https://github.com/coq/coq.git#59de2827)
# path        ~/opam-coq.8.8.1/4.06.1/.opam-switch/build/coq.8.8.2
# command     ~/opam-coq.8.8.1/opam-init/hooks/sandbox.sh build dune build -p coq -j 7
# exit-code   1
# env-file    ~/opam-coq.8.8.1/log/coq-8925-d6b0cc.env
# output-file ~/opam-coq.8.8.1/log/coq-8925-d6b0cc.out
### output ###
# [...]
# Warning:
# Cannot open /Users/vsiles/opam-coq.8.8.1/4.06.1/.opam-switch/build/coq.8.8.2/_build/install/default/theories
# [cannot-open-path,filesystem]
# While loading initial state:
# Warning:
# Cannot open /Users/vsiles/opam-coq.8.8.1/4.06.1/.opam-switch/build/coq.8.8.2/_build/install/default/plugins
# [cannot-open-path,filesystem]
# File "./theories/Init/Notations.v", line 128, characters 0-32:
# Error:
# File not found on loadpath : ltac_plugin.cmxs
# Loadpath: /Users/vsiles/opam-coq.8.8.1/4.06.1/.opam-switch/build/coq.8.8.2/_build/default
#
```
(same kind of output of 4.07)

**Comment by ejgallego** [comment]
I see, that's a different bug indeed due to the strategy to locate the libraries. Will be fixed when #8421 is merged / finished.

So try then to get the `-debug -stm-debug` from 8.8.1 [or even 8.9~beta]

**Comment by vsiles** [comment]
```
[vsiles@vsiles-mbp:~/opam-coq.8.8.1]
$ coqide -debug -stm-debug
(Spawn  ,95355) EXEC: /Users/vsiles/opam-coq.8.8.1/4.02.3/bin/coqtop -main-channel stdfds -control-channel 127.0.0.1:57332:57333 --xml_format=Ppcmds -async-proofs on -ideslave -debug -stm-debug
(Spawn  ,95355) PID 95358
(Spawned,95358) starting controller thread
gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
[DEBUG] Start eval_call Init None
[DEBUG] End eval_call
[DEBUG] End of Coqide.main
95358:master:0] defining 1 (cache=Y)
95358:master:0] setting cur id to 1
(Spawn  ,95358) EXEC: /Users/vsiles/opam-coq.8.8.1/4.02.3/bin/coqtop -main-channel stdfds -control-channel 127.0.0.1:57336:57337 --xml_format=Ppcmds -debug -stm-debug -toploop proofworkertop -worker-id proofworker:0 -async-proofs-worker-priority low
(Spawn  ,95358) PID 95359
(Spawned,95359) starting controller thread
95359:proofworker:0:0] defining 1 (cache=Y)
95359:proofworker:0:0] setting cur id to 1
95358:master:0] Initializing workers
95358:master:3] waiting for a task
[pid 95358] <-- Init None
[pid 95358] --> GOOD 1
[DEBUG] Handling coqtop answer
[DEBUG] Start eval_call SetOptions [(["Printing";"Coercions"],false);(["Printing";"Matching"],true);(["Printing";"Notations"],true);(["Printing";"Existential";"Instances"],false);(["Printing";"Unfocused"],false);(["Printing";"Implicit"],false);(["Printing";"All"],false);(["Printing";"Universes"],false)]
[DEBUG] End eval_call
[pid 95358] <-- SetOptions [(["Printing";"Coercions"],false);(["Printing";"Matching"],true);(["Printing";"Notations"],true);(["Printing";"Existential";"Instances"],false);(["Printing";"Unfocused"],false);(["Printing";"Implicit"],false);(["Printing";"All"],false);(["Printing";"Universes"],false)]
[pid 95358] --> GOOD
[DEBUG] Handling coqtop answer
```

**Comment by ejgallego** [comment]
The init sequence looks good I think. I'm afraid you'll need help from OSX people :/

**Comment by vsiles** [comment]
Ok :D Thanks for the help anyway !

**Comment by herbelin** [comment]
Hi Vincent,

I checked and it works for me on MacOS X 10.11.1, coqide 8.8.1 (and master), lablgtk 2.18.6, ocaml 4.06.1, gtk+ 2.24.29 or 2.24.31 (both are installed by brew, I don't know which is used).

The error `gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead` is always displayed for me at exit time, so it is probably not relevant here.

Did it work before? With which version of coqide? Installed by which way?

**Comment by ejgallego** [comment]
Maybe you have some old config file in `$HOME` that's making GTK / CoqIDE confused?

**Comment by vsiles** [comment]
I have gtk+: stable 2.24.32_2  by brew, and ocaml 4.02.3 lablgtk 2.18.5 coq/coqide 8.8.1 by opam 
I'll try to chcek for the old configs but I'm pretty sure I don't have: the mac is 1 month old and I just installed gtk via brew yesterday

**Comment by vsiles** [comment]
I really don't get what's happening. I just found mbeffara coq-au-vim plugin, I think I'll stick with it :D Thanks for the help !
If I can rule some more commands to help debugging, don't hesitate to ask me to do so.

**Comment by vbgl** [comment]
Does running CoqIDE on macOS require a X environment (à la [XQuartz](https://www.xquartz.org/))?

**Comment by vsiles** [comment]
Note that the .dmg from Coq's website works correctly (with the usual issue that default keybindings are messing with the Mac WM :D)

**Comment by herbelin** [comment]
> Does running CoqIDE on macOS require a X environment (à la XQuartz)?

That's a good question. Personally, I run CoqIDE without having installed the X11 app, but I have brew "cask" xquartz installed. So, if not done, do `brew cask install xquartz`.

> the usual issue that default keybindings are messing with the Mac WM :D)

There is an open PR to fix that, #8567. You can try copy `ide/MacOS/default_accel_map` from the Coq archive to your `~/.config/coq/coqide.keys` file.

**Comment by vsiles** [comment]
@herbelin @vbgl Thanks ! I installed xquartz and now it is correctly displaying the UI. I don't know if opam can/should check for that, but that's missing from the installation page.

**Comment by herbelin** [comment]
How did you install gtk+? I guess that it is at this time that installing xquartz should have been required (or at least strongly suggested).

**Comment by vsiles** [comment]
Using brew when after opam complained it was missing. I don't know if that matters, but I installed using `brew install`, not `brew cask install` (I just discovered that one)

**Comment by ejgallego** [comment]
I guess we can close this issue then.

**Comment by MSoegtropIMC** [comment]
For those running into such issues in the future, here are some notes of someone who switched to Mac recently:

- To me homebrew looks like opening some really huge security holes - it appears to makes paths which are in the search path of elevated processes writable to everyone.
- MacPorts seems not to have this issue, so I used MacPorts to install dependencies
- In MacPorts, there is an X11 and a Quartz variant of gtk3 and as far as I can tell the X11 variant is the default. The X11 variant requires an X server to run CoqIDE, while the Quartz variant uses OSX native drawing, which is preferable (to me). The following command explains the situation quite well:

```
$ port variants gtk3
gtk3 has the variants:
   quartz: Enable native macOS graphics support
     * conflicts with x11
   universal: Build for multiple architectures
[+]x11: Enable X11 support
     * conflicts with quartz
```

The right variant is installed with
```
sudo port install gtk3 +quartz
sudo port install gtksourceview3 +quartz
sudo port install adwaita-icon-theme
```

You can check what you have installed with
```
$ port installed | grep quartz
  cairo @1.16.0_0+quartz+x11 (active)
  gtk3 @3.24.12_0+quartz (active)
  gtksourceview3 @3.24.11_0+quartz (active)
  pango @1.42.4_0+quartz+x11 (active)

$ port installed | grep x11
  cairo @1.16.0_0+quartz+x11 (active)
  gd2 @2.2.5_0+x11 (active)
  giflib @4.2.3_0+x11 (active)
  glib2 @2.58.3_0+x11 (active)
  gnuplot @5.2.7_0+aquaterm+luaterm+pangocairo+qt+wxwidgets+x11 (active)
  graphviz @2.40.1_2+pangocairo+x11 (active)
  pango @1.42.4_0+quartz+x11 (active)
  tk @8.6.9_2+x11 (active)
```
The above is the status which lead to a properly working CoqIDE with opam. I also have wxMaxima installed which needs the remaining x11 libraries - you might not have them. If you have some wrong variants of GTK3 installed, do e.g.
```
$ sudo port uninstall adwaita-icon-theme
$ sudo port uninstall gtksourceview3
$ sudo port uninstall gtk3
$ sudo port uninstall inactive (only required if you did upgrades in-between)
$ sudo port uninstall leaves (repeat this until you get an error)
```
Then install the quartz version as explained above. For me this resulted in errors when updating the font cache when installing some fonts. Running the font cache update command separately 2 times fixed this, but I guess one can also just delete the font cache and rebuild it.

You can also check the shared library dependencies of your coqide binary as follows:
```
otool -L /.opam/default/bin/coqide
:
/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
:
```
If your binary does not depend on Cocoa, you likely have compiled it for X11. When the correct (quartz) gtk3 is installed, a straight forward opam install works. In summary this sequence should work:
```
# Install MacPorts
$ xcode-select —install
# Download package file from https://www.macports.org/install.php
# Double click package file in finder
$ export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
$ sudo port -v selfupdate

# Install OCaml and Opam via MacPorts
$ sudo port install ocaml
$ sudo port install opam
$ opam init
# possibly switch opam to a different OCaml here, but for me the system version did work fine
$ opam install dune
$ opam user-setup install 

# Install Coq via Opam
$ opam pin add coq 8.10.1

# Install CoqIDE prerequisites via MacPorts and compile CoqIDE with opam
$ sudo port install gtk3 +quartz
$ sudo port install gtksourceview3 +quartz
$ sudo port install adwaita-icon-theme
$ opam install coqide
```
If others read and try this, please give me some feedback. I cannot easily bring my Mac back into its original state, so I am not 100% sure I didn't miss anything. I will update the Install on Mac instructions accordingly as soon as I got some feedback.
