### ISSUE TITLE
Failure of post-action to definition shows the `no fix_exn` message

### ISSUE THREAD

**Issue by herbelin** [coq/coq#8685]
#### Version

From Coq 8.5 to current master.

#### Description of the problem

```
Fail Coercion c := eq_refl 0.
(* 
c is defined
Future: no fix_exn.
You have probably created a Future.computation from a value without passing the ~fix_exn argument.  You probably want to chain with an already existing future instead.
The command has indeed failed with message:
Error: c is not a function.
*)
```
I found this while working on unifying the code for declaration of lemmas and declaration of regular definitions. I wanted to backport the fix 2aafc6f1 of #3780 to `DeclareDef` but this started to generate this error. I then realized that I could reproduce a similar message with the above.

The code of `DeclareDef.declare_definition` already calls the coercion hook with a `fix_exn` and I have difficulties to understand what the exact problem is. Could it be a problem of propagating the `fix_exn` in chains of hooks? What is the right way to use `fix_exn`? Passed to the hook as in `DeclareDef.declare_definition` or applied to the final exception, as in `Lemmas.save`?

**Comment by ejgallego** [comment]
#5479 the only solution I know for `fix_exn` is indeed to remove it and make the traversal of the document to happen forward. Not a small task.

**Comment by herbelin** [comment]
And isn't there a simple maybe short-term fix, like it seems to me that @gares made in #3780?

**Comment by gares** [comment]
We could just drop the warning about fix_exn, it is only relevant to a developer and essentially says "in this stack trace someone is catching A and raising B without passing the exn-info from A to B". Irrelevant for a user, my bad it is still there.

**Comment by herbelin** [comment]
So, if I find a way to make it dependent on a debug flag, it could just remain in case the option `-debug` is passed?
