### ISSUE TITLE
Numerous "Coqide internal error: Source ID 99999 was not found when attempting to remove it" dialogs

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8715]
#### Description of the problem

When doing ordinary editing operations in CoqIDE, I got errors such as the following about 100 times over the course of 2-3 hours.  I don't remember such a severe problem in 8.7 (the previous official build I was using), but I do think I saw some of these.  Has anything changed?

The message appears to come from GTK, not from OCaml code.

@MSoegtropIMC, would you try this in your environment?  I'm starting CoqIDE from the Windows command line, not a bash, if that makes any difference.

![image](https://user-images.githubusercontent.com/1253341/46848670-08267680-cda0-11e8-9324-d3b24631c5da.png)

**Comment by MSoegtropIMC** [comment]
This explains why I haven't seen it so far - I am 99% using the 64 bit version. I agree that 32/64 bit info should be in the version info. I will ask Andrew for his experience - as far as I know he is using Coq IDE and 32 bit (because it is a bit faster for cache reasons).

**Comment by gares** [comment]
I've tried to track down the issue in the past but unfortunately I could not find the origin. I think I managed to disable the popup, it should be visible only if coqide is run with -debug.

**Comment by jfehrle** [comment]
Thanks @gares, I was running with -debug in some cases--I didn't consider that as a relevant variable.

**Comment by ejgallego** [comment]
@jfehrle can you still reproduce this bug?

**Comment by jfehrle** [comment]
You want me to try using 8.9 or master?

**Comment by jfehrle** [comment]
If @herbelin checks in the labgtk3 version, that may change the behavior a lot.

**Comment by ejgallego** [comment]
`master` or `gtk3`

**Comment by jfehrle** [comment]
I haven't yet been able to build coqide locally, even after several attempts.
