### ISSUE TITLE
[ci] [gitlab] `expire_in` not set in all targets.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8735]
As of today, the CI build produces some "keep forever" artifacts. IMHO, there is not point in doing so, and we should add the corresponding `expire_in` to all targets.

**Comment by SkySkimmer** [comment]
Why?

**Comment by ejgallego** [comment]
> Why?

Why do we want to keep artifacts forever?

**Comment by ejgallego** [comment]
For example, what's the utility of keeping the Nix ones?

**Comment by Zimmi48** [comment]
Why don't we define `expire_in` at top-level?

**Comment by ejgallego** [comment]
Still remaining:
- `doc-template`
- `test-suite-template`
- `nix-template`
- `test-suite:egde:dune:dev`

**Comment by Zimmi48** [comment]
> Why don't we define `expire_in` at top-level?

**Comment by SkySkimmer** [comment]
Keeping test suite logs is deliberate.

**Comment by Zimmi48** [comment]
Then it should be kept as well in the nix-template since this is also about test suite logs.
