### ISSUE TITLE
CoqIDE: Help / Browse xxx links to 8.6.1 version documents, not current version

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8749]
#### Description of the problem

CoqIde menu items Help/Browse Coq Manual and Help/Browse Coq Library bring up the 8.6.1 documents.

Looks like the URLs come from the file coqiderc.  Probably not updated when you install/build a new version.

**Comment by jfehrle** [comment]
Also, when I try to update the ref man URL in the Preferences dialog, it appears to apply
"http://coq.inria.fr/distrib/V8.8.2/refman/" but seems to lose that change, dropping the "V".  Strange.  A similar URL works for the library.

**Comment by Zimmi48** [comment]
>Looks like the URLs come from the file coqiderc. Probably not updated when you install/build a new version.

That's indeed a correct analysis of the situation. This file is generated once and for all when you first launch CoqIDE. I also find this a bit unfortunate.

>Also, when I try to update the ref man URL in the Preferences dialog, it appears to apply
"http://coq.inria.fr/distrib/V8.8.2/refman/" but seems to lose that change, dropping the "V". Strange. A similar URL works for the library.

I didn't understand this sentence but the URL you gave is indeed correct. There used to be compatibility symlinks but nowadays, we only publish with the `V`.

**Comment by Alizter** [comment]
Looks like all coq versions from 8.11 to 8.15 have this fixed. Therefore closing.

**Comment by jfehrle** [comment]
I think you meant "master" instead of 8.15 (which won't exist for another 6 months).

**Comment by jfehrle** [comment]
Also the URL `https://coq.inria.fr/distrib/V8.14.0/refman/` doesn't exist because it's not yet released (while `https://coq.inria.fr/distrib/V8.13.0/refman/` does).  But I agree it works fine for 8.13.

**Comment by Zimmi48** [comment]
> I think you meant "master" instead of 8.15 (which won't exist for another 6 months).

When you build `master` it tells you version 8.15+alpha. It is fine to designate this development version like this, especially given that it is more precise than `master` when reading back in a few years.
