### ISSUE TITLE
Temporary regression in universe constraints registration

### ISSUE THREAD

**Issue by herbelin** [coq/coq#8785]
#### Version

In versions 8.8.0-8.8.2

#### Description of the problem

I encountered a regression introduced in 2e30531e7 (before 8.8.0) and fixed in f53890d (before 8.9) with the following example:
```coq
Universe u v w.
Inductive invertible {X:Type@{u}} {Y:Type} (f:X->Y) : Prop := .

Inductive FiniteT : Type -> Prop :=
  | add_finite: forall T:Type@{v}, FiniteT T -> FiniteT (option T)
  | bij_finite: forall (X:Type@{w}) (Y:Type) (f:X->Y), FiniteT X ->
    invertible f -> FiniteT Y.

Set Printing Universes.

Axiom a : False.
(*
Constraint v <= u.
Constraint v <= w.
*)
Lemma finite_subtype: forall (X:Type) (P:X->Prop),
  FiniteT X -> (forall x:X, P x \/ ~ P x) ->
  FiniteT {x:X | P x}.
Proof.
intros.
induction H.

destruct (H0 None).
destruct a.

pose (g := fun (x:{x:T | P (Some x)}) =>
  match x return {x:option T | P x} with
    | exist _ x0 i => exist (fun x:option T => P x) (Some x0) i
  end).
apply (bij_finite _ _ g).
apply IHFiniteT.
intro; apply H0.
destruct a.


pose (g := fun (x:{x:X | P (f x)}) =>
  match x with
  | exist _ x0 i => exist (fun x:Y => P x) (f x0) i
  end).
apply bij_finite with _ g.
apply IHFiniteT.
intro; apply H0.
destruct a.

Qed.
(* 
Illegal application: 
The term "@invertible" of type
 "forall (X : Type@{u}) (Y : Type@{Top.4}),
  (X -> Y) -> Prop"
cannot be applied to the terms
 "{x : T | P0 (Some x)}" : "Type@{v}"
 "{x : option T | P0 x}" : "Type@{max(Set,v)}"
 "g"
   : "{x : T | P0 (Some x)} ->
      {x0 : option T | P0 x0}"
The 1st term has type "Type@{v}"
which should be coercible to "Type@{u}".
*)
```
I did not succeed in making it smaller. Expanding one of the `pose` makes it succeed. Replacing `apply with` makes it succeed. Removing one of the two cases of the proof by cases on `H0` makes it succeed. Adding explicitly one or the other of the two constraints between `v`, `u` and `w` makes it succeed.

This is not anymore open (for 8.9) and I'm going to submit a PR to add a test.

PS: There is a CoqIDE bug too. If one goes directly to the end and click on the gears, the `Qed` succeeds. If one goes line by line if fails. Maybe worth a distinct issue?

**Comment by SkySkimmer** [comment]
>fixed in f53890d

That commit isn't supposed to change behaviour, what is going on?
