### ISSUE TITLE
Report on the 8.7 to 8.9 compatibility of packages in coq-contribs

### ISSUE THREAD

**Issue by herbelin** [coq/coq#8793]
This is a summary about porting "contribs" to 8.7 and 8.9, and to produce opam packages for them.

#### Porting

I discontinued the following "obsolete" packages: `jprover`, `legacy-ring` (`ring` version 2), `legacy-field` (`field` version 1), `rational` (`ring` version 1), string (source of current `string`), `micromega` (empty directory). If no objection from @ybertot, I would also remove `recursive-definition` which is subsumed by `Function` and `Equations`.

Five developments have moved from `coq-contribs` to `coq-community`: `aac-tactics`, `lemma-overloading`, `stalmarck`, `bertrand`, `qarith-stern-brocot`.

I failed to (easily) upgrade relatively to the following Coq changes:
- change of representation of real constants: `high-school-geometry` (I renounced)
- change of naming of hypotheses after removal of option `Standard Proposition Elimination Names`: `finger-tree` (I temporarily renounced)
- change in the API:
  - `counting`: due to removal of a declaration hook (this is a amusing plugin though, I'm probably going to submit a way to continue it)
  - `ergo`: due to difficulty in managing hash-tables on `econstr` (I temporarily renounced, but this is an interesting plugin)

Something should be done to remove `intuitionistic-nuprl` which is maintained upstream. Also for `relation-algebra` which is maintained upstream too.

#### Opam packages

There are scripts in `coq-contribs/coq-contribs/META` to create opam packages. I produced them for all contributions which compile in 8.6, 8.7 and 8.8. We could in theory weaken the constraints when a package is known to compile with several versions, but it is still to do.

I basically reused the encoding of coq-contribs style of metadata into opam which Matej did. Don't hesitate to make suggestions on conventions (keywords, format of authors, ...). I used 8.X.0 as version number but that's maybe not a very good idea. Something like 1.0+8.8 may be better?

Note: `lemma-overloading` (in coq-community) does not have an opam package.

#### Web page

I have a(n unpolished) tool to automatically build a web page for a package (with coqdoc-style file browsing). To be continued.

#### Upgrading to 8.7

The main difficulties to upgrade to 8.7 have been:
- the change of representation of constants in `R` (pretty difficult, was requiring thinking, sometimes gives simplification)
- adding `Require Extraction`/`Require FunInd` (relatively easy, but often)
- `Save` -> `Qed` (easy, sed-style)
- change of behavior of `{  }` in notations
- port of ocaml file (mainly the `EConstr` move, representation of locations)

#### Upgrading to 8.8

Upgrading to 8.8 was easy. The main changes were:
- move of `Local` in prefix position (easy, sed-style)
- port of ocaml file (representation of locations, various renamings such as `Term` -> `Constr`, etc., no thinking needed in general)
- one exceptional need for `Set Typeclasses Axioms Are Instances`
- a change of `omega` wrt to the use of section variable (difficult to track)
- only `fingertree` was using `Unset Standard Proposition Elimination Names` in practice 

#### Upgrading to 8.9

Upgrading to Coq 8.9 seems to require much more changes. Here is a (first) list of them, with the two first items very common:

- `Implicit Arguments` -> `Arguments`
- adding an argument to `fix` or `cofix`
- `Quote`: write Ltac code instead?
- adding `Require` for primitive notations (easy)
- adapting to removal of `ROmega`, `omega can't solve`
- port of ocaml file (`Prop` -> `Set`/`Prop`, various renamings, such as `kind_of_term` -> `kind`, `identifier` -> `Id.t`, etc.)

What tools or recommendations to give for upgrading to 8.9 wrt the above changes?

**Comment by JasonGross** [comment]
> adding Require for primitive notations (easy)

To make the easiest one easier, I think the changelog mentions a script that will do this automatically (if not, I can dig up the script from commit messages of PRs I've submitted to fix this)

How much of the behavior of Quote that is used can be replaced by reification by parametricity/pattern?

**Comment by herbelin** [comment]
> How much of the behavior of Quote that is used can be replaced by reification by parametricity/pattern?

It is used in - only - two contribs but I did not investigate yet how easy it would be to change it. At the current time, I just made an overview to evaluate what to do.

> To make the easiest one easier, I think the changelog mentions a script that will do this automatically (if not, I can dig up the script from commit messages of PRs I've submitted to fix this)

Well, it worked beautifully to insert a `Require Import String` just in front of other `Require`!

Unfortunately, in this case, it introduced another problem: it declares also `++` as a string notation for `String.append` and this overrides the notation `++` for `List.app`.

Re-adding `Require Import Datatypes` does not work. Would there be a way to activate the string notation only at importing of a submodule of `String`?

**Comment by JasonGross** [comment]
> Would there be a way to activate the string notation only at importing of a submodule of String?

Yes.  Feel free to submit a PR that stuffs `Declare ML Module ` in some submodule of String.  Alternatively, pass `-compat 8.8`.

**Comment by herbelin** [comment]
Yes, this works by using
```coq
Module Export StringSyntax. Declare ML Module "string_syntax_plugin". End StringSyntax.
```
in `String.v` and using
```coq
Require Coq.Strings.String.
Import String.StringSyntax.
```
in the file to compile.

**Comment by herbelin** [comment]
> Are there other "obsolete" packages that you had discontinued earlier or is that the full list? I suggest making this information explicit by:

I removed completely `string` and `micromega` (respectively redundant and empty).

I finally kept  `jprover`, `legacy-ring`, `legacy-field`, `rational`, and actually also `recursive-definition`, but marking them with an unmaintained status.

There are no other unmaintained packages (in the sense of stopping to make them compiling with Coq). Of course, there is also the case of the 3 "contribs" which are on coq-community and the 4 packages which are maintained upstream (possibly on coq-community): `corn`, `math-classes`, `relation-algebra`, `lemma-overloading` and `intuitionistic-nuprl`.

> updating the README with a prominent mention that the contrib is archived and is not receiving new compatibility updates;

There is now a README for all those 5 unmaintained packages.

> using the archiving feature of GitHub (keeps the repo but display as archived / read-only);

I don't know what it is, but I don't think this is necessary.

> removing the contrib from the list of contribs at https://github.com/coq-contribs/coq-contribs (no need to continue artificially applying updates that are common to all contribs).

Thus, I don't remove the unmaintained packages (even if pointless to maintain) from this list, but the README explains their status.

I did not push all changes yet, as there seems to be a confusion on what to do with `bertrand`, `qarith-stern-brocot` and `stalmarck`. To deal with them mechanically, it is easier for me to keep them as submodule of `coq-contribs/coq-contribs`, even if they are not any more a repository of `coq-contribs` (since in `coq-community`).

I'd be ok to remove them from `coq-contribs` when it is clear that `coq-community` comes with an architecture for automation (i.e. for checking compilation automatically and for producing opam packages automatically). I see that you started to add ci to coq-community, but I did not look at how it is done.

**Comment by Zimmi48** [comment]
>I removed completely string and micromega (respectively redundant and empty).

Well technically, the micromega repository was not fully empty: it had a git history of before being moved to Coq.

>corn, math-classes, lemma-overloading

These three ones should not appear anywhere in coq-contribs if I'm not mistaken.

> > using the archiving feature of GitHub (keeps the repo but display as archived / read-only);
> 
> I don't know what it is, but I don't think this is necessary.

See an example with the four last repositories here: https://github.com/coq/

>I did not push all changes yet, as there seems to be a confusion on what to do with bertrand, qarith-stern-brocot and stalmarck. To deal with them mechanically, it is easier for me to keep them as submodule of coq-contribs/coq-contribs, even if they are not any more a repository of coq-contribs (since in coq-community).

Indeed, you are the maintainer so feel free to do it in the way you feel is best.

**Comment by herbelin** [comment]
> Well technically, the micromega repository was not fully empty: it had a git history of before being moved to Coq.

This history was short (37 commits).

Actually, my "completely removed" is only as submodules of the [coq-contribs](http://github.com/coq-contribs/coq-contribs) repository. It is not as repositories of the [coq-contribs](http://github.com/coq-contribs) organization. I shall consider archiving them as repositories as you showed.

The distinction between the collection of submodules listed in the repository `coq-contribs` (which e.g. includes the `coq-community` package `bertrand`, but not the `coq-contribs` repository `legacy-ring`) and the collection of repositories in the organization `coq-contribs` (which on the other side includes `legacy-ring` but not `bertrand`) should probably be clarified...

Currently, the role of the former is mainly to uniformly manage various actions on repositories, such as checking compilation, producing releases, producing opam packages.

**Comment by ejgallego** [comment]
What should we do with this issue?

**Comment by ejgallego** [comment]
I suggest this information is added to some file in the coq-contribs repository or in `doc/` in Coq, IMHO the report has done its function so closing.
