### ISSUE TITLE
Spurious name collisions with Automatic Introduction

### ISSUE THREAD

**Issue by jashug** [coq/coq#8819]
#### Version

Coq 8.8+beta1

#### Description of the problem

```
Theorem foo (_ : nat) (H : bool) : True.
(* Error: H is already used. *)
```

To perform automatic introduction, `Theorem` uses `intro` for anonymous parameters, which automatically assigns `H` to the `nat` parameter, and then proceeds to use `intro H` for the second, named, `bool` parameter. This is in `vernac/lemmas.ml` `start_proof_with_initialization`.

We could consider using `intros ? H` instead?

**Comment by jashug** [comment]
After #8820 goes in, this behavior can be improved by tweaking `auto_intros_tac` to call `intros`

**Comment by ejgallego** [comment]
LGTM

**Comment by jashug** [comment]
Typeclass generalization ` ``{TypeClass A B}` (I can't figure out how to write a single backtick...) has the potential to add a complicating factor, in we need to make sure the names `A` and `B` are included as fixed binder names.
Note to self to investigate where the desugaring of the backtick binder happens.
