### ISSUE TITLE
Simple typo in the document

### ISSUE THREAD

**Issue by wkwkes** [coq/coq#8837]
### version
master

### Description of the problem
`t~0` in https://github.com/coq/coq/blob/master/doc/sphinx/language/cic.rst#normal-form may be a typo of `t_0`.

**Comment by Zimmi48** [comment]
@wkwkes Good catch! Do you want to make a PR fixing this?

**Comment by wkwkes** [comment]
Thanks. Yes, I'll make a PR.

I also noticed that right arrows in the third example of https://coq.inria.fr/distrib/current/refman/language/cic.html#inductive-definitions should be `→` instead of `->`.
So, I'll fix this too.
