### ISSUE TITLE
Primitive records with anonymous fields

### ISSUE THREAD

**Issue by vbgl** [coq/coq#8838]
Currently (tested with Coq 8.8.2), it is not possible to define a “primitive record” with anonymous fields. Here is a dummy example:

```
Set Primitive Projections.
Record r := { n : nat ; _ : n = n }.
(*
r is defined as a non-primitive record
Warning: The record r could not be defined as a primitive record
[non-primitive-record,record]
n is defined
*)
```

I would like to better understand why this is the case. Is it by accident? due to some technical debt? for theoretical reasons?

In particular, I guess that it would be possible to have η-conversion for such records: the fact that the projection has no user-facing name should not imply that the kernel cannot refer to that projection.

**Comment by ppedrot** [comment]
The problem is that you definitely need to be able to refer to this projection in some syntactic way. Currently and for bad reasons, the kernel uses a mix of names and indices to refer to projections, but it can be done with indices only. In that case, it becomes imaginable to have a syntax `r.(0)` to refer to the first field and so on.

**Comment by SkySkimmer** [comment]
Not being able to refer to the projection except through destructing lets or `match ... with Build_foo n anon => ...` is one thing, but also the system itself internally relies on there being a constant for each projection. This will change eventually but it still WIP for now.

**Comment by ppedrot** [comment]
> This will change eventually but it still WIP for now.

Yes, I was not claiming this could be done overnight, but my point was rather that there is no good reason for this not to be the case.

**Comment by SkySkimmer** [comment]
Question has been answered.
