### ISSUE TITLE
Regression following typeclass functionalization.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#8848]
#### Version

8.10+alpha (788ff535ed27d5142cd18878f8478bfc161945cd)

#### Description of the problem

[This file](https://github.com/coq/coq/files/2526134/bug.v.gz) compiles fine with be144dcaa1d1d8ff22e9e39f49fd247e813ac1f8 but fails to compile with 788ff535ed27d5142cd18878f8478bfc161945cd. It seems to indicate a regression introduced in #8741.

Note that this file depends on SSReflect. Sorry for failing to minimize further.

Found thanks to the CI cron job of lemma-overloading (see coq-community/lemma-overloading#14).

**Comment by mattam82** [comment]
I found the issue. I inverted two arguments by mistake during my cleanup :/
