### ISSUE TITLE
[feature request] String syntax notations should live in user-land, not plugin land

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8853]
Now that Numeral Notations has been merged, it would be nice to be able to also register string and ascii syntax notations in userland.

Internally, a setup similar to numeral notations should be fairly straightforward.

I propose the following setup for user-land:
- Add a `char` type to `Coq.Init` that has 256 constructors.
- Add a command `String Notation <inductive> <parsing> <printing> : scope` which registers a string syntax notation
- Add standard library functions converting back and forth between `ascii` and `char`, and between `string` and `list char`.

The parsing function should have type `list char -> <inductive>` or `list char -> option <inductive>`.  The printing function should have type `<inductive> -> list char` or `<inductive> -> option (list char)`.  The standard library should register an ascii printing notation that parses only singleton lists, and also a string printing notation.

Ideally, there would also be support for parsing/printing things like `list ascii` and `list char` as strings; I'm not sure how hard this would be to support internally.

**Comment by Zimmi48** [comment]
What is the relation to #8483?

**Comment by JasonGross** [comment]
I think it is mostly independent of #8483.  There is a bit of overlap in terms of "what type should the primitive syntax for ascii recognize?"  (Although it is also possible to be mostly agnostic on that, and have a separate `Register` invocation for each of the 256 primitive ascii characters.)  But I think mainly this enhancement would make the stdlib `string` type less special.

**Comment by herbelin** [comment]
> Now that Numeral Notations has been merged, it would be nice to be able to also register string and ascii syntax notations in userland.

That makes sense, yes. The setup looks good.

**Comment by gmalecha** [comment]
@JasonGross What's the performance of the byte type? I did some experiments with it a little while ago and it seemed much slower than using something like `N` because the functions that process it are so large, e.g. the equality checker is 2^16 cases.

**Comment by andres-erbsen** [comment]
I did some experiments a while ago using byte^numbytes instead of word and observed significant (3x) speedup over the bedrock word type (though using the 2^8-case versions functions that go through bool^8). I think the difference comes from "some experiments" being an ill-defined measure; is there something specific that we should benchmark?
