### ISSUE TITLE
`make distclean` does not clean `ide/xml_lexer.cmi`

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#8865]
#### Version

Current master: 0ac673e562c34245e4e48efc428d808e917be79b

#### Operating system

Linux.

#### Description of the problem

After a `git pull` to the current master, and a `make distclean`, I ended up with the following error when running `./configure -local; make`:

```
Error: The implementation ide/protocol/xml_lexer.ml
       does not match the interface ide/xml_lexer.cmi:
       The value `lowercase' is required but not provided
```

It appears that `make distclean` does not clean enough.

**Comment by SkySkimmer** [comment]
I don't think we're going to fix this.

**Comment by Zimmi48** [comment]
For later readers: do `make clean` before doing `git pull` or use `git clean -dfx` at any time (watch out if you have untracked files). `make clean` cannot remember of the history of where files used to be.
This kind of issues will be solved once and for all when we remove the make-based system and switch to Dune only.
