### ISSUE TITLE
vm_compute crash on int31_rect

### ISSUE THREAD

**Issue by vbgl** [coq/coq#8885]
#### Version

Crash witnessed on Linux x86_64 with Coq versions 8.5pl3, 8.6.1, 8.7.2, 8.8.2, some recent master.

#### Description of the problem

The following example crashes (segmentation fault).

```
From Coq Require Import Cyclic31.

Definition Nat `(int31) := nat.
Definition Zero (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _: digits) := 0.

Check (eq_refl (int31_rect Nat Zero 1) : 0 = 0).
Check (eq_refl (int31_rect Nat Zero 1) <: 0 = 0).
```

Maxime pretends such a crash can be turned into a proof of False.

Spoiler: the compilation of the `int31_rect` constant occurs before the retroknowledge is informed that `int31` is the int31 type. The fix is trivial and coming soon.

**Comment by herbelin** [comment]
Why does it crash? Doesn't the absence of retroknowledge block the execution?

**Comment by vbgl** [comment]
Compilation to bytecode occurs before retroknowledge is there: the third argument to `int31_rect` is expected to be a constructed value (`I31 a b c d …`).

Evaluation (when executing the last `Check` above) occurs after retroknowledge is told about the type `int31`: it thus gives to `int31_rect` a plain OCaml integer. In a nutshell: the bytecode expects a pointer, it receives an integer. Crash follows.

**Comment by vbgl** [comment]
Yes. Changing the retroknowledge does not invalidate byte code already generated.
