### ISSUE TITLE
`lia` fails in the presence of dependent hypotheses

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#8898]
#### Version

The Coq Proof Assistant, version 8.8.2 (September 2018)
compiled on Sep 30 2018 13:38:22 with OCaml 4.05.0

#### Operating system

Linux

#### Description of the problem

The `lia` tactic fails when some of the hypotheses is used in another hypothesis. For example, when having `(p : 0 < 0) (H: p = p)`, it will fail because `p` appears in `H`.

I discovered this issue by replacing all occurrences of  `omega` into `lia` in some project. If I understood well, the plan is to eventually deprecate `omega` in favor of `lia`, so it would be good if `lia` was at least as strong as `omega`.

I suppose the solution is easy: `lia` should prune such dependent hypotheses in a first stage.

```coq
Require Import Omega Psatz.

Lemma foo : forall (p : 0 < 0) (H: p = p), False.
Proof.
  intros p H. omega. (* succeeds *)
Restart.
  intros p H. Fail lia. (* fails *)
Restart.
  intros p H. clear H. lia. (* succeeds *)
Qed.
```

**Comment by ppedrot** [comment]
That's strange, I thought @maximedenes fixed this one...

**Comment by SkySkimmer** [comment]
>`omega. (* fails *)`

but it doesn't?

**Comment by robbertkrebbers** [comment]
> > omega. (* fails *)
> 
> but it doesn't?

That was a fypo: `omega` indeed succeeds, fixed the description of the issue.

**Comment by Blaisorblade** [comment]
Dup of #7878.

> That's strange, I thought @maximedenes fixed this one...

@ppedrot So #7886 will supposedly be fixed by #7878... in 8.11?

**Comment by ppedrot** [comment]
I guess so :/

**Comment by maximedenes** [comment]
I'll try to extract the fix.

**Comment by maximedenes** [comment]
See #7878.

**Comment by Zimmi48** [comment]
Didn't you mean #7886?

**Comment by maximedenes** [comment]
Indeed, edited, thanks!

**Comment by rnrand** [comment]
Presumably these are the same bug, but the contradiction (or part of the contradiction) appearing in the goal breaks things as well (so we need an `exfalso` rather than a `clear`.)

```
Lemma foo : forall (p : 0 < 0) (f : 0 < 0 -> nat), f p = S (f p) .
Proof.
  intros. omega. (* succeeds *)
Restart.
  intros. Fail lia. (* fails *)
Restart.
  intros. exfalso. lia. (* succeeds *)
Qed.

Lemma bar : forall (m n : nat) (p : m < n) (q : n < m)  (f : m < n -> nat), f p = S (f p) .
Proof.
  intros. omega. (* succeeds *)
Restart.
  intros. Fail lia. (* fails *)
Restart.
  intros. exfalso. lia. (* succeeds *)
Qed.
```

(The second popped up in the wild for me.)
