### ISSUE TITLE
dune build system should provide a list of convenient targets

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#8900]
This is discussed in #8729, but I couldn't find an issue that states it explicitly. Please close if I missed it.

In my daily development routine, I need aliases for the following:
- all plugins individually (I don't want to have to explicitly remember which vo file I have to compile)
- states (likewise having to spell out `theories/Init/Prelude.vo` is a big no)
- miniopt / pluginsopt (I don't want to wait for the thermodynamical death of the universe to check that ml files are ok)
- printers
- tools

Other people probably have different needs, we should gather them in this PR.

**Comment by ejgallego** [comment]
Most of the targets should be able to do now [or are already present], however my typical way of working with Dune is a bit different than make, first, because the dev profile uses opaque by default so in most cases way less recompilation is needed, second, because a very typical setup is just a continuous build with `--watch` so I don't need to worry too much other than setting up your editor properly. Of course if battery life is a concern that's another thing.

In fact, I am not sure I like to have such a gazillion of fine-grained targets. They are a bit of a burden to properly maintain unless they correspond to truly logical installable units, and indeed the time gain vs doing a normal build is just not there.

**Comment by SkySkimmer** [comment]
How many cores do you throw at compilation?

Gaëtan Gilbert

**Comment by ejgallego** [comment]
> How many cores do you throw at compilation?

From 8 to 32.

**Comment by ejgallego** [comment]
Personally I would rather prefer targets to be directed by actions, for example "build everything needed to run this part of the test suite" or "build everything so I can launch a toplevel + prelude" , or "build everything so I can load coq.stdlib.streams".

**Comment by SkySkimmer** [comment]
Mostly I want "build every ml so I can fix type errors without wasting my time with the stdlib" ie byte/coqocaml. I tried dune for a bit but without that it was too annoying.

>indeed the time gain vs doing a normal build is just not there.

Disagree. At least with my 4thread laptop cpu.

**Comment by ejgallego** [comment]
> Mostly I want "build every ml so I can fix type errors without wasting my time with the stdlib" ie byte/coqocaml. I tried dune for a bit but without that it was too annoying.

The thing is that defining "every ml file" in a modular build system is not so easy. Do you consider CoqIDE? All the plugins? All the ml files tested in the CI.

What happens if I add a random `kernel/foo.ml` that nothing is using? Why should it be build?

Anyways, I guess we will implement this kind of target by manually listing the set of `cma` to be build and be done with it.

> Disagree. At least with my 4thread laptop cpu.

I'd be interested in seeing the actual example, just by using opaque you gain _so much_ that it seems obvious to me that build should be faster.

But indeed I guess I'll add an `.ml`-only mode to coq_dune.

**Comment by ejgallego** [comment]
#8901 should help with the common request of having a quicker build mode. Still not perfect but see the comments in the PR.

> * all plugins individually (I don't want to have to explicitly remember which vo file I have to compile)

What do you mean here?

> * states (likewise having to spell out `theories/Init/Prelude.vo` is a big no)

Current `states` target does work OK, we could indeed teach `coq_dune` to use `coqtop.byte` for additional speedup, but the delta is so small in my laptop that I don't bother [building from scratch coqtop.byte vs coqtop.opt saves 5 seconds, however in common use opaque does mean that we rebuild a pretty small number of files on average].

> * miniopt / pluginsopt (I don't want to wait for the thermodynamical death of the universe to check that ml files are ok)
> * printers
> * tools

Shouldn't these 3 targets be under a more general "build all ml files quick". Current quick target from scratch is pretty OK IMHO:
```
$ time make -f Makefile.dune quick
real	0m22,452s
user	1m25,791s
sys	0m32,325s
```

**Comment by rgrinberg** [comment]
> Mostly I want "build every ml so I can fix type errors without wasting my time with the stdlib" ie byte/coqocaml. I tried dune for a bit but without that it was too annoying.

The `@check` target in dune 1.5.0 does this. It's also faster than a bytecode only target as it will not link executables. It will also make sure that your cmt/cmti & .merlin files are up to date as well. Dune 1.5.0 is released but is still waiting to make it to opam-repository at this time.

**Comment by ejgallego** [comment]
Oh, I was aware of `@check` but I was under the impression that `@check` would not build `.ml` files, but it seems I was wrong.

IIUC Gaëtan wants indeed to check the consistency of type users too, not only the interfaces.

**Comment by rgrinberg** [comment]
> IIUC Gaëtan wants indeed to check the consistency of type users too, not only the interfaces.

Type users? `@check` will make sure the entire project type checks. I don't think it's possible to generate the .cmt files without type checking.

**Comment by ejgallego** [comment]
Indeed I see, I got confused somehow and I thought you were generating only the `.cmti` files.

I am happy with `@check`.

**Comment by gares** [comment]
Wet plugins, I guess PMP wants to type `make ssreflect` rather than `make plugins/SSR/ssrbool.vo`

**Comment by ppedrot** [comment]
I confirm that I want to give the name of the plugin as a target, e.g. `ssreflect` for this plugin. (Maybe relying on the directory names also makes sense, in which case it would be `ssr`).

**Comment by gares** [comment]
Note that pluginsopt does not invalidate the stdlib, nor other vo depending on it. Eg if I debug the last file of mathcomp thanks to pluginsopt I can add a print in the ml code and recompile no vo (unlike states). This feature is mandatory for me. If @check does not relink, I'm afraid it is not enough.

**Comment by SkySkimmer** [comment]
>Note that pluginsopt does not invalidate the stdlib, nor other vo depending on it. Eg if I debug the last file of mathcomp thanks to pluginsopt I can add a print in the ml code and recompile no vo (unlike states). This feature is mandatory for me. If @check does not relink, I'm afraid it is not enough.

Maybe we could have a build mode where dune ignores the dependency .v files have on ml files, so one would change the ml code and compile and dune would skip the v files? Not sure how much dune supports messing with dependencies.

**Comment by ejgallego** [comment]
> I confirm that I want to give the name of the plugin as a target, e.g. `ssreflect` for this plugin. (Maybe relying on the directory names also makes sense, in which case it would be `ssr`).

I am not sure I understand the workflow you need. What does "plugin" mean here? Differently from OCaml, Coq doesn't have a notion of "archive" such as cma.

Maybe you could put an actual example of what your workflow is. The Dune build happens to be different enough as for some workflows not to translate to others [a good example is the use of opaque]

**Comment by ppedrot** [comment]
Typical workflow: I am debugging some Coq development that depends on ssreflect. I modify some OCaml code inside the coq repo, and I need to recompile ssreflect to check what happens with this changes.

**Comment by ejgallego** [comment]
> Typical workflow: I am debugging some Coq development that depends on ssreflect. I modify some OCaml code inside the coq repo, and I need to recompile ssreflect to check what happens with this changes.

Well, my point is that you need to compile more than ssreflect right? In this use case, you need to compile both `ssreflect` and all its dependencies, including `.vo` files that load it right?

IMHO the way this should work is not by you caring about rebuilding ssreflect, but you should compose Coq and the development you are debugging, then rebuilding the problematic file on the development will trigger the proper incremental build.

What do you think?

**Comment by ejgallego** [comment]
> Maybe we could have a build mode where dune ignores the dependency .v files have on ml files, so one would change the ml code and compile and dune would skip the v files? Not sure how much dune supports messing with dependencies.

This can be done, however I am very wary of compromising the integrity of the rebuild. Dune works in a digest-based way, so if a .vo file is identical it won't trigger the rebuild.

As of today tho .vo files depend on the digest of coqtop. This could be relaxed but it is IMHO pretty low priority, and indeed it seems a pretty dangerous path to walk.

**Comment by ppedrot** [comment]
> IMHO the way this should work is not by you caring about rebuilding ssreflect, but you should compose Coq and the development you are debugging, then rebuilding the problematic file on the development will trigger the proper incremental build.

How do I do that when the Coq and the development repo are separate? I don't want to copy-and-paste code in between repos, if this is the suggested workflow.

**Comment by ejgallego** [comment]
> Note that pluginsopt does not invalidate the stdlib, nor other vo depending on it. Eg if I debug the last file of mathcomp thanks to pluginsopt I can add a print in the ml code and recompile no vo (unlike states). This feature is mandatory for me. If `@check` does not relink, I'm afraid it is not enough.

I am very puzzled that the behavior you describe is mandatory for you as in fact the make-based system doesn't work the way you describe unless I didn't understand.

A change in plugins [or `pluginsopt`] will of course invalidate all their dependencies including the depending `.vo` files. In this regard both make and Dune depend on coqdep.

Of course you can in Dune only build ssreflect and still call `coqtop` with stale vo files, but that's quite fragile when using both systems. In Dune for example `quick` doesn't subsume `pluginsopt`

```
$ touch plugins/ltac/g_ltac.mlg 
egallego@lasserre:~/external/coq-master$ make states -j
rm -f  
make --warn-undefined-variable --no-builtin-rules -f Makefile.build states
make[1]: se entra en el directorio '/home/egallego/external/coq-master'
COQPP   plugins/ltac/g_ltac.mlg
OCAMLDEP  plugins/MLFILES plugins/MLIFILES
OCAMLC    plugins/ltac/g_ltac.ml
OCAMLOPT  plugins/ltac/g_ltac.ml
OCAMLC -pack -o plugins/ltac/ltac_plugin.cmo
OCAMLC    plugins/cc/g_congruence.ml
OCAMLC    plugins/firstorder/g_ground.ml
OCAMLC    plugins/syntax/g_numeral.ml
OCAMLOPT -pack -o plugins/ltac/ltac_plugin.cmx
OCAMLOPT -shared -o plugins/ltac/ltac_plugin.cmxs
OCAMLOPT  plugins/ltac/tauto.ml
OCAMLOPT  plugins/cc/g_congruence.ml
OCAMLOPT  plugins/firstorder/ground.ml
OCAMLOPT  plugins/syntax/g_numeral.ml
OCAMLOPT -pack -o plugins/cc/cc_plugin.cmx
OCAMLOPT -pack -o plugins/syntax/numeral_notation_plugin.cmx
OCAMLOPT  plugins/firstorder/g_ground.ml
OCAMLOPT -shared -o plugins/cc/cc_plugin.cmxs
COQC -noinit theories/Init/Notations.v
OCAMLOPT -pack -o plugins/ltac/tauto_plugin.cmx
OCAMLOPT -shared -o plugins/syntax/numeral_notation_plugin.cmxs
OCAMLOPT -shared -o plugins/ltac/tauto_plugin.cmxs
OCAMLOPT -pack -o plugins/firstorder/ground_plugin.cmx
COQC -noinit theories/Init/Logic.v
OCAMLOPT -shared -o plugins/firstorder/ground_plugin.cmxs
COQC -noinit theories/Init/Datatypes.v
COQC -noinit theories/Init/Logic_Type.v
COQC -noinit theories/Init/Specif.v
COQC -noinit theories/Init/Nat.v
COQC -noinit theories/Init/Tauto.v
COQC -noinit theories/Init/Wf.v
COQC -noinit theories/Init/Peano.v
COQC -noinit theories/Init/Tactics.v
COQC -noinit theories/Init/Prelude.v
make[1]: se sale del directorio '/home/egallego/external/coq-master'
```

**Comment by ejgallego** [comment]
> How do I do that when the Coq and the development repo are separate? I don't want to copy-and-paste code in between repos, if this is the suggested workflow.

Composition works by putting both projects together under the same tree, I guess the proper workflow is to have an `external` folder in the coq repos and there you can `symlink` the external layout there, do a submodule, etc... Or the other way around, you can add a `coq` folder to the dev and they will compose.

Tooling is not yet in place but the rules are pretty flexible.

**Comment by ppedrot** [comment]
> Tooling is not yet in place but the rules are pretty flexible.

That's a chicken-and-egg problem, if I might say. I want to switch to dune but tooling is not there, and realizing what tooling I need requires switching to dune...

**Comment by gares** [comment]
> I am not sure I understand the workflow you need.

I want the equivalent of `make bin/coqtop && make plugisopt`. That is rebuild Coq (and plugins) in native code but do not rebuild the prelude.

Yes, there is a reason why .vo files depend on the hash of coqtop, but this dependency is too strict. If one adds a print the .vo files are perfectly fine (If one changes the constr data type, they are not, hence the dependency).

Indeed this could be achieved by dropping (temporarily) the dependency of .vo files from coqtop.
Is there a way of doing this?

**Comment by ejgallego** [comment]
Well, tooling is just `ln -s` in this case, or `git checkout`, or whatever system you prefer. I guess different developers will have different preferences.

For example I have my own script that I am about to submit that prepares a full set of overlays. If such overlays are dunerized I automatically get a global build and emacs gets the todo-list.

**Comment by ejgallego** [comment]
> I want the equivalent of `make bin/coqtop && make plugisopt`. That is rebuild Coq (and plugins) in native code but do not rebuild the prelude.

I am not sure what this has to do with Dune, I mean, you can workaround the build system of course if you want too, the exact same commands will have the same effect.

> Indeed this could be achieved by dropping (temporarily) the dependency of .vo files from coqtop.
> Is there a way of doing this?

This is trivial to do in Dune, dunno about make. But it is very low priority for me as I am not very comfortable with such an option. Sooner of later it will create bad problems when people do start abusing it.

**Comment by ejgallego** [comment]
@ppedrot imagine you have `~/coq-projects/` then when in your own `coq` checkout, just do `ln -s ~/coq-projects/foo` and that's all what you will need when we finish dunerizing devs.

How to systematize this I dunno. My own script does a fresh checkout, creates a branch, and setups the overlay file.

**Comment by gares** [comment]
> if you want too, the exact same commands will have the same effect.

If we move to a dune only build system I will no be able to run that command, or any other make based command. This is the whole point of this issue.

> This is trivial to do in Dune, dunno about make.

In make the feature I'm talking about is already there, what are we talking about?

If it is easy then it is good news, but I don't know how to do that.
Could you add a target in `Makefile.dune` for that? Or write the invocation here at least.

**Comment by ejgallego** [comment]
> If we move to a dune only build system I will not be able to run that command, or any other make based command. This is the whole point of this issue.

There are two things here: one is what Dune / make can do. What you are doing has nothing to do with make, you are working outside make's shoulders in a fragile way. So I don't think it is fair to ask Dune to do something that you are doing outside make.

Second, is of course you can keep the hack and use Dune, `dune build coqtop && dune build plugins` will do the same that you were doing. However I am not sure such fragile behavior can be supported properly.

> In the make base build system the feature I'm talking about is already there, what are we talking about?

You are talking about two things:
- compiling plugins only, then running Coq: this has nothing to do with make. You are just building a part of the stuff and relying on stale binaries. It is not a "feature", but it happens to work, and so does in Dune, provided you _manually_ maintain the consistency of the system.
- the other is having the .vo files don't depend on plugins / coqtop. AFAICS the make system doesn't implement this [I could be wrong]. This would be easy to do in Dune. Out of curiosity, how do you do this in `make`?

**Comment by ejgallego** [comment]
> Could you add a target in `Makefile.dune` for that?

If you are talking about the rebuild hack I can add a `plugins` target, so `states` + `plugins` will work for you, but I don't plan to support this as a single target as if you want to workaround the build system IMHO you are on your own.

If you are talking about dropping the dependency on `coqtop` I am very very wary of it, but I could add a flag to `coq_dune` so the `.vo` rules don't force the rebuild of `coqtop`. But this is meant to cause problems as if the rules don't depend on `coqtop` users will get a very bad error when `coqtop` wasn't built.

Sorry, I am not a fan of having the user do the build system job. Much less when we are talking about saving a few seconds in most cases.

**Comment by ppedrot** [comment]
> Sorry, I am not a fan of having the user do the build system job. Much less when we are talking about saving a few seconds in most cases.

OK, I have to disagree here. This dirty trick often saves literally **hours** of compilation.

**Comment by ejgallego** [comment]
> This dirty trick often saves literally **hours** of compilation.

Care to share a concrete example?

I'd bet that indeed you are losing more time dealing with the build hacks than with the issue proper at hand, as we lack proper incremental builds and you have to painfully do `make` in coq, then `clean` in the other repo, `make` again, pray things are consistent, etc...

With my composed builds I have still not even cared a bit about build time, things are always ready using `-watch` but I admit I have a fast computer.

Anyways my point is that the make-based system doesn't support the trick, so I don't want to add it either. You are free to invoke the hack as you do today of course.

**Comment by ppedrot** [comment]
> Care to share a concrete example?

Often I have to fiddle several times before getting a patch right, or I want to quickly witness differences on timing. On developments like fiat, lambda-rust, mathcomp or similar ones that have big dependency chains, it is a nightmare to have to recompile everything from scratch. No matter how many cores you have, this is still time-consuming.

Also, not everybody has 512 liquid-nitrogen-cooled cores. And often I do develop on batteries. (Like, for instance, right now.)

**Comment by gares** [comment]
> Care to share a concrete example?

We gave you example *n* times already. Add a print and go back checking the same bug.v that failed before without recompiling any deps.v files it depends on. Then add a second print and repeat until bug.v works.
If there a 2h of compilation to reach bug.v... well I don't care how fragile things are, at worse you get a SIGSEGV, and in the specific case you never do.

If I've  understood correctly `dune build coqtop && dune build plugins` builds the binaries but not any `.vo`.
It is fine like that.

**Comment by ejgallego** [comment]
> * make ci-foo (this doesn't depend on anything, so it will start right at whatever file was failing)

Note that indeed that is a very big problem that I hope we can fix with Dune. `ci-foo` should properly depend on the stuff it uses. With Dune, you can compile a file in `ci-foo` properly and it won't recompile the stdlib in full [which is what happens today] but only the right files. For example if you compose with HoTT it will compile nothing.

> make world - make coqocaml is
> > real	4m21.533s
> That is not seconds.

My laptop is way faster [and IMHO it makes little sense to have devs with machines that are not state-of-the-art], but indeed that's my point above, "make world" doesn't make a lot of sense anymore to me. What I see is several libraries `coq.stdlib.reals` etc... that are only compiled when really needed. So here, YMMV.

I am convinced much of the pain that is trying to be alleviated by the hack is due to the lack of proper incremental build. For example, if I need to run a test on the test suite I shouldn't have to compile the full stdlib but only the right dependencies.

Even so I recognize the hack is useful, but my point is that make doesn't really support it, so it is unfair to demand that from Dune. Mainly, because the build system cannot read your brain and know whether your changes do matter for vo file generation.

**Comment by Zimmi48** [comment]
>and IMHO it makes little sense to have devs with machines that are not state-of-the-art

:money_with_wings: 

>What I see is several libraries coq.stdlib.reals etc... that are only compiled when really needed. So here, YMMV.

I see the same but we are not there yet.

>I am convinced much of the pain that is trying to be alleviated by the hack is due to the lack of proper incremental build.

Except when indeed the long dependency chain is in the external library you are trying to test like @ppedrot mentioned.

>Mainly, because the build system cannot read your brain and know whether your changes do matter for vo file generation.

Indeed, it is the developer who should know if they want to use this strategy. In any case, it seems that what you proposed `dune build coqtop && dune build plugins` satisfies this requirement. You only need to add the `plugins` target IIUC.

**Comment by ejgallego** [comment]
> You only need to add the `plugins` target IIUC.

Yup; but the hack won't work properly if you are using composed builds or your contrib has a plugin, etc... so you'll have to imitate a non-compositional build [in the way make works]

We will have to add proper support for it to `coq_dune`, but indeed my point is that this is purely an enhancement as `make` doesn't support it.

**Comment by gares** [comment]
When I build with make I find myself waiting until I see it compiler some vo, and then I hit `^C` to stop.
Is there anything like that? Can I see what dune is doing and stop it?

**Comment by ppedrot** [comment]
@gares you can export `DUNEOPT=--display=short` in the environment. I think it should be the default actually, I really don't like compilation blackboxes. Note that it breaks some targets though.

**Comment by gares** [comment]
> Note that it breaks some targets though.

Can you say more about this?

**Comment by Zimmi48** [comment]
See #8956 for instance (I suppose that was what @ppedrot meant).

**Comment by ejgallego** [comment]
This and other questions are covered in the documentation `dev/doc/build-system.dune.md`

For some reason it seems people is not aware of that file.

**Comment by ejgallego** [comment]
> @gares you can export `DUNEOPT=--display=short` in the environment. I think it should be the default actually, I really don't like compilation blackboxes. Note that it breaks some targets though.

See the docs on how to customize the display to your taste.

**Comment by ejgallego** [comment]
> When I build with make I find myself waiting until I see it compiler some vo, and then I hit `^C` to stop.

That's a very strange usage pattern. Why don't just make the actual vo you want?

**Comment by ejgallego** [comment]
This is mostly solved IMO, so I will close soon unless more comments arise; in general, the target developers want to ml files is `check`, for running `coqtop/coqc` you want to run the shims, and for `.vo` files you want well the right vo file.

`DUNEOPTS` will go away as dune is now usable without the bootstrapping step; waiting for the release as to submit the PR.

**Comment by ejgallego** [comment]
As discussed on gitter these targets offer a really large speedup in general for many reasons, if you find Dune slower than make please report.

[For example Dune will rebuild files based on the digest, this would be almost perfect for Coq however the digest of coqc tends to change very easily but I will implement a cutoff mode soon tho!]

**Comment by ejgallego** [comment]
By the way support for "cutoffs" [that is to say, allowing to rebuild coqtop but the vo files] is indeed very important but it does have its own issue and I haven't' forgotten about it

https://github.com/ocaml/dune/issues/1523
