### ISSUE TITLE
`coqdep` not printing warnings, but a warning it cannot print them

### ISSUE THREAD

**Issue by gares** [coq/coq#8913]
#### Version

8.8.2

#### Description of the problem

```
COQDEP VFILES
Warning, feedback message received but no listener to handle it!
```

I've no clue when this was introduced, but @ejgallego may know better.

**Comment by ejgallego** [comment]
See if #8914 helps. That PR was part of a different PR removing the need for the "boot" mode of coqdep, and thus allowing to process the whole set of dependencies way quicker, but maybe it is good we get it merged first.
