### ISSUE TITLE
coqtop dies badly with -arg in  _CoqProject

### ISSUE THREAD

**Issue by davidnowak** [coq/coq#8921]
#### Version

8.8.2 

#### Operating system

macOS 10.14.1

#### Description of the problem

Having the line `-arg "-w -notation-overridden"` in _CoqProject and opening a file with coqide causes coqtop to "die badly".

A not so convenient workaround is to configure coqide so that it ignores the file _CoqProject.

This bug report is related to feature request #8818.

**Comment by anton-trunov** [comment]
Here is a relevant thread: https://github.com/coq/coq/issues/5773#issuecomment-424286568

AFAIR, the upshot was that

```
-arg -w -arg -notation-overridden
```

should work in both CoqIDE and PG

**Comment by davidnowak** [comment]
@anton-trunov Thanks

Duplicate of #5773

**Comment by anton-trunov** [comment]
@davidnowak No problem :)
