### ISSUE TITLE
[Declare Scope] is not part of v8.9+beta1 but is part of the release notes

### ISSUE THREAD

**Issue by tchajed** [coq/coq#8925]
#### Version

```
The Coq Proof Assistant, version 8.9+beta1 (November 2018)
compiled on Nov 5 2018 6:51:11 with OCaml 4.06.0
```

#### Operating system

macOS

#### Description of the problem

`Declare Scope` is documented in `CHANGES.md` for v8.9+beta1 but the commit that introduced it was never actually included in v8.9. There was a lot of discussion on the PR that introduced the feature (#7135) and it seems a good deal of confusion around who was responsible for merging and moving things in `CHANGES.md`.

I'd like to see this included in Coq v8.9 quickly since I'm using `Declare Scope` to avoid warnings in Coq master and it's the only source of incompatibility in my projects with v8.9 (and even v8.8.2).

**Comment by silene** [comment]
Sorry, I won't merge such a large change into Coq 8.9 after the beta has been released.

**Comment by tchajed** [comment]
If there'll be another beta it could be included there (I don't know what the schedule is), but otherwise the simple but important fix is to update CHANGES.md to move this entry to Coq v8.10.

**Comment by Zimmi48** [comment]
@tchajed Done in #8926

**Comment by Zimmi48** [comment]
Note that it is not part of the release notes in the v8.9 branch, only in master: that's why this is a 8.10+beta1 fix.
