### ISSUE TITLE
Bind Scope does not commute with Notation

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#8942]
#### Version

8.8.2

#### Description of the problem

Doing `Bind Scope` *after* a `Notation` in the same scope seems to only work partially. Here I define a notation `~~ b` for some type of boolean expressions. Then writing `~~ b` (where `b` is a variable) is fine, but trying to write `~~ (~~ b)` leads to an error that the inner `~~` has no interpretation.

```coq
Inductive bexp : Type :=
| BNot : bexp -> bexp.

Notation "~~ b" := (BNot b) (at level 75) : bexp_scope.
Bind Scope bexp_scope with bexp.

Definition not (b : bexp) : bexp := ~~ b.        (* OK, using [bexp_scope] at type [bexp]? *)
Fail Definition notnot (b : bexp) : bexp := ~~ (~~ b). (* Not OK *)
```

If the `Bind Scope` precedes the notation, then everything seems fine.

```coq
Inductive bexp : Type :=
| BNot : bexp -> bexp.

Bind Scope bexp_scope with bexp.
Notation "~~ b" := (BNot b) (at level 75) : bexp_scope.

Definition not (b : bexp) : bexp := ~~ b.
Definition notnot (b : bexp) : bexp := ~~ (~~ b).
```

**Comment by andres-erbsen** [comment]
This behavior makes sense to me.

When `Notation` is executed, the parsing scopes for all arguments should be determined. In the first example, I think `b` gets marked as to be parsed in `core_scope`. In the second example, the `Bind Scope` rule is in effect and `b` gets marked to be parsed in `bexpr_scope`. Afaik the foolproof way is:

~~~~~
Notation "~~ b" := (BNot b%bexp) (at level 75) : bexp_scope.
~~~~~

**Comment by JasonGross** [comment]
It is a little bit confusing, though, because `Bind Scope` does (mostly) commute with `Definition` (I think this behavior was introduced sometime after 8.3 or 8.4):
```coq
Delimit Scope True_scope with True.
Module A.
  Definition foo0 (x : True) (v : Type) := x.
  About foo0.
  (* foo0 : True -> Type -> True

Argument scopes are [_ type_scope]
foo0 is transparent
Expands to: Constant Top.foo0
   *)
  Bind Scope True_scope with True.
  About foo0.
  (* foo0 : True -> Type -> True

Argument scopes are [True_scope type_scope]
foo0 is transparent
Expands to: Constant Top.foo0
   *)
  Definition foo1 (x : True) (v : Type) := x.
  About foo1.
  (* foo1 : True -> Type -> True

Argument scopes are [True_scope type_scope]
foo1 is transparent
Expands to: Constant Top.foo1
   *)
End A.
About A.foo0.
(* A.foo0 : True -> Type -> True

Argument scopes are [_ type_scope]
A.foo0 is transparent
Expands to: Constant Top.A.foo0
 *)
About A.foo1.
(* A.foo1 : True -> Type -> True

Argument scopes are [True_scope type_scope]
A.foo1 is transparent
Expands to: Constant Top.A.foo1
*)
```

**Comment by herbelin** [comment]
I would tend to stay with the current behavior: changing retroactively scopes in notations would be a bit complicated. This may even invalidate the notation if the same variable is used several times in scopes which later happen to be different.

**Comment by Lysxia** [comment]
Thanks Andres, that helped me understand what is going on. It does seem impossible to have `Bind Scope` commute with `Notation`.

**Comment by ppedrot** [comment]
Let's close then.
