### ISSUE TITLE
Kernel anomaly with universes and inlining

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#8951]
I don't understand how univ poly and functor inlining work together, so I wrote one example:

```coq
Module Type T.
  Polymorphic Parameter Inline t@{i} : Type@{i}.
End T.

Module M.
  Polymorphic Definition t@{i} := nat.
End M.

Module Make (X:T).
  Include X.

End Make.

Module P := Make M.
```

and got:

```
Anomaly "File "kernel/mod_subst.ml", line 306, characters 15-21: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

I need guidance on how to fix this.

**Comment by ppedrot** [comment]
This most likely indicates some serious bug in the kernel... Luckily there was an assertion there.

**Comment by SkySkimmer** [comment]
>I need guidance on how to fix this.

Was the stuff I said on gitter not enough?

**Comment by maximedenes** [comment]
> ... but this is worse than that. Even `subst_constant` applies terms to empty instances... And that one is used by the VM.

Yeah, I saw that too. And outside of the kernel, there's more of it: `subst_global` etc.

**Comment by ppedrot** [comment]
@maximedenes You can remove most of the calls to `subst_global` and use `subst_global_reference` instead. I am writing a patch for that, but you might already be doing the same.

**Comment by maximedenes** [comment]
> I am writing a patch for that, but you might already be doing the same.

It's already done before I submitted this, let's synchronize.

**Comment by JasonGross** [comment]
Can this be used to get a proof of False

**Comment by SkySkimmer** [comment]
No, the assert catches attempts.

Gaëtan Gilbert
