### ISSUE TITLE
Should the numeral notations plugin be listed in META.coq.in?

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8963]
It's not, currently.  Also, the old natsyntax, etc, plugins are still listed.  Should they be removed?  Can the CI check things like this?

**Comment by ejgallego** [comment]
> Can the CI check things like this?

`META.coq` is automatically generated when buillding with Dune so no need to add CI checks. Indeed the file should be consistent, but it is also likely that we remove it for 8.10.
