### ISSUE TITLE
CoqIDE does not pass the name of the current modpath

### ISSUE THREAD

**Issue by tlringer** [coq/coq#8989]
#### Version

The Coq Proof Assistant, version 8.10+alpha (October 2018)
compiled on Oct 25 2018 11:39:02 with OCaml 4.06.1

#### Operating system

Fedora 22

#### Description of the problem

I am developing a plugin for logging changes in Coq as users make them. As part of this, I need to get the module path from which the plugin is loaded. I do this using `Lib.current_mp ()`.

Right now, I have a file `testdebug.v` with the following contents:

```
Require Import Analytical.Analytics. (* my plugin *)
Set Debug Analytics. (* print logging info locally *)
```

When I run this with `coqc`, I get the following output:

```
((time 1542142301.489689) (session-module: testdebug) (session 1542142300.542698)  (Control (StmObserve 3)))
```

Note the `session-module` there, which is taken from `Lib.current_mp ()` at load-time. However, when I open this in CoqIDE and execute it, I get the following instead:

```
((time 1542142348.179430) (session-module: Top) (session 1542142345.429123) (Control (StmObserve 3)))
```

Here, the `session-module` is `Top` instead of `testdebug`. Because of this, if users edit files in CoqIDE, it is currently impossible for my logging tool to tell what files they are editing. I am not sure if this has implications for other parts of the code.

@maximedenes said that this was due to a bug in CoqIDE, which is not passing the current modpath. I'm not sure exactly how this works, but I'm reporting an issue so that we can discuss this. He also pointed out that @ppedrot and @gares would probably know more.

I can provide my plugin code if you are interested, but it is a bit of a pain since it currently requires a branch of Coq not merged into master yet (that @ejgallego is developing) that has hooks into add, remove, and exec exposed to plugins. You can reproduce this by writing a simple plugin however that just logs the current modpath at loadtime:

```
let log =
  let session_module = ModPath.to_string (Lib.current_mp ()) in
  Feedback.msg_notice (Pp.str session_module)
```

**Comment by SkySkimmer** [comment]
>I am not sure if this has implications for other parts of the code.

It does, try putting
~~~coq
Definition bar := Prop.
Check foo.bar
~~~
in a file `foo.v`, it will work with coqc but not interactively.

**Comment by Janno** [comment]
This also has implications for Mtac2, where we allow users to call Ltac tactics by name (as in a string) and we were trying to disambiguate local Ltac's that were shadowing global ones by prefixing them with the current module path. Of course this worked in `coqc` but not `coqtop`.. We worked around it somehow but I would very much appreciate `coqtop` being smarter here. 

(I suppose similar issues would arise with the Mtac2 primitive to look up a Gallina definition by name.)

**Comment by SkySkimmer** [comment]
Have a look at #8991.

**Comment by SkySkimmer** [comment]
By the way @ejgallego for Talia's plugin it seems like it would be useful to have an accessor for the stm doc_type (the VCS.doc_type reference) instead of using Lib.current_mp().

**Comment by ppedrot** [comment]
This works when there is a `_CoqProject` though, right?

**Comment by tlringer** [comment]
> This works when there is a `_CoqProject` though, right?

Do you have to tell CoqIDE about the `_CoqProject` somehow? I tried it in a project where I have a `_CoqProject` and it didn't change anything. Selecting `Make` or `Compile buffer` in the `Tools` menu selects the right module path, but my local output as I step through still says `Top`.

**Comment by SkySkimmer** [comment]
@ppedrot WDYM by "this"?

**Comment by gares** [comment]
> Do you have to tell CoqIDE about the `_CoqProject` somehow?

Yes, look at the Preferences menu.

**Comment by tlringer** [comment]
It has the right default settings looking for `_CoqProject` already. It doesn't change the result stepping through within the IDE. 

The fix for this looks good though, thank you for getting to it so quickly.
