### ISSUE TITLE
Program Fixpoint does not understand the "if" syntax.

### ISSUE THREAD

**Issue by Matafou** [coq/coq#9007]
#### Version
8.8
#### Operating system
linux
#### Description of the problem
Program Fixpoint seems to not understand the "if then else" syntax: 
```
Require Import Program.Wf Recdef NArith.
Open Scope N_scope.

Program Fixpoint log10 (n : N) { wf N.lt n } : N :=
  if N.ltb n 10 then 0 else log10 (n / 10).
Next Obligation
```
gives the wrong obligation:
```
  n : N
  log10 : forall n0 : N, n0 < n -> N
  ============================
  n / 10 < n
```
where the information `N.ltb n 10 = false` is not there.

Note that if I replace if by a match on booleans the obligation is correct.

**Comment by eponier** [comment]
This behaviour is explained in the [documentation](https://coq.inria.fr/refman/addendum/program.html#syntactic-control-over-equalities):

> Likewise, the if construct is not treated specially by Program so boolean tests in the code are not automatically reflected in the obligations. One can use the dec combinator to get the correct hypotheses [...]
