### ISSUE TITLE
`evd.mli` does not reflect `evd.ml`

### ISSUE THREAD

**Issue by liyishuai** [coq/coq#9009]
#### Version

8.10+alpha

#### Operating system
- Ubuntu 14.04.5 LTS
- macOS 10.13.3

#### Description of the problem

In QuickChick [Build#748](https://travis-ci.org/QuickChick/QuickChick/builds/455734972):
> This expression has type Constr.t
but an expression was expected of type Evd.etypes = Evd.econstr

According to [evd.ml](https://github.com/SkySkimmer/coq/blob/master/engine/evd.ml#L24), these types are the same. However, such equivalence is not reflected in [evd.mli](https://github.com/SkySkimmer/coq/blob/master/engine/evd.mli#L31).

**Comment by ppedrot** [comment]
Thankfully they're not, that's the *raison d'être* of the `EConstr` interface. You definitely don't want these types to be equal, even though they appear to be internally implemented the same. `EConstr` API statically enforces invariance by evar substitution.
