### ISSUE TITLE
opam package for coq.dev needs update

### ISSUE THREAD

**Issue by erikmd** [coq/coq#9050]
#### Version

Coq `master` *via* https://github.com/coq/opam-coq-archive

#### Description of the problem

The latest nightly build of opam's package `coq.dev` has failed on Docker Hub, and it appears that https://github.com/coq/opam-coq-archive/blob/master/core-dev/packages/coq.dev/opam is out of sync w.r.t. the new build system of Coq (it still relies on `make` and `camlp5`).

Could someone familiar with `dune` prepare an update of the recipe in opam-coq-archive? We could then restart the build on Docker Hub to get a newest `coqorg/coq:dev` image.

**Comment by ejgallego** [comment]
I think we could indeed just add a quick fix to this opam file. Removing the two lines mentioning camlp5 should suffice.

**Comment by RalfJung** [comment]
So `make` is still a thing, but `camlp5` is no longer a dependency?

**Comment by ejgallego** [comment]
Yup, camlp5 is not needed in master anymore.

**Comment by erikmd** [comment]
Thanks! :+1: So I've triggered the rebuild of `coqorg/coq:dev`.

Indeed @ejgallego, removing the `camlp5` dependency was sufficient; by curiosity regarding the `dune` infrastructure, could it fully replace the `make` build system from now on, or would something be missing?
(I'm asking that just because I've noticed there's no `install:` rule in [coq.opam](https://github.com/coq/coq/blob/aa151dbc7aa501bac78b835a80f9a25c5316d2dc/coq.opam), unlike [opam-coq-archive's opam](https://github.com/coq/opam-coq-archive/blob/d57a6a141fb69d81735e6dd39089b77173e7bc24/core-dev/packages/coq.dev/opam).)
