### ISSUE TITLE
Unexpected failure of typeclasses resolution (due to Hint Mode being applied too aggressively)

### ISSUE THREAD

**Issue by vbgl** [coq/coq#9058]
I wished the following example succeeded.

~~~
Class A X := { opA: X -> X }.
Hint Mode A ! : typeclass_instances.

Class B X {aX: A X} Y := { opB: X -> Y -> Y }.
Hint Mode B - - ! : typeclass_instances.

Section Section.

Context X {aX: A X} Y {bY: B X Y}.

Set Typeclasses Debug.

Let ok := fun x (y: Y) => @opB _ _ _ bY (opA x) y.
Fail
Let ko := fun x (y: Y) => opB (opA x) y.

End Section.
~~~

The debug trace reads as follows.

> Debug: 1: looking for (A ?X) with backtracking
> Debug: 1: no match for (A ?X), 0 possibilities
> Debug: 1: looking for (A ?X) with backtracking
> Debug: 1: no match for (A ?X), 0 possibilities

I’d guessed that the problem “B ?X Y” would be solved (by finding `bY`); that would fix the variable “?X” and simplify the other problems to “A X” (for which there is solution `aX`).

**Comment by vbgl** [comment]
@mattam82 Maybe Matthieu has some comments on this use case of type classes.

**Comment by mattam82** [comment]
You want a different order of resolution than the one naturally used by typeclasses. When it respects dependencies, it tries to solve the least dependent constraints first, so here the `A ?X` constraint, and otherwise fails. We could instead delay such constraints whose mode does not match.

**Comment by mattam82** [comment]
Yes, the scheduling is not modified. The implementation uses proof search on the list of goals and does not support suspension easily (one can hack with shelve currently). With the evar constraints reified as a list of candidates now, it should be relatively simple to change the code to call proof search independently on each constraint, supporting suspension of constraints according to their mode.

**Comment by CohenCyril** [comment]
Another problematic example:
```
Record X : Type := mkX {nX : nat}.

Class A (x : X) (y : nat) := {}.
Hint Mode A - ! : typeclass_instances.

Section Section.

Instance Ax0 : A (mkX 0) 0.

Let zero := fun x y (a : A x y) => @nX x.

(* X is not a class *)
Let test : (@zero _ 0 _) = 0. reflexivity. Qed.

Existing Class X.
(* now, X is a class *)

Set Typeclasses Debug.
Fail Let test' : (@zero _ 0 _) = 0.

End Section.
```
Here, when `X` is not a class, the search of instance for `A _ 0` succeeds, but when it becomes a class, the resolution tries to solve it first and fails (no declared instance), while searching for the same `A _ 0` as before should succeed...

**Comment by maximedenes** [comment]
Probably the same as #5735.

**Comment by RalfJung** [comment]
This issue is blocking us from setting a reasonable `Hint Mode` for the `Equiv` typeclass in std++. That class is used a lot, but TC search often gets cancelled too early if we restrict it to not proceed when the goal is an evar.

Cc @robbertkrebbers
