### ISSUE TITLE
`coqc` and `coqdep` don't agree on ambiguous modules, and `coqc` seems to pick a random one.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#9080]
Files [modules under `theories`]:
- `M.v`:
```coq
From L Require Import A.
Print a.
```
- `M/A.v`:
```coq
Definition a := 0.
```
- `N/A.v`
```coq
Definition a := 1.
```
- `_CoqProject`:
```
-R theories L
```
make will say:
```
COQDEP VFILES
*** Warning: in file theories/M.v, 
    required library A matches several files in path
    (found A.v in theories/N and theories/M; used the latter)
*** Warning: in file theories/M.v, 
    required library A matches several files in path
    (found A.v in theories/N and theories/M; used the latter)
COQC theories/N/A.v
COQC theories/M.v
a = 1
     : nat
COQC theories/M/A.v
```
despite using choosing `M` both in `coqdep` and in the runtime. Now do:
```
$ touch theories/N/A.v
$ make
```
and we get:
```
COQDEP VFILES
*** Warning: in file theories/M.v, 
    required library A matches several files in path
    (found A.v in theories/N and theories/M; used the latter)
*** Warning: in file theories/M.v, 
    required library A matches several files in path
    (found A.v in theories/N and theories/M; used the latter)
COQC theories/N/A.v
COQC theories/M.v
a = 0
     : nat
```
the whole system seems so broken that I am not sure what to even propose here.

**Comment by ejgallego** [comment]
Note that `coqc` emits no warning whatsoever.

**Comment by herbelin** [comment]
Indeed, both `coqdep` and `coqc`/`coqtop` are using `readdir` but they don't browse the list in the same order (as `cat .coqdeps.d` shows). Indeed, one more place needing factorization (or at least, as a quick fix, to fix `coqdep`).

**Comment by Blaisorblade** [comment]
> the whole system seems so broken that I am not sure what to even propose here.

Just my 2 cents: As a requirement, I'd prefer a warning/error over making the behavior consistent; I understand the refactoring might be more urgent (per https://github.com/coq/coq/issues/9839#issuecomment-477168307), but a quickfix might be justified since that refactoring is not easy.

**Comment by Alizter** [comment]
On 8.16 coqdep throws a warning and coqc rejects the ambiguous path. I would therefore consider this closed.
