### ISSUE TITLE
Installation via OPAM failed on macOS in Travis CI

### ISSUE THREAD

**Issue by liyishuai** [coq/coq#9084]
#### Version

8.10+alpha

#### Operating system
macOS

#### Description of the problem

[QuickChick build #771.3](https://travis-ci.org/QuickChick/QuickChick/jobs/459251880#L927) could not install `coq.dev` via opam:
```
#=== ERROR while compiling coq.dev ============================================#
# context     2.0.1 | macos/x86_64 | ocaml-base-compiler.4.05.0 | https://coq.inria.fr/opam/core-dev
# path        ~/.opam/ocaml-base-compiler.4.05.0/.opam-switch/build/coq.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j1
# exit-code   2
# env-file    ~/.opam/log/coq-86220-d4902a.env
# output-file ~/.opam/log/coq-86220-d4902a.out
### output ###
# [...]
# sed: 1: "1i # 1 "gramlib/plexing ...": command i expects \ followed by text
# make[1]: Circular coqpp/coqpp_parse.cmi <- coqpp/coqpp_parse.cmo dependency dropped.
# OCAMLDEP  plugins/MLFILES plugins/MLIFILES
# Fatal error: exception Failure("gramlib__pack/gramlib.ml : empty map file or parse error")
# cp -a gramlib/gramext.ml gramlib__pack/gramlib__Gramext.ml
# sed -e "1i # 1 \"gramlib/gramext.ml\"" -i gramlib__pack/gramlib__Gramext.ml
# sed: 1: "1i # 1 "gramlib/gramext ...": command i expects \ followed by text
# OCAMLOPT  config/coq_config.ml
# File "config/coq_config.ml", line 1:
# Error: Could not find the .cmi file for interface config/coq_config.mli.
# make[1]: *** [config/coq_config.cmx] Error 2
# make: *** [submake] Error 2
```

**Comment by liyishuai** [comment]
Notice that the same version has been built multiple times with different results:
- [Build #762](https://travis-ci.org/QuickChick/QuickChick/builds/456433078) succeeded
- [Build #764](https://travis-ci.org/QuickChick/QuickChick/builds/456739112) and [#765](https://travis-ci.org/QuickChick/QuickChick/builds/457685652) failed, but they should be either OCaml or Homebrew's fault
- [Build #770.3](https://travis-ci.org/QuickChick/QuickChick/jobs/458596859#L935) failed in the same way as the issue mentioned

**Comment by ejgallego** [comment]
That's a problem with OSX `sed`, I dunno why it has worked well here so far :S 

We could try `sed -i'.bak'` which should work I think.

**Comment by ejgallego** [comment]
This is fixed AFAICT, right? [Please reopen if not]
