### ISSUE TITLE
Travis macOS packaging job currently failing with timeout.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#9090]
The packaging job was already very close to the timeout limit but since 22 hours ago, all the jobs have been going over this time limit. I expect this isn't specific to the master branch (but is due to changes on Travis's side), and if that's the case, it means that the 8.9.0 release could be affected by this (unless it is build and not just signed on a VM). @vbgl @maximedenes What is the status of #7501?

**Comment by ejgallego** [comment]
I guess the easiest solution is to add a build stage an put `brew` stuff on the build cache.

**Comment by Zimmi48** [comment]
I confirm that the problem is there as well in the v8.9 branch: https://travis-ci.org/coq/coq/builds/464804987

Ping @vbgl @maximedenes: is that going to block the package generation for 8.9.0 or are you going to do this on a VM anyways?

In any case this seems relevant at least for the kind of testing that @silene had asked before tagging the release and that would have been useful to do once more.

**Comment by Zimmi48** [comment]
At the very least I would like an acknowledgement of either @vbgl or @maximedenes that they have read this, are aware of the problem, and this is not going to block 8.9.0.

**Comment by maximedenes** [comment]
Regarding
- building the macOS package, yes, this is going to be a problem, since we were relying on this job AFAIK
- signing: I don't know what the current situation of the certificate is

**Comment by Zimmi48** [comment]
That sound pretty catastrophic...
