### ISSUE TITLE
Test suite does not pass with `-async-proofs on`

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#9093]
Running the test-suite with `-async-proofs on` (on top of #9072, otherwise proof delegation never occurs) reveals a few problems:

- success/polymorphism.v
- output-modulo-time/ltacprof_cutoff.v
- bugs/closed/bug_4306.v
- bugs/closed/bug_3612.v

I keep them here for reference. Will investigate a bit more, and probably call for help, especially on the two that triggers universe-related errors...

**Comment by SkySkimmer** [comment]
>output-modulo-time/ltacprof_cutoff.v

I doubt it makes sense to expect this one to work. In fact how come the output tests work, shouldn't the order get messed up?

**Comment by ejgallego** [comment]
Side effects are ordered, unless they happen inside opaque proofs.

**Comment by ejgallego** [comment]
In fact likely an opaque proof with side effects is likely to be marked as synch.

**Comment by SkySkimmer** [comment]
The issue in polymorphism.v can be reproduced with just
~~~coq
Unset Universe Polymorphism.

Ltac exact0 := let x := constr:(Type) in exact 0.

Lemma lemma_restrict_abstract@{} : nat.
Proof. abstract exact0. Qed.
(* Debug: 10237:proofworker:0:0 STM: sending back a fat state
Error: Universe {polymorphism.1} is unbound. *)
~~~

**Comment by maximedenes** [comment]
> > output-modulo-time/ltacprof_cutoff.v
> 
> I doubt it makes sense to expect this one to work. In fact how come the output tests work, shouldn't the order get messed up?

Yes, this one is more of a design issue. What seems trickier is the universe-related ones.

**Comment by ejgallego** [comment]
We have requested many times for info about the design of universe handling, it would be good if we could understand more !

**Comment by SkySkimmer** [comment]
#9222 fixes bug_3612.v
#9223 fixes polymorphism.v and bug_4306.v

**Comment by maximedenes** [comment]
Wow! You should make us pay for such an efficient hotline ;) Thanks!

**Comment by gares** [comment]
What is left then? IIRC the plan was to simply run ltacprof in sync mode

**Comment by maximedenes** [comment]
> What is left then? IIRC the plan was to simply run ltacprof in sync mode

How should I implement that?

**Comment by gares** [comment]
many test-suite subfolders support `(* coqopts: bla bla *)`, I've recently added it to `ide/`, see the Makefile in the test suite

**Comment by maximedenes** [comment]
Oh you mean hiding the bug by changing the flags in the test suite? I think we should rather fix the problem. I thought you meant making proofs run synchronously when the Ltac profiler is on.

**Comment by gares** [comment]
We can do that too, but I don't think being able to use profiling *and* async proofs is useless.
It is just that in batch mode you have no control when the line "Print Ltac Profile" is executed, and if you play it too early then you get silly results. We don't have a nice was to script the following interaction, imagine I'm using the firebug profiler:
- start the profiler
- reload the page
- stop the profiler (after the page finished loading)
- observe the results.

In interactive mode, if you stop the profile before the page even starts loading you are stupid, but it is not a bug that chrome lets you do that, IMO.

What happens in the tests using Coqc is exactly the silly *user* behavior.

Still, with async proofs off, the test performed by coqc is useful and we can keep it.

**Comment by ejgallego** [comment]
Indeed the vernacular seems like a really bad interface for a profile, so @gared is spot on.

**Comment by maximedenes** [comment]
This is all fixed, big thanks to @SkySkimmer @gares and @ejgallego !
