### ISSUE TITLE
please explain why arguments of S cannot be made implicit

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9098]
#### Version

8.8.2

#### Operating system

Arch Linux, up to date as of one week

#### Description of the problem

~~~~~coq
Arguments S {_}.
(* Error: Argument _ cannot be declared implicit. *)
~~~~~

**Comment by ejgallego** [comment]
Possibly related to #11098

**Comment by gares** [comment]
It is a limitation of the current implementation, IIRC if the argument has no name then It can't be implicit...
