### ISSUE TITLE
dev/doc/MERGING.md should include a mention of how to check which file I'm a codeowner on

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#9110]
#### Version

master

#### Description of the problem

https://github.com/coq/coq/blob/master/dev/doc/MERGING.md#code-owners should include an invocation that will tell me which files I've been requested to review as codeowner on a particular PR.  Ideally, it should also mention the link to see all PRs that I've been requested for review on.

**Comment by SkySkimmer** [comment]
>an invocation that will tell me which files I've been requested to review as codeowner on a particular PR

You can try `dev/tools/check-owners-pr.sh xxxx` but it will sometimes be incorrect. Complain to github about it.
