### ISSUE TITLE
how to contribute to the standard library?

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9113]
At various points I have seen pull requests about adding one or another piece to the standard library. It seems to me that these take a long time to be resolved, and often the response is rather ambivalent. This perception is not ideal, even if inaccurate.

To make contributing to the standard library easier, it would be good to prepare some guidelines on what is expected of contributions, and what kind of contributions are accepted at all? In particular, 

- which parts of the standard library are deprecated or abandoned and should not be updated?
- if functions x and y are in the standard library, when is a lemma about the interaction of x and y welcome?
- what makes a function on existing types a good addition?
- when is a new type a good addition?
- what lemmas to submit in the same pr and what to submit as separate PRs?

I understand that it is probably best not to set the answers in stone, but at least I would find having even approximate guidance very helpful. Some of this might fit well in `CONTRIBUTING`.

For example, I have been dumping the following lemma out of my head on several projects:

~~~~~
    Lemma Z__testbit_mod_pow2 a n i (H:0<=n): Z.testbit (a mod 2 ^ n) i = ((i <? n) && Z.testbit a i)%bool.
    Proof.
      destruct (Z.ltb_spec i n);
        rewrite ?Z.mod_pow2_bits_low, ?Z.mod_pow2_bits_high
          by auto with zarith; trivial.
    Qed.
~~~~~

There are hundreds of similar lemmas in https://github.com/mit-plv/fiat-crypto/tree/master/src/Util/ZUtil, some of which are not useful commonly enough to be in the standard library.  https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/ListUtil.v#L60 is also a common source of copy-paste for me. https://github.com/mit-plv/fiat-crypto/tree/master/src/Util has even more rather generic stuff. I would love to get some of this included in the standard library so that I can point to that instead of explaining "yeah this lemma you are looking for has been proven as a part of several projects, look for it in this github repository of mine" over and over again.

Recent PRs about standard library are searched at https://github.com/coq/coq/pulls?utf8=✓&q=is%3Apr+label%3A"part%3A+standard+library"+

**Comment by Zimmi48** [comment]
Thanks for your question. I was wondering the same thing about one year ago as the standard library appeared as the most unattended / unmaintained part of the code so I asked a few questions during a Coq WG: https://youtu.be/euwh_ToBiYo?t=7588
This led to the stdlib2 project (https://github.com/coq/stdlib2) led by @maximedenes. There are no real plans to make contributing to the current standard library much easier because we would prefer people to contribute to stdlib2. Unfortunately the README of the project still claims to be in phase 1 (from what I heard, phase 3 has actually started) but in any case, external code contributions are only expected in phase 4.
I am well aware that you already know the existence of this project since you even opened issues in this repo. The fact that you are coming back here and asking how to contribute to the current standard library sounds IMHO like a warning to the people in charge of stdlib2 that they are not doing their job of making this a collaborative effort. At the very least, communication on what is happening needs to improve!

**Comment by Zimmi48** [comment]
Time has passed, the stdlib2 project has made some progress, and yet, it is far from the point where it is welcoming external code contributions. I am starting to think that we should in fact have contributing guidelines for stdlib1, and be more actively welcoming to contributions there as well, even if we expect stdlib2 to replace it at some point (but likely in a not-so-soon future).

I would support a PR adding some guidelines on how to contribute to the standard library to `CONTRIBUTING.md`. Such a section should probably say that we expect principally incremental (small) contributions, as opposed to stdlib2 at some later point.

But I think that we additionally need to start finding more maintainers for the standard library outside of the core development team. We just stared doing so with the new @coq/reals-library-maintainers team, but this could be done for other parts of the library as well.

**Comment by Zimmi48** [comment]
Some basic info for someone who would want to start writing such guidelines:
- the code for the standard library is in the `theories/` (and a bit in `plugins/`) in the main Coq repository (this repository);
- for now, the standard library is written in vanilla style, although if a user wanted to start using ssreflect somewhere that would not necessarily be a problem (but probably not in an existing file);
- not all files use bullets and focusing brackets, but modified code should introduce them (see also #9386);
- some modules contain comments about being deprecated: they should not be modified but can be removed (example: #9811);
- when adding a new file, it should be listed in https://github.com/coq/coq/blob/master/doc/stdlib/index-list.html.template;
- when submitting a PR, one can see in the statuses at the bottom a link to the stdlib doc artifact as soon as it has been produced;
- here is an example comment about what should probably go into the standard library: https://github.com/coq/coq/pull/9803#issuecomment-476184757.
