### ISSUE TITLE
Sphinx warning for use of single backticks.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#9118]
@cpitclaudel If I'm not mistaken, all uses of single backticks without a preceding `:foo:` in the manual are wrong (and people continue to introduce some because they are used to Markdown syntax). Can we get a warning for this? (We should really strive for a CI that catches as much as possible by itself. Nowadays, most of my documentation reviewing is to tell people they are not using the format correctly.)

**Comment by cpitclaudel** [comment]
I can look into a warning. But maybe we should instead assign a good default role to single backticks, and encourage people to use that?  For example, maybe single backticks should mean the same as `:g:`?

**Comment by Zimmi48** [comment]
Can we make single backticks be equivalent to double backticks? This is what people usually mean when they use them.
BTW it's not completely clear to me what purpose `:g:` serves in practice. It is supposed to be used for Coq terms, but vernacular too? It is displayed in bold contrary to double backticks verbatim, but is it also useful as a semantic tag, e.g. for company-coq?

**Comment by cpitclaudel** [comment]
I don't think it's useful as a semantic tag for company coq; the hope was to do Coq syntax highlighting on `:g:` parts, but not on regular double backtick blocks.

Yup, we can make it equivalent to double backticks. It should be enough to add `default_role = 'literal'` to conf.py (but I can't build Coq right now :/ can you test it?).

**Comment by Zimmi48** [comment]
It works, thanks! I'll open a PR.
