### ISSUE TITLE
Wrong environment when printing errors about modules

### ISSUE THREAD

**Issue by herbelin** [coq/coq#9136]
#### Version

master and before

#### Description of the problem

This is another example about being able to print module fields in the right environment:

```coq
Module Type MONAD.
  Parameter t : Type.
  Parameter ret : forall n:nat, t.
End MONAD.

Module MErr <: MONAD.
  Definition t := nat.
  Definition ret := @Some.
End MErr.
(* Signature components for label ret do not match: expected type
"??" but found type "forall A : Type, A -> option A". *)
```
Technically, the `??` is due to `Nametab.shortest_qualid_of_global` failing to find the name `MErr.t` in the name table.

There is a protection in `Constrextern` to catch errors from `Nametab.shortest_qualid_of_global` when printing a global reference, but, here, the call to `Nametab.shortest_qualid_of_global` is done in `Namegen` and it bypasses the protection put in `Constrextern` by `Printer.safe_gen`.

A quick fix, while waiting for more robust modules, would be to move the protection from `Constrextern.extern_reference` directly to `Nametab.shortest_qualid_of_global`.

**Comment by Alizter** [comment]
Seems to work in 8.15.
