### ISSUE TITLE
coqc.byte -vio2vo doesn't work

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#9141]
~~~bash
$ mkdir /tmp/tmp; cd /tmp/tmp
$ echo 'Lemma foo : Type. Proof. exact Type. Qed.' > foo.v
$ coqc -Q . X -quick foo.v
$ coqc.byte -Q . X -vio2vo foo
File .../plugins/ltac/ltac_plugin.cmxs is not a bytecode object file.
Warning: File ./foo.v: proof of foo: chars 29-40
Could not load plugin .../plugins/ltac/ltac_plugin.cmxs

$ coqc.byte -Q . X -quick foo.v
$ coqc.byte -Q . X -vio2vo foo
Warning: File ./foo.v: proof of foo: chars 29-40
File not found on loadpath : ltac_plugin.cmo
Loadpath: .../toploop:/tmp/tmp
~~~

**Comment by SkySkimmer** [comment]
Now works when -quick was used with coqc.byte.
Still broken when switching between byte and native, not sure if that's worse keeping an issue about (it may make it more annoying to ocamldebug vio2vo on a file produced with native, other than that who cares)

**Comment by ejgallego** [comment]
IMHO this bug should be kept open.

**Comment by gares** [comment]
I guess the problem is that the libobject for declare ml module has "foo" while the summary entry has "path/to/foo.cmxs" and if you change from opt to byte it tries to load the wong file:https://github.com/coq/coq/blob/master/vernac/mltop.ml#L342

**Comment by ejgallego** [comment]
Good catch, indeed mltop seems to have a few problems like that and we have been bitten by them in serapi. I'd like to change a few things there but we'd need to switch to findlib.dynlink first.

**Comment by ejgallego** [comment]
This should be solved by https://github.com/coq/coq/issues/7698

**Comment by ejgallego** [comment]
-vio2vo removed in #18424
