### ISSUE TITLE
Unshelve and Grab Existential Variables counterintuitive after admit

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9171]
#### Version

8.8.2

#### Operating system

Arch Linux, up to date as of yesterday.

#### Description of the problem

After using `admit` in a proof, `Unshelve` and `Grab Existential Variables` behave differently and neither behavior makes sense to me. The observed behavior is as follows:

```coq
Goal True.
  assert True as H by admit.
  exact H.

  (* subgoal 1 (ID 2) is: *)
  (*  True *)
  (* You need to go back and solve them. *)

  Unshelve.
  Fail idtac.
  (* The command has indeed failed with message: *)
  (*         No such goal. *)

  Grab Existential Variables.
  (*   ============================ *)
  (*   True *)

  exact I.
  Fail Qed.
  (* The command has indeed failed with message: *)
  (* Attempt to save a proof with given up goals. If this is really what you want to do, use *)
  (* Admitted in place of Qed. (in proof Unnamed_thm) *)

  Grab Existential Variables.
  Fail idtac.
  Unshelve.
  Fail idtac.
  Fail Qed.
```

Original occurrance: https://github.com/mit-plv/bedrock2/commit/fdd13872d8e098ebbaf276579e43b6166336b59d#diff-c0185cd7db6c073ff1d48ab41ebdfaabR387 (to reproduce remove `Require Import AdmitAxiom` from https://github.com/mit-plv/bedrock2/commit/fdd13872d8e098ebbaf276579e43b6166336b59d#diff-c0185cd7db6c073ff1d48ab41ebdfaabR271).

Maybe relevant for #9170

Potentially related #6202 (using `ltac:(...)`)

**Comment by herbelin** [comment]
I would say that the correct behavior is that `Grab Existential Variables` does not grab  goals which are explicitly recorded as having been given up. (Moreover, by grabbing given up goals, `Grab Existential Variables` is obviously breaking the invariant that to any given up goal is associated an evar which is _unresolved_.)

**Comment by andres-erbsen** [comment]
The behavior 8.4 had in this situation was exactly what I expected. I am not sure what an appropriate behavior would be because I don't know what was the motivation for changing it in the first place. I think I the most surprised by the fact that I can get to a state where all subgoals are solved (and there is no guardedness issue or anything) and `Qed` fails. So what @herbelin suggests sounds fine to me, though calling the admits `subgoals` is perhaps inappropriate -- based on this wording I thought I could solve them by continuing the proof, I expected `Unshelve` to succeed and let me finish the proof by filling in the admits.

**Comment by herbelin** [comment]
>  though calling the admits subgoals is perhaps inappropriate -- based on this wording I thought I could solve them by continuing the proof

I agree that this is confusing.

**Comment by Zimmi48** [comment]
>I expected Unshelve to succeed and let me finish the proof by filling in the admits.

No, this would not be appropriate because you would then be able to leave `admit` / `give_up` in your code. This is not intended that way.

**Comment by herbelin** [comment]
Is someone working on a fix of `Grab Existential Variables` here?

**Comment by Zimmi48** [comment]
If the goal is to deprecate / remove this command, I don't think that fixing it with respect to admitted goals is important. (In particular, it could be understood -and documented- that `Grab Existential Variables` grabs *all* existing existential variables, even though it doesn't make it possible to prove an admitted goal that way.)

**Comment by herbelin** [comment]
> I don't think that fixing it with respect to admitted goals is important.

Yes, that's a possibility. My point was that, in the meantime, the behavior is inconsistent with the concept of `given_up` goals and that it may be worth to do something about it rather than living in an unsatisfactory "no man's land".

Told otherwise: how to organize ourselves to fix the remaining problems of the shelf?

**Comment by Zimmi48** [comment]
>Told otherwise: how to organize ourselves to fix the remaining problems of the shelf?

I can answer to that part.

1. Find all the bugs in tested libraries by preparing overlays for #9170.
2. Fix the ones that are blocking (this one is not IMHO).
3. Deprecate then remove `Grab Existential Variables`

**Comment by herbelin** [comment]
> I can answer to that part.
>
> 1. Find all the bugs in tested libraries by preparing overlays for #9170.
> 2. Fix the ones that are blocking (this one is not IMHO).
> 3. Deprecate then remove `Grab Existential Variables`

Looks indeed good and realistic for 8.10.

**Comment by Alizter** [comment]
`Grab Existential Variables` has been deprecated https://github.com/coq/coq/pull/12516/commits/e348b1b6761315cdeea9e4c1c2f610ace9787e4a and removed https://github.com/coq/coq/commit/2564d001fba3bf9ea4533f87c73db4c64e94406d in favour of `Unshelve`. Therefore closing this issue.
