### ISSUE TITLE
Argument_renaming.rename_* called too often

### ISSUE THREAD

**Issue by gares** [coq/coq#9181]
Commit d335953af623429092303076c7bcf06ee5de50db calls the renaming machinery at each inner call in retyping. I may understand renaming the resulting type when the term being typecheck is a constant/inductive, but calling it at each node seems to much. I don't know when retyping is called, but here just printing a term seems to trigger a call to renaming...

**Comment by herbelin** [comment]
My commit message was not very informative about the examples that it covered, so I would need some further thinking to place myself in the context of the PR and of its impact.

@gares: is your question a question of efficiency or a question of semantics?

**Comment by gares** [comment]
I was adding a debug printing, printing a type, and incidentally I was also printing something in the code of arguments_renaming because I was fixing a bug there. And I noticed that the call to pr_constr_env was calling arguments_renaming many many times.

I thought it was just not intended. After all retyping seems a very technical component, far from the end user that is the one for which renamings are relevant after all.

**Comment by herbelin** [comment]
Yes, that seems far from the end user and I don't remember exactly why it was needed. Suspectingly for terms which are eventually exposed in goals and have an impact on hypothesis naming.

I let you decide whether you think something more should be done or if it can be closed.
