### ISSUE TITLE
Prop vs. Type and injectivity

### ISSUE THREAD

**Issue by sweirich** [coq/coq#9228]
#### Description of the problem

I was surprised by this behavior in Coq. 
This bit of code works:

```
Inductive C : Type := MkC.
Inductive T : Type := MkT : C -> T.
Lemma injT : forall x y, MkT x = MkT y -> x = y.
Proof. intros x y H. inversion H. reflexivity. Qed.
```

but this definition is unprovable (unless I unfold B or annotate B with Type).

```
Definition B := C.
Inductive U : Type := MkU : B -> U.
Lemma injU : forall x y, MkU x = MkU y -> x = y.
Proof. intros x y H. inversion H. Abort.
```

Even though the sorts of C & B are annotated with Type, Coq gives them both sort Prop. And equalities between Props are discarded by default (https://coq.inria.fr/refman/proof-engine/tactics.html#coq:tacn.inversion.) By why is the equality retained on the first example but not on the second?

**Comment by olaure01** [comment]
The behavior seems to be the same without the Type annotations:
```
Inductive C := MkC.
Inductive T := MkT : C -> T.
Lemma injT : forall x y, MkT x = MkT y -> x = y.
Proof. intros x y H. inversion H. reflexivity. Qed.

Definition B := C.
Inductive U := MkU : B -> U.
Lemma injU : forall x y, MkU x = MkU y -> x = y.
Proof. intros x y H.
inversion H. Fail reflexivity.
unfold B in x. inversion H. reflexivity.
Qed.
```

**Comment by herbelin** [comment]
Hi @sweirich, setting `Set Keep Proof Equalities` (e.g. locally to your proof) should also do the trick.

Implicit in @skyskimmer's answer is that there are actually two representations of `Prop` in the implementation. One is as an impredicative universe at the bottom of the `Type` hierarchy (an impredicative "hProp"), and another one is as an explicitly "tagged" copy of this impredicative universe, typically for the purpose of extraction. The code of Coq does not deal consistently with these two representations.
- in your first example, the system is using the representation as a `Type` universe and treats `Prop` as a `Type`,
- in the second example, it only sees the tagged (extraction-oriented) copy and intends `Prop` to be opaque (unless using `Set Keep Proof Equalities`).

The tendency, as hinted by @skyskimmer, is to go away from the underlying model and to make available to the user only the tagged copy. This is obtained by restricting the universe polymorphism quantification to universes above `Set`. Contrastingly, the choice was to implement template polymorphism using unrestricted universe polymorphism quantification, but this has turned to be a source of confusion for the users in the past.

**Comment by sweirich** [comment]
Thanks to both of you for the detailed answers.

**Comment by sweirich** [comment]
I will close this issue now as my question has been answered.
