### ISSUE TITLE
Universe polymorphism for parameter-free inductive types

### ISSUE THREAD

**Issue by herbelin** [coq/coq#9233]
#### Description of the problem

Trying to understand better #9228 and the difference between template and universe polymorphism, I arrived to the following question. Why
```
Polymorphic Inductive C (A : Type) : Type := MkC (a:A).
```
gives
```
Polymorphic NonCumulative Inductive
C@{Top.1} (A : Type@{Top.1}) : Type@{Top.1} :=  MkC : A -> C@{Top.1} A
```
but
```
Polymorphic Inductive D : Type := MkD.
```
gives
```
Polymorphic NonCumulative Inductive D@{Top.1} : Type@{Top.1} := MkD : D@{Top.1}
```
Is it an indirect effect of how the minimization heuristics are implemented, which would minimize the conclusion of `C` (as in template polymorphism) but not of `D`?

Indirectly related: is there a way to get a subtyping between `D@{Set}` into `D@{i}` [Added: or even an equality]? The following fails:
```
Universes i.
Check fun x : D@{Set} => x : D@{i}.
```

**Comment by SkySkimmer** [comment]
I don't understand the question. 
>Is it an indirect effect of ...

What do you mean by "it" exactly?

**Comment by SkySkimmer** [comment]
>Indirectly related: is there a way to get a subtyping between D@{Set} into D@{i}

That's what Cumulative does.

**Comment by herbelin** [comment]
> That's what `Cumulative` does.

My fault. I tried to set the `Cumulative` flag after the definition and it should have rung a bell that it was not taken into account since it was still printed `NonCumulative`.

> What do you mean by "it" exactly?

By "it", I mean that the type of `C` above is (only) `Type@{Top.1}` and not something of the form `Inductive C@{Top.1 Top.2} (A : Type@{Top.1}) : Type@{Top.2}` with `Top.1 <= Top.2` as in the case of `D`, or, conversely, that the type of `D` is `Inductive C@{Top.1} : Type@{Top.1}` and not simply `Inductive D : Type@{max()}`, as in the case of `C`, where `max()` would be here the smaller universe (i.e. typically `Set` if one wants all universes to be at least above `Set`).

As a comparison, extending the construction pattern to a longer arity, we have for instance:
```
Polymorphic Cumulative Inductive prod A B := pair : A -> B -> prod A B.
Print prod.
(* prod@{Top.4 Top.5} (A : Type@{Top.4}) (B : Type@{Top.5}) : Type@{max(Top.4,Top.5)} *)
```

So, I was wondering whether it was the way minimization was written which made that maybe, some virtual `Top.2` representing the conclusion was minimized to `Top.1` in the case of `C` but that in the case of `D`, the same universe representing the conclusion was not minimized to the minimal level?

In particular, assuming that my reconstruction of what happened is indeed what happened, would it make sense to do that the minimization gives `D : Set` so that the behavior is closer to what happens in the template case (up to having universes ranging over all `u` >= `Prop` in the template case, and over all `u` >= `Set` in the explicitly quantified case).

Side question, which probably was already answered, sorry about it. Is there an efficiency cost to cumulativity? And if not, why not to have it by default in the polymorphic case?

**Comment by SkySkimmer** [comment]
>So, I was wondering whether it was the way minimization was written which made that maybe, some virtual Top.2 representing the conclusion was minimized to Top.1 in the case of C

Yes, for inductive types after doing typechecking we turn the codomain universe into a flexible algebraic if it was introduced by `Type` (in the same way that template triggers when you use `Type` but not `Type@{u}`). Then we run minimisation which will collapse it with others guided by constraints.

> but that in the case of D, the same universe representing the conclusion was not minimized to the minimal level?

Minimisation turns a universe `u` into `Set` only when both `Minimization ToSet` is enabled (that's the default) and more importantly there must be a constraint `Set <= u`, which in the case of these inductives there isn't.

>Side question, which probably was already answered, sorry about it. Is there an efficiency cost to cumulativity? And if not, why not to have it by default in the polymorphic case?

We don't really know the cost (if there's one). HoTT breaks when cumulativity is enabled for non-understood reasons so we can't really bench.

**Comment by herbelin** [comment]
Thanks a lot for these information. So, if I understand correctly, the current status is:
- for the first point, to decide whether we want a change or not, and if yes, implementing it, I guess, by ensuring `Set <= u` at the time of generating the conclusion `u` of the inductive type;
- for the efficiency of cumulativity, that it may be instructive to investigate the failure of HoTT but that it is time demanding.

Is that your view too?

**Comment by maximedenes** [comment]
@SkySkimmer can you say if the final summary of @herbelin is accurate? If so, maybe we can close this issue.
