### ISSUE TITLE
Windows v8.9: AAC_tactics has wrong require statements

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#9234]
In the v8.9 branch there is a glitch in AAC_tactics. There used to be a patch to adjust import statements so that the Tutorial and other files would work out of the box (without adjusting Require commands). On December 6th this was corrected in AAC_tactics master:

https://github.com/coq-community/aac-tactics/commit/aead5cd61ec114d077d6128a87c908088292c36a#diff-19f9381828a2e9804938d9bab7e71f5e

and the patch in Coq was removed around the same time but now 8.9 has neither the patch nor the updated commit.

The easy fix is to update the version of AAC_tactics in ci-basic-overlay.sh

**Comment by Zimmi48** [comment]
Fixed in #9235.
