### ISSUE TITLE
CI should check META.coq.in

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#9253]
#### Version

8.10+alpha

#### Description of the problem

There is no sanity check of META.coq.in, as far as I can tell, and no doc on when it should be updated.  I am not entirely sure what should or should not go in this file, e.g., there's still natsyntax even though numeral notations removed the nat syntax plugin, and I added an entry for string notations, but there's no entry for numeral notations.

cc @ejgallego

**Comment by ejgallego** [comment]
`META.coq.in` will be removed / orphaned as soon as the Dune build is considered out of experimental status which should happen pretty soon.

**Comment by Zimmi48** [comment]
This file can be removed as soon as Dune becomes the only supported build system (likely before 8.10). In the meantime, indeed, this file should reflect closely what is generated by Dune but it seems a bit overkill to add a CI test just for this for such a short period.
