### ISSUE TITLE
merge-pr doesn't look at the azure status

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#9257]
It seems like because it's a "github check" merge-pr doesn't care about the status for azure pipelines.
We should either change the script or see if it's possible to have azure run as a regular CI.

**Comment by SkySkimmer** [comment]
We don't use azure anymore.

**Comment by Zimmi48** [comment]
Now we use GitHub Checks for everything in CI. So what we get is `error: CI unsuccessful on []` with a list always empty. This isn't a big deal since most people aren't using the `merge-pr.sh` script anymore, but it would probably make sense to simplify it to only print `error: CI unsuccessful`.
