### ISSUE TITLE
lia works less well with universe polymorphism than omega

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#9268]
#### Version

8.8.2

#### Description of the problem

```
Require Import Coq.ZArith.ZArith.
Require Import Coq.micromega.Lia.

Local Open Scope Z_scope.

Definition Register := Z%type.

Definition Opcode := Z%type.

Inductive InstructionI : Type
  := Lb : Register -> Register -> Z -> InstructionI
  |  InvalidI : InstructionI.

Inductive Instruction : Type
  := IInstruction : InstructionI -> Instruction.

Definition funct3_LB : Z := 0.

Definition opcode_LOAD : Opcode := 3.

Set Universe Polymorphism.

Definition MachineInt := Z.

Definition funct3_JALR := 0.

Axiom InstructionMapper: Type -> Type.

Definition apply_InstructionMapper(mapper: InstructionMapper Z)(inst: Instruction): Z :=
  match inst with
  | IInstruction   InvalidI   => 2
  | IInstruction   (Lb  rd rs1 oimm12) => 3
   end.

Axiom Encoder: InstructionMapper MachineInt.

Definition encode: Instruction -> MachineInt := apply_InstructionMapper Encoder.

Lemma foo: forall (ins: InstructionI),
    0 <= encode (IInstruction ins) ->
    0 <= encode (IInstruction ins) .
Proof.
  Set Printing Universes.
  intros.
```

opens the following goal:

```
  ins : InstructionI
  H : 0 <= encode@{Top.1295} (IInstruction ins)
  ==============================================
  0 <= encode@{Top.1296} (IInstruction ins)
 ```

On this goal, `lia` fails with "Cannot find witness", while `omega` and `assumption` succeed.

#### Desired behavior:

`lia` should solve the goal.

/cc @andres-erbsen

**Comment by samuelgruetter** [comment]
Just ran into this again, would be good to have this fixed, especially for goals which `lia` can solve but `omega` cannot solve.
My current workaround is to `Set Printing Universes`, then look for terms `t` which differ only by universes, and to `remember t as x` for all such `t`, followed by `lia`, but that's very cumbersome if `lia` is used as a part of a bigger script.

**Comment by ppedrot** [comment]
I think that this is due to this snippet in Coq_micromega:
```
   let compute_rank_add env sigma v =
    let rec _add env n v =
     match env with
      | [] -> ([v],n)
      | e::l ->
         if EConstr.eq_constr sigma e v
         then (env,n)
         else
          let (env,n) = _add l ( n+1) v in
           (e::env,n) in
    let (env, n) =  _add env 1 v in
     (env, CamlToCoq.positive n)
```
It should use a universe-aware equality test instead, and propagate the constraints.

**Comment by samuelgruetter** [comment]
I think that unfortunately, this issue is not yet resolved.
I just tested with latest Coq master (commit 424c1973e96dfbf3b2e3245d735853ffa9600373, Mon Apr 1 19:40:53 2019 +0000, `Merge PR #9725: Lia:  various impovements (support for #8764, fix #9268 and  #9615)`), and I while the case I posted above now indeed works, I still have a case where `lia` fails, but `split; lia` succeeds, and `omega` succeeds as well.

You can see this case here: https://github.com/mit-plv/bedrock2/blob/49ed956ae0b170d40cf695be121053971ca8afbe/compiler/src/EmitsValid.v#L545

I tried to isolate it, but I failed, because I can't get to print enough internals to make it apparent how two terms which should be the same differ.

I tried

```
Set Printing Implicit.
Set Printing Universes.
Set Printing All.
```

and then the goal looks as follows:

```
  compilation_params : parameters@{Top.18 Top.19 Top.20 Top.21}
  binds : list Register
  a : @actname compilation_params
  args : list Register
  H : Z.le Z0 (@Zlength Instruction (@compile_ext_call compilation_params binds a args))
  H0 : Z.le (@Zlength Instruction (@compile_ext_call compilation_params binds a args))
	 (Zpos (xI (xI xH)))
  ==============================================================================================
  Logic.and (Z.le Z0 (@Zlength Instruction (@compile_ext_call compilation_params binds a args)))
    (Z.le (@Zlength Instruction (@compile_ext_call compilation_params binds a args))
       (Zpos (xI (xI xH))))
```

`lia` fails on this goal, but if I do

```
remember (@compile_ext_call compilation_params binds a args) as C.
```

then the goal becomes

```
  compilation_params : parameters
  binds : list Register
  a : actname
  args : list Register
  C : list Instruction
  HeqC : C = compile_ext_call binds a args
  H : 0 <= Zlength C
  H0 : Zlength C <= 7
  ========================================
  0 <= Zlength C <= 7
```

and `lia` succeeds.
So I assume that the three occurrences of `C` somehow differ, and `lia` doesn't recognize that they're the same, but I don't know how I can print all the internals which would reveal how they differ.

Apologies for not being able to minimize the bug; could you please have a look at it in the full context? Building bedrock2 should be simple, just make sure you clone with the `--recursive` option, and then `make -j2` should work.

**Comment by fajb** [comment]
This goes beyond my understanding of universes...
When printing the terms (on the ml side) I get:
- one term C1 with universe annotations 
- another term C2 without such annotations
Moreover, C1 <> C2 even when ignoring universes `EConstr.eq_constr_nounivs` returns false
Yet, C1 and C2 can be unified `Unification.w_unify` succeeds.

A fix would be to always try to unify. This looks costly and overkill...
If there is no lighter suggestion, this is what I would propose...

For the record, the terms C1 and C2 obtained by `Printer.pr_econstr_env' are:
C1 : 
@Zlength Instruction
  (@compile_ext_call@{compiler.EmitsValid.18 compiler.EmitsValid.19 compiler.EmitsValid.20
     compiler.EmitsValid.21} compilation_params binds a args)

C2 : @Zlength Instruction (@compile_ext_call compilation_params binds a args)

**Comment by JasonGross** [comment]
Just a guess, but is one of these the compatibility constant for a primitive projection and the other one not?  (I imagine that primitive projections do not take universes.)

**Comment by SkySkimmer** [comment]
>I still have a case where lia fails, but split; lia succeeds, and omega succeeds as well.

Is this still such that disabling univ polymorphism lets it succeed? Otherwise please go to a new issue.

**Comment by samuelgruetter** [comment]
I don't know if disabling universe polymorphism would make it succeed, and in order to know, I would have to minimize it (which I failed at) or to temporarily disable universe polymorphism for (almost) all of bedrock2, which might be a bigger undertaking, so I'm afraid I'm unable to answer your question @SkySkimmer.

**Comment by fajb** [comment]
@JasonGross I think you are right: primitive projections are the culprit.
The reification code should use some `EConstr.eq_constr_universes_proj` and not `EConstr.eq_constr_universes`.
I say some because I think the  terms are of the form 
App(Const(compile_ext_call),[|compilation_params binds a args|])
and
App(Proj(compile_ext_call,compilation_params),[|binds a args|])
which does not seem to be covered.

**Comment by JasonGross** [comment]
@samuelgruetter you should be able to minimize it by, after copy/pasting the goal, ruining `cbv delta [<projection>]` in either the goal or the hypotheses (but not both).

**Comment by samuelgruetter** [comment]
Minimized new issue: https://github.com/coq/coq/issues/9892
