### ISSUE TITLE
`Unset Nested Proofs Allowed` does not capture nested `Instance` proofs.

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#9272]
On `master`, `Goal True. Goal True.` triggers an error, but:

```coq
Class C := { n : nat }.
Instance: C. Instance: C.
```

passes. I believe this is a bug, that will make migrating to `Unset Refine Instance Mode` more difficult. I'll try to fix it.

**Comment by maximedenes** [comment]
In fact, we can be conservative and forbid commands which *may* open proofs inside proofs.

**Comment by ejgallego** [comment]
Indeed #9129 should make this kind of stuff much easier to spot / refactor.

The PR itself seems ready, but a few questions indeed may appear in some parts that like to open proofs.
