### ISSUE TITLE
Override/remove existing coercions

### ISSUE THREAD

**Issue by tonyxty** [coq/coq#9275]
I can't find a way to override/remove a coercion once it is added.  Say if a library I imported declares a coercion `bool >-> nat`, sending `true` to `1` and `false` to `0`.  But I want the opposite
`Local Coercion bool_to_nat' (b:bool) := match b with true => 0 | false => 1 end.`
Currently this does not seem possible, even locally.  Coq just gives an `Ambiguous paths` warning and ignores the latter declaration.

Some possible solutions that comes to mind:

- Add commands to manipulate them like hints in a HintDb.
- Or perhaps add a priority system to resolve ambiguous paths?
- Or the simple solution: when ambiguous paths occur, let the new declaration override the old one.  And local ones always take over global ones.

**Comment by jgrosso** [comment]
This isn't a solution, but here's a hack that might work for others:

I'm using the [Extructures](arthuraa/extructures) library, and I wanted to override the built-in coercion from `{fmap A}` to `A -> Prop`. So, I wrapped the original constructor (`FMap.fmap_of`) with my own `fmap_of'` function and redefined the notation. Apparently, `fmap_of` and `fmap_of'` being nominally different was enough to let me define a new coercion.

```coq
(** Coercions can't be overridden, so we'll define a wrapper type (and some new, yet similar-looking)
    notation to convince Coq to use this coercion instead. *)
Definition fmap_of' (S : ordType) (T : Type) := @FMap.fmap_of _ _ (Phant (S -> T)).

Notation "'{' 'fmap' S '→' T '}'" := (fmap_of' S T) (at level 0) : type_scope.

Definition fmap_to_Prop (A : ordType) (B : Type) (R : {fmap A → B}) (k : A) (v : B) : Prop :=
  getm R k = Some v.

Coercion fmap_to_Prop : fmap_of' >-> Funclass.
```

**Comment by ana-borges** [comment]
I believe that as of 8.15 it is now possible to import everything except coercions, cf. https://github.com/coq/coq/pull/14892.
