### ISSUE TITLE
CeCILL-B license blocks ssreflect inclusion in Debian

### ISSUE THREAD

**Issue by bbarenblat** [coq/coq#9281]
CC: @gares, @maximedenes, @Zimmi48

While packaging Coq 8.8.2 for Debian, I noticed that plugins/ssrmatching/ssrmatching.mli and plugins/ssrmatching/ssrmatching.v still have [CeCILL-B](https://cecill.info/licences/Licence_CeCILL-B_V1-en.html) license headers. I believe CeCILL-B is not DFSG-free: Section 5.3.4 requires that

> Any Licensee who may distribute a Modified Software hereby expressly agrees to … mention, on a freely accessible website describing the Modified Software, at least throughout the distribution term thereof, that it is based on the Software licensed hereunder, and reproduce the Software intellectual property notice….

This fails the [desert island test](https://wiki.debian.org/DesertIslandTest) – a community of developers without internet access will be unable to comply with the terms of the license and will therefore be unable to legally distribute modified versions among themselves.

Looking at the discussion on the [ssreflect merge](https://github.com/coq/coq/pull/669), it sounds like the Coq development team may have the authority to relicense those files under LGPL-2, which would be ideal. Otherwise, Debian will be unable to ship ssreflect with Coq in Debian’s next release.

**Comment by gares** [comment]
I read the merge PR and indeed there I acknowledge that when a part of SSR was merged into Coq (ssrmacthing) its code was under a dual license (CeCILLE-B + LGPL 2.1) I forgot to pick the one that better fit. I'll prepare a PR, but it will be on master, not sure how helpful it will be for packaging 8.8.2.

**Comment by gares** [comment]
Merry Christmas!

**Comment by bbarenblat** [comment]
The 8.9.0 release introduced [plugins/ssrmatching/g_ssrmatching.mli](https://github.com/coq/coq/blob/cdfbae93094594dac72eb9464fadd652836e7e0d/plugins/ssrmatching/g_ssrmatching.mli), which is licensed under CeCILL-B. Should that file also have its license banner changed?

**Comment by Zimmi48** [comment]
Indeed, that was clearly an overlook. The corresponding `.ml4` file has the right header.

**Comment by Zimmi48** [comment]
@bbarenblat Is this urgent for the Debian freeze as well?

**Comment by bbarenblat** [comment]
Less so. Policy allows developers to upload “small, targeted fixes” during a freeze; I’d consider this a small and targeted fix. However, if you have the chance to commit a change to the header in the next day or two, that would make my life a bit easier. :)
