### ISSUE TITLE
Project level option system

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#9295]
Currently if you want to set some options throughout your project (eg Primitive Projections) you either put `Set Primitive Projections.` at the top of every file, or put `Export Set Primitive Projections.` in some options file and `Require Import myoptions.` at the top of all other files. This is a pain and liable to lead to forgetting to do it for new files. You can also `Global Set` in your options file and require it whenever it isn't already transitively required but this is messy especially if you want people to use you as a library.
Alternatively you could put `-arg -l -arg myoptions.v` in your _CoqProject, but coq_makefile won't register the dependency and there are probably random things breaking.

Meanwhile if we want to set an option for the stdlib without setting it for everyone else we have no way to do it really (or maybe the -l hack would work).

Can we come up with some better system? Preferrably something that we can get to work with both coq_makefile and the upcoming dune build systems.
cf #8052, [some WG discussion about _CoqProject format](https://github.com/coq/coq/wiki/CoqWG-2018-12-19)

**Comment by ejgallego** [comment]
That's a tricky issue IMHO that goes down to the current libobject design. Dune could support the `-l` approach fine, but it seems quite messy. Using command line parameters/flags could be better [like OCaml does for -safe-string] and indeed you could even save in `dune-package` which options are transitive.

But a problem here is that options are really too heterogeneous.

**Comment by Zimmi48** [comment]
Note that there already exist some options which have corresponding command line flags (e.g. `-w`). So this issue boils down to: do we want to manually extend this list, or do we want a generic way of setting an option through a command-line flag? I would lean towards the latter, and this generic support would in fact be quite consistent with what I proposed in #8027 (to have a generic way to set an option locally to a single command using an attribute).

**Comment by ejgallego** [comment]
I plan to extend the dune file format to support this, at least for a few choices such as primitive projections, consistency options, etc...

**Comment by Zimmi48** [comment]
Doesn't look doable if `coqc` itself doesn't support setting these options on the command line...

I'd also like to understand how the choice between which options are supported and which are not will be done. It sounds much saner to me to just add a generic mechanism that supports setting any option on the command-line, and add support for this mechanism in Dune.

**Comment by Zimmi48** [comment]
Closed by #9876
