### ISSUE TITLE
Fiat-crypto-legacy targets used by CI are unusable

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#9298]
Our CI script for fiat-crypto-legacy runs the following commands:
```
git submodule update --init --recursive
./etc/ci/remove_autogenerated.sh 
make print-old-pipeline-lite old-pipeline-lite lite-display
make print-old-pipeline-nobigmem old-pipeline-nobigmem nonautogenerated-specific nonautogenerated-specific-display
```

On my machine, the third step takes 10-15 minutes before starting to compile a file... which makes it practically impossible to write an overlay.

**Comment by maximedenes** [comment]
In fact, it seems I had discussed this before, and @JasonGross implemented a `coq-without-new-pipeline` target that was more efficient (to be tested). Shouldn't we track that one instead of the current ones?

**Comment by JasonGross** [comment]
Is this now fixed?  Or is there still an issue?  The transfer to a frozen branch has been completed.

**Comment by maximedenes** [comment]
This is not fixed. `make ci-fiat-crypto-legacy` still takes ages before even launching `coqc`.

**Comment by JasonGross** [comment]
I want to confirm: this is true even after running `./etc/ci/remove_autogenerated.sh`?  The propose of this script is to remove hundreds of .v files which are only built when requested, which vastly slow down the build.  (Don't commit the changes made by this script (which should only touch files you're not worried about).  Or do commit them, and I can strip the changes from the PR myself.)

If indeed the issue persists after running this script, I can fix the build system within 10 days.

**Comment by JasonGross** [comment]
Oh, I see you are running exactly the script of the CI with `make ci-fiat-crypto-legacy`.  I'll prepare a fix within 10 days.
