### ISSUE TITLE
Create grammar extraction tool for documentation; changes to how grammars are used in the doc

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#9310]
We need a tool to generate Sphinx `.. productionlist::` constructs and regular expressions such as those used in  `.. tacn:: apply {? @term }` and `.. cmd:: {? Local|Global} Obligation Tactic := @tactic` automatically.  This will improve correctness and completeness of the grammars in the documentation.  I expect the output will still need manual editing to get the most readable result.

I have a rough prototype that extracts the grammar from the .mlg files using the AST from coqpp.  (The other approach would be to extract it from the Coq parser.  That seemed like it would be harder to reverse engineer and might not have all the info we want.)

The tool would also produce a file with the entire combined grammar (and only the grammar) in a single file--stripping out non-grammar parts of the `.mlg` files such as production actions and OCaml code.  This should be much easier to read.  If we check that file into to git, it should make it easier to identify future grammar changes that will require documentation changes.

The tool could generate plugin-specific output describing the extensions in each plugin.  I'm not sure we cover that in the doc today.

Currently some of the `.. productionlist::` constructs use metacharacters such as `[` and `|` that are also literal values that are used in the Coq grammar, which tends to be confusing.  I'd like to avoid having any metacharacters here.  This can be done by automatically rewriting in-line constructs such as `LIST1 constr SEP "."` with a new non-terminal and productions.  Same idea for `OPT constr` and `[ A | B ]`.  Empty productions can be made more explicit by having them all refer to a single `empty` non-terminal.

Sphinx regular expressions lack a way to represent `[ A | B ]`, which is needed for a handful of productions.  So again we use the same character as both a regular character and a metacharacter.  (I had a prototype for such a construct working months ago, but I couldn't do the latex part--help appreciated.)

Probably the tool would be able to do a few editing operations.  For example, it might automatically replace a reference to a specified nonterminal with its right-hand side.  The tool probably could output a subset of the grammar defined by a set of top and bottom symbols (e.g. all productions reachable from `simple_tactic` but excluding `constr`, ...).

Let me know your thoughts.

**Comment by Zimmi48** [comment]
>The tool could generate plugin-specific output describing the extensions in each plugin. I'm not sure we cover that in the doc today.

For now the doc for plugins is mixed up with the rest of the reference manual.

>Let me know your thoughts.

Ideally, given enough annotations, the tool could produce exactly the same grammar as included in the manual and thus verify that the manual is in sync with the parser and be included in CI. Obviously, this should be harder to do, so it could be done as a later step.

**Comment by jfehrle** [comment]
> For now the doc for plugins is mixed up with the rest of the reference manual.

I imagine plugins add a limited number of productions to existing non-terminals plus a larger number of their own non-terminals.  I think the best approach would be to show the added productions integrated into the main grammar but marked to indicate they're for a specific plugin, e.g. like the `(SSR plugin)` below.

```
intropattern_list          ::=  intropattern ... intropattern
                                empty                       (SSR plugin)
```

The new non-terminals would be in a separate section for each plugin.  There could be a note before the productionlist mentioning the required plugin.  I suppose there could be a parenthetical comment on every line to that affect, but that's surely overkill.

**Comment by Zimmi48** [comment]
Well, a very big part of the grammars come from the Ltac plugin itself, although this one is loaded by default, so I suppose you were mostly talking about the ones that are not.
In any case, the grammar introduced by the SSR plugin itself is not so small (see https://coq.inria.fr/refman/proof-engine/ssreflect-proof-language.html#introduction-in-the-context for instance).
When these plugins are documented in separate chapters (which is the case most of the time), it makes sense to keep the grammar definitions in the specific chapters...

**Comment by Zimmi48** [comment]
Most of this work has already been done (thanks to @jfehrle). The integration of the corrected grammar in the manual is under way. The later steps will involve cleaning the edit files as much as possible (i.e. making the parser closer to the documented grammar when this does not change the semantics) and automatically checking that new changes to the grammar are documented. I'm leaving this issue open to track this.

**Comment by Zimmi48** [comment]
Closing in favor of #16652.
