### ISSUE TITLE
Implicit arguments are not inferred on Instances with implicit binders.

### ISSUE THREAD

**Issue by jashug** [coq/coq#9313]
#### Version
Coq master 2a7992f75c86a15512568ac61ca4c43e23242b28

#### Description of the problem

```
Set Implicit Arguments.
Existing Class True.

Instance foo1 (a : nat) {b : nat} (e : a = b) : True := I.
About foo1.
(* Argument b is implicit and maximally inserted *)
Fail Check foo1 (a := 3).
Check foo1 3.

Definition foo2 (a : nat) {b : nat} (e : a = b) : True := I.
About foo2.
(* Argument a is implicit
   Argument b is implicit and maximally inserted *)
Check foo2 (a := 3).
Fail Check foo2 3.

Instance foo3 (a b : nat) (e : a = b) : True := I.
About foo3.
(* Arguments a, b are implicit *)
```

This is inconsistent with the behavior of all other commands, Definition,
Theorem, Record, etc., and arises from the two uses of `~enriching:false` in `classes.ml`.
(The declaration of instances is the only place setting `~enriching:false`, apart from the `Arguments` command)
https://github.com/coq/coq/blob/8c040974facb733682d24c488dc89941671f4ab7/vernac/classes.ml#L111
https://github.com/coq/coq/blob/8c040974facb733682d24c488dc89941671f4ab7/vernac/classes.ml#L154

**Comment by maximedenes** [comment]
@mattam82 was this behavior desired or not?

**Comment by mattam82** [comment]
Nope, that’s an overlook I think.
