### ISSUE TITLE
Names generated by `Instance` can clash

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#9323]
Defining anonymous instances can fail at `Qed` because it generates a name which clashes:

in `A.v`
```coq
Class C := { x : True }.
Global Instance: C.
now constructor.
Qed.
```

in `B.v`
```coq
Require A.

Instance: A.C.
now constructor.
Qed.

Import A.

Instance: C.
now constructor.
Qed.
```

This is making the resolution of https://github.com/coq/coq/pull/8094 painful, because the warning suggests to insert an `Import`, but then we often fall in this case, where some instance definitions error.

**Comment by maximedenes** [comment]
@mattam82 do you know where this could come from?

**Comment by mattam82** [comment]
Certainly the fresh name generation for anonymous instances is not using the right set of identifiers to avoid.

**Comment by mattam82** [comment]
Hmm, the Namegen.is_global is misleading, it treats imported refs as not clashing, which hides the fact that the identifier was also used for the first instance declaration in B.v

**Comment by maximedenes** [comment]
Well, `is_global` has no written spec. What does "global" mean in this context? AFAIK, the only thing that matters w.r.t. the kernel is that the label should be fresh in the structure containing the definition.

**Comment by mattam82** [comment]
I suppose for namegen.ml, the spec should be indeed what you propose: the identifier should be free in the current structure so that one can add an object labeled by it in the structure. @herbelin right?

**Comment by herbelin** [comment]
Right, the `is_global` test is wrong and should be what you said. And this presumably applies to the name-generating command `Goal` as well.
