### ISSUE TITLE
Anomaly Grammar.extend when defining notation

### ISSUE THREAD

**Issue by tchajed** [coq/coq#9329]
#### Version

The Coq Proof Assistant, version 8.10+alpha (December 2018)
compiled on Dec 31 2018 5:54:58 with OCaml 4.07.0

#### Operating system

macOS 10.14.2

#### Description of the problem

This notation triggers `Error: Anomaly "Uncaught exception Failure("Grammar.extend")."`:

```coq
Notation "< a ; b >" :=
  (sum a b) (at level 18, a at level 19, b at level 20).
```

It seems the levels are important to triggering the bug.

**Comment by herbelin** [comment]
Fixed in #9337. Thanks for reporting.
