### ISSUE TITLE
I installed Coq, but it does not start.

### ISSUE THREAD

**Issue by jawilliam** [coq/coq#9330]
#### Version
8.8.2

#### Operating system
Windows 10 Pro 64 bits

#### Description of the problem
I installed, but it does not start.

**Comment by gares** [comment]
I assume you are trying to start coqide, right?

**Comment by jawilliam** [comment]
Yes, I do. I was several days normally working with CoqIde and suddenly it started to do this. When I execute it, I can see the process with the task manager, but no user interface is showed. I have reinstalled it several times, but there is not way it newly shows its interface.

**Comment by gares** [comment]
I've no idea of what could have happened, but I guess that it is due to some change happened to your system (OS updates, other software you installed).

Maybe try to really remove Coq's directory before reinstalling, to be sure nothing in there annoys a freshly installed Coq.

**Comment by SkySkimmer** [comment]
@jawilliam any news?

**Comment by jawilliam** [comment]
No, simply I cannot use Coq in laptop anymore.

**Comment by Zimmi48** [comment]
@jawilliam The question was: did you try the suggestion above?

>Maybe try to really remove Coq's directory before reinstalling, to be sure nothing in there annoys a freshly installed Coq.

**Comment by jawilliam** [comment]
Yes, I did. In fact, I did it many times.

**Comment by maximedenes** [comment]
@jawilliam Are you still experiencing the problem?

**Comment by ppedrot** [comment]
No answer and too little debug data to find out the reason, so closing.
