### ISSUE TITLE
Yet another Anomaly: Evar was not declared

### ISSUE THREAD

**Issue by Ptival** [coq/coq#9333]
#### Version
The Coq Proof Assistant, version 8.8.1 (January 2019)
compiled on Jan 2 2019 11:47:15 with OCaml 4.06.1

#### Operating system
Mac OSX Mojave

#### Description of the problem
Trying to write some zip for vectors, I encountered the "Evar was not declared" anomaly:

```
Require Coq.Vectors.VectorDef.
Require Import PeanoNat.

Fixpoint vectorZip {a b : Type} :
  forall {n : nat} (xs : VectorDef.t a n) (ys : VectorDef.t b n), VectorDef.t (a * b) n :=
  fix vectorZipFix {n} (xs : VectorDef.t a n) (ys : VectorDef.t b n) {struct xs} : VectorDef.t (a * b) n :=
    match
      xs in VectorDef.t _ n'
      return VectorDef.t b n' -> VectorDef.t (a * b) n'
    with
    | VectorDef.nil _ => fun _ => VectorDef.nil _
    | VectorDef.cons _ x pn xs =>
      fun ys =>
        match
          ys in VectorDef.t _ n'
          return S pn = n' -> VectorDef.t a pn -> VectorDef.t (a * b) n'
        with
        | VectorDef.nil _ => fun absurd => False_rect _ (Nat.neq_succ_0 _ absurd)
        | VectorDef.cons _ y pn' ys =>
          fun eq => fun xs' =>
                  let xs' := eq_rect _ _ xs _ (eq_add_S _ _ eq) in
                  VectorDef.cons _ (x, y) pn' (vectorZipFix xs' ys)
        end eq_refl xs
    end ys.
```

**Comment by Ptival** [comment]
The following almost identical alternative succeeds:
```
Fixpoint vectorZip {a b : Type} {n : nat} (xs : VectorDef.t a n) (ys : VectorDef.t b n) : VectorDef.t (a * b) n.
  refine (
    match
      xs in VectorDef.t _ n'
      return VectorDef.t b n' -> VectorDef.t (a * b) n'
    with
    | VectorDef.nil _ => fun _ => VectorDef.nil _
    | VectorDef.cons _ x pn xs =>
      fun ys =>
        match
          ys in VectorDef.t _ n'
          return S pn = n' -> VectorDef.t a pn -> VectorDef.t (a * b) n'
        with
        | VectorDef.nil _ => fun absurd => False_rect _ (Nat.neq_succ_0 _ absurd)
        | VectorDef.cons _ y pn' ys =>
          fun eq => fun xs' =>
                  let xs' := eq_rect _ _ xs _ (eq_add_S _ _ eq) in
                  VectorDef.cons _ (x, y) pn' (vectorZip _ _ _ xs' ys)
        end eq_refl xs
    end ys
    ).
Defined.
```

**Comment by herbelin** [comment]
From an implementation point of view, the analysis is the following. The elaboration-level guard checker `Pretyping.search_guard` calls the kernel-level guard checker `Inductive.check_fix`. The latter fails but the term contains evars. The kernel-level guard checker produces an error in an empty evar map (since it is a kernel error and the kernel is not supposed to know evars). Then, the error printer fails at the time of printing the evar.

I see two possible solutions:
- Raising a specific elaboration-level guard error containing the right evar map so that the printer does not fail.
- Checking that the term has no evar before calling the kernel guard checker.

I feel that solution 2 would be less informative user-side and I would be tempted to try solution 1. Any opinion on what to do best?

**Comment by herbelin** [comment]
In any case, thanks @Ptival for reporting!

**Comment by Columbus240** [comment]
On 4814585a11468b171eaa7b41eb4ea8dc48a647e1, the situation is still similar as before. The second definition succeeds while the first fails. Notably, it doesn’t fail with "Anomaly" anymore, but with 'Recursive definition of vectorZipFix is ill-formed."

Interestingly, the following code is accepted. I.e. the `fix` in the first example was unnecessary.
```coq
Fixpoint vectorZip {a b : Type} {n : nat} (xs : VectorDef.t a n) (ys : VectorDef.t b n) : VectorDef.t (a * b) n :=
    match
      xs in VectorDef.t _ n'
      return VectorDef.t b n' -> VectorDef.t (a * b) n'
    with
    | VectorDef.nil _ => fun _ => VectorDef.nil _
    | VectorDef.cons _ x pn xs =>
      fun ys =>
        match
          ys in VectorDef.t _ n'
          return S pn = n' -> VectorDef.t a pn -> VectorDef.t (a * b) n'
        with
        | VectorDef.nil _ => fun absurd => False_rect _ (Nat.neq_succ_0 _ absurd)
        | VectorDef.cons _ y pn' ys =>
          fun eq => fun xs' =>
                  let xs' := eq_rect _ _ xs _ (eq_add_S _ _ eq) in
                  VectorDef.cons _ (x, y) pn' (vectorZip xs' ys)
        end eq_refl xs
    end ys.
```
IMHO it’s fine as it is now.

**Comment by ejgallego** [comment]
Thanks for triaging this issue @Columbus240 , I will proceed to close.
