### ISSUE TITLE
Windows installer: and Flocq and Interval as packages to Windows installer

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#9351]
I want to add Flocq (indepdendent of VST or CompCert) and Coq-Interval as Windows installer packages. On the way I would also add Interval to CI.

Configuring and building Flocq and Interval is straight forward, but there are a few issues with remake install:

- cause of the mix of MinGW and cygwin, the install path ends up to have a \r in it, which is added to the path - likely some issue with awk (it does not strip \r on cygwin)
- examples are not installed
- README is not installed
- quite a few (but not all) examples import Interval with Require Import Interval_tactic (without Interval.)

I think the last one should be fixed in the Interval sources, but for the install issues I am not so sure. Redoing the installer and including examples and README would be 3 lines in the shell script. On the other hand fixing the \r issue might be rather intricate since I think awk or whatever is called via some automake / configure magic, so that I can't easily add a strip (might have to patch automake). We had a lot of similar issues with sed and I ended up compiling a patched sed which strips \r.

@silene : First I hope that you don't have any objections against adding Flocq and Interval. Then I would like to have your opinion on how to get around the install issues:

a) simply write my own install procedure
b) Fix the /r issue and add installation of examples and README to the remake install target

**Comment by Zimmi48** [comment]
@MSoegtropIMC @vbgl I am turning this issue into a blocker for 8.10.0 because given that it was "fixed" in 8.9.1, not doing it for 8.10.0 would be a serious regression.

**Comment by MSoegtropIMC** [comment]
One missing thing here is Gappa tool, which I also added in 8.9.1. It originally crashed on 64 bit Windows cause of the int/pointer size difference there. I fixed it and provided a patch to @silene which he was not 100% happy with. I can quickly make a PR which is equivalent to what is in 8.9.1. I would say the risk is low. Worst case gappa tool (an external C++ app) crashes and fails to provide a proof. But I tested my patched version quite a bit and so far it did work fine, so I think it is better than not having it.

**Comment by silene** [comment]
I have now released Gappa 1.3.5, which should hopefully fix the remaining issues on 64-bit Windows, hopefully.

**Comment by Zimmi48** [comment]
@MSoegtropIMC This is a gentle reminder of this issue, now that you are no longer busy with fixing CoqIDE on Windows.

**Comment by Zimmi48** [comment]
@MSoegtropIMC ping

**Comment by MSoegtropIMC** [comment]
Yes, sorry - I somehow forgot about it since it is already in 8.9.1 and I am working daily with it - will do it together with the pinning this weekend.
