### ISSUE TITLE
Unbound value and unbound module errors with QuickChick

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#9365]
See QuickChick/QuickChick#137.

#### Version

Coq 8.8.2

QuickChick 1.0.2

OCaml 4.07.1

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following code fails for no reason.

```
From QuickChick Require Import QuickChick.

Inductive litter := metal | plastic.
Derive GenSized for litter.
Derive Show for litter.

Module Pain.

  Inductive lint := dust | fabric.
  Derive GenSized for lint.
  Derive Show for lint.

End Pain.

Module Suffering.

  Check arbitrary : G litter.
  Fail Sample (arbitrary : G litter).

  Import Pain.

  Check arbitrary : G lint.
  Fail Sample (arbitrary : G lint).

End Suffering.

Import Pain.

Sample (arbitrary : G litter).
Sample (arbitrary : G lint).
```

```
arbitrary : G litter : G litter
QuickChecking (arbitrary : G litter)
File "/tmp/QuickChick/009001/QuickChickbeefed.ml", line 824, characters 18-28:
Error: Unbound value showlitter
The command has indeed failed with message:
Could not compile test program

arbitrary : G lint : G lint
QuickChecking (arbitrary : G lint)
File "/tmp/QuickChick/009002/QuickChick2faded.ml", line 824, characters 18-36:
Error: Unbound module Pain
The command has indeed failed with message:
Could not compile test program

QuickChecking (arbitrary : G litter)
[plastic; metal; plastic; plastic; metal; metal; metal; metal; metal; metal]

QuickChecking (arbitrary : G lint)
[dust; fabric; dust; fabric; dust; fabric; dust; dust; dust; dust; dust]
```

#### Notes

Users of CoqIDE will see
some of the messages in the message window and
others in the standard output stream,
which is why I interleaved them here by their time of arrival.

I reported this bug to the Coq project
with a reference in the QuickChick project,
because I do not know whether this bug is caused by one or the other.

**Comment by JasonGross** [comment]
This is very likely a QuickChick bug.  Coq itself does not do OCaml compilation from vernacular commands.  If QuickChick uses extraction, it's possible there's some issue with Coq's extraction (though it seems more likely that there's an issue with how QuickChick uses extraction), and if that's the case, feel free to reopen this bug or open a new bug with an example of the failure that does not involve QuickChick.
