### ISSUE TITLE
Syntax error caused by an empty file

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#9371]
#### Version

Coq 8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

Let us put the following tactic into `Tactic.v` and nothing into `Nothing.v`.

```
Ltac idmatch :=
  match goal with
  | |- _ => idtac
  end.
```

Now, calling `coqc Nothing.v && coqc Tactic.v` works just as one would expect.
However, calling `coqc Nothing.v Tactic.v` fails in a strange way.

```
File "./Tactic.v", line 3, characters 4-5:
Error:
Syntax error: [match_context_rule] expected after '|' (in [match_context_list]).
```

#### Notes

The message obtained by calling `coqc -help` suggests
that more than one file may be specified,
which is why I expected this to work.

```
Usage: coqc <options> <Coq options> file...
```

**Comment by ejgallego** [comment]
Calling `coqc` with two files is not really supported; the state will be messed up as you can see.

There have been some improvements on master and hopefully this should work in the future, for now just do one `coqc` call per `.v` file.

**Comment by Alizter** [comment]
coqc no longer accepts multiple files, therefore this issue doesn't seem relevant anymore.
