### ISSUE TITLE
Canonical structure inference breaks with applied primitive projections

### ISSUE THREAD

**Issue by arthuraa** [coq/coq#9375]
#### Version

8.8.2

#### Operating system

Linux

#### Description of the problem

In the following snippet, Coq fails to identify the primitive projection in `tata_toto` as a head constant. The second declaration works fine.

```
Set Primitive Projections.

Record toto : Type := Toto {
  toto1 : Type;
  toto2 : toto1 -> Type
}.

Record tata := Tata {
  tata1 : Type
}.

Canonical Structure tata_toto (x : toto) X :=
  Tata (toto2 x X).

(* Warning: Projection value has no head constant: toto2 x X *)

Canonical Structure tata_tata (x : tata) := Tata (tata1 x).

(* No problem here. *)
```

**Comment by gares** [comment]
If you have a minute please check #9377 fixes the issue for you (I imagine you have a larger test case).

**Comment by arthuraa** [comment]
Works like a charm! Thanks!
