### ISSUE TITLE
`red` doesn't reduce lambdas

### ISSUE THREAD

**Issue by gmalecha** [coq/coq#9376]
#### Version

The Coq Proof Assistant, version 8.8.2 (November 2018)
compiled on Nov 7 2018 21:54:20 with OCaml 4.07.0

#### Operating system

Linux

#### Description of the problem

The following command fails:

```coq
Eval red in (fun x => x) 1.
Toplevel input, characters 0-27:
> Eval red in (fun x => x) 1.
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: No head constant to reduce.
```

The documentation states that red performs *beta* reduction which is what should happen here.

I tried master and 8.8.2 and both seem to have the same problem. Is there any other way to force *only* this reduction?

**Comment by gmalecha** [comment]
Oops, I misread the documentation.

**Comment by jeromesimeon** [comment]
This might do the trick?
```
Eval cbv beta in (fun x => x) 1.
```
