### ISSUE TITLE
Creation of Windows workers should be documented or automated

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#9401]
This issue is a reminder that we should either document the creation of workers on the Inria CloudStack infrastructure, or migrate to a platform like Azure where such creation is transparent for us.

**Comment by ejgallego** [comment]
This is a RC-critical bug so setting some tags so we are reminded.

**Comment by Zimmi48** [comment]
What is even more critical for the next major release is that we don't have a functioning macOS packaging job on master anymore. Given that @vbgl is the next RM, and also an engineer of the Coq consortium, and given how promising Azure looks, I seriously hope that we will be able to fix once and for all these issues for 8.10.
