### ISSUE TITLE
Manual examples broken with nested proofs

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#9407]
Code snippets like here:

https://coq.inria.fr/distrib/current/refman/language/gallina-extensions.html?highlight=generalizable#implicit-generalization

trigger an error about nested proofs. It's a pity that errors on these examples (which are meant to be successfully executed) is not caught by our documentation build.

**Comment by Zimmi48** [comment]
That's quite sad indeed.
This issue is mostly a duplicate of #7433. Incidentally, I had marked this issue as a blocker for 8.9.0 but it was not enough to trigger any action.
Note that your more general remark is related to #7755.
