### ISSUE TITLE
Only template polymorphic empty inductives are optimized away during extraction

### ISSUE THREAD

**Issue by tchajed** [coq/coq#9416]
#### Version

The Coq Proof Assistant, version 8.10+alpha (December 2018)
compiled on Dec 31 2018 5:54:58 with OCaml 4.07.0

#### Operating system

macOS

#### Description of the problem

Normally empty inductives are optimized away by extraction, but it seems that this feature relies on template polymorphism:

```coq
From Coq Require Extraction.
Extraction Language OCaml.

Unset Auto Template Polymorphism.

#[universes(monomorphic)]
Inductive ind1 :=.

#[universes(template)]
Inductive ind2 :=.

#[universes(polymorphic)]
Inductive ind3 :=.

Inductive container : Type :=
| Monomorphic (x:ind1)
| Template (x:ind2)
| Polymorphic (x:ind3)
.


Extraction container.
(* type container =
| Monomorphic of ind1
| Template
| Polymorphic of ind3
*)
(* note Template takes no argument - the empty inductive has been optimized
away, as desired *)
```

**Comment by SkySkimmer** [comment]
This is not strictly about being template, the issue is that without template non-annotated inductives get declared > Prop.
~~~coq
#[universes(notemplate)]
Inductive ind1 :=.
Fail Check ind1 : Prop.
(* error ind1 has type Type *)

#[universes(notemplate)]
Inductive ind2 : Prop :=.

Inductive container : Type :=
| Monomorphic (x:ind1)
| OK (x:ind2).
Extraction container.
(* type container =
| Monomorphic of ind1
| OK
*)
~~~

**Comment by ppedrot** [comment]
So, that's not a bug, is it?

**Comment by SkySkimmer** [comment]
I think we probably want to minimise the universe of a non-annotated inductive before the kernel sees it. Maybe wait for #9444 so we can minimise to Prop sanely.

**Comment by tchajed** [comment]
I actually wanted my empty inductive to be in Type (so that things don't change as much when I do add constructors), but if I recall there's some separate issue that you can't force an empty inductive to be in Type. This seems like a pretty niche and low-priority issue, now that I understand what's going on.

I would like an example like this to be in the test suite so the Coq devs observe one of the changes from disabling template polymorphism.

**Comment by ppedrot** [comment]
#14802 seems to go the other way around, i.e. it would force empty types in Type to be kept by extraction rather than erased. I don't know if this is enough to consider this bug as fixed, and I am not sure what to think.

**Comment by SkySkimmer** [comment]
Not a bug, just automatic Prop lowering being confusing
