### ISSUE TITLE
Automatic packaging for OSX

### ISSUE THREAD

**Issue by vbgl** [coq/coq#9427]
Packages for OSX should be automatically built, as soon as a new version is tagged.

The 8.9 branch has an ad-hoc mechanism using manually-triggered builds on Gitlab-CI executed by a private trusted runner.

**Comment by Zimmi48** [comment]
FWIW I just read that IOHK uses [`nix-darwin`](https://github.com/LnL7/nix-darwin) to [set up](https://github.com/input-output-hk/iohk-ops/tree/master/nix-darwin) their machines to prepare their macOS packages
