### ISSUE TITLE
"Locate" lacking newlines between notations [regression]

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#9428]
#### Version

8.9.0

#### Operating system
Linux

#### Description of the problem

The following file
```
Notation "b1 && b2" := (if b1 then b2 else false).
Locate "&&".
```
prints
```
Notation
"b1 && b2" := if b1 then b2 else false (default interpretation)"x && y" := andb x y : bool_scope
```
As you can see, a newline is missing between the two printed notations.

This is a recent regression, I think it still worked fine with the 8.8 series.

**Comment by herbelin** [comment]
This is already fixed in 4b02fbd92 which should backported to v8.9. Made #9491 for that.
