### ISSUE TITLE
[feature request] Ability to disable warnings locally

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#9430]
It would be great if there was a way to locally disable a warning -- similar to what `#[allow(foo)]` does in Rust, which disables the warning for the next item/statement only.

We currently have the "notation-overridden" warning disabled globally in Iris.  I'd like to enable it again, but we have some cases where overriding notation is just the most convenient thing to do:
```coq
Class Embed (A B : Type) := embed : A → B.
Arguments embed {_ _ _} _%I : simpl never.
Notation "⎡ P ⎤" := (embed P) : bi_scope.
Instance: Params (@embed) 3 := {}.
Typeclasses Opaque embed.

(* ... *)

Class BiEmbed (PROP1 PROP2 : bi) := {
  bi_embed_embed :> Embed PROP1 PROP2;
  bi_embed_mixin : BiEmbedMixin PROP1 PROP2 bi_embed_embed;
}.

(* ... *)

Section embed_laws.
  Context `{BiEmbed PROP1 PROP2}.
  (* Override notation to help type inference *)
  Local Notation embed := (embed (A:=PROP1) (B:=PROP2)).
  Local Notation "⎡ P ⎤" := (embed P) : bi_scope.
  Implicit Types P : PROP1.
```
This is actually a situation where overriding notation is (a) a local effect and (b) has predictable behavior, so I see no good reason to go through the pain of defining and opening a separate scope here.

I hear Coq has a notion of attributes now, seems like they would be a perfect fit for this.

**Comment by Zimmi48** [comment]
See also #8027.

**Comment by RalfJung** [comment]
On Gitter I learned about `Local Set Warnings "-notation-overridden"`, which works for this case.  I could understand if you want to close this issue because in a way the feature is already available.

**Comment by Zimmi48** [comment]
No, I wouldn't close it. I'm :100: % in favor of this feature request. In fact, I was surprised that it was not a duplicate given how important I thought it was.

**Comment by Alizter** [comment]
What is the intended scope of these attributes? Should they cover all vernac commands?

**Comment by Zimmi48** [comment]
Yes, that's what I had in mind.
