### ISSUE TITLE
Asynchronous proofs crash proof workers in CoqIDE

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#9431]
#### Version

Coq 8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following actions crash proof workers.

* Open CoqIDE.
* Insert the following code into the buffer.
* Navigate to the end.
* Navigate to any point between `Proof` and `Qed` of the first goal.
* Navigate to any point between `Goal` and `Proof` of the first goal.
* Navigate to the end.

```
Goal False.
Proof. try constructor. Qed.

Goal True.
Proof. try constructor. Qed.
```

```
Coqtop died badly.
```

There are two ways to recover.
The more convenient one is to be more careful.

* After navigating to any point between `Goal` and `Proof` of the first goal...
* Before navigating to the end...
* Navigate to any point before `Goal` of the first goal.
* Navigate to the end.

The less convenient one is to disable asynchronous proofs altogether.

* Open the *Tools* menu.
* Open the *Coqtop arguments* dialog.
* Enter `-async-proofs off` into the text field.
* Push the `OK` button.
* Navigate to the end.

**Comment by ejgallego** [comment]
Hi @Tuplanolla , your reports are very appreciated, however may I suggest you try the `master` branch of Coq for IDE-related issues? Even 8.9 would be better.

There has been many many fixes to that area since 8.8, thus you may find that some issues do manifest differently.

**Comment by Tuplanolla** [comment]
Sure thing, @ejgallego.
This is all I have for now, anyway.

**Comment by staffehn** [comment]
This still applies to master. Minimal examlple:
```coq
Goal True.
Proof.
Qed.
```
Instructions (CoqIDE buttons):
1. Go to end.
2. Backward one command.
3. Backward one command.
4. Go to end.

**Comment by ejgallego** [comment]
That shouldn't be too hard to fix would the STM developers allocate some time to it:
```
12863:proofworker:1:0] reaching: 6
12863:proofworker:1:0] reached (cache)
12863:proofworker:1:0] failed with the following exception: 
                        (in proof Unnamed_thm): Attempt to save an incomplete proof
                       frame @ file "stm/stm.ml", line 1604, characters 20-35
                       raise @ file "clib/exninfo.ml", line 65, characters 2-15
                       frame @ file "lib/future.ml", line 132, characters 19-23
                       frame @ file "stm/stm.ml", line 1593, characters 14-65
                       frame @ file "proofs/proof_global.ml", line 355, characters 12-35
                       raise @ file "proofs/proof.ml", line 382, characters 4-43
```

**Comment by ejgallego** [comment]
But indeed the bug underlines a deficiency of the current proof-communication model.
