### ISSUE TITLE
Problems with opam  install coqide in ubuntu 18.04

### ISSUE THREAD

**Issue by dnantes** [coq/coq#9459]
#### Version

 $ opam --version
2.0.3

The Coq Proof Assistant, version 8.9.0 (February 2019)
compiled on Feb 1 2019 13:43:13 with OCaml 4.07.1

#### Operating system
ubuntu 18.04 lts

#### Description of the problem
I am trying to install Coqide on my computer but I keep receiving this failure message 

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build conf-gtksourceview 2
└─ 
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please
make sure they are installed before retrying:
    libgtksourceview2.0-dev

----------------------------
but I already have the libgtksouceview2.0-dev installed. 

$ sudo apt install libgtksourceview2.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgtksourceview2.0-dev is already the newest version (2.10.5-3).
The following packages were automatically installed and are no longer required:
  aspcud clasp darcs gringo libcoq-ocaml linux-headers-4.15.0-42
  linux-headers-4.15.0-42-generic linux-image-4.15.0-42-generic
  linux-modules-4.15.0-42-generic linux-modules-extra-4.15.0-42-generic
  mmm-mode ocaml ocaml-base opam-docs x11proto-dri2-dev x11proto-gl-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--
What should I do?

**Comment by Zimmi48** [comment]
It is possible that opam is not seeing that this external dependency is already installed. Do you have `pkg-config` installed?

**Comment by ejgallego** [comment]
Closing as inactive.
