### ISSUE TITLE
Notation, missing blank with format clause

### ISSUE THREAD

**Issue by gert-smolka** [coq/coq#9463]
#### Description of the problem

Notation "'Sigma' x .. y , p" :=
    (sigT (fun x => .. (sigT (fun y => p)) ..))
      (at level 200, x binder, y binder, right associativity,
      format "'[' 'Sigma' '/ ' x .. y , '/ ' p ']'").

Check forall x y, Sigma a b, x = a * S y + b /\ b <= y.
 
Bug: Sigma a b is printed as Sigmaa b (blank missing)
Works fine if format clause is omitted.

**Comment by JasonGross** [comment]
This is not a bug.  If you have `n` spaces in `format`, you get `n-1` spaces in the display.  Since you only have one space between various things, you get 0 spaces in the display.  It renders fine with
```coq
Notation "'Sigma' x .. y , p" :=
  (sigT (fun x => .. (sigT (fun y => p)) ..))
    (at level 200, x binder, y binder, right associativity,
     format "'[' 'Sigma'  '/ ' x .. y , '/ ' p ']'").
```

You may also want an extra space after the comma.

**Comment by gert-smolka** [comment]
Thanks.
