### ISSUE TITLE
8.9.0 thinks ocamlopt exists on platforms where it does not

### ISSUE THREAD

**Issue by bbarenblat** [coq/coq#9464]
If I build 8.9.0 on MIPS, for which no OCaml native compiler backend exists, `configure` seems to think that it can do native compilation.

```
  Native Compiler enabled     : true
```

Running `make`, unsurprisingly, fails.

    "/usr/bin/ocamlfind" opt -thread -rectypes -w +a-4-9-27-41-42-44-45-48-50-58-59   -safe-string -strict-sequence   -I coqpp -I config -I clib -I lib -I kernel -I kernel/byterun -I library -I engine -I pretyping -I interp -I proofs -I parsing -I printing -I tactics -I vernac -I stm -I toplevel -I tools -I tools/coqdoc -I plugins/omega -I plugins/romega -I plugins/micromega -I plugins/quote -I plugins/setoid_ring -I plugins/extraction -I plugins/cc -I plugins/funind -I plugins/firstorder -I plugins/derive -I plugins/rtauto -I plugins/nsatz -I plugins/syntax -I plugins/btauto -I plugins/ssrmatching -I plugins/ltac -I plugins/ssr -I "+camlp5" -g     -c clib/cObj.ml
    ocamlfind: Not supported in your configuration: ocamlopt

A [full typescript](https://benjamin.barenblat.name/coq_8.9.0_mips_failure.log) is available.

**Comment by SkySkimmer** [comment]
As far as I can tell it's a mistake in the makefile dependencies:
Before 382ee49700c4b4ee78ba95b2e86866ebd3b35d74 we have the dependency chain (where `world` is the default target):
`world`: `coq`: `coqbinaries`: `$(COQTOPEXE)` = `bin/coqtop` (which in byte mode is copied from bin/coqtop.byte)

After  `$(COQTOPEXE)` is replaced with `$(TOPBIN)` (later renamed `$(TOPBINOPT)`) which contains `bin/coqtop.opt`.

Could you try with f3542483eb783fb6ddd72576eb77ad47b81b27fb?

>  Native Compiler enabled     : true

That's actually about the `native_compile` evaluation system, which isn't what's causing the failure.

**Comment by SkySkimmer** [comment]
We should add a CI test with no ocamlopt (if possible really no ocamlopt, not just configure -byte-only)

**Comment by bbarenblat** [comment]
Unfortunately, cherry-picking f3542483eb783fb6ddd72576eb77ad47b81b27fb on top of the 8.9.0 release gives the same error.

**Comment by JasonGross** [comment]
Btw, @bbarenblat, the thing to check to see if `./configure` thinks you have ocamlopt, is the `BEST=` line in `./config/Makefile` after `./configure`.  @SkySkimmer maybe we should emit that in the output of `./configure` as well?

**Comment by JasonGross** [comment]
Why do we have, in `Makefile.build`,
```
define bestocaml
$(if $(OPT),\
$(OCAMLOPT) $(MLINCLUDES) $(OPTFLAGS) $(LINKMETADATA) -o $@ -linkpkg $(1) $^ && $(STRIP) $@ && $(CODESIGN) $@,\
$(OCAMLC) $(MLINCLUDES) $(BYTEFLAGS) $(CUSTOM) -o $@ -linkpkg $(1) $^)
endef
```
?  
Shouldn't that be checking if `OPT` is `opt` vs `byte`, rather than if it is empty vs non-empty?

**Comment by ejgallego** [comment]
> We should add a CI test with no ocamlopt (if possible really no ocamlopt, not just configure -byte-only)

I'm not sure that's so easy to do well, can OCaml be configured in such a way?

I was aware we don't really test all the corner cases, however I am not too worried as in theory Dune should be able to take care of this in an easier way.

**Comment by ejgallego** [comment]
Another non-optimal setup is for platforms where dynamic linking is not available.

**Comment by andres-erbsen** [comment]
ocaml has option --no-native-compiler but I didn't manage to build camlp5 with it https://builds.sr.ht/~andres/job/26008

**Comment by SkySkimmer** [comment]
Try just coq master, it doesn't need camlp5.

**Comment by andres-erbsen** [comment]
coq master on ocaml --no-native-compiler builds coq but coq does not run [script](https://builds.sr.ht/api/jobs/26055/manifest), [log](https://builds.sr.ht/~andres/job/26055). 

```typescript

COQC -noinit theories/Init/Notations.v
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory make[1]: Leaving directory 
```

**Comment by ejgallego** [comment]
How about the Dune build?

**Comment by andres-erbsen** [comment]
does not work either. [script](https://builds.sr.ht/api/jobs/26075/manifest), [log](https://builds.sr.ht/~andres/job/26075#task-build-1583).

```
File "theories/Init/dune", line 49, characters 0-832:
49 | (rule
50 |  (targets Prelude.vo Prelude.glob .Prelude.aux)
51 |  (deps (:pp-file ../../theories/Init/Prelude.v)
....
60 |        ../../plugins/syntax/numeral_notation_plugin.cmxs
61 |        ../../plugins/syntax/string_notation_plugin.cmxs)
62 |  (action (chdir %{project_root} (run coqc -boot -coqlib %{project_root} -noinit -R theories Coq  theories/Init/Prelude.v))))
Error: No rule found for plugins/cc/cc_plugin.cmxs
```
and so on

**Comment by JasonGross** [comment]
@SkySkimmer There is also an issue with `FAKEIDE` dependencies: we have `coqbinaries` depends on ` $(FAKEIDE)`, the `FAKEIDE` line is
```makefile
$(FAKEIDE): $(call bestobj, $(FAKEIDECMO)) | $(IDETOP)
```
and `IDETOP` is unconditionally defined as `IDETOP=bin/coqidetop.opt$(EXE)`.  If we change `IDETOP` to `IDETOPEXE`, that fixes things, and I think it has the correct semantics even on platforms with ocamlopt.

**Comment by bbarenblat** [comment]
With @JasonGross’s patches, Coq at least builds. The test suite fails, though:

  - test-suite/misc/poly-capture-global-univs.sh explicitly tries to make a .cmxs, which obviously won’t work on platforms without ocamlopt.

  - The unit tests fail because they explicitly call ocamlopt.

Both of these should be easy fixes, and I’ll see if I can patch them myself.

I don’t want to rush anyone, but in the interest of full disclosure: I ran across this issue while packaging Coq 8.9 for Debian, and there is a release freeze next week. I can’t patch out the breakage within in the next day, it’s therefore likely that Debian 10 will ship with Coq 8.8.2 instead of Coq 8.9.0.

**Comment by ejgallego** [comment]
Thanks @bbarenblat , I wonder if the right fix for Debian would be just to remove Coq from MIPS.

I am not sure I see a lot of value for Coq on a platform that doesn't have `ocamlopt`, for sure it will be very slow to use for non trivial proofs.

**Comment by bbarenblat** [comment]
In the long term, that may indeed be the correct fix. Unfortunately, Debian currently doesn’t have a way for packages to specify that they require ocamlopt – only to specify that they require OCaml. If Coq decides to officially desupport non-native architectures, I’ll work with the Debian OCaml maintainers to get Coq removed from MIPS, but that’s a sufficiently disruptive change that it probably can’t occur this late in the release cycle.

**Comment by ejgallego** [comment]
I see, I thought it would have been easier to remove an architecture by just modifying the control file, but if that requires FTP master intervention indeed it may be trickier.

**Comment by SkySkimmer** [comment]
>test-suite/misc/poly-capture-global-univs.sh explicitly tries to make a .cmxs, which obviously won’t work on platforms without ocamlopt.

The reason it wants to make the cmxs separately from the next make call is to differentiate failures because we need to update the ml sources vs the real failure of the test. That means it should be enough to build the cma regardless of presence of ocamlopt.

For the unit tests if they're too annoying just skip them (by removing unit-tests from SUBSYSTEMS in test-suite/Makefile), they don't test much yet.

**Comment by SkySkimmer** [comment]
See https://github.com/coq/coq/pull/9477 (although that's on master)

**Comment by bbarenblat** [comment]
@SkySkimmer, thank you! I’ll try that right now.

**Comment by bbarenblat** [comment]
With @SkySkimmer’s patches and disabling the .vio-related tests (I think because of https://github.com/coq/coq/issues/9141), I’ve successfully built 8.9.0 on MIPS. It now fails in `make install`, which tries to install a bunch of .cmx files.

**Comment by andres-erbsen** [comment]
is it the same error as at https://builds.sr.ht/~andres/job/26407#task-build-3193 at https://github.com/coq/coq/pull/9477 ?

**Comment by bbarenblat** [comment]
Could be. I’m running with `-j5`, so things are a bit more interleaved, and I only see errors trying to install the .cmx files. Here’s the [full build log](https://benjamin.barenblat.name/coq_8.9.0-1_mips_failure2.log).

**Comment by SkySkimmer** [comment]
I think https://github.com/coq/coq/pull/9477 fixed this
