### ISSUE TITLE
-async-proofs-tac-j option doesn't work for coqc

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#9484]
#### Description of the problem

It seems that the `-async-proofs-tac-j` command line option is now parsed by `coqc`, and files which do not contain `par: someTactic.` commands compile correctly, but if a file contains `par: someTactic.`, an error occurs when the proof worker subprocess is started:

```
$ cat Async.v
```

```
Lemma test: forall a: nat, a = 1 \/ a = 2 -> a <> 0.
Proof.
  intros.
  destruct H.
  par: congruence.
Qed.
```

```
$ coqc -async-proofs-tac-j 1 Async.v 
```

```
Error: integer expected after option -async-proofs-tac-j
Handshake with tacticworker:0 failed: End_of_file
```

Trying some other ways of passing the integer argument, none of which works:

```
$ coqc -async-proofs-tac-j1 Async.v 
```

```
Warning: File "./-async-proofs-tac-j1" has been implicitly expanded to
"./-async-proofs-tac-j1.v" [file-no-extension,filesystem]
Error: Can't find file ./-async-proofs-tac-j1.v
```

```
$ coqc -async-proofs-tac-j=1 Async.v 
```

```
Warning: File "./-async-proofs-tac-j=1" has been implicitly expanded to
"./-async-proofs-tac-j=1.v" [file-no-extension,filesystem]
Error: Can't find file ./-async-proofs-tac-j=1.v
```

```
$ coqc -test-some-inexistent-option Async.v 
```

```
Warning: File "./-test-some-inexistent-option" has been implicitly expanded
to "./-test-some-inexistent-option.v" [file-no-extension,filesystem]
Error: Can't find file ./-test-some-inexistent-option.v
```

#### Coq Version

Coq master d9afe70c9c65359b6eb827f5b30d84f24074efa1 of Tue Feb 5 16:51:53 2019

**Comment by ejgallego** [comment]
This is indeed a bug on the recent refactoring, should be easy to fix, thanks for the feedback.

**Comment by ejgallego** [comment]
Ok PR submitted.

**Comment by ejgallego** [comment]
Hopefully this works now, thanks @samuelgruetter for you patience.

**Comment by samuelgruetter** [comment]
Thanks, now (semi-)blocked on https://github.com/coq/coq/issues/9533
