### ISSUE TITLE
Error: Anomaly "Uncaught exception Failure("unknown level 202")."

### ISSUE THREAD

**Issue by Janno** [coq/coq#9490]
#### Description of the problem
The following code raises an uncaught exception. In my understanding, it should work just fine.
```coq
Declare Custom Entry with_pattern.
Declare Custom Entry M_branch.
Notation "'with' | p1 | .. | pn 'end'" :=
  (cons p1 (.. (cons pn nil) ..))
  (in custom with_pattern at level 91, p1 custom M_branch at level 202, pn custom M_branch at level 202).
Notation "'bla'" := I (in custom M_branch at level 202).
Notation "'[use_with'  l  ]" := (l) (at level 0, l custom with_pattern at level 91).
Check [use_with with | bla end].
Check [use_with with | bla | bla end].
(* 
Error: Anomaly "Uncaught exception Failure("unknown level 202")."
Please report at http://coq.inria.fr/bugs/.
frame @ file "toplevel/coqloop.ml", line 380, characters 10-36
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "toplevel/coqloop.ml", line 265, characters 6-89
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacstate.ml", line 22, characters 10-35
raise @ file "clib/exninfo.ml", line 65, characters 2-15
*)
```

*Note* that in line 8 (second-to-last line), the same notation with just one instance of the recursive part works.

#### Coq Version
8.9 & master as of today.

cc @herbelin (who probably knows best what's going on here)

**Comment by maximedenes** [comment]
@herbelin are you ok with being the assignee?

**Comment by staffehn** [comment]
This is the same bug as described in #9532 (in that issue the *actual* bug becomes more apparent).

**Comment by Janno** [comment]
@maximedenes I put the consortium label on this. Mtac2 could benefit from custom expressions for all our fancy notation but this bug blocks any attempts to make use of them.

**Comment by maximedenes** [comment]
Having a look. Could be related to #9521.

**Comment by maximedenes** [comment]
The backtrace isn't useful due to #11310. We should probably fix that first to get an idea of what's going on here.

**Comment by Janno** [comment]
@maximedenes Just in case you missed @staffehn's comment: #9532 is probably a much better indicator of what happens. And that seems to be a confusion of parsing entries. My example code can be made to fail more gracefully by creating a notation in constr at level 202 (e.g. `Notation "'flub'" := I (at level 202).`) Then it becomes obvious that Coq is trying to parse constrs instead of my custom entries.

**Comment by maximedenes** [comment]
Thanks, that helps!

**Comment by maximedenes** [comment]
Ok, I have a fix for all these issues, it was fairly easy. Will push in the afternoon.

**Comment by maximedenes** [comment]
> Will push in the afternoon.

Done (https://github.com/coq/coq/pull/11311).
