### ISSUE TITLE
destruct with eqn: can fail with Cannot create self-referring hypothesis

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#9494]
#### Description of the problem

The following code

```
Set Mangle Names.

Lemma foo(a: nat): True.
Proof.
  let N := fresh in destruct a eqn: N.
```

fails with `Error: Cannot create self-referring hypothesis _0`.

This code never refers to autogenerated names, and it works if `Set Mangle Names.` is removed, so I believe it should also work with `Set Mangle Names.` (that's an invariant I'd expect to hold for this feature).

#### Coq Version

8.9

**Comment by jashug** [comment]
The same error without `Set Mangle Names`:
```
Lemma foo (a : nat) : True.
Proof.
destruct a eqn: n.
(* Cannot create self-referring hypothesis n *)
```

**Comment by samuelgruetter** [comment]
Interesting, so I'd say it's a bug in `destruct`: To destruct the term, it should not pick names which equal the name passed via `eqn:`.

**Comment by jashug** [comment]
As far as I can tell, the error is triggered through calling `change_in_hyp` in `atomize_param_of_ind_then` which calls `Tactics.convert_hyp` which calls `Logic.convert_hyp` which calls `check_decl_position`
https://github.com/coq/coq/blob/7886c6d8e0663ba346fff52837012c7fc952ecc1/tactics/tactics.ml#L3268

But the root of the problem may be in `Tactics.induction_gen`, which comes up a new name to give the induction argument (in this case producing `let n := a`) without avoiding anything:

https://github.com/coq/coq/blob/7886c6d8e0663ba346fff52837012c7fc952ecc1/tactics/tactics.ml#L4523-L4526

I'll try avoiding the `eqn`, but I'm don't understand how destruct works well enough to tell if that's just a patch hiding further problems.

-----

```coq
Lemma foo(a: nat): True.
Proof.
destruct a eqn:H.
Show Proof.
(*
(fun a : nat =>
 let n := a in
 let H : a = n := eq_refl in
 match n as n0 return (a = n0 -> True) with
 | 0 => fun H0 : a = 0 => ?Goal@{H:=H0}
 | S n0 =>
     fun H0 : a = S n0 =>
     ?Goal0@{n:=n0; H:=H0}
 end H)
*)
```

Choosing `eqn:n` instead produces the error, presumably from `destruct` trying to produce
`let n := a in let n : a = n := eq_refl` and getting confused.

**Comment by JasonGross** [comment]
> I'll try avoiding the `eqn`, but I'm don't understand how destruct works well enough to tell if that's just a patch hiding further problems.

Not knowing anything about how the inner workings of destruct are implemented, this sounds like the correct patch.
