### ISSUE TITLE
Don’t run timing tests by default outside CI

### ISSUE THREAD

**Issue by bbarenblat** [coq/coq#9497]
Tests that use `Timeout` are inherently fragile because the timeouts are specified in seconds and different hardware runs at different speeds. Debian currently [patches out several tests](https://salsa.debian.org/ocaml-team/coq/blob/7cbefd56ba087ae51bc618db5bc72a51d10dedbf/debian/patches/remove-time-sensitive-tests.patch) because the timeouts are invalid on platforms where Coq is running as bytecode. The problem is not specific to architecture, though; if I pulled out my old Pentium 4 laptop, I’m guessing the timeouts might not be valid there either.

To fix this, I think the Coq build system should run timing-based tests by default only when it detects it’s running on CI. The timing-based tests should still be available under a target so that interested developers can run them and sanity-check their work, but the CI system should become the official baseline for what those timeouts represent.

**Comment by ejgallego** [comment]
Actually the makefile should already have support for this using the `COMPLEXITY` variable.

**Comment by SkySkimmer** [comment]
>Actually the makefile should already have support for this using the COMPLEXITY variable.

If you look at their patches they're about tests in bugs/closed using timeout. Specifically well-known offenders #3441 (https://github.com/coq/coq/issues/7388) and #4811 (https://github.com/coq/coq/issues/7483). Maybe we should just drop them from the test suite, they're not very high value.

**Comment by Zimmi48** [comment]
I'm all for dropping these tests using `Timeout` from the test-suite entirely. This is not the same as the complexity tests which should be kept. See also #7483.
