### ISSUE TITLE
Warning "Not considering unicode character "ₛ" of unknown lexical status as part of identifier [..]"

### ISSUE THREAD

**Issue by Janno** [coq/coq#9500]
#### Description of the problem

The following code raises a warning in line 2:
```coq
Notation "'Testₛ'" := I (at level 0).
Check Testₛ.
(*Warning: Not considering unicode character "ₛ" of unknown lexical
status as part of identifier "Test". [unrecognized-unicode,parsing] *)
```

In a misguided attempt to fix this issue myself (#9480), I learned from @vbgl that `ₛ` and similar sub/superscript characters are *not unclassified* but instead classified as a modifier.

Independent of that, I don't understand the warning itself. It is telling me that the keyword is internally made of two identifiers, `Test` and `ₛ`? Do I need to know that? Also, why is `ₛ` reported as unclassified if it's actually classified as a modifier? 

Even if this can't be fixed, I would like to know the actual implications of this warning. Will notation like this break in the future?

#### Coq Version
8.9 & master as of a day ago or so

**Comment by vbgl** [comment]
A data point: “Testₛ” is a valid identifier in Java.

**Comment by Janno** [comment]
I don't see this warning anymore on recent master and 8.11. It seems like subscript characters are now allowed to be part of identifiers. `Definition Testₛ := 1.` is valid Coq. Thus, I am closing this issue.
