### ISSUE TITLE
`Top_printers.print_pure_econstr` is not exported

### ISSUE THREAD

**Issue by thierry-martinez** [coq/coq#9503]
#### Description of the problem

`Top_printers.print_pure_econstr` is not exported (while `Top_printers.print_pure_constr` is).
This can be inconvient for debugging.

#### Coq Version

coq trunk (bd25768d7c), version 8.10+alpha (February 2019)

**Comment by SkySkimmer** [comment]
Will you make a PR?

**Comment by thierry-martinez** [comment]
@SkySkimmer: done!
