### ISSUE TITLE
what identifiers are parsed as `ident` in custom entries?

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9514]
I am thoroughly confused by this behavior.

```coq
Declare Custom Entry expr.
Notation "[ e ]" := e (e custom expr at level 2).
Notation "x" := x (in custom expr at level 0, x ident).
Print Grammar expr.
(* no output? *)
Check fun a => [a].
(* fun a : ?T => a *)
(*      : ?T -> ?T *)
(* where *)
(* ?T : [ |- Type] *)
Check nat.
(* nat *)
(*      : Set *)
Check [nat].
(* Error: The variable nat was not found in the current environment. *)
Check [Coq.Init.Datatypes.nat].
(* Error: Syntax error: ']' expected after [constr:expr level 2] (in [constr:operconstr]). *)
```

coq 8.9.0

@herbelin ?

**Comment by JasonGross** [comment]
What is confusing about this?  I interpret this as implying that `ident` is like "local variable".  `Check [nat]. ` fails for the same reason that `Check x`; `Check [Coq.Init.Datatypes.nat].` fails with the same error message as `Check fun Coq.Init.Datatypes.nat => _.`

**Comment by andres-erbsen** [comment]
what does "local variable" mean in your explanation? I can `Check nat` just fine outside the `[  ]`.

**Comment by JasonGross** [comment]
Update after taking with Andres: my current understanding is that "ident" parsing is "anything that could be a binder" and "global" is parsed as "anything that could refer to a definition".  The interpretation of "ident" is "Var node" (cf Ltac2's Constr.Unsafe.kind), while the interpretation of "global" is "Constant node" (also cf Ltac2).

"Local variable" means "stuff above the line / in the context if you go into tactics in terms"

**Comment by herbelin** [comment]
This part is not well documented and actually not very clean.

`ident` is for bound variables, and actually also for `_`. It includes section/goal variables and bound variables but no global references.

`global` is for references. It includes not only constants, but also names of constructor, inductive type, and... variables (but not `_`).

If these entries are not used too much in the wild, it might be worth to do some cleaning before they are documented.

**Comment by herbelin** [comment]
I made #11841 to try to clarify the `ident` terminology (compared to the `name` terminology and compared to what happens in `Tactic Notation`).
