### ISSUE TITLE
-async-proofs-tac-j 0 doesn't work for coqc

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#9533]
#### Description of the problem

If I pass 0 to the `-async-proofs-tac-j` command line option, compilation fails:

```
$ cat Async.v
```

```
Lemma test: forall a: nat, a = 1 \/ a = 2 -> a <> 0.
Proof.
  intros.
  destruct H.
  par: congruence.
Qed.
```

```
$ coqc -async-proofs-tac-j 0 Async.v 
```

```
File "./Async.v", line 6, characters 0-4:
Error:  (in proof test): Attempt to save an incomplete proof
```

#### Expected behavior

The tactic behind the `par:` should be executed on the main `coqc` process, no proof worker process should be spawned, and the file should compile successfully.

#### Discussion

There several behaviors how `par:` could be compiled:

0. Spawn 0 proof workers, do everything on the main `coqc` process
1. Spawn 1 proof worker, main `coqc` process waits until proof worker has done all the work (not really useful, could also do it directly on the main `coqc` process)
2. Spawn 2 proof workers
3. Spawn 3 proof workers
4. etc

It would also be imaginable that to get behavior 0), I'd have to write `-async-proofs-tac-j 1`, because the number would stand for the total number of processes including the main `coqc` process.

In any case, it seems behavior 0) is not available at the moment, but would be useful to have.

#### Coq Version

Coq master 3b9d338c751acd6694038b30e0c40637449df86a of Fri Feb 8 17:36:14 2019 +0100

**Comment by ejgallego** [comment]
Umm, cc: @gares

**Comment by gares** [comment]
I think the easy fix is to impose the value to be `>= 1`.
Falling back to `all:` is also possible, but more work.

**Comment by samuelgruetter** [comment]
This is an easy fix indeed :wink: 
But I still think the proper fix would be a valuable feature, so I opened a new issue: https://github.com/coq/coq/issues/9550
