### ISSUE TITLE
dune and coqtop.byte

### ISSUE THREAD

**Issue by mattam82** [coq/coq#9537]
#### Description of the problem

I was trying to use coqtop.byte built with dune to debug something in equations and failed.
First issue is that just running coqtop.byte failed, one has to 
```
export LD_LIBRARY_PATH=PATH_TO_COQ/_build/install/default//lib/stublibs:$LD_LIBRARY_PATH
```
For this to run, otherwise the dynamic library linker fails to find a DLL.

After this, processing works, and I can drop to the toplevel, however `#use "include";;` fails, and after adding the PATH_TO_COQ/dev directory to the source files it succeeds but cannot find the object files it needs. Adding #directory "PATH_TO_COQ/_build/default/dev" it still fails with:
```
File "/Users/sozeau/dev/coq/coq/_build/default/dev/top_printers.ml", line 13, characters 5-10:
Error: Unbound module Sorts
Hint: Did you mean Sort?
File "/Users/sozeau/dev/coq/coq/_build/default/dev/vm_printers.ml", line 2, characters 5-9:
Error: Unbound module Term
Unbound value ppid.
...
```

**Comment by ejgallego** [comment]
Thanks for the report @mattam82 , first issue is usually solved with `dune exec coqtop.byte`, regarding the paths I will have a look.

The plan indeed is to add a `dune coqtop` command that would set the paths in the proper way, and would allow to load any arbitary plugin / package.

**Comment by ejgallego** [comment]
Ok @mattam82, some points that I hope are helpful.

## Getting a composed build:

Do:
```
$ git clone equations ....
$ dune utop equations
```
will get you a developer shell. Adding `equations.plugin` to the `topbin/dune` file will link equations statically on the binary. Of course you can create your own.

## Dropping:
You want to start with `dune exec`, then add the right directories:
```
$ dune exec coqtop.byte
$ Drop.
# #directory "/home/egallego/external/coq-master/dev";;
#directory "/home/egallego/external/coq-master/_build/default/kernel/.kernel.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/lib/.lib.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/clib/.clib.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/engine/.engine.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/library/.library.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/pretyping/.pretyping.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/parsing/.parsing.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/interp/.interp.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/proofs/.proofs.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/printing/.printing.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/tactics/.tactics.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/vernac/.vernac.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/toplevel/.toplevel.objs/";;
#directory "/home/egallego/external/coq-master/_build/default/plugins/ltac/.ltac_plugin.objs/";;
#use "include";;
```
and this will work; note that ltac modules are of the from `Ltac_plugin__foo` so they may need rewriting in the file indeed.

I guess indeed we should make the `include` file generated like `db-dune.dbg` and for it to include the proper paths.

**Comment by ejgallego** [comment]
Dune shall include better support for toplevels in 1.7, so indeed we could maybe hack something like that. For example under `utop` printers will be loaded automatically c.f.: https://github.com/ocaml-community/utop/pull/269
