### ISSUE TITLE
`Existential` and `Grab Existential` commands are obsolete and redundant with `Unshelve`

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#9545]
As described in #9170, we seem to have quite a mess here with the "shelf`.

What the solution is seems not clear, thus I am closing the above PR and opening this issue. The "shelf" was introduced in 8.5 and introduced massive compatibility problems. Unfortunately, it seems that there is no specification of what the "shelf" neither how it should behave.

A few bugs are outlined in the #9170 , see also #4509 , #6292, and #8386 .

It seems to me that we should converge then to a unique command that has clear semantics, closing this issue.

**Comment by ppedrot** [comment]
Closed by #14819.
