### ISSUE TITLE
Qed takes almost 4 hours to close

### ISSUE THREAD

**Issue by HuStmpHrrr** [coq/coq#9546]
#### Description of the problem

Qed took 3.7 hours to close a lemma:

```
fmsubty_to_fdsubty is defined

<infomsg>Finished transaction in 13391.78 secs (13357.157u,6.398s) (successful)
</infomsg>
```

However, I don't think it should take so much time. In my inductive type, I have a function member, namely,

```
T ::= A x (B -> T)
```

In my proof, it is required to generate another `B -> T'`, by

```
f : B -> T
fun y : B => inversion of (f y)
```

which I speculate contribute to the excessive slowness. Since the proof is not directly structural induction, I chose to use `Fixpoint` and rely on termination checker to guarantee soundness.

Another speculation is that the lemma relies on equational reasoning and Equations which might introduce some slowness.

The related code is here: https://gitlab.com/JasonHuZS/AlgDotCalculus/blob/master/dsub/FsubMinus.v#L450

Sorry to have to post the whole project here, cuz I have no idea where things went so sub-optimal.
#### Coq Version
8.8.2

**Comment by ppedrot** [comment]
There are many reasons a Qed can go wrong this way. Typically it is due to some conversion problem that gets unfolded in a way that triggers an exponential or similar blowup.

**Comment by HuStmpHrrr** [comment]
is there anyway to benchmark which part is the problem?

**Comment by ppedrot** [comment]
No easy one that I know of, unluckily. You can always instrument the Coq code yourself, but it's highly unwieldy.

**Comment by gares** [comment]
I think you could try to add an axiom `xxx : False` and comment out bits and pieces of your proof and replace them by `case xxx`. In this way you may find the culprit. I have no better idea.

**Comment by HuStmpHrrr** [comment]
I handled this by proving a general inductive hypothesis, which only takes 8 secs to close. It does seem like unfolding definitions related to the particular proposition I was proving.
