### ISSUE TITLE
Coq shouldn't require `-linkall`

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#9547]
As of today, any executable linking to Coq has to specify `-linkall` as to properly initialize the parser and some other structures.

IMHO, we should fix our static initialization system so this is not the case.

cc for some discussion: https://github.com/ocaml/dune/issues/1819

**Comment by maximedenes** [comment]
@ejgallego can I assign this issue to you?

**Comment by ejgallego** [comment]
> @ejgallego can I assign this issue to you?

I can't commit to fix this in the short term as it needs some deep coqpp modification; note that I already track issues I've submitted myself anyways.

**Comment by Zimmi48** [comment]
@ejgallego Are these coqpp modifications described somewhere? Would it be appropriate to describe them here or should there be another issue opened about them. If there is such an issue or it is created, then we can label this one as "needs" something (how to put the label name is not yet clear to me though, it doesn't seem to be any of the ones that we already have, or it would have to be generalized).

**Comment by ejgallego** [comment]
So basically you need `coqpp` to stop generating static initializers and instead produce a `register ()` function that is called by the users of the grammar files.

Not difficult, but time consuming.

**Comment by ejgallego** [comment]
No label needed IMHO, what to do is pretty clear [have all the right initializers called in the dep chain]

**Comment by Zimmi48** [comment]
But is this something that you are considering implementing yourself or for which you would prefer to request the help of someone else in @coq/parsing-maintainers? And if so, do they understand the idea?

**Comment by ejgallego** [comment]
If I have time I'll implement myself but I cannot give a bound now, so anyone is free to take on it of course.

**Comment by ejgallego** [comment]
Note that #15220 and in general proper plugin linking in OCaml seems to require `-linkall`.

This is very unfortunate, but we don't have a short term fix for now :S
