### ISSUE TITLE
Bug in functor types

### ISSUE THREAD

**Issue by sacerdot** [coq/coq#9555]
Hi,
Coq is messing up the functor types in this situation:

```coq
Module Type M. Axiom n : nat. End M.
Module Type F(X: M) := M.
Print Module Type F.
```
Output:
```coq
Module Type F = Funsig (X:F) Sig Parameter n : nat. End
(*                       ^ here it should be M, not F *)
```

The bugs is not in the pretty-printer: I observed it running a sanity check on the XML files
I export with my plugin. The kernel data structures are already messed up.

Coq version: 8.9.0

**Comment by SkySkimmer** [comment]
By the time we return from `subst_modtype_and_resolver` in `translate_modtype` it's too late. I don't knw what the fix should be though.

**Comment by herbelin** [comment]
Finally, a PR fixing the bug can be found at #15385.
