### ISSUE TITLE
`auto using lem` cannot solve a goal when `apply lem` can.

### ISSUE THREAD

**Issue by luochen1990** [coq/coq#9562]
#### Description of the problem

When I'm working on an exercise of [sf/plf/Hoare.v](https://softwarefoundations.cis.upenn.edu/plf-current/Hoare.html#lab55),  I tried to replace `symmetry; apply t_update_same.` with `auto using t_update_same.` but failed, and find it wierd since it also failed when I replace `apply t_update_same.` with `auto using t_update_same.` . 

I think it will hold that for all lemma `lem`, if `apply lem` solves the goal, then `auto using lem` will also solve it, since `auto` will try `apply lem` at first round, but in the following example it doesn't hold.

```
Theorem hoare_asgn_fwd_exists :
  forall a P,
  {{fun st => P st}}
    X ::= a
  {{fun st => exists m, P (st & { X --> m }) /\
                st X = aeval (st & { X --> m }) a }}.
Proof.
  intros a P.
  unfold hoare_triple.
  intros.
  inversion H. subst.
  exists (st X).
  replace (st & {X --> aeval st a; X --> st X}) with (st & {X --> st X}) by (symmetry; auto using t_update_shadow).
  replace (st & {X --> st X}) with st.
  split; trivial.
  symmetry.
  clear.
  debug auto using t_update_same. (* `auto using` not works here *)
  apply t_update_same. (* but `apply` works *)
Qed.
```

I tried to make a  stand alone example:

```
Lemma lem_update_same:
  forall (st : state), st & {X --> st X} = st.
Proof.
  intros.
  debug auto using t_update_same. (* `auto using` here works *)
Qed.
```

but it failed to reproduce the problem, I don't know why, so I have to paste the whole proof code here, I'm very sorry for the authors of Software Foundations to do that but I don't know how to avoid it.

#### Coq Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.9.0 (January 2019)
compiled on Jan 17 2019 16:07:40 with OCaml 4.07.0
```

**Comment by Zimmi48** [comment]
>I think it will hold that for all lemma `lem`, if `apply lem` solves the goal, then `auto using lem` will also solve it, since `auto` will try `apply lem` at first round, but in the following example it doesn't hold.

This assumption is incorrect in general.

I can't test your code because it depends on notations that are defined in SF. But the general idea is that if `simple apply` can't solve your goal, then `auto` can't.

I'll classify this issue as a documentation bug, because the documentation of `auto` is clearly too imprecise at the current time, and should highlight this caveat.
