### ISSUE TITLE
-boot cleanup for test suite Makefile

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#9575]
After #9560 -boot should be exactly -q + allow defining modules in Coq. The test suite has `coqc_boot := $(BIN)coqc -coqlib $(LIB) -boot -q -test-mode -R prerequisite TestSuite $(COQFLAGS)` but the -boot isn't actually useful. Let's remove it.

**Comment by ejgallego** [comment]
Note that I have a PR that removes -boot entirely, I didn't submit to avoid stacked PRs.

**Comment by ejgallego** [comment]
Ok here it is: #9576
