### ISSUE TITLE
Internal bug in algebraic functor module type representation

### ISSUE THREAD

**Issue by sacerdot** [coq/coq#9579]
Consider the following two similar lines:

Module F (X: T) <: S with Module E := X := Make(X).
Module F(X: T)    : S with Module E := X := Make(X).

The algebraic expression "S with Module E := X" should be wrapped into a MoreFunctor abstraction
on (X: T) . However, while that is handled correctly in the case of typing (second line), the code in
Declaremods is weird for the first line.

In particular in function Declaremods.build_subtypes the empty list of args is passed to
Mod_typing.translate_modtype. That could make sense, because at the time of the call (X: T) has
been internalized (call to intern_arg in function Declaremods.declare_module).   However, the result
(variable subs) is used in line "check_subtypes mp subs" in the same function *after* unfreezing the
summary and reverting  the declaration of X.  At that point the algebraic expressions contained in
subs should be MoreFunctor-abstracted over X, which is not the case.

The bug does not manifest because check_subtypes ignores the algebraic expression fields and
subs is later thrown away. I can however observe it in my XML exportation plugin since I insert an
hook at the end of the function to observe subs.  Without that hook there is no way for any printing
command (like Print Module F) to print the subtyping constraints: they are forgotten. The same bug
is in the code to declare module types.

I can probably somehow avoid the bug myself in the code of the plug-in, but I believe that it would be
better to fix Coq code anyway to avoid in the future to have developers re-discover the bug if somebody
changes the code and starts using the algebraic expression in some way.

Note: passing args in place of [] is not a quick fix that works because it changes the elaborated type as
well and further Coq code to check the subtyping relation relies on the fact that the non-algebraic
structure expression was computed from the non-abstracted algebraic expression. The code logic
is twisted.

Coq version: 8.9.0

Cheers,
C.S.C.

**Comment by SkySkimmer** [comment]
Probably some substitution is applied incorrectly like in https://github.com/coq/coq/issues/9555 
I don't know if they're the same bug or 2 related bugs though.

**Comment by sacerdot** [comment]
Dear @SkySkimmer,

I have investigated the bug and re-edited the issue with an exact explanation of what is going on.
It is definitely unrelated to #9555 and it has nothing to do with substitutions.

**Comment by herbelin** [comment]
Finally, a PR fixing the internal representation can be found at #15386.
