### ISSUE TITLE
CoqIDE built with dependencies in default.nix segfaults at launch.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#9587]
#### Description of the problem

Building CoqIDE inside `nix-shell` or using `nix-build` produces a CoqIDE binary that segfaults at launch. (I have the same problem with the CoqIDE versions that I have installed through nixpkgs BTW.) It looks definitely related to NixOS/nixpkgs#54278, but since it seems this issue isn't being worked on, maybe we should do a local fix such as pinning to an older revision of nixpkgs (while overriding dune to have a recent enough version).

#### Coq Version

8.10+alpha (5ea4369bd4604b61ccc669f136827299920fb635)

**Comment by gares** [comment]
The issue you point to is about gtk, we don't have control over what/how nix packages. The segfault seems to be an ABI mismatch. IMO this but is totally off topic.

**Comment by Zimmi48** [comment]
We have control because we pin the version of nixpkgs we use in `default.nix`. Since it didn't use to be the case, we could decide to pin an older version. The only issue would be that it doesn't contain a recent enough version of dune, thus that's why I was talking about overriding its definition).

**Comment by gares** [comment]
oh, I see, then it seems something we should fix.

**Comment by maximedenes** [comment]
@Zimmi48 can you be the assignee? If not, maybe @vbgl?

**Comment by Zimmi48** [comment]
@vbgl Feel free to re-assign.

**Comment by vbgl** [comment]
Cannot reproduce.

Isn’t this a bug on your system, Théo?

**Comment by Zimmi48** [comment]
>Cannot reproduce.

How interesting! To be investigated.

**Comment by Zimmi48** [comment]
@vbgl I have just updated the channels of my systems. They are both on NixOS 18.09 while I'm installing CoqIDE from nixpkgs-unstable / our own pinned version of nixpkgs-unstable in `default.nix`, which apparently is the condition to reproduce the problem (a dependency version mismatch). Interestingly, I do not observe the segfault in one of the two systems (i3 session, with some tweaks https://github.com/Zimmi48/dotfiles/blob/0defe6c798910fe5dcf545058d005d4f5dfda978/dell-desktop-theo.nix#L47-L52) but I observe the segfault on the other (i3 session, but with XFCE installed https://github.com/Zimmi48/dotfiles/blob/0defe6c798910fe5dcf545058d005d4f5dfda978/hp-elitebook-theo.nix#L60). There is something off from the usual Nix philosophy of having every dependency listed in a derivation since it seems that in this case we have Gtk applications that try to interact with system-wide installed APIs. I see that in #9279, you have added `glib gnome3.defaultIconTheme wrapGAppsHook` to the list of CoqIDE dependencies. Isn't it the kind of change that would add the missing dependencies and fix this issue?

**Comment by vbgl** [comment]
I think you indeed need to add the dependencies. Caveat: all binaries will be wrapped. Is it good or not? I don’t know.

This particular problem should disappear when the nix package is split: the CoqIDE package only will get the gnome wrapping hook.

**Comment by Zimmi48** [comment]
I thought the addition of this line in `default.nix` would fix the issue for the Coq Nix package that we build from master, but it seems that it is not the case.

https://github.com/coq/coq/blob/1d68c24736b4cf68ac0c2f70122e3f3d28f0e876/default.nix#L50

**Comment by vbgl** [comment]
May you show a backtrace?

**Comment by Zimmi48** [comment]
The `-debug` flag does not show anything: the "Segmentation fault" message is the first thing that happens after launching CoqIDE.

**Comment by vbgl** [comment]
I was thinking of using `gdb` or the like. Notice that since the CoqIDE binary is wrapped, you may have to run the wrapper manually before running the naked binary from your debugger.

**Comment by Zimmi48** [comment]
I no longer have this problem since switching to NixOS 19.03. This doesn't mean that the problem has disappeared but I can't debug it anymore.
