### ISSUE TITLE
[kernel] [termination checking] reduction strategy incomplete

### ISSUE THREAD

**Issue by gares** [coq/coq#9598]
```coq
Inductive pair := K (n1 : nat) (n2 : nat).
Definition fst (p : pair) : nat := match p with K n _ => n end.
Definition mkK a b := K a b.
Fixpoint rec (x : nat) : nat := fst (K 0 (rec x)). (* works *)
Fixpoint rec (x : nat) : nat := fst (mkK 0 (rec x)). (* fails *)
```
The code in `inductive.ml` unfolds `mkK` then unfolds `fst` (but forgets it unfoleded `mkK`), hence it finds `match (mkK ...) with..` then it re-unfolds `mkK` but forgets that the obtained term is not neutral for the enclosing context.

**Comment by gares** [comment]
My original example is less trivial because the problem is not that `rec` is applied to a non-smaller term, but that (in branch where the rec call is discarded) it is not applied enough. In another branch the rec call is applied to a smaller term.

(untested)
```coq
Inductive pair := K (n1 : nat) (n2 : nat -> nat).
Definition fst (p : pair) : nat := match p with K n _ => n end.
Definition snd (p : pair) : nat := match p with K _ f => f end.
Definition mkK a b := K a b. 

Fixpoint rec (x : nat) : nat := match x with S w => (fst (K w rec)) + (snd (mkK w rec) w) | O => O end.
```

**Comment by mattam82** [comment]
Yes, that typical. I don't have another example from the top of my head. What I'm seeing more often in equations is that the recursive call or its structural argument is abstracted during a commutative cut with a match, and the guard fails to track this: morally, if the recursive call is not applied to enough arguments outside the match that's fine, as long at its instances in the branches are correctly applied to subterms (baring matches that rewrite in the type of the recursive function, which would be another instance of the propext issue). That would extend the guard significantly I think, and I don't know how to justify it cleanly. Everything's fine with well-founded recursion, so I'm not so interested in pushing that for now :)

**Comment by mattam82** [comment]
Hmm, I guess for your example you can use the same justification as what we do allowing `fix f x := let _ := f x in foo`
