### ISSUE TITLE
`Private Inductive` does not prevent generating a match

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#9608]
I believe the following should not be accepted:

```coq
Module M.
Private Inductive foo := C : foo -> foo.
End M.

Scheme Induction for M.foo Sort Prop.
```

I'm very surprised because privacy is seen by the kernel, so how come it can be circumvented?

**Comment by SkySkimmer** [comment]
The kernel stores privacy but currently doesn't read it.
What surprises me is that this one is accepted, but eg 
~~~coq
Module M.
Private Inductive foo :=.
End M.

Scheme Induction for M.foo Sort Prop.
~~~
isn't.

**Comment by maximedenes** [comment]
There's a test for privacy in the code generating the schemes, but it looks broken (as is probably `Inductive.is_private`). This is how I realized this issue.

**Comment by maximedenes** [comment]
Maybe that's unrelated, though, I haven't checked.
