### ISSUE TITLE
lia regression since 8.9

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9615]
#### Description of the problem

```coq
Require Import ZArith Lia. Local Open Scope Z_scope.
Goal
  forall q r lx : Z,
  8 * lx = 2 ^ 4 * q + r ->
  0 <= r < 2 ^ 4 ->
  forall q0 r0 : Z,
  q * 2 ^ 3 = 8 * q0 + r0 -> 0 <= r0 < 8 -> q * 2 ^ 3 = 8 * q0.
Proof.
  intros.
  Lia.lia. (* runs a long time, failed on travis *)
Qed.
```

#### Coq Version

8.9 good, c899b3085f2e15ef05fe3a66470df9bc25eeda59 bad, current-ish master bad (https://github.com/mit-plv/bedrock2/runs/66542251)

this is currently breaking bedrock2 build, I will look for a workaround tomorrow (it's 1am here).

**Comment by ejgallego** [comment]
That's a nice example to bisect, thanks! It should be easy to pinpoint candidates tho by looking at the changelog.

**Comment by vbgl** [comment]
I bet on this: 71280c8f38824e28bb0464ed15d951b542e33b48

Frédéric, are you aware of this? Maybe already working on it…

ping @fajb

**Comment by fajb** [comment]
I recently found regressions. This is one of those.
Sorry to hear they happen in real code...

For this specific case, the old code  works -- but this is a lucky case; it also has limitations.

Unset Simplex. is a current workaround.

I am working on it and hope to eventually find a satisfactory solution.
