### ISSUE TITLE
Weird lack of shadowing in pattern matching

### ISSUE THREAD

**Issue by andreasabel** [coq/coq#9616]
Playing with Coq 8.9.0 after a long abstinence (you want it that way!), I am stumbling over this mystifying error (with some dejavues):
```coq
Inductive Ord : Type :=
  sup (I : Type) (f : I -> Ord) : Ord.

Fixpoint Good (o : Ord) : Prop :=
  match o with
    sup I f => forall i:I, Good (f i)
  end.
```
```
In environment
Good : Ord -> Prop
o : Ord
I : Type
f : I -> Ord
The term "I" has type "Type"
while it is expected to have type 
"True".
```
I would have expected the pattern `sup I f` to shadow any previous bindings for `I` (which is apparently defined in the implicitly loaded prelude).  The printing of the environment seems to side with me, it displays a binding of `I : Type`.  Thus, it is mysterious why I am clashing with the seemingly self-contradicting expectation `I : True` of Coq.  

One explanation could be that a local binding does not shadow a global binding, thus, the binding `I : Type` is ignored as `I : True` takes precedence.  This explanation however, is refuted by the presence of `f : I -> Ord` in the environment, which would be ill-typed if `I : True`, thus, it could not have entered the environment were not `I : Type` taking precedence over `I : True`.
A further refutation of the "global dominates local" comes from the simple experiment 
```coq
Definition Bla (I : Type) : True := I.
```
with the expected error:
```
In environment
I : Type
The term "I" has type "Type"
while it is expected to have type 
"True".
```
Here, Coq is showing me its sane face.

In my opinion, the situation is fucked up (you want it that way?!).
If in a pattern binding such as `sup I f` the `I` can stand for the term `I : True`, then the error is that the pattern is ill-formed already, and, thus, the error should be
```
In environment
Good : Ord -> Prop
o : Ord
The term "I" has type "True"
while it is expected to have type 
"Type".
```
Quite a difference, imho.  Note that there is no `I : Type` in the environment here, and also the attributations "has" and "is expected" are now correct.  The "has" is the already established truth, while the "is expected" is a candidate for a truth coming from wish that a certain syntactic construct (`sup I ...`) is well-formed.

**Comment by ppedrot** [comment]
If anything and without having looked at the code, that looks like a problem with pattern-matching compilation, probably calling some elaboration code in the wrong environment. Term name scoping in Coq is the sane thing you expect (not talking about tactics but that's another story).

**Comment by ejgallego** [comment]
Yup, it looks like a bug; it could be even be a printing one [not very likely tho]

**Comment by ppedrot** [comment]
Just realized I misread your example: the problem has nothing to do with name scoping.

It is just that `I` happens to be a constructor (for `True`) that is bound in the default environment, so that when you write a pattern `sup I f`, Coq rightly believes you are trying to deeply match on the `I` constructor and throws the type error at you.

You may rightfully complain that sane languages like OCaml have distinct syntactic classes for variables and constructors, but unluckily Coq made the opposite choice too long ago to be solved. In the meantime, I am closing this bug as INVALID.

**Comment by ejgallego** [comment]
Oh indeed that's so confusing; at least this should be in FAQ.

**Comment by ejgallego** [comment]
I also think that the error message is pretty poor; not even the location of `I` is given; we should at least fix that, WDYT @herbelin ?

**Comment by ppedrot** [comment]
I agree, the distinction between variables and constructors in pattern-matching is a real minefield, it is not uncommon to write e.g. a catch-all clause by mistyping the name of the constructor, leading Coq to believe you're actually writing a variable.

**Comment by SkySkimmer** [comment]
>I also think that the error message is pretty poor; not even the location of I is given; we should at least fix that, WDYT @herbelin ?

It's a trivial fix, see https://github.com/coq/coq/pull/9619 (at least for this case, there are probably other paths where locations are dropped)

**Comment by ejgallego** [comment]
Thanks folks
