### ISSUE TITLE
Coq IDE 8.9.0 "Browse Coq manual" opens manual for 8.8.2

### ISSUE THREAD

**Issue by andreasabel** [coq/coq#9617]
Coq IDE 8.9.0 menu item "Help -> Browse Coq manual" opens manual for 8.8.2 at https://coq.inria.fr/distrib/V8.8.2/refman/ .

**Comment by vbgl** [comment]
The URL is stored in your local configuration file for CoqIDE. Mine is at: `$HOME/.config/coq/coqiderc`. If you remove the wrong lines (say running `sed -i '/^\(doc\|library\)_url/d' coqiderc` in the appropriate directory), you’ll get correct URLs instead.

**Comment by gares** [comment]
I think we should just remove this "option" from the config file
