### ISSUE TITLE
anomaly universe undefined after Local Unset Simplex

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9623]
#### Description of the problem

After running `Local Unset Simplex` and `Local Set Simplex` inside a proof, an unrelated case later on fails with an undefined universe anomaly. Re-stating goal at which it fails using `Set Printing All` does not produce the same anomaly.

code https://github.com/mit-plv/bedrock2/commit/4fb867ff4ac8737f6cc308ee894dea7accab9fbe
(re-stated https://github.com/mit-plv/bedrock2/commit/15cb18fed5c682186cade9ecd9c5d87fd8856ae9)
build log https://builds.sr.ht/~andres/job/32324#task-bedrock2-317
build instructions https://builds.sr.ht/api/jobs/32324/manifest
context #9615

#### Coq Version

c899b3085f2e15ef05fe3a66470df9bc25eeda59 and `246hkmh714iz31vqn8k2f71g9k5rfbs9` ("The Coq Proof Assistant, version 8.10+alpha (February 2019) compiled on Feb 21 2019 13:52:15 with OCaml 4.06.1")

**Comment by JasonGross** [comment]
cc @ejgallego about side effects inside proofs?

**Comment by andres-erbsen** [comment]
A similar anomaly also occurs when using `abstract`... (at `intuition congruence` in `lightbulb.v` in fiat-crypto). cc @samuelgruetter

**Comment by ppedrot** [comment]
This option was removed, closing.
