### ISSUE TITLE
Documentation on (E)Constr.mkEvar?

### ISSUE THREAD

**Issue by fakusb** [coq/coq#9625]
During my work on a ocaml-plugin for coq, I found myself in the following situation:
I had an `Evar.` in hand that I wanted to turn into an `EConstr`, but I had no idea how to call `EConstr.mkEvar`, as I need an `econstr array` to build the `existential` to pass to `EConstr.mkEvar`. And I was not able to unerstand what this array is/what it is needed for.

I found the following documentation in Costr, but at least to me it wasn't helpfull

```
(** [constr array] is an instance matching definitional [named_context] in
   the same order (i.e. last argument first) *)
type 'constr pexistential = Evar.t * 'constr array
```

So the documentation for mkEvar might needs improvement?

**Comment by ejgallego** [comment]
Thanks @fakusb , for reference this is the current pointer:
- https://coq.inria.fr/api/master/coq/Constr/index.html#term-constructors.
- https://coq.inria.fr/api/master/coq/EConstr/index.html#constructors

IMHO that's pretty poor for such key functions indeed.

**Comment by SkySkimmer** [comment]
The manual explains that existential variables live in a context: https://coq.inria.fr/distrib/current/refman/language/gallina-extensions.html?highlight=existential#existential-variables
So to make a term from one you need to provide values for the variables in its context.

I don't know what you want to do with a naked evar so I can't tell you how to get those values.

**Comment by fakusb** [comment]
Ok, I now know for sure _why_ this is needed. In my case, I knew that the evar was instantiated in an evar_map I was holding, and I was wondering how to "look up" how exactly it was instantiated.

I got the naked evar from Proofview.Goal.goal, but just noticed that this is to be 'avoided if possible'. I fixed my problem in another way.
