### ISSUE TITLE
Miller pattern unification fails on evars

### ISSUE THREAD

**Issue by ggonthier** [coq/coq#9663]
#### Description of the problem

Miller patterns are an important sub case of higher order unification where functions have MGUs. Its implementation is instrumental in allowing, for instance, a function type `A -> R` match a generic pi-type pattern of the form `forall x : ?B, ?F x`. Unfortunately this is broken in Coq, when `R` is an evar `?RT`, as then Coq can try and fail to assign `?F x` to `?RT` (the local `x` is not in its context), and this failure is persistent. This makes the behaviour of unification highly dependent on the order in which assignments are made to evars, as _any_ term assignment to `?RT`, including a dummy `(fun T => T) ?RT0`, would allow unification to succeed.
  Unfortunately it turns out the constraint processing order for `Canonical` instances _always_ triggers this bug; this issue is blocking me in a mathcomp adding support for dependent functions in the finite function library (mathcomp/dependent-positive-finfun).

Sample code displaying the issue:
```
Definition id_depfn S T (f : forall x : S, T x) := f.
Fail Definition idn : nat -> nat := @id_depfn _ _ (fun x => x).
Definition idn : nat -> nat := @id_depfn _ _ ((fun x => x) : _ -> (fun T => T) _).
```

**Comment by Janno** [comment]
I can't say I really understand the issue but it got me curious and I found out that all of these definitions succeed when using Unicoq (and writing `id_depfn _ _` instead of just `id_depfn`). Not sure if this helps.

**Comment by gares** [comment]
> (forall x : _, _ x).

I think that in this writing the second underscore sees `x` twice, one because it happens to be under the binder and another one because you pass `x` as an argument to it. I did not look at the code, but I guess it is not in the pattern fragment for Coq.

Another way to put it, evars are not all quantified at the top level as you example seems to expect.

> Fail Definition idn : nat -> nat := id_depfn (fun x => x).

So this one seems the show a real bug (here T is quantified at he toplevel, so it sees `x` only once.

**Comment by ggonthier** [comment]
@gares you are correct, I had oversimplified the issue in some of the lines. I've edited them out to leave only the `id_depfn` ones, which are closer to the real problem anyway.
