### ISSUE TITLE
[ssr] fix documentation of `by [tacs]`

### ISSUE THREAD

**Issue by gares** [coq/coq#9669]
The manual in unclear about `by [t1|t2]` meaning `first [done| t1;done | t2;done]`.

**Comment by gares** [comment]
CC @amahboubi @affeldt-aist @CohenCyril

**Comment by erikmd** [comment]
This documentation issue had been spotted during PR https://github.com/coq/coq/pull/9651#issuecomment-467574586, I can prepare a small related PR.
