### ISSUE TITLE
Uncaught exception Failure("lexing: empty token") in Coqdoc

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#9670]
#### Version

Coq 8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following code demonstrates some quirks in Coqdoc
that eventually trigger a fatal error and corrupt the output.
I wrote it in the form of a poem to ease the frustration.

```
Require Import String.
Open Scope string_scope.

Compute "More than 4 leading dashes produce a horizontal rule.".
(** For such a task, a number so miniscule.
    ----
    Thinking four is more than four,
    really shakes me to my core. *)

Compute "Documentation starts with (**, followed by a space,
and ends with *).".
(** There should therefore be no case,
    for the end --- to be preceded --- by a space.
    Except this one, of course. *)
(** * * *)
(** * **)

Compute "Coq material is quoted between the delimiters [ and ].
Inside quotations,
the code is pretty-printed in the same way as it is in code parts.".
(** Unless the code is
    [Compute "Documentation starts with (**, followed by a space,
    and ends with *).".] and,
    in the previously seen parts,
    the parsing restarts. *)

Compute "Preformatted vernacular is enclosed by [[ and ]].
The former must be followed by a newline
and the latter must follow a newline.".
(** So the lack of a line break,
    a choice one can easily make,
    should not end so abysmally.
[[
Compute "Coqdoc presupposes that the given Coq files are well-formed
(at least lexically).".
]] *)
(* But we are now stuck inside the enclosure,
   required to endure,
   until the next block of documentation. *)

Compute "Coqdoc is robust: it shouldn't fail, whatever the input is.".
(** It does not fail,
    until [Fatal error: exception Failure("lexing: empty token")]
    causes it to bail. *)

Compute "But remember: ""garbage in, garbage out"".".
(** And garbage en route.
    In loving memory of the lost footer. *)
```

Following `]]` with `*)` is what causes the fatal error.

#### Notes

All of the strings we `Compute` are
from [the reference manual section _Utilities_][utilities] on Coqdoc.

[utilities]: https://coq.inria.fr/refman/practical-tools/utilities.html

**Comment by herbelin** [comment]
Indeed, `coqdoc` relies on a lexer which is not aware of all the complexity of Coq syntax. What would be needed is to use the parser of Coq instead... Sorry about it.

**Comment by Blaisorblade** [comment]
It'd help to add line numbers to the error report; that should be easier than switching lexers.

**Comment by herbelin** [comment]
From the point of view of the lexer, the error is at the end of the file (because it continues to look again and again to the `]]` which it overlooked at the time it was here) and this is not very informative anyway. If what you expect is an error at the `]] *)`, coqdoc is unable to see it. The point is that coqdoc only recognizes special parts of the syntax with a weak control over it.  Everything else is browsed uninterpreted (in particular a `]]` or a `(**` in a wrong place is uninterpreted and undected).

**Comment by Blaisorblade** [comment]
Interesting, but then I'd still like the filename — `make html` runs coqdoc on all files at once (and I have 90). Luckily that can be avoided, but it's still not great:

```
$ time make html
COQDOC -d html
Fatal error: exception Failure("lexing: empty token")
make[1]: *** [html] Error 2
make: *** [html] Error 2
```

**Comment by Lysxia** [comment]
coqdoc could report the location of the opening `[[` it thinks is mismatched. And given that this seems a pretty common mistake to make, coqdoc could also keep track of `]]` sequences that it ignores and report them if there is an error. Or just accept `]] *)` as a valid delimiter.
