### ISSUE TITLE
"coqc -async-proofs on xxx.v" doesn't print the location of some errors

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#9671]
#### Description of the problem

`coqc -async-proofs on xxx.v` doesn't print the location of some errors, whereas `coqc xxx.v` and `coqtop -async-proofs on <xxx.v` do.  (example and the input file below):

This is a problem for users who encounter one of these errors because they'll have no easy way to determine where the error is.  It's also a problem for output tests that generate these errors because the actual output will vary across different tests suites.  (e.g. in https://github.com/coq/coq/pull/8669).

In contrast, I do see location info for syntax errors with each of the alternative commands.

This seems to me a regression related to the introduction of coqc.  (The output test in https://github.com/coq/coq/pull/8669 worked correctly in CI several months ago, prior to coqc).

Observe there is no location info ("File ..." or "Toplevel input ...") on the first command:

```
$ bin/coqc.exe -async-proofs on test-suite/output/Error_msg_diffs.v
Error:
In environment
T : Type
p : T -> bool
a : T
t1, t2 : btree T
IH1 : count p (rev_tree t1) = count p t1
IH2 : count p (rev_tree t2) = count p t2
Unable to unify "(if p a then 1 else 0) + (count p t1 + count p t2)" with
 "(if p a then 1 else 0) + (count p t2 + count p t1)".

$ bin/coqc.exe test-suite/output/Error_msg_diffs.v
File ".\test-suite/output/Error_msg_diffs.v", line 31, characters 0-12:
Error:
In environment
T : Type
p : T -> bool
a : T
t1, t2 : btree T
IH1 : count p (rev_tree t1) = count p t1
IH2 : count p (rev_tree t2) = count p t2
Unable to unify "(if p a then 1 else 0) + (count p t1 + count p t2)" with
 "(if p a then 1 else 0) + (count p t2 + count p t1)".

$ bin/coqtop.exe -async-proofs on <test-suite/output/Error_msg_diffs.v
Toplevel input, characters 0-12:
> reflexivity.
> ^^^^^^^^^^^^
Error:
In environment
T : Type
p : T -> bool
a : T
t1, t2 : btree T
IH1 : count p (rev_tree t1) = count p t1
IH2 : count p (rev_tree t2) = count p t2
Unable to unify "(if p a then 1 else 0) + (count p t1 + count p t2)" with
 "(if p a then 1 else 0) + (count p t2 + count p t1)".
```

The input file:
```
Require Import Arith List Bool.

Inductive btree (T : Type) : Type :=
  Leaf | Node (val : T) (t1 t2 : btree T).

Arguments Leaf {T}.
Arguments Node {T}.

Fixpoint rev_tree {T : Type} (t : btree T) : btree T :=
match t with
| Leaf => Leaf
| Node x t1 t2 => Node x (rev_tree t2) (rev_tree t1)
end.

Fixpoint count {T : Type} (p : T -> bool) (t : btree T) : nat :=
match t with
| Leaf => 0
| Node x t1 t2 =>
  (if p x then 1 else 0) + (count p t1 + count p t2)
end.

Lemma count_rev_tree {T} (p : T -> bool) t : count p (rev_tree t) = count p t.
Proof.
induction t as [ | a t1 IH1 t2 IH2].
  easy.
simpl.
rewrite IH1.
rewrite IH2.
reflexivity.
rewrite (Nat.add_comm (count p t2)).
easy.
Qed.
```

**Comment by jfehrle** [comment]
Here's what I learned while trying to understand the problem:

Topfmt.print_err_exn generates the error message.  `loc` is `None` for the `coqc -async-proofs on` case, so the location line isn't printed.  It appears that when an exception is raised, the `loc` information must be saved through Exninfo/Store (perhaps this is necessary to pass the loc due to OCaml limitations?)

In the failing case, `!default_phase` is `InteractiveLoop` and `Printexc.to_string ex` in Coqc.main is `Stm.RemoteException(_)`.

In the working case with coqc, pr_phase matches on `_, Some loc` and `Printexc.to_string ex` is `ExplainErr.EvaluatedError(_, 0)`

**Comment by ejgallego** [comment]
This should indeed be fixed, however I do suggest you tweak the test file [hopefully you can] so this problem is avoided. Alternative you can add an `-async-proofs off` to the header as is done in a few files such as `output/FunExt.v`

**Comment by jfehrle** [comment]
The test is supposed to generate an error, so adding `-async-proofs off` is the only useful workaround.

**Comment by SkySkimmer** [comment]
Why aren't you using `Fail`? Especially considering you have code after the failing line.

**Comment by jfehrle** [comment]
> Why aren't you using `Fail`?

What's the benefit?  Convention?  Documenting the point of the failure?  Avoiding running the 3 lines after the failure?  I've not used `Fail` before though it's not entirely unfamiliar.

**Comment by SkySkimmer** [comment]
Use Fail for commands which should fail. That way your test won't die after the failing command. Also Fail doesn't print location information so it works around this bug.

**Comment by jfehrle** [comment]
> Use Fail for commands which should fail. That way your test won't die after the failing command.

What do you mean by "die"?  The test works.  coqc quits upon the first error, which is appropriate.

Also, `Fail` doesn't include the diff highlights, which is the point of the test:

![image](https://user-images.githubusercontent.com/1253341/53659283-0571d400-3c10-11e9-8749-b5b7a0f3731e.png)

**Comment by SkySkimmer** [comment]
Fixed by https://github.com/coq/coq/pull/17650
