### ISSUE TITLE
Unification failure even if the RHS contains a single evar with distinct vars

### ISSUE THREAD

**Issue by erikmd** [coq/coq#9673]
### Description of the problem

During the development of coq/coq#9651 (tacticals `under` and `over`), I've noticed that sometimes Coq doesn't succeed in unifying goals of the form `expr(i,j) = ?Evar i j` despite the RHS is a single "Miller pattern".

It was blocking for the `over` terminator, but I noticed one could workaround it by manually changing the LHS to beta-redex form, in order to make the unification succeed.

I developed a pre-processing tactic that automates this workaround (see below) and I also include in this post a few MWEs. This helper tactic is now part of coq/coq#9651 but I wanted to open an issue to ask (1) whether this unification issue in this particular form is already known, and (2) whether it might be solved "upstream" (i.e. without requiring that helper tactic)?  

I Cc @ggonthier and @gares in case so they'd like to add remarks or extra similar test-cases, as we discussed related topics today.

### Minimal working examples

```coq
Require Import ssreflect.

Ltac beta_expand c e :=
  match e with
  | ?G ?z =>
    let T := type of z in
    match c with
    | context f [z] =>
      let b := constr:(fun x : T => ltac:(let r := context f [x] in refine r)) in
      rewrite -{1}[c]/(b z); beta_expand b G
    | (* constant *) _ =>
      let b := constr:(fun x : T => ltac:(exact c)) in
      rewrite -{1}[c]/(b z); beta_expand b G
    end
  | ?G => idtac
  end.

Ltac helper :=
  move=> *;
  lazymatch goal with
  | [ |- ?c = ?e ] =>
    beta_expand c e
  end.

(********************************************************************)

Lemma test0 (i : nat) : True.
evar (f : nat -> nat).
have: 0 = f i.
  rewrite /f; clear f.
  done. (* ok *)
done.
Qed.

Lemma test1_bug (i : nat) : True.
evar (f : nat -> nat).
have: i + 2 = f i.
  rewrite /f; clear f.
  (* |- i + 2 = ?f i *)
  Fail done.
  helper.
  done.
done.
Qed.

Lemma test2_bug (i j : nat) : True.
evar (f : nat -> nat -> nat).
have: i * (i - 1) + j = f i j.
  rewrite /f; clear f.
  (* |- i * (i - 1) + j = ?f i j *)
  Fail done.
  helper.
  done.
done.
Qed.
```

### Coq Version

Tested with 8.8.2, compiled with OCaml 4.05.0 on Debian GNU/Linux

**Comment by JasonGross** [comment]
It's not clear to me that this is a bug; which of the following do you want `?f` to be instantiated with in the last case?
- `fun i0 j0 => i0 * (i0 - 1) + j0`
- `fun i0 _ => i0 * (i0 - 1) + j`
- `fun i0 j0 => i0 * (i - 1) + j0`
- `fun i0 _ => i0 * (i - 1) + j`
- `fun i0 j0 => i * (i0 - 1) + j0`
- `fun i0 _ => i * (i0 - 1) + j`
- `fun _ j0 => i * (i - 1) + j0`
- `fun _ _ => i * (i - 1) + j`

Anyway, here is a much smaller example:
```coq
Goal forall x : nat, True.
  intro x.
  let v := open_constr:(x + 1 = _ x) in
  pose (eq_refl : v).
```
Note that if you insert `pose v as V; instantiate (1:=ltac:(clear x)) in (Value of V);` after the `let` and before the `pose`, then it works fine.

I think perhaps a better question here is: how are you generating the applications of evars to these variables, and why aren't you clearing each of these variables from the context of the evar when you generate the application?

**Comment by gares** [comment]
You have to create the evar *before* `i` is introduced in the context, otherwise the evar sees `i` twice, once because it is in its original context and another time because you pass `i` to it explicitly.

**Comment by erikmd** [comment]
Thanks for your comments.

@gares 
> You have to create the evar _before_ `i` is introduced in the context, otherwise the evar sees `i` twice, once because it is in its original context and another time because you pass `i` to it explicitly.

Good catch! my minimal-working-examples were broken and the `over` tactic doesn't seem to require using the `beta_expand` workaround, even in the case where we relying on a "context lemma" with two binders such as `eq_mx`.
So I simplified the code in 3b1ccf2005aad90eb0d9f05c4f36f91c2aeccbf2

@JasonGross 
> I think perhaps a better question here is: how are you generating the applications of evars to these variables, and why aren't you clearing each of these variables from the context of the evar when you generate the application?

Actually the `under` tactics starts by creating the evar(s) in the first place, before introducing variables for the binders, so the issue I suspected (because of a non-realistic test-case of `over`) should just not appear with `under + over` :)
Closing the issue now.
