### ISSUE TITLE
Error "[...]:proofworker:0:0 STM: sending back a fat state" in CoqIDE, from a correct program that is using "Function" with "measure".

### ISSUE THREAD

**Issue by staffehn** [coq/coq#9680]
#### Description of the problem
I'm not sure weather this is a bug in CoqIDE or the compiler, I so far was only able to get an error with the following example code when using CoqIDE.

The example is:
```coq
Require Import FunInd.
Require Arith.
Require Recdef.
Function test i {measure (fun i => i) i} : nat
 := match i with | 0 => 0
                 | S j => test j
    end.
Proof.
  intros.
  constructor.
Qed.
```

Sucessfully loads in coqtop. Also sucessfully is interpreted in CoqIDE, when stepping through it line-by-line. If hovever, in CoqIDE, I skip directly from anywhere before the "Function ..." definition to afteR the "Qed." (for example by just pressing the "go to end" button), I get:

In Messages: "`****:proofworker:1:0 STM: sending back a fat state`", where `****` is a varying number (perhaps a thread id).

In Errors an entry with:
Line: 10
Error message: Universe inconsistency.

#### Coq Version
CoqIDE 8.9.0
The Coq Proof Assistant, version 8.9.0 (February 2019)
compiled on Feb 27 2019 0:54:30 with OCaml 4.02.3

**Comment by staffehn** [comment]
In another issue which is closed, #8609, I found the example:
```coq
Goal Prop.
Proof.
set (a := Prop).
Qed.
```
Which, when loaded in CoqIDE, if you press "go to end", does the same, as the above (i.e. Message "[...]STM: sending back a fat state"), except with Error message: Attempt to save an incomplete proof (in proof Unnamed_thm).
This however is a program that also normally fails, though with the "Attempt to save an incomplete proof (in proof Unnamed_thm)" simply in the Message tab.

**But**, the same example can also cause a Pop-Up: `Warning` with `Coqtop died badly.` if executed in the following manner:

First enter the program into CoqIDE or open a file containing it.
Then press "go to end".
Then press "Backward one command" three times (so that "Goal Prop." is still highlighted in green, but "Proof." is not).
Finally press "go to end" again, or alternatively three times "forward one command" (both give the same Pop-Up).

**Comment by ejgallego** [comment]
This is a known problem, and there is hope the situation in 8.10 improves. Unfortunately it will be hard to fix in 8.9.

#9645 should greatly help towards fixing this.

**Comment by ejgallego** [comment]
For now the workaround is to either go step by step or to process that particular file with the `-async-proofs off` setting.

**Comment by ejgallego** [comment]
I can confirm that in master this seems to work much better, would you mind trying a recent 8.10 build @staffehn ?

**Comment by staffehn** [comment]
@ejgallego Just managed to compile master ^^
The "STM: sending back a fat state" errors are gone.
It is however still possible to archieve the "Coqtop died badly." in CoqIDE.
#9431 is thee same bug, I'll comment on there.

**Comment by ejgallego** [comment]
Thanks! Hopefully we can fix the other bug too.
