### ISSUE TITLE
Automatically-generated format for `only parsing` notation overwrites format of earlier `only printing` notation.

### ISSUE THREAD

**Issue by Janno** [coq/coq#9683]
#### Description of the problem
The following code shows how including the `'with'` and `'end'` keywords in the `only parsing` notation in `T1` and `T2` changes how the forced line breaks in the `only printing` notation in line 10 are printed or ignored, respectively. I can only hope that I am too tired to see some obvious mistake in what I am doing here.

```coq
Declare Scope blafu.
Delimit Scope blafu with B.
Axiom DoesNotMatch : Type.
Axiom consumer : forall {A} (B : A -> Type) (E:Type) (x : A) (ls : list nat), unit.

Notation "|  p1  |  ..  |  pn" := (@cons _ p1 .. (@cons _ pn nil) ..) (at level 91) : blafu.
Notation "'mmatch_do_not_write' x 'in' T 'as' y 'return' 'M' p 'with_do_not_write' ls" :=
    (@consumer _ (fun y : T => p%type) DoesNotMatch x ls%B)
      (at level 200, ls at level 91, only parsing).
Notation "'mmatch' x 'in' T 'as' y 'return' 'M' p 'with' ls 'end'" :=
  (@consumer _ (fun y : T => p%type) DoesNotMatch x ls%B)
    (at level 200, ls at level 91, only printing,
     format "'[  ' mmatch  '/' x ']'  '/' '[  ' in  '/' T ']'  '/' '[  ' as  '/' y ']'  '/' '[  ' return  M  p ']'  with  '//' '[' ls ']'  '//' end"
     ).

Module T1.
Notation "'mmatch' x 'in' T 'as' y 'return' 'M' p ls" :=
  (mmatch_do_not_write x in T as y return M p with_do_not_write ls)
    (at level 200, ls at level 91, only parsing).
Check (mmatch 1 +2 +3+4+5+6 in nat as x return M (x = x) | 1). (* line breaks after [with] and before [end] *)
End T1.
Module T2.
Notation "'mmatch' x 'in' T 'as' y 'return' 'M' p 'with' ls 'end'" :=
  (mmatch_do_not_write x in T as y return M p with_do_not_write ls)
    (at level 200, ls at level 91, only parsing).
Check (mmatch 1 +2 +3+4+5+6 in nat as x return M (x = x) with | 1 end). (* no line break after [with] or before [end] *)
End T2.
```

#### Coq Version
master

**Comment by Janno** [comment]
Okay, I did some more minimizing:
```coq
Axiom consumer : nat -> list nat -> unit.
Notation "'mmatch' x 'with' ls 'end'" :=
  (consumer x ls) (at level 200, ls at level 91, only printing,
                   format "'[  ' mmatch  '/' x ']'  with  '//' '[' ls ']'  '//' end").
Local Notation "'mmatch' x ls" :=
  (consumer x ls)
    (at level 200, ls at level 91, only parsing).
Check consumer 1 (1::nil). (* Has line breaks *)
Notation "'mmatch' x 'with' ls 'end'" :=
  (consumer x ls)
    (at level 200, ls at level 91, only parsing).
Check consumer 1 (1::nil). (* Doesn't have line breaks *)
```

My current hypothesis is that
1) the last notation matches the `only printing` notation perfectly and overwrites the format attached to that with the default format generated by coq, *even though* it is marked as parsing only.
2) the second-to-last notation doesn't match perfectly and thus doesn't affect the `only printing` notation.

**Comment by Janno** [comment]
And indeed, giving a format to the `only parsing` notation (the one with `with .. end`) does overwrite the format of the `only printing` notation. This is a strong indicator to me that this might also be the case when one doesn't specify a format for the `only parsing`—only that coq will use the default format, I suppose.

**Comment by Janno** [comment]
This problem seems to be fixed on master but not on 8.11. Can I assume that the fix (whatever it was) will make it into 8.12?

**Comment by ejgallego** [comment]
> Can I assume that the fix (whatever it was) will make it into 8.12?

Yes; it would interesting to know if we have a test case covering this.

**Comment by Janno** [comment]
`git bisect` points to:

```
commit 039b2423cf7b85f2f5960dde6a1586f0f07cf9d0
Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
Date:   Sun Sep 29 00:06:19 2019 +0200

    Addressing #6082 and #7766 (overriding format of notation).
```

A quick glance didn't result in an obvious test case for this particular bug here (which was not mentioned in the commit). @herbelin can surely say for certain!

Reading the diff does seem to indicate that specifying a format for parsing-only notations is now met with a warning which says that the format is irrelevant. Hopefully that also applies also to the default format—if that is even a thing for parsing-only notations after this commit. So it seems the bug was fixed in way that makes a lot of sense to me! :)

**Comment by herbelin** [comment]
#10832 has already two tests, but none with `only printing`. If @ejgallego is not afraid of the extra burden of managing an extra PR adding a test, I can add one.

**Comment by Alizter** [comment]
Seems that #10832 already has the needed tests. Closing this issue.
