### ISSUE TITLE
Index out of bounds in native_compute

### ISSUE THREAD

**Issue by mattam82** [coq/coq#9684]
#### Description of the problem

Running a native_compute in file examples/AlmostFull.v of this branch of Equations https://github.com/mattam82/Coq-Equations/tree/almost_full_native_compute_bug
on current master results in an "Index out of bounds" error. It's hard to minimize. I would bet we're doing something wrong with universes (there are a few polymorphic things there).

#### Coq Version

master

**Comment by maximedenes** [comment]
I'm afraid this reveals a critical bug:

```coq
Set Primitive Projections.

Record foo := mkFoo { proj1 : bool; proj2 : bool }.

Definition x := mkFoo true false.
Definition proj x := proj2 x.

Lemma oops : proj = fun x => proj1 x.
Proof. native_compute; reflexivity. Qed.

Lemma bad : False.
assert (proj1 x = proj x).
  rewrite oops; reflexivity. 
discriminate.
Qed.

Print Assumptions bad.
```

The bug was introduced by e1e7888ac4519f4b7470cc8469f9fd924514e352. It is trivial to fix, I'll submit a patch.

**Comment by maximedenes** [comment]
Cc @ppedrot

**Comment by ppedrot** [comment]
Oh my, sorry...
