### ISSUE TITLE
coq-makefile: print-pretty-timed-diff broken

### ISSUE THREAD

**Issue by fakusb** [coq/coq#9705]
When trying to use the print-pretty-timed-diff target, there is some problem with the invoked python code (at least when using Python 3.7.2):

```
> make -f Makefile.coq print-pretty-timed-diff 
Traceback (most recent call last):
  File "/home/fakusb/.opam/coq-dev/lib/coq//tools/make-both-time-files.py", line 16, in <module>
    print_or_write_table(table, args[3:])
  File "/home/fakusb/.opam/coq-dev/lib/coq/tools/TimeFileMaker.py", line 215, in print_or_write_table
    print(table.encode("utf-8"), file=binary_stdout)
TypeError: a bytes-like object is required, not 'str'
make: *** [Makefile.coq:337: print-pretty-timed-diff] Error 1
```

this occurs both on coq 8.8.2 and master (at least in a build from 2 weeks ago)

**Comment by fakusb** [comment]
Removing this `-` is a workaround for me, to at least get the diffs as a file.
https://github.com/coq/coq/blob/5f7bb95b6532a6983a2d1880aa531e4e4dd6568d/tools/CoqMakefile.in#L127

**Comment by JasonGross** [comment]
> Removing this - is a workaround for me, to at least get the diffs as a file.

Indeed, and you should also be able to pass `TIME_OF_PRETTY_BUILD_EXTRA_FILES=" "` or `TIME_OF_PRETTY_BUILD_EXTRA_FILES=/dev/null` on the command line.

I suspect this is yet another python 2/python3 issue, and I am not very familiar with the standard ways of fixing this.

**Comment by JasonGross** [comment]
I'm confused by this error message.  Shouldn't `encode` be giving us a `bytes` object already?

**Comment by fakusb** [comment]
I don't have any deeper uinderstanding of python, but using `binary_stdout.write(table.encode("utf-8"))` instead of `print` solves the problem for me, and runs in both python2 and python3.
This fails if the code would use `sys.stdout` instead of `sts.stdout.buffer`, but I'm not sure this should/can happen here. (The [note here](https://docs.python.org/3/library/sys.html#sys.stdin) maybe says that there should always be a buffer in our context? Not sure though...)

**Comment by JasonGross** [comment]
Perhaps the failure happens with your choice if you redirect stdout to a file?

**Comment by JasonGross** [comment]
@fakusb Can you confirm if https://github.com/coq/coq/pull/9766 fixes your problem?

**Comment by fakusb** [comment]
#9766 fixes my problem, and works with both python2 and python3 and with redirecting the output to an file or stdout.

**Comment by JasonGross** [comment]
Great, thanks for testing!  (Btw, if you have a log file that the code previously failed on (the output of `make TIMED=1` or whatever), I'd be happy to add it to the test-suite if you upload it here or make a PR to add it.)
