### ISSUE TITLE
Proof editing in progress despite aborting in CoqIDE

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#9709]
#### Version

Coq 8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following actions result in a stuck state.

* Open CoqIDE.
* Insert the following code into the buffer.

```
Module M.

Theorem no : False.
Proof. constructor. Defined.

Definition yes : True := I.

End M.
```

* Navigate to any point between the end of `Definition` and `End`.
* Navigate forward.
* Observe the suggestion.

```
Proof editing in progress.
Proofs currently edited: no.
Use "Abort All" first or complete proof(s).
```

* Insert `Abort All.` between the end of `Definition` and `End`.
* Navigate forward.
* Navigate forward.
* Observe the same suggestion again.

```
Proof editing in progress.
Proofs currently edited: no.
Use "Abort All" first or complete proof(s).
```

* Replace `Abort All` with `Abort`.
* Navigate forward.
* Observe the error message.

```
No focused proof (No proof-editing in progress).
```

There is no way to recover.

**Comment by gares** [comment]
The suggestion is unclear and outdate. It should tell you to Abort or Admit the proof of `no`.

**Comment by Alizter** [comment]
Since 8.11 the suggestion no longer appears. It lets you close the module, but it seems that `no` is aborted. However the original issue of being stuck doesn't seem to be relevant any more. Therefore I am closing this issue.
