### ISSUE TITLE
Print Ltac prints invalid Ltac by neglecting to insert constr:

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#9716]
#### Description of the problem

```coq
Require Import Coq.Lists.List.
Ltac foo x := match x with @List.map ?A ?B => constr:((A, B)) end.
Print Ltac foo.
(* Ltac foo x := match x with
              | map (B:=?B) => (A, B)
              end *)
```
This printed Ltac is not valid, as it is missing the `constr:`.

#### Coq Version

8.10+alpha (a83eac8463787c13a2dbd3903baf2b59ca1a4635)

Possibly a duplicate of #6613, though here it actually generates invalid Ltac rather than merely surprising Ltac.

Related: #5169

**Comment by herbelin** [comment]
See #13028 for a fix.
