### ISSUE TITLE
CoqIDE crashes randomly

### ISSUE THREAD

**Issue by JonasOberhauser** [coq/coq#9721]
#### Description of the problem

CoqIDE crashes every few minutes. The files I have opened are irrelevant (it also crashes for files with just a few hundred lines). To be precise, CoqIDE stops responding and has to be shut down manually.

I think it is related among other things to searching in the file (using the text search, not the Search command), or maybe more generally, moving around in the file. But I'm not sure this is really the precise issue.

#### Coq Version

8.9 on Windows. I updated two days ago from 8.7.2 (on my windows 10 pc) and from 8.5 (on my windows 7 pc) and didn't have nearly as many problems before. 
To update, I uninstalled the previous version using the windows program manager, then downloaded the installer of the new version from the website and ... installed it.
The problem exists both on my Windows 7 and my Windows 10 pc.

**Comment by gares** [comment]
Could you please be more specific?
When CoqIDE freezes, and you are searching, is Coq also computing? (is the progress bar in the bottom-right corner active?)

**Comment by JonasOberhauser** [comment]
![image](https://user-images.githubusercontent.com/183564/55282771-a9ec5080-534b-11e9-9068-d94085c27831.png)

**Comment by ejgallego** [comment]
I'd suggest you try coq master as it has seen quite a few changes in coqide

**Comment by ejgallego** [comment]
Also, tweaking a few options may help. For example `async off` of `error-resiliance off`

**Comment by JonasOberhauser** [comment]
> Also, tweaking a few options may help. For example `async off` of `error-resiliance off`

I tried finding these options (with the help of google) but I couldn't, would you kindly tell me where to find them? Thanks 👍
