### ISSUE TITLE
Notations without variables quietly reserve levels

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#9726]
#### Version

Coq 8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following code causes an unexpected error.

```
Notation "'!'" := False (at level 42, left associativity).
Notation "P '?'" := (P -> !) (at level 42, left associativity).

Check ! ? ?.
```

```
Level 42 is already declared right associative while it is now expected to be left associative.
```

There are two ways to recover.
The morally correct one is to omit the level of the notation for `!`,
which puts it at level `0`.

```
Notation "'!'" := False.
Notation "P '?'" := (P -> !) (at level 42, left associativity).

Check ! ? ?.
```

The morally questionable one is to reserve the notation for `?` beforehand.

```
Reserved Notation "P '?'" (at level 42, left associativity).

Notation "'!'" := False (at level 42).
Notation "P '?'" := (P -> !).

Check ! ? ?.
```

#### Notes

It appears that notations without variables
reserve their level to be right-associative,
even though they are not subject to reserved associativities themselves.

**Comment by SkySkimmer** [comment]
When I run the example code the error is on the second Notation line, not on the Check.
Looks like a duplicate of https://github.com/coq/coq/issues/9079

**Comment by Tuplanolla** [comment]
This is indeed a duplicate of #9079.
