### ISSUE TITLE
[dune] coq_config contents break coq_makefile

### ISSUE THREAD

**Issue by gares** [coq/coq#9735]
Coq_config.ml contains `gramlib/.pack`, but with inside the dune build tree these files are elsewhere:
```
./_build/default/gramlib/gramlib.cma
./_build/install/default/lib/coq/gramlib/gramlib.cma
```

**Comment by ejgallego** [comment]
That seems weird, and I cannot reproduce. How are you calling Dune?

**Comment by gares** [comment]
Last time I did a `make -f Makefile.dune world`, but in any case I've never passed options or anything, just use targets for the makefile you provide.

**Comment by gares** [comment]
I'm on f902a4939ccdd59e7d178fd938fe4c59da81d68c

**Comment by ejgallego** [comment]
I cannot reproduce, are you sure you are not in a dirty build tree? What does `ls -l config` say?

`coq_config.ml` is special, as Dune will respect a user-provided one.

**Comment by gares** [comment]
It must have been dirty than, I can't reproduce it anymore (and I did run git clean).

**Comment by gares** [comment]
OK, now I have an up to date work tree and a related problem is still there.
The directories for plugins are there, but gramlib is not.
```
COQMF_COQ_SRC_SUBDIRS=config lib clib kernel library engine pretyping interp gramlib/.pack parsing proofs tactics toplevel printing ide stm vernac plugins/btauto plugins/cc plugins/derive plugins/extraction plugins/firstorder plugins/fourier plugins/funind plugins/ltac plugins/micromega plugins/nsatz plugins/omega plugins/rtauto plugins/setoid_ring plugins/ssr plugins/ssrmatching plugins/syntax
```
I see a `gramlib/.pack` thing, but with inside the dune build these files are elsewhere:
```
./_build/default/gramlib/gramlib.cma
./_build/install/default/lib/coq/gramlib/gramlib.cma
```

**Comment by gares** [comment]
I've updated the issue. It is a different one but the title works for both, so I guess we can just leave this open

**Comment by ejgallego** [comment]
> I see a `gramlib/.pack` thing, but with inside the dune build these files are elsewhere:

Yes that's the problem I was referring to before, will cherry pick from #8729 , but indeed Coq Makefile should use findlib to locate object files, depending on the layout is not a good idea.

By the way these are two totally separated issues so you should have opened a new, one, now the title is incorrect and the history a bit messy.

**Comment by gares** [comment]
I confirm that removing the `.pack` solves the problem
