### ISSUE TITLE
Micromega cannot be used independently from tactics anymore

### ISSUE THREAD

**Issue by ckeller** [coq/coq#9749]
#### Description of the problem

I (in SMTCoq) use Micromega at the OCaml level independently from tactics. In particular, I use the function `dump_proof_term`.
This is not possible anymore (without copy-paste) since coq_micromega.mli now exposes only the tactics. It would be nice to expose also a bunch of functions that allow one to use it independently from tactics.
In addition, I am also using the function `tauto_lia` which has been removed also from coq_micromega.ml.

#### Coq Version

Since Coq-8.9

**Comment by ejgallego** [comment]
cc: @fajb ?

**Comment by Zimmi48** [comment]
It would be good to add SMTCoq to Coq's CI (whenever possible) to avoid encountering this kind of issues (removing of APIs that we don't know are used) in the future...

**Comment by fajb** [comment]
Hi @ckeller ,

I have no problem exposing dump_proof_term.
For tauto_lia, my take is that it should not  be exposed -- it is dead code.
And probably disappeared for this reason.

@ckeller , my advise is be to directly use the linear prover i,e. Certificate.lia.
It is exposed and has a clear specification i.e. it generates a checkable proof of unsatisfiability.

**Comment by ckeller** [comment]
Hi @Zimmi48 
I am clearly thinking of that, but before I have to port it to Coq-8.9 ;-)

Hi @fajb 
Thank you for your answer. I will try to use `Certificate.lia`.
When I am done, I will make a PR for exposing `dump_proof_term`.
