### ISSUE TITLE
tactic remember makes goal ill-typed

### ISSUE THREAD

**Issue by clucas26e4** [coq/coq#9750]
#### Description of the problem
In the following example, the goal is "H a p" with "p : f a".
The tactic "remember (f a) as b" changes the type of "p" to "b", which makes "H a p" ill-typed.
~~~coq
Parameter A : Type.

Parameter f : A -> A.
Parameter P : A -> Prop.
Parameter H : forall a, P (f a) -> Prop.

Lemma Foo : forall a (p : P (f a)), H a p.
  intros a p.
  remember (f a) as b.
  match goal with |- ?g => let _ := type of g in idtac end. (* fails *)
  Check (H a p). (* fails (goal is H a p) *)
~~~
#### Coq Version
8.9.0

**Comment by olaure01** [comment]
In `coq 8.4pl6` it generates an error message at `remember`:
```Error: The correctness of the conclusion relies on the body of b```
while it seems to be accepted since `coq 8.5pl3`.

**Comment by ppedrot** [comment]
Seems fixed in master.
