### ISSUE TITLE
Fix pkg-config / dune issues in Windows build (follow up on #9279)

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#9760]
This is a follow up on the pkg-config / dune discussion on PR #9279, since it gets increasingly off topic / lengthy there.

Summary of the problem: Cygwin replace pkg-config with pkgconf, so that pkg-config is now just a shell script calling pkgconf with suitable parameter for the configuration. This is especially useful for cross compilation (as we have it, MinGW on cygwin). With this change there is just one pkgconfig executable which uses different configuration files, rather than one executable for each configuration.

See <https://www.mail-archive.com/cygwin@cygwin.com/msg160233.html>

Cygwin says that they follow other distros with this move, but I didn't check this.

The issue with dune is that dune can't execute shell scripts (easily) on Windows and also simply expects an executable for pkg-config (I am pretty sure that this is the issue).

A possible solution would be to create a small executable version of the MinGW specific pkg-config shell script.

**Comment by MSoegtropIMC** [comment]
One more notes: If we agree that creating an executable pkg-config for MinGW is the right solution, this would be quick. The use of pkg-config is anyway hacked in most modules which need it, because most call the cygwin pkg-config rather than the MinGW pkg-config. For this reason I copy the right pkg-config in the local bin-special folder, which comes first in path.

I think changing dune such that it uses pkgconf directly is not an option - first this seems not yet standard on Linux and second one would have to find a way to pass the proper configuration.

**Comment by ejgallego** [comment]
> I think changing dune such that it uses pkgconf directly is not an option - first this seems not yet standard on Linux and second one would have to find a way to pass the proper configuration.

Oh, definitively I think Dune should learn about `pkgconf` if that is going to become the standard; we cannot expect users to have to hack stuff at this level just to build a package.

As for now, I dunno what to do; first step for sure is to see the detailed dune log.

**Comment by MSoegtropIMC** [comment]
> Oh, definitively I think Dune should learn about `pkgconf` if that is going to become the standard; we cannot expect users to have to hack stuff at this level just to build a package.

Good point - one can make it an alternative. Is there some documentation on cross building and dune? What is the standard way to tell dune to use MinGW pkg-config? Or does Dune not work on this level of abstraction (make doesn't, but automake/autoconf does).

> As for now, I dunno what to do; first step for sure is to see the detailed dune log.

Ok, I do a local build to get it, although I am pretty sure that the "pkg-config not found" is the issue (If you ask windows to find an executable named pkg-config, it will consult a list of executable extensions, and no extension is not in this list).

Btw.: is the cairo build new? Why did it run through at first after I did the pkg-config fix?

**Comment by avsm** [comment]
See https://github.com/ocaml/opam-repository/issues/13636 for the corresponding opam issue

**Comment by ejgallego** [comment]
Thanks @avsm !

**Comment by ejgallego** [comment]
> Is there some documentation on cross building and dune? What is the standard way to tell dune to use MinGW pkg-config? Or does Dune not work on this level of abstraction (make doesn't, but automake/autoconf does).

I am not familiar with cross-compilation but I've heard Dune does support it: https://dune.readthedocs.io/en/latest/advanced-topics.html#cross-compilation

> Btw.: is the cairo build new? Why did it run through at first after I did the pkg-config fix?

What do you mean? Cairo is indeed a dependency of lablgtk3 if that's what you mean, the build has been there since the beginning I think.

**Comment by MSoegtropIMC** [comment]
> What do you mean? Cairo is indeed a dependency of lablgtk3 if that's what you mean, the build has been there since the beginning I think.

Ah sorry. I meant the Windows 64 build went through after my pkg-config fix, but this was on master, not on the lablgtk3 branch.

So do we agree that in order to get things forward, I add a tiny C / executable wrapper to replace the shell script?

**Comment by rgrinberg** [comment]
Why C and not an OCaml executable?

Another issue could be is that the dune build might not use the pkg-config wrapper that is local to the project. But that is something that we can rectify in dune.

**Comment by MSoegtropIMC** [comment]
> Why C and not an OCaml executable?

Well something which is one or two lines (except of headers ...) in C is probably more light weight if written in C.

> Another issue could be is that the dune build might not use the pkg-config wrapper that is local to the project. But that is something that we can rectify in dune.

Not in our setup. We anyway had the issue to force the build system to use the mingw pkg-config executable. We can use the same mechanism to force the build system to use our executable.

The mechanism is btw. that we have a folder bin_special which comes first in PATH and in which we put executables or symlinks which we want to be considered first.

**Comment by ejgallego** [comment]
> Why C and not an OCaml executable?

Does configurator register the `pkg-config` wrapper as a dependency? Otherwise we may have indeed trouble building it.

**Comment by rgrinberg** [comment]
Configurator does not register any dependencies. However, the rule that invokes the configurator executable may do so.

**Comment by MSoegtropIMC** [comment]
Fixed by #9728 and #9731.
