### ISSUE TITLE
Minor regression regarding the warning message of `Extraction`

### ISSUE THREAD

**Issue by erikmd** [coq/coq#9762]
#### Description of the problem

It seems that unlike Coq 8.7.2 that was displaying the following output:
```
$ docker run --rm -it coqorg/coq:8.7.2 rlwrap coqtop
Extraction nat.
(* Error: To use extraction commands, first run [Require Extraction]. *)
```
this helpful message is not generated anymore:

```
$ docker run --rm -it coqorg/coq:8.8.2 rlwrap coqtop
Extraction nat.
(* Error: Syntax error: illegal begin of vernac. *)
```

```
$ docker run --rm -it coqorg/coq:8.9.0 rlwrap coqtop
Extraction nat.
(* Error: Syntax error: illegal begin of toplevel:vernac_toplevel. *)
```

**Comment by ejgallego** [comment]
This is on purpose, in 8.7 a special compatibility rule in the parser was kept for this purpose, however it was cleaned up in 8.8.

IMHO I'd close this as a won't fix, as the use of custom parsing rules to help with this doesn't scale.

However we could have a better parsing error recovering mechanism that would allow to plug for "hints".

**Comment by SkySkimmer** [comment]
See https://github.com/coq/coq/pull/938

**Comment by erikmd** [comment]
OK! Thanks for your feedback @ejgallego and @SkySkimmer

**Comment by ejgallego** [comment]
Thanks to you! Note that I'd support keeping this bug open as an usability issue, but indeed it is likely better just to open a PR implementing a hint table for parsing error.

**Comment by samuelgruetter** [comment]
Just ran into this, and fortunately Google led me here, but a better error message would be nice
