### ISSUE TITLE
Grammar of `Arguments ` in the doc is incomplete; you can put multiple arguments in the same delimiters

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#9765]
Note that the grammar of `Arguments ` here is still incomplete; you can put multiple arguments in the same delimiters, e.g., `Arguments map [A B] f l.`

_Originally posted by @JasonGross in https://github.com/coq/coq/pull/9757#issuecomment-472421221_

This should be fixed both for the implicits section about arguments and the scopes section, and note that for scopes, arguments can also be delimited by `(` `)`s.

Creating this issue mostly as a reminder.

**Comment by jfehrle** [comment]
I think https://github.com/coq/coq/pull/11718 covered this.  Right?

**Comment by Zimmi48** [comment]
Yep, thanks!
