### ISSUE TITLE
Timing diff scripts should support non-utf8

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#9767]
#### Description of the problem

TimeFileMaker.py does not support files which emit non-utf-8 to stdout.  See [this job log](https://gitlab.com/coq/coq/-/jobs/176113494) and the conversation in https://github.com/coq/coq/pull/9752.  It would be nice for them to support this.  This requires using bytes/`rb` rather than `r`, etc.  I might do this on my own in about two weeks, though I'd love if someone more familiar with python3 and `bytes` would do this.

#### Coq Version

8.9

**Comment by JasonGross** [comment]
@andres-erbsen or @samuelgruetter Can you point us at a particular file and commitish that prints non-utf-8 to the console, for inclusion in the test-suite, when I (or someone else) gets around to working on this?

**Comment by samuelgruetter** [comment]
[Here](https://travis-ci.com/mit-plv/bedrock2/jobs/184001043#L1195)'s a log on Travis with some non-utf8 in the console. It's from commit https://github.com/mit-plv/bedrock2/commit/9b427dc4cea9731a7869eb7c68a1de95047dd7be, file [bedrock2/src/BytedumpTest.v](https://github.com/mit-plv/bedrock2/blob/9b427dc4cea9731a7869eb7c68a1de95047dd7be/bedrock2/src/BytedumpTest.v)

**Comment by andres-erbsen** [comment]
an alternative to updating the script would be up change bedrock2 build to not output binary to console. it would probably require changing the build organization (currently we just call coq makefile). fixing the script is probably preferred anyway.

**Comment by ejgallego** [comment]
I am much afraid that I don't understand what is going on here, however we must get the `bedrock2` build fixed in the CI, please point us to what the right workaround is.

**Comment by JasonGross** [comment]
The right workaround for now is to redirect the output of `make ` to `/dev/null` for the bedrock2 ci, and cite this issue in a comment.

**Comment by andres-erbsen** [comment]
Actually, it should work just to grep out lines with high bytes...

**Comment by andres-erbsen** [comment]
`echo -ne 'ab\x80c\ndd\nas' | LANG=en_US.UTF-8 grep -a '^.*$'`
produces
`dd`
`as`

**Comment by ejgallego** [comment]
> The right workaround for now is to redirect the output of `make ` to `/dev/null` for the bedrock2 ci, and cite this issue in a comment.

That seems pretty radical, if something else fails how are we going to debug it?
