### ISSUE TITLE
Documentation missing for "change in"

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#9773]
#### Description of the problem

It turns out that `change Term in H` is a valid tactic invocation, but it is not documented at https://coq.inria.fr/refman/proof-engine/tactics.html#coq:tacn.change.

#### Coq Version

8.9.0

**Comment by RalfJung** [comment]
Hm, actually there is something about "in" in the next section in the docs, but I'd have assumed this to be mentioned in the part about `change` itself. The title "Performing computations" does not invite me to read that section when I am looking for "how to do something in the context".

**Comment by Zimmi48** [comment]
> Hm, actually there is something about "in" in the next section in the docs, but I'd have assumed this to be mentioned in the part about `change` itself. The title "Performing computations" does not invite me to read that section when I am looking for "how to do something in the context".

I don't get what you mean. `change ... in` is the last documented variant in the documentation of `change`. This is not in the next section "Performing computation" but in the section "Rewriting". I agree that the tactics chapter should be reorganized (see in particular point 1.2 in #8946: Consolidate the "Rewriting" and the "Performing computations" section in a single section on applying term transformations) but in this particular case, it seems to me that the bug should be closed as invalid.

**Comment by RalfJung** [comment]
> change ... in is the last documented variant in the documentation of change.

Indeed, you are right. I must have somehow entirely missed that *oops*
