### ISSUE TITLE
Improved treatment of non cumulative universes (sprop)

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#9782]
Strictly speaking if we generate a universe variable `u` for a type we are not allowed to later decide that it's a strict proposition, as that would require `SProp <= u`. This is worked around by pretending SProp is cumulative during pretyping. If we could handle setting `u := SProp` maybe we could do something more principled.

This is related to being able to set `u := Prop` ie https://github.com/coq/coq/pull/9444 which is probably a prerequisite.

One noncumulativity-specific issue is what to do when we have `u < v` and we want to set `u := SProp`: currently `u < v` implies `u <= v` so it would be forbidden, but if the `<=` isn't actually used by the term we're constructing we want to be able to proceed. So the question is how to differentiate between a `u < v` which is just `u+1 <= v` (`SProp+1 = Set+1` so this causes no issues) and a `u < v` which includes `u <= v`.

Additionally, currently non-cumulativity of sprop is implemented in a ad-hoc way by intercepting constraints at the boundary between the universe-specific UGraph and the general-purpose AcyclicGraph. If we solve the above issue we may also want to have AcyclicGraph understand that some nodes are noncumulative (ie `<=` on them implies `=`).

**Comment by ppedrot** [comment]
Fixed by #16903.
