### ISSUE TITLE
Documentation rebuilds from scratch after a failure

### ISSUE THREAD

**Issue by Lysxia** [coq/coq#9788]
When working on the documentation (e.g., refman) (which is slow to build), whenever an error occurs, the next time I run `make doc` (or `make refman-html`) somehow rebuilds everything from scratch, instead of only the files I touched. Is there a way to avoid this?

**Comment by SkySkimmer** [comment]
See https://github.com/sphinx-doc/sphinx/issues/6035

**Comment by Zimmi48** [comment]
Yes this is a known problem of Sphinx. @cpitclaudel reported it upstream. Note that is the build fails because of fatal warnings, there are (documented) ways of making the warnings non fatal when building (see `doc/README.md`).
