### ISSUE TITLE
Notation not printing when using a binder

### ISSUE THREAD

**Issue by beta-ziliani** [coq/coq#9802]
#### Description of the problem

The bug reported in #9662 is related; the issue has to do with having a λ-abstraction in the definition of the notation.

As a simple example, the following notation works as expected:

```
Notation "'bla' a 'ble' b 'blu'" := ((a, b)) (at level 0).
Definition test' := bla tt ble tt blu.
Print test'. (* prints `test = bla tt ble tt blu` *)
```

However, once we enclose a term under a λ, it stops working:
```
Notation "'bla' a 'ble' b 'blu'" := ((a, (fun u:unit=>b))) (at level 0).
Definition test := bla tt ble tt blu.
Print test. (* prints `test = (tt, fun _ : unit => tt)` *)
```

#### Coq Version

The bug seems to be old, lately spotted in current master (9ac5483132b42e845a0708491843693b70893eef)

**Comment by herbelin** [comment]
Hi @beta-ziliani, do you need to name the unbound `u`? The following works:
```
Notation "'bla' a 'ble' b 'blu'" := ((a, (fun _:unit=>b))) (at level 0).
Definition test := bla tt ble tt blu.
Print test.
```
Sorry for the late answer. You probably already made your own idea of the problem in the meantime.

**Comment by beta-ziliani** [comment]
I don't remember what it was... but thanks! :-) feel free to mark it as solved.
