### ISSUE TITLE
Anomaly : "not an arity"

### ISSUE THREAD

**Issue by kyoDralliam** [coq/coq#9809]
#### Description of the problem
Trying to define the (not-well typed) function `fib0` below  raise an `Error: Anomaly "Not an arity." Please report at http://coq.inria.fr/bugs/.`. If `Program Definition` is used instead of `Definition` the type error is correctly reported. Inlining the parameters `gen_op` and `gen_ty` of `FreeF` also remove the error. 

```Coq
Section FreeMonad.

  Variable S : Type.
  Variable P : S -> Type.

  Inductive FreeF A : Type :=
  | retFree : A -> FreeF A
  | opr     : forall s, (P s -> FreeF A) -> FreeF A.

End FreeMonad.

Section Fibonnacci.

  Inductive gen_op := call_op : nat -> gen_op.
  Definition gen_ty (op : gen_op) :=
    match op with
    | call_op _ => nat
    end.

  Definition fib0 (n:nat) : FreeF gen_op gen_ty nat :=
    match n  with
    | 0
    | 1 => retFree _ _ _ 1
    | S (S k) => opr _ _ _ (call_op (S k)) 
(fun r1 => opr _ _ _ (call_op k) 
(fun r0 => retFree (* _ _ _ *) (r1 + r0)))
    end.

End Fibonnacci.
```

#### Coq Version
Version 8.8.2 and master (revision `beaccf0befcc59178ca59913e63625fa42f6d186`)

Would it be related to #7645 ?

**Comment by Zimmi48** [comment]
#7645 seems to be fixed while this anomaly still exists in 8.12.
