### ISSUE TITLE
CoqIDE on gtk3 has wrong defaults for selection BG

### ISSUE THREAD

**Issue by gares** [coq/coq#9812]
In a standard gnome system (no color customization) and after wiping out the old coqide config file,
text selection has a transparent background an white text. As a result you don't see the text you are selecting. I've no idea what CoqIDE does wrong, but on gtk2 it was not the case

**Comment by ppedrot** [comment]
It seems you can tweak the `coq_style.xml` file to override these settings, but I don't know how to do this in a way that is consistent with the dynamic foreground color of the editor. The relevant stanzas to add to the style file are
```
<style name="selection" foreground="..." background="..." />
<style name="selection-unfocused" foreground="..." background="..." />
```

**Comment by ejgallego** [comment]
Indeed I saw that but I thought it was an effect of my highly non standard gtk color scheme [I have some problem with apps from time to time]

**Comment by maximedenes** [comment]
This is marked as a beta blocker, but there's no assignee. Please assign within a few days, or we'll have to remove the blocker status.

**Comment by ppedrot** [comment]
I am assigning it to myself, because it really is a blocker. I think I'll go for the easy workaround, by tweaking the style file, even though it's going to be problematic on alternative color scheme, otherwise I don't really how to fix that.

**Comment by ppedrot** [comment]
After scanning the GTK documentation, it looks like we're missing the right API for a portable fix, so that I'll be forced to hack the style file indeed. Is that non-generic workaround considered to be enough?

**Comment by ppedrot** [comment]
News from the front: this is even more complicated than I thought originally. I am starting to wonder whether the sanest solution wouldn't be not to allow the user to change the background colour of the text editor.

**Comment by ejgallego** [comment]
How come our use of the sourceview widget is different from what (for example) `gEdit` and friends do?

**Comment by ppedrot** [comment]
We don't have the right API, we should be using CSS styling instead of bluntly modifying the widget colour properties, which doesn't play well with the new GTK3 model.

**Comment by ejgallego** [comment]
> We don't have the right API, we should be using CSS styling instead of bluntly modifying the widget colour properties, which doesn't play well with the new GTK3 model.

The API is missing from where, from `lablgtk3` ?

**Comment by ppedrot** [comment]
Indeed.

**Comment by ejgallego** [comment]
I see, maybe we should open a bug there?

Note that hacking on labgtk3 is quite pleasant these days for merlin + Dune users, so maybe we could add it on time.
