### ISSUE TITLE
feature request: allow assigning Set to a global universe variable

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9813]
#### Description of the problem

```coq
Universe u.
Constraint u = Set.
(* Error: Universe inconsistency. *)
```

It would be nice if this worked, so that libraries that use global universe variables for definitions that could also have been written as universe-polymorphic can be used with standard library types that live in `Set`. (maybe the use of global universe variables is by accident, for performance reasons (e.g. #9507), or as a workaround for undesired behavior...). As refactoring universe management code seems to be on the table (e.g. #9444), I am putting this wish out here.

#### Coq Version

8.9.0

**Comment by SkySkimmer** [comment]
Wontfix IMO
