### ISSUE TITLE
Support `apply in *` and `apply in H1, H2`.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#9816]
#### Description of the problem

It is quite annoying that the `apply in *` and `apply in H1, H2` syntax are not supported while the same syntax is supported for `rewrite`, `unfold`, etc.

#### Coq Version

8.9.0

**Comment by gares** [comment]
The LHS of the rewrite rule can occur in many places. Not so sure about the premise of a lemma. Which use case do you have in mind?

**Comment by Zimmi48** [comment]
Simply not having to repeat a line when you do have several premises on which you want to apply uniformly a given lemma. And having a consistent syntax. I did hit this problem several times in the process of preparing the Coq project for my students this year, and I also had a student ask me exactly how to do this yesterday during a practice session, so that's what prompted me to record the enhancement request.

Note that the semantics of `in *` should be the same as for `rewrite`, i.e. if it doesn't work on a particular hypothesis, no problem as long as it did work on others. There might still be a tricky point in the sense that `apply ... in` and `apply` are two quite different tactics whereas `rewrite` and `unfold` are quite uniform when used in the goal or in the context. So what I'm more interested in having is `apply in * |-`. But having `in H1, H2` would already be very good.

**Comment by gares** [comment]
I m curious since it never happened to me. Can I see the exercise?

**Comment by Zimmi48** [comment]
I didn't look precisely at what the student was doing when he asked the question. However, I can extract two examples from my solution to the project (but I'd rather not show the solution in full :wink:).

My context contains:
```
  Hin__n' : mem n (vertices (of_cotree t2)) <> true
  Hin__m' : mem m (vertices (of_cotree t2)) <> true
```

and I'm doing the following:

```
  apply not_true_is_false in Hin__n'.
  apply not_true_is_false in Hin__m'.
```

Later, another example has the following in the context:

```
  Hin__n : Cotree.In n t1
  Hin__m : Cotree.In m t1
```

and I'm doing the following:

```
      all: apply In_complement in Hin__n as ?.
      all: apply In_complement in Hin__m as ?.
```

which gives me:

```
  Hin__n : Cotree.In n t1
  H0 : Cotree.In n (complement_cotree t1)
  Hin__m : Cotree.In m t1
  H1 : Cotree.In m (complement_cotree t1)
```

That's the only two examples I have. I might have had other ones who disappeared after refactorings.

**Comment by gares** [comment]
Thanks

**Comment by herbelin** [comment]
> It is quite annoying that the `apply in *` and `apply in H1, H2` syntax are not supported while the same syntax is supported for rewrite, unfold, etc.

What would be your general syntax? Just `* | {+, hyp }`?

By the way, I have mixed feelings regarding the `,`-separated syntax for hypotheses, which:
- is used inconsistently (e.g. `unfold c, d` vs `fold t u`)
- is sometimes causing associativity headaches, for instance in  `destruct t, u in h, k |- *` where we allow `in` only once, because otherwise we wouldn't know in `destruct x in h, k` if it is about destructing `x` in both `h` and `k` or destructing `x` in `h`, then destructing `k` everywhere.

**Comment by herbelin** [comment]
I made a first draft at #12246.

Some first questions:
- Isn't `apply c in *` too risky, finding unifications which the user was not expecting?
- How to manage the `as pat` clause? I.e. in `apply c in H1, H2 as pat`:
  - should we specially forbid the use of fixed introduction names (since it would mechanically lead to asking two hypotheses to have the same name)
  - or should we just let the users experiment by themselves that names of the form `?H` have to be given
  - or should we have `in H1 as pat1, H2 as pat2`? But then, how to interpret `in * as pat`?

**Comment by olaure01** [comment]
@herbelin 
- the `apply c in *` case is not clear to me
- concerning `apply c in H1, H2`, I would support `apply c in H1 as pat1, H2 as pat2`

**Comment by herbelin** [comment]
>     * the `apply c in *` case is not clear to me
> 
>     * concerning `apply c in H1, H2`, I would support `apply c in H1 as pat1, H2 as pat2`

This looks reasonable to me. @Zimmi48, would you be ok with this or do you see a use case for the `*` variant?

**Comment by Zimmi48** [comment]
I'm OK with not supporting the `*` variant. However, I'm concerned about syntax inflation and would very much like if it was possible to share the syntax for the `in` clause with the tactics that already support it...

**Comment by herbelin** [comment]
Indeed, that'd be better to unify the syntax. Maybe could we then keep the `*` clause but do not allow that it supports the `as` clause?

Alternatively, we could explain the difference with other uses of `in` by saying that `apply` is about a whole statement while the other usages are about occurrences in a statement.

I realize in passing that `change` accepts a `*` clause... and it fails if not all hypotheses are convertible (making it rather useless).

**Comment by Zimmi48** [comment]
A possibility would be to have *two* `in` syntax. Just two would be already more consistent than "a lot". And clearly document the difference between the two kinds of tactics (acts on an occurrence vs acts on a whole statement).

**Comment by Zimmi48** [comment]
Maybe we could rename `in` into `on` when it acts on the whole statement...

**Comment by herbelin** [comment]
> A possibility would be to have two in syntax. And clearly document the difference between the two kinds of tactics.

Indeed. That'll be a nice way to explain.

Continuing with `change`, I see that `change type in H1, H2` and `change type in *` is not documented. Note that `change ... with ...` would be different since it is now about occurrences.

> Maybe we could rename `in` into `on` when it acts on the whole statement...

Why not!
