### ISSUE TITLE
"make sphinx" fails on Windows upon starting coqtop

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#9818]
#### Description of the problem

`make sphinx` fails on Windows with the message from Python/expect `Cannot find a physical path bound to logical path matching suffix\r\r\n<> and prefix Coq.\r\r\n\r\r\n` upon the first invocation of coqtop.

Removing the COQLIB on this line in Makefile.doc fixes the problem on Windows.

```
SPHINXENV:=COQBIN="$(CURDIR)/bin/" COQLIB="$(CURDIR)"
```

Here's what you get running coqtop with COQLIB set by hand:
```
$ pwd
/cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq

$ COQLIB="/cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq"

$ export COQLIB

$ bin/coqtop.exe
Welcome to Coq 8.10+alpha (March 2019)
Warning:
Cannot open /cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq/theories
[cannot-open-path,filesystem]
Warning:
Cannot open /cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq/plugins
[cannot-open-path,filesystem]
Error: Cannot find a physical path bound to logical path matching suffix '<>' and prefix Coq.
```

#### Coq Version 8.9+

**Comment by Zimmi48** [comment]
Interesting. I'm wondering if it could have any relation to #9799. Did you check if this bug was already present in V8.9.0?

**Comment by ejgallego** [comment]
I think the culprit look legit, quoting in make this way doesn't work for windows I think. Does `make -f Makefile.dune refman-html` does work?

**Comment by jfehrle** [comment]
The problem is that coqtop expects the path in windows format, not in cygwin format:

```
$ cygpath -w $COQLIB
C:\Users\Jim.DESKTOP-MMPNVGH\Documents\coqSource\coq

$ COQLIB=`cygpath -w $COQLIB`

$ echo $COQLIB
C:\Users\Jim.DESKTOP-MMPNVGH\Documents\coqSource\coq

$ bin/coqtop.exe
Welcome to Coq DESKTOP-MMPNVGH:/cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq,print_gram2 (5c5a9d97dd743d1337d2a48e4f6b8b48e5c37d5b)

Coq < Quit.
```

Using / anywhere in the Windows path causes a failure, e.g. `COQLIB=C:\Users\Jim.DESKTOP-MMPNVGH\Documents\coqSource/coq` will cause a failure.  That's seems likely related to the problem in #9799.  Seems like we should have code that will convert such filenames into the right format as this seems like something users will stumble into frequently.

**Comment by jfehrle** [comment]
Correction: As @MSoegtropIMC points out in https://github.com/coq/coq/issues/9799, Windows does accept `/` in pathnames, though in the DOS shell, they typically must be quoted.  Windows certainly doesn't know how to handle `/cygdrive/c/`.
