### ISSUE TITLE
unimath vs UniMath makes create-overlay.sh fail   

### ISSUE THREAD

**Issue by Matafou** [coq/coq#9845]
#### Description of the problem

Reproduce by doing this:
```
./dev/tools/create_overlays.sh Matafou 8347 unimath
```
After compilation (takes a while) the script fails because the directory created is `_build_ci/UniMath` instead of `_build_ci/unimath`.

Solution: either have the name of an "external projects" always match its git name, or make the infrastructure able to compute the name of the directory.

The problem comes from:
[this file](https://github.com/coq/coq/blob/master/dev/tools/create_overlays.sh) at line 69:
    

```
setup_contrib_git $_CONTRIB_DIR $_CONTRIB_GITPUSHURL
```
where `$_CONTRIB_DIR` is incorrect.

#### Coq Version
master

**Comment by ejgallego** [comment]
We are indeed doing this:

> have the name of an "external projects" always match its git name

we have fixed quite a few but not UniMath, please submit a PR.

**Comment by Matafou** [comment]
which way should I change the names? should I change unimath to UniMath or the reverse?

**Comment by ejgallego** [comment]
The name of the ci stuff should match the git_download call, that is to say, it should become ci-UniMath.

This is an extremely annoying limitation, so if any bash expert knows how to improve please do so.

**Comment by SkySkimmer** [comment]
We can change the git_download call instead, I'll make a PR.
