### ISSUE TITLE
_CoqProject: -R breaks compilation

### ISSUE THREAD

**Issue by liyishuai** [coq/coq#9846]
#### Description of the problem

In herbelin/reduction-effects#2, I could build the plugin without `-R` option in `_CoqProject`, which installs into `Top`. However, if I add `-R` back (in [dir](//github.com/liyishuai/reduction-effects/tree/dir) branch), the generated Makefile first complains that ML module was not found:
> COQDEP redeffect_plugin.mlpack
CAMLDEP -pp redeffect.ml4
COQDEP PrintingEffect.v
*** Warning: in file PrintingEffect.v, declared ML module redeffect_plugin has not been found!
*** Warning: in file PrintingEffect.v, declared ML module redeffect_plugin has not been found!
COQC PrintingEffect.v
File "./PrintingEffect.v", line 6, characters 0-37:
Error:
File not found on loadpath : redeffect_plugin.cmxs
Loadpath: /foo/reduction-effects:/bar...

I managed to generate `redeffect_plugin.cmxs` with `make -k` (failed with same message), and then tried to `make` again. This time it shows something different:
> COQC PrintingEffect.v
File "./PrintingEffect.v", line 18, characters 8-16:
Error:
Syntax error: 'Equivalent' 'Keys' expected after 'Declare' (in [vernac:command]).

It seemed that `redeffect_plugin.cmxs` was somehow ignored. Is this behavior expected?

Update: both `-Q` and `-R` broke the compilation.

#### Coq Version

8.7.2 and 8.8.2

**Comment by ejgallego** [comment]
You are missing the `-I` declaration; this is not a bug per-se, but more of an usability issue.

**Comment by ejgallego** [comment]
See for example https://github.com/ppedrot/ltac2/blob/master/_CoqProject
