### ISSUE TITLE
Classes/Morphisms.v doesn't work in CoqIDE

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#9862]
In current master, load `Classes/Morphisms.v` in CoqIDE and click "go to end".

The:
```
(* -*- coding: utf-8; coq-prog-args: ("-coqlib" "../.." "-R" ".." "Coq" "-top" "Coq.Classes.Morphisms") -*- *)
```
line is not executed, and if Coq wasn't compiled with `-local` the setting of the library namespace will be incorrect making this test fail:
```
let init_setoid () =
  if is_dirpath_prefix_of classes_dirpath (Lib.cwd ()) then ()
  else Coqlib.check_required_library ["Coq";"Setoids";"Setoid"]
```

**Comment by SkySkimmer** [comment]
I can't reproduce.

**Comment by ejgallego** [comment]
Are you sure you are running with the default options on Linux [that is, CoqIDE spawning workers].

**Comment by ejgallego** [comment]
Umm, maybe indeed I had a problem in my setup, wait a sec.

**Comment by ejgallego** [comment]
I closed inadvertently but indeed I cannot reproduce now; I was looking for an example that @maximedenes had about a file having this kind of problems. Maybe he recalls.

**Comment by ejgallego** [comment]
Umm, that's due to the header not applying in my build env:
```
(* -*- coding: utf-8; coq-prog-args: ("-coqlib" "../.." "-R" ".." "Coq" "-top" "Coq.Classes.Morphisms") -*- *)
```
then, this doesn't trigger properly:
```
let init_setoid () =
  if is_dirpath_prefix_of classes_dirpath (Lib.cwd ()) then ()
  else Coqlib.check_required_library ["Coq";"Setoids";"Setoid"]
```
so indeed this is a bug I think. In the default build env CoqIDE gets the paths by setting the local flag, but otherwise the things are broken.

**Comment by Zimmi48** [comment]
FTR this header is Emacs-specific. It was never intended that CoqIDE would parse it. This kind of thing is usually solved with `_CoqProject` options for CoqIDE, but I hope that Dune will provide a cleaner solution.

IIRC @JasonGross was the one to add these headers.

**Comment by SkySkimmer** [comment]
Maybe we should move the global lookups in rewrite to Coqlib, and inline the error to those lookups so it only triggers when needed (the goal of the init_setoid is to provide a recommendation "please require Setoids").
ie something like
~~~ocaml
let find_setoid_ref s = try Coqlib.find_ref s with _ -> Coqlib.check_required_library ["Coq";"Setoids";"Setoid"]; assert false
~~~
