### ISSUE TITLE
Remove Load?

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#9865]
The purpose of the Load command is not clear to me, so I'm making this issue to ask if people are interested in removing it.

A CI run https://gitlab.com/SkySkimmer/coq/pipelines/54070918 shows that in the developments we track Load is used by compcert and corn (ignore the failing plugins, they're because of ml API desynch).
- compcert is because of https://github.com/AbsInt/CompCert/blob/fc504771df607f86c6d6117902c88dfacc95393b/extraction/extraction.v#L150 (I think that's the only Load in compcert). I don't fully understand what it does, could it be done as a Require Import or otherwise handled by the build system? cc @xavierleroy 
- corn is because of https://github.com/coq-community/corn/blob/bfc495cd2bfa2af9128ee5c08228cad9f614824b/tactics/FieldReflection.v#L192 and a few identical loads in other files. It loads a file containing a bunch of `Opaque` directives. This can't be done as an Import because `Global Opaque` is Require time (load_function = cache_strategy in redexpr) (default/Local has no effect past its origin module). Require-time effects are generally considered a mistake so maybe we can just change it to import-time? See also https://github.com/coq/coq/pull/9864

**Comment by ejgallego** [comment]
I am neutral on it; in the past it was worse, nowadays I think we can live with the current semantics.

**Comment by xavierleroy** [comment]
I don't know what `Load` does, exactly, but CompCert uses it as if it were textual inclusion, in conjunction with the `-load-vernac-source` option to `coqtop`.  

There is a machine-independent file `extraction.v` that contains only directives and is run with `coqtop -load-vernac-source`.  It needs to search in the path and to load a machine-dependent file `extractionMachdep.v`, which also contains only directives.  

It would feel strange to compile `extractionMachdep.v` just so that it can be `Require Import`-ed in `extraction.v`.

**Comment by JasonGross** [comment]
I think another use-case for `Load` via `-l` is if you want to have a global options file which is loaded into every other file; you should probably not then list it in `_CoqProject` (the compilation will be circular), and also it would be nice to not need to copy the coqc invocation to compile it before loading it.

**Comment by Zimmi48** [comment]
@JasonGross This doesn't look like a use case that we should keep supporting, instead we should provide proper support for project-wide options (see #9295).

**Comment by andres-erbsen** [comment]
Is there an alternative (to `Load`) for factoring out `Local Notation`, `Local Coercion`, `Local Hint`, etc into a conceptual unit?

**Comment by SkySkimmer** [comment]
-l and the Load command go through different code paths AFAICT, I would say -l is not relevant to this issue.

>Is there an alternative (to Load) for factoring out Local Notation, Local Coercion, Local Hint, etc into a conceptual unit?

A regular module should work fine for the ones which act at Import time, the ones which act at Require time or can't survive modules should be considered bugs (although it may take time to fix them due to backward compat concerns)
For instance Coercion used to be require-time but that behaviour is deprecated in 8.9 and it will be import-time only in 8.10.

**Comment by xavierleroy** [comment]
> This doesn't look like a use case that we should keep supporting

On what authority do you say so?  @JasonGross 's use case sounds pretty reasonable to me.

**Comment by Zimmi48** [comment]
Thanks for splitting my sentence precisely at the point where it changes its meaning @xavierleroy :wink:

**Comment by ejgallego** [comment]
> -l and the Load command go through different code paths AFAICT, I would say -l is not relevant to this issue.

Actually `Load` has slightly better semantics than `-l` [for example think of a LSP server], and even if they don't use the exact same code now unification could happen at some point [in the past they were unified I think but Load got buggy due to the STM or something]

**Comment by maximedenes** [comment]
> The purpose of the Load command is not clear to me, so I'm making this issue to ask if people are interested in removing it.

`Load` can be seen as an atomic textual inclusion. Is there anything wrong about that?

> Thanks for splitting my sentence precisely at the point where this changes its meaning

@Zimmi48 To be fair, I think your sentence was a bit unclear. I guess you meant: "we should keep supporting this use case, but as project-wide options".

**Comment by SkySkimmer** [comment]
Looks like Load is still useful and won't get removed today.
