### ISSUE TITLE
Cleanup duplication of Flocq in CompCert and of CompCert in VST

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#9886]
Currently CompCert uses its own copy of Flocq (CompCert has been recently updated to use the latest version of Flocq) and VST uses its own version of CompCert (and yet another copy of Flocq). This has the effect that tools like CoqInterval or Gappa cannot really be used to discharge numeric proof goals in verification of C code, which somehow impedes one of the main advantages of Coq.

The goal is to cleanup this, so that one can showcase verification of numeric C code.

I labeled this as feature since it is a substantial feature to be able to do this.

**Comment by ejgallego** [comment]
How is this a bug in Coq and not in CompCert / VST?

**Comment by MSoegtropIMC** [comment]
One can configure VST to use an external CompCert - this is currently not the default. I want to switch this. For CompCert switching to an external Flocq requires a minor patch to module include statements, which was agreed to do in Coq (for the Windows installer build).

But I mostly opened the issue here to state that I want to see in 8.10beta a C toolchain which works together with the great floating point und numerics tools from INRIA. It is simply not nice to say "yes in principle you can do all these things efficiently with one tool, but in practice it doesn't work cause of - well what?"

**Comment by Zimmi48** [comment]
> How is this a bug in Coq and not in CompCert / VST?

That's not a "bug" for projects to want vendored dependencies. However, until recently, there was no good support for this and thus this leads to issues like using a different namespace and such, and not supporting building with installed versions. But Dune should help here. See also the discussion in #9792.

**Comment by ejgallego** [comment]
Moving from vendored to non-vendored libs is tricky even in the OCaml case tho; it's true that Dune's "1.0" Coq support should help quite a bit vendoring libs, [provided that the developments we are talking about are willing to adopt Dune as a build system which somehow I am very skeptical of it happening], however it won't reach so far as to interpret external Coq dependencies until "2.0".

Metadata for installed Coq libraries is not enough to do this reliably IMO; but well, we maybe figure out a way; but I think we'll need a different install format for that.

**Comment by MSoegtropIMC** [comment]
Regardless of the technicalities on how to achieve this goal, I hope we can agree on that it is a desirable goal to have a linked chain from Gappa and CoqInterval via Flocq to VST and CompCert rather than independent pieces of chains. As I said, I think this is a very good show case for the strength of Coq, and it is not nice at all that this show case doesn't work for (in my possibly naive view - I will see) minor technical reasons.

**Comment by Zimmi48** [comment]
@MSoegtropIMC Sorry for the off-topic. I was answering Emilio on the question of whose bug it is. But I think that your practical approach is what will work best in a first phase.

**Comment by vbgl** [comment]
Ping @MSoegtropIMC Will this be addressed by the next β?

**Comment by MSoegtropIMC** [comment]
I would love to but I really have issues fixing the remaining bugs in CoqIDE on Windows. I would say that CoqIDE is much higher prio. It is the same for teh other 8.10 issues / PRs assigned to me. In the end I had to invest a lot of time in setting up a proper OCaml development environment on Windows (this is still ongoing but should be fixed soon). The comes fixing the CoqIDE bug and then ...

**Comment by MSoegtropIMC** [comment]
This is deprecated with Coq Platform (and anyway fixed in CompCert and VST).

**Comment by MSoegtropIMC** [comment]
The PR which removed the old build scripts and switched to Coq Platform was (#13598).
