### ISSUE TITLE
Print Ltac missing parentheses change meaning

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9894]
#### Description of the problem

```coq
Set Printing All.
Ltac misprinted := assert_fails (idtac; fail).
Print misprinted.
(* Ltac Top.misprinted := assert_fails idtac; fail *) (* THIS IS WRONG *)
```

I don't know how to make an output test, so the wrong printing is just shown above. The difference is semantically significant:

```coq
Goal True.
  assert_succeeds (assert_fails (idtac; fail)).
  assert_fails    (assert_fails idtac; fail).
Abort.
```

#### Coq Version

8.9.0

**Comment by JasonGross** [comment]
See also #9716 , #9715 , #6613, #5436 , #5169 , #3079
Possible duplicate of #3079

**Comment by ppedrot** [comment]
Indeed, that's a duplicate, the common reason is that the printer doesn't respect the argument level. Let's close this one.

Duplicate of #3079
