### ISSUE TITLE
Pin addon/plugin version for 8.9.1

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#9907]
The addon/plugin versions for 8.9 have (mostly) not been updated since Sep 2018.

Check what is the latest versions which builds (or otherwise "best" version) for all plugins/addons delivered in the Windows installer and pin the versions in ci-basic-overlay.sh accordingly.

**Comment by Zimmi48** [comment]
PR was merged. (@MSoegtropIMC We have to close most of your issue by hand because you don't take advantage of GitHub's closing feature: you should write "Close #9907" instead of "Issue #9907" in your commit messages.)
