### ISSUE TITLE
cases where lia fails but omega succeeds in bedrock2

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#9920]
By cloning the bedrock2 repo recursively, checking out [this commit](https://github.com/mit-plv/bedrock2/commit/0bf7d31a36b2d1a94a0d5fe163f0c3245b01bfe1), and running `make`, and grepping the build log for the keyword `BAD_LIA`, one can look for cases where `omega` succeeds but `lia` fails.

At the moment (coq master 424c1973e96dfbf3b2e3245d735853ffa9600373), there are 11 such cases, and I'm assuming they're due to one of https://github.com/coq/coq/issues/9892, https://github.com/coq/coq/issues/9512, https://github.com/coq/coq/issues/9268, but I'm just posting this here to suggest a way to test proposed new fixes for `lia`.

**Comment by pi8027** [comment]
@samuelgruetter I have attempted to reproduce this issue with Coq (`master`), bedrock2 (`master`), and coqutil (`master` + cherry-picking `lia_performance`) but I don't see any `BAD_LIA`. I guess that it is disappeared thanks to #9856. Would you update the status of this issue?

**Comment by samuelgruetter** [comment]
I re-ran the experiment (see [here](https://github.com/coq/coq/issues/9921#issuecomment-590023208) for more details) and can confirm that there are no more goals where lia fails but omega succeeds, so we can close this.
