### ISSUE TITLE
In bedrock2, lia is 2x slower than omega in "regular" cases (but faster in outliers)

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#9921]
In bedrock2, I made aliases `bomega` and `blia` for `omega` and `lia`, so that we can redefine these aliases to investigate whether we could replace `omega` by `lia` and what the performance changes would be.

In [this commit](https://github.com/mit-plv/bedrock2/commit/0bf7d31a36b2d1a94a0d5fe163f0c3245b01bfe1) in bedrock2, I defined both of `bomega` and `blia` to be the same tactic which runs both `omega` and `lia`, and prints their running times.

In this build, there are 90916 invocations of `omega` and `lia`, and except for three extreme cases in `bedrock2/bedrock2/src/Examples/bsearch.v`, all `omega` invocations run in less than 1 second, and all `lia` invocations run in less than 10 seconds.

The sum of all invocation times for omega is 5x lower than for lia (317s vs 1782s).
If we ignore the three extreme cases, omega is 64x faster than omega (27.2s vs 1744.5s).
And if we add 1ms for each invocation which was reported as 0ms to account for lack of fine granularity, omega is still 16x faster (again with 3 extreme cases ignored, 106s vs 1745s).

So this means that in this build, almost half an hour of computation time is spent in `lia`, whereas a build without any instrumentation only takes 25min.

So before [replacing omega by lia](https://github.com/coq/coq/pull/7878), it would be important to fix these performance problems.

It seems that the performance problems are not related to linear arithmetic, but rather, to preprocessing performance problems, eg https://github.com/coq/coq/issues/9919.

As the following graph illustrates, omega and lia running times do not seem to be linearly correlated:

![omega-vs-lia-master1](https://user-images.githubusercontent.com/2394355/55657313-dc70d000-57c7-11e9-97a2-b3b70e78d64c.png)

And in this graph, I sorted all invocations by running time (independently for lia and omega). The area below the curve corresponds to the total running time, and we see that lia performs worse both on "small" goals and on "large" goals:

![ranked_invocationtimes_master1](https://user-images.githubusercontent.com/2394355/55657332-e7c3fb80-57c7-11e9-96b9-23b2f85c1e94.png)

Coq version: master 424c1973e96dfbf3b2e3245d735853ffa9600373

**Comment by fajb** [comment]
@samuelgruetter , interesting figures. Could you confirm that zify is not the only culprit?
If you could extract a few problematic instances, that would help finding the origin of the problem.

**Comment by samuelgruetter** [comment]
It seems zify is the main culprit, but to further analyze, you'd have to try different ways of logging things to extract the information you're interested in. One thing to do is to run `COQMF_ARGS='-arg "-profile-ltac"' make` so that an Ltac profile is displayed for each file, another idea would be to modify `compare_omega_lia_timed`(https://github.com/mit-plv/coqutil/blob/c96058fc719c87c4fce16cac42633c63753efc3d/src/Z/Lia.v#L52) so that instead of doing `time "lia" lia`, it would do the right-hand side of `lia` and time each command separately, and write a script which searches for interesting ratios between the time taken by `zify` and the total time, for instance.

**Comment by samuelgruetter** [comment]
[Here](https://github.com/mit-plv/bedrock2/blob/f77359778598c8bfa86e9d74dbb3c089fb1e5b38/bedrock2/src/Examples/ARPResponderProofs.v#L86-L88)'s an example where `lia` is ~20x slower than omega.

**Comment by fajb** [comment]
I looked at your example and can't see anything obviously wrong.
The proof term is small and is using the right hypotheses.
With my experimental version of zify, I notice *only* a  ~3.5x.
Also, using `abstract` and `native_cast_no_check`, I get results similar to omega. 
``
  Ltac zchecker_abstract checker :=  (Lia.zchange checker ; native_cast_no_check (eq_refl true)).

  Ltac zchecker_aext := zchecker_abstract ZMicromega.ZTautoCheckerExt_sound.

 Ltac fast_lia := abstract (Lia.preprocess ; xlia zchecker_aext).
``
So, maybe, there is hope for a decent efficiency even for small goals.

**Comment by andres-erbsen** [comment]
We used to use `abstract` in a way rather similar to this, but we then identified it a as a source of anomalies and stopped (see #9037, #9146).

**Comment by fajb** [comment]
Hi @samuelgruetter  

Could you redo your experiments using PR #9856 and tell me how it now compares with omega ?
PR #9856 re-implements zify and also makes a few optimisations to lia.

**Comment by samuelgruetter** [comment]
It looks better!

I reran the performance tests and got the following:

Total omega time: 309.4s, total lia time: 60.3s, so one would be tempted to believe that lia is now 5x faster than omega.
*However*, this is a very skewed picture, because omega spends ~280s in three pathological cases, while lia solves these much faster (and there are >90000 cases in total).

Now if we drop the three pathological cases, the picture looks different:

Total omega time: 28.1s
Total lia time: 59.9s

So I would say

- lia is still ~2x slower than omega and could/should be improved to match or exceed omega
- But in a 35min build, it's not extremely important whether we spend 30s or 1min to solve the linear arithmetic goals, so I would not say anymore that the situation is "alarming"

Here's a case where lia is ~8x slower than omega: https://github.com/mit-plv/coqutil/commit/53862aabf960757528908052810cc7278de9698d

If you want to continue working on improving lia performance, I would find it important that you can run this test yourself to get immediate feedback on a change, rather than having to wait for my slow round-trip time (I'm currently in an internship which is not Coq-related).

So I tried hard to make this process reproducible, I hope it should work on any linux-like system with bash. Please let me know if the following instructions allow you to run this test and obtain similar numbers:

```
opam switch create OnlyOcaml4.06.1 4.06.1
eval $(opam env)
opam install num ocamlfind

mkdir lia
cd lia

git clone -b zify --depth=1 git@github.com:fajb/coq.git
cd coq/
./configure -local
make
export PATH=`pwd`/bin:$PATH
cd ..

git clone -b lia_performance --recursive git@github.com:mit-plv/bedrock2.git
cd bedrock2/
time make 2>&1 | tee log1.txt
iconv -t UTF-8 -c -o log1conv.txt log1.txt
python3 analyze.py log1conv.txt
```

**Comment by fajb** [comment]
@samuelgruetter thanks for the update and your time.

**Comment by samuelgruetter** [comment]
I re-ran the omega vs lia performance experiment with Coq 8.11.0 and the latest bedrock2 (see [here](https://github.com/mit-plv/bedrock2/blob/f4e9dcff30187b47d0082dbe54da95d2c063305a/analyze_lia_vs_omega.py) for how).

The summary is basically the same as [back in June](https://github.com/coq/coq/issues/9921#issuecomment-500176595):
* If we only consider the goals on which neither omega nor lia goes crazy (which rare enough that we can deal with it), omega spends a total of 28s on them, while lia spends a total of 60s on them.
* There are goals where omega is faster, and other goals where lia is faster, and overall, on the workload created by bedrock2, omega is about 2x faster than lia.
* The total time spent in omega or lia is <= 1 min, while the total build time is >1 hour.
* There are no goals that omega solves, but lia does not solve.
* If omega was removed from Coq, it would not be a problem for bedrock2.

So the only reason to keep this issue open is because it could help improve lia's performance, but it's not a blocker any more.

**Comment by ejgallego** [comment]
Thanks for the information @samuelgruetter

**Comment by Blaisorblade** [comment]
Since `omega` was removed, it's really up to @fajb whether this issue is still helpful, but it seems a rather generic (and not quite actionable) "make lia faster": so I'm tentatively closing it. Please reopen if you disagree.
