### ISSUE TITLE
coqpp --help: Fatal error

### ISSUE THREAD

**Issue by silene** [coq/coq#9932]
#### Description of the problem

```
$ coqpp --help
Fatal error: exception Invalid_argument("Filename.chop_extension")
```

#### Coq Version

8.10

**Comment by gares** [comment]
`coqpp` seems an "internal" utility (called by coq_makefile or dune), so I think the issue is minor.
Why did you try to invoke it by hand?

**Comment by silene** [comment]
Because, in 8.10, as a plugin writer, you have to use it: "In an effort to reduce dependency on camlp5, the use of several grammar macros is discouraged. Coq is now shipped with its own preprocessor, called coqpp, which serves the same purpose as camlp5."

**Comment by gares** [comment]
I see, because you use no dune and not coq_makefile.
Then I guess we need a proper manpage

**Comment by silene** [comment]
It is always the same issue: I need to support several versions of Coq, including older ones. Dune might help in the future, but for now, I am stuck trying to invoke Coq tools by hand.
