### ISSUE TITLE
Nix job failing on pyrolyse.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#9934]
Recently observed many occurrences:

- https://gitlab.com/coq/coq/-/jobs/192693812
- https://gitlab.com/coq/coq/-/jobs/192968888
- https://gitlab.com/coq/coq/-/jobs/192559300

Every time the log contains:

```
error: cloning builder process: Operation not permitted
error: unable to start build process
```

**Comment by ejgallego** [comment]
This seems related to sandboxing and kernel configuration; note all the failures are on pyrolise so you should see what's changed there.

**Comment by ejgallego** [comment]
I wouldn't be surprised if some internal table of disk space got full.

**Comment by ejgallego** [comment]
I suggest renaming to "Jobs on pyrolise cannot execute Nix sandboxing"

**Comment by Zimmi48** [comment]
Either this was a temporary problem, or this is a non-deterministic one: this job on pyrolyse suceeded https://gitlab.com/coq/coq/-/jobs/193983580.

**Comment by ejgallego** [comment]
I dunno, maybe somebody or some script performed maintenance? Failure seems gone for now it seems.

**Comment by Zimmi48** [comment]
Let's close for now and reopen if we see it again.
