### ISSUE TITLE
Anomaly: universe undefined

### ISSUE THREAD

**Issue by cl-wood** [coq/coq#9950]
#### Description of the problem
Anomaly "Universe Top.40279 undefined."
Please report at http://coq.inria.fr/bugs/.

1. Checkout https://github.com/cl-wood/bedrock2/tree/coq_anomaly
2. make bedrock2
3. Fails at https://github.com/cl-wood/bedrock2/blob/coq_anomaly/bedrock2/src/Examples/lightbulb.v#L220

#### Coq Version

The Coq Proof Assistant, version 8.9.0 (January 2019)
compiled on Jan 18 2019 17:57:48 with OCaml 4.07.1

**Comment by Columbus240** [comment]
It builds on v8.10.2 without triggering an anomaly at the indicated line. It fails to build on v8.13.2.

**Comment by ppedrot** [comment]
If there is no way to reproduce on a modern Coq, let's close. Please reopen an issue if you manage to port the example to a recent version.
