### ISSUE TITLE
Documentation of exact_no_check, vm_cast_no_check

### ISSUE THREAD

**Issue by ckeller** [coq/coq#9951]
#### Description of the problem

Is it  on purpose that tactics such as exact_no_check, vm_cast_no_check, are not documented?

Other unsafe tactics, such as fix, are documented.

#### Coq Version

8.9

**Comment by Zimmi48** [comment]
The current view is that nothing should be left undocumented.

**Comment by cpitclaudel** [comment]
These tactics are documented now: https://coq.inria.fr/refman/proof-engine/tactics.html#performance-oriented-tactic-variants
