### ISSUE TITLE
Bug in the "sorted" problem in Yves Bertot video 3011 created on 6/26/2017

### ISSUE THREAD

**Issue by thuy48** [coq/coq#9958]
Bug in the "sorted" problem in Yves Bertot video 3011 created on 6/26/2017
The example was executed under Windows 10 on both versions 64 bit and the alternate.
The line where the error occurs is the last one in the following script :

Inductive sorted: list nat -> Prop :=
snil: sorted nil
| ssingle: forall x, sorted(x::nil)
| scons: forall x y l, x <= y -> sorted(y :: l) -> sorted(x::y::l).

Fixpoint insert x l :=
  match l with nil => x::nil | y::l' => if leb x y then x::l else
    insert x l' end.

Lemma insert_sorted: forall x l, sorted l -> sorted(insert x l).

Proof.

intros x l H; induction H.
simpl.
apply ssingle.
  simpl.
  case_eq(leb x x0).
  intros xlx0.
  apply scons.
  apply leb_complete. assumption.

apply ssingle.
  intros x0lx.
  apply leb_complete_conv in x0lx.

  apply scons.{* execution of this line fails in CoqIDE 8.9.0 *)

*****************************************************************************
In environment
x, x0 : nat
x0lx : x0 < x
Unable to unify "sorted (?M1073 :: ?M1074 :: ?M1075)"
with "sorted (x :: nil)".

*****************************************************************************

8.9.0 Coq Version

**Comment by ppedrot** [comment]
Do you have a precise link to the material?

**Comment by thuy48** [comment]
http://www-sop.inria.fr/members/Yves.Bertot/videos-coq/
If you click on #3 on that page at the line:
Le cours est décomposé en 7 parties. Des liens vers des archives compressées pour chaque partie sont disponibles : partie 1, 2, 3, 4, 5, 6, 7. 

Then extract all the files of the 3rd part, then the video to view is the number 3011.

I duplicate in the enclosed script file .
[Bug.txt](https://github.com/coq/coq/files/3077487/Bug.txt)

**Comment by thuy48** [comment]
Link to the video:

https://files.inria.fr/videos/coq-bertot/3011.mp4


________________________________

**Comment by JasonGross** [comment]
This is not a bug in Coq; you transcribed `insert` wrong.  The `else` branch is missing a `y::`

**Comment by thuy48** [comment]
many thanks, my apologies :)


On April 14, 2019, at 12:14 PM, Jason Gross <notifications@github.com> wrote:


This is not a bug in Coq; you transcribed insert wrong. The else branch is missing a y::
