### ISSUE TITLE
coqide doesn't open 

### ISSUE THREAD

**Issue by yunoJ** [coq/coq#9969]
OS: ubuntu 18.04
coq: 8.9.0
coqide: 8.9.0
installed with: opam

I'm trying to open coqide via terminal. It worked the first time after downloading the program but 
![Screenshot from 2019-04-18 14-34-53](https://user-images.githubusercontent.com/43490944/56338941-25248200-61e7-11e9-8e0e-620c5c9bddcd.png) error pops up.

I entered "opam show coqide" to check if it not installed and as you can see below, my coqide version is up-to-date. (I think)
![Screenshot from 2019-04-18 14-35-58](https://user-images.githubusercontent.com/43490944/56338982-4f763f80-61e7-11e9-85b8-da309b291daf.png)

https://coq.inria.fr/opam-using.html says that I have to type in 
> export OPAMROOT=~/opam-coq.8.9.0
> eval `opam config `env`
eveyrtime I open a new shell and I followed the steps.

Please help...

**Comment by SkySkimmer** [comment]
>`export OPAMROOT=~/opam-coq.8.9.0`

Why do we have this with "Instructions target an OPAM newcomer"?

@yunoJ what do you have in (if they exist)
- ~/.opam
- ~/.opam/4.02.3/bin
- ~/opam-coq.8.9.0
- ~/opam-coq.8.9.0/bin
?

Did you run that `opam show` after the export/eval opam config?
What does `opam list` say?
What does `echo $PATH` say?

**Comment by yunoJ** [comment]
~/.opam: download-cache, log, ocaml-base-compiler.4.02.3, opam-init, repo, config, config.lock, lock
~/.opam/4.02.3/bin: I don't have this one
~/opam-coq.8.9.0: download-cache, log, ocaml-base-compiler.4.02.3, opam-init, repo, config, config.lock, lock
~/opam-coq.8.9.0/bin: this one doesn't exist either

I ran `opam show` after the export/eval opam config,

`opam list` says 
![Screenshot from 2019-04-18 15-46-28](https://user-images.githubusercontent.com/43490944/56341835-45593e80-61f1-11e9-8782-9653ebe76dc6.png)

`echo $PATH` says
![Screenshot from 2019-04-18 15-46-54](https://user-images.githubusercontent.com/43490944/56341846-4be7b600-61f1-11e9-8fcc-116d7a0769d4.png)

**Comment by SkySkimmer** [comment]
How about `~/.opam/ocaml-base-compiler.4.02.3/bin` and `~/opam-coq.8.9.0/ocaml-base-compiler.4.02.3/bin` ?

Your PATH is looking wrong, the `` eval `opam config env` `` should have put `~/opam-coq.8.9.0/ocaml-base-compiler.4.02.3/bin` in there.
What does `opam config env` (without the `eval`) say?

**Comment by yunoJ** [comment]
there are a lot in both of the directories...I think they have same files though. Should I list all of them? Can you specify the required files?

![Screenshot from 2019-04-18 16-00-02](https://user-images.githubusercontent.com/43490944/56342467-10e68200-61f3-11e9-9792-6c05409907b9.png)
I guess `~/opam-coq.8.9.0/ocaml-base-compiler.4.02.3/bin` is included

**Comment by SkySkimmer** [comment]
>there are a lot in both of the directories...I think they have same files though. Should I list all of them? Can you specify the required files?

Is `coqide` there?

Did you run opam config before the `echo $PATH`?

**Comment by yunoJ** [comment]
coqide is in both of the directories you mentioned above.

I think I ran echo $PATH before `opam config`. But the results are the same whether I ran `opam config` before or not.

**Comment by SkySkimmer** [comment]
What happens when you run `~/opam-coq.8.9.0/ocaml-base-compiler.4.02.3/bin/coqide`? how about `eval $(opam config env); coqide` as a one liner?

>But the results are the same whether I ran opam config before or not.

That's very strange.
Do you have anything liable to reset your PATH in your ~/.bashrc or ~/.profile or similar?

**Comment by SkySkimmer** [comment]
> But the results are the same whether I ran opam config before or not.

you mean after `eval $(opam config env)` not just `opam config env` right?

**Comment by yunoJ** [comment]
Sorry for the late reply.

Both of the suggestions you made works (opening with `~opam/...../bin/coqide` and `eval $(....)`.

I don't think I have anything to reset my PATH in my ~/.bashrc or ~/.profile.

And no I mean `opam config env`

**Comment by SkySkimmer** [comment]
>And no I mean opam config env

You have to eval it, by itself it just prints stuff.

**Comment by yunoJ** [comment]
I think what you are saying is `echo $PATH` and `echo $PATH` after `eval $(opam config env)` should have different results right? Well they print the same path...

**Comment by yunoJ** [comment]
I tried again with `opam init` before any other commands. I did type it first when I downloaded coq and coqide and thought it wouldn't be necessary to type it again everytime I opened a new shell. It works now. Thanks for the support :)
