### ISSUE TITLE
coq_makefile's generated Makefiles emit systematically a warning

### ISSUE THREAD

**Issue by gares** [coq/coq#9974]
Since d9fb8db86d5b4ddc79a207c5f0ac32eb98215e78 `coqc -opt` is deprecated but https://github.com/coq/coq/blob/master/tools/CoqMakefile.in#L737 uses that option, hence the warning (the same holds for `-byte`).

I suspect it is enough to remove `$(OPT)` from https://github.com/coq/coq/blob/master/tools/CoqMakefile.in#L179 to avoid the warning, but then one should also patch the value of `COQC` https://github.com/coq/coq/blob/master/tools/CoqMakefile.in#L81 in the conditional 
https://github.com/coq/coq/blob/master/tools/CoqMakefile.in#L163 I guess since the semantics of `-byte` is to use the bytecode version of coqc

**Comment by gares** [comment]
I don't think 8.9 can be released with that warning.

**Comment by ejgallego** [comment]
Actually is there a use case for calling `coqc.byte`?

We don't even build it in Dune.

**Comment by gares** [comment]
Use case for building coqc.byte: Ocamldebug. Given that coqtop does not accept -compile, how do you debug coqc if you don't build it in bytecode?

About coq makefile: I don't see any use case other than the absence of native coqc. I don't recall, maybe if there is no native backend we name the bytecode binary without .byte.

**Comment by ejgallego** [comment]
I was under the impression that people would call `coqc.byte` manually in that case instead of going thru coq_makefile, but if that's useful why not?

Note that both the makefiles and Dune will install `coqc.byte` as `coqc` if a native version is not available, thus `coqc` can be used by default as a synonym of "best".

**Comment by gares** [comment]
I expect one calls coqc.byte by hand, but you wrote that you don't even build it, so I gave you a use case for building it.

Wrt CoqMakefile.in, since `coqc` means "best" the only fix needed is to not pass `$(OPT)` to coqc.

**Comment by ejgallego** [comment]
I meant from coq makefile, sorry I was not clear. Yeah we should build it definitevely.

There are some subtlelies when plugins are involved tho, coqc.byte will need the CMA version.

**Comment by maximedenes** [comment]
@gares are you going to work on fixing this? Can I mark you as the assignee?

**Comment by gares** [comment]
Not this week I'm afraid.

**Comment by maximedenes** [comment]
I'm afraid we are going to have to consider it is not a blocker for the beta.

**Comment by Zimmi48** [comment]
> I'm afraid we are going to have to consider it is not a blocker for the beta.

Another interpretation of this sentence would have been to keep the blocker label but delay the issue to the 8.9.0 milestone. Not my call though.

**Comment by ejgallego** [comment]
Fix is pretty trivial tho so not a big deal anyways.
