### ISSUE TITLE
Enable a MinGW Windows bytecode debug build

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#9975]
Since CoqIDE crashes in 8.10 on Windows, I need to debug this. Creating bytecode binaries of the main coq tools works with some patches to the makefiles, but building a bytcode version of CoqIDE is tricky cause of the dependencies to C libraries like GTK3 and Cairo2.

There has been some discussion on the topic in #8729.

Since we can hardly release 8.10 with a broken CoqIDE on Windows, I set this to high prio.

**Comment by ejgallego** [comment]
You can also use the dune build which by the way will get you way further as it will properly compose in case you need to trace across libraries .

Also, gdb + native tends to work very well (in Linux tho)

**Comment by MSoegtropIMC** [comment]
Some more notes on this:

The DLL `dllcairo_stubs.dll` which is not found during `OCAMLC -o bin/coqide.byte.exe` is installed in the correct path:
```
$ ocamlfind printconf
Effective configuration:
: 
The ld.conf file can be found here:
    C:\bin\cygwin_coq64_ms_coqide\usr\x86_64-w64-mingw32\sys-root\mingw\libocaml\ld.conf
```
The ld.conf file mentioned above contains:
```
C:/bin/cygwin_coq64_ms_coqide/usr/x86_64-w64-mingw32/sys-root/mingw/libocaml/stublibs
C:/bin/cygwin_coq64_ms_coqide/usr/x86_64-w64-mingw32/sys-root/mingw/libocaml
```
The DLL is in the above stublib path. Please note that all OCaml tools in the windows build are MinGW tools and can handle both / and \ in paths.

As @ejgallego suggested setting:
```
CAML_LD_LIBRARY_PATH="C:\bin\cygwin_coq64_ms_coqide\usr\x86_64-w64-mingw32\sys-root\mingw\libocaml\site-lib\stublibs"
```
fixes this although I tend to agree with @gares that it should work without this setting when the files are in the default folder. With the above setting I now get:
```
Error while linking ide/coqide_os_specific.cmo:
The external function `win32_interrupt' is not available
```
I am looking into this ...

**Comment by MSoegtropIMC** [comment]
@ejgallego : so you are suggesting to base the debug build functionality on #8729? I thought about this since the old makefiles anyway will go away soon and it doesn't make that much sense to add new features to them. I might bother you quite a bit with questions though if I do this.

**Comment by ejgallego** [comment]
Indeed I we already have a setup that works for your debug case I'd may be more efficient just to use it.

No idea if it'll work tho, but no harm in trying I guess.

**Comment by ejgallego** [comment]
Note that the setup you need is already on master, no need of any extra PR or patch.

**Comment by ejgallego** [comment]
How to call ocamldebug from dune is detailed in the documentation in dev/doc/build-system.dune.md

**Comment by MSoegtropIMC** [comment]
Ok, I am reading `build-system.dune.md` on master and see where it leads me ...

**Comment by MSoegtropIMC** [comment]
One thing I still don't get: how do I tell dune if I want a native or bytecode build? Does it to both if there are no (modes ...) lines in the dune files? Or is this the --profile release vs --profile dev option?

**Comment by MSoegtropIMC** [comment]
@ejgallego : I have issues with path separators:
```
dune build
:
Error while running 'C:\bin\cygwin_coq64_ms_coqide\usr\x86_64-w64-mingw32\sys-root\mingw\bin/ocamlfind.exe ocamlc -version' (exit code 3)
```
Where does dune get the path with backward slashes from? I took some care to make sure that all paths built into the mingw OCaml tools use forward slashes, so that they need not be quoted:
```
$ ocamlc -where
C:/bin/cygwin_coq64_ms_coqide/usr/x86_64-w64-mingw32/sys-root/mingw/libocaml
```
Quoting the command dune tries to execute works:
```
$ 'C:\bin\cygwin_coq64_ms_coqide\usr\x86_64-w64-mingw32\sys-root\mingw\bin/ocamlfind.exe' ocamlc -version
4.07.1
```

**Comment by MSoegtropIMC** [comment]
Then there is a (I guess not so critical) issue:
```
"doc/plugin_tutorial/tuto3/src/dune", line 5, characters 12-28:
  (libraries coq.plugins.ltac))
                ^^^^^^^^^^^^^^^^
Library "coq.plugins.ltac" not found.
Hint: try: dune external-lib-deps --missing @@default
```
the hint gives:
```
dune external-lib-deps --missing @@default
The following libraries are missing in the default context:
- coq.plugins.ltac
Hint: try: opam install coq
```
Looks a bit like a hen and egg problem ...

**Comment by ejgallego** [comment]
As mentioned in the readme the debug stuff needs you to run the build, we could fix that now. So you need to run the voboot target at least once.

Dune by default will build only what's requested. The default target is the install files, and these indeed depend on both the byte and native versions of the library. Quick builds are done by check

**Comment by MSoegtropIMC** [comment]
@ejgallego : thanks for the explanation. I think the debug vs. release question could be explained a bit better in the dune documentation.

Regarding the configure path issue: this works:
```
    ocaml.exe configure.ml -no-ask -native-compiler no
    make -f Makefile.dune voboot -j 6
    dune build -j 6
```
The processes create by configure.ml seem to inherit the path from ocaml.exe. If I call ocaml.exe without path or with a path using / it works. If I call ocaml with a (quoted) path containing \ it doesn't work. Dune seems to use \ in the ocaml.exe path and then doesn't get the quoting right. But I can work around it by calling configure upfront as above. I used the same parameters as when called by dune.

**Comment by MSoegtropIMC** [comment]
@ejgallego : there is one more issue with dune on cygwin/MinGW: `dune exec dev/dune-dbg` tries to execute a shell script with CreateProcess. This does not work on Windows - you get an 'Exec format error'.

This leads me to two questions:

1.) wouldn't it be easier to plug in my "Pico posix shell" into dune. It does support evaluation of she-bangs (of cause one still needs a shell then, but for simple stuff one could restrict oneself to pico shell as well). I guess it would also solve the issue with calling ocamlc I outlined before.

2.) Would it make more sense to compile dune for cygwin rather than for MinGW since it is part of the build tools. E.g. the make and remake used are also a cygwin executables, not MinGW. This would solve such problems but might also open other problems - e.g. one would need an OCaml for cygwin then (can be installed as cygwin package) and I hear that the cygwin OCaml is broken in some ways, but I guess it might work for dune. A cygwin executable can handle cygwin paths and windows paths as long as they use / instead of \. MinGW (and Windows in general) can also handle paths with /, so I generally use Windows paths with / as smallest common denominator between MinGW and cygwin.

**Comment by ejgallego** [comment]
> wouldn't it be easier to plug in my "Pico posix shell" into dune

I personally have no interest on dealing with shell; in this case the shell script is just a workaround for the lack of OCamldebug support in Dune, but I may add it right away. Anyways the workaround is pretty easy `dune build dev/dune-dbg && dune exec -- bash _build/default/dev/dune_dbg` ; you can add an alias to automate that.

> Would it make more sense to compile dune for cygwin rather than for MinGW

What would we gain for that? Personally I'd rather support MinGW, Dune has not problems handling MinGW paths; is likely Coq that does.

**Comment by MSoegtropIMC** [comment]
@ejgallego : I am making (slow) progress. I have one question regarding the cairo DLL. I didn't look properly and the path is indeed not in ld.conf. The cairo DLLs are in

    C:/bin/cygwin_coq64_ms_coqide2/usr/x86_64-w64-mingw32/sys-root/mingw/libocaml/site-lib/stublibs

while the path in ld.conf is

    C:/bin/cygwin_coq64_ms_coqide2/usr/x86_64-w64-mingw32/sys-root/mingw/libocaml/stublibs

I wonder what is the best way to fix this. Of cause I can add the site-lib/stublibs folder to ld.conf in my scripts, but the OCaml docs suggest that one should put stuff in the system stublib folder. See <https://caml.inria.fr/pub/docs/manual-ocaml/runtime.html#s-ocamlrun-dllpath> chapter 11.3, number 4. So should one change the cairo dune or opam files (not sure where this is in) to put it into the system stublib folder or do you think I should add the site-lib stublib folder to ld.conf?

**Comment by ejgallego** [comment]
> The cairo DLLs are in

That's a bit strange, as the ocaml-cairo install file says:
```
stublibs: [
  "_build/install/default/lib/stublibs/dllcairo_stubs.so"
]
```
how did the files ended in `site-lib` ?

**Comment by ejgallego** [comment]
> So should one change the cairo dune or opam files (not sure where this is in) to put it into the system stublib folder or do you think I should add the site-lib stublib folder to ld.conf?

The `ocaml-cairo` dune and opam files don't say anything on where the stublibs should be installed; that's the responsibility of the tool calling the build process [opam or whatever script you used to build Cairo]

If that's opam, then opam seems to be configure incorrectly in the system. What does `opam var` say?

**Comment by ejgallego** [comment]
So for example if you are using opam and ocamlfind, they have to match in their configs, otherwise you need to manually tweak them; if you install findlib using opam that's already the case.

**Comment by MSoegtropIMC** [comment]
The way the cairo2 ocaml wrapper is built and installed is:
```
  if build_prep https://github.com/Chris00/ocaml-cairo/archive 0.6 tar.gz 1 ocaml_cairo2-0.6; then
    make_arch_pkg_config

    log2 dune build cairo2.install
    log2 dune install cairo2
    log2 dune clean
    build_post

  fi
```
The lablgtk DLLs also end up in this folder. These are built with
```
  if build_prep https://github.com/garrigue/lablgtk/archive  3.0.beta5  tar.gz 1 lablgtk-3.0.beta5 ; then
    make_arch_pkg_config

    # lablgtk3 includes more packages that are not relevant for Coq,
    # such as gtkspell
    log2 dune build -p lablgtk3
    log2 dune install lablgtk3

    log2 dune build -p lablgtk3-sourceview3
    log2 dune install lablgtk3-sourceview3

    log2 dune clean
    build_post
  fi
```
All other Dlls are installed in the system stublib folder, but this are just the OCaml standard library DLLs (unix, ...).

**Comment by MSoegtropIMC** [comment]
So I am almost there. I can build native and bytecode CoqIDE and they bring up the UI. The only issue is that I get immeadiately a "coqtop died badly" message. I am not sure why. Is there a way to see error messages from coqtop when started by coqide? On the console I see only messages from coqide.
The last system commands before coqtop dies are:
```
18:51:09,2699028	coqidetop.opt	6916	Load Image	C:\bin\coq64_ms_coqide2\lib\coq\plugins\numeral_notation\numeral_notation_plugin.cmxs	SUCCESS	Image Base: 0x642c0000, Image Size: 0x63000
18:51:09,2700422	coqidetop.opt	6916	CloseFile	C:\bin\coq64_ms_coqide2\lib\coq\plugins\numeral_notation\numeral_notation_plugin.cmxs	SUCCESS	
18:51:09,2794821	coqidetop.opt	6916	CreateFile	C:\bin\cygwin_coq64_ms_coqide2\home\soegtrop\.config\coq\coqrc.8.10+alpha	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
18:51:09,2795850	coqidetop.opt	6916	CreateFile	C:\bin\cygwin_coq64_ms_coqide2\home\soegtrop\.config\coq\coqrc	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
18:51:09,2798014	coqidetop.opt	6916	CreateFile	C:\bin\cygwin_coq64_ms_coqide2\home\soegtrop\.coqrc.8.10+alpha	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
18:51:09,2800083	coqidetop.opt	6916	CreateFile	C:\bin\cygwin_coq64_ms_coqide2\home\soegtrop\.coqrc	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
18:51:09,2801686	ocamlrun.exe	7720	TCP Receive	DESKTOP-A1A5UC0:55390 -> DESKTOP-A1A5UC0:55392	SUCCESS	Length: 45, seqnum: 0, connid: 0
18:51:09,2801959	coqidetop.opt	6916	TCP Send	DESKTOP-A1A5UC0:55392 -> DESKTOP-A1A5UC0:55390	SUCCESS	Length: 45, startime: 7871926, endtime: 7871926, seqnum: 0, connid: 0
18:51:11,6363700	coqidetop.opt	6916	TCP Receive	DESKTOP-A1A5UC0:55395 -> DESKTOP-A1A5UC0:55389	SUCCESS	Length: 20, seqnum: 0, connid: 0
18:51:11,6363916	coqidetop.opt	6916	TCP Receive	DESKTOP-A1A5UC0:55395 -> DESKTOP-A1A5UC0:55389	SUCCESS	Length: 1, seqnum: 0, connid: 0
18:51:11,6364104	ocamlrun.exe	7720	TCP Send	DESKTOP-A1A5UC0:55389 -> DESKTOP-A1A5UC0:55395	SUCCESS	Length: 21, startime: 7872161, endtime: 7872161, seqnum: 0, connid: 0
18:51:11,6364585	ocamlrun.exe	7720	TCP Disconnect	DESKTOP-A1A5UC0:55390 -> DESKTOP-A1A5UC0:55392	SUCCESS	Length: 0, seqnum: 0, connid: 0
18:51:11,6364949	coqidetop.opt	6916	TCP Receive	DESKTOP-A1A5UC0:55393 -> DESKTOP-A1A5UC0:55391	SUCCESS	Length: 0, seqnum: 0, connid: 0
18:51:11,6365756	coqidetop.opt	6916	TCP Disconnect	DESKTOP-A1A5UC0:55392 -> DESKTOP-A1A5UC0:55390	SUCCESS	Length: 0, seqnum: 0, connid: 0
18:51:11,6366333	ocamlrun.exe	7720	TCP Disconnect	DESKTOP-A1A5UC0:55389 -> DESKTOP-A1A5UC0:55395	SUCCESS	Length: 0, seqnum: 0, connid: 0
18:51:11,6366980	coqidetop.opt	6916	TCP Disconnect	DESKTOP-A1A5UC0:55395 -> DESKTOP-A1A5UC0:55389	SUCCESS	Length: 0, seqnum: 0, connid: 0
18:51:11,6367338	ocamlrun.exe	7720	TCP Disconnect	DESKTOP-A1A5UC0:55391 -> DESKTOP-A1A5UC0:55393	SUCCESS	Length: 0, seqnum: 0, connid: 0
18:51:11,6367670	ocamlrun.exe	7720	CreateFile	C:\bin\coq64_ms_coqide2\bin	SUCCESS	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
18:51:11,6367774	coqidetop.opt	6916	TCP Disconnect	DESKTOP-A1A5UC0:55393 -> DESKTOP-A1A5UC0:55391	SUCCESS	Length: 0, seqnum: 0, connid: 0
18:51:11,6368089	ocamlrun.exe	7720	QueryDirectory	C:\bin\coq64_ms_coqide2\bin\coqidetop.byte.exe	NO SUCH FILE	Filter: coqidetop.byte.exe
18:51:11,6368115	ocamlrun.exe	7720	TCP Disconnect	DESKTOP-A1A5UC0:55388 -> DESKTOP-A1A5UC0:55394	SUCCESS	Length: 0, seqnum: 0, connid: 0
18:51:11,6368299	ocamlrun.exe	7720	CloseFile	C:\bin\coq64_ms_coqide2\bin	SUCCESS	
18:51:11,6368518	coqidetop.opt	6916	TCP Disconnect	DESKTOP-A1A5UC0:55394 -> DESKTOP-A1A5UC0:55388	SUCCESS	Length: 0, seqnum: 0, connid: 0
18:51:11,6370056	coqidetop.opt	6916	RegCloseKey	HKLM\System\CurrentControlSet\Services\WinSock2\Parameters\Protocol_Catalog9	SUCCESS	
18:51:11,6370346	ocamlrun.exe	7720	CreateFile	C:\bin\coq64_ms_coqide2\Resources\bin\	PATH NOT FOUND	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
18:51:11,6375409	coqidetop.opt	6916	RegCloseKey	HKLM\System\CurrentControlSet\Services\WinSock2\Parameters\NameSpace_Catalog5	SUCCESS	
18:51:11,6376261	ocamlrun.exe	7720	CreateFile	C:\bin\coq64_ms_coqide2\bin\coqidetop.opt	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
18:51:11,6376560	ocamlrun.exe	7720	QueryBasicInformationFile	C:\bin\coq64_ms_coqide2\bin\coqidetop.opt	SUCCESS	CreationTime: 21/04/2019 18:22:12, LastAccessTime: 21/04/2019 18:22:12, LastWriteTime: 21/04/2019 16:55:30, ChangeTime: 21/04/2019 18:22:20, FileAttributes: A
18:51:11,6376698	ocamlrun.exe	7720	CloseFile	C:\bin\coq64_ms_coqide2\bin\coqidetop.opt	SUCCESS	
18:51:11,6378419	ocamlrun.exe	7720	RegOpenKey	HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\coqidetop.opt	NAME NOT FOUND	Desired Access: Query Value, Enumerate Sub Keys
18:51:11,6378611	ocamlrun.exe	7720	RegOpenKey	HKLM\Software\Microsoft\Wow64\x86\xtajit	NAME NOT FOUND	Desired Access: Query Value
18:51:11,6380004	ocamlrun.exe	7720	CreateFile	C:\bin\coq64_ms_coqide2\bin\coqidetop.opt	SUCCESS	Desired Access: Read Data/List Directory, Execute/Traverse, Read Attributes, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Delete, AllocationSize: n/a, OpenResult: Opened
18:51:11,6380538	ocamlrun.exe	7720	CreateFileMapping	C:\bin\coq64_ms_coqide2\bin\coqidetop.opt	FILE LOCKED WITH ONLY READERS	SyncType: SyncTypeCreateSection, PageProtection: PAGE_EXECUTE|PAGE_NOCACHE
18:51:11,6380735	coqidetop.opt	6916	Thread Exit		SUCCESS	Thread ID: 6348, User Time: 0.0000000, Kernel Time: 0.0000000
```
So coqtop loads the last plugin image, then tries to access a .coqrc file which it doesn't find, then it sends 45 bytes to coqide (ocamlrun) and then I think it disconnects. Please note that the entries are sorted by time and for whatever reason they can be silghtly changed in order, so although ocamlrun disconnects first it could be coqidetop which disconnects.

I think @gares is the expert for the coqide - coqtop protocol?

**Comment by MSoegtropIMC** [comment]
P.S.: the payload of the TCP/IP communication between coqide and coqidetop is:
```
<call val="Init"><option val="none"/></call>

<value val="good"><state_id val="1"/></value>
```
The 21 bytes on the 3rd channel are binary.

**Comment by ejgallego** [comment]
>   log2 dune install cairo2

For some reason `dune install` is then using the wrong folder to install, I don't recall the exact rules, but this is indeed then a bug in configure step when building Dune or a bug in some environment. Dune should be built such that it installs packages properly.

Likely, as you have you own package system you want indeed to pass the right parameters to `dune install`.

> The 21 bytes on the 3rd channel are binary.

be sure you have build the whole of Coq `make -f Makefile.dune world` before invoking this.

**Comment by gares** [comment]
You should be able to get more output by passing coqide `-debug`.

**Comment by MSoegtropIMC** [comment]
@gares : With -debug I get this (besides a few GTK messages about missing icons)
```
(Spawn  ,660) EXEC: coqidetop.opt -main-channel 127.0.0.1:55602:55603 -control-channel 127.0.0.1:55600:55601 --xml_format=Ppcmds -async-proofs off -coqlib C:/bin/coq64_ms_coqide2/lib/coq -debug
(Spawned,172) starting controller thread
Welcome to Coq 8.10+alpha (April 2019)
[DEBUG] Start eval_call Init None
[pid 172] <-- Init None
[DEBUG] End eval[pid 172] --> GOOD 1
_call
[DEBUG] End of Coqide.main
[DEBUG] Signal ignored (normal if Win32)
[DEBUG] Coqtop reader failed, resetting: Coq.TubeError("ERR")
(Spawn  ,660) death sentence for 1068
(Spawned,172) death sentence received
```
Hopefully this gives you a hint.

Another question: how can I start coqide and coqtopide independently, so that I can debug them with ocamldebug?

@ejgallego : make -f Makefile.dune world didn't produce any extra files - it seems to be equivalent to what I already had.

**Comment by MSoegtropIMC** [comment]
@gares : I need a way to start coqidetop in the debugger so that coqide can talk to it. The only other way to debug this is adding a lot of prints (unless there are higher levels of debug output than -debug). I guess you have a way of doing this. Can you please share the command lines I have to give to coqidetop and coqide when I want to start them separately? Or should I use fake-ide for such kind of debugging of coqidetop?

**Comment by MSoegtropIMC** [comment]
@ppedrot : maybe you also have the answer for the question I asked above on starting coqide and coqidetop separately in a debugger.

**Comment by gares** [comment]
I don't recall if there is support for that. I did add some support in the stm for its workers but even if coqide uses the same spawn/spawned modules, the support might not the be ready. The trick was to add a command line option to set an env variable for the spawned process. IIRC you can export a variable and the ocaml runtime waits untill ocamldebug connects to the socket/ pipe given in the variable, see ocamldebug doc. I m travelling, sort for brevity.

**Comment by ejgallego** [comment]
TTBOMK this should work much better now, tho I am not sure about all the details involved here as there seem to be multiple issues. Marking for review.

**Comment by SkySkimmer** [comment]
Closing as resolved until someone contradicts.
