### ISSUE TITLE
coqdep gives incorrect warning

### ISSUE THREAD

**Issue by andreaslyn** [coq/coq#9993]
#### Description of the problem
While working on https://github.com/HoTT/HoTT/pull/1027 i ran into the following problem. By running the commands:
```
mkdir -p Dir/Sub1
mkdir -p Dir/Sub2

echo "Definition F := 1." > Dir/Sub1/File.v
echo "Definition F := 2." > Dir/Sub2/File.v
echo "From Dir.Sub1 Require Import File. Print F." > Dir/Test.v

coqc -R Dir Dir Dir/Sub1/File.v
coqc -R Dir Dir Dir/Sub2/File.v
coqdep -R Dir Dir Dir/Test.v
```
I get the output:
```
Dir/Test.vo Dir/Test.glob Dir/Test.v.beautified: Dir/Test.v Dir/Sub1/File.vo
Dir/Test.vio: Dir/Test.v Dir/Sub1/File.vio
*** Warning: in file Dir/Test.v, 
    required library File matches several files in path
    (found File.v in Dir/Sub1 and Dir/Sub2; used the latter)
*** Warning: in file Dir/Test.v, 
    required library File matches several files in path
    (found File.v in Dir/Sub1 and Dir/Sub2; used the latter)
```
We can see from the output that it uses the former `Dir/Sub1/File.v`, but it gives an incorrect warning about using the latter `Dir/Sub2/File.v`. It would also be wrong to use the latter because we are explicitly asking it to look for `File` in `Dir.Sub1`.

#### Coq Version
Coq version 8.9.0

**Comment by maximedenes** [comment]
This is the same as https://github.com/coq/coq/issues/11631. I'm closing this one since the other issue has received some comments. Thanks for reporting!
